### ISSUE TITLE
Loss of static typing on react-navigation/expo-router `Stack`

### ISSUE THREAD

**Issue by AJTJ** [expo/expo#23404] opened 2023-07-09 04:52 UTC
### Minimal reproducible example

The `Stack` here is not able to be statically typed: https://github.com/AJTJ/free-app/blob/main/app/_layout.tsx#L144

### Summary

this new Stack
```ts
import { Stack } from "expo-router/stack";
```
Doesn't allow you to create types and params like the react-navigation "Stack" did.

like so (this is the react-navigation Stack):

```ts
export type RootStackParamList = {
  Landing: undefined;
  ...
  ...
  FormReordering: {
    form: FormRequestV1;
    formName: string;
  };
};

export type AllNavigationProps = NativeStackNavigationProp<RootStackParamList>;

const Stack = createNativeStackNavigator<RootStackParamList>();
```
In fact, I'm not even sure how to pass statically typed props to components with the new Link and/or router.push

It seems like you can do something like this:
```ts
  const handleFormPress = (form: FormFragment) => {
    router.push({ pathname: "ReportBuilder", params: { form } });
  };
 ```
But it isn't statically typed. The only thing that seems typed is the new Link component through the typed routes, which feels brittle being dependent on a CLI. Why not just have static typing like before to be used by the react-navigation useNavigate hook?

Why is the capacity to statically type all the routes buried? Internally the Expo Router Stack is still using `createNativeStackNavigator`, but the capacity to add our own static types through generics has been buried. It would be nice if we could still do that.  **This feels like a regression**

Within Expo Router, `router` or `router.push` don't seem to have a static typing configuration. Whereas before you might just do something like this:

```ts
export type Props = NativeStackScreenProps<RootStackParamList, "ReportBuilder">;
export function ReportBuilder(props: Props) {
  let navigation = useNavigation<AllNavigationProps>();

  navigation.navigate("Home");
}
```
And it was all cleanly typesafe.

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 13.0.1
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
Yarn: 1.22.17 - /usr/local/bin/yarn
npm: 7.24.2 - ~/.nvm/versions/node/v16.17.1/bin/npm
Watchman: 2023.07.03.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.12.1 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
IDEs:
Android Studio: 2022.2 AI-222.4459.24.2221.10121639
Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
npmPackages:
expo: ^49.0.0 => 49.0.0
react: 18.2.0 => 18.2.0
react-dom: 18.2.0 => 18.2.0
react-native: 0.72.1 => 0.72.1
react-native-web: ~0.19.6 => 0.19.6
npmGlobalPackages:
eas-cli: 3.15.0
Expo Workflow: bare

^ This is not true. I am still in managed workflow... is this also a bug?

**Comment by marklawlor** [comment] 2023-07-11 02:13
React Navigation is "screen" based, while Expo Router is "URL based". This means your `pathname` prop should be an actual pathname (e.g. `/report-builder`) not the name of the screen.

**Comment by AJTJ** [comment] 2023-07-11 17:48
> React Navigation is "screen" based, while Expo Router is "URL" based. This means your `pathname` prop should be an actual pathname (e.g. `/report-builder`) not the name of the screen.

Thanks for your response. I think that distinction is clear, and I'm not sure if it is related to what I'm trying to achieve. What I'm attempting to achieve is the same level of static typing that was achievable with react-navigation. Previously done by passing a generic to the `createNativeStackNavigator` function like so:
```ts
const Stack = createNativeStackNavigator<RootStackParamList>();
```
And with that `RootStackParamList` you can define all the params that each "URL" is expecting.

**Comment by AJTJ** [comment] 2023-07-11 20:34
@marklawlor I suppose, more specifically, does this mean that I should be storing complex objects in state, rather than passing them as properties (like you could with react-navigation) since all local or global search params now need to be serializable in a url?

**Comment by marklawlor** [comment] 2023-07-11 23:49
You should use the `<Stack />` component from `expo-router` instead of creating your own. https://docs.expo.dev/routing/layouts/ 

```tsx
import { Stack } from 'expo-router';

export default function Layout() {
  return <Stack />;
}
```

You can use the `[typedRoutes](https://docs.expo.dev/router/reference/typed-routes/)` to generate the types for the routes.

The goals of Expo Router are different to React Navigation, so some concepts will not translate 1-1. Expo Router is built to support the Web and future architectures such as React Server Components, both of which cannot support complex objects as route parameters.

**Comment by marklawlor** [comment] 2023-09-28 23:59
Revisiting this issue, I don't think my answers were that clear. Part of the problem is a philosophical difference between React Navigation & Expo Router. RN allows you set route param as complex objects, while ER define routes as URLs, which are rather somewhat more restrictive.

This was a purposeful choice to ensure that Expo Router works across all platforms (e.g Web) and scenarios (e.g App Clips for native) where complex objects cannot be as easily serialised. So while we do offer typing, it isn't going to be to the same level of complexity as RN, as we simply don't expose that aspect.

I'm going to close this issue but I'll still response to responses if you have any more questions

**Closed by marklawlor** 2023-09-28 23:59 UTC
Labels: needs review
