### ISSUE TITLE
Cherry-pick JSC update (from React native 0.59.10)

### ISSUE THREAD

**Issue by mojtabast** [expo/expo#5205] opened 2019-08-06 23:05 UTC
Hi,
My app is crashing on some android devices, it seems this is [a verified issue ](https://github.com/facebook/react-native/issues/24261#issuecomment-514332549) and [has been fixed](https://github.com/facebook/react-native/pull/25449) in 0.59.10

[Expo](https://docs.expo.io/versions/latest/sdk/overview/) is using 0.59.8 for SDK 33 & SDK 34. is there any plan to upgrade to 0.59.10? Or is it possible to do that without ejecting?

**Comment by cruzach** [comment] 2019-08-07 15:48
Hi! Thanks for sharing this with us

We regularly upgrade the `react-native` version, but probably won't in the next SDK release (35). Although, we can probably cherry-pick this fix for that SDK release

**Comment by mojtabast** [comment] 2019-08-07 19:03
Thanks @cruzach, that would be great.

Although I don't know about the release time for SDK 35 and also compatibility the Expo's modules if it takes time, how about a minor/patch version for SDK 34?

**Comment by ide** [comment] 2019-08-08 16:58
We can cherry-pick this into SDK 35. We are conservative with minor releases, though, since the overhead of doing a release is high.

**Comment by wkozyra95** [comment] 2019-08-09 07:30
We already use that jsc version (245459.0.0)
In sdk34 it was from the beginning
On sdk33 
- (Jul 2) v245459.0.0 was updated when support for 64 bit was added (https://github.com/expo/expo/commit/a6d7c5a84f8da1d55f4322c831ee57348338dd85).
- (Jun 5) the previous version (241213.2.0) was also newer than in react-native (added in https://github.com/expo/expo/commit/33142e83b1048aae86bdfc1d89844212f4e66cef)

**Comment by ide** [comment] 2019-08-09 19:27
Let's close this issue then. We've updated JSC since the timeline described above and any crashes are likely to have a different root cause.

**Closed by ide** 2019-08-09 19:27 UTC
