### ISSUE TITLE
Clicking at category action which not open app to foreground, not trigger NotificationResponseReceivedListener

### ISSUE THREAD

**Issue by shakedmanes** [expo/expo#11462] opened 2020-12-24 16:17 UTC
### Summary of Issue 
In android, when clicking at notification category action which created with `openAppToForeground: false` option,
the NotificationResponseReceivedListener event listener is not triggered.

This occurs on standalone apps (mine is in managed workflow btw).

In my example, I'm simply trying to dismiss the notification when clicking at 'Cancel' category action on the notification - which does not happen.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 4.0.16 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.19.0 - /usr/local/bin/node
      npm: 6.13.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.16
    Expo Workflow: managed

Target: Android

#### Steps to Reproduce:

Here's [snack](https://snack.expo.io/@ahihenachta/notification-action-not-triggered) to reproduce with following steps:

1. Create a standalone app from the above snack or equivalent.
2. Run the standalone app.
3. Click at 'Create Notification Category' button (creates a notification category actions for the notification).
4. Click at 'Schedule Notification' and immediately exit the app (Schedule notification for the next 7 seconds).
5. When notification appears, click at 'Cancel' action (which will emit action to dismiss the notification).

#### Expected Behavior:
NotificationResponseReceivedListener should be triggered (notification should be dismissed).

#### Actual Behavior:
NotificationResponseReceivedListener was not triggered (notification still exists in notification tray).

**Comment by shakedmanes** [comment] 2021-01-06 21:20
> @shakedmanes I think this has to do with how you're removing the subscription, i was able to trigger `NotificationResponseReceivedListener` as long as the app is backgrounded (if the app is killed, the notification response received listeners won't be triggered, since they require spinning up the JS). 

So you are saying that by removing the 32 line in the snack, which contains `subscription.remove();` it should trigger the notification response received listeners?
Because I have tried removing that line but it still does not trigger.

Maybe somehow that is the expected behavior? Which caused by the `openAppToBackground` option? (When it configured to `false`)

**Comment by cruzach** [comment] 2021-01-06 21:37
Are you trying to trigger the notificationResponseReceiver while the app is _backgrounded_, or while the app is completely killed?

**Comment by shakedmanes** [comment] 2021-01-06 21:42
When the app is completely killed, which is working when I tap at the notification category button which configured with `openAppToForeground=true` (The 'Accept' button in the snack).

**Comment by cruzach** [comment] 2021-01-06 21:51
Yeah, that's expected behavior for `openAppToForeground=false` if the app is killed

**Comment by shakedmanes** [comment] 2021-01-06 21:54
I think it would be useful if it will be mentioned somewhere in the docs, its kind of confusing situation 😅

**Comment by cruzach** [comment] 2021-01-06 21:56
Sure, just to explain- since the app is killed, and you are choosing **not** to foreground the app, the JS is never spun up, so there are no listeners registered to be triggered.

**Comment by shakedmanes** [comment] 2021-01-06 21:59
Thanks for the explanations and the quick response!

**Comment by shakedmanes** [comment] 2021-01-06 22:06
By the way, there's any way of implementing that behavior in android devices?
I mean the behavior for dismissing the notification without opening the app to foreground by tapping notification button (as sane as WhatsApp and other apps perform with 'Mark as read' or similar)
I know that behavior supported with ios devices by set the `customDissmissAction` property when creating notification categories.

**Comment by cruzach** [comment] 2021-01-06 22:16
that's a good question- after some quick searching, it doesn't look like there's a way for us to do that. I think that the `autoDismiss` property probably _should_ apply to that, but it seems that it only works if the actual notification itself is clicked. [It seems you are not the only one looking for this behavior (even from a native android dev perspective)](https://stackoverflow.com/questions/56293760/auto-dismiss-notification-on-android-9-app-when-notification-action-performed)

**Comment by cruzach** [comment] 2021-01-06 22:16
this issue is fixed in https://github.com/expo/expo/commit/8ec57cff3e196c9c96b1d76f3775e2c607eb207f

**Closed by cruzach** 2021-01-06 22:16 UTC
Labels: Android, Notifications, needs more info, pending closure

**Comment by MatthiasMuller** [comment] 2022-01-09 22:44
@cruzach Hey, just a little question, is there currently a solution to trigger actions when app is killed and openAppToForeground is false?

**Comment by AliMonam** [comment] 2022-09-20 13:25
What is the point of having Category Action, when we should keep the app in the background?

**Comment by lsandini** [comment] 2023-10-22 14:08
If one category is "alert snooze", then you just want to trigger a new local notification x minutes later, without opening the app
