### ISSUE TITLE
Error on Android build after expo eject

### ISSUE THREAD

**Issue by nartydev** [expo/expo#5546] opened 2019-09-05 11:59 UTC
### Environment

Expo CLI 3.0.8 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^2.18.3 => 2.18.3
    npmGlobalPackages:
      expo-cli: 3.0.8

The app is for Android & iOS and i use ExpoKit to make payments available.

### Steps to Reproduce

You can git clone https://github.com/nartydev
And try to sync the gradle with android studio

### Expected Behavior

I juste want to build a apk file and run app on Android device

### Actual Behavior

it doesn't work and the actual error is : 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unimodules-task-manager-interface:checkDebugManifest'.
> Failed to create parent directory '/Applications/MAMP/htdocs/teaser-beta/node_modules/unimodules-task-manager-interface/android/build' when creating directory '/Applications/MAMP/htdocs/teaser-beta/node_modules/unimodules-task-manager-interface/android/build/intermediates/check_manifest_result/debug/checkDebugManifest/out'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6m 21s
1 actionable task: 1 executed
ERROR: Failed to create parent directory '/Applications/MAMP/htdocs/teaser-beta/node_modules/unimodules-task-manager-interface/android/build' when creating directory '/Applications/MAMP/htdocs/teaser-beta/node_modules/unimodules-task-manager-interface/android/build/intermediates/check_manifest_result/debug/checkDebugManifest/out'

INFO: The following project options are deprecated and have been removed: 
android.useDeprecatedNdk
NdkCompile is no longer supported
Affected Modules: app, expo-ads-admob, expo-ads-facebook, expo-analytics-amplitude, expo-analytics-segment, expo-app-loader-provider, expo-av, expo-background-fetch, expo-barcode-scanner, expo-brightness, expo-calendar, expo-camera, expo-constants, expo-contacts, expo-crypto, expo-document-picker, expo-face-detector, expo-facebook, expo-file-system, expo-font, expo-gl, expo-gl-cpp, expo-google-sign-in, expo-haptics, expo-image-manipulator, expo-image-picker, expo-intent-launcher, expo-keep-awake, expo-linear-gradient, expo-local-authentication, expo-localization, expo-location, expo-mail-composer, expo-media-library, expo-permissions, expo-print, expo-random, expo-secure-store, expo-sensors, expo-sharing, expo-sms, expo-speech, expo-sqlite, expo-task-manager, expo-web-browser, unimodules-barcode-scanner-interface, unimodules-camera-interface, unimodules-constants-interface, unimodules-core, unimodules-face-detector-interface, unimodules-file-system-interface, unimodules-font-interface, unimodules-image-loader-interface, unimodules-permissions-interface, unimodules-react-native-adapter, unimodules-sensors-interface, unimodules-task-manager-interface

INFO: API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with 'variant.getExternalNativeBuildProviders()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getExternalNativeBuildTasks(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
```
Affected Modules: app

Thanks !

**Comment by cruzach** [comment] 2019-09-06 19:30
Are you getting this error even when trying to build a blank Expokit project? 

Did this error crop up after upgrading SDKs? If so I'd double check over [these upgrade steps](https://docs.expo.io/versions/latest/expokit/expokit/#android-1)

**Comment by nartydev** [comment] 2019-09-06 19:48
I have the same error when i if i create a blank Expokit project
![image](https://user-images.githubusercontent.com/16448382/64456233-09ffd380-d0f0-11e9-8897-c88325620c3a.png)

I developed the whole application on Expo and then I updated the SDK and I made an expo reject

**Comment by cruzach** [comment] 2019-09-06 19:58
Hm I just tried this on a blank Expokit project and didn't see any errors, same version of Android Studio (just the `variant.getExternalNativeBuildTasks()` warning), so this might be environmental

**Comment by reetika-2** [comment] 2019-09-07 16:53
<img width="1338" alt="Screenshot 2019-09-07 at 10 04 25 PM" src="https://user-images.githubusercontent.com/44520837/64477629-a04cfb80-d1bb-11e9-98ec-adb82213b95e.png">
<img width="1338" alt="Screenshot 2019-09-07 at 10 04 46 PM" src="https://user-images.githubusercontent.com/44520837/64477630-a216bf00-d1bb-11e9-842c-2e2824e349fc.png">
<img width="1440" alt="Screenshot 2019-09-07 at 10 04 57 PM" src="https://user-images.githubusercontent.com/44520837/64477632-a642dc80-d1bb-11e9-9430-16e3fd5d5c7f.png">
<img width="1440" alt="Screenshot 2019-09-07 at 10 05 08 PM" src="https://user-images.githubusercontent.com/44520837/64477633-a7740980-d1bb-11e9-8b1b-42052ea42fdd.png">
<img width="1440" alt="Screenshot 2019-09-07 at 10 05 17 PM" src="https://user-images.githubusercontent.com/44520837/64477635-a93dcd00-d1bb-11e9-9779-6d93fc55a775.png">
<img width="1440" alt="Screenshot 2019-09-07 at 10 05 30 PM" src="https://user-images.githubusercontent.com/44520837/64477637-aa6efa00-d1bb-11e9-81cd-038bc62131d5.png">

I am getting this error only in android build, not for ios.

package.json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "axios": "^0.19.0",
    "core-js": "^3.2.1",
    "expo": "^33.0.0",
    "expo-constants": "^5.0.1",
    "expo-facebook": "^5.0.1",
    "expo-font": "^5.0.1",
    "expo-google-app-auth": "^6.0.0",
    "expo-location": "^5.0.1",
    "expo-permissions": "^5.0.1",
    "expokit": "^33.0.6",
    "firebase": "^6.6.0",
    "react": "16.8.3",
    "react-dom": "^16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-elements": "^1.2.0",
    "react-native-geocoding": "^0.3.0",
    "react-native-google-autocomplete": "^0.1.7",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-razorpay": "^2.1.29",
    "react-native-swiper": "^1.5.14",
    "react-native-unimodules": "^0.5.4",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^3.12.1",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.1.1"
  },
  "private": true
}
kindly help me if you know about its solution

**Comment by nartydev** [comment] 2019-09-07 17:04
> Hm I just tried this on a blank Expokit project and didn't see any errors, same version of Android Studio (just the `variant.getExternalNativeBuildTasks()` warning), so this might be environmental

I can try what, reinstall android studio ? So this is not in relation with the code ?

**Comment by cruzach** [comment] 2019-09-09 15:13
I have the same version of Android studio, you could try clearing all the caches/Android settings files and rerunning on the blank project? I'm running `expo-cli` 3.0.10 so I would try upgrading to that as well

**Comment by nartydev** [comment] 2019-09-09 16:32
> I have the same version of Android studio, you could try clearing all the caches/Android settings files and rerunning on the blank project? I'm running `expo-cli` 3.0.10 so I would try upgrading to that as well

I have try to delete all of application and install but nothing happen...  I wil try to upgrade expo

**Comment by nartydev** [comment] 2019-09-10 21:33
Now i have this error : 
`ERROR: Failed to create parent directory '/Applications/MAMP/htdocs/teaser-beta/node_modules/react-native-unimodules/node_modules/unimodules-image-loader-interface/android/build' when creating directory '/Applications/MAMP/htdocs/teaser-beta/node_modules/react-native-unimodules/node_modules/unimodules-image-loader-interface/android/build/intermediates/check_manifest_result/debug/checkDebugManifest/out'
`

**Comment by nartydev** [comment] 2019-09-16 09:21
> Your `react-native` version dependency should point to Expo's fork of React Native for that particular SDK you're using

I have change my dependency for react-native by this : 
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz"

And now the error when gradle try to sync : 
`ERROR: Could not get unknown property 'VersionNumber' for settings 'android' of type org.gradle.initialization.DefaultSettings.
`

**Comment by nartydev** [comment] 2019-09-17 12:06
> Your `react-native` version dependency should point to Expo's fork of React Native for that particular SDK you're using

I have replaced the dependency "react-native-unimodules": "^0.5.4" so the error now is is : 

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-background-fetch:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.


2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-analytics-segment:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.


3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-brightness:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-ads-admob:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

5: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-app-auth:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.


6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-ads-facebook:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.


7: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-barcode-scanner:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by nartydev** [comment] 2019-09-17 14:22
I have add all modules in package.json : 

`
 "expo-app-auth": "^6.0.0",
        "expo-background-fetch": "^6.0.0",
        "expo-analytics-segment": "^6.0.0",
        "expo-brightness": "^6.0.0",
        "expo-ads-admob": "^6.0.0",
        "expo-ads-facebook": "^6.0.0",
        "expo-crypto": "^6.0.0",
        "expo-document-picker": "^6.0.0",
        "expo-image-picker": "^6.0.0",
        "expo-local-authentication": "^6.0.0",
        "expo-intent-launcher": "^6.0.0",
        "expo-contacts": "^6.0.0",
        "expo-font": "^6.0.0",
        "expo-camera": "^6.0.0",
        "expo-facebook": "^6.0.0",
        "expo-gl": "^6.0.0",
        "expo-location": "^6.0.0",
        "expo-print": "^6.0.0",
        "expo-random": "^6.0.0",
        "expo-media-library": "^6.0.0",
        "expo-mail-composer": "^6.0.0",
        "expo-keep-awake": "^6.0.0",
        "expo-google-sign-in": "^6.0.0",
        "expo-image-manipulator": "^6.0.0",
        "expo-sms": "^6.0.0",
        "expo-sharing": "^6.0.0",
        "expo-speech": "^6.0.0",
        "expo-web-browser": "^6.0.0",
        "expo-sensors": "^6.0.0",
        "react-native-adapter": "^6.0.0"
`
And now the error : 

`ERROR: Manifest merger failed : Attribute data@scheme at manifestMerger682676670814378203.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.` but i put it in gradle

**Comment by superphil0** [comment] 2019-10-01 11:54
Hey, just ejected with SDK 35, get something very smilar to @reetika-2 
with my app but also from clean
steps to reproduce
seems this might be related to unimodules somehow not being correctly setup ?

expo init
expo eject
expo install expo-av
expo run android

**Comment by cruzach** [comment] 2019-10-01 20:55
@superphil0 what error are you seeing?

**Comment by superphil0** [comment] 2019-10-01 21:06
Hey I already fixed it, I had to run the jetifier you might want to add this to the expo-av documentation

**Comment by tsapeta** [comment] 2020-06-30 12:28
SDK33 is no longer supported and looks like running Jetifier solved this issue — so I'm closing the issue.

**Closed by tsapeta** 2020-06-30 12:28 UTC
Labels: Android, bug, needs repro, project: expokit
