### ISSUE TITLE
[expo-image 2.0.0] borderWidth, borderColor props doesn't take effects on Android

### ISSUE THREAD

**Issue by chinamcafee** [expo/expo#32964] opened 2024-11-16 03:43 UTC
### Minimal reproducible example

https://github.com/chinamcafee/expo-image-bug-report

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

As Minimal reproducible example shows, 
`
  image: {
    marginTop: 200,
    height: 150,
    width: 150,
    backgroundColor: '#0553',
    borderWidth: 3,
    borderColor: 'red'
  }
`
    borderWidth: 3,
    borderColor: 'red'
doesn't take effects on Android both on Expo Go and development builds, but on IOS, every props works well.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - ~/Library/Caches/fnm_multishells/12221_1711903376778/bin/node
      Yarn: 1.22.22 - ~/Library/Caches/fnm_multishells/45833_1731728316909/bin/yarn
      npm: 10.8.1 - ~/Library/Caches/fnm_multishells/12221_1711903376778/bin/npm
      Watchman: 2024.11.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/lib/ruby/gems/3.2.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7
      react: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
    npmGlobalPackages:
      eas-cli: 12.6.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by brentvatne** [comment] 2024-11-16 07:12
thanks for the report! this is actually a duplicate of https://github.com/expo/expo/issues/32814

it's also listed in known issues of sdk 52 release notes: https://expo.dev/changelog/2024/11-12-sdk-52#known-issues

**Closed by brentvatne** 2024-11-16 07:12 UTC
Labels: needs review
