### ISSUE TITLE
audio module - android - Oreo vs. Nougat

### ISSUE THREAD

**Issue by davidgithub1980** [expo/expo#2141] opened 2018-08-26 20:41 UTC
Hi, my dev is the following:

**"expo": "^29.0.0"
"react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz"**

My app under development is using the Expo **Audio** module. Whenever the app is run on an **Android Oreo device**, the sound is audible. But whenever the app is run on an **Android Nougat device or tablet**, the sound is inaudible. Is the the Expo Audio module not backward compatible?

**Comment by ide** [comment] 2018-08-27 21:50
It's intended to work on all supported versions of Android (currently 4.4+ and perhaps 5+ soon).

**Comment by LukasNavickas** [comment] 2019-07-28 16:50
Audio module does not work with Android (Expo 32 and 33)

**Comment by mczernek** [comment] 2019-10-18 10:49
The issue is very generic and does not provide any description nor examples. We cannot reproduce it. I am closing it for now.

@LukasNavickas @davidgithub1980  In case you still have problems running Audio on newest Expo, please let us know by opening another issue. We'll be more than happy to help!
Please make sure you provide some description and code snippets or, ideally [snack](https://snack.expo.io) on how you try to use Audio module.

**Closed by mczernek** 2019-10-18 10:49 UTC
Labels: Audio, project: android-runtime
