### ISSUE TITLE
Expo Camera not visible in Maskview (Eas Development Client)

### ISSUE THREAD

**Issue by johndev247** [expo/expo#16654] opened 2022-03-16 14:01 UTC
### Summary

I'm Using expo for my react native project and trying to use Maskview and a camera overlay for a face detection, it works perfect on expo go app but when i use eas to build a development client, it doesn't work, rather i get just the white background of the parent view and the maskview. if I replace the camera with Image, it will show but camera wont. I actually switched to eas build to test react native fastimage i added, so after seeing that the fastimage is working good, I can just switch back to using expo go app to continue with the other part of the project but my fear is, after I finish the project and submit it to the app stores, the users may experience the same thing.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Environment

expo SDK 43

### Reproducible demo

    <MaskedView style={{ flex: 1 }}
           maskElement={
                 <View style={{ backgroundColor: '#00000077', flex: 1, }} >
                        <View style={{ backgroundColor: '#ff00ff',borderRadius: 200, flex: 1 }} />
                  </View>
           }>
      <Camera style={{width:50, height:50}}/>
    </MaskedView>

**Comment by byCedric** [comment] 2022-03-17 13:06
Hi @johndev247! Can you share a repo with the libraries you use? With that, we can investigate what's going on.

**Comment by johndev247** [comment] 2022-03-19 04:34
@byCedric Here is a repo of the repo example. This will work with "expo start" command, but if built with eas build development, the downloaded client version will not show the camera but can show anything like Image, Text or anything else. Repo: [https://github.com/johndev247/Expo-Camera](url)

**Comment by tcdavis** [comment] 2022-03-23 17:45
Thanks @johndev247.  From what I can tell the issue is not limited to the camera component: the only thing I could get to mask as expected was an image component.  Is that what you are seeing as well?

It seems there are a number of Android specific issues on the MaskView repo, so it's possible what we're seeing is a duplicate of something there which may have a workaround already

**Comment by johndev247** [comment] 2022-03-30 01:59
@tcdavis  Ok Thanks, I will check the repo to see if there is any workaround

**Closed** 2022-06-28 01:59 UTC
Labels: needs repro, Camera, Custom Client

**Comment by wajahat9876** [comment] 2023-10-06 11:18
I have an issue that on my react native application MaskView causing my camera to not open on android device but all i have done is that update my MaskView and Expo Camera library and make a new Development Client after that my application is running Fine and issue resolved.
