### ISSUE TITLE
EAS does not build Expo SDK v44 Managed App

### ISSUE THREAD

**Issue by pheuter** [expo/expo#15680] opened 2021-12-21 20:28 UTC
### Summary

The following error is thrown on EAS build servers when trying to build an app that worked on Expo SDK v43 with no code changes other than `expo upgrade` to v44.

```
› Compiling expo-localization Pods/ExpoLocalization » LocalizationModule.swift

❌  (node_modules/expo-localization/ios/LocalizationModule.swift:14:5)

  12 |     }
  13 | 
> 14 |     function("getLocalizationAsync") {
     |     ^ cannot find 'function' in scope
  15 |       return Self.getCurrentLocalization()
  16 |     }
  17 |   }
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoLocalization' from project 'Pods')
▸ 	CompileSwift normal arm64 /Users/expo/workingdir/build/node_modules/expo-localization/ios/LocalizationModule.swift (in target 'ExpoLocalization' from project 'Pods')
▸ 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoLinearGradient' from project 'Pods')
▸ (3 failures)
** ARCHIVE FAILED **
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoLocalization' from project 'Pods')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoLinearGradient' from project 'Pods')
	CompileSwift normal arm64 /Users/expo/workingdir/build/node_modules/expo-localization/ios/LocalizationModule.swift (in target 'ExpoLocalization' from project 'Pods')
The following build commands failed:
(3 failures)
Exit status: 65
+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.185.1                 |
| sdk         | iPhoneOS15.0.sdk        |
+-------------+-------------------------+
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

```
Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.2.0 - ~/.nvm/versions/node/v17.2.0/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v17.2.0/bin/yarn
      npm: 8.1.4 - ~/.nvm/versions/node/v17.2.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.0
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    npmGlobalPackages:
      eas-cli: 0.42.4
      expo-cli: 5.0.3
    Expo Workflow: managed
```

### Reproducible demo

https://expo.dev/accounts/careswitch/projects/careswitch/builds/69e426f5-c071-40cc-bfec-fa5e58aadccc

I'm not sure how to share something reproducible here since `expo r` works just fine and the app loads normally on the Expo Go dev client. The issue is encountered solely when doing `eas build` during the step that builds the `expo-localization` native package.

**Comment by brentvatne** [comment] 2021-12-21 20:45
here is a good guide to trying to reproduce: https://expo.fyi/manual-debugging

**Comment by brentvatne** [comment] 2021-12-21 20:50
it looks like from your build that you have `@unimodules/core` installed. you should find where that is coming from and remove it. react-native-unimodules and its dependent packages are no longer used in sdk43+

**Comment by pheuter** [comment] 2021-12-21 21:08
@brentvatne Brilliant, that appeared to be the issue, appreciate that insight a lot! Appeared to work just fine in Expo SDK v43, v44 not so much, and didn't catch it in the v44 blog post, but found another blog post that did call out this change unrelated to the v44 release.

**Comment by brentvatne** [comment] 2021-12-21 22:04
thanks for the follow up! we need to add some validation to `expo doctor` for this

**Comment by mariomurrent-softwaresolutions** [comment] 2021-12-23 06:31
Had the same issue after upgrading. I started the build with using --clear-cache and also upgraded to the latest Expo SDK 44.0.1. 
Seems like those steps fixed the issue for me

**Comment by flygomel** [comment] 2021-12-23 13:16
Same issue after upgrading to SDK 44.
Can't build locally.

`
› Compiling expo-localization Pods/ExpoLocalization » LocalizationModule.swift

❌  (/Users/a.yelistratau/Dev/Projects/Tillybom/app/node_modules/expo-localization/ios/LocalizationModule.swift:14:5)

  12 |     }
  13 |
> 14 |     function("getLocalizationAsync") {
     |     ^ cannot find 'function' in scope
  15 |       return Self.getCurrentLocalization()
  16 |     }
  17 |   }

› Compiling @unimodules/core Pods/UMCore » UMCore-dummy.m
› Compiling expo-system-ui Pods/ExpoSystemUI » ExpoSystemUIModule.swift

❌  (/Users/a.yelistratau/Dev/Projects/Tillybom/app/node_modules/expo-system-ui/ios/ExpoSystemUI/ExpoSystemUIModule.swift:17:5)

  15 |     }
  16 |
> 17 |     function("getBackgroundColorAsync") { () -> String? in
     |     ^ cannot find 'function' in scope
  18 |       Self.getBackgroundColor()
  19 |     }
  20 |

› Packaging @unimodules/core Pods/UMCore » libUMCore.a
› Compiling expo-haptics Pods/ExpoHaptics » HapticsModule.swift

› 2 error(s), and 1 warning(s)

Failed to build iOS project. "xcodebuild" exited with error code 65.
error Command failed with exit code 1.
`

How to fix it?

**Comment by flygomel** [comment] 2021-12-23 15:57
In my case removing @bugsnag/expo module helped me

**Comment by mariomurrent-softwaresolutions** [comment] 2021-12-23 15:57
I think there are a lot of libraries which are currently not really compatible with the new SDK :(

**Comment by lc3t35** [comment] 2021-12-29 16:59
> In my case removing @bugsnag/expo module helped me

What @bugsnag/expo module has to do with expo-localization (it does not use it according to my yarn.lock) ? 
Is it a typo in the swift code added by @tsapeta in [ios] Migrate expo-localization to the new API (#15266)  -> func instead of function ?

**Comment by tsapeta** [comment] 2021-12-29 17:34
> What @bugsnag/expo module has to do with expo-localization (it does not use it according to my yarn.lock) ?

Right, they have nothing to do, so I doubt it solved anything.

> Is it a typo in the swift code added by @tsapeta?

Nope, that's correct, this is from our new API for writing native modules in Swift. It's defined here https://github.com/expo/expo/blob/7cebba6ba876eddef39d22fcef5e88a8d3161623/packages/expo-modules-core/ios/Swift/Objects/ObjectDefinitionComponents.swift#L25 (but it's been somewhere else in version released for SDK44).

My assumption is still that you have incorrect version of `expo-modules-core` linked in your app. Can you show me the output of `yarn why expo-modules-core`?

**Comment by tsapeta** [comment] 2021-12-29 17:38
Actually, I've just checked `@bugsnag/expo` and it depends on `expo-constants@^12.1.3` which is from SDK43, so it might be possible that somehow the old version of the modules core got installed 🤔

**Comment by lc3t35** [comment] 2021-12-29 17:40
Thanks ! I try without @bugsnag/expo and open a ticket on bugsnag.

**Comment by tsapeta** [comment] 2021-12-29 17:50
```
=> Found "expo-modules-core@0.4.9"
```

Yes, that's it! As a temporary workaround you can use [yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to enforce using version `^0.6.3` of `expo-modules-core` or `^13.0.0` of `expo-constants`.
I need to think a bit more what would be the best solution for bugsnag so we don't hit such issues in the future 🤔

**Comment by lc3t35** [comment] 2021-12-29 18:02
(not familiar with resolutions ...) something like this : 

```
"resolutions": {
    "@bugsnag/expo/expo-modules-core": "^0.6.3"
}
```

**Comment by tsapeta** [comment] 2021-12-29 18:18
`@bugsnag/expo` doesn't directly depend on the modules core so I think it should be `@bugsnag/expo/**/expo-modules-core` but I'd feel more confident with
```json
"resolutions": {
  "expo-constants": "~13.0.0"
}
```

**Comment by tsapeta** [comment] 2021-12-30 11:40
I guess this resolved an issue, so I'm closing it.

**Closed by tsapeta** 2021-12-30 11:40 UTC
Labels: needs review

**Comment by pardeephrgdev** [comment] 2022-02-09 13:02
Not solved yet. I still having the issue. Not able to build by eas. Also I am not getting any error while compilation. -
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/99012613/153206313-ec454b2a-dede-4b5c-b9d1-cc5ae6ec9ef6.png">

**Comment by mariomurrent-softwaresolutions** [comment] 2022-02-09 13:12
@pardeephrgdev What have you tried so far?

**Comment by venurasasankaabyeisnghe** [comment] 2022-02-11 02:49
function("getLocalizationAsync") ^ cannot find 'function' in scope
I had the above error on an expo bare workflow project when I install the expo-localization using "yarn add expo-localization" which installed the latest package.
To solve it I ran "expo install expo-localization" which downgraded it to version "expo-localization": "~11.0.0"
I am using "expo": "^43.0.0"

**Comment by tsapeta** [comment] 2022-02-11 11:48
I confirm that the newest version of `expo-localization` is not compatible with SDK43 and olders. We always recommend to use `expo install` command that ensures you have the right versions 😉

**Comment by brentvatne** [comment] 2022-04-06 20:46
@chancesmith - can you share a reproducible example?

**Comment by chancesmith** [comment] 2022-04-07 15:38
I'm wondering how I can scale down to a vanilla expo app or ignite app.
Do I have to have an example app in TestFlight to run an EAS build?

**Comment by chancesmith** [comment] 2022-04-07 16:18
Lastly, I removed `react-native-unimodules` and the build passed. Glorious 👏
