### ISSUE TITLE
Inconsistent notification object between ios and android

### ISSUE THREAD

**Issue by pascalchristian** [expo/expo#9118] opened 2020-07-07 12:23 UTC
### Summary of Issue 
Notification object (especially the `data` object) is presented differently between ios and android

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.21.13 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
      Shell: 5.0.16 - /bin/bash
    Binaries:
      Node: 12.18.0 - /usr/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.4 - /usr/bin/npm
    npmPackages:
      @expo/webpack-config: ^0.12.16 => 0.12.17 
      expo: ^38.0.0 => 38.0.8 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.13
```

Target: ios (real device) and android (real device, `"useNextNotificationsApi": true`)

### Reproducible Demo
```
const notificationResponseSubscription = Notifications.addNotificationResponseReceivedListener(response => {
      console.log('Notification clicked');
      console.log(response);
    });
```

 
### Steps to Reproduce
Send push notification, click on it, and read console.log output

### Expected Behavior vs Actual Behavior
**Actual Behavior**
actual content of `data` is located in `response.notification.request.content.data` for android
actual content of `data` is located in `response.notification.request.content.data.body` for ios

**Expected Behavior**
actual content of `data` is located in `response.notification.request.content.data.body` for both
(consistent with snack in https://docs.expo.io/versions/latest/sdk/notifications/)

**Comment by pascalchristian** [comment] 2020-07-07 12:24
Might be related to https://github.com/expo/expo/issues/9059

**Comment by cruzach** [comment] 2020-07-07 18:59
This is duplicate of 9059 (linked above), so I'm going to close it to keep the conversation in one place

**Closed by cruzach** 2020-07-07 18:59 UTC
Labels: Notifications
