### ISSUE TITLE
[SDK34, Ejected, Android] Duplicate jar entry [com/facebook/react/uimanager/UIManagerReanimatedHelper.class]

### ISSUE THREAD

**Issue by lc3t35** [expo/expo#5820] opened 2019-10-01 12:30 UTC
### Environment
```
Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @types/react: 16.9.2 => 16.9.2
      @types/react-native: 0.60.13 => 0.60.13
      expo: 34.0.4 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.1.tar.gz => 0.59.8
      react-navigation: 3.11.1 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.1.2
```
Works fine on iOS / Testflight.
Target is Android

### Steps to Reproduce

expo eject
react-native link
remove unneeded lines in app/src/main/java/host/exp/exponent/MainApplication.java
```
  import com.horcrux.svg.SvgPackage;
  import com.swmansion.reanimated.ReanimatedPackage;
  import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
and
  new SvgPackage(),
  new ReanimatedPackage(),
  new RNGestureHandlerPackage()
```
gradlew installDebug -> OK on connected device
build with AndroidStudio in debug mode (Build, Generate Signed Bundle), adb install app-debug.apk -> OK on connected device
build and Generate Signed Bundle with AndroidStudio in *release mode*

### Expected Behavior

Generate apk in release mode

### Actual Behavior
Errors while building APK
```
java.lang.RuntimeException: Job failed, see logs for details
	at com.android.build.gradle.internal.transforms.ProGuardTransform.transform(ProGuardTransform.java:209)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	at sun.reflect.GeneratedMethodAccessor415.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Can't write [/Users/xxxxxxx/android/app/build/intermediates/transforms/proguard/release/0.jar] (Can't read [/Users/xxxxxxx/node_modules/react-native-reanimated/android/build/intermediates/intermediate-jars/release/classes.jar(;;;;;;;**.class)] (Duplicate jar entry [com/facebook/react/uimanager/UIManagerReanimatedHelper.class]))
	at proguard.OutputWriter.writeOutput(OutputWriter.java:202)
	at proguard.OutputWriter.execute(OutputWriter.java:89)
	at proguard.ProGuard.writeOutput(ProGuard.java:515)
	at proguard.ProGuard.execute(ProGuard.java:210)
	at com.android.build.gradle.internal.transforms.BaseProguardAction.runProguard(BaseProguardAction.java:66)
	at com.android.build.gradle.internal.transforms.ProGuardTransform.doMinification(ProGuardTransform.java:274)
	at com.android.build.gradle.internal.transforms.ProGuardTransform.access$000(ProGuardTransform.java:67)
	at com.android.build.gradle.internal.transforms.ProGuardTransform$1.run(ProGuardTransform.java:178)
	at com.android.builder.tasks.Job.runTask(Job.java:47)
	at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:282)
	... 1 more
Caused by: java.io.IOException: Can't read [/Users/xxxxxx/node_modules/react-native-reanimated/android/build/intermediates/intermediate-jars/release/classes.jar(;;;;;;;**.class)] (Duplicate jar entry [com/facebook/react/uimanager/UIManagerReanimatedHelper.class])
	at proguard.InputReader.readInput(InputReader.java:214)
	at proguard.InputReader.readInput(InputReader.java:184)
	at proguard.OutputWriter.writeOutput(OutputWriter.java:191)
	... 11 more
Caused by: java.io.IOException: Duplicate jar entry [com/facebook/react/uimanager/UIManagerReanimatedHelper.class]
	at proguard.io.ZipOutput.createOutputStream(ZipOutput.java:155)
	at proguard.io.ZipOutput.createOutputStream(ZipOutput.java:120)
	at proguard.io.JarWriter.createOutputStream(JarWriter.java:137)
	at proguard.io.FilteredDataEntryWriter.createOutputStream(FilteredDataEntryWriter.java:111)
	at proguard.io.FilteredDataEntryWriter.createOutputStream(FilteredDataEntryWriter.java:111)
	at proguard.io.ClassDataEntryWriter.createOutputStream(ClassDataEntryWriter.java:93)
	at proguard.io.ExtraDataEntryWriter.createOutputStream(ExtraDataEntryWriter.java:135)
	at proguard.io.IdleRewriter.read(IdleRewriter.java:49)
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
	at proguard.io.JarReader.read(JarReader.java:83)
	at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
	at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
	at proguard.InputReader.readInput(InputReader.java:210)
	... 13 more
```
### Reproducible Demo

Mentionned as warning here https://github.com/expo/expo/pull/5648, error in this issue

**Comment by ide** [comment] 2019-10-02 03:37
You might want to try deleting the JAR from react-native-reanimated and seeing what happens. I'd recommend debugging further to find the root cause.

**Comment by lc3t35** [comment] 2019-10-07 12:07
Removing the jar from react-native-reanimated works fine.

**Comment by BJW** [comment] 2019-10-07 14:10
I had the same problem. Could you please tell a newbie how/where you deleted the JAR ?

**Comment by CarterBland** [comment] 2019-10-21 16:23
Which JAR am I deleting? I deleted `intermediate-jars/release/classes.jar` & `intermediate-jars/release/res.jar` aswell as `transforms/mergeJavaRes/release/0.jar` but they seem to get regenerated and throwing the error.

**Comment by lc3t35** [comment] 2019-11-17 20:23
This problem still exists in SDK35 ...

**Comment by nicefella** [comment] 2019-12-13 14:11
Deleting .jar files didn't help. 
Is there any one who could overcome this issue? Thanks.

**Comment by pencilcheck** [comment] 2019-12-21 21:21
You need to remove the file (or folders).

Add a line before your build script

```rm -rf ./node_modules/react-native-reanimated/android/src/main/java/com/facebook/```

And that will fix the issue

**Comment by christiandave090697** [comment] 2020-05-29 09:31
are there any update on this? im facing the same issue :(

**Comment by expjess** [comment] 2020-07-07 20:13
Hi @christiandave090697 - are you still having trouble after [removing the file(s) from your src folder](After SDK 38, your ExpoKit apps in the App Store and Play Store will continue to run indefinitely, but you’ll need to migrate to the Bare or Managed workflows in order to get bugfixes and new features in Expo modules)? Looks like that worked for @pencilcheck and others.

**Comment by tsapeta** [comment] 2020-07-09 08:50
As we no longer support ExpoKit and the potential workaround has been posted above, I'm closing this bug report. Please migrate to managed or bare workflow instead of using ExpoKit 😉

**Closed by tsapeta** 2020-07-09 08:50 UTC
Labels: Android, ExpoKit, bug

**Comment by cpamp** [comment] 2020-09-17 20:20
Deleting the jar just gave me an error that the jar could not be found. I got around this by renaming the `UIManagerReanimatedHelper` class
