### ISSUE TITLE
Calendar issues:  Calendar.createEventAsync is throwing an error in ios

### ISSUE THREAD

**Issue by reactexcel** [expo/expo#4861] opened 2019-07-08 11:59 UTC
Here is my code
package.json

{
"main": "node_modules/expo/AppEntry.js",
"scripts": {
"start": "expo start",
"android": "expo start --android",
"ios": "expo start --ios",
"eject": "expo eject",
"test": "node ./node_modules/jest/bin/jest.js --watchAll"
},
"jest": {
"preset": "jest-expo"
},
"dependencies": {
"@expo/samples": "2.1.1",
"axios": "^0.18.0",
"expo": "^32.0.0",
"expo-calendar": "^5.0.1",
"expo-facebook": "^4.0.0",
"immutability-helper": "^3.0.0",
"lodash": "^4.17.11",
"moment": "^2.24.0",
"react": "16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
"react-native-autocomplete-input": "^3.6.0",
"react-native-get-location": "^1.1.2",
"react-native-image-picker": "^0.28.1",
"react-native-modalbox": "^1.7.1",
"react-native-snap-carousel": "^3.7.5",
"react-native-touch": "0.0.2",
"react-navigation": "^3.0.9",
"react-redux": "^6.0.0",
"redux": "^4.0.1",
"redux-actions": "^2.6.4",
"redux-logger": "^3.0.6",
"redux-saga": "^1.0.1"
},
"devDependencies": {
"babel-preset-expo": "^5.0.0",
"jest-expo": "^32.0.0"
},
"private": true
}

import { Calendar } from 'expo';

await Calendar.createCalendarAsync(calendarDetails).then(async (id)=>{
await Calendar.createEventAsync(Calendar.DEFAULT, eventDetails).then((eventId)=>{
console.log(eventId)
})
})

error

RemoteConsole.js:80 Possible Unhandled Promise Rejection (id: 0):
Error: Event with id 53035617-8016-42A8-BC6D-7F132B11ECB7 was not saved
Error: Event with id 53035617-8016-42A8-BC6D-7F132B11ECB7 was not saved

**Comment by cruzach** [comment] 2019-07-08 16:21
duplicate of #4838 

@reactexcel, you already have an issue open, so please don't open new ones for the same problem

**Closed by cruzach** 2019-07-08 16:21 UTC

**Comment by danish4114** [comment] 2019-07-09 04:31
I just created this one because i did not get any reply further for the problem,
so please help me, i am not publishing my app on store just because of this issue.
Thanks!
