### ISSUE TITLE
Expo-Task-Manager install breaks android app

### ISSUE THREAD

**Issue by Tinmania2018** [expo/expo#8950] opened 2020-06-24 20:27 UTC
### Summary of Issue (just a few sentences)
My app worked fine until the installation of expo-task-manager. IOS still works, android however failed to build

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Unavailable since it is a ejected app. Target is android. 

rn version; 0.62.2 expo-task-manager: 8.3.0 expo: 35.0.0 react-native-unimodules: ^0.9.1

### Reproducible Demo

`node_modules/react-native-unimodules/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/ReactAdapterPackage.java:29: error: cannot find symbol
    AppLoaderProvider.registerLoader(context, "react-native-headless", RNHeadlessAppLoader.class);`

- This should include as little code as possible, please don't simply link your entire project
- Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
- If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
- If you need more guidance, please see https://stackoverflow.com/help/mcve

As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!

### Steps to Reproduce
Install expo-task-manager and the android build failed. I reverted back to before the installation to double-check of this installation is indeed the culprit. With reverting back the app works again. 

### Expected Behavior vs Actual Behavior

Build the android app the same as the IOS app. I already updated the react-native-unimodels package but this did not help.

**Comment by cruzach** [comment] 2020-06-29 16:02
Hey @Tinmania2018 , this is most likely due to using RN .62 with Expo SDK 35. If you'd like to use that version of RN, you should upgrade to SDK 38. Since you're in the bare workflow, this means that upgrading react-native-unimodules to the latest version will probably resolve the issue - https://github.com/expo/expo/tree/master/packages/react-native-unimodules. What version is shown in your lockfile?

Can you provide a repo we can use to reproduce the issue?

**Comment by hussainahmad** [comment] 2020-07-02 04:21
Hey @cruzach  , I m using `"react-native-unimodules": "^0.8.1",` with react native version `"react-native": "0.61.5"` , before it was working fine, now When I try to make release build I m getting this issue.

**Comment by charanjit-singh** [comment] 2020-07-25 10:56
@cruzach     "react-native-unimodules": "^0.9.1"

**Comment by Tinmania2018** [comment] 2020-07-27 11:36
@cruzach  I did update the unimodules package but it unfortunatly didn't resolve this issue. To be honest I ditched this entire package and worked around it using different functions.

**Comment by charanjit-singh** [comment] 2020-07-29 18:36
I solved it using: 'expo update'

**Comment by byCedric** [comment] 2020-07-30 18:13
@Tinmania2018 That's unfortunate that it didn't work out the way it should for you, sorry for that. Thanks for trying our package though. If you encounter something with one of our packages, feel free to open a Github issue or ask a question on the [forums](https://forums.expo.io/) or [slack](https://slack.expo.io/)!

Closing this issue for now.

**Closed by byCedric** 2020-07-30 18:13 UTC
Labels: Android, Requesting changes to issue, TaskManager
