### ISSUE TITLE
[Expo Web] Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by MalcolmTomisin** [expo/expo#7036] opened 2020-02-12 20:46 UTC
I'm trying to compile a project that uses the deprecated-react-native-listview component , whenever I try to do that I always do get this error on the command line - 
"Failed to compile.
project/node_modules/deprecated-react-native-listview/index.js 27:12
Module parse failed: Unexpected token (27:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const merge = require('react-native/Libraries/vendor/core/merge');
| 
> import type {Props as ScrollViewProps} from 'react-native/Libraries/Components/ScrollView/ScrollView';
| 
| const DEFAULT_PAGE_SIZE = 1;
"
Project was set up with expo SDK 36

**Comment by cruzach** [comment] 2020-02-14 22:00
Does that library support web? It's not clear from this ticket why this is a bug with Expo, so I'm going to close the issue for now. If you can fill out the full bug report template, we can re-open 👍

**Closed by cruzach** 2020-02-14 22:00 UTC

**Comment by nikolang** [comment] 2020-03-12 20:11
I also got this error when trying to build for the web. It seems it is a Problem with the scrollView. I always thought that this compenent supports web. 

If it does not support web I would appreciate an alternative or a workaround I can use. I have no idea how to solve this.

**Comment by curtisbelt** [comment] 2020-05-26 13:14
The issue is that `/node_modules/deprecated-react-native-listview/index.js` is in typescript. I solved this by creating`webpack.config.js` and  [including the module names](https://github.com/expo/expo-cli/tree/master/packages/webpack-config#include-modules).

Found this solution via: https://forums.expo.io/t/webpack-loader-with-mixed-ts-and-js/32996/2

webpack.config.js

```js
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(
    {
      ...env,
      babel: {
        dangerouslyAddModulePathsToTranspile: ['deprecated-react-native-listview'],
      },
    },
    argv,
  );
  return config;
};
```
