### ISSUE TITLE
[expo-modules][expo-dev-client][SDK51] build error with `useFrameworks: 'static'`

### ISSUE THREAD

**Issue by leonhh** [expo/expo#28209] opened 2024-04-15 12:59 UTC
### Minimal reproducible example

https://github.com/leonhh/expo-reproducer/tree/4120ccfc4de5b1df55e284f76b4fc289339bf9a0

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Setting `useFrameworks` to true in combination with the new architecture will cause build errors on iOS:

app.json:
```json
"plugins": [
  [
    "expo-build-properties",
    {
      "ios": {
        "useFrameworks": "static",
        "newArchEnabled": true
      }
    }
  ]
],
```

The following error:
```sh
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptWeakObject.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptTypedArray.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptRuntime.mm

❌  (node_modules/react-native/ReactCommon/cxxreact/JSExecutor.h:15:10)

  13 | #include <cxxreact/NativeModule.h>
  14 | #include <folly/dynamic.h>
> 15 | #include <jsinspector-modern/InspectorInterfaces.h>
     |          ^ 'jsinspector-modern/InspectorInterfaces.h' file not found
  16 | #include <jsinspector-modern/ReactCdp.h>
  17 | 
  18 | #ifndef RN_EXPORT

› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIUtils.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIInstaller.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIConversions.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXAppDefines.m
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.11.0/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
      Watchman: 2024.04.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0-canary-20240411-55a0085 => 51.0.0-canary-20240411-55a0085 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.0-rc.8 => 0.74.0-rc.8 
    npmGlobalPackages:
      eas-cli: 7.3.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✖ Check Expo config (app.json/ app.config.js) schema
Unexpected error while running 'Check Expo config (app.json/ app.config.js) schema' check:
TypeError: Cannot read properties of undefined (reading 'schema')
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions
One or more checks failed, indicating possible issues with the project.

**Comment by leonhh** [comment] 2024-04-15 13:07
Also a somewhat related issue https://github.com/expo/expo/issues/27414 in a different expo package. Both work fine with the old architecture.

**Comment by efstathiosntonas** [comment] 2024-04-22 18:12
have the same issue on `51.0.0-preview.0` and `expo-modules-core@1.12.0`

**Comment by DarrKing** [comment] 2024-04-23 15:52
Same issue on "expo": "~50.0.17",

**Comment by MartinGambit** [comment] 2024-04-24 07:57
Same issue with  "expo": "^50.0.15" and rn 0.74

**Comment by DarrKing** [comment] 2024-04-24 09:25
In what way did you remove those dependencies @MartinGambit

**Comment by MartinGambit** [comment] 2024-04-24 10:29
Simply by downgrading react-native 0.74.0 back to 0.73.4 and then running pod install

**Comment by DarrKing** [comment] 2024-04-24 10:30
Cool thanks @MartinGambit. Tried this already, didn't work for myself unfortunately.

**Comment by MartinGambit** [comment] 2024-04-24 10:35
Well maybe there is a mismatch with your expo version. i am currently using "expo": "^50.0.15".
Also i would try cleaning build folder in xcode and rebuilding your app.

**Comment by enchorb** [comment] 2024-04-24 12:02
Same issue with RN `0.74` and Expo `50.0.17`

**Comment by tmitchel2** [comment] 2024-04-24 13:24
Unfortunately seeing this issue also after upgrading to react-native 0.74.  In my case static frameworks is requirement for firebase.

**Comment by tmitchel2** [comment] 2024-04-24 13:41
https://github.com/facebook/react-native/pull/42747 seems to be the cause.

`add_dependency(s, "React-jsinspector", :framework_name => 'jsinspector_modern')`

The"React-jsinspector" pod will only be included if the framework_name is 'jsinspector_modern' ?

**Comment by tmitchel2** [comment] 2024-04-24 13:46
And looks like it is being attended to on https://github.com/expo/expo/pull/27976

**Comment by MartinGambit** [comment] 2024-04-24 15:55
> Unfortunately seeing this issue also after upgrading to react-native 0.74. In my case static frameworks is requirement for firebase.

Yea same here

**Comment by leonhh** [comment] 2024-04-24 17:59
Please be aware that expo does not officially support react-native 0.74 yet. Support for 0.74 will most certainly only come out for SDK 51 and not for SDK 50.

**Comment by QuentinDanjou** [comment] 2024-04-24 19:07
@leonhh is there a place to see ETA for the next SDK version? (especially that v51?)

**Comment by davidjbng** [comment] 2024-05-07 08:49
I still get the same error with Expo 51.0.0

## Repro

[davidjbng/expo-use-frameworks-static](https://github.com/davidjbng/expo-use-frameworks-repro)

## Environment
> expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 3.7.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 22.1.0 - ~/.local/share/nvm/v22.1.0/bin/node
      npm: 10.7.0 - ~/.local/share/nvm/v22.1.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /Users/dj/.rvm/gems/ruby-2.7.8/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 33.0.2, 34.0.0
        System Images: android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-UpsideDownCakePrivacySandbox | Google Play ARM 64 v8a, android-VanillaIceCream | Google Play ARM 64 v8a
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: 51.0.0 => 51.0.0 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    Expo Workflow: bare

**Comment by b0iq** [comment] 2024-05-07 20:35
Expo 51 react native 0.74.1 

Still same issue

**Comment by jingp-ofload** [comment] 2024-05-08 01:02
Same here, can we reopen this issue?

**Comment by jingp-ofload** [comment] 2024-05-08 01:35
As a workaround, use `package-patch` add  
```
add_dependency(s, "React-jsinspector", :framework_name => 'jsinspector_modern')
```
to node_modules/expo-modules-core/ExpoModulesCore.podspec

**Comment by jingp-ofload** [comment] 2024-05-08 01:46
> [facebook/react-native#42747](https://github.com/facebook/react-native/pull/42747) seems to be the cause.
> 
> `add_dependency(s, "React-jsinspector", :framework_name => 'jsinspector_modern')`
> 
> The"React-jsinspector" pod will only be included if the framework_name is 'jsinspector_modern' ?

This solution not working for me.

**Comment by dungphung** [comment] 2024-05-08 02:44
Expo 51 react native 0.74.1
`(node_modules/react-native/ReactCommon/cxxreact/JSExecutor.h:15:10)

  13 | #include <cxxreact/NativeModule.h>
  14 | #include <folly/dynamic.h>
> 15 | #include <jsinspector-modern/InspectorInterfaces.h>
     |          ^ 'jsinspector-modern/InspectorInterfaces.h' file not found
  16 | #include <jsinspector-modern/ReactCdp.h>
  17 | 
  18 | #ifndef RN_EXPORT`
Still same issue

**Comment by jingp-ofload** [comment] 2024-05-08 05:52
I just realised that my issue is from `expo-dev-menu` not `expo-modules-core`

**Comment by voxlz** [comment] 2024-05-08 08:57
Also faceing this issue in SDK 51

**Comment by leonhh** [comment] 2024-05-08 09:32
> I just realised that my issue is from `expo-dev-menu` not `expo-modules-core`

Yes, this is an issue with expo-dev-client and is not related to expo-modules. Removing expo-dev-client fixes the issue. 

See https://github.com/expo/expo/issues/27414 for this issue

**Comment by sousaweb** [comment] 2024-05-08 15:10
Same problem here, after upgrading expo@50 to expo@51 and recreated the ios folder. 
In order to solve i removed the package.json and yarn.lock changes, ran the yarn install, so it downgraded to expo@50 and now its working fine again as before. I will wait more weeks to this fix be released, this way i can use the new expo@51.


 13 | #include <cxxreact/NativeModule.h>
  14 | #include <folly/dynamic.h>
> 15 | #include <jsinspector-modern/InspectorInterfaces.h>
     |          ^ 'jsinspector-modern/InspectorInterfaces.h' file not found
  16 | #include <jsinspector-modern/ReactCdp.h>
  17 | 
  18 | #ifndef RN_EXPORT

**Comment by a-eid** [comment] 2024-05-08 15:47
we're facing the same issue after upgrading from sdk 50.

**Comment by hewad-mubariz** [comment] 2024-05-08 18:19
having the same issue while trying to upgrade from sdk 50 to 51

**Comment by hirbod** [comment] 2024-05-08 18:39
I'll add my +1 too - indeed breaking, also without newArch enabled

**Comment by brentvatne** [comment] 2024-05-08 18:47
https://github.com/facebook/react-native/pull/44252 was merged into 0.74.1 which was meant to fix this but I'm able to reproduce this on SDK 51 on projects with static frameworks, we'll investigate

**Comment by Darren120** [comment] 2024-05-09 03:35
+1 

a bit different

❌  error: SHA-1 for file /var/folders/dy/lzfv254j3x3xxxwykt7v63d80000gn/T/eas-build-local-nodejs/205af4f1-34af-4030-bd12-xxxxxx/build/node_modules/expo/AppEntry.js (/var/folders/dy/lzfv254j3x33cmwykt7v63d80000gn/T/eas-build-local-nodejs/205af4f1-34af-4030-bd12-xxxxxx/build/node_modules/expo/AppEntry.js) is not computed.

exit 65

**Comment by H4ck3r-x0** [comment] 2024-05-09 05:35
i had smiler issue yesterday, #28676, and what i did is i installed fresh expo app, and i looked at the package.json file and i had to remove some of i think it is not unnecessary, that i do not really know what they are.
```
  "resolutions": {
    "react-refresh": "~0.14.0",
    "expo-modules-core": "~1.11.0"
  },
  "overrides": {
    "react-refresh": "~0.14.0",
    "expo-modules-core": "~1.11.0"
  },
  "expo": {
    "install": {
      "exclude": [
        "react-native-safe-area-context"
      ]
    }
  },
  ```
  the above code is from my old package.json so i removed them, and rebuild the app 
  ```
  eas build --platform ios --profile preview
  ```
  and the build went smoothly.
  
  so this is my old package.json,
  ```
  {
  "name": "here is my app name :)",
  "version": "1.0.0",
  "scripts": {
    "android": "expo start --android",
    "format": "eslint \"**/*.{js,jsx,ts,tsx}\" --fix && prettier \"**/*.{js,jsx,ts,tsx,json}\" --write",
    "ios": "expo start --ios",
    "start": "expo start",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@react-native-picker/picker": "2.7.5",
    "@react-navigation/native": "^6.1.7",
    "axios": "^1.6.5",
    "expo": "^51.0.0",
    "expo-font": "~12.0.4",
    "expo-image-picker": "~15.0.4",
    "expo-linking": "~6.3.1",
    "expo-localization": "~15.0.3",
    "expo-location": "~17.0.1",
    "expo-router": "~3.5.10",
    "expo-secure-store": "~13.0.1",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.4",
    "expo-updates": "~0.25.9",
    "expo-web-browser": "~13.0.3",
    "moment": "^2.30.1",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.1",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-reanimated": "3.10.0",
    "react-native-safe-area-context": "^4.6.3",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "@typescript-eslint/eslint-plugin": "^6.7.2",
    "@typescript-eslint/parser": "^6.7.2",
    "eslint": "^8.50.0",
    "eslint-config-universe": "^12.0.0",
    "prettier": "^3.0.3",
    "tailwindcss": "3.3.2",
    "typescript": "~5.3.3"
  },
  "eslintConfig": {
    "extends": "universe/native"
  },
  "resolutions": {
    "react-refresh": "~0.14.0",
    "expo-modules-core": "~1.11.0"
  },
  "overrides": {
    "react-refresh": "~0.14.0",
    "expo-modules-core": "~1.11.0"
  },
  "expo": {
    "install": {
      "exclude": [
        "react-native-safe-area-context"
      ]
    }
  },
  "private": true
}
``` 

the new package.json
```
{
  "name": "this is my app name :)",
  "version": "1.0.0",
  "scripts": {
    "android": "expo start --android",
    "format": "eslint \"**/*.{js,jsx,ts,tsx}\" --fix && prettier \"**/*.{js,jsx,ts,tsx,json}\" --write",
    "ios": "expo start --ios",
    "start": "expo start",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@react-native-picker/picker": "2.7.5",
    "@react-navigation/native": "^6.1.7",
    "axios": "^1.6.5",
    "expo": "~51.0.0",
    "expo-font": "~12.0.4",
    "expo-image-picker": "~15.0.4",
    "expo-linking": "~6.3.1",
    "expo-location": "~17.0.1",
    "expo-router": "~3.5.10",
    "expo-secure-store": "~13.0.1",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.4",
    "expo-updates": "~0.25.9",
    "expo-web-browser": "~13.0.3",
    "moment": "^2.30.1",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.1",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-safe-area-context": "^4.6.3",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.6",
    "react-native-reanimated": "3.10.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "@typescript-eslint/eslint-plugin": "^6.7.2",
    "@typescript-eslint/parser": "^6.7.2",
    "eslint": "^8.50.0",
    "eslint-config-universe": "^12.0.0",
    "prettier": "^3.0.3",
    "tailwindcss": "3.3.2",
    "typescript": "~5.3.3"
  },
  "eslintConfig": {
    "extends": "universe/native"
  },
  "private": true
}
```

also i changed the eas.json file 
```
{
  "cli": {
    "version": ">= 9.0.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "channel": "development"
    },
    "preview": {
      "distribution": "internal",
      "ios": {
        "simulator": true
      },
      "channel": "preview"
    },
    "production": {
      "channel": "production"
    }
  },
  "submit": {
    "production": {}
  }
}
```

to use the version of eas cli to 9.0.0 it was something like 7.0.

**Comment by mikevercoelen** [comment] 2024-05-09 11:45
Made it work with these patches based on this PR: https://github.com/expo/expo/pull/28702

[expo-dev-launcher+4.0.13.patch](https://github.com/expo/expo/files/15261740/expo-dev-launcher%2B4.0.13.patch)
[expo-dev-menu+5.0.13.patch](https://github.com/expo/expo/files/15261743/expo-dev-menu%2B5.0.13.patch)

**Closed** 2024-05-09 14:11 UTC
Labels: Issue accepted

**Comment by LetapF** [comment] 2024-05-09 18:45
> +1
> 
> a bit different
> 
> ❌ error: SHA-1 for file /var/folders/dy/lzfv254j3x3xxxwykt7v63d80000gn/T/eas-build-local-nodejs/205af4f1-34af-4030-bd12-xxxxxx/build/node_modules/expo/AppEntry.js (/var/folders/dy/lzfv254j3x33cmwykt7v63d80000gn/T/eas-build-local-nodejs/205af4f1-34af-4030-bd12-xxxxxx/build/node_modules/expo/AppEntry.js) is not computed.
> 
> exit 65 building for development profile works,
> 
> running prod fails.,
> 
> going back to 50.0.17 this issue goes away.

I have the same issue when i updated to expo 51

**Comment by brentvatne** [comment] 2024-05-09 18:59
please run `npx expo install --fix` and it should be resolved!

**Comment by Darren120** [comment] 2024-05-09 19:57
> [RUN_FASTLANE] ❌ error: SHA-1 for file /var/folders/x1/5vgd16c972g7592wt79sgtg00000gn/T/eas-build-local-nodejs/cd46cca2-93ed-45b8-91bd-b1d64d045365/build/node_modules/expo/AppEntry.js (/var/folders/x1/5vgd16c972g7592wt79sgtg00000gn/T/eas-build-local-nodejs/cd46cca2-93ed-45b8-91bd-b1d64d045365/build/node_modules/expo/AppEntry.js) is not computed.
> 
> [RUN_FASTLANE] ▸ ** ARCHIVE FAILED ** [RUN_FASTLANE] ▸ The following build commands failed: [RUN_FASTLANE] ▸ PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/xxxx/Library/Developer/Xcode/DerivedData/xxxx-ceyyddgvrbnwiebxdxvergijjchz/Build/Intermediates.noindex/ArchiveIntermediates/xxxx/IntermediateBuildFilesPath/xxxxx.build/Release-iphoneos/xxxx.build/Script-xxxxx.sh (in target 'xxxxx' from project 'xxxxx') [RUN_FASTLANE] ▸ (1 failure) [RUN_FASTLANE] ** ARCHIVE FAILED ** [RUN_FASTLANE] [RUN_FASTLANE] [RUN_FASTLANE] The following build commands failed: [RUN_FASTLANE] PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/xxxxx/Library/Developer/Xcode/DerivedData/xxxxx-xxxxx/Build/Intermediates.noindex/ArchiveIntermediates/xxxxx/IntermediateBuildFilesPath/xxxxx.build/Release-iphoneos/xxxxx.build/Script-0xxxxxx.sh (in target 'xxxx' from project 'xxxx') [RUN_FASTLANE] (1 failure) [RUN_FASTLANE] Exit status: 65 [RUN_FASTLANE] [RUN_FASTLANE] +---------------------------------------+ [RUN_FASTLANE] | Build environment | [RUN_FASTLANE] +-------------+-------------------------+ [RUN_FASTLANE] | xcode_path | /Applications/Xcode.app | [RUN_FASTLANE] | gym_version | 2.220.0 | [RUN_FASTLANE] | sdk | iPhoneOS17.4.sdk | [RUN_FASTLANE] +-------------+-------------------------+ [RUN_FASTLANE] Looks like fastlane ran into a build/archive error with your project [RUN_FASTLANE] It's hard to tell what's causing the error, so we wrote some guides on how [RUN_FASTLANE] to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/ [RUN_FASTLANE] Before submitting an issue on GitHub, please follow the guide above and make [RUN_FASTLANE] sure your project is set up correctly. [RUN_FASTLANE] fastlane uses `xcodebuild` commands to generate your binary, you can see the [RUN_FASTLANE] the full commands printed out in yellow in the above log. [RUN_FASTLANE] Make sure to inspect the output above, as usually you'll find more error information there [RUN_FASTLANE] [RUN_FASTLANE] [!] Error building the application - see the log above [RUN_FASTLANE] Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs. [CLEAN_UP_CREDENTIALS] Destroying keychain - /var/folders/x1/5vxxxxx/T/eas-build-xxxx.keychain [CLEAN_UP_CREDENTIALS] Removing provisioning profile
> 
> Build failed The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs. npx exited with non-zero code: 1 Error: build command failed.

same error might be related to https://github.com/react-native-menu/menu/issues/801

**Comment by Darren120** [comment] 2024-05-09 19:57
> please run `npx expo install --fix` and it should be resolved!

same issue might be related to https://github.com/react-native-menu/menu/issues/801

**Comment by hirbod** [comment] 2024-05-09 20:02
@brentvatne I can confirm that its fixed after running `npx expo install --fix`

**Comment by jingp-ofload** [comment] 2024-05-09 22:43
> Made it work with these patches based on this PR: #28702
> 
> [expo-dev-launcher+4.0.13.patch](https://github.com/expo/expo/files/15261740/expo-dev-launcher%2B4.0.13.patch) [expo-dev-menu+5.0.13.patch](https://github.com/expo/expo/files/15261743/expo-dev-menu%2B5.0.13.patch)

This is great! @Kudo Can I know what is the plan to release this so we could decide if go with patches.

**Comment by aniolpages** [comment] 2024-05-09 22:55
@jingp-ofload this should be fixed if you update expo-dev-client to the latest version. You can use `npx expo install --fix`

I've also had this issue and upgrading solved it.

**Comment by brentvatne** [comment] 2024-05-09 22:58
> When I updated Expo to the latest version as indicated in https://docs.expo.dev/workflow/upgrading-expo-sdk-walkthrough/ and also ran npx expo install --fix but it still didn't work

we released the fix this morning

**Comment by zhxie** [comment] 2024-05-12 07:45
> [RUN_FASTLANE] ❌ error: SHA-1 for file /var/folders/x1/5vgd16c972g7592wt79sgtg00000gn/T/eas-build-local-nodejs/cd46cca2-93ed-45b8-91bd-b1d64d045365/build/node_modules/expo/AppEntry.js (/var/folders/x1/5vgd16c972g7592wt79sgtg00000gn/T/eas-build-local-nodejs/cd46cca2-93ed-45b8-91bd-b1d64d045365/build/node_modules/expo/AppEntry.js) is not computed.
> 
> [RUN_FASTLANE] ▸ ** ARCHIVE FAILED ** [RUN_FASTLANE] ▸ The following build commands failed: [RUN_FASTLANE] ▸ PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/xxxx/Library/Developer/Xcode/DerivedData/xxxx-ceyyddgvrbnwiebxdxvergijjchz/Build/Intermediates.noindex/ArchiveIntermediates/xxxx/IntermediateBuildFilesPath/xxxxx.build/Release-iphoneos/xxxx.build/Script-xxxxx.sh (in target 'xxxxx' from project 'xxxxx') [RUN_FASTLANE] ▸ (1 failure) [RUN_FASTLANE] ** ARCHIVE FAILED ** [RUN_FASTLANE] [RUN_FASTLANE] [RUN_FASTLANE] The following build commands failed: [RUN_FASTLANE] PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/xxxxx/Library/Developer/Xcode/DerivedData/xxxxx-xxxxx/Build/Intermediates.noindex/ArchiveIntermediates/xxxxx/IntermediateBuildFilesPath/xxxxx.build/Release-iphoneos/xxxxx.build/Script-0xxxxxx.sh (in target 'xxxx' from project 'xxxx') [RUN_FASTLANE] (1 failure) [RUN_FASTLANE] Exit status: 65 [RUN_FASTLANE] [RUN_FASTLANE] +---------------------------------------+ [RUN_FASTLANE] | Build environment | [RUN_FASTLANE] +-------------+-------------------------+ [RUN_FASTLANE] | xcode_path | /Applications/Xcode.app | [RUN_FASTLANE] | gym_version | 2.220.0 | [RUN_FASTLANE] | sdk | iPhoneOS17.4.sdk | [RUN_FASTLANE] +-------------+-------------------------+ [RUN_FASTLANE] Looks like fastlane ran into a build/archive error with your project [RUN_FASTLANE] It's hard to tell what's causing the error, so we wrote some guides on how [RUN_FASTLANE] to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/ [RUN_FASTLANE] Before submitting an issue on GitHub, please follow the guide above and make [RUN_FASTLANE] sure your project is set up correctly. [RUN_FASTLANE] fastlane uses `xcodebuild` commands to generate your binary, you can see the [RUN_FASTLANE] the full commands printed out in yellow in the above log. [RUN_FASTLANE] Make sure to inspect the output above, as usually you'll find more error information there [RUN_FASTLANE] [RUN_FASTLANE] [!] Error building the application - see the log above [RUN_FASTLANE] Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs. [CLEAN_UP_CREDENTIALS] Destroying keychain - /var/folders/x1/5vxxxxx/T/eas-build-xxxx.keychain [CLEAN_UP_CREDENTIALS] Removing provisioning profile
> 
> Build failed The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs. npx exited with non-zero code: 1 Error: build command failed.

I have the same issue with you, and I fixed by changing `main` field in package.json from a older version `node_modules/expo/AppEntry.js` to `expo/AppEntry.js`.

**Comment by Darren120** [comment] 2024-05-12 23:45
> > [RUN_FASTLANE] ❌ error: SHA-1 for file /var/folders/x1/5vgd16c972g7592wt79sgtg00000gn/T/eas-build-local-nodejs/cd46cca2-93ed-45b8-91bd-b1d64d045365/build/node_modules/expo/AppEntry.js (/var/folders/x1/5vgd16c972g7592wt79sgtg00000gn/T/eas-build-local-nodejs/cd46cca2-93ed-45b8-91bd-b1d64d045365/build/node_modules/expo/AppEntry.js) is not computed.
> > [RUN_FASTLANE] ▸ ** ARCHIVE FAILED ** [RUN_FASTLANE] ▸ The following build commands failed: [RUN_FASTLANE] ▸ PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/xxxx/Library/Developer/Xcode/DerivedData/xxxx-ceyyddgvrbnwiebxdxvergijjchz/Build/Intermediates.noindex/ArchiveIntermediates/xxxx/IntermediateBuildFilesPath/xxxxx.build/Release-iphoneos/xxxx.build/Script-xxxxx.sh (in target 'xxxxx' from project 'xxxxx') [RUN_FASTLANE] ▸ (1 failure) [RUN_FASTLANE] ** ARCHIVE FAILED ** [RUN_FASTLANE] [RUN_FASTLANE] [RUN_FASTLANE] The following build commands failed: [RUN_FASTLANE] PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/xxxxx/Library/Developer/Xcode/DerivedData/xxxxx-xxxxx/Build/Intermediates.noindex/ArchiveIntermediates/xxxxx/IntermediateBuildFilesPath/xxxxx.build/Release-iphoneos/xxxxx.build/Script-0xxxxxx.sh (in target 'xxxx' from project 'xxxx') [RUN_FASTLANE] (1 failure) [RUN_FASTLANE] Exit status: 65 [RUN_FASTLANE] [RUN_FASTLANE] +---------------------------------------+ [RUN_FASTLANE] | Build environment | [RUN_FASTLANE] +-------------+-------------------------+ [RUN_FASTLANE] | xcode_path | /Applications/Xcode.app | [RUN_FASTLANE] | gym_version | 2.220.0 | [RUN_FASTLANE] | sdk | iPhoneOS17.4.sdk | [RUN_FASTLANE] +-------------+-------------------------+ [RUN_FASTLANE] Looks like fastlane ran into a build/archive error with your project [RUN_FASTLANE] It's hard to tell what's causing the error, so we wrote some guides on how [RUN_FASTLANE] to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/ [RUN_FASTLANE] Before submitting an issue on GitHub, please follow the guide above and make [RUN_FASTLANE] sure your project is set up correctly. [RUN_FASTLANE] fastlane uses `xcodebuild` commands to generate your binary, you can see the [RUN_FASTLANE] the full commands printed out in yellow in the above log. [RUN_FASTLANE] Make sure to inspect the output above, as usually you'll find more error information there [RUN_FASTLANE] [RUN_FASTLANE] [!] Error building the application - see the log above [RUN_FASTLANE] Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs. [CLEAN_UP_CREDENTIALS] Destroying keychain - /var/folders/x1/5vxxxxx/T/eas-build-xxxx.keychain [CLEAN_UP_CREDENTIALS] Removing provisioning profile
> > Build failed The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs. npx exited with non-zero code: 1 Error: build command failed.
> 
> I have the same issue with you, and I fixed by changing `main` field in package.json from a older version `node_modules/expo/AppEntry.js` to `expo/AppEntry.js`.

yah, after checking out their new tempaltes it does seem to be updated, weird how --fix didnt do anything
im gonna stick with 50.0.17 for the time being...

**Comment by brentvatne** [comment] 2024-05-12 23:59
> I have the same issue with you, and I fixed by changing main field in package.json from a older version node_modules/expo/AppEntry.js to expo/AppEntry.js.

> yah, after checking out their new tempaltes it does seem to be updated, weird how --fix didnt do anything
im gonna stick with 50.0.17 for the time being...

that shouldn't be required - we changed this in the template for completely unrelated reasons: `npm publish` on npm >8, which is what we use to publish our templates, pulls in the node_modules directory to the package if we include the `node_modules/` in lookup. if you can share a way for me to reproduce an issue here i'd be interested in seeing it.
