### ISSUE TITLE
[docs] [Gatsby] Guide doesn't work for RN / Expo 36

### ISSUE THREAD

**Issue by DennisOosterling** [expo/expo#7360] opened 2020-03-13 11:42 UTC
https://docs.expo.io/versions/latest/guides/using-gatsby/

when you follow this guide you currently get an error when trying to run `gatsby develop`

```
ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '@pmmmwh/react-refresh-webpack-plugin/src/overlay' in '/Users/dennis/Documents/mb-site/.cache'

File: .cache/error-overlay-handler.js

failed Building development bundle - 3.458s
```

Easy fix is to either use 
 `"react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",`

or

`yarn add "@pmmmwh/react-refresh-webpack-plugin"`

Although this fixes it, it is not the nicest way to fix.

**Comment by fson** [comment] 2020-03-18 14:09
This seems to be related to this issue in Gatsby: https://github.com/gatsbyjs/gatsby/issues/22250. The `.cache/error-overlay-handler.js` tries to import `@pmmmwh/react-refresh-webpack-plugin/src/overlay`, which it cannot resolve because Yarn does not hoist it to the top level of the `node_modules` folder.

It seems like someone is working on this. In the meantime, you could try one of the following:
- Temporarily add `@pmmmwh/react-refresh-webpack-plugin` as a devDependency of your project:
```
yarn add --dev "@pmmmwh/react-refresh-webpack-plugin"
```
- Use version `2.19.38` of `gatsby` (or older), which doesn't have this issue
```
yarn add gatsby@2.19.38
```

**Comment by IjzerenHein** [comment] 2020-05-18 09:22
Retested with the latest Gatsby version and confirmed that this problem is no longer an issue. 

**package.json**
```
{
  "dependencies": {
    "expo": "~37.0.3",
    "gatsby": "^2.21.33",
    "gatsby-plugin-react-native-web": "^3.1.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  }
}
```

Closing

**Closed by IjzerenHein** 2020-05-18 09:22 UTC
Labels: Platform: web, project: docs
