### ISSUE TITLE
If query parameters of a link contains brackets then expo router removes that query parameter

### ISSUE THREAD

**Issue by rajatkantinandi** [expo/expo#28286] opened 2024-04-18 13:40 UTC
### Minimal reproducible example

https://github.com/rajatkantinandi/expo-router-brackets-bug-demo

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

When part of the URL specifically in the query params contains something in brackets (Example: http://localhost:8081/page2?title=Test%20title%202%20(With%20brackets)), then the expo router removes the query parameter entirely. Please try out the reproducible demo above. Expo router v3, Expo SDK 50.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.1 => 50.0.17 
      expo-router: ~3.4.3 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.2.0
    Expo Workflow: managed

**Comment by rajatkantinandi** [comment] 2024-04-18 13:49
Looks like this is not only an issue with the Link component. Even if I enter the URL manually on the address bar then also, expo router removes the brackets.

**Comment by bhyoo99** [comment] 2024-04-19 03:52
Same Issue

**Comment by marklawlor** [comment] 2024-04-19 05:38
Duplicate of https://github.com/expo/expo/issues/26664 will be fixed in the next release

**Closed by marklawlor** 2024-04-19 05:38 UTC
Labels: needs review, Router
