### ISSUE TITLE
[expo-media-library] Invalid column COUNT(*) exception on Android 10.

### ISSUE THREAD

**Issue by ahmetbicer** [expo/expo#9635] opened 2020-08-08 09:29 UTC
### Summary of Issue 

I am trying to implement a custom gallery on my app. I am using expo-media-library to get albums. App crashes when `getAlbumsAsync()` called, only in Android 10.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Bare react native project
"expo-av": "^8.4.0",
"expo-media-library": "^8.4.0",
"expo-video-thumbnails": "^4.2.1",
"react-native-unimodules": "^0.10.1",

buildToolsVersion = "29.0.0"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29

Also i am requesting legacyExternalStorage on my AndroidManifest.xml file.
```
<application  
...
android:requestLegacyExternalStorage="true" 
>
...
</application>
```
Tested devices;
Emulator: Google Pixel 3XL Android 10
Device: Samsung galaxy M31 Android 10

### Reproducible Demo
Just call `getAlbumsAsync()` on android 10 device or emulator. This is how i am getting albums on other api versions.
```
getAlbums = async () => {
    const res = await MediaLibrary.requestPermissionsAsync()
    if (res.granted) {
      MediaLibrary.getAlbumsAsync()
                     .then((albums) => console.log(albums))
                     .catch((err) => console.warn(err)) // not catching any error app directly crashes
    }
  }
``` 

### Steps to Reproduce

Just call `getAlbumsAsync()` on android 10 device or emulator.

### Expected Behavior vs Actual Behavior
Expected: Get albums from that function call.
Actual: App crashes.

I also got the log dump from `adb logcat` you can see from this [link](https://gist.github.com/ahmetbicer/b1b5905503c1bc085fe8f5fdd0e0eea2). You can see in the first lines i requested permissions. java.lang.IllegalArgumentException: Invalid column COUNT(*) in line 11.

Thanks!

**Comment by barthap** [comment] 2020-08-10 06:38
I can confirm the issue. It seems to be related to #5905 and [this](https://stackoverflow.com/questions/60623594/replacement-for-group-by-in-contentresolver-query-in-android-q-android-10-a). SQL grouping queries are no longer supported. cc @lukmccall 

I see you are using bare workflow. If you don't need album's `assetCount` property, you can temporarily fix it for now, by commenting out those lines:
```diff
--- a/node_modules/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetAlbums.java
+++ b/node_modules/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetAlbums.java
@@ -27,9 +27,9 @@ class GetAlbums extends AsyncTask<Void, Void, Void> {
   @Override
   protected Void doInBackground(Void... params) {
     List result = new ArrayList();
-    final String countColumn = "COUNT(*)";
-    final String[] projection = {MediaStore.Images.Media.BUCKET_ID, MediaStore.Images.Media.BUCKET_DISPLAY_NAME, countColumn};
-    final String selection = MediaStore.Files.FileColumns.MEDIA_TYPE + " != " + MediaStore.Files.FileColumns.MEDIA_TYPE_NONE + ") GROUP BY (" + MediaStore.Images.Media.BUCKET_ID;
+    //final String countColumn = "COUNT(*)";
+    final String[] projection = {MediaStore.Images.Media.BUCKET_ID, MediaStore.Images.Media.BUCKET_DISPLAY_NAME};
+    final String selection = MediaStore.Files.FileColumns.MEDIA_TYPE + " != " + MediaStore.Files.FileColumns.MEDIA_TYPE_NONE;
 
     try (Cursor albums = mContext.getContentResolver().query(
         EXTERNAL_CONTENT,
@@ -43,14 +43,14 @@ class GetAlbums extends AsyncTask<Void, Void, Void> {
       } else {
         final int bucketIdIndex = albums.getColumnIndex(MediaStore.Images.Media.BUCKET_ID);
         final int bucketDisplayNameIndex = albums.getColumnIndex(MediaStore.Images.Media.BUCKET_DISPLAY_NAME);
-        final int numOfItemsIndex = albums.getColumnIndex(countColumn);
+        //final int numOfItemsIndex = albums.getColumnIndex(countColumn);
 
         while (albums.moveToNext()) {
           Bundle album = new Bundle();
           album.putString("id", albums.getString(bucketIdIndex));
           album.putString("title", albums.getString(bucketDisplayNameIndex));
           album.putParcelable("type", null);
-          album.putInt("assetCount", albums.getInt(numOfItemsIndex));
+          //album.putInt("assetCount", albums.getInt(numOfItemsIndex));
           result.add(album);
         }
         mPromise.resolve(result);

```

**Comment by ahmetbicer** [comment] 2020-08-10 07:52
Hi @barthap thank you for suggestion. Unfortunately i am using that assetCount property. I hope it will be a easy fix for you.

**Comment by barthap** [comment] 2020-08-10 12:16
Hi @ahmetbicer 
If you want a quick fix to make `assetCount` working - follow some changes from this commit: https://github.com/expo/expo/commit/1b7f61097c07506fad51fe7e913df9f3b421a9ad

These are not yet final changes, but they should do the trick for you now. When I finish and do some cleanup, I'll open a PR for this.

**Comment by ahmetbicer** [comment] 2020-08-10 12:53
@barthap Thank you so much for quick fix! Do you want me to close the issue or wait until the PR.

**Comment by barthap** [comment] 2020-08-10 13:36
It will be closed automatically after my PR is merged, Thanks.

**Closed** 2020-08-12 07:33 UTC
Labels: Android, MediaLibrary
