### ISSUE TITLE
Flipper React DevTools not working with Expo Dev Clients

### ISSUE THREAD

**Issue by CarlosBM18** [expo/expo#17897] opened 2022-06-17 12:29 UTC
### Summary

We’ve been struggling to have Flipper working with React DevTools plugin. We’ve already installed and configured the expo-community-flipper package, but it keeps saying that the plugin is not available. We don’t use Hermes and we are in the Expo SDK 45 using Dev Clients.

This message appears on the Flipper app:
<img width="921" alt="image" src="https://user-images.githubusercontent.com/30117015/174293338-275a7569-ef48-44cf-bbce-b5cfecf5edf2.png">

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Package versions

`"expo-dev-client": "~1.0.0",
"expo": "^45.0.4",
"expo-community-flipper": "^45.1.0",
    "react-native-flipper": "^0.146.1",
`

### Environment

`System: OS: macOS 12.2.1 Shell: 5.8 - /bin/zsh Binaries: Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node Yarn: 1.22.19 - /opt/homebrew/bin/yarn npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm Managers: CocoaPods: 1.11.3 - /usr/local/bin/pod SDKs: iOS SDK: Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5 IDEs: Android Studio: 2021.2 AI-212.5712.43.2112.8609683 Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild npmPackages: babel-preset-expo: ~9.1.0 => 9.1.0 expo: ^45.0.4 => 45.0.4 react: 17.0.2 => 17.0.2 react-dom: 17.0.2 => 17.0.2 react-native: 0.68.2 => 0.68.2 Expo Workflow: bare`

### Reproducible demo

Just try to create a Dev Client with `[expo-community-flipper](https://www.npmjs.com/package/expo-community-flipper)` configured and try to connect Flipper, the React DevTools plugin will be unavailable

**Comment by brentvatne** [comment] 2022-06-17 17:12
Duplicate of #17852

We're aware of this issue and are working to resolve it, sorry for the hassle!

**Closed by brentvatne** 2022-06-17 17:12 UTC
Labels: needs review, expo-dev-client

**Comment by hirbod** [comment] 2022-06-19 06:49
You can run React DevTools without any changes like so:

`yarn add -D react-devtools-core`

Then edit your App.tsx/App.js with following default settings.

```tsx
import { connectToDevTools } from "react-devtools-core";

if (__DEV__) {
  connectToDevTools({
    host: "localhost",
    port: 8097,
  });
}
```

**Comment by CarlosBM18** [comment] 2022-06-20 18:59
I already tried it but didn't work

**Comment by CarlosBM18** [comment] 2022-06-20 19:00
> You can run React DevTools without any changes like so:
> 
> `yarn add -D react-devtools-core`
> 
> Then edit your App.tsx/App.js with following default settings.
> 
> ```tsx
> import { connectToDevTools } from "react-devtools-core";
> 
> if (__DEV__) {
>   connectToDevTools({
>     host: "localhost",
>     port: 8097,
>   });
> }
> ```

I already tried it but didn't work

**Comment by hirbod** [comment] 2022-06-20 19:01
Weird, working for me. But I've only tested with iOS tbh

**Comment by todorone** [comment] 2022-06-24 05:52
> > You can run React DevTools without any changes like so:
> > `yarn add -D react-devtools-core`
> > Then edit your App.tsx/App.js with following default settings.
> > ```tsx
> > import { connectToDevTools } from "react-devtools-core";
> > 
> > if (__DEV__) {
> >   connectToDevTools({
> >     host: "localhost",
> >     port: 8097,
> >   });
> > }
> > ```
> 
> I already tried it but didn't work

Doesn't work for me too

**Comment by maxefi-blockchess** [comment] 2023-02-05 10:45
is this one fixed?

having the same issue with the latest packages: `"expo": "^47.0.13"`, `"expo-dev-client": "~2.0.1"`,     `"react-native-flipper": "^0.177.0"` and `"expo-community-flipper": "^47.0.2"`
