### ISSUE TITLE
Dependency conflict between Expo and Expo-Asset (Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45.)

### ISSUE THREAD

**Issue by cmot17** [expo/expo#22543] opened 2023-05-18 16:42 UTC
### Minimal reproducible example

https://github.com/cmot17/expotest

### Summary

When I create a new Expo app, I get the following error on app launch: 
`WARN  Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45.`

Some Googling shows previous issues where this was caused by having multiple versions of `expo-constants` installed. Upon investigation, there appears to be a version conflict:
<img width="607" alt="image" src="https://github.com/expo/expo/assets/25753364/9bae3de9-4675-41b8-8fdb-6db83d0178c0">

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/Library/Caches/fnm_multishells/23979_1684427371899/bin/node
      Yarn: 3.3.1 - ~/Library/Caches/fnm_multishells/23979_1684427371899/bin/yarn
      npm: 9.6.2 - ~/Library/Caches/fnm_multishells/23979_1684427371899/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.17
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    Expo Workflow: managed

**Comment by isik-dev** [comment] 2023-07-12 12:43
I have spent a while dealing with this issue and here's what I can say:
- There are a bunch of workarounds like this to fix your issue. They are scattered around here in this repo, just checkout both closed and open issues.
- However, the safest and optimal (I would also add, 'eventual') fix is bumping your expo to 49. [Migration Guide](https://blog.expo.dev/expo-sdk-49-c6d398cdf740)

**Comment by afj95** [comment] 2023-11-13 20:20
I faces the same issue and I couldn't find any solution from above fixes and I don't have `expo-constants` & `expo-assets` in my `package.json` but I found `expo-constants` in  `yarn.lock`

Any help ideas please ?

**Comment by vonovak** [comment] 2024-08-26 10:51
Hello and thanks for reporting,
because the issue is old and resolved in the meantime I'm going to close it.
For old setups there's [the above workaround](https://github.com/expo/expo/issues/22543#issuecomment-1570161545).
Thank you 🙂

**Closed by vonovak** 2024-08-26 10:51 UTC
Labels: Issue accepted, needs review
