### ISSUE TITLE
iOS (Testflight): This app does not have permission to show notifications

### ISSUE THREAD

**Issue by jaymastero** [expo/expo#7680] opened 2020-04-06 09:54 UTC
### Environment
Expo CLI 3.17.15 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.4
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.17.15

### Steps to Reproduce
My code for registering for push notifications:
```js
const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
        const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
        finalStatus = status;
    }
    if (finalStatus !== 'granted') {
        alert('Failed to get push token for push notification!');
        return;
    }
    let token;
    try {
        token = await Notifications.getExpoPushTokenAsync();
    } catch (err) {
        new SentryErrorHandler()
            .setPage('home')
            .setErrorType('get-expo-push-token-error')
            .setException(err)
            .capture();
    }

```

### Expected Behavior
When i run the app inside the Expo client, it works fine. 
The push notifications are being deliver to the Expo Client.

### Actual Behavior
When its deployed to the Testflight the app doesn't ask for the notifications permissions and returns this error `This app does not have permission to show notifications` 

We have updated the expo sdk from 35 to 37 but it didn't help at all..
We also tried to build the apps cleaning the certs but also no luck.

**Comment by cruzach** [comment] 2020-04-06 21:05
@jaymastero this looks like a duplicate of https://github.com/expo/expo/issues/5869

You can take a look there, but it seems like this is caused by adding the `remote-notifications` value to your app.json's `ios.infoplist. UIBackgroundModes` key

**Closed by cruzach** 2020-04-06 21:05 UTC
Labels: Needs triage
