### ISSUE TITLE
expo not working in build android apk let me know the solution Linking app from other app 

### ISSUE THREAD

**Issue by city0666** [expo/expo#9610] opened 2020-08-07 10:48 UTC
expo not working in build android apk let me know the solution Linking app from other app not working ? https://docs.expo.io/workflow/linking/#linking-from-your-app-to-other-apps

import * as Linking from 'expo-linking';

Linking.openURL('https://expo.io');

**Comment by byCedric** [comment] 2020-08-10 13:12
Hi @city0666! Thanks for your issue report, unfortunately, [I can't reproduce your issue](https://snack.expo.io/@bycedric/fda66f). Can you share an example where this is not working for you? With that, we can investigate it and help you solve your issue.

**Comment by city0666** [comment] 2020-08-15 08:28
Am directing the google map in linking, when am taking the build its doesn't  work only issue in google map other urls are working

**Comment by cruzach** [comment] 2020-11-05 21:57
hi @city0666, without a reproducible demo, there's not much we can do to investigate or help here. I'm going to close this issue for now, but if you can provide a [Snack](https://snack.expo.io/) that has all the code we need to reproduce the issue, I'm happy to reopen it

**Closed by cruzach** 2020-11-05 21:57 UTC
Labels: Android, Linking, Requesting changes to issue
