### ISSUE TITLE
iOS Push Notification problems: "APNS token has not been set" on second run. SDK v31

### ISSUE THREAD

**Issue by miklschmidt** [expo/expo#2906] opened 2018-12-04 16:39 UTC
### Environment

```
  Expo CLI 2.6.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.6.0
```

iOS 12, ejected ExpoKit app. Tested on iPhone 6S, 6 Plus, 7 Plus and XR.
### Steps to Reproduce
I apologize that this is a bit tedious to reproduce, mostly because you need to setup all the necessary push notification certificates and provisioning profiles with Apple for your associated bundle id. [Here's a guide](https://reactorapps.io/blog/ios-certificate-guide/). Once that is done, these are the necessary steps to reproduce it.

1) initialize a new project with `expo init`, then run `expo eject` and choose the expokit option. Enter your bundle id that you used when configuring push notifications with Apple.

2) Run the usual `pod update && pod install`.

3) Replace app.js with the following: 
```js
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

import { Permissions, Notifications } from 'expo';

async function registerForPushNotificationsAsync() {
	const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);
	let finalStatus = existingStatus;

	// only ask if permissions have not already been determined, because
	// iOS won't necessarily prompt the user a second time.
	if (existingStatus !== 'granted') {
		// Android remote notification permissions are granted during the app
		// install, so this will only ask on iOS
		const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
		finalStatus = status;
	}

	// Stop here if the user did not grant permissions
	if (finalStatus !== 'granted') {
		return;
	}

	// Get the token that uniquely identifies this device
	let token = await Notifications.getDevicePushTokenAsync();
	return token;
}

export default class App extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			token: { status: 'no token' },
		};
	}

	componentDidMount() {
		this.getToken();
	}

	async getToken() {
		const token = await registerForPushNotificationsAsync();
		this.setState({ token });
	}

	render() {
		return (
			<View style={styles.container}>
				<Text>Token: {JSON.stringify(this.state.token)}</Text>
			</View>
		);
	}
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#fff',
		alignItems: 'center',
		justifyContent: 'center',
	},
});
```

4) Open the xcode workspace, enable push notifications under entitlements, uncheck `Debug executable` in `product > scheme` and run the project on an iOS device.

5) Give push notification permissions when asked, and verify that your token is printed on the screen.

6) Close the app (don't just background it, you need to actually close it).

7) Reopen the app, and notice the warning: `APNS token has not been set`, even though status is `granted`. Notifications are not received within the app at this point. They still work if the app is backgrounded or closed.

### Expected Behavior
Token is returned from `registerForPushNotificationsAsync` on subsequent runs.

### Actual Behavior
Unhandled Promise Rejection: Error: APNS token has not been set. No token is returned.

### Reproducible Demo

See reproduction steps.

**Comment by miklschmidt** [comment] 2018-12-05 10:33
Additional information: The same code works perfectly fine if not ejected and built with expo build:ios.

**Comment by ide** [comment] 2018-12-11 21:13
I suspect that what's happening is the app is taking an unsupported code path when trying to register for remote notifications and there isn't a simple workaround. In your native (Obj-C) logs do you see "Expo Remote Notification services won't work in an ExpoKit app because Expo cannot manage your APNS certificates."?

**Comment by mseijas** [comment] 2018-12-12 15:49
I'm running into the same issue as well. I'm not seeing the "Expo Remote Notification services won't work in an ExpoKit app because Expo cannot manage your APNS certificates." message in my logs though. Any ideas what might be going on?

**Comment by miklschmidt** [comment] 2018-12-14 13:12
I can't get anything token related working in my test app right now, not sure what happened exactly but the permissions never get set correctly even after removing and reinstalling the app. I will keep trying whenever i have time and get back to you. I do not recall seeing any errors in the console though.

**Comment by gutosanches** [comment] 2019-02-13 18:49
@miklschmidt I'm going through this same issue right now, did you figure it out?

**Comment by gutosanches** [comment] 2019-02-14 03:38
If anyone else falls here with this same issue, I was able to get tokens using react-native's own [`PushNotificationIOS.addEventListener('register', handler)`](https://facebook.github.io/react-native/docs/pushnotificationios#addeventlistener).

**Comment by miklschmidt** [comment] 2019-02-14 09:40
@gutosanches i ended up rewriting everything depending on modules with native code, and then not ejecting at all. Should've thought about just using react-native's own API's, lol.

**Comment by llamaluvr** [comment] 2019-02-21 17:54
@ide I can confirm I'm getting the "Expo Remote Notification services won't work in an ExpoKit app because Expo cannot manage your APNS certificates." (or at least I'm hitting that in the debugger- didn't bother looking at the logs after that).
I just noticed our Expo(Kit) 31 app hasn't been receiving push notifications for a while, and traced this back to this commit: https://github.com/expo/expo/commit/7100de8c2de1aab0f470c63b0b05fbef1659ff82#diff-ea0f6f7704f4806da65e2fc03077a0e3.

Basically, because it's an ExpoKit app, the Expo code that runs in `application:didFinishLaunchingWithOptions:` isn't calling `UIApplication.registerForRemoteNotifications`, and, in turn, `application:didRegisterForRemoteNotificationsWithDeviceToken:` isn't getting the device push notification token.

The error message can be a bit of a head-scratcher for an ExpoKit user, because there's reasons to register push notifications other than we want to use Expo's push notification service. The comments with that change do indicate more of a showstopper reason- the code can't guarantee that the ExpoKit app has push notification entitlements, and requesting the token without them would cause a crash. Wondering if it'd be possible to have a Info.plist flag to enable Expo push token registration in Expo, kind of like the FCM_ENABLED flag on the Android side that allows us to use the existing Expo configuration for FCM. It was pretty nice that we could still lean push notification setup code already in Expo, and just change which token we used `Expo.Notifications.getDevicePushTokenAsync()`.

Since it seems like it's just this one missing connection, I'm wondering if another workaround would be to call `dispatch_async(dispatch_get_main_queue(), ^{
       [RCTSharedApplication() registerForRemoteNotifications];
     });` directly in `application:didFinishLaunchingWithOptions:` after all of the Expo bootstrapping.

**Comment by jacobsmith** [comment] 2019-03-02 02:39
For anyone else who stumbles here from google, I was able to get the actual APNS token by adding `[application registerForRemoteNotifications]` to my AppDelegate.m

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    [application registerForRemoteNotifications];
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
```
(Of note, I do *not* have the code that PushNotificationIOS tells you to add to the AppDelegate.m - I was having conflicts with ExpoKit and AppDelegate.m both trying to declare handlers for notifications.

then in my JS code, I can call:

```
    Notifications.getDevicePushTokenAsync().then(success => this.setState({ text: `Expo: ${JSON.stringify(success)}`}))
```

that returns `{ "type": "apns", "data": "<32 byte apns token>" }`


I'm then able to handle notifications with:

`    Notifications.addListener(this._handleNotification)`

And, additionally, the notification sent to APNS has to be of a certain form because ExpoKit does some validation of the notification. I believe this is a private API, so things may change in the future, but it is necessary for now:

```
{
  "experienceId": <expo bundle identifier - eg, @username/project>,
  "body": {
    <whatever data you want to pass, params for your client app, etc.>
  }
}
```

I'm using the RPush gem and the `alert` key of the notification object is the actual text displayed - I'm not sure what that corresponds to in "pure" APNS, but hopefully this helps someone along the way.

Sorry if this is a bit garbled, it's the result of about 20 hours fighting with APNS and ExpoKit in a detached Expo app (:

**Comment by jeremybdk** [comment] 2019-05-07 20:02
This behaviour is also present on SDK v32 with latest ExpoKit, I am running into the same issue

**Comment by AaronBedward** [comment] 2019-11-30 12:56
Just a quick note for the IOS devs - if you can't get the device token don't forget to add the capability in XCODE

**Comment by giautm** [comment] 2020-01-15 09:01
@AaronBedward : Thank you, I just ran into same issue that `Permissions.askAsync(Permissions.NOTIFICATIONS)` always return `undetermined` status. Solved with add Capability:

<img width="811" alt="Screen Shot 2020-01-15 at 16 00 01" src="https://user-images.githubusercontent.com/12751435/72419904-4a631280-37b0-11ea-9679-1a56d5a59309.png">

**Comment by tsapeta** [comment] 2020-06-30 12:45
Looks like the workaround has been found, so I'm closing this issue as ExpoKit is also no longer supported. Recently we've rewritten Notifications API from scratch so you can give them a try if you're still hitting this.

**Closed by tsapeta** 2020-06-30 12:45 UTC
Labels: Notifications, iOS, project: expokit
