### ISSUE TITLE
[SDK 50] react-native-maps config plugin issue

### ISSUE THREAD

**Issue by medyahyejoud** [expo/expo#26539] opened 2024-01-19 23:11 UTC
### Minimal reproducible example

https://github.com/medyahyejoud/expo-50-test

### Summary

Hey guys,

After upgrading our app expo SDK 50, we started getting a new error when we try to build the application.
Before upgrading we didn't have any problems, the app builds fine for both iOS and Android, on EAS servers and locally.

I tried to debug myself and narrow down where the issue might be, and I think it is related to `expo/config-plugins`, we have two custom plugins to solve some issues we had:

- One is for react-native-maps on iOS when using GOOGLE_PROVIDER, from [this issue](https://github.com/react-native-maps/react-native-maps/issues/4502#issuecomment-1304599405), [here is the file](https://github.com/medyahyejoud/expo-50-test/blob/3de3ea61bf108d350500acc9b1237486c6beba72/bin/react-native-maps-plugin.js)
- The other one is related to an issue where iOS simulator not builds locally in M1 ARM chips, [here is the file](https://github.com/medyahyejoud/expo-50-test/blob/3de3ea61bf108d350500acc9b1237486c6beba72/bin/react-apple-ios-simulator-not-found-plugin.js).

The build process crashes during the Prebuild phase (on EAS and locally) with this error:

```bash
✖ Prebuild failed
Error: [ios.dangerous]: withIosDangerousBaseMod: Failed to match "/\s*__apply_Xcode_12_5_M1_post_install_workaround\(installer\)/i" in contents:
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}
ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
platform :ios, podfile_properties['ios.deploymentTarget'] || '13.4'
install! 'cocoapods',
  :deterministic_uuids => false
prepare_react_native_project!
# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...), which will be excluded. To fix this,
# you can also exclude `react-native-flipper` in `react-native.config.js`
#
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
#   }
# }
# ```
flipper_config = FlipperConfiguration.disabled
if ENV['NO_FLIPPER'] == '1' then
  # Explicitly disabled through environment variables
  flipper_config = FlipperConfiguration.disabled
elsif podfile_properties.key?('ios.flipper') then
  # Configure Flipper in Podfile.properties.json
  if podfile_properties['ios.flipper'] == 'true' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"])
  elsif podfile_properties['ios.flipper'] != 'false' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"], { 'Flipper' => podfile_properties['ios.flipper'] })
  end
end
target 'expo50test' do
  use_expo_modules!
# @generated begin react-native-maps - expo prebuild (DO NOT MODIFY) sync-e9cc66c360abe50bc66d89fffb3c55b034d7d369
  pod 'react-native-google-maps', path: File.dirname(`node --print "require.resolve('react-native-maps/package.json')"`)
# @generated end react-native-maps
  config = use_native_modules!
  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Note that if you have use_frameworks! enabled, Flipper will not work if enabled
    :flipper_configuration => flipper_config
  )
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end
Error: [ios.dangerous]: withIosDangerousBaseMod: Failed to match "/\s*__apply_Xcode_12_5_M1_post_install_workaround\(installer\)/i" in contents:
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}
ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
platform :ios, podfile_properties['ios.deploymentTarget'] || '13.4'
install! 'cocoapods',
  :deterministic_uuids => false
prepare_react_native_project!
# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...), which will be excluded. To fix this,
# you can also exclude `react-native-flipper` in `react-native.config.js`
#
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
#   }
# }
# ```
flipper_config = FlipperConfiguration.disabled
if ENV['NO_FLIPPER'] == '1' then
  # Explicitly disabled through environment variables
  flipper_config = FlipperConfiguration.disabled
elsif podfile_properties.key?('ios.flipper') then
  # Configure Flipper in Podfile.properties.json
  if podfile_properties['ios.flipper'] == 'true' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"])
  elsif podfile_properties['ios.flipper'] != 'false' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"], { 'Flipper' => podfile_properties['ios.flipper'] })
  end
end
target 'expo50test' do
  use_expo_modules!
# @generated begin react-native-maps - expo prebuild (DO NOT MODIFY) sync-e9cc66c360abe50bc66d89fffb3c55b034d7d369
  pod 'react-native-google-maps', path: File.dirname(`node --print "require.resolve('react-native-maps/package.json')"`)
# @generated end react-native-maps
  config = use_native_modules!
  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Note that if you have use_frameworks! enabled, Flipper will not work if enabled
    :flipper_configuration => flipper_config
  )
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end
    at addLines (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/utils/generateCode.js:85:19)
    at Object.mergeContents (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/utils/generateCode.js:58:17)
    at /Users/expo/workingdir/build/bin/react-apple-ios-simulator-not-found-plugin.js:25:36
    at action (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:201:29)
    at interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:27)
    at action (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:206:14)
    at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins
npx expo prebuild --no-install --platform ios exited with non-zero code: 1
```

When I remove this plugin from `app.config.ts` plugins list `./bin/react-native-maps-plugin`, the prebuild phase passes but this error gets thrown later in the build:

```bash
❌  (/Users/expo/workingdir/build/ios/build/Build/Products/Debug-iphonesimulator/Google-Maps-iOS-Utils/GoogleMapsUtils.framework/Headers/GoogleMapsUtils-Swift.h:327:2)

  325 | 
  326 | #else
> 327 | #error unsupported Swift architecture
      |  ^ unsupported Swift architecture
  328 | #endif
  329 |

❌  (node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.h:7:9)

   5 | //
   6 | 
>  7 | #import "GMUHeatmapTileLayer.h"
     |         ^ could not build module 'GoogleMapsUtils'
   8 | 
   9 | @interface AIRGoogleMapHeatmap : UIView
  10 | 

› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapHeatmap.m

› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapCircleManager.m

› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapCircle.m

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » SelletyDev/SelletyDev » Build Phases » '[CP-User] [RNFB] Core Configuration'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » SelletyDev/SelletyDev » Build Phases » '[CP-User] [RNFB] Crashlytics Configuration'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » Pods/abseil » Build Phases » 'Create Symlinks to Header Folders'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

▸ ** BUILD FAILED **

▸ The following build commands failed:

▸ 	CompileC /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmapManager.o /Users/expo/workingdir/build/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmapManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-google-maps' from project 'Pods')

▸ (1 failure)

** BUILD FAILED **

The following build commands failed:

	CompileC /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmapManager.o /Users/expo/workingdir/build/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmapManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-google-maps' from project 'Pods')

(1 failure)

Exit status: 65
```

When I remove this plugin from `app.config.ts` plugins list `./bin/react-apple-ios-simulator-not-found-plugin`, the prebuild phase passes but this error gets thrown later in the build:

```bash
❌  (ios/Pods/Target Support Files/Pods-expo50test/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/medyahyejoud/Library/Developer/Xcode/DerivedData/expo50test-ctzzjhfgxkxlukcknfpwebycpogd/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule
   9 | import EXConstants
  10 | import ExpoFileSystem
  11 | import ExpoKeepAwake


❌  (ios/Pods/Target Support Files/Pods-expo50test/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/medyahyejoud/Library/Developer/Xcode/DerivedData/expo50test-ctzzjhfgxkxlukcknfpwebycpogd/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule
   9 | import EXConstants
  10 | import ExpoFileSystem
  11 | import ExpoKeepAwake


› 2 error(s), and 0 warning(s)

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.
```

Its important to note, that previously with SDK 49, we had this resolution to silence expo-doctor:

```json
"resolutions": {
  "@expo/config-plugins": "~7.2.2"
},
```
After upgrading to SDK 50, we removed it because it started to error out in expo-doctor.

Thanks 🙏 

### Environment

```
expo-env-info 1.2.0 environment info:

System:
  OS: macOS 14.2.1
  Shell: 3.5.1 - /opt/homebrew/bin/fish
Binaries:
  Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
  Yarn: 1.22.19 - ~/.yarn/bin/yarn
  npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Watchman: 2023.01.09.00 - /opt/homebrew/bin/watchman
Managers:
  CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode: 15.2/15C500b - /usr/bin/xcodebuild
npmPackages:
  expo: ^50.0.2 => 50.0.2 
  react: 18.2.0 => 18.2.0 
  react-dom: 18.2.0 => 18.2.0 
  react-native: 0.73.2 => 0.73.2 
npmGlobalPackages:
  eas-cli: 6.1.0
  expo-cli: 6.3.10
Expo Workflow: managed
```

**Comment by medyahyejoud** [comment] 2024-01-20 00:50
I think the issue is somewhat related to: 

```json
[
  "expo-build-properties",
  {
    ios: {
      useFrameworks: "static",
    },
  },
],
```
But it is required for react-native-firebase.

**Comment by boblitex** [comment] 2024-01-22 00:17
just commenting cos I have this exact issue at the moment, tried creating an issue but the expo bot is relentless, I'd love to follow along for the resolution

**Comment by keith-kurak** [comment] 2024-01-23 19:42
Hi!

So, the most proximate cause of why this is failing is because the parts inside the default Podfile that the config plugin is trying to find with its regexes are no longer there as of SDK 50. You can see from the [diff](https://docs.expo.dev/bare/upgrade/?fromSdk=49&toSdk=50#iospodfile) that most of the changes to the Podfile from SDK 49 to 50 happen to be the very parts that would require this plugin to work 😅 .

Anyway, I was able to get your reproduction to build by making the following changes to the config plugins, basically finding a new bit of text to anchor onto in order to get these additions into roughly the same place.

**react-native-maps-plugin.js**
```diff
      const newCode = generateCode.mergeContents({
        tag: "withReactNativeMaps",
        src: contents,
        newSrc: code,
-        anchor: /\s*get_default_flags\(\)/i,
-        offset: 2,
+        anchor: /\s*use_react_native!\(/i,
+        offset: -1,
        comment: "#",
      });
```

**react-apple-ios-simulator-not-found-plugin.js**
```diff
    const addCode = generateCode.mergeContents({
        tag: "withReactAppleIosSimulatorNotFoundFix",
        src: contents,
        newSrc: code,
-      anchor:
-       /\s*__apply_Xcode_12_5_M1_post_install_workaround\(installer\)/i,
-        offset: 1,
+       anchor:
+          /\s*installer.target_installation_results.pod_target_installation_results/i,
+      offset: -2,
        comment: "#",
      });
```

This should get you going for now, though it's probably something you'll want to check on future SDK upgrades. I'm accepting the issue so we can look at what we can do between the documentation and the built-in handling of the maps configuration to make this a better experience, since it seems like most anyone trying to integrate the Google provider into iOS would need to add this when following our MapView doc.

The context behind **react-native-maps-plugin.js** makes sense to me; if you have any additional information about the history behind **react-apple-ios-simulator-not-found-plugin.js** (e.g., a link to an issue introducing the workaround), that'd be much appreciated!

**Comment by medyahyejoud** [comment] 2024-01-23 21:15
Hello @keith-kurak,

I appreciate the detailed response. At the moment, we've downgraded to SDK 49 until we can ensure there is no issue.

Regarding the `react-native-maps-plugin`, it was surprising to me that it isn't mentioned in the Expo docs, considering it seems to be a common issue for the Google provider on iOS. If there's anything I can help with in terms of documentation, or perhaps the plugin should be included with the package, I'd be happy to contribute.

As for `react-apple-ios-simulator-not-found-plugin`, I found the solution in this [issue](https://github.com/expo/expo/issues/15800#issuecomment-1537149496). This is the error that gets thrown when removing the plugin, as already mentioned in the issue:

```bash
❌  (ios/Pods/Target Support Files/Pods-expo50test/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/medyahyejoud/Library/Developer/Xcode/DerivedData/expo50test-ctzzjhfgxkxlukcknfpwebycpogd/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule
   9 | import EXConstants
  10 | import ExpoFileSystem
  11 | import ExpoKeepAwake


❌  (ios/Pods/Target Support Files/Pods-expo50test/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/medyahyejoud/Library/Developer/Xcode/DerivedData/expo50test-ctzzjhfgxkxlukcknfpwebycpogd/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule
   9 | import EXConstants
  10 | import ExpoFileSystem
  11 | import ExpoKeepAwake


› 2 error(s), and 0 warning(s)

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.
```

Thanks a bunch!

**Comment by flexbox** [comment] 2024-01-25 17:00
👋 Hey there

I can finally dig back into building issues, last time was with SDK 46 😂 
https://github.com/react-native-maps/react-native-maps/issues/4502

thank you @keith-kurak for your answer, i will give you an update when my build will be successful with 
```
"expo": "^50.0.3",
"react-native-maps": "1.8.0",
```

**Comment by jens1101** [comment] 2024-01-29 06:42
Good day. I am also experiencing the same "unsupported Swift architecture" error when building locally on a M1 Mac. `react-native-maps` [v1.8.2 updated it's GoogleMapsUtils dependency](https://github.com/react-native-maps/react-native-maps/releases/tag/v1.8.2). When I manually update `react-native-maps` then local builds work just fine, however expo-doctor complains about the version mismatch. Could the recommended version be bumped to 1.8.2 to fix this specific issue?

**Comment by flexbox** [comment] 2024-02-01 09:20
Hello @medyahyejoud 

I successfully build my app with these dependencies 
```
"@expo/config-plugins": "~7.8.0",
"expo": "^50.0.3",
"react-native-maps": "1.10.0",
```

I was importing a custom `react-native-maps-plugin` on my `app.config.ts`, but you don't need it anymore.

![CleanShot 2024-02-01 at 10 18 39](https://github.com/expo/expo/assets/360936/6a147b91-5d1c-49bf-ac48-505168fc78e2)

Can you double check and let us know if your problem is solved

If yes you can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by medyahyejoud** [comment] 2024-02-01 13:18
Hello @flexbox,

"I'll attempt the upgrade, but it might require some time. We're anticipating a major update, and at the moment, we can't afford to upgrade all dependencies. It appears that @jens1101 is encountering a similar problem with the 'unsupported Swift architecture.' Perhaps this is a compelling reason to investigate the issue."

**Comment by medyahyejoud** [comment] 2024-02-01 13:19
Helo @flexbox,

I'll attempt the upgrade, but it might require some time. We're anticipating a major update, and at the moment, we can't afford to upgrade all dependencies. It appears that @jens1101 is encountering a similar problem with the 'unsupported Swift architecture.' Perhaps this is a compelling reason to investigate the issue.

**Comment by kpamidov** [comment] 2024-02-01 22:44
I got this error "AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS." when try to use <MapView provider={PROVIDER_GOOGLE}

here is my dependencies in package.json

```
"dependencies": {
    "@hookform/resolvers": "^3.3.4",
    "@kanzitelli/if-component": "^0.3.0",
    "@mindinventory/react-native-tab-bar-interaction": "^2.2.3",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/datetimepicker": "7.2.0",
    "@react-native-community/blur": "^4.3.2",
    "@react-native-community/netinfo": "9.3.10",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.14",
    "@react-navigation/stack": "^6.3.20",
    "@tanstack/react-query": "^4.35.7",
    "axios": "^1.5.1",
    "babel-plugin-inline-import": "^3.0.0",
    "eslint-config-prettier": "^9.0.0",
    "expo": "^49.0.13",
    "expo-blur": "~12.4.1",
    "expo-build-properties": "^0.8.3",
    "expo-dev-client": "~2.4.12",
    "expo-haptics": "~12.4.0",
    "expo-linking": "~5.0.2",
    "expo-location": "~16.1.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-updates": "~0.18.19",
    "i18n-js": "4.2.0",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "lottie-react-native": "5.1.6",
    "mobx": "^6.10.2",
    "mobx-persist-store": "^1.1.3",
    "mobx-react": "^9.0.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.6",
    "react-native-confirmation-code-field": "^7.3.2",
    "react-native-dotenv": "^3.4.9",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-maps": "^1.10.0",
    "react-native-maps-directions": "^1.9.0",
    "react-native-mmkv": "^2.10.2",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^17.1.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-root-toast": "^3.5.1",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-svg": "13.9.0",
    "react-native-svg-transformer": "^1.1.0",
    "react-native-ui-lib": "^7.12.0",
    "react-native-vector-icons": "^10.0.2",
    "react-native-webview": "13.2.2",
    "rn-bounceable": "^1.2.0",
    "rn-swipe-button": "^1.3.8",
    "yup": "^1.3.2"
  },
```

I also use expo managed workflow. Can you please help me how to resolve it, because I searched almost every thread for this problem but didn't found a solution

**Comment by GoldMyr1994** [comment] 2024-02-02 21:09
Hello,
following suggestion of @flexbox I was able to make a build! 
<img width="1134" alt="Screenshot 2024-02-02 alle 23 02 49" src="https://github.com/expo/expo/assets/7756919/e8f016a0-b18e-4ee5-b072-3be4d30cb7da">

I removed custom plugin.
<img width="342" alt="Screenshot 2024-02-02 alle 23 05 52" src="https://github.com/expo/expo/assets/7756919/f5fdab00-0510-4de0-ad81-c927345e6718">

```
"@expo/config-plugins": "~7.8.0",
"expo": "~50.0.5",
"react-native-maps": "1.10.0",
```

Also able to reach the map on iOS!
<img width="332" alt="Screenshot 2024-02-02 alle 23 03 01" src="https://github.com/expo/expo/assets/7756919/2e1ef062-8e73-4e75-a681-030996d9e36f">

**Comment by zell180** [comment] 2024-02-05 11:01
Using it with firebase give me this problem

`✔ Cleared android, ios code
✔ Created native projects | gitignore already synced
⚠️  Skipped Metro config updates:
› Existing Metro config found; not overwriting.
› You will need to extend the default @expo/metro-config in your Metro config.
  Learn more: https://docs.expo.dev/guides/customizing-metro

✔ Updated package.json and added index.js entry point for iOS and Android
📦 Using npm to install packages.
✔ Cleaned JavaScript dependencies 2688ms
✔ Installed JavaScript dependencies 5633ms
✖ Config sync failed
[ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate.
Error: [ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate.
    at /usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Maps.ts:199:19
    at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:29)
    at interceptingMod (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:27)
    at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:27)
    at interceptingMod (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at evalModsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:172:25)
    at compileModsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:82:10)
    at configureManagedProjectAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:58:12)
    at prebuildAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/prebuildAppAsync.ts:88:21)
    at actionAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:37:3)`

How to fix?

**Comment by jens1101** [comment] 2024-02-06 08:48
I was also able to get iOS simulator builds working with the latest Expo.

**Comment by zell180** [comment] 2024-02-06 08:56
> Using it with firebase give me this problem
> 
> `✔ Cleared android, ios code ✔ Created native projects | gitignore already synced ⚠️ Skipped Metro config updates: › Existing Metro config found; not overwriting. › You will need to extend the default @expo/metro-config in your Metro config. Learn more: https://docs.expo.dev/guides/customizing-metro
> 
> ✔ Updated package.json and added index.js entry point for iOS and Android 📦 Using npm to install packages. ✔ Cleaned JavaScript dependencies 2688ms ✔ Installed JavaScript dependencies 5633ms ✖ Config sync failed [ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate. Error: [ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate. at /usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Maps.ts:199:19 at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:29) at interceptingMod (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:27) at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:27) at interceptingMod (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21) at evalModsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:172:25) at compileModsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:82:10) at configureManagedProjectAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:58:12) at prebuildAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/prebuildAppAsync.ts:88:21) at actionAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:37:3)`
> 
> How to fix?

Find the error: need to install expo-cli local (like new doc)

**Comment by djnewage** [comment] 2024-02-09 02:23
i am encountering the same error

 ERROR  react-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS. 
  "expo": "^50.0.0",
  "react-native-maps": "1.10.0"

**Comment by IronBlossom** [comment] 2024-03-21 16:33
Issue still persist for building locally `eas build --profile dev-ios-tar --platform ios --local --clear-cache`:
`    "@expo/config-plugins": "^7.8.4",
    "expo": "^50.0.14",
    "react-native-maps": "1.10.0",
`

...even after removing `useFramework: "static"` which was recommended from another SO thred.

**Closed** 2024-03-22 23:01 UTC
Labels: iOS, MapView, Issue accepted

**Comment by medyahyejoud** [comment] 2024-03-22 23:05
> Hi!
> 
> So, the most proximate cause of why this is failing is because the parts inside the default Podfile that the config plugin is trying to find with its regexes are no longer there as of SDK 50. You can see from the [diff](https://docs.expo.dev/bare/upgrade/?fromSdk=49&toSdk=50#iospodfile) that most of the changes to the Podfile from SDK 49 to 50 happen to be the very parts that would require this plugin to work 😅 .
> 
> Anyway, I was able to get your reproduction to build by making the following changes to the config plugins, basically finding a new bit of text to anchor onto in order to get these additions into roughly the same place.
> 
> **react-native-maps-plugin.js**
> 
> ```diff
>       const newCode = generateCode.mergeContents({
>         tag: "withReactNativeMaps",
>         src: contents,
>         newSrc: code,
> -        anchor: /\s*get_default_flags\(\)/i,
> -        offset: 2,
> +        anchor: /\s*use_react_native!\(/i,
> +        offset: -1,
>         comment: "#",
>       });
> ```
> 
> **react-apple-ios-simulator-not-found-plugin.js**
> 
> ```diff
>     const addCode = generateCode.mergeContents({
>         tag: "withReactAppleIosSimulatorNotFoundFix",
>         src: contents,
>         newSrc: code,
> -      anchor:
> -       /\s*__apply_Xcode_12_5_M1_post_install_workaround\(installer\)/i,
> -        offset: 1,
> +       anchor:
> +          /\s*installer.target_installation_results.pod_target_installation_results/i,
> +      offset: -2,
>         comment: "#",
>       });
> ```
> 
> This should get you going for now, though it's probably something you'll want to check on future SDK upgrades. I'm accepting the issue so we can look at what we can do between the documentation and the built-in handling of the maps configuration to make this a better experience, since it seems like most anyone trying to integrate the Google provider into iOS would need to add this when following our MapView doc.
> 
> The context behind **react-native-maps-plugin.js** makes sense to me; if you have any additional information about the history behind **react-apple-ios-simulator-not-found-plugin.js** (e.g., a link to an issue introducing the workaround), that'd be much appreciated!

Thanks @keith-kurak, I've finished upgrading today and everything works great. Much appreciated.
