### ISSUE TITLE
How to create responsive website?

### ISSUE THREAD

**Issue by ggunti** [expo/expo#7489] opened 2020-03-26 20:47 UTC
Now expo supports also web (using ‘react-native-web’), but how it is possible to make the web version responsive? There exist a package similar to bootstrap for ‘react-native-web’ which allows to easily create responsive website?

I was informed about [media queries](https://blog.expo.io/media-queries-with-react-native-for-ios-android-and-web-e0b73ed5777b), but I think it's enough hard to use them (you have to write lot of additional code), it would be much nicer to have a bootstrap-like grid system which would have effect only on web version. Such way could be possible to easily build iOS & android apps + RESPONSIVE website.

I am interested to see other persons opinion about this idea. I also would be interested to create such a library if you think it sounds a good idea (and if not exist such a library yet).

**Comment by cruzach** [comment] 2020-03-27 19:54
Since this is a question and not a bug report, I'm going to close this issue. Thanks for [posting on the forums](https://forums.expo.io/t/how-to-create-responsive-website/34796/2) already! 

In terms of minimal-effort responsive design, I second that Flexbox sounds like the best/easiest solution

**Closed by cruzach** 2020-03-27 19:54 UTC
