### ISSUE TITLE
I work on two Expo projects. I published one, and it somehow published to both.

### ISSUE THREAD

**Issue by zholmes1** [expo/expo#9521] opened 2020-08-01 03:27 UTC
I'm not looking to blame anyone here, I'm looking for some guidance as to why this might have happened. I was working this morning on Project #1 and published a new release. Later in the day, I received reports that Project #2 was displaying a totally different app. I have no idea how this possibly could have happened. I use `expo publish` from the root directory of my expo project, so why would a publish from Project #1 deploy OTA updates to Project #2?

I really just want to know why this happened so I can avoid it in the future.

**Comment by cruzach** [comment] 2020-08-03 13:43
Publishes are related to your app by the project identifier: `@yourExpoUsername/yourProjectSlug`, so the only way that this could happen is if you have the same project identifier for each one. Providing your app.json files might help illuminate what happened

@zholmes1 happy to help try and figure out what happened here, but since it's not a bug with the Expo SDK I'm going to close the issue for now

**Closed by cruzach** 2020-08-03 13:43 UTC
