### ISSUE TITLE
[iOS] Internal distribution: app is not installing

### ISSUE THREAD

**Issue by mwegener-com** [expo/expo#15501] opened 2021-12-10 15:04 UTC
### Summary

I followed the instructions on Internal distribution - Expo Documentation to set up an ad hoc installation on my iPhone.

I tried eas device:create with both options:
1. manually entering the UUID
2. downloading and installing the profile to register the device.

Both options seemed to work fine.
Also eas build --profile preview --platform all worked fine.

When I click on install on my iOS build with my phone, I get the message "Go to your home screen to check the installation process". The problem is that there is nothing on my home screen. The application is not being installed.

Do I need to have a specific profile installed for this to work?
I would guess that I need the “Apple Provisioning Profile” created in Expo Dev.
When I download this profile to my iPhone and open the file, my phone directs me to the “profile page” in the phone settings, but then there is nothing to install.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.0.1 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 7.0.3 - /usr/local/bin/npm
      Watchman: 2021.12.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 29.0.2, 30.0.0, 32.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.4 => 43.0.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

### Reproducible demo

See above.

**Comment by mwegener-com** [comment] 2021-12-10 21:27
Thanks @brentvatne. Where else should I ask for help?

**Comment by brentvatne** [comment] 2021-12-10 21:30
when you run `eas device:create` you will see this

<img width="983" alt="Screen Shot 2021-12-10 at 1 28 07 PM" src="https://user-images.githubusercontent.com/90494/145643626-98e25708-a041-4f0c-90d9-41b19b8610c6.png">

when you scan the qr code you will see this:

![IMG_0960](https://user-images.githubusercontent.com/90494/145643690-68b0857e-c3ae-44b0-a110-86d37c59291c.jpeg)

follow those instructions.

> Thanks @brentvatne. Where else should I ask for help?

https://forums.expo.dev. remember that issues are for bugs whereas your question seems to be more oriented around how to use the tool

**Comment by mwegener-com** [comment] 2021-12-10 21:36
@brentvatne I think it is a bug. 
I did all these steps. 
 
When I run `eas build --profile preview --platform all`, the correct phone with the correct UUID is listed.

After the build finishes successfully, I scan the "app-install-qr" with my phone. My phone recognizes the QR code but nothing happens if I tap on the action "open in iTunes". (See video) 

I've already tried to delete all profiles and certificates, generate new ones and register my phone again. 
Same problem.. also with a different iPhone on a different iOS version.


https://user-images.githubusercontent.com/64470126/145644167-c63983ed-bf95-4ca7-81dd-c07e905b6408.mov

**Comment by brentvatne** [comment] 2021-12-10 22:11
it is necessary to have the certificate installed on your device, it is not just for registering the uuid (although that is part of it). i just walked through this and i'm seeing a similar behavior, which is certainly not expected. i wonder if something changed in the latest ios release and if others can repro, i'll re-open issue to investigate

**Comment by brentvatne** [comment] 2021-12-10 22:23
when you run `eas build` do you see your device udid on this list?

<img width="921" alt="Screen Shot 2021-12-10 at 2 23 51 PM" src="https://user-images.githubusercontent.com/90494/145648933-3afe537f-caf7-4789-b03e-972bb7da3972.png">

**Comment by mwegener-com** [comment] 2021-12-10 22:48
> when you run `eas build` do you see your device udid on this list?
> 
> <img alt="Screen Shot 2021-12-10 at 2 23 51 PM" width="921" src="https://user-images.githubusercontent.com/90494/145648933-3afe537f-caf7-4789-b03e-972bb7da3972.png">

Yes, it's on the list. 
But, but I don't know if the device UUID's are fetched from apple or eas Server. I think my UUID was already send to apple during Xcode Setup

**Comment by brentvatne** [comment] 2021-12-10 23:00
i was mistaken and the purpose of installing the profile is just to extract your udid.

if you see your udid listed there and then build with a provisioning profile that uses those udids, then you should be able to install on your device

**Comment by brentvatne** [comment] 2021-12-10 23:03
can you verify that your device is registered on the apple developer portal? https://developer.apple.com/account/resources/devices/list

**Comment by mwegener-com** [comment] 2021-12-10 23:05
Yes it is there.

<img width="1321" alt="Bildschirmfoto 2021-12-11 um 00 04 12" src="https://user-images.githubusercontent.com/64470126/145652115-c39a56b9-3fd2-4625-a37e-c60893fd832e.png">
<img width="1269" alt="Bildschirmfoto 2021-12-11 um 00 04 23" src="https://user-images.githubusercontent.com/64470126/145652117-a1cbed45-080b-4eef-859d-5d74b30d4435.png">
<img width="1211" alt="Bildschirmfoto 2021-12-11 um 00 05 17" src="https://user-images.githubusercontent.com/64470126/145652155-46239ac9-2fa1-4670-a9e6-2e9a4fd4e3ed.png">

**Comment by quinlanj** [comment] 2021-12-10 23:11
Just to sanity check, what happens when you open the link on your phone without using the QR Code, and press install? With either flow, ideally, you should see something like this:
![IMG_7497](https://user-images.githubusercontent.com/6380927/145652473-5198327e-d124-499d-a7df-5edb0d13561d.PNG)

**Comment by mwegener-com** [comment] 2021-12-10 23:12
I don't get the Alert, just the modal on the bottom.

**Comment by mwegener-com** [comment] 2021-12-10 23:18
https://user-images.githubusercontent.com/64470126/145652954-5c71181d-a854-49bb-ac0a-7cf8c60e4d4e.MOV

**Comment by brentvatne** [comment] 2021-12-10 23:38
@mwegener-com - can you verify in itunes that your udid is correct? ([this is how you can find it](https://stackoverflow.com/a/173030

**Comment by mwegener-com** [comment] 2021-12-10 23:39
> @mwegener-com - can you verify in itunes that your udid is correct? ([this is how you can find it](https://stackoverflow.com/a/17303061/659988))

Yes, already checked

**Comment by brentvatne** [comment] 2021-12-10 23:43
can you try registering your device here? https://expo.dev/register-device/1a27a20a-9ecf-4d34-8946-266db0a4ac43

i'll do a build of an app with this udid and see if it installs on your device.

**Comment by brentvatne** [comment] 2021-12-11 00:02
the other thing that i would try - reboot your iphone.

**Comment by mwegener-com** [comment] 2021-12-11 03:02
> can you try registering your device here? https://expo.dev/register-device/1a27a20a-9ecf-4d34-8946-266db0a4ac43
> 
> 
> 
> i'll do a build of an app with this udid and see if it installs on your device.

Done.

**Comment by mwegener-com** [comment] 2021-12-11 03:02
> the other thing that i would try - reboot your iphone.

I did , a lot of times 😂

**Comment by brentvatne** [comment] 2021-12-11 05:13
> > can you try registering your device here? https://expo.dev/register-device/1a27a20a-9ecf-4d34-8946-266db0a4ac43
> > i'll do a build of an app with this udid and see if it installs on your device.
> 
> Done.

https://expo.dev/accounts/brents/projects/mwegener/builds/0a90dddb-2dca-4da8-99d8-b3a72c36bfe9

let me know if installing this works for you

**Comment by mwegener-com** [comment] 2021-12-11 12:09
Yes and no. 
I got the alert with "install", but I cannot open the app, because "the integrity could not be verified".

If you would send me your UUID, I could add you to my app and we could check the other way round.

![image](https://user-images.githubusercontent.com/64470126/145675967-5f161595-283c-4841-a2ca-57cb5f0fd3a9.png)
![image](https://user-images.githubusercontent.com/64470126/145675971-cfa98315-ec6c-44d5-ace3-4de1d0d3dd1b.png)
![image](https://user-images.githubusercontent.com/64470126/145675972-5c5ffed4-0a46-4e60-a1d8-ed0e2a566743.png)

**Comment by mwegener-com** [comment] 2021-12-11 20:37
@brentvatne I set up a completely new project (Expo managed js) and then installed only expo-dev-client. 
If I build this project with the same eas profile, I can install and run the app on my iPhone without any problems.

So the problem must be somewhere with the Cabernet & Co. App.
Do you have any idea what I can do?

App has no errors, runs fine on Android (native + simulator) and iOS (simulator).

I compare both eas logs and was able to find the following differences:

cabernet:
<img width="1172" alt="Bildschirmfoto 2021-12-11 um 21 27 55" src="https://user-images.githubusercontent.com/64470126/145690834-d8bd5357-351e-40d1-b52c-cdd6d3fc07f1.png">
new-app:
<img width="1159" alt="Bildschirmfoto 2021-12-11 um 21 28 05" src="https://user-images.githubusercontent.com/64470126/145690841-317eef45-4b02-44c5-8bfc-566c1581e83a.png">

cabernet:
<img width="1143" alt="Bildschirmfoto 2021-12-11 um 21 30 16" src="https://user-images.githubusercontent.com/64470126/145690856-11436062-4541-4786-adc6-5d2bf5c6be95.png">
new-app:
<img width="1153" alt="Bildschirmfoto 2021-12-11 um 21 30 27" src="https://user-images.githubusercontent.com/64470126/145690862-76844b3b-7d03-4caa-b478-45855eb560f0.png">

cabernet:
<img width="1159" alt="Bildschirmfoto 2021-12-11 um 21 33 34" src="https://user-images.githubusercontent.com/64470126/145690864-b327311e-d5c2-486a-888f-515a7706c136.png">
new-app:
<img width="1160" alt="Bildschirmfoto 2021-12-11 um 21 33 44" src="https://user-images.githubusercontent.com/64470126/145690868-1cc76e16-e8d1-4c5b-9364-bed4918304e6.png">

**Comment by brentvatne** [comment] 2021-12-12 04:32
> Yes and no. I got the alert with "install", but I cannot open the app, because "the integrity could not be verified".

sorry about that, i accidentally deleted the distribution cert i believe. this build would work: https://expo.dev/accounts/brents/projects/mwegener/builds/bbb732e2-23ef-4ffa-89c7-8912e6bebd14

it's hard to say without more info about the app exactly what's going on. it's not clear to me why ios is not showing the install dialog for your particular app. the idea you have here around copying over app.json and package.json seems solid, maybe you can continue copying everything from the app over and see if there is some point when it stops working? also, have you tried doing a simulator build of your app? what about testflight?

**Comment by mwegener-com** [comment] 2021-12-12 15:05
@brentvatne I don't get it.
Even if I copy all my stuff to the new app, it is still working fine.

Haven't tried TestFlight yet. Simulator is working fine.

I also tried to change the slug and name of my original app the get a new project in expo.dev, but I still wasn't able to install it on my phone.

**Comment by mwegener-com** [comment] 2021-12-12 19:27
I found the problem. 
The character "&" is not allowed as a name in the app.json 😄 

It would be great if you could add some check.. 

Thanks for your help!

**Comment by quinlanj** [comment] 2021-12-12 22:51
oh interesting 😮. that error is given by s3 if our server clock is too far off. If it caused the ipa not be uploaded, it would completely make sense that you aren't able to install the app since we never managed to save it successfully to s3!

Could you give us your build link so we can verify this hypothesis? You can email secure@expo.io the info if you'd prefer not to post it on the public issue :)

**Comment by mwegener-com** [comment] 2021-12-12 23:07
The mentioned error still exists, but without the "&" I'm able to install the app successfully.
<img width="1172" alt="Bildschirmfoto 2021-12-13 um 00 04 13" src="https://user-images.githubusercontent.com/64470126/145733219-28463629-4beb-4578-8f66-ac19d4f61b80.png">

Is there a way to keep the `&` in my app name? It would be great, because if I replace it with "and" the name is really long.

Email with build link is sent.

**Comment by quinlanj** [comment] 2021-12-14 19:34
awesome, thanks for the email. much appreciated!

**Comment by mwegener-com** [comment] 2021-12-24 12:11
@quinlanj any news?

**Comment by quinlanj** [comment] 2022-01-04 01:05
hey @mwegener-com I've rolled out the fix to production just now. let me know if it works!

**Comment by quinlanj** [comment] 2022-01-20 01:22
Closing this issue now, afaict the issue is fixed. Feel free to open another issue if this is not the case!

**Closed by quinlanj** 2022-01-20 01:22 UTC
Labels: pending closure

**Comment by mwegener-com** [comment] 2022-01-20 05:49
Sorry, I haven't had time to check it out yet..
