### ISSUE TITLE
Classic Builds (expo build): Unsupported SDK Version (45) 

### ISSUE THREAD

**Issue by tknuts** [expo/expo#17455] opened 2022-05-11 10:53 UTC
### Summary

When running: 

expo build:android -t app-bundle 

with SD45, I get the following error:

Unsupported SDK version: our app builders do not support SDK version 45, yet. The latest SDK version is 45.0.0.
Unsupported SDK version
Error: Unsupported SDK version
    at Object.checkIfSdkIsSupported (/usr/local/lib/node_modules/expo-cli/src/commands/build/utils.ts:80:11)
    at AndroidBuilder.checkProjectConfig (/usr/local/lib/node_modules/expo-cli/src/commands/build/AndroidBuilder.ts:50:5)
    at AndroidBuilder.prepareProjectInfo (/usr/local/lib/node_modules/expo-cli/src/commands/build/BaseBuilder.ts:72:5)
    at AndroidBuilder.command (/usr/local/lib/node_modules/expo-cli/src/commands/build/BaseBuilder.ts:41:7)

### What platform(s) does this occur on?

Android

### SDK Version

45

### Environment

    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 7.18.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0 => 45.0.2 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.25.0
      expo-cli: 5.4.3
    Expo Workflow: managed

### Reproducible demo

expo build:android -t app-bundle

**Comment by tknuts** [comment] 2022-05-11 15:44
No support for expo build in SDK 45 yet

**Comment by ibrahim-ozturk** [comment] 2022-05-11 18:10
what we can do :(

**Comment by baifachuan** [comment] 2022-05-12 05:52
I meet the same error, how can I fix it in my project?

**Comment by langpp** [comment] 2022-05-12 11:15
yeah i get same error

**Comment by idindrakusuma** [comment] 2022-05-12 11:21
Try to build using `aes` @baifachuan 
https://blog.expo.dev/expo-sdk-45-f4e332954a68
 
```
› npm install -g eas-cli
› eas build -p android
```

**Comment by idindrakusuma** [comment] 2022-05-12 11:22
> I meet the same error, how can I fix it in my project?

Try to build using `aes` @baifachuan 
https://blog.expo.dev/expo-sdk-45-f4e332954a68
 
```
› npm install -g eas-cli
› eas build -p android
```

**Comment by superyarik** [comment] 2022-05-16 09:36
is there is ETA of fixing this?

**Comment by tknuts** [comment] 2022-05-16 09:47
I took all the headaches and "upgraded" to EAS, but that wasn't a walk in the park. Special plugin fix required to make it work on Android 12.

**Comment by amagnolo** [comment] 2022-05-16 10:26
EAS Update is still in "preview", so it's not an option for us. Classic build is feature complete, so I expect it will support SDK45 soon. This issue should be re-opened until fixed.

**Comment by superyarik** [comment] 2022-05-16 10:30
also EAS flow have limitations for builds and push counts

**Comment by tknuts** [comment] 2022-05-16 10:33
You will be forced into it soon anyways.... Which limitations ?

**Comment by superyarik** [comment] 2022-05-16 10:39
have a look this https://expo.dev/pricing
```
Push Notifications

First 1,000 Monthly Active Users (MAU) included

Then, $2 per 1,000 MAU
```

so it will be smart stay on classic builds as long as you can

**Comment by tknuts** [comment] 2022-05-16 11:03
Thanks for the tip :-)

**Comment by tknuts** [comment] 2022-05-16 12:10
The want us to move to eas now, hence this issue :-)

**Comment by amerikan** [comment] 2022-05-16 23:35
When they released SDK 45 they said Classic Build would arrive later for it.

> Arriving shortly after the release
> Snack support for SDK 45 will be available soon.
> Support for SDK 45 on the classic build service (expo build:[ios|android] and turtle-cli) **will be ready within a week or two of this release**

Keep in mind 45 was released May 5, 2022, so maybe the classic build is coming any time soon now.

https://blog.expo.dev/expo-sdk-45-f4e332954a68

**Comment by ide** [comment] 2022-05-17 00:21
Hi everyone - there are a few things about EAS I'd like to help clarify in this thread.

**SDK 45 support for `expo build:android` and `expo build:ios` (Classic Builds) will come soon:** the [SDK 45 release notes](https://blog.expo.dev/expo-sdk-45-f4e332954a68#5f13) mention the delay. We prioritized releasing SDK 45 before Classic Builds supported it so that the SDK was available sooner for developers who aren't using Classic Builds or who don't need to do a build right away. 

**Developers will need to migrate from Classic Builds:** the next SDK (SDK 46) will be the last version supported by Classic Builds. This means that future SDKs, specifically SDK 47 and later, will require building on your own hardware or using EAS Build. Please note that SDK 47 will be the first SDK released after this year's major iOS 16 release, so plan in advance.

**EAS Build is one of three ways to migrate from Classic Builds:** there are three mutually compatible options you can mix and match. We design Expo to be free and open source and to work on your own hardware, and EAS is an optional suite of cloud services that manages even more parts of app development. These are the three options:

1. Run `expo prebuild` to generate Android Studio and Xcode projects you can compile on your own hardware using raw Android and iOS development tools.
2. Use `eas build --local`, which runs on your own hardware while still using your Expo account and your app credentials you have uploaded to/created with EAS.
3. Use `eas build`, which runs in the EAS cloud.

The blog post announcing the final roadmap for Classic Builds explains these options in more detail with links to the docs: https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60#fd46

**EAS Update (in preview) does not affect any of this:** EAS Update is a separate service in preview. It is production-ready but we are improving the developer flow.

EAS Build is generally available and out of preview.

**Push notifications pricing:** the EAS pricing page mentions tentative future pricing for push notifications that is independent from Classic Builds. The way an app is compiled does not affect the pricing for other services it uses. This page also needs to be changed since we don't expect to start charging for push notifications soon and need to first clearly communicate the changes with enough time for developers to comfortably plan around the changes.

I hope this post makes things a little clearer. Sorry for the parts that are confusing right now!

**Comment by alexlukelevy** [comment] 2022-05-17 14:05
> Would be nice if `eas build --local`, could accept params like --force or --legacy-peer-deps as your cloud build. Makes it hard to use local builds.

You can add the npm params to an `.npmrc` file to ensure they're always supplied.

**Comment by dmi3y** [comment] 2022-05-17 22:02
I have error about sdk 45 is not supported but I'm on sdk 44:

```
npx expo-env-info
npx: installed 2 in 1.424s

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.10 - /usr/local/bin/node
      Yarn: 1.22.0 - ~/.yarn/bin/yarn
      npm: 6.14.7 - ~/Developer/Matternet/terminal/node_modules/.bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed
```

**Comment by AmenBreak175** [comment] 2022-05-20 11:30
I managed to create an apk (not aab) for my project using this command:
```
eas build --profile preview
```
This method is described here: https://docs.expo.dev/build/eas-json/

**Comment by AlexanderNo** [comment] 2022-05-21 09:17
Any updates on the classic build support for 45? Looking forward to it 🎈

**Comment by amerikan** [comment] 2022-05-24 17:53
> looks like classic bulds for SDK45 working now

I can confirm that classic builds on SDK45 are working for me now too! 👍🏼

**Comment by ide** [comment] 2022-05-24 19:03
Closing this issue since, as a couple people have noted above, Classic Builds now support SDK 45. We've also update [the SDK 45 release notes](https://blog.expo.dev/expo-sdk-45-f4e332954a68#5f13) to mention this change.

**Closed by ide** 2022-05-24 19:03 UTC
Labels: needs review, CLI
