### ISSUE TITLE
`React.lazy` is not working in Expo SDK 49

### ISSUE THREAD

**Issue by hinodi** [expo/expo#23570] opened 2023-07-17 07:17 UTC
### Minimal reproducible example

https://github.com/hinodi/expo-sdk-49

### Summary

Initiate a brand new project with Expo SDK 49, then try to use `React.lazy`, but it's not working

`Detail.js`
```
import { Text } from 'react-native';

export default () => <Text>Detail</Text>;
```
`App.js`
```
import { lazy, Suspense, useState } from 'react';
import { View, Button } from 'react-native';

const Detail = lazy(() => import('./Detail'));

export default function App() {
  const [showDetail, setShowDetail] = useState(false);

  return (
    <View>
      <Button title="Show Detail" onPress={() => setShowDetail(true)} />
      {showDetail && (
        <Suspense fallback={<View />}>
          <Detail />
        </Suspense>
      )}
    </View>
  );
}
```

**Full steps to reproducible `without` example codebase:**
1. init a new project with Expo SDK 49 `npx create-expo-app@latest --template blank@sdk-49`
2. make some changes the same as [this commit](https://github.com/hinodi/expo-sdk-49/commit/bf31866d6c90874cb5f3083b09a3c16e6ed4a574)
3. run the project `npm run ios`
4. press the `Show Detail` button on the App
5. will see the below errors:

**Full steps to reproducible with example codebase:**
1. clone the project `git@github.com:hinodi/expo-sdk-49.git`
2. `cd expo-sdk-49`
3. install dependencies `npm install`
4. run the project `npm run ios`
5. press the `Show Detail` button on the App
6. will see the below errors:

**Error Screenshots/Logs**
- app errors

  <table>
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img width="250" src="https://github.com/expo/expo/assets/26211549/db6b13ae-dbbc-4c7e-9606-cc2884e280a3"/></td>
    <td><img width="250" src="https://github.com/expo/expo/assets/26211549/eb0e8086-dd94-4361-ab17-046dfbcd4af8" /></td>
  </tr>
  </table>
- console error logs

  <img width="1000" src="https://github.com/expo/expo/assets/26211549/3e9cb0b0-9b4c-428a-a5ea-a0bda8116976">

**Affected platforms**
- iOS: `iOS 15.2`
- Android: `API 30`

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/dinh.huynh/.rvm/rubies/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.3 => 49.0.3 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      eas-cli: 3.15.1
    Expo Workflow: managed
```

**Comment by maartenschumacher** [comment] 2023-07-17 08:09
I solved by downgrading metro, see https://github.com/facebook/metro/issues/1019

**Comment by gasolin** [comment] 2023-07-17 08:57
can reproduce with the above demo

**Comment by maartenschumacher** [comment] 2023-07-17 09:05
> I solved by downgrading metro, see [facebook/metro#1019](https://github.com/facebook/metro/issues/1019)

I actually noticed that this breaks the bundle step of release builds, so we can only use this workaround in dev

**Comment by byCedric** [comment] 2023-07-19 18:25
Hi all! Sorry for the trouble, I just confirmed that the lazy bundle loading in Metro is relying on a feature that has not shipped with React Native yet ([see comment](https://github.com/facebook/metro/issues/1019#issuecomment-1642373034)).

To fix, or workaround it, there are a few options:

**1. Add `@expo/metro-runtime` as dev dependency, and import it in your app entryfile (e.g. `/index.js`, or `/App.js`).**
This adds the Metro runtime polyfills that we use in Expo Router, which does work fine since it doesn't rely on the unshipped React Native functionality.

  - `$ npx expo install @expo/metro-runtime`
  - `import '@expo/metro-runtime`;` (put this at the top in your app entry file)

**2. Disable lazy loading with `EXPO_NO_METRO_LAZY=true npx expo start`.**
This disables actual lazy loading and/or bundle splitting, instead, it will treat async imports as regular imports.

Note that this should not affect any production builds, since async imports and bundle splitting is only enabled in development.

Hope this helps!

**Comment by byCedric** [comment] 2023-08-14 15:13
Fixed by #23675

**Closed by byCedric** 2023-08-14 15:13 UTC
Labels: project: upstream

**Comment by johnculviner** [comment] 2023-09-18 19:52
A good option I've found is to put this into your `app.config.ts`

```
// TODO this can be removed after RN 73 likely per: https://github.com/expo/expo/issues/23570#issuecomment-1642555869
process.env.EXPO_NO_METRO_LAZY='true'
```

That way there isn't any chance of extra deps making into final builds, and no one on your team needs to know about an extra env var.

this

**Comment by SmileYang966** [comment] 2024-01-05 05:12
> A good option I've found is to put this into your `app.config.ts`
> 
> ```
> // TODO this can be removed after RN 73 likely per: https://github.com/expo/expo/issues/23570#issuecomment-1642555869
> process.env.EXPO_NO_METRO_LAZY='true'
> ```
> 
> That way there isn't any chance of extra deps making into final builds, and no one on your team needs to know about an extra env var.

This works for me!

**Comment by ehxxn** [comment] 2024-06-05 08:13
I still get this error in expo 50 only on Android
