### ISSUE TITLE
node_modules\expo\AppEntry.js` was not found

### ISSUE THREAD

**Issue by yehoan** [expo/expo#3891] opened 2019-03-29 15:58 UTC
Hi,
   when  i  use  npm install my project  and  use expo start to  start project  the  system  remind us 

The resource `D:\code\RN\node_modules\_react-native@0.57.1@react-native\node_modules\expo\AppEntry.js` was not found

but  i   not  understand  the  reason  and  i check  my  package.json  it  is  not change  beacause  once  it  use  okay  so  i  just  want  to know  the reason 

this  is  my  package.json 
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "@ant-design/react-native": "3.0.6",
    "dva-core": "^1.4.0",
    "expo": "^32.0.0",
    "js-combinatorics": "^0.5.4",
    "lodash.clonedeep": "^4.5.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-calendar-select": "^0.1.2",
    "react-native-iphone-x-helper": "^1.2.0",
    "react-native-render-html": "^3.10.0",
    "react-native-ultimate-listview": "^3.3.0",
    "react-navigation": "^2.12.1",
    "react-navigation-redux-helpers": "2.0.5",
    "react-redux": "^5.0.7",
    "rn-event-emitter": "^1.1.0",
    "sentry-expo": "^1.11.2"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}

yes   i   find  my  node_modules not  have  AppEntry.js  so  i  want  to know  the  reason

**Comment by yehoan** [comment] 2019-03-29 17:08
![image](https://user-images.githubusercontent.com/22631753/55250055-6086fd00-5288-11e9-9b2e-dc71b89df8e5.png)
but  i  find  it  have

**Comment by yehoan** [comment] 2019-03-29 17:13
![image](https://user-images.githubusercontent.com/22631753/55250374-ff135e00-5288-11e9-8a40-11527b326f7b.png)

**Comment by brentvatne** [comment] 2019-03-29 19:26
hello! i'm going to close this because the error message that you're showing us indicates that there is some very weird file structure going on - eg: why is there some directory called "_react-native@0.57.1@react-native" inside of node_modules?

if you can provide a reproducible example we can look at it but otherwise you'll need to figure it our on your own, sorry!

**Closed by brentvatne** 2019-03-29 19:26 UTC
Labels: project: sdk

**Comment by yehoan** [comment] 2019-03-29 22:46
i just use  npm  install  package.json  file  and  find  not  use  so  i  try  use  cnpm   it  is  a  mirror  of  npm  it is  okay  and  can  download   some  file   but  when  i  use   expo  start     it is  show  this  error  message

**Comment by yehoan** [comment] 2019-03-30 04:02
???

**Comment by pckz** [comment] 2019-06-03 21:32
Same for me. 
@yehoan  Do you can solve it?

**Comment by pckz** [comment] 2019-06-03 21:39
@yehoan 
1. Delete file **.babelrc** 
2. run 
`npm i --save-dev babel-plugin-module-resolver@latest`

**Comment by mryraghi** [comment] 2019-08-08 14:36
> @yehoan
> 
> 1. Delete file **.babelrc**
> 2. run
>    `npm i --save-dev babel-plugin-module-resolver@latest`

Thanks @pckz, it works but why is that?

**Comment by kopax** [comment] 2019-12-19 15:34
I have the same issue after doing `rm -rf node_modules && npm install`, did you solve it?
