### ISSUE TITLE
Facebook login not returning to Expo App

### ISSUE THREAD

**Issue by DanMotataeanu** [expo/expo#6235] opened 2019-11-11 23:13 UTC
### Environment

  Expo CLI 3.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.19.0 - C:\Users\Dan M\AppData\Roaming\npm\yarn.CMD
      npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

My app is running in Expo app for the moment

### Steps to Reproduce

I implemented Facebook login code as stated in your docs, it opens the login form, then my app and when I click on Continue (after I get notified that I will grant the app permisions to see my friends and profile) the screen gets white and I don't get any redirect to Expo App in oprder to handle the log in

### Expected Behavior

Return to expo app

### Actual Behavior
White screen and a cancel button on left on iOS

### Reproducible Demo
    handleLogin = async () => {
    const {type, token} = await Facebook.logInWithReadPermissionsAsync("id", { 
    permissions: ["user_friends"],
    });
    if(type==="success")
    {
     const cred = firebase1.auth.FacebookAuthProvider.credential(token);
     auth.signInWithCredential(cred).catch(error => {
     console.log("erropr")
     })
      
    }

**Comment by sjchmiela** [comment] 2019-11-12 09:45
Duplicate of https://github.com/expo/expo/issues/6112, this should be fixed in SDK 36.

**Closed by sjchmiela** 2019-11-12 09:45 UTC
Labels: bug
