### ISSUE TITLE
Lottie (DangerZone) animations crashing only in android expo client app new update

### ISSUE THREAD

**Issue by lazantha** [expo/expo#2007] opened 2018-07-18 15:56 UTC
Lottie animation is crashing only in android (I'm not using images for the animation), it did work before in andriod (before updating expo client) and also still (even after the update) working on ios. This happened after updating expo client apk.... does anyone know how to fix this?

```
componentDidMount(){
        this.animation.play();
}

render(){
     return(
              <View style={{
                    top: 0,
                    width: Dimensions.get('screen').width,
                    height: Dimensions.get('screen').height,
                    position: 'absolute',
                    justifyContent: 'center',
                    alignItems: 'center',
                    opacity: 0.5
                }}>
                        <Lottie
                            resizeMode='cover'
                            style={{
                                width: '100%',
                                height: '50%',
                                justifyContent: 'center',
                                alignItems: 'center'
                            }}
                            ref={animation => {
                                this.animation = animation;
                            }}
                            source={require('../../Animations/background_anim/data.json')}
                        /> 
                </View>
          );
}
```
![screenshot_2018-07-18-20-05-34-1](https://user-images.githubusercontent.com/19486122/42893087-0ebc9522-8ad1-11e8-843d-7ad67c3a67f7.png)

**Comment by esamelson** [comment] 2018-07-18 21:54
Hi @lazantha - could you post a snack that fully reproduces this issue? That would help us greatly in being able to identify and fix the crash. If not, could you post the native logs from the crash (`adb logcat`)?

**Comment by lazantha** [comment] 2018-07-19 05:35
Hi @esamelson , 
this is the [snack](https://snack.expo.io/HJhVfj6m7) ,i tried reproduce the issue, but somehow i found a way to avoid the crash by embedding data in the json file directly in the App class as a variable.
Thank you!

**Comment by lazantha** [comment] 2018-07-19 18:05
I tried using lottie again, it's still crashing, even after copying data into app.js

**Comment by brentvatne** [comment] 2018-07-19 18:10
https://snack.expo.io/Bkf27IRmm - here's another example of it working

**Comment by lazantha** [comment] 2018-07-20 15:08
Thank you very much @brentvatne , I'll try......

**Comment by lazantha** [comment] 2018-07-20 17:33
Even by trying that snack on my phone (S4 mini android Kit Kat), and also in Bluestacks (3.56) the app crashes! (Same error)

**Comment by gwalshington** [comment] 2018-07-24 21:12
This is happening to me too - exact same circumstances and very similar code. It's not crashing in dev - it just doesn't show up. In production it's crashing the client.

**Comment by lazantha** [comment] 2018-07-26 20:58
Hi @esamelson , 
I'm sorry I don't use Android Studio to do that

**Comment by gwalshington** [comment] 2018-07-27 18:48
@esamelson same - I'm not using Android Studio.

Not sure if it helps, but here's the apk. 
https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40walshcostigan/lexody-237d084bc67bc4fad94d0ca76b90e336-signed.apk

It doesn't crash on Samsung Galaxy S5, but it doesn't render anything from Lottie.

Samsung Galaxy S7 completely crashes on opening the app, with no errors in the JS console. Sorry I couldn't be more help!

**Comment by esamelson** [comment] 2018-08-01 00:47
Hi @lazantha and @gwalshington - I'm still unable to reproduce the crash on our test devices. 😞 It seems like this is a device specific issue caused by some library or API not being available on certain devices. We may be able to help if you're able to provide logs from a crash -- you can install and use the [adb tools](https://developer.android.com/studio/command-line/adb) without Android Studio.

**Comment by gwalshington** [comment] 2018-09-06 03:56
@esamelson I notice Lottie doesn't work on the Lottie Expo example for Android either: https://docs.expo.io/versions/latest/sdk/lottie

**Comment by MikePodgorniy** [comment] 2018-09-17 09:01
@esamelson 
here is crash.log from my app (kitkat emu, android sdk 19) with latest expo client 2.8.0
https://gist.github.com/MikePodgorniy/0d99cd3cb4434a081499172853287005

and crash.log from https://snack.expo.io/Byu2WM2af?session_id=snack-session-By6znk6OQ  (kitkat emu, android sdk 19)
https://gist.github.com/MikePodgorniy/bea504609f87fbf9dde10e517982497a

**Comment by KBB99** [comment] 2019-03-12 12:28
Not sure if anyone still needs this, but I had made the mistake of adding 'react-native-lottie' to my package.json instead of importing {Lottie} from DangerZone. It should look like this: 
```javascript
import { DangerZone } from 'expo';
let { Lottie } = DangerZone
```
Here's the documentation [https://docs.expo.io/versions/latest/sdk/lottie/]

**Comment by thegreatgabsby** [comment] 2019-04-04 19:19
Alright, I have here a gist from my error:

https://gist.github.com/thegreatgabsby/c09b430e707862069d8a92f82d731647

And I figured it is probably a problem of the Animation itself. Plugged in the animation of the example and it worked. To give you a hint of what might be going on.

Hope this helps

**Comment by JonathanLorimer** [comment] 2019-06-19 20:41
> Alright, I have here a gist from my error:
> 
> https://gist.github.com/thegreatgabsby/c09b430e707862069d8a92f82d731647
> 
> And I figured it is probably a problem of the Animation itself. Plugged in the animation of the example and it worked. To give you a hint of what might be going on.
> 
> Hope this helps.
> 
> EDIT:
> 
> Exporting the animation to support old json format in the advanced settings made it work for me

@gabmichels what do you mean old json format? I thought there was only one standardized json format?

**Comment by thayssn** [comment] 2019-06-30 22:57
@gabmichels  thank you so much. It tottaly worked for me.

**Comment by AdamJNavarro** [comment] 2019-08-08 00:28
Hey all,

It looks like @gabmichels's solution has solved this issue so I'm going to close this thread. 
If anyone is still encountering this issue on a presently supported SDK version (30-34) and has Minimal, Complete and Verifiable Example (MCVE) and better yet, the root cause identified, we encourage you to create a new issue with said information!

Cheers,
Adam

**Closed by AdamJNavarro** 2019-08-08 00:28 UTC
Labels: status: needs more info
