### ISSUE TITLE
Expo blank white screen after splash screen when the standalone built android apk is installed in android phone

### ISSUE THREAD

**Issue by ManojRakshu** [expo/expo#9420] opened 2020-07-27 12:11 UTC
Here, in my expo app, it is running  without any problem in expo developer tools, and android emulator. But when the standalone apk is installed to physical device, while running, after the splash screen its showing white blank screen. Here I'm pasting the package.json,app.json,App.js,DashBoard.js(landing component if authenticated) and Login.js(landing component if not authenticated)
package.json
`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/drawer": "^5.8.6",
    "@react-navigation/native": "^5.7.1",
    "@react-navigation/stack": "^5.7.1",
    "expo": "~38.0.8",
    "expo-status-bar": "^1.0.2",
    "firebase": "^7.17.1",
    "native-base": "^2.13.13",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-easy-grid": "^0.2.2",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-maps": "^0.27.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "~2.9.0",
    "react-native-web": "~0.11.7",
    "react-router-native": "^5.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true
}
`
app.json
`{
  "expo": {
    "name": "Csearch",
    "slug": "Csearch",
    "version": "1.0.0",
    "orientation": "portrait",
    "sdkVersion": "38.0.0",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#2e64ae"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "android": {
      "package": "com.geekonomy.Csearch",
      "versionCode": 1
    },
    "ios": {
      "supportsTablet": true
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
`
Login.js
`import React, { Component } from "react";
import { Item, Label, Button, Input, Text } from "native-base";
import { Image, StyleSheet, View, SafeAreaView } from "react-native";
import fire from "../config/fire";
import { Dimensions } from "react-native";
import { TouchableOpacity } from "react-native-gesture-handler";
class Login extends Component {
  constructor(props) {
    super(props);
    this.login = this.login.bind(this);
    this.state = {
      email: "",
      password: "",
    };
  }
  login() {
    fire
      .auth()
      .signInWithEmailAndPassword(this.state.email, this.state.password)
      .then((u) => {
        console.log(u);
      })
      .catch((error) => {
        console.log(error);
      });
  }
  render() {
    return (
      <View style={styles.container}>
        <Image
          style={{
            height: Dimensions.get("window").height / 2,
            width: Dimensions.get("window").width,
          }}
          source={require("../assets/login.png")}
        />
        <Item floatingLabel>
          <Label>Email</Label>
          <Input onChangeText={(email) => this.setState({ email })} />
        </Item>
        <Item floatingLabel last>
          <Label>Password</Label>
          <Input
            secureTextEntry={true}
            onChangeText={(password) => this.setState({ password })}
            placeholder="Password"
          />
        </Item>

        <Item
          style={{
            marginTop: 10,
            marginBottom: 10,
            justifyContent: "center",
            alignItems: "center",
            borderBottomColor: "white",
          }}
        >
          <Button info onPress={this.login}>
            <Text> Login </Text>
          </Button>
        </Item>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2e64ae",
  },
});
export default Login;
`
DashBoard.js
`import * as React from "react";
import { View, Image } from "react-native";
import { BackButton } from "react-router-native";
import { createDrawerNavigator } from "@react-navigation/drawer";
import { AntDesign } from "@expo/vector-icons";
import { NavigationContainer } from "@react-navigation/native";
import ShowData from "./showdata";
import ShowGangs from "./ShowGangs";
import InitialDb from "./initialDb";
import { createStackNavigator } from "@react-navigation/stack";
import { Entypo } from "@expo/vector-icons";
import fire from "../config/fire";
import { TouchableOpacity } from "react-native-gesture-handler";
const Drawer = createDrawerNavigator();
const DashBoardStack = createStackNavigator();
const ShowGangsStack = createStackNavigator();
const ShowCriminalsStack = createStackNavigator();
const DashBoardStackScreen = ({ navigation }) => (
  <DashBoardStack.Navigator
    screenOptions={{
      headerStyle: {
        backgroundColor: "#2e64ae",
      },
      headerTintColor: "#fff",
      headerTitleStyle: {
        fontWeight: "bold",
      },
    }}
  >
    <DashBoardStack.Screen
      name="DashBoard"
      component={InitialDb}
      options={{
        title: "Dashboard",
        headerLeft: () => (
          <TouchableOpacity onPress={() => navigation.openDrawer()}>
            <Entypo name="menu" size={24} color="black" />
          </TouchableOpacity>
        ),
        headerRight: () => (
          <TouchableOpacity onPress={() => fire.auth().signOut()}>
            <AntDesign name="logout" size={24} color="black" />
          </TouchableOpacity>
        ),
      }}
    />
  </DashBoardStack.Navigator>
);
const ShowGangsStackStackScreen = ({ navigation }) => (
  <ShowGangsStack.Navigator
    screenOptions={{
      headerStyle: {
        backgroundColor: "#2e64ae",
      },
      headerTintColor: "#fff",
      headerTitleStyle: {
        fontWeight: "bold",
      },
    }}
  >
    <ShowGangsStack.Screen
      name="ShowGangs"
      component={ShowGangs}
      options={{
        title: "Gangs",
        headerLeft: () => (
          <TouchableOpacity onPress={() => navigation.openDrawer()}>
            <Entypo name="menu" size={24} color="black" />
          </TouchableOpacity>
        ),
        headerRight: () => (
          <TouchableOpacity onPress={() => fire.auth().signOut()}>
            <AntDesign name="logout" size={24} color="black" />
          </TouchableOpacity>
        ),
      }}
    />
  </ShowGangsStack.Navigator>
);
const ShowCriminalsStackScreen = ({ navigation }) => (
  <ShowCriminalsStack.Navigator
    screenOptions={{
      headerStyle: {
        backgroundColor: "#2e64ae",
      },
      headerTintColor: "#fff",
      headerTitleStyle: {
        fontWeight: "bold",
      },
    }}
  >
    <ShowCriminalsStack.Screen
      name="ShowCriminals"
      component={ShowData}
      options={{
        title: "Criminals",
        headerLeft: () => (
          <TouchableOpacity onPress={() => navigation.openDrawer()}>
            <Entypo name="menu" size={24} color="black" />
          </TouchableOpacity>
        ),
        headerRight: () => (
          <TouchableOpacity onPress={() => fire.auth().signOut()}>
            <AntDesign name="logout" size={24} color="black" />
          </TouchableOpacity>
        ),
      }}
    />
  </ShowCriminalsStack.Navigator>
);
export default class DashBoard extends React.Component {
  render() {
    return (
      <>
        {/* <Image
          style={{ width: 400, height: 400, borderRadius: 400 / 2 }}
          source={require("../assets/login.png")}
        /> */}
        <NavigationContainer>
          <BackButton />
          <Drawer.Navigator initialRouteName="DashBoard">
            <Drawer.Screen name="DashBoard" component={DashBoardStackScreen} />
            <Drawer.Screen
              name="ShowGangs"
              component={ShowGangsStackStackScreen}
            />
            <Drawer.Screen
              name="ShowCriminals"
              component={ShowCriminalsStackScreen}
            />
          </Drawer.Navigator>
        </NavigationContainer>
      </>
    );
  }
}
`
App.js
`import "react-native-gesture-handler";
import { StatusBar } from "expo-status-bar";
import { AppLoading } from "expo";
import React from "react";
import { StyleSheet, Text, View } from "react-native";
import Login from "./components/Login";
import DashBoard from "./components/DashBoard";
import { BackButton, NativeRouter, Switch, Route } from "react-router-native";
import fire from "./config/fire";
import * as Font from "expo-font";
import { Ionicons } from "@expo/vector-icons";
import ShowSelectedCriminals from "./components/ShowSelectedCriminals";
import SelectedGangDetails from "./components/selectedGangDetails";
import GangCriminalDetails from "./components/GangCriminalDetails";
import ShowGangs from "./components/ShowGangs";
import Showdata from "./components/showdata";
import { Entypo } from "@expo/vector-icons";
import { AntDesign } from "@expo/vector-icons";

import {
  Container,
  Header,
  Left,
  Right,
  Title,
  Subtitle,
  Body,
  Button,
  Icon,
} from "native-base";
import { TouchableOpacity } from "react-native-gesture-handler";

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      user: {},
      isReady: false,
    };
  }
  authListener() {
    fire.auth().onAuthStateChanged((user) => {
      if (user) {
        this.setState({ user });
      } else {
        this.setState({ user: null });
      }
    });
  }
  async componentDidMount() {
    await Font.loadAsync({
      Roboto: require("native-base/Fonts/Roboto.ttf"),
      Roboto_medium: require("native-base/Fonts/Roboto_medium.ttf"),
      ...Ionicons.font,
    });
    this.setState({ isReady: true }, () => {
      this.authListener();
    });
  }

  render() {
    if (!this.state.isReady) {
      return <AppLoading />;
    }
    return (
      <NativeRouter>
        <BackButton />
        <Switch>
          <Route exact path="/">
            {this.state.user ? <DashBoard /> : <Login />}
          </Route>
          <Route path="/criminalDetails" component={ShowSelectedCriminals}>
            {/* {this.state.user ? <ShowSelectedCriminals /> : <Login />} */}
          </Route>
          <Route path="/gangDetails" component={SelectedGangDetails}>
            {/* {this.state.user ? <SelectedGangDetails /> : <Login />} */}
          </Route>
          <Route path="/gangCriminalDetails" component={GangCriminalDetails}>
            {/* {this.state.user ? <GangCriminalDetails /> : <Login />} */}
          </Route>
          <Route path="/ShowGangs">
            {this.state.user ? <ShowGangs /> : <Login />}
          </Route>
          <Route path="/Showdata">
            {this.state.user ? <Showdata /> : <Login />}
          </Route>
        </Switch>
      </NativeRouter>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
`

**Comment by cruzach** [comment] 2020-07-27 13:16
hi @ManojRakshu , we like to keep github reserved for bug reports in the Expo SDK, and this seems likely to be a bug in your code, so I'm going to close this issue. We provide a guide on debugging (specifically for standalone apps) [here](https://docs.expo.io/workflow/debugging/#production-errors), so I suggest giving the steps listed there a try to try and figure out what's going on.

If you find out that this is a bug with Expo, please provide a [minimal reproducible demo](https://stackoverflow.com/help/minimal-reproducible-example) like we ask for in the issue template, thanks!

**Closed by cruzach** 2020-07-27 13:16 UTC

**Comment by n-ii-ma** [comment] 2023-12-31 09:34
Same thing is happening for me.

**Comment by Eshtreeli** [comment] 2024-02-17 10:21
same

**Comment by devDoubleH** [comment] 2024-03-17 10:43
same here

**Comment by adelphysi1986** [comment] 2024-03-17 10:48
Isoolved it! Add  expo-build-properties plug in

**Comment by devDoubleH** [comment] 2024-03-17 10:54
@adelphysi1986 you mean like this:       [
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 31,
            "targetSdkVersion": 31,
            "buildToolsVersion": "31.0.0"
          },
          "ios": {
            "deploymentTarget": "13.4"
          }
        }
      ],

**Comment by horlas08** [comment] 2024-03-20 08:43
> I solved it! Just add expo-build-properties plug in to app json



> @adelphysi1986 you mean like this: [ "expo-build-properties", { "android": { "compileSdkVersion": 31, "targetSdkVersion": 31, "buildToolsVersion": "31.0.0" }, "ios": { "deploymentTarget": "13.4" } } ],

that didnt solve my problem however going to _layout.tsx i found out that SplashScreen.hideAsync() didnt have await and is call inside useEffect which can't take async so i clear the splash screen code and copy it again from https://docs.expo.dev/versions/latest/sdk/splash-screen/#usage 
here SplashScreen.hideAsync() is with await and inside useCallback 
i hope this help

**Comment by devDoubleH** [comment] 2024-03-21 04:06
@horlas08 thanks for attention. But actually my problem is not associated with splash screen.

https://github.com/expo/expo/assets/83258481/16f4e5ec-79e6-410d-8b04-a72800bf4e2c

**Comment by horlas08** [comment] 2024-03-21 04:34
You own issue is totally different
Can you provide more info
Are you making an api when click the button or provide your code 
to snack @ https://snack.expo.dev/

**Comment by devDoubleH** [comment] 2024-03-21 05:09
Yep, but it is not an api yet just a navigating to another page. So I think the problem is with android I believe because everything is going well in ios.

https://github.com/expo/expo/assets/83258481/0fdbf1de-10d9-4372-825c-fc95ddbb49ba

```
        <Pressable
          className="w-full rounded-xl bg-white h-10 mt-4 flex justify-center items-center"
          onPress={() => router.replace("/main/tabs/home")}
        >
          <Text className="text-xl">Kirish</Text>
        </Pressable>
``` I am using expo router. @ManojRakshu are you experiencing like this situation ?

**Comment by horlas08** [comment] 2024-03-21 08:26
Can u share the screenshot of your app folder structure especially the app/ forder

**Comment by devDoubleH** [comment] 2024-03-21 13:19
<img width="368" alt="Screenshot 2024-03-21 at 18 19 11" src="https://github.com/expo/expo/assets/83258481/5f2a6a52-a554-4a0b-bf29-d31a5740b3fe">

**Comment by horlas08** [comment] 2024-03-21 15:08
I don't think anything wrong with your code and folder structure 
You can try the below debug process. Maybe it may help

Delete node_modules folder and reinstall using npm or yarn
Try another andriod device, especially if you can get physical andriod phone
You can start the npm with -c flag

**Comment by devDoubleH** [comment] 2024-03-22 06:06
@horlas08 thanks! I have tried all solutions you have told but no progress If I find any solution I'll leave it here.

**Comment by Naveen-g09** [comment] 2024-04-13 08:09
> @horlas08 thanks! I have tried all solutions you have told but no progress If I find any solution I'll leave it here.
> 

Hey, Found anything?

**Comment by Naveen-g09** [comment] 2024-04-13 08:09
> @horlas08 thanks for attention. But actually my problem is not associated with splash screen.
> 
> https://github.com/expo/expo/assets/83258481/16f4e5ec-79e6-410d-8b04-a72800bf4e2c
> 
> 

Same happens for me but if I change my device theme, I can see the app

**Comment by horlas08** [comment] 2024-04-13 09:35
> > @horlas08 thanks for attention. But actually my problem is not associated with splash screen.
> > 
> > https://github.com/expo/expo/assets/83258481/16f4e5ec-79e6-410d-8b04-a72800bf4e2c
> > 
> > 
> 
> Same happens for me but if I change my device theme, I can see the app

@Naveen-g09, have you tried it on physical device

**Comment by Naveen-g09** [comment] 2024-04-13 09:37
> > > @horlas08 thanks for attention. But actually my problem is not associated with splash screen.
> > > 
> > > https://github.com/expo/expo/assets/83258481/16f4e5ec-79e6-410d-8b04-a72800bf4e2c
> > > 
> > > 
> > 
> > Same happens for me but if I change my device theme, I can see the app
> 
> @Naveen-g09, have you tried it on physical device

Yes

Here are the videos https://github.com/expo/expo/assets/76151123/ebf3c18b-6385-462d-85ca-f7aae71733c5

https://github.com/expo/expo/assets/76151123/c16cb0cf-7cf5-4d6c-8031-5fc3b9532923

**Comment by horlas08** [comment] 2024-04-13 11:07
> > > > @horlas08 thanks for attention. But actually my problem is not associated with splash screen.
> > > > 
> > > > https://github.com/expo/expo/assets/83258481/16f4e5ec-79e6-410d-8b04-a72800bf4e2c
> > > > 
> > > > 
> > > 
> > > Same happens for me but if I change my device theme, I can see the app
> > 
> > @Naveen-g09, have you tried it on physical device
> 
> Yes
> 
> Here are the videos https://github.com/expo/expo/assets/76151123/ebf3c18b-6385-462d-85ca-f7aae71733c5
> 
> https://github.com/expo/expo/assets/76151123/c16cb0cf-7cf5-4d6c-8031-5fc3b9532923
> 
> 

There is probably a bug in your code. Which sdk are you using

**Comment by Naveen-g09** [comment] 2024-04-13 11:10
> > > > > @horlas08 thanks for attention. But actually my problem is not associated with splash screen.
> > > > > 
> > > > >   
> > > > >     
> > > > >     
> > > > > 
> > > > >     1111.mp4
> > > > 
> > > > 
> > > > Same happens for me but if I change my device theme, I can see the app
> > > 
> > > 
> > > @Naveen-g09, have you tried it on physical device
> > 
> > 
> > Yes
> > Here are the videos https://github.com/expo/expo/assets/76151123/ebf3c18b-6385-462d-85ca-f7aae71733c5
> > 
> >   
> >     
> >     
> > 
> >     Screen_Recording_20240412_003502_ella.mp4
> 
> There is probably a bug in your code. Which sdk are you using

sdk 50

**Comment by Naveen-g09** [comment] 2024-04-13 11:12
> > > > > > @horlas08 thanks for attention. But actually my problem is not associated with splash screen.
> > > > > > ```
> > > > > > 1111.mp4
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Same happens for me but if I change my device theme, I can see the app
> > > > 
> > > > 
> > > > @Naveen-g09, have you tried it on physical device
> > > 
> > > 
> > > Yes
> > > Here are the videos https://github.com/expo/expo/assets/76151123/ebf3c18b-6385-462d-85ca-f7aae71733c5
> > > ```
> > > Screen_Recording_20240412_003502_ella.mp4
> > > ```
> > 
> > 
> > There is probably a bug in your code. Which sdk are you using
> 
> sdk 50

My auth screen looks well, but when rest of the component mounts this is the behavior it happens
i think it is because of this hook but i cannot figure out how

this is my root layout.tsx:


```
  useEffect(() => {
    setTimeout(() => {
      SplashScreen.hideAsync(
        // @ts-ignore
        global.bootSplash,
        { fade: true },
      );
    }, 900);
  }, [loaded]);

  if (!loaded) {
    return null;
  }
  ```

**Comment by horlas08** [comment] 2024-04-13 12:52
I think you need to check how to set up expo splashscreen in a proper way. You can copy the example from the link below https://docs.expo.dev/versions/latest/sdk/splash-screen/

**Comment by devDoubleH** [comment] 2024-04-14 08:22
@Naveen-g09 hello there. I didn't tried yet let me try.

**Comment by devDoubleH** [comment] 2024-04-14 08:24
@Naveen-g09 thanks for research I and toggling theme is also worked on me on android.

**Comment by devDoubleH** [comment] 2024-04-14 08:25
So then it is a theme problem in expo ?

**Comment by Naveen-g09** [comment] 2024-04-14 08:30
> So then it is a theme problem in expo ?

Yeah seems to be, something after auth coming to homescreen does this.
I am trying some ways to figure out.

Here's what didn't work:
1. Giving the app a constant theme in app.config.js or app.json from ```user interface style : "automatic"``` to ```"light"```


If i figure it out, will mention you here.

**Comment by Naveen-g09** [comment] 2024-04-14 08:32
> > So then it is a theme problem in expo ?
> 
> Yeah seems to be, something after auth coming to homescreen does this.
> I am trying some ways to figure out.
> 
> Here's what didn't work:
> 1. Giving the app a constant theme in app.config.js or app.json from ```user interface style : "automatic"``` to ```"light"```
> 
> 
> If i figure it out, will mention you here.
> 

Does evan look onto things like these? 
@EvanBacon @expo-bot

**Comment by devDoubleH** [comment] 2024-04-14 08:33
I used this in my project actually: const {
  createRunOncePlugin,
  withAndroidStyles,
  AndroidConfig,
} = require("@expo/config-plugins");

function setForceDarkModeToFalse(styles) {
  styles = AndroidConfig.Styles.assignStylesValue(styles, {
    add: true,
    parent: AndroidConfig.Styles.getAppThemeLightNoActionBarGroup(),
    name: `android:forceDarkAllowed`,
    value: "false",
  });

  return styles;
}

const withDisableForcedDarkModeAndroid = (config) => {
  return withAndroidStyles(config, (config) => {
    config.modResults = setForceDarkModeToFalse(config.modResults);
    return config;
  });
};

module.exports = createRunOncePlugin(
  withDisableForcedDarkModeAndroid,
  "disable-forced-dark-mode",
  "1.0.0"
);

**Comment by devDoubleH** [comment] 2024-04-14 08:33
I used this in my project: `const {
  createRunOncePlugin,
  withAndroidStyles,
  AndroidConfig,
} = require("@expo/config-plugins");

function setForceDarkModeToFalse(styles) {
  styles = AndroidConfig.Styles.assignStylesValue(styles, {
    add: true,
    parent: AndroidConfig.Styles.getAppThemeLightNoActionBarGroup(),
    name: `android:forceDarkAllowed`,
    value: "false",
  });

  return styles;
}

const withDisableForcedDarkModeAndroid = (config) => {
  return withAndroidStyles(config, (config) => {
    config.modResults = setForceDarkModeToFalse(config.modResults);
    return config;
  });
};

module.exports = createRunOncePlugin(
  withDisableForcedDarkModeAndroid,
  "disable-forced-dark-mode",
  "1.0.0"
);
`

**Comment by Naveen-g09** [comment] 2024-04-14 08:39
> android:forceDarkAllowed
(does this work?)

is your repo open to look at?

**Comment by devDoubleH** [comment] 2024-04-14 08:50
nope

**Comment by devDoubleH** [comment] 2024-04-15 01:23
Hello everyone @Naveen-g09 @horlas08 I found the issue it was `expo-blur` or `react-native-community/blur` more details: [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens/issues/1661)

**Comment by devDoubleH** [comment] 2024-04-15 01:33
you can also check this one: [expo-blur android](https://docs.expo.dev/versions/latest/sdk/blur-view/#experimentalblurmethod)

**Comment by Naveen-g09** [comment] 2024-04-15 06:54
ahhhhhh that's nice, Thanks a lot @devDoubleH .Indeed that was the issue. Now looking on ways to fix it, have you figured out a way to use expo blur and not get this?

**Comment by devDoubleH** [comment] 2024-04-15 07:24
```
tabBarBackground: () =>
          Platform.OS === "android" ? null : (
            <BlurView
              tint="light"
              intensity={100}
              blurReductionFactor={5}
              experimentalBlurMethod="none"
              style={[
                StyleSheet.absoluteFill,
                {
                  borderTopRightRadius: 20,
                  borderTopLeftRadius: 20,
                  overflow: "hidden",
                  backgroundColor: "transparent",
                },
              ]}
            />
          )

**Comment by Naveen-g09** [comment] 2024-04-15 07:47
thanks alot! @devDoubleH
