### ISSUE TITLE
ImagePicker.launchCameraAsync() doesn't follow documentation

### ISSUE THREAD

**Issue by mjakobsen** [expo/expo#1919] opened 2018-06-26 13:21 UTC
Hello, Im using the ImagePicker to both take a new photo, and chose one from the phone. According to the [documentation](https://docs.expo.io/versions/v28.0.0/sdk/imagepicker), both scenaries should be able to ask for a base64 string in the result.
However after upgrading to sdk 28 [according to this](https://blog.expo.io/expo-sdk-v28-0-0-is-now-available-f30e8253b530), and upgrading to @types/expo": "^27.0.3" that is the newest to my knowlagde. 
Now my problem is that the CameraOption that "await ImagePicker.launchCameraAsync" takes for parameter, does not have a "base64" option, so I can't get a base 64 string.

### Steps to Reproduce

1. Call ImagePicker.launchCameraAsync with base64: true

### Expected Behavior

A result including a base64 string of the taken image

### Actual Behavior

A result with no base64 string

### Alternatively

A workaround to get the uri into a File or Blog variable so i can send that to Firebase instead of a base64 string

**Comment by nikki93** [comment] 2018-06-26 19:34
There should be no changes in this feature in sdk 28... Which version did you upgrade from? And also which platform (iOS / Androd)?

**Comment by mjakobsen** [comment] 2018-06-26 21:07
@nikki93 I came from sdk version 26
I tried to just add the "base64: true" and tested it on an android phone.
The thing is according to the typescript definition there is no option for base64 in the CameraOptions that the LaunchCameraAsync function takes

p.s in sdk version 26 it didn't work either i upgraded to get more types for the Camera permissions as well

**Comment by aalices** [comment] 2018-06-27 07:07
@mjakobsen can you create a snack reproducing your issue?  Are you using Expo Client or your app is detached / standalone ?

**Comment by mjakobsen** [comment] 2018-06-27 09:40
I have found a workaround for this, using the uri from ImagePicker, so im no longer depended on a base64, should still be fixed imo thou :)

**Comment by anp** [comment] 2018-06-28 07:02
@mjakobsen glad to hear you found a workaround! We'd still love to resolve the issue you had, and it's much more likely that we'll be able to be certain we've fixed it if you can help us reproduce it. If you could post a [Snack](https://snack.expo.io) we can use to trigger the problem you hit, we'd really appreciate it. I'm going to close this until we hear back from you since it sounds like your problem is resolved and we don't have enough information yet to treat this as a bug report.

Also, one thing you might want to look at -- you mentioned TypeScript definitions for Expo but we don't currently maintain any TS libs as far as I know (although I could be wrong). If the type definitions are a community effort then you may want to let them know they're missing an option to the method!

**Closed by anp** 2018-06-28 07:02 UTC
