### ISSUE TITLE
Fetch Request not working on android or web, but working on IOS

### ISSUE THREAD

**Issue by DylanRiden** [expo/expo#11679] opened 2021-01-19 17:59 UTC
### Summary of Issue:
 When I make any request with fetch to my API, it works on IOS fine, but a "TypeError: Network request failed" error occurs on Android or with web.
I have tested with different android phones and using different "Accept: application/json" headers but still can't figure this out, it also seems to only be occurring with my API

### Reproducible Demo

https://snack.expo.io/@dylander/7cfe32

 
### Steps to Reproduce
Just run the snack on android. The fetch can be seen in the AssetExample function 

### Expected Behavior vs Actual Behavior

Expected: The response is shown in the console like on iOS

Actual: The request fails

**Comment by brentvatne** [comment] 2021-01-20 04:08
### web

open your console in chrome and run fetch:

```
fetch('https://api.dbine.co.uk')
Promise {<pending>}
7cfe32:1 Access to fetch at 'https://api.dbine.co.uk/' from origin 'https://snack.expo.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

the api does not support cross origin requests. expo web is still web, and you need to follow cross origin policies

### android

https://snack.expo.io/@notbrent/11679

it's unclear to me what is happening here. the request does not work over https for this particular server, but works fine on http

my guess is this is somehow related to the `Alt-Svc` header, given that's the only meaningful difference in the responses

<img width="1238" alt="Screen Shot 2021-01-19 at 7 56 38 PM" src="https://user-images.githubusercontent.com/90494/105125466-4cca0d80-5a91-11eb-9315-8d8e1bdc61be.png">


<img width="1238" alt="Screen Shot 2021-01-19 at 7 56 42 PM" src="https://user-images.githubusercontent.com/90494/105125460-49368680-5a91-11eb-844c-d1807d149b97.png">

if you control that api, try removing the header. if you want to dig into this deeper, i'd suggest ejecting the app and inspecting the request with native android debugging tools. i'm not particularly familiar with this http header so i do not know what the expected behavior is in this case.

there are a number of quirks with fetch on android and you may have stumbled upon one. see others here https://github.com/facebook/react-native/issues?q=android+fetch

**Comment by brentvatne** [comment] 2021-01-20 04:11
going to actually close this because it's an upstream react-native issue, if you'd like to create an issue there that outlines it that'd be great. hopefully the information above makes sense

**Closed by brentvatne** 2021-01-20 04:11 UTC
Labels: project: upstream

**Comment by Aparus** [comment] 2021-02-05 20:24
I faced the same issue. On web i handled it with installing 'cors' extension -- now it works on web. 
But on android expo client I even doesn't see any error, though I use try/catch. I tried with promise, with async await, with  fetch and axios. Nothing is working :(

**Comment by Aparus** [comment] 2021-02-05 20:31
I faced the same issue. On web i handled it with installing 'cors' extension -- now it works on web.
But on android expo client I even doesn't see any error, though I use try/catch. I tried with promise, with async await, with fetch and axios. Nothing is working :(

**Comment by jabedzaman** [comment] 2023-12-11 05:10
any fix was found???
