### ISSUE TITLE
Expo dev client can only connect with running dev server and not static files hosted using expo export

### ISSUE THREAD

**Issue by Silvest89** [expo/expo#13896] opened 2021-08-03 13:36 UTC
### Summary

Currently the custom development client can only connect to a running dev server.  (Unlike expo go).  Connecting to static files served with Nginx only works with Expo Go, not with a custom development client

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Package versions

```
    "expo-dev-client": "^0.4.4",
    "expo-dev-launcher": "^0.6.4",
    "expo-dev-menu-interface": "^0.3.2",
```

### Environment

```
  Expo CLI 4.9.1 environment info:
    System:
      OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.17.1 - /usr/bin/node
      Yarn: 1.22.10 - ~/projects/differentlab/mobile-react/node_modules/.bin/yarn
      npm: 7.19.1 - /usr/bin/npm
    npmPackages:
      expo: ^42.0.0 => 42.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: bare

```

### Reproducible demo or steps to reproduce from a blank project

Use expo export to generate static files.
Host it using either a local php/nginx/python server. Connect to it. Won't work with your custom dev client but it does with Expo GO

**Comment by byCedric** [comment] 2021-08-03 14:40
Hi @Silvest89, what is the error you are running into? We have updated the OTA spec to support dev clients, I think you are running into these changes. Might be good to take a look at the technical specification and see if you are missing a specific header or response https://docs.expo.dev/technical-specs/expo-updates-0/

**Comment by Silvest89** [comment] 2021-08-03 16:21
![error](https://user-images.githubusercontent.com/2388338/128050869-a3b79646-2157-48b6-ad15-c7e37931cef7.jpeg)

This is the error I am getting when accessing  <server url>/ios-index.json  it works perfectly fine when using Expo GO

**Comment by Silvest89** [comment] 2021-08-04 14:53
@byCedric 
Is there a difference in implementation between Expo GO and custom dev clients? The GO app works fine when scanning QR, custom dev clients give the above error ^

**Comment by esamelson** [comment] 2021-08-04 21:45
Hey @Silvest89 - thanks for the report! We're working on a fix for this, hang tight.

**Comment by esamelson** [comment] 2021-08-06 19:32
hi @Silvest89 - this is fixed in `expo-dev-client@0.4.7` and `expo-updates@0.8.4` which are both out now (you'll need to upgrade both to get the full fix). Thanks again for the report, and let us know if you have any further issues.

**Closed by esamelson** 2021-08-06 19:32 UTC
Labels: needs more info, Custom Client

**Comment by Silvest89** [comment] 2021-08-17 06:50
> hi @Silvest89 - this is fixed in `expo-dev-client@0.4.7` and `expo-updates@0.8.4` which are both out now (you'll need to upgrade both to get the full fix). Thanks again for the report, and let us know if you have any further issues.

Now I don't get the above error anymore but just this instead:

![Screenshot from 2021-08-17 08-49-37](https://user-images.githubusercontent.com/2388338/129677388-70d79a1c-febf-454d-9997-575ecc611eee.png)

Expo GO works fine.

**Comment by esamelson** [comment] 2021-08-17 18:27
Hey @Silvest89 - what `content-type` value are you serving the manifest with from your local server?

**Comment by Silvest89** [comment] 2021-08-20 07:15
> Hey @Silvest89 - what `content-type` value are you serving the manifest with from your local server?

Just the usual json for the index.json and javascript for the bundles.
I have tested it using PYTHON local server, PHP -S (local server) and nginx (they serve the correct content-type automatically)

The thing is Expo GO app works fine in all cases.

**Comment by esamelson** [comment] 2021-08-30 22:17
I'm not able to reproduce this with a python SimpleHTTPServer; when I open `http://0.0.0.0:8000/ios-index.json` the response comes back with a content-type of `application/json` and my development client opens the app correctly. If you're still having issues with this, I'd suggest verifying that the content-type of the response is correct.

The reason that Expo Go behaves differently is because custom clients also have the ability to load bundles from a plain react-native server (`npx react-native start`), which means we need to infer more information from the content-type header as not much other information is available from this kind of server.
