### ISSUE TITLE
OTA Updates Not working on Expo SDK 39

### ISSUE THREAD

**Issue by be90728** [expo/expo#10417] opened 2020-09-28 06:45 UTC
## 🐛 Bug Report

Originally, I used "expo-updates" as a manual update library. When I updated the Expo SDK from 37 to 39, it couldn't work anymore. So I tried to change the app.json so that Expo standalone can update automatically via OTA, but OTA update still doesn't work...
I am using TestFlight as the test standard
I use Google Translate, I am from Taiwan, thanks.

Expo CLI 3.27.10 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.14
      react-navigation: ^4.1.1 => 4.4.1
    Expo Workflow: managed

### Reproducible Demo

this is my app.json file:
{
  "expo": {
     ...
     "updates": {
      "fallbackToCacheTimeout": 30000,
      "enabled": true,
      "checkAutomatically": "ON_LOAD"
    }
     ...
  }
}

**Comment by jtklein** [comment] 2020-09-28 09:52
I have the same problem, OTA Updates are not applied anymore since updating from Expo SDK 38 to 39. It was working as expected in 38 (i.e. updating on launch and then the new update available on the launch after that).

My app.json update config:
`this is my app.json file:
{
"expo": {
...
    "updates": {
      "enabled": true,
      "checkAutomatically": "ON_LOAD",
      "fallbackToCacheTimeout": 0
    },
...
}
}`

I have also added a button to use the following code preceded by a check of `Updates.checkForUpdateAsync()`. But the check does not return true.
`await Updates.fetchUpdateAsync();
    await Updates.reloadAsync();`

**Comment by Aryk** [comment] 2020-09-28 11:51
I'm getting the same issue as well after upgrading from 38 -> 39. I have no "updates" key in my app.json. I'm just expecting the default behavior (kill the app, reopen, get a new version). It's completely broken.

**Comment by Aryk** [comment] 2020-09-28 12:08
Can anyone reading this put a like if OTA updates is still working for them after upgrading to SDK 39?

**Comment by DavidBrear** [comment] 2020-09-28 12:40
@Aryk broken for me as well. Looks like it might be a bug in SDK 39. I guess trying to be on the cutting edge means we sometimes get cut. So yeah it's not just you.

**Comment by cruzach** [comment] 2020-09-28 13:49
Are you trying to publish to a release channel other than default? If you are, then this is probably a duplicate of https://github.com/expo/expo/issues/10304

**Comment by Aryk** [comment] 2020-09-28 14:13
@cruzach - I did and then I saw this thread that things were broken.

Now I'm using just default:

>> expo build:android -t apk
>> expo publish

I kill the app, reopen it, OTA not showing up. I was using it a lot this past week in SDK 38, was working great, but now it's completely broken.

**Comment by Aryk** [comment] 2020-09-28 14:26
@cruzach  - I believe the other guys on this thread are having problems with the default OTA update as well.
 

@DavidBrear , @jtklein , @be90728 , can you guys confirm that it happens with you guys specifically on default?

**Comment by jtklein** [comment] 2020-09-28 14:34
I do not use the default release-channel.

**Comment by Aryk** [comment] 2020-09-28 14:37
So "default" is working for you? Maybe I need to try adding the "updates" key in app.json to get default working?

**Comment by DavidBrear** [comment] 2020-09-28 14:40
I was using release channels `prod` and `develop` for my app and I just tried publishing without the release channel flag but did not see the changes in my app. I'm suspecting it's because I built the app with the release channel explicitly set so this is probably a dupe in my case. Thanks Expo team for looking into this. I appreciate all your hard work.

**Comment by Aryk** [comment] 2020-09-28 14:45
> I was using release channels `prod` and `develop` for my app and I just tried publishing without the release channel flag but did not see the changes in my app. I'm suspecting it's because I built the app with the release channel explicitly set so this is probably a dupe in my case. Thanks Expo team for looking into this. I appreciate all your hard work.

Thats what I thought too...then I tried default and it will wasn't working. 

Can you try something like

```
>> expo build:android -t apk
>> expo publish
```

and tell me if it works? Would be good to know if I'm the only one experiencing issues with "default".

Btw, do you have the "updates" key set in your app..json?

**Comment by Aryk** [comment] 2020-09-28 15:11
Ok, seems I got it working on default after I put the "updates" key with this information:

"updates": {
"fallbackToCacheTimeout": 30000,
"enabled": true,
"checkAutomatically": "ON_LOAD"
}

@cruzach  - Is that supposed to be required?

**Comment by DavidBrear** [comment] 2020-09-28 15:35
@Aryk yep, that worked. I did the android build. put it on an android device then made a change (I added an "!" on a sentence) and then I did expo publish to the default channel and the OTA updates showed up. Looks like it's just pushing to specific release channels isn't working.

**Comment by be90728** [comment] 2020-09-28 16:43
Yes, I have confirmed that OTA updates will not work when publishing non-default channels
I will test to change the "checkAutomatically" of app.json to "ON_ERROR_RECOVERY"
I will try to update manually on Android using fetchUpdateAsync and reloadAsync

**Comment by brentvatne** [comment] 2020-09-28 18:06
@Aryk - i can't repro any issues with the default release channel. the above config you provided isn't necessary, in a new app without it updates to the default channel will work as expected (loaded async in the background, you may need to wait a few seconds after opening the app for the download to finish in the background and then restart the app to get the update)

we are tracking and discussing release channel issues here: https://github.com/expo/expo/issues/10304

**Closed by brentvatne** 2020-09-28 18:06 UTC
Labels: Issue needs review

**Comment by Aryk** [comment] 2020-09-28 19:29
> @Aryk - i can't repro any issues with the default release channel. the above config you provided isn't necessary, in a new app without it updates to the default channel will work as expected (loaded async in the background, you may need to wait a few seconds after opening the app for the download to finish in the background and then restart the app to get the update). if you can share an app with a certain config that reproduces this for you, please create a new issue and link to the github repo.
> 
> we are tracking and discussing release channel issues here: #10304

Sounds good...if I have some time...I will try removing the "updates" key from package and see if it's happening with me.

I've been using the OTA updates feature a ton and even have a very elaborate system of updating while the app is in use, etc. The OTA would get triggered even before the task was finished. 

Thank goodness I got atleast the default channel working, not sure what I would do with the OTA updates.

**Comment by brentvatne** [comment] 2020-09-28 19:31
i tried without the updates key entirely and with the updates key and also with only `"fallbackToCacheTimeout": 0` and both worked for me. if you can provide a repro it would be very helpful to know that this is actually an issue so we can investigate it further

**Comment by gang544043963** [comment] 2020-09-29 02:37
This is bug in SDK 39, refer to https://github.com/expo/expo/issues/10304

**Comment by noemipi** [comment] 2020-10-01 10:06
Hello, got same issue, have you got any news about it??

**Comment by Fatima-Naseer** [comment] 2020-10-21 07:31
@Aryk Can you please let me know about configurations for expo-updates as I've started working with a bare workflow and after creating a build on default channel, my app is crashing. Also, I've gone through expo doc for expo-updates setup but still facing the issue. Your suggestions would be of great help.

**Comment by brentvatne** [comment] 2020-10-23 22:19
@Fatima-Naseer - hello! you might want to debug *why* your app is crashing. if you find there is a bug with any expo package then please post an issue with more information.

<hr />

the topic of this issue was about was resolved two weeks ago so i will lock this issue. create a new issue and follow the issue template if you can demonstrate that you are experiencing something similar, thanks!
