### ISSUE TITLE
I have resolved Notification routing when the user click on the notification using package expo-notification

### ISSUE THREAD

**Issue by MWaqasHussain-dev** [expo/expo#10919] opened 2020-11-04 08:19 UTC
import * as Notifications from 'expo-notifications';
i have used this package

i have used component life cycle async componentDidMount and putted my notificationRespondListner in it  and it respond me back when ever the app is in foreground, background, or even the app is killed i have done and tested it on the build and it also routes when ever the user clicks on it to the desired screen by placing the logic inside this function E.g -> see this function below  this.callingHandleNotification(Response)
i tried using this with hooks but it does not responds but in the life cycle it working properly 
async componentDidMount(){

 Notifications.setNotificationHandler({
      handleNotification: async () => ({
        shouldShowAlert: true,
        shouldPlaySound: true,
        shouldSetBadge: false,
      }),
    });

Notifications.addNotificationResponseReceivedListener(Response => {
      this.callingHandleNotification(Response)
    });
}
callingHandleNotification= asnyc (notification)=>{
//place your routing logic here 
}

**Comment by MWaqasHussain-dev** [comment] 2020-11-04 08:20
@cruzach

**Comment by byCedric** [comment] 2020-11-04 10:17
Hi @MWaqasHussain-dev, thanks for the issue. But, I'm not sure what's your issue here. You didn't follow the bug report template, assuming you experience a bug here. That's unfortunate because it helps you communicate your issue or bug to us, in a way that we can help find out what's going on. I'll close this issue because I'm not sure what's going on and don't have enough info to reproduce this issue on our end.

If you think this is an issue on our end, please open a new bug report with all the info we ask for in the template.

**Closed by byCedric** 2020-11-04 10:17 UTC
Labels: Notifications
