### ISSUE TITLE
Android standalone app crashes when using image prop on MapView.Marker

### ISSUE THREAD

**Issue by imshreyansh** [expo/expo#10898] opened 2020-11-02 13:39 UTC
### Summary of Issue 

Android standalone app crashes when using image prop on MapView.Marker
This is exactly the same issue 2 years ago:
#1431
It happens again in SDK39. It was working fine in SDK38

It happens again in SDK39. It was working fine in SDK38

I guess something has changed in asset bundling.

It's happening only for standalone Android apps.
Here is the log from adb logcat:

`unknown:ViewManager: Error while updating prop image
unknown:ViewManager: java.lang.reflect.InvocationTargetException
unknown:ViewManager: at java.lang.reflect.Method.invoke(Native Method)
unknown:ViewManager: at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:4)
unknown:ViewManager: at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:2)
unknown:ViewManager: at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:9)
unknown:ViewManager: at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:3)
unknown:ViewManager: at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:8)
unknown:ViewManager: at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:2)
unknown:ViewManager: at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:15)
unknown:ViewManager: at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:10)
unknown:ViewManager: at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:1)
unknown:ViewManager: at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:6)
unknown:ViewManager: at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:1)
unknown:ViewManager: at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:7)
unknown:ViewManager: at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:1)
unknown:ViewManager: at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
unknown:ViewManager: at android.view.Choreographer.doCallbacks(Choreographer.java:796)
unknown:ViewManager: at android.view.Choreographer.doFrame(Choreographer.java:727)
unknown:ViewManager: at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
unknown:ViewManager: at android.os.Handler.handleCallback(Handler.java:907)
unknown:ViewManager: at android.os.Handler.dispatchMessage(Handler.java:99)
unknown:ViewManager: at android.os.Looper.loop(Looper.java:216)
unknown:ViewManager: at android.app.ActivityThread.main(ActivityThread.java:7464)
unknown:ViewManager: at java.lang.reflect.Method.invoke(Native Method)
unknown:ViewManager: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
unknown:ViewManager: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
unknown:ViewManager: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
unknown:ViewManager: at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:248)
unknown:ViewManager: at android.content.res.Resources.getDrawableForDensity(Resources.java:939)
unknown:ViewManager: at android.content.res.Resources.getDrawable(Resources.java:879)
unknown:ViewManager: at android.content.res.Resources.getDrawable(Resources.java:854)
unknown:ViewManager: at versioned.host.exp.exponent.modules.api.components.maps.AirMapMarker.setImage(AirMapMarker.java:17)
unknown:ViewManager: at versioned.host.exp.exponent.modules.api.components.maps.AirMapMarkerManager.setImage(AirMapMarkerManager.java:1)
unknown:ViewManager: ... 25 more
unknown:DisabledDevSupportManager: Caught exception
unknown:DisabledDevSupportManager: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'image' of a view managed by: AIRMapMarker
unknown:DisabledDevSupportManager: at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:13)
unknown:DisabledDevSupportManager: at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:2)
unknown:DisabledDevSupportManager: at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:9)
unknown:DisabledDevSupportManager: at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:3)
unknown:DisabledDevSupportManager: at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:8)
unknown:DisabledDevSupportManager: at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:2)
unknown:DisabledDevSupportManager: at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:15)
unknown:DisabledDevSupportManager: at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:10)
unknown:DisabledDevSupportManager: at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:1)
unknown:DisabledDevSupportManager: at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:6)
unknown:DisabledDevSupportManager: at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:1)
unknown:DisabledDevSupportManager: at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:7)
unknown:DisabledDevSupportManager: at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:1)
unknown:DisabledDevSupportManager: at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
unknown:DisabledDevSupportManager: at android.view.Choreographer.doCallbacks(Choreographer.java:796)
unknown:DisabledDevSupportManager: at android.view.Choreographer.doFrame(Choreographer.java:727)
unknown:DisabledDevSupportManager: at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
unknown:DisabledDevSupportManager: at android.os.Handler.handleCallback(Handler.java:907)
unknown:DisabledDevSupportManager: at android.os.Handler.dispatchMessage(Handler.java:99)
unknown:DisabledDevSupportManager: at android.os.Looper.loop(Looper.java:216)
unknown:DisabledDevSupportManager: at android.app.ActivityThread.main(ActivityThread.java:7464)
unknown:DisabledDevSupportManager: at java.lang.reflect.Method.invoke(Native Method)
unknown:DisabledDevSupportManager: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
unknown:DisabledDevSupportManager: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
unknown:DisabledDevSupportManager: Caused by: java.lang.reflect.InvocationTargetException
unknown:DisabledDevSupportManager: at java.lang.reflect.Method.invoke(Native Method)
unknown:DisabledDevSupportManager: at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:4)
unknown:DisabledDevSupportManager: ... 23 more
unknown:DisabledDevSupportManager: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
unknown:DisabledDevSupportManager: at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:248)
unknown:DisabledDevSupportManager: at android.content.res.Resources.getDrawableForDensity(Resources.java:939)
unknown:DisabledDevSupportManager: at android.content.res.Resources.getDrawable(Resources.java:879)
unknown:DisabledDevSupportManager: at android.content.res.Resources.getDrawable(Resources.java:854)
unknown:DisabledDevSupportManager: at versioned.host.exp.exponent.modules.api.components.maps.AirMapMarker.setImage(AirMapMarker.java:17)
unknown:DisabledDevSupportManager: at versioned.host.exp.exponent.modules.api.components.maps.AirMapMarkerManager.setImage(AirMapMarkerManager.java:1)
unknown:DisabledDevSupportManager: ... 25 more`

### Steps to Reproduce
This is the Demo app to reproduce the error:
https://github.com/uchamb/expo-map-marker-test

It's only Android issue, works great on iOS.

This is already built APK if you want to debug yourself (You need to click "show markers" button to see error):
https://drive.google.com/file/d/1fEy3c5YZVUkfUOpNJaxNXjTuy4g-4bSS/view?usp=sharing

**Comment by imshreyansh** [comment] 2020-11-02 13:43
@byCedric  please help sir

**Comment by byCedric** [comment] 2020-11-02 15:00
Duplicate of #10846

**Closed by byCedric** 2020-11-02 15:00 UTC
Labels: Android, MapView, bug
