### ISSUE TITLE
expo-firebase-analytics: is there a way to enabled debugView?

### ISSUE THREAD

**Issue by mblodorn** [expo/expo#7745] opened 2020-04-08 17:49 UTC
There is no mention of how to do this in the documentation and I don't know if my custom events are being logged in my app because I can't enable debugView.

More info: https://firebase.google.com/docs/analytics/debugview

**Comment by cruzach** [comment] 2020-04-08 19:48
I'm not sure if this is available, @IjzerenHein might know more, though

We keep github reserved for bug reports so I'm going to close this since it's more of a question (possibly a good feature request)

**Comment by IjzerenHein** [comment] 2020-04-10 15:55
@mblodorn We currently have this in review and we're taking a closer look whether we can support this 👍

**Comment by mblodorn** [comment] 2020-04-10 16:22
thank you @IjzerenHein ! I can write the documentation if this feature become available :)

**Comment by IjzerenHein** [comment] 2020-04-15 14:02
Hey! A new version on `expo-firebase-analytics` has been published to NPM. It contains the debug-view support. You can enable it using the `setDebugModeEnabled` method. This is only possible on the Expo client though, on all other environments calling this function will throw an error.

Having said that. During testing we have seen that sometimes events don't appear in the Analytics dashboard, although these events have most definitely been delivered to the google analytics cloud end-point. It is at this moment still unclear why this is, but it could well be that the analytics back-end is overloaded or dropping events because of other reasons.

**Comment by mblodorn** [comment] 2020-04-15 16:00
thank you @IjzerenHein !

**Comment by Foosballfan** [comment] 2020-04-17 14:53
I'm trying to access this in the expo client but get `Error: setDebugModeEnabled is not available in this environment.`
Any advice on how to get it working?
I am on expo-firebase-analytics@2.2.0

**Comment by IjzerenHein** [comment] 2020-04-17 15:11
On what device/platform are you running it on?

**Comment by Foosballfan** [comment] 2020-04-17 16:09
I tried iOS 13 simulator and Samsung Note 10 physical, both had the same message.

**Comment by IjzerenHein** [comment] 2020-04-20 07:47
@Foosballfan 
Could you verify the following?
- Verify that you have a valid web-config in `app.json` (key: `expo.web.config.firebase`)
- Are you running this on the standard Expo client, or a custom-build; or a stand-alone build? (this only works on the standard client)
- Other methods work without errors, like calling `logEvent`

**Comment by Foosballfan** [comment] 2020-04-20 08:50
Ah, it's the first step that I'm not doing. I only have the Android and iOS config.

It is in Expo client and I see no errors from calling logEvent
The error about `setDebugModeEnabled is not available in this environment` just threw me off.

Thanks

**Comment by prathamudeshmukh** [comment] 2020-04-29 08:02
I get 
```No native ExpoFirebaseAnalytics module found, are you sure the expo-firebase-analytics's module is linked properly?```,
when trying to use `Analytics.setDebugModeEnabled(true)`.

Can you help me here, thanks.

**Comment by IjzerenHein** [comment] 2020-04-29 15:10
> I get
> `No native ExpoFirebaseAnalytics module found, are you sure the expo-firebase-analytics's module is linked properly?`,
> when trying to use `Analytics.setDebugModeEnabled(true)`.
> 
> Can you help me here, thanks.

Which SDK version are you using? This requires SDK 37.

**Comment by prathamudeshmukh** [comment] 2020-04-30 06:57
yes, I am upgrading to SDK 37 now, thanks.

**Comment by BenoitFroment** [comment] 2020-05-14 14:32
expo-firebase-analytics 2.3.0 here, with Expo SDK 37. iOS/Android/Web application configured in Firebase + app.json setup with path to files for both ios and android and web.config.firebase contains all of the required keys.

Can't see my events in Firebase nor use DebugView (Analytics.setDebugModeEnabled(true)). 

Anyone successfully used it ?

**Comment by IjzerenHein** [comment] 2020-05-18 08:52
@BenoitFroment Are you using it on the Expo client or a standalone build? Also, are you using it on Android or iOS?

**Comment by jennylihan** [comment] 2020-05-20 09:11
I have a similar issue to @BenoitFroment. I can only enable Debug Mode when I run my Expo app via my web browser because I have the[Google Analytics Debugger chrome extension installed](url). When I use Analytics.setDebugModeEnabled(true) via my Expo client, it says the function is undefined.

**Comment by IjzerenHein** [comment] 2020-05-20 13:21
@jennylihan Please make sure you have the latest version of `expo-firebase-analytics` installed and that you have a valid firebase web configuration in `app.json` (key `expo.web.config.firebase`).

**Comment by BenoitFroment** [comment] 2020-05-22 08:42
@IjzerenHein I'm using Expo Client on iOS simulator or my own iPhone X by flashing the QRcode.
@jennylihan Run your Expo App via web browser? What does it means ? React Native Debugger in Chrome ? I tried your extension w/o success.

**Comment by bilarslan** [comment] 2020-05-22 11:05
When trying to use Analytics.setDebugModeEnabled(true), I get "Analytics.setDebugModeEnabled(true) is not a function." error.
I am using Expo Client on my own Android device.

**Comment by yzalvov** [comment] 2020-05-22 16:25
@bilarslan, as @IjzerenHein said, you have to make sure the `expo-firebase-analytics` module you use is the latest. For me `yarn add expo-firebase-analytics` did the trick. The module was updated to `expo-firebase-analytics  2.3.0` and `Analytics.setDebugModeEnabled` is there to use.

Unfortunately `expo install expo-firebase-analytics` as suggested by `Expo SDK 37` docs doesn't provide you with latest version of that module, so use `yarn` instead. 

Notice that `Expo` will warn you about unexpected version after you `expo start` your project. Still, the `DebugMode`, as everything else, is keep working fine for me, so I don't mind the warning.

**Comment by brentvatne** [comment] 2020-05-22 18:08
perhaps we should change the semver matcher that we use for specifying compatibility of expo-firebase-analytics with a given sdk: https://github.com/expo/expo/blob/sdk-37/packages/expo/bundledNativeModules.json#L29

currently it's `~` but it seems like based on our usage in practice `^` could work too and not require us to update `bundledNativeModules.json` after publishing updates to expo-firebase-analytics @IjzerenHein. we'd just have to be careful not to add features with new native dependencies in a minor bump

**Comment by IjzerenHein** [comment] 2020-05-26 14:51
@yzalvov Ah that explains it. I wasn't aware that only patch versions were being installed. Thanks for finding this out and reporting it here 👍 

@brentvatne Yes that might be a solution. I guess we should have also updated `bundledNativeModules.json` when releasing the expo sdk. I'm not sure what the correct procedure is for that. @tsapeta what is the criteria for updating `bundledNativeModules.json` when releasing a new expo package ?

**Comment by srborines** [comment] 2020-06-05 18:53
Hi! I have being trying to use the debugView but I am not able to do it. I have followed the next steps:
1-Add with npm expo-firebase-analytics 2.3.0.
2- Create an app web at my Firebase Console.
3- Copy the configuration unde expo.web.config.firebase at my app.json
4- Call `Analytics.setDebugModeEnabled(true);` at my App.tsx
5- Execute my app in my phone with Expo cliente mode.

After following these steps I cant see any activity at my DebugView. 
Am I doing right?

**Comment by yzalvov** [comment] 2020-06-06 06:03
@srborines did you create any native app in Firebase and put the settings to your `app.js` as described by the docs? I guess only web settings might be not enough.

**Comment by srborines** [comment] 2020-06-08 09:20
@yzalvov yes, I had created also ios and android apps in firebase to my builds.

I have it already working, it just took some time to start working, like two hours after I created the web app in firebase console. 

I can see now the events but anyway not all events are being registered in my DebugView, I don't really understand why. I see them all logged in my expo console but I can't see them all at my DebugView.

**Comment by mikescott** [comment] 2020-11-22 11:13
I have the same issue. My details in app.json are correct, but calling `Analytics.setDebugModeEnabled(true)` only seems to print events to the console, they never appear in Firebase's DebugView. I'm using a managed workflow. Please re-open this issue.

**Comment by vitaly87** [comment] 2020-11-29 12:52
I have same issue as @mikescott  can this issue be reopen ?

**Comment by IjzerenHein** [comment] 2020-12-07 08:23
@mikescott, @vitaly87 Are you using the Expo client from the App-store or your own published app?

**Comment by chanonroy** [comment] 2021-02-01 14:21
I can confirm that I am seeing `logEvent` come through on both the console and in Firebase Analytics DebugView on iOS/Android just fine with the following ingredients:
- `"expo": 38.0.8`
- `"expo-firebase-analytics": "~2.4.1"`
- `"firebase": "7.9.0"`

Also, I had to make sure to use these two methods:
- `setDebugModeEnabled(true)`
- `setUnavailabilityLogging(true)`

One thing to note is to use the `debugDevice` dropdown to make sure that your correct device is being displayed.

**Comment by vimkestech** [comment] 2021-05-27 13:15
setDebugModeEnabled(true)
setUnavailabilityLogging(true)

please use asyn/await use  await Analytics.logEvent("login");
its working for me

**Comment by tsapeta** [comment] 2021-05-29 10:34
As the above solution seems to be working fine, I'm closing the issue 😉

**Closed by tsapeta** 2021-05-29 10:34 UTC
Labels: Firebase, FirebaseAnalytics

**Comment by quememo** [comment] 2024-12-27 18:31
this seems to be outdated now due to `expo-firebase-analytics` is no longer being maintained
