### ISSUE TITLE
Notificaitons data when app is closed

### ISSUE THREAD

**Issue by mgiorgi-github** [expo/expo#3531] opened 2019-02-18 17:19 UTC
### Environment
Expo SDK 32 on Mac 10.13.6

### Steps to Reproduce
Close the app and send push notification with data param

### Expected Behavior
The app read the data param

### Actual Behavior
When the app is foreground or background the app receive the data param but if it is closed the app opens but does not do anything

------------------------------------------------------------

When the app is foreground or background the listener on componentDidMount is triggered because the view is mounted… but if app is closed where i can read the data? The view is mounted after receive notification and the listener is not called, i’ve tried to use props.exp.notification on root component but there is no “notification” prop after open app by notification tap…

**Comment by AdamJNavarro** [comment] 2019-02-18 22:09
Hey @mgiorgi-github,

Would you be able to provide a Snack demonstrating this behavior? Without a repro case and any code it really isn't possible for us to debug this issue.

Cheers,
Adam

**Comment by mgiorgi-github** [comment] 2019-02-18 22:44
Hi, i’ve follow the example of documentation, the listener is triggered only if app is open, if the app is closed and tap on notification, the app opens but the listener is not called... i’ve insert a simple alert info it. With prevoius sdk this worked fine.

**Comment by expjess** [comment] 2019-02-19 02:10
Hey @mgiorgi-github - thanks for following the template (!), but since we aren't able to reproduce your issue with what you have, we aren't going to be able to be much help (even though we really really want to help you out!!) unless you are able to give us some more info. A Snack, as @AdamJNavarro mentioned, might do the trick, and you can also check out this guideline for creating a [minimum, complete verified example](https://stackoverflow.com/help/mcve).

**Comment by mgiorgi-github** [comment] 2019-02-19 08:04
Hi all, thanks for reply!
This is the Snack: https://snack.expo.io/@mgiorgi/push-notification

If you copy and paste this code into App.js of standalone app and  run "expo publish" in order to update the code you can see the issue.
1. if the app is open foreground or background all work fine
2. if the app is closed and tap the notification, the app is opens, show the token but not the data param

This is my push command:
exp.host/--/api/v2/push/send" -d '{
"to": "ExponentPushToken[mrOsZoOjTdPg4s92yeqw3I]",
"title": "Title",   
"body": "Text",
"data": { "action": "rating", "type": "A" }
}'

Thanks

**Comment by nebmesemaou** [comment] 2019-02-20 08:46
same here on ios

**Comment by mgiorgi-github** [comment] 2019-02-28 11:29
no news about this issue?
do you need other specifications?

**Comment by nebmesemaou** [comment] 2019-02-28 12:08
guys pls fix this

**Comment by AdamJNavarro** [comment] 2019-02-28 22:46
Hey @mgiorgi-github,

My apologies for the delay. Didn't realize this was actually a standalone issue. Is this occurring on both platforms for you or just iOS as @nebmesemaou indicates?

All the best,

Adam

**Comment by nebmesemaou** [comment] 2019-03-01 07:47
ya its just IOS specific 
Android working like a charm

**Comment by budziam** [comment] 2019-03-03 20:32
Hi, same issue here. Standalone iOS application is not handling notifications correctly.

### Steps to Reproduce:
1. Close application
2. Send notification
3. Click on the notification.

### Expected Behaviour:
Application is open and callback is fired (registered by Notifications.addListener)

### Actual Behaviour
Apllication is open, callback is **not** fired

**Comment by fortsm** [comment] 2019-03-10 18:33
Had same issue on ios standalone. Pls fix.

**Comment by novakben** [comment] 2019-03-10 21:45
Same here

**Comment by esamelson** [comment] 2019-03-12 00:20
Hi all -- sorry for the slow followup. I think our docs may be wrong here. It looks like in the case of opening the app from a notification, the notification data is passed as `props.exp.notification` on the root app component rather than calling the notifications listener.

I'm going to go ahead and close this as a duplicate of #3663 (which is newer but has a much more complete repro description). Please go ahead and follow that issue instead of this one for followup, but I believe the issue should be resolved by looking at `props.exp.notification` in this one case (and a docs fix on our end).

**Comment by nebmesemaou** [comment] 2019-03-13 06:44
also try props.exp.notification on root component but "notification" property still empty when i open app with notification

**Comment by mgiorgi-github** [comment] 2019-03-13 08:34
Same behavoiur for me

**Comment by theraku** [comment] 2019-03-14 11:48
+1

**Comment by deng-yc** [comment] 2019-03-15 02:26
+1

**Comment by esamelson** [comment] 2019-03-20 21:03
closing as a duplicate of #3663 - please track updates to this issue over there, thanks!

**Closed by esamelson** 2019-03-20 21:03 UTC
Labels: Notifications
