### ISSUE TITLE
Is there a way to execute a function in Expo Task Manager?

### ISSUE THREAD

**Issue by vrinch** [expo/expo#9578] opened 2020-08-06 04:28 UTC
I would like to know if there is a way to execute a function in expo task manager, I have tried severally but the app keeps crashing with an undefined error. Below is my sample code

````
import React from 'react';
import { Text, TouchableOpacity } from 'react-native';
import * as TaskManager from 'expo-task-manager';
import * as Location from 'expo-location';
import { connect } from 'react-redux';
import firebaseApi from '../src/firebase';

const LOCATION_TASK_NAME = 'background-location-task';

export default class Component extends React.Component {
  onPress = async () => {
    await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
      accuracy: Location.Accuracy.Balanced,
      timeInterval: 10000,
    });
  };

showLocation = (location) => {
  const { activeList } = this.props;
  console.log('current location:', location);
  firebaseApi.update({ activeList, location });
  //I need it to update my firebase realtime database 
}

  render() {
    return (
      <TouchableOpacity onPress={this.onPress} style={{marginTop: 100}}>
        <Text>Enable background location</Text>
      </TouchableOpacity>
    );
  }
}

TaskManager.defineTask(LOCATION_TASK_NAME, async ({ data, error }) => {
  if (error) {
    console.log(error);
    return;
  }
  if (data) {
    const { locations } = data;
    const latitude = locations[0].coords.latitude;
    const longitude = locations[0].coords.longitude;
    const loc = { latitude, longitude };
Component.showLocation(loc);
    // Storing Received Lat & Long to DB by logged In User Id
  }
});

const mapStateToProps = (state) => ({
  activeList: state.userDetail.activeList,
});
````

**Comment by guilhermepaula** [comment] 2020-08-06 15:20
Maybe duplicate of #9570

**Comment by vrinch** [comment] 2020-08-06 16:52
@guilhermepaula  its not a duplicate, I am trying to know if its possible to update my database with the new location gotten at intervals using the task manager

**Comment by guilhermepaula** [comment] 2020-08-06 17:05
@vrinch I still guessing its a duplicate. In SDK 37 I was able to call an API in defineTask with location gotten in startLocationUpdatesAsync, but in SDK 38 I gotta several erros like reported in #9570.

**Comment by vrinch** [comment] 2020-08-06 17:08
@guilhermepaula  can you please explain how you were able to call an api?
or maybe if its possible to run a function from the class in the task manager, because I have an array I want to pass from my redux store into my api

**Comment by guilhermepaula** [comment] 2020-08-06 17:27
@vrinch I just followed the [documentation](https://docs.expo.io/versions/latest/sdk/location/#locationstartlocationupdatesasynctaskname-options)

MyComponent.js
```
import * as Location from "expo-location";

export default class MyComponent extends React.Component {
  componentDidMount() {
    Location.startLocationUpdatesAsync("LOCATION_TASK_NAME", {
      accuracy: Location.Accuracy.Balanced,
      timeInterval,
      distanceInterval: 20,
    });
  }
}
```

App.js
```
import * as TaskManager from "expo-task-manager";

export default class App extends React.Component {
  render() {
    ...
  }
}

TaskManager.defineTask(
  "LOCATION_TASK_NAME",
  async ({ data, error }) => {
    if (error) {
      console.log("I GOT AN ERROR", error);
      return;
    }
    if (data) {
      const { locations } = data;
      const body = {
        latitude: locations[0].coords.latitude,
        longitude: locations[0].coords.longitude,
      };
      await callServiceMethod(requestBody);
    }
  }
);
```

**Comment by vrinch** [comment] 2020-08-06 17:40
thanks for your effort
but I dont know if you understand what I mean
I need to update my database with the latest location whether the app is in fore or background.
Along with an array that contains some values from my redux store
I want to know if its possible to run a function for the Class Component in Task Manager?
Kindly look at my code maybe you would get a better understanding of what I mean

**Comment by guilhermepaula** [comment] 2020-08-06 20:13
vrinch, I don't know much of Redux if its possible to access Redux store directly in TaskManager.defineTask.

**Comment by vrinch** [comment] 2020-08-06 20:16
Okay
But do you have an idea if a function can be executed in the task manager

**Comment by guilhermepaula** [comment] 2020-08-06 20:20
@vrinch Yes, I call an API in TaskManager with no problem until SDK 37, like in my code above.

**Closed** 2020-08-11 14:41 UTC
