### ISSUE TITLE
[SDK49] expo-updates makes SplashScreen image not Render on APK

### ISSUE THREAD

**Issue by islamouzou** [expo/expo#23363] opened 2023-07-07 11:26 UTC
### Minimal reproducible example

https://github.com/islamouzou/expo-updates-demo

### Summary

As the title says , when i create a project using the latest SDK 49 , even the default expo template without any change to the code , when i generate an apk using (npx eas build -p android --profile preview --local ) even on the cloud , while expo-updates is installed on my project (no need to use anything from the package , just install it ) the splash screen image disappears . i tried uninstalling expo-updates then rebuilding i got my splash screen back upon the app launch .

this behaviour is only in production release ( APK) , it doesn't happen in dev client .

i tried this with expo-updates@0.18.8 and 0.18.7 , 0.17.0 i got the same behaviour .

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 11.7.6
Shell: 5.8 - /bin/zsh
Binaries:
Node: 18.16.0 - /usr/local/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn
npm: 9.5.1 - /usr/local/bin/npm
Watchman: 2023.05.22.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.12.1 - /usr/local/bin/pod
SDKs:
Android SDK:
API Levels: 19, 27, 28, 31, 32, 33, 34
Build Tools: 27.0.0, 27.0.3, 28.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 34.0.0
System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom
Android NDK: 22.1.7171670
IDEs:
Android Studio: 2022.2 AI-222.4459.24.2221.10121639
Xcode: /undefined - /usr/bin/xcodebuild
npmPackages:
expo: ~49.0.0 => 49.0.0
react: 18.2.0 => 18.2.0
react-native: 0.72.1 => 0.72.1
npmGlobalPackages:
eas-cli: 3.15.0
expo-cli: 6.3.9
Expo Workflow: bare

**Comment by douglowder** [comment] 2023-07-08 22:02
I removed expo-updates from your `package.json`, and your owner info from `app.json`, then did the following steps:

```
yarn
eas init
eas build:configure
eas build -e preview -p android --local
```

This APK runs and shows the splash screen on the emulator.

I then did this:

```
npx expo install expo-updates
npx expo update:configure
eas build -e preview -p android --local
```

This APK also runs and shows the splash screen on the emulator.

So I am not able to reproduce the issue.

**Comment by goxr3plus** [comment] 2023-07-09 14:17
@douglowder  @islamouzou 

I have the same issue on all my devices after exporting to apk  i will send videos , i opened also an issue on expo forums on discord group [link](https://discord.com/channels/695411232856997968/1020197677327204412/threads/1127200572462866532) : 

How it works with expo SDK 49:


https://github.com/expo/expo/assets/20374208/f332d984-4135-4d50-a6cd-9231e211fad1


How it worked with expo SDK 48:



https://github.com/expo/expo/assets/20374208/ea35ebf4-cbca-47df-b8d2-0a99e7cbc704



This is a bad user experience and a bug , i can reproduce on every single real device . 

I have tested on S21 ultra , and some new xiaomi models.

**Comment by douglowder** [comment] 2023-07-09 17:31
@goxr3plus thanks for the information. Questions:

- Does this only reproduce on real devices, and not on emulator?
- If you start with the example app provided by @islamouzou , and then follow the steps that I did (see https://github.com/expo/expo/issues/23363#issuecomment-1627527224), are you able to see the problem occur on real devices?

**Comment by islamouzou** [comment] 2023-07-09 18:53
@douglowder for me it happens on both , and both emulator and phone I tested on were on Android 12 if it helps .

**Comment by goxr3plus** [comment] 2023-07-09 20:00
> @goxr3plus thanks for the information. Questions:
> 
> * Does this only reproduce on real devices, and not on emulator?
> * If you start with the example app provided by @islamouzou , and then follow the steps that I did (see [[SDK49] expo-updates makes SplashScreen image not Render on APK #23363 (comment)](https://github.com/expo/expo/issues/23363#issuecomment-1627527224)), are you able to see the problem occur on real devices?

It happens both for real devices and emulator but only when i install "expo-updates" package with Expo SDK 49.

I removed expo-updates, rebuild the project and published on Playstore and now the splash screen works correctly. Apparently it's an "expo-updates" issue.

**Comment by douglowder** [comment] 2023-07-09 21:42
@goxr3plus thanks for confirmation that you see the issue on emulator.

Did you try the steps I went through in my earlier comment?

**Comment by thespacemanatee** [comment] 2023-07-10 02:37
@douglowder I see the issue as well. You might have to launch the app several times, for me it starts bugging out after the second launch.

**Comment by ChromeQ** [comment] 2023-07-10 05:04
I am also facing the same issue on emulator and physical device.

I tried downgrading expo-splash-screen to 0.18.2 (the versions working on sdk 48) but it won't build, but sending an eas update does succeed but didn't display the splash screen.

I uninstalled expo-updates and splash screen displayed with expo-splash-screen@0.20.4. This certainly looks like a problem with sdk 49.

**Comment by ChromeQ** [comment] 2023-07-10 05:31
@douglowder I followed your steps in your comment on the repo provided by @islamouzou but with one addition, I added the following to the top of App.js to really highlight the problem as it loads so quickly it is hard to tell if the splash screen actually shows up:
```js
import * as SplashScreen from "expo-splash-screen";

SplashScreen.preventAutoHideAsync();
```
This will ensure the splash screen is not dismissed until I call `SplashScreen.hideAsync()` (which I don't so it should stay on screen indefinitely) and it does stay on screen when expo-updates is not installed. Once expo-updates is installed it goes straight into the app. Hope this helps reproduce the issue and find a solution

**Comment by douglowder** [comment] 2023-07-10 08:48
@ChromeQ thanks for this! I can now see the issue and reproduce it reliably.

**Comment by douglowder** [comment] 2023-07-11 02:51
We have identified the root cause.

There is a temporary workaround:

- At the end of your `android/gradle.properties` file, add the line

```
EX_UPDATES_ANDROID_DELAY_LOAD_APP=false
```

- If your project is managed (i.e. does not have native `ios` or `android` directories), then you should execute

```
npx expo prebuild --no-install --platform android
```

and then modify `android/gradle.properties` as above.

After this, EAS builds should have the correct behavior restored.

We are working on a proper fix for this issue.

**Comment by ChromeQ** [comment] 2023-07-11 13:32
Thanks for the update @douglowder , I gave it a try but I didn't get success but that's ok, I'll wait for the proper fix 👍️

**Comment by Pcpkomputer** [comment] 2023-07-17 16:23
i have similar issue with expo updates and after updated to SDK 49  and after adding EX_UPDATES_ANDROID_DELAY_LOAD_APP=false it still show something like this, before in SDK 48 it's work and no delay at all

Splash cover +   <item name="android:windowIsTranslucent">true</item>

[https://youtube.com/shorts/rVAh74qL_Tg?feature=share](url)

**Comment by ewein** [comment] 2023-07-17 18:41
I'm also seeing the same issue.

**Comment by nscerrimt** [comment] 2023-07-17 20:30
I am also facing the same issue.  @douglowder do you have an idea when the fix will be released please?

**Comment by Pcpkomputer** [comment] 2023-07-18 01:10
I will show you normal behaviour when using sdk48 and android:windowTranslucent to true, this all break after update to sdk49 @douglowder 

https://www.youtube.com/shorts/z_RJApuS6tU

**Comment by douglowder** [comment] 2023-07-18 02:51
@Pcpkomputer thanks for the videos -- it would be helpful for you to post a link to the project that was used to produce them. If setting `EX_UPDATES_ANDROID_DELAY_LOAD_APP=false` does not resolve the issue for you, then you may be seeing a different problem.

**Comment by ChromeQ** [comment] 2023-07-18 03:07
@douglowder I also didn't get success setting `EX_UPDATES_ANDROID_DELAY_LOAD_APP=false` in a managed project then building with eas. 

Has anybody had success with this workaround?

**Comment by douglowder** [comment] 2023-07-18 03:21
@ChromeQ I have merged a change that will allow you to change this setting for managed projects... new release will happen soon.

**Comment by Pcpkomputer** [comment] 2023-07-18 03:30
I have adding this line EX_UPDATES_ANDROID_DELAY_LOAD_APP=false before add that line there's no splash at all just white screen, but after add that splash is show but there's bug like 1 sec showing white screen and the splash is show like video I mentioned above, do you know what is the problem? because before it's not like this in sdk48  @douglowder

**Comment by ChromeQ** [comment] 2023-07-18 03:46
> @ChromeQ I have merged a change that will allow you to change this setting for managed projects... new release will happen soon.

Excellent @douglowder I will take a look and maybe apply with patch-package to test it out. Will the fox require a new build or will OTA expo-update be sufficient to roll out the fix to existing users?

**Comment by douglowder** [comment] 2023-07-18 04:03
@ChromeQ a new build would be needed

**Comment by douglowder** [comment] 2023-07-18 17:45
@Pcpkomputer just to be clear, setting `EX_UPDATES_ANDROID_DELAY_LOAD_APP=false` is not sufficient for your app, you actually have to revert https://github.com/expo/expo/commit/ee57fd9fcdf923a5a794665f6d3ebedd5376040e to restore correct behavior? That is very important info, thank you! We would really appreciate having a project that can reproduce this, if you can provide it.

**Comment by Pcpkomputer** [comment] 2023-07-18 23:38
After I doing some experiment with expo-updates especially with my component that fetch updates dynamically from expo server and delay it until the splashscreen and the main screen is ready / show + i added your lines EX_UPDATES_ANDROID_DELAY_LOAD_APP=false + change , it's working but just a delay about 0.3 sec and not noticeable like above one, so I think maybe this is because new react native 0.72
? Because i try to build again in sdk48 with RN 0.71 it's working like before and no delay at all, and when I revert expo-updates to https://github.com/expo/expo/commit/ee57fd9fcdf923a5a794665f6d3ebedd5376040e and also remove updates components, even I also revert expo-splash-screen, in sdk49 it still delay

![Screenshot 2023-07-19 at 06 22 35](https://github.com/expo/expo/assets/13756456/073daabb-d186-448b-bc28-0e7250fe7223)

https://github.com/expo/expo/assets/13756456/e5f009b3-ebf7-4f5d-bfbe-7043bd5cd58f

This happen in android pie, and android above like 12, is not affected by this, maybe i will stick to this for now until i find the fix, because I also need expo sdk49 and react native 0.72 for the newer update 😅

@douglowder to reproduce it simply create 2 project 1 with expo sdk48 and other one with exposdk49, bare react native and I use settings splash for cover and just adding this item in styles.xml <item name="android:windowIsTranslucent">true</item> for removing side effect of the solid color preview splash (https://user-images.githubusercontent.com/379606/120575871-b1e62600-c3d6-11eb-9435-5dee19791294.mp4)

Also this is only happen in my device with android pie version or maybe before android pie also

**Comment by douglowder** [comment] 2023-07-19 01:44
@Pcpkomputer thanks very much for the analysis and the repro steps! These will help us a lot. @Kudo

**Comment by singhayush1403** [comment] 2023-07-21 07:38
@douglowder is there a way to fix this without building android native directory?

**Comment by nscerrimt** [comment] 2023-07-22 07:25
> @ChromeQ I have merged a change that will allow you to change this setting for managed projects... new release will happen soon.

@douglowder In release 49.0.4, the same issue is still there for managed projects.  Do we have to make any config changes?

**Comment by douglowder** [comment] 2023-07-22 18:03
@singhayush1403 the android app must indeed be rebuilt.

@nscerrimt the release with the fix for managed projects is not yet published in a release. Once this happens, I'll add a note here.

**Comment by cowlabs-xyz** [comment] 2023-07-24 14:54
We are aiming to submit new build on friday, do you think we will be so lucky that a fix will already be released then? :)

**Comment by singhayush1403** [comment] 2023-07-24 15:20
@cowlabs-xyz you can fix the problem for now by using patch-package. I did it and it works

**Comment by rohankm** [comment] 2023-07-24 15:25
> @cowlabs-xyz you can fix the problem for now by using patch-package. I did it and it works

where is the patch-package file?

**Comment by douglowder** [comment] 2023-07-24 17:44
The fix is published in `expo-updates@0.18.11` (it is under the `next` tag, not `latest`).

**Comment by nscerrimt** [comment] 2023-07-25 08:56
@douglowder , I have updated expo-updates to 0.18.11 on my expo-managed app. I have now stopped using expo prebuild and I am not setting EX_UPDATES_ANDROID_DELAY_LOAD_APP=false anywhere.  However, I am still getting a white blank screen instead of my splash screen on production builds.

Do you know what may be the cause please?

**Comment by esipavicius** [comment] 2023-07-25 09:58
> The fix is published in `expo-updates@0.18.11` (it is under the `next` tag, not `latest`).

For iOS its working without `EX_UPDATES_ANDROID_DELAY_LOAD_APP`.
Fo android `EX_UPDATES_ANDROID_DELAY_LOAD_APP` it should be set to false. I saw by default is true. 

So I add `EX_UPDATES_ANDROID_DELAY_LOAD_APP=false` to `.env` file in main app dir. 
Also in `eas.json` builds -> env -> `"EX_UPDATES_ANDROID_DELAY_LOAD_APP": "false"`

**Comment by ChromeQ** [comment] 2023-07-25 10:41
Will there be some documentation updates @douglowder? This "delay" is not intuitive that it comes at the cost of sacrificing a splash-screen.
iirc there was a fallback delay for the updates, and if the update does not download and apply within that timeout then it will be applied the next time, and in that case I would see the splash-screen for longer (slow update) - is that not the case anymore even with this fix? I'd rather see a splash screen than the app logo for that delay

**Comment by cowlabs-xyz** [comment] 2023-07-25 13:33
We upgreded to eas-cli@3.17.0 and expo-updates@0.18.11 the splash screen now shows with

eas.json paremter
env: {
				"EX_UPDATES_ANDROID_DELAY_LOAD_APP": "false"
} 
for the relevant build profile

thanks!

**Comment by manuelmhtr** [comment] 2023-07-26 13:48
Is this related to #23599?

**Closed** 2023-07-28 04:25 UTC
Labels: Android, SplashScreen, Updates, Issue accepted

**Comment by Kudo** [comment] 2023-07-29 09:35
the above expo-bot comment is wrong. please upgrade expo@49.0.6 and expo-splash-screen@0.20.5 to fix the problem

**Comment by aelassas** [comment] 2023-07-30 19:39
I confirm. Upgrading to expo@49.0.6 and expo-splash-screen@0.20.5 fixes the issue. To upgrade, run the following commands:
```bash
yarn add expo@49.0.6
npx expo install --fix
```

**Comment by shafterihno** [comment] 2023-08-09 20:37
> I confirm. Upgrading to expo@49.0.6 and expo-splash-screen@0.20.5 fixes the issue. To upgrade, run the following commands:
> 
> ```shell
> yarn add expo@49.0.6
> npx expo install --fix
> ```

it worked for me aswell,finally after a lot of time spent on this 0.0
