### ISSUE TITLE
Cache-Control has a bug on Android

### ISSUE THREAD

**Issue by kreativka** [expo/expo#8598] opened 2020-06-01 20:19 UTC
## 🐛 Bug Report

expo doesn't respect ```fetch(url,{cache: 'no-store', headers:{'Cache-Control':'no-store'});```

Like in #1639 expo caches all HTTP requests to ```/data/user/0/host.exp.exponent/files/okhttp```
or ```/data/user/0/com.nameofaap/files/okhttp```. 
This works well with React Native 61.4, 62.2.

### Environment

  Expo CLI 3.21.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.17.0 - /usr/local/opt/node@12/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/opt/node@12/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild

Target: Android and expo SDK 36 and 37

### Steps to Reproduce

https://snack.expo.io/@kreativka/b025d9

```fetch(url,{cache: 'no-store', headers:{'Cache-Control':'no-store'});```

After pressing/clicking text, there is an alert with response.headers and the address of fetched URL. It will always be set to ```Cache-Control: Public, max-age=0``` no matter what is set on fetch() and what headers are sent back from server...

### Expected Behavior

It should respect cache: no-store, and do not cache anything when ```cache: no-store``` and ```Cache-Control: no-store``` are set.

### Actual Behavior

It doesn't respect cache: no-store. Stores all responses...

```
generic_x86:/data/user/0/host.exp.exponent/files/okhttp # ls
0658d2187eebbdcc611e1bea1ea3220e.0 
0658d2187eebbdcc611e1bea1ea3220e.1 
...
journal
```

### Reproducible Demo

https://snack.expo.io/@kreativka/b025d9

**Comment by brentvatne** [comment] 2020-06-01 22:25
i am able to reproduce this in expo client and in standalone apps.

i am not able to reproduce it in a bare project (both in rn 62 and 61). so this is indeed an issue with react-native on android in the managed expo environment

**Comment by mikemoate** [comment] 2020-06-16 09:58
@brentvatne when is this issue likely to get triaged? There are security implications here, with apps using Expo caching data locally and unencrypted that should not be cached.

**Comment by ide** [comment] 2020-07-01 20:26
It looks like the root cause lies somewhere in `expoview/src/main/java/host/exp/exponent/network/ExponentNetwork.java`. This file, which originally was named `android/app/src/main/java/host/exp/exponent/HttpClient.java`, sets up an OkHttp interceptor and caches all responses so that they are potentially available if the app goes offline. This behavior was implemented over four years ago in universe@2542e28c4b41b86824ee1f52177d911b016d4310.

If the app is online, responses that the server doesn't want to cache wouldn't be served, since the interceptor stores them with `max-age=0` (expire immediately). However, OkHttp implements "expire immediately" as "store this resource until a request tries to read it"; that is, the resource is inaccessible through the networking APIs and OkHttp, but it's accessible if you browse to your app's data files and look at the OkHttp cache.

We probably need to change this caching policy but need to be careful not to break updates or bundled assets. The new `expo-updates` has not yet been integrated into the development client and that will take time, but once it has, updates should be isolated from changes to `ExponentNetwork`.

@mikemoate We dedicate a portion but not the majority of our time to issues and with the high volume of issues, pragmatically speaking we can spend a limited amount of time on any issue on average. There are a few prerequisites to this issue and since it touches most network requests the scope of this change is potentially large. One of the things we've been doing is highlighting high-quality issues that identify the root cause and effects on the wider Expo ecosystem (e.g. https://github.com/expo/expo/issues/8971 is a great example) since those issues tend to be prioritized.

**Comment by to-str** [comment] 2020-07-14 09:52
We are currently hit by this problem, is there a workaround for the time being?

**Comment by ide** [comment] 2020-07-14 18:22
I don't think there is a shortcut. The diagnosis is described above: https://github.com/expo/expo/issues/8598#issuecomment-652629473

**Comment by to-str** [comment] 2020-07-15 11:13
We worked around server side, if anyone has the problem on rails. Our solution completely disables all caching possibilities to avoid `304` responses were you might not even have the data at all. This has solved the problem in our case, just leaving it here to maybe save somebody an hour or two.

In an initializer:
```ruby
Rails.application.config.middleware.delete Rack::ETag
```

In `application_controller.rb` (or whatever makes sense for you)
```ruby
  before_action :set_as_private

  def set_as_private
    expires_now
  end
```

**Comment by kreativka** [comment] 2020-07-15 12:31
> We worked around server side, if anyone has the problem on rails. Our solution completely disables all caching possibilities to avoid `304` responses were you might not even have the data at all. This has solved the problem in our case, just leaving it here to maybe save somebody an hour or two.
> 
> In an initializer:
> 
> ```ruby
> Rails.application.config.middleware.delete Rack::ETag
> ```
> 
> In `application_controller.rb` (or whatever makes sense for you)
> 
> ```ruby
>   before_action :set_as_private
> 
>   def set_as_private
>     expires_now
>   end
> ```

From what I gather you're sending headers without ETag, and with Cache-control: no-cache. This doesn't solve the issue here, you still have every request/response stored in ```/data/user/0/host.exp.exponent/files/okhttp``` .

**Comment by to-str** [comment] 2020-07-15 16:42
@kreativka You are correct, the problem we had primarily is that our client did not persist any data. So if the server gave the answer "304" which does not include data, our app fell flat on its face because of this. The rails changes at least make it work, and as we are not depending on caching at the moment, don't have a performance impact. The saving of the local cache data is another problem entirely, I agree. But we are in testing right now and not dealing with delicate data (yet).

**Comment by mikemoate** [comment] 2020-12-04 11:41
@brentvatne @byCedric with the release of Expo SDK40 expected soon, have the `expo-updates` changes referenced above been completed (they seem to be based on the SDK39 release notes)?

If so, then would it be sufficient here to modify the conditional at https://github.com/expo/expo/blob/master/android/expoview/src/main/java/host/exp/exponent/network/ExponentNetwork.java#L184 to include obeying the `currentResponseHeader` if it contains `no-cache` as well.

The bundled assets case would seem to already be handled by the dedicated interceptor at https://github.com/expo/expo/blob/master/android/expoview/src/main/java/host/exp/exponent/network/ExponentNetwork.java#L124

I'm keen to try and help progress this issue, given the obvious security implications (unencrypted caching of responses that are explicitly marked as do not cache).

**Comment by brentvatne** [comment] 2020-12-04 19:41
@mikemoate - we plan to revisit this for sdk 41, we'll keep you updated here

**Comment by mikemoate** [comment] 2021-06-03 10:04
@brentvatne did this make it into the Expo 41 release in the end?

**Comment by mishaaxe** [comment] 2022-02-15 17:48
The problem still exists even in version 44.0.6

**Comment by brentvatne** [comment] 2022-02-17 00:17
this should have been fixed in https://github.com/expo/expo/commit/c0afa77db08402f9d4c8772105701e53671eb78b

cc @esamelson

**Comment by ide** [comment] 2022-02-18 01:08
Closing since there are no more network interceptors on Android. Feel free to open a new issue if you see `fetch()` for URLs that send back `cache-control: no-store` (not `no-cache`) cause the HTTP response to be written to disk.

**Closed by ide** 2022-02-18 01:08 UTC
Labels: Android, Network
