### ISSUE TITLE
sqlite delete query not working

### ISSUE THREAD

**Issue by shakogegia** [expo/expo#2948] opened 2018-12-10 13:01 UTC
Hi, I try run this query and its not working, its not throwing error but not deleting row in database. 

I checked db file and id is correct.

`select` and `insert` queries are working fine, but `delete` query not works.

here is my code

```js
const db = Expo.SQLite.openDatabase('sample.db')

db.transaction(
   (tx) => {
   		tx.executeSql('delete from tasks where key = ?', [id])
   }
)
```

**Comment by brentvatne** [comment] 2018-12-10 19:03
hi can you please create a full reproducible example on https://snack.expo.io/?

also, let me know what operating system and sdk version this is happening with

**Comment by shakogegia** [comment] 2018-12-11 10:33
SDK 30, I just upgraded to 31, but still same

**Comment by ardyfeb** [comment] 2018-12-11 18:34
I have same issue,
Try place argument directly and use template literal: 
```
tx.executeSql(`delete from tasks where key = ${id}`, null)
```

**Comment by brentvatne** [comment] 2018-12-11 21:10
> hi can you please create a full reproducible example on https://snack.expo.io/?

^ please 😅

**Comment by shakogegia** [comment] 2018-12-12 09:18
@brentvatne I don`t get the idea of creating reproducible example snack, 

```
const db = Expo.SQLite.openDatabase('sample.db')

db.transaction(
   (tx) => {
   		tx.executeSql('delete from tasks where key = ?', [id])
   }
)
```

thats all the code snippet I use for deletion, and not works.

**Comment by ardyfeb** [comment] 2018-12-13 06:46
> @ardyfeb same :(
> 
> I dont know what to do.
> I checked query with some Sqlite GUI and works fine but with app its not working

Yes me too, before i use on app, i always test on sqlite GUI. If i use argument parameter to replace `?` on query, the result returning null but i use template literal everything works fine

**Comment by Davorak** [comment] 2019-06-04 18:19
Here is a working example based on the available todo app that uses sqlite:
https://snack.expo.io/SJXDSVVRN

At the bottom of the screen the items table is rendered as a json list.  It is updated when you add an item to the list and when you delete.

Deleting seems to be working find in this example.

**Comment by esamelson** [comment] 2019-11-02 00:35
Hi, it looks like this issue has been resolved so I'm going to close this. Please create a new issue with a full repro case (see [here](https://stackoverflow.com/help/minimal-reproducible-example) for how to create a solid repro example) if this still happens in any of the currently supported SDK versions.

**Closed by esamelson** 2019-11-02 00:35 UTC
Labels: SQLite

**Comment by zubairnahmed** [comment] 2019-12-20 21:03
This is still happening for me. Delete isn't working when SQLite is extracted from `expo-sqlite`. I'm using the managed flow. Can't quite replicate on https://snack.expo.io/ since I can't install the `expo-sqlite` package to test. Anyone else still facing this issue / know of way around?
