### ISSUE TITLE
standalone app archive issue 

### ISSUE THREAD

**Issue by juvham** [expo/expo#2074] opened 2018-08-06 07:01 UTC
Error: read ETIMEDOUT
    at _errnoException (util.js:992:11)
    at TLSWrap.onread (net.js:618:25)
Command /bin/sh failed with exit code 1

**Comment by jakubste** [comment] 2018-08-06 14:54
Could you provide more details?

**Comment by sjchmiela** [comment] 2018-08-16 06:39
Closing as a duplicate of https://github.com/expo/expo/issues/2075.

**Closed by sjchmiela** 2018-08-16 06:39 UTC
