### ISSUE TITLE
[expo-sqlite] Error: Call to function 'NativeDatabase.prepareAsync' has been rejected. Caused by: java.lang.NullPointerException: java.lang.NullPointerException]

### ISSUE THREAD

**Issue by bogdanbaghiu** [expo/expo#28176] opened 2024-04-12 15:56 UTC
### Minimal reproducible example

https://github.com/bogdanbaghiu/librarysqlite

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Hello community!

I'm building an application for a personal library and I found a bug in the expo-sqlite library. I have put a minimum repo so that it can be reproduced.

What I do is that I enter the first book, then I click on the Edit button and on the new screen I click on the Save button without making any modifications. The first time it works fine, the second time too; but the third one already gives me the error "Call to function 'NativeDatabase.prepareAsync' has been rejected.
→ Caused by: java.lang.NullPointerException: java.lang.NullPointerException".

The version of the **expo-sqlite** library is `13.4.0` and that of **expo** is `50.0.14`

I have uploaded a minimal reproducible example and also a small video where you can see the error:

![image](https://github.com/expo/expo/assets/37840937/150d6852-a5b3-4ed5-8ddf-d305cbf784e3)

https://github.com/expo/expo/assets/37840937/5bfeb2c7-ff57-4118-aaee-86c7ca5f80b6

### Environment

![image](https://github.com/expo/expo/assets/37840937/650fc8ef-505f-4dcb-aef6-d5c6256b89e0)

 

>   expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.5 - ~\node_modules\.bin\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0
        System Images: android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play Intel x86_64 Atom, android-UpsideDownCakePrivacySandbox | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: AI-223.8836.35.2231.11005911
    npmPackages:
      expo: ~50.0.14 => 50.0.15
      react: ^18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

![image](https://github.com/expo/expo/assets/37840937/de0f55e6-3a52-4a9b-a88f-eb4782bb41a9)

**Didn't find any issues with the project!**

**Comment by ALYREZA** [comment] 2024-04-14 21:55
I'm using `openDatabaseSync` function and getting this error message : 
` ERROR  Error: Call to function 'NativeDatabase.prepareSync' has been rejected.
→ Caused by: Error code : no such table: notes, js engine: hermes`

especially in android periodically working in emulator but when i run this command to create apk `eas build -p android -e preview` it failed on startup of application and wont work,
i'm using `"drizzle-orm": "^0.30.8",`
`"expo": "~50.0.15",`
` "expo-sqlite": "~13.4.0",` using next version `expo-sqlite/next"`

**Comment by Kudo** [comment] 2024-04-16 12:16
@bogdanbaghiu did you run the app through `npx run:android` or eas build or just expo-go? i encounter this error at first but then it's fine after re-run the app. then i cannot repro the `java.lang.NullPointerException` you mentioned.
```
 ERROR  [Error: Call to function 'NativeDatabase.prepareAsync' has been rejected.
→ Caused by: Error code : no such table: books]
```
do i miss any steps?

@ALYREZA the `no such table: notes` might be different problem than this NullPointerException one. please help to prepare a repro and create a new issue. thanks!

**Comment by bogdanbaghiu** [comment] 2024-04-16 13:33
Hello @Kudo 
Thanks for answering and sorry for not putting the commands to execute this error.

In my case I execute: npx expo start
Then I wait for the menu to load and press the a key on the keyboard. After pressing it, the app opens in the Android emulator and the first time it gives me that error. I kill all the applications and then I go back to the vscode console and press "a" again. The application opens again with the data loaded, but if I do the three steps then the error appears.

On the other hand, if I try to execute the command `npx run:android` that you execute it gives me an error, I think it is because I do not have it configured in my package.json

![image](https://github.com/expo/expo/assets/37840937/0f5de63d-1d5d-4021-bded-03f3a91d1acf)

Therefore it keeps happening to me. Please try it with the npx expo start command and then click on a. With that I think you can reproduce it

**Comment by Kudo** [comment] 2024-04-16 16:26
@bogdanbaghiu thanks for confirming that. it's interesting because the error happens only on expo-go but not `npx expo run:android` or `eas build`. i would take a further look later

**Comment by bayramarslan** [comment] 2024-04-17 21:14
Hello @bogdanbaghiu 

I was also encountering the same problem,
Reconnecting while opening the database solved my problem. I'm not sure if this is the right approach.

``` JS
const database = await SQLite.openDatabaseAsync(DATABASE_NAME, 	{
    useNewConnection: true
});
```

**Comment by bogdanbaghiu** [comment] 2024-04-17 22:03
Hello @bayramarslan .

Thank you for the comment and the parameter that you have told me. In theory, only the first time I run the npx expo start command with the Android phone connected it shows me a NativeDatabase.prepareAsync error but then it works fine. At first it may be a small patch, but I think having two open connections is not good. Furthermore, since the error continues to appear the first time, it means that something is not being executed correctly.

@Kudo Today I was thinking about what it could be and I think the solution may be that the database is executed as a promise and when trying to open it so quickly there is no time for the entire process to be executed and the database to be ready for it. This is regarding the error that appears the first time the app is installed, as it happened to you.

Regarding the error that I mentioned at the beginning of this incident, I thought that it may be because the system does not have time to close the transaction or that they conflict with each other and that they remain open without closing even though they are async. Errors are possible. Although I am not sure about this since I cannot mount the expo repository environment locally, since I have Windows.

**Comment by Kudo** [comment] 2024-04-25 11:58
it is possible that the issue was resolved by #27748 but we didn't backport the issue to expo-go. since we are prepare expo-go for sdk 51.
could you try to use [development builds](https://docs.expo.dev/develop/development-builds/introduction/) than expo-go and check whether it works for you?

**Comment by bogdanbaghiu** [comment] 2024-05-01 19:38
ok @Kudo , I try and will tell if works

**Comment by esobine** [comment] 2024-05-10 14:02
I notice that I had this error on expo go:

![image](https://github.com/expo/expo/assets/83951935/3a7bdad8-1c6a-4293-8616-b96daa433cf7)

When I try to request a database that has more than 1 table, I am only able to retrieve data from a single table.

**Comment by Kudo** [comment] 2024-05-10 17:33
@bogdanbaghiu the line looks wrong from your repro. it will cause concurrent db queries. changing the initial loading to true will resolve the problem.

@esobine  please prepare a repro, that would us to identify the problem easier.

**Comment by esobine** [comment] 2024-05-10 19:35
@Kudo Here my repro https://github.com/esobine/expo-db-prob related to a problem with requesting an existing database. I have written a readme that explains my issue in more detail. I am very new to Expo and I hope it will help to identify the potential problem. Sorry in advance if I do not address this issue correctly.

**Comment by Kudo** [comment] 2024-05-11 10:02
@esobine nice repro! the problem of your case is that you didn't use the `dbLoaded` somewhere. when db is not loaded yet, you should prevent render to your `<BoardScreen>`.

since you are in sdk 51 and i saw you've tried to use the new `assetSource`, then you could prevent boilerplate code to import existing database from your assets.
1. you should first run `adb uninstall host.exp.exponent` to remove expo-go first since you may have local database already. by default, we don't overwrite existing db from assets.
2. here is the patch to your code
```diff
diff --git a/App.js b/App.js
index 4bcf142..7f3f604 100644
--- a/App.js
+++ b/App.js
@@ -6,37 +6,12 @@ import { Ionicons } from "@expo/vector-icons";
 import StatsScreen from "./src/components/StatsScreen";
 import HabitsScreen from "./src/components/HabitsScreen";
 import BoardScreen from "./src/components/HomeScreen";
-import * as FileSystem from "expo-file-system";
-import { Asset } from "expo-asset";
 import { ActivityIndicator } from "react-native";
 import { SQLiteProvider } from "expo-sqlite";

-const loadDataBase = async () => {
-  const dbName = "test.db";
-  const dbAsset = require("./assets/test.db");
-  const dbUri = Asset.fromModule(dbAsset).uri;
-  const dbFilePath = `${FileSystem.documentDirectory}SQLite/${dbName}`;
-
-  const fileInfo = await FileSystem.getInfoAsync(dbFilePath);
-  if (!fileInfo.exists) {
-    await FileSystem.makeDirectoryAsync(
-      `${FileSystem.documentDirectory}SQLite`,
-      { intermediates: true }
-    );
-    await FileSystem.downloadAsync(dbUri, dbFilePath);
-  }
-};
-
 const Tab = createBottomTabNavigator();

 export default function App() {
-  const [dbLoaded, setDbLoaded] = useState();
-
-  useEffect(() => {
-    loadDataBase()
-      .then(() => setDbLoaded(true))
-      .catch((e) => console.error(e));
-  }, []);
   return (
     <SafeAreaView style={{ flex: 1 }}>
       <NavigationContainer>
@@ -50,7 +25,7 @@ export default function App() {
         >
           <SQLiteProvider
             databaseName="test.db"
-            /* assetSource={{ assetId: require("./assets/test.db") }} */
+            assetSource={{ assetId: require("./assets/test.db") }}
             useSuspense
           >
             <Tab.Navigator
```

**Comment by esobine** [comment] 2024-05-11 14:42
Thank you Kudo for your explanations, now I have a clearer understanding of how it functions and why it was not working previously!

**Comment by barathiofficial** [comment] 2024-05-16 21:12
Check this: https://orm.drizzle.team/docs/get-started-sqlite#expo-sqlite

![image](https://github.com/expo/expo/assets/80629680/cdc6ccd9-c165-403c-8e99-ec44c98aa64c)

**Comment by MarceloGoncalvesBraga** [comment] 2024-06-18 17:58
import * as SQLite from "expo-sqlite";

class Sqlite3Connector {
  async configureConnection() {
    const databaseConnector = await SQLite.openDatabaseAsync("newdatabase.db", 	{ useNewConnection: true });
    databaseConnector? console.log("Database Connected") : console.log("Database Not Connected");
    return databaseConnector;

  }
// consultas individual
  async query(sql, params) {
    const databaseConnector = await this.configureConnection();

    try {
      const result = await databaseConnector.runAsync(sql, params);
      const row = { "Linhas Afetadas ":result.changes };
      return row;
      
    } catch (error) {
      console.error(error);
      return error;
    } finally {
      await databaseConnector.closeAsync();
    }
  }
}
// exemplo  do meu uso

 async updateCodeTitle(title, id) {
    const sql = `UPDATE codigos SET title = ? WHERE id = ? `;
    const params = [title, id];
    const result = await this.databaseConnector.query(sql, params);
    return result ? result : false;
  }
// utilizando withTransactionAsync com varias alteracoes ao mesmo tempo
  async query(sql, params) {
    const databaseConnector = await this.configureConnection();

    try {
      await databaseConnector.withTransactionAsync(async () => {
       const result = await databaseConnector.runAsync(sql, params);
       const nss = await databaseConnector.runAsync('UPDATE codigos SET subtitle = ? WHERE id = ?', ["xxxxxx", 1]); 
      });
      const result = await databaseConnector.runAsync(sql, params);
     const row = { "Linhas Afetadas ":result.changes };
     return row;
      
    } catch (error) {
      console.error(error);
      return error;
    } finally {
      await databaseConnector.closeAsync();
    }
  }
** funciona assim sem erro com sqllite 14 e expo 51, espero que ajude alguem

**Comment by Kudo** [comment] 2024-06-24 14:52
i am going to close this issue since the issue should be resovled by #27748. if it still happen to you, please recreate a new issue with repro example. i will investigate further. thanks!

**Closed by Kudo** 2024-06-24 14:52 UTC
Labels: SQLite, Issue accepted

**Comment by devmaster518** [comment] 2024-08-11 06:02
Thanks, @bayramarslan 
It helped me a lot.
