### ISSUE TITLE
Expo crashes on specific Android device: TC510K (zebra TC51)

### ISSUE THREAD

**Issue by Snabel** [expo/expo#1144] opened 2017-12-21 09:01 UTC
First time installing the App. Crashes imediately on startup. Tried installing from app-store and I got it too by running "yarn run android" following the Get started section of the react native documentation. 

Model:
TC510K (zebra TC51)

Android version:
6.0.1

**Comment by Snabel** [comment] 2017-12-21 09:07
Working fine on my other android device (Galaxy 7). I need to have it working on the Zebra device since we are utilising a hardware scanner on that device.

**Comment by anp** [comment] 2017-12-21 20:53
Hi! Sorry to hear you're having problems. Do you think you could help us diagnose the problem here by providing [device logs](https://docs.expo.io/versions/latest/guides/logging.html#view-logs-from-android-device-or-emulator)? Doesn't look like it'll be easy for us to pick up one of these to reproduce the issue, but we might be able to figure out what's wrong with the system logs. Thanks!

**Comment by jesseruder** [comment] 2018-02-07 05:00
Closing this until we have more information.

**Closed by jesseruder** 2018-02-07 05:00 UTC
Labels: project: android-runtime, status: needs more info

**Comment by mistre83** [comment] 2018-04-12 12:26
At 12/04/2018 i have the same problem with TC51

**Comment by bealoui1** [comment] 2018-04-24 13:17
I investigated further: I found other posts where people where having NoSuchMethodError in their android app. Their fix was to upgrade the gradle plugin.

So, I cloned the expo repo, upgraded the project to Android Studio 3.2 and gradle to 4.4.
Also had to fix builkd.gradle file due to the deprecation of android-apt.
After compiling, the fresh apk installs and works fine on a Zebra TC70x device.
