### ISSUE TITLE
[Urgent] Sound doesn't play on Android (expo-av@8.0.0, SDK 37)

### ISSUE THREAD

**Issue by n-sviridenko** [expo/expo#8174] opened 2020-05-06 11:29 UTC
### Environment

```
  Expo CLI 3.19.2 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.8
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
```

### Steps to Reproduce

You can find the reproducible example here: https://github.com/n-sviridenko/expo-av-android-bug

**Upgrading `expo-av` doesn't solve the issue.**

### Expected Behavior

Sound gets played on Android

### Actual Behavior

Sound doesn't play

### Reproducible Demo

You can find the reproducible example here: https://github.com/n-sviridenko/expo-av-android-bug

**Comment by n-sviridenko** [comment] 2020-05-06 11:29
We cannot launch because of this and trying to solve this for a few days already.

**Comment by byCedric** [comment] 2020-05-07 11:09
Hi @n-sviridenko! thanks for the issue report and repro, I can confirm the video audio is not working when changing the audio mode. I tried setting it to default or provide no other options at all. (cc @bbarthec)

> For reproduce reference:
> The video link in the code didn't work for me, but using this [Vimeo URL](https://vimeo.com/1084537) and fetching the MP4 URL with [this site](http://savevideo.me/) worked for me.

**Comment by n-sviridenko** [comment] 2020-05-08 08:01
Hi @byCedric . Yes, we also figured that out.

However, we have another issue now: https://github.com/expo/expo/issues/8209

**Comment by IjzerenHein** [comment] 2020-07-30 12:31
I've tried to reproduce this using the given repo but was unable to (running on Android emulator API 30). The vimeo link didn't work but after creating a new one, it played audio and video for multiple videos just fine.

Please update the repo with a reproduction case and provide more details (android version etc).
Also, the `expo-av-android-bug` is missing the `debug.keystore` file.

**Comment by IjzerenHein** [comment] 2020-10-26 10:11
Closing this issue as we have been unable to reproduce it. Feel free to reopen with new reproduction steps if this problem still occurs for you.

**Closed by IjzerenHein** 2020-10-26 10:11 UTC
Labels: AV, Android, Bare Workflow, Video, bug, needs repro, status: needs more info
