### ISSUE TITLE
@expo/cli 46.0.9 - nothing seems to work as before (I have read and followed the blog)

### ISSUE THREAD

**Issue by GreenCurveDev** [expo/expo#18852] opened 2022-08-26 16:39 UTC
### Summary

Default project (npx expo init ABC) cannot be  ejected using npx expo prebuild as recommended in https://blog.expo.dev/the-new-expo-cli-f4250d8e3421

Gives error **Error: [android.dangerous]: withAndroidDangerousBaseMod: Failed to find the instance of sharp used by the global sharp-cli package.**
**"You can install it using `npm install -g sharp-cli@^1.10.0`."**
**For prerequisites, see: https://sharp.dimens.io/en/stable/install/#prerequisites** 
Note:  'https://sharp.dimens.io/en/stable/install/#prerequisites' does not exist!

Running **npm install -g sharp-cli@^1.10.0`** gives more errors
"npm ERR! command C:\Windows\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm ERR!   VError.cpp
npm ERR!   VInterpolate.cpp
npm ERR!   VImage.cpp
npm ERR!   win_delay_load_hook.cc
npm ERR!      Creating library C:\Users\green\AppData\Roaming\npm\node_modules\sharp-cli\node_modules\sharp\build\Release\libvips-cpp.lib and object C:\Users\green\AppData\Roaming\npm\node_modules\sharp-cli\node_modules\sharp\build\Release\libvips-cpp.exp
npm ERR!   Generating code
npm ERR!   Previous IPDB not found, fall back to full compilation."

In summary, **nothing** seems to work with this new 'local' version of expo-cli

I have been using expo for over a year now and never encountered any of these issues until upgrading

### What platform(s) does this occur on?

Not Applicable

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.4 - ~\AppData\Roaming\npm\npm.CMD
    npmPackages:
      expo: ~46.0.9 => 46.0.9
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.4 => 0.69.4
      react-native-web: ~0.18.7 => 0.18.8
    Expo Workflow: bare

### Minimal reproducible example

npx expo init ABC
cd ABC
npx expo start - /* runs app fine */
npx expo prebuild - /* fails with errors shown in description */

**Comment by GreenCurveDev** [comment] 2022-08-26 19:29
Hi Amandeep, many thanks for responding - appreciate it. I will try your suggestions and report back . Re: 'other' things - this referred to behaviour of existing projects that were upgraded to the latest expo version. These were already "prebuilt" but ceased to operate as before - specifically native packages (eg camera) were non longer accessible when running the app. There were also issues using Expo Go which seemed to now seem to require tunnelling enabled (though I have no idea why) to access - perhaps unrelated but I will try and isolate to find out. Btw, in order to progress with a time critical piece of work I have downgraded to 46.0.8 which does not seem to have the same issues.

**Comment by amandeepmittal** [comment] 2022-08-26 21:20
Whenever you will be able to isolate the issue you were facing with Expo Go, please go ahead and open a new issue for that.

About the camera issue, are you referencing to #18234 that you opened a while back? As suggested, please look into the possible workarounds for that since it is known and not necessarily related to Expo SDK 46 or the new Expo CLI.

The version `46.0.9` only bumps to the latest React Native version and was released only a few moments ago [PR](https://github.com/expo/expo/pull/18841). Also, I'd recommend you to use `npx create-expo-app` and `npx expo <command>` within the project repository to use local CLI so that `npx expo prebuild` works fine with the Expo project.

In your reproducing example instructions, you used global CLI to create the new project. If for some command that is not available on the local CLI, to use the global CLI, you can use `expo-cli <command>`.

Feel free to open another issue if you find something that is hindering your progress. I am going to close this one for now.

**Closed by amandeepmittal** 2022-08-26 21:20 UTC
Labels: needs review
