### ISSUE TITLE
Font.loadAsync throws exception on ejected app

### ISSUE THREAD

**Issue by pintusoliya** [expo/expo#5649] opened 2019-09-14 10:55 UTC
### Environment
"OS": "Mac OS"
"iOS": "12"
"sdkVersion": "31.0.0",
"expo": "^32.0.0",
"react": "16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",

Hi, I recently detached SDK 31. I’m trying to load in fonts and icons for async caching. I got following error. If any one can help then comment here.

[Unhandled promise rejection: Error: File 'file:///Users/pc/Library/Developer/CoreSimulator/Devices/951FE537-3500-4C48-BFBD-76B79BDB0D4A/data/Containers/Data/Application/99AD884C-8FB6-4E14-8FB9-0B7334326163/Library/Caches/ExponentExperienceData/%2540pintusoliya%252Fstatiq/ExponentAsset-4ac1aa9324ac7dc3513d26a25b08a5f6.otf' isn't readable.]

**Comment by AdamJNavarro** [comment] 2019-09-16 17:56
Hey @pintusoliya,

It looks like your versions are all out of order. You have SDK version set to 31 but have 32 values for `expo` and `react-native`. Can you make sure you have unified versions and see if that helps? Another thing of importance is that you will need to upgrade to SDK33 if you intend to release the project on the Play Store as it now requires 64-bit support which is available with SDK33+. I'm going to close this issue but please feel free to open a new one if you have unified your versions and can provide a reproducible example of the error.

Cheers,
Adam

**Closed by AdamJNavarro** 2019-09-16 17:56 UTC
Labels: bug

**Comment by Changdao** [comment] 2019-09-21 08:33
I met this issue.
The root cause of my case is that there is no 'ios.publishManifestPath' key specified in app.json,  I switch Eject mode and managed mode frequently, occasionally the key is removed as version merge.

A little suggestion: I investigated this issue in a bout 4 hours, I added some debug log into expo-font, expo-file-system etc. Once I notied that the asset was treated as downloaded, I known that the asset wasn't bundled into app. Then I checked the build setting, I noticed that there is a post script for expo to bundle assets, this is the first time I build for IOS, then I went to check the build log, the expo shell print a warn:
```
Skipped assets bundling because the 'ios.publishManifestPath' key is not specified in the app manifest.
```
As I experienced, the asset bundle of expo made me very confused, hope that the expo can promote  the document, build messages and debugging information can help the newbie very much.
