### ISSUE TITLE
Screen Orientation to landscape utilises half of the screen

### ISSUE THREAD

**Issue by NRHunsdale** [expo/expo#17700] opened 2022-05-31 13:43 UTC
### Summary

When the screen orientation changes to landscape the content is only taking up half of the screen. In the Expo Go app, things work as expected, but _not_ in the development build (_using_ `expo start --dev-client`). 

I did read the [warning](https://docs.expo.dev/versions/latest/sdk/screen-orientation/#warning) outlined in the Expo Screen Orientation documentation however, this issue is explained to only pertain to iPad's and the screenshot shared below is an iPhone Mini 13.

![orientation_problem](https://user-images.githubusercontent.com/6906036/171184794-cbe0bef1-eb2b-45ce-8a81-2dbe67d1c48a.jpg)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45.0.0

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0
      expo: ^45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@villa_control/sdk45-expo-screen-orientation-half-screen

**Comment by fencer-yd** [comment] 2022-06-06 12:21
Android platform does not have this problem, only ios has this problem

**Comment by fencer-yd** [comment] 2022-06-14 04:08
@NRHunsdale I tried it according to the latest expo45 version and found that this was not a problem with expo. Later, I introduced react-navigation 6.0 and found that it was related to the routing presentation form of react-navigation. The default screen presentation was card, so I replaced the presentation with After `presentation: 'fullScreenModal'` everything works fine.

**Comment by NRHunsdale** [comment] 2022-06-14 10:28
> @NRHunsdale I tried it according to the latest expo45 version and found that this was not a problem with expo. Later, I introduced react-navigation 6.0 and found that it was related to the routing presentation form of react-navigation. The default screen presentation was card, so I replaced the presentation with After `presentation: 'fullScreenModal'` everything works fine.

Thanks for investigating @fencer-yd 🙏

**Comment by brentvatne** [comment] 2022-06-28 02:10
duplicate of #17724

**Closed by brentvatne** 2022-06-28 02:10 UTC
Labels: needs review

**Comment by nn1900** [comment] 2022-06-30 10:56
any updates on this? it's quite troublesome when testing user interface in different screen orientations and tuning the transitioning performance while rotating screen...

**Comment by nn1900** [comment] 2022-07-01 09:46
see workaround here: https://github.com/expo/expo/issues/17724#issuecomment-1172120835
