### ISSUE TITLE
Android standalon app crahes when MapView Marker has a custom image.

### ISSUE THREAD

**Issue by spierr** [expo/expo#1737] opened 2018-05-08 13:12 UTC
### Environment

"expo": 27.0.1
 "react": 16.3.1
 "react-native": https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz

### Steps to Reproduce

Open a standalon app in Android with a MapView Marker that has a custom image. The app crashes and you can get this message from the logcat: "JSApplicationIllegalArgumentException: Error while updating property ‘image’ of a view managed by: AIRMapMarker"

### Reproducible Demo

https://snack.expo.io/@spierr/errorsample

**Comment by EvanBacon** [comment] 2018-05-08 23:08
I feel like this could be related to something in react-native-maps https://github.com/react-community/react-native-maps/issues/1073 I think the version of maps in expo is the exact same, maybe a little older

**Comment by esamelson** [comment] 2018-05-10 23:08
I'm going to close this as a duplicate of https://github.com/expo/expo/issues/1431 .

**Closed by esamelson** 2018-05-10 23:08 UTC
