### ISSUE TITLE
[docs] Tables which has a pipe in a code are broken

### ISSUE THREAD

**Issue by Nkzn** [expo/expo#10499] opened 2020-10-01 15:35 UTC
SSIA. The `|` in the code (`) is recognized as a table separator.

code:

```markdown
| Name                                    | Type                              | Description                                                                                                                                                         |
| --------------------------------------- | --------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [iosClientId][g-creds]                  | `string | undefined`              | The iOS client id registered with Google for use in the Expo client app.                                                                                            |
```

capture:

<img width="824" alt="スクリーンショット 2020-10-02 0 16 16" src="https://user-images.githubusercontent.com/434227/94828786-ca1b3500-0444-11eb-9130-6dc791ee879a.png">

page: https://docs.expo.io/versions/v39.0.0/sdk/google/

This was caused by #10177 . MDX v1 is GFM compliant, and GFM has same problem.

| Name                                    | Type                              | Description                                                                                                                                                         |
| --------------------------------------- | --------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [iosClientId][g-creds]                  | `string | undefined`              | The iOS client id registered with Google for use in the Expo client app.                                                                                            |

this can be solved with escaping the pipe in GFM.

```markdown
| Name                                    | Type                              | Description                                                                                                                                                         |
| --------------------------------------- | --------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [iosClientId][g-creds]                  | `string \| undefined`              | The iOS client id registered with Google for use in the Expo client app.                                                                                            |
```

| Name                                    | Type                              | Description                                                                                                                                                         |
| --------------------------------------- | --------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [iosClientId][g-creds]                  | `string \| undefined`              | The iOS client id registered with Google for use in the Expo client app.                                                                                            |

but, in the MDX v1.6.18, `\` is remaining.

<img width="1134" alt="スクリーンショット 2020-10-02 0 31 08" src="https://user-images.githubusercontent.com/434227/94830531-9f31e080-0446-11eb-9825-c017856d8876.png">

This is MDX's issue. https://github.com/mdx-js/mdx/issues/1285

# workaround

revert #10177 😢

**Comment by ide** [comment] 2020-10-01 20:35
We've merged a partial fix (https://github.com/expo/expo/pull/10500) but it looks like a bug with MDX still causes botched rendering, it's just less botched now (you can figure out what to do, it just looks broken).

**Comment by barthap** [comment] 2020-10-02 13:46
#10311 is related

https://docs.expo.io/versions/v39.0.0/sdk/app-auth/#tokenresponse is also affected

**Comment by byCedric** [comment] 2020-10-05 13:57
To fix this issue fully, we probably have to wait until https://github.com/remarkjs/remark/pull/536 is merged and released. It's an issue within remark's internals. Until then, we can do two things:

1. "Cheat" our way around the pipe character (`|`), by using a similar [character like the divisor (`∣`)](https://en.wikipedia.org/wiki/Vertical_bar).

2. Wrap code blocks with `<InlineCode>string \| null</InlineCode>` to allow character escaping (works around the remark parser).

In the example below, the first line has the divisor character and second line has `<InlineCode>` wrapped and escaped `|`.
![Screenshot 2020-10-05 at 15 55 46](https://user-images.githubusercontent.com/1203991/95088440-4488d500-0723-11eb-917b-5b8514666498.png)

@ide Which one do you prefer? I think 1 is the simplest solution, but also might be too confusing for people to contribute with. 2 is very expressive and increases the code (decreases readability from markdown). Either way, this would solve our current issue until the fix is released.

**Closed** 2020-10-05 15:38 UTC
Labels: docs

**Comment by ide** [comment] 2020-10-05 16:51
I agree the second option is better. The issue is non-obvious and needs to be communicated instead of hidden behind a different unicode character since this is text that people type. The divisor character would make sense to me if it were autogenerated on each build and never typed by people, but otherwise no one is going to know they need to type it. Also it presumably breaks copy/pasting from the docs.

**Comment by wooorm** [comment] 2020-10-07 14:20
It’s not remark internals. It’s MDX internals
