### ISSUE TITLE
Dev menu doesn't show up any more when you shake the device on Android

### ISSUE THREAD

**Issue by bill-pairaktaridis** [expo/expo#7713] opened 2020-04-07 13:27 UTC
### Environment

```

  Expo CLI 3.17.18 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.8.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6200805
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.6 => 37.0.6 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.3.7 => 4.3.7 
    npmGlobalPackages:
      expo-cli: 3.17.18
```

Target: Android

### Steps to Reproduce

Shake device

### Expected Behavior

Should show the new dev menu

### Actual Behavior

Doesn't show anything

**Comment by IjzerenHein** [comment] 2020-04-07 14:34
Hey! I've been trying but have been unable to reproduce this. Could you try rebooting your phone and see whether it has any effect?

**Comment by chrisbobbe** [comment] 2020-04-07 23:36
And you're using a physical device, right, not the emulator?

**Comment by Chofito** [comment] 2020-04-08 01:21
I have the same problem, it happens when the project is run without having opened the expo app and it doesn't happen in new projects.
There are other issues related to the status bar and keyboard moving screens up, any intention of releasing these fixes before version 38?

**Comment by bill-pairaktaridis** [comment] 2020-04-08 07:31
Rebooted my phone and still nothing. This was not an issue prior to the upgrade.

**Comment by tylerc** [comment] 2020-04-08 16:48
I'm seeing this on an emulator with Expo 37. If I use `expo start` and then `Run on an android device/emulator` none of the normal actions (CTRL+M nor `./adb shell input keyevent 82`) will get the Dev menu to open. If I switch out of the app, open the installed Expo app, and then switch back to my app it starts working.

The emulator I'm using is a Pixel 2 running Android Pie/API 28. I start it with `-wipe-data` every time for a completely clean emulator, so nothing residual is causing this.

**Comment by cruzach** [comment] 2020-04-08 20:14
Tested this on both a OnePlus physical device, and on a Pixel emulator, and the shake gesture and CMD+M both work for me in bringing up the dev menu. If you're seeing this behavior, please try to provide as much information as possible to help us reproduce it

**Comment by Tyler-Pritchard** [comment] 2020-04-08 21:52
> I have the same problem, it happens when the project is run without having opened the expo app and it doesn't happen in new projects.

Was having the same issue w/ an iPhone6 - shaking the phone didn't bring up any menu at all.  Tried closing everything and relaunching the project with Expo already open-- it works now!  Thank you!

**Comment by Tyler-Pritchard** [comment] 2020-04-08 21:53
> I have the same problem, it happens when the project is run without having opened the expo app and it doesn't happen in new projects.
> There are other issues related to the status bar and keyboard moving screens up, any intention of releasing these fixes before version 38?

Was having the same issue w/ an iPhone6 - shaking the phone didn't bring up any menu at all. Tried closing everything and relaunching the project with Expo already open-- it works now! Thank you!

**Comment by brentvatne** [comment] 2020-04-08 22:35
> Tried running it through the Expo app, like I do on the iPhone and it works. So it's an issue with running it straight from the command line with a.

@tsapeta @esamelson - this sounds like something introduced with the new dev menu

**Comment by bill-pairaktaridis** [comment] 2020-04-09 07:11
Yes, it shows up if I run it through the Expo app. But my normal flow is running it through "a" from the terminal.

**Comment by levani** [comment] 2020-04-10 07:23
I can confirm that dev menu does not show up when I launch the app from command line. It does show up only when I open it directly from the expo client.

Tested on Galaxy S10 and on emulator as well. Same thing.

**Comment by clintjansen** [comment] 2020-04-10 13:20
Same, menu doesn't open.
Also running -a from the command line with expo start also doesn't auto boot the app like it usually would. 
I have to manualy press 'a' after expo is started

**Comment by bill-pairaktaridis** [comment] 2020-04-10 13:33
Yeah, `-a` has been broken for a couple versions now

**Comment by clintjansen** [comment] 2020-04-10 15:07
Ah use --android instead and it works again, this also goes for the menu (although it seems a bit slower than before)

**Closed** 2020-04-13 19:14 UTC
Labels: Client, needs repro, project: android-runtime

**Comment by menaaziz27** [comment] 2023-09-01 22:43
I faced the same when I was trying to shake it while I was running the app via `expo start` command, but then I downloaded the `expo-cli` package and ran the app with `expo-cli` start --tunnel` and I shook the phone and voila! it worked!

**Comment by LabGecko** [comment] 2024-02-23 21:00
Getting the same issue on a Fairphone 4 with the current version (as of today) of Expo and Expo Go. Tried shaking multiple different ways and nothing changed.

**Comment by brentvatne** [comment] 2024-02-23 21:06
@LabGecko - I don't have a Fairphone 4 to test against but I suspect there is something non-standard in their OS that is isn't compatible with this gesture. You could use the interactive prompt in Expo CLI to toggle the menu:

```
› Using Expo Go
› Press s │ switch to development build

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu
› Press o │ open project code in your editor

› Press ? │ show all commands
```

press the `m` key to toggle menu

**Comment by LabGecko** [comment] 2024-02-23 21:21
@brentvatne Fairphones use pretty vanilla Android, but I get your point and agree it's likely. Thanks for the workarounds!
