### ISSUE TITLE
Location services in Android not working

### ISSUE THREAD

**Issue by arjunrao87** [expo/expo#436] opened 2017-07-29 22:20 UTC
I am using Location services in my react native Expo app. This is my code snippet.

`  

    let { status } = await Permissions.askAsync(Permissions.LOCATION);
    if (status !== 'granted') {
      this.setState({
        errorMessage: 'Permission to access location was denied',
      });
    } else{
      console.log( "Permission to access location was granted");
    }

    let that = this;
    let {location} = await Location.watchPositionAsync({timeInterval:1000}, function(location){
      console.log( "Location = " + JSON.stringify( location ) );
      that.setState({ location:location });
    });

`
I would expect the code to get  the location of the user every 1000ms ( 1 second ). However, 2 things happens -
1. In the iOS simulator, it gets the real location the first time but doesnt get the location every 1 second.
2. In the Android simulator ( Genymotion, any version of Android ), the await function never returns and the location is never obtained. 

Point to note : In the Android emulator I keep getting the error 

> Android Geocoder not present. Please check if Geocoder.isPresent() before invoking the search

Could this have something to do with the location services not getting triggered?

This is a major impediment with testing any location based service using Expo. Can someone point out if I am using the API incorrectly?

**Comment by aswinmohanme** [comment] 2017-07-30 02:39
Is it working when you test on a Physical Device ? Location services on Emulators are buggy.

**Comment by arjunrao87** [comment] 2017-07-30 20:50
Yeah I tested it on the physical device. it looks like this line 

`let {location} = await Location.watchPositionAsync({timeInterval:1000}, function(location){`

does not return

**Comment by jesusmgg** [comment] 2017-07-31 06:55
Have you tried installing Google Apps (opengapps) into Genymotion?

**Comment by kmiasko** [comment] 2017-08-10 21:12
Can confirm.

Android 6, physical device:

`
  componentWillMount() {
    Location.getProviderStatusAsync()
      .then(status => {
        console.log('Getting status');
        if (!status.locationServicesEnabled) {
          throw new Error('Location services disabled');
        }
      })
      .then(_ => Permissions.askAsync(Permissions.LOCATION))
      .then(permissions => {
        console.log('Getting permissions');
        if (permissions.status !== 'granted') {
          throw new Error('Ask for permissions');
        }
      })
      .then(_ => {
        console.log('Have permissions');
        const subscriber = Location.watchPositionAsync({
          timeInterval: 1000,
        }, (location) => {
          console.log('Location change: ', location);
          this.setState({ location })
        });
        this.setState({ subscriber });
      })
      .catch(error => {
        console.log(error);
        this.setState({
          errorMessage: 'Permission to access location was denied',
        });
      });
  }
`

console output:

`
Getting status
Getting permissions
Have permissions
`

Location is not returned, no error.

**Comment by phillip055** [comment] 2017-08-20 17:15
Any updates?

**Comment by phillip055** [comment] 2017-08-20 17:31
Update: watchPositionAsync gets location only once but keeps gps on and getCurrentPositionAsync is working

**Comment by Ruzo** [comment] 2017-08-24 12:02
I would guess that my problem is related to this one which still happens on version 20.0.0.
I'm using MapView with Markers that open a Modal with a list of URLs which can be opened using the WebBrowser API.
Using reverseGeocodeAsync to get the location from MapView's onRegionChangeComplete latlng works fine. However, as soon as the WebBrowser API is used to open and close a URL, reverseGeocodeAsync stops returning the location when the region changes on MapView.

**Comment by dseawel** [comment] 2017-09-30 03:25
This was resolved for me after I set my Google Geocoding API key...
[](https://docs.expo.io/versions/latest/sdk/location.html#expolocationsetapikeyapikey)

Get your key here: [](https://developers.google.com/maps/documentation/geocoding/start)

**Comment by Ruzo** [comment] 2017-09-30 14:12
@dseawel The reason to use the setApiKey is described as:
"This method can be useful for Android devices that do not have Google Play Services, hence no Geocoder Service."
I still tried it but it didn't work for my situation.

**Comment by milad1367** [comment] 2017-10-04 15:07
hi, this is spaghetti code because I, not enough time.but it will solve your problems. I tested it . and worked correctly.
```
import React, { Component } from 'react';
import { Platform, Text, View, StyleSheet } from 'react-native';
import { Constants, Location, Permissions } from 'expo';

export default class MyLocation extends Component {
  state = {
    location: null,
    milad:null,
    errorMessage: null,
  };

  componentWillMount() {
    if (Platform.OS === 'android' && !Constants.isDevice) {
      this.setState({
        errorMessage: 'Oops, this will not work on Sketch in an Android emulator. Try it on your device!',
      });
    } else {
    //  this._getLocationAsync();
    let testlocation =  Expo.Location.watchPositionAsync({
      enableHighAccuracy: true,
      timeInterval :1,
      distanceInterval :1
    }, (loc)=>{
      if(loc.timestamp){
      this.setState({
        milad:loc
      })
    }
    else {
      console.log("nooooooooooooooooo loc");
    }
    });
    }
  }
  componentWillUnmount() {
    this.testlocation && this.testlocation.remove();
    this.testlocation = null;
  }

  _getLocationAsync = async () => {
    let { status } = await Permissions.askAsync(Permissions.LOCATION);
    if (status !== 'granted') {
      this.setState({
        errorMessage: 'Permission to access location was denied',
      });
    }

  //  let location = await Location.getCurrentPositionAsync({});
 //   this.setState({ location });
    
  };

  render() {
    let text = 'Waiting..';
    let milad = "milad location...";
    if (this.state.errorMessage) {
      text = this.state.errorMessage;
    } else if (this.state.location) {
      text = JSON.stringify(this.state.location);
    }
    milad = JSON.stringify(this.state.milad);

    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>{text}</Text>
        <Text> milad: </Text>
        <Text> {milad} </Text>
      
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    textAlign: 'center',
  },
});


```

**Comment by pcooney10** [comment] 2017-10-07 17:04
I am also experience issues with the Location api on certain android devices & Genymotion.

Google Play Service is enabled, and the `Permissions.askAsync(Permissions.LOCATION)` function returns `status granted` in the console. The `Location.getCurrentPositionAsync({})` function seems to hang with a silent error in the console.

**Comment by rainbowhat** [comment] 2017-10-08 20:07
Facing this issue too

**Comment by pcooney10** [comment] 2017-10-08 23:37
@rainbowhat on a device or Genymotion / Android Studio?

Are the location services enabled?

**Comment by dikaiosune** [comment] 2017-10-11 19:43
@pcooney10 thanks for the detailed info here. 

@rainbowhat can you take a look at the solution that @pcooney10 listed?

@Ruzo it seems like you're reporting a different issue with a different API. If you're still having problems can you open a separate bug report?

@kmiasko it seems like your code sets the result of the watchLocationAsync call to state, but IIRC that function returns a Promise. What happens if you await the subscription object before setting it in state?

It looks to me like the various issues reported here are due to location services being disabled, due to a missing API key, or due to Genymotion's iffy support for location services. And without a concrete reproduction that works on a physical device with location services enabled, I'm not sure there's anything we're able to fix. I'd love to be wrong though, so please post back if you have a repro case to share! Closing for now, but I'll reopen if there's something we can address. Thanks!

**Comment by dikaiosune** [comment] 2017-10-11 19:44
Also, I may be wrong about Genymotion's support for location services, but I wouldn't assume a watcher for location would work on Genymotion unless you also cause Android to think its faked location has been changed.

**Closed by dikaiosune** 2017-10-11 19:43 UTC
Labels: project: client-android, project: sdk

**Comment by kmiasko** [comment] 2017-10-12 06:09
@dikaiosune Nope, at least not in the documentation. [https://docs.expo.io/versions/latest/sdk/location.html#expolocationwatchpositionasyncoptions-callback](watchPositionAsync) . `watchPositionAsync` returns subscriber that allows to cancel it. Coords object is passed through callback.

**Comment by mithlesh-pantelwar** [comment] 2018-01-07 15:21
This issue is with android when location service is disabled and permission is granted..
So to solve this .. first use Expo.Location.getProviderStatusAsync()..
it return an object.. inside the object there are 4 fields.. for this task we need only two: 
locationServicesEnabled (boolean),  gpsAvailable (boolean) ..check their boolean value.. if any of them is false..Expo.LocationgetCurrentPositionAsync({}) .. will give promise rejection error..
so to not to get this error.. we have to enable ' locationServicesEnabled (boolean),  gpsAvailable (boolean) '
..To enable these.. we have to use Expo.IntentLauncherAndroid. to open the location setting and enable it..
to Open location setting.. required code is: 

import { IntentLauncherAndroid } from 'expo';
// Open location settings
IntentLauncherAndroid.startActivityAsync(
  IntentLauncherAndroid.ACTION_LOCATION_SOURCE_SETTINGS
);

Then call Expo.getCurrentPositionAsync() .. now you will get your location..

**Comment by nahuelhds** [comment] 2018-03-09 23:49
In my case, doing `Location.getCurrentPositionAsync({ enableHighAccuracy: true })` does the trick (I'm on Genymotion)

**Comment by mawippel** [comment] 2019-04-12 21:24
> In my case, doing `Location.getCurrentPositionAsync({ enableHighAccuracy: true })` does the trick (I'm on Genymotion)

Just saved my day, thank you!
