### ISSUE TITLE
Crash Expo Client in Simulator when tap to Perf Monitor

### ISSUE THREAD

**Issue by tiendn** [expo/expo#4834] opened 2019-07-05 08:13 UTC
## 🐛 Bug Report
Crash Expo Client in Simulator when tap to **Perf Monitor**
### Environment
 Expo CLI 2.20.10 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: 3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.21.1

iPhoneXR 12.2 Simulator

### Steps to Reproduce
* `Command + Control + Z` to open Development Mode
* Select: `Show Perf Monitor`
* Tap to Perf Monitor

### Expected Behavior
Show the detail of Perf Monitor

### Actual Behavior
Crash app

### Reproducible Demo
![giphy](https://user-images.githubusercontent.com/15717476/60707994-343de500-9f37-11e9-8f48-86a147968a35.gif)

**Comment by cruzach** [comment] 2019-07-05 19:02
Hi @tiendn! I just tried this on the same simulator, and experienced no crashes. Is your app doing anything else in the background?

**Comment by tiendn** [comment] 2019-07-05 23:50
No, I don't.
No background location.

**Comment by cruzach** [comment] 2019-07-09 13:34
Hm, well we need a way to reproduce this on our end. What version of the Expo client are you running?

**Comment by cruzach** [comment] 2019-07-09 13:35
Hm, well we need a way to reproduce this on our end. What version of the Expo client are you running?

**Comment by tiendn** [comment] 2019-07-09 14:29
hmm, It's run on iPhone Simulator, so I think it's the latest version.

**Comment by dellwatson** [comment] 2019-07-23 06:38
i also had crash in real physical device (iphone 7)

expo 33 and with newest CLI, and newest expo app too.

i did try some reanimated, and causes RAM to explode, but once i revert back to normal, the perf monitor still crashes everytime i touch it even though the apps is working normal... so i had to hide it but unable to maximize the window of performance monitor.

**Comment by cruzach** [comment] 2019-07-23 13:22
Please share a reproducible example that I can run to see this behavior

**Comment by dihan** [comment] 2019-12-21 21:00
having same issue expo 35.0.0

**Comment by jniac** [comment] 2020-01-04 14:43
Same issue (i think) in expo 36.0.0 on device (iPad iOS 13).

**Comment by Razorholt** [comment] 2020-02-26 04:35
Same issue in expo 36. How can we find out the reason behind the crash?

**Comment by kalypzo** [comment] 2020-04-18 16:51
Got the same issue as well using 36 on iPhone 11 Pro simulator. In my case, it completely crashes Expo, not just the underlying app. It was working before, but recently upgraded the expo-cli and Xcode. Unfortunately, I'm not sure what version of Xcode or the expo-cli I was on before this started happening.

**XCode**
Xcode 11.4.1
Build version 11E503a

**expo-cli**
3.18.4

**MacOS Catalina**
Version 10.15.3

**Node**
v13.5.0

**NPM**
6.13.7

**Simulator**
iPhone 11 Pro (13.4.1)

---
![ExpoBug](https://user-images.githubusercontent.com/5160486/79643591-b703f980-8171-11ea-9d38-02ab4ca97fd6.gif)

**Comment by hadnet** [comment] 2020-04-22 22:20
I'm using a bare workflow of Expo and my app crashes as well when toggling perf monitor, same as kalypzo (but I'm not using the Expo app, just running yarn ios).

**Comment by rajtatata** [comment] 2020-04-30 09:21
Guys, I installed Simulator 13.3 from Xcode -> Preferences -> Component, and when i ran simulator with 13.3 it worked again.
I think the problem was with latest simulator update.

**Comment by magtastic** [comment] 2020-05-04 11:37
Can confirm that @rajtatata solution worked for me. Consistently crashes when on iOS simulator 13.4.1 (iPhone 11 Pro Max), downloaded 13.3 and now it works perfectly.

**Comment by lukmccall** [comment] 2020-07-27 15:28
I think I can close this issue. The latest simulator version should do the job ;)

**Closed by lukmccall** 2020-07-27 15:28 UTC
Labels: needs repro, status: needs more info
