### ISSUE TITLE
Back button in the nested stack while going from different stack

### ISSUE THREAD

**Issue by JustynaKK** [expo/expo#33576] opened 2024-12-10 14:06 UTC
### Minimal reproducible example

https://github.com/JustynaKK/expo-router-nested-back-button

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Hi, I have stacks in the tabs
A - A1 - A2
B - B1 - B2
When I go for the first time A -> B -> B1, then B1  has back button which takes back to B screen. 
However if I am in A and do router.push(B1) or Link to B1 without previously going to B, then B1 doesn't have back button. And then when I click on the B route in the tab it takes me diractely to B1.
And it only happens if I never went to B. 
I tried initialRouteName but it is not changing anything

Do you know how to fix it?

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.5.0 - ~/.npm-global/bin/npm
      Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 31, 34
        Build Tools: 33.0.1, 34.0.0, 35.0.0
        System Images: android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.19072.14.2412.12360217
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.6 => 52.0.6 
      expo-router: ~4.0.5 => 4.0.5 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.2.1
    Expo Workflow: managed
```

**Comment by marklawlor** [comment] 2024-12-11 15:03
Your reproduction repro does not match your description so I'm unable to confirm your issue exactly. However I think I understand what you are describing.

A & B are in different Stacks, where A & B are the initialRouteName for each stack.

When you first navigate to a new Stack (moving from A -> B), the route you navigate to becomes the inital route for that stack. So going from A -> B -> B1 has a back button because the B stack has two routes. A -> B1 creates a B stack with only one screen (because B1 is the initial route).

In Expo Router, we are moving away from the terminology of `initialRouteName` because its confusing why the route isn't always the initial route. Instead we're called them anchor routes.

When you navigate from A -> B1 you can use these options

`<Link href="/b1" withAnchor />` or `router.push('/b1', { withAnchor: true }`).

This way, when you navigate from A->B1 it will include the anchor B route and your history will be A->B->B1, with the B stack having two screens and a back button.

I hope that answers your issue. I'm going to close this issue as it didn't provide a valid reproduction. If I didn't answer your issue can you please create a new issue with a valid reproduction demonstrating the issue

**Closed by marklawlor** 2024-12-11 15:03 UTC
Labels: needs review, Router
