### ISSUE TITLE
locking screen orientation buggy in SDK37

### ISSUE THREAD

**Issue by JustynaKK** [expo/expo#8210] opened 2020-05-08 08:10 UTC
### Environment

  Expo CLI 3.18.6 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.7.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Justyna\AppData\Roaming\npm\yarn.CMD
      npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
    npmPackages:
      expo: ^37.0.8 => 37.0.8
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4

Target: iOS

### Steps to Reproduce

On the splash screen I am fetching the current orientation of the phone and then I am locking the app to this orientation
```		
await ScreenOrientation.getOrientationAsync().then((orientationId) => {
    orientation = ScreenOrientation.Orientation[orientationId];
    ScreenOrientation.lockAsync(
    ScreenOrientation.OrientationLock[orientation]
    );
});
```
In SDK36, everything was working as expected:
1. On initial: when phone was in landscape position the app was loaded and locked in landscape for the whole time of app working, therefore:
2. When coming back from the background, doesn't matter if the phone was in landscape or portrait position, app was loaded as locked.
https://streamable.com/jhmee9

In SDK37:
1. On initial, when phone is in the horizontal position, it is rotating by itself to the portrait
https://streamable.com/0a5qw5

2. However when I rotate the phone form portrait to landscape orientation on initial, it's 'catching' horizontal position and the app is loaded in landscape.  But when coming back from background, when phone is in portrait position, it is first loaded to the phone position, and then rotating by itself to locked position.
https://streamable.com/3obzqo

I know that there is an option to set orientation in the app.json, however my app should work in both landscape/horizontal position, as locked on initial. Setting 'orientation' to 'default' does not change anything. 

Specially the issue with not fetching properly orientation on initial is problematic, as clients using this app on the tablets build in the wall

**Comment by MichelBahl** [comment] 2020-05-16 15:42
Maybe you have to use [Device Motion](https://docs.expo.io/versions/latest/sdk/devicemotion/#devicemotionisavailableasync), to detect the device orientation.

After you get the device orientation you can lock the screen orientation.

**Comment by JustynaKK** [comment] 2020-05-18 07:29
It seems that device motion working on updates/changes of the device position, and for my case I need initial value, the same which was return in SDK 36 from ScreenOrientation.getOrientationAsync()

**Comment by BrodaNoel** [comment] 2020-06-07 11:10
I'm having the same problem here.

My `app.json` has:
```json
"orientation": "portrait",
```

And I am using ReactNative Modal in this way:
```js
      <RNModal
        animationType="none"
        supportedOrientations={['portrait']}
        transparent={false}
        onRequestClose={this.onClose}
      >
        // ...
      </RNModal>
```

In order to reproduce the issue, I have to follow these steps:

1. Put the phone on Portrait
2. Open a modal
3. Put the phone on Landscape (nothing is gonna happens)
4. Close the Modal.

After closing the modal, you are going to see that the app is in Landscape mode

Then, you can move to Portrait, and it's gonna properly become Portrait, and not gonna switch to Landscape (unless you open the modal again)

I created this Snack just so you copy & paste the code.
Don't try it directly over the Snack, because you need to change `app.json` value

**Closed** 2020-06-15 15:18 UTC
Labels: ScreenOrientation

**Comment by JustynaKK** [comment] 2020-07-07 14:32
After updating to 1.1.1, initial screen in still rotating on iPad pro
https://vimeo.com/user114959970/review/436104636/afbc59ab40?fbclid=IwAR1J2EHMjd-F0p6CgQ8PeXsCbafW6dmR2O0z3kqbvhecE0iRa5YbgG3O648

**Comment by lukmccall** [comment] 2020-07-07 15:12
Unfortunetly, your link doesn't work: ![image](https://user-images.githubusercontent.com/9578601/86802131-fbb67700-c074-11ea-9d31-8ec728b5f1ce.png)

**Comment by JustynaKK** [comment] 2020-07-08 08:06
This should work: https://vimeo.com/436104636

**Comment by lukmccall** [comment] 2020-07-08 08:09
That will be very tricky :/ Please, create a new issue for that. I'll look at this and try to fix it.

**Comment by JustynaKK** [comment] 2020-07-08 08:44
I submitted the issue: https://github.com/expo/expo/issues/9131
It seems as the same problem as in this issue: https://github.com/jellyfin/jellyfin-expo/issues/74
