### ISSUE TITLE
[calendar] SDK 34 Calendar.DEFAULT changes

### ISSUE THREAD

**Issue by LarkStephens** [expo/expo#5291] opened 2019-08-12 08:41 UTC
### Environment

Expo CLI 3.0.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

I am developing for Android and iOS.

### Steps to Reproduce
In the release announcment for SDK 34 the following is listed under breaking changes:

"Calendar : the DEFAULT constant has been removed. To use the default calendar, pass null instead. This fixes an occasional issue when the calendar name coincides with a SQLite keyword."

I’m trying to adjust my code to accomidate the changes, but I keep getting an error:

``createEventAsync must be called with an id (string) of the target calendar``

The way I’ve been replacing the code was from…

``Calendar.createEventAsync(Calendar.DEFAULT, {//details in here...})``

…to…

``Calendar.createEventAsync(null, {//details in here...})``

### Expected Behavior

The Expo Calendar should create a new Event

### Actual Behavior

The Expo Cli reports the following when I try to save an event:
``createEventAsync must be called with an id (string) of the target calendar``

### Reproducible Demo
I was able to reproduce the error by downloading this snack I've made and installing it and running the code attached to the button:

https://snack.expo.io/@lark/crabby-truffle

It doesn’t crash, it just prints the error to the cli. 
If it is relevant, I am testing on a Samsung A10 running Android 9.

**Comment by lukmccall** [comment] 2019-08-12 09:22
Hi, I'm thinking it's a mistake in our documentation. `Calendar.DEFAULT` was removed and replaced with `null` only in functions connected with reminders. This decision was made because Android API doesn't provide something like default calendar.
So if you want to create an event, you need to provide a valid calendar's id.
I suggest firstly creating calendar using `createCalendarasync` and then adding events.

**Comment by LarkStephens** [comment] 2019-08-12 09:26
Super, I'll try and get that going later this afternoon and will report back then.
Thanks for the help and clarification!

**Comment by LarkStephens** [comment] 2019-08-12 12:26
I've edited the snack to try to create a Calendar, but I'm having trouble getting it to create one. I can't find an example for a cross-platform Calender details argument, so I filled out all the required fields for both OS.
After downloading and installing again I get the error:
https://snack.expo.io/@lark/crabby-truffle

`[Unhandled promise rejection: Error: Calendar could not be saved: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference]`
`- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:155:41 in createErrorFromErrorData`
`- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:104:55 in <unknown>`
`- ... 5 more stack frames from framework internals`

**Comment by connor-odoherty** [comment] 2019-08-12 19:59
Let me know if I should file this as a separate bug/feature request, but is there any way to create an event for the user's default calendar anymore?

In the past, a null CalendarId would automatically find the user's default Calendar, and export data to said calendar.

Now, as far as I can tell, there is no way to find out what a user's default Event Calendar might be, even though this is a pretty typical functionality on iOS. 

We would like to avoid creating a brand new calendar on the user's device, as we think this is invasive, and it still leaves us guessing which provider (iCloud, GMail, etc.) to use.

Ideally, this plugin would re-enable null Calendar ID for iOS and only pass back an error for Android. Is that at all possible?

**Comment by lukmccall** [comment] 2019-08-13 07:00
@LarkStephens, According to our documentation `accessLevel` should be a single string, not an array of strings.

@connor-odoherty, I think, you can get the default calendar on iOS using  `Calendar.getCalendarsAsync`. Correct me if I'm wrong.

**Comment by LarkStephens** [comment] 2019-08-13 09:56
@lukmccall Thanks, that really helped, I'd passed over those docs a dozen and a half times and I kept missing it!

With regards to the default calendar on iOS, I'm looking at the iOS results of Calendar.getCalendarsAsync and none are the obvious default, unless the first one, titled 'Work' is the default. Re-implementing it for iOS might have merit.

**Comment by connor-odoherty** [comment] 2019-08-13 17:06
@lukmccall On Android, the `isDefault` attribute is set as expected. However, the Expo documentation (and my own experiences) confirmed that this is Android only, unfortunately.

On other, older plugins, the isDefault attribute is listed as an attribute of both. But knowing Apple's rapidly changing policies, I could see how that is deprecated.

Is there any other way to expose the default Event Calendar on iOS?

**Comment by lukmccall** [comment] 2019-08-29 08:15
I will close this issue, because the problem connected with getting the default calendar was moved to #5301. 

Also, I've created PR which add a getter for the default calendar (#5485).

**Closed by lukmccall** 2019-08-29 08:15 UTC
Labels: bug
