### ISSUE TITLE
[android][notifications] disabling OTA updates breaks notifications on standalone APK

### ISSUE THREAD

**Issue by DiegoAndai** [expo/expo#10562] opened 2020-10-05 19:55 UTC
### Summary of Issue

Remote notifications stop working on android santdalone apk built with `"updates": { "enabled": false }` app.json config.

### Environment

```
  Expo CLI 3.27.13 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.11.0 - ~/.nodenv/versions/14/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nodenv/versions/14/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.14 
    npmGlobalPackages:
      expo-cli: 3.27.13
    Expo Workflow: managed
```

Tested on Android 9 and 10

### Reproducible Demo

To reproduce you can use this repo: https://github.com/DiegoAndai/notif-debug-1

#### Quick way:

There are two APKs on the repo, these have a "send remote notification" button so you can easily test if the notifications are being displayed. The only difference between the two is the `"updates"` app.json field. The one built with `"updates": { "fallbackToCacheTimeout": 0 }` (lets call it apk **A**) displays notifications as expected, but the one built with `"updates": { "enabled": false }` (apk **B**) doesn't show anything.

#### Slower way:

You can build your own apks with the code on the repo. I made two commits, one with each configuration described above. You'll have to provide the FCM configuration.

The apks also show a local notification button, the Exponent Push Token and the `"updates"` field content of the manifest.

### Steps to Reproduce

Whether you built your own or use the provided apks, install and use the "send remote notification" button, one will show notifications and the other won't. The app also displays the Exponent Push Token if you want to use the notification tool, which doesn't show any error messages for the apk **B**, even though notifications don't show up.

### Expected Behavior vs Actual Behavior

Remote notifications should work with either configuration.

### Notes

Both configurations work fine on Expo Client, probably as `"updates": { "enabled": ... }` is ignored

I don't think the updates configuration has much to do with notifications, so maybe there is a deeper problem and there are more symptoms that I'm not seeing. I really don't know much about how to debug this further or search for an explanation in Expo's source code.

When using the `"updates": { "fallbackToCacheTimeout": 0 }` (apk **A**), updates are not disabled, and as I published the `"updates": { "enabled": false }` (apk **B**) version after, the apk **A** displays `updates manifest field: { "enabled": false }` after a while (as it downloads the update), but the notifications still work. That's why I describe the bug as "Remote notifications stop working on android santdalone apk **built** with `"updates": { "enabled": false }`".

I hope that helps. Thanks in advance!

**Comment by cruzach** [comment] 2020-10-05 20:12
hey @DiegoAndai, sorry about this one, I believe it is caused by [this check here](https://github.com/expo/expo/blob/master/android/expoview/src/main/java/host/exp/exponent/fcm/ExpoFcmMessagingService.java#L42). In your logs, do you see `No experience found for id @yourUsername/slug`?

**Comment by DiegoAndai** [comment] 2020-10-06 01:48
Hi @cruzach! thanks for the quick response. Yes! I'm seeing this:

`E/expo-notifications: No experience found for id @diegoandai/notif-debug-1`

Is there a way I can fix this while still disabling OTA updates?

**Comment by esamelson** [comment] 2020-10-06 02:25
Hey @DiegoAndai -- thanks for the helpful report and repro case. We should have a fix out for this soon -- hold tight!

**Comment by DiegoAndai** [comment] 2020-10-06 17:00
@esamelson thank you for the quick fix!

Sorry if this is kind of a dumb question but after #10570 is merged the build service will be fixed or do we have to wait for the next SDK release?

**Comment by esamelson** [comment] 2020-10-07 00:45
Hey @DiegoAndai -- no need to wait for the next SDK release, we just need to deploy the fix to our build servers and then once it's deployed you'll need to rerun `expo build:android`. We're working on this now and I'll update/close this issue when it's done.

**Comment by esamelson** [comment] 2020-10-07 02:08
fix is deployed to production! Going to close this now but please let us know if the issue persists.

**Closed by esamelson** 2020-10-07 02:08 UTC
Labels: Android, Notifications, Updates
