### ISSUE TITLE
SDK 35 MediaLibrary no Asset id

### ISSUE THREAD

**Issue by rxhivzero** [expo/expo#5756] opened 2019-09-24 10:03 UTC
### Environment

  Expo CLI 3.1.1 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @ant-design/react-native: ^3.1.15 => 3.1.15 
      expo: 35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: 4.0.6 => 4.0.6 
    npmGlobalPackages:
      expo-cli: 3.1.1

### Steps to Reproduce

Use await MediaLibrary.getAssetsAsync()
The get data is like 
<img width="572" alt="截圖 2019-09-24 下午5 58 57" src="https://user-images.githubusercontent.com/9067017/65502249-03959800-def5-11e9-993d-a1a9d228ce08.png">

I can't use MediaLibrary.getAssetInfoAsync(asset) without Asset id
I need get localUri to upload  MediaLibrary video.

**Comment by AdamJNavarro** [comment] 2019-09-24 15:25
Hey @rxhivzero,

Could you please create a reproducible example of this issue using [Snack](snack.expo.io)? Also, are you experiencing this on Android, iOS or both?

Cheers,
Adam

**Comment by rxhivzero** [comment] 2019-09-25 04:11
Hi @AdamJNavarro 
I try new project is work,maybe I did something wrong.
but ios getAssetInfoAsync not localUri when video asset

<img width="644" alt="截圖 2019-09-25 下午12 07 21" src="https://user-images.githubusercontent.com/9067017/65568709-59b61a00-df8d-11e9-9366-12d36e10a10f.png">

https://snack.expo.io/@cofit/medialibrary-example

**Comment by Haper** [comment] 2019-09-25 08:44
The same problem: only preview image will be uploaded by video asset uri.
SDK - 32-35

**Comment by tsapeta** [comment] 2019-09-28 17:09
The original issue seems to be solved, so I'm going to close it. In terms of the issue with missing `localUri` if the asset is a video, please follow this issue: #2448

**Closed by tsapeta** 2019-09-28 17:09 UTC
Labels: MediaLibrary, bug, needs repro
