### ISSUE TITLE
[expo-notifications][bare workflow] Listener registered by addNotificationResponseReceivedListener() doesn't fire when the app is closed and then opened by tapping the push notification

### ISSUE THREAD

**Issue by yaroslavnikiforov** [expo/expo#7787] opened 2020-04-09 21:14 UTC
### Environment

| software         | version
| ---------------- | -------
| expo | detached to bare RN app
| react-native     | 0.61.5
| expo-notifications     | 0.1.1
| platform OS | iOS

### Steps to Reproduce

According to the [documentation](https://github.com/expo/expo/tree/master/packages/expo-notifications#addnotificationresponsereceivedlistenerlistener-event-notificationresponse--void-void) listeners registered by `addNotificationResponseReceivedListener(listener: (event: NotificationResponse) => void): void` will be called whenever a user interacts with a notification (eg. taps on it).
If the app was closed (not in the background) and then opened by tapping the push notification, listener registered by this method will not be called.

### Expected Behavior

Callback for `addNotificationResponseReceivedListener` should fire on the next tick after the app starts with the notification data, in the same way as `Notifications.addListener()` from managed workflow works. To be able to update the UI based on the notification, or maybe navigate to a particular screen when a notification was selected.

### Actual Behavior

When the user taps on push notification when the app is killed, that just launch the app and listener doesn't trigger.

If there are any other ways to handle such a case with expo-notifications, please tell us.

**Comment by serhiipalash** [comment] 2020-04-10 15:14
@sjchmiela `addNotificationResponseReceivedListener` catches push notification by pressing on which you opened the app, but only if you add listener just after the app start. When you add listener after some delay (300ms) "initial" push notification will be ignored.

So, this works

```
export default class App extends React.Component {
  render() {
    return null
  }

  componentDidMount() {
    addNotificationResponseReceivedListener((response) => {
      console.log('App was opened by notification: ', response.notification)
    })
  }
}
```

and this doesn't

```
export default class App extends React.Component {
  render() {
    return null
  }

  componentDidMount() {
    setTimeout(
       () => {
          addNotificationResponseReceivedListener((response) => {
            console.log('App was opened by notification: ', response.notification)
          })
    }, 1000)
  }
}
```

Catching "initial" notification is needed when it has attached deep link and you need to navigate on it just after app start.

In our app we don't attach any notification listener during the loading time (fonts, persisted state, etc.). Usually it takes 300-500ms to finish loading and then we attach notification listener. So, the bug was that this listener doesn't catch "initial" notification. But we made a workaround and now everything works fine.

If you think that this is not a real issue, then feel free to close it (the main problem could be with backward compatibility with `Expo.Notifications` as they were handling this "delay-case"). You can also rename this issue in a more descriptive way.

P.S. Thank you for `expo-notifications` in general :)

**Comment by serhiipalash** [comment] 2020-04-10 15:22
> catches push notification by pressing on which you opened the app, but only if you add listener just after the app start

To clarify, by "the app start" I mean fresh app start and not focusing app from the background. When you focus app from the background by notification press it will be catched by listener because the listener itself was already added.

**Comment by bayoremit** [comment] 2020-04-14 22:13
@serhiipalash , do you pls mind sharing what your workaround was?

Thanks!

**Comment by serhiipalash** [comment] 2020-04-15 06:44
@bayoremit the workaround is that we attach a new listener on app start and remove it on app loading end. So, now we have two listeners: the old "main listener" and the new "initial notification listener", and we handle initial notification in the new one.

**Comment by robertying** [comment] 2020-04-21 14:18
Another simple workaround is to install pushnotification-ios from RN core. It's deprecated but enough for fetching initial notifications without too much code changing.

**Comment by sjchmiela** [comment] 2020-04-21 15:25
Could you please try ensuring that the `NotificationResponseListener` is the first listener that is added in the application? (before `setNotificationHandler` or `addNotificationReceivedListener`, etc.)? This **should** help you resolve the issue. If not, I will try to find a better solution.

This is not an easy problem because of the way that iOS architectured its new, non-deprecated notifications framework, [`UserNotifications`](https://developer.apple.com/documentation/usernotifications?language=objc) — there is no notion of _initial notification_ per se, the _initial notification_ is delivered just as if it was a regular notification, there is nothing special about it. That's why I have decided not to create an artificial `getInitialNotificationAsync` method — it would have to either depend on the timing, which may be different on different devices in different states.

`expo-notifications` is [supposed to persist _pending notification responses_](https://github.com/expo/expo/blob/66f2a378c18b6d2a23806ab12905a94951f642d9/packages/expo-notifications/ios/EXNotifications/Notifications/EXNotificationCenterDelegate.m#L126-L130) for [until a listener is registered](https://github.com/expo/expo/blob/66f2a378c18b6d2a23806ab12905a94951f642d9/packages/expo-notifications/ios/EXNotifications/Notifications/EXNotificationCenterDelegate.m#L178-L182). If the listener isn't triggered with the initial notification it may be because the pending events are consumed by another component. I haven't had noticed this behavior when I was developing the library, otherwise I would have put this in the docs, sorry!

`React-RCTPushNotification` uses a [deprecated `UILocalNotification`](https://developer.apple.com/documentation/uikit/uilocalnotification?language=objc) classes and a deprecated way of fetching the _initial notification_ which may not work properly in newer versions of iOS — that's why it's deprecated.

**Comment by robertying** [comment] 2020-04-21 15:40
Hi @sjchmiela thanks for elaborating this. I tried to add `addNotificationResponseReceivedListener` as early as in index.js, but the listener never fires. 😢

**Comment by cHaLkdusT** [comment] 2020-04-21 16:18
*addNotificationResponseReceivedListener* is not firing in iOS but is working in Android. 🤔

**Comment by cHaLkdusT** [comment] 2020-04-21 16:24
Hi @sjchmiela, I've tried attaching *addNotificationResponseReceivedListener* listener before `setNoficationHandler` or `addNotificationReceivedListener` but is still is not firing in iOS but is working in Android. 🤔

**Comment by sjchmiela** [comment] 2020-04-22 12:12
Hey, sorry for making you go through this problem, I have introduced a bug to the implementation at the last stage of developing so I didn't notice it — I have reproduced the bug and I think I also fixed it.

Would you mind checking if applying [this patch](https://gist.github.com/sjchmiela/50e017f9e5e70bf7ae32f5b988931149) with `patch-package` solves the problem for you?

**Comment by sjchmiela** [comment] 2020-04-22 12:19
`expo-notifications@0.1.3-rc.0` is now available. Note that (at least I) had to do some magic to make Xcode rebuild the Pods project — you may need to <kbd>Product</kbd> > <kbd>Clean build folder</kbd> to use the updated code (I also had to remove the app from the simulator on which I was testing the fix 🤷) (if it works for you without all this hacks, great!).

**Comment by cHaLkdusT** [comment] 2020-04-22 14:29
Hi @sjchmiela, Unfortunately, it wasn't able to make it work on my end. Here's what I did:

1. In terminal, run `$ expo install expo-notifications@0.1.3-rc.0`
2. `$ cd ios && pod install`
3.  Xcode > Product > Clean Build Folder (SHFT + CMD + K). *I also did full clean build folder (OPT + SHFT + CMD + K)*
4. Uninstall app in simulator
5. Ran app. Put it background state and waited scheduled notification.
Sample code snippet I used to trigger local notification.
```
const trigger = new Date(Date.now() + 5 * 1000);
Notifications.scheduleNotificationAsync({
     content: {
       title: 'Trigger after 5 seconds',
     },
     trigger,
   });
```

I tested both in simulator and iPhone device, still no luck.

**Comment by sjchmiela** [comment] 2020-04-22 14:38
Thanks for the swift reply — do you mean you wasn't able to show the notification? Let me write out all the steps to reproduce this specific bug:

1. Ensure notifications are allowed to be presented.
2. Schedule notification to be presented in eg. 5 seconds.
3. Immediately, background the application.
4. See the notifications arrive after 5 seconds.
5. Kill the app. (Double Home tap, swipe app up) — important to reproduce this specific bug.
6. Tap on one of the notifications.
7. The listener should be triggered.

I have put up a simple reproducing application I was testing the bug on at https://github.com/sjchmiela/expo-notifications-initial-notification-test if it helps.

**Comment by cHaLkdusT** [comment] 2020-04-22 16:57
Hi @sjchmiela, I used your demo application, it is very straightforward. I can confirm that it is working! However, on my own project I can't make it work. 😅 What I am looking now is, it could be React Native issue? I'm using RN v0.62.1. I'll try playing around with few RN version to see if this can affect this issue.

**Comment by robertying** [comment] 2020-04-23 07:20
@sjchmiela this works for me! Thank you for your timely response and fix! 👍

**Comment by arberK** [comment] 2020-04-23 08:29
@sjchmiela I can confirm it fixed the problem for me also. Great work

**Comment by nicwhitts** [comment] 2020-04-23 23:41
I'm having a weird problem too and it sounds like its related but might not be.

`addNotificationReceivedListener` SOMETIMES gets called with the notification in foreground. But never gets called in the background...

But the alert never shows, ever. 

I had to eject and its just caused the push notifications to break.

**Comment by sjchmiela** [comment] 2020-04-24 06:45
Hey @nicwhitts, could you please file a new issue? It's ain't easy to guess the platform you're referring to, environment etc. and a new issue template prompts you to fill out this information (which comes in handy!) 🙂

**Comment by nicwhitts** [comment] 2020-04-29 11:49
The problem was that i was still requesting for notification permission in the 'old' expo managed way.

**Comment by joaocosta9** [comment] 2020-05-04 03:08
Hello. I eject to bare workflow and followed the documentation regarding push notifications. I'm already receiving a token but this token isn't working and I think it's because of the experienceId. As described in the documentation. `const expoPushToken = await Notifications.getExpoPushTokenAsync({
    experienceId,
  });`
Does any of you know what does this value means and where can I get it from? Thanks!!

**Comment by sjchmiela** [comment] 2020-05-04 07:24
Hey @joaocosta9, `experienceId` is a string of form: `@<your-expo-username>/<project-id>`, so eg. if I had a project `TestNotifications` which in `app.json` would have `id: "test-notifications"`, since my Expo username is `sjchmiela`, the experience ID would be:

```
@sjchmiela/test-notifications
```

To see what is your username, run `expo whoami` in the terminal. I got:

```
Logged in as sjchmiela
```

To see what is the project's ID, go see `app.json#expo.id`.

Remember that to be able to send notifications with Expo servers (that's probably what you're trying to do if you're fetching the Expo push token) you also need to have credentials set up. Follow [this guide](https://github.com/expo/expo/tree/master/packages/expo-notifications#add-your-projects-credentials-to-expo-server-optional) to ensure it's done!

**Closed** 2020-05-04 09:00 UTC
Labels: Bare Workflow, Notifications

**Comment by sjchmiela** [comment] 2020-05-04 10:53
`expo-notifications@0.1.4` fixes this issue. Note that for the fix to be applied on iOS you may need to clean the build folder as per https://github.com/expo/expo/issues/7787#issuecomment-617744857. Thank you for your patience!

**Comment by joaocosta9** [comment] 2020-05-04 18:23
Hey @sjchmiela thanks for you help

**Comment by joaocosta9** [comment] 2020-05-04 18:32
hey @sjchmiela thanks for your help, the token I'm receiving is now correct. But unfortunately, when I try to use the Expo Push notifications tool and send the notification my app immediately closes and I don't even receive the notification. Does anyone know what is this about? I have already tried everything that is in the documentation

**Comment by polsson12** [comment] 2020-05-05 08:15
I updated to 0.0.14 and when my app is in the foreground, it crashes immediately without even receiving the notification. When the app is in the background, the notification is never received, neither when the app is opened by clicking the app icon, nor by tapping the notification that pops up.

**Comment by sjchmiela** [comment] 2020-05-05 12:36
Hey, the `v0.1.4` contains a bug I'm now fixing. Sorry for the trouble. You can track the issue at https://github.com/expo/expo/issues/8142.

**Comment by polsson12** [comment] 2020-05-05 13:22
Good to hear! When do you think you can have a `v0.1.5` or rc available?

**Comment by polsson12** [comment] 2020-05-05 21:21
@sjchmiela, with 0.1.6 release I'm able to receive notifications when app is in foreground in the callback in Notifications.addNotificationReceivedListener().
However, I'm still not able to receive any notifications when app is in background and opened by clicking the app icon or the notification bar.

OS: Android version 10
Device: Google Pixel 3

Any suggestions?

**Comment by anasanzari** [comment] 2020-07-20 05:55
@polsson12 same issue with us, foreground works, but background doesn't

**Comment by zholmes1** [comment] 2020-07-21 15:37
Same issue here. I am unable to get any information about the notification that was clicked to open the app (while the app was closed)

I'm using `addNotificationResponseReceivedListener`, and it will only fire if I send a notification while the app is open

**Comment by kale94** [comment] 2020-07-22 12:36
Same issue here. `addNotificationResponseReceivedListener` does not work on android at all.
[Example on Snack](https://docs.expo.io/push-notifications/overview/) also doesn’t work.

**Comment by panuavakul** [comment] 2020-07-25 11:51
I have the same issue as @kale94 
`addNotificationResponseReceivedListener` and `addNotificationResponseReceivedListener` does not work in Android at all while the same code work perfectly in iOS

**Comment by rodneyrehm** [comment] 2020-07-29 16:49
I've got the same/similar issue with `expo-notifications@0.3.3`. iOS works perfectly fine, Android not as much:

* [Notification](https://docs.expo.io/versions/latest/sdk/notifications/#notification) object passed to the callbacks of `setNotificationHandler` and `addNotificationReceivedListener` shows `event.request.content.body !== event.request.trigger.remoteMessage.notification.body` - in fact pretty much all of [NotificationContent](https://docs.expo.io/versions/latest/sdk/notifications/#notificationcontent) is null
* callback of `addNotificationResponseReceivedListener` is not invoked

### Configuration

`expo init` produces a `android/build.gradle` containing

```
dependencies {
  classpath 'com.google.gms:google-services:4.3.3'
  classpath("com.android.tools.build:gradle:3.5.3")

  // NOTE: Do not place your application dependencies here; they belong
  // in the individual module build.gradle files
}
```

which is why I did not change it to `com.google.gms:google-services:4.2.0` as instructed by the [react-native-firebase Bare Workflow Setup](https://docs.expo.io/guides/setup-native-firebase/#bare-workflow-setup) instructions.

### Test Code

```js
// code executes synchronously as an import of the app's entrypoint (index.js)
Notifications.setNotificationHandler({
  handleNotification: async (event) => {
    console.log('Notifications.handleNotification', JSON.stringify(event, null, 2))
    return {
      shouldShowAlert: true,
      shouldPlaySound: false,
      shouldSetBadge: false,
    }
  },
  handleSuccess: (notificationId: string) => {
    console.log('Notifications.handleSuccess', notificationId)
  },
  handleError: (error) => {
    console.log('Notifications.handleError', error)
  },
})
Notifications.addNotificationReceivedListener((event) => {
  console.log('Notifications.handleReceived', JSON.stringify(event, null, 2))
})
Notifications.addNotificationResponseReceivedListener((event) => {
  console.log('Notifications.handleResponseReceived', JSON.stringify(event, null, 2))
})
```

### Output of app in foreground

```js
Notifications.handleNotification {
  "request": {
    "content": {
      "autoDismiss": true,
      "title": null,
      "sound": "default",
      "badge": null,
      "data": null,
      "body": null,
      "subtitle": null
    },
    "trigger": {
      "remoteMessage": {
        "originalPriority": 1,
        "sentTime": 1596039852832,
        "notification": {
          "lightSettings": null,
          "visibility": null,
          "sound": null,
          "eventTime": null,
          "titleLocalizationArgs": null,
          "localOnly": false,
          "usesDefaultSound": false,
          "channelId": null,
          "notificationPriority": null,
          "title": null,
          "icon": null,
          "vibrateTimings": null,
          "usesDefaultLightSettings": false,
          "notificationCount": null,
          "bodyLocalizationKey": null,
          "clickAction": null,
          "link": null,
          "body": "It appears notifications work fine on your device.",
          "tag": null,
          "titleLocalizationKey": null,
          "imageUrl": null,
          "ticker": null,
          "usesDefaultVibrateSettings": false,
          "color": null,
          "bodyLocalizationArgs": null,
          "sticky": false
        },
        "from": "891288934389",
        "data": {},
        "ttl": 2419,
        "to": null,
        "messageType": null,
        "priority": 1,
        "collapseKey": "<my-app-id></my-app-id>",
        "messageId": "<message-id>"
      },
      "type": "push"
    },
    "identifier": "<message-id>"
  },
  "date": 1596039852832
}

Notifications.handleReceived {
  "request": {
    "content": {
      "autoDismiss": true,
      "title": null,
      "sound": "default",
      "badge": null,
      "data": null,
      "body": null,
      "subtitle": null
    },
    "trigger": {
      "remoteMessage": {
        "originalPriority": 1,
        "sentTime": 1596039852832,
        "notification": {
          "lightSettings": null,
          "visibility": null,
          "sound": null,
          "eventTime": null,
          "titleLocalizationArgs": null,
          "localOnly": false,
          "usesDefaultSound": false,
          "channelId": null,
          "notificationPriority": null,
          "title": null,
          "icon": null,
          "vibrateTimings": null,
          "usesDefaultLightSettings": false,
          "notificationCount": null,
          "bodyLocalizationKey": null,
          "clickAction": null,
          "link": null,
          "body": "It appears notifications work fine on your device.",
          "tag": null,
          "titleLocalizationKey": null,
          "imageUrl": null,
          "ticker": null,
          "usesDefaultVibrateSettings": false,
          "color": null,
          "bodyLocalizationArgs": null,
          "sticky": false
        },
        "from": "891288934389",
        "data": {},
        "ttl": 2419,
        "to": null,
        "messageType": null,
        "priority": 1,
        "collapseKey": "<my-app-id>",
        "messageId": "<message-id>"
      },
      "type": "push"
    },
    "identifier": "<message-id>"
  },
  "date": 1596039852832
}

Notifications.handleSuccess "<message-id>"
```

### Output of app in background (tap on notification)

```js
// nothing at all
```

**Comment by ludwig-adoria** [comment] 2020-07-30 15:13
Same here, works well in iOS / broken on android 
you can test it with snack example on the documentation : https://docs.expo.io/push-notifications/overview/

**Comment by ludwig-adoria** [comment] 2020-07-30 15:40
Fix for me

**Comment by jm90m** [comment] 2020-08-27 21:23
@ludwig-adoria what was the fix ? It's broken on android for me but works well on iOS

**Comment by ludwig-pro** [comment] 2020-08-28 07:10
i maded a mistake with app.json on android

Open your app.json and add the following inside of the "expo" field:

```
{
  "expo": {
    ...
    "android": {
      ...
      "useNextNotificationsApi": true,
    }
  }
}
```

**Comment by dmbejar** [comment] 2020-09-06 10:59
What worked for me was just writing the Notifications functions **outside** the main App() function. 

`
Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});

Notifications.addNotificationResponseReceivedListener((response) => {
  alert('Notification message was clicked!');
});

export default function App() {
   // Your code
};
`

**Comment by dmbejar** [comment] 2020-09-06 11:03
What worked for me was just writing the Notifications functions **outside** the main App() function. 

```
import React from 'react';
import * as Notifications from 'expo-notifications';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});

Notifications.addNotificationResponseReceivedListener((response) => {
  alert('Notification message was clicked! And it worked even when the app was closed, my lucky friend!');
});

export default function App() {
   // Your code
};
```

**Comment by dekunleroy** [comment] 2020-09-08 15:03
> What worked for me was just writing the Notifications functions **outside** the main App() function.
> 
> ```
> import React from 'react';
> import * as Notifications from 'expo-notifications';
> 
> Notifications.setNotificationHandler({
>   handleNotification: async () => ({
>     shouldShowAlert: true,
>     shouldPlaySound: false,
>     shouldSetBadge: false,
>   }),
> });
> 
> Notifications.addNotificationResponseReceivedListener((response) => {
>   alert('Notification message was clicked! And it worked even when the app was closed, my lucky friend!');
> });
> 
> export default function App() {
>    // Your code
> };
> ```
@dmbejar did this work on android for you? I'm testing on Android 10 and it's not working

**Comment by ltsharma** [comment] 2020-09-21 18:44
@dmbejar yes it worked for me too (for android emulator), gonna test device now.

**Comment by ltsharma** [comment] 2020-09-21 20:13
It worked outside of component...

**Comment by coopbri** [comment] 2020-10-10 21:23
@ltsharma, I'm glad to hear this worked for you outside of the component! I tried doing the same with no luck. Is it still working for you? I am using Expo SDK 39.

**Comment by ltsharma** [comment] 2020-10-10 21:24
Yes, its working for me. Even now...

**Comment by coopbri** [comment] 2020-10-10 21:42
Thanks @ltsharma! I must have a deeper problem then, will investigate. Appreciate your response.

**Comment by Maoravitan** [comment] 2020-11-05 10:12
> I'm having a weird problem too and it sounds like its related but might not be.
> 
> `addNotificationReceivedListener` SOMETIMES gets called with the notification in foreground. But never gets called in the background...
> 
> But the alert never shows, ever.
> 
> I had to eject and its just caused the push notifications to break. (iv followed instructions to setup correctly)
> Also tried the 0.1.3 version
> 
> Permissions says push notifications are granted, but app isn't showing in the notifications settings, so weird

for getting notification when the app is in background you should use: addNotificationResponseReceivedListener
for example:

```
useEffect(() => {
    
    //when app close
    const backgroundSubscription = Notifications.addNotificationResponseReceivedListener( (response:NotificationResponse) => {
      console.log('close ########')
      console.log(response.notification.request.content.data)
      const obj:{fieldId:number, insightId:number}|any = response.notification.request.content.data
    })

    //when app open
    const foregroundSubscription = Notifications.addNotificationReceivedListener( (notification:any) => {
      console.log('open ########')
    })
    return ()=>{
        backgroundSubscription.remove();
        foregroundSubscription.remove();
    };
  }, []);
```

**Comment by mfy5013** [comment] 2020-11-06 03:36
for me it was not working on android. Once i set useNextNotificationsApi: true it worked perfectly

**Comment by MWaqasHussain-dev** [comment] 2020-11-06 05:53
Its working for me when i have placed it to ComponentDidMount(){} root level
