### ISSUE TITLE
GL Shadows rendering not working properly

### ISSUE THREAD

**Issue by gavrix** [expo/expo#7502] opened 2020-03-23 17:52 UTC
I have been trying to make my scene render meaningful shadows for a while now. At first it was rendering as if the whole scene was covered in shadows. I then found this reference https://github.com/expo/expo-three/issues/38
the trick of removing `createRenderbuffer` sort of made a difference, but shadows are still off on a complex scene. 
take a look at this gif
![1](https://user-images.githubusercontent.com/354010/77346559-d04d8d80-6d0c-11ea-9b09-867640aaabdd.gif)

here's the code
```
  gl.createRenderbuffer = (() => ({}));

  const renderer = new ExpoTHREE.Renderer({ gl });
  renderer.shadowMap.enabled = true
  renderer.shadowMap.type = THREE.BasicShadowMap

  renderer.setSize(gl.drawingBufferWidth, gl.drawingBufferHeight);
  renderer.setClearColor(0xffffff, 1.0);
  renderer.shadowMap.enabled = true;

  /// Standard Camera
  const camera = new THREE.PerspectiveCamera(70, gl.drawingBufferWidth / gl.drawingBufferHeight, 0.1, 1000);
  camera.position.set(10, 10, 0);
  camera.lookAt(0, 0, 0);

  // scene
  const scene = new THREE.Scene();

  scene.add(new THREE.AmbientLight(0xffffff, 0.5));

  const light = new THREE.DirectionalLight(0xffffff, 0.5);
  light.position.set(0, 5, 0);
  light.castShadow = true; // default false
  scene.add(light);

  const shadowHelper = new THREE.DirectionalLightHelper(light, 2, 0x0000ff)
  scene.add(shadowHelper)

  //Create a plane that receives shadows (but does not cast them)
  const planeGeometry = new THREE.PlaneBufferGeometry(10, 10, 32, 32);
  const planeMaterial = new THREE.MeshStandardMaterial({
    color: 0x00ff00,
    side: THREE.DoubleSide,
  });
  
  const plane = new THREE.Mesh(planeGeometry, planeMaterial);
  plane.receiveShadow = true;
  plane.rotation.x = Math.PI / 2;
  plane.position.y = -2;
  scene.add(plane);

  const material = new THREE.MeshPhongMaterial({color: 0xff0000});
  const geometry = new THREE.BoxGeometry(1, 1, 1);

  const cube = new THREE.Mesh(geometry, material);
  cube.castShadow = true; //default is false
  cube.receiveShadow = true
  cube.renderOrder = 3

  const another = new THREE.Mesh(new THREE.BoxGeometry(1.5, 1.5, 1.5), material);
  another.position.set(0, 2, 0)
  another.castShadow = true
  another.receiveShadow = true
  another.renderOrder = 1
  scene.add(another)

  light.shadow.camera.left = -1
  light.shadow.camera.right = 1
  light.shadow.camera.top = -1
  light.shadow.camera.bottom = 1
  
  const helper = new THREE.CameraHelper(light.shadow.camera)
  scene.add(helper)
  
  scene.add(cube);

  function animate() {
    requestAnimationFrame( animate );

    cube.rotation.x += 0.01;
    cube.rotation.y += 0.01;
    renderer.render( scene, camera );
    gl.endFrameEXP();
  }
  animate();

  renderer.render(scene, camera);
  gl.endFrameEXP();
```

I understand the bigger non-moving cube should NOT have any shadow on it, yet, the cube under it generates some shadow which looks like it's inverted even?

I suspect, that that this trick with suppressing framebuffer is only masking a problem ? or am I missing something?

**Comment by tsapeta** [comment] 2020-03-27 17:05
Hi @gavrix! I've transferred this issue to expo repository because it doesn't seem to be related to `expo-three` package. I was able to reproduce your issue without `expo-three`, using `THREE.WebGLRenderer`. So issue in `expo-gl` is more likely.

I tried to find out where this issue is and what's causing it, but without much success. What I've found so far:
- Certainly, `gl.createRenderbuffer = (() => ({}));` is not a solution to anything. This example uses a renderbuffer and this function must be implemented in the proper way so that it calls native OpenGL ES functions. It's just a coincidence it helped in any way.
- It happens on both iOS and Android and works well on web (I used Expo for Web where plain WebGLRenderingContext is being used) - so the problem might be somewhere in C++ code (same code used on both mobile platforms) which tries to imitate WebGL specification.
- Those cubes are not the cause - a minimal reproducible demo for me was to just use ambient light, directional light and a plane. In such scenario you can notice that the directional light makes a shadow on the plane - it's definitely not what we expect.
- Three.js is logging some warnings that `EXT_texture_filter_anisotropic` and `OES_texture_float_linear` extensioins are not supported. In fact, `expo-gl` doesn't support extensions even though the devices support them. Despite this it's relatively easy to mock these extensions so I did it. Warnings were gone, but issue remained.
- I tried using `PointLight` instead of `DirectionalLight` with no luck - the light had no effect.

Can I ask you @gavrix to provide the code for the second example with small balls? I'd just like to check whether this is the same issue or not. Hopefully it will help me discover something else 😉

**Comment by tsapeta** [comment] 2020-03-30 21:07
I have some good news 😊 I've got it working! 🥳

Briefly, once you put any light to your scene, three.js starts using depth/stencil renderbuffer to make things rendered in correct order. Sadly, it uses `gl.DEPTH_STENCIL` as the second parameter (called `internalformat`) of `renderbufferStorage` and everything would be fine because it's fully compliant with WebGL specification, however it turned out this constant is not allowed in OpenGL ES 3.0 equivalent `glRenderbufferStorage` that we use internally. It requires more specific option that tells what's the size of depth and stencil buffers – the solution is to use `gl.DEPTH24_STENCIL8` instead of `gl.DEPTH_STENCIL`.
This is to be fixed in our native C++ code, but before that you can use a workaround in your JS code, just put this at the beginning of `onContextCreate` callback:

```javascript
const originalRenderbufferStorage = gl.renderbufferStorage;
gl.renderbufferStorage = (...args) => {
  args[1] = args[1] === gl.DEPTH_STENCIL ? gl.DEPTH24_STENCIL8 : args[1];
  return originalRenderbufferStorage.apply(gl, args);
};
```

Please, let me know whether this workaround works, especially with the second demo 🙏

**Comment by gavrix** [comment] 2020-03-31 04:19
@tsapeta hey! thanks for such a fast response! proposed workaround appears to have fixed the issue. 
Here's the code I used for the last demo, all the shadows are perfect with your proposed work around. 

<details><summary>Here's the code I used for the last demo, all the shadows are perfect with your proposed work around. </summary>

```ts
const GLDemo = () => {
  const [camera, setCamera] = useState(null)
  const controlsRef = useRef<any>(null)
  const [gl, setGL] = useState(null)
  
  useEffect(() => {
    if (!gl) return 

    if (Platform.OS !== 'web') {
      const originalRenderbufferStorage = gl.renderbufferStorage;
      gl.renderbufferStorage = (...args) => {

        args[1] = args[1] === gl.DEPTH_STENCIL ? gl.DEPTH24_STENCIL8 : args[1];
      
        return originalRenderbufferStorage.apply(gl, args);
      
      };
    }

    const scene =  new THREE.Scene()
    scene.autoUpdate = true

    const camera = new THREE.PerspectiveCamera(75, gl.drawingBufferWidth / gl.drawingBufferHeight, 0.1, 1000);
    camera.position.z = 500;
    setCamera(camera)
      
    const renderer = new ExpoTHREE.Renderer({ gl, preserveDrawingBuffer: true });
    renderer.shadowMap.enabled = true
    renderer.shadowMap.type = THREE.PCFSoftShadowMap
    renderer.toneMapping = THREE.ACESFilmicToneMapping

    renderer.outputEncoding = THREE.sRGBEncoding

    renderer.setSize(gl.drawingBufferWidth, gl.drawingBufferHeight);
    
    const ambientLightIntensity =  2
    const ambientLight = new THREE.AmbientLight( 0x2222222, ambientLightIntensity);
    scene.add( ambientLight );

    const spotLightIntensity =  5
    const spotLight = new THREE.SpotLight(0xF2F7D5, spotLightIntensity, 0, 0.4 , 0, 1)
    spotLight.castShadow = true
    spotLight.shadow.radius = 2
    
    const lightGroup = new THREE.Group()
    lightGroup.add(spotLight)

    spotLight.position.set(300, 150, 150)              
    scene.add(lightGroup)

    const balls = new THREE.Group()
    scene.add(balls)

    for (let i = 0; i < 200; i++) {
      const subShape = new THREE.Mesh(new THREE.SphereGeometry(5, 10, 10), new THREE.MeshStandardMaterial({color: 0x0000ff, side: THREE.FrontSide, }))
      subShape.castShadow = true
      subShape.receiveShadow = true
      const container = new THREE.Object3D()
      container.add(subShape)
      balls.add(container)
      subShape.position.setComponent(0, 100)
      container.rotateZ(Math.random() * Math.PI * 2)
      container.rotateY(Math.random() * Math.PI * 2)      
    }

    const shpere = new THREE.SphereBufferGeometry(90, 50, 50)        
    const shape = new THREE.Mesh(shpere, new THREE.MeshStandardMaterial({color: 0xff0000, side: THREE.FrontSide, }))    

    shape.castShadow = true
    shape.receiveShadow = true        

    scene.add(shape)

    let stillOn = true
    const animate = () => {
        if (stillOn) requestAnimationFrame(animate);
        
        controlsRef.current && controlsRef.current.update()
        lightGroup.rotation.copy(camera.rotation)
        renderer.render(scene, camera);
        gl.endFrameEXP();
        
    };
    animate()
    return () => {
      stillOn = false
    }
  }, [gl])
  
//OrbitControls bridge for RN was taken from expo-three, it's optional for this demo
  return (
    <OrbitControls style={{flex: 1}} camera={camera} controlsRef={controlsRef}>
      <GLView style={{flex: 1}} onContextCreate={setGL}/>
    </OrbitControls>
  )
}

```
</details>

![IMG_EAC6BFAFDC6E-1](https://user-images.githubusercontent.com/354010/77986413-ffec2f00-72e4-11ea-8ea0-e919ed251a54.jpeg)

**Closed** 2020-03-31 16:30 UTC
Labels: GLView
