### ISSUE TITLE
[docs] 

### ISSUE THREAD

**Issue by JuanRdBO** [expo/expo#21833] opened 2023-03-24 18:49 UTC
### Summary

The native code in the guide [here](https://docs.expo.dev/bare/installing-updates/) has [changed](https://react-native-community.github.io/upgrade-helper/?from=0.70.7&to=0.71.3) for the expo sdk 48 and it's recommended RN version. Is there a way to update it to the newest version?

### Link to the related docs page

https://docs.expo.dev/bare/installing-updates/

**Comment by douglowder** [comment] 2023-04-05 07:17
Dupe of #21835, closing.

**Closed by douglowder** 2023-04-05 07:17 UTC
Labels: docs
