### ISSUE TITLE
Expo 25 standalone iOS build crashes Facebook login

### ISSUE THREAD

**Issue by dackom** [expo/expo#1334] opened 2018-01-26 16:25 UTC
After upgrading to expo 25, in standalone iOS expo build facebook login crashes app. In expo client, and in simulator, everything is working normal. First a black screen for a second, and then app quits.

In expo 24, everything was working normal.

Anyone else experiencing this?

**Comment by mikesholiu** [comment] 2018-01-26 20:38
I am experiencing this exact issue as well, although it started in expo 24. In production mode while developing in the simulator it works fine, but in the standalone it causes a crash.

**Comment by esamelson** [comment] 2018-01-26 23:13
actually, going to close as a duplicate of #1327

**Closed by esamelson** 2018-01-26 23:13 UTC
Labels: project: ios-runtime, project: sdk
