### ISSUE TITLE
MOV Video Playback Stretched on iOS

### ISSUE THREAD

**Issue by mespencer** [expo/expo#10248] opened 2020-09-19 19:17 UTC
### Summary of Issue
When playing MOV video files on iOS the initial playback is stretch/squished. Once it has looped it will resize to whatever resize mode is specified.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
 Expo CLI 3.24.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.3.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 

Platform: iOS 14.0

### Reproducible Demo

https://snack.expo.io/@mespencer/mov-video-issue
 
### Steps to Reproduce
Render a Video component with an MOV video specified as the source (either local or remote).

### Expected Behavior vs Actual Behavior

It should respect the specified resize mode immediately instead playing back once stretched/squished before respecting the resize mode.

**Comment by iamdavidmartin** [comment] 2020-09-19 20:22
@mespencer is your issue the same as the one I just posted?
https://github.com/expo/expo/issues/10249

**Comment by mespencer** [comment] 2020-09-19 21:06
Yes, I believe so

**Comment by vuongductuanktmt** [comment] 2020-09-21 10:18
same issue!

**Comment by brentvatne** [comment] 2020-10-01 00:19
closing because duplicate of https://github.com/expo/expo/issues/10249 :)

**Comment by byCedric** [comment] 2020-10-08 13:06
> closing because duplicate of #10249 :)

**Closed by byCedric** 2020-10-08 13:06 UTC
Labels: AV, Issue needs review, Video
