### ISSUE TITLE
getCurrentPositionAsync halt in Android Expo App

### ISSUE THREAD

**Issue by ccnuyan** [expo/expo#10707] opened 2020-10-16 16:12 UTC
### getCurrentPositionAsync halt in Android Expo App

Location.getCurrentPositionAsync() halt in Android Expo App

### Environment

sdk:39.0.3
model: Huawei STK-AL100
Andriod Expo App:2.17.4
```
Expo CLI 3.28.0 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.3 => 39.0.3 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ./sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.28.0
    Expo Workflow: managed
```

### Reproducible Demo

```
const onGetLocationButtonPress = async () => {
    let { status } = await Location.requestPermissionsAsync();
    if (status !== "granted") {
      setErrorMsg("Permission to access location was denied");
    } else {
      console.log(1);
      let loc = await Location.getCurrentPositionAsync();
      console.log(2);
      setLocation(JSON.stringify(loc));
      console.log(3);
    }
  };
```

### Steps to Reproduce

Press GetLocationButton

### Expected Behavior vs Actual Behavior

Expected: 
1
2
3
Actual: 
1

when it works in ios simulator.

**Comment by ronal2s** [comment] 2020-10-19 01:17
Set a catch and let me know what error return

**Comment by hulleyaj** [comment] 2020-10-21 01:28
Let me know if you can't see this repo.
https://github.com/hulleyaj/ll-location/commits/main
Commit:
8f9a1f6bc0b37a7faf8cd5e3c222a827b2d3ee1b

If you yarn, and then run on your android phone, I'm having the same issues.  I'm still trying to figure out whats going on.

On the entrypoint of App.js, the component's useEffect can resolve the location.  I copy and pasted the code into a sub component (NativeScreen) to which I'm still rendering inside App.js but NativeScreen can't get the location.


Psuedo:

function App() {
useEffect(() => location = getLocation() )

<App.js>
  <Text>{ location }</Text> //renders fine
  <NativeScreen /> //location hangs up
</App.js>
}

**Comment by ccnuyan** [comment] 2020-10-24 13:45
> Set a catch and let me know what error return
I change the code to
`  const onGetLocationButtonPress = async () => {
    let { status } = await Location.requestPermissionsAsync();
    if (status !== "granted") {
      setErrorMsg("Permission to access location was denied");
    } else {
      try {
        console.log(1);
        const loc = await Location.getCurrentPositionAsync({
          accuracy: Location.Accuracy.Low,
        });
        console.log(2);
      } catch (err) {
        console.log(3);
        console.log(err);
      }
    }
  };`

no error to catch, the log in terminal is

`
Running application on STK-AL00.
1
`

**Comment by shizongli94** [comment] 2021-02-06 05:06
Got the same problem.
Mine solved by installing Google Play Services since I don't already have one on my Android phone. 

It would be nice if the Expo team can do away with Google stuff.

**Comment by uvishere** [comment] 2021-05-10 05:04
Hi,
did anyone found a resolution to this issue? I'm having a similar type of error. 
The problem persists on a real android device only. 

Any solutions would be helpful.

**Comment by ARM-Visionpool** [comment] 2021-08-28 01:09
I've run into this same issue. Completely Broken within Expo SDK 42. I'm trying to run it on an Android 11 Samsung GS10 phone. Following elpampa's snack https://snack.expo.io/@rvieceli/expo-issue-10756 (on related iOS issue with same feature) I tried to run it on my phone directly and it never resolves. Tried in my own codebase and it always shows: 

_Location provider is unavailable. Make sure that location services are enabled._
at http://IP_ADDRESS:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:260079:91 in getCurrentPositionAsync$

**Comment by byCedric** [comment] 2021-09-10 15:27
Hi everyone, I'm closing this issue in favor of #14248. If you are still having issues with this today, please [take a look at this comment](https://github.com/expo/expo/issues/14248#issuecomment-915099538).

**Closed by byCedric** 2021-09-10 15:27 UTC
Labels: Android, Location, needs review

**Comment by OneLoneFox** [comment] 2022-11-09 22:59
I'm still facing this issue in SDK 45 it also happened in SDK 43 before upgrading, It happens at random and halts indefinitely without *ever throwing an exception

`
useEffect(() => {
    (async () => {
      try {
        console.log('Trying to request Location permission');
        let { status } = await Location.requestForegroundPermissionsAsync();
        console.log('Location permission status is:', status);
        if (status !== 'granted') {
          return;
        }

        console.log('Trying to get current position');
        let location = await Location.getCurrentPositionAsync({
          accuracy: Location.Accuracy.Balanced,
          enableHighAccuracy: true,
          timeInterval: 5
        });
        console.log('Got current position');
      } catch (e) {
        console.log('Caught', e.message);
      }
    })();
}. []);
`

Sometimes the output will reach "Got current position" and sometimes it will halt at "Trying to get current position" without throwing an exception.

This happens randomly and I can reproduce it both in an android emulator with google services and on a physical device (Xiomi Mi 9T - android 10)

*I waited for over a minute and the promise never resolved nor did it throw an exception
