### ISSUE TITLE
Font.loadAsync loads some fonts, does not load others

### ISSUE THREAD

**Issue by rahamin1** [expo/expo#4217] opened 2019-05-14 11:39 UTC
### Environment

Expo CLI 2.17.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.9.4 - C:\Users\yossi\AppData\Roaming\npm\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

Target: Android

### Steps to Reproduce

In an expo generated project (project with tabs), I modified the Font.loadAsync call as following:

```
Font.loadAsync({
  // The following fonts are loaded successfully
        'space-mono': require('./assets/fonts/SpaceMono-Regular.ttf'),
        'pixel-font': require('./assets/fonts/PixelFJVerdana12pt.ttf'),
        'Anton': require('./assets/fonts/Anton.ttf'),
        'OpenSans-Regular': require('./assets/fonts/OpenSans-Regular.ttf'),
        'OpenSans-CondLight': require('./assets/fonts/OpenSans-CondLight.ttf'),
        'Montserrat-Regular.ttf': require('./assets/fonts/Montserrat-Regular.ttf'),

  // The following fonts are not loaded (an error message is displayed. See 'actual behavior' below.
        'Raleway-Regular': require('./assets/fonts/Raleway-Regular.ttf'),
        'Alegreya-Regular': require('./assets/fonts/Alegreya-Regular.ttf'),
        'NotoSans-Regular': require('./assets/fonts/NotoSans-Regular.ttf'),
        'Oswald-Regular': require('./assets/fonts/Oswald-Regular.ttf'),
        'EBGaramond-Regular': require('./assets/fonts/EBGaramond-Regular.ttf'),
        'RobotoRegular': require('./assets/fonts/Roboto-Regular.ttf'),
      }),
```

### Expected Behavior

To have all fonts loaded successfully.

### Actual Behavior

In the above fonts list, all the fonts that are listed after `The following fonts are not loaded `  are not loaded. The others are loaded properly.
For the fonts that don't load, I get the following message:
`Font.loadAsync unexpected exception: Font not found /data/user/0/host.exp.exponent/cache/ExperienceData/<Folder>/ExponentAsset-<number>.ttf`

### Reproducible Demo

- Create a new expo project, using `expo init` (with tabs)
- Replace `Font.loadAsync` with the above code
- Run the app on your android emulator or device

### App.json:

```
{
  "expo": {
    "name": "expo-fonts2",
    "slug": "expo-font2",
    "privacy": "public",
    "sdkVersion": "32.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "packagerOpts": {
      "assetExts": ["ttf"]
    },
    "icon": "./assets/images/icon.png",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  }
}
```

### package.json:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-navigation": "^3.0.9"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "jest-expo": "^32.0.0"
  },
  "private": true
}
```

**Comment by tanx** [comment] 2019-06-10 17:29
I'm having this problem too in Expokit. Upgraded to expo 33 and did a fresh eject. Some `.ttf` files cannot be loaded.

**Comment by brentvatne** [comment] 2019-06-10 17:48
can you share the font files that you are having trouble with? and preferably a full reproducible example?

**Comment by rahamin1** [comment] 2019-06-10 19:03
You can try mine...

**Comment by tanx** [comment] 2019-06-14 21:08
> can you share the font files that you are having trouble with? and preferably a full reproducible example?

@brentvatne I pushed it here. thanks for your time.

https://github.com/lightninglabs/lightning-app/tree/mobile/expokit-33.0.5/mobile

**Comment by tanx** [comment] 2019-06-14 21:12
The exact error message is:
```
[Unhandled promise rejection: Error: Downloaded file for asset 'OpenSans-Light.ttf' Located at http://192.168.1.201:19001/assets/../src/asset/font/OpenSans-Light.ttf?platform=android&hash=9ff12f694e5951a6f51a9d63b05062e7?platform=android&dev=true&minify=false&hot=false failed MD5 integrity check]
```

**Comment by rahamin1** [comment] 2019-06-15 05:06
I am not sure that the problem that @tanx is having is the same as mine: my project is not ejected, and I am getting a different error message.

**Comment by Josh-Burgess** [comment] 2019-06-17 15:21
Having this same issue with image assets after upgrading to SDK 33.

Happens both in the ejected and non-ejected versions of the app.

Code to load images is here:
```
export async function LoadImage(Assets, {key, image}) {
	if (typeof image === 'string') {
		const isLoaded = await Image.prefetch(image);

		Assets[image] = {uri: image, isLoaded};
	} else {
		console.log(`loading ${key}`);
		Assets[key] = await Asset.fromModule(image);
		await Assets[key].downloadAsync();
		console.log(`${key} downloaded`);
	}

	return Assets;
}
```

**Comment by robertcreaner** [comment] 2019-06-28 23:51
Also experiencing this issue after upgrading to expo 33. It only started to occur after my assets were 'optimized'. The doesn't seem to be a way to disable the new optimize assets feature either :/

**Comment by brentvatne** [comment] 2019-06-28 23:53
@robertcreaner - i can't imagine that those things are related, unless you're depending on loading image files as fonts for some reason. but i'm willing to be convinced with a reproducible example

**Comment by tanx** [comment] 2019-06-29 00:12
FWIW I get this error only on bare builds when starting the dev server. The bundled JS can load the fonts and images just fine.

**Comment by dayman** [comment] 2019-08-01 14:21
Having same error but after updating to Expo 34. Before (on 33) there was no issues with same ttf files.

**Comment by robertcreaner** [comment] 2019-08-06 18:06
Not sure if this is related, but some of my assets were failing the md5 integrity check because the file name contained a special character '+'. 

Changing '5+.png' to '5plus.png' fixed it for me

**Comment by tonnenpinguin** [comment] 2019-08-13 10:28
I'm seeing the same issue as @dayman . After upgrading to 34 I got the following error message once:
```
fontFamily "Roboto-Regular" is not a system font and has not been loaded through Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
```
It seems like the App refuses to load all assets (including icons) for me though. Removing all Special Characters from the file names didn't change anything either.

**Comment by chumlee007** [comment] 2019-08-14 03:06
I'm have the same issue.  I created a clean project, tried loading the font as per your example using SDK 34, and I keep getting the fontFamily is not a system font error. 

[test-app.zip](https://github.com/expo/expo/files/3499674/test-app.zip)

**Comment by robertcreaner** [comment] 2019-08-14 17:16
@chumlee007 Can you try replace your code with this:
`await Promise.all([Font.loadAsync({'Mont': require('./assets/Montserrat-Regular.ttf')})]);`

**Comment by mohmdalfaha** [comment] 2019-08-17 20:15
I am facing the same issue when importing Font from 'expo'
when upgrading to 33 I get a lot of deprecation messages 

I just ignored the new deprecation messages and kept importing form 'expo' for now as it works fine, hoping It get fixed soon

`import { AppLoading, Font, Asset, Icon } from 'expo';`
`//import * as Font from 'expo-font';`
`//import { Asset } from 'expo-asset';`
`//import * as Icon from '@expo/vector-icons'`

**Comment by tonnenpinguin** [comment] 2019-08-19 09:13
@robertcreaner I refactored my App to use the AppLoading component and its callbacks. However, the issue still persists :(

**Comment by robertcreaner** [comment] 2019-08-20 19:58
@tonnenpinguin have can you try the following: 
- delete your node_nodules and package-lock.json 
- run npm install 
- run expo start -c

If that doesnt work try using yarn or the expo install command

**Comment by rnakhan** [comment] 2019-08-25 19:07
I was able to solve this by deleting yarn.lock (I am using yarn) and removing node_modules after upgrade. Then running yarn install again.

On the way I also upgraded expo cli, node and also used expo_codemod to take care of any upgrade related changes to my code. I also had to "expo install" packages that are moved out like react-native-gesture-handler

I think the key for me was to delete the lock files and also clear cache by expo start -c

**Comment by mfy5013** [comment] 2019-08-31 01:43
Same issue here worked fine with SDK 33

**Comment by mfy5013** [comment] 2019-08-31 02:36
Resolved when deleted node_modules and cleared cache

**Comment by lc3t35** [comment] 2019-10-28 14:31
SDK35, I have the same problem on Android (works fine with iOS)
```
we have in handleLoadingError ! [Error: Font.loadAsync unexpected exception: Font asset not found asset_297d2036e658f24e043ac6b49106f881.ttf]
```

**Comment by LouisJS** [comment] 2019-11-22 14:31
Upgraded from Expo SDK 33 to SDK 34. Loading 'roboto-regular.tff' from assets.

```
fontFamily "Roboto-Regular" is not a system font and has not been loaded through Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Font.loadAsync.
- node_modules/expo/build/environment/muteWarnings.fx.js:26:24 in error
- ... 39 more stack frames from framework internals
```

While i'm loading font with :

```
await Font.loadAsync({
        'Roboto-Regular': require('../assets/fonts/roboto-regular.ttf'),
        'Roboto-Bold': require('../assets/fonts/roboto-bold.ttf'),
});
```

**Comment by brentvatne** [comment] 2019-11-22 23:40
@LouisJS - please share a reproducible example

**Comment by lc3t35** [comment] 2019-11-23 13:31
I solved this with sdk35 with `undocumented` expo command
```
expo bundle-assets --platform android --dest ./android/app/src/main/assets

expo bundle-assets --help

  Usage: bundle-assets [options] [project-dir]

  Bundles assets for a detached app. This command should be executed from xcode or gradle.

  Options:

    --dest [dest]          Destination directory for assets
    --platform [platform]  detached project platform
    --config [file]        Specify a path to app.json
    -h, --help             output usage information
```

**Comment by kopax** [comment] 2019-12-30 21:02
I have the same issue on sdk 36. Using safari. `Font.loadAsync ` fail after 3000ms timeout.

**Comment by thoarrown** [comment] 2020-01-05 14:13
I have same issue with environment: 
expo SDK: 36.0.0;
expo-cli: 3.11.3
Then I have fixed by: npm install expo@36.0.1 or npm install expo@36.0.2 then create file react-native.config.js add: 
module.exports = {
	rnpm: {
		assets: ["./assets/fonts"]
	}
};
. Done Fixed

**Comment by kopax** [comment] 2020-01-05 14:46
It seems that `rnpm` is deprecated, see https://medium.com/@a_rahmanshah/can-you-please-update-the-article-with-react-native-config-js-as-rnpm-is-now-deprecated-468139cfc84b and https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide so it should just be: 

```js
module.exports = {
  assets: ["./assets/fonts"]
};
``` 

How did you do?

**Comment by thoarrown** [comment] 2020-01-05 14:55
> @thoarrown It seems that `rnpm` is deprecated, see https://medium.com/@a_rahmanshah/can-you-please-update-the-article-with-react-native-config-js-as-rnpm-is-now-deprecated-468139cfc84b and https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide so it should just be:
> 
> ```js
> module.exports = {
>   assets: ["./assets/fonts"]
> };
> ```
> 
> How did you do?

Well, actually, I did read the medium article, I tried to do it but it still didn't work. So I went looking for another answer on github and I tried following an answer on it:
expo sdk 36.0.0 => 36.0.2
create react-native.config.js file and instead of you add in package.json, you put in react-native.config.js like this:
```
module.exports = {
   assets: ["./assets/fonts"]
};
```
Remember to delete `rnpm` in package.json
If I do not satisfy you can clarify, I am very pleased.

**Comment by oshimayoan** [comment] 2020-01-23 07:38
> I have the same issue on sdk 36. Using safari. Font.loadAsync fail after 3000ms timeout. I just catch the error and do nothing, because I do not see unloaded font. Is this a good way to solve the problem? Idk.

Hey @kopax, have you solved yours? I got the same problem, not just on Safari but also on Firefox.

**Comment by kopax** [comment] 2020-01-23 08:42
When I say safari, I mean the safari browser installed on the iphone. 
I haven't tried with another browser on ios.

I haven't found how to solve it, I just wrapped the `Font.loadAsync` in a silent try catch block, and it work fine. No clue why this is happening

**Comment by oshimayoan** [comment] 2020-01-23 09:52
I think I found the cause. So actually, the font is loaded but it takes more than 3000ms on Safari and Firefox.

FontObserver that being used by the `expo-font` has default timeout 3000ms and there is no way to change that timeout from `loadAsync`.

So when I tried to set the state without waiting for `loadAsync` it works fine on the web even though the default font will be used first as the font has not been loaded yet.

This implementation is fixing my problem:
```tsx
if (IS_WEB) {
  Font.loadAsync({
    'open-sans-bold': require('./assets/fonts/OpenSans-Bold.ttf'),
  });
} else {
  await Font.loadAsync({
    'open-sans-bold': require('./assets/fonts/OpenSans-Bold.ttf'),
  });
}
setFontsLoaded(treu);
```

**Comment by kopax** [comment] 2020-01-28 06:30
> FontObserver that being used by the `expo-font` has default timeout 3000ms and there is no way to change that timeout from `loadAsync`.

Thanks for finding the root cause, perhaps a PR to expo where they configure `FontObserver` would do the trick in a futur version.

I do not get your duplicate code, this seems more straightforward and less error prone (you will still wait 3000ms, which is better than calling `setFontsLoaded(true)` after 0ms like in your code sample):

```jsx
    try {
      await Font.loadAsync(fonts);
    } catch (e) {
      // Safari FontObserver timeout after 3000ms, this will fail silently
    }
```

**Comment by oshimayoan** [comment] 2020-01-28 09:29
The reason I use duplicate code is that the `FontObserver` is using setTimeout. Unfortunately, we can't *catch* any thrown error by asynchronous code such as `setTimeout` using `try..catch`. That's why we need `.catch` for that.

Actually, I could also simplify that code into:
```tsx
Font
  .loadAsync({
    'open-sans-bold': require('./assets/fonts/OpenSans-Bold.ttf'),
  })
  .then(() => setFontsLoaded(true))
  .catch(() => setFontsLoaded(true));
```

**Comment by oshimayoan** [comment] 2020-01-28 09:52
Oops, my bad. I think I still lack understanding regarding that matter.

I just re-read a few sources and you're right! I can actually use `try..catch` for that.

**Comment by kopax** [comment] 2020-01-29 04:05
The last synthax with `.then().catch()` is the asynchronous form. with `async/await`, it is synchronous`, beware it is different, especially if you run something after that line.

For your understanding, every function that return pending promise can be wrapped in a try catch block equivalent to what you just wrote.

.then() is unecessary, since we wait with `await`, the next line can be setFontsLoaded(true) or anything else that can be run after. The catch block is like the `.catch()`. More generally, when using `async/await` with promise, the code will generally look cleaner and more maintainable because it doesn't have async and sync code everywhere.

**Comment by WahidHasanAriyanto** [comment] 2020-03-03 07:24
> I solved this with sdk35 with `undocumented` expo command
> 
> ```
> expo bundle-assets --platform android --dest ./android/app/src/main/assets
> 
> expo bundle-assets --help
> 
>   Usage: bundle-assets [options] [project-dir]
> 
>   Bundles assets for a detached app. This command should be executed from xcode or gradle.
> 
>   Options:
> 
>     --dest [dest]          Destination directory for assets
>     --platform [platform]  detached project platform
>     --config [file]        Specify a path to app.json
>     -h, --help             output usage information
> ```
> 
> If you build with Android Studio rather than gradlew command, this is not run; so you have to run it manually before building.

never did this before but everything gone well. But yesterday, when i run npm start after build with android studio i need to do this expo bundle assets

**Comment by ccheever** [comment] 2020-03-20 23:37
Hi--

We think there are two issues here.

One is a possible issue with Android font loading -- that some font files work and some font files don't. If you are having this issue, please create a new issue with a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) including the actual font files you are having trouble loading, and we can investigate that. We didn't see any of the actual font files here in any of the comments where people had this problem.

The other issue here is that there is no way to configure the timeout for font loading in Expo web currently, even though library under the hood being used does have a configurable timeout (that defaults to 3 seconds / 3000 ms). If you are interested in configuring that option, then please open a new issue asking for that and explaining what is important to you. cc @EvanBacon 

Closing this issue for now, but please open a new focused issue if you have one of the above issues or a different issue.

**Closed by ccheever** 2020-03-20 23:37 UTC
Labels: Font

**Comment by markcorrea** [comment] 2021-05-14 00:12
Have been facing the same issue today, what solved for me was:
- install `expo-app-loading` instead of `expo` to use AppLoading;
- remove `node-modules`;
- remove `package-lock.json`;
- run in terminal `npm cache clean -f`;
- run in terminal `npm install`;

After that the font loaded.

**Comment by sultan-arshi** [comment] 2025-04-05 19:47
+1
