### ISSUE TITLE
[expo-media-library][Android] Add support for presentPermissionsPickerAsync for Android

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#29537] opened 2024-06-07 13:22 UTC
### Minimal reproducible example

https://github.com/RRaideRR/expo-media-library-selective-permissions

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Android introduced support for partial photo access a couple of months ago (https://developer.android.com/about/versions/14/changes/partial-photo-video-access). If the user gave `accessPriviliges=limited`, expo-media-library provides no way to ask him again to adjust his selection. `expo-image-picker` resolved that issue with #28510. 

My current solution is to re-ask the user to give his permission on Android. However, this does not trigger the `MediaLibrary.addListener`. So there is no chance to recognise asset changes on Android.

```
  if (Platform.OS === 'ios') {
    MediaLibrary.presentPermissionsPickerAsync();
    return;
  }

  if (Platform.OS === 'android') {
    requestPermission();
  }
```

In my naive imagination it would be nice to have the `presentPermissionsPickerAsync` method work for Android as well (in a similar manner compared to iOS).

iOS:
https://github.com/expo/expo/assets/3411292/5d2379ca-1734-4574-9925-f0a5939d7bd9

Android:

https://github.com/expo/expo/assets/3411292/bf6c5136-af26-4dfa-a54c-cf0be4781e25

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
      Watchman: 2024.04.29.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/opt/ruby/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.11 => 51.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by vonovak** [comment] 2024-06-19 06:49
@RRaideRR hello and thanks for the bug report. You're mentioning https://github.com/expo/expo/pull/28510, though afaict that PR didn't really deal with permissions (and it wasn't merged). The last PR I see dealing with permissions is https://github.com/expo/expo/pull/28897 - can you just confirm which you intended to link?
Thank you :)

**Comment by RRaideRR** [comment] 2024-06-19 08:23
As you pointed out: #28897 brings granular permissions on Android to `expo-image-picker`. That was also done with #27749 for `expo-media-library` and it works fine.

For those people who are writing their own image picker (note to my past self: don't do this again), I need a possibility to re-ask a user on Android to re-consider their media selection (similar to the iOS specific method `presentPermissionsPickerAsync`) .  

I think you are right that #28510 is not the right reference here (it seemed similar but I think it isn't).

**Comment by vonovak** [comment] 2024-06-19 09:34
@RRaideRR thanks for adding that.

The way I'm seeing it right now is:

- to re-ask a user on Android to change their media selection, call `MediaLibrary.requestPermissionsAsync()` - that brings up the expected dialog. You pointed this out in your workaround as well.
- as you also mentioned, the issue is that the listener subscribed via `MediaLibrary.addListener` is not triggered. From what I can tell, the native code that backs up the listener will fire the listener when new assets are added to the media library. When user changes the selection, this event listener is not fired in native and this is the expected behavior on Android side afaict. We need to document this better. [Android docs](https://developer.android.com/about/versions/14/changes/partial-photo-video-access) don't mention a way to listen to changes in user selection, and I haven't found another resource that would cover this.

We could, after user changes selection and closes the permissions dialog, query the media store and try to figure out if the selection has changed. However, it'd be a brittle and inefficient process and I believe it's best that it's handled on the application side based on what your requirements are ([android docs](https://developer.android.com/about/versions/14/changes/partial-photo-video-access#query-library) - this would correspond to `MediaLibrary.getAssetsAsync()` on Expo's side).

So the way I see the resolution here is to keep the existing behavior and improve the docs. 

Thanks for reporting and let me know if you have some more thoughts.

**Comment by RRaideRR** [comment] 2024-06-20 18:24
Hey @vonovak ,

thanks a lot for your detailed thoughts on this and your PR which also includes an update for the docs. Really appreciate this. I think this will make things clearer in the future.

> However, it'd be a brittle and inefficient process and I believe it's best that it's handled on the application side based

I agree here as well :).

**Closed** 2024-06-24 13:26 UTC
Labels: MediaLibrary, Issue accepted
