### ISSUE TITLE
[GLView] GLView on RN 0.62 fails on getting context because: undefined is not an object (evaluating 'gl.__exglCtxId = exglCtxId')

### ISSUE THREAD

**Issue by pacoelayudante** [expo/expo#7623] opened 2020-04-03 01:43 UTC
#### ¿What?
GLView on RN 0.62 throws error #6583 constantly, in development and in release (on Android)
`undefined is not an object (evaluating 'gl.__exglCtxId = exglCtxId')`
I'm using
 * React Unimodules 0.9.0
 * React Native 0.62 (recently released)
 * Expo-GL 0.8.1

#### Then...
So in my research I arraived to this point! The culprit!?
https://github.com/expo/expo/blob/66d2c309df2ba2b976d54fa13015d915129fef94/packages/expo-gl-cpp/android/src/main/jni/EXGL.cpp#L28-L33

To reach that point, I asked a few questions to the code, specifically here
https://github.com/expo/expo/blob/876929686c1d843ea016e23fd592cadbbe15a52e/packages/expo-gl/build/GLView.js#L329-L333
I asked the program to print some stuff, and I found out that when I did
`console.log(global.__EXGLContexts)`
that returned `{"":and here the glcontext}`
so
`console.log(Object.keys(global.__EXGLContexts))` -> `[""]`

#### Finally (a temporary workaround)
so I was like... heck, let's try
`const gl = global.__EXGLContexts[""];`
`gl.__exglCtxId = exglCtxId;`
`delete global.__EXGLContexts[""];`
And that works! But it's probably nasty, in some way. So that's that...

**Comment by giorgioma** [comment] 2020-04-06 18:36
I have removed and reinstalled npm packages, it now seems to work out of the box, maybe it was due to an old dep?

**Comment by pacoelayudante** [comment] 2020-04-06 21:14
> I have removed and reinstalled npm packages, it now seems to work out of the box, maybe it was due to an old dep?
Mmhhh.. weird ¿do you recall wath packages have you reinstalled?

**Comment by brentvatne** [comment] 2020-04-06 22:14
we generally test compat of libraries in expo sdk against the latest version that we support in the managed workflow (currently 0.61.5) but will move towards 0.62 compat now as the 0.62 release itself stabilizies and we start to use it at expo as well

**Comment by cruzach** [comment] 2020-04-14 19:18
Looks like this works on a bare project using 0.61, so I'm going to close this issue because of what Brent said above ^

**Comment by pacoelayudante** [comment] 2020-04-14 22:31
> Looks like this works on a bare project using 0.61, so I'm going to close this issue because of what Brent said above ^

I see how that makes sense. But I still think this may come handy when porting to 0.62, if not already handled.
But... it might also have been a local problem, as giorgioma said, he get it working resintalling some libraries.
And I also should notify that this worked on dev mode, but in release mode it works with the "normal" code

**Comment by brentvatne** [comment] 2020-04-16 21:38
good point, i'll leave it open so we can look into it when we start updating to 62

**Comment by nicholasio** [comment] 2020-05-06 20:34
I can confirm the same issue when upgrading react native to 0.62 on an existing app. Your workaround did fix the issue.

**Comment by wood1986** [comment] 2020-05-08 08:42
@pacoelayudante Does the hack work on emulator?

**Comment by pacoelayudante** [comment] 2020-05-08 14:29
@wood1986 
Ummm... I do not remember using the emulator, I worked directly on device via adb...
BUT, I did made a modification when deploying to production. It seemed like the original code worked properly in some cases (maybe that happens with the emulator too?)
This is what I ended up doing
```javascript
    const gl = global.__EXGLContexts[exglCtxId] ? global.__EXGLContexts[exglCtxId] : global.__EXGLContexts[""];
    gl.__exglCtxId = exglCtxId;
    if (global.__EXGLContexts[exglCtxId]) {
        delete global.__EXGLContexts[exglCtxId];
    }
    else {
        delete global.__EXGLContexts[""];
    }
```
Assuming that code can work with both the original and unexpected behaviour of expo-gl
I hope it helps you
(keep in mind that, since this is changing the node_module, reinstalling or updating modules might reset these changes in your project)

**Closed** 2020-05-20 13:05 UTC
Labels: Needs triage

**Comment by wkozyra95** [comment] 2020-05-21 17:18
`expo-gl-cpp@8.2.0` should have this issue fixed

**Comment by serhiipalash** [comment] 2021-02-03 11:55
> `expo-gl-cpp@8.2.0` should have this issue fixed

@wkozyra95 , no the issue is still there. We have these deps in prod and the issue is live, but very rare - maybe 5-6 events per day on 27K daily users

```
"expo-gl": "^9.2.0",
"expo-gl-cpp": "^9.2.0",
```

**Comment by serhiipalash** [comment] 2021-02-07 11:14
> This is what I ended up doing

@pacoelayudante there is another bug which happens on next line with `glesVersion` being `undefined`

https://github.com/expo/expo/issues/8118

The issues seems to be related. Your patch fixes `evaluating 'gl.__exglCtxId = exglCtxId'` issue, but doesn't fix `glesVersion` issue. Do you have any idea what is happening here and why your fix didn't help?

**Comment by wkozyra95** [comment] 2021-02-08 15:41
Were you able to reproduce that locally or only on production? 
What device / android version?
Does it happen on a client or only in standalone builds?

Are you sure that those errors come from version older than 8.2.0? Fix was in native code so OTA update won't fix that and potentially there might be users that didn't update their app and still have old version.

**Comment by serhiipalash** [comment] 2021-02-08 17:18
> Were you able to reproduce that locally or only on production?

We were not able to reproduce `evaluating 'gl.__exglCtxId = exglCtxId` error locally, but It's presented in our production app. It's very rare. We tacked it 7 times during last 2 weeks having 30K daily active users.

> What device / android version?

Always on iOS, different versions of iOS starting from 12.4.9 and ending 14.4.

> Does it happen on a client or only in standalone builds?

We have a bare RN app, so it happens always in standalone builds.

> Are you sure that those errors come from version older than 8.2.0? Fix was in native code so OTA update won't fix that and potentially there might be users that didn't update their app and still have old version.

We upgraded to 8.4.0 from 8.1.0 on 10th October 2020, then we upgraded to 9.2.0 from 8.4.0 on 7th January 2021. We can see the bug on all app versions after upgrading from 8.1.0, but it disappeared in last 7 days when I applied the hack from  @pacoelayudante to `expo-gl` JS code.

We don't have OTA updates, we have just a bare app.

> Those js errors are only side effects of failed initialization

Ok, I understand. Can we try to fix it somehow? The error https://github.com/expo/expo/issues/8118 is still alive in our app and there are around 20 events daily and it's fatal. Maybe I should upgrade all Expo dependencies to the latest, not only `expo-gl` and `expo-gl-cpp`? We have a lot of expo packages in v8, for example `expo-assets`.

More context:
1. `evaluating 'gl.__exglCtxId = exglCtxId` was happening only on iOS and https://github.com/expo/expo/issues/8118 - on Android.
2. we have photo filters in our app, so we render multiple GLViews at once

![Simulator Screen Shot - iPhone 8 - 2021-02-08 at 19 17 37](https://user-images.githubusercontent.com/14208343/107256645-68965300-6a42-11eb-8af0-7add1e6e598a.png)

**Comment by pacoelayudante** [comment] 2021-02-21 21:41
Have in mind I have a very light understanding of that level of stuff, I had enough to stick a quick patch, but I can't go a lot further. Also, this was quite a while ago and I don't remember a lot of the situation.

What I can tell you and maybe can help you are two things.
First it was pretty consistent bug for me, that made it easier to hack, so the first thing I would try is push the thing until it begins to generate the bug more constantly.
The other thing is, the process I used to identify where to make the hack was to casually litter console logs right inside the expo libs around the "area of pain", first wider and then closing in until I could pinpoint it. I mean it's not a brillant solution, but it's a good temp solution if you are not already doing it (if you can reproduce the bug more constantly). It might be time consuming

side note: ¿you mean the thing happens 5-6 over 27k users? I don't think fixing that is worth your time, even the most basic upgrade to UX/UI will have more impact.

**Comment by Joshandrews43** [comment] 2021-06-02 21:39
Has anyone found a solution to this?  @serhiipalash  I have ~5k daily users and I see this ~15 times a day, every user in my app is using this feature every session, so that could be why we have a higher ratio.
