### ISSUE TITLE
App force closes when opening after detach to ExpoKit

### ISSUE THREAD

**Issue by pedro-lb** [expo/expo#6184] opened 2019-11-05 23:24 UTC
Hello,

I've been having a problem using detached apps with ExpoKit - when I run `react-native run-android`, the app is installed correctly but force closes as soon as I open it.

Expo version: 35.0.0

Steps to reproduce:

`expo init` - any type of app is fine
`expo eject` - select `ExpoKit`
`react-native run-android`

App is installed but force closes as soon as it's opened.

Also I'm using `react-native run-android` instead of `expo start` because I need to link a few libs but apparently `expo start` doesn't link them? It's confusing.

**Comment by cruzach** [comment] 2019-11-06 17:14
closing as duplicate of #6188

**Closed by cruzach** 2019-11-06 17:14 UTC
