### ISSUE TITLE
ScrollView not shrinking when virtual keyboard is open for a standalone app only

### ISSUE THREAD

**Issue by nbaghiro** [expo/expo#2242] opened 2018-09-21 18:59 UTC
Hi all,

I have developed an app using Expo and published it to both stores successfully. Really love your service. 

I just got a weird issue recently that happens only in my standalone app. 

### Expected Behavior
There are multiple pages inside the app that has input fields and I made the root container view for these fields to be ScrollView so when I have the virtual keyboard open, the whole view shrinks so that keyboard does not cover any input field. 

### Actual Behavior
The exactly expected behavior happens when I run the app locally or through expo client app. But when I build a standalone app to submit to stores, all the pages with input fields act like View and not shrink at all when the keyboard is open. 

### Reproducible Demo
I don't really know to provide a demo for this situation. It happens on the standalone app only so it is really weird. Let me know if you know an easier way to demo it to you. 

### Expo Versions
Expo SDK 29, live standalone build had 26.0.0 but I downgraded and rebuilt, the issue was still happening

### Screenshots
![closed](https://user-images.githubusercontent.com/12300880/45900839-eb091400-bdae-11e8-9fee-67cc572d7c20.jpg)
![expoclient](https://user-images.githubusercontent.com/12300880/45900840-eba1aa80-bdae-11e8-9cb8-b0b714f87370.jpg)
![standalone](https://user-images.githubusercontent.com/12300880/45900841-eba1aa80-bdae-11e8-9aed-8fe7ba68f7f7.jpg)

**Comment by kingofbob** [comment] 2018-09-25 05:07
#2172 similar issue to this

**Comment by esamelson** [comment] 2018-09-28 01:11
Closing as a duplicate of #2172 . We'll do our best to have a fix out for this soon -- in the meantime it seems like using `splash.resizeMode: "contain"` in app.json is a workaround.

**Closed by esamelson** 2018-09-28 01:11 UTC
