### ISSUE TITLE
Error building in Xcode 'UIView+React.h' file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by Jordan4jc** [expo/expo#2222] opened 2018-09-18 15:36 UTC
### Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.0.0
  Yarn: 1.5.1
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

ExpoKit

### Steps to Reproduce

(Write your steps here:)

1. Run `pod install` to make sure all pods are present
2. Open in xcode and run a build

### Expected Behavior

App the be built and installed on device

### Actual Behavior

Receive the error `'UIView+React.h' file not found with <angled> include; use "quotes" instead` in `TickViewManger.m` file

I am using the latest cocoa pods which I believe was 1.5.0, I saw [this issue](https://github.com/expo/expo/issues/1614) which suggests to uninstall cocoa pods and reinstall to 1.4.0 and that didn't seem to work either after running `pod install` again

How can I fix this from reappearing every time I `pod install` or upgrade expo?

**Comment by sjchmiela** [comment] 2018-11-24 08:45
Hey, @Jordan4jc! Your encountering of this issue was not caused by Expo, but rather a bug in a third-party library you've added to your ejected project — `react-native-material-kit`. 🙂

I'll let myself close this issue and kindly redirect you to https://github.com/xinthink/react-native-material-kit/issues/371, where Tamiyadd (don't want to @-at him without a purpose) proposed a simple, temporary solution, given that the https://github.com/xinthink/react-native-material-kit/pull/372 hasn't been merged yet.

**Closed by sjchmiela** 2018-11-24 08:45 UTC
