### ISSUE TITLE
"FileSystem.documentDirectory" is the same location as "FileSystem.cacheDirectory"

### ISSUE THREAD

**Issue by robinpaulson** [expo/expo#4811] opened 2019-07-03 16:26 UTC
### Environment
Expo CLI 2.21.2 environment info:
    System:
      OS: Linux 5.0 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
      npm: 6.9.2 - ~/.nvm/versions/node/v11.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.21.2

target: Android

### Steps to Reproduce
use these lines in an expo react-native project:
import * as FileSystem from 'expo-file-system';
console.log(FileSystem.documentDirectory)
console.log(FileSystem.cacheDirectory)

### Expected Behavior
that they print two different locations to the console

### Actual Behavior
they print the same location to the console. in my case:
file:///data/data/host.exp.exponent/files/ExperienceData/%2540anonymous%252Fsdtest-8210fe1e-4dac-41dd-a4f1-e1d8d323fd0d/

this appears to be the cache directory. it is not the documents directory

### Reproducible Demo
see above

**Comment by cruzach** [comment] 2019-07-05 18:20
What device is this on? [Tested on a simulator](https://snack.expo.io/@charliecruzan/nervous-macaroni-and-cheese), it returns two different directories

**Comment by robinpaulson** [comment] 2019-07-06 00:23
Samsung galaxy j1 ace

**Comment by lukmccall** [comment] 2019-07-15 12:10
Could you check if this issue occurred on different devices? We were trying to reproduce this behaviour, but we were unsuccessful. Could you also provide us your Android version.

**Comment by robinpaulson** [comment] 2019-07-16 04:30
I only have one device, will ask friends to try my code and get back to you.

Also, it's Android 5.1.1

**Comment by lukmccall** [comment] 2019-08-28 07:30
I am sorry for the late reply. 
Unfortunately, I'm not able to reproduce this bug.

**Comment by lukmccall** [comment] 2019-10-01 08:48
Could you check if this bug still exists in SDK 35?

**Comment by sjchmiela** [comment] 2019-11-04 12:16
We weren't able to reproduce this bug, hence I will let myself close this issue tentatively. I believe on SDK35 this bug shouldn't occur.

**Closed by sjchmiela** 2019-11-04 12:16 UTC
Labels: FileSystem, bug, project: android-runtime, status: needs more info
