### ISSUE TITLE
[SDK50] Icon font no longer works after upgrading from 49 to 50

### ISSUE THREAD

**Issue by MikeKovarik** [expo/expo#27602] opened 2024-03-12 19:45 UTC
### Minimal reproducible example

https://github.com/MikeKovarik/expo50-icon-font-issue-repro

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

No (web-only issue)

### Summary

After upgrading to expo 50 (from 49) icon font was no longer loading, resulting in squares instead of icons.

This happens only on the web. Running the same code in ios simulator works well.

The same issue is discussed in [26668](https://github.com/expo/expo/issues/) but the people there somehow resolve it by modifying metro config and/or they use `expo-font`. I use neither in my app as I use `react-native-paper` which then uses `react-native-vector-icons/MaterialCommunityIcons` but how it handles the icon font is out of my hand. Neither do i have `metro.config.js`.

I managed to distill it down to a simple [repro](https://github.com/MikeKovarik/expo50-icon-font-issue-repro) which only uses `react-native-vector-icons` directly.

#### example - expo 50

web is broken; ios works
Notice how the font `MaterialCommunityIcons...` is missing in the requests when compared to the next screenshot.

<img width="1509" alt="Screenshot 2024-03-12 at 20 17 23" src="https://github.com/expo/expo/assets/3995401/556828cf-5232-4645-b152-5abaa6671c5e">

#### example - expo 49

web is works; ios works

<img width="1507" alt="Screenshot 2024-03-12 at 20 20 48" src="https://github.com/expo/expo/assets/3995401/c54b519f-6b43-468d-bb0f-c2ec2c975c75">

Sidenote: Upgrading to expo 50 also brought new error. But that's not my concern here.

```
ERROR in ./node_modules/expo-modules-core/build/uuid/uuid.web.js:9:8
Module not found: Can't resolve 'crypto'
   7 |   const cryptoObject =
   8 |     typeof crypto === 'undefined' || typeof crypto.randomUUID === 'undefined'
>  9 |       ? require('crypto')
     |        ^
  10 |       : crypto;
  11 |
  12 |   if (!cryptoObject?.randomUUID) {
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~19.0.1 => 19.0.1 
      expo: ^50.0.11 => 50.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 5.9.3
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by MikeKovarik** [comment] 2024-03-12 20:00
One workaround I just found is to explicitly list the font inside `useFont`. But for this i had to:

1) import `expo-font` which i did not use in my app previously
2) in my prod app, I'm not directly using `react-native-vector-icons`, I should not have to keep track of dependencies of my dependencies. Also this could break if the lib changes their folder structure.

```js
import { useFonts } from 'expo-font';

export default function App() {
  const [fontsLoaded, fontError] = useFonts({
    'MaterialCommunityIcons': require('./node_modules/react-native-vector-icons/Fonts/MaterialCommunityIcons.ttf'),
  });
...
}
```

**Comment by brentvatne** [comment] 2024-03-12 21:25
hi @MikeKovarik! i'd suggest switching to using metro for web instead of webpack. we deprecated support for webpack in sdk 50 (https://expo.dev/changelog/2024/01-18-sdk-50) and, although we intend to keep it working for this sdk 50, it's not a high priority for us. i tried switching the example project to metro and it worked as expected

**Comment by EvanBacon** [comment] 2024-03-12 21:25
The issue is that we need to add a webpack alias for `react-native-vector-icons` to `@expo/vector-icons` since we no longer do this in babel.

**Comment by yuheil** [comment] 2024-04-08 08:16
@MikeKovarik I get the same `Can't resolve 'crypto'` after updated to expo 50 on web platform, how do you deal with it?

**Comment by Victor-Varghese** [comment] 2024-04-16 06:47
Any updates/ workarounds ?

Facing similar issues in iOS. After upgrading to expo 50 fonts and icons weer not loading.

Able to fix the fonts issue by loading them on build time. But icons are still not loading on iOS. Tried using babel-plugin-module-resolver, but icons are still not loading

```
 [
        'babel-plugin-module-resolver',
        {
          alias: {
            'react-native-vector-icons': '@expo/vector-icons',
          },
        },
      ],
```

Android works fine. iOS fails.

I tried using icons on a new expo 50 project and it works fine

**Comment by lc3t35** [comment] 2024-04-28 18:45
I have the same issue with ios build 

ReferenceError: Property 'Icon' doesn't exist, js engine: hermes

![image](https://github.com/expo/expo/assets/921372/572569b1-2b40-4f83-bc7d-20b89cc2ec5c)

I tried useFont method suggested by @MikeKovarik without success

**Comment by raci-aivy** [comment] 2024-04-29 08:39
After upgrading to SDK 50, I also have the following warning in web:

```
WARNING in ./node_modules/react-native-paper/lib/module/components/MaterialCommunityIcon.js:24:4
Module not found: Can't resolve 'react-native-vector-icons/MaterialCommunityIcons'
22 |   // Optionally require vector-icons
23 |   MaterialCommunityIcons =
> 24 |     require('react-native-vector-icons/MaterialCommunityIcons').default;
25 | } catch (e) {
26 |   let isErrorLogged = false;
27 | 
```

I've tried it with the alias but it didn't help
`config.resolve.alias['^react-native-vector-icons(/.*)?$'] = '@expo/vector-icons$1'`

Any suggestions here?!

**Comment by butri71** [comment] 2024-04-29 14:54
For me icons are no longer rendered since upgrading to SDK 50 for Android, fine on iOs.

Tried using babel-plugin-module-resolver, but icons are still not loading on Android but all normal on iOs.

Has anyone solved the issue on Android since Expo 50?
I wonder if this has anything to do with the breaking changes mentioned in the documentation "_...@expo/vector-icons has been updated to use react-native-vector-icons@10.0.0: ..._"

**Comment by Victor-Varghese** [comment] 2024-04-30 05:19
> Any updates/ workarounds ?
> 
> Facing similar issues in iOS. After upgrading to expo 50 fonts and icons weer not loading.
> 
> Able to fix the fonts issue by loading them on build time. But icons are still not loading on iOS. Tried using babel-plugin-module-resolver, but icons are still not loading
> 
> ```
>  [
>         'babel-plugin-module-resolver',
>         {
>           alias: {
>             'react-native-vector-icons': '@expo/vector-icons',
>           },
>         },
>       ],
> ```
> 
> Android works fine. iOS fails.
> 
> I tried using icons on a new expo 50 project and it works fine


I started upgrading from scratch and it worked this time without any workarounds.

**Comment by butri71** [comment] 2024-04-30 11:29
> > Any updates/ workarounds ?
> > Facing similar issues in iOS. After upgrading to expo 50 fonts and icons weer not loading.
> > Able to fix the fonts issue by loading them on build time. But icons are still not loading on iOS. Tried using babel-plugin-module-resolver, but icons are still not loading
> > ```
> >  [
> >         'babel-plugin-module-resolver',
> >         {
> >           alias: {
> >             'react-native-vector-icons': '@expo/vector-icons',
> >           },
> >         },
> >       ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Android works fine. iOS fails.
> > I tried using icons on a new expo 50 project and it works fine
> 
> I started upgrading from scratch and it worked this time without any workarounds.

@Victor-Varghese what do you mean "._..upgrading from scratch_" - can you please share the steps you followed? In my case I had to install expo 50.0.17 which contains the patch to bypass Apple warning on Manifest

**Comment by Victor-Varghese** [comment] 2024-04-30 11:36
followed steps here: https://docs.expo.dev/workflow/upgrading-expo-sdk-walkthrough/

```
npm install expo@latest
npx expo install --fix
```

**Comment by GWesley** [comment] 2024-05-10 21:43
> followed steps here: https://docs.expo.dev/workflow/upgrading-expo-sdk-walkthrough/
> 
> ```
> npm install expo@latest
> npx expo install --fix
> ```

thanks

**Comment by EmePin** [comment] 2024-05-12 01:20
> webpack.config.js

How I change to metro?

**Comment by lc3t35** [comment] 2024-06-03 17:31
FYI Follow up here for sdk51 : https://github.com/expo/vector-icons/issues/303 
Downgrading to "@expo/vector-icons": "^13.0.0" is the current workaround.

**Comment by brentvatne** [comment] 2024-06-03 22:03
i'm going to close this issue because it has veered quite off the original topic - which is icons on web when using webpack. if you are using webpack, see https://github.com/expo/expo/issues/27602#issuecomment-1992614729

if you are experiencing another issue with icons, please create a new issue and include a minimal reproducible example.

**Closed by brentvatne** 2024-06-03 22:03 UTC
Labels: Platform: web, needs review
