### ISSUE TITLE
Urgent! Ask PHONE_CALL Permission with expo!

### ISSUE THREAD

**Issue by alfredorods** [expo/expo#7149] opened 2020-02-21 23:03 UTC
Hi i am trying to create a react native with expo app the main app's function is call users in an automatic way but we are not able to request PHONE_CALL permission using expo! what is the best way to call any Android permission?

The app is only Android but we don´t know   how to request this permission!

Thanks for your help!

**Comment by cruzach** [comment] 2020-02-21 23:12
Since this isn't part of the [permissions requested in the managed workflow](https://docs.expo.io/versions/latest/workflow/configuration/#android), you'll need to eject to the [bare workflow](https://docs.expo.io/versions/v36.0.0/introduction/managed-vs-bare/#bare-workflow) and request this in the Android manifest file 

(duplicate of https://github.com/expo/expo/issues/1729)

**Closed by cruzach** 2020-02-21 23:12 UTC
