### ISSUE TITLE
Camera stopped

### ISSUE THREAD

**Issue by DenisDov** [expo/expo#501] opened 2017-08-15 10:00 UTC
My image picker camera crashed on android 4.4.2, when i click save photo. On android 5+ and IOS 9+ camera working fine.
![download](https://user-images.githubusercontent.com/13405393/29311172-6fe905f0-81b9-11e7-906e-1443bfb0106e.jpeg)

**Comment by sebid** [comment] 2017-08-15 11:57
https://github.com/expo/expo/issues/429
Duplicate of one of the issues we're facing, we haven't found a workaround for it yet, considering it a limitation at this point.

**Comment by jesseruder** [comment] 2017-08-21 22:19
We have someone looking into this, going to close since it's a duplicate of #429.

**Closed by jesseruder** 2017-08-21 22:19 UTC
