### ISSUE TITLE
Expo 51: expo-sensors: DeviceMotion.addListener crashes on Android with Java Context error

### ISSUE THREAD

**Issue by paulschreiber** [expo/expo#28879] opened 2024-05-14 19:43 UTC
### Minimal reproducible example

https://github.com/paulschreiber/expo-51-sensors-crash/tree/main

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

After upgrading from Expo 50 to Expo 51, calling `DeviceMotion.addListener` crashes on Android.
- crash occurs on Pixel 7a
- crash occurs on emulator of Pixel 3a
- crash does not occur on iOS

I have created an example with two branches:
`main`: expo 51, crashes
`fix/expo50`: expo 50, no crash

Here's the crash:
<img width="421" alt="image" src="https://github.com/expo/expo/assets/86784/5ef23a11-97ba-4963-866a-71bd0bfd449a">

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.13.1/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.13.1/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/paul/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 27, 29, 30, 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.6 => 51.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: ^0.74.1 => 0.74.1 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by behenate** [comment] 2024-05-15 08:21
You are right, duplicate of https://github.com/expo/expo/issues/28820, fixed in https://github.com/expo/expo/pull/28839

**Closed by behenate** 2024-05-15 08:21 UTC
Labels: needs review

**Comment by gani2009** [comment] 2024-08-05 17:44
> You are right, duplicate of #28820, fixed in #28839

its not infact fixed

**Comment by paulschreiber** [comment] 2024-08-05 17:47
It was fixed for us. Please file a new bug with a reproducible example.
