### ISSUE TITLE
Custom fonts not loading on upgrade from SDK 47->48

### ISSUE THREAD

**Issue by jaimemarijke** [expo/expo#21928] opened 2023-03-31 18:00 UTC
### Minimal reproducible example

https://snack.expo.dev/@jaimemarijke/custom-fonts-not-loading-with-sdk-48

### Summary

On upgrading from Expo SDK 47 -> 48, my custom fonts no longer load.

Stack trace:
```
 LOG  fontsLoaded: false
 LOG  fontLoadingError: null
 LOG  fontsLoaded: true
 LOG  fontLoadingError: null
 ERROR  fontFamily "IBM Plex Sans" is not a system font and has not been loaded through Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Font.loadAsync.
RCTText
Text@http://192.168.1.158:19000/index.bundle?platform=ios&dev=true&hot=false:74517:27
RCTView
View
App@http://192.168.1.158:19000/index.bundle?platform=ios&dev=true&hot=false:103313:44
withDevTools(App)@http://192.168.1.158:19000/index.bundle?platform=ios&dev=true&hot=false:102997:27
RCTView
View
RCTView
View
AppContainer@http://192.168.1.158:19000/index.bundle?platform=ios&dev=true&hot=false:85872:36
main(RootComponent)@http://192.168.1.158:19000/index.bundle?platform=ios&dev=true&hot=false:91072:28
```

Notably, when I log the `fontsLoaded` boolean, I can see that it becomes `true`, but I still get an error about custom fonts not loading.

Minimal code example (copied from https://docs.expo.dev/versions/latest/sdk/font/#usage with very minimal edits)
```
import React, { useCallback } from 'react';

import { useFonts } from 'expo-font';
import * as SplashScreen from 'expo-splash-screen';
import { StyleSheet, Text, View } from 'react-native';

SplashScreen.preventAutoHideAsync();

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
});

const App = () => {
  const [fontsLoaded, fontLoadingError] = useFonts({
    'IBM Plex Sans': require('./assets/fonts/IBMPlexSans.ttf'),
  });

  console.log('fontsLoaded:', fontsLoaded);
  console.log('fontLoadingError:', fontLoadingError);

  const onLayoutRootView = useCallback(async () => {
    if (fontsLoaded) {
      await SplashScreen.hideAsync();
    }
  }, [fontsLoaded]);

  if (!fontsLoaded) {
    return null;
  }

  return (
    <View style={styles.container} onLayout={onLayoutRootView}>
      <Text style={{ fontFamily: 'IBM Plex Sans', fontSize: 30 }}>IBMPlexSans</Text>
      <Text style={{ fontSize: 30 }}>Platform Default</Text>
    </View>
  );
};

export default App;
```

I included a minimal code sample as a snack, but it doesn't reproduce the error, possibly because the Snack UI doesn't have the option to use SDK 48 yet.

I noticed that there are many other historical variations on this issue, often when upgrading between older versions of the SDK. The most common fixes seemed to involve 

1. nuking installed packages (`rm -rf node_modules && npm cache clean --force && rm -rf .expo && rm package-lock.json`)
2. Making sure to expo install expo-managed modules 

None of these fixes have worked for me

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.8.0/bin/yarn
      npm: 8.19.1 - ~/.nvm/versions/node/v18.8.0/bin/npm
      Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.9 => 48.0.9
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    npmGlobalPackages:
      eas-cli: 3.8.1
    Expo Workflow: bare

**Comment by jaimemarijke** [comment] 2023-03-31 18:16
Hmm, a possible clue. I just noticed that when I run `expo install`, it still says its using SDK 47:

```
npx expo install @react-native-async-storage/async-storage@~1.17.3 -- --legacy-peer-deps                                                                                   1 ↵
› Installing 1 SDK 47.0.0 compatible native module using npm
> npm install --legacy-peer-deps
```

This is despite following the [upgrade instructions](https://blog.expo.dev/expo-sdk-48-ccb8302e231) to upgrade to SDK 48 (`npm install expo@^48.0.0`)

**Comment by amandeepmittal** [comment] 2023-04-01 17:25
Hey @jaimemarijke, did you try removing  `sdkVersion": "47.0.0"` from your project's `app.json` and trying running it again? I tried running your example without the `sdkVersion": "47.0.0"` (the one you shared on Snack), locally with SDK 48 and it is working for me.

<img width="1494" alt="CleanShot 2023-04-01 at 22 53 12@2x" src="https://user-images.githubusercontent.com/10234615/229305580-fb3a0e35-84a4-4d0e-999c-3ba2649e27e9.png">

> I included a minimal code sample as a snack, but it doesn't reproduce the error, possibly because the Snack UI doesn't have the option to use SDK 48 yet.

Yes, you are right. The SDK 48 isn't released on Snack yet. Sorry for the inconvenience there. Closing this issue for now.

**Closed by amandeepmittal** 2023-04-01 17:25 UTC
Labels: needs review

**Comment by jaimemarijke** [comment] 2023-04-02 20:12
I'm not entirely sure which step fixed it. I did remove `sdkVersion": "47.0.0"`, but IIRC that wasn't enough. In the end, I:

- cleaned out all packages & the npm cache (`rm -rf node_modules && npm cache clean --force && rm -rf .expo && rm package-lock.json`)
- removed every single dependency listed in my `package.json` (saved the list for later)
- `npm install expo@48.0.0`
- `expo install <all dependencies I just deleted from package.json>`

And that seemed to be enough to fix it

**Comment by amandeepmittal** [comment] 2023-04-03 06:57
I think the another reason it got resolved on your end was deleting `node_modules`. Because, earlier, when you had `sdkVersion` property, the modules might not have got updated.

I'd also suggest using `npx expo [command]` in future so that it uses the latest version of Expo CLI.

**Comment by jaimemarijke** [comment] 2023-04-03 19:17
I had deleted `node_modules` a number of times and that didn't fix it (`rm -rf node_modules && npm cache clean --force && rm -rf .expo && rm package-lock.json`)

Oh, yes, I was actually using `npx expo [command]` just forgot to write it that way in my comment.

**Comment by amandeepmittal** [comment] 2023-04-04 20:24
Interesting. I couldn't repro the why removing `node_modules` didn't fix in this case after creating a new project with SDK 47 and then migrating to SDK 48. Feel free to open a new issue if you face something similar or any other issues.

**Comment by kouamegerard** [comment] 2023-07-09 13:03
Hi,
if you still have this error try to go back to the previous version, this works with my version SDK 48 of expo

**Comment by hieucd04** [comment] 2023-09-16 02:06
I was using `expo@49.0.11` and the only `expo-font` version that worked for me was `11.4.0`

**Comment by adeelibr** [comment] 2023-09-23 21:44
> const onLayoutRootView = useCallback(async () => {
>     if (fontsLoaded) {
>       await SplashScreen.hideAsync();
>     }
>   }, [fontsLoaded]);

@hieucd04 Thank you, 3 hours of struggle and your comment was the only thing that helped! Cheers

**Comment by mryechkin** [comment] 2023-10-01 19:03
> I was using `expo@49.0.11` and the only `expo-font` version that worked for me was `11.4.0`

I, too, wasted several hours before finding that this was the cause. Thank you!

**Comment by ericktanida-dev** [comment] 2023-10-24 23:31
> I was using `expo@49.0.11` and the only `expo-font` version that worked for me was `11.4.0`

Thank you, I spent 2 hours trying to solve it... ty <3
