### ISSUE TITLE
On Android 6 (maybe 7) push notifications do not pop up

### ISSUE THREAD

**Issue by Noitidart** [expo/expo#7056] opened 2020-02-15 14:30 UTC
## 🐛 Bug Report
This is from here - this discussion here - https://www.reddit.com/r/reactnative/comments/f269bx/your_opinion_on_expo_push_notifications/fhf8bpi/

> Oops I meant on Andriod. On ios things work fine in foreground. I didnt know the foreground thing was 10+ only though. Please advise if you know solution for the no heads up display on android, topics:
> 
> 
> https://forums.expo.io/t/android-7-does-not-show-push-notification-android-8-and-ios-works-well/19292
> 
> 
> https://forums.expo.io/t/android-notification-not-popping-up/28678

And reply with test case:

> perhaps this is an issue on android 7 and lower, i don't have a device handy to try it. on android 8 i ran the code in this snack: https://snack.expo.io/@notbrent/snack-push-example - then copied and pasted the expo push token to https://expo.io/notifications and added a title and body and specified the notification channel 'blah' and it showed the notification while the app was foregrounded. if this doesn't work for you on android 7 please create an issue on expo/expo repo on github
### Environment

App target: Android 6 and 7

  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.5 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.7

### Steps to Reproduce

https://www.reddit.com/r/reactnative/comments/f269bx/your_opinion_on_expo_push_notifications/fhf8bpi/

### Expected Behavior

The notification should popup. 

### Actual Behavior
The notification comes but it doesnt popup. It is sitting silently in the tray.

**Comment by brentvatne** [comment] 2020-02-18 20:02
thanks for the report @Noitidart! cc @sjchmiela since you're working on notifications at the moment

**Comment by sjchmiela** [comment] 2020-06-15 07:22
I have just confirmed that this issue does not appear when using `expo-notifications`. I'll let myself close this issue tentatively as the package will be available to use in SDK38 soon and is available for bare workflow already. 🙂

**Closed by sjchmiela** 2020-06-15 07:22 UTC
Labels: Notifications, bug, project: android-runtime
