### ISSUE TITLE
Uncaught Error: 29.0.0 is not a valid SDK version

### ISSUE THREAD

**Issue by saundefined** [expo/expo#3504] opened 2019-02-13 12:36 UTC
### Environment

```
Expo CLI 2.10.1 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.5.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.5 => 32.0.5 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.0.9 
    npmGlobalPackages:
      expo-cli: 2.10.1
```

app.json
```
{
  "expo": {
    "name": "app",
    "description": "app",
    "slug": "app",
    "privacy": "unlisted",
    "sdkVersion": "32.0.0",
    "version": "1.0.0",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app1024.png",
    "splash": {
      "image": "./assets/icons/splash.png",
      "backgroundColor": "#F8F8F8",
      "resizeMode": "cover"
    },
    "packagerOpts": {
      "assetExts": [
        "ttf",
        "mp4"
      ]
    },
    "notification": {
      "icon": "./assets/icons/app48.png",
      "color": "#000000",
      "androidMode": "default"
    },
    "ios": {
      "buildNumber": "1",
      "supportsTablet": true,
      "bundleIdentifier": "com.company.bundle",
      "usesIcloudStorage": true,
    },
    "android": {
      "package": "com.company.bundle",
      "versionCode": 1,
      "permissions": []
    },
    ...
  }
}
```

package.json
```
{
  "name": "app",
  "version": "1.0.0",
  "description": "app",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "test": "node_modules/.bin/jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/react-native-action-sheet": "2.1.0",
    "expo": "^32.0.5",
    "expo-analytics": "^1.0.7",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-barcode-builder": "1.0.5",
    "react-native-datepicker": "1.7.2",
    "react-native-dropdownalert": "3.9.2",
    "react-native-elements": "1.0.0",
    "react-native-keyboard-aware-scroll-view": "0.8.0",
    "react-native-masked-text": "1.10.1",
    "react-native-segmented-control-tab": "3.4.0",
    "react-native-side-menu": "1.1.3",
    "react-native-swipe-list-view": "^1.5.1",
    "react-native-swiper": "1.5.14",
    "react-native-text-input-mask": "0.8.0",
    "react-navigation": "^3.0.9",
    "sentry-expo": "~1.9.0"
  },
  "devDependencies": {
    "jest-expo": "^32.0.0"
  }
}
```
I tried use `expo: 32.0.0`, and `expo: 32.0.5` - the result is the same

### Steps to Reproduce
1. Run expo build:android
2. Upload .apk to Google.Play

### Expected Behavior
Some users have an error on launch: Uncaught error: 29.0.0 is not a valid SDK version. Options are 32.0.0, UNVERSIONED

And others – have a correct app.

### Reproducible Demo

![screenshot_20190209-094628](https://user-images.githubusercontent.com/4685504/52712033-76748300-2fa4-11e9-8c22-a8f43687359c.png)

**Comment by AdamJNavarro** [comment] 2019-02-13 21:16
Hey @saundefined,

Based on your `app.json`, it looks like you only have ever built with SDK32 but just for clarity's sake, have you ever built and distributed a binary running SDK29?

Cheers,
Adam

**Comment by saundefined** [comment] 2019-02-14 05:09
@AdamJNavarro Thanks, I sent additional info on email.

**Comment by AdamJNavarro** [comment] 2019-02-14 18:44
Just confirmed that we received the e-mail. Thank you!

**Comment by esamelson** [comment] 2019-02-20 00:40
We've deployed a fix for this to our SDK 32 standalone app builders for Android. If users continually experience this error even when connected to the internet, publishing an updated bundle should work as an quick fix/workaround, but to get the error to go away completely you'll need to make a new build of your app on SDK 32 and release the updated binary in the Play Store.

I'm going to go ahead and close this ticket as the issue has been fixed, but let us know if you continue to experience this problem.

**Comment by saundefined** [comment] 2019-02-20 12:22
@esamelson 

Hi, I tried with build 83055389-8f27-4b73-8dc0-dbc6d1784cd5, some people haven't solved the problem.

Device and app info:

![img_3114](https://user-images.githubusercontent.com/4685504/53091432-fd84a680-3522-11e9-92b5-d00fa9be4a32.jpeg)
![img_3116](https://user-images.githubusercontent.com/4685504/53091433-fe1d3d00-3522-11e9-9c34-6f655bf2493a.jpeg)
![img_3117](https://user-images.githubusercontent.com/4685504/53091434-fe1d3d00-3522-11e9-856e-e3a858a890a4.jpeg)

What additional info can I ask to help resolve it?

**Comment by esamelson** [comment] 2019-02-20 20:10
@saundefined - could you confirm that you released this new binary? (83055389-8f27-4b73-8dc0-dbc6d1784cd5) on Google Play and all your users who are still experiencing the issue have updated to this latest release?

**Comment by saundefined** [comment] 2019-02-22 06:14
@esamelson Yes, some users have a problem solved and some – not.
Now, 2 users have been updated the app to the last build and have said that they have the same error.

**Comment by esamelson** [comment] 2019-02-26 01:15
@saundefined - I suspect that those users have not actually updated to the latest version; sometimes it takes a while for new versions to propagate out everywhere through Google Play. Could you double check that the have the correct latest version number?

**Comment by saundefined** [comment] 2019-02-26 07:19
@esamelson Yes, I ask about it at once

Build 83055389-8f27-4b73-8dc0-dbc6d1784cd5 was upload to Google.Play with 1.7.6 number – on last screenshots, there was displayed an actual version.

**Comment by esamelson** [comment] 2019-03-01 01:42
@saundefined - hmmm ok. I have not been able to reproduce this in any cases other than the one I already fixed. For the users who are still affected, does this happen always, or does it correlate with lack of network availability? And did they have many previous versions of the app installed?

If you can help test and provide a scenario to reliably reproduce this, it would go a really long way in getting this fixed sooner! 🙂

**Comment by saundefined** [comment] 2019-03-01 06:10
@esamelson, I also can not reproduce this error on any device - neither physical nor cloud.
But users still send an error message to the mail.
I'll check the application code again, maybe something is wrong inside it.
Regarding the error, I can clarify additional information from users - what information would be useful for you to diagnose?

**Comment by saundefined** [comment] 2019-03-01 06:12
For double-checking I sent to Google.Play new build – 9ba10b4d-cbbb-45b2-a490-a7412ca43acd.

**Comment by esamelson** [comment] 2019-03-02 01:00
Hey @saundefined - any of this information from my post above could be helpful:
> For the users who are still affected, does this happen always, or does it correlate with lack of network availability? And did they have many previous versions of the app installed?

**Comment by saundefined** [comment] 2019-03-04 06:26
@esamelson Hmm... I asked one of the users about the app:
He tried to launch it with mobile and wifi network – there is the same a result.
I sent him 9ba10b4d-cbbb-45b2-a490-a7412ca43acd .apk build, he removed Google.Play version, replace it with .apk directly – the app launched without errors.

What can Google.Play do with the app? 🤷‍♂️

**Comment by esamelson** [comment] 2019-10-09 19:47
Hi, we're closing inactive issues that apply to SDK versions we no longer support. We've made a number of fixes and improvements to the OTA update storage logic since this issue was opened. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.

**Closed by esamelson** 2019-10-09 19:47 UTC
