### ISSUE TITLE
[Video][iOS] Video component crashing on multiple video load when not using useNativeControls

### ISSUE THREAD

**Issue by cropd** [expo/expo#3912] opened 2019-04-02 15:10 UTC
### Environment

Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.1.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.14.0

App target is iOS (iPad).

### Steps to Reproduce

When loading video files multiple times in a short period of time the app crashes.
It might look like an uncommon use case, but my app is basically loading video files on touch events and it crashes after 10-30 touches depending on the device.

I've made a simplified snack:
https://snack.expo.io/@mrbananas/dGVzdC

Click multiple times on "Load Video" and it will crash. 
Click on "Toggle Controls" first and it won't crash if you hit "Load Video" multiple times.

It's hard to crash it in the simulator, but on an iPhone or iPad it's easy to reproduce. My older iPad crashes much faster than my new iPhone.

### Expected Behavior

Not crashing with `useNativeControls` set to false or omitted.

### Actual Behavior

The app is crashing when loading video files in a short period of time not using `useNativeControls`.

### Reproducible Demo

https://snack.expo.io/@mrbananas/dGVzdC

**Comment by cropd** [comment] 2019-04-25 01:46
Maybe it's somehow related to #577? Only this problem is the other way around..

**Comment by sjchmiela** [comment] 2019-05-10 13:09
I wasn't able to reproduce this problem on `master`. Since SDK32 release some changes were applied to the AV module, so my guess/wish is that the problem has been fixed. Let's wait to the SDK33 release and test then! 🙂

**Comment by IjzerenHein** [comment] 2020-07-24 15:59
Hi! We've fixed various stability issues with expo-av and we think we fixed this issue as well. I've released a test-version for you to try out and I'd love to hear whether this solves the problem for you.

You can test it in a bare project using `yarn install expo-av@8.4.0`.
And you can find the changelog here: https://github.com/expo/expo/blob/master/packages/expo-av/CHANGELOG.md

Let us know whether this fixes the problem for you!

**Comment by IjzerenHein** [comment] 2020-07-30 09:57
Closing this as `expo-av@8.4.0` contains stability fixes that should fix these crashes. Feel free to reopen with additional reproduction info if the problem still exists.

**Closed by IjzerenHein** 2020-07-30 09:57 UTC
Labels: AV, Video, iOS

**Comment by krisbaum74** [comment] 2020-12-21 05:10
i have a timer set to change video source every 5 seconds, this crashes after around 10-20 plays on iOS. It does not crash on Android. I believe this is still a bug.
