### ISSUE TITLE
Push notifications not working after restoring backup on iOS

### ISSUE THREAD

**Issue by sweebee** [expo/expo#10924] opened 2020-11-04 17:20 UTC
### Summary of Issue 

Sending a push notification to an iPhone which has been restored from a backup doesn't work. The push tool just returns 'ok' in the response.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.28.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.21.0 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.7.5 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-navigation: ^4.0.10 => 4.3.7 
    npmGlobalPackages:
      expo-cli: 3.28.2
    Expo Workflow: managed
```

### Reproducible Demo

-
 
### Steps to Reproduce

Restore a iPhone with a backup (the app was installed on the old iphone) and send a push notification to it. The device wont receive it but expo tells everything went fine. The only solution is removing the app ant install it again.

### Expected Behavior vs Actual Behavior

The pushtoken retrieved with the ```getExpoPushTokenAsync``` should work.

**Comment by cruzach** [comment] 2020-11-04 19:32
as we state in the docs:
> Note: a status of `ok` along with a receipt ID means that the message was received by Expo's servers, not that it was received by the user (for that you will need to check the [push receipt](https://docs.expo.io/push-notifications/sending-notifications/#push-receipts)).

the push receipt will probably contain information you need to debug further.

Anyways, this looks like a duplicate of https://github.com/expo/expo/issues/2824 (which there's already a draft PR open to fix- https://github.com/expo/expo/pull/10908/files) so I'm going to close this and you can follow along there 👍

**Closed by cruzach** 2020-11-04 19:32 UTC
Labels: Issue needs review
