### ISSUE TITLE
SDK21: Android: Standalone cannot launchCamera/ImageLibraryAsync

### ISSUE THREAD

**Issue by Palisand** [expo/expo#700] opened 2017-09-29 00:54 UTC
```
const result = await ImagePicker.launchCameraAsync();
```
User is prompted to allow for the app to access the camera and after doing so, nothing happens. Subsequent attempts do not result in a prompt.

```
const result = await ImagePicker.launchImageLibraryAsync();
```
Nothing happens.

I have included the `CAMERA` permission in _`package.json`_.

**Comment by quinlanj** [comment] 2017-09-29 01:20
hey @Palisand , could you give us a reproduction of the bug or give us more info on this problem? It will go a long ways when we try to root cause and fix the issue.

**Comment by aalices** [comment] 2017-09-29 07:57
I think this is a duplicate of #627

**Comment by terribleben** [comment] 2017-10-02 16:45
Closing as a duplicate of #627

**Closed by terribleben** 2017-10-02 16:45 UTC
Labels: status: needs more info
