### ISSUE TITLE
[expo-updates] TypeError: Invalid URL:    /data/user/0/com.package.name/files/.expo-internal/a0a6ad452b623fde757f922ab79192ea

### ISSUE THREAD

**Issue by terrysahaidak** [expo/expo#32527] opened 2024-11-01 12:23 UTC
### Minimal reproducible example

I have no idea how to reproduce it and why would it happen

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Summary

After integrating the expo-updates in my app after fetching manually a new update, on the next reload it will crash with this stack, any hints to to even debug this would be appreciated.

Manual reload throws this error `Cannot relaunch without a launched update.`

```
TypeError: Invalid URL:    /data/user/0/com.package.name/files/.expo-internal/a0a6ad452b623fde757f922ab79192ea
Stack trace:
  - URLImpl@1:1796819
  - setup@1:1788264
  - URL@1:1789298
  - anonymous@1:2718581
  - loadModuleImplementation@1:154252
  - guardedLoadModule@1:153486
  - metroRequire@1:152769
  - anonymous@1:2614890
  - loadModuleImplementation@1:154252
  - guardedLoadModule@1:153486
  - metroRequire@1:152769
  - anonymous@1:2604043
  - loadModuleImplementation@1:154252
  - guardedLoadModule@1:153486
  - metroRequire@1:152769
  - anonymous@1:2563336
  - loadModuleImplementation@1:154252
  - guardedLoadModule@1:153486
  - metroRequire@1:152769
  - anonymous@1:2559532
  - loadModuleImplementation@1:154252
  - guardedLoadModule@1:153486
  - metroRequire@1:152769
  - anonymous@1:1840295
  - loadModuleImplementation@1:154252
  - guardedLoadModule@1:153486
  - metroRequire@1:152769
  - anonymous@1:1840107
  - loadModuleImplementation@1:154252
  - guardedLoadModule@1:153486
  - metroRequire@1:152769
  - anonymous@1:164000
  - loadModuleImplementation@1:154252
  - guardedLoadModule@1:153443
  - metroRequire@1:152769
  - global@1:151704

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.3 - ~/.nvm/versions/node/v18.20.3/bin/node
      Yarn: 4.0.0 - ~/.yarn/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v18.20.3/bin/npm
      Watchman: 2024.06.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /Users/terrysahaidak/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 34
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-32 | Google Play ARM 64 v8a, android-35 | Google Play Experimental 16k Page Size ARM 64 v8a
        Android NDK: 21.3.6528147
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.38 => 51.0.38 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.6 => 0.74.6 
    npmGlobalPackages:
      eas-cli: 12.6.2
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check for common project setup issues
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: updates, android, ios. 


The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/datetimepicker@8.2.0 - expected version: 8.0.1
  @react-native-community/netinfo@11.3.2 - expected version: 11.3.1
  @sentry/react-native@5.31.0 - expected version: ~5.24.3
  @shopify/flash-list@1.7.1 - expected version: 1.6.4
  @shopify/react-native-skia@1.5.0 - expected version: 1.2.3
  react-native-gesture-handler@2.20.0 - expected version: ~2.16.1
  react-native-pager-view@6.4.1 - expected version: 6.3.0
  react-native-reanimated@3.12.0 - expected version: ~3.10.1
  react-native-safe-area-context@4.11.0 - expected version: 4.10.5
  react-native-screens@3.34.0 - expected version: 3.31.1
  react-native-webview@13.10.3 - expected version: 13.8.6
  @babel/core@7.23.5 - expected version: ^7.24.0
  typescript@5.5.4 - expected version: ~5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.
```

**Comment by terrysahaidak** [comment] 2024-11-01 12:27
thanks expo bot very cool of you, but would be cool if someone could actually suggest me how to debug this since anything from the suggested steps is no helpful at all

**Comment by terrysahaidak** [comment] 2024-11-02 10:21
let me know how can I help to debug this, there is a possibility something is wrong with my bare workflow setup, but i'm not sure what exactly. iOS works just fine.

**Comment by douglowder** [comment] 2024-11-02 10:44
> After integrating the expo-updates in my app after fetching manually a new update, on the next reload it will crash with this stack

We need to understand exactly what you meant by this statement. We are happy to help, but we need the detailed steps that you took to hit this error. Normally you would have to integrate expo-updates into the app first, or you would not be able to fetch an update at all.

**Comment by terrysahaidak** [comment] 2024-11-02 10:49
I integrated expo-updates on both iOS and Android.
Here is the code i use to fetch the update:

```ts
function useExpoUpdates() {
    const {currentlyRunning, isUpdateAvailable} = Updates.useUpdates();

    useEffect(() => {
        Printer.log.debug('Updates: currentlyRunning', currentlyRunning);
        Printer.log.debug('Updates: isUpdateAvailable', isUpdateAvailable);
    }, []);

    React.useEffect(() => {
        async function update() {
            await Updates.fetchUpdateAsync().catch(() => {
                Printer.log.debug('Updates: error fetching update');
            });
        }
        if (isUpdateAvailable) {
            Printer.log.debug('update available');

            update().catch(() => {
                Printer.log.debug('Updates: error fetching update');
            });
        }
    }, [isUpdateAvailable]);
}
```

This code currently works on both iOS and Android. It sees the update, it fetches and then `isPendingUpdate` is true.

After closing the app and opening it again to apply the update the app will crash on Android with that stack trace. The next time I open the app it won't crash, but does not run the update.

**Comment by terrysahaidak** [comment] 2024-11-02 10:51
Again there is high chance i did something wrong somewhere while integrating the library, so I hope my case will also help improve error handling.

**Comment by terrysahaidak** [comment] 2024-11-02 10:55
When I was calling`reloadAsync` (when isUpdatePending is true) after `fetchUpdateAsync`, it would fail with this error. `:

https://github.com/expo/expo/blob/24d5ae5f288013df19ac09a3406c6a507d781ddb/packages/expo-updates/android/src/main/java/expo/modules/updates/EnabledUpdatesController.kt#L190


Here is my AndroidManifest part:
```
    <meta-data android:name="expo.modules.updates.ENABLED" android:value="true"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_CHECK_ON_LAUNCH" android:value="NEVER"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_LAUNCH_WAIT_MS" android:value="0"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://u.expo.dev/__edited__"/>
    <meta-data android:name="expo.modules.updates.EXPO_RUNTIME_VERSION" android:value="@string/expo_runtime_version"/>
    <meta-data android:name="expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY" android:value="{&quot;expo-channel-name&quot;:&quot;production&quot;}"/>
    ```

**Comment by douglowder** [comment] 2024-11-02 12:22
> After closing the app and opening it again to apply the update the app will crash on Android with that stack trace. The next time I open the app it won't crash, but does not run the update.

This suggests that there is a bug in the JS code in the update. If you rebuild the entire Android app with the updated JS code, does it run successfully?

**Comment by terrysahaidak** [comment] 2024-11-02 14:21
Yes, the app works just fine with the same code on Android. I did like 30 tests at least.

One thing it made me curious is the URL is missing `file://` prefix. So this URL metro uses to load the bundle, and usually on Android we have to add `file://`. Since the stack trace coming from JS.

The url: `/data/user/0/com.package.name/files/.expo-internal/a0a6ad452b623fde757f922ab79192ea`

**Comment by brentvatne** [comment] 2024-11-02 18:59
i agree with @douglowder that this looks like it's coming from your app js code. do you have sentry or a similar tool in your app? that might help you get more insight into the precise issue. 

you can also try following the instructions here to run updates in your debug build and add breakpoints: https://docs.expo.dev/eas-update/debug/#runtime-issues

other guidance on that page also applies. if you can share a minimal reproducible example or some information we can use to help further, we can do so! closing until then since it's not actionable for us

**Closed by brentvatne** 2024-11-02 18:59 UTC
Labels: needs review
