### ISSUE TITLE
[SDK 50] expo/config-plugins cutom plugins crashes the build

### ISSUE THREAD

**Issue by medyahyejoud** [expo/expo#26533] opened 2024-01-19 20:11 UTC
### Minimal reproducible example

https://github.com/medyahyejoud/expo-sdk-50-reproduction

### Summary

Hey guys,

After upgrading our app expo SDK 50, we started getting a new error when we try to build the application.
Before upgrading we didn't have any problems, the app builds fine for both iOS and Android, on EAS servers and locally.

I tried to debug myself and narrow down where the issue might be, and I think it is related to `expo/config-plugins`, we have two custom plugins to solve some issues we had:

- One is for react-native-maps on iOS from [this issue](https://github.com/react-native-maps/react-native-maps/issues/4502#issuecomment-1304599405), [here is the file](https://github.com/medyahyejoud/expo-sdk-50-reproduction/blob/f468a799ac3a94c2d0d3d1bfbbda36ae5fc59575/bin/react-native-maps-plugin.js)
- The other one is related to an issue where iOS simulator crashes in M1 Macbook Pro, [here is the file](https://github.com/medyahyejoud/expo-sdk-50-reproduction/blob/f468a799ac3a94c2d0d3d1bfbbda36ae5fc59575/bin/react-apple-ios-simulator-not-found-plugin.js).

The build process crashes during the Prebuild phase with this error:

```bash
✖ Prebuild failed
Error: [ios.dangerous]: withIosDangerousBaseMod: Failed to match "/\s*__apply_Xcode_12_5_M1_post_install_workaround\(installer\)/i" in contents:
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '13.4'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...), which will be excluded. To fix this,
# you can also exclude `react-native-flipper` in `react-native.config.js`
#
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
#   }
# }
# ```
flipper_config = FlipperConfiguration.disabled
if ENV['NO_FLIPPER'] == '1' then
  # Explicitly disabled through environment variables
  flipper_config = FlipperConfiguration.disabled
elsif podfile_properties.key?('ios.flipper') then
  # Configure Flipper in Podfile.properties.json
  if podfile_properties['ios.flipper'] == 'true' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"])
  elsif podfile_properties['ios.flipper'] != 'false' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"], { 'Flipper' => podfile_properties['ios.flipper'] })
  end
end

target 'TestApp' do
  use_expo_modules!
# @generated begin react-native-maps - expo prebuild (DO NOT MODIFY) sync-e9cc66c360abe50bc66d89fffb3c55b034d7d369
  pod 'react-native-google-maps', path: File.dirname(`node --print "require.resolve('react-native-maps/package.json')"`)
# @generated end react-native-maps
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Note that if you have use_frameworks! enabled, Flipper will not work if enabled
    :flipper_configuration => flipper_config
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end

Error: [ios.dangerous]: withIosDangerousBaseMod: Failed to match "/\s*__apply_Xcode_12_5_M1_post_install_workaround\(installer\)/i" in contents:
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '13.4'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...), which will be excluded. To fix this,
# you can also exclude `react-native-flipper` in `react-native.config.js`
#
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
#   }
# }
# ```
flipper_config = FlipperConfiguration.disabled
if ENV['NO_FLIPPER'] == '1' then
  # Explicitly disabled through environment variables
  flipper_config = FlipperConfiguration.disabled
elsif podfile_properties.key?('ios.flipper') then
  # Configure Flipper in Podfile.properties.json
  if podfile_properties['ios.flipper'] == 'true' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"])
  elsif podfile_properties['ios.flipper'] != 'false' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"], { 'Flipper' => podfile_properties['ios.flipper'] })
  end
end

target 'TestApp' do
  use_expo_modules!
# @generated begin react-native-maps - expo prebuild (DO NOT MODIFY) sync-e9cc66c360abe50bc66d89fffb3c55b034d7d369
  pod 'react-native-google-maps', path: File.dirname(`node --print "require.resolve('react-native-maps/package.json')"`)
# @generated end react-native-maps
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Note that if you have use_frameworks! enabled, Flipper will not work if enabled
    :flipper_configuration => flipper_config
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end

    at addLines (/Users/medyahyejoud/Development/sellety/expo-sdk-50-reproduction/node_modules/@expo/config-plugins/build/utils/generateCode.js:85:19)
    at Object.mergeContents (/Users/medyahyejoud/Development/sellety/expo-sdk-50-reproduction/node_modules/@expo/config-plugins/build/utils/generateCode.js:58:17)
    at /Users/medyahyejoud/Development/sellety/expo-sdk-50-reproduction/bin/react-apple-ios-simulator-not-found-plugin.js:25:36
    at action (/Users/medyahyejoud/Development/sellety/expo-sdk-50-reproduction/node_modules/@expo/config-plugins/build/plugins/withMod.js:201:29)
    at interceptingMod (/Users/medyahyejoud/Development/sellety/expo-sdk-50-reproduction/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:27)
    at action (/Users/medyahyejoud/Development/sellety/expo-sdk-50-reproduction/node_modules/@expo/config-plugins/build/plugins/withMod.js:206:14)
    at async interceptingMod (/Users/medyahyejoud/Development/sellety/expo-sdk-50-reproduction/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/medyahyejoud/Development/sellety/expo-sdk-50-reproduction/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/medyahyejoud/Development/sellety/expo-sdk-50-reproduction/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async action (/Users/medyahyejoud/Development/sellety/expo-sdk-50-reproduction/node_modules/@expo/config-plugins/build/plugins/createBaseMod.js:61:21)
```

When I comment `./bin/react-native-maps-plugin` & `./bin/react-apple-ios-simulator-not-found-plugin` entries from the plugins array in `app.config.ts`, I don't see that error, but the build errors out with this error:

```bash
❌  (/Users/expo/workingdir/build/ios/build/Build/Products/Debug-iphonesimulator/Google-Maps-iOS-Utils/GoogleMapsUtils.framework/Headers/GoogleMapsUtils-Swift.h:327:2)

  325 | 
  326 | #else
> 327 | #error unsupported Swift architecture
      |  ^ unsupported Swift architecture
  328 | #endif
  329 |

❌  (node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.h:7:9)

   5 | //
   6 | 
>  7 | #import "GMUHeatmapTileLayer.h"
     |         ^ could not build module 'GoogleMapsUtils'
   8 | 
   9 | @interface AIRGoogleMapHeatmap : UIView
  10 | 

› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapHeatmap.m

› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapCircleManager.m

› Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapCircle.m

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » SelletyDev/SelletyDev » Build Phases » '[CP-User] [RNFB] Core Configuration'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » SelletyDev/SelletyDev » Build Phases » '[CP-User] [RNFB] Crashlytics Configuration'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » Pods/abseil » Build Phases » 'Create Symlinks to Header Folders'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

▸ ** BUILD FAILED **

▸ The following build commands failed:

▸ 	CompileC /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmapManager.o /Users/expo/workingdir/build/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmapManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-google-maps' from project 'Pods')

▸ (1 failure)

** BUILD FAILED **

The following build commands failed:

	CompileC /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/arm64/AIRGoogleMapHeatmapManager.o /Users/expo/workingdir/build/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmapManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-google-maps' from project 'Pods')

(1 failure)

Exit status: 65
```

Which why we had this custom plugins in the first place.

This are the changes made to `app.config.ts` after fully following the instructions to upgrade to SDK 50, I added `expo.ios.config.usesNonExemptEncryption: false`, `expo.ios.usesAppleSignIn: true` and this entries to the plugins array: 
```json
[
  "expo-secure-store",
  "expo-apple-authentication",
  "@react-native-google-signin/google-signin",
  [
    "expo-font",
    {
      "fonts": ["./assets/fonts/Metropolis-Bold.otf"],
    },
  ]
]
```

Its important to note, that previously with SDK 49, we had this resolution to silence expo-doctor:

```json
"resolutions": {
  "@expo/config-plugins": "~7.2.2"
},
```
After upgrading to SDK 50, we removed it because it started to error out in expo-doctor.

Thanks 🙏 

### Environment

```
expo-env-info 1.2.0 environment info:

System:
  OS: macOS 14.2.1
  Shell: 3.5.1 - /opt/homebrew/bin/fish
Binaries:
  Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
  Yarn: 1.22.19 - ~/.yarn/bin/yarn
  npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Watchman: 2023.01.09.00 - /opt/homebrew/bin/watchman
Managers:
  CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode: 15.2/15C500b - /usr/bin/xcodebuild
npmPackages:
  expo: ^50.0.2 => 50.0.2 
  react: 18.2.0 => 18.2.0 
  react-dom: 18.2.0 => 18.2.0 
  react-native: 0.73.2 => 0.73.2 
npmGlobalPackages:
  eas-cli: 6.1.0
  expo-cli: 6.3.10
Expo Workflow: managed
```

**Comment by brentvatne** [comment] 2024-01-19 20:20
hey @medyahyejoud! can you please try to narrow this down further? it looks like you have many packages inside this example you gave. it should include the least amount of packages and code as you can possibly narrow it down to while still reproducing

**Comment by brentvatne** [comment] 2024-01-19 20:41
closing this for now but happy to investigate when there is a more minimal example that narrows it down

**Closed by brentvatne** 2024-01-19 20:41 UTC
Labels: needs review

**Comment by medyahyejoud** [comment] 2024-01-19 21:28
@brentvatne, thanks for the guidance, should I edit this issue or open a new one?
