### ISSUE TITLE
Signing for PlayStore broken

### ISSUE THREAD

**Issue by Hirbod** [expo/expo#6615] opened 2019-12-25 12:26 UTC
Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.13.2 - ~/Gitlab/nightstomp/netstar/nummernschild-app/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 

Hello,

I have successfully published my app as a bundle (aab) on the PlayStore. I wanted to install a small update after a few days, because there are problems with the keyboard. I have executed "expo build:android -t app-bundle" as usual.

Afterwards I tried to upload directly via the cli (after it failed with the message that the fingerprint is invalid) also via the PlayStore. I got the same message that the fingerprint of the upload key does not match.

I have tried to download the upload key, but I get the following message:
> expo fetch:android:upload-cert
There is no valid Keystore defined for this app
Writing upload key to /my/path/to/xxxxx_upload_cert.pem
keytool exited with non-zero code: 1

I had "Google App Signing" enabled in PlayStore from the beginning, even before I knew anything about an "expo opt-in" command. There was already an upload certificate in my PlayStore. I let Expo manage the entire process and never generated anything myself.

Now I'm stuck here and don't know what to do. I can't download any hashes or upload certificates, nor can I update my app. This is absolute horror right now. I had extra Expo manage everything to avoid problems right here.

How can we fix the problem now? It is really urgent.

**Comment by cruzach** [comment] 2019-12-26 15:38
Hi! We're aware of this issue and are looking into it now, but I'm going to close this issue in favor of https://github.com/expo/expo-cli/issues/1394 since it's in the appropriate repo

We'll keep you updated there, very sorry for the inconvenience of this issue! Hopefully we'll resolve it soon

**Closed by cruzach** 2019-12-26 15:38 UTC

**Comment by Hirbod** [comment] 2019-12-26 16:07
But my issue is that a prev. singed App through expo isn’t updatable anymore while I’ve chosen to let expo handle everything. The issue is bigger than just a unfetchable key - it’s like expo does not have a clue which key it used before and ends up generating new ones.

**Comment by cruzach** [comment] 2019-12-26 16:17
Yeah, seems like there's some mismatch with identifying the stored keystore. whether you're grabbing that keystore through `expo fetch` or by trying to upload a new apk, I think it's still the same root cause

**Comment by Hirbod** [comment] 2019-12-26 16:21
Ok. I ended up requesting a upload cert reset at google and providing my own upload key when building an APK
