### ISSUE TITLE
Screen mouting twice when using usePathname, useSegment, etc in a _layout

### ISSUE THREAD

**Issue by oliviercperrier** [expo/expo#25133] opened 2023-10-31 04:24 UTC
### Minimal reproducible example

https://github.com/oliviercperrier/demo-expo-router-screen-mounting-twice

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I have a _layout for a stack of screens and in this layout i need to use the `usePathname` hook to get the current path and show a Step Progress at the top of the screens.

When i use `usePathname` or other hooks that return new values on screen change, the target screen is mounted twice and some time when you push i new screen, the previous screen gets mounted and third time.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 3.16.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by brentvatne** [comment] 2023-10-31 22:57
duplicate of #25120

**Closed by brentvatne** 2023-10-31 22:57 UTC
Labels: needs review, Router
