### ISSUE TITLE
react-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS

### ISSUE THREAD

**Issue by techied** [expo/expo#31023] opened 2024-08-15 22:15 UTC
### Summary

This issue is NOT related to react-native-maps in Expo Go

When creating a development build of an app, using react-native-maps and the `google` map provider, the map does not display and logs an error:

> AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS

This error did not occur as of a couple days ago, and is affecting my builds even when reverting to older versions of `expo` (by checking out older commits in my project, that I know built correctly at the time)

Building with Xcode, on eas, and with `eas build --local` all did not resolve the issue. I suspect this is a problem with `expo prebuild`?

Related discord thread: https://discord.com/channels/695411232856997968/1273616402749849650

### What platform(s) does this occur on?

iOS

### SDK Version

51.0.28

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.28 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.3
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/techied/expo-react-native-maps

**Comment by levymetal** [comment] 2024-08-16 00:00
I've been having the same issue since yesterday. 

After a bit of digging, it looks like the `EXPO_UNSTABLE_CORE_AUTOLINKING` guard conflicts with the way the `react-native-google-maps` pod is inserted into the Podfile. The `react-native-google-maps` pod is anchored to `/use_native_modules/`, and the first occurrence of this is nested within the `EXPO_UNSTABLE_CORE_AUTOLINKING` condition. I feel it might have something to do with https://github.com/expo/expo/pull/30914, although I'm not entirely sure.

https://github.com/expo/expo/blob/e8b507d8f0a30aa9664c5a301f573e2311c78cdd/packages/%40expo/config-plugins/src/ios/Maps.ts#L110

https://github.com/expo/expo/blob/8086be4bb637c7ed236fbad111e04f9222a8208c/apps/bare-expo/ios/Podfile#L47

As a result of this generation, the `react-native-google-maps` pod is skipped unless `EXPO_UNSTABLE_CORE_AUTOLINKING` is set to `1`. I don't believe this is intentional.

I'm a little confused because my packages are locked (expo 51.0.14) and haven't changed, yet the Podfile is using the new generation. Do the build commands execute a command from a remote package? 

Because I can't figure out how to downgrade the Podfile generation, I'm using `patch-package` to change the anchor to from `use_native_modules` to `use_frameworks`, which has got me back up and running again, although I don't know if that's really the best anchor.

**Comment by damaestro** [comment] 2024-08-16 01:48
> After a bit of digging, it looks like the `EXPO_UNSTABLE_CORE_AUTOLINKING` guard conflicts with the way the `react-native-google-maps` pod is inserted into the Podfile. The `react-native-google-maps` pod is anchored to `/use_native_modules/`, and the first occurrence of this is nested within the `EXPO_UNSTABLE_CORE_AUTOLINKING` condition.

This is the issue. If you add the needed code into the `else` branch everything works again:

```
  if ENV['EXPO_UNSTABLE_CORE_AUTOLINKING'] == '1'
    Pod::UI.puts('Using expo-modules-autolinking as core autolinking source'.green)
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
# @generated begin react-native-maps - expo prebuild (DO NOT MODIFY) sync-e9cc66c360abe50bc66d89fffb3c55b034d7d369
  pod 'react-native-google-maps', path: File.dirname(`node --print "require.resolve('react-native-maps/package.json')"`)
# @generated end react-native-maps
    config = use_native_modules!(config_command)
  else
# @generated begin react-native-maps - expo prebuild (DO NOT MODIFY) sync-e9cc66c360abe50bc66d89fffb3c55b034d7d369
  pod 'react-native-google-maps', path: File.dirname(`node --print "require.resolve('react-native-maps/package.json')"`)
# @generated end react-native-maps
    config = use_native_modules!
  end
```

Obviously, this will break any CNG workflow. What @rybaier and I have done for now is run a clean `prebuild`, manually modify the `ios/Podfile`, and then re-install the pod. This at least got our local dev environments back up and our CNG pipeline can wait for a proper fix.

Prebuild:
```
npx expo prebuild --clean
```

Modify the resulting `ios/Podfile` to fix up the inclusion of react-native-google-maps. 

Re-install the pod:
```
pod install --project-directory=ios
```

You will see something like the following indicating the install worked correctly this time:

```
Downloading dependencies
Installing Google-Maps-iOS-Utils (4.2.2)
Installing GoogleMaps (7.4.0)
Installing react-native-google-maps (1.14.0)
```

**Comment by davidtiede** [comment] 2024-08-16 02:40
Having the same issue and @damaestro's change works as a temporary fix- at least to get this building locally again. Specifically adding this line after the `else` and before the `config = use_native_modules!`.

```
pod 'react-native-google-maps', path: File.dirname(`node --print "require.resolve('react-native-maps/package.json')"`)
```

**Comment by lucasrose** [comment] 2024-08-16 05:53
Thanks for the workaround here @damaestro. It looks like using a plugin could handle this for builds in the meantime.
https://gist.github.com/lucasrose/d6c5355c3bead9c42bf9bb9c03a0f66d

**Comment by ryskin** [comment] 2024-08-16 14:04
Same (

**Comment by besim10** [comment] 2024-08-16 14:35
same

**Comment by techied** [comment] 2024-08-16 18:09
The biggest question I have that still remains is: how is this breaking older versions of Expo? Is there a server involved in the process somewhere?

**Comment by davidtiede** [comment] 2024-08-16 18:13
> The biggest question I have that still remains is: how is this breaking older versions of Expo? Is there a server involved in the process somewhere?

My guess would be a dependency of expo has changed, like `expo-module-autolinking` bumping from `1.11.1` to `1.11.2` ~2 days ago... so older versions of expo are still installing the same latest dependencies with the issue. I'm not sure if that's the package that's causing the issue specifically, but given the temporary workaround, it might be related.

**Comment by techied** [comment] 2024-08-16 21:41
> > The biggest question I have that still remains is: how is this breaking older versions of Expo? Is there a server involved in the process somewhere?
> 
> My guess would be a dependency of expo has changed, like `expo-modules-autolinking` bumping from `1.11.1` to `1.11.2` ~2 days ago... so older versions of expo are still installing the same latest dependencies with the issue. I'm not sure if that's the package that's causing the issue specifically, but given the temporary workaround, it might be related.

Sure, but this shouldn't be possible with a lockfile

**Comment by davidtiede** [comment] 2024-08-16 23:48
> > > The biggest question I have that still remains is: how is this breaking older versions of Expo? Is there a server involved in the process somewhere?
> > 
> > 
> > My guess would be a dependency of expo has changed, like `expo-modules-autolinking` bumping from `1.11.1` to `1.11.2` ~2 days ago... so older versions of expo are still installing the same latest dependencies with the issue. I'm not sure if that's the package that's causing the issue specifically, but given the temporary workaround, it might be related.
> 
> Sure, but this shouldn't be possible with a lockfile

For sure, and without knowing the root cause, it’s hard to pinpoint. From what I understand, even with a lockfile, sub-dependencies and peer dependencies that aren’t locked to a specific version (e.g., ^1.0.0 or ~1.0.0) could still bump to a newer minor or patch version on the next install. This could potentially introduce changes or issues, though it’s probably not that common.. but maybe likely what happened here? tbd

**Comment by lishaan** [comment] 2024-08-17 07:18
Looks like our team chose the wrong day to tinker with new native modules. We added a new native module 2 days back and couldn't stop getting this error.

We were able to reproduce it all day yesterday (August 16th) by running the following commands:

git clean -dfx
pnpm i
pnpm run ios

However, this issue has somehow been magically fixed today. Would really love an explanation because we were all in crisis mode for the past few days.

**Comment by ryskin** [comment] 2024-08-17 07:57
Yes it's working now!

**Comment by levymetal** [comment] 2024-08-18 03:25
Looks like this was fixed by https://github.com/expo/expo/pull/31036.

As to how this affects projects with locked dependencies, I've done some more digging found that `expo prebuild` downloads templates from Github, and by default downloads the latest template for the current SDK from the matching branch (eg [sdk-51](https://github.com/expo/expo/tree/sdk-51)).

However, by utilising the template flag, you can pass a specific remote or local path to prebuild. For example, to lock your template to the current working version for SDK 51, this should work:

```sh
npx expo prebuild --template https://github.com/expo/expo/tree/08970a94acaccfba33dee5e9bfdf6a98f60383d4/templates/expo-template-bare-minimum
```

More info here: https://github.com/expo/fyi/blob/main/prebuild-without-npm-access.md#using-a-template-from-github

Ideally templates should be locked with the SDK patch instead of the major. This would be easy if releases were tagged (ala https://github.com/facebook/react-native/tags), but they aren't, so I'm not sure how realistic this is.

Alternatively, and perhaps even better, would be to distribute the templates in a package, allowing the templates to be versioned like any other dependency, and avoids hitting a remote on prebuild.

@Kudo, given you're the author of https://github.com/expo/expo/pull/31036, do you have any thoughts here or can you tag anyone who can weigh in? I feel like the current behaviour of downloading the latest template for the current SDK is likely to bite people again in the future, so it would be nice to see this improved.

**Comment by zhouzh1** [comment] 2024-08-19 06:15
Agree with what @levymetal said above.

**Closed** 2024-08-19 16:38 UTC
Labels: CLI

**Comment by Kudo** [comment] 2024-08-20 03:12
@levymetal Thank you for sharing your insight. I think we could simplify the process by adding a command like `npx expo prebuild --template npm:expo-template-bare-minimum@51.0.50`, which would make it easier without needing to locate the specific commit SHA.

Regarding the idea of sticking to a specific prebuild template version as a patch version for the expo package, we've had extensive discussions on this in the past. Locking the template version could limit our flexibility to apply timely [hotfixes](https://github.com/expo/expo/commit/ecdb66f0bc022a599c49f08338577cb6d5cf306a) for issues like [this](https://github.com/facebook/react-native/issues/35210). Typically, we don't make significant changes to the template in SDK patch versions. The breaking change this time was necessary to support React Native 0.75 in SDK 51.

I completely understand the desire to avoid this problem in the future, but there isn't a perfect solution that works universally. Issues can arise from many different sources. Personally, I lean towards not sticking to a specific template version, as it allows us to quickly republish the latest template without requiring users to bump their expo package versions. However, if you prefer to stick to a template version, you can always use something like `npx expo prebuild --template npm:expo-template-bare-minimum@51.0.50`. Hopes that makes sense to you.
