### ISSUE TITLE
'SplashScreen.show' has already been called for given view controller.

### ISSUE THREAD

**Issue by haibert** [expo/expo#14824] opened 2021-10-21 02:37 UTC
### Summary

This warning comes up on initial launch. 

Also I somtimes still get the ' No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first' error even though i'm upgraded to the latest beta which was supposed to address this issue

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

 Expo CLI 4.12.6 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.8.0 - /usr/local/bin/npm
      Watchman: 2021.10.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0-beta.4 => 43.0.0-beta.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.6
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://github.com/haibert/SplashScreenIssue

I created a blank project with a custom dev client, installed only the libraries needed to reproduce this issue. It basically happens if you have a custom dev client I think, it works fine in expo go. The issue is either from the custom dev client or expo splash screen its self.

### Stacktrace (if a crash is involved)

'SplashScreen.show' has already been called for given view controller.

**Comment by AhmadHoranieh** [comment] 2022-01-27 09:39
Hey, how did you end up solving this? It only started popping up for me after I upgraded my SDK.

**Comment by marcushf** [comment] 2022-02-03 15:46
Also having this issue, can you share how you solved? Thanks!

**Comment by semoal** [comment] 2022-02-19 18:52
Sorry for pinging. But someone did discover something about this?

**Comment by newme616** [comment] 2022-02-20 20:46
I have this too

**Comment by fabio-alvarenga** [comment] 2022-03-05 17:23
Also experiencing this on SDK 44, using expo-dev-client, at least for iOS. 

Adding to the thread: this is happening **intermittently.** There are certain times in which the splash screen actually opens **twice (!)**, being stuck there in the second time.

Here's what happens:

1. I open the app
2. The splash screen appears normally
3. The splash screen gives way to the app entry point (App.tsx loads)
4. Then, after half a second, another splash screen opens, leaving you stuck.

Couldn't find a way to reproduce it yet, but I'm afraid this might happen in production.

Also worth noting: the warning `'SplashScreen.show' has already been called for given view controller.` does not show up when the splash screen opens twice. Which makes sense; the method was called successfully but didn't detect that the splash screen  had already been called.

**Comment by newme616** [comment] 2022-03-05 18:07
> Also experiencing this on SDK 44, using expo-dev-client, at least for iOS. 
> 
> 
> 
> Adding to the thread: this is happening **intermittently.** There are certain times in which the splash screen actually opens **twice (!)**, being stuck there in the second time.
> 
> 
> 
> Here's what happens:
> 
> 
> 
> 1. I open the app
> 
> 2. The splash screen appears normally
> 
> 3. The splash screen gives way to the app entry point (App.tsx loads)
> 
> 4. Then, after half a second, another splash screen opens, leaving you stuck.
> 
> 
> 
> Couldn't find a way to reproduce it yet, but I'm afraid this might happen in production.
> 
> 
> 
> Also worth noting: the warning `'SplashScreen.show' has already been called for given view controller.` does not show up when the splash screen opens twice. Which makes sense; the method was called successfully but didn't detect that the splash screen  had already been called.

Exactly the same on SDK 43

**Comment by fabio-alvarenga** [comment] 2022-03-07 19:46
Fixed it by reading the docs. I was doing some nasty operations with multiple AsyncStorage key/value pairs on startup + Context API and that probably was dispatching double `SplashScreen.show` in the background, automatically.

Now I'm in control of the SplashScreen, hiding it only after the UI is ready to be rendered, after the AsyncStorage restores the state.

I just wish the docs were more informative on that side (i.e., explore more in depth when it's advisable to manually control the SplashScreen vs. the default, mysterious behavior behind the scenes).

For reference: https://docs.expo.dev/versions/latest/sdk/splash-screen/

Might open a PR to edit the page once I'm more knowledgeable on that topic.

**Comment by WillenOLeal** [comment] 2022-05-14 07:46
Having the same issue on SDK 45 with dev-client, and `expo-splash-screen: 0.15.1`

**Comment by joey-harward** [comment] 2022-05-24 19:18
> I never solved it guys, I just gave up on it because its not doing any harm lol, SDK 45 is around the corner at the end march.. maybe itll fix it

It is not fixed in SDK 45 :(

**Comment by haibert** [comment] 2022-05-24 23:58
@joey-harward yea I'm honestly surprised at how quiet the expo team is being about this issue this issue seems to be wide spread

**Comment by PedroBern** [comment] 2022-05-31 18:52
Same issue here. SDK 45 with `--dev-client`

**Comment by brentvatne** [comment] 2022-05-31 19:29
can someone share a minimal reproducible example?

the repo from the original post doesn't exist anymore

**Comment by haibert** [comment] 2022-05-31 19:48
@brentvatne 
Here it is 
https://github.com/haibert/SplashScreenIssueRepo

**Comment by brentvatne** [comment] 2022-05-31 21:45
@haibert - could you make this a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) please? there is a lot of unrelated stuff there

**Comment by haibert** [comment] 2022-05-31 22:05
> @haibert - could you make this a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) please? there is a lot of unrelated stuff there

We'll I left the font loading logic there because I'm 99% sure calling hide on the splash screen manually after loading the fonts is what causes this bug even though I'm following the documentation example. But I guess I can remove everything else, I will send an update shortly

**Comment by brentvatne** [comment] 2022-05-31 22:09
@haibert - the app should have no more than what is absolutely required to reproduce this - in terms of code and dependencies

**Comment by haibert** [comment] 2022-05-31 22:48
@brentvatne Got it, please check now 
https://github.com/haibert/SplashScreenIssueRepo

**Comment by brentvatne** [comment] 2022-06-01 00:55
@haibert - there is still a ton of unrelated stuff in there, eg: react-native-windows. it may be easier for you to try initializing a new project and slowly adding pieces to it until you are able to reproduce the problem again, then remove pieces until it goes away, in order to narrow it down

**Comment by haibert** [comment] 2022-06-02 01:57
@brentvatne https://github.com/haibert/SplashScreenIssue

I created a blank project with a custom dev client, installed only the libraries needed to reproduce this issue.

**Comment by ansh** [comment] 2022-06-09 20:33
I too am having this issue and the culprit seems to be only expo-dev-client as this warning only started showing up after setting up expo-dev-client.

**Comment by haibert** [comment] 2022-06-09 23:57
I think the expo team is at appjs conference hopefully we'll hear something when they're back

**Comment by raajnadar** [comment] 2022-06-11 16:28
Yes the culprits is dev client, in one project I didn't use the dev client and issue did not popup

**Comment by jwoo92** [comment] 2022-06-12 00:11
I am seeing this using SDK 45 and expo-dev-client@1.0.0

**Comment by RWOverdijk** [comment] 2022-06-17 12:48
I've managed to shut up the warnings. I know it's disgusting, but I use the dev client for demos so I had no other choice.

You can be cool, too! You can be just like me. All it takes is two lines of code:

```tsx
import { LogBox } from 'react-native';

LogBox.ignoreLogs(['SplashScreen.show']);
```

Again: this is ew. But some people might be in the same boat as me.

**Comment by bayramn** [comment] 2022-06-17 23:30
I was also experiencing this on SDK 45, using expo-dev-client. After reading @fabio-alvarenga response, I looked my code and found I was calling `await SplashScreen.hideAsync()` bit excessively so I removed one and warning went away. 

I think warning is coming up because of calling `SplashScreen.hideAsync()` repeatedly after calling once before, at least in my case was.

**Comment by brentvatne** [comment] 2022-06-28 03:10
@haibert - I cloned your repo and I can't reproduce it there, any advice?

https://user-images.githubusercontent.com/90494/176083854-152a7afe-78eb-4fe2-b06a-05bca08eb0b6.mov

**Comment by haibert** [comment] 2022-06-28 04:56
@brentvatne I literally just recreated it again by creating a new fresh project. Im on a M1 mac does that make a difference?  i'm baffled. Can anyone else in this issue please try and report to us?

**Comment by joey-harward** [comment] 2022-06-28 05:02
> @brentvatne I literally just recreated it again by creating a new fresh project. Im on a M1 mac does that make a difference? i'm baffled. Can anyone else in this issue please try and report to us?

yes still happening to me on a fresh project

**Comment by RWOverdijk** [comment] 2022-06-28 06:55
Same. It might be the m1, because I'm on an m1 max. Although that would be pretty weird to me.

**Comment by joey-harward** [comment] 2022-06-28 11:44
> Same. It might be the m1, because I'm on an m1 max. Although that would be pretty weird to me.

I'm actually not on an M1

**Comment by AAlvarez90** [comment] 2022-07-08 11:55
This is what I did to silence it (using the latest SDK, I believe is 45).
1. Import it:
`import ExpoSplashScreen from "expo-splash-screen";`

then in your App() component:
```
  const hideSplash = async () => {
    try {
      await ExpoSplashScreen.hideAsync();
    } catch {}
  }
```

Then in the use effect inside your App:

```
  useEffect( () => {
    hideSplash();
  }, []);
```

You can also declare the function inside your use effect and call it immediately...

**Comment by haibert** [comment] 2022-07-08 14:05
@AAlvarez90 did your code before this look like the code from the example from the documentation ?

**Comment by edinhorod** [comment] 2022-07-27 16:55
I managed to solve this by let to use AppLoadding from expo-app-loading:
`import AppLoading from "expo-app-loading";`
Before
`return <ThemeProvider theme={theme}>{fontsLoaded ? <Routes /> :<AppLoading />}</ThemeProvider>;`
After
`return <ThemeProvider theme={theme}>{fontsLoaded ? <Routes /> : null}</ThemeProvider>;`

**Comment by dvkellerman** [comment] 2022-08-04 12:18
> @haibert - I cloned your repo and I can't reproduce it there, any advice?
> Screen.Recording.2022-06-27.at.8.09.46.PM.mov

I was able to reproduce it using dev-client on real device: 
```
eas build --profile development --platform ios
expo start --dev-client 
```

**Comment by winghouchan** [comment] 2022-09-05 19:18
> Also I somtimes still get the ' No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first' error

I got this error when upgrading Expo SDKs and React Native in a bare project. Following the instructions for changes to the `AppDelegate.mm` file in [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/) introduced the issue for me. I followed the [manual installation instructions for Expo Modules](https://docs.expo.dev/bare/installing-expo-modules/) to resolve.

**Comment by paradite** [comment] 2022-09-10 04:39
I got a similar warning with the app (dev-client, SDK 46) when I open the app **and then** enter split-screen with another app on a SamSung S21. The app is stuck in splash screen without loading the existing screen.

The app works fine otherwise without the split-screen, or if the app is not already opened when entering the split screen.

The exact error (warning) when the app got stuck in splash screen is 
> [Error: No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show' (https://github.com/expo/expo/tree/main/packages/expo-splash-screen#-configure-android).]

**Comment by MichaelHabermas** [comment] 2022-09-12 01:04
THis got it fixed for me: https://stackoverflow.com/questions/68823075/error-no-native-splash-screen-registered-for-given-view-controller-for-react-n/69378908#69378908

**Closed** 2022-09-19 16:20 UTC
Labels: SplashScreen, Issue accepted, Development Builds

**Comment by connorpmullins** [comment] 2022-09-26 18:39
@lukmccall  - mind linking to the fix? I'd like to patch my Expo 45 until we can take the time to upgrade.

**Comment by jaymes-bearden** [comment] 2022-09-30 22:51
> I got this error when upgrading Expo SDKs and React Native in a bare project.

Exact same scenario for me -- I was upgrading forwards through 4 SDK versions following the React Native Upgrade Helper which undid some changes by Expo.

Following the [manual installation instructions for Expo Modules](https://docs.expo.dev/bare/installing-expo-modules/) fixed my splash screen issues with Android.

**Comment by Kuohamkun** [comment] 2022-10-28 20:17
I am using expo and I had the same error in ios. Maybe this is not directly related to `expo-splash-screen` , I encountered this error when trying to use AsyncStorage. I installed and configured `expo-splash-screen` but the same error persisted. I sounds strange, so I restarted the simulator, then after relaunching the project, the error disappears :). Hope this helps someone!

**Comment by erisvaldojunior** [comment] 2022-11-17 13:49
Is it fixed on SDK 47? Can someone confirm?

**Comment by Madhawa97** [comment] 2022-11-23 16:27
My error went away when I deleted and reinstalled expo go in my iOS sim.

**Comment by challme28** [comment] 2022-11-24 21:39
I recently upgraded from Expo 45 to 46.
I have the latest expo-cli: 6.0.8
I followed [manual installation instructions for Expo Modules](https://docs.expo.dev/bare/installing-expo-modules/#configuration-for-ios) after the upgrade (including the [guide](https://blog.expo.dev/expo-sdk-45-f4e332954a68)) and it worked.

**Comment by ansh** [comment] 2022-11-25 05:44
Seems like it has been fixed in the latest Expo SDK version (both 46 and 47).

**Comment by grzegorz-krzeminski** [comment] 2023-01-25 10:10
It is still happening on my app on SDK 47 :(

**Comment by Darren120** [comment] 2023-01-26 00:49
sdk 47 still happening

**Comment by jeffreyvalle** [comment] 2023-03-26 06:34
@paradite @haibert 
On my end, solved ' No native splash screen registered for given view controller. Call 'SplashScreen.show' warning while using Expo 47 dev client. 

If you're calling SplashScreen.preventAutoHideAsync() and hideAsync() in the same file or screen try introducing more delay between the two calls by separating them into different screens/navigation. I have the first screen my app loads call hideAsync(), and I call preventAutoHideAsync() from the file all of my native navigation is exported from. Delete the dev client from your device and npx expo run and the warning is gone, simply reloading with 'r' was not enough. Maybe the general solution is introducing more delay between the calls, and knowing that you need to delete client/npx expo run to see if what you've done has done the trick.

Good luck!

**Comment by Developeranees** [comment] 2023-03-31 09:22
Same on Expo 48 :(

**Comment by pkayfire** [comment] 2023-04-25 20:15
Happening to me on Expo 47. Seems like it's isolated to dev client. Didn't face the same issue on Expo Go or production.

**Comment by NicolasD27** [comment] 2023-04-26 14:23
I also had this problem, I fixed it by delaying the display of a modal :

 I have a modal from "react-native-modal" that would open before the splash screen had disapeared. I added a timeout so that I'm sure it will open after the splash screen has been hidden and now no problem anymore. 
 
 Maybe it will help some

**Comment by slimandslam** [comment] 2023-04-30 21:14
Still happening in Expo 48.

**Comment by mangowi** [comment] 2023-04-30 21:53
Happening on Expo 48 bare-workflow

**Comment by rohith-thummanapally** [comment] 2023-05-17 02:11
> sdk 47 still happening. i am on expo start --dev-client
> 
> @grzegorz-krzeminski i was able to solve mine by setting the backgroundColor on the "splash" at app.json to #3F51B5. then restart dev client

this worked for me, thanks.

**Comment by th3f0r3ign3r** [comment] 2023-07-03 01:49
Hello having the same problem a Expo `48`using expo-router template with typescript

**Comment by vendramini** [comment] 2023-07-22 20:17
I tried everything you guys said here, nothing worked out. It's working perfectly on Android but on iOS I get this error, it doesn't even start the app. SDK 48, expo-router, typescript. I'm giving up and keep doing my job on Android hoping to get it fixed when NX allows me to update to SDK 49.

**Comment by dondxniel** [comment] 2023-07-23 09:47
Hello, @lukmccall. You said it will be fixed in SDK 47. I'm using expo 49 and I'm still getting the warning.

**Comment by claudiofus** [comment] 2023-08-21 07:37
I'm facing the same problem with Expo SDK 49, it's so frustrating!

**Comment by BaptistePro** [comment] 2023-09-03 14:31
> I'm facing the same problem with Expo SDK 49, it's so frustrating!

Same problem with : 
```json
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/stack": "^6.3.17",
    "expo": "~49.0.8",
    "expo-build-properties": "^0.6.0",
    "expo-dev-client": "~2.4.8",
    "expo-secure-store": "^12.3.1",
    "expo-status-bar": "~1.6.0",
    "expo-system-ui": "^2.4.0",
    "install": "^0.13.0",
    "intl": "^1.2.5",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-circular-progress-indicator": "^4.4.2",
    "react-native-gesture-handler": "^2.12.1",
    "react-native-google-mobile-ads": "^12.1.0",
    "react-native-reanimated": "^3.3.0",
    "react-native-safe-area-context": "^4.6.3",
    "react-native-screens": "~3.22.0",
    "expo-splash-screen": "~0.20.5"
```

**Comment by SohelIslamImran** [comment] 2023-09-28 00:16
Same issue

**Comment by Navaie** [comment] 2023-10-17 05:37
Same problem here. Happening in production quite a lot, but haven't managed to reproduce it in any way..

**Comment by yolpsoftware** [comment] 2023-10-30 20:31
Same problem here. Happening in production, we are seeing it a lot in Sentry.

**Comment by lsps9150414** [comment] 2023-11-03 03:47
Happening in v.49 using development build

**Comment by yolpsoftware** [comment] 2023-11-03 06:56
Yes, SDK 49, but also in production.

**Comment by brentvatne** [comment] 2023-11-03 22:34
in sdk 50 we're removing this warning entirely because it's not actionable

**Comment by lsps9150414** [comment] 2023-11-17 02:20
> in sdk 50 we're removing this warning entirely because it's not actionable

@brentvatne hey, could you elaborate what the root cause is and what is the impact of the issue not being actionable on the Expo side?

**Comment by brentvatne** [comment] 2023-11-17 18:33
the warning has never been actionable. there are cases where the splash screen can't be shown or hidden because it's either already shown or already hidden, and so this warning doesn't really do much

**Comment by emrahyurttutan** [comment] 2023-11-18 10:39
expo v49;

When I edited it like this, the problem was solved. 
SplashScreen.hideAsync() to await SplashScreen.hideAsync();

`js
import * as React from "react";
import * as Font from "expo-font";
import * as SplashScreen from "expo-splash-screen";
import { FontAwesome, Ionicons } from "@expo/vector-icons";
export default function useCachedResources() {
  const [isLoadingComplete, setLoadingComplete] = React.useState(false);

  // Load any resources or data that we need prior to rendering the app
  React.useEffect(() => {
    async function loadResourcesAndDataAsync() {
      try {
        SplashScreen.preventAutoHideAsync();

        // Load fonts
        await Font.loadAsync({
          ...FontAwesome.font,
          ...Ionicons.font,
          "Poppins-Medium": require("../assets/fonts/Poppins/Poppins-Medium.ttf"),
          "Poppins-Bold": require("../assets/fonts/Poppins/Poppins-Bold.ttf"),
          "Poppins-Light": require("../assets/fonts/Poppins/Poppins-Light.ttf"),
          "Poppins-Regular": require("../assets/fonts/Poppins/Poppins-Regular.ttf"),
          IcoMoon: require("../assets/fonts/icomoon/icomoon.ttf"),
        });
      } catch (e) {
        // We might want to provide this error information to an error reporting service
        SplashScreen.preventAutoHideAsync();
        //console.warn(e);
      } finally {
        setLoadingComplete(true);
        await SplashScreen.hideAsync();
      }
    }
    loadResourcesAndDataAsync();
  }, []);

  return isLoadingComplete;
}
`
