### ISSUE TITLE
expo-notifications

### ISSUE THREAD

**Issue by hashemalkayal** [expo/expo#18629] opened 2022-08-12 17:11 UTC
### Summary

[expo-notifications] Error encountered while updating server registration with latest device push token., [Error: Fetching the token failed: Please set your Project ID. A valid Firebase Project ID is required to communicate with Firebase server APIs: It identifies your application with Firebase.Please refer to https://firebase.google.com/support/privacy/init-options.]

### What platform(s) does this occur on?

Android

### Environment

npx expo-env-info

### Minimal reproducible example

![image](https://user-images.githubusercontent.com/73720742/184409321-bd31c2a7-8f1b-4a4d-9978-ed4671ed1188.png)

**Comment by forki** [comment] 2022-08-12 17:46
duplicate of https://github.com/expo/expo/issues/18570

**Closed** 2022-08-13 06:47 UTC
Labels: needs review
