### ISSUE TITLE
[ios] Standalone apps - Serve the proper js bundle based on publish time

### ISSUE THREAD

**Issue by quinlanj** [expo/expo#1719] opened 2018-05-04 18:06 UTC
IPA's always prefer loading the cached js bundle over the embedded one. However, there are cases when this is not correct. For example, if you upload a new IPA with a newer embedded bundle than what is originally cached on a user's phone, the old cache version will be preferred over the newer embedded version.

Relevant parts from someone experiencing this on forums:
## Reproducing issue

For example, I have two builds: 

SDK version | Build version | Embedded JS version
--- | --- | ---
v25.0.0 | 1.3.9 | 1.3.9
v27.0.0 | 1.4.5 | 1.4.5

Then, do the followings:

1. Install v1.3.9 in TestFlight
2. Open it, showing version 1.3.9
3. Update to app with build version 1.4.5 in TestFlight
4. Open it, still showing version 1.3.9
    - (which is not even in the same channel, of the same SDK version)
5. Close app, reopen, showing version 1.4.5
    - (not downloaded remotely because I have set `"checkAutomatically": "ON_ERROR_RECOVERY"`)

Btw, this happens on ios **AND** android.

## Build procedure

I am building a standalone each time with following precedures:

```bash
# Publish updates
exp publish --release-channel prod-v4

# Build apps
exp build:ios --release-channel prod-v4 --no-publish  # --no-publish will use the most recent published release
exp build:android --release-channel prod-v4  --no-publish
```

## Investigation direction

Can you guys have a check on the logics of choosing js version in standalones?

The updated standalone may be using the JS cache in local storage, but using **embedded JS** should be prior to using the **JS cache**.

Full thread:
https://forums.expo.io/t/updating-standalone-always-use-old-js-bundle-at-first-launch/9457/7

**Comment by carsonwah** [comment] 2018-05-08 08:59
@quinlanj @esamelson I should add that Android also has this behaviour. Thanks.

**Comment by esamelson** [comment] 2018-05-08 17:45
@carsonwah I am unable to repro this issue on Android. I've written the steps I'm following below -- if you are doing something different that causes this behavior, could you let me know?

1. Publish JS version 1, SDK 26 with `checkAutomatically: 'ON_ERROR_RECOVERY'`
2. Make a standalone build A with version 1 and install on device
3. Publish JS version 2, SDK 26
4. Update JS over-the-air on device so that build A is now running version 2
5. Publish JS version 3, SDK 27
6. Make a standalone build B with version 3
7. Install B over A on device and launch

On iOS I see JS version 2 (incorrect, as you've described). However, on Android I see JS version 3 (correct).

We did have this issue on Android previously but it was fixed in March: https://github.com/expo/expo/issues/1122#issuecomment-369356252. Is it possible you have not tested on Android since then?

**Comment by carsonwah** [comment] 2018-05-09 11:27
@esamelson You are right. I didn't know about this fix before. I was experiencing this issue on both platforms before SDK 26. But I was only testing on iOS when I posted it on the forum.

Just tested it on Android and it is working well.

**Closed** 2018-05-11 18:15 UTC
Labels: in progress

**Comment by victorwads** [comment] 2018-05-15 21:27
I an similar issue.

SDK version | Build version |  Ios Embedded JS version  |  Android Embedded JS version | Available OTA version
-- | -- | -- | --
v26.0.0 | 2.0.1 | 2.1.4 | X | 2.1.10
v27.0.0 | 2.1.10 | 2.1.10 | 2.1.10 | OTA Disabled

Then, do the followings:
Install v2.0.1 in TestFlight
Open it, showing version 2.1.4(JS Embedded)
The app will prompt to Update via OTA and will update to  js version 2.1.10 (JS Embedded)
Update to app with build version 2.1.10 in TestFlight
Open it, and an error occurs:
![32506463_1737011736393361_1517451523800432640_n](https://user-images.githubusercontent.com/20746587/40084440-878051a6-586d-11e8-912a-315b4b421ad5.jpg)

---------------------
The expected behavior wold be the new app handle the user data excluding old bundle versions.
If the user uninstall and install the app, it works fine.

**Comment by esamelson** [comment] 2018-05-15 21:49
Hi @victorwads - the fix for the original issue here has now been deployed to our build servers. Could you try making a new build and see if your issue is fixed?

**Comment by victorwads** [comment] 2018-05-15 21:59
@esamelson my apps are detached cause i use native links

**Comment by esamelson** [comment] 2018-05-15 22:17
@victorwads in that case, try following the upgrade guide here: https://docs.expo.io/versions/v27.0.0/expokit/expokit#upgrading-expokit . I believe we've just released iOS version 2.5.9 so try pointing your ExpoKit tag there.

**Comment by martsie** [comment] 2018-07-06 07:18
We've had the same issue the last 2 releases using sdk27. Deployed apps are opening with old release versions despite `exp:publish:history --platform android` showing the most recent build. Maybe it's due to having different release channels for different platforms - we're going to try not using release channels for our next build to hopefully fix it.

**Comment by esamelson** [comment] 2018-07-06 17:18
Hi @martsie . You need both the new and old apps to be built with this fix in order to see the correct behavior. So going forward you shouldn't see this again, but unfortunately you'll need to deal with it for one more release cycle :( Sorry for the inconvenience.

**Comment by martsie** [comment] 2018-07-09 01:34
I think our issue was happening because we weren't incrementing the app version in the app.json (we were only incrementing the build versions for Android and iOS which are required to upload to the stores). Incrementing the app version fixed the issue.
