### ISSUE TITLE
Rogue Expo XDE Helper processes

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#1529] opened 2018-03-13 07:41 UTC
There are dozens of Expo XDE Helper processes that don't seem to get cleaned up by Expo. I only just noticed them, the below screenshot is after closing about half of them (the ones with more memory, averaging about 1-200mb each).
<img width="912" alt="screen shot 2018-03-13 at 12 40 15 am" src="https://user-images.githubusercontent.com/1566400/37328405-40cf7464-2657-11e8-853b-8f5f9d2c0b58.png">

**Comment by terribleben** [comment] 2018-03-22 18:09
Hey there, closing this thread as a duplicate of https://github.com/expo/expo/issues/177 . This bug has actually been really hard for us to reproduce (although we do sometimes see it), so if you can provide any other info about your system or the circumstances where you saw it, that'd be really helpful. Thanks!

**Closed by terribleben** 2018-03-22 18:09 UTC
Labels: project: xde/exp/xdl
