### ISSUE TITLE
Expo Image prefetch method doesn't have a way to supply headers

### ISSUE THREAD

**Issue by TowhidKashem** [expo/expo#33412] opened 2024-12-04 00:13 UTC
### Minimal reproducible example

https://github.com/expo/expo

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

Expo Image component lets you supply headers like this:

```
  <Image
    source={{
      uri: source,
      headers: {
        Authorization: `Bearer ${authToken}`
      }
    }}
    //...
  />
```

The prefetch option should too, but currently it only accepts:

```
  static async prefetch(
    urls: string | string[],
    cachePolicy?: ImagePrefetchOptions['cachePolicy']
  ): Promise<boolean>;
  ```
  
  This appears to be a mistake cause the `ImagePrefetchOptions` type does include the headers:
  
  ```
  export type ImagePrefetchOptions = {
  /**
   * The cache policy for prefetched images.
   * @default 'memory-disk'
   */
  cachePolicy?: 'disk' | 'memory-disk' | 'memory';

  /**
   * A map of headers to use when prefetching the images.
   */
  headers?: Record<string, string>;
};
```

But the implementation is lacking it. Please add it so that images that are behind authenticated endpoints can be prefetched.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.1 - /opt/homebrew/opt/node@20/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/opt/node@20/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.10 => 52.0.14 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Validate packages against React Native Directory package metadata
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by chrfalch** [comment] 2024-12-04 16:22
Hi @TowhidKashem - thanks for reporting this issue! It looks to me like the iOS implementation is using the header provided to the `prefetch` method - this is from the `ImageModule.swift` file implementing the iOS native version of `prefetch`:

<img width="838" alt="image" src="https://github.com/user-attachments/assets/6efe416e-1476-4edf-bc14-459152f953c5">

Could you add a small example showing code that shows how your are trying to use it?

**Comment by TowhidKashem** [comment] 2024-12-04 17:00
> Hi @TowhidKashem - thanks for reporting this issue! It looks to me like the iOS implementation is using the header provided to the `prefetch` method - this is from the `ImageModule.swift` file implementing the iOS native version of `prefetch`:
> 
> <img alt="image" width="838" src="https://private-user-images.githubusercontent.com/875252/392477711-6efe416e-1476-4edf-bc14-459152f953c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzE2MTIsIm5iZiI6MTczMzMzMTMxMiwicGF0aCI6Ii84NzUyNTIvMzkyNDc3NzExLTZlZmU0MTZlLTE0NzYtNGVkZi1iYzE0LTQ1OTE1MmY5NTNjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNjU1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmRiNDQ0NzhmN2M4ZTA3NzU1ZmY0Njg0MmE2ZDU4NGRkYjFlZWZkZTZiMTEwMWQ1ZmIzM2MyNWVmZmI0MDcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PEtzgn5nT1TH3oj1w_zaQog2C3MS1PPsiMw0z8YgtdI">
> Could you add a small example showing code that shows how your are trying to use it?
> 
> Looks like it was added in April through #28133.

Thanks for the response, I think the problem is that the Javascript side of things needs to be updated because now there is no way to provide the headers on the javascript end.

This is how I am using it:

`await ExpoImage.prefetch(images, 'memory-disk');` // no way to provide headers with the current interface

it works for images that don't require authentication. For images that do there is simply no way to provide the header info, as you can see from the typescript interface it doesn't accept it:

```
  static async prefetch(
    urls: string | string[],
    cachePolicy?: ImagePrefetchOptions['cachePolicy']
  ): Promise<boolean>;
  ```
  
  it should be something like:
  
```
  static async prefetch(
    urls: string | string[],
    options?: ImagePrefetchOptions
  ): Promise<boolean>;
```

I didn't look into the function to see if it supports options or not, but the type is wrong and perhaps the function (on javascript side) is wrong too.

Let me know if my explanation isn't clear...

**Comment by chrfalch** [comment] 2024-12-04 17:06
The explanation is good - would be very nice with a small reproduction as a GitHub repo that I can use for investigation, without it it'll be hard to find a solution.

**Comment by chrfalch** [comment] 2024-12-04 17:52
Just tested quickly and I'm seeing that the following seems to be working correctly - also tested that this is propagated to iOS:

```ts
 Image.prefetch(
      "... some image url ...",
      {
        cachePolicy: "memory",
        headers: {
          "Header-key": "value",
        },
      }
    );
```

If this works for you, please close this issue :)

**Closed** 2024-12-04 20:12 UTC
Labels: needs review
