### ISSUE TITLE
expo-secure-storage alternatives for android versions 5 and older

### ISSUE THREAD

**Issue by rungwe** [expo/expo#6386] opened 2019-11-27 06:56 UTC
I wanted to know if there any suggestions regarding use of secure storage in persisting credentials, since only android version above 5 are supported how best can I deal with cases where other users have older android versions which are not supported. I had thought of temporarily using Asyc storage in that case but I couldn't find a relevant api to determine if secure storage is supported or not on that device at runtime

**Comment by cruzach** [comment] 2019-11-27 16:03
Closing this since it's not a bug with the Expo SDK, and questions like this are better off posted on our [forums](https://forums.expo.io/)

Expo supports Android 5 and above, so for versions below Android 5 I can't really give you a good answer.

For Android 5, specifically, I think your proposed solution of using AsyncStorage would work. You can check the device OS at runtime using Expo's [Device.osVersion](https://docs.expo.io/versions/latest/sdk/device/#deviceosversion) constant

**Closed by cruzach** 2019-11-27 16:03 UTC
