### ISSUE TITLE
No native splash screen registered for provided activity

### ISSUE THREAD

**Issue by pfalcetti** [expo/expo#10548] opened 2020-10-05 12:34 UTC
## 🐛 Bug Report

I'm getting this error in my Expo App, both IOS and ANDROID:

`Unhandled promise rejection: Error: No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show'`

I'm using Expo Managed workflow ,so i'm not using inside my App the expo-splash-screen module.

Current SDK version installed: "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz"

#10464 is not solving this issue.

How can i solve this ? 

Thanks

**Comment by AbdnhVmpr** [comment] 2020-10-05 15:42
This bug has blocked me completely. I updated all my applications on Play store with the latest expo SDK. But now when I install one of these apps on my device, it crashes. Now I noticed that there's this bug. I hope that they solve this as fast as possible :(

**Comment by walosha** [comment] 2020-10-05 17:51
same issue here

**Comment by brentvatne** [comment] 2020-10-05 17:52
hi there! are you using the latest version of expo client? you should see 2.17.4 at the bottom of your "Projects" tab on ios and android

**Comment by brentvatne** [comment] 2020-10-05 18:49
closing this because i can't reproduce, the reporter didn't follow the issue template, and i am fairly confident that the issue is caused by an outdated expo client version.

**Closed by brentvatne** 2020-10-05 18:49 UTC
Labels: Android, SplashScreen, iOS, status: needs more info

**Comment by pfalcetti** [comment] 2020-10-06 07:49
Hello @brentvatne . Sorry for the un-complete issue. 

I've opened a new issue #10573 , with info to reproduce it.

But i figured out the problem: 

With no Expo client App installed on my device, after running the expo start command for running the app on android, it's  installing the Expo client app V.2.17.2 instead of the last 2.17.4.

Updating the Expo client app the problem is gone as u suggested. 

Should i open a new issue for the wrong version of Expo client app installed with the command expo start ? 

Thank u for help.

**Comment by pniby** [comment] 2022-07-19 10:40
In my case, the problem was because I missed the followiing line in `MainActivity.Java`
`import expo.modules.ReactActivityDelegateWrapper;
`
