### ISSUE TITLE
Barcode scanner not working on some android devices with expo v27

### ISSUE THREAD

**Issue by frecson** [expo/expo#1782] opened 2018-05-22 21:15 UTC
### Issue

Hi! I hope someone could help me! 

I have made an app with expo for iOS and Android devices. One of the main functions of the app is to scan a QR code, I’m using the BarCodeScanner component. The app is working fine in iOS devices, but is not working in some Android versions. To be more specific I made a lot of tests in Huawei P20 models and Huawei Mate 10 with android versions 8.0, 8.1 and 7.0 and the latest version of expo installed in the devices (2.5.2). I have checked some other posts about this issue, some people resolved it by downgrading the expo version to 22, but I want to know if there is not another solution because from 22 to 27 (my actual version) there is a lot of time. I’m using expo v27.0.1. Even the Expo app isn’t working on these android versions when I try to scan the QR code for my project.

My code to scan the QR is similar to this example: https://snack.expo.io/Skxzn6-5b
  
### Environment

  OS: macOS High Sierra 10.13.1
  Node: 8.11.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

### Expected Behavior

In my app: Scan the QR code and make some things when the QR is detected.
In Expo app: Scan the QR generated for my project and open the app when is detected (the normal behavior of Expo QR reader in Android).

### Actual Behavior

With the expo app I can’t scan the QR generated by my project, nothing happens, I just put the camera in front of the QR to read the code and nothing happens, just like if there was not code in front of the camera, so, because the expo app isn’t working either, I think the problem is not with the code of my app. When I run my app is the same thing, nothing happens, no error, no action, no logs, nothing, it just doesn’t work. It’s working with a Galaxy S5 with android 6.0.1 but not with the other versions I mentioned above.

### Reproducible Demo

The last Expo app version isn't working, even the basic example in snack isn't working either: https://snack.expo.io/Skxzn6-5b

I think the issue is about the android versions I'm using and the version of Expo, the camera api used in Expo maybe has bugs with the latest versions of android.

Thanks!

**Comment by schazers** [comment] 2018-05-22 21:16
Thanks for the detailed report! We'll have a look.

**Comment by frecson** [comment] 2018-05-22 21:28
Great! Thanks!

**Comment by kirning** [comment] 2018-05-23 03:30
it is not work in my phone too. my phone is meizu pro5

**Comment by ccheever** [comment] 2018-05-23 07:33
Here is a forum post with another issue with Huawei phones.
https://forums.expo.io/t/oncameraready-not-called-for-android/10073/2

**Comment by frecson** [comment] 2018-05-24 19:27
Hi! Is there any news about this? 
Thanks!

**Comment by brentvatne** [comment] 2018-05-24 19:29
@frecson - please try this out and let me know if it works for you: https://snack.expo.io/SyKYf5E17

**Comment by frecson** [comment] 2018-05-24 22:34
@brentvatne it didn't work! The same thing happens, is not detecting the QR. I made the test with Huawei P20 pro, Android 8.1.0

Thanks for your help!

**Comment by fresswolf** [comment] 2018-05-27 13:15
I can confirm these issues on a Huawei Media MediaPad T3 10' with Android 7.0 and EMUI 5.1.1 as well. The issue is present with both the BarCodeScanner and Camera component, with onBarCodeRead not being called. Also, when implementing the onFacesDetected callback, faces are not detected and onMountError is called with the object {"isOperational": false}.
I've investigated this quite a bit and found something strange. When resetting the device to factory settings, everything with above APIs work as expected, until the first reboot of the device. Afterwards you can reboot the device, reinstall the apps, clear caches etc. as often as you like, it won't help. Until you reset the device back to factory settings (Advances settings -> Reset all settings).

I know this all sounds weird, but I can reproduce this behaviour consistently. In fact, rebooting is fine until you install your first expo based app (or the expo app from the play store itself). From that moment on, when you reboot, all of the expo apps show the issues. Which hints to me that there is also a problem with Huawei's or EMUI's implementation of sandboxing. 

The next step would be to detach to ExpoKit and debug the native component with Android Studio. But it seems that work is already being done on the issue?

@esamelson were you able to find the cause of those problems?

**Comment by frecson** [comment] 2018-05-28 15:34
That's true @fresswolf, because the very first time I used the app It worked fine. 

Thanks for the report @esamelson. Do you know when will this release be available?

**Comment by aalices** [comment] 2018-05-29 13:53
Hi all, we started using Google Mobile Vision as a barcode detecting library and it occurred it sometimes does not work for some phones ( my Huawei was able to scan but stopped 🤷‍♀️ ) so we decided to use the lib we used before (zxing) if GMV says it is not available for the device. We'll release probably next week

**Comment by IrregularShed** [comment] 2018-06-08 17:39
I'm getting this behaviour as well, on my Moto G5. (Annoyingly my whole reason for trying out Expo in the first place was to make a barcode scanning app!) Glad to see there is work going on though.

**Comment by aptkingston** [comment] 2018-06-11 15:55
SDK 24 is the latest version that works on my Huawei P9 running Android 7.0. I've tried every release since then and none have been able to scan barcodes. Downgrading to SDK 24 should work as a temporary solution until things are hopefully fixed in the upcoming SDK 28 release.

**Comment by fresswolf** [comment] 2018-06-11 16:20
@aptkingston It's a bug in recent versions of Google Play Services since May 8th. See the discussion here: https://issuetracker.google.com/issues/80454351.
Google seems very slow at addressing this issue.

**Comment by IrregularShed** [comment] 2018-06-14 08:43
It's working well for me 👍

**Comment by aptkingston** [comment] 2018-06-14 09:13
SDK 28 is working for me, great job!

**Comment by esamelson** [comment] 2018-06-14 16:43
Awesome, I'm going to go ahead and close this since it seems the issue is resolved. If you run into similar issues in the future, please open a new issue with specific details about your device and situation.

**Closed by esamelson** 2018-06-14 16:43 UTC
Labels: project: misc-libraries

**Comment by fresswolf** [comment] 2018-06-14 18:56
Note that at the same time, google fixed the issue in play services 12.8.62, which is currently in beta is due for release soon. So it will start to work again in SDK 27 in a few days

**Comment by esamelson** [comment] 2018-06-14 19:00
@fresswolf I believe the change we made was backported, so it should work in all SDK versions in the new Expo client, or if you just rebuild your standalone app. No need to upgrade or wait for Google :)

**Comment by tarunkolla** [comment] 2018-07-02 17:43
Have the same issue still. Works on iOS and web but crashes on Android (SDK28).

**Comment by esamelson** [comment] 2018-07-02 17:45
Hi @tarunkolla - could you open a new issue and follow the template there to the best of your ability? The more details the better. This particular issue has been fixed and there was a big change in SDK 28, so it's likely you're seeing a new issue.
