### ISSUE TITLE
Fatal error: Something unexpected has happened. Only dynamically created `ViewModuleWrapper` can be initialized without params.

### ISSUE THREAD

**Issue by mrousavy** [expo/expo#25835] opened 2023-12-09 12:27 UTC
### Minimal reproducible example

npx react-native@latest init Repro --version 0.73.0 # then set up expo-modules-core in there

### Summary

When adding expo-modules-core to a bare RN 0.73 app, it immediately crashes upon launch with the following error:

```
com.facebook.react.JavaScript (8): Fatal error: Something unexpected has happened. Only dynamically created `ViewModuleWrapper` can be initialized without params.
```
![Screenshot 2023-12-09 at 13 24 49](https://github.com/expo/expo/assets/15199031/96deb08a-ee30-4ba9-ba35-75fb15bb3da7)

Maybe a bit off-topic, but I'm only using expo-image for now (which is awesome btw!), so I'm wondering if all these wrappers are needed for expo-image to work? This is wrapping every `UIManager` instance here.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v18.17.0/bin/yarn
      npm: 10.2.5 - ~/.nvm/versions/node/v18.17.0/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 34
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.0 => 0.73.0 
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: bare

**Comment by achingbrain** [comment] 2023-12-11 09:30
I'm seeing the same thing, a box-fresh project almost runnable after working around [this issue](https://stackoverflow.com/questions/69871829/undefined-method-apply-xcode-12-5-m1-post-install-workaround), [this issue](https://github.com/thebergamo/react-native-fbsdk-next/issues/346), [this issue](https://github.com/margelo/react-native-quick-crypto/issues/189) and also [this issue](https://github.com/facebook/react-native/issues/33178).

**Comment by jaysoniNucleus** [comment] 2023-12-11 12:18
Same issue i am facing

**Comment by tsapeta** [comment] 2023-12-11 16:22
A stable version of React Native 0.73.0 was released less then a week ago. It introduced breaking changes for libraries and there are still some that don't support it yet. SDK 49 is intended to be used with React Native 0.72 (see the compatibility table https://docs.expo.dev/versions/latest/#each-expo-sdk-version-depends-on-a-react-native-version). SDK 49 does not support React Native 0.73 and the team is now focused on releasing SDK 50 that supports it, I'm going to close this issue.

Beta of SDK 50 should be out this week and you can expect this issue to be solved there. In the meantime, you can use a canary version – read more on how to use canary versions here https://docs.expo.dev/versions/latest/#using-pre-release-versions.

**Closed by tsapeta** 2023-12-11 16:22 UTC
Labels: needs review

**Comment by carbopilot** [comment] 2023-12-11 17:07
@tsapeta .. 

Yes, we all know of the compatibility table, but 90% of us are here developing cutting edge apps, relying on latest libraries that we invest in - like expo.

There's been numerous RC's and nothing had been advised of incompatibility. Is no testing done until RN is released? 

Should teams whom wish to use the latest tech decouple expo from their apps?

**Comment by Kudo** [comment] 2023-12-11 18:12
React Native 0.73, released just last week, marks an exciting step forward, but it's crucial for both library authors and app developers to take a moment to ensure everything is compatible and functioning as expected. We're thrilled to announce that the SDK 50 beta, fully supporting React Native 0.73, is just around the corner. Please stay tuned for its release.

I'd like to emphasize that our testing process begins well before the official release of React Native. In fact, the issue you're referring to was proactively tackled in #24019 a few months back, thanks to our diligent testing with React Native nightlies. Our team also promptly reported the Android Gradle Plugin (AGP) 8 breaking changes, as you can see in [this thread](https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1677632448). It's worth noting, however, that some third-party libraries are yet to update for these changes. We're actively working on alternative solutions, like the one proposed in [this pull request](https://github.com/facebook/react-native/pull/41085). Moreover, during recent react-native release candidate testing stage, we identified and addressed a regression related to reloading, as detailed in [this pull request](https://github.com/facebook/react-native/pull/41678).

Given the various changes and updates, we recommend a brief wait for SDK 50 to ensure a smooth transition. Your patience and support during this phase are greatly appreciated, as they contribute to a more robust and efficient development environment for everyone.

**Comment by mrousavy** [comment] 2023-12-11 18:31
I understand that SDK 49 is not intended to be used with RN 0.73, I was just creating this issue in hopes to help save some time and already report it since I already tried it :)

**Comment by Kudo** [comment] 2023-12-11 18:49
thanks @mrousavy!

FWIW, this particular issue could be fixed as https://github.com/expo/expo/commit/db6683c660bdd3365d10d482503fa3339f6b894a#diff-35c03278290200391460fe4f92b8270f70a16ef9187f2dcab571d826a32e9b02L41, by using patch-package if that's a blocker. in #24019, i have traced back to upstream change from https://github.com/facebook/react-native/blob/540c41be9/packages/react-native/React/Views/RCTComponentData.m#L506-L507. that would break our assumption.

**Comment by mrousavy** [comment] 2023-12-12 12:02
Thanks Kudo, much appreciated! :)

**Comment by Kudo** [comment] 2023-12-14 02:02
FWIW, sdk 50 is available in beta now: https://expo.dev/changelog/2023/12-12-sdk-50-beta. please let us know if there's any problems from react-native 0.73 support. thanks for waiting.

**Comment by irinalarisabarbos** [comment] 2024-01-03 10:56
I experience the same error with:
    "expo": ">=50.0.0-0 <51.0.0",
    "react-native": "0.73.1",
