### ISSUE TITLE
[SDK52] KeyboardAvoidingView doesn't animate

### ISSUE THREAD

**Issue by quentez** [expo/expo#32575] opened 2024-11-04 10:51 UTC
### Minimal reproducible example

https://github.com/quentez/keyboard-bug-repro

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

Using the new SDK 52 version of Expo, the `KeyboardAvoidingView` component doesn't properly animate and instead jumps directly to the final position. This worked properly in SDK 50.

In the linked repository, you can find a project created using the Expo scaffolding tool and only modified to upgrade to SDK 52 and add a new screen with a `TextInput` in it. When focusing the input on iOS, the keyboard appears but the view does not animate.

The same example works using the ReactNative "Getting Started" project template using RN 76.1, so this appears to be Expo-related.

### Environment

```text
expo-env-info 1.2.0 environment info:
  System:
    OS: macOS 15.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.8.3 - /opt/homebrew/bin/npm
    Watchman: 2024.09.23.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
  IDEs:
    Xcode: 16.1/16B40 - /usr/bin/xcodebuild
  npmPackages:
    expo: ~52.0.0-preview.18 => 52.0.0-preview.18 
    expo-router: ~4.0.0-preview.11 => 4.0.0-preview.11 
    react: 18.3.1 => 18.3.1 
    react-dom: 18.3.1 => 18.3.1 
    react-native: 0.76.1 => 0.76.1 
    react-native-web: ~0.19.10 => 0.19.13 
Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Didn't find any issues with the project!
```

**Comment by mhoran** [comment] 2024-11-04 16:34
I think this could be related to #32546.

**Comment by quentez** [comment] 2024-11-11 00:12
@mhoran I see you found the underlying reason for #32546. Could that `onLayout` issue also be part of the reason for this one or does it look like something else entirely?

**Comment by mhoran** [comment] 2024-11-11 00:32
I think so. I compared Expo v51 behavior to v52 with the corresponding dependencies loaded and see that `onLayout` fires whenever the keyboard appears or disappears on v51 but this does not happen in v52.

**Comment by quentez** [comment] 2024-11-11 02:21
That makes sense. Thank you for investigating! 🙇‍♂️

**Comment by brentvatne** [comment] 2024-11-12 22:55
duplicate of https://github.com/expo/expo/issues/32546

**Closed by brentvatne** 2024-11-12 22:55 UTC
Labels: needs review

**Comment by quentez** [comment] 2024-11-15 13:13
For reference, this is related to: https://github.com/software-mansion/react-native-reanimated/issues/6684

**Comment by mhoran** [comment] 2024-11-15 13:31
There is also another issue on React Native that was just opened: https://github.com/facebook/react-native/issues/47617. It's a bit unclear to me issue you're experiencing; you have the same dependencies loaded as #32546 so it could be that, or it could be the upstream React Native issue. Regardless, it seems to be some sort of New Architecture issue with animations, either natively in React Native or via Reanimated.

**Comment by quentez** [comment] 2024-11-15 13:34
Interesting. In my case I wasn't able to repro on a brand new RN 0.76 project while it was happening on a new Expo project. But yeah since that's also what `KeyboardAvoidingView` uses internally so that would explain it as well.

**Comment by moritzlang** [comment] 2024-12-16 11:24
Any update on this? I have the same issue

**Comment by kriit24** [comment] 2024-12-31 06:10
in my case it does not do anything - no scrolling and no avoiding on textinput press

**Comment by antochan** [comment] 2025-01-17 23:19
I'm still experiencing this on my expo build. 

Currently on:
"react-native": "0.76.6"
"react-native-reanimated": "~3.16.1",
"expo": "~52.0.25",

I'm also noticing the same jumpy behavior on the react native demo here
https://reactnative.dev/docs/keyboardavoidingview

Does this mean the patch is still not in?

**Comment by julianallchin** [comment] 2025-02-03 01:19
I am also experiencing this with the same versions as @antochan
