### ISSUE TITLE
Multiple DeviceNotRegistered errors

### ISSUE THREAD

**Issue by toxox** [expo/expo#1745] opened 2018-05-11 12:28 UTC
Hi Expo team!

Recently I experienced issues with push notifications using Expo's service in standalone apps. I have set up email alerts to inform me about cases when push receipts contain errors. Some time on May 9th I started receiving unusually high number of alerts: roughly 50% of our users stopped receiving notifications. The errors themselves look like this:

``` 
{
    "status": "error",
    "message": "The recipient \"ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]\" is not associated with a device actively registered to receive push notifications; stop sending notifications to this recipient until you get an Expo push token from it once again and still have its permission to send notifications.",
    "details": {
      "error": "DeviceNotRegistered"
    }
  },
```
The app is configured in a way that it will send a request to update token value in DB whenever updated token is available via `Notifications.getExpoPushTokenAsync`. The problem is that this method still returns old token (the one we already have and using it results in an error). The only way I could get a new token is reinstalling the app completely, which is far from an ideal solution.

Diagnostics report:

Environment:
  OS: Linux 4.4
  Node: 8.6.0
  Yarn: 1.6.0
  npm: 5.3.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz

Things to note:
1) Neither app or back-end had been updated for about a month before the issue first appeared
2) This looks different from #1568 as iOS devices are affected as well.
3) Users definitely didn't block notifications from the app on their devices.
4) I'm using expo-server-sdk package

Questions:
1) What's the lifespan of expo tokens? Is it possible that they just expired?
2) Is it possible that these tokens hit their usage limits or something? We kind of send a lot of notifications daily.

Is there any way I can fix this on my side? Let me know if there's any other info you need, I'll be glad to help you with the investigation.

Thanks.

**Comment by jimmylee** [comment] 2018-05-11 20:55
@toxox its my understanding at the moment that you need to update your versions (SDK) to the latest since we've made some changes to how this works.

**Comment by jimmylee** [comment] 2018-05-11 20:57
I would try these dependencies:

```
    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",
```

**Comment by ide** [comment] 2018-05-12 02:35
"DeviceNotRegistered" is something that Expo does not control. For iOS notifications, that is entirely decided by Apple, and for FCM notifications, it is decided by Google. They may unregister a device token for any reason.

One thing you mentioned in the original post is that `getExpoPushTokenAsync` always returns the same value. This is how the API works: there is only one Expo push token per installation of an app and it maps to the latest native device token (i.e. APNs or FCM token), which the iOS client periodically sends to the Expo servers when:

(a) the app starts and has permission to send and show notifications and
(b) you call `getExpoPushTokenAsync` and the app has permission to send show notifications

**Comment by physixfan** [comment] 2018-05-12 20:11
A lot of people are experiencing the same issue, and here's some complaints on the expo forum: https://forums.expo.io/t/push-notification-error-devicenotregistered/9662
Please give us a solution how to fix this, thanks!

**Comment by miraan** [comment] 2018-05-13 12:46
I also have this issue, is there a fix?

**Comment by anp** [comment] 2018-05-14 21:47
Hi everyone! I'm looking into this to rule out some recent changes to our push notification broker. If you're still experiencing this issue could you [email me](mailto:adam@expo.io) the Expo push token(s) for the affected devices?

**Comment by physixfan** [comment] 2018-05-15 04:48
It seems the problem is fixed as of 2018.05.14 21:00 PST! Thanks!

**Comment by anp** [comment] 2018-05-15 17:11
Hi everyone! Sorry this took a little while to discover, the underlying bug here was caused by a caching error being swallowed and converted into a "token no longer valid" error. We've resolved the caching issue and will be following up soon to prevent this from happening again. This problem does not appear to have affected the majority of users, but we're extremely sorry for everyone who was affected.

If you're still seeing this error, please let us know and we'll look into it!

**Closed by anp** 2018-05-15 17:11 UTC
Labels: project: push-notifications

**Comment by georgiosd** [comment] 2019-06-10 15:16
@anp are you saying that the value from `getExpoPushTokenAsync` can change over time?

We are getting tons of `DeviceNotRegistered` errors presumably from users which have been logged into the app for a long time.

We're getting this token when the user logs into the app but the login is indefinite (with a refresh token).

What are missing here?

**Comment by ide** [comment] 2019-06-10 21:12
For a given installation, the value of `getExpoPushTokenAsync` will not change. It is 100% independent of your login, since it is associated with a device; not a user. If people disable notifications or don't open the app for a very long time, Apple or Google may expire the underlying device token.

**Comment by georgiosd** [comment] 2019-06-11 04:14
@ide ok, but how do we handle either case?

**Comment by ide** [comment] 2019-06-11 09:06
If notifications are disabled or the native device token has otherwise expired, the correct way to handle it is to stop sending notifications to the token. Apple and Google mention this in their docs and ask not to receive notifications to expired device tokens.

When the Expo app is opened, it will re-register the latest native device token with Expo's servers. If there is still an issue in this case, identifying the root cause is the most useful way to make progress on a fix.

**Comment by georgiosd** [comment] 2019-06-11 09:21
@ide so we should be calling `Permissions.getAsync` at startup and if not `granted` we should be deleting the expo token (which we can still get with`Notifications.getExpoPushTokenAsync()`) from our servers, correct?

**Comment by ide** [comment] 2019-06-11 18:09
Yes, if the permissions aren't granted you should stop sending notifications to the token. You also should look for DeviceNotRegistered response codes -- this is Apple & Google's policy and separate from Expo.

**Comment by georgiosd** [comment] 2019-06-12 05:44
@ide thanks. It would be helpful to say those things in the docs - they're very basic right now.

**Comment by georgiosd** [comment] 2019-06-13 15:20
@ide so it seems that we are not deleting DeviceNotRegistered tokens which is fine, that's easy to fix.

However now we're seeing an issue with some Android phones where the status comes back as `ok` but the user is not getting the notification, and permissions are enabled fine.

How do we debug this?

**Comment by nicolasrouanne** [comment] 2019-10-23 13:02
I get it that we should delete the `ExpoPushToken` when we get a `DeviceNotRegistered ` but how do we know if the user has re-enabled Notifications in his settings? That would mean his `ExpoPushToken` (the same one) is now valid again and we can send him notifications.

But how can we know that, to trigger the correct behaviour?
