### ISSUE TITLE
MediaPlayer not working on Android

### ISSUE THREAD

**Issue by gsunsnackv** [expo/expo#3258] opened 2019-01-19 00:04 UTC
### Environment

  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 4.4.23 - /usr/local/bin/bash
    Binaries:
      Node: 11.5.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.npm-packages/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.1
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.6.14

This bug is for Android 9 version 28 only. The demo project works fine on Android 8.x and 7.x

### Steps to Reproduce
(Write your steps here:)

1. expo init an empty project
2. Add a expo `Video` tag and get the ref
3. In `componentDidMount` use the ref to start the video using `loadAsync`
4. Set `androidImplementation` to `MediaPlayer`  according to the doc here: https://docs.expo.io/versions/latest/sdk/av.html

### Expected Behavior
Expect video to work properly on Android

### Actual Behavior
Video never plays. Some times `loadAsync` just stuck, no error. Sometimes it fails with error:
```
[15:54:27] Load encountered an error: the OnErrorListener was called with 'what' code 1 and 'extra' code -2147483648.
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:95:55 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:397:4 in __invokeCallback
- ... 4 more stack frames from framework internals
```

### Reproducible Demo
https://github.com/gsunsnackv/old-media-player-not-working-android-9
https://snack.expo.io/rJhgYkg7E

**Comment by gsunsnackv** [comment] 2019-02-06 19:01
@AdamJNavarro  @sjchmiela Any update on this? We feel that only Android 9 have this problem but we are not 100% sure

**Comment by James2516** [comment] 2019-10-05 00:50
Still broken on SDK 35.
Repro snack: https://snack.expo.io/rJHDOvS_r
Please test with an actual device to see the error. It works on Snack's simulator for some reason.

**Comment by esamelson** [comment] 2019-10-14 19:51
Thanks for the updated repro, @James2516 ! Could you provide some steps for how to trigger the error with your snack? I ran it and went through the "recording" -> "playing" cycle a bunch of times with no errors.

**Comment by James2516** [comment] 2019-10-15 03:17
@esamelson did you run it on an actual Android device (i.e. *not* emulator/iOS)?
It's reproducible on my Samsung S6 Android 7.0.

**Comment by esamelson** [comment] 2019-10-15 19:37
@James2516 I don't have an Android 7 device handy to test with right now, but based on other comments it looks like it affects Android 9. It worked fine on my Google Pixel 2 yesterday, so based on this I will assume this is one of those annoying Android issues that's device/hardware-specific 😞

**Comment by James2516** [comment] 2019-10-16 00:38
@esamelson are you using the latest public Expo client? 
This is the error I get if that helps:
![](https://i.imgur.com/kDS5dZx.png)

**Comment by mczernek** [comment] 2019-11-19 10:19
I've reproduced and hopefully fixed the issue in [this PR](https://github.com/expo/expo/pull/6320). Let's hope it gets merged before SDK36.

**Closed** 2019-11-19 10:23 UTC
Labels: Video, project: android-runtime
