### ISSUE TITLE
Load encountered an error: player not created.

### ISSUE THREAD

**Issue by halallahh** [expo/expo#147] opened 2017-05-03 15:48 UTC
I got this error ```Load encountered an error: player not created.``` when try load recording audio. 

 Same issue when running with this example app:
https://github.com/expo/audio-recording-example/issues/1

**Comment by skevy** [comment] 2017-05-04 19:05
cc @gkufera

**Comment by gkufera** [comment] 2017-05-04 19:38
Hi @halallahh -- 

Can I have some more details about the device you were running this on, if it this bug is reproducible, and what audio you were trying to play? Does this happen on your device with all types of audio, or just audio created from recording?

Thanks!

**Comment by halallahh** [comment] 2017-05-04 20:35
Hi, I running on android device alcatel one touch flash 2 (Lolipop). Just audio created from recording and other audio format is fine can play without any problem.

**Comment by skevy** [comment] 2017-05-04 21:26
From https://github.com/expo/audio-recording-example/issues/1 (which I closed):

```
Load encountered an error: player not created.
createErrorFromErrorData@http://192.168.1.7:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:3215:24
http://192.168.1.7:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:3173:49
__invokeCallback@http://192.168.1.7:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:3488:21
http://192.168.1.7:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:3347:32
guard@http://192.168.1.7:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:3286:7
invokeCallbackAndReturnFlushedQueue@http://192.168.1.7:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:3346:12
invokeCallbackAndReturnFlushedQueue@[native code]
```

**Comment by skevy** [comment] 2017-05-04 21:26
@halallahh it seems like you're attempting to use the audio API from CRNA...is that correct?

**Comment by halallahh** [comment] 2017-05-05 07:47
I tried with expo and CRNA. same result.

**Comment by gkufera** [comment] 2017-05-06 23:06
Hi @halallahh -- so we can make sure we are on the same page, can you send me a sample of the code you ran in CRNA which failed? Have you tried to run the [audio recording example app](https://github.com/expo/audio-recording-example) on your phone, and what was the result?

Thanks!

**Comment by halallahh** [comment] 2017-05-07 15:41
I just run same code with that example code in CRNA. Yes, I run that example with my phone.

**Comment by gkufera** [comment] 2017-08-16 02:39
Hi @halallahh,

This bug should be fixed in SDK20, since we moved to a more robust backend for AV playback on Android. Please let me know if the bug still exists and we can reopen the issue.

Thanks!

Greg

**Closed by gkufera** 2017-08-16 02:39 UTC
Labels: project: client-android, project: sdk, status: needs more info
