### ISSUE TITLE
TypeError undefined is not an object (evaluating 'Component.propTypes')

### ISSUE THREAD

**Issue by haseebrehmancb** [expo/expo#6880] opened 2020-01-28 13:34 UTC
### Environment

Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.9.0 => 16.9.19 
      @types/react-native: ^0.60.15 => 0.60.31 
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^3.0.9 => 3.3.2 
    npmGlobalPackages:
      expo-cli: 3.11.7

Targeted App : iOS

### Steps to Reproduce

Steps To Reproduce!
Run the following commands
1) expo upgrade (upgrading from expo 35.0.0 to 36.0.0)
2) expo start -c

### Expected Behavior

App should start as fine as it was before upgrading expo

### Actual Behavior

Error screen showing when the app is started.
Error message: "TypeError undefined is not an object (evaluating 'Component.propTypes')"

![Simulator Screen Shot - iPhone 11 - 2020-01-28 at 19 28 06](https://user-images.githubusercontent.com/50589885/73272605-76e14a80-4204-11ea-801d-8e7bf8239bf3.png)

**Comment by cruzach** [comment] 2020-01-28 16:57
Without sharing a project that reproduces this, it's really hard to help

The upgrade to SDK 36 brings with it an upgrade for React (to v 16.9) so maybe you should look through the breaking changes there, or the breaking changes for RN. How are you setting up your prop types? Might be useful to [check this guide](https://reactjs.org/docs/typechecking-with-proptypes.html)

**Comment by Codigo-Fuentes** [comment] 2020-02-01 16:53
exact same issue +1

**Comment by gablabelle** [comment] 2020-02-13 04:18
@cruzach if you clone [this repo](https://github.com/MengTo/react-native-for-designers) and update to latest expo (SDK 36) you will be able to reproduce the error.

**Comment by Roxk-33** [comment] 2020-02-20 14:42
exact same issue +1

**Comment by oldevelopment** [comment] 2020-02-21 16:18
same issue

**Comment by oldevelopment** [comment] 2020-02-21 16:21
running "expo install expo-file-system" fixed it, follow https://docs.expo.io/versions/latest/workflow/upgrading-expo-sdk-walkthrough/

**Comment by laseur** [comment] 2020-02-22 18:15
I had the same issue and to workaround I simply put:

import React, { Component } from 'react';

at the very top of ./node_modules/react-native-gesture-handler/GestureHandler.js

Be aware that this is a temporary solution and I hope the package is fixed soon.

**Comment by cruzach** [comment] 2020-02-24 15:22
@gablabelle that project is on SDK 32, so you'll want to read through the release notes for 33, 34, 35, and 36 to upgrade. We've made quite a few updates since then

This error message is most likely coming from incompatible library versions installed. Make sure that your run `expo install` so that you automatically get the best version for your project

**Comment by laseur** [comment] 2020-02-24 15:34
The problem is the compatibility with the new expo versions. Keeping it in expo 32 / 33 will do the trick. However have a look at the error messages in the console. Some "import { linear-gradient } from "expo" should be replaced for import { LinearGradient } from 'expo-linear-gradient'; etc.

**Comment by cruzach** [comment] 2020-02-24 21:42
Closing this since it's not a bug with the Expo SDK

**Closed by cruzach** 2020-02-24 21:42 UTC
Labels: bug, needs repro, status: needs more info

**Comment by thestoneoflapiz** [comment] 2020-04-04 08:39
I'm having the same problems in sdk34, `expo install` didn't do the trick. Anyone?
