### ISSUE TITLE
IOS Simulator on Mac M1 Chip running very slowly

### ISSUE THREAD

**Issue by max-taylor** [expo/expo#12173] opened 2021-03-09 23:59 UTC
### Do you understand that any Expo CLI issues opened in the core Expo repository will be closed?

Yes

**Comment by max-taylor** [comment] 2021-03-10 00:01
Hi, I've been using Expo the last couple days and developing on an IOS simulator. It was running quite well and I was having no issues, as of the last day that has changed and it is running horribly slow and is mostly unresponsive. When I check the resource monitor I can see the Exponent task is consuming up to 80% of resources at times.

I've uninstalled and reinstalled Expo and Xcode and still having the issue.

Any suggestions would be great. Thanks

**Comment by brentvatne** [comment] 2021-04-13 04:26
hi there! i don't have any suggestions for you. m1 is new and you're going to run into issues when using it with various software. as far as i know this is specific to m1 and out of our control, but if you have more information on the root cause and believe it's something we can influence then we'd be happy to investigate. closing until we have more info

**Closed by brentvatne** 2021-04-13 04:26 UTC
