### ISSUE TITLE
Getting 'Image source "null" doesn't exist' when rendering local images after update to sdk 52 

### ISSUE THREAD

**Issue by LouisMuriuki** [expo/expo#33623] opened 2024-12-12 00:24 UTC
### Minimal reproducible example

https://github.com/LouisMuriuki/sdk52-img-null

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

After updating to sdk 52 from 51
I realised that my local images were not being rendered, I
I can see an error saying image source is null but If i console log them i can clearly see a number representing the images:

LOG [8, 9, 10, 11, 12]
WARN ReactImageView: Image source "null" doesn't exist

My app is a  prebuild bare react native app.
I was initially using  Image component from react native, so i switched to expo-image and got the same result.
I have tried a number of different alternative including adding the images with useAssest, using useImage but to no avail,

I would really like to test Dom components and even use on production :) and this seems to be a barrier.

help would be appreciated.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
      Watchman: 2024.08.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/lui/.gem/ruby/3.3.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.18 => 52.0.18 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
    npmGlobalPackages:
      eas-cli: 14.1.0
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, userInterfaceStyle, splash, ios, android, plugins. 


One or more checks failed, indicating possible issues with the project.
```

**Comment by chrfalch** [comment] 2024-12-18 14:06
Hi, @LouisMuriuki - thanks for submitting the issue. I've tried your reproduction project and it shows the error you describe. I made the test case even simpler and smaller by using the following code in `App.tsx` also showing the same issue:

```tsx
import React from "react";
import { Image, StyleSheet, Text, View } from "react-native";

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>
      <Image
        source={require("./assets/login/image1.png")}
        style={{ width: 250, height: 250 }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

When initializing a new expo project using `npx create-expo-app@lastest` and using the above code + your image - it all works as expected.

I tried adding the following code to the component to see how the assets are resolved:

`console.log("Resolved asset value:", Image.resolveAssetSource(require("./assets/login/image1.png")));`

This results in:

´Resolved asset value: null`

Meaning that the assets aren't packaged correctly in your project

Could it be that your project contains configuration or packages that are no longer necessary or might cause issues like the problem you are seeing? 

I'd try creating a new project with `create-expo-app` and add the packages and code from your project and see if you can find the offending configuration or packages in your project.

Closing this for now since it doesn't look like it is a problem in SDK-52.

**Closed by chrfalch** 2024-12-18 14:06 UTC
Labels: needs review

**Comment by Vadko** [comment] 2025-05-26 22:08
Reason why this repro is unable to resolve images, but blank expo does it without any issues is in tsconfig:

```typescript
"paths": {
  "*": ["ts-declarations/*", "node_modules/*"]
},
```

removing this section makes asset resolution back to normal

**Comment by Vadko** [comment] 2025-05-27 13:47
I’ve encountered the exact same error, but for a different reason—it was related to how @react-native/assets-registry works in monorepos when using the default Metro config with pnpm in hoisted mode.

Specifically, since @react-native/assets-registry is referenced without an absolute path in the default config, it doesn’t work with pnpm if nodeLinker is set to hoisted. To resolve this, @react-native/assets-registry should be included under publicHoistPattern, as mentioned here: https://github.com/expo/expo/issues/26606#issuecomment-2888852642

To fix the issue, assetRegistryPath should also be resolved as an absolute path—currently, everything else is resolved absolutely except for this one.

There is already a pull request that addresses this, but it was unfortunately closed: https://github.com/expo/expo/pull/30368
