### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by dhairyasenjaliya** [expo/expo#11786] opened 2021-01-29 16:10 UTC
**Summary**

 bare workflow in ios not able to use InAppPurchases in ios tried every version of unimodule 
 
"react-native-unimodules": "^0.11.0",

if I comment below line in expo-in-app-purchase->build->InAppPurchases.js
// const eventEmitter = new EventEmitter(ExpoInAppPurchases);
then it will work 

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

 "react": "16.13.1",
  "react-native": "^0.63.2",

ejected bare flow

**Reproducible demo or steps to reproduce from a blank project**
https://github.com/dhairyasenjaliya/InAppPurchaseTest

_No response_

![simulator_screenshot_AB4AC6F6-15A6-42E7-8BDE-4608D80EDFD7](https://user-images.githubusercontent.com/47522946/106298783-59f9b000-627a-11eb-9dd6-270674eb2227.png)

**Comment by pckz** [comment] 2021-01-30 15:58
Same error

After upgrade to Expo SDK 40 (because 39 has a problem with the first launch at SplashScreen) I have the same errors:

1. Invariant Violation: Native module cannot be null.
2. Invariant Violation: "main" has not been registered

:(

**Comment by cruzach** [comment] 2021-02-01 14:53
@dhairyasenjaliya if you can provide a reproducible demo, we can look into this

**Comment by dhairyasenjaliya** [comment] 2021-02-02 05:24
@cruzach here you go I have replicated the project try to run you can easily reproduce the error

**Comment by cruzach** [comment] 2021-02-02 14:27
That project fails to build for me, looks like it's missing font assets, and it has a long list of dependencies in package.json

Please start with a blank project, and reproduce from there

**Comment by picklenick-dev** [comment] 2021-03-04 08:59
Just upgraded to 40 and have the same problem.

**Comment by picklenick-dev** [comment] 2021-03-04 16:51
[bareproject.zip](https://github.com/expo/expo/files/6085278/bareproject.zip)

@cruzach I can reproduce the error in this project. This what I have done:
With the latest version of expo (4.2.1)

 1. expo init my-test-bare
 2. expo install expo-in-app-purchases
 3. Added setPurchaseListener in the App.tsx file
 
 Same error 
 
 Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

If I comment out the line that @dhairyasenjaliya mentions the app starts normally on my iphone (not emulator)

**Comment by picklenick-dev** [comment] 2021-03-11 21:18
No update on this?

I get the error on two separate machines using node 15.11.0 and npm 7.6.2.

**Comment by brg8** [comment] 2021-03-16 12:56
I am having the same problem.

**Comment by cruzach** [comment] 2021-03-16 13:34
I tried following these steps:
```
- expo init my-test-bare
- expo install expo-in-app-purchases
- **npx pod install***
- Imported expo-in-app-purchases in App.tsx and added setPurchaseListener in the App.tsx file.
```

and could not reproduce. Without a reproducible demo, there's very little we can do to help 😞

**Comment by picklenick-dev** [comment] 2021-03-16 13:53
@cruzach I solved the issue, however I don't know what solved the issue really. 

This is what I did.

1. Installed the latest version of Xcode 12.X.X
2. Cleaned all my cache npm and yarn cache. 
3. Deleted yarn.lock and node_modules 
4. Deleted podfile.lock and pods and reinstalled it.
5. Added main: "index.js" to my package.json file
6. In my AppDelegate.m file i changed it to:

  `bridge moduleName:@"main" `
  
I hope this helps anyone with the same issue.

**Comment by brg8** [comment] 2021-03-16 15:38
Trying to trace the problem. Right now I'm seeing this code in the in-app purchase package:

```
import { NativeModulesProxy } from '@unimodules/core';
export default NativeModulesProxy.ExpoInAppPurchases;
```

In my case `NativeModulesProxy.ExpoInAppPurchases` is null. Seems that in-app purchases are not included in my unimodules. Then when the module tries:

```
const eventEmitter = new EventEmitter(ExpoInAppPurchases);
```

That is what throws the exception. I likely am missing an obvious configuration option for unimodules.

**Comment by picklenick-dev** [comment] 2021-03-16 15:49
Yup. I had the same problem. It worked by commenting out that line.

Try all those steps I wrote in my earlier comment.

I would also recommend creating a new project with expo init, add expo-in-app-purchase and then do expo eject.

Compare your AppDelegate and every file and see if there is a difference. After you've done that do a new pod install.

I spent a few days on this....

**Comment by brg8** [comment] 2021-03-16 15:57
Do you happen to have a commit diff that solved it for you?

**Comment by brg8** [comment] 2021-03-16 18:42
@cruzach  I made a minimal repo for reproduction: https://github.com/brg8/expo-in-app-purchases-violation-repro/tree/main. The commands I ran to produce the app are in the readme.

Reproduction Steps:

```
git clone git@github.com:brg8/expo-in-app-purchases-violation-repro.git
cd expo-in-app-purchases-violation-repro/
npm install
npx pod-install
expo start
```

Then load the app on your mobile device. The exception you will initially see is `"main" has not been registered...` etc. The app will run fine on the simulator so make sure to use the Expo Go app on a device.

Comment out this line from App.js

```
import * as InAppPurchases from "expo-in-app-purchases";
```

Then reload the app and everything should work fine. Then uncomment the line and the exception will change to `Native module cannot be null.`

Please let me know if you are able to reproduce. I am a big fan of expo and appreciate the work you guys do.

**Comment by cruzach** [comment] 2021-03-16 18:44
>make sure to use the Expo Go app on a device 

`expo-in-app-purchases` is not supported in Expo Go, that would explain why you're running into this error. As it says in the docs:
> This module is currently only available in the bare workflow.

**Comment by brg8** [comment] 2021-03-16 18:52
@cruzach Thanks!

I suspected this was why, however reading through https://docs.expo.io/bare/using-expo-client/  it was not 100% clear to me if this was why. Since the in-app purchase package is an expo package I thought maybe it was compatible. Good to know that this is the reason.

Reading through https://docs.expo.io/versions/latest/sdk/in-app-purchases/ makes it seem like I will be able to test in-app purchases in development. If the package will only work on the simulator and the simulator doesn't support testing in-app purchases how do you suggest developers test this in development?

**Comment by cruzach** [comment] 2021-03-16 18:54
you will have to test it using a physical device

> If the package will only work on the simulator

What makes you say that it only works on a simulator?

**Comment by brg8** [comment] 2021-03-16 19:00
So it seems the only option here is to build the app through XCode and test on my device via USB? That's fine then. Reading through the expo docs I was under the impression I would not have to do this, thus leading to my confusion. Might I suggest adding a note to https://docs.expo.io/bare/exploring-bare-workflow/ that the three options to run your application are:
- Simulator/Emulator
- Expo Go App
- On your device via USB

Since only the first two are mentioned I excluded the third from being possible.

I was mistaken to say "it only works on a simulator". What I meant was, "it doesn't work on the expo go app".

**Comment by picklenick-dev** [comment] 2021-03-16 19:08
@brg8 I'm glad you recieved help.

@cruzach I ejected around version 37 and my app has worked perfectly for 9 months.

I suspect that some setting to detect if a project is "bare" or "managed" has changed from 39 to 40. After checking the diff between a completly new ejected project and mine I resolved it as I said earlier. However, I'm not completly sure which line of code "did it".

**Comment by cruzach** [comment] 2021-05-03 15:48
Closing since it looks like this has been resolved. Just FYI for anyone finding this later: `Native module cannot be null` is a common error message when a native library has not been linked properly, so that's where you should start your search

**Closed by cruzach** 2021-05-03 15:48 UTC
Labels: Bare Workflow, InAppPurchases, iOS, needs repro, needs review

**Comment by lukewis** [comment] 2021-07-12 02:47
@cruzach would you consider re-opening this?  Prior to SDK 40, we were able to run our app within Expo Go.  Understandably, we can't test in-app-purchases in Expo Go, but we could use Expo Go for all other portions, and then switch to XCode only for testing purchases.  As of SDK 40, we can no longer use Expo Go at all due to the error mentioned (which is a bit hit to productivity).

Using the repro that @brg8 put together, if you switch to using expo v39, the app runs fine, but using SDK 40 (and also 41) it blows up with the mentioned error.
https://github.com/brg8/expo-in-app-purchases-violation-repro/tree/main

**Comment by picklenick-dev** [comment] 2021-07-12 05:41
@lukewis the same applies to me. My app uses SDK 40 and in app purchases works in production on an iphone. However, in order to debug my app in Expo Go I have to comment out the line:

const eventEmitter = new EventEmitter(ExpoInAppPurchases);

It is a small hit to productivity.

**Comment by abelfiore** [comment] 2021-07-12 11:56
This is a big issue for me too. Please reopen - thanks!

**Comment by cruzach** [comment] 2021-07-12 12:50
Since SDK 40, we've allowed for optional imports, so if you're seeing this error then you should wrap your `import * as InAppPurchases from "expo-in-app-purchases";
` in a try/catch

**Comment by lukewis** [comment] 2021-07-14 02:22
Thanks for the tip @cruzach!  Unfortunately I'm still having trouble.  I'm using SDK 41 and have my import as follows:
```
let InAppPurchases: any;
try {
  InAppPurchases = require("expo-in-app-purchases");
} catch {
  console.warn(
    "Unable to load expo-in-app-purchases.  This is expected if running in Expo Go."
  );
}
```

But I still see the same error.  The only way I've been able to run is by commenting out the line that @picklenick-dev mentions above (which is much appreciated, but doesn't feel like a sustainable solution).  Besides SDK 40, are there any other necessary dependencies (specific react/react-native versions, etc)?  I'm currently using
```
"expo": "^41.0.0",
"expo-in-app-purchases": "~10.1.1",
"react": "16.13.1",
"react-native": "0.63.4",
```

**Comment by abelfiore** [comment] 2021-07-17 12:27
@cruzach Can you provide a link or example to a more complete example? I can't seem to get your suggestion to work either. I'm having the same issue as @lukewis.

**Comment by cruzach** [comment] 2021-07-19 13:24
You need to be using an up to date version of `metro` tp have optional imports, which you'll get from using the most recent `expo-cli`

**Comment by lukewis** [comment] 2021-07-20 02:15
Thanks @cruzach .  I updated to expo-cli v4.8.1 and still see the same issue.  The odd thing is if I `expo init` to create a new project, all works as expected.  However, I can't seem to get it to work in my old project.  Any chance you have an old repo lying around you could try upgrading to see if you experience anything similar?  Below is some diagnostic info from both the working and non-working apps.  The only difference is the version spec for react-native, but the package-lock.json files show that both apps are using 0.63.4.  I'll continue comparing the working and non-working apps to see if I can narrow anything else down.

# Working
```
Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: bare
```
# Non-working
```
Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: bare
```

**Comment by picklenick-dev** [comment] 2021-09-04 07:50
I still have the same problem with SDK 42. Were you able to solve it @lukewis?

**Comment by garrett-gottlieb** [comment] 2021-12-30 09:01
Second this - it should still run on simulator without crashing.

**Comment by skriems** [comment] 2022-02-13 08:15
It's quite unfortunate, that a simple import statements breaks DX in such a way. I've managed to use lukewis try/catch approach and also stubbed all functions my code uses
```
let InAppPurchases = {
  connectAsync: () => new Promise<void>(resolve => resolve()),
  disconnectAsync: () => new Promise<void>(resolve => resolve()),
  getProductsAsync: () => new Promise(resolve => resolve({ responseCode: 2, results: [] })),
  ...
};

try {
  InAppPurchases = require("expo-in-app-purchases");
} catch {
  console.warn(
    "Unable to load expo-in-app-purchases.  This is expected if running in Expo Go."
  );
}
```
This way TS is happy and I don't have to mess with my implementation code.

If there's no way to not break DX so badly, I would suggest to put the types in a dedicated package maybe? 🤔  

Anyhow. It seems my Expo Go days are over and I now have to use Xcode :)

**Comment by pckz** [comment] 2022-04-06 15:02
Any news about this issue? :(

**Comment by dragoscv** [comment] 2022-12-17 01:10
`yarn remove expo-in-app-purchases
`
this will fix the problem. the library is deprecated
