### ISSUE TITLE
When using a custom private npm registry expo preuild sends the EXPO_TOKEN value as the authorization

### ISSUE THREAD

**Issue by trajano** [expo/expo#21740] opened 2023-03-17 03:26 UTC
### Summary

have a .npmrc with a custom registry
```
registry=https://myown.com/
```
Then in your ~/.npmrc set your credentials.

Install a package and confirm that itt is using the custom registry by looking at the lock file.

Now run `DEBUG=* npx expo prebuild --no-install --platform ios` 

It will say Unexpected end of JSON

If you modify the client.js file it will show that it is sending the expo token value

### What platform(s) does this occur on?

Android, iOS

### SDK Version

47, 48

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
      Watchman: 2023.03.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 31
        Build Tools: 30.0.2, 31.0.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.3.0
      expo: ~48.0.6 => 48.0.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
      react-native-web: ~0.18.11 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.8.1
    Expo Workflow: bare

### Minimal reproducible example

n/a

**Comment by trajano** [comment] 2023-03-17 03:27
I wrote a lot of what I went through in https://forums.expo.dev/t/eas-local-build-stopped-working-again-only-ios/70222/4

**Comment by brentvatne** [comment] 2023-04-10 22:58
hi there! i'm not quite sure what the cause is here, this is a common use case on EAS Build and appears to work as expected there. if you'd like to dig into it further and send a PR to fix it, that would be much appreciated! I'm going to close this because there is no minimal reproducible example provided and it's unlikely we will investigate this without more information.

**Closed by brentvatne** 2023-04-10 22:58 UTC
Labels: CLI
