### ISSUE TITLE
Push Notifications not sending to device from production

### ISSUE THREAD

**Issue by tknuts** [expo/expo#7270] opened 2020-03-04 11:48 UTC
Any of you experiencing problems sending push notifications via api: https://exp.host/--/api/v2/push/send from Windows Azure hosted services ? 

If I run the exact same code from local debug, it sends fine. But after deploying to Azure serveres, the Worker can not send push messages to the app..

Any ideas ?

**Comment by cruzach** [comment] 2020-03-09 14:49
Closing since this is not a valid bug report, and is a duplicate of https://github.com/expo/expo/issues/7277

**Closed by cruzach** 2020-03-09 14:49 UTC
