### ISSUE TITLE
detached project apk "unable to load script from assets 'index.android.bundle'"

### ISSUE THREAD

**Issue by IElgohary** [expo/expo#2111] opened 2018-08-15 18:52 UTC
### Environment
  OS: macOS High Sierra 10.13.6
  Node: 8.3.0
  Yarn: 1.3.2
  npm: 6.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^27.0.0 => 27.1.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Target: ExpoKit Android

### Steps to Reproduce
1. detach the app.
2. publish the app on expo.
3. create a signed apk using gradlew or android studio.
4. install the apk on a device

### Expected Behavior
The app should show the splash screen in production 

### Actual Behavior
In development, the app works fine, however in production, a blue screen appears the first time I open the app with the message "unable to load script from assets 'index.android.bundle'" but when I close the app and open it again, the message disappears and the app works properly.
![screenshot_20180815-205055](https://user-images.githubusercontent.com/15884858/44166973-1bcd9d80-a0cd-11e8-8426-a94cc0998329.png)

## sorry but I'm unable to reproduce the issue on another project

**Comment by sjchmiela** [comment] 2018-08-16 06:47
Hi @IElgohary!

Have you by any change upgraded Gradle plugin to version 3 recently? This could make this bug appear. 🤔 

To fix it, please open the `expo.gradle` file in `projectDir/android`, backup the content somewhere (if my workaround doesn't help) and try to replace with https://gist.github.com/sjchmiela/c73b16008d886f2f55308c7e495479f7.

Let me know if it helps! 🙂

**Comment by IElgohary** [comment] 2018-08-16 07:45
@sjchmiela thanks for your help 😊 I tried that but still the same issue happens 😕

**Comment by sjchmiela** [comment] 2018-08-16 07:48
Hm, and if you unzip the APK, what files does it contain in the `assets` folder?

**Comment by IElgohary** [comment] 2018-08-16 08:17
<img width="260" alt="screen shot 2018-08-16 at 10 16 31" src="https://user-images.githubusercontent.com/15884858/44196892-7f8faf00-a13d-11e8-969c-ff7dd1a3f081.png">

**Comment by sjchmiela** [comment] 2018-08-23 07:48
Hi @simb4!

I see CRNA ejects to ExpoKit v27 which didn't require `expokit` NPM dependency. 🙂 Please try using `expo-pre29.gradle` contents for `expo.gradle`.

@IElgohary I wasn't able to reproduce this issue, maybe you could create another plain project and detach there and see what's different in your project and the newly created, working one?

**Comment by simb4** [comment] 2018-08-23 11:33
Actually, I found `detached-scripts ` at `android` folder, so I changed the path to there and it worked! 
Thank you!

**Comment by sjchmiela** [comment] 2018-10-11 10:47
I'm glad everything looks like it should work for everybody! Closing this issue tentatively, if anything comes up again, please file a new issue! 🙂

**Closed by sjchmiela** 2018-10-11 10:47 UTC

**Comment by BlazJurisic** [comment] 2018-10-24 14:10
I have tried @sjchmiela 's fix and issue is still present.

**Comment by sjchmiela** [comment] 2018-10-24 14:21
Hey, @BlazJurisic, could you please submit a new issue describing your problem in detail? 🙂

**Comment by BlazJurisic** [comment] 2018-10-24 18:04
@sjchmiela  https://github.com/expo/expo/issues/2499
