### ISSUE TITLE
Permission.askAsync crashed on the Android phone.

### ISSUE THREAD

**Issue by Shing-Ho** [expo/expo#11060] opened 2020-11-17 01:54 UTC
### Summary of Issue 
In the Android phone, after I call `Permissions.askAsync()` it crashed on Android. Crashes means the app is closing immediately after I click allow button.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.3/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.16 => 0.12.29 
      expo: ^38.0.0 => 38.0.10 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.3.9 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed

  Galaxy S10+
  Android Version 10

### Reproducible Demo

```
  React.useEffect(() => {
    requestPermissions();
  }, [requestPermissions]);

 const requestPermissions = React.useCallback(async () => {
    try{
      const result = await Permissions.askAsync(
        Permissions.CAMERA, Permissions.CAMERA_ROLL
      )
      debug && console.log('RESULT>>>>>>>>>>>> ', result)
    } catch(e) {
      console.log('e', e)
    }
  }, []);
```

### Expected Behavior vs Actual Behavior

It should not crash the app

**Comment by Shing-Ho** [comment] 2020-11-17 01:55
@brentvatne Could you check this issue please?

**Comment by brentvatne** [comment] 2020-11-17 01:56
please provide a mcve: https://stackoverflow.com/help/minimal-reproducible-example

you can put it on https://snack.expo.io or share a github repo

**Comment by brentvatne** [comment] 2020-11-17 01:57
also, you're not using the latest version of the expo sdk. we include a lot of bugfixes and improvements in each release, so you might want to consider upgrading to sdk 39

**Comment by Shing-Ho** [comment] 2020-11-17 01:58
It's private repo so hard to share you, And for upgrade from 38 to 39, is there any good docs for upgrade it without any problem?

**Comment by brentvatne** [comment] 2020-11-17 01:58
my friend, i do not want to access your application. i want a *minimal reproducible example* - please read https://stackoverflow.com/help/minimal-reproducible-example and follow the instructions.

**Comment by cruzach** [comment] 2020-11-17 18:34
@Shing-Ho here's an example snack of `expo-camera`, it works on Android 10 for me (both SDK 38 and 39), so hopefully that will help you to debug your code - https://snack.expo.io/@charliecruzan/basic-camera-usage

Closing this for now since it doesn't look like a bug in the Expo SDK

**Closed by cruzach** 2020-11-17 18:34 UTC
Labels: Issue needs review
