### ISSUE TITLE
Styles as array not working 

### ISSUE THREAD

**Issue by NewCoder2023** [expo/expo#33730] opened 2024-12-17 23:51 UTC
### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

Changing: <Pressable style={styles.element}>to  <Pressable style={[styles.element, {backgroundColor: category.backgroundColor}]}> makes the styles.element stop working. Also (I know this should be a separate issue but I'm still a junior and I find it hard to create a reproducible example but I think in iOS the bottom tab bar in expo router isn't recognized as a border. Items go underneath which causes them not be centered via flexBox. In Android it works. This causes much more usage of margin in IOS then in Android

`<Pressable style={styles.element}>`

to  

`<Pressable style={[styles.element, {backgroundColor: category.backgroundColor}]}>`

makes the styles.element stop working.

```javascript
import React from "react";
import { StyleSheet } from "react-native";
import { ThemedView } from "./ThemedView";
import { ThemedText } from "./ThemedText";
import { Link } from "expo-router";
import { Pressable } from "react-native";
import { Image } from "expo-image";
import { useColorScheme } from "react-native";
import { coustomTheme } from "./coustomTheme";
import { SafeAreaView } from "react-native-safe-area-context";
import { View, Text } from "react-native";

export default function QuestionLinksFirst() {
  const colorScheme = useColorScheme();
  const themeStyles = coustomTheme();

  const categories = [
    {
      name: "Rechtsfragen",
      image: require("@/assets/images/rechtsfragen.png"),
      backgroundColor: "red",
    },
    {
      name: "Quran",
      image: require("@/assets/images/quran.png"),
      backgroundColor: "blue",
    },
    {
      name: "Historie",
      image: require("@/assets/images/historie.png"),
      backgroundColor: "green",
    },
    {
      name: "Glaubensfragen",
      image: require("@/assets/images/glaubensfragen.png"),
      backgroundColor: "yellow",
    },
  ];

  return (
    <>
      {categories.map((category, index) => (
        <Link
          key={index}
          href={
            {
              pathname: category.path,
              params: {
                category: category.name,
              },
            } as any
          }
          asChild
        >
          <Pressable style={[styles.element, { backgroundColor: category.backgroundColor }]}>
            {category.name}
          </Pressable>
        </Link>
      ))}
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignContent: "center",
    gap: 20,
  },

  element: {
    flexDirection: "column",
    gap: 10,
    justifyContent: "center",
    alignItems: "center",
    width: "45%",
    height: "30%",
    borderRadius: 30,
  },

  elementIcon: {
    width: "80%",
    height: "auto",
    aspectRatio: 1.5,
    alignSelf: "center",
  },

  elementText: {
    fontSize: 15,
    fontWeight: "bold",
    padding: 5,
    textAlign: "center",
    paddingHorizontal: 5,
  },
});


### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.3.0 - /opt/homebrew/bin/node
      npm: 11.0.0 - ~/.npm-global/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.19 => 52.0.19 
      expo-router: ~4.0.13 => 4.0.13 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 14.1.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by chrfalch** [comment] 2024-12-18 14:30
Hi, @NewCoder2023  - please provide a small and working example, a small GitHub project created with `npx create-expo-app` would be helpful next time. 

I managed to test the example in a new expo project and could not reproduce any issues. Some screenshots or images would also be great for us when trying to help.

This is the code I tested:

```tsx
import React from "react";
import { StyleSheet } from "react-native";
import { Pressable } from "react-native";
import { useColorScheme } from "react-native";
import { View, Text } from "react-native";

export default function QuestionLinksFirst() {
  const categories = [
    {
      name: "Rechtsfragen",
      backgroundColor: "red",
    },
    {
      name: "Quran",
      backgroundColor: "blue",
    },
  ];

  return (
    <>
      {categories.map((category, index) => (
        <Pressable
          key={index}
          style={[
            styles.element,
            { backgroundColor: category.backgroundColor },
          ]}
        >
          <Text>{category.name}</Text>
        </Pressable>
      ))}
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignContent: "center",
    gap: 20,
  },

  element: {
    flexDirection: "column",
    gap: 10,
    justifyContent: "center",
    alignItems: "center",
    width: "45%",
    height: "30%",
    borderRadius: 30,
  },
});
```

Using the array notation for styles worked well and gave the following results:

<img width="233" alt="image" src="https://github.com/user-attachments/assets/b8e0526e-890d-4091-822b-ae70eb159d53" />

I'll close this issue for now, please feel free to comment or create a new issue any time.

**Closed by chrfalch** 2024-12-18 14:30 UTC
Labels: needs review
