### ISSUE TITLE
How to handle Gitlab-CI and expo build/publish ?

### ISSUE THREAD

**Issue by kopax** [expo/expo#6639] opened 2019-12-30 04:48 UTC
I work on a react-native application that I am building with expo SDK36.

I want to `build` and `publish` within a Gitlab-CI but it fail, this is how my `.gitlab-ci.yml` job look like:

```yaml
staging-native:
  stage: publish
  script:
    - npm i
    - npm run build:android:staging -- --no-wait || echo skipping
    - npm run build:ios:staging -- --no-wait || echo skipping
    - npm run publish:staging || echo skipping
  only:
    - tags
  tags:
    - docker
```

This is what I am trying:

```javascript
$ npm run build:android:staging -- --no-wait || echo skipping

> @freeland/app-test-native@1.0.11 prebuild:android:staging /mnt/mesos/sandbox/builds/freeland/app-test-native
> npm run expo:login


> @freeland/app-test-native@1.0.11 expo:login /mnt/mesos/sandbox/builds/freeland/app-test-native
> if test $CI; then expo login --non-interactive -u "${EXPO_CLI_USER}"; fi


Success. You are now logged in as freeland.

> @freeland/app-test-native@1.0.11 build:android:staging /mnt/mesos/sandbox/builds/freeland/app-test-native
> expo build:android --release-channel staging --non-interactive "--no-wait"

- Making sure project is set up correctly...
[04:20:26] Checking if there is a build in progress...

[04:20:27] Unable to find an existing Expo CLI instance for this directory, starting a new one...
[04:20:38] Starting Metro Bundler on port 19001.
[04:20:44] Tunnel ready.
[04:20:44] Publishing to channel 'staging'...
[04:20:45] Building iOS bundle
[04:26:32] Building Android bundle
[04:26:32] Finished building JavaScript bundle in 18371ms.
[04:26:45] Analyzing assets
[04:26:45] Finished building JavaScript bundle in 13139ms.
[04:26:46] Finished building JavaScript bundle in 1127ms.
[04:26:47] Finished building JavaScript bundle in 1240ms.
[04:26:47] Uploading assets
[04:26:48] No assets changed, skipped.
[04:26:48] Processing asset bundle patterns:
[04:26:48] - /mnt/mesos/sandbox/builds/freeland/app-test-native/assets/*
[04:26:48] Uploading JavaScript bundles
[04:26:50] Published
[04:26:50] Your URL is

https://exp.host/@freeland/app-test-native?release-channel=staging

[04:26:50] › Closing Expo server
[04:26:50] › Stopping Metro bundler
Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @freeland/app-test-native@1.0.11 build:android:staging: `expo build:android --release-channel staging --non-interactive "--no-wait"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @freeland/app-test-native@1.0.11 build:android:staging script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-30T04_26_50_356Z-debug.log
skipping
$ npm run build:ios:staging -- --no-wait || echo skipping

> @freeland/app-test-native@1.0.11 prebuild:ios:staging /mnt/mesos/sandbox/builds/freeland/app-test-native
> npm run expo:login


> @freeland/app-test-native@1.0.11 expo:login /mnt/mesos/sandbox/builds/freeland/app-test-native
> if test $CI; then expo login --non-interactive -u "${EXPO_CLI_USER}"; fi


Success. You are now logged in as freeland.

> @freeland/app-test-native@1.0.11 build:ios:staging /mnt/mesos/sandbox/builds/freeland/app-test-native
> expo build:ios --apple-id "${EXPO_APPLE_ID}" --release-channel staging -t simulator --non-interactive "--no-wait"

- Making sure project is set up correctly...
[04:26:58] Checking if there is a build in progress...

[04:26:58] Unable to find an existing Expo CLI instance for this directory, starting a new one...
Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @freeland/app-test-native@1.0.11 build:ios:staging: `expo build:ios --apple-id "${EXPO_APPLE_ID}" --release-channel staging -t simulator --non-interactive "--no-wait"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @freeland/app-test-native@1.0.11 build:ios:staging script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-30T04_26_59_785Z-debug.log
skipping
$ npm run publish:staging -- --no-wait || echo skipping

> @freeland/app-test-native@1.0.11 prepublish:staging /mnt/mesos/sandbox/builds/freeland/app-test-native
> npm run expo:login


> @freeland/app-test-native@1.0.11 expo:login /mnt/mesos/sandbox/builds/freeland/app-test-native
> if test $CI; then expo login --non-interactive -u "${EXPO_CLI_USER}"; fi


Success. You are now logged in as freeland.

> @freeland/app-test-native@1.0.11 publish:staging /mnt/mesos/sandbox/builds/freeland/app-test-native
> expo publish --release-channel staging --non-interactive "--no-wait"


  error: unknown option `--no-wait'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @freeland/app-test-native@1.0.11 publish:staging: `expo publish --release-channel staging --non-interactive "--no-wait"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @freeland/app-test-native@1.0.11 publish:staging script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-30T04_27_04_374Z-debug.log
skipping
Job succeeded
```

I expected them to pass. Perhaps I am not doing the right way, how do you people `build` and `publish` a expo project on Gitlab-CI?

**Comment by cruzach** [comment] 2019-12-30 22:00
Hi again @kopax! We have a couple docs pages on this topic, checkout [publishing on CI](https://docs.expo.io/versions/latest/guides/setting-up-continuous-integration/#publish-new-builds) (there's a gitlab-ci example there) and [building apps on your CI](https://docs.expo.io/versions/latest/distribution/turtle-cli/). It looks like your passing some incompatible flags in your example

Closing this since it's not a bug with Expo- we prefer questions like this to be posted on our [forums](https://forums.expo.io/) 😄

**Closed by cruzach** 2019-12-30 22:00 UTC

**Comment by kopax** [comment] 2019-12-30 22:51
Hi @cruzach and thanks for your reply. Just to inform you that I am still not able to run expo within CI properly despite I have read all of your links multiple time.

This could also have helped: https://blog.expo.io/new-automation-features-in-expo-cli-7a901afcc1bc

In fact, none of them did. What I can produce locally can't be produce within Gitlab-CI and it seems the issue is due to metro being necessary to start and shutdown gracefully during `expo publish` and `expo build:android/ios` .

I really wished I can get a continuous delivery process with expo, is there anything I can configure besind `fs.inotify.max_user_watches = 524288` to get the same stability as in `localhost`?

**Comment by kopax** [comment] 2019-12-31 01:39
I solved it by doing a background process with  `expo start &`  before running the build, my job look like this: 

```yaml
# Publish expo
staging-native:
  stage: publish-native
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-staging"
    paths:
      - icimatin-${CI_BUILD_TAG}-staging.apk
      - icimatin-${CI_BUILD_TAG}-staging.ipa
    expire_in: 1 week
  script:
    - npm i
    - npx expo start &
    - EXPO_PID=$(echo $!)
    - expo build:ios --release-channel staging --non-interactive
    - expo build:android --release-channel staging --non-interactive
    - expo publish --release-channel staging -- --max-workers 1 --non-interactive
    - curl -o myapp-${CI_BUILD_TAG}-staging.apk "$(npx expo url:apk --non-interactive)" || echo skip
    - curl -o myapp-${CI_BUILD_TAG}-staging.ipa "$(npx expo url:ipa --non-interactive)" || echo skip
    - kill -9 $EXPO_PID
  only:
    - tags
  tags:
    - docker
```

**Comment by luizjr** [comment] 2020-01-05 00:41
> I solved it by doing a background process with `expo start &` before running the build, my job look like this:
> 
> ```yaml
> # Publish expo
> staging-native:
>   stage: publish-native
>   artifacts:
>     name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-staging"
>     paths:
>       - icimatin-${CI_BUILD_TAG}-staging.apk
>       - icimatin-${CI_BUILD_TAG}-staging.ipa
>     expire_in: 1 week
>   script:
>     - npm i
>     - npx expo start &
>     - EXPO_PID=$(echo $!)
>     - expo build:ios --release-channel staging --non-interactive
>     - expo build:android --release-channel staging --non-interactive
>     - expo publish --release-channel staging -- --max-workers 1 --non-interactive
>     - curl -o myapp-${CI_BUILD_TAG}-staging.apk "$(npx expo url:apk --non-interactive)" || echo skip
>     - curl -o myapp-${CI_BUILD_TAG}-staging.ipa "$(npx expo url:ipa --non-interactive)" || echo skip
>     - kill -9 $EXPO_PID
>   only:
>     - tags
>   tags:
>     - docker
> ```

is there any way to get the link to the android bundle AAB file?

Example:
**

> npx expo url: aab --non-interactive

**

**Comment by kopax** [comment] 2020-01-05 22:57
I do not get your question. What do you mean?

**Comment by luizjr** [comment] 2020-01-05 23:39
> I do not get your question. What do you mean?

Android App Bundle (expo build:android -t app-bundle). App bundles are recommended.
[https://docs.expo.io/versions/latest/distribution/building-standalone-apps/](https://docs.expo.io/versions/latest/distribution/building-standalone-apps/)

Android App Bundle(.aab) reduces final APK distribuited by Play Store.
You can run this command to see the result:
```sh
expo build:android -t app-bundle
```

**Comment by croossin** [comment] 2020-04-24 02:39
What about the upload portion to iTunes for TestFlights?

**Comment by dacevedo12** [comment] 2020-04-24 17:31
I'm having the exact same error and the suggested solution (expo start) seems hackish.
expo-cli used to work well with Gitlab CI before. Shouldn't this issue be reopened?

**Comment by thexa4** [comment] 2020-07-17 12:18
Expo seems to have an (undocumented?) dependency on `/bin/ps`. It's not an essential package in Debian and derivatives (like Ubuntu) so if you are using a minimal docker image expo won't be able to run `ps` and will die.

You can make it work by installing the `procps` package in your ci script:

    apt-get update --quiet
    DEBIAN_FRONTEND=noninteractive apt-get --yes install procps

The workaround mentioned works because the `ps` command is only used during cleanup and by killing it with `kill -9` you won't actually run the cleanup.
