### ISSUE TITLE
Pressable elements not working on native android devices (with new arch)

### ISSUE THREAD

**Issue by DrZoidberg09** [expo/expo#30032] opened 2024-06-26 21:03 UTC
### Minimal reproducible example

https://github.com/DrZoidberg09/RN-Android-Touch-Issue/

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

With newest Expo SDK 51 and new arch enabled, pressable elements dont work under native android. Please see here: https://github.com/facebook/react-native/issues/44643

Basically everything pressable is acting strange in an stack in expo router. In the header onPress does not work, onPressIn and onPressOut does work.

In the screen its acting completely strange, especially if a proper apk is used instead of expo prebuild.

Actually, expo router with new arch is completely not usable under android.

btw: tested with Samsung devices

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.3 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - ~/tmp/node_modules/.bin/yarn
      npm: 10.8.1 - /opt/homebrew/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 8.0.0
    Expo Workflow: bare

**Comment by DrZoidberg09** [comment] 2024-06-28 12:18
I checked further and the issue comes from native-stack. With react navigation stack it works fine, with native-stack this issue happens. 

And as Expo Router wrapps react naviagtion native-stack, it appears in Expo router.

**Comment by marklawlor** [comment] 2024-07-01 20:30
Closing this issue in favour of tracking it under the React Navigation / React Native Screens repos.

As stated, Expo Router is built ontop of these libraries. Once the issue is fixed in upstream packages it will be fixed in Expo Router

**Closed by marklawlor** 2024-07-01 20:30 UTC
Labels: needs review, Router

**Comment by kriit24** [comment] 2024-12-05 05:20
same thing with ios [https://github.com/expo/expo/issues/32927](https://github.com/expo/expo/issues/32927)
