### ISSUE TITLE
Turn on debug mode and the console reports an Error

### ISSUE THREAD

**Issue by AKclown** [expo/expo#11689] opened 2021-01-20 07:36 UTC
question：
    When I turn on the debug mode, the console reports an Error  And sometimes it gets stuck；

The console reports an error as shown below：
![image](https://user-images.githubusercontent.com/33648653/105142138-2bbaf880-5b35-11eb-9f7f-5ac2d3077c34.png)

What causes it to report an error, and how to solve it?

**Comment by cruzach** [comment] 2021-01-20 21:38
hi! this is actually an upstream react-native issue: facebook/react-native#28844 (since we use react-native's built in debugging, any issues there also occur in expo projects). Closing this since it's not a bug with Expo. Sidenote- I think i've run into this and although it's an ugly log, I was still able to continue on in debug mode, not sure if that's the case for you

**Closed by cruzach** 2021-01-20 21:38 UTC
