### ISSUE TITLE
[expo-camera] - Barcode Scanning with Camera2Api not working (Android)

### ISSUE THREAD

**Issue by wieckowskimateusz** [expo/expo#25545] opened 2023-11-23 09:11 UTC
### Minimal reproducible example

https://snack.expo.dev/@mateusz_tarotanalytics/barcodescanner-not-working-with-camera2api-

### Summary

Hey, we are during rewriting a project. Barcode/QR Code scanning not working with camera2Api on Android. Scanning barcodes with manual focus is the one of the most important features in the our (speeds up scanning).

In old project which is based on different libraries version everything works perfectly. 
With the newest expo, expo-camera and expo-barcode-scanner not working.  

**Old project env:**
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
      Watchman: 2023.09.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.2 
      expo: ~47.0.14 => 47.0.14 
      metro: ^0.72.3 => 0.72.4 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
      react-native-web: ~0.18.7 => 0.18.12 
      react-navigation: ^4.4.4 => 4.4.4
      expo-barcode-scanner": ~12.1.0
      expo-camera": "~13.1.0
     npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
      Watchman: 2023.09.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: bare

ALSO:
    "expo-barcode-scanner": "~12.5.3",
    "expo-camera": "~13.4.4",

**Comment by maxphillipsdev** [comment] 2023-11-24 00:18
@wieckowskimateusz I tried reproducing the issue with the example. Even with Camera2Api Enabled I was able to scan a QR code. I had to play with the focus depth slider a bit to get the code in focus but once it was the scanning worked as expected. I used an iPhone 12 mini on iOS v17.2

**Comment by hbriese** [comment] 2023-11-24 01:14
This is a duplicate of #18996

**Comment by hbriese** [comment] 2023-11-24 01:15
> @wieckowskimateusz I tried reproducing the issue with the example. Even with Camera2Api Enabled I was able to scan a QR code. I had to play with the focus depth slider a bit to get the code in focus but once it was the scanning worked as expected. I used an iPhone 12 mini on iOS v17.2

This bug only occurs on Android

**Comment by wieckowskimateusz** [comment] 2023-11-24 07:48
> This is a duplicate of #18996

In my case app not crashing, just not working. Tested on Android versions: 9, 13 and 14.

**Comment by maxphillipsdev** [comment] 2023-11-24 07:56
@hbriese @wieckowskimateusz My bad, I missed the bit about it being android only. I tried again on android this time and it was not working for me as well. Does sound like a duplicate of the other issue.

**Comment by wieckowskimateusz** [comment] 2023-11-24 08:02
> @hbriese @wieckowskimateusz My bad, I missed the bit about it being android only. I tried again on android this time and it was not working for me as well. Does sound like a duplicate of the other issue.

This is a bit annoying, we have been using this feature for several years and from time to time it stops working in some versions

**Comment by Estevete** [comment] 2023-11-30 11:27
Same issue here 👍

**Comment by arturwitkowski-ps** [comment] 2023-12-07 07:47
I've got the same issue, any news about it?

**Comment by lukmccall** [comment] 2024-05-15 12:40
We have recently introduced a new version of the camera ([read more)](https://expo.dev/changelog/2024/05-07-sdk-51#next-camera-and-sqlite-apis-are-now-the-defaults), and we will no longer maintain the old version. It appears that the new implementation has already resolved your issue! However, please feel free to open a new issue if you encounter a similar problem with our new implementation.

**Closed by lukmccall** 2024-05-15 12:40 UTC
Labels: Issue accepted
