### ISSUE TITLE
Expo camera recording black for a split second

### ISSUE THREAD

**Issue by Luke20w** [expo/expo#18202] opened 2022-07-12 11:30 UTC
### Summary

I’ve noticed an issue with expo-camera where it will record black for a split second at the beginning of every clip.

I’ve seen this issue posted elsewhere but no-one has been able to give any solutions or provide reproducible examples so I created a simple snack to reproduce it here https://snack.expo.dev/_gU35_IWk. You can record a video and you’ll see that recorded video play back as soon as you stop recording. From my testing on an iPhone 12 Pro Max, it shows a split second of black at the beginning of every clip.

Has anyone been able to record videos without this black flash? It seems like it would be a pretty important issue for the expo team to focus on if it’s actually an issue with the package rather than my implementation. The workaround I can think of would be to chop off the first few frames of every recorded video but obviously that’s not ideal. I’m also willing to help fix the issue if anyone would like to point me in the direction of where to start looking for the problem

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### Environment

System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 17.4.0 - /usr/local/bin/node
      npm: 8.12.1 - ~/Desktop/Projects/CrowdClips-Project/CrowdClips/mobile/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.4 
      react: ^17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.4.11
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/_gU35_IWk

**Comment by brentvatne** [comment] 2022-07-12 22:38
Duplicate of https://github.com/expo/expo/issues/1057

**Closed by brentvatne** 2022-07-12 22:38 UTC
Labels: needs review
