### ISSUE TITLE
Unable to use tunnelling with local expo-cli

### ISSUE THREAD

**Issue by notlamc** [expo/expo#19567] opened 2022-10-16 07:37 UTC
### Summary

I'm attempting to migrate from using global expo-cli to local, I like the idea that projects contain all the tooling they need. I've always hated the idea of global packages.

The project I am having problems with is running on WSL2, so I can't access the app on my mobile device without using tunnelling.

Global expo-cli allowed me to do `expo start --dev-client --tunnel` -- This works fine

However, when running `npx expo start --dev-client --tunnel` I get the following error and the project doesn't start:

`Failed to resolve the Android SDK path. Default install location not found: /home/craig/Android/sdk. Use ANDROID_HOME to set the Android SDK location.
Failed to resolve the Android SDK path. Default install location not found: /home/craig/Android/sdk. Use ANDROID_HOME to set the Android SDK location.
Error: spawn adb ENOENT
Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`

If I revert to the old global expo-cli, this doesn't happen but that defeats the purpose of migrating.

### What platform(s) does this occur on?

Windows 11 with WSL2

### SDK Version

46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    npmPackages:
      expo: ~46.0.9 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.4.0
    Expo Workflow: managed

### Minimal reproducible example

npx expo start --dev-client --tunnel

**Comment by gabrieldonadel** [comment] 2022-10-16 22:06
@notlamc have you tried running `echo $ANDROID_HOME` on WSL2 to check if that variable is set?

**Comment by notlamc** [comment] 2022-10-17 07:47
Consider the following two commands. The only difference between them is the addition of the `--tunnel` flag.

1ST COMMAND:
➜  test-app-mobile-app git:(master) ✗ npx expo start --dev-client         
Starting project at /home/craig/repos/test-app-mobile-app
Starting Metro Bundler

QR CODE HERE

› Metro waiting on exp+test-app-mobile-app://expo-development-client/?url=http%3A%2F%2F172.24.173.22%3A8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Press a │ open Android
› Press w │ open web

› Press r │ reload app
› Press m │ toggle menu

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
› Stopped server

2ND COMAND:
➜  test-app-mobile-app git:(master) ✗ npx expo start --dev-client --tunnel
Starting project at /home/craig/repos/test-app-mobile-app
Starting Metro Bundler
Failed to resolve the Android SDK path. Default install location not found: /home/craig/Android/sdk. Use ANDROID_HOME to set the Android SDK location.
Failed to resolve the Android SDK path. Default install location not found: /home/craig/Android/sdk. Use ANDROID_HOME to set the Android SDK location.
Error: spawn adb ENOENT
Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by RSchneider94** [comment] 2022-10-31 15:47
Any news here? still not able to run in tunnel.

**Comment by Eddielin0926** [comment] 2022-11-24 13:56
I have the same issue with the local expo! In addition, my global expo can not open the tunnel either.
```
Error starting ngrok: Starting tunnels timed out
Tunnel URL not found (it might not be ready yet), falling back to LAN URL.
```
By the way, is it necessary that wsl2 also needs to install Android SDK?

**Comment by aleqsio** [comment] 2022-11-24 14:06
@notlamc This PR should fix the original issue, could you try this again on the current version
https://github.com/expo/expo/pull/19593

While you shouldn't need to for the tunnel feature, you can set up the Android SDK on WSL2 for other platform specific features.

This seems to be a possible way to do that:
https://javascript.plainenglish.io/how-to-set-up-react-native-on-your-wsl2-for-android-development-a09ee37bf628

**Comment by aleqsio** [comment] 2022-11-24 14:13
@Eddielin0926 Thanks for reporting the issue! It's hard to offer better support on errors reported by ngrok - it can be caused by a variety of issues.

Can you please check if ngrok itself is working for you in WSL2 by exposing a test port?

Closing for now as I don't think it's related to the original issue, but happy to take a look if you're able to provide more details.

**Closed by aleqsio** 2022-11-24 14:13 UTC
Labels: needs review, CLI
