### ISSUE TITLE
From August 2020, new apps must target at least Android 10 (API level 29)

### ISSUE THREAD

**Issue by sa1dai** [expo/expo#9411] opened 2020-07-27 05:50 UTC
## 🐛 Bug Report

Google starts to send this message while uploading app to google play:
![Screenshot_2020-07-23_14-10-30 (1)](https://user-images.githubusercontent.com/47157550/88507036-23e62580-cfe4-11ea-83ca-a7e3da19b79b.png)

There are multiple threads about this on expo forum:
https://forums.expo.io/t/from-august-2020-new-apps-must-target-at-least-android-10/40699
https://forums.expo.io/t/anforderungen-an-die-ziel-api-ebene-ab-august-2020/40827

Google [documentation](https://support.google.com/googleplay/android-developer/answer/113469#targetsdk) says that 'From August 2020' means 'August 3, 2020':

<img src='https://i.ibb.co/TK7c7DY/screenshot-418.png'  height='500'/>
 
### Steps to Reproduce

1. `expo build:android`
2. upload bundle to google play

### Expected Behavior vs Actual Behavior

No message occure vs warning

**Comment by tsapeta** [comment] 2020-07-27 07:32
I'm closing it because it's a duplicate of #8469 — we're aware of this issue and are working on it right now.

**Closed by tsapeta** 2020-07-27 07:32 UTC
Labels: Issue needs review
