### ISSUE TITLE
iosDisplayInForeground preventing the listener to fire

### ISSUE THREAD

**Issue by YahiaBadr** [expo/expo#7863] opened 2020-04-16 12:55 UTC
### Environment

Running on IOS
Expo SDK 37

### Steps to Reproduce

`expo init`
add `{"notification":"iosDisplayInForeground":true}` in `app.json`
then the notification is not catches in the Notification Listerner while running the app on IOS.

### Expected Behavior

i expected that the listener function will fire however it didn't.

**Comment by byCedric** [comment] 2020-04-16 13:41
Hi @YahiaBadr. The `iosDisplayInForeground` only affects if the notifications from the app are shown when the app is in the foreground. If I understand it correctly, the notification is displayed but the notification listeners are not triggered. Unfortunately, without a repro or more information I'm not sure where the problem could be. The only thing I can suggest is [trying the solution from Cruzan on our forum](https://forums.expo.io/t/handle-ios-push-notification-when-in-foreground/19828/6).

Hope it helps!

**Comment by YahiaBadr** [comment] 2020-04-18 11:30
@byCedric yes you understood it correctly. But i didn't get it from the snack. I will try to make a repo and post its link here.

**Comment by cruzach** [comment] 2020-07-09 14:33
Hey @YahiaBadr - I was able to reproduce this issue myself on SDK 37, thanks for bringing it up! This has been resolved with the new `expo-notifications` module, since you now handle whether or not the notification displays while the app is foregrounded with [`setNotificationHandler`](https://docs.expo.io/versions/latest/sdk/notifications/#setnotificationhandlerhandler-notificationhandler--null-void)

If you can't upgrade to SDK 38 to use the new module yet, then you can workaround this issue until you do upgrade by providing `"_iosDisplayInForeground":"true"` with your notifications, which will achieve the same effect as the app.json key, except the listener **will** fire 👍 You can test that with [this snack i made](https://snack.expo.io/@charliecruzan/push-notifications-legacy) and send a notification using terminal with:
```
curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '{
  "to": "ExponentPushToken[XXXXXX]",
  "title":"hello", "body": "world", "_iosDisplayInForeground":"true"
}'
```
and the notification was displayed, and the listener fired.

**Closed by cruzach** 2020-07-09 14:33 UTC
Labels: Notifications, iOS, needs repro
