### ISSUE TITLE
[Expo-Notifications][IOS] ExpoPushToken not regenerating new one after reinstallation

### ISSUE THREAD

**Issue by Silavin** [expo/expo#11605] opened 2021-01-12 10:44 UTC
### Summary of Issue 
For some reason, only on the IOS, the expo push token is not regenerating a new one after I deleted the app and reinstalled. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 4.0.16 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.9 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 26, 27, 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.16
    Expo Workflow: bare

### Reproducible Demo

This is the function I used to create the expo push token.

`registerForPushNotificationsAsync = () => async (dispatch, getState, others) => {
	const { expo } = config;

	const { authentication: { credentials: { accessToken } = {} } = {} } = getState();
	if (!accessToken) {
		return '';
	}

	const existingStatus = await allowsNotificationsAsync(dispatch);

	let finalStatus = existingStatus;
	if (!existingStatus) {
		finalStatus = await requestNotificationPermissionAsync(dispatch);
	}

	if (!finalStatus) {
		return '';
	}

	let experienceId = Constants.manifest.id
	if (!Constants.manifest.id) {
		// Absence of the manifest means we're in bare workflow
		// experienceId = '@username/example';
		experienceId = `@my-technologies/${expo.slug}`;
	}
	const development = expo.slug !== 'production';

	const token = await Notifications.getExpoPushTokenAsync({ development, experienceId: experienceId });

	if (token !== null) {
		console.log('Saving Push Token To The Backend');
		try {
			console.log('Succesfully Saving the Push Token');
		} catch (e) {
			console.log('Error Saving the Push Token');
		}
	}

	return token;
};`

**Comment by cruzach** [comment] 2021-01-12 20:00
what version of `expo-notifications` are you using? When we ask for a reproducible demo, we mean everything needed to reproduce (not just the one function)

**Comment by Silavin** [comment] 2021-01-19 05:00
We are using expo notification 0.8.2.

**Comment by cruzach** [comment] 2021-01-19 21:19
Tested this with `expo-notifications` ^0.8.2 and `expo-constants` ^9.1.1 and couldn't reproduce the issue. Called:
```
await Notifications.getExpoPushTokenAsync({
  experienceId: "@charliecruzan/myapp",
})
 ```
then deleted the app, then reinstalled it (debug scheme), and the expo push token was different.
  
Without [a reproducible demo](https://stackoverflow.com/help/minimal-reproducible-example), there isn't much we can do, so I'm going to close this issue for now. If you can provide a minimal example of this issue, then I'm happy to reopen and investigate @Silavin

**Closed by cruzach** 2021-01-19 21:19 UTC
Labels: Notifications, iOS, needs more info, needs repro
