### ISSUE TITLE
Expo web not working on windows. ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by klebann** [expo/expo#19945] opened 2022-11-09 10:48 UTC
### Summary

I have managed to find temporary fix by adding:
`"web": "SET NODE_OPTIONS=--openssl-legacy-provider && expo start --web"`
But its ugly.

Any better solution?
Why its not working with LTS node.js and fresh build?
Maybe I have something misconfigured?
Am I doing something wrong?

### What platform(s) does this occur on?

Web

### SDK Version

npx expo -v  = 0.4.8

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.3
      expo: ~47.0.3 => 47.0.3
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.9 => 0.18.10
    Expo Workflow: managed

### Minimal reproducible example

npx expo start --web

PowerShell output:
```
npx expo start --web
Starting project at C:\Users\jakub\Desktop\Git\uber-clone
Starting Metro Bundler
Starting Webpack on port 19006 in development mode.
‼ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\jakub\Desktop\Git\uber-clone\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\jakub\Desktop\Git\uber-clone\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\jakub\Desktop\Git\uber-clone\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\jakub\Desktop\Git\uber-clone\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\jakub\Desktop\Git\uber-clone\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\jakub\Desktop\Git\uber-clone\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\jakub\Desktop\Git\uber-clone\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\jakub\Desktop\Git\uber-clone\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\jakub\Desktop\Git\uber-clone\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\jakub\Desktop\Git\uber-clone\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\jakub\Desktop\Git\uber-clone\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
```

**Comment by brentvatne** [comment] 2022-11-25 23:09
this is an issue with webpack, see related issue on create-react-app: https://github.com/facebook/create-react-app/issues/11562

it seems that it may be fixed on v6, which is not yet released

**Closed** 2022-11-25 23:08 UTC
Labels: needs review, CLI, invalid issue: third-party library

**Comment by goatandsheep** [comment] 2022-12-05 01:08
If you look at @klebann 's deps, the problem is actually expo webpack-config. Label should say CLI not third party

**Comment by lauditus** [comment] 2023-04-09 12:58
I face the same problem in termux.
