### ISSUE TITLE
[bare][ios] linkingUri is undefined on iOS.

### ISSUE THREAD

**Issue by giautm** [expo/expo#8272] opened 2020-05-12 20:05 UTC
### Environment

```
  Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.10 
      react: ~16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ^0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.3
```
![image](https://user-images.githubusercontent.com/12751435/81739924-5fce1c00-94c6-11ea-87e6-1e196c2b9aa1.png)

<img width="1059" alt="Screen Shot 2020-05-13 at 03 04 16" src="https://user-images.githubusercontent.com/12751435/81740048-868c5280-94c6-11ea-8d7e-744575fcc5da.png">

**Comment by brentvatne** [comment] 2020-05-12 20:53
`Linking `from the `expo` package isn't supported in bare workflow. we're in the process of transitioning over to the `expo-linking` package, you can go ahead and install this in your project and use it in place, but it does't provide all of the capabilities that you get in the managed workflow, eg: `Linking.makeUrl()` will warn and return empty string because it's not exposed via manifest in bare

**Comment by giautm** [comment] 2020-05-12 21:22
Hi @brentvatne , I don't got any warning after switch to `expo-linking`. :-/ Then exception still throw.

**Comment by brentvatne** [comment] 2020-05-12 21:33
what is the code in your app that is triggering this?

**Comment by giautm** [comment] 2020-05-12 21:33
The following code is no longer valid, cause by `no-publish workflow` feature? 

https://github.com/expo/expo/blob/071e91e336f88078bc56883b5def5d325a302589/packages/expo-linking/src/Linking.ts#L110-L116

**Comment by brentvatne** [comment] 2020-05-12 22:17
`Linking.makeUrl()` never worked in bare apps, we now try to show a better warning

**Comment by giautm** [comment] 2020-05-13 04:26
No, I jusst call Linking.makeUrl(‘/‘) to get url for react-navigation. That is expo code, not my app code. 😄

**Comment by brentvatne** [comment] 2020-05-13 04:35
yeah, that's what i was asking - i was just wondering what code you were actually calling in your app.

in a bare app if you import `import * as Linking from 'expo-linking';` and call `Linking.makeUrl()` you will get a warning and it will return an empty string. this is because we don't know what scheme you want to use in a bare app so we can't provide the same API. in a managed app we just have a single `scheme` field in app.json so we can use that. so instead of calling `Linking.makeUrl()` to get a path for react-navigation, just give react-navigation your scheme directly: `'yourscheme://`

if you `import { Linking } from 'expo';` and call `Linking.makeUrl()` in a bare app then you will get a red screen. we migrated our docs to recommend people install `expo-linking` like we have done with most of the rest of the sdk and handled the error better in `expo-linking`.

you happened to stumble into linking in a weird transition period where importing `Linking` from expo hasn't been officially deprecated and so it's likely most people are using it still and will need to adjust their code when ejecting to accommodate for that.

if `import * as Linking from 'expo-linking'; Linking.makeUrl('/')` throws a red screen error for you then let me know - it should just warn. closing this issue unless this is what is happening to you

**Closed by brentvatne** 2020-05-13 04:35 UTC
Labels: Needs triage

**Comment by giautm** [comment] 2020-05-13 05:57
> if `import * as Linking from 'expo-linking'; Linking.makeUrl('/')` throws a red screen error for you then let me know - it should just warn.

@brentvatne : It's still throw a red screen, as I said. (Plz, don't troll me 🙄)

I have uploaded a video, please take a look. 
https://vimeo.com/giautm/review/417909113/d0d466570f

**Comment by brentvatne** [comment] 2020-05-13 06:11
hey! sorry i'm not sure what you mean by "Plz, don't troll me" - i am having a pretty hard time understanding your issue, perhaps due to the language barrier, so please don't interpret anything i'm saying as rude, i am just trying my best to understand.

can you share a reproducible example app that demonstrates this issue you're encountering? i created a new bare app and used `Linking.makeUrl('/')` from `expo-linking` and did not get a redscreen, you can see here: https://github.com/brentvatne/issue-8272

screenshot:
<img width="495" alt="Screen Shot 2020-05-12 at 11 10 15 PM" src="https://user-images.githubusercontent.com/90494/81777479-c55de080-94a5-11ea-827a-ca42be5d2df8.png">

happy to reopen the issue if you can demonstrate this for me

**Comment by giautm** [comment] 2020-05-13 06:44
Thanks for your patience with me.

I just eject new app, and it working fine. I don't know why it happened in my app. I trying to `console.log(Constants.manifest)` at this line.
https://github.com/expo/expo/blob/071e91e336f88078bc56883b5def5d325a302589/packages/expo-linking/src/Linking.ts#L110-L116

It print a full manifest, instead of `null`. It may cause the red-screen.

NULL & warning in new app:
```
 LOG  Running "main" with {"rootTag":21,"initialProps":{}}
 LOG  Constants.manifest null
 WARN  Linking.makeUrl is not supported in bare workflow. Switch to using your scheme string directly.
```

**Update**: I found the issue, I re-assign `Constants.manifest` in `App.tsx` to supply some default values. My bad.

Once again, thank you for your help.

**Comment by brentvatne** [comment] 2020-05-13 06:50
great, i’m so glad you were able to figure it out! thanks for following up 👍👍

**Comment by giautm** [comment] 2020-05-13 06:59
You may not remember, but we connected on Facebook, and I follow you on twitter. "troll" is not rude in my country, It means softer, just for fun. :smile: Thanks for taking the time all day for me.

**Comment by brentvatne** [comment] 2020-05-13 07:03
i do remember! haha that’s good to know, communicating over text between cultures is hard sometimes 😂
