### ISSUE TITLE
Background app transition to the foreground when clicking on app icon

### ISSUE THREAD

**Issue by mradziwon** [expo/expo#2181] opened 2018-09-07 14:09 UTC
### Environment
- Exp v28 detached
- Android for example Xiaomi Redmi 5A, Xiaomi Redmi 4A, Huawei phones

It works fine on all Samsung phones.

### Steps to Reproduce

1. Detach exp v28 to ExpoKit
2. Fix build by adding `android/detach-scripts` and removing [compile project(path: ':expoview')](https://forums.expo.io/t/cant-build-android-project-after-detaching-from-expo-sdk-28-0-0/12239/5)
3. Build app and start it on Android device
4. Move app to the background
5. Click on app icon on main desktop

It only happens when clicking on app icon to make transition from background to foreground.

### Expected Behavior

App comes back to foreground in a second.

### Actual Behavior

I can see wallpaper and icons for 5-6 seconds and app is responding to gestures, clicks in inputs and it even sends requests to backend, but whole app layout is 'transparent'.

I can make transition to other screen or open a drawer menu.
If I click in input the keyboard will open. Perf monitor is also visible when activated.

Screenshots(My icon is under blue square):

![1screenshot_2018-09-07-16-46-29](https://user-images.githubusercontent.com/6785984/45223604-5edff280-b2c0-11e8-9f2f-e7f0472fc6fe.png)

![2screenshot_2018-09-07-16-54-43](https://user-images.githubusercontent.com/6785984/45223613-62737980-b2c0-11e8-8ff9-4d8d74f20d4e.png)

**Comment by mradziwon** [comment] 2018-09-10 13:41
There are no errors in logcat. I recorded short video of the problem:
https://streamable.com/fxsu2

**Comment by mradziwon** [comment] 2018-09-10 14:17
I think I've found a solution, but I'm not sure if it will break something else. I had to change `android: name = ". MainActivity" android: launchMode = "singleTask"` back to default - `android: launchMode = "standard"`. Will this have a negative impact on the the expo application?

**Comment by mradziwon** [comment] 2018-09-10 14:48
It isn't a solution, because now react-native-firebase fcm resets the whole application on notification click.

**Comment by n-sviridenko** [comment] 2018-11-30 20:06
@mradziwon what's the current state? should we use `singleTask` or `singleTop`? We use sdk `v30`.
The issue is that `expo-firebase-notifications` requires `singleTop`: https://github.com/expo/expo/blob/master/packages/expo-firebase-notifications/README.md
However `Linking` requires `singleTask`: https://github.com/expo/expo/issues/1788#issuecomment-410082338

**Comment by tsapeta** [comment] 2019-09-28 15:54
SDK28 that you used when creating this issue is no longer supported and also we deprecated `expo-firebase-*` modules since then, so I'm gonna close this issue. Please create a new issue if this still happens in any of the currently supported SDK versions.

**Closed by tsapeta** 2019-09-28 15:54 UTC
Labels: project: firebase, project: notification-service
