### ISSUE TITLE
The latest expo upgrade on Android (Meizu PRO6) (SDK 33 upgrade, at 31 May 2019)  doesn't work properly.

### ISSUE THREAD

**Issue by gamardzoba** [expo/expo#4382] opened 2019-06-03 09:25 UTC
### Environment

```
Expo CLI 2.18.7 environment info:
    System:
      OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
      Shell: 5.5.1 - /bin/zsh
    Binaries:
      Node: 12.3.1 - ~/.nvm/versions/node/v12.3.1/bin/node
      Yarn: 1.16.0 - /usr/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.3.1/bin/npm
    npmPackages:
      expo: ^32.0.6 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1                                                          
      react-navigation: ^3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 2.18.7
```

It is VueNative app running in dev mode under Ubuntu 18.10. Before the upgrade from 31 May 2019 for Android (Add support for Expo SDK 33) it run correctly. This upgrade caused the following error:
### Steps to Reproduce
1. Init brand new Vue Native project according to https://vue-native.io/docs/installation.html#Setup-with-Vue-Native-Cli
2. Run with `expo start` and scan QR code with Meizu PRO6 (Android 6.0)

### Expected Behavior

I have to get a result of 
```
<template>
  <view class="container">
    <text class="text-color-primary">My Vue Native App</text>
    </view>
</template>

```

### Actual Behavior

I got a blank screen with nothing. 

For all other existing apps, not just inited one, I got such error: 
![S90603-120758](https://user-images.githubusercontent.com/3626876/58790744-a13d2280-85f9-11e9-824c-3a5fd53f2bba.jpg)

**Comment by Hajan39** [comment] 2019-06-03 09:47
I have the same problem, with react-native app on Windows. When I start my app in expo, it crashes.

**Comment by rafaelmoraisdev** [comment] 2019-06-03 10:58
Quoting @gamardzoba:
> I got a blank screen with nothing.

I have the exact same problem on iphone simulator. The Expo Client updated to 2.11.0 and now it does not render, it was working fine on Expo Client 2.10.06. Is there any way to downgrade on iPhone simulator?

**Comment by koredefashokun** [comment] 2019-06-03 12:08
@rafaelmoraisdev If you use `react-native-screens`, comment it out for now. The new client does not work with that (yet).

**Comment by rafaelmoraisdev** [comment] 2019-06-03 12:10
That was it! Thanks @koredefashokun

**Comment by cruzach** [comment] 2019-06-03 16:44
Looks like this is a duplicate of #4371! Fix is pending 👍 

(Closing bc duplicate)

**Closed by cruzach** 2019-06-03 16:44 UTC
Labels: bug

**Comment by vkatsar** [comment] 2019-06-11 14:36
For NativeBase developers please remove "transparent" attributes from buttons
