### ISSUE TITLE
How should I exit In App Purchases Test Mode

### ISSUE THREAD

**Issue by AlenToma** [expo/expo#12163] opened 2021-03-09 15:00 UTC
### Summary

So I decided to implement in-app-purchases using expo-in-app-purchases. everything worked greet.

Now I have done my part and want it on Production mode.

When I try to Buy thing in my app it says test Card How should I exit this?

I have released now my app on google play console and its in review.

My app now is in production, but the test mode part is still on. What should I do to exit it. 

There was no documentation on this part and I am really lost now.

This may not be the plugin problem but I have found no documentation and dont know how i should exist this test mode part.

My app Name is [NovelManager](https://play.google.com/store/apps/details?id=com.novelmanager&gl=US)

### Here is my code.
```
import * as InAppPurchases from 'expo-in-app-purchases';
export default class payment {
    private static finishTransactionCallback?: (purchase: any) => Promise<void>;
    constructor() {

    }

    public static connectAsync = async () => {
        await InAppPurchases.connectAsync();
        InAppPurchases.setPurchaseListener(async ({ responseCode, results, errorCode }) => {
            // Purchase was successful
            if (responseCode === InAppPurchases.IAPResponseCode.OK) {
                results.forEach(purchase => {
                    if (!purchase.acknowledged) {
                        console.log(`Successfully purchased ${purchase.productId}`);
                        // Process transaction here and unlock content...
                        // Then when you're done
                        payment.finishTransactionAsync(undefined, purchase);
                    }
                });
            } else
                if (responseCode === InAppPurchases.IAPResponseCode.USER_CANCELED) {
                    console.log('User canceled the transaction');
                } else if (responseCode === InAppPurchases.IAPResponseCode.DEFERRED) {
                    console.log('User does not have permissions to buy but requested parental approval (iOS only)');
                } else {
                    console.warn(`Something went wrong with the purchase. Received errorCode ${errorCode}`);
                }
        });
    }

    public static async disconnectAsync() {
        await InAppPurchases.disconnectAsync();
    }

    public static getPurchaseHistoryAsync = async () => {
        var item = await InAppPurchases.getPurchaseHistoryAsync();
        if (item && item.results && item.results.length > 0)
            return item.results;
        else return [] as (InAppPurchases.InAppPurchase | InAppPurchases.IAPItemDetails)[];
    }

    public static getProducts = async (itemList: string[]) => {
        var item = await InAppPurchases.getProductsAsync(itemList);
        if (item && item.results && item.results.length > 0)
            return item.results;
        else return [] as (InAppPurchases.InAppPurchase | InAppPurchases.IAPItemDetails)[];
    }

    public static finishTransactionAsync = async (callBack?: (purchase: any) => Promise<void>, purchase?: any) => {
        try {
            if (callBack)
                payment.finishTransactionCallback = callBack;
            else {
                await InAppPurchases.finishTransactionAsync(purchase, false);
                purchase.acknowledged = true;
                if (payment.finishTransactionCallback)
                    await payment.finishTransactionCallback(purchase);

            }
        } catch (error) {
            console.log(error);
        }
    }

    public static async requestPayment(productId: string) {
        try {
            await InAppPurchases.purchaseItemAsync(productId);
            return true;
        }
        catch (error) {
            console.log("Something went wrong. with purchase:" + productId);
            console.log(error);
        }

        return false;
    }
}
```

**Comment by cruzach** [comment] 2021-08-03 21:20
If your app is released through a production track, it shouldn't be using your sandbox or test accounts. Maybe try removing your Google account from the "License testers" in the Play Console? 

Closing this since it's not a bug with `expo-in-app-purchases`, although I would like to know what the root cause of this ended up being?

**Closed by cruzach** 2021-08-03 21:20 UTC
