### ISSUE TITLE
Exception occurred while executing exported method askAsync on module ExpoPermissions: null

### ISSUE THREAD

**Issue by janicduplessis** [expo/expo#5548] opened 2019-09-05 17:52 UTC
## 🐛 Bug Report

I'm getting this error in production:

Encountered an exception while calling native method: Exception occurred while executing exported method askAsync on module ExpoPermissions: null

Happened 429 times for 89 users over 25 days.

### Environment

Android, regular RN project with unimodules

![image](https://user-images.githubusercontent.com/2677334/64365652-9d4ae300-cfe2-11e9-94c3-66be86c9071e.png)

### Steps to Reproduce

I cannot reproduce locally. I'm pretty sure it comes from this call:

```
const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
```

### Expected Behavior

No error

### Actual Behavior

It doesn't seem to cause a noticeable issue, afaik there is no need to require permissions for notifications on Android. Not sure what the code that ask notif permissions does on Android.

### Reproducible Demo

N/A

**Comment by janicduplessis** [comment] 2019-09-05 18:02
Here's a more detailled breakdown of android versions:

![image](https://user-images.githubusercontent.com/2677334/64367165-a7baac00-cfe5-11e9-921d-6fb51462efa6.png)

I tried reproducing on a Android 9 simulator but no luck there. The only Android device I have currently is on Android 7.1.2 and also doesn't repro.

**Comment by lukmccall** [comment] 2019-10-25 09:02
Hi @janicduplessis, which version of `expo-permissions` do you use?
It'll be nice if you also provide a part of your `packages.json`, which contains expo related dependencies.

**Comment by AryanJ-NYC** [comment] 2020-01-09 18:55
@lukmccall I get a similar error. Am using:

```
    "expo": "~36.0.2",
    "expo-analytics-amplitude": "~8.0.0",
    "expo-camera": "^8.0.0",
    "expo-constants": "^8.0.0",
    "expo-contacts": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-image-picker": "~8.0.0",
    "expo-linear-gradient": "~8.0.0",
    "expo-mail-composer": "~8.0.0",
    "expo-permissions": "~8.0.0",
```

**Comment by Phillip-Cognativ** [comment] 2020-02-05 01:43
> @lukmccall I get a similar error. Am using:
> 
> ```
>     "expo": "~36.0.2",
>     "expo-analytics-amplitude": "~8.0.0",
>     "expo-camera": "^8.0.0",
>     "expo-constants": "^8.0.0",
>     "expo-contacts": "~8.0.0",
>     "expo-font": "~8.0.0",
>     "expo-image-picker": "~8.0.0",
>     "expo-linear-gradient": "~8.0.0",
>     "expo-mail-composer": "~8.0.0",
>     "expo-permissions": "~8.0.0",
> ```
> 
> I was _also_ asking for Android notification permissions which are a [normal category permission](https://stackoverflow.com/questions/37294076/push-notifications-gcm-permission-at-runtime).
> 
> I've changed my code to something like:
> 
> ```ts
> if (Platform.OS === 'ios')
>   await Permissions.askAsync(Permissions.NOTIFICATIONS)
> ```

I get this error when asking for 'dangerous' permissions (Location, Camera). `Permissions.askAsync(Permissions.LOCATION)` will error on Android devices that need this to be requested so then I can't get permission.

Also a regular RN project with Unimodules. Using expo-permissions 8.0.0

Is this library able to ask for dangerous permissions on Android at the moment?

**Comment by WouterFlorijn** [comment] 2020-02-05 11:36
@lukmccall any idea if there's a possible workaround or fix for this? We're having the same issue and it's blocking our release since we updated Expo.

My reproduction steps (for both production and development):
- Install the app.
- Disable push notifications in Android settings.
- Call `Permissions.askAsync(Permissions.NOTIFICATIONS)`

Result: nothing happens for the user, and the console shows the error mentioned in the issue.

**Comment by Phillip-Cognativ** [comment] 2020-02-05 22:14
@WouterFlorijn 

My working solution is to keep a list of dangerous Android permissions, and only prompt an Android user for those permissions, ignoring normal permissions. Notifications is a normal permission so it is set automatically and I don't think expo-permissions is able to prompt the user to reset it if they have manually disabled it like you have done.

```
export const PERMISSIONS: {[key: string]: Permission } = {
  CALENDAR: EXPermissions.CALENDAR,
  CAMERA: EXPermissions.CAMERA,
  CONTACTS: EXPermissions.CONTACTS,
  LOCATION: EXPermissions.LOCATION,
  MICROPHONE: EXPermissions.AUDIO_RECORDING,
  CAMERA_ROLL: EXPermissions.CAMERA_ROLL,
  LOCAL_NOTIFICATIONS: EXPermissions.USER_FACING_NOTIFICATIONS,
  NOTIFICATIONS: EXPermissions.NOTIFICATIONS,
  SETTINGS: EXPermissions.SYSTEM_BRIGHTNESS,
};

export const DANGEROUS_PERMISSIONS: Permission[] = [
  PERMISSIONS.CALENDAR,
  PERMISSIONS.CAMERA,
  PERMISSIONS.CONTACTS,
  PERMISSIONS.LOCATION,
  PERMISSIONS.AUDIO_RECORDING,
  PERMISSIONS.CAMERA_ROLL,
  PERMISSIONS.SYSTEM_BRIGHTNESS,
];
```

**Comment by BrodaNoel** [comment] 2020-02-23 13:17
I'm having the same problem and I only use
```
Permissions.askAsync(Permissions.USER_FACING_NOTIFICATIONS)
```

**Comment by yangga** [comment] 2020-03-19 03:54
Same here. Does anyone have a solution for this?

**Comment by yasahmed** [comment] 2020-05-17 21:36
any solution ?

**Comment by lukmccall** [comment] 2020-05-18 09:40
Hi @yasahmed. Could you provide logs from your device? Or provide more details about your environment, android version? It'll be nice if you also create a simple demo that can reproduce this bug. 

I've looked at this bug in the past, but unfortunately, I couldn't reproduce it.

**Comment by Speedy1991** [comment] 2020-06-22 08:11
Hi @lukmccall 

```
import {Permissions} from 'react-native-unimodules'
const {granted} = await Permissions.askAsync(
    Permissions.USER_FACING_NOTIFICATIONS,
    Permissions.NOTIFICATIONS,
  )
```
Leads to
`[Mon Jun 22 2020 10:00:20.368]  WARN     0 [Error: Encountered an exception while calling native method: Exception occurred while executing exported method askAsync on module ExpoPermissions: permission cannot be null or empty]`

Strangely calling `getAsync` returns always true (even it is disabled via android app settings)
```
 const {granted, canAskAgain} = await Permissions.getAsync(
    Permissions.USER_FACING_NOTIFICATIONS,
    Permissions.NOTIFICATIONS,
  )
  // granted: true, canAskAgain: true
```

Setup (Bare Project):

```
"react": "16.13.1",
"react-native": "0.62.2",
"react-native-unimodules": "0.9.1",
```

Tested on a real Android 9 device with disabled notifications

**Comment by lukmccall** [comment] 2020-06-22 12:41
Hi @Speedy1991, the bug which you found isn't connected with this issue. So, I've created a separate issue for this (see https://github.com/expo/expo/issues/8909). 
It concerns problems with the `askAsync` method. The issue with `getAsync` was fixed by https://github.com/expo/expo/pull/8539 and it will be available in the `SDK 38`.

**Comment by RodolfoGS** [comment] 2020-07-05 00:09
Same here:
```
Encountered an exception while calling native method: Exception occurred while executing exported method askAsync on module ExpoPermissions: permission cannot be null or empty
```

I can't reproduce it, I get that errors in Sentry.

```
  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.12 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      expo-permissions: ^9.0.1
    npmGlobalPackages:
      expo-cli: 3.21.13
```

Devices:
![image](https://user-images.githubusercontent.com/870365/86522865-d2ee7180-be29-11ea-898f-ff6854adb6fd.png)

![image](https://user-images.githubusercontent.com/870365/86522866-dc77d980-be29-11ea-85ca-d3eafc744844.png)

**Comment by lukmccall** [comment] 2020-07-06 06:27
Hi @RodolfoGS, your problem should be fixed by https://github.com/expo/expo/pull/8910 ;)

**Comment by lukmccall** [comment] 2020-07-15 07:44
Closing this issue due to inactivity. Moreover, we can't reproduce it either. If this is still a problem for you and it's reproducible using the latest SDK version, feel free to open up a new issue!

**Closed by lukmccall** 2020-07-15 07:44 UTC
Labels: Android, Bare Workflow, Permissions, bug, status: needs more info

**Comment by RodolfoGS** [comment] 2020-07-15 13:26
@lukmccall sorry, I don't saw your comment.
Yes, was fixed with https://github.com/expo/expo/pull/8910 Thank you so much for your help, you are great 🥇
