### ISSUE TITLE
Permissions.getAsync or Permissions.askAsync Not working

### ISSUE THREAD

**Issue by StudyTae** [expo/expo#4668] opened 2019-06-20 08:24 UTC
### Environment

Expo CLI 2.20.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.20.2
     "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
     "expo": "^33.0.0",
    "expo-ads-admob": "~5.0.1",
 

Android real device : LGM-V300S.
Android Studio 3.3.2
macOS 10.14.5
Standalone App(ExpoKit)

### Steps to Reproduce

Connect the actual device to the Android studio, start an extension, and then click the Run app button in the Android studio to install the app on the device. The permissions check is successful in this app.

However, after 'expo publish' build  => signed Bundle APK => select APK => click release=>   V1,V2 Check => APK on the device to run. 

Pressing a button does not generate an alert for the privilege.

### Expected Behavior

Shall be operated like a  simulator apk.

### Actual Behavior

The actual APK does not notify you of any permissions.

### Reproducible Demo
https://snack.expo.io/H1sswTuyS
~~~js
import React, { Component } from "react";
import {
  Platform,
  StyleSheet,
  View,
  Text,
  Modal,
  TouchableOpacity,
  TouchableHighlight,
  Image,
  Alert,
  NativeModules
} from "react-native";
import * as Permissions from "expo-permissions";
import { Ionicons } from "@expo/vector-icons";


class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      alertVisibility: true
    };
  }

  static navigationOptions = ({ navigation }) => {
    return {
      headerLeft: (
        <TouchableOpacity style={{ paddingLeft: 25 }} onPress={() => {}}>
          <Ionicons
            name={"ios-arrow-back"}
            size={30}
            color={"#ffffff"}
          />
        </TouchableOpacity>
      ),

      headerRight: null
    };
  };

  

  showCustomAlert(visible) {
    this.setState({ alertVisibility: visible });
  }

  okButton = async () => {
    this.setState({
      buttonColor: "#ffd90d"
    });
    const permission = await Permissions.getAsync(Permissions.CAMERA_ROLL);
    if (permission.status !== "granted") {
      const newPermission = await Permissions.askAsync(Permissions.CAMERA_ROLL);

      if (newPermission.status === "granted") {
        const permission2 = await Permissions.getAsync(Permissions.CAMERA);
        if (permission2.status !== "granted") {
          const newPermission2 = await Permissions.askAsync(Permissions.CAMERA);
          if (newPermission2.status === "granted") {
            const permission3 = await Permissions.getAsync(
              Permissions.NOTIFICATIONS
            );
            if (permission3.status !== "granted") {
              const newPermission3 = await Permissions.askAsync(
                Permissions.NOTIFICATIONS
              );
              if (newPermission3.status === "granted") {
                const permission4 = await Permissions.getAsync(
                  Permissions.REMINDERS
                );
                if (permission4.status !== "granted") {
                  const newPermission4 = await Permissions.askAsync(
                    Permissions.REMINDERS
                  );
                  if (newPermission4.status === "granted") {
                    this.setState({ alertVisibility: false });
                    this.props.navigation.navigate("RegisterWalletIndex");
                  } else {
                    this.setState({ alertVisibility: false });
                    this.props.navigation.navigate("RegisterWalletIndex");
                  }
                }
                if (permission4.status === "granted") {
                  console.log(
                    "permission4.status not granted"
                  );
                } else {
                 console.log(
                    "permission4.status not granted"
                  );
                }
              } else {
                const permission4 = await Permissions.getAsync(
                  Permissions.REMINDERS
                );
                if (permission4.status !== "granted") {
                  const newPermission4 = await Permissions.askAsync(
                    Permissions.REMINDERS
                  );
                  if (newPermission4.status === "granted") {
                    this.setState({ alertVisibility: false });
                    this.props.navigation.navigate("RegisterWalletIndex");
                  } else {
                    this.setState({ alertVisibility: false });
                    this.props.navigation.navigate("RegisterWalletIndex");
                  }
                }
                if (permission4.status === "granted") {
                  console.log(
                    "permission4.status not granted"
                  );
                } else {
                  console.log(
                    "permission4.status not granted"
                  );
                }
              }
            }
            if (permission3.status === "granted") {
              console.log(
                    "permission4.status not granted"
                  );
            } else {
               console.log(
                    "permission4.status not granted"
                  );
            }
          } else {
            const permission3 = await Permissions.getAsync(
              Permissions.NOTIFICATIONS
            );
            if (permission3.status !== "granted") {
              const newPermission3 = await Permissions.askAsync(
                Permissions.NOTIFICATIONS
              );
              if (newPermission3.status === "granted") {
                const permission4 = await Permissions.getAsync(
                  Permissions.REMINDERS
                );
                if (permission4.status !== "granted") {
                  const newPermission4 = await Permissions.askAsync(
                    Permissions.REMINDERS
                  );
                  if (newPermission4.status === "granted") {
                    this.setState({ alertVisibility: false });
                    this.props.navigation.navigate("RegisterWalletIndex");
                  } else {
                    this.setState({ alertVisibility: false });
                    this.props.navigation.navigate("RegisterWalletIndex");
                  }
                }
                if (permission4.status === "granted") {
                  console.log(
                    "permission4.status not granted"
                  );
                } else {
                  console.log(
                    "permission4.status not granted"
                  );
                }
              } else {
                console.log(
                    "permission3.status not granted"
                  );
                const permission4 = await Permissions.getAsync(
                  Permissions.REMINDERS
                );
                if (permission4.status !== "granted") {
                  const newPermission4 = await Permissions.askAsync(
                    Permissions.REMINDERS
                  );
                  if (newPermission4.status === "granted") {
                    this.setState({ alertVisibility: false });
                    this.props.navigation.navigate("RegisterWalletIndex");
                  } else {
                    this.setState({ alertVisibility: false });
                    this.props.navigation.navigate("RegisterWalletIndex");
                  }
                }
                if (permission4.status === "granted") {
                  console.log(
                    "permission4.status not granted"
                  );
                } else {
                  console.log("permission4.status not granted");
                }
              }
            }
            if (permission3.status === "granted") {
              console.log(
                    "permission4.status not granted"
                  );
            }
          }
        }
        if (permission2.status === "granted") {
          console.log(
                    "permission4.status not granted"
                  );
        } else {
          console.log(
                    "permission4.status not granted"
                  );
        }
      } else {
        alert("close");
      }
    } else {
      if (permission.status === "granted") {
        console.log(
                    "permission4.status not granted"
                  );
      } else {
        console.log(
                    "permission4.status not granted"
                  );
      }
    }
  };

  androidButton = async () => {
    const permission = await Permissions.getAsync(Permissions.CAMERA_ROLL);
    if (permission.status !== "granted") {
      const newPermission = await Permissions.askAsync(Permissions.CAMERA_ROLL);
      if (newPermission.status === "granted") {
        const permission2 = await Permissions.getAsync(Permissions.CAMERA);
        if (permission2.status !== "granted") {
          const newPermission2 = await Permissions.askAsync(Permissions.CAMERA);
          if (newPermission2.status === "granted") {
            const permission3 = await Permissions.getAsync(
              Permissions.NOTIFICATIONS
            );
            if (permission3.status !== "granted") {
              const newPermission3 = await Permissions.askAsync(
                Permissions.NOTIFICATIONS
              );
              if (newPermission3.status === "granted") {
                this.setState({ alertVisibility: false });
                this.props.navigation.navigate("RegisterWalletIndex");
              }
            }
            if (permission3.status === "granted") {
              this.setState({ alertVisibility: false });
              this.props.navigation.navigate("RegisterWalletIndex");
            } else {
              console.log("permission3.status not granted");
            }
          } else {
            const permission3 = await Permissions.getAsync(
              Permissions.NOTIFICATIONS
            );
            if (permission3.status !== "granted") {
              const newPermission3 = await Permissions.askAsync(
                Permissions.NOTIFICATIONS
              );
              if (newPermission3.status === "granted") {
                this.setState({ alertVisibility: false });
                this.props.navigation.navigate("RegisterWalletIndex");
              } else {
                this.setState({ alertVisibility: false });
                this.props.navigation.navigate("RegisterWalletIndex");
              }
            }
            if (permission3.status === "granted") {
              this.setState({ alertVisibility: false });
              this.props.navigation.navigate("RegisterWalletIndex");
            }
          }
        }
        if (permission2.status === "granted") {
          this.setState({ alertVisibility: false });
          this.props.navigation.navigate("RegisterWalletIndex");
        }
      } else {
        Alert.alert(
          "info",
          `Text`,
          [
            {
              text: "ok",
              onPress: () => alert("close")
            }
          ],
          { cancelable: false }
        );
      }
    } else {
      const permission2 = await Permissions.getAsync(Permissions.CAMERA);
      if (permission2.status !== "granted") {
        const newPermission2 = await Permissions.askAsync(Permissions.CAMERA);
        if (newPermission2.status === "granted") {
          this.setState({ alertVisibility: false });
          this.props.navigation.navigate("RegisterWalletIndex");
        } else {
          this.setState({ alertVisibility: false });
          this.props.navigation.navigate("RegisterWalletIndex");
        }
      } else {
        this.setState({ alertVisibility: false });
        this.props.navigation.navigate("RegisterWalletIndex");
      }
    }
  };

  render() {
    return (
      <View style={styles.MainContainer}>
        <Modal
          visible={this.state.alertVisibility}
          transparent={true}
          animationType={"fade"}
          onRequestClose={() => {
            this.showCustomAlert(!this.state.alertVisibility);
          }}
        >
          <View
            style={{
              flex: 1,
              height: "100%",
              alignItems: "center",
              justifyContent: "center",
              backgroundColor: "rgba(0,0,0,.8)"
            }}
          >
            <View style={styles.alertmainview}>
              <Text style={styles.alerttitle}>Text</Text>

              <View
                style={{
                  width: "60%",
                  height: 1,
                  backgroundColor: "#fed80c",
                  marginLeft: 20
                }}
              />

              <Text style={styles.alertmessage}>
               Text
              </Text>
              <View>
                <Text style={styles.subtitle}>Text</Text>
                <View
                  style={{
                    flexDirection: "row",
                    backgroundColor: "#efefef",
                    alignItems: "center",
                    marginLeft: 20,
                    marginRight: 20,
                    borderRadius: 3,
                    marginBottom: 10
                  }}
                >
                  <Text style={styles.subtitletextstorage}>Text</Text>
                  <Text style={styles.subtitletext2}>Text</Text>
                </View>

                <Text style={styles.subtitle}>Text Text</Text>
                <View
                  style={{
                    flexDirection: "column",
                    backgroundColor: "#efefef",
                    marginLeft: 20,
                    marginRight: 20,
                    borderRadius: 3
                  }}
                >
                  <View style={{ flexDirection: "row", marginTop: 6 }}>
                    <Text style={styles.subtitletext}>Text</Text>
                    <Text style={styles.subtitletext2}>Text Text</Text>
                  </View>
                  <View
                    style={{
                      flexDirection: "row",
                      paddingTop: 8,
                      paddingBottom: 8
                    }}
                  >
                    <Text style={styles.subtitletext}>Text</Text>
                    <Text style={styles.subtitletext2}>
                      Text
                    </Text>
                  </View>
                </View>
              </View>
              <View
                style={{
                  width: "90%",
                  height: 1,
                  backgroundColor: "#fed80c",
                  marginLeft: 20,
                  marginRight: 20,
                  marginTop: 20
                }}
              />

              <View
                style={{
                  width: "100%",
                  alignItems: "flex-end",
                  paddingRight: 20,
                  paddingTop: 10
                }}
              >
                <TouchableHighlight
                  underlayColor="#ffd90d"
                  style={styles.buttonStyle}
                  onPress={() =>
                    Platform.OS === "ios"
                      ? this.okButton()
                      : this.androidButton()
                  }
                >
                  <Text style={styles.TextStyle}> ok </Text>
                </TouchableHighlight>
              </View>
            </View>
          </View>
        </Modal>
        <Image
          style={{ width: 180, height: 180 }}
          source={require("./assets/snack-icon.png")}
          resizeMode="contain"
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  MainContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: Platform.OS == "ios" ? 20 : 0,
    backgroundColor: "rgba(0,0,0,.8)"
  },

  alertmainview: {
    width: "90%",
    borderRadius: 8,
    backgroundColor: "#fff"
  },

  alerttitle: {
    fontSize: 18,
    textAlign: "left",
    paddingLeft: 24,
    paddingTop: 30,
    marginBottom: 10
  },

  alertmessage: {
    fontSize: 14,
    padding: 20
  },
  subtitle: {
    fontWeight: "bold",
    marginLeft: 20,
    paddingTop: 12,
    fontSize: 12,
    paddingBottom: 8
  },
  subtitletext: {
    fontWeight: "bold",
    marginLeft: 10,
    fontSize: 14
  },
  subtitletextstorage: {
    fontWeight: "bold",
    marginLeft: 10,
    fontSize: 14,
    marginTop: 6,
    marginBottom: 6
  },
  subtitletext2: {
    marginLeft: 10,
    fontSize: 14,
    color: "#434343"
  },
  buttonStyle: {
    width: 60,
    height: 34,
    justifyContent: "center",
    borderRadius: 20,
    marginBottom: 18
  },

  TextStyle: {
    textAlign: "center",
    fontSize: 14,
    fontWeight: "bold"
  }
});

export default App;
~~~

**Comment by cruzach** [comment] 2019-06-20 15:56
Hi @StudyTae- 

The code you've provided has a lot going on (with a repro, it's best to include just enough to show the unwanted behavior). If I understand correctly- `Permissions` are asked for on your simulator correctly, but once you `expo build:android` and get/install the apk, it doesn't ask for Permissions anymore (even if they aren't granted)? And is this **only** happening with Expokit builds?

I'm also curious what your `android.permissions` key in your `app.json` file is, as [that can make a difference](https://docs.expo.io/versions/latest/sdk/permissions/#android-permissions-equivalents-inside-appjson)

**Comment by StudyTae** [comment] 2019-06-21 01:07
Yes, I used RealDevice and when I did the simulator with Android Studio, it worked normally. But when I made the releaseAPK after '`expo publish`', I didn't give me permission notice.

I'm using `Expokit`, so I made modifications to my authority on `Android Studio`.

my manifests
```
<permission
    android:name="com.smartcore.dadadac.permission.C2D_MESSAGE"
    android:protectionLevel="signature"/>

  <!-- These are required permissions to make the app run -->
  <uses-permission android:name="com.smartcore.dadadac.permission.C2D_MESSAGE" />
  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
  <uses-permission tools:node="remove" android:name="android.permission.WAKE_LOCK" />

  <!-- ADD PERMISSIONS HERE -->
    <uses-permission android:name="com.android.vending.BILLING" />
  <!-- BEGIN OPTIONAL PERMISSIONS -->
  <uses-permission android:name="android.permission.MANAGE_DOCUMENTS" />
  <uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_PHONE_STATE" />
  <uses-permission android:name="android.permission.USE_FINGERPRINT" />
  <uses-permission tools:node="remove" android:name="android.permission.VIBRATE" />
  <uses-permission android:name="com.android.launcher.permission.INSTALL_SHORTCUT" />
  <uses-permission tools:node="remove" android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

  <!-- These require runtime permissions on M -->
  <uses-permission  tools:node="remove" android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission  tools:node="remove" android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission  tools:node="remove" android:name="android.permission.READ_CONTACTS" />
  <uses-permission tools:node="remove" android:name="android.permission.READ_CALENDAR" />
    <uses-permission tools:node="remove" android:name="android.permission.WRITE_CALENDAR" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission tools:node="remove" android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.WRITE_SETTINGS" />
  <uses-permission  tools:node="remove" android:name="android.permission.READ_SMS" />
```

my app.json
~~~json
{
  "expo": {
    "name": "name",
    "description": "This project is really great.",
    "slug": "slug",
    "privacy": "public",
    "sdkVersion": "33.0.0",
    "packagerOpts": {
      "config": "./rn-cli.config.js"
    },
    "platforms": ["android"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",

    "android": {
      "package": "com.smartcore.dadadac",
      "publishBundlePath": "android/app/src/main/assets/shell-app.bundle",
      "publishManifestPath": "android/app/src/main/assets/shell-app-manifest.json",
      "splash": {
        "backgroundColor": "#000000"
      }
    },
    "updates": {
      "fallbackToCacheTimeout": 0,
      "enabled": false
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true,
      "usesIcloudStorage": true,
      "bundleIdentifier": "com.jackson.myapps",
      "publishBundlePath": "ios/mvw/Supporting/shell-app.bundle",
      "publishManifestPath": "ios/mvw/Supporting/shell-app-manifest.json"
    },
    "isDetached": true,
    "detach": {
      "iosExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.8.4-sdk30.0.0-3de13133-1adc-4ba1-8569-a84011e570b4.tar.gz",
      "androidExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/android-v2.8.1-sdk30.0.0-0fde103b-be3d-43f9-bc48-3035aa136971.tar.gz"
    },
    "scheme": "exp6c94a01048724a76bc92dca0c0cdd24a"
  }
}

~~~

**Comment by cruzach** [comment] 2019-08-12 18:36
Hey @StudyTae - your repro isn't runnable on it's own. Could you provide one that successfully runs in snack or `expo-cli` locally? Also, you can pass multiple permissions types to [Permissions.askAsync](https://docs.expo.io/versions/latest/sdk/permissions/#permissionsaskasynctypes) which will simplify your code a lot

**Comment by conilas** [comment] 2019-09-24 10:30
I have the *exact* same issue when using expo 35. It works normally (asking permissions and stuff) when local, but when I assemble to release and use it, no permissions are asked. 

I can try to add a repro case later on today

**Comment by m4ttheweric** [comment] 2019-10-03 18:46
@conilas You mentioned that you "forgot to re-generate the shell-bundle". How exactly do you do this? I may be having a similar issue after upgrading.

**Comment by conilas** [comment] 2019-10-04 12:50
You are probably going to laugh, but ```expo publish``` is what I forgot.

**Comment by lukmccall** [comment] 2019-10-08 13:12
I'm closing this issue, cause it was fixed earlier. Feel free to open this issue again if this bug comes back.

**Comment by Derewith** [comment] 2019-10-10 00:35
i am having the same issue here, using sdk 35 .. my _app.json_
`{
  "expo": {
    "name": "sit_alpha",
    "description": "",
    "slug": "sit-alpha",
    "sdkVersion": "35.0.0",
    "version": "1.0.4",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "loading": {
      "icon": "./assets/images/icon.png",
      "hideExponentText": true
    },
    "icon": "./assets/images/icon.png",
    "splash": {
      "image": "./assets/icons/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "packagerOpts": {
      "assetExts": [
        "ttf",
        "mp4",
        "otf",
        "xml"
      ]
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "it.bizzarrowebgroup.sitapp"
    },
    "assetBundlePatterns": [
      "assets/images/*"
    ],
    "android": {
      "package": "it.bizzarrowebgroup.sitapp",
      "versionCode": 6,
      "icon": "./assets/images/icon.png",
      "config": {
        "googleMaps": {
          "apiKey": "mykey"
        }
      },
      "permissions": [],
    },
    "isDetached": false,
    "scheme": "sitapp",
    "platforms": [
      "android",
      "ios"
    ]
  }
}
`
and this is the function on call 
`checkMultiPermissions = async () => {
    const { status } = await Permissions.getAsync(Permissions.CAMERA,Permissions.CAMERA_ROLL,Permissions.LOCATION);
    if (status !== 'granted') {
      Alert.alert('Hey! You have not enabled selected permissions');
    }
  };`

I've also tried to change my app.json android.permissions with `["ACCESS_FINE_LOCATION",
        "ACCESS_COARSE_LOCATION",
        "CAMERA",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE"]`  but after doing it with also expo publish and expo build:android the apk not have any permissions at all..

**Comment by lukmccall** [comment] 2019-10-14 07:57
Hi @Derewith, `Permissions.getAsync` doesn't return you 'granted', if you earlier didn't ask for permission. Except, the situation when you're using Android's version below 6. So, you can't expect that your function returns 'granted' status (You can read more about Android's permissions [here](https://developer.android.com/training/permissions/requesting)). 

However, I'm not sure if I understand your situation correctly. If not, please correct me and provide more information.

**Comment by Derewith** [comment] 2019-10-14 18:26
Hi @lukmccall my apk doesn't have any permission at all.
I'm using this function 
```
  getLocationAsync = async () => {
    const { status } = await Permissions.askAsync(Permissions.LOCATION);
    if (status === 'granted') {
      // return Location.getCurrentPositionAsync({ enableHighAccuracy: true });
      let location = await Location.getCurrentPositionAsync({ enableHighAccuracy: true });
      const region = {
        latitude: location.coords.latitude,
        longitude: location.coords.longitude,
        ...deltas
      };
      return this.setState({
        region
      });
    } else {
      throw new Alert.alert('Location permission not granted');
    }
  }
```
to ask the permission, then the `getAsync` to catch them all. 
But when i compile with `expo build:android `and test the apk on device , the app doesn't have any permission at all.

In my app.json here my android set-up
```
"android": {
      "package": "it.bizzarrowebgroup.sitapp",
      "versionCode": 6,
      "icon": "./assets/images/icon.png",
      "config": {
        "googleMaps": {
          "apiKey": "mykey"
        }
      },
      "permissions": ["ACCESS_FINE_LOCATION","ACCESS_COARSE_LOCATION","CAMERA","READ_EXTERNAL_STORAGE","WRITE_EXTERNAL_STORAGE"],
      "playStoreUrl": "playstorelink"
    },
```

**Comment by lukmccall** [comment] 2019-10-15 15:11
@Derewith, I've tried to reproduce this. Sadly, I failed.

What I did:
1. Created a new standalone app using `expo init`.
2. Copied the `android` section into my `app.json`.
3. Created a simple demo to ask/get permissions ([code](https://snack.expo.io/@lukaszkosmaty/github---permissions-not-working-in-standalone-app)).
4. Run `expo publish`  after that `expo builds: android`.
5. Run it on an Android device.

Everything worked fine. Please tell me if I've done something wrong.

I've also tried to install your app. However, I don't have a required account.
So, it will be nice if you create Github repo with everything needed to reproduce this issue.

**Comment by Derewith** [comment] 2019-10-15 18:54
@lukmccall thank you for your tests.
I really don't know why, but now after doing `expo builds: android` everything works. So the issue is solved.

**Comment by lukmccall** [comment] 2019-10-16 06:16
Nice 👍 
I'm closing this issue. Feel free to reopen it if this bug occurs again.

**Closed by lukmccall** 2019-10-16 06:16 UTC
Labels: Permissions, needs repro, project: android-runtime
