### ISSUE TITLE
expo-font@10.2.1 fonts not loaded

### ISSUE THREAD

**Issue by iswebdevloper** [expo/expo#19266] opened 2022-09-27 10:32 UTC
### Summary

font not loaded using expo-font@10.2.1 i had to downgrade to 10.2.0 to working with a custom fonts

### What platform(s) does this occur on?

Android/IOS

### SDK Version

46

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.1 - /usr/local/bin/npm
      Watchman: 2022.09.05.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.6
    Expo Workflow: bare

### Minimal reproducible example

```
//Font source 

export const fontSource = {
    "Lato-Bold": require('../assets/fonts/Lato-Bold.ttf'),
    "Lato-Semibold": require('../assets/fonts/Lato-Semibold.ttf'),
    "Lato-Regular": require('../assets/fonts/Lato-Regular.ttf'),
    "Lato-Medium": require('../assets/fonts/Lato-Medium.ttf'),
    "Lato-Light": require('../assets/fonts/Lato-Light.ttf'),
    "Lato-Thin": require('../assets/fonts/Lato-Thin.ttf'),
}


const [isReady, setIsReady] = React.useState(false);

//font loader
const loadFonts = React.useCallback(async () => {
    try {
      await loadAsync(fontSource);
    } catch (error) {
      console.log('Load font Error', error);
    }
    finally {
      setIsReady(true);
    }
  }, []);
```

**Comment by MatthieuMu** [comment] 2022-09-27 13:22
Same problem encountered today.

@Bonassa to go back you can lock the version with the following commands : 
`yarn upgrade expo-font@10.2.0`
or
`npm i expo-font@10.2.0`

You can also change the version number directly in the package.json file and run your package manager to update your lockfiles.

**Comment by brentvatne** [comment] 2022-09-27 16:35
I've reverted the latest to 10.2.0, we'll investigate this issue

**Comment by brentvatne** [comment] 2022-09-27 17:51
I can't reproduce this, can someone please share a repository that I can clone and run to reproduce?

**Comment by brentvatne** [comment] 2022-09-27 17:55
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/90494/192600582-abfa869b-4bbe-42cd-9164-d8270031a188.png">

https://github.com/brentvatne/try-repro-fonts

<hr />

https://github.com/expo/expo/pull/19234 is the only diff between 10.2.0 and 10.2.1 and would not cause this type of issue. I'll leave this issue open because it seems multiple people have experienced this issue at the same time, but as I said above I need a way to reproduce this

**Comment by uwemneku** [comment] 2022-09-27 21:29
Hello, @brentvatne I was able to reproduce the issue when trying to load font from ```@expo-google-fonts```
Here is the repo. https://github.com/uwemneku/wintinkin_quiz

While deduging, I noticed that adding a useEffect that takes ```fontsLoaded``` as a dependency throws an error saying 
```Rendered more hooks than during the previous render```

**Comment by brentvatne** [comment] 2022-09-27 21:32
I see what is happening here:

```
expo-font@~10.2.0:
  version "10.2.0"
  resolved "https://registry.yarnpkg.com/expo-font/-/expo-font-10.2.0.tgz#881f767e13b2b534a4d3ffaedcf675ce6b63439d"
  integrity sha512-2V4EcpmhNoppaLn+lPprZVS+3bmV9hxLPKttKh2u8ghjH/oX9bv3u4JVo77SYh0EfrWO4toqVyXn8pXH8GpbIg==
  dependencies:
    fontfaceobserver "^2.1.0"

expo-font@~10.2.1:
  version "10.2.1"
  resolved "https://registry.yarnpkg.com/expo-font/-/expo-font-10.2.1.tgz#c13e65e864befaa4710504096b68635c6f7e48d8"
  integrity sha512-sxy5GrdtY+Ka8Wo5wnrcFFeO6MbYC6Dris5wMLqshvVK6BneJNMUsFvwRfvVgg0TzsmMAc3Rlca2xyZ8ettinw==
  dependencies:
    fontfaceobserver "^2.1.0"
```

there are two versions of `expo-font` in the project - one from the `expo` package and one that is a direct dependency in your package.json. if you update the `expo` package to `46.0.13` it will resolve the issue.

**Comment by uwemneku** [comment] 2022-09-27 21:44
Thanks @brentvatne. Upgrading expo to ```46.0.13``` fixed the issue

**Comment by brentvatne** [comment] 2022-09-27 21:44
I reverted the version of expo-font that is installed to `~10.2.0`. With this change, if your lockfile already has 10.2.0 installed due to lockfile being generated prior to the most recent release, then `npx expo install expo-font` will install 10.2.0. If you have 10.2.1 in lockfile, then 10.2.1 will be installed.

Thanks for the info @uwemneku!

**Closed by brentvatne** 2022-09-27 21:44 UTC
Labels: needs more info
