### ISSUE TITLE
Expo Camera - onBarcodeScanned does not fire after granting permission on first open (and mounting) after a fresh install

### ISSUE THREAD

**Issue by robinderozario** [expo/expo#28758] opened 2024-05-10 15:20 UTC
### Minimal reproducible example

https://github.com/robinderozario/CameraExample

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Steps to reproduce (using the minimal reproducible example).

1. After a fresh install of the app, open it, and grant permission using the native prompt.
2. Try scanning a barcode. Note that `onBarcodeScanned` is not called.
3. Close and reopening the app. Now `onBarcodeScanned` is successfully called when pointing at a barcode.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.8.0 - /usr/local/bin/node
      npm: 10.2.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.2 => 51.0.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 7.7.0
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by alanjhughes** [comment] 2024-05-10 16:16
Hi - can you provide an example barcode that is not scanning?

**Comment by robinderozario** [comment] 2024-05-10 16:32
Sure thing. Thanks for looking into this so quickly!

<img width="447" alt="Example_barcode" src="https://github.com/expo/expo/assets/66564342/f919eab9-0eca-4572-be2a-e1bea31c975e">

**Comment by alanjhughes** [comment] 2024-05-10 20:59
This issue is also fixed by following the example from our docs. The reproducible example project does this

```typescript
   ...
  const [permission, requestPermission] = useCameraPermissions();

  if (!permission) {
    // Camera permissions are still loading.
    return <View />;
  }

  <CameraView
        style={styles.camera}
        facing={"back"}
        onBarcodeScanned={onBarcodeScanned}
        barcodeScannerSettings={{
          barcodeTypes: ["ean13", "ean8", "upc_a"],
          interval: 1000,
        }}
      >
    {!permission.granted ? (
      <View
        style={{
          flex: 1,
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Text>No access to camera</Text>
        <Button onPress={requestPermission} title="Give permission" />
      </View>
    ) : null}
  </CameraView>
```
Which is incorrect and doesn't make sense because the camera has to render for it's children to render and that should not happen if you don't have permission. 

Doing this as shown in our docs

```typescript
export default function App() {
  const [facing, setFacing] = useState('back');
  const [permission, requestPermission] = useCameraPermissions();

  if (!permission) {
    // Camera permissions are still loading.
    return <View />;
  }

  if (!permission.granted) {
    // Camera permissions are not granted yet.
    return (
      <View style={styles.container}>
        <Text style={{ textAlign: 'center' }}>We need your permission to show the camera</Text>
        <Button onPress={requestPermission} title="grant permission" />
      </View>
    );
  }

  function toggleCameraFacing() {
    setFacing(current => (current === 'back' ? 'front' : 'back'));
  }

  return (
    <View style={styles.container}>
      <CameraView style={styles.camera} facing={facing}>
        <View style={styles.buttonContainer}>
          <TouchableOpacity style={styles.button} onPress={toggleCameraFacing}>
            <Text style={styles.text}>Flip Camera</Text>
          </TouchableOpacity>
        </View>
      </CameraView>
    </View>
  );
}
```
Works correctly for all of the issues you opened except the one that would require you to prompt the user to enable the permission from settings.

**Closed by alanjhughes** 2024-05-10 20:59 UTC
Labels: needs review

**Comment by robinderozario** [comment] 2024-05-13 09:42
I see, that makes sense. Thanks for explaining.

I personally prefer to use the native request prompt from iOS over showing the custom "request permission" component as a default. Triggering the native prompt requires the CameraView component to be mounted even when no permission has been granted yet. I found that simply calling "requestPermission()" when the screen mounts solves all the issues I was experiencing. I.e., the permission variable not updating + the barcode not scanning: after accepting the native prompt.

`
useEffect(() => {
    requestPermission();
}, []);
`

Since "requestPermission()" does not raise a request pop-up, and since it does not do anything when permission cannot be asked again, this seems like a perfectly okay "workaround". At least for my use case.
