### ISSUE TITLE
Notifications.getDevicePushTokenAsync() crashes expo

### ISSUE THREAD

**Issue by hughbe** [expo/expo#2023] opened 2018-07-23 13:27 UTC
### Attention

The following code crashes
```
import { Constants, Notifications, Permissions } from 'expo';
export default class MainPage extends React.Component {
    async registerForPushNotifications() {
        const { status } = await Permissions.getAsync(Permissions.NOTIFICATIONS);

        if (status !== 'granted') {
            const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
            if (status !== 'granted') {
                return;
            }
        }

        const expoPushToken = await Notifications.getExpoPushTokenAsync();
        await AsyncStorage.setItem('ExpoPushToken', expoPushToken);

        const { data: token, type: platform } = await Notifications.getDevicePushTokenAsync();
          alert(data);
          alert(type);

        return expoPushToken;
    }

    async componentDidMount() {
        const token = await this.registerForPushNotifications();
    }

    render() {
        return null;
    }
}
```
  
### Steps to Reproduce

See code above and run in Expo client

### Expected Behavior

No crash

### Actual Behavior

Expo client crashes

**Comment by sjchmiela** [comment] 2018-07-23 15:59
Hi @hughbe!

I was able to reproduce the issue on iOS, on a real device with SDK 28 and here's [the Snack](https://snack.expo.io/HJf9pwm4X). Please, add such details next time you post the issue, it will help us debug your issue faster. 🙂 

Regarding the issue, please note that Expo documentation on Notifications states two important things:

1. [`getDevicePushTokenAsync()`](https://docs.expo.io/versions/v28.0.0/sdk/notifications#exponotificationsgetdevicepushtokenasyncconfig) requires an argument — a _config_ object with `gcmSenderId` string property. When I was testing the code it looked like providing an empty object to the function call prevented Expo Client from crashing.
2. `Notifications.getDevicePushTokenAsync()` is listed under section [Standalone App Only](https://docs.expo.io/versions/v28.0.0/sdk/notifications#standalone-app-only), so probably it will only return meaningful results when app is archived to a standalone IPA/APK. See [Building Standalone Apps](https://docs.expo.io/versions/v28.0.0/distribution/building-standalone-apps) guide for more information on standalone apps.

Although you should have been calling the function with the `config` argument, Expo Client shouldn't really crash due to not doing this. I'll submit a PR fixing this behavior, thanks for creating this issue! 👍

**Comment by terribleben** [comment] 2018-07-24 17:56
fix landed internally, will go out with SDK 29.

**Closed** 2018-07-25 10:40 UTC
Labels: project: ios-runtime, project: sdk, status: pending
