### ISSUE TITLE
Error: Permissions module not found. Are you sure that Expo modules are properly linked?

### ISSUE THREAD

**Issue by arberK** [expo/expo#13495] opened 2021-07-05 14:08 UTC
### Summary

I updated all the expo dependencies (ink. `react-native-unimodules `at ver 0.14.1) in my bare react-native app. Since then, I'm having troubles when a module tries to fetch the permissions. 
"` Error: Permissions module not found. Are you sure that Expo modules are properly linked?`"

There is no documentation regarding the new module `expo-modules-core` (also installed). Did I miss something ?

Might have been caused by [#12961](https://github.com/expo/expo/pull/12961) @tsapeta 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Environment

    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.15.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: 0.64.2 => 0.64.2 

### Reproducible demo or steps to reproduce from a blank project

  const {status} = await Notifications.requestPermissionsAsync();

**Comment by yernandus** [comment] 2021-07-05 14:37
same here, Error: Permissions module is null. Are you sure all the installed Expo modules are properly linked?

**Comment by josiasMO** [comment] 2021-07-05 15:07
Same issue for me. I'm trying to revert some packages to previous versions, but no success so far.

**Comment by yernandus** [comment] 2021-07-05 15:17
I have updated all expo related libs and now everything works. I am use bare react native

**Comment by josiasMO** [comment] 2021-07-05 15:21
@yernandus can you post here your dependencies section from package.json?
I want to compare my expo packages to see which one I need to update.

**Comment by josiasMO** [comment] 2021-07-05 15:39
Found the solution for me. I had to update expo-notifications:

``` 
npm install expo-notifications@0.12.2
```

**Comment by daveslutzkin** [comment] 2021-07-06 01:18
I just added expo-notifications to a bare app, followed the instructions (`pod install`), tried calling `Notifications.getPermissionsAsync()`, got this error.

**Comment by daveslutzkin** [comment] 2021-07-06 01:34
None of the 0.12 series work, but downgrading to 0.11.6 of `expo-notifications` gets past this error.

**Comment by c-mcdonald** [comment] 2021-07-06 04:58
I'm seeing this as well with expo-camera whilst trying to build on iOS - reporting the below:

`Unable to resolve module unimodules-pmerissions-interface /node_modules/expo-camera-build/Camera.types.js: unimodules-permissions-interface could not be found within the project`

Builds successfully on Android though. This is on a project that worked fine on SDK 41 and now fails at build after upgrading to SDK 32. Using bare workflow.

**Comment by josiasMO** [comment] 2021-07-06 12:59
@daveslutzkin the `expo-notifications` 0.12.2 worked for me, but I had to update `expo` to v42.0.0 as well.

**Comment by brentvatne** [comment] 2021-07-07 03:01
can someone share a minimal reproducible example of this issue?

i believe that there may be a library with an incorrect dependency. we collapsed interfaces into a single package and removed expo-permissions from react-native-unimodules in this release.

you can work around it by installing whatever package is listed as missing, eg: `expo install unimodules-permissions-interface` and/or `expo install expo-permissions`. a reproducible example would be helpful for us to resolve the underlying issue, though

**Comment by daveslutzkin** [comment] 2021-07-07 03:16
For me it was complaining about constants, I tried installing it explicitly but no dice - same error. I don't have a repro sorry, I ended up using a different push library.

**Comment by wbroek** [comment] 2021-07-07 14:32
Got the same with the imagePicker in my project with unimodules. Tried different things like different versions of the package, unimodules, excluding the expo-permission but the permission interface cannot be found.

Made a test project @brentvatne which return the error on iOS and Android that there is no permission interface: https://github.com/wbroek/permissionTest

We are on version 0.13 of unimodules because of https://github.com/expo/expo/issues/13168 so now 0.13 and 0.14 are not working for us.

**Comment by daveslutzkin** [comment] 2021-07-09 03:39
I was wrong earlier when I said `expo-contacts` and `expo-location` were working for us - they're broken too. Both give the Permissions error from the top of thread. Manually installing `expo-permissions` with `expo add expo-permissions` doesn't make a difference.

**Comment by daveslutzkin** [comment] 2021-07-09 03:50
Downgrading expo-contacts to 8.6.0 and expo-location to 11.0.0 (which requires changing to deprecated methods) avoids the issue.

**Comment by brentvatne** [comment] 2021-07-09 05:24
@wbroek - the repository works fine on react-native-unimodules 0.14.

@daveslutzkin - can you confirm that your issue is with the latest version of expo-* packages and an old version of react-native-unimodules?

i'd like to close this issue because it is only happening, as far as i know, if you haven't yet updated react-native-unimodules.

**Comment by daveslutzkin** [comment] 2021-07-09 06:01
@brentvatne correct, thanks. Bitten by semver! My react-native-unimodules was on `~0.13` which obviously won't bump to 0.14. I guess I wouldn't usually expect a minor version bump to break things like that, might be worth adding a line to the error message.

**Comment by wbroek** [comment] 2021-07-09 06:52
@brentvatne yes works with 0.14, we where on 0.13 because of https://github.com/expo/expo/issues/13168 and could not find that they where not compatible with 0.13 was that mentioned?
Can be closed for me

**Comment by c-mcdonald** [comment] 2021-07-13 00:21
Thanks @brentvatne bumped react-native-unimodules to 0.14.5 and now works. Thanks

**Closed** 2021-07-23 17:45 UTC
Labels: Notifications, Permissions, needs repro, needs review
