### ISSUE TITLE
Le module sdk est introuvable dans nodes_modules lors de l'execution mais pourtant j'ai installé ça

### ISSUE THREAD

**Issue by Marivaux97** [expo/expo#12075] opened 2021-03-03 01:31 UTC
### Summary

Salut
Je veux utiliser le module 'expo-speech' dans mon projet react native expo, je l'ai installé donc en faisant expo install expo-speech et l'installation est terminée avec succes, mais soudain quand je veux l'utiliser je reçois une erreur qui dit: 
Unable to resolve module expo-speech from C:\Users\Marivaux BAMPENDE\Documents\Mes Projets\appliMobileExpo1\myapp\components\About.js: expo-speech could not be found within the project or in these directories:
  node_modules

Aidez moi s'il vous plait comment resoudre ce probleme merci:

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Environment

expo diagnostic

### Reproducible demo or steps to reproduce from a blank project

Unable to resolve module expo-speech from C:\Users\Marivaux BAMPENDE\Documents\Mes Projets\appliMobileExpo1\myapp\components\About.js: expo-speech could not be found within the project or in these directories:
  node_modules

Veuilles m'aider svp

**Comment by brentvatne** [comment] 2021-03-04 00:34
hi there! are you sure it was installed in the correct project and that the installation was successful?

if you can't figure it out, please try creating a small example project that you can share with us (https://stackoverflow.com/help/minimal-reproducible-example) and we can help to investigate :)

i will close this issue because it is not a bug in expo, but i will pay attention to your response

**Closed by brentvatne** 2021-03-04 00:34 UTC
Labels: needs review
