### ISSUE TITLE
trying to ios:build, but getting cert errors

### ISSUE THREAD

**Issue by arnorhs** [expo/expo#1153] opened 2017-12-22 11:05 UTC
hey there

i'm trying to run `exp ios:build`, and ran into some cert problems. i've tried clearing with `exp ios:build -c`, which made me re-enter my login info, but i still get the same error:

```
[exp] Generating distribution certificate...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to fetch distribution certificate. Request ID c2565520-e705-11e7-bb62-258c2574a374, message: Unable to add new certificate to your account (maximum number reached). Please delete one of your certificates or upload an existing one.
```

i've tried having exp handle my cert for me, and i've also tried uploading a new one - but always run into a similar problem.

**Comment by ShMcK** [comment] 2017-12-22 19:32
Same issue.

**Comment by quinlanj** [comment] 2017-12-22 22:36
@arnorhs @ShMcK , we are starting to move away from handling certs on our remove servers, and instead, are moving towards local authentication. Could you guys give that a try to see if it unblocks you? It can be run with by installing the latest version of exp: `npm i -g exp` and running `exp build:ios --local-auth`. More details in this blog post under Two factor authentication: https://blog.expo.io/introducing-support-for-build-dashboards-apple-two-factor-authentication-81d288a3d03

**Comment by ShMcK** [comment] 2017-12-22 23:10
I think for me the issue is related to having an existing app in the app store that the Expo app is meant to replace.

```
 Reason:Multiple profiles found with the name
```

Not sure how to resolve this. Running `npm build:ios -c` doesn't seem to clear existing credentials.

**Comment by quinlanj** [comment] 2017-12-23 00:02
@ShMcK try `exp build:ios --local-auth -c` instead of `npm`

**Comment by stanwilsonjr** [comment] 2017-12-23 03:44
@quinlanj  Having the same issue even with non 2FA


```[exp] Validating Apple credentials...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials. Request ID ad79c690-e792-11e7-826d-01bfd05be7c1, message: Internal error occurred. Please try again in a few minutes or contact support.

**Comment by terribleben** [comment] 2017-12-27 17:42
Hi, @arnorhs, this message from your log

> Unable to add new certificate to your account (maximum number reached). Please delete one of your certificates or upload an existing one.

Suggests that you might try removing one of your existing certificates. Have you tried that?

**Comment by ShMcK** [comment] 2017-12-28 18:19
Had a typo earlier. It seems running `-c` with `--local-auth` does not clear your credentials.

Running `-c` without `--local-auth` clears credentials. The two are currently incompatible.

Is there another way to clear certificates?

**Comment by fxfactorial** [comment] 2017-12-28 18:24
@ShMcK Hi, the a new release of `exp` 47.2.0 ensures that `-c` clears credentials.

**Comment by ShMcK** [comment] 2017-12-28 18:26
@fxfactorial, that's great news. Thanks! When will 47.2 be released?

**Comment by fxfactorial** [comment] 2017-12-28 22:09
@ShMcK Recently Released

**Comment by c316** [comment] 2017-12-29 16:13
I have 47.2.2 and I'm not able to build:ios.

I get this same message below if I use --local-auth or not.

```
myAppDirectory $ exp build:ios -c --local-auth 
[exp] DEPRECATED: --local-auth and --expert-auth are no-ops now, will be removed in future
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Removed existing credentials
? How would you like to upload your credentials?
 Expo handles all credentials, you can still provide overrides

We need your Apple ID/password to manage certificates and
provisioning profiles from your Apple Developer account.

Note: Expo does not keep your Apple ID or your Apple password.

? What's your Apple ID? me@gmail.com
? Password? ************
[exp] Validating Credentials...
[exp] Error while gathering & validating credentials
[exp] undefined
[exp] undefined
```

**Comment by fxfactorial** [comment] 2017-12-29 16:14
@c316 Hi, thanks for the report. Aware and trying to fix, about to push a version to help with debugging, in a few minutes.

**Comment by fxfactorial** [comment] 2017-12-29 16:27
@c316 Can you try again, `47.2.4` and with `EXPO_DEBUG=true` as environment variable. Much appreciated.

**Comment by ShMcK** [comment] 2017-12-29 16:48
@c316, it may be that gmail cannot be used as a valid apple id.

**Comment by fxfactorial** [comment] 2017-12-29 16:49
A gmail based ID is fine. Please try again with the new version.

**Comment by dackom** [comment] 2017-12-29 16:53
I have 47.2.4 and get exact same thing:

[exp] Validating Credentials...
[exp] Error while gathering & validating credentials
[exp] undefined

**Comment by fxfactorial** [comment] 2017-12-29 16:54
@dackom can you run the program with EXPO_DEBUG=true and the full output.

**Comment by dackom** [comment] 2017-12-29 16:57
Is this correct way how I am doing:

 > EXPO_DEBUG=true
 > exp build:ios  
[exp] Making sure project is set up correctly...
/[exp] Warning: You are using npm version 5.6.0. There may be bugs in this version, use it at your own risk. We recommend version 4.6.1.
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
? How would you like to upload your credentials?
 Expo handles all credentials, you can still provide overrides

We need your Apple ID/password to manage certificates and
provisioning profiles from your Apple Developer account.

Note: Expo does not keep your Apple ID or your Apple password.

? What's your Apple ID? dacko.m@gmail.com
? Password? *********
[exp] Validating Credentials...
[exp] Error while gathering & validating credentials
[exp] undefined
[exp] Set EXPO_DEBUG=true in your env to view the stack trace.

Sorry for stupid question, but how do I set-up this EXPO_DEBUG=true?

**Comment by c316** [comment] 2017-12-29 16:59
@dackom I believe you just need to run ```export EXPO_DEBUG=true``` before you run the ```exp build:ios``` command

**Comment by fxfactorial** [comment] 2017-12-29 17:00
You can do: `EXPO_DEBUG=true exp build:ios`

**Comment by dackom** [comment] 2017-12-29 17:01
Heh. Yeah, Got two more lines:

[exp] Validating Credentials...
[exp] Error while gathering & validating credentials
[exp] [object Object]
[exp] undefined
[exp] undefined

**Comment by c316** [comment] 2017-12-29 17:03
This is what I get now on 47.2.4

```
myAppDirector $ exp build:ios
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[ { action: 'ruby_dir',
    path: '/Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx',
    doesExist: false },
  { action: 'app_management',
    path: '/Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/app_management',
    doesExist: true },
  { action: 'fetch_cert',
    path: '/Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/fetch_cert',
    doesExist: true },
  { action: 'fetch_new_provisioning_profile',
    path: '/Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/fetch_new_provisioning_profile',
    doesExist: true },
  { action: 'fetch_push_cert',
    path: '/Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/fetch_push_cert',
    doesExist: true },
  { action: 'validate_apple_certs',
    path: '/Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/validate_apple_certs',
    doesExist: true },
  { action: 'validate_apple_credentials',
    path: '/Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/validate_apple_credentials',
    doesExist: true },
  { action: 'validate_apple_push_certs',
    path: '/Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/validate_apple_push_certs',
    doesExist: true } ]
? How would you like to upload your credentials?
 Expo handles all credentials, you can still provide overrides

We need your Apple ID/password to manage certificates and
provisioning profiles from your Apple Developer account.

Note: Expo does not keep your Apple ID or your Apple password.

? What's your Apple ID? me@gmail.com
? Password? **************
[exp] Validating Credentials...
[exp] Error while gathering & validating credentials
[exp] [object Object]
[exp] undefined
[exp] undefined
```

**Comment by fxfactorial** [comment] 2017-12-29 17:08
@c316 Thanks for your patience and help, can we try `47.2.5`.

**Comment by c316** [comment] 2017-12-29 17:12
@fxfactorial 

Here you go

```
[exp] Validating Credentials...
[exp] Error while gathering & validating credentials
[exp] [object Object]
[exp] {"result":"failure","reason":"Could not understand JSON reply from Ruby local auth scripts","rawDump":"/Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/definition.rb:252:in `rescue in lock': There was an error while trying to write to Gemfile.lock. It is likely that  (Bundler::InstallError)\nyou need to allow write permissions for the file at path: \n/Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/lib/vendor/Gemfile.lock\n\tfrom /Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/definition.rb:237:in `lock'\n\tfrom /Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/environment.rb:34:in `lock'\n\tfrom /Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/runtime.rb:44:in `setup'\n\tfrom /Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler.rb:122:in `setup'\n\tfrom /Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/setup.rb:18:in `<top (required)>'\n\tfrom /Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'\n\tfrom /Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'\n\tfrom /Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'\n"}
[exp] undefined
[exp] undefined

```

**Comment by dackom** [comment] 2017-12-29 17:13
Just to confirm, I've got exactly same thing as @c316 with 47.2.5 ...

**Comment by fxfactorial** [comment] 2017-12-29 17:24
Thank you @c316  and @dackom , can you try `yarn global remove exp` and then trying with `npm i -g exp`?

**Comment by dackom** [comment] 2017-12-29 17:24
Hmm.. I don't have yarn installed at all.. should I remove it with npm first?

**Comment by fxfactorial** [comment] 2017-12-29 17:26
@dackom For wherever your `node_modules` is, can you do: 

```
$ whoami
$ ls -halt node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/lib/vendor
```

I am not sure why permissions would be messed up

**Comment by c316** [comment] 2017-12-29 17:33
I used yarn to install exp because I can't get it to work with npm (see below block for error)

```
~ $ sudo npm i -g exp

> @expo/traveling-fastlane-darwin@1.0.17 preinstall /usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin
> node platform.js

/usr/local/bin/exp -> /usr/local/lib/node_modules/exp/bin/exp.js

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/exp/node_modules/spawn-sync
> node postinstall


> @expo/ngrok@2.3.0 postinstall /usr/local/lib/node_modules/exp/node_modules/@expo/ngrok
> node ./postinstall.js

ngrok - error unpacking binary { Error: EACCES: permission denied, open '/usr/local/lib/node_modules/exp/node_modules/@expo/ngrok/bin/ngrok'
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/exp/node_modules/@expo/ngrok/bin/ngrok' }
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-linux@1.0.17 (node_modules/exp/node_modules/@expo/traveling-fastlane-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/traveling-fastlane-linux@1.0.17: wanted {"os":"win32,linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @expo/ngrok@2.3.0 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @expo/ngrok@2.3.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2017-12-29T17_26_58_205Z-debug.log
```

After reinstalling with yarn I get this for the permission query

```
~ $ whoami
me
~ $ ls -halt /Users/me/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/lib/vendor
total 16
drwxr-xr-x  3 root  staff    96B Dec 29 11:32 .bundle
drwxr-xr-x  6 root  staff   192B Dec 29 11:32 .
drwxr-xr-x  3 root  staff    96B Dec 29 11:31 ruby
drwxr-xr-x  5 root  staff   160B Dec 29 11:31 ..
-rw-r--r--  1 root  staff   426B Dec 25 06:02 Gemfile
-rw-r--r--  1 root  staff   3.6K Dec 25 06:02 Gemfile.lock
```

**Comment by dackom** [comment] 2017-12-29 17:36
This is getting even stranger now:
npm root -g gives me:
/usr/local/lib/node_modules

When I go there, there is no @expo folder in it. So in parent when I do:
/usr/local/lib > ls -halt node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/lib/vendor 

Returns:

ls: node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.17-osx/lib/vendor: No such file or directory

**Comment by c316** [comment] 2017-12-29 17:39
@dackom Did you remove exp already? If so, that is why you are getting that message

**Comment by dackom** [comment] 2017-12-29 17:39
I removed it, and installed it again. All with -g option.

**Comment by fxfactorial** [comment] 2017-12-29 17:40
@c316 Why is your yarn install running as root? 

@dackom it would be under exp/node_modules

Just pushed another version,

**Comment by c316** [comment] 2017-12-29 17:41
@fxfactorial Not sure. I've always had to use sudo to install any global packages...wonder if that has anything to do with it...

**Comment by fxfactorial** [comment] 2017-12-29 17:42
things under `~/.yarn` should be owned by your user account, not global.

**Comment by dackom** [comment] 2017-12-29 17:50
Installed 47.2.7 ... exp build:ios gives 

[exp] Error while gathering & validating credentials
[exp] [object Object]
[exp] {"result":"failure","reason":"Could not understand JSON reply from Ruby local auth scripts","rawDump":"/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.0.18-osx/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /usr/local/apache-maven/apache-maven-3.2.3/bin in PATH, mode 040777\n{\"result\":\"success\",\"teams\":[{\"status\":\"active\",\"teamId\":\"PKAJXSL5KZ\",\"type\":\"Individual\",\"extendedTeamAttributes\":{},\"teamAgent\":{\"personId\":1012592183,\ ......

Other apple account data...

**Comment by fxfactorial** [comment] 2017-12-29 18:09
@dackom Can you try please: 47.2.8.

**Comment by dackom** [comment] 2017-12-29 18:20
Yeah, it looks like its working. I've got a link to monitor build on web, so I guess it will be fine.

Thank you @fxfactorial .  :)

**Comment by dackom** [comment] 2017-12-29 18:21
Except, that build is now failed, on web:

[10:17:16] Finished 'ios-shell-app' after 9.59 s
done running shell app builder
creating app on dev center
Getting Redis connection...
Got Redis connection...
Waiting to receive message...
Executing command: fastlane produce -u  -b PKAJXSL5KZ -a com.squadmonster.app --skip_itc --app_name Squad Monster --app_version 1.0.8
unable to create app on dev center
Executing command: security delete-keychain /tmp/turtle-agent/727ef283-ecc4-11e7-aa4b-0050568e2416.keychain
Restoring keychain list...
Executing command: security list-keychains -s /private/tmp/turtle-agent/44659856-eb34-11e7-aa4b-0050568e2416.keychain
Restored keychain list.

**Comment by fxfactorial** [comment] 2017-12-29 18:23
Check your apple developer account, under app ID, do you have this listed there?

**Comment by dackom** [comment] 2017-12-29 18:25
Yes, of course. I already builded app month ago or something... and put it on store and everything worked well...

**Comment by fxfactorial** [comment] 2017-12-29 18:26
Did you bump version?

**Comment by dackom** [comment] 2017-12-29 18:27
Yes. 1.0.6 is active build version in itunes connect, this is 1.0.8.

**Comment by c316** [comment] 2017-12-29 19:14
@fxfactorial yea, this is something I've been meaning to fix. Got that fixed now, thanks. 

It seems to be all fixed.

**Comment by robert-newapptech** [comment] 2017-12-29 23:05
I am also running into cert issues as of today. Before running this, I revoked all old certificates. Is there somewhere I need to go to remove one of the "Multiple profiles found with the name"?

`exp --version
47.3.2`

```
EXPO_DEBUG=true exp build:ios -c
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Removed existing credentials
[ { action: 'ruby_dir',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.1-osx',
    doesExist: false },
  { action: 'app_management',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.1-osx/app_management',
    doesExist: true },
  { action: 'fetch_cert',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.1-osx/fetch_cert',
    doesExist: true },
  { action: 'fetch_new_provisioning_profile',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.1-osx/fetch_new_provisioning_profile',
    doesExist: true },
  { action: 'fetch_push_cert',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.1-osx/fetch_push_cert',
    doesExist: true },
  { action: 'validate_apple_certs',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.1-osx/validate_apple_certs',
    doesExist: true },
  { action: 'validate_apple_credentials',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.1-osx/validate_apple_credentials',
    doesExist: true },
  { action: 'validate_apple_push_certs',
    path: '/usr/local/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.2.1-osx/validate_apple_push_certs',
    doesExist: true } ]
? How would you like to upload your credentials?
 Expo handles all credentials, you can still provide overrides

We need your Apple ID/password to manage certificates and
provisioning profiles from your Apple Developer account.

Note: Expo does not keep your Apple ID or your Apple password.

? What's your Apple ID? APPLE_ID
? Password? **********************
[exp] Validating Credentials...
{ action: 'teams attempt retrieval',
  dump: { result: 'success', teams: [ [Object] ] } }
[exp] You have 1 teams
Only 1 team associated with your account, using Team ID: TEAM_ID
{ teamId: 'TEAM_ID' }
? Will you provide your own Distribution Certificate? Let Expo handle the process
? Will you provide your own Push Certificate? Let Expo handle the process
⠦ Now producing files for distCert{ result: 'success',
  certPrivateSigningKey: '-----BEGIN RSA PRIVATE KEY-----\blahblahblah',
  certPassword: 'blahblahblah' }
⠙ Now producing files for pushCert{ result: 'success',
  pushPrivateSigningKey: '-----BEGIN RSA PRIVATE KEY-----\blahblahblah',
  pushPassword: 'blahblahblah' }
⠦ Now producing files for provisioningProfile{ result: 'success',
  name: 'BUNDLE_ID',
  prefix: 'PREFIX' }
⠙ Now producing files for provisioningProfile{ result: 'failure',
  reason: 'Multiple profiles found with the name \'BUNDLE_ID AppStore\'.  Please remove the duplicate profiles and try again. There were errors in the data supplied. Please correct and re-submit.',
  rawDump:
   { responseId: '52cb0354-72d9-48f2-857d-8e8a0b6eafd3',
     resultCode: 35,
     resultString: 'There were errors in the data supplied. Please correct and re-submit.',
     userString: 'Multiple profiles found with the name \'BUNDLE_ID AppStore\'.  Please remove the duplicate profiles and try again.',
     creationTimestamp: '2017-12-29T22:54:57Z',
     protocolVersion: 'QH65B2',
     userLocale: 'en_US',
     requestUrl: 'https://developer.apple.com/services-account/QH65B2/account/ios/profile/createProvisioningProfile.action',
     httpCode: 200,
     validationMessages: [ [Object] ] } }
[exp] Error while gathering & validating credentials
[exp] {}
[exp] Reason:Multiple profiles found with the name 'BUNDLE_ID AppStore'.  Please remove the duplicate profiles and try again. There were errors in the data supplied. Please correct and re-submit., raw:{"responseId":"52cb0354-72d9-48f2-857d-8e8a0b6eafd3","resultCode":35,"resultString":"There were errors in the data supplied. Please correct and re-submit.","userString":"Multiple profiles found with the name 'BUNDLE_ID AppStore'.  Please remove the duplicate profiles and try again.","creationTimestamp":"2017-12-29T22:54:57Z","protocolVersion":"QH65B2","userLocale":"en_US","requestUrl":"https://developer.apple.com/services-account/QH65B2/account/ios/profile/createProvisioningProfile.action","httpCode":200,"validationMessages":[{"validationKey":"provisioningProfileName","validationUserMessage":"Multiple profiles found with the name 'BUNDLE_ID AppStore'.  Please remove the duplicate profiles and try again."}]}
[exp] Error: Reason:Multiple profiles found with the name 'BUNDLE_ID AppStore'.  Please remove the duplicate profiles and try again. There were errors in the data supplied. Please correct and re-submit., raw:{"responseId":"52cb0354-72d9-48f2-857d-8e8a0b6eafd3","resultCode":35,"resultString":"There were errors in the data supplied. Please correct and re-submit.","userString":"Multiple profiles found with the name 'BUNDLE_ID AppStore'.  Please remove the duplicate profiles and try again.","creationTimestamp":"2017-12-29T22:54:57Z","protocolVersion":"QH65B2","userLocale":"en_US","requestUrl":"https://developer.apple.com/services-account/QH65B2/account/ios/profile/createProvisioningProfile.action","httpCode":200,"validationMessages":[{"validationKey":"provisioningProfileName","validationUserMessage":"Multiple profiles found with the name 'BUNDLE_ID AppStore'.  Please remove the duplicate profiles and try again."}]}
    at IOSBuilder._throwIfFailureWithReasonDump (/Users/Edgar/universe/dev/exp/src/commands/build/IOSBuilder.js:354:13)
    at IOSBuilder._callee4$ (/Users/Edgar/universe/dev/exp/src/commands/build/IOSBuilder.js:248:10)
    at tryCatch (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by fxfactorial** [comment] 2017-12-29 23:25
@robert-newapptech Hi Robert, you would need to go to your developer.apple.com account and remove a provisioning profile

**Comment by fourcolors** [comment] 2018-01-02 21:23
@fxfactorial I'm having the same issue. Why do I have extra provisioning profiles?

**Comment by fxfactorial** [comment] 2018-01-02 21:52
You can have only 1 provisioning profile per app. The current behavior is that when you don't have the provisioning profile with us and want exp to manage credentials, then it creates new certs and hence creates a new provisioning profile.

**Comment by fxfactorial** [comment] 2018-01-06 10:04
Is this resolved for you @arnorhs ?

**Comment by terribleben** [comment] 2018-01-17 02:25
Closing - let us know if you think this same issue is unresolved and should remain open.

**Closed by terribleben** 2018-01-17 02:25 UTC
Labels: status: needs more info

**Comment by isthaison** [comment] 2018-02-24 02:23
I have issue
![image](https://user-images.githubusercontent.com/22739578/36624645-45987cae-1944-11e8-973e-09c1f6f192fb.png)
![image](https://user-images.githubusercontent.com/22739578/36624648-50248456-1944-11e8-81ed-fda26f14e62c.png)

**Comment by fxfactorial** [comment] 2018-02-24 02:42
Hi, word descriptions of the problems are usually better than pictures.

1) so you have a paid Apple account ?
2) are you trying to make an enterprise based account ? If so then need to use a flag that tells exp to make enterprise based certs. So would want to do: exp build:ios --apple-enterprise-account

**Comment by isthaison** [comment] 2018-02-26 01:20
Dear Mr. Edgar!
At this time, I am having a project that to build an in-house app, but I
got a trouble with the authentication of push notifications IOS (APNS) I
truly need your help.

I using Apple Developer Enterprise Program to build .ipa with certificate :
certificate iOS Distribution In house , Apple Push Services .Finally, I
have build completed .ipa
I have current done with .ipa file and used https://www.diawi.com/ for
installing apps in reality.
I did receive token, but I could not send
and receive a notification while I was using
https://expo.io/dashboard/notifications and facing issue:
" InvalidCredentials: Expo was unable to establish a secure connection to
the Apple Push Notification service. This potentially is due to an invalid
APNs certificate or token for your Apple developer account; if you have
provided your own APNs certificate or token, carefully verify that it is
for production and is in the format Expo expects."

I am looking forward to hearing from you soon. Please contact me via Skype:
is.thaison@hotmail.com
Yours faithfully
Son Nguyen



============================================================================
Nguyen Thai Son
Designer and Programmer at P & S Software CO., LTD
---------------------------------------------------------------------------
m. +84 976 853 112
e. is.thaison@gmail.com
facebook https://www.facebook.com/is.thaison
w. http://hscooperation.com
a. Binh Duong Province

**Comment by ide** [comment] 2018-02-26 01:35
“Production” certificates refer to those for production apps in the App Store, not in-house IPAs. I suspect that is the issue here.

**Comment by isthaison** [comment] 2018-02-26 01:55
So
I try build ios with  method
[image: Inline image 1]
I using windows 10. You can offer resolve!

============================================================================
Nguyen Thai Son
Designer and Programmer at P & S Software CO., LTD
---------------------------------------------------------------------------
m. +84 976 853 112
e. is.thaison@gmail.com
facebook https://www.facebook.com/is.thaison
w. http://hscooperation.com
a. Binh Duong Province

**Comment by ide** [comment] 2018-02-26 02:06
I can’t see the image you uploaded but make sure you have a paid Apple developer account and are making an app to distribute through the App Store.

**Comment by isthaison** [comment] 2018-02-26 02:14
![image](https://user-images.githubusercontent.com/22739578/36650289-348d05f0-1ad5-11e8-8ab5-71302ff1d3d9.png)
![capture](https://user-images.githubusercontent.com/22739578/36650328-6b239e44-1ad5-11e8-8fa2-aee87bcd2457.PNG)

**Comment by ide** [comment] 2018-02-26 03:51
It looks like you need to be the Agent or and Admin for you Apple developer team, and the team needs to be a regular team that can publish to the App Store.

**Comment by gregbenner** [comment] 2018-03-01 20:44
https://developer.apple.com/account/ios/profile/ delete provision certificates or any mentioned in the build tool (infact it's safe to delete them all as Expo will recreate them)

**Comment by Jonathan0wh** [comment] 2019-05-27 15:48
@gregbenner You're my life saver!

**Comment by feliperaul** [comment] 2019-09-24 16:30
Expo definitely needs to improve the handling of these certificates and profiles ... their value proposition is abstract all this complexity, but we feel a lot of pain with the current handling they are doing. A lot of bugs, error messages, push notifications not working.
