### ISSUE TITLE
Issue with bold text in Oneplus and Oppo phones.

### ISSUE THREAD

**Issue by pulkonet** [expo/expo#1186] opened 2017-12-31 08:05 UTC
![whatsapp image 2017-12-31 at 13 32 41](https://user-images.githubusercontent.com/24983958/34460247-25214f54-ee2f-11e7-9a2a-5f6a2fa95cf1.jpeg)
This text gets omitted in the expo app due to unsupported OnePlus Slate font, and it persists over all expo apps using OnePlus Slate font. Attached Screenshot is from expo mobile app. It works fine with other fonts such as Roboto etc

**Comment by EvanBacon** [comment] 2017-12-31 17:52
Have you seen this yet? https://forums.expo.io/t/text-cut-off-on-oneplus-device/4999

**Comment by pulkonet** [comment] 2017-12-31 17:59
Yes I have seen it. The suggested things there are workarounds and not the actual solution, it not a recap native issue. Because if I build an app and don't use expo it works just fine.

**Comment by ide** [comment] 2018-01-02 23:42
Is the OnePlus Slate font included on the device or do you install it with the Expo.Font API? If the latter, that API installs fonts different than React Native and might have some unintentional differences in behavior. It seems like the font is supported, though, since some of the characters are rendered.

**Comment by pulkonet** [comment] 2018-01-02 23:45
Former though. The font is the default font on my OnePlus device. And the
font might be supported but not very well in this case.

**Comment by ide** [comment] 2018-01-02 23:56
Hm, thanks for the details, I'm not sure what the issue could be though. Would need to dive in deeper and find a small repro, possibly in the native code or native config.

**Comment by Jense5** [comment] 2018-02-22 20:30
Is there going to be a fix for this?

**Comment by N1ghtly** [comment] 2018-03-07 13:58
Any news on this issue?

**Comment by gnprice** [comment] 2018-10-03 19:02
There's been detailed discussion of this issue here: facebook/react-native#15114 (It's marked as closed, but don't let that fool you.)

Still not clear what the cause is, or how to consistently work around it AFAICT. But that seems to be the issue to follow for discussion.

**Comment by vitorreis** [comment] 2018-10-23 09:09
seems to be related to #21729

**Closed** 2019-02-07 21:00 UTC
Labels: project: android-runtime, project: sdk
