### ISSUE TITLE
Can't compile on Android (build failed)

### ISSUE THREAD

**Issue by JB-CHAUVIN** [expo/expo#3266] opened 2019-01-19 14:08 UTC
Hello,

I am compiling my app with Expo's server, but I got the following error : 

[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] A problem occurred configuring project ':ReactAndroid'.
[stderr] > Failed to notify project evaluation listener.
[stderr]    > Failed to install the following Android SDK packages as some licences have not been accepted.
[stderr]         platforms;android-27 Android SDK Platform 27
[stderr]         build-tools;27.0.3 Android SDK Build-Tools 27.0.3
[stderr]      To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
[stderr]      Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
[stderr]      
[stderr]      Using Android SDK: /usr/local/android-sdk-linux
[stderr]    > Failed to install the following Android SDK packages as some licences have not been accepted.
[stderr]         platforms;android-27 Android SDK Platform 27
[stderr]         build-tools;27.0.3 Android SDK Build-Tools 27.0.3
[stderr]      To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
[stderr]      Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
[stderr]      
[stderr]      Using Android SDK: /usr/local/android-sdk-linux
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 12s

Any ideas ?

Build reference : https://expo.io/builds/f506c849-fef4-4a53-9f99-8278c7358b17 

Best regards

**Comment by nogalosa** [comment] 2019-01-19 15:06
I'm having same issue.

**Comment by shabeebk** [comment] 2019-01-19 15:21
I took has the same issue now. Is this going to be fixed any soon?

This is the error which I got from the build logs.

It has failed at running gradle

Checking the license for package Android SDK Build-Tools 28.0.3 in /usr/local/android-sdk-linux/licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] A problem occurred configuring project ':app'.
[stderr] > Failed to install the following Android SDK packages as some licences have not been accepted.
[stderr]      build-tools;28.0.3 Android SDK Build-Tools 28.0.3
[stderr]   To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
[stderr]   Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
[stderr]   
[stderr]   Using Android SDK: /usr/local/android-sdk-linux
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 15s

**Comment by boscoeut** [comment] 2019-01-19 18:02
Same Issue

[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] A problem occurred configuring project ':ReactAndroid'.
[stderr] > Failed to notify project evaluation listener.
[stderr]    > Failed to install the following Android SDK packages as some licences have not been accepted.
[stderr]         platforms;android-27 Android SDK Platform 27
[stderr]         build-tools;27.0.3 Android SDK Build-Tools 27.0.3
[stderr]      To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
[stderr]      Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
[stderr]      
[stderr]      Using Android SDK: /usr/local/android-sdk-linux
[stderr]    > Failed to install the following Android SDK packages as some licences have not been accepted.
[stderr]         platforms;android-27 Android SDK Platform 27
[stderr]         build-tools;27.0.3 Android SDK Build-Tools 27.0.3
[stderr]      To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
[stderr]      Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
[stderr]      
[stderr]      Using Android SDK: /usr/local/android-sdk-linux
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 14s

**Comment by shabeebk** [comment] 2019-01-20 05:54
It looks like this issue is resolved somehow. I am now able to build the standalone.

**Comment by serhiipalash** [comment] 2019-01-20 11:18
We are having this issue too. 

It looks like this an is issue with configuring `turtle-cli` [DockerFile](https://github.com/expo/turtle/blob/3a5562108542247869b4af21c571155e1645f71c/Dockerfile).

Maybe this fix for similar issue from CircleCI can help to fix it
https://github.com/circleci/circleci-images/commit/1ac3ee07c1142291cafaf74c21b04fed46016a57

https://discuss.circleci.com/t/licences-for-android-build-tools-not-accepted/17285

**Comment by boraerbasoglu** [comment] 2019-01-20 20:05
Same here

**Comment by boraerbasoglu** [comment] 2019-01-20 21:00
We need quick fix we cannot upload our APK because of that. We believe expo team

**Comment by serhiipalash** [comment] 2019-01-20 22:05
> We need quick fix

@boraerbasoglu you can try to publish, if your fix doesn't relay on updating native modules.

**Comment by moddatherrashed** [comment] 2019-01-21 00:07
I have the same issue, and i need a quick solution too, i have to go live in maximum 2 days !!!!
Thanks guys 
```
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] A problem occurred configuring project ':ReactAndroid'.
[stderr] > Failed to notify project evaluation listener.
[stderr]    > Failed to install the following Android SDK packages as some licences have not been accepted.
[stderr]         platforms;android-27 Android SDK Platform 27
[stderr]         build-tools;27.0.3 Android SDK Build-Tools 27.0.3
[stderr]      To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
[stderr]      Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
[stderr]      
[stderr]      Using Android SDK: /usr/local/android-sdk-linux
[stderr]    > Failed to install the following Android SDK packages as some licences have not been accepted.
[stderr]         platforms;android-27 Android SDK Platform 27
[stderr]         build-tools;27.0.3 Android SDK Build-Tools 27.0.3
[stderr]      To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
[stderr]      Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
[stderr]      
[stderr]      Using Android SDK: /usr/local/android-sdk-linux
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 11s
Error: Process exited with non-zero code: 1
    at ChildProcess.child.on (/app/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by Sivli-Embir** [comment] 2019-01-21 02:21
Same issue. Not critical on this end but would be nice.

**Comment by RaymondKen** [comment] 2019-01-21 03:01
Issue solved for me, I updated expo to 30.0.1 in my package.json.

**Comment by kibot914** [comment] 2019-01-21 04:15
Same issue, please fix it asap

**Comment by bonham000** [comment] 2019-01-21 04:18
Same issue

**Comment by kibot914** [comment] 2019-01-21 04:19
For your references : 
https://forums.expo.io/t/cant-compile-android-to-build-this-project-accept-the-sdk-license-agreements-and-install-the-missing-components-using-the-android-studio-sdk-manager/18340

The problem probably can only fixed on expo building server

**Comment by JakeHedman** [comment] 2019-01-21 07:09
Same issue. Also seeing some warning before the error:
```
Parallel execution with configuration on demand is an incubating feature.
> Configure project :app
AWS Device Farm Plugin version 1.3
Checking the license for package Android SDK Build-Tools 28.0.3 in /usr/local/android-sdk-linux/licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
Checking the license for package Android SDK Platform 27 in /usr/local/android-sdk-linux/licenses
Warning: License for package Android SDK Platform 27 not accepted.
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] A problem occurred configuring project ':app'.
[stderr] > Failed to install the following Android SDK packages as some licences have not been accepted.
[stderr]      platforms;android-27 Android SDK Platform 27
[stderr]      build-tools;28.0.3 Android SDK Build-Tools 28.0.3
[stderr]   To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
[stderr]   Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
[stderr]   
[stderr]   Using Android SDK: /usr/local/android-sdk-linux
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 13s
Error: Process exited with non-zero code: 1
    at ChildProcess.child.on (/app/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by nouraien** [comment] 2019-01-21 07:58
The same here!
Updating expo did not solve the problem
`[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] A problem occurred configuring project ':ReactAndroid'.
[stderr] > Failed to notify project evaluation listener.
[stderr]    > Failed to install the following Android SDK packages as some licences have not been accepted.
[stderr]         platforms;android-27 Android SDK Platform 27
[stderr]         build-tools;27.0.3 Android SDK Build-Tools 27.0.3
[stderr]      To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
[stderr]      Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
[stderr]      
[stderr]      Using Android SDK: /usr/local/android-sdk-linux
[stderr]    > Failed to install the following Android SDK packages as some licences have not been accepted.
[stderr]         platforms;android-27 Android SDK Platform 27
[stderr]         build-tools;27.0.3 Android SDK Build-Tools 27.0.3
[stderr]      To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
[stderr]      Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
[stderr]      
[stderr]      Using Android SDK: /usr/local/android-sdk-linux
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 11s
Error: Process exited with non-zero code: 1
    at ChildProcess.child.on (/app/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)`

**Comment by nouraien** [comment] 2019-01-21 07:59
The same here!
Updating expo did not solve the problem.

**Comment by mlrminds** [comment] 2019-01-21 08:34
Same issue here.

**Comment by gilbertKaradja** [comment] 2019-01-21 08:41
Updating expo cli didn't fix it for me, Someone on the forums mentioned a fix by accepting licenses locally. Not sure how that can fix a remote build machine.

**Comment by dsokal** [comment] 2019-01-21 09:13
Hey guys,
sorry for the inconvenience. I'm working on the fix right now.

**Comment by ebrahimhassan121** [comment] 2019-01-21 10:53
i had the same issue 
but after opening android studio and opened sdk tools to install google play licensing library
it works fine

**Comment by theRealSheng** [comment] 2019-01-21 11:16
+1

I´m using VS code for the react native app. On the other hand, I downloaded Android Studio just to download the SDK´s. I still get the same error as above.

` Configure project :app
AWS Device Farm Plugin version 1.3
Checking the license for package Android SDK Build-Tools 28.0.3 in /usr/local/android-sdk-linux/licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
Checking the license for package Android SDK Platform 27 in /usr/local/android-sdk-linux/licenses
Warning: License for package Android SDK Platform 27 not accepted.
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] A problem occurred configuring project ':app'.
[stderr] > Failed to install the following Android SDK packages as some licences have not been accepted.
[stderr]      platforms;android-27 Android SDK Platform 27
[stderr]      build-tools;28.0.3 Android SDK Build-Tools 28.0.3
[stderr]   To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
[stderr]   Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
[stderr]   
[stderr]   Using Android SDK: /usr/local/android-sdk-linux
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 14s`

Looking forward for a fix. Thanks!

**Comment by NazeerBZ** [comment] 2019-01-21 11:21
+1
Created a new app just to check but same [logs](https://expo.io/builds/35bdbd1e-d5a7-4561-9f00-64176767b38f).

**Comment by boraerbasoglu** [comment] 2019-01-21 11:45
> Hey guys,
> sorry for the inconvenience. I'm working on the fix right now.

Thanks Dominic waiting for it

**Comment by tiagodprovenzano** [comment] 2019-01-21 11:46
Got the same issue here. iOS build was also misbehaving if trying to publish on a different slug. 

https://expo.io/builds/7fada719-a01b-46d7-8f93-727fa29d1961

**Comment by AbdelrahmanNabil96** [comment] 2019-01-21 12:02
Not sure if they pushed the fix already or not, but the issue was resolved by itself for me after 4-5 attempts.

**Comment by dsokal** [comment] 2019-01-21 12:03
Yes, we pushed the fix 20 minutes ago and now we're monitoring if the issue is resolved.

**Comment by theRealSheng** [comment] 2019-01-21 13:02
It works! Thank you!

**Closed** 2019-01-21 13:22 UTC

**Comment by MizzleDK** [comment] 2019-01-22 06:52
Still getting this error when attempting to build with api-27-alpha:

> Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-28 Android SDK Platform 28
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.

> Starting container circleci/android:api-27-alpha
  image is cached as circleci/android:api-27-alpha, but refreshing...
api-27-alpha: Pulling from circleci/android
Digest: sha256:772f61d984ffc57a7c99c41a393be6f39d9c514bd5825cf0c8060a65e2eb2f01
Status: Image is up to date for circleci/android:api-27-alpha
  using image circleci/android@sha256:772f61d984ffc57a7c99c41a393be6f39d9c514bd5825cf0c8060a65e2eb2f01

It worked as expected on January 18.

**Comment by dsokal** [comment] 2019-01-22 08:03
@MizzleDK are you trying to build with `turtle-cli`? If so, make sure to install the latest version of it - 0.5.3 and make sure that you clear the cache (`~/.turtle/androidDependencies` directory) after the upgrade.

**Comment by daxbradley** [comment] 2019-06-05 12:18
I know I'm late to the party, but I had the same problem, but in muy case it was because I had installed a newer version of sdk on my pc and it installed in a different location, causing a conflict. Once I restored the path to point it to the correct build the compiler behaved properly. Maybe that will help someone who doesn't want to go in and manually enter code the hard way if you are using a 3rd party application like I am (Clickteam Fusion 2.5)
