### ISSUE TITLE
[expo-camera][ANDROID] Cannot record video on new expo camera sdk 51 on Android

### ISSUE THREAD

**Issue by timbabs1** [expo/expo#28746] opened 2024-05-10 10:48 UTC
### Minimal reproducible example

https://github.com/timbabs1/example-exposdk51-camera-not-working-android.git

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

After upgrading to Expo 51 SDK, cannot record video while using the new camera view module

Getting error recording video [Error: Video recording failed: Video recording Failed: Unknown error]

Reproducible in expo go and expo development client

I have linked a minimal reproducible example with this. Give camera permission, microphone permissions and tap 'Record Camera' which should reproduce the issue

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
      Watchman: 2023.10.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /opt/homebrew/Cellar/cocoapods/1.13.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 26, 30, 31, 33, 34
        Build Tools: 26.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-29 | Google Play ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | ARM 64 v8a
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.2 => 51.0.2 
      expo-router: ~3.5.11 => 3.5.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 8.0.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

**Comment by alanjhughes** [comment] 2024-05-10 11:12
Hi @timbabs1 - The issue is with the documentation. The max recording duration is not in seconds but milliseconds. You have it set to 5 which is too small and this is causing the error. I'll update the documentation

**Comment by alanjhughes** [comment] 2024-05-10 11:44
@timbabs1 - [This](https://github.com/expo/expo/pull/28749) PR should fix the problem. I didn't handle the maxDuration correctly on android. Sorry for the inconvenience.

**Comment by timbabs1** [comment] 2024-05-10 12:03
Ah I see, nice thats alright. So for now should we set it in milliseconds for android until that PR is merged?

@alanjhughes

**Comment by alanjhughes** [comment] 2024-05-10 12:04
@timbabs1 - Yes, but even then it'll return an incorrect error when it exceeds the duration. The PR will be merged soon and published later. Your not using expo go?

**Comment by timbabs1** [comment] 2024-05-10 12:14
@alanjhughes Well for the Minimal reproducible example I have used expo go but in the project I am working on no, I am using a development build

And oh okay, when might this be published?

**Closed** 2024-05-10 12:30 UTC
Labels: needs review

**Comment by alanjhughes** [comment] 2024-05-10 12:43
@timbabs1 - should be out in a few hours

**Comment by alanjhughes** [comment] 2024-05-10 13:05
@timbabs1  just minor version bump to the camera package. This PR will be labeled as published when it's out

**Comment by timbabs1** [comment] 2024-05-10 13:11
@alanjhughes Thanks, noted

**Comment by alanjhughes** [comment] 2024-05-10 18:43
@timbabs1 new version has been published

**Comment by timbabs1** [comment] 2024-05-10 20:58
Ah thanks I will check it soon

**Comment by timbabs1** [comment] 2024-05-10 21:13
Hi @alanjhughes so testing this, it works fine now when just recording and manually cancelling, but it doesn't work when you set the max duration for the video :(

I have also pushed the update to the reproduction repo

**Comment by alanjhughes** [comment] 2024-05-10 21:17
@timbabs1 did you change the duration? I see you have 5000 set on android which will be 5000 seconds

**Comment by alanjhughes** [comment] 2024-05-10 21:17
Should have mentioned that I made it correctly accept seconds like iOS does

**Comment by timbabs1** [comment] 2024-05-10 21:23
Right @alanjhughes but setting 5 causes it to crash immediately with the Error recording video [Error: Video recording failed: Video recording Failed: Unknown error]

**Comment by alanjhughes** [comment] 2024-05-10 21:30
@timbabs1 I just pulled your repro again and it's working fine. Are you using expo go?

**Comment by alanjhughes** [comment] 2024-05-10 21:34
Also noticed your ref is incorrect. You can just do this
```typescript
  const cameraRef = useRef<CameraView>(null);
```

**Comment by timbabs1** [comment] 2024-05-10 21:43
Hi @alanjhughes  yes I am using expo go and have updated the ref. Changes have been push

Are you using expo go as well?

**Comment by alanjhughes** [comment] 2024-05-10 21:43
No, this change will not be in expo go. It is not updated frequently. You will need to use a development builds to get the latest changes

**Comment by timbabs1** [comment] 2024-05-10 23:07
@alanjhughes Ah yes I can see the change after updating expo dev client. It works now, many thank! :)

**Comment by pablobarreraf** [comment] 2024-05-12 09:49
sorry to interject but does this mean that it will work on a development build only? and not debugging on my local connected to the expo go app?

**Comment by alanjhughes** [comment] 2024-05-12 10:19
@pablobarreraf - For now, but there will be a new version of expo go released soon. Sidenote, you should not be using expo go to develop you entire project. It is purely a playground app for learning and testing.

**Comment by kakidiakoafonso** [comment] 2024-06-21 19:14
After a put the maxDuration in milliseconds i still getting this error in development build and expo go

**Comment by mbiang** [comment] 2024-07-13 03:54
I am also receiving the "Getting error recording video [Error: Video recording failed: Video recording Failed: Unknown error]" for android users.  We are on expo-camera/next (49.1.1).

Are users are reporting blank screens after pressing the startVideo button.  Is the correct resolution to upgrade to the latest expo-camera?

**Comment by alanjhughes** [comment] 2024-07-13 07:53
@mbiang you're on an older version of you are still importing from `expo-camera/next`. The next package is now the default and has received numerous fixes since it was in beta

**Comment by RyflectApp** [comment] 2024-10-04 05:00
I'm using development build, import {
  CameraView,
  CameraType,
  useCameraPermissions,
  useMicrophonePermissions,
} from "expo-camera";  this line of code where the maxDuration is 30 seconds showing an error and in android Video recording failed: Unknown Error.  const startRecording = async () => {
    if (cameraRef.current && mode === "video") {
      const CameraRecordingOptions = {
        maxDuration: 30,
      };
      setIsRecording(true);
      const video = await cameraRef.current.recordAsync(CameraRecordingOptions); 
      console.log("Videoe taken: ", video);
      setIsRecording(false);
    }
  }; works perfectly fine in IOS

**Comment by scottsoif** [comment] 2024-10-08 18:52
> Hi @timbabs1 - The issue is with the documentation. The max recording duration is not in seconds but milliseconds. You have it set to 5 which is too small and this is causing the error. I'll update the documentation

maxDuration is still showing seconds in documentation

https://docs.expo.dev/versions/latest/sdk/camera/#camerarecordingoptions

Please correct this
