### ISSUE TITLE
Add Landscape support to Expo Home app

### ISSUE THREAD

**Issue by lucfranken** [expo/expo#126] opened 2017-04-25 09:42 UTC
When I run the iOS simulator
I run it in landscape mode (because my app depends on that)

Expected: The Expo app (where you select the app to open) would also be landscape
Actual result: It's rotated so it's hard to select the right app to run

More details: This mostly happens if your app crashes while developing. So the first time you run the simulator it's fine (because it's in portrait mode). Then I turn the simulator. Then every time I have to restart my app it's in the wrong orientation.

**Comment by brentvatne** [comment] 2017-04-26 19:05
Can you post a video of what you're experiencing? In the example below, I don't manually change the orientation at all -- the simulator adjusts the orientation as needed.

![orientation](https://cloud.githubusercontent.com/assets/90494/25451923/a1468e1c-2a78-11e7-9a70-098426d98c36.gif)

**Comment by sonaye** [comment] 2017-04-26 21:43
Do you have `"orientation": "portrait",` in your `exp.json`?

**Comment by skevy** [comment] 2017-05-04 19:41
@lucfranken just wanted to ping you on this...were you able to figure out your issue/can you provide us more info?

**Comment by lucfranken** [comment] 2017-05-05 05:42
Thanks for the notification! Sorry missed it. See attached also a nice gif:

![expo-issue-126](https://cloud.githubusercontent.com/assets/1609379/25734703/fb626d28-3165-11e7-807b-7a1c8eaadcd3.gif)

You see the interface of Expo stays in portrait. 

> Do you have "orientation": "portrait", in your exp.json?

I do not have that tag at all since it should work for both. Did that according to:


> Lock your app to a specific orientation with portrait or landscape. Defaults to no lock. default, portrait, landscape
https://docs.expo.io/versions/v16.0.0/guides/configuration.html#orientation

**Comment by terribleben** [comment] 2017-05-05 18:14
Thanks for the information. We need to improve the logic in how our Expo Home screen manages its orientation. This will be supported once we add Runtime Orientation Lock to our SDK, which is a high priority and should happen soon.

**Comment by kevinaditya** [comment] 2017-05-10 01:22
@terribleben Would the next update include the logic of the app orientation itself?

It seems like there is something wrong with the logic on landscape orientation as it keeps displaying me an upside down screen

![video 1](https://cloud.githubusercontent.com/assets/1035360/25879070/add74266-3572-11e7-8ce3-c59874ff0a5e.gif)

**Comment by terribleben** [comment] 2017-05-10 01:28
No, we're not working on Runtime Orientation Lock for the next release.

Thanks for the video, we'll see if we can write better behavior when we address this feature.

**Comment by dikaiosune** [comment] 2017-06-28 19:11
Runtime orientation lock shipped in SDK 18: https://docs.expo.io/versions/v18.0.0/sdk/screen-orientation.html

Closing, but if I'm misunderstanding the issue here please let me know and we can reopen.

**Comment by macrozone** [comment] 2017-09-01 08:09
@dikaiosune: The issue is definitly not solved.

If you specify e.g. `  "orientation": "landscape"` in app.json, the app will start in landscape, but expo home does not respect this orientation, its always in portrait. Switching between the app and expo home is therefore very annoying

**Comment by mmazzarolo** [comment] 2017-11-10 10:02
Can confirm that it is still an issue on `"expo": "^22.0.2"`

**Comment by SupriyaKalghatgi** [comment] 2017-11-20 09:54
+1

**Comment by rodrix** [comment] 2017-12-14 06:19
Still buggy on  "expo": "^23.0.4".

File app.json:

{
  "expo": {
	"name": "app",
	"version": "1.0.0",
	"slug": "app",
	"ios": {
	  "bundleIdentifier": "app.bolado"
	},
	"android": {
	  "package": "app.bolado",
	  "orientation": "portrait" <---------------------------------------- I've tried here, and nothing...
	},
	"orientation": "portrait", <---------------------------------------- I've tried here, and nothing...
	"sdkVersion": "23.0.0" 
  }
}



=/

**Comment by dihan** [comment] 2018-07-04 11:30
Any news on this bug? Currently we lock it to LANDSCAPE_LEFT as thats the only landscape mode that does not flip upside down. Currently on 25.0.0 but wanted to know if this was fixed before upgrading to 28.0

**Comment by brentvatne** [comment] 2018-07-04 19:12
to be clear here, the issue is that "Expo Home" - the part of the Expo client app that lets you open projects and sign in and so on - is locked to portrait. I'll need to make it work nicely on landscape

**Comment by terribleben** [comment] 2018-07-05 22:45
I've renamed the issue and hidden some comments which appeared to be unrelated. To clarify, this topic is a feature request to add landscape support to our Home app.

**Comment by SupriyaKalghatgi** [comment] 2018-07-06 05:09
I dont think this is a feature request, since it is not mentioned anywhere that this is restricted to `portrait` mode only

**Comment by cruzach** [comment] 2019-08-16 18:37
Expo Home supports landscape now, so closing this issue (think it was just forgotten)

**Comment by julianmnst** [comment] 2019-10-05 15:49
What version of Expo Home supports landscape? @cruzach I'm using 2.13.0 and configured "orientation": "landscape" -- not working at all.

**Comment by cruzach** [comment] 2019-10-07 14:40
2.13.0 should support landscape

**Comment by brentvatne** [comment] 2019-10-10 21:49
closed with a misunderstanding, it is currently not possible to set the home app itself to landscape, although you can change the orientation of your app within the expo client just fine

**Comment by sjchmiela** [comment] 2019-11-15 21:59
Although Home doesn't support landscape on iPhone, I think the original motivation of the issue, which was adding support for landscape mode on iPad to Home has been solved (just checked):

![IMG_ED93B1367E00-1](https://user-images.githubusercontent.com/1151041/68978541-53108a00-07fb-11ea-93ca-e448d52eb76e.jpeg)

**Closed** 2020-05-07 02:13 UTC
Labels: Client
