### ISSUE TITLE
"orientation: portrait" in app.json (zoom on landscape)

### ISSUE THREAD

**Issue by yassinouider** [expo/expo#10698] opened 2020-10-15 18:15 UTC
### Summary of Issue 
When we turn the screen in landscape orientation, it zooms in and shouldn't have this behavior.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
Expo CLI 3.28.0 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.28.0
    Expo Workflow: managed
```

### Reproducible Demo
You can view the [demo](https://expo.io/@yassinouider/projects/cameraOrientation)

### Steps to Reproduce

1. Create template expo app
`expo init`

app.json
```javascript
{
  "expo": {
    "name": "cameraOrientation",
    "slug": "cameraOrientation",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "description": ""
  }
}
```

App.js ([https://docs.expo.io/versions/latest/sdk/camera/#usage](https://docs.expo.io/versions/latest/sdk/camera/#usage))
```javascript
import React, { useState, useEffect } from 'react';
import { Text, View, TouchableOpacity } from 'react-native';
import { Camera } from 'expo-camera';

export default function App() {
  const [hasPermission, setHasPermission] = useState(null);
  const [type, setType] = useState(Camera.Constants.Type.back);

  useEffect(() => {
    (async () => {
      const { status } = await Camera.requestPermissionsAsync();
      setHasPermission(status === 'granted');
    })();
  }, []);

  if (hasPermission === null) {
    return <View />;
  }
  if (hasPermission === false) {
    return <Text>No access to camera</Text>;
  }
  return (
    <View style={{ flex: 1 }}>
      <Camera style={{ flex: 1 }} type={type}>
        <View
          style={{
            flex: 1,
            backgroundColor: 'transparent',
            flexDirection: 'row',
          }}>
          <TouchableOpacity
            style={{
              flex: 0.1,
              alignSelf: 'flex-end',
              alignItems: 'center',
            }}
            onPress={() => {
              setType(
                type === Camera.Constants.Type.back
                  ? Camera.Constants.Type.front
                  : Camera.Constants.Type.back
              );
            }}>
            <Text style={{ fontSize: 18, marginBottom: 10, color: 'white' }}> Flip </Text>
          </TouchableOpacity>
        </View>
      </Camera>
    </View>
  );
}
```
### Expected Behavior vs Actual Behavior
When we turn the screen in landscape orientation, it zooms in and shouldn't have this behavior.

Thank you

**Comment by byCedric** [comment] 2020-10-19 15:37
Hi @yassinouider, thanks for the detailed issue report, repro, _and_ demo ❤️   I'm not 100% sure what you mean by "zooming". I think the distortion you see is related to #10372 and caused by the use of `flex: 1`. It's stretched out of proportion and might cause the "zoom effect" you mentioned.

If this is the issue you mentioned, we can "manually" work around this missing resize feature (from #10372). I created a snack where I emulate or fake a cover resize mode with the camera. You can [see that here](https://snack.expo.io/@bycedric/expo-camera-fullscreen-cover-workaround). That keeps the camera ratio in balance, without distorting the camera preview itself.

For now, I'm closing this issue to track the progress through #10372. If you think this is another issue, let me know! 

Hope this helps!

**Closed by byCedric** 2020-10-19 15:37 UTC
Labels: Issue needs review
