### ISSUE TITLE
Snack image asset loading issue

### ISSUE THREAD

**Issue by SmileHub** [expo/expo#28652] opened 2024-05-07 11:31 UTC
### Summary

As I've encountered the same issue with my own code where image doesn't get loaded if it's loading from "required" source, i went into the official documentation.

Inside the docs https://reactnative.dev/docs/image there are only 2 images out of coded 3 images loaded. This image isn't loaded as well:

      <Image style={styles.tinyLogo} source={require('@expo/snack-static/react-native-logo.png')} />

resulting a missing image:

![image](https://github.com/expo/expo/assets/8821939/37bc5a75-3967-4015-994f-8b02c0fe17e6)
As seen in source, the image isn't even added to the sources (same thing i encounter in my app):
![image](https://github.com/expo/expo/assets/8821939/a34d358b-d8fc-4978-bcc4-60993a668ef2)

The issue was suggested to be reported here, while original report was done:
https://github.com/facebook/react-native/issues/44314#event-12687732050

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android, iOS

### Environment

https://reactnative.dev/docs/image

### Reproducible demo

Official website documentation covers the demo: https://reactnative.dev/docs/image

**Comment by brentvatne** [comment] 2024-05-07 16:18
cc @byCedric - perhaps related to the `@expo/snack-static` namespace?

**Comment by Kudo** [comment] 2024-05-07 16:53
i can confirm that snack works for custom `require('../assets/some-image.png')`. it's just broken from the `@expo/snack-static` alias.

**Comment by byCedric** [comment] 2024-05-07 18:31
It's interesting, the assets are loaded properly within the asset registry. It's like something is wrong when loading the asset through `<Image />`,

**Comment by byCedric** [comment] 2024-05-07 18:45
SDK 50 seems to be suffering from a bug around prefixing the public-hosted folder. This has been resolved in SDK 51, but to get the RN docs working, I manually added the asset to the S3 bucket (without version prefix).

Thanks for reporting this! Closing as it's resolved now.

**Closed by byCedric** 2024-05-07 18:45 UTC
Labels: project: snack, needs review
