### ISSUE TITLE
expo-updates crashes iOS app on startup

### ISSUE THREAD

**Issue by Higr25** [expo/expo#12641] opened 2021-04-21 12:50 UTC
### Summary

**Closely related issue**

[related issue](https://github.com/expo/expo/issues/7846)

**Expected behavior**

should check whether update is available or not

**Actual behavior**

app crashes on error in checkForUpdatesAsync()

**Description**

Suddenly out of the blue, our app keeps crashing 1 second after start in production or when published by expo publish. The problem is only on iOS (all versions), android works just fine. After some debugging, we figured out it it crashes on this section of code in App.js:

```
componentDidMount() {
    Updates.checkForUpdateAsync()
            .then((update) => {      
                if (update.isAvailable) {
                    Updates.fetchUpdateAsync()
                    .then((reload) => {
                        Updates.reloadAsync();
                    })
                    .catch((e) => {
                        console.log(e);
                    })
                }
            })
            .catch((e) => {
                console.log(e); - this line will catch
            })
}
```
Catched the error for the function checkForUpdateAsync():

`[Error: The updates module controller has not been properly initialized. If you’re in development mode, you cannot check for updates. Otherwise, make sure you have called [[ABI40_0_0EXUpdatesAppController sharedInstance] start].]`

Didn’t have any issue with updates before and this section of code didn’t change for about 1 year.

Any help would be greatly appreciated as I’m currently in dead end.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40

### Environment

 Expo CLI 4.3.0 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      npm: 6.14.6 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.1 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://github.com/brentvatne/issues-7846

**Comment by brentvatne** [comment] 2021-04-23 02:58
this impacted sdk 39 and 40 in expo go, this is fixed in expo go on simulator (update with `expo client:install:ios`) and we should have the updated version on the app store soon

**Comment by Higr25** [comment] 2021-04-23 07:50
@brentvatne how is expo go app update going to fix this, if the app is crashing in production, when downloaded through google play/app store?

**Comment by brentvatne** [comment] 2021-04-26 01:19
can you further explain how to reproduce this? the example you linked to, https://github.com/brentvatne/issues-7846, is sdk 37, and doesn't include the code that you referenced at the start of your post. please create a minimal reproducible example and an exact set of steps to follow. read this for more info: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by brentvatne** [comment] 2021-04-26 01:20
closing this again actually because if this were an issue faced by more people we would surely know, so i am inclined to believe that there is an error somewhere in your app code. but i am willing to be convinced with a minimal reproducible example!

**Closed by brentvatne** 2021-04-26 01:20 UTC
Labels: needs review
