### ISSUE TITLE
Fail to connect camera service

### ISSUE THREAD

**Issue by dflourusso** [expo/expo#860] opened 2017-10-26 13:17 UTC
I'm using `Expo.Camera` in a modal.
First time it is working well, but if the modal was opened again, it throws `Fail to connect camera service! (Only on Android)

[Snack to test](https://snack.expo.io/Bk90LDJRb)

![img_1240](https://user-images.githubusercontent.com/5544901/32055012-320622d6-ba3f-11e7-8ab9-7fa530c51d6c.GIF)

**Comment by verzil** [comment] 2017-10-27 22:41
I am unable to reproduce the same situation using your snack. However i did run into a simular problem before. 
It was because I had two components that use the Camera module. when the second one opens the first one is unable to gain access to the camera.
 I am wonder if that is your case as well

**Comment by wlwg** [comment] 2017-11-02 07:50
I’m having the same issue only on Android. As mentioned earlier, I have two components that use the Camera component within a modal. I can open the first one, but when I closed it and try to open the second one, it threw the error posted.
I assume it was because even I closed the modal which contains the Camera component, the camera resource is still occupied. 
A workaround would be much appreciated!

**Comment by verzil** [comment] 2017-11-04 02:03
Hey @wlwg I have encountered a similar problem. It seems that if you require the Camera module inside of your component, at most you can only have one Camera component within your custom component.

A work around would be to create a Camera Component that just request and render the Camera.
Import it in the Component that you want use the camera, and setting it to ```null``` when you don't need it anymore.

Hopefully this fixes your problem

**Comment by wlwg** [comment] 2017-11-04 07:05
@verzil Thanks for your suggestion. I did try setting camera to null on closing the modal which contains the Camera, but it didn’t work. Still the same error.

**Comment by wlwg** [comment] 2017-11-22 06:46
Let's go vote for this feature request https://expo.canny.io/feature-requests/p/explicit-openclose-methods-for-camera

**Comment by terribleben** [comment] 2018-07-02 22:36
Hey there! We just tested this more recently and it appears to be working. We've made a lot of changes to both Camera and Modal since SDK 22. Sorry this issue appears to have been overlooked in the meantime.

Let us know if you're still having trouble. I'm going to close this for now.

**Closed by terribleben** 2018-07-02 22:36 UTC
Labels: project: sdk
