### ISSUE TITLE
Impossible to use styled-components with Expo-Router web

### ISSUE THREAD

**Issue by OnlineImpresa** [expo/expo#26489] opened 2024-01-18 09:42 UTC
### Minimal reproducible example

https://github.com/OnlineImpresa/issue-styled-components-expo-router

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

- Create a new Expo Project and install `expo-router`, `react-dom` and `react-native-web`
- Install `styled-components`
- Create a `/app/index.tsx` file
- Create a new component with styled:
```tsx
import styled from 'styled-components';

const StyledView = styled.div`
	background-color: red;
	flex: 1;
	align-items: center;
	justify-content: center;
`
```
OR
```tsx
import styled from 'styled-components/native';

const StyledView = styled.View`
	background-color: red;
	flex: 1;
	align-items: center;
	justify-content: center;
`
```
- Start the server and open the web page
- Console will output: 
`Unable to resolve "stylis" from "node_modules/styled-components/dist/styled-components.browser.esm.js"`

This problems happens after installing `expo-router`, so it could be a problem relative to Metro bundler, i guess.

More details:

```
Unable to resolve "stylis" from "node_modules/styled-components/dist/styled-components.browser.esm.js"
Error: While trying to resolve module `stylis` from file `/Users/***/Desktop/styled-components-bug/node_modules/styled-components/dist/styled-components.browser.esm.js`, the package `/Users/***/Desktop/styled-components-bug/node_modules/stylis/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/***/Desktop/styled-components-bug/node_modules/stylis/dist/stylis.mjs`. Indeed, none of these files exist:

  * /Users/***/Desktop/styled-components-bug/node_modules/stylis/dist/stylis.mjs(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs)
  * /Users/***/Desktop/styled-components-bug/node_modules/stylis/dist/stylis.mjs/index(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs)
    at DependencyGraph.resolveDependency (/Users/***/Desktop/styled-components-bug/node_modules/metro/src/node-haste/DependencyGraph.js:289:17)
    at Object.resolve (/Users/***/Desktop/styled-components-bug/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/***/Desktop/styled-components-bug/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/***/Desktop/styled-components-bug/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at async Graph._addDependency (/Users/***/Desktop/styled-components-bug/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 0)
    at async Graph._processModule (/Users/***/Desktop/styled-components-bug/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
    at async Graph._traverseDependenciesForSingleFile (/Users/***/Desktop/styled-components-bug/node_modules/metro/src/DeltaBundler/Graph.js:249:5)
    at async Graph.traverseDependencies (/Users/***/Desktop/styled-components-bug/node_modules/metro/src/DeltaBundler/Graph.js:157:9)
    at async DeltaCalculator._getChangedDependencies (/Users/***/Desktop/styled-components-bug/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:281:42)
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.5.1 - /usr/local/bin/node
      npm: 9.8.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.1 
      expo: ~49.0.15 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 3.13.2
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by marklawlor** [comment] 2024-01-18 21:12
Duplicate of https://github.com/expo/expo/issues/24554, resolved in SDK 50

**Closed by marklawlor** 2024-01-18 21:12 UTC
Labels: needs review, Router
