### ISSUE TITLE
java.lang.RuntimeException when Android apps starts

### ISSUE THREAD

**Issue by yleclanche** [expo/expo#6805] opened 2020-01-20 08:48 UTC
### Environment

  Expo CLI 3.11.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.19.1 - S:\DEV\Tools\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

    "@expo/vector-icons": "~10.0.0",
    "@react-native-community/netinfo": "5.1.0",
    "axios": "^0.19.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "expo": "~36.0.0",
    "expo-analytics": "^1.0.13",
    "expo-asset": "~8.0.0",
    "expo-constants": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-network": "^2.0.0",
    "expo-web-browser": "~8.0.0",
    "html-entities": "^1.2.1",
    "md5-hex": "^3.0.1",
    "mobx": "^5.15.1",
    "mobx-react": "^6.1.4",
    "moment-timezone": "^0.5.27",
    "native-base": "^2.13.8",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-autoheight-webview": "^1.3.6",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-reanimated": "~1.4.0",
    "react-native-render-html": "^4.2.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-svg": "9.13.3",
    "react-native-swiper": "^1.6.0-nightly.5",
    "react-native-web": "~0.11.7",
    "react-native-webview": "^8.0.2",
    "react-navigation": "~4.0.10",
    "react-navigation-drawer": "^2.3.3",
    "react-navigation-stack": "~1.10.3",
    "react-navigation-tabs": "~2.6.2",
    "sentry-expo": "^2.0.1",
    "string-strip-html": "^4.3.12"

### Expected Behavior

No crash.

### Actual Behavior

I assume the crash happens at startup because sentry doesn't report any error.
I can't reproduce the issue with my device. 

Error from Google Play Console :

```
java.lang.RuntimeException: 
  at host.exp.exponent.experience.a$b.run (BaseExperienceActivity.java:7)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:224)
  at android.app.ActivityThread.main (ActivityThread.java:7520)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
```

This happens on Android 8.1, 9 and 10.

**Comment by PiotrSzlagura** [comment] 2020-01-20 10:12
I'm experiencing the same issue, Google Play says it's happened about 100 times during last 4 days.

**Comment by PiotrSzlagura** [comment] 2020-01-20 11:30
After few tests I can see that this crash happens right after app start, even before any logic has opportunity to run. Adding `componentDidCatch` handler in root component didn't catch this error.

**Comment by yleclanche** [comment] 2020-01-20 11:45
@PiotrSzlagura do you see any packages in common between our apps ? 
How did you manage to reproduce the error ?

**Comment by PiotrSzlagura** [comment] 2020-01-20 12:08
It's related to expo version 36 or latest react native. Our testers just opened app on various devices, confirmed crashes are on:

- Xiaomi Mi Note 3, Android 9
- Xiaomi Mi Mix 2, Android 9
- Samsung Galaxy Note 8, Android 9

Google play says that most of the crashes occur on Android 9 (72,5%) and Android 10 (23,9). There is also one occurrence on Android 8.

I am just now building apk with downgraded expo version (35.0.0). I'll let you know if this fixes this crash.

**Comment by PiotrSzlagura** [comment] 2020-01-20 12:43
It's confirmed that downgrade fixed this issue. Packages changed during downgrade:

| Package | Crashing version | Working version |
| --- | --- | --- |
| expo | ^36.0.0 | ^35.0.0 |
| expo-constants | ~8.0.0 | ~7.0.0 |
| expo-font | ~8.0.0 | ~7.0.0 |
| expo-permissions | ~8.0.0 | ~7.0.0 |
| react | 16.9.0 | 16.8.3 |
| react-native | https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz | https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz |
| react-native-svg | 9.13.3 | 9.9.5 |
| react-native-webview | 7.4.3 | 7.0.5 |

**Comment by Xanewok** [comment] 2020-01-20 14:27
Probably a duplicate of https://github.com/expo/expo/issues/6523

**Comment by PiotrSzlagura** [comment] 2020-01-20 16:10
I just checked and it turns out this problem also occurs when dark mode is not turned on. Android 8 has no such option and there are crashes on it too, with the same stack trace.

**Comment by cruzach** [comment] 2020-01-20 17:03
6523 isn't specific to dark mode, we've reproduced it with and without, so I'm going to close this as a duplicate

**Closed by cruzach** 2020-01-20 17:03 UTC
Labels: bug
