### ISSUE TITLE
PanGestureHandler receiving simultaneousHandlers from ScrollViews no longer works in newest Expo client on IOS

### ISSUE THREAD

**Issue by jordanbb** [expo/expo#4415] opened 2019-06-04 17:57 UTC
## 🐛 Bug Report

The newest Expo client (v2.11.0) has broken `PanGestureHandler` and `ScrollView`s ability to stream their gestures at the same time when passing a parent `ScrollView` ref into the `PanGestureHandler` `simultaneousHandlers` prop.

### Environment

-SDK 32
-Expo CLI 2.17.2
-System OS: Windows 10

### Steps to Reproduce

Please see the reproducible demo

### Reproducible Demo

https://snack.expo.io/@blueiqjordan/7c905f

**Note: This is only an issue on ios, android appears to still work fine.**

### Expected Behavior

While gesturing inside the red box, it should stream both the pan gesture event and the native scrolling (up/down or to the right). This continues to work on andriod. Its worth noting that this behavior still works on ios with the previous expo version (2.10.0).

### Actual Behavior

On ios if you gesture inside the red box, the PanGestureHandler consumes the gesture and doesn't allow parent ScrollView's gestures to activate.

**Comment by ide** [comment] 2019-06-04 18:29
We upgraded react-native-gesture-handler, which most likely affected this. Are you seeing this issue with SDK 32 or 33?

**Comment by jordanbb** [comment] 2019-06-04 18:36
SDK 32

**Comment by jordanbb** [comment] 2019-06-05 05:34
If you run the snack I linked under Reproducible Demo with SDK 33 instead of SDK 32 it seems to work fine. However this should be working with SDK 32 since it was in the previous expo client.

**Comment by tsapeta** [comment] 2019-06-05 16:20
Hey @jordanbb,
I've been trying to find out the cause of this issue, no luck so far. Could you send us a result of `yarn why react-native-gesture-handler` command?

**Comment by jordanbb** [comment] 2019-06-05 18:04
I have a project using SDK 32 but its not set up with `yarn` unfortunately. Here is the result of `npm ls react-native-gesture-handler` instead. 
```
+-- expo@32.0.2
| `-- react-native-gesture-handler@1.0.14
`-- react-navigation@3.0.9
  `-- @react-navigation/native@3.0.3
    `-- react-native-gesture-handler@1.0.14 
```
If that isn't helpful I can see if I can set up a minimal project with `yarn` instead.

**Comment by tsapeta** [comment] 2019-06-05 20:00
This is enough, thank you! Just wanted to make sure you're using compatible version 😉

**Comment by swengle** [comment] 2019-11-05 21:39
Any update on this issue. Looks like gesture-handler 1.5 is upcoming, does that fix simultaneousHandlers?

**Comment by ide** [comment] 2019-11-07 07:20
No updates - when there are updates they will be posted on the issue.

**Comment by swengle** [comment] 2019-11-07 18:21
That’s fine but you should report the component as unusable in the main
docs or remove it from the docs once you know it’s not working and you are
not actively trying to fix it.

It’s not fair to developers to deliver a broken product and expect us to
dive into your tickets to understand what’s going on.

Right now your product does not work for thus feature? Is there some other
way you might consider communicating what actual plugins work

**Comment by ide** [comment] 2019-11-07 22:58
It sounds like one specific scenario is unusable but the component works otherwise for several developers and for them removing it from the docs isn't the best course of action. In general the most productive way forward is to figure out the root cause and how to address it from there.

**Comment by tsapeta** [comment] 2020-07-11 18:14
Just tested this with SDK38 using https://snack.expo.io/@tsapeta/simultaneoushandlers-ios-issue demo.
Looks like it works fine now, so I'm closing the issue 🙂

**Closed by tsapeta** 2020-07-11 18:14 UTC
Labels: GestureHandler, bug, iOS
