### ISSUE TITLE
StatusBar hidden create black bar

### ISSUE THREAD

**Issue by red-made** [expo/expo#15244] opened 2021-11-18 16:41 UTC
### Summary

StatusBar hidden produces a black bar

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.9.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.23.0 - /usr/local/bin/npm
      Watchman: 2021.11.08.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I'm working on a couple of apps on expo v 43 (1 updated app from 40 and 1 started directly from version 43), in both when I use the hidden status bar on the android emulator I have a black bar of the same size as the status bar (when visible) in the top of the screen. The bar only disappears if I use a translucent bar, but obviously the translucent bar contains information (clock, network ecc..), so this is not a solution.

The problem is the same with react native's StatusBar and with expo-status-bar.

```
// black bar
import { StatusBar } from 'expo-status-bar';
<StatusBar hidden={true} />

// black bar
import { StatusBar } from 'expo-status-bar';
<StatusBar hidden />

// black bar
import { StatusBar } from 'react-native';
<StatusBar hidden={true} />

// black bar
import { StatusBar } from 'react-native';
<StatusBar hidden />

```

**Comment by murat0** [comment] 2021-12-06 12:21
+1 Having the same issue with a bare expo installation

**Comment by emmsdan** [comment] 2022-01-18 13:37
@murat0  have you been able to find a fix??

**Comment by oliverjarvis** [comment] 2022-03-21 19:55
I'm still having the exact same issue. @murat0 @emmsdan @red-made has anyone figured out the fix for this?

**Comment by BrianEngel42** [comment] 2022-03-26 10:50
fix?

**Comment by IagoR0cha** [comment] 2022-04-08 18:28
Same problem here, with sdk 44... Any solution?

**Comment by michelazzam** [comment] 2022-05-09 12:18
+1

**Comment by dodoto** [comment] 2022-05-18 06:50
+1 and meanwhile translucent didn't work

**Comment by bhaskarrijal** [comment] 2022-05-30 15:22
+1 to the issue. Toggling the StatusBar to hidden hides the Status Bar but won't set its background to match with the active screen's background.

**Comment by MainAdc95** [comment] 2022-07-03 17:19
+1 ..

**Comment by chadders404** [comment] 2022-07-31 22:15
+1 setting the status bar to hidden _does_ hide the status bar, but now there's a black bar at the top of the app. Hope someone finds a fix

**Comment by sckwokyboom** [comment] 2022-08-09 15:00
+1

**Comment by ggchicote** [comment] 2022-11-09 13:33
I'm facing the same issue, does anybody could find a solution?

**Comment by Karl-EdwardFPJeanMehu** [comment] 2022-12-15 19:10
Same issue. bump!

**Comment by mtuguldurb** [comment] 2022-12-26 14:48
for me <StatusBar translucent hidden backgroundColor='transparent' /> fixed it

**Comment by ggchicote** [comment] 2023-01-06 09:46
> 

could you share a bit more of your code? How did you set up your app.config.js/app.json file? do you have Managed or bare workflow?

**Comment by kirtikapadiya** [comment] 2023-01-16 06:44
@mtuguldurb
Thanks !!
This `<StatusBar translucent hidden backgroundColor='transparent' />`  fixed issue for me.
Expo SDK 47, Managed workflow application.

**Comment by mtuguldurb** [comment] 2023-01-17 02:53
@ggchicote I think I didn't set up manually any of that, by the way I used React Native CLI.

**Comment by chadders404** [comment] 2023-01-18 03:40
I'm running a managed workflow, Android, SDK 47. The `translucent` / `backgroundColor='transparent'` method has not worked for me- the back bar still remains. I suspect it's to do with the punch hole camera as this does not occur on android phones that do not have a display cut out such as a camera or notch.

**Comment by ggchicote** [comment] 2023-01-27 14:50
@chadders404 I got to the same conclusion but any solution so far.

**Closed** 2023-02-22 22:56 UTC
Labels: needs review, incomplete issue: missing or invalid repro

**Comment by jifakir** [comment] 2023-04-05 07:00
`android > app > src > main > res > styles.xml
<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
`
solved my issue

**Comment by Noitidart** [comment] 2023-08-30 02:36
> `android > app > src > main > res > styles.xml` `<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>` solved my issue

Did you have to set minSdkVersion to 27? Or does it work fine without it? I was hoping to continue supporting down to minSdkVersion 24 and 26.

**Comment by Noitidart** [comment] 2023-08-30 16:17
I wrote a config plugin for this. It works even if I don't use expo-build-properties and set minSdkVersion to 27. If anyone has details on if it's okay to do this without changing minSdkVersion, please confirm. Here is the config plugin:


First create this file in the root directory:

```
import { withAndroidStyles } from '@expo/config-plugins';
import {
  assignStylesValue,
  getAppThemeLightNoActionBarGroup
} from '@expo/config-plugins/build/android/Styles';

import type { ConfigPlugin } from '@expo/config-plugins';

/**
 * Adapt to Android P notch screens. Android P (Android 9.0) introduced support
 * for devices with display cutouts, commonly referred to as notches. When the
 * status bar is hidden on these screens, a black bar shows, and the screen
 * contents shifts down by the height of that bar. This is described nicely at -
 * https://stackoverflow.com/q/64595311/1828637.
 */
const withPreventAndroidBlackBar: ConfigPlugin = expoConfig =>
  withAndroidStyles(expoConfig, modConfig => {
    modConfig.modResults = assignStylesValue(modConfig.modResults, {
      add: true,
      parent: getAppThemeLightNoActionBarGroup(),
      name: 'android:windowLayoutInDisplayCutoutMode',
      value: 'shortEdges'
    });

    return modConfig;
  });

export default withPreventAndroidBlackBar;
```


Then run `npx tsc withAndroidSplashScreen.ts --watch --skipLibCheck`.

Then to your app.json plugins add `"./withPreventAndroidBlackBar.js",`

**Comment by chadders404** [comment] 2023-09-16 18:36
> I wrote a config plugin for this. It works even if I don't use expo-build-properties and set minSdkVersion to 27. If anyone has details on if it's okay to do this without changing minSdkVersion, please confirm. Here is the config plugin:
> 
> First create this file in the root directory:
> 
> ```
> import { withAndroidStyles } from '@expo/config-plugins';
> import {
>   assignStylesValue,
>   getAppThemeLightNoActionBarGroup
> } from '@expo/config-plugins/build/android/Styles';
> 
> import type { ConfigPlugin } from '@expo/config-plugins';
> 
> /**
>  * Adapt to Android P notch screens. Android P (Android 9.0) introduced support
>  * for devices with display cutouts, commonly referred to as notches. When the
>  * status bar is hidden on these screens, a black bar shows, and the screen
>  * contents shifts down by the height of that bar. This is described nicely at -
>  * https://stackoverflow.com/q/64595311/1828637.
>  */
> const withPreventAndroidBlackBar: ConfigPlugin = expoConfig =>
>   withAndroidStyles(expoConfig, modConfig => {
>     modConfig.modResults = assignStylesValue(modConfig.modResults, {
>       add: true,
>       parent: getAppThemeLightNoActionBarGroup(),
>       name: 'android:windowLayoutInDisplayCutoutMode',
>       value: 'shortEdges'
>     });
> 
>     return modConfig;
>   });
> 
> export default withPreventAndroidBlackBar;
> ```
> 
> Then run `npx tsc withAndroidSplashScreen.ts --watch --skipLibCheck`.
> 
> Then to your app.json plugins add `"./withPreventAndroidBlackBar.js",`

I've attempted this solution on Expo managed workflow (SDK 49) with no success, however as I am not an experienced coder and do not understand the solution, I'm potentially implementing it incorrectly. After saving the suggested config plug in the root directory as "withPreventAndroidBlackBar.ts" and run `npx tsc withAndroidSplashScreen.ts --watch --skipLibCheck`, it opened an unfamiliar looking terminal and printed the following error: 

error TS6053: File 'withAndroidSplashScreen.ts' not found.
The file is in the program because:
Root file specified for compilation

Unsure why I was running a command for a file I knew I didn't have, I tried running the same command but for the file I'd just created: `npx tsc withPreventAndroidBlackBar.ts --watch --skipLibCheck` which didn't return any errors, but produced no behavioural changes in the app. The black bar still remains.

So this didn't work for me, but huge thanks to @Noitidart nevertheless for trying to make a fix. I hope this thread is reopened so a solution can be found or further information shared.

**Comment by mkhoussid** [comment] 2023-12-13 16:02
> for me `<StatusBar translucent hidden backgroundColor='transparent' />` fixed it

Did the trick for me:
```
<StatusBar backgroundColor={'transparent'} translucent />
```

**Comment by alimohsinz** [comment] 2023-12-15 08:12
yes it work for me but the whole app layout is lifted up by the size of statusbar ....

**Comment by chadders404** [comment] 2024-03-19 20:21
This issue is definitely still persisting. I have created a snack to demonstrate: 

https://snack.expo.dev/@chadders404/blessed-blue-kiwi but **you will need to view it on an android phone with a punchole camera or notch**, not just an emulator.

If you are for some reason unable to view the snack, reproducing this bug is easy, you just need three things:
1. React Native Expo Project (seemingly any version)
2. Android phone with punch hole camera or notch with Expo Go installed
3. **Status bar set to hidden** (doesn't matter if it's the StatusBar imported form react native or expo-status-bar - the behaviour is the same. eg. `<StatusBar hidden={true}`

I think if this could be fixed, it would have been by now - I'm resigned to having to eject from Expo early on all my full screen projects, but I'm once again commenting here just in case someone wants to give this puzzle another go.

**Comment by jrpn93** [comment] 2024-04-10 07:43
Adding `<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>` in android/app/src/main/res/values.xml resolved my issue.

Here is my styles.xml ,

```
<resources>

    <!-- Base application theme. -->

    <!-- Replaced below line to fully disable Force Dark Mode in android, because it is causing issues in some devices like Xiomi/Redmi overriding the black placeholder text color to white  -->
    <!-- <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar"> -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">

        <!-- Customize your theme here. -->

        <!-- Below line will hide the Default SplashScreen -->
        <!-- <item name="android:windowIsTranslucent">true</item> -->

        <!-- Below Two lines will make the navigation bar Transparent -->
        <item name="android:windowTranslucentNavigation">true</item> -->
        **<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>**
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
        <item name="android:windowSplashScreenBackground">#f4f0fb</item>
    </style>

    <style name="SplashScreenTheme" parent="SplashScreen_SplashTheme">
        <item name="colorPrimaryDark">#000000</item>
    </style>

</resources>
```

**Comment by shubhamguptadream11** [comment] 2024-08-18 09:23
Shared my findings with one possible fix here: https://github.com/facebook/react-native/issues/46070#issuecomment-2295191599

**Comment by bijan3s** [comment] 2024-11-10 19:00
For anyone still looking for a solution, this works with Expo as well.

Run: npx expo prebuild

Edit styles: Open your project in Android Studio, go to android/app/src/main/res/values/styles.xml, and add <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item> inside <style name="AppTheme"> (add it at the end of the item list).

Update min SDK: In android/build.gradle (Project: your project name) , set minSdkVersion to 27.

Modify Layout: In your Expo project’s _layout, set up the stack like this:

<Stack
  screenOptions={{
    headerShown: false,
    navigationBarHidden: true,
    statusBarHidden: true,
    statusBarTranslucent: true,
  }}
>
This should enable full immersive mode, even on phones with notch cutouts!

**Comment by igweze** [comment] 2025-04-21 06:33
This issue is bothersome and frustrating. None of the above worked for me in 2025. Expo is excellent, but they should fix this bug or issues for us.

**Comment by bijan3s** [comment] 2025-04-21 07:37
> This issue is bothersome and frustrating. None of the above worked for me in 2025. Expo is excellent, but they should fix this bug or issues for us.

Well actually it fixed for me using latest version of expo , 52.4x I think and you just use expo status bar package and no native code needed

**Comment by igweze** [comment] 2025-04-21 15:58
> > This issue is bothersome and frustrating. None of the above worked for me in 2025. Expo is excellent, but they should fix this bug or issues for us.
> 
> Well actually it fixed for me using latest version of expo , 52.4x I think and you just use expo status bar package and no native code needed

Thanks, it's now working. I updated to the  latest version as you advised

**Comment by ugoi** [comment] 2025-06-29 22:01
I'm using expo version 53.0.13 and expo-status-bar ~2.2.3 and experiencing same issue

**Comment by mkhoussid** [comment] 2025-06-30 09:54
All issues that I have been experiencing have been resolved with expo 53. Check your dependencies, run `npx expo-doctor`
