### ISSUE TITLE
Basic Jest tests failing after SDK36 upgrade (from SDK35)

### ISSUE THREAD

**Issue by nucat176** [expo/expo#6700] opened 2020-01-07 19:31 UTC
### Environment

  Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      @bugsnag/expo: ^6.4.1 => 6.4.1 
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^3.0.9 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.11.3

Target: iOS with CI in GitLab

### Steps to Reproduce

1. expo upgrade
2. npx just --ci (via gitlab runner) 

### Expected Behavior

App-test.js (auto-generated) passes as it did before the upgrade

### Actual Behavior

```
$ npx jest --ci
FAIL __tests__/App-test.js
   ● Test suite failed to run
        Jest encountered an unexpected token
     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
     Here's what you can do:
      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
      • If you need a custom transformation specify a "transform" option in your config.
      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
     You'll find more details and examples of these config options in the docs:
     https://jestjs.io/docs/en/configuration.html
     Details:
     /builds/adam_whistle/lootscoot/node_modules/unimodules-permissions-interface/build/PermissionsInterface.js:1
     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export var PermissionStatus;
                                                                                              ^^^^^^
     SyntaxError: Unexpected token export
       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
       at Object.<anonymous> (node_modules/expo-location/src/Location.ts:2:1)
```

### Reproducible Demo

I am having trouble creating a reproducible demo of this, but I can share a few relevant files that might be helpful:

1. package.json

```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo",
    "transform": {
      "^.+\\.js$": "babel-jest"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base)"
    ],
    "moduleNameMapper": {
      "@bugsnag/expo": "<rootDir>/mock/bugsnag.mock.js",
      "toggle-switch-react-native": "<rootDir>/mock/ToggleSwitchReactNative.mock.js"
    }
  },
  "dependencies": {
    "@bugsnag/expo": "^6.4.1",
    "@expo/samples": "2.1.1",
    "@expo/vector-icons": "^10.0.0",
    "@pusher/chatkit-client": "^1.13.2",
    "@pusher/chatkit-client-react": "^0.1.2",
    "axios": "^0.19.0",
    "expo": "^36.0.0",
    "expo-analytics-amplitude": "~8.0.0",
    "expo-asset": "~8.0.0",
    "expo-av": "~8.0.0",
    "expo-barcode-scanner": "~8.0.0",
    "expo-blur": "~8.0.0",
    "expo-branch": "~2.0.0",
    "expo-camera": "~8.0.0",
    "expo-constants": "~8.0.0",
    "expo-facebook": "~8.0.0",
    "expo-file-system": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-google-sign-in": "~8.0.0",
    "expo-permissions": "~8.0.0",
    "expo-react-native-adapter": "^3.0.1",
    "firebase": "^5.9.0",
    "formik": "^1.5.1",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "moment-holiday": "^1.5.1",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
    "react-native-calendar-strip": "^1.3.9",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-gifted-chat": "^0.11.3",
    "react-native-google-places-autocomplete": "^1.3.9",
    "react-native-maps": "0.26.1",
    "react-native-modal-selector": "^1.1.2",
    "react-native-snap-carousel": "^3.7.5",
    "react-native-web": "^0.11.7",
    "react-native-webview": "7.4.3",
    "react-navigation": "^3.0.9",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "rn-webview": "^0.1.0",
    "socket.io-client": "^2.2.0",
    "toggle-switch-react-native": "^2.1.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^8.0.0",
    "expo-cli": "^3.11.3",
    "jest-expo": "^36.0.0",
    "react-native-dotenv": "^0.2.0",
    "react-test-renderer": "16.8.3"
  },
  "private": true
}
```

2. babel.config.js

```js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      'babel-preset-expo',
      'module:react-native-dotenv',
    ],
    sourceMaps: true,
    plugins: [
      '@babel/transform-react-jsx-source',
    ],
  };
};
```

**Comment by esamelson** [comment] 2020-01-08 20:18
Hey there @nucat176 ! Sorry you're running into this 😞 I'm not able to reproduce this on a new blank SDK 36 project which means it's most likely an issue with something in your code. If you can create a reproducible example that demonstrates the problem we might be able to help more. I'd suggest following [this guide](https://stackoverflow.com/help/minimal-reproducible-example) to try and do so, and in the process you might even discover and fix what's causing the issue in the first place 🙂 I'm going to close this ticket for now, but feel free to open a new one if you come up with a repro and determine it's an issue on our end.

**Closed by esamelson** 2020-01-08 20:18 UTC
Labels: bug
