### ISSUE TITLE
Multiple issues with new Splash screen API

### ISSUE THREAD

**Issue by ryanvanderpol** [expo/expo#542] opened 2017-08-24 16:14 UTC
I've been playing with the new (SDK v20) splash screen API and have found multiple issues. 

Here's what I expect to see:

1. My splash screen
2. My app 

However, here is what I see when launching the app cold on iOS:

1. Blank white screen while the app maximizes
2. Screen with the background color i specified in app.json, with a loading indicator on top
3. My splash screen
4. Blank white screen
5. My app.

Here's a photo of `2`:

![image](https://user-images.githubusercontent.com/1936460/29676311-5427dd2c-88bd-11e7-94b0-c096350a615a.png)

Here's what happens on Android

1. Blank white screen
2. Expo logo fades in on white screen
3. My splash screen appears with the Expo logo overlayed on top
4. Blank white screen
5. My app

Here's a photo of the splash image with the Expo logo on top.

![image](https://user-images.githubusercontent.com/1936460/29676101-b52fbca8-88bc-11e7-8032-9b0d6e629e46.png)

I understand that `4` is a known issue (per the SDK release notes) but the rest seems like bugs.

On a fresh install, the app seems to freeze on a blank white screen.  After force closing and opening again it works (with the above effects).  This may be a separate issue.

Here is what my `app.json` looks like:

```
{
  "expo": {
    "sdkVersion": "20.0.0",
    "orientation": "portrait",
    "name": "XXX",
    "icon": "./assets/icons/Icon.png",
    "version": "0.1.1",
    "slug": "xxx",
    "ios": {
      "bundleIdentifier": "com.xxx.yyy"
    },
    "android": {
      "package": "com.xxx.yyy"
    },
    "loading": {
      "backgroundImage": "./assets/images/Splash.png",
      "splash": {
        "backgroundColor": "#222127",
        "image": {
          "ios": {
            "backgroundImage": "./assets/images/Splash.png"
          }
        }
      }
    }
  }
}
```

**Comment by nsillik** [comment] 2017-08-24 19:50
@ryanvanderpol sorry you're having trouble with this. I'm working on reproducing the issue right now but was wondering if you could answer a few questions:

1. How are you running your app on iOS and Android? i.e. are you running through the Expo app, or using the [Standalone Instructions](https://docs.expo.io/versions/latest/guides/building-standalone-apps.html)?
2. Does exp (or xde) provide any output regarding the `loading.splash.*` keys?
3. If you use the not-experimental `loading.backgroundImage` and `loading.backgroundColor`, do you get the results you expect?

I'll keep you updated on my findings as I attempt to reproduce.

**Comment by ryanvanderpol** [comment] 2017-08-24 22:10
@nsillik thanks. I'm not at my desk right now but I'll try to answer your questions the best I can. 

1. It is runninf standalone. For iOS it is installed via TestFlight and Android via an apk. Both were created via `exp build:ios` or `exp build:android`

2. I have not seen anything different in the CLI logs, so I think my answer is no. 

3. Per the app.json I posted above, I think I *am* using `loading.backgroundImage`. I haven't tried `backgroundColor` yet. 

Thanks for your help. Having a smooth splash experience is really critical for us to have a polished presentation. Flashing 4 different screens in rapid succession definitely doesn't feel polished.

**Comment by nsillik** [comment] 2017-08-24 22:17
I've set up a super basic splash screen example [here](https://github.com/nsillik/expo-splash-screen-example) and it all seems to be working after running `exp build:ios -t simulator` and running in the simulator. It also worked for me running from the Expo app itself.

**Comment by nsillik** [comment] 2017-08-24 22:18
I will say there are some improvements not yet available which should come in a release in the near future, including Android support as well. I'll let you know when that becomes available for testing as well.

**Comment by sonaye** [comment] 2017-08-25 12:00
Similar to #529.

**Comment by ryanvanderpol** [comment] 2017-08-25 12:33
That's it?  I report several different visible issues and this just gets closed? Very clearly the issues I'm reporting are happening at the Expo level -- I assume during the build phase.

**Comment by sonaye** [comment] 2017-08-25 12:35
@ryanvanderpol the issue is still open.

**Comment by ryanvanderpol** [comment] 2017-08-25 12:36
Oh, yup, you're right. I noticed it got closed and then failed to notice it got reopened.

**Comment by sonaye** [comment] 2017-08-25 12:41
@ryanvanderpol I've been using expo since the sdk 5 days (over a year), I can assure that the support is top notch here, great team behind the platform, tackling this is a matter of time.

**Comment by nsillik** [comment] 2017-08-25 16:07
@ryanvanderpol sorry, I accidentally fat-fingered the close button while making another comment. Take a look at my responses above, I'm hoping they can help diagnose your issues.

**Comment by ryanvanderpol** [comment] 2017-08-29 15:24
@nsillik I don't see much of a difference between your code and mine, but I haven't built your app and uploaded it to TestFlight, so I can't say for sure that yours doesn't exhibit the same issues as mine.  Did you do that?  Detach and upload to iTunes Connect?  Does `exp build:ios -t simulator` create the exact same experience as detaching and uploading to the App Store/TestFlight?

Also, does changing any values in `app.json` require a new build to be uploaded to iTunes Connect? IIRC, Splash screens in iOS are stored as metadata on the app, or in a plist?  So it seems like just doing another build to the Expo servers wouldn't actually change that part on my app once installed.  Is that correct?

**Comment by acomito** [comment] 2017-08-29 20:28
I'm having the same issue. Somebody is saying a white screen is there when the app starts. They're also saying it just pops up out of nowhere while using the app. I've never had it happen when I use, and I'm not getting any sentry error logs, so Im really not sure what it could be.

**Comment by ryanvanderpol** [comment] 2017-08-30 14:12
@nsillik I've created a video of what happens when I open the app.  Actually, in this video, you can't even see the actual splash image.  You see white screen, the loading screen (presumably this is created using `expo.loading.splash.backgroundColor`?), a white flash, then the login screen (the first screen in my app).  As I said before, instead of the initial white screen and the loading screen, I expect to see my splash image.

![splash](https://user-images.githubusercontent.com/1936460/29876656-6d8eb526-8d6b-11e7-9d1c-80491282ba50.gif)

Here is the relevant `app.json` running in this app:

```
{
  "expo": {
    "sdkVersion": "20.0.0",
    "loading": {
      "backgroundColor": "#222127",
      "hideExponentText": true,
      "splash": {
        "backgroundColor": "#222127",
        "image": {
          "ios": {
            "backgroundImage": "./assets/images/Splash.png"
          }
        }
      }
    }
  }
}
```

When I update `app.json` do I always need to rebuild and push a new version to TestFlight?

Also, someone else in Slack reported experiencing the same problems.

**Comment by nsillik** [comment] 2017-08-31 17:49
@ryanvanderpol I think we've fixed this issue now. Please try `exp build:ios` again and let me know if it's working as expected. Sorry it took a while, it was hard to chase down.

**Comment by ryanvanderpol** [comment] 2017-08-31 17:54
@nsillik great to hear!  I'm running a build now and will reply back with the results -- it might take a while since I'll have to reupload to iTunes Connect / TestFlight and all that jazz.

Any word on when the white flash will be fixed?  Or is there at least some way to change it to a different color?

**Comment by nsillik** [comment] 2017-08-31 18:32
@ryanvanderpol the white flash should be fixed in SDK 21.

You can also test in simulator by running `exp build:ios -t simulator` and then using a tool like [`ios-sim`](https://github.com/phonegap/ios-sim) to launch it like so: `ios-sim launch your-app-name.app --devicetypeid "iPhone-7, 10.3"`

**Comment by sonaye** [comment] 2017-08-31 18:42
@nsillik It's working now, ignoring the white flash screen, I noticed that the indicator is showing in the splash screen itself, is that a glitch?

<img src="https://user-images.githubusercontent.com/23000873/29939495-b41e756a-8e94-11e7-8a9d-5ec3a2fc2c2e.gif" width="400">

Notice here:

<img src="https://user-images.githubusercontent.com/23000873/29939615-21fc5ec6-8e95-11e7-87c3-88371b55cd0a.png" width="400">

**Comment by nsillik** [comment] 2017-08-31 19:34
@ryanvanderpol yes, that's a bug that's been removed in the current development branch along with the white flash!

**Comment by ryanvanderpol** [comment] 2017-08-31 19:54
@nsillik great. I haven't had a chance to test my app yet (the previous poster seems to have had good results, though, so I'm excited to see what happens). I know out of safety you'll say I shouldn't do it, but is the current dev branch (master?) stable enough to use?  We're planning on releasing our app next week and would love to have a solid splash screen included.

**Comment by ryanvanderpol** [comment] 2017-08-31 22:19
@nsillik bad news and sort of good news.  The good news is that my splash screen is now the first thing that shows up when the app opens.  The bad news is I think it's all even weirder now than it was before.  Here's an updated video of what happens when I open my app after this last update:

![splash-2](https://user-images.githubusercontent.com/1936460/29947376-4dbd60fa-8e77-11e7-8dd7-74a86fd1f275.gif)

Now what I see is:
1. Splash screen (yay!)
2. White screen
3. loading screen
4. Splash screen (again?)
5. white flash
6. my app

**Comment by sonaye** [comment] 2017-09-02 08:30
@ryanvanderpol are you using `<AppLoading />`?

**Comment by ryanvanderpol** [comment] 2017-09-02 13:55
@sonaye I don't know what this is, so... no.  I spent the last couple days chatting with @nsillik directly and I think he's figured it all out.  I'll let him update this issue with his findings.

**Comment by sonaye** [comment] 2017-09-02 15:04
I suspected that, I would recommend [<AppLoading />](https://docs.expo.io/versions/v20.0.0/sdk/app-loading.html) to be the first rendered component of your app to ensure a seamless transition between it and the splash screen.

+ I noticed another issue with the splash screen (after update), I will outline it in a gif later today.

**Comment by sonaye** [comment] 2017-09-02 16:17
<img width="400" alt="screen shot 2017-09-02 at 6 49 17 pm" src="https://user-images.githubusercontent.com/23000873/29996787-dd3d7f48-900d-11e7-8584-a495820af287.gif">

Notice the sequence:
1) Opening the app, original icon disappears as preparation for the transition (so far so good).
<img width="144" alt="screen shot 2017-09-02 at 6 48 20 pm" src="https://user-images.githubusercontent.com/23000873/29996880-9f057602-900f-11e7-82e1-7e83282a08ee.png">

2) During transition, the splash screen is not loaded, instead backgroundColor is doing the work here while loading the splash screen locally (I am guessing) + the indicator is showing during transition (known issue).

<img width="231" alt="screen shot 2017-09-02 at 6 48 37 pm" src="https://user-images.githubusercontent.com/23000873/29996881-9f0c3852-900f-11e7-8f28-de755aaa9b72.png">
<img width="399" alt="screen shot 2017-09-02 at 6 48 46 pm" src="https://user-images.githubusercontent.com/23000873/29996882-9f11279a-900f-11e7-8d68-d8e94cb26970.png">

3) The app is now taking the full size of the screen and no splash screen yet.
<img width="397" alt="screen shot 2017-09-02 at 6 49 07 pm" src="https://user-images.githubusercontent.com/23000873/29996883-9f17ce56-900f-11e7-8f80-465f5d0dd3bd.png">

4) The splash screen starts showing, this is not the expected behavior, this should happen in (1).
<img width="398" alt="screen shot 2017-09-02 at 6 49 17 pm" src="https://user-images.githubusercontent.com/23000873/29996884-9f1d00f6-900f-11e7-87b0-d2edd26ae6bf.png">

5) Now the splash screen is present.
<img width="397" alt="screen shot 2017-09-02 at 6 51 04 pm" src="https://user-images.githubusercontent.com/23000873/29996894-c7bb1dd6-900f-11e7-8f77-1ad75b9986cc.png">

6) White screen (knowing issue)
7) `<AppLoading />` is mounted while loading assets/fonts .. etc.
8) `<App />` is mounted when ready.

Not sure why this is happening, this **only** happens for IOS builds submitted through TestFlight, builds with `--type simulator` work fine similar to my gif above https://github.com/expo/expo/issues/542#issuecomment-326386121.

cc: @nsillik

**Comment by cseelus** [comment] 2017-09-05 18:49
What size do you all use for your splash screen? We use 2732x2048 (to also work up to the iPad Pro 12.9 screen) and since 20.1.1 (worked with 20.0.1) we have this rather strange issue with its aspect ratio on smaller screens:

After opening
![img_7228](https://user-images.githubusercontent.com/3188392/30051555-c31f9d82-9222-11e7-9045-613f9482d104.jpg)

After a few ms (this is as it should be)
![img_7229](https://user-images.githubusercontent.com/3188392/30051545-b968a676-9222-11e7-8e9a-60eea44addb4.jpg)

**Comment by ryanvanderpol** [comment] 2017-09-05 18:51
@cseelus we're using 1080x1920 for the base.  I'm not sure if Expo uses the `@2x` images for this, but we also have a 2160x2840 version in there, too.

**Comment by AdamPD** [comment] 2017-09-07 03:57
This is affecting our app too.  The process seems to work like this:

- Tapping the app icon expands the app with the correct `backgroundColor` and a spinner, but nothing else (no `backgroundImage`).
- The screen almost immediately switches to the all white screen for almost an entire second (way more than just a "flicker").
- After the white screen, it finally shows the `backgroundImage` correctly with the spinner until `AppLoading` is unmounted.

Ultimately, it looks very unprofessional.  We expect this:

- Splash screen to appear immediately with the correct `backgroundImage` and no spinner.
- As soon as the app starts loading assets, the spinner appears (without any flickering etc.)
- Assets load and the loading screen disappears.

**Comment by AdamPD** [comment] 2017-09-12 01:40
Just a follow up which seems to affect Android.  Android will load the `icon` in the `loading` key and display that over the top of the `backgroundImage`.  So if you want a splash image on Android you almost have to use an "empty"/transparent icon to not have it conflict.  Furthermore, Android doesn't seem to bundle the icon into the apk, therefore it takes some time for the icon to initially show.

We really need a consistent API for both platforms.

**Comment by AdamPD** [comment] 2017-09-13 13:52
@ryanvanderpol - in my case I simply went with a loading icon (no backgroundImage) at the root level, and then a splash backgroundImage for iOS only.  This "works" (with the obvious issues of delays in loading icon because it's in a CDN etc.)

**Comment by sonaye** [comment] 2017-09-22 02:44
<img src="https://user-images.githubusercontent.com/23000873/30727086-be4b1f88-9f57-11e7-84d4-90c3cf93f8b9.gif" width="400">

SDK 21, still unable to get the result we are looking for, would appreciate an updated example on how to implement this properly.

- White screen is still visible
- Glitch when transitioning from splash to loading screens for the first time, possibly because the splash image is bundled whereas the loading image is downloaded, is it possible to show the splash bundled image on both the splash and loading screens?

Other issues on IOS have been resolved, thanks for the work @nsillik.

**Comment by jhalborg** [comment] 2017-09-22 06:48
Also very interested in a way to move/style the activity indicator.

**Comment by ryanvanderpol** [comment] 2017-09-22 15:32
Update from my end now with v21.  Marginal improvement, but still unacceptable.  Here is what I see:

1. Splash screen (yay! this is new)
2. blank white screen
3. blank screen with my background color
4. splash screen again
5. white flash
6. sign in screen

2-5 should not be happening.

![splash-v21](https://user-images.githubusercontent.com/1936460/30752051-219c92fc-9f89-11e7-89c6-2814d46c3d07.gif)

**Comment by jhalborg** [comment] 2017-09-26 09:10
@sonaye and @cseelus - How did you move the activityindicator below the middle? Mine looks like this:

![simulator screen shot - iphone 5s - 2017-09-26 at 11 03 27](https://user-images.githubusercontent.com/6643672/30852160-25730cb0-a2ab-11e7-9919-dc3bc9d7c16b.png)

SDK 20.0, app.json:

```...
"loading": {
      "backgroundImage": "./assets/icons/Splash.png",
      "hideExponentText": true
    },
...

**Comment by sonaye** [comment] 2017-09-26 09:15
@jhalborg Upgrade to SDK 21 and use [the new API](https://docs.expo.io/versions/latest/guides/configuration.html#splash-2). `hideExponentText` is deprecated you can remove it, no need for `loading` if it's the same as the splash I believe.

**Comment by sonaye** [comment] 2017-09-29 15:16
@nsillik We are holding a first release waiting for this issue to be addressed, can you provide any update?

**Comment by terribleben** [comment] 2017-09-29 16:02
We're expecting to land some improvements here in SDK 22.

**Comment by pcooney10** [comment] 2017-10-05 19:34
Is there any way to test the new Splash screen api in iOS without doing `exp build:ios`? If no, is there any way to run the generated `.ipa` file on a simulator before submitting it to the app store?

**Comment by cseelus** [comment] 2017-10-05 21:52
@pcooney10 Stackoverflow might be your friend for that type of questions, but try `exp build:ios --type simulator`

**Comment by AdamPD** [comment] 2017-10-18 00:15
I really feel getting this right should be a very high priority.  It makes the apps look really unprofessional.

**Comment by dikaiosune** [comment] 2017-10-18 00:15
@AdamPD I agree wholeheartedly. Stay tuned for our next release, several improvements coming.

**Comment by sonaye** [comment] 2017-10-19 08:05
Fixed in SDK 22, managed to get a pre-release sneak peak.

<img src="https://user-images.githubusercontent.com/23000873/31760245-ba1baa7a-b4bc-11e7-89ff-23ccb4b29482.gif" width="400">

**Comment by terribleben** [comment] 2017-10-19 22:36
Closing this since the issue report is no longer reflected in what we shipped with SDK 22. If more specific bugs come up, feel free to open more issues.

**Closed by terribleben** 2017-10-19 22:36 UTC
Labels: project: client-android, project: client-ios

**Comment by 3axap4eHko** [comment] 2017-11-28 00:35
But Android has the same issue

**Comment by mauroporrasp** [comment] 2018-01-01 15:37
Same issue in Android.

**Comment by vdlindenmark** [comment] 2018-04-05 13:59
Same issue for Android. iOS is fixed for no.
@terribleben , please reopen for android...
