### ISSUE TITLE
Push Notifications don't work on new phone that is restored from an old phone due to duplicate device ID

### ISSUE THREAD

**Issue by rikkitissier** [expo/expo#6051] opened 2019-10-21 21:02 UTC
### Environment

(Relates to Expo Push Notification service)

### Steps to Reproduce

1) Set up a new iPhone, and choose to restore from a backup of an existing iPhone with the Expo client or production expo app.
2) Try sending a push notification using the Expo notification tool to the push token reported by the new phone (it'll be the same as the one on the old phone!)

### Expected Behavior

I would expect _both_ devices (old and new) to receive the notification, or at the very least the newest-registered device. 

### Actual Behavior

Only the old device receives the notification.

This is happening because both devices now have the *same* Device ID/push token, which is supposed to be unique across app installations. I guess restoring a phone from a backup doesn't count as a new installation in practice.

While ideally each device would have a unique ID, even if restored from the same backup, another solution would be to ensure all devices with the same ID receive push notifications.

### Reproducible Demo

I can't really do this since it requires restoring a phone from a backup :D

**Comment by cruzach** [comment] 2019-10-22 14:16
The push token will stay the same, that's intended. However, the new device should be receiving the push notification. Is this happening in the Expo Client, or in a standalone app?

**Comment by rikkitissier** [comment] 2019-10-22 16:00
Both... well, neither I suppose is more accurate! I wasn't receiving push notifications either in the Expo client or my production app (which is installed via TestFlight). If I sent a notification using the Expo notification tool (to rule out any issue with our own infrastructure), Expo client on the old phone received it, but the new phone did not.

Once I reinstalled the Expo client on the new phone (to generate a new push token) then it was able to receive them.

**Comment by cruzach** [comment] 2019-10-22 17:36
Well, glad you were able to keep it working. It's been known to cause issues for push notifications if you continue using the old phone that you migrated from

**Comment by outaTiME** [comment] 2020-01-06 22:42
Hi guys i can confirm this, 

Today i bought a new phone and configured transferring data from my old device, after that the new device gets the same installation id and push token instead of a new one, expo should need to handle this to send notifications to the new device.

Thanks !!!

**Comment by travislang** [comment] 2020-01-07 16:37
I ran into the same issue, and it got merged into issue #2824.

This seems like a pretty major bug since I have not figured out any way to detect when this happens to alert the user.

@cruzach You said that the push token is supposed to stay the same, but isn't the push token based on the underlying device ID?  Plus I can't imagine the installationId should stay the same since that is unique based on the device too...?

**Comment by imwilliamxy** [comment] 2020-12-03 02:43
We are experiencing the same problem.
Restore app from iCloud in new iOS device, But the device id and push token  are as same as old device.

**Comment by brentvatne** [comment] 2020-12-03 05:25
this will be resolved in sdk 40, see https://github.com/expo/expo/pull/10261 for context

**Comment by cruzach** [comment] 2020-12-03 15:48
adding on to what Brent said, if you'd like to get your hands on the fix out right now- you can [try out the SDK 40 beta](https://blog.expo.io/expo-sdk-40-beta-is-now-available-2e98264f66b2) 💻 thanks in advance for helping us make our releases even smoother!

**Comment by cruzach** [comment] 2020-12-18 16:44
SDK 40 is released so I'm going to close this issue, lmk if you're still seeing this on the newest version

**Closed by cruzach** 2020-12-18 16:44 UTC
Labels: Notifications, bug
