### ISSUE TITLE
[expo-updates] Native iOS crash when new OTA update is available

### ISSUE THREAD

**Issue by mackenziekira** [expo/expo#14930] opened 2021-10-27 23:55 UTC
### Summary

Seeing a native iOS crash consistently when updating from sdk 42 app version to sdk 43 app version, when there is a new OTA update available for the sdk 43 version. Built via EAS Build.

From crash report, looks like the native error is:
`#3	0x10412022c in __90-[EXUpdatesAppLauncherWithDatabase _maybeCopyAssetFromMainBundle:withLocalUrl:completion:]_block_invoke ()
`
<img width="505" alt="Screen Shot 2021-10-27 at 4 53 05 PM" src="https://user-images.githubusercontent.com/7525998/139163577-3b99650b-9301-4d5d-a068-d357379049ab.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

```
  Expo CLI 4.4.6 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 17.0.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.2 => 0.16.2 
      expo: ^43.0.1 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1) Have two app builds in Testflight, both built via EAS Build, but one is on Expo SDK 42 (tied to release channel `"sdk42-release-candidate-v0"`), and the other has been updated to Expo SDK 43 (tied to release channel `"sdk43-release-candidate-v0"`).
2) From TestFlight, download SDK 42 build
3) Publish an OTA update to SDK 43 release channel (`"sdk43-release-candidate-v0"`)
4) Download SDK 43 build from TestFlight
5) Open, hard close, and reopen app. On second open, see native crash

**Comment by zhigang1992** [comment] 2021-10-30 15:32
This was happening for a lot for us as well, we are blocked on release for this.

**Comment by RodolfoGS** [comment] 2021-11-01 01:52
I've the same issue upgrading from `expo:42.0.3, expo-updates:0.8.4` to `expo:43.0.1, expo-updates:0.10.9`
iOS Hermes disabled.
Described perfectly by @mackenziekira and @zhigang1992
This is a stopper to launch to production for me.

**Comment by zhigang1992** [comment] 2021-11-01 02:50
Are you guys using custom fonts by any chance? from `@expo-font` for example?

**Comment by zhigang1992** [comment] 2021-11-01 04:46
On the instance of crash, it seems like the sourceUrl is nil

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/1057756/139622882-abf9a2a8-4412-47e6-8184-9694450d76cd.png">

and prior to the crash, the successful lunch has following logs

```
2021-11-01 12:44:39.968016+0800 popshoplive[14644:3665743] [native] Could not find image file:///var/mobile/Containers/Data/Application/F3670E13-65F0-474C-A61C-7B0517F04B92/Library/Application%20Support/.expo-internal/d8a27e7402627398acca24ea9700790a.png
2021-11-01 12:44:39.969592+0800 popshoplive[14644:3665743] [native] Could not find image file:///var/mobile/Containers/Data/Application/F3670E13-65F0-474C-A61C-7B0517F04B92/Library/Application%20Support/.expo-internal/d8a27e7402627398acca24ea9700790a.png
2021-11-01 12:44:40.030503+0800 popshoplive[14644:3665743] [native] RNBlurhash: The provided Blurhash string was invalid.
2021-11-01 12:44:40.031985+0800 popshoplive[14644:3665743] [native] RNBlurhash: The provided Blurhash string was invalid.
2021-11-01 12:44:40.032141+0800 popshoplive[14644:3665743] [native] RNBlurhash: The provided Blurhash string was invalid.
2021-11-01 12:44:40.032978+0800 popshoplive[14644:3665743] [native] RNBlurhash: The provided Blurhash string was invalid.
2021-11-01 12:44:40.037782+0800 popshoplive[14644:3665743] [native] Could not find image file:///var/mobile/Containers/Data/Application/F3670E13-65F0-474C-A61C-7B0517F04B92/Library/Application%20Support/.expo-internal/d8a27e7402627398acca24ea9700790a.png
2021-11-01 12:44:40.039282+0800 popshoplive[14644:3665743] [native] Could not find image file:///var/mobile/Containers/Data/Application/F3670E13-65F0-474C-A61C-7B0517F04B92/Library/Application%20Support/.expo-internal/d8a27e7402627398acca24ea9700790a.png
2021-11-01 12:44:40.040749+0800 popshoplive[14644:3665743] [native] Could not find image file:///var/mobile/Containers/Data/Application/F3670E13-65F0-474C-A61C-7B0517F04B92/Library/Application%20Support/.expo-internal/d8a27e7402627398acca24ea9700790a.png
2021-11-01 12:44:40.042603+0800 popshoplive[14644:3665743] [native] Could not find image file:///var/mobile/Containers/Data/Application/F3670E13-65F0-474C-A61C-7B0517F04B92/Library/Application%20Support/.expo-internal/d8a27e7402627398acca24ea9700790a.png
2021-11-01 12:44:40.050253+0800 popshoplive[14644:3665743] [native] Could not find image file:///var/mobile/Containers/Data/Application/F3670E13-65F0-474C-A61C-7B0517F04B92/Library/Application%20Support/.expo-internal/d8a27e7402627398acca24ea9700790a.png
2021-11-01 12:44:40.082999+0800 popshoplive[14644:3665743] [native] Could not find image file:///var/mobile/Containers/Data/Application/F3670E13-65F0-474C-A61C-7B0517F04B92/Library/Application%20Support/.expo-internal/d8a27e7402627398acca24ea9700790a.png
2021-11-01 12:44:40.084363+0800 popshoplive[14644:3665743] [native] Could not find image file:///var/mobile/Containers/Data/Application/F3670E13-65F0-474C-A61C-7B0517F04B92/Library/Application%20Support/.expo-internal/d8a27e7402627398acca24ea9700790a.png
2021-11-01 12:44:40.118970+0800 popshoplive[14644:3665743] [native] Could not find image file:///var/mobile/Containers/Data/Application/F3670E13-65F0-474C-A61C-7B0517F04B92/Library/Application%20Support/.expo-internal/d8a27e7402627398acca24ea9700790a.png
```

**Comment by zhigang1992** [comment] 2021-11-01 05:19
```
diff --git a/node_modules/expo-updates/ios/EXUpdates/AppLauncher/EXUpdatesAppLauncherWithDatabase.m b/node_modules/expo-updates/ios/EXUpdates/AppLauncher/EXUpdatesAppLauncherWithDatabase.m
index f5d6706..06b272a 100644
--- a/node_modules/expo-updates/ios/EXUpdates/AppLauncher/EXUpdatesAppLauncherWithDatabase.m
+++ b/node_modules/expo-updates/ios/EXUpdates/AppLauncher/EXUpdatesAppLauncherWithDatabase.m
@@ -260,8 +260,12 @@ - (void)_maybeCopyAssetFromMainBundle:(EXUpdatesAsset *)asset
     }

     if (matchingAsset && matchingAsset.mainBundleFilename) {
+      NSString *bundlePath = [[NSBundle mainBundle] pathForResource:matchingAsset.mainBundleFilename ofType:matchingAsset.type];
+      if (bundlePath == nil) {
+        completion(NO, nil);
+        return;
+      }
       dispatch_async([EXUpdatesFileDownloader assetFilesQueue], ^{
-        NSString *bundlePath = [[NSBundle mainBundle] pathForResource:matchingAsset.mainBundleFilename ofType:matchingAsset.type];
         NSError *error;
         BOOL success = [NSFileManager.defaultManager copyItemAtPath:bundlePath toPath:[assetLocalUrl path] error:&error];
         dispatch_async(self->_launcherQueue, ^{
```

This patch will prevent the crash from happening, but I'm not sure if it will have any affect on the update itself.

**Comment by awinograd** [comment] 2021-11-01 15:14
I wonder if this missing asset issue might be related to / share a root cause with https://github.com/expo/expo/issues/14806?

**Comment by brentvatne** [comment] 2021-11-02 00:08
thank you for reporting! @esamelson is investigating

**Comment by esamelson** [comment] 2021-11-02 00:51
Hey everyone, thanks for the reports. We've just published @zhigang1992 's patch (thanks again for the PR!) in expo-updates@0.10.10, which should at least mitigate this issue and prevent any more crash loops while we continue to investigate the root cause.

**Comment by RodolfoGS** [comment] 2021-11-02 02:02
@esamelson I tested that version (`0.10.10`) on testflight, native crash was gone but now after receive an OTA update I receive this exception.
```
File 'file:///var/mobile/Containers/Data/Application/FD7062A7-4C3E-4272-847E-0C6148EACE99/Library/Application%20Support/.expo-internal/140c53a7643ea949007aa9a282153849.ttf' for font 'evilicons' doesn't exist
```

I load this fonts in my `App.js` like this:

```
import * as Font from 'expo-font';
import * as Icon from '@expo/vector-icons';

...

async componentDidMount() {
    ...

    await Font.loadAsync({
        // preload icons
        ...Icon.EvilIcons.font,
        ...Icon.Ionicons.font,
        ...Icon.SimpleLineIcons.font,
    });
}
```

```
expo: 43.0.1
@expo/vector-icons: 12.0.5
expo-font: 10.0.3
expo-updates: 0.10.10
```

**Comment by esamelson** [comment] 2021-11-02 03:11
thanks for the info @RodolfoGS . do you have the same code and fonts in the SDK 42 version of your app?

**Comment by RodolfoGS** [comment] 2021-11-02 12:14
@esamelson Yes, the same code and the same fonts. No one line changed in the code of App.js, 100% equal.

**Comment by collinrijock** [comment] 2021-11-02 17:25
> Hey everyone, thanks for the reports. We've just published @zhigang1992 's patch (thanks again for the PR!) in expo-updates@0.10.10, which should at least mitigate this issue and prevent any more crash loops while we continue to investigate the root cause.

Upgrading the expo-updates solved this issue for me. Thanks!

**Comment by esamelson** [comment] 2021-11-02 18:46
@RodolfoGS (or anyone else running into this issue) -- could I ask which version of expo-updates you had installed in the SDK 42 build of your app?

**Comment by mackenziekira** [comment] 2021-11-02 18:53
@esamelson I had `"0.8.0"` installed in the sdk 42 build

**Comment by collinrijock** [comment] 2021-11-02 19:23
I had "expo-updates": "~0.8.2",

**Comment by RodolfoGS** [comment] 2021-11-02 19:41
I had expo:42.0.3, expo-updates:0.8.4

**Comment by esamelson** [comment] 2021-11-02 21:25
thanks all. really sorry about this issue, it's been difficult to track down, but we've now released expo-updates@0.10.11 with a more comprehensive fix. if you're still running into this issue, 0.10.11 should resolve the problem, but please do let me know if not!

**Comment by RodolfoGS** [comment] 2021-11-03 02:22
I updated to `0.10.11` but I continue receiving the exception when I try to load the fonts.
1. I install a version app with `expo: 42.0.3` + `expo-updates: 0.8.4` from TestFlight
2. Open the app
3. Install a version with `expo: 43.0.1` + `expo-updates: 0.10.11` from TestFlight
4. Open the app and automatically download an OTA version.
5. Fire the exception: 
```
File 'file:///var/mobile/Containers/Data/Application/0636F34F-8C96-4467-A1AD-375D1173FFE6/Library/Application%20Support/.expo-internal/140c53a7643ea949007aa9a282153849.ttf' for font 'evilicons' doesn't exist
```

**Comment by esamelson** [comment] 2021-11-03 03:40
Yikes, thanks for the report 😕 we'll continue looking into this.

I've still been unable to fully reproduce the issue, unfortunately. A few questions -- before (1) is another version of the app installed, or is it a fresh installation? and in (2), is an OTA update downloaded to the SDK 42 app?

**Comment by Yonom** [comment] 2021-11-03 22:01
@esamelson we are getting a ton of weird behavior in our SDK 43 builds due to this bug https://github.com/expo/expo/issues/15033

Maybe it is related to this? I don't know...

**Comment by mattaronoff** [comment] 2021-11-04 18:13
Confirming @RodolfoGS 's experience even after updating to expo-updates v0.10.12. We've got a bare workflow app, and the following path is broken:

* Install App Store build, enter and set up app as normal
* Update (via TestFlight) to the new, post-SDK-43 build
* On first run of the new build, all image and font assets are missing.
* After killing and restarting the app, things work as expected (this is different than pre-patch, when we'd end up in a crash-on-launch loop here).

We still can't ship with the app behaving this way, though. Any movement here?

**Comment by esamelson** [comment] 2021-11-04 19:36
Yes, we've finally been able to identify and reproduce the root issue here. A fix is in flight and should be coming later today. Hang tight -- we're really sorry for the inconvenience!!

**Comment by esamelson** [comment] 2021-11-05 01:09
Hi all -- expo-updates@0.10.13 is out now with what should be the final fix for this issue. Thanks to everyone who provided comprehensive reports and information about this bug, and apologies once again that we let it slip through the cracks. Please let me know if this patch resolves things for you.

**Comment by RodolfoGS** [comment] 2021-11-05 02:05
Awesome, thank you so much @esamelson. I've just tested `expo-updates@0.10.13` and now works perfectly 👍
Tested on iOS 15.1, iPhone X.

**Closed** 2021-11-08 16:48 UTC
Labels: Updates, needs review, SDK 43
