### ISSUE TITLE
Recent increase in 'No matching activity' errors from `WebBrowser.openBrowserAsync()`

### ISSUE THREAD

**Issue by WolfyUK** [expo/expo#12045] opened 2021-02-26 08:21 UTC
**Summary**

An app in production since August 2020 that launches a web browser using `WebBrowser.openBrowserAsync()` is failing to do so without throwing 'No matching activity' errors on some Android devices, but with an increasing frequency during 2021 so far. It seems to be mostly affecting devices running Android 11 (a full list of device models is available).

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

_No response_

**Environment**

Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      npm: 6.14.11 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.12 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: 0.61.4 => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
      react-navigation: ^4.0.10 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

```
...
try {
  await WebBrowser.openBrowserAsync("https://www.google.co.uk");
} catch (e) {
  console.error(e.message); // === "No matching activity"
}
```

The issue above is occurring with increasing frequency on an app in production on Expo 37. I am aware of `WebBrowser.getCustomTabsSupportingBrowsersAsync()` which will be implemented to determine whether a browser is available before attempting to open one, but I would like to know why this may be suddenly occurring more often. A new version of the app on Expo 39 is not ready to be released but I am concerned that the problem will still persist. I am unable to replicate in the Emulator running Android 11.

For reference, the affected devices to date are:

- CPH2025
- J8110
- J8210
- Pixel 2
- Pixel 3
- Pixel 3a
- Pixel 5
- SM-F916B
- SM-G770F
- SM-G780F
- SM-G781B
- SM-G970F
- SM-G973F
- SM-G975F
- SM-G977B
- SM-G980F
- SM-G981B
- SM-G986B
- SM-G988B
- SM-G991B
- SM-G996B
- SM-G998B
- SM-N770F
- SM-N970F
- SM-N975F
- SM-N976B
- SM-N980F
- SM-N981B
- SM-N986B
- T799H
- XQ-AT51
- XQ-AU51
- XQ-AU52

Unfortunately OS versions are not currently logged in the version of the app in production but my suspicion is that these are Android 11.

**Comment by WolfyUK** [comment] 2021-02-26 10:36
Just found [this link](https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9), but I'm not sure of its relevance.

**Comment by WolfyUK** [comment] 2021-02-26 11:39
Also receiving the following exception on Android 11 in the Emulator when calling `WebBrowser.getCustomTabsSupportingBrowsersAsync()`. This does not occur in Expo 39, so I expect the answer to this query will be to upgrade.

```
Error: Encountered an exception while calling native method: Exception occurred while executing exported method getCustomTabsSupportingBrowsersAsync on module ExpoWebBrowser: Attempt to read from field 'android.content.pm.ActivityInfo android.content.pm.ResolveInfo.activityInfo' on a null object reference
fn@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2152:45
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:116068:40
getCustomTabsSupportingBrowsersAsync$@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:212848:107
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25691:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25867:32
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25691:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25767:30
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25797:19
tryCallTwo@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27056:9
doResolve@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27220:25
Promise@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27079:14
callInvokeWithMethodAndArg@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25796:33
enqueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25801:157
async@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25818:69
getCustomTabsSupportingBrowsersAsync@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:212827:38
canOpenBrowser$
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25691:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25867:32
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25691:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25767:30
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25797:19
tryCallTwo@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27056:9
doResolve@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27220:25
Promise@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27079:14
callInvokeWithMethodAndArg@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25796:33
enqueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25801:157
async@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25818:69
_callee$@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:297149:91
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25691:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25867:32
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25691:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25767:30
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25797:19
tryCallTwo@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27056:9
doResolve@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27220:25
Promise@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27079:14
callInvokeWithMethodAndArg@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25796:33
enqueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25801:157
async@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25818:69
_callee@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:297142:42
executeAction@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:100863:22
res@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:100843:27
_callee3$@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:292900:81
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25691:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25867:32
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25691:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25767:30
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25797:19
tryCallTwo@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27056:9
doResolve@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27220:25
Promise@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27079:14
callInvokeWithMethodAndArg@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25796:33
enqueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25801:157
async@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25818:69
_callee3@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:292895:42
touchableHandlePress@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:53846:47
touchableHandlePress@[native code]
_performSideEffectsForTransition@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:52482:36
_performSideEffectsForTransition@[native code]
_receiveSignal@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:52408:46
_receiveSignal@[native code]
touchableHandleResponderRelease@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:52287:26
touchableHandleResponderRelease@[native code]
invokeGuardedCallbackImpl@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:9056:21
invokeGuardedCallback@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:9152:42
invokeGuardedCallbackAndCatchFirstError@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:9156:36
executeDispatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:9263:48
executeDispatchesInOrder@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:9283:26
executeDispatchesAndRelease@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:9388:35
forEach@[native code]
forEachAccumulated@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:9378:22
runEventsInBatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:9412:27
runExtractedPluginEventsInBatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:9500:25
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10526:42
batchedUpdates$1@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:21980:20
batchedUpdates@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10474:36
_receiveRootNodeIDEvent@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10525:23
receiveTouches@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10555:34
__callFunction@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2696:49
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2409:31
__guard@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2650:15
callFunctionReturnFlushedQueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2408:21
callFunctionReturnFlushedQueue@[native code]
```

**Comment by WolfyUK** [comment] 2021-02-26 13:13
I have also tried upgrading `expo-web-browser` from `8.2.1` to `8.5.0` (as seems to be working in Expo 39) to no avail within the Expo 37 project

**Comment by nnabinh** [comment] 2021-05-25 02:18
I'm experiencing the same issue. It fails randomly on Android devices.
Expo 41.

**Comment by sohcah** [comment] 2021-07-09 16:20
Getting the same issue here, rather frustrating.

**Comment by giautm** [comment] 2021-07-28 00:55
I getting same issue, Android 11, device model SM-A507FN

**Comment by giautm** [comment] 2021-07-28 01:01
This issue may related

https://github.com/expo/expo/issues/2838

**Comment by RenatoSerra22** [comment] 2021-07-31 10:54
Still getting this for a few of my users and already got a negative review for it :(

**Comment by giautm** [comment] 2021-07-31 14:18
> Still getting this for a few of my users on android trying to login with google

Hi, I can preproduce this case on android. Just remove all browser and disable chrome in Settings. You will get this error.

**Comment by pekq** [comment] 2021-08-02 14:04
My users were also experiencing this. I was able to track this back to a single commit where we bumped Android API version target from `29` to `30`.

So going back to `29` resolved the issue for us:

`build.gradle`

```diff
project.ext {
  minSdkVersion = 23
+  compileSdkVersion = 29
+  targetSdkVersion = 29
+  buildToolsVersion = '29.0.2'
-  compileSdkVersion = 30
-  targetSdkVersion = 30
-  buildToolsVersion = '30.0.0'
}
```

**Comment by tomKrueger** [comment] 2021-08-17 01:42
Hey I seem to be getting this error as well.   Building new app but did most on iOS now working on Android and getting blocked by this.  Appreciate the help as I'm stuck!

Using Android Emulator Pixel 5 API 30.

A few versions from Package.json:
"expo": "^42.0.3",
"expo-auth-session": "~3.3.1",
"expo-web-browser": "~9.2.0",
"react-native-web": "~0.13.18",
"react-native-webview": "11.6.5",

I'm getting it when trying to prompt for login using AuthSession.  AuthSession opens a browser.
const authRequest = new AuthSession.AuthRequest(authRequestOptions);
const authorizeResult = await authRequest.**promptAsync**(discovery, {
      useProxy: true,
});
       
promptAsync is causing the error.

Stack Trace:
[Unhandled promise rejection: Error: No matching activity!]
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:50 in promiseMethodWrapper
at node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-web-browser/build/WebBrowser.js:57:7 in openBrowserAsync
at node_modules/expo-web-browser/build/WebBrowser.js:57:7 in openBrowserAsync
at node_modules/expo-web-browser/build/WebBrowser.js:158:0 in _openBrowserAndWaitAndroidAsync
at http://192.168.68.110:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:219844:37 in _openBrowserAndWaitAndroidAsync
at node_modules/expo-web-browser/build/WebBrowser.js:173:0 in _openAuthSessionPolyfillAsync
at node_modules/expo-web-browser/build/WebBrowser.js:173:0 in _openAuthSessionPolyfillAsync
at node_modules/expo-web-browser/build/WebBrowser.js:86:7 in openAuthSessionAsync
at node_modules/expo-web-browser/build/WebBrowser.js:86:7 in openAuthSessionAsync
at node_modules/expo-auth-session/build/AuthRequest.js:75:4 in promptAsync
at http://192.168.68.110:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:220145:41 in promptAsync
at node_modules/expo-auth-session/build/AuthRequest.js:75:4 in promptAsync

Thank you!!!!!
Tom

**Comment by sumnerwarren** [comment] 2021-08-25 13:45
We are seeing this on some Android 11 devices when the user has the DuckDuckGo app set as their default browser. It seems that DuckDuckGo does not support the Custom Tabs Service and thus is not included in the `servicePackages` returned by [`WebBrowser.getCustomTabsSupportingBrowsersAsync`](https://docs.expo.dev/versions/latest/sdk/webbrowser/#webbrowsergetcustomtabssupportingbrowsersasync), which causes `defaultBrowserPackage` to be null. This helper is not actually used by `openBrowserAsync`, but as best I can tell it effectively does the same sort of intent lookup and ultimately come to the conclusion that DuckDuckGo as a default browser cannot be used as an auth session browser.

If the user changes their 1) default browser, 2) uninstalls DuckDuckGo, or 3) has DuckDuckGo installed without a default browser being selected, then `openBrowserAsync` works as expected. I was able to reproduce the issue and the user-initiated resolutions in a Pixel 4 API 30 emulator with DuckDuckGo, Chrome, and the OS default web browser installed. I'm not sure if this is an Expo bug necessarily, but it definitely seems wrong that although there are browsers available that could work as an auth session browser (Chrome in this case), the attempt fails seemingly because the default browser does not meet the requirements.

A development-driven solution that appears to work is adding
```
<queries>
  <package android:name="com.duckduckgo.mobile.android" />
</queries>
```
to our app's manifest file (following [this post](https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9) linked above). This is obviously a very specific and poor solution, but it may help determine how to approach the intent resolution issue.

**Comment by timoisalive** [comment] 2021-09-02 12:36
Hey, we bumped into this error as well and I was wondering does the above merged PR fix the issue? If so, I assume it will be included in the next expo release, right?

**Comment by sumnerwarren** [comment] 2021-09-02 18:27
@timoisalive No, #14181 does not resolve this issue. It fixes a related logic loop the user can get stuck in after encountering this issue.

**Comment by timoisalive** [comment] 2021-09-06 07:50
Ok, thanks for the info @sumnerwarren . Hopefully there's some progress on this issue as well soon...

**Comment by hixus** [comment] 2021-09-07 13:56
Stumbled upon this today as google map links stopped working with android 11 (api level 30) devices. 

This link `https://www.google.com/maps/search/?api=1&query=47.5951518%2C-122.3316393&query_place_id=ChIJKxjxuaNqkFQR3CK6O1HNNqY` is correct and from [google maps guide](https://developers.google.com/maps/documentation/urls/get-started). Works otherwise in the device but if opened thru our app with openBrowserAsync it results in `[Error: No matching activity!]`

With older android versions api level 28, 29 works fine.

**Comment by haveamission** [comment] 2021-11-02 00:43
> My users were also experiencing this. I was able to track this back to a single commit where we bumped Android API version target from `29` to `30`.
> 
> So going back to `29` resolved the issue for us:
> 
> `build.gradle`
> 
> ```diff
> project.ext {
>   minSdkVersion = 23
> +  compileSdkVersion = 29
> +  targetSdkVersion = 29
> +  buildToolsVersion = '29.0.2'
> -  compileSdkVersion = 30
> -  targetSdkVersion = 30
> -  buildToolsVersion = '30.0.0'
> }
> ```

This was working for me, but now trying to push a new build, Google Play Store requires 30 as of today, so this is a bit of a problem.

**Comment by plaporte** [comment] 2021-11-06 00:09
Any actual fix for this? With Google mandating API 30+, I haven't found a solution other than telling my users to set chrome as their default browser.

**Comment by mudiman** [comment] 2021-11-06 04:53
I also faced similar issue Note for any one simulator it doesnt work somehow it wasnt opening browser but it seems to work on actual device

**Comment by haveamission** [comment] 2021-11-06 06:29
Upgrading to Expo 41 seems to have fixed the issue for me

**Comment by plaporte** [comment] 2021-11-06 15:13
> Upgrading to Expo 41 seems to have fixed the issue for me

Expo 43 here with the issue persisting.

**Comment by joranb** [comment] 2021-11-18 11:55
I got the same issue using the Android emulator (Pixel running on API 30). Works fine in web, but get this error when trying to run it on Android and the browser does not start.

**Comment by pke** [comment] 2021-11-29 15:16
> > My users were also experiencing this. I was able to track this back to a single commit where we bumped Android API version target from `29` to `30`.
> > So going back to `29` resolved the issue for us:
> > `build.gradle`
> > ```diff
> > project.ext {
> >   minSdkVersion = 23
> > +  compileSdkVersion = 29
> > +  targetSdkVersion = 29
> > +  buildToolsVersion = '29.0.2'
> > -  compileSdkVersion = 30
> > -  targetSdkVersion = 30
> > -  buildToolsVersion = '30.0.0'
> > }
> > ```
> 
> This was working for me, but now trying to push a new build, Google Play Store requires 30 as of today, so this is a bit of a problem.

But now you can't publish to the Playstore anymore. They require 30 as target since November.

**Comment by thedewpoint** [comment] 2021-11-30 21:35
Also having this issue, Pixel 5 API 30 expo 42

**Comment by thedewpoint** [comment] 2021-11-30 23:18
I got it working by installing chrome on my emulator. I downloaded it from this link https://www.apkmirror.com/apk/google-inc/chrome/chrome-96-0-4664-45-release/google-chrome-fast-secure-96-0-4664-45-2-android-apk-download/download/?forcebaseapk

This doesn't help with people not having chrome installed though.

**Comment by bpringe** [comment] 2021-12-06 17:52
We've experienced this issue as well. This seems to make WebBrowser.openBrowserAsync not usable for production, at least for Android. Has anyone switched to a different method or found a workaround?

**Comment by tajetaje** [comment] 2021-12-12 21:40
> I got the same issue using the Android emulator (Pixel running on API 30). Works fine in web, but get this error when trying to run it on Android and the browser does not start.

Likewise, fine on iOS Expo Go, but the emulator goes nuts.

**Comment by rvmelo** [comment] 2021-12-15 22:32
I'm having the same issue and I'm on expo sdk 42 and android 11. This happens with me even with  google chrome navigator installed. This is what I get as a result from running `WebBrowser.getCustomTabsSupportingBrowsersAsync()`:

```
result:  Object {
  "browserPackages": Array [
    "com.sec.android.app.sbrowser",
  ],
  "defaultBrowserPackage": "com.sec.android.app.sbrowser",
  "preferredBrowserPackage": "com.sec.android.app.sbrowser",
  "servicePackages": Array [
    "com.android.chrome",
    "com.sec.android.app.sbrowser",
  ],
}
```

**Comment by armenavanesi** [comment] 2021-12-16 07:38
Getting this one too on Expo 42. Users can't log in via Google.

**Comment by boomboxbacardi** [comment] 2021-12-16 09:18
I solved this by upgrading Expo 40 to Expo 41.

**Comment by giautm** [comment] 2021-12-16 09:50
This is can't resolve by anyway, even upgrade SDK. It's related to Chrome on Android.

**Comment by boomboxbacardi** [comment] 2021-12-16 10:02
@giautm I'll be more thoroughly with my solution.

The error was thrown in the `expo-web-browser` package and bumping it alone didn't make it work. I tried several versions of that npm package but didnt work. 

I was able to conclude that `targetSdkVersion = 29` did not throw the "No matching activity" error but `targetSdkVersion = 30` gave me the error.

Solution that worked for me:

1. Get the latest expo cli version
2. Upgrade expo through their terminal wizard. Also follow this guide https://blog.expo.dev/expo-sdk-41-12cc5232f2ef (I use bare workflow)
3. Use `"expo-auth-session": "~1.4.0"` instead of later versions
4. Remove `expo-random` since it was failing my Android build


Note that I have not tested the iOS version yet. I had to get something out to fix this problem for some of our Android users.

**Comment by rvmelo** [comment] 2021-12-16 14:55
> I'm having the same issue and I'm on expo sdk 42 and android 11. This happens with me even with google chrome navigator installed. This is what I get as a result from running `WebBrowser.getCustomTabsSupportingBrowsersAsync()`:
> 
> ```
> result:  Object {
>   "browserPackages": Array [
>     "com.android.chrome",
>   ],
>   "defaultBrowserPackage": "com.android.chrome",
>   "preferredBrowserPackage": "com.android.chrome",
>   "servicePackages": Array [
>     "com.android.chrome",
>     "com.sec.android.app.sbrowser",
>   ],
> }
> ```
> 
> I'm using ` WebBrowser.openBrowserAsync` from ` expo-web-browser` to open my link to the browser.

A curious fact is that I get this error on my laptop and on my deskot it works fine. I tried running the project with `expo start` and with `expo build:android` and I get the same behaviour

**Comment by mrchess** [comment] 2021-12-17 16:25
Any easy way to reproduce this issue is to try to run, on Expo 43, the simple WebBrowser Redirect Example in a Pixel 5 API30 emulator.
https://github.com/expo/examples/tree/master/with-webbrowser-redirect

You will get this
<img width="202" alt="Screen Shot 2021-12-17 at 11 25 01 AM" src="https://user-images.githubusercontent.com/106922/146576162-4debabbd-27f6-42bc-b7b1-7bd3093a9f21.png">
.

**Comment by giautm** [comment] 2021-12-17 20:59
@mrchess : Do you trying to install Chrome on your emulator yet?

**Comment by beerent** [comment] 2021-12-28 12:16
for what it's worth - this happened to me because I was using an android emulator that did not have a browser. I installed an emulator that had the play store included with the emulator. This emulator had chrome installed out of the box and this error went away.

**Comment by hixus** [comment] 2022-01-13 10:12
I can repeat this with OnePlus Pro 9 and Expo 43 sdk. If url does redirect it fails to open. For example https://youtu.be/CeOjDcYqdIg does not work as it does redirect.

**Comment by Ggayane** [comment] 2022-01-13 21:00
@hixus I had the same issue for Android only, found the solution: it turned out you can pass the `browserPackage` as an option with the name of a browser, which you can get from `WebBrowser.getCustomTabsSupportingBrowsersAsync()`. 
Complete code:

```js
const tabsSupportingBrowsers = await WebBrowser.getCustomTabsSupportingBrowsersAsync();
const defaultBrowser = tabsSupportingBrowsers?.defaultBrowserPackage;
await WebBrowser.openBrowserAsync(href, { browserPackage: defaultBrowser })

**Comment by imegoff** [comment] 2022-01-14 11:25
The same issue persists on SM-F926U if Chrome is not marked as a default browser.

**Comment by giautm** [comment] 2022-01-14 21:47
@hixus hey, I don't think it breaks on other platforms, Based on this code https://github.com/expo/expo/blob/eb76b7b5e1ffbf6dd16f2b78b33f582b8a1b11be/packages/expo-web-browser/src/WebBrowser.ts#L36-L62

So, what is the exception?

**Comment by hixus** [comment] 2022-01-15 09:54
> @hixus hey, I don't think it breaks on other platforms, Based on this code
> 
> https://github.com/expo/expo/blob/eb76b7b5e1ffbf6dd16f2b78b33f582b8a1b11be/packages/expo-web-browser/src/WebBrowser.ts#L36-L62
> 
> So, what is the exception?

Seems ios exception is the one from line 55 (`The method or property WebBrowser.getCustomTabsSupportingBrowsersAsync is not available on ios, are you sure you've linked all the native dependencies properly`), so that should be moved to else clause or removed completely.

**Comment by tajetaje** [comment] 2022-01-17 16:56
> > @hixus hey, I don't think it breaks on other platforms, Based on this code
> 
> > 
> 
> > https://github.com/expo/expo/blob/eb76b7b5e1ffbf6dd16f2b78b33f582b8a1b11be/packages/expo-web-browser/src/WebBrowser.ts#L36-L62
> 
> > 
> 
> > So, what is the exception?
> 
> 
> 
> Seems ios exception is the one from line 55 (`The method or property WebBrowser.getCustomTabsSupportingBrowsersAsync is not available on ios, are you sure you've linked all the native dependencies properly`), so that should be moved to else clause or removed completely.

That would certainly fix the issue, but the availability check does fall before the platform check on all other methods of WebBrowser (and many other APIs I'm sure) so perhaps changing it to be inconsistent with those would not be the best choice? Of course I can't help but agree that I don't see the value in that design.

**Comment by danilo900** [comment] 2022-03-01 12:20
Hey, we still with that problem!?

{"browserPackages": [], "defaultBrowserPackage": null, "preferredBrowserPackage": null, "servicePackages": []}

**Comment by danilo900** [comment] 2022-03-01 13:47
Found out the Solution Guys:

https://developer.android.com/training/package-visibility/use-cases

Just add: 

`<queries>
    <intent>
      <action android:name="android.support.customtabs.action.CustomTabsService" />
    </intent>
  </queries>`

into AndroidManifest

Before:
{"browserPackages": [], "defaultBrowserPackage": null, "preferredBrowserPackage": null, "servicePackages": []}

After:
 {"browserPackages": ["com.android.chrome"], "defaultBrowserPackage": "com.android.chrome", "preferredBrowserPackage": "com.android.chrome", "servicePackages": ["com.android.chrome"]}

it was required in Android 11 (API level 30) or higher.


![Screen Shot 2022-03-01 at 10 42 55](https://user-images.githubusercontent.com/33874563/156180476-bf82b6a0-24f3-463f-854a-2fb6bc815bfb.png)

**Comment by giautm** [comment] 2022-03-01 14:04
> Found out the Solution Guys:
> https://developer.android.com/training/package-visibility/use-cases

The managed workflow really has intents for query check browser in the manifest: https://developer.android.com/training/package-visibility/use-cases#check-browser-available

What's your workflow? Managed or bare/ or vanilla RN project?

**Comment by danilo900** [comment] 2022-03-01 14:08
> 

Yea, Vanilla RN Project, so we need to manually add it.

I think managed doesn't need because expo control it, but it should be updated in expo packages (if ins't)

And on bare workflow I guess it should be done manually either

**Comment by danilo900** [comment] 2022-03-01 14:34
> > I think managed doesn't need because expo control it, but it should be updated in expo packages (if ins't)
> 
> The latest question: what's version of expo-web-browser? In the version 10.1.0 they have the intent in the manifest: https://github.com/expo/expo/blob/main/packages/expo-web-browser/android/src/main/AndroidManifest.xml

Ah nice!
Iam currently in a lower version ("expo-web-browser": "^8.6.0"), I can't update right now because of the new dependencies.

**Comment by isotopeee** [comment] 2022-03-08 12:47
In my case, I had to:

1. In `AndroidManifest.xml`, add:

```xml
<queries>
  <intent>
    <!-- Required for opening tabs if targeting API 30 -->
    <action android:name="android.support.customtabs.action.CustomTabsService" />
  </intent>
</queries>
```

2. I've encountered an "unexpected element \<queries\> found in \<manifest\>" error so I had to update the `android/build.gradle` and `android/gradle/wrapper/gradle-wrapper.properties` files: https://github.com/lukasgit/flutter_contacts/issues/220#issuecomment-1061725322

**Comment by isotopeee** [comment] 2022-03-09 11:57
> Hi @isotopeee, what is the version of package `expo-web-browser` in your application? Can you upgrade to the latest version?

I'm on `expo-web-browser` version `8.0.0`. I haven't tried upgrading yet though.

**Comment by abhishek18feb** [comment] 2022-03-23 04:27
> Found out the Solution Guys:
> 
> https://developer.android.com/training/package-visibility/use-cases
> 
> Just add:
> 
> `<queries> <intent> <action android:name="android.support.customtabs.action.CustomTabsService" /> </intent> </queries>`
> 
> into AndroidManifest
> 
> Before: {"browserPackages": [], "defaultBrowserPackage": null, "preferredBrowserPackage": null, "servicePackages": []}
> 
> After: {"browserPackages": ["com.android.chrome"], "defaultBrowserPackage": "com.android.chrome", "preferredBrowserPackage": "com.android.chrome", "servicePackages": ["com.android.chrome"]}
> 
> it was required in Android 11 (API level 30) or higher.
> 
> ![Screen Shot 2022-03-01 at 10 42 55](https://user-images.githubusercontent.com/33874563/156180476-bf82b6a0-24f3-463f-854a-2fb6bc815bfb.png)

I have tested this but this solution is not working (I tested it for Android Version 12)

**Comment by giautm** [comment] 2022-03-23 08:31
Hey @abhishek18feb, can you try this code?
```
let browserPackage: string | undefined;
if (Platform.OS === "android") {
  const tabsSupportingBrowsers = await WebBrowser.getCustomTabsSupportingBrowsersAsync();
  browserPackage = tabsSupportingBrowsers?.preferredBrowserPackage;
}
await WebBrowser.openBrowserAsync(link, { browserPackage });
```

**Comment by abhishek18feb** [comment] 2022-03-23 09:06
> Hey @abhishek18feb, can you try this code?
> 
> ```ts
> let browserPackage: string | undefined;
> if (Platform.OS === "android") {
>   const tabsSupportingBrowsers = await WebBrowser.getCustomTabsSupportingBrowsersAsync();
>   browserPackage = tabsSupportingBrowsers?.preferredBrowserPackage;
> }
> await WebBrowser.openBrowserAsync(link, { browserPackage });
> ```

Hey @giautm , Getting this output for tabsSupportingBrowsers
{ defaultBrowserPackage: null,
      servicePackages: [ 'com.android.chrome' ],
      browserPackages: [],
      preferredBrowserPackage: null }

**Comment by giautm** [comment] 2022-03-23 09:13
You can pick the first element of browserPackages to use.

**Comment by pavelbabenko** [comment] 2022-07-26 12:28
Had the same issue with Android 11

**Comment by RocketRonz** [comment] 2022-10-19 15:06
I've noticed this error on newer versions of Android when attempting to open a URL with no protocol. Prefixing with https:// when missing fixed it for me.

**Comment by dingyonglaw** [comment] 2023-01-10 11:55
I have tested changing default browser from Chrome to something else, then it stopped working. 
Switch it back to Chrome, then it works.

As an interim solution, we ask our user switch their default browser to Chrome:
https://support.google.com/chrome/answer/95417

**Closed** 2023-02-22 22:56 UTC
Labels: needs review, incomplete issue: missing or invalid repro

**Comment by lbecker34** [comment] 2023-10-24 15:46
I had this happen to me. It was because on the discovery document didn't have a complete url for all of the different authorization urls. In the Expo docs, they have you resolve the "discoveryDocument" in a memo without paying attention to any state variables. So, if your url is resolved via a state variable then you need to watch it on useMemo.

```typescript

const discoveryDocument = React. useMemo(() => {
// userPoolUrl was empty on first load of the component, making the endpoints below invalid urls.
const userPoolUrl = settings.auth;
return ({
authorizationEndpoint: userPoolUrl + '/oauth2/authorize',
tokenEndpoint: userPoolUrl + '/oauth2/token',
revocationEndpoint: userPoolUrl + '/oauth2/revoke',
}, [settings]); // make sure you watch the state variable where your url goes to.
})
```

**Comment by raldred** [comment] 2024-04-22 15:28
We have a reoccurring issue with this on Samsung A54 devices.

**Comment by JClackett** [comment] 2024-05-03 12:47
Getting this a lot still only on android

**Comment by fantasyado** [comment] 2024-07-15 03:25
Still get this error from Sentry :
<img width="862" alt="image" src="https://github.com/user-attachments/assets/eda557a1-78c1-4fe3-b248-c5e0566b5d69">

**Comment by asleepace** [comment] 2024-07-25 04:35
Seeing a lot of these issues as well on newer Android devices

**Comment by tlmader** [comment] 2024-07-29 17:15
Getting this error on my Samsung Galaxy S22, running Android 13, **but only when Chrome is the default browser**. I changed my browser to Firefox and was able to open the browser from the app.

I had a user experiencing the same error (verified via Sentry), and the workaround to change the default browser allowed them to continue.

**Comment by MoeKanan** [comment] 2024-07-29 18:53
@brentvatne is it possible to re-open this issue, please? it's still happening on Android devices
