### ISSUE TITLE
abi27_0_0.com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String error when importing pre populated sqlite3 db into my app.

### ISSUE THREAD

**Issue by sunilkumarc** [expo/expo#1913] opened 2018-06-23 13:00 UTC
I'm facing the above error when trying to import a prepopulated db into my app. Here is the information about my app.

1. First I created a database using sqlite3 command line tool:
`sqlite3 myDB.db`

2. Created a table and inserted some data into this table.

3. Now I have a file called myDB.db inside www folder at the root of my app directory. 
![screen shot 2018-06-23 at 6 23 46 pm](https://user-images.githubusercontent.com/3911000/41809884-90b1a73e-7712-11e8-9f8f-0190f9145812.png)

4. After the above steps, I'm trying to access this db inside my FactsCardsPage.js using below code.
![screen shot 2018-06-23 at 6 26 43 pm](https://user-images.githubusercontent.com/3911000/41809911-e524e93e-7712-11e8-8173-18ac15462b83.png)

5. But I'm getting below error when trying to run the app. Any help is appreciated!
![screen shot 2018-06-23 at 6 27 22 pm](https://user-images.githubusercontent.com/3911000/41809940-5afcc8ca-7713-11e8-9c45-62615ce4da4b.png)

**Comment by esamelson** [comment] 2018-06-25 18:16
Hi @sunilkumarc - could you post a reproducible example (maybe a [snack](https://snack.expo.io/) to help us narrow down this issue? It's hard to tell what's going on without being able to repro the issue ourselves. Thanks!

**Comment by sjchmiela** [comment] 2018-07-02 10:19
Duplicate of https://github.com/expo/expo/issues/1903#issuecomment-399676866

**Closed by sjchmiela** 2018-07-02 10:19 UTC
Labels: status: needs more info
