### ISSUE TITLE
Generating new SplashScreen for Android with yarn expo-splash-screen fails with "Cannot convert ExpectedElement to Element when deletionFlag is set"

### ISSUE THREAD

**Issue by andordavoti** [expo/expo#15527] opened 2021-12-13 12:12 UTC
### Summary

Trying to generate SplashScreens for the app for Android with "yarn expo-splash-screen --image-path PATH_TO_PNG --status-bar-style light-content --image-resize-mode cover --background-color #25186" works fine for iOS but fails with "Cannot convert ExpectedElement to Element when deletionFlag is set" for Android.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.21.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

### Reproducible demo

Running "yarn expo-splash-screen --image-path PATH_TO_PNG --status-bar-style light-content --image-resize-mode cover --background-color #25186" in a bare project should make you able to reproduce the issue.

**Comment by brentvatne** [comment] 2021-12-13 19:19
duplicate of https://github.com/expo/expo/issues/13547

**Closed by brentvatne** 2021-12-13 19:19 UTC
Labels: needs review
