### ISSUE TITLE
Splash Screen image doesn't render

### ISSUE THREAD

**Issue by leonardolombardi07** [expo/expo#11590] opened 2021-01-10 19:09 UTC
### Summary of Issue
- Can't make Splash Screen image appear in SDK 40. It happens in all my projects updated to SDK 40 and to new projects created with expo init

### Environment
expo diagnostics output:
  Expo CLI 3.21.13 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2        
      react-native-web: ~0.11.7 => 0.11.7

Using Expo with a Xiaomi Redmi Note 7 smartphone

### Reproducible Demo
- It doesn’t make sense to create a snack, as they don’t render a splash screen
- Expo blank template project: https://github.com/leonardolombardi07/splash-screen-problem
- Published project (to check if the problem was restricted to development enviroment):  https://expo.io/@fluxoconsultoria/projects/outro

### Steps to Reproduce
1) Use expo-cli to create a new project with expo init __name_of_project
2) Change expo.splash.backgroundColor in app.json to see that changing the background color affects the splash screen, but the image in path ./assets/splash.png doesn't render in any case

### Expected Behavior vs Actual Behavior
Expected: render the splash.png image with the splash screen
Actual: splash screen renders, but without the image

### Extra information
This is happening to all my projects upgraded to SDK 40. As I use expo-app-loading in all of them, at first I though it was a problem related to the package (also taking into account changes made in this update). So I tried to migrate to expo-splash-screen, but the problem persisted.
Sorry to open an issue about this, I hope this is not something I'm doing wrong. Just to be clear, expo is amazing!!

**Comment by Meinl** [comment] 2021-01-11 16:03
I'm having same issue. After upgrading from SDK 39 to SDK 40 updated to expo-cli v4.x.x. works fine when I launch my app through expo app, but the issue still in production as standalone app, and appear Expo logo instead my custom splash screen.
![Screenshot_20210111-113728](https://user-images.githubusercontent.com/8104557/104205644-645c2300-540d-11eb-99ce-200b3782cf5e.png)

**Comment by Meinl** [comment] 2021-01-14 14:17
Any news? I'm worried with this, I have a live app with this issue. Thanks

**Comment by brentvatne** [comment] 2021-01-17 02:09
@Meinl - this is not reproducible given the project that you provided. please provide your exact splash screen image you are trying to use and your exact app.json configuration.

**Comment by Meinl** [comment] 2021-01-18 13:00
Hi, thanks for you answer. I have another standalone apps with same config but it has not been a problem. The image I'm using have this properties:

<img width="265" alt="Captura de Pantalla 2021-01-18 a la(s) 09 53 33" src="https://user-images.githubusercontent.com/8104557/104918143-17c79900-5973-11eb-9fd1-ad6b34f22386.png">

Also, the app.json:

<img width="300" alt="Captura de Pantalla 2021-01-18 a la(s) 09 54 38" src="https://user-images.githubusercontent.com/8104557/104918225-36c62b00-5973-11eb-8a7d-8dc54a009b16.png">

And file structure:

<img width="242" alt="Captura de Pantalla 2021-01-18 a la(s) 09 55 16" src="https://user-images.githubusercontent.com/8104557/104918307-51000900-5973-11eb-97c4-f1fa103ecd8d.png">

This was an upgrade from SDK 38 yo SDK 40 with `expo upgrade`

**Comment by Meinl** [comment] 2021-01-20 12:53
I make another build, with any single change and works well. I've no idea what could have happened. Thanks anyway for your time.

**Comment by joaops95** [comment] 2021-01-22 09:13
Hey guys, i'm struggling a lot with this... After building several times aab or apk, the app always loads with that creepy Expo splash screen, I would like to remove the image but seems like an impossible task, I also tried so many different configurations in the app.json and app.config.js.

**Comment by dducro** [comment] 2021-01-25 12:58
We also have a build in production with this issue after the upgrade to SDK 40. If I build the app on my machine the issue persists, when the same project is build on an other system the correct splash screen is shown. My guess would be it has something to do with building the js locally and not with the process on Expo's servers. Hope a fix for this is found soon!

**Comment by mobeendev** [comment] 2021-02-07 12:08
Experiencing the same issue on SDK 40.

**Comment by Gogn** [comment] 2021-02-10 15:10
Same here.

Step to reproduse:
1) expo init test
1.1) Chose Managed: tabs (typescript)
2) "backgroundColor" work fine but splash screen not showing.

**Comment by dducro** [comment] 2021-02-10 15:30
This fixed it for me: update the `expo-cli` -> `build:android` APK

**Comment by Gogn** [comment] 2021-02-11 06:12
I use standard favicon as example "image":
"splash": {
      "image": "./assets/images/favicon.png",
      "resizeMode": "contain",
      "backgroundColor": "#0079C2"
    },
and that what I got:
![Screenshot_20210211_101109](https://user-images.githubusercontent.com/1881637/107607084-a0bfb080-6c51-11eb-8069-010087b57e0d.png)

**Comment by Gogn** [comment] 2021-02-15 06:00
Any news?

**Comment by Gogn** [comment] 2021-02-17 06:44
As workaround I resize image and put it into a big canvas. But it reduce image qualty.

**Comment by vivek-bluebash** [comment] 2021-02-23 06:17
The same issue persists with me since me being using `expo-app-loading` and shifting to `expo-fonts`.

**Comment by vivek-bluebash** [comment] 2021-02-23 06:20
Expo diagnostics in my case:

> Expo CLI 3.26.2 environment info:
>     System:
>       OS: macOS 10.15.6
>       Shell: 3.2.57 - /bin/sh
>     Binaries:
>       Node: 12.18.3 - /usr/local/bin/node
>       Yarn: 1.22.10 - /usr/local/bin/yarn
>       npm: 7.0.15 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     IDEs:
>       Android Studio: 4.0 AI-193.6911.18.40.6626763
>       Xcode: /undefined - /usr/bin/xcodebuild
>     npmPackages:
>       expo: ~40.0.0 => 40.0.0 
>       react: 16.13.1 => 16.13.1 
>       react-dom: 16.13.1 => 16.13.1 
>       react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
>       react-native-web: ~0.13.12 => 0.13.18 
>     npmGlobalPackages:
>       expo-cli: 3.26.2
>

**Comment by mobeendev** [comment] 2021-02-23 10:11
Any fixes?

**Comment by brentvatne** [comment] 2021-02-23 21:03
@mobeendev - share a project that i can clone and run that reproduces this issue. nobody has been able to do this so far so we can't help

**Comment by vivek-bluebash** [comment] 2021-02-24 05:29
Thanks @brentvatne, updating expo-cli helped me solve the issue.

**Comment by brentvatne** [comment] 2021-02-24 23:29
i'll close and reopen if someone can provide a reproducible example. please remember to keep your expo-cli up to date (`npm i -g expo-cli`) and have a great day!

**Closed by brentvatne** 2021-02-24 23:29 UTC
Labels: Android, SplashScreen, needs more info

**Comment by mobeendev** [comment] 2021-03-02 20:10
@brentvatne I created the project with lattest version of Expo and my cli is old, maybe its due to that.
However when used the older version i.e 37, it is working.

**Comment by Gogn** [comment] 2021-03-04 11:23
I checked original icon ("./assets/images/splash.png") and it's a small logo in a bigger canvas (1284x2778).
I scaled my image and canvas like original and after that it's looks Ok.

**Comment by RRajnishR** [comment] 2021-07-11 14:58
Hey Guys,
This problem seems to still persist. I have replaced the splash and other icons with the custom files. but other thab background color, Icon stays unchanged. I have updated my expo-cli and tried clearing npm cache.

Was anyone able to fix this?

**Comment by bleszerd** [comment] 2021-11-19 13:29
The solution for me was to rename the files.
"splashh.png" works, but "./assets/splash.png" always displays the default splash screen

**Comment by code-reaper08** [comment] 2021-11-27 19:07
> The solution for me was to rename the files. "splashh.png" works, but "splash.png" always displays the default splash screen

Thanks @bleszerd 🤠 
It works now!

**Comment by isimmons** [comment] 2021-12-14 20:49
Same here. Renamed my splash file and changed it in app.json and it works.

 I thought it was the old splash.png being cached somewhere so I tried adding the --clear command to my npm start in package.json. This cleared the cache and rebuilt it but the expo splash screen still came up even while cache was building. 

I even renamed and deleted the old splash.png image but it still shows up if I use the name splash.

Was running expo --version 5.0.0 and updated to 5.0.1 with no change.

**Comment by drpiou** [comment] 2022-01-14 08:58
For anyone who struggle with this, and if you are on a bare workflow, then you have to do this instead:
https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-installation-in-bare-react-native-projects

This comes from the Expo documentation, it was just in the middle of the page (because managed and bare workflow are not correctly separated in the documentation in my opinion):
https://docs.expo.dev/guides/splash-screens/#bare-workflow-apps

**Comment by hashiguchip** [comment] 2022-02-14 05:17
I solved it by raising the version of node.js
12.x  -> 16.x

**Comment by Enzo-21** [comment] 2022-02-25 04:00
Hey guys, did you realize that the file expo provides within de /assets folder is actually the image that looks like there's no image?
![Captura de Pantalla 2022-02-25 a la(s) 00 59 51](https://user-images.githubusercontent.com/47162956/155651157-9d114198-9749-45ce-9a0c-938825363e1b.png)
![Captura de Pantalla 2022-02-25 a la(s) 00 59 57](https://user-images.githubusercontent.com/47162956/155651163-65fefa65-2242-4df8-9180-feb698c85b8d.png)

**Comment by Enzo-21** [comment] 2022-02-25 04:05
Hey guys! Did you realize that the file expo provides inside the /assets folder is actually an image trying to look like there's no image? Just change that image for another one, use photoshop or any othe
![Captura de Pantalla 2022-02-25 a la(s) 01 05 36](https://user-images.githubusercontent.com/47162956/155651681-53076cde-6215-4671-93d6-b42a577e4bda.png)
r editing software to edit the exact file. It worked for me.
![Captura de Pantalla 2022-02-25 a la(s) 01 05 40](https://user-images.githubusercontent.com/47162956/155651692-8ffd33a2-474e-4dfa-a496-ea70b786484c.png)

**Comment by dev-wyatt** [comment] 2023-07-19 16:39
I'm new to expo but running `expo prebuild` solved my issue

**Comment by JCYDigitalinnov** [comment] 2024-02-15 12:42
> I'm new to expo but running `expo prebuild` solved my issue

If issue is still persists

Delete the `.expo` folder then run `expo prebuild --clean`

**Comment by manujgogoi** [comment] 2024-07-12 10:57
`npx expo prebuild --clean` has solved the problem for me.

**Comment by AhmedAbuelenin** [comment] 2024-10-29 12:36
For me i forgot to add app.json config into my app.config.ts then i tried the previous solutions 

```
import {ConfigContext, ExpoConfig} from 'expo/config';
import 'ts-node/register';

export default ({config}: ConfigContext): ExpoConfig => ({
  ...config,
  name: 'my-app',
  slug: 'my-app',
});
```

**Comment by aakashv6433** [comment] 2025-02-18 09:05
> `npx expo prebuild --clean` has solved the problem for me.

even after running this and creating a new build I still see a broken splash icon even though the image seems to have been updated inside the drawable directory within the android folder.
