### ISSUE TITLE
App crashes when importing large JSON file (~6mb)

### ISSUE THREAD

**Issue by aikewoody** [expo/expo#18365] opened 2022-07-25 14:49 UTC
### Summary

Production builds built with EAS crash instantly when opened on iOS (only tested on iPhone 13 mini & iPhone 13 Pro so far). This is a recent bug/problem in our codebase that didn't happen a few weeks ago.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45.0.6

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 5.5.1
    Expo Workflow: managed

### Reproducible demo

I have stripped down 99% of the code in our project (but left behind all the dependencies and configuration files we use):
https://github.com/beerinabox/my-beer-minimal-example-react-native

The crash on iOS devices that keeps happening on startup is the following:
<img width="1538" alt="Screenshot 2022-07-25 at 16 47 53" src="https://user-images.githubusercontent.com/17004429/180805602-3fb99a19-9fd1-4cdd-bb30-8113a39a36ca.png">

**Comment by douglowder** [comment] 2022-07-29 20:49
Hello @aikewoody , I pulled your example repo, and set it up with my own EAS account to do a build for internal distribution (see the "preview" section):

```json
{
  "cli": {
    "version": ">= 0.54.1"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "channel": "preview",
      "distribution": "internal"
    },
    "production": {
      "cache": {
        "key": "2022-07-25 15:28:00"
      },
      "channel": "production"
    }
  },
  "submit": {
    "production": {}
  }
}

```

It runs fine on the device without crashing.

**Comment by aikewoody** [comment] 2022-08-01 16:44
@douglowder Thanks for testing the reproducible demo!

I investigated further and found the issue, it's caused by a "large" json file we have in our production environment that's bundled with the js code. The file is `5.8MB` in size and is only 2 levels deep (it's a large array of objects).

Are you okay with me adding you to our private Github repo so you're able to reproduce the issue?

**Comment by douglowder** [comment] 2022-08-01 16:57
Yes I'd be fine to test the private repo! 👍

**Comment by aikewoody** [comment] 2022-08-02 08:19
@douglowder The manager (who can add people to our private repo) is on vacation so I decided to go ahead with the public repo that I linked to in the first comment. A new commit is pushed that contains the big json files (there is ugly code right now but it's purely intended for debugging 🙃)

**Comment by aikewoody** [comment] 2022-08-02 11:50
@douglowder The issue can be bypassed by using the `expo-asset` and `expo-file-system` libraries:
```
const assetResult = await Asset.loadAsync(require('~/assets/data/beers-production.txt'));
const rawText = await FileSystem.readAsStringAsync(assetResult[0].localUri || '');
const beers = JSON.parse(rawText) as TBeer[];
```

With the above code the "big" json files can be loaded into the memory, while the below code crashes:
```
const beers = require('~/assets/data/beers-production.json') as TBeer[];
```

**Comment by douglowder** [comment] 2022-08-05 18:48
Thanks very much for all the detailed info. I have set up your repo with my own EAS account and reproduced the issue. I'll investigate on this end and see if I can come up with a fix.

**Comment by douglowder** [comment] 2022-08-06 01:24
The fix is to place the `assets` directory at the top level of the project, instead of under the `src` directory.  I also ran `expo doctor` and it updated your version of `expo-updates`.  See this diff:

```diff
diff --git a/app.json b/app.json
index d257cbc..a988dcf 100644
--- a/app.json
+++ b/app.json
@@ -2,7 +2,7 @@
   "expo": {
     "android": {
       "adaptiveIcon": {
-        "foregroundImage": "./src/assets/adaptive-icon.png",
+        "foregroundImage": "./assets/adaptive-icon.png",
         "backgroundColor": "#FFFFFF"
       },
       "package": "dev.douglowderexpo.mybeer",
@@ -15,7 +15,7 @@
     "assetBundlePatterns": [
       "**/*"
     ],
-    "icon": "./src/assets/icon.png",
+    "icon": "./assets/icon.png",
     "ios": {
       "bundleIdentifier": "dev.douglowderexpo.my-beer",
       "buildNumber": "5",
@@ -44,7 +44,7 @@
     "scheme": "mybeer",
     "slug": "my-beer",
     "splash": {
-      "image": "./src/assets/splash.png",
+      "image": "./assets/splash.png",
       "resizeMode": "contain",
       "backgroundColor": "#ffffff"
     },
diff --git a/src/assets/adaptive-icon.png b/assets/adaptive-icon.png
similarity index 100%
rename from src/assets/adaptive-icon.png
rename to assets/adaptive-icon.png
diff --git a/src/assets/data/beers-headers.csv b/assets/data/beers-headers.csv
similarity index 100%
rename from src/assets/data/beers-headers.csv
rename to assets/data/beers-headers.csv
diff --git a/src/assets/data/beers-production.csv b/assets/data/beers-production.csv
similarity index 100%
rename from src/assets/data/beers-production.csv
rename to assets/data/beers-production.csv
diff --git a/src/assets/data/beers-production.json b/assets/data/beers-production.json
similarity index 100%
rename from src/assets/data/beers-production.json
rename to assets/data/beers-production.json
diff --git a/src/assets/data/beers-production.txt b/assets/data/beers-production.txt
similarity index 100%
rename from src/assets/data/beers-production.txt
rename to assets/data/beers-production.txt
diff --git a/src/assets/data/beerstyles-headers.csv b/assets/data/beerstyles-headers.csv
similarity index 100%
rename from src/assets/data/beerstyles-headers.csv
rename to assets/data/beerstyles-headers.csv
diff --git a/src/assets/data/beerstyles-production.csv b/assets/data/beerstyles-production.csv
similarity index 100%
rename from src/assets/data/beerstyles-production.csv
rename to assets/data/beerstyles-production.csv
diff --git a/src/assets/data/beerstyles-production.json b/assets/data/beerstyles-production.json
similarity index 100%
rename from src/assets/data/beerstyles-production.json
rename to assets/data/beerstyles-production.json
diff --git a/src/assets/data/beerstyles-production.txt b/assets/data/beerstyles-production.txt
similarity index 100%
rename from src/assets/data/beerstyles-production.txt
rename to assets/data/beerstyles-production.txt
diff --git a/src/assets/data/breweries-headers.csv b/assets/data/breweries-headers.csv
similarity index 100%
rename from src/assets/data/breweries-headers.csv
rename to assets/data/breweries-headers.csv
diff --git a/src/assets/data/breweries-production.csv b/assets/data/breweries-production.csv
similarity index 100%
rename from src/assets/data/breweries-production.csv
rename to assets/data/breweries-production.csv
diff --git a/src/assets/data/breweries-production.json b/assets/data/breweries-production.json
similarity index 100%
rename from src/assets/data/breweries-production.json
rename to assets/data/breweries-production.json
diff --git a/src/assets/data/breweries-production.txt b/assets/data/breweries-production.txt
similarity index 100%
rename from src/assets/data/breweries-production.txt
rename to assets/data/breweries-production.txt
diff --git a/src/assets/icon.png b/assets/icon.png
similarity index 100%
rename from src/assets/icon.png
rename to assets/icon.png
diff --git a/src/assets/splash.png b/assets/splash.png
similarity index 100%
rename from src/assets/splash.png
rename to assets/splash.png
diff --git a/package.json b/package.json
index 9b6b609..e8ff9c5 100644
--- a/package.json
+++ b/package.json
@@ -42,7 +42,7 @@
     "expo-linear-gradient": "~11.3.0",
     "expo-random": "~12.2.0",
     "expo-splash-screen": "~0.15.1",
-    "expo-updates": "~0.13.3",
+    "expo-updates": "~0.13.4",
     "expo-web-browser": "~10.2.1",
     "firebase": "^9.8.4",
     "react": "17.0.2",
diff --git a/src/App.tsx b/src/App.tsx
index f3b37e0..1df0151 100644
--- a/src/App.tsx
+++ b/src/App.tsx
@@ -28,7 +28,7 @@ export function App() {
         // @note: this crashes
         // const beersDirty = require('~/assets/data/beers-production.json') as TBeer[];
 
-        const beersResult = await Asset.loadAsync(require('~/assets/data/beers-production.txt'));
+        const beersResult = await Asset.loadAsync(require('../assets/data/beers-production.txt'));
         const beersRawText = await FileSystem.readAsStringAsync(beersResult[0].localUri || '');
         const beersDirty = JSON.parse(beersRawText) as TBeer[];
 
@@ -50,7 +50,7 @@ export function App() {
         // @note: this crashes
         // const breweriesDirty = require('~/assets/data/breweries-production.json') as TBrewery[];
 
-        const breweriesResult = await Asset.loadAsync(require('~/assets/data/breweries-production.txt'));
+        const breweriesResult = await Asset.loadAsync(require('../assets/data/breweries-production.txt'));
         const breweriesRawText = await FileSystem.readAsStringAsync(breweriesResult[0].localUri || '');
         const breweriesDirty = JSON.parse(breweriesRawText) as TBrewery[];
 
@@ -79,7 +79,7 @@ export function App() {
         // @note: this crashes
         // const beerstylesDirty = require('~/assets/data/beerstyles-production.json') as TBeerstyle[];
 
-        const beerstylesResult = await Asset.loadAsync(require('~/assets/data/beerstyles-production.txt'));
+        const beerstylesResult = await Asset.loadAsync(require('../assets/data/beerstyles-production.txt'));
         const beerstylesRawText = await FileSystem.readAsStringAsync(beerstylesResult[0].localUri || '');
         const beerstylesDirty = JSON.parse(beerstylesRawText) as TBeerstyle[];
 

```

**Comment by aikewoody** [comment] 2022-08-09 20:59
@douglowder Thanks again for taking the time to look into the issue and our projects code!

To be honest I would like to reopen the ticket (or if you prefer it I can also make a new ticket) as the original issue still exists. We do have found a solution to bypass the problem by using `expo-asset` and `expo-file-system` to "import" large json files but the "normal" way of doing this, by using `require`, still results in the crash: `maximum call stack size exceeded`

I want to suggest the following list of possible actions to fully resolve this issue (ordered from most to least most favourable solution):
1. Find the root cause of why importing large json files results in a crash and fix it (there is a high chance this is caused by something outside of the expo code)
2. Find a way to detect if there is a large json file required (that will result in a crash) and warn the developer about it
3. Write a short explanation about this caveat in the documentation (this is something I can do and would be okay volunteering for 👌)

**Comment by brentvatne** [comment] 2022-08-16 20:25
hey @aikewoody! it looks like the original repository isn't around anymore, would you be able to reshare a reproducible example?

**Comment by aikewoody** [comment] 2022-08-17 07:45
@brentvatne Thank you for re-opening the issue! Yes, I have created a new public repo with bare minimum code:
https://github.com/aikewoody/expo-example-import-large-json-file

**Comment by aikewoody** [comment] 2022-11-15 09:32
I have re-tested this issue with the latest version of Expo `^47.0.0` and it's still happening

**Comment by aleqsio** [comment] 2022-11-15 11:45
I can see this issue on Expo Go SDK 47, but the cause for that should be the underlying Hermes issue:
https://github.com/facebook/hermes/issues/135

**Comment by aikewoody** [comment] 2022-11-15 11:53
@aleqsio That sounds like a very plausible explanation. With this insight I think this issue can be closed now (as the underlying problem is caused by the hermes engine).

Do you see value in adding this insight somewhere to the docs of expo?

**Comment by aleqsio** [comment] 2022-11-15 12:24
Yeah, I don't see this being fixed in any short timeframe seeing as this issue has been up since 2019, so we should perhaps provide a workaround in the docs.

I think the best workaround is using JSON parse on an asset in place of requiring. I've tried disabling `inlineRequires` as one [commenter](https://github.com/facebook/hermes/issues/135#issuecomment-808817771) suggested in the issue without seeing any changes, but that felt like not the best solution anyways.

**Closed** 2022-11-15 12:46 UTC
Labels: Updates, Issue accepted, SDK 45

**Comment by aikewoody** [comment] 2022-11-15 13:12
@aleqsio It is indeed difficult to find a place in the docs for this. The only place I can think of right now would be on the [Asset](https://docs.expo.dev/versions/latest/sdk/asset/) documentation. @brentvatne I'm curious about your thoughts on this

**Comment by chrisdrifte** [comment] 2023-10-09 17:20
I'm facing a similar issue after my ajv schemas js file grew to 16k lines -- it was very difficult to debug the source of the crash. An early reference point for me was https://docs.expo.dev/build-reference/troubleshooting/, and if there had been a note on that page about this possible issue I'd likely have been able to figure it out a bit more quickly.

**Comment by yeefun** [comment] 2024-03-25 14:08
@chrisdrifte 

> I'm facing a similar issue after my ajv schemas js file grew to 16k lines -- it was very difficult to debug the source of the crash. An early reference point for me was [docs.expo.dev/build-reference/troubleshooting](https://docs.expo.dev/build-reference/troubleshooting/), and if there had been a note on that page about this possible issue I'd likely have been able to figure it out a bit more quickly.

How did you know that? Could you explain how you identified the root cause? I'm struggling for it.
