### ISSUE TITLE
AsyncStorage and Permissions.askAsync Android failing

### ISSUE THREAD

**Issue by yasso1am** [expo/expo#2351] opened 2018-10-03 16:19 UTC
I recently had to detach to expo kit because I couldn't find a workaround for these two APIs failing on my Android app. They work 100% as expect for iOS, but crash the app on Android. After detaching I have found it still doesn't work.

### Environment
Environment:
  OS: macOS 10.14
  Node: 8.11.4
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.2 AI-181.5540.7.32.5014246

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

### Steps to Reproduce

After the user is prompted to accept, on iOS,status will return 'granted', but on Android, status will return 'undefined'. I believe I added permissions to READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE properly to my android.permissions in app.json

```
requestPhotoAccess = async () => {
      let { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL)
      this.setState({hasCameraPermission: status })
  }

```

On iOS, the entire function will run, either returning the stored token, and logging the user in, or rejected them. On Android, the function won't run at all. I hit none of my 'catch' blocks, and nothing is resolved.
```
export function checkLocalToken() {
  return new Promise(async (resolve, reject) => {
    try {
      const token = await AsyncStorage.getItem(STORAGE_TOKEN)
      const user_id = await AsyncStorage.getItem(STORAGE_USER_ID)
      if (token && user_id !== null) {
        axios.get(`${BASE_URL}/profile/${user_id}`, { headers: {authorization: `Bearer ${token}`}})
        .then( async (res) => {
          let user = await res.data.data
          await AsyncStorage.setItem(STORAGE_TOKEN, token)
          await AsyncStorage.setItem(STORAGE_USER, JSON.stringify(user))
          await AsyncStorage.setItem(STORAGE_USER_ID, user_id)
          resolve({ token, user })
          })
          .catch( error => {
            console.log("The token must have expired call failed")
            reject(error)
          })
      }
    } catch (err){
      console.log("There is no saved user")
      reject(err)
    }
  });
}

```

### Expected Behavior

I would expect that the same thing on Android would happen that happens on my iOS app. I would have access to the storage on the device to save their token, and retrive it upon opening the app again in the future. Same goes for accessing the Camera roll. 

### Actual Behavior

For the user check, it seems to work the first or second time I open the app on the emulator or a real device, but then consecutive checks has the entire function failing and the app seems to hang on the log in screen, not allowing me to sign the user in and store the token, and never allowing me to take them to the next page, because storing the token is a critical step in the log in process. The only way I can reset this is by wiping the device, rebuilding the app and starting over - which buys me two more app boots before I run into issues again. Additionally for the Camera Roll, the entire app crashes.

-->

**Comment by bbarthec** [comment] 2018-10-05 17:57
Hello @yasso1am! I've created [snack](https://snack.expo.io/@barthec/tactless-tea) that is a minimal example of your problems.
Regarding issues:
* I couldn't reproduce scenario of yours.
* `AsyncStorage` is `react-native` module, so nothing from us can be done here (if anything wrong at all), but I believe you had some wrong logic flow:
```javascript
export function checkLocalToken() {
  return new Promise(async (resolve, reject) => {
    try {
      ...some important things...
      if (token && user_id !== null) {
        ...logic goes on... 
      }
      // what happens here?
      // Nothing! Promise is neither resolved nor rejected.
      // SPOTTED hanging logic!
    } catch (err) {
      ...something...
    }
  });
}
```
* `Permissions` work as a charm as well.

Please check [provided snack](https://snack.expo.io/@barthec/tactless-tea), especially hitting `Permissions` module matter. Please ensure you're having up-to-date client app from `Google Play Store` and your environment is also mostly up-to-date.

I'm closing this issue tentatively. Feel free to reopen if any problem is still occurring.

**Closed by bbarthec** 2018-10-05 17:57 UTC
