### ISSUE TITLE
Push notifications suddenly stopped shipping, receiptIds exist with 'ok' but are empty when retrieved

### ISSUE THREAD

**Issue by iuliuvisovan** [expo/expo#21862] opened 2023-03-27 14:49 UTC
### Minimal reproducible example

https://snack.expo.dev/@anthemis/bug-notification

### Summary

**Minimal Reproducible Example:** 
https://expo.dev/notifications (Use token: `ExponentPushToken[H7MgrvHafvWJteRiUOd0DQ]`  - Results in 200 in console but nothing is shipped)

**I'm using this standard code to send push notifications:**

```
export async function sendNotificationToTokens(pushTokens: string[], pnToSend: PushNotificatonBody) {
  const expo = new Expo()

  const messages: any = []
  for (const pushToken of pushTokens) {
    if (!Expo.isExpoPushToken(pushToken)) {
      continue
    }

    messages.push({
      to: pushToken,
      sound: 'default',
      body: pnToSend.title,
      data: pnToSend.data,
    })
  }

  console.log('Sending messages', messages);

  const chunks = expo.chunkPushNotifications(messages)
  const tickets: any[] = []
  for (const chunk of chunks) {
    try {
      const ticketChunk = await expo.sendPushNotificationsAsync(chunk)
      console.log('ticketChunk', ticketChunk)
      tickets.push(...ticketChunk)
    } catch (error) {
      logError(error, 'Error sending push notification')
    }
  }

  const receiptIds: any[] = []
  for (const ticket of tickets) {
    if (ticket.id) {
      receiptIds.push(ticket.id)
    }
  }

  console.log('receiptIds', receiptIds)

  const receiptIdChunks = expo.chunkPushNotificationReceiptIds(receiptIds)
  for (const chunk of receiptIdChunks) {
    try {
      const receipts = await expo.getPushNotificationReceiptsAsync(chunk)
      console.log('receipts', receipts)

      for (const receiptId in receipts) {
        const { status, message, details } = receipts[receiptId] as any
        if (status === 'ok') {
          continue
        } else if (status === 'error') {
          logError(message, 'getPushNotificationReceiptsAsync error')

          if (details && details.error) {
            logError(details.error, 'getPushNotificationReceiptsAsync error')
          }
        }
      }
    } catch (error) {
      logError(error, 'getPushNotificationReceiptsAsync error')
    }
  }
}
```

We are succesfully set up and live (standalone apps both Android and iOS), push notifications worked as expected for a good few weeks on both platforms. Now suddenly during normal testing (but not [600 PNs/s](https://docs.expo.dev/push-notifications/faq/#limit-of-sending-notifications), more like 20-30 per minute) they stopped shipping at all - on both Android and iOS.

Testing with the (Push Notifications Tool)[https://expo.dev/notifications] (e.g. token: `ExponentPushToken[H7MgrvHafvWJteRiUOd0DQ`]) it shows no error (and Network Inspect endpoint returns 200).

These are some receiptIds that were returned with { status: 'ok' }:

```
ticketChunk [
  { status: 'ok', id: '4459f4f8-5b05-4bcf-9150-38cf4544e7a3' },
  { status: 'ok', id: '98f7fd41-d0c7-4b62-b2a2-1436b38860e2' }
]
```

Trying to fetch them via command line also gives empty object (with probably 200 response).

![image](https://user-images.githubusercontent.com/11357552/227961920-6411fe8b-afcc-441c-bb95-447ddda0b3ee.png)

Any help?

Context 1: We were sending (or attempting to) an abnormal amount of notifications to invalid tokens (to devices which have had the app uninstalled in the meantime) - but this was only for Android (even then would need to know this) - and then it also wouldn't explain why iOS stopped receiving them as well.

Context 2: Both iOS & Android have stopped receiving anything.

Context 3: We are using 2 different standalone apps (one with normal package name, and one with ".staging" prefix - both stopped receiving anything).

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 12.6.2
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 18.11.0 - /opt/homebrew/bin/node
Yarn: 1.22.19 - ~/.yarn/bin/yarn
npm: 9.6.2 - /opt/homebrew/bin/npm
Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
SDKs:
iOS SDK:
Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
IDEs:
Android Studio: 2021.1 AI-211.7628.21.2111.8309675
Xcode: 14.2/14C18 - /usr/bin/xcodebuild
npmGlobalPackages:
eas-cli: 3.8.1
expo-cli: 6.1.0

**Comment by Swampi995** [comment] 2023-03-27 14:55
we have the same issue, suddenly it stopped working even though we didn't modify anything

**Comment by brg8** [comment] 2023-03-27 16:52
The expo status page says a fix has been implemented, but I haven't been able to deliver a push yet. Has anyone else seen an improvement?

**Comment by avisionx** [comment] 2023-03-27 17:57
Same issue, has the root cause for the same been detected?

**Comment by Kudo** [comment] 2023-03-28 03:57
hi there! it may take some time to consume the processing queue after mitigating the server error. could someone help to double check whether the problem still exists?

**Comment by avisionx** [comment] 2023-03-28 08:06
@Kudo I just checked the issue has been mitigated for me getting realtime notifs now. Thanks team on working on the same at priority!

**Comment by himrocks33** [comment] 2023-03-28 12:21
@Kudo I can confirm as well that the issue has been mitigated for our app as well.

**Comment by Kudo** [comment] 2023-03-28 15:17
thanks @avisionx @himrocks33 for the kindly confirmation. i'm closing this issue. feel free to let us know if there's any problem.

**Closed by Kudo** 2023-03-28 15:17 UTC
Labels: needs review

**Comment by kovacsni76574** [comment] 2023-07-31 14:47
Hello, I somehow have a similar issue. On my app the data Objekt is empty when logging the response from 'https://exp.host/--/api/v2/push/getReceipts'. A few weeks ago everything worked fine... has someone also had issues with the notifications?
