### ISSUE TITLE
expo-splash-screen 0.20.5 android dev build fails

### ISSUE THREAD

**Issue by reft** [expo/expo#23801] opened 2023-08-02 10:11 UTC
### Summary

Installing the latest expo-splash-screen, 0.20.5, gives the following error when running:

> eas build --profile development --platform android --clear-cache

![image](https://github.com/expo/expo/assets/3218213/6a55c58f-a7ce-48e4-8765-e61728858a6c)

![image](https://github.com/expo/expo/assets/3218213/809f31a6-063a-45dc-baad-f5a826aa9482)

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

"expo": "49.0.0",
"expo-dev-client": "~2.4.6",
"expo-splash-screen": "~0.20.5"

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.6.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: 49.0.0 => 49.0.0
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.7
    Expo Workflow: managed

### Reproducible demo

```
import * as logger from '../helpers/logger'
import * as SplashScreen from 'expo-splash-screen'
import useAsyncEffect from 'use-async-effect'

const useSplashScreen = () => {
  const hideSplashScreen = async () => {
    try {
      await SplashScreen.hideAsync()
    } catch (err) {
      logger.error('use splash screen hide error', err)
    }
  }

  useAsyncEffect(async () => {
    try {
      await SplashScreen.preventAutoHideAsync()
    } catch (err) {
      logger.error('use splash screen prevent auto hide error', err)
    }
  }, [])

  return { hideSplashScreen }
}

export default useSplashScreen

```

### Stacktrace (if a crash is involved)

Not full stacktrace (There was an error creating your Issue: body is too long (maximum is 65536 characters).)

> Task :expo-splash-screen:compileDebugKotlin FAILED

[stderr] 

e: file:///home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/SplashScreenReactActivityLifecycleListener.kt:16:3 'onContentChanged' overrides nothing

[stderr] 

FAILURE: Build failed with an exception.

[stderr] 

* What went wrong:

[stderr] 

Execution failed for task ':expo-splash-screen:compileDebugKotlin'.

[stderr] 

> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

[stderr] 

   > Compilation error. See log for more details

[stderr] 

* Try:

[stderr] 

> Run with --stacktrace option to get the stack trace.

[stderr] 

> Run with --info or --debug option to get more log output.

[stderr] 

> Run with --scan to get full insights.

[stderr] 

* Get more help at https://help.gradle.org

[stderr] 

BUILD FAILED in 7m 7s

710 actionable tasks: 710 executed

Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

**Comment by dlbears** [comment] 2023-08-02 10:42
same issue, my temp workaround is to downgrade to 0.20.4

**Comment by mohammadgarmroodi** [comment] 2023-08-02 11:07
+1

**Comment by manamelacedric** [comment] 2023-08-02 15:45
+1

**Comment by igo211** [comment] 2023-08-02 19:44
+1 and can confirm workaround is to downgrade to 0.20.4

**Comment by Alekzv9** [comment] 2023-08-02 19:52
> +1 and can confirm workaround is to downgrade to 0.20.4

I removed expo-splash-screen entirely and still seeing this issue

**Comment by adamhake** [comment] 2023-08-02 20:40
I'm having the same issue on 0.20.5 on production builds: 

```
[stderr] 

FAILURE: Build failed with an exception.

[stderr] 

* What went wrong:

[stderr] 

Execution failed for task ':expo-splash-screen:compileReleaseKotlin'.

[stderr] 

> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
```

Downgrading to 0.20.4 fixed it for me as well.

**Comment by josephine-boyu** [comment] 2023-08-03 03:29
+1
eas-cli version: .3.17.1
 "dependencies": {
    "expo": "^49.0.5",
    "react-native": "0.72.3",
    "expo-splash-screen": "~0.20.4"
} 
I had try to run "npx expo prebuild --clean" and "npm uninstall expo-splash-screen", it works.
But I’m still wondering why it build failed and don't know is there  another problem after I uninstall expo-splash-screen.

**Comment by Pcpkomputer** [comment] 2023-08-03 08:02
+1 same after upgrade

**Comment by burhanyilmaz** [comment] 2023-08-03 11:38
> +1 same after upgrade
> 
> edited :
> 
> For everyone that encounter this problem, I am solved it by this [#23363 (comment)](https://github.com/expo/expo/issues/23363#issuecomment-1656690232)

Your solutions didn't work for me :/

**Comment by konyilwin** [comment] 2023-08-03 13:07
I'm encountering same issue with expo-splash-screen version 0.20.5 when trying to build my Android app in both development and production mode. The build process consistently fails with this version, and I hope it will be resolved soon.

**Comment by aleqsio** [comment] 2023-08-03 14:52
I tried building an app with `"expo-splash-screen": "~0.20.5"` and the build does pass for me, so I can't really fix the issue.

Would someone be able to provide a repository reproduction which fails to build on EAS?

**Comment by aleqsio** [comment] 2023-08-03 15:12
To fix, please update `expo` to latest (49.0.6).

**Comment by burhanyilmaz** [comment] 2023-08-03 15:19
> "expo-splash-screen": "~0.20.5"


Can you try this repo?
There is no issue in development mode. After release update(`eas update`), splash screen is showing as white.
https://github.com/burhanyilmaz/expo-splash-screen-eas-update

**Comment by aleqsio** [comment] 2023-08-03 15:25
@burhanyilmaz Can you still see the issue after bumping expo to "~49.0.6",

**Comment by burhanyilmaz** [comment] 2023-08-03 20:54
> @burhanyilmaz Can you still see the issue after bumping expo to "~49.0.6"? This new version is supposed to fix the white splash screen.

it is not worked. I think the issue is related to building.
There is this message `✔ Uploading assets skipped - no new assets found`

**Comment by burhanyilmaz** [comment] 2023-08-03 21:11
Issue is this
### ✔ Uploading assets skipped - no new assets found
it means this splash screen image is not imported anywhere.

**Comment by manamelacedric** [comment] 2023-08-04 07:37
Upgrading expo to 49.0.6 fixes the issue for me

**Comment by burhanyilmaz** [comment] 2023-08-04 11:30
> Upgrading expo to 49.0.6 fixes the issue for me

can you share this command (`npx expo-env-info `)log? may be related to some environment. after the upgrading, it didn't work

**Comment by manamelacedric** [comment] 2023-08-04 11:32
> > Upgrading expo to 49.0.6 fixes the issue for me
> 
> can you share this command (`npx expo-env-info `)log? may be related to some environment. after the upgrading, it didn't work

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30, 31, 33
        Build Tools: 30.0.3, 33.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ^49.0.6 => 49.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    Expo Workflow: bare

**Comment by burhanyilmaz** [comment] 2023-08-04 11:36
> > > Upgrading expo to 49.0.6 fixes the issue for me
> > 
> > 
> > can you share this command (`npx expo-env-info `)log? may be related to some environment. after the upgrading, it didn't work
> 
> expo-env-info 1.0.5 environment info: System: OS: Windows 10 10.0.22621 Binaries: Node: 18.16.1 - C:\Program Files\nodejs\node.EXE Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD SDKs: Android SDK: API Levels: 29, 30, 31, 33 Build Tools: 30.0.3, 33.0.0 System Images: android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86_64 Atom IDEs: Android Studio: AI-213.7172.25.2113.9123335 npmPackages: expo: ^49.0.6 => 49.0.6 react: 18.2.0 => 18.2.0 react-native: 0.72.3 => 0.72.3 Expo Workflow: bare

Almost same env. 
https://github.com/burhanyilmaz/expo-splash-screen-eas-update
Can you try my repo? Btw development is working well. After eas update, production is not working a well-related splash screen.

**Comment by douglowder** [comment] 2023-08-05 01:18
@burhanyilmaz you should upgrade to 49.0.6 this way:

```
yarn add expo@49.0.6
npx expo install --fix
```

The second command ensures that you have the right versions of other expo modules. For the splash screen to work, you should have

```
expo@49.0.6
expo-splash-screen@0.20.5
expo-modules-core@1.5.9
expo-updates@0.18.11
```

Please let us know if the above fixes your issue.

**Comment by burhanyilmaz** [comment] 2023-08-05 06:43
> @burhanyilmaz you should upgrade to 49.0.6 this way:
> 
> ```
> yarn add expo@49.0.6
> npx expo install --fix
> ```
> 
> The second command ensures that you have the right versions of other expo modules. For the splash screen to work, you should have
> 
> ```
> expo@49.0.6
> expo-splash-screen@0.20.5
> expo-modules-core@1.5.9
> expo-updates@0.18.11
> ```
> 
> Please let us know if the above fixes your issue.

Thank you for your solution. But it didn't work. My package.json
```
{
  "name": "splash-screen-bug",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "49.0.6",
    "expo-modules-core": "1.5.9",
    "expo-splash-screen": "0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-updates": "0.18.11",
    "react": "18.2.0",
    "react-native": "0.72.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "typescript": "^5.1.3"
  },
  "private": true
}

```

my log
`✔ Uploading assets skipped - no new assets found` expo didn't see the my assets.

```
[expo-cli] Starting Metro Bundler
[expo-cli] 
[expo-cli] warning: Watchman `watch-project` returned a warning: Recrawled this watch 21 times, most recently because:
[expo-cli] MustScanSubDirs UserDroppedTo resolve, please review the information on
[expo-cli] https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
[expo-cli] To clear this warning, run:
[expo-cli] `watchman watch-del '/Users/burhanyilmaz/girisim/test/splash-screen-bug' ; watchman watch-project '/Users/burhanyilmaz/girisim/test/splash-screen-bug'`
[expo-cli] warning: Watchman `query` returned a warning: Recrawled this watch 21 times, most recently because:
[expo-cli] MustScanSubDirs UserDroppedTo resolve, please review the information on
[expo-cli] https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
[expo-cli] To clear this warning, run:
[expo-cli] `watchman watch-del '/Users/burhanyilmaz/girisim/test/splash-screen-bug' ; watchman watch-project '/Users/burhanyilmaz/girisim/test/splash-screen-bug'`
[expo-cli] 
[expo-cli] iOS Bundling complete 4267ms
[expo-cli] Android Bundling complete 4268ms
[expo-cli] iOS Building Hermes bytecode for the bundle
[expo-cli] Android Building Hermes bytecode for the bundle
[expo-cli] 
[expo-cli] 
[expo-cli] Bundle                      Size
[expo-cli] ┌ index.ios.hbc           848 kB
[expo-cli] ├ index.android.hbc       854 kB
[expo-cli] ├ index.ios.hbc.map      3.44 MB
[expo-cli] └ index.android.hbc.map  3.46 MB
[expo-cli] 
[expo-cli] 💡 JavaScript bundle sizes affect startup time. Learn more: https://expo.fyi/javascript-bundle-sizes
[expo-cli] Finished saving JS Bundles
[expo-cli] Dumping asset map
[expo-cli] Dumping source maps
[expo-cli] Preparing additional debugging files
[expo-cli] Export was successful. Your exported files can be found in dist
✔ Exported bundle(s)
✔ Uploaded 2 app bundles
✔ Uploading assets skipped - no new assets found
✔ Channel: main pointed at branch: main
✔ Published!
```

**Comment by reft** [comment] 2023-08-05 09:13
Just upgraded to 49.0.6 and it works for both internal and production builds, thanks!

**Comment by marcus-chr** [comment] 2023-08-07 09:03
I'm using the following packages:
```
"expo-splash-screen": "0.20.5",
"expo": "49.0.6",
```
But still getting the error:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':expo-splash-screen:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
```
Seems like this was fixed for many others though. Anyone else experiencing issues after running `npx expo install --fix`?

**Comment by marcus-chr** [comment] 2023-08-07 11:28
> > I'm using the following packages:
> > ```
> > "expo-splash-screen": "0.20.5",
> > "expo": "49.0.6",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But still getting the error:
> > ```
> > FAILURE: Build failed with an exception.
> > * What went wrong:
> > Execution failed for task ':expo-splash-screen:compileReleaseKotlin'.
> > > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Seems like this was fixed for many others though. Anyone else experiencing issues after running `npx expo install --fix`?
> 
> Are you sure you upgraded as instructed?
> 
> npm i -g eas-cli yarn add expo@^49.0.6 npx expo install --fix npx expo-doctor@latest
> 
> You could also try to regenerate your .lock file if you're using yarn.

Yes, I did all of that and getting same error.

**Comment by brentvatne** [comment] 2023-08-07 20:36
@marcus-chr - please share a minimal reproducible example

**Comment by Juliyaone** [comment] 2023-08-09 19:45
{
  "name": "horynize",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-community/datetimepicker": "7.2.0",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-community/slider": "4.4.2",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/stack": "^6.3.17",
    "@reduxjs/toolkit": "^1.9.5",
    "@types/react": "~18.2.14",
    "expo": "^49.0.6",
    "expo-linear-gradient": "~12.3.0",
    "expo-network": "~5.4.0",
    "expo-splash-screen": "~0.20.4",
    "expo-status-bar": "~1.6.0",
    "expo-updates": "~0.18.11",
    "formik": "^2.4.3",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-radial-slider": "^1.0.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-svg": "13.9.0",
    "react-native-svg-transformer": "^1.1.0",
    "react-redux": "^8.1.2",
    "typescript": "^5.1.3",
    "yup": "^1.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

**Comment by marcus-chr** [comment] 2023-08-10 08:18
> @marcus-chr - please share a minimal reproducible example

Sorry for late reply. Everything works fine now!

The mistake was on my side, I still had the following code in `package.json` which now is removed:
```
"resolutions": {
  "expo-modules-core": "1.5.5"
},
```

**Comment by brentvatne** [comment] 2023-08-11 18:29
closing this because the solution is to update the `expo` package to `^49.0.6`

**Closed by brentvatne** 2023-08-11 18:29 UTC
Labels: Issue accepted, Development Builds, needs review
