### ISSUE TITLE
Duplicate symbol error after link react-native-webview

### ISSUE THREAD

**Issue by potatoMa** [expo/expo#5914] opened 2019-10-09 02:10 UTC
Hello guys, I got a trouble after adding react-native-webview to my project(my project is bare apps) with these command line :
```
expo install react-native-webview
react-native link react-native-webview
```
and when I building my ios app, it failed with this error:
```
duplicate symbol '_OBJC_CLASS_$__SwizzleHelperWK' in:
    /Users/Library/Developer/Xcode/DerivedData/gizwits-super-app-rn-buuoxsstdsjnxhbbxpznhjcrobrs/Build/Products/Debug-iphonesimulator/ExpoKit/libExpoKit.a(RNCWKWebView.o)
    /Users/Library/Developer/Xcode/DerivedData/gizwits-super-app-rn-buuoxsstdsjnxhbbxpznhjcrobrs/Build/Products/Debug-iphonesimulator/react-native-webview/libreact-native-webview.a(RNCWebView.o)
duplicate symbol '_OBJC_METACLASS_$__SwizzleHelperWK' in:
    /Users/username/Library/Developer/Xcode/DerivedData/gizwits-super-app-rn-buuoxsstdsjnxhbbxpznhjcrobrs/Build/Products/Debug-iphonesimulator/ExpoKit/libExpoKit.a(RNCWKWebView.o)
    /Users/username/Library/Developer/Xcode/DerivedData/gizwits-super-app-rn-buuoxsstdsjnxhbbxpznhjcrobrs/Build/Products/Debug-iphonesimulator/react-native-webview/libreact-native-webview.a(RNCWebView.o)
duplicate symbol '_OBJC_CLASS_$_RNCWKProcessPoolManager' in:
    /Users/username/Library/Developer/Xcode/DerivedData/gizwits-super-app-rn-buuoxsstdsjnxhbbxpznhjcrobrs/Build/Products/Debug-iphonesimulator/ExpoKit/libExpoKit.a(RNCWKProcessPoolManager.o)
    /Users/username/Library/Developer/Xcode/DerivedData/gizwits-super-app-rn-buuoxsstdsjnxhbbxpznhjcrobrs/Build/Products/Debug-iphonesimulator/react-native-webview/libreact-native-webview.a(RNCWKProcessPoolManager.o)
duplicate symbol '_OBJC_METACLASS_$_RNCWKProcessPoolManager' in:
    /Users/username/Library/Developer/Xcode/DerivedData/gizwits-super-app-rn-buuoxsstdsjnxhbbxpznhjcrobrs/Build/Products/Debug-iphonesimulator/ExpoKit/libExpoKit.a(RNCWKProcessPoolManager.o)
    /Users/username/Library/Developer/Xcode/DerivedData/gizwits-super-app-rn-buuoxsstdsjnxhbbxpznhjcrobrs/Build/Products/Debug-iphonesimulator/react-native-webview/libreact-native-webview.a(RNCWKProcessPoolManager.o)
duplicate symbol '_OBJC_IVAR_$_RNCWKProcessPoolManager._sharedProcessPool' in:
    /Users/username/Library/Developer/Xcode/DerivedData/gizwits-super-app-rn-buuoxsstdsjnxhbbxpznhjcrobrs/Build/Products/Debug-iphonesimulator/ExpoKit/libExpoKit.a(RNCWKProcessPoolManager.o)
    /Users/username/Library/Developer/Xcode/DerivedData/gizwits-super-app-rn-buuoxsstdsjnxhbbxpznhjcrobrs/Build/Products/Debug-iphonesimulator/react-native-webview/libreact-native-webview.a(RNCWKProcessPoolManager.o)
ld: 5 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
It looks like expokit has duplicated symbols with react-native-webview, or did I do something wrong? Thank you for help!
* Xcode version: 11.0
* Expo sdk version: 34.0.1

**Comment by cruzach** [comment] 2019-10-09 17:14
Did you run `pod install`?  Make sure to follow all the instructions on the [`react-native-webview` readme](https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md#react-native-webview-getting-started-guide)

**Comment by potatoMa** [comment] 2019-10-10 01:41
@cruzach Yes I did.

**Comment by potatoMa** [comment] 2019-10-12 02:11
> Did you run `pod install`? Make sure to follow all the instructions on the [`react-native-webview` readme](https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md#react-native-webview-getting-started-guide)

Yes I did, I have followed the instructions and while I run ```react-native unlink react-native-webview``` and then ```cd ios && pod install``` the app can be built successfully in Xcode.But if I unlink react-native-webview I cannot use Webview in my app, can anyone help?

**Comment by cruzach** [comment] 2019-10-14 13:46
why are you unlinking?

**Comment by potatoMa** [comment] 2019-10-15 03:06
> why are you unlinking?

I just want to provide more information, if I link and pod install, the build will failed because of duplicate symbol error.

**Comment by cruzach** [comment] 2019-10-15 13:47
I was confused since you said:
> But if I unlink react-native-webview I cannot use Webview in my app
So I thought, well you need to link for it to work.

I just tested this myself on an `expo init -t bare-minimum` project, after running 
- `expo install react-native-webview`
- `react-native link react-native-webview`
- `cd ios && pod install`

and I built with no errors, using this code: 
```
import React, { Component } from "react";
import { WebView } from "react-native-webview";

export default class App extends Component {
  render() {
    return (
      <WebView source={{ uri: "https://expo.io" }} style={{ marginTop: 20 }} />
    );
  }
}
```
can you try that and see if it works? If not, please provide a full repro

**Comment by TheDude70** [comment] 2019-10-18 03:09
I have exact same issue after I ejected expo to expokit. I tried react-native link, tried manual linking, both with same result: duplicate symbols.

@cruzach I also created a bare-minimum project with only react-native-webview and it indeed builds correctly. The issue must therefore lie as far as I can tell with expo projects ejected to Expokit.

**Comment by TheDude70** [comment] 2019-10-19 04:42
@cruzach An update to further trying to get things to work. I realized my project was on Expo SDK 34, so decided to upgrade to SDK 35, but that only made things worse. After linking react-native-webview I now ended up with **53** duplicate symbols instead of just 5. Without react-native-webview it builds and runs just fine.

**Comment by TheDude70** [comment] 2019-10-19 12:03
After much trial and error finally got it working and hopefully this will help @potatoMa or others.

@potatoMa are you sure you have a bare app? Bare app would not have Expokit as standard.

When using Expokit there is no need to do `react-native link` as `react-native-webview` is incorporated in Expo. It is confusing when following the documentation. Linking is for bare apps, which I thought was any Expo ejected app. So what I did to get things working is to have the matching version incorporated into Expo by doing the following steps:

`react-native unlink react-native-webview`
`pod install`
`expo install react-native-webview@7.0.5` 
`clean/build in XCode`

This gave me a successful build, but I encountered a blank `WebView` (which was one of the reasons I kept trying to do react-native link. Turns out that I needed to specify a width and height in the style prop, i.e. `<WebView style={{width: 500, height: 300}} source={{ html: "<h1>Hello world</h1>"}} />, which then gave me a successful WebView implementation in my ejected expo project.

**Comment by UdithaKasun** [comment] 2019-10-24 12:56
`duplicate symbol '_OBJC_CLASS_$__SwizzleHelperWK' in:
    /Users/test/Library/Developer/Xcode/DerivedData/delivery-bpolxrxvqfxdgsbqewgavbvxkyde/Build/Products/Debug-iphonesimulator/ExpoKit/libExpoKit.a(RNCWKWebView.o)
    /Users/test/Library/Developer/Xcode/DerivedData/delivery-bpolxrxvqfxdgsbqewgavbvxkyde/Build/Products/Debug-iphonesimulator/libRNCWebView.a(RNCWebView.o)
duplicate symbol '_OBJC_METACLASS_$__SwizzleHelperWK' in:
    /Users/test/Library/Developer/Xcode/DerivedData/delivery-bpolxrxvqfxdgsbqewgavbvxkyde/Build/Products/Debug-iphonesimulator/ExpoKit/libExpoKit.a(RNCWKWebView.o)
    /Users/test/Library/Developer/Xcode/DerivedData/delivery-bpolxrxvqfxdgsbqewgavbvxkyde/Build/Products/Debug-iphonesimulator/libRNCWebView.a(RNCWebView.o)
duplicate symbol '_OBJC_CLASS_$_RNCWKProcessPoolManager' in:
    /Users/test/Library/Developer/Xcode/DerivedData/delivery-bpolxrxvqfxdgsbqewgavbvxkyde/Build/Products/Debug-iphonesimulator/ExpoKit/libExpoKit.a(RNCWKProcessPoolManager.o)
    /Users/test/Library/Developer/Xcode/DerivedData/delivery-bpolxrxvqfxdgsbqewgavbvxkyde/Build/Products/Debug-iphonesimulator/libRNCWebView.a(RNCWKProcessPoolManager.o)
duplicate symbol '_OBJC_METACLASS_$_RNCWKProcessPoolManager' in:
    /Users/test/Library/Developer/Xcode/DerivedData/delivery-bpolxrxvqfxdgsbqewgavbvxkyde/Build/Products/Debug-iphonesimulator/ExpoKit/libExpoKit.a(RNCWKProcessPoolManager.o)
    /Users/test/Library/Developer/Xcode/DerivedData/delivery-bpolxrxvqfxdgsbqewgavbvxkyde/Build/Products/Debug-iphonesimulator/libRNCWebView.a(RNCWKProcessPoolManager.o)
duplicate symbol '_OBJC_IVAR_$_RNCWKProcessPoolManager._sharedProcessPool' in:
    /Users/test/Library/Developer/Xcode/DerivedData/delivery-bpolxrxvqfxdgsbqewgavbvxkyde/Build/Products/Debug-iphonesimulator/ExpoKit/libExpoKit.a(RNCWKProcessPoolManager.o)
    /Users/test/Library/Developer/Xcode/DerivedData/delivery-bpolxrxvqfxdgsbqewgavbvxkyde/Build/Products/Debug-iphonesimulator/libRNCWebView.a(RNCWKProcessPoolManager.o)
ld: 5 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

I didn't link the library bu still get this in Expo SDK 35 in a detached app.

**Comment by thanh90** [comment] 2019-11-12 07:56
> After much trial and error finally got it working and hopefully this will help @potatoMa or others.
> 
> @potatoMa are you sure you have a bare app? Bare app would not have Expokit as standard.
> 
> When using Expokit there is no need to do `react-native link` as `react-native-webview` is incorporated in Expo. It is confusing when following the documentation. Linking is for bare apps, which I thought was any Expo ejected app. So what I did to get things working is to have the matching version incorporated into Expo by doing the following steps:
> 
> `react-native unlink react-native-webview`
> `pod install`
> `expo install react-native-webview@7.0.5`
> `clean/build in XCode`
> 
> This gave me a successful build, but I encountered a blank `WebView` (which was one of the reasons I kept trying to do react-native link. Turns out that I needed to specify a width and height in the style prop, i.e. `<WebView style={{width: 500, height: 300}} source={{ html: "SOME HTML"}} />, which then gave me a successful WebView implementation in my ejected expo project.

Thank bro, that's what I looking for

**Comment by cruzach** [comment] 2019-11-12 14:49
Going to close this as it seems the problem was caused by unnecessarily linking a module that was already linked

**Closed by cruzach** 2019-11-12 14:49 UTC
Labels: bug, needs repro, project: expokit

**Comment by wcandillon** [comment] 2019-11-19 17:02
@TheDude70 Thank you for saving me hours of work 🙌🏻

**Comment by alexbuicescu** [comment] 2020-03-21 20:25
@cruzach maybe this is an issue with the docs? There are plenty other errors similar to this one and all because those libraries are already linked by expo. The trouble is that in docs it says to do a `expo install lib_here` or if you have a bare app to do something along the lines of `npm install lib_here && react-native link lib_here && pod install` but neither one of these works with expokit in case you have auto-linking active (which I think is the default since expo 35/36)
