### ISSUE TITLE
Cannot destructure property `allowedHost` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by Siyavoshi** [expo/expo#5727] opened 2019-09-22 08:31 UTC
### Environment

Expo CLI 3.1.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.17.3 - C:\Users\user\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312

Android and web
### Steps to Reproduce

Created a bare-minimum project using "expo-init my-app"  as well as "create-react-native-app my-app". 
"yarn android" runs just fine but when I run "yarn web", DevTools opens in the browser but I get this in the terminal:
 
D:\ReactNative\TestExpo>yarn web
yarn run v1.17.3
$ expo start --web
Starting project at D:\ReactNative\TestExpo
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Starting Metro Bundler on port 19001.
Successfully ran `adb reverse`. Localhost URLs should work on the connected Android device.
Tunnel ready.
Cannot destructure property `allowedHost` of 'undefined' or 'null'.
Set EXPO_DEBUG=true in your env to view the stack trace.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

It's a brand-new project.

### Expected Behavior

I expect the default react native boilerplate to show up in the browser.

### Reproducible Demo

https://github.com/Siyavoshi/expo-bug

**Comment by kations** [comment] 2019-09-22 10:17
getting the same error with a fresh expo init project and also with an upgraded from sdk 34 to 35

**Comment by NWylynko** [comment] 2019-09-22 11:34
yup, web was fine on sdk 34 before updating project to sdk 35, now getting this error

**Comment by robinstraub** [comment] 2019-09-22 16:11
This issues come from the createDevServerConfigAsync.ts script receiving for argv `undefined`

As a temporary solution before this issue is fixed, you can use a custom webpack config and replace the argv value by a custom one.

see [https://docs.expo.io/versions/latest/guides/customizing-webpack/](https://docs.expo.io/versions/latest/guides/customizing-webpack/) for how to setup it.

basically you install @expo/webpack-config (`npm i @expo/webpack-config`), and you add a `webpack.config.js` file to the root of your project.

As for the configuration, you can use the following

```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function(env, argv) {
  // assign argv properties to an empty object. currently argv is undefined, causing the issue.
  const config = await createExpoWebpackConfigAsync(env, Object.assign({}, argv));
  
  // customize the configuration to your needs

  return config;
};
```

Beware that it does not solve the underlying issue, but only allows you to use expo web nonetheless.

**Comment by DLevai94** [comment] 2019-09-22 16:51
After downgrading to 34, problem still present.

**Comment by Siyavoshi** [comment] 2019-09-23 06:40
@robinstraub 's solution worked for me, but I'll keep this issue open until a proper fix.

**Comment by jjg77** [comment] 2019-09-23 13:40
@robinstraub solution works for me too, but I have to run "expo start --web" twice, the first run always fails with same error.

**Comment by MOwais** [comment] 2019-09-23 18:56
getting the same error for an existing expo project. one second expo start -w was fine next second I started getting this error

**Comment by Florianer** [comment] 2019-09-23 20:40
Confirmed, @robinstraub 's solution worked for me, too. Multiple "expo start --web" didn't do the trick. Just follow the instruction, but do not generate the `webpack.config.js` on your own, as you will then not get the file generated.

**Comment by ide** [comment] 2019-09-25 00:52
This should be fixed in https://github.com/expo/expo-cli/commit/5aab6e1e2846e625282801eac13ac97edf2a8dce, which has been published to npm.

**Closed by ide** 2019-09-25 00:52 UTC
Labels: bug
