### ISSUE TITLE
[expo-image] using numbers as an image source is not supported on web

### ISSUE THREAD

**Issue by philiplindberg** [expo/expo#21440] opened 2023-02-28 13:59 UTC
### Minimal reproducible example

https://github.com/philiplindberg/expo-image-repro

### Summary

I'm trying to display local SVGs in my universal app (native + web) but I'm running into some issues when defining the image source. On native, it seems like I have to define the source using `require` (e.g. `require(./path/to/image.svg)`), but on web only the path itself is supported (e.g. `./path/to/image.svg`) - see linked [repro](https://github.com/philiplindberg/expo-image-repro). 

Is there a way to define the source of a local SVG that works across both native and web?

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.6.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.4.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.4 => 48.0.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
      react-native-web: ~0.18.10 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.0.8
    Expo Workflow: managed

**Comment by aleqsio** [comment] 2023-03-09 10:23
I can't reproduce this :/ 

It works for me in the cloned repro and when trying to use svgs using require - not sure what happened but if you can still repro would be curious to see what's inside the `require` result.

**Comment by aleqsio** [comment] 2023-03-20 12:08
Ok, sorry, seems I was a bit too rush in closing this.

**Comment by aleqsio** [comment] 2023-03-20 12:34
Ok, found it:

It breaks if you set `app.json > expo > web > bundler` to "metro"

**Comment by philiplindberg** [comment] 2023-03-21 17:26
Awesome, thanks for investigating that so quickly! Looking forward to seeing those two PRs merged.

**Closed** 2023-04-11 13:53 UTC
Labels: Issue accepted

**Comment by aleqsio** [comment] 2023-04-24 11:29
Try to bump expo-image to latest and see if that fixes the issue

**Comment by Akronae** [comment] 2023-04-25 09:27
It works with
```
expo-image@1.2.1
metro@0.73.7
metro-resolver@0.73.7
expo@48.0.4
```
Without any patch needed.
Everything works fine, even base64 URLs, it's really great 😄 
_(except that anoying `Some dependencies are incompatible with the installed expo version` message)_
Thx!

**Comment by philiplindberg** [comment] 2023-04-28 12:33
I can confirm that the issue has been resolved with the latest version of `expo-image` (1.2.1).

I did have to add the following lines to my `package.json` to get more recent versions of `metro` and `metro-resolver`:

```json
"resolutions": {
  "metro": "0.76.1",
  "metro-resolver": "0.76.1"
}
```
