### ISSUE TITLE
[docs] Documentation is not enough for configuring jest

### ISSUE THREAD

**Issue by felpsio** [expo/expo#27152] opened 2024-02-18 13:40 UTC
### Summary

Documentation for setting up unit tests is incomplete.

In a fresh project based on the expo router template I can't get my tests to run. Looks like there is something missing from the jest.config.js or the babel.

My test:
```
import { Text, View } from 'react-native';

const App = () => {
  return (
    <View>
      <Text>Hello</Text>
    </View>
  );
};

describe('<App />', () => {
  it('has 1 child', () => {
    expect(1).toBe(1);
  });
});
```

Output:
```
14 | import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/Accessib
            ^
error: Unexpected typeof
    at /Users/USER/PROJECT/node_modules/react-native/index.js:14:8

 0 pass
 1 fail
Ran 1 tests across 1 files. [13.00ms]
```

my settings:

babel.config.js
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      ['babel-preset-expo', { jsxImportSource: 'nativewind' }],
      'nativewind/babel',
    ],
  };
};

```

PS: I tested removing nativewind and the problem persists.

tsconfig.json
```
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true,
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["**/*.ts", "**/*.tsx", ".expo/types/**/*.ts", "expo-env.d.ts"]
}
```

package.json:
```
"jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
    ]
  },
...
"expo": "~50.0.7",
"@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "jest": "^29.3.1",
    "jest-expo": "~50.0.2",
    "react-test-renderer": "18.2.0",
    "typescript": "^5.1.3"
...
  ```

### Link to the related docs page

https://docs.expo.dev/develop/unit-testing/

**Comment by tomhendra** [comment] 2024-02-27 17:06
Some detailed docs on how to configure jest-expo/universal + @testing-library/react-native in a TS project would be fantastic.

**Comment by amandeepmittal** [comment] 2024-04-07 18:27
Hey @felpsio, I'm not able to reproduce the error you shared. I've created a reproducible example based on the information you provided: https://github.com/amandeepmittal/jest-27152-issue. Please try to run it locally on your machine and let me know if you see the same issue.

**Comment by glade-at-gigwell** [comment] 2024-06-20 22:42
I found that running the tests through bun doesn't work right, and we *must* execute the test job through npm.

**Comment by amandeepmittal** [comment] 2024-06-21 07:06
@glade-at-gigwell, which bun version are you using?

**Comment by glade-at-gigwell** [comment] 2024-06-21 17:57
1.1.13.

**Comment by glade-at-gigwell** [comment] 2024-06-21 17:58
If I drop into a terminal in web storm and use `npm run test`, the create-expo-app tests work.  If it's invoked through bun, well, that's how I found this ticket. 

(I also noticed the SDK51 ships 1 test file, but the jest pattern doesn't match this file name. )

**Comment by amandeepmittal** [comment] 2024-07-29 20:53
Hey @glade-at-gigwell, maybe that's an issue with Bun package manager? If you can share a reproducible example, please feel free to share that by opening a new issue.

You are right, in the new default template, the file pattern  used is `*-test.tsx` which is the configuration provided by `jest-expo`. We're updating the Testing guide (previously called Unit Testing) in this PR: https://github.com/expo/expo/pull/30695 which covers this information.

I'm closing this issue for now.

**Closed by amandeepmittal** 2024-07-29 20:53 UTC
Labels: docs

**Comment by MarcHbb** [comment] 2024-08-26 11:27
@glade-at-gigwell 
I have exactly the same issue. I just install bun (expo 51) but all my tests are failing but when using npm it's all good

**Comment by miraritech** [comment] 2024-12-26 17:06
Adding a comment for folks coming from google who's running SDK52,
I got this error when running `bun test`.
```
# Unhandled error between tests
-------------------------------
15 | import typeof ActionSheetIOS from './Libraries/ActionSheetIOS/ActionSheetIOS';
```

Bun is the culprit, or at least I don't know how to use bun.
Bun allow us to run a shorthand version of a command (similar to yarn) like: `bun start` instead of `bun run start`.
By common sense, we usually add `test` script in our package.json and assume it will run `bun run test`.

But turns out `bun test` is a reserved command in bun.. `bun run test` solved it though...

**Comment by Syakhisk** [comment] 2024-12-26 17:08
Adding a comment for folks coming from google who's running SDK52,
I got this error when running `bun test`.

```
# Unhandled error between tests
-------------------------------
15 | import typeof ActionSheetIOS from './Libraries/ActionSheetIOS/ActionSheetIOS';
```
Bun is the culprit, or at least I don't know how to use bun.
Bun allow us to run a shorthand version of a command (similar to yarn). Think `bun start` instead of `bun run start`.
By common sense, we usually add `test` script in our package.json and assume it will run `bun run test`.

But turns out `bun test` is a reserved command in bun.. `bun run test` solved it though...
