### ISSUE TITLE
Android: Video not loading

### ISSUE THREAD

**Issue by alohawav** [expo/expo#958] opened 2017-11-13 16:52 UTC
I’m using Expo.Video to render videos whose source is the Vimeo API. It can load the video seamlessly on iOS, however on Android, it loads them randomly, and 90% of the time none of the videos are loaded. They are the same video files on both systems, so they are not broken links.

Has anyone ever had problems loading videos to android and was able to resolve them?

**Code fragment:**

```js 
replay = async (PlaybackStatus) => {
    if (PlaybackStatus.didJustFinish) {
      await this.videoPlayer.setPositionAsync(0)
      this.setState({ shouldPlay: false })
    }
  }
```

[...]

```js 
<Video
                  ref={(o) => (this.videoPlayer = o)}
                  source={{ uri }}
                  rate={1.0}
                  volume={1.0}
                  muted={false}
                  resizeMode="cover"
                  style={videoStyle}
                  shouldPlay={this.state.shouldPlay}
                  useNativeControls={Platform.OS === 'ios'}
                  onPlaybackStatusUpdate={(PlaybackStatus) => this.replay(PlaybackStatus)}
                />
```

P.S. I'm using native controls only on iOS because of the bizarre behavior of Android (it's still frozen at the same point during scrolling).

Related Packages:
        "expo": "^22.0.0",
        "react-native": "https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz",
        "react": "16.0.0-beta.5",
        "axios": "^0.16.2",
        "react-redux": "^5.0.6",
        "redux": "^3.7.2",
        "redux-axios-middleware": "^4.0.0",

**Comment by jimmylee** [comment] 2017-11-13 20:05
Hi @alohawav sorry you're encountering problems on Android, I've looped in @jesseruder who has far more expertise than myself to take a quick look.

**Comment by ksnll** [comment] 2017-11-15 08:11
Same happening here, both loading bug and native controls problem

**Comment by sjchmiela** [comment] 2017-12-20 11:58
Hello @alohawav and @ksnll!

What problems have you encountered when using `Video` component?

Here's a sample snack showcasing `<Video />` usage that seems to work properly: https://snack.expo.io/@sjchmiela/android-native-controls-and-replay-showcase.

**Comment by sjchmiela** [comment] 2018-01-23 17:11
I'll close this (I believe the issue may have been resolved) for now, feel free to reopen this if the problem occurs again!

**Closed by sjchmiela** 2018-01-23 17:11 UTC
Labels: project: android-runtime, project: media, ready, status: needs more info

**Comment by watadarkstar** [comment] 2018-06-06 22:22
related: https://forums.expo.io/t/videos-disappear-in-a-flatlist-on-android/10408

**Comment by tslater** [comment] 2018-07-22 22:43
I'm having some serious troubles with videos that work great in iOS and the native android video player. They either don't show up, or skip many frames, sometimes appear to only show only 2-3 frames while the audio for the who video plays. The issue occurs on both the android simulator and my device. Any tips on how to diagnose?

**Comment by henrymoulton** [comment] 2018-07-25 11:04
@tslater I'm experiencing this now, investigating solutions

**Comment by sjchmiela** [comment] 2018-07-25 11:11
Hi @tslater, could you please open a new issue? This one is quite old, happening on SDK 22, the cause of your problem may be completely unrelated. 🤷‍♂️ A Snack reproducing the issue would also help a ton!

**Comment by henrymoulton** [comment] 2018-07-25 12:07
@sjchmiela posted in #2028

**Comment by thekrol01** [comment] 2019-02-08 11:02
Same issue with Videos in a Flatlist on Android. SDK32.
https://github.com/expo/expo/issues/3443
