### ISSUE TITLE
[Battery][Android] Standalone app crash - Battery Module - onBatteryStateChange - java.lang.NullPointerException

### ISSUE THREAD

**Issue by jamesbechet** [expo/expo#5759] opened 2019-09-24 14:57 UTC
## 🐛 Bug Report
Since I've upgraded to SDK 34 and 35, I'm getting this crash in production. However, I'm only getting this error on Android. Sentry doesn't seem to catch anything.

I'm not using the `Battery` module at all.

I've hesitated to post this error since I'm not able to reproduce in development, but it happened to different devices in production. It's the exact stack trace every single time. So if you have an idea on how to prevent me to have this issue, it would greatly appreciated.

Here's the full error:
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3118)
  at android.app.ActivityThread.-wrap18 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1593)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:163)
  at android.app.ActivityThread.main (ActivityThread.java:6228)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)
Caused by: java.lang.NullPointerException: 
  at expo.modules.battery.BatteryModule.onBatteryStateChange (BatteryModule.java:78)
  at expo.modules.battery.BatteryStateReceiver.onReceive (BatteryStateReceiver.java:16)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3103)
```

### Environment
Production - Managed App - Standalone Android

### Steps to Reproduce
N/A

### Expected Behavior
To not crash.

### Actual Behavior
Crashes.

### Reproducible Demo
N/A

**Comment by jamesbechet** [comment] 2019-09-24 15:03
This seems to be the error:
`mEventEmitter.emit(BATTERY_CHARGED_EVENT_NAME, result);`

https://github.com/expo/expo/blob/master/packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryModule.java#L78

Is there a way that `mEventEmitter` is not defined here? Since i'm not using using the `Battery` module, that could explain it.

**Comment by bill-pairaktaridis** [comment] 2019-09-25 09:59
I'm having the same. Dozens of crashes that I can't reproduce locally.

**Comment by randomjunk** [comment] 2019-09-26 06:04
yeah, 1000s of crashes reported on the Play Store in 2 days with this.
0 user complaints though, so maybe not noticeable to the user.

We built with expo 35 on Saturday:
```
Caused by: java.lang.NullPointerException: 
  at expo.modules.battery.BatteryModule.onBatteryStateChange (BatteryModule.java:78)
  at expo.modules.battery.BatteryStateReceiver.onReceive (BatteryStateReceiver.java:16)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3309)
```

Also (lower frequency):
```
Caused by: java.lang.NullPointerException: 
  at expo.modules.battery.BatteryLevelReceiver.onReceive (BatteryLevelReceiver.java:18)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3306)
```

And probably unrelated, but still new with Expo 35 so I'll include in case relevant (much lower frequency):
```
java.lang.RuntimeException: 
  at host.exp.exponent.experience.BaseExperienceActivity$2.run (BaseExperienceActivity.java:196)
  at android.os.Handler.handleCallback (Handler.java:873)
```

**Comment by sweebee** [comment] 2019-09-26 06:12
same here, see a lot of crashes on android.

**Comment by randomjunk** [comment] 2019-09-26 07:01
I don't know much about unimodules, but the problem would seem to be use of statics (everywhere else unimodules appear to use effectively singleton instances exclusively):
https://github.com/expo/expo/blob/master/packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryModule.java#L30
registering listeners in onCreate:
https://github.com/expo/expo/blob/master/packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryModule.java#L67
then not implementing onDestroy to cleanup:

Also the rather surprising thing that despite not using the battery module at all, our app is now subscribing to these events (I would have expected a register on first call system).

**Comment by randomjunk** [comment] 2019-09-26 11:58
This is trivial to reproduce in the expo bare app:
![power-cable-crash](https://user-images.githubusercontent.com/440763/65686640-4d00f700-e05d-11e9-9d55-d556dc6718de.gif)

(using expo's default Android 5 emulator)

Stack:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: host.exp.exponent, PID: 3757
    java.lang.RuntimeException: Unable to start receiver expo.modules.battery.BatteryStateReceiver: java.lang.NullPointerException: Attempt to invoke interface method 'void org.unimodules.core.interfaces.services.EventEmitter.emit(java.lang.String, android.os.Bundle)' on a null object reference
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2616)
        at android.app.ActivityThread.access$1700(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void org.unimodules.core.interfaces.services.EventEmitter.emit(java.lang.String, android.os.Bundle)' on a null object reference
        at expo.modules.battery.BatteryModule.onBatteryStateChange(BatteryModule.java:78)
        at expo.modules.battery.BatteryStateReceiver.onReceive(BatteryStateReceiver.java:16)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2609)
        at android.app.ActivityThread.access$1700(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

**Comment by linus** [comment] 2019-09-26 14:55
We see this as well. Thousands of crashes over the last couple of days. We need 35 to upgrade for iOS, I guess now we will have to support two tracks for the two platforms?

**Comment by randomjunk** [comment] 2019-09-26 15:03
Right, so I've looked into this a bit more.

The problem appears to be that that intents are registered in the manifest:
https://github.com/expo/expo/blob/master/packages/expo-battery/android/src/main/AndroidManifest.xml#L4

Which implies they can always be instantiated and created by the OS as an entry point to your application. Except that the BatteryModule makes no attempt to initialise the app, so this fails dramatically with an NPE.

This is exacerbated in the bare-expo project as the BatteryModule is *never* created. I'm not sure why that is, but it isn't (tested with Log.w() output in the onCreate method -- you have to add to HomeActivity.homeExpoPackages() for it to appear). This means you always get an NPE, and even if you add a guard to that, it fails to update the battery status in the app.

As of Android 8 these manifest declared implicit broadcasts were disallowed. So on Android 8 and later the NPE doesn't generally happen.

As the intents trigger even when the app is backgrounded, the result is a crash report every time the user plugs in their charger/unplugs their charger on Android <= 7.1.
Which is why we have thousands of reports.

I *think* a fix is to simply remove the contents of the AndroidManifest.xml in the expo.modules.battery package.

**Comment by mikemoate** [comment] 2019-09-26 15:38
#5754 would appear to be a duplicate of this issue.

**Comment by Gorbus** [comment] 2019-09-27 11:07
Apparently a PR was posted to solve the issue but do we have to submit a new version of the app, an OTA update or something  for it to be effective or will it be solved on its own ?

**Comment by cruzach** [comment] 2019-09-27 17:58
@Gorbus that fix will require you to rebuild your apk

**Comment by cruzach** [comment] 2019-09-27 18:28
This fix has been deployed, so I'm closing this issue 👍

**Closed by cruzach** 2019-09-27 18:28 UTC
Labels: Battery, bug

**Comment by linus** [comment] 2019-09-30 09:46
> This fix has been deployed, so I'm closing this issue 👍

What should we do in order to ship a fix for this?
I see that the expo-battery module has been bumped; we don't use expo-battery, but are bitten by this bug anyway.

**Comment by Gorbus** [comment] 2019-09-30 09:58
as cruzach mentionned in his first answer you have to rebuild an apk or aab and submit it again to the play store for an update.

**Comment by linus** [comment] 2019-09-30 10:01
@Gorbus thanks. I can't seem to find expo `35.0.1` though, so when I rebuild I think I get the exact same code?

**Comment by Gorbus** [comment] 2019-09-30 10:06
I think it was backported into sdk 35 so if you don't need expokit (managed workflow for example) you are good just with sdk 35. With expokit I don't know but apprently 35.0.1 should exist.

**Comment by linus** [comment] 2019-09-30 12:41
Thanks, I am on the managed workflow. So I don't need to update any dependencies, just rebuild it. Check.
