### ISSUE TITLE
"Your app currently targets API level 28 and must target at least API level 29" Warning on Google Play Console

### ISSUE THREAD

**Issue by formaldehydeson** [expo/expo#9370] opened 2020-07-23 22:41 UTC
I just went to upload my app (built as an app bundle) that's in testing to the Google Play Console and was met with this warning:

Warnings
Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance.

From August 2020, new apps must target at least Android 10 (API level 29).
From November 2020, app updates must target Android 10 (API level 29).

Tip: Change your app's target API level. Learn how. [https://developer.android.com/distribute/best-practices/develop/target-sdk.html]

![image](https://user-images.githubusercontent.com/5740730/88345211-81901e80-cd13-11ea-83d5-8b23b9f71cfb.png)

My app is using Expo SDK version 38.0, and I had previously uploaded a version built with 38.0 with no warning. Is anybody else seeing this warning pop up now? And what needs to be done to alleviate it?

**Comment by karanmartian** [comment] 2020-07-24 18:28
@formaldehydeson Yes I am seeing the same issue. Does this mean that app wont work on Android 10? or it will but not just with the highest level of security?

**Comment by SamuelFoisy** [comment] 2020-07-24 18:37
@formaldehydeson same issue here! Is there any plan to patch this soon?

**Comment by cruzach** [comment] 2020-07-24 19:36
@karanmartian Expo apps work on Android 10, this is just a warning from Google Play. We're working on this and already have an open issue, so I'm going to close this as a duplicate of https://github.com/expo/expo/issues/8469

**Closed by cruzach** 2020-07-24 19:36 UTC
