### ISSUE TITLE
[Expo Router] [SDK52] Deeplink does not navigate to the right route

### ISSUE THREAD

**Issue by inkless** [expo/expo#32987] opened 2024-11-17 05:05 UTC
### Minimal reproducible example

https://github.com/inkless/expo-router-bug

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Note: This is a dummy app created by `create-expo-app`, nothing really changed except I added `expo-dev-client` and updated the `scheme` to `expobug` in app.json.

Reproduction steps:
1. `yarn install`
2. `npx expo run:ios`
3. Verify the app is properly opened and functioning
4. Navigate to Home tab
5. `npx uri-scheme open expobug://explore --ios`

Expected Behavior: 
App navigates to Explore tab

Actual Behavior:
The simulator is popping up a modal asking for user permission, once confirmed, nothing happened.
App does not navigate to Explore tab.

Additional Context:
1. When the app is closed, using `npx uri-scheme open expobug://explore --ios` will open the app, but not navigating to the right page
2. When the app is killed, using `npx uri-scheme open expobug://explore --ios` will be pop up the development client and asking users to pick an app, it will be able to navigate to the right page.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.7.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nodenv/versions/20.10.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.7.0 - ~/.nodenv/versions/20.10.0/bin/npm
      Watchman: 2024.10.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7
      expo-router: ~4.0.6 => 4.0.6
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
      react-native-web: ~0.19.13 => 0.19.13
    npmGlobalPackages:
      eas-cli: 12.6.2
    Expo Workflow: managed
```

**Comment by marklawlor** [comment] 2024-11-19 00:05
Closing as duplicate of #33031. We'll track this issue there as its a problem with the `expo-linking` package.

**Closed by marklawlor** 2024-11-19 00:05 UTC
Labels: needs review, Router
