### ISSUE TITLE
Android Adaptive Icon Not Appearing

### ISSUE THREAD

**Issue by JJwilkin** [expo/expo#10035] opened 2020-09-01 23:53 UTC
### Summary of Issue 
I am having an issue with setting Android Adaptive Icon (foreground/background) fields in the app.json file. I followed the Expo documentation https://docs.expo.io/guides/app-icons/ however the app icon is just surrounded by a white circle.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: 0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.3.9 => 4.4.0
    npmGlobalPackages:
      expo-cli: 3.25.1
```

### Reproducible Demo
```
{
  "name": "ChowTime",
  "displayName": "ChowTime",
  "expo": {
    "name": "ChowTime",
    "slug": "ChowTime",
    "version": "3.0.0",
    "icon":"./assets/icon.png",
    "android": {
      "package": "com.yourcompany.chowtime",
      "versionCode": 2,
      "icon": "./assets/icon.png",
      "adaptiveIcon": { 
        "foregroundImage": "./assets/icon.png",
        "backgroundColor": "#000000" 
      }
    },
    "splash": {
      "image": "./assets/splashScreen.png",
      "resizeMode": "cover"
    },
    "platforms": ["ios", "android", "web"],
    "assetBundlePatterns": ["**/*"]
  }
}
```

 

### Expected Behavior vs Actual Behavior
The background color should be the black background I set, instead, it is the default white by Expo

![118780231_932666763876637_1421175259356935128_n](https://user-images.githubusercontent.com/44853346/91917023-c2714080-ec8c-11ea-8f95-ee60c1299c2e.png)

**Comment by byCedric** [comment] 2020-09-02 13:59
Hi @JJwilkin, thanks for writing in. Could you try if either one of these workarounds work for you?

1. Remove the `expo.icon` property to solely rely on `expo.android.adaptiveIcon`. If this works, we need to reverse this priority.
2. Use `expo.android.adaptiveIcon.backgroundImage` instead with just the black color. Could be [related to this issue](https://github.com/expo/expo/issues/7374#issuecomment-623699812).

Hope this helps!

**Comment by JJwilkin** [comment] 2020-09-02 14:17
Hi @byCedric, unfortunately both 1/2 didn't work. I tried a variety of different combinations but it seems Expo only pays attention to expo.icon, I added expo.android.icon, it ignored that as well. 

I tried the backgroundImage property with the same dimensions as my foregroundImage (1024x1024) and no changes are reflected

**Comment by JJwilkin** [comment] 2020-09-02 14:25
This is my App.Json as it stands:

```
{
  "name": "ChowTime",
  "displayName": "ChowTime",
  "expo": {
    "name": "ChowTime",
    "slug": "ChowTime",
    "version": "3.0.0",
    "icon":"./assets/icon.png",
    "android": {
      "package": "com.yourcompany.chowtime",
      "versionCode": 2,
      "icon": "./assets/greenicon.png",
      "adaptiveIcon": { 
        "foregroundImage": "./assets/greenicon.png",
        "backgroundImage": "./assets/green-background.png"
      }
    },
    "splash": {
      "image": "./assets/splashScreen.png",
      "resizeMode": "cover"
    },
    "platforms": ["ios", "android", "web"],
    "assetBundlePatterns": ["**/*"]
  }
}
```

**Comment by soullivaneuh** [comment] 2020-10-15 22:13
I have exactly the same issue. Here is my configuration file:

```
{
  "expo": {
    "name": "xxx",
    "slug": "xxx"
    "privacy": "unlisted",
    "platforms": ["ios", "android", "web"],
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffcfd1"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "icon": "./assets/icon.png",
      "adaptiveIcon": {
        "foregroundImage": "./assets/icon.android.png",
        "backgroundColor": "#ffcfd1"
      }
    }
  }
}
```

Using expo v3.27.14 including the fix of #7374:

```
  Expo CLI 3.27.14 environment info:
    System:
      OS: Linux 5.7 Manjaro Linux
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.7.0 - /usr/bin/node
      npm: 6.14.8 - /usr/bin/npm
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.27.14
    Expo Workflow: managed
```

**Comment by soullivaneuh** [comment] 2020-10-31 16:38
@byCedric May you have any clue about the root cause of this issue? :thinking:

**Comment by cruzach** [comment] 2020-11-02 18:45
This is the same as https://github.com/expo/expo/issues/7374 which I wrongfully closed (the PR only affected the bare workflow). Are the devices you are testing on Android 7 or below? 

I think this might have to do with a missing `ic_launcher_round` configuration in the managed workflow

**Comment by soullivaneuh** [comment] 2020-11-16 00:50
Well, I just figured out some configuration keys of my `app.json` are removed bu my `app.config.js` logic including... the adaptive icon configuration. :upside_down_face: 

I am right now making a new build to verify it's the cause of the issue, but may be it's the same thing for @JJwilkin: Do you have any side `app.config.js` on your project?

**Comment by MedjahdiKaram** [comment] 2020-12-18 20:28
> Well, I just figured out some configuration keys of my `app.json` are removed bu my `app.config.js` logic including... the adaptive icon configuration. 🙃
> 
> I am right now making a new build to verify it's the cause of the issue, but may be it's the same thing for @JJwilkin: Do you have any side `app.config.js` on your project?
> 
> Edit: That was my issue.

Please can you explain more how you figured it out ?

**Comment by brentvatne** [comment] 2020-12-18 22:15
@soullivaneuh - if you have app.config.js and app.json you need to spread the app.json "base config" in app.config.js

from https://docs.expo.io/workflow/configuration/#dynamic-configuration-with-appconfigjs

```
export default ({ config }) => {
  console.log(config.name); // prints 'My App'
  return {
    ...config,
  };
};
```

**Comment by cruzach** [comment] 2021-01-13 16:44
Going to allow myself to close this issue since it seems to be explained by improper app.json & app.config.js usage? Although if that's not the case let me know and I can re-open (but please include your device and android OS version so I can reproduce, as I asked for in [this comment](https://github.com/expo/expo/issues/10035#issuecomment-720656023))

**Closed by cruzach** 2021-01-13 16:44 UTC
Labels: Android, needs more info

**Comment by moxley** [comment] 2022-05-01 17:16
I had this same problem. I was testing on an old simulated device: a Pixel 2. The Expo placeholder icon always showed in the Expo developer menu no matter what I tried. Then, when I tried on a Pixel 5, my app icon appeared.
