### ISSUE TITLE
Old Google Sign in doesn't redirect back to the app, instead goes to google.com

### ISSUE THREAD

**Issue by otaviogaiao** [expo/expo#4739] opened 2019-06-27 13:26 UTC
## 🐛 Bug Report

I had an app on SDK 31 that used the old google sign in. All worked fine, however, after upgrading to SDK 33, the lib doesn't redirect me back to my app after I login with google. It goes instead to www.google.com . This only happens on standalone Android. No error is thrown and my app doesn't receive any answer. 

### Environment

```
  Expo CLI 2.20.11 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.7 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.20.11
```

App is available for iOS and Android. But only on Android standalone the issue occurs.

### Steps to Reproduce

Build an Android APK with the old Google signIn. Try to sign in and you will see google won't redirect back to the app. I tested on Xiaomi Redmi NOTE 3 and on Samsung galaxy S9+.

### Expected Behavior

After login, the web view should redirect back to the app.

### Actual Behavior

After login, the web view/browser remains open and redirects to google.com

### Reproducible Demo

The issue only happens with the Android Standalone. Not reproducible on snacks.

Here is how I'm doing the auth part:

```
     import { Google } from 'expo';
     .....
     
      const result = await Google.logInAsync({
        androidClientId: GOOGLE_ANDROID_CLIENT_ID,
        iosClientId: GOOGLE_IOS_CLIENT_ID,
        androidStandaloneAppClientId: GOOGLE_ANDROID_STANDALONE_CLIENT_ID,
        iosStandaloneAppClientId: GOOGLE_IOS_STANDALONE_CLIENT_ID,
        scopes: ["profile", "email"]
      });
      if (result.type === "success") {
       //do stuff
      }else {
        //do other stuff
     }

```

Until SDK 31, everything worked fine. Any help is appreciated.

**Comment by cruzach** [comment] 2019-06-27 15:19
duplicate of [4655](https://github.com/expo/expo/issues/4655)

relevant [PR](https://github.com/expo/expo/pull/4671)

**Closed by cruzach** 2019-06-27 15:19 UTC
Labels: bug
