### ISSUE TITLE
Upgrade lottie-react-native

### ISSUE THREAD

**Issue by dmi3y** [expo/expo#5812] opened 2019-09-30 18:46 UTC
### Environment

```
Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @ant-design/react-native: ^3.1.15 => 3.1.15
      @types/react: ^16.8 => 16.9.2
      @types/react-native: ^0.60.8 => 0.60.8
      expo: ^34.0.3 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.0 => 4.0.0
```

iOS

https://lottiefiles.com/7490-blink-animation
<img width="978" alt="Screen Shot 2019-09-28 at 10 15 38 PM" src="https://user-images.githubusercontent.com/1277279/65826628-8c863980-e23d-11e9-8bd4-d00fd15cbe8c.png">

**VS**

https://snack.expo.io/@dmi3y/4f6484
<img width="498" alt="Screen Shot 2019-09-28 at 10 15 02 PM" src="https://user-images.githubusercontent.com/1277279/65826626-7bd5c380-e23d-11e9-8be7-8a3e0bc88b17.png">

**Expected behavior:**
Colors are the same

**Actual behavior:**
Colors different

### Versions
Lottie: 2.5.0

Also opened bug report on Lottie react-native side https://github.com/react-native-community/lottie-react-native/issues/567

Thanks!

**Comment by cruzach** [comment] 2019-09-30 19:58
You can narrow down whether or not this is an Expo-specific issue by starting a bare react-native project and implementing the same code

**Comment by dmi3y** [comment] 2019-10-04 01:26
Seems like it is Lottie itself, tested it on minimal react native project [repo](https://github.com/dmi3y/lottieTest) and seeing same behavior.

![Screen Shot 2019-10-03 at 6 17 00 PM](https://user-images.githubusercontent.com/1277279/66174719-4fd68b80-e60b-11e9-8d76-877ba6887f1b.png)

**Comment by dmi3y** [comment] 2019-10-04 17:33
Okay I'm taking it back, just did proper lottie upgrade to v3 and it looks like it is fine now. Same repo [link](https://github.com/dmi3y/lottieTest). Thanks.

**Comment by dmi3y** [comment] 2019-10-10 18:10
Tagging @tsaiDavid and @alexofthewu for visibility

**Comment by cruzach** [comment] 2019-10-11 15:56
Duplicate of #5559, so closing this and we'll keep track of it in that issue

**Closed by cruzach** 2019-10-11 15:56 UTC
Labels: Lottie, bug, status: needs more info
