### ISSUE TITLE
Expo.Google.logInAsync fails with DEVELOPER_ERROR  (detached, standalone app)

### ISSUE THREAD

**Issue by s7dhansh** [expo/expo#440] opened 2017-07-31 08:27 UTC
I have followed https://docs.expo.io/versions/v19.0.0/sdk/google.html to the letter to get my google signin working but it fails with this error:
```
[exp] [Error: Status{statusCode=DEVELOPER_ERROR, resolution=null}]
```
Google tells me that the SHA1 configuration is wrong, but I have cross checked everything at least 10 times.

I was able to get signIn working with `behavior: 'web'` (thanks to https://github.com/expo/expo/issues/203#issuecomment-311264794) but still, I would like the native login.
Any help?

**Comment by lllymok** [comment] 2017-09-01 11:12
Hello I have the same problem

**Comment by janicduplessis** [comment] 2017-09-20 02:14
This should be fixed in sdk 21

**Closed** 2017-09-20 02:14 UTC
Labels: project: client-android, project: sdk

**Comment by apiel** [comment] 2017-10-08 21:06
I updated to expo 21 and still get the issue :-/

**Comment by janicduplessis** [comment] 2017-10-12 18:30
It's possible that the error is happening because something is not properly configured, the error returned from the google sdk is not useful so it is hard to tell what is going on.

**Comment by apiel** [comment] 2017-10-12 18:34
Sorry I forgot to mention that manage to make it with https://docs.expo.io/versions/latest/sdk/google.html#deploying-to-a-standalone-app-on-android

I just didn't seen it...

**Comment by janicduplessis** [comment] 2017-10-12 21:06
@apiel Awesome!

**Comment by apiel** [comment] 2017-10-13 17:12
Hmm after updating my code, it's stopped to work. So I wonder if I have to make all the manipulation again. 
The problem is that the error is not very clear. I can open the google sign in form, then I select my account and then I get an error :-/
![image](https://user-images.githubusercontent.com/5873198/31557735-4a5ca656-b04a-11e7-863d-736247316295.png)

Does anyone know what does this means?

**Comment by nolangarrido** [comment] 2017-10-29 21:13
If you enabled Google Play App Signing and are seeing this error, make sure your Google credentials reflect the re-signed artifact created by Google and not the build created by Expo.

To get the proper credentials into Google in this case, you'll have to upload your Expo build into Google Play, then download the artifact after Google re-signs the build, then grab the certificate hash from the new APK file and update your Google keys and app.json file with the new hash.

Your re-signed artifact file will be in the Google Play console under Release Management -> Artifact Library.

**Comment by apiel** [comment] 2017-10-30 20:08
@nolangarrido thx for the advice but right now I am not using google play. I simply upload the apk on my mobile directly...
