### ISSUE TITLE
Expokit - Android TypeError: undefined is not an object (evaluating 'StripeModule.init')

### ISSUE THREAD

**Issue by danijel** [expo/expo#3597] opened 2019-02-27 12:19 UTC
### Environment
Expo CLI 2.11.3 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.6.2 - /usr/local/bin/zsh
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.5
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: 2.17.0 => 2.17.0
    npmGlobalPackages:
      expo-cli: 2.11.3

This is ejected ExpoKit app, everything works fine on ios, on android it crashes when I try to open my payments screen

### Steps to Reproduce

1. eject to expokit
2. put Stripe.setOptionsAsync call in componentWillMount and try to open that screen in android simulator

### Expected Behavior

Expect it to open credit card form like it does on ios, like it worked with sdk 30,
When updating to sdk 32 from 30 I started with freshly ejected app, to which I installed payments pod and copied my code.
IOS just works, android I can't get to work no matter what I do,
I tried changing build.gradle and settings.gradle like in the docs,
I even tried adding keepclass lines to proguard file, no luck

### Actual Behavior
Throws error 
TypeError: TypeError: TypeError: undefined is not an object (evaluating 'StripeModule.init')
triggered from 
- node_modules/expo-payments-stripe/src/Stripe.js:19:24 in setOptionsAsync

<img width="303" alt="screen shot 2019-02-27 at 13 07 13" src="https://user-images.githubusercontent.com/148387/53489685-1563a980-3a92-11e9-8fb4-be41b261d8ad.png">

**Comment by danijel** [comment] 2019-02-28 13:02
@cruzach @Szymon20000 if it helps I created repo with examples from
https://github.com/expo/expo/tree/master/packages/expo-payments-stripe/examples/with-expokit

only did expo init, expo eject, took the sources from there and ran with android studio
Opening card form screen throws error.

this repo url is https://github.com/danijel/stripe-test

let me know if I can help in any way

**Comment by peniqliotuv** [comment] 2019-03-02 21:39
You need to add the ExPayments STripe pod

**Comment by danijel** [comment] 2019-03-04 07:58
@peniqliotuv ios works, problem is android

**Comment by Szymon20000** [comment] 2019-03-06 14:10
Currently using expo-payments-stripe in ejected apps is not as seamless as It should be. I will work on that. Please, use the following steps in order to make your app work. 

1. Add expo-payments-stripe to `app/build.gradle`.(
 ```groovy 
   api 'host.exp.exponent:expo-task-manager-interface:1.0.0'
  +api 'host.exp.exponent:expo-payments-stripe:2.0.0' (without "+" of course )
 ```
2. Import `StripePackage` into `MainApplication.java`
  ``` java
     import expo.modules.payments.stripe.StripePackage;
 ```
3. Add `StripePackage` to `MainApplication.java`. 
  ``` java
      public List<Package> getExpoPackages() {
        return Arrays.<Package>asList( 
          ...
          new StripePackage()
       );
     }
  ```

**Comment by danijel** [comment] 2019-03-06 16:03
@Szymon20000 Thanks, this does the trick, I confirmed with stripe-test repo from above, in my app I switched to tipsi-stripe in the meantime, but I will switch back, thanks again.
Not sure should I close this issue or wait for next sdk.

**Comment by omorhefere** [comment] 2019-03-31 11:58
Hey does anyone know how to solve this problem on IOS?

I get the error using both expo-payments-stripe and tips-stripe

**Comment by danijel** [comment] 2019-04-01 08:34
@omorhefere I never had any issues on IOS, this was only on android, on IOS you need to eject and install pod, following 
https://docs.expo.io/versions/latest/sdk/payments/#adding-the-payments-module-on-ios
always worked without issues.

**Comment by lightninglu10** [comment] 2019-04-05 23:51
@Szymon20000 Can you guys add these instructions to the readme? They're not in the readme which makes it hard to track down what the issue is.

**Comment by lightninglu10** [comment] 2019-04-09 00:57
@danijel are you sure @Szymon20000 's tips work? Tried to use this but now can't build the app because of https://github.com/expo/expo/issues/3933

**Comment by danijel** [comment] 2019-04-09 06:56
@lightninglu10 yes, verified with the stripe-test repo above and I have an app on play store running with this fix

**Comment by lightninglu10** [comment] 2019-04-09 18:15
@danijel which version of expo-payments-stripe are you running? is it 3.0.0 or 4.0.0?

**Comment by danijel** [comment] 2019-04-09 19:13
@lightninglu10 I did not run into that error,

expo-payments-stripe is acutally 2.0.0

https://github.com/danijel/stripe-test/blob/f78ed5fcaf7fe367cd5e26732d1ee9e01b86d69d/yarn.lock#L2277

I actually did not add it to package.json, it's what came with expo

https://github.com/danijel/stripe-test/blob/master/package.json

Hope this helps

**Comment by tlmader** [comment] 2019-07-18 23:14
Using ExpoKit and with SDK 33.

I added the following to `build.gradle`
```
  api 'host.exp.exponent:expo-payments-stripe:5.0.1'
```

But when adding `StripePackage` to `getPackages`, I get the following error:
![image](https://user-images.githubusercontent.com/2181467/61498132-ac6cc780-a987-11e9-9c86-7fc4d34a65d7.png)

Any ideas?

**Comment by tlmader** [comment] 2019-07-18 23:32
@Szymon20000 I'm using ExpoKit and SDK 33.

I tried adding `StripePackage` to `getExpoPackages`:

```
  public List<Package> getExpoPackages() {
    List<Package> packages = new BasePackageList().getPackageList();
    packages.add(new StripePackage()); // Add Stripe package
    return packages;
  }
```

However, this causes the app to crash on start.

Any ideas?

**Comment by lightninglu10** [comment] 2019-07-25 21:20
@tlmader have you resolved the issue?

I'm getting an error still trying to upgrade to SDK 33 and using `"expo-payments-stripe": "^5.0.1",`

**Comment by yegorius** [comment] 2019-07-27 22:05
Try "expo-payments-stripe": "^6.0.0", version 5.0.0 lacked unimodule.json file.

**Comment by isthisshivam** [comment] 2020-06-04 07:23
> 
> 
> @peniqliotuv ios works, problem is android

Can you please tell me the steps to workout in  IOS?

**Comment by LivanDiaz** [comment] 2020-06-28 05:24
----TypeError: undefines is not an object (evaluating 'StripeModule.init') ---- im getting the same error in IOS ... using expo-payments-stripe  "version": "8.1.0" ...

**Comment by LivanDiaz** [comment] 2020-09-04 06:05
@danijel i have same issue in IOS ... any solution would be of great help ..

**Comment by LivanDiaz** [comment] 2020-09-07 16:24
@isthisshivam, @peniqliotuv ... hello, for me it works with Android but it is throwing me that same error with ios ... any solution ??? It would be of great help .. thanks ...

**Comment by isthisshivam** [comment] 2020-09-07 17:37
Yes this is the issue just becasue of the initialisation of stripe module
is not working correctly and you just need to do one thing  create a build
with xcode once after that stripe module installed and work perfectly
Thanks

**Comment by LivanDiaz** [comment] 2020-09-07 17:45
@isthisshivam thanks for answering, excuse me for the ignorance ... could you be a little more specific or give me the steps to follow to achieve this ...

**Comment by isthisshivam** [comment] 2020-09-08 03:58
First you open your iOS directory with xcode
Second build you project with xcode
Install a build from xcode  and use it for the development
If there are any query please let me know I will available
Thanks

**Comment by LivanDiaz** [comment] 2020-09-09 19:07
@isthisshivam hi ... it worked but ... I created a small project I ran it with Xcode while I edited my code with VSCode and it worked perfectly, but when I run my project from the VSCode console it keeps giving me the same error ... it is as if from Xcode the linking of the modules will work fine but not outside of it ...

**Comment by isthisshivam** [comment] 2020-09-09 19:18
Yes it will work like that you need to work on same manner

**Comment by LivanDiaz** [comment] 2020-09-09 19:28
@isthisshivam  So there is no other way that I can work without using the XCode to start my project ??? It is complicated because to do all this I had to mount a MacOS virtual machine ... currently the PC I have uses Windows ...

**Comment by LivanDiaz** [comment] 2020-09-09 20:39
@isthisshivam I will find a way ... I am very grateful for your time and for your help ...

**Comment by isthisshivam** [comment] 2020-09-10 05:15
🙏

**Comment by cruzach** [comment] 2021-07-07 14:27
Hi! Since the `expo-payments-stripe` module was deprecated with the release of SDK 42, I'm going to close this issue.

We collaborated with the team at Stripe to make the `@stripe/stripe-react-native` library work seamlessly in Expo projects, so we recommend you use that library instead. [Learn more in the API reference](https://docs.expo.io/versions/latest/sdk/stripe/), and check out this [excellent YouTube video that walks through integrating Stripe in your Expo app](https://www.youtube.com/watch?v=DZlAET7Tgx4&ab_channel=UnsureProgrammer). Thanks!

**Closed by cruzach** 2021-07-07 14:27 UTC
Labels: Android, Payments
