### ISSUE TITLE
path is undefined here. making app:createReleaseExpoManifest FAILED

### ISSUE THREAD

**Issue by nebmesemaou** [expo/expo#8373] opened 2020-05-20 01:36 UTC
https://github.com/expo/expo/blob/5c79e370e5eaba71f3dbe7904c323e488fdf050d/packages/expo-updates/scripts/createManifest.js#L75

when runing react-native run-android --variant=release

OS = Windows 10
node -v = v12.16.3
npm -v = 6.14.5
expo -V = 3.20.9

"dependencies": {
    "expo": "37.0.11",
    "expo-notifications": "~0.1.1",
    "expo-splash-screen": "^0.2.3",
    "expo-task-manager": "~8.1.0",
    "expo-updates": "0.2.3",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "0.61.4",
    "react-native-device-info": "5.5.8",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-screens": "~2.2.0",
    "react-native-unimodules": "0.9.1",
    "react-native-web": "^0.11.7"
  },

**Comment by byCedric** [comment] 2020-05-26 12:16
Hi @nebmesemaou! Thanks for the issue report, we will investigate this asap! (cc @esamelson)

**Comment by nebmesemaou** [comment] 2020-05-26 17:23
thx solved with expo-updates@0.2.5

**Comment by esamelson** [comment] 2020-05-26 18:06
Hi, this is a duplicate of https://github.com/expo/expo/issues/8377#issuecomment-633077241 which has been fixed! Closing this for now, please let us know if you continue to see issues on Windows.

**Closed by esamelson** 2020-05-26 18:06 UTC
Labels: Bare Workflow, OS: Windows, bug

**Comment by byCedric** [comment] 2020-05-26 19:40
Ah sorry @esamelson, I couldn't find the PR. Glad it's fixed! 😄
