### ISSUE TITLE
`Location.startLocationUpdatesAsync` results in NullPointerException

### ISSUE THREAD

**Issue by hanselsen** [expo/expo#8483] opened 2020-05-26 06:19 UTC
### Environment
```
Expo CLI 3.20.9 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.3.2 - C:\Users\hans\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ^37.0.12 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      react-native-web: ~0.11.7 => 0.11.7
```
Targeting Android 7, 8, 10

### Steps to Reproduce

I have a sticky notification where I notify the user that his position is being monitored. This notification is suddenly gone. In Crashlytics, all I can find is a one specific crash.

### Expected Behavior

To start the service and then have the background service run as long as the app remains active.

### Actual Behavior

After about 15-60 minutes, the app crashes (or at least the sticky notification is gone).
And I have this stack trace in Crashlytics:

```
Fatal Exception: java.lang.RuntimeException: Unable to start service expo.modules.location.services.LocationTaskService@97ff6c3 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4222)
       at android.app.ActivityThread.access$2100(ActivityThread.java:231)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1984)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

### Reproducible Demo

You can view the code I used in the `backgroundTasks.js` [here](https://snack.expo.io/UeogW2ZjF)

**Comment by hanselsen** [comment] 2020-05-29 14:05
Hey guys. Any news on this? This is really annoying and I failed in finding what it is or how to fix it.

**Comment by byCedric** [comment] 2020-06-08 11:15
Hi @hanselsen! It looks like this might be caused by the [`onStartCommand` getting a `null`](https://www.hellsoft.se/how-to-service-on-android---part-2/#onstartcommand-) for intent. ([on this line](https://github.com/expo/expo/blob/master/packages/expo-location/android/src/main/java/expo/modules/location/services/LocationTaskService.java#L45)). I'm not 100% sure how we can handle the channel ID without intent. (cc @tsapeta)

**Comment by hanselsen** [comment] 2020-06-17 06:47
After some vigorous testing, your suggestion seems to be the solution @byCedric .
Is this something that will be included in a near Expo version?

**Comment by superyarik** [comment] 2020-07-03 09:09
looks like i facing same problem - SDK38, when i use phone(galaxy S7) in another apps i receive message about my app closing. In android studio logs i see this:

`07-03 00:16:26.769 6239-6239/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.hubex.engineer, PID: 6239
    java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke interface method 'void l.d.a.c.a(android.content.Context, l.d.a.c$b, java.lang.Runnable, l.d.b.l.e)' on a null object reference
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void l.d.a.c.a(android.content.Context, l.d.a.c$b, java.lang.Runnable, l.d.b.l.e)' on a null object reference
        at expo.modules.taskManager.TaskService.executeTask(TaskService.java:17)
        at expo.modules.taskManager.Task.execute(Task.java:2)
        at expo.modules.location.taskConsumers.LocationTaskConsumer.executeTaskWithLocationBundles(LocationTaskConsumer.java:4)
        at expo.modules.location.taskConsumers.LocationTaskConsumer.didExecuteJob(LocationTaskConsumer.java:10)
        at expo.modules.taskManager.TaskService.handleJob(TaskService.java:7)
        at expo.modules.taskManager.TaskJobService.onStartJob(TaskJobService.java:3)
        at android.app.job.JobService$1.onStartJob(JobService.java:71)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) `

**Comment by roger-schaer** [comment] 2020-07-06 11:12
Hello,

I'm also facing the same issue, the app crashes when the app is "closed" by swiping after putting it into the background. I tried with the Expo client on an emulator (Pixel 4, Android 10) as well as on a real device, and also tried with a standalone APK, always with the same result:

```
FATAL EXCEPTION: main
    Process: host.exp.exponent, PID: 8998
    java.lang.RuntimeException: **Unable to start service abi38_0_0.expo.modules.location.services.LocationTaskService@4745321 with null**: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
        at android.app.ActivityThread.access$1800(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: **Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference**
```

I stripped down my code to simply do a "console.log" of the locations (basically the sample shown in the [docs](https://docs.expo.io/versions/latest/sdk/location/#task-parameters)), so I don't think the problem stems from my implementation.

Is there any fix planned for the near future or a work-around that doesn't require ejecting from Expo?

Thank you very much for your help!

**Comment by syedhaider03** [comment] 2020-07-13 08:55
I am using it in bare react native app with unimodules installed and experience the same issue, when the app is launched from killed state it works fine but when we try to use it in already running app it always gives the error and then crashes the app after some time and you will need to kill the app and start it again to start working.
![Screenshot_1594578786](https://user-images.githubusercontent.com/43629380/87285037-79b0cd00-c510-11ea-84ff-2a88321d8c0b.png)

**Comment by roger-schaer** [comment] 2020-07-16 14:10
Hello again,

I can now confirm that a similar problem also happens with the background GeoFencing feature, which either doesn't trigger or shows a similar error message as for the background location tracking. On iOS, both features worked perfectly so far.

It seems the problem could really be more deep and be related to the TaskManager, I've also seen issues/forum posts for the BackgroundFetch feature with similar error messages.

It would really be appreciated to have a feedback in terms of when a fix might be implemented, as my app is highly dependent on the background location tracking feature.

Thank you for your response!

**Comment by hnabbasi** [comment] 2020-07-21 22:35
My app is crashing after the location updates start. And it is a NPE,

```
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.PersistableBundle.unparcel()' on a null object reference
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8034)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.PersistableBundle.unparcel()' on a null object reference
        at android.os.BaseBundle.putAll(BaseBundle.java:542)
        at expo.modules.location.taskConsumers.LocationTaskConsumer.didExecuteJob(LocationTaskConsumer.java:142)
        at expo.modules.taskManager.TaskService.handleJob(TaskService.java:331)
        at expo.modules.taskManager.TaskJobService.onStartJob(TaskJobService.java:13)
        at android.app.job.JobService$1.onStartJob(JobService.java:62)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8034) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076) 
```
and the problem seems to be here,  

https://github.com/expo/expo/blob/8baac603e92f5e63eb046d6898c968f8e4d2118e/packages/expo-location/android/src/main/java/expo/modules/location/taskConsumers/LocationTaskConsumer.java#L142

**Comment by hnabbasi** [comment] 2020-07-21 23:38
I am on 8.2.1 and `onStartCommand` does return `START_REDELIVER_INTENT` in the task service. But issue persists. To workaround it, I had to make 2 fixes,

Swallow exception for a bad/empty bundle in LocationTaskConsumer.java
```java
for (PersistableBundle persistableLocationBundle : data) {
  try {
    Bundle locationBundle = new Bundle();
    Bundle coordsBundle = new Bundle();

    if (persistableLocationBundle != null) {
      coordsBundle.putAll(persistableLocationBundle.getPersistableBundle("coords"));
      locationBundle.putAll(persistableLocationBundle);
      locationBundle.putBundle("coords", coordsBundle);

      locationBundles.add(locationBundle);
    }
  } catch (Exception e) {
    continue;
  }
}
```
Also, there is a sporadic error in GeofencingTaskConsumer.java, so checking for null takes care of it,
```java
// Get the geofences that were triggered. A single event can trigger multiple geofences.
List<Geofence> triggeringGeofences = event.getTriggeringGeofences();

if(triggeringGeofences == null) {
  return;
}

for (Geofence geofence : triggeringGeofences) { ... }
```
Though this is a workaround, and swallowing exceptions is almost always bad. 🤷‍♂️

**Comment by mitrosunay** [comment] 2020-08-13 06:09
Any Update ? still got the error and app is not working properly anymore. I think we need to unregister the task when the app is killed. however it s not possible to listen event killed where there is no js dev working when the app is killed. Looking for a solution...

**Comment by superyarik** [comment] 2020-08-13 09:09
as for us - we disable this functionality on android, waiting this issue fix...

**Comment by hnabbasi** [comment] 2020-08-13 13:22
We dropped expo location all together and built native implementation for iOS and Android. Seems like the library is not ready for Production quite yet.

**Comment by guilhermepaula** [comment] 2020-08-18 15:21
Does this [release](https://github.com/expo/expo/blob/master/packages/expo-location/CHANGELOG.md#830--2020-07-16) has any relation with this issue?

**Comment by andkom** [comment] 2020-09-14 08:56
try this patch

```
@@ -42,13 +51,17 @@ public class LocationTaskService extends Service {
   @Override
   @TargetApi(26)
   public int onStartCommand(Intent intent, int flags, int startId) {
-    Bundle extras = intent.getExtras();
+    if (intent != null) {
+      Bundle extras = intent.getExtras();
+
+      if (extras != null) {
+        mChannelId = extras.getString("appId") + ":" + extras.getString("taskName");
+      }
 
-    if (extras != null) {
-      mChannelId = extras.getString("appId") + ":" + extras.getString("taskName");
+      return START_STICKY;
     }
 
-    return START_STICKY;
+    return START_REDELIVER_INTENT;
   }
```

**Comment by Zanchee** [comment] 2020-09-25 14:51
Please move any future discussion of this issue to #9288 so that we can have it all in one place.

**Comment by jaxidian** [comment] 2020-09-29 22:15
Is it possible to somehow catch this exception to prevent the application from crashing when in managed mode? Or are we forced to either deal with the crashes or completely remove all dependencies on `startLocationUpdatesAsync`?

**Comment by Zanchee** [comment] 2020-09-29 23:50
@jaxidian please refer to #9288

**Comment by jaxidian** [comment] 2020-10-01 14:46
Hi @Zanchee and thanks for the response. I have read that entire thread and I was unable to find an answer to if this question there. And since comments are disabled there, I'm unable to ask this question there. Is there a better place for me to ask this question? I'm not looking for a work-around to the bug. I'm asking if it's possible to handle the exception to avoid an application crash - I'm hoping to just log the situation and having a degraded application experience when this bug hits, but to do that I need to catch the exception.

**Comment by Zanchee** [comment] 2020-10-01 15:01
The crash occurs in the native code (Java) This means  that nothing you can do in the managed flow will prevent it from crashing if this occurs. The only temporary solutions are to not use the service, or eject to a bare flow and fix it yourself. These steps are outlined in the "Update" section of the author's post in #9288 

Let me know if that helps 👍

**Comment by jaxidian** [comment] 2020-10-01 17:38
Yep, that's the answer I needed (nothing I can do). Thank you! :-)

**Comment by byCedric** [comment] 2020-10-19 18:41
This has been fixed in Expo Client `2.17.4`, thanks to everyone who helped and sorry for the long turnaround!

**Closed by byCedric** 2020-10-19 18:41 UTC
Labels: Android, Location, TaskManager, bug, ⭐️ Root Cause Known

**Comment by jaxidian** [comment] 2020-10-27 19:53
@byCedric I understand how this would help us with local debugged apps. How does this help us with standalone apps? Does the CLI or something else also have the fix in it?

Side note: I think this fixes/closes #9570

**Comment by Zanchee** [comment] 2020-10-27 20:01
@jaxidian if you rebuild your standalone app with the CI again, it will use the `2.17.4` version.

**Comment by Zanchee** [comment] 2020-10-27 20:01
Can confirm it worked, ass I rebuilt standalone apps this weekend and tested background location successfully.

**Comment by jaxidian** [comment] 2020-10-27 20:07
Thanks. We'll proceed with that. Do you know if SDK v39 is required, or does this fix it also for 38?

**Comment by Zanchee** [comment] 2020-10-27 20:11
@jaxidian I believe there were additional fixes that were made in 39 to accommodate this, so 39 would be the safest bet.

**Comment by superyarik** [comment] 2020-10-28 17:50
@Zanchee but 2.17.4 is the version on expo client, how it includes in builded standalone app?

**Comment by Zanchee** [comment] 2020-10-28 17:52
@superyarik rebuild the standalone app and it will use the same version that the expo client app is using.

The standalone apps are nothing more than the expo client with all the debug stuff removed.
