### ISSUE TITLE
Upgading SDK 37 to 38 and build standalone app: on update of the app blank screen

### ISSUE THREAD

**Issue by heritiermwalila** [expo/expo#10134] opened 2020-09-10 07:42 UTC
## 🐛 Bug Report
Blank screen on users app after they update the app 
### Summary of Issue 

Hi, I tried to submit last time a build under expo SDK 37 Google play warning says I need to submit a level 29 API and I upgrade 37 to 38, and the issue was fixed. Now the main issue is for all existing users trying to update my new app with SDK 38 they got a blank screen

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Production SDK 38

### Steps to Reproduce
An existing app running under 37, upgrade the bundle to 38 and build and submit to google play store, once approved try to update the app and you will get a blank screen

### Expected Behavior vs Actual Behavior
No bank screen should show for a user trying to update the app

**Comment by cruzach** [comment] 2020-09-14 14:57
Hi, we need a reproducible demo in order to troubleshoot this issue. Since we haven't received other reports like this, it's probably not a bug with Expo, and instead a result of your code. (maybe a breaking change in SDK 38? be sure to check the [changelog](https://github.com/expo/expo/blob/master/CHANGELOG.md))

I'm going to close this for now, but if you can provide a reproducible demo or error message we'll be happy to investigate

**Closed by cruzach** 2020-09-14 14:57 UTC
Labels: Issue needs review
