### ISSUE TITLE
addNotificationResponseReceivedListener or useLastNotificationResponse is not firing when app is killed

### ISSUE THREAD

**Issue by Terspychore** [expo/expo#11933] opened 2021-02-12 20:39 UTC
**Summary**

Both **useLastNotificationResponse** hook and **addNotificationResponseReceivedListener** isn't firing when my expo app is killed. Working only in background and foreground. My expo-notifications package is up-to-date : "^0.9.0".

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

40.0.1

**Environment**

>   Expo CLI 4.1.6 environment info:
>     System:
>       OS: macOS 10.15.5
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
>       npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
>     IDEs:
>       Android Studio: 4.1 AI-201.8743.12.41.7042882
>       Xcode: 12.4/12D4e - /usr/bin/xcodebuild
>     npmPackages:
>       expo: ^40.0.1 => 40.0.1
>       react: 16.13.1 => 16.13.1
>       react-dom: 16.13.1 => 16.13.1
>       react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
>       react-native-web: ~0.13.12 => 0.13.18
>     npmGlobalPackages:
>       expo-cli: 4.1.6
>     Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

```
Notifications.setNotificationHandler({
	handleNotification: async () => ({
		shouldShowAlert: true,
		shouldPlaySound: false,
		shouldSetBadge: false,
	}),
});

Notifications.addNotificationResponseReceivedListener((response) => {
  console.log("received response!", response);
});

const handlePush = async ({ notification }) => {
	console.log("navigate");
}


export default function App() {


	const lastNotificationResponse = Notifications.useLastNotificationResponse();

	React.useEffect(() => {
		console.log(lastNotificationResponse);
					if (lastNotificationResponse && lastNotificationResponse.actionIdentifier === Notifications.DEFAULT_ACTION_IDENTIFIER) {
					handlePush(lastNotificationResponse);
			}
	}, [lastNotificationResponse]);
```

**Comment by artsnr1** [comment] 2021-02-19 09:43
Same here. It is triggering when both expo and app (inside expo) are killed (removed from recent apps) but it isn't triggering when only app is killed. And also not working in production. Terspychore did you find a workaround.

**Comment by ruiqbarbosa** [comment] 2021-02-19 19:46
I am facing the exactly same problem. When the application is killed the `addNotificationResponseReceivedListener` event is never triggered.

**Comment by jparksecurity** [comment] 2021-02-23 03:43
I have the same issue here.

I was able to fix this on Android by puting `Notifications.addNotificationResponseReceivedListener` inside of `useLayoutEffect`

I haven't tested it on a blank project, so IDK if it works only for my case.

**Comment by endronk** [comment] 2021-02-25 18:03
Same here, using:
- Android
- SDK 40
- expo-notifications 0.8.2 and 0.9.0

It also doesn't work on my project when using `Notifications.addNotificationResponseReceivedListener` inside of `useLayoutEffect`.

**Comment by endronk** [comment] 2021-02-25 18:36
I'm afraid that there won't be any solution for this on Android...

> The Android framework advises that apps that have been stopped (not in background) should not be started without explicit user interaction. FCM follows this recommendation and thus does not deliver messages to stopped apps. What I believe is happening on the devices in question is that apps that are swiped from the recents list are being stopped and thus not receiving messages from FCM.

https://github.com/firebase/quickstart-android/issues/41#issuecomment-239195950

> When an app is in a Force Stopped / Force Killed state most events including FCM messages for push notifications will not be received.

https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown#the-app-is-force-stopped

I tried killing my WhatsApp and yeah, I didn't receive any notification when someone sent me a message.

**Comment by Terspychore** [comment] 2021-02-28 20:15
> Same here (using v 0.9.0). It is triggering when both expo and app (inside expo) are killed (removed from recent apps) but it isn't triggering when only app is killed. And also not working in production. Terspychore did you find a workaround.

No workaround still. Working only when app is in background

**Comment by cruzach** [comment] 2021-03-03 20:38
@jparksecurity is correct- fixes for this have landed and are published for the bare workflow in `expo-notifications@0.10.0`, but if you are on the managed workflow you will need to wait until SDK 41 is released (we'll be opening up the SDK 41 beta within the next few weeks, so you don't have very long to wait)

I'll set a reminder to close this issue once the beta is released

**Closed** 2021-03-03 20:40 UTC
Labels: Notifications, pending closure

**Comment by islamouzou** [comment] 2021-03-04 09:26
> @jparksecurity is correct- fixes for this have landed and are published for the bare workflow in `expo-notifications@0.10.0`, but if you are on the managed workflow you will need to wait until SDK 41 is released (we'll be opening up the SDK 41 beta within the next few weeks, so you don't have very long to wait)

Will this include the fix for startLocationUpdatesAsync() ???

**Comment by cruzach** [comment] 2021-03-04 14:31
yes, you can view that issue and relevant PR for more details https://github.com/expo/expo/pull/11536

**Comment by ErikHasp** [comment] 2021-05-24 07:48
Can someone confirm this is working for them? I am still getting null on killed app with SDK 41.0.0 and `expo-notifications: 0.11.6` on android 11. Both on Expo Go and on .apk

**Comment by islamouzou** [comment] 2021-11-22 19:33
The issue is still there  SDK 42 (managed ), using the addNotificationResponseReceivedListener or the new hook even if it's the first line in App.js , same results , However sometimes it works .

**Comment by bondansebastian** [comment] 2022-02-16 12:29
I still experienced this issue on SDK 44 (managed)

**Comment by dfabreguette-ap** [comment] 2022-03-17 15:54
I also have same issue, using SDK 42 in bare workflow, and associated expo-notifications v0.12.3. Using addNotificationResponseReceivedListener, useLastNotificationResponse hook (or getLastNotificationResponseAsync equivalent) gives always the same response : null.
This is always returning null, not just when the app is killed. 
For some reasons, I've struggled upgrading SDK to 43 (due to unimodules migration). 
Will the 43 SDK ugprade solve the problem ?

**Comment by entiendoNull** [comment] 2022-05-06 06:48
On SDK43 I was unsuccessful to capture the event with `addNotificationResponseReceivedListener` on Android when the app was killed. I tried to register the listener in a `useLayoutEffect` instead of an `useEffect` but that changed nothing. 

Desperately I tried the `useLastNotificationResponse` out instead of manually register eventListeners and I was able to receive and handle notifications on Android when the app was in a "killed" state.

My original approach was to register `addNotificationReceivedListener` and `addNotificationResponseReceivedListener` for both iOS and Android. 
- On iOS I was able to capture and handle events on all app states (foreground, background and killed). 
- On Android I was able to capture and handle events in the foreground, background.

My final approach:
- `addNotificationReceivedListener` and `addNotificationResponseReceivedListener` was used to capture and handle events on iOS as that seemed to work perfectly.
-  `addNotificationReceivedListener` and `useLastNotificationResponse` was used to capture and handle events on Android.

It certainly seems like the `addNotificationResponseReceivedListener` problem is still not resolved.

**Comment by appsgenie** [comment] 2022-10-07 02:30
> On SDK43 I was unsuccessful to capture the event with `addNotificationResponseReceivedListener` on Android when the app was killed. I tried to register the listener in a `useLayoutEffect` instead of an `useEffect` but that changed nothing.
> 
> Desperately I tried the `useLastNotificationResponse` out instead of manually register eventListeners and I was able to receive and handle notifications on Android when the app was in a "killed" state.
> 
> My original approach was to register `addNotificationReceivedListener` and `addNotificationResponseReceivedListener` for both iOS and Android.
> 
> * On iOS I was able to capture and handle events on all app states (foreground, background and killed).
> * On Android I was able to capture and handle events in the foreground, background.
> 
> My final approach:
> 
> * `addNotificationReceivedListener` and `addNotificationResponseReceivedListener` was used to capture and handle events on iOS as that seemed to work perfectly.
> * `addNotificationReceivedListener` and `useLastNotificationResponse` was used to capture and handle events on Android.
> 
> It certainly seems like the `addNotificationResponseReceivedListener` problem is still not resolved.

How did you use `useLastNotificationResponse`? Was it in same place as `addNotificationReceivedListener` for Android? And do you know how to get that working with class components?

**Comment by chen-rn** [comment] 2023-03-12 21:33
> I still experienced this issue on SDK 44 (managed)

Were you able to fix this? Can someone confirm if this is fixed March 2023?

**Comment by berataras** [comment] 2023-09-02 14:32
September 2023 and still not working... When will it be resolved?

**Comment by Louay17** [comment] 2023-09-08 12:26
> > I still experienced this issue on SDK 44 (managed)
> 
> Were you able to fix this? Can someone confirm if this is fixed March 2023?

I confirm its working!
@berataras @chen-rn  make sure you are calling `addNotificationResponseRecievedListener`  early in your app’s startup as @cruzach mentioned here [https://forums.expo.dev/t/push-notification-doesnt-open-specific-screen-when-app-is-killed-works-only-in-foreground-and-background/53890/2](url)

**Comment by dmrugalski** [comment] 2023-10-19 11:40
For me solution above didn't want to work, but I solve that problem in other way.

Thats my response from different [thread](https://github.com/expo/expo/issues/14078#issuecomment-1770380889).

> > still an issue on Android even with initializing addNotificationResponseReceivedListener before any other react code
> 
> I believe it's not the case. I struggled with that for a long time but looks like I found a solution that work in my case. To solve my problem I use getLastNotificationResponseAsync() not in main file (App.tsx) but in one of its child so after loading few libs and initialization some of the code. To be clear,
> 
> I use it in getInitialURL() function (of course only for android, iOS works OK for me.
> 
> ```
> const linking = {
>   prefixes: [...],
>   async getInitialURL() {
>     if (Platform.OS === 'android') {
>       const lastNotificationResponse = Notifications.getLastNotificationResponseAsync();
>       lastNotificationResponse.then(response => {
>         if (!!response) {
>           storeNotificationFromStartup(response.notification);
>         }
>       })
>     }
>   }
> }
> <NavigationContainer ref={navigationRef}
>                      linking={linking}>
>   [...]
> </NavigationContainer>
> ```
> 
> in `storeNotificationFromStartup` I save it into AsyncStorage and read that after API calls and initialization my app with data from backend.

**Comment by AnhTP-Corize** [comment] 2024-01-20 09:29
@dmrugalski seems it's not working for me. When I kill app and then tap into noti, lastNotificationReponse returns null

**Comment by berataras** [comment] 2024-02-19 10:30
this is my last way and it's worked for me.

```
"expo": "^49.0.0",
"expo-notifications": "~0.20.1",
```
**src/app/_layout.tsx:**
```
function StackScreens() {
    import { useLastNotificationResponse } from 'expo-notifications';
    const lastNotificationResponse = useLastNotificationResponse();
  
    useEffect(() => {
      if (lastNotificationResponse) {
        let data = lastNotificationResponse?.notification?.request?.content?.data;
  
        if (data) {
          //code
        }
      }
    }, [lastNotificationResponse]);
    
    return (
        <Stack
          initialRouteName="(tabs)"
        >
       ...
    )
}
```
