### ISSUE TITLE
Admob "AdMobBanner" requesting multiple times to server

### ISSUE THREAD

**Issue by ahmadeyamin** [expo/expo#12114] opened 2021-03-05 09:17 UTC
### Summary

Admob "AdMobBanner" requesting multiple times to server event "onAdViewDidReceiveAd" maybe for this reason my account got AdsLimition.

This Problem only happens with AdMobBanner. PublisherBanner is sending 1 request to the server.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40.0.1

### Environment

  Expo CLI 4.2.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 15.7.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.4.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@akashbudhia/admob-android-multiple-fill-request-bug

Expo AdMob package gives an "AdMobBanner" component to show banner ads. It's working fine but the problem is it's sending 2-5 requests to show a single Ad and rerender after screen rotation and keyboard open, close. 
It reduces Impression, Show Rate significantly, and increases Requests 3-5 times. This is very bad for any AdMob account

"PublisherBanner" doesn't have any issue like this. 
![image](https://user-images.githubusercontent.com/29674341/110093712-38ce3700-7dc5-11eb-8993-e6b7a235c081.png)

AdMob disabled my account for this reason maybe.

if AdMob not work then we have to stop our app development :(

**Comment by mikejsdev** [comment] 2021-03-07 09:22
I am having this exact same problem and it has killed my app in production. 

Someone raised this issue back in November and nothing is being done about it and no one is even assigned to deal with it: https://github.com/expo/expo/issues/11046

If no one is planning to fix this does anyone at least know if there are alternatives that can be used with expo? As surly this effects all users, I don't see how any expo users can be using AdMob at the moment and therefore expo isn't an option for anyone who wants ads on their app.

**Comment by ahmadeyamin** [comment] 2021-03-07 09:27
Last night after 8-9 hours of work I successfully ejected my project from Expo managed. 

Now I'm using https://rnfirebase.io and it's working fine. Also, I'm missing the Expo easy development environment.

**Comment by mikejsdev** [comment] 2021-03-12 17:13
Thanks @ahmadeyamin , I have been unable to solve this too and so will have to eject my expo project. This is really annoying.

**Comment by youngminz** [comment] 2021-04-13 16:43
It seems to be linked to this issue. - https://github.com/sbugert/react-native-admob/issues/525

**Comment by mikejsdev** [comment] 2021-04-15 11:05
I have been hoping that Expo SDK version 41  would fix this issue as it updates the expo-admob package version. Howver, I can confirm that this issue remains and is exactly the same!!! 

@youngminz did you manage to make any progress on this? you mentioned in https://github.com/sbugert/react-native-admob/issues/525 that you might fork the package?

**Comment by youngminz** [comment] 2021-04-15 12:40
@mikejsdev I changed to PublisherBanner and distributed the app.  My app doesn't have a lot of traffic, so it's difficult to make an accurate judgment, but it seems to be able to receive AdMob ads normally, and ad revenue seems to be accumulating normally. The traffic is so low that it is difficult to determine if the show rate is normal, but it looks fine in my AdMob Console.  (SDK 40)

**Comment by mikejsdev** [comment] 2021-04-16 06:33
@youngminz thanks loads for this, it works for me too. I swapped over to PublisherBanner and released my app. I am still get ads through so I assume it's working, but like you my traffic is low so it's hard to tell. I Have no idea what the difference between AdMobBanner and PublisherBanner is, I'm just hoping they are interchangeable as clearly AdMobBanner  is unusable at the moment. Thanks again for finding and sharing the fix.

**Comment by cruzach** [comment] 2021-04-16 16:00
Looking into this, it seems like it's likely due to [this listener](https://github.com/expo/expo/blob/master/packages/expo-ads-admob/android/src/main/java/expo/modules/ads/admob/AdMobBannerView.java#L32-L38) we're adding in the AdMobBannerView, since that is triggering a new ad load each time

**Closed** 2021-04-20 14:35 UTC
Labels: needs review
