### ISSUE TITLE
ExpoKit: access getReactInstanceManager and getCurrentReactContext inside MainActivity results in NullPointerException

### ISSUE THREAD

**Issue by iagormoraes** [expo/expo#2861] opened 2018-11-29 21:03 UTC
I can't call for **getReactInstanceManager()** and **getCurrentReactContext()** inside my MainActivity.java file:

### Environment
Expo CLI 2.3.8 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.0 => 30.0.0
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
      react-navigation: 2.13.0 => 2.13.0
    npmGlobalPackages:
      expo-cli: 2.3.8

The project uses ExpoKit.

### Steps to Reproduce
Call this.getReactInstanceManager().getCurrentReactContext() inside MainActivity.java file from a expo project detached to ExpoKit.

(Write your steps here:)

1. detach any project to expokit
2. go to MainActivity.java file
3. try to get ReactInstanceManager getReactInstanceManager

### Expected Behavior

It should return the ReactInstanceManager reference and have access to the getCurrentReactContext method to be able to send native events for javascript side to listen to.

### Actual Behavior

It does not allow me to receive the context on first open in app, it crashes because there is no reference, it is null like the example: 

"NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.JavaScriptModule com.facebook.react.bridge.ReactContext.getJSModule(java.lang.Class)' on a null object reference"

### Reproducible Demo

Download a blank project from expo SDK 30, detach it and try for yourself.

**Comment by sjchmiela** [comment] 2018-11-30 14:35
Hey, @iagorm! If you just ejected from Expo SDK, `MainActivity` probably extends `DetachActivity`, right? If so, you shouldn't be able to call `getReactInstanceManager` method inside any `MainActivity` method, since there is no such method in any of the superclasses of `MainActivity`. `getReactInstanceManager` is defined in `ReactActivity`, which is used by plain React Native in its activity. To handle multiple React Native versions, Expo doesn't use `ReactActivity`, we use our own `ReactNativeActivity` and others instead.

If you need to access `ReactInstanceManager` from inside the activity, you'll need to use `mReactInstanceManager` instance variable of `MainActivity`. It's of class [`RNObject`](https://github.com/expo/expo/blob/master/android/expoview/src/main/java/host/exp/exponent/RNObject.java), which is a reflection-based abstraction over calling methods on unknown classes.

Try accessing the manager like this:
```java
if (mReactInstanceManager != null && mReactInstanceManager.isNotNull() && !mIsCrashed) {
    ReactInstanceManager manager = (ReactInstanceManager) mReactInstanceManager.get();
    // your code
}
```

Note this straightforward cast to `com.facebook.react.ReactInstanceManager` will only work in SDK30+, in previous versions you would need to cast the object to `abiXX_0_0.com.facebook.react.ReactInstanceManager` or call methods on the manager via `call()` methods on `RNObject`.

**Comment by iagorm** [comment] 2018-12-02 15:11
> Hey, @iagorm! If you just ejected from Expo SDK, `MainActivity` probably extends `DetachActivity`, right? If so, you shouldn't be able to call `getReactInstanceManager` method inside any `MainActivity` method, since there is no such method in any of the superclasses of `MainActivity`. `getReactInstanceManager` is defined in `ReactActivity`, which is used by plain React Native in its activity. To handle multiple React Native versions, Expo doesn't use `ReactActivity`, we use our own `ReactNativeActivity` and others instead.
> 
> If you need to access `ReactInstanceManager` from inside the activity, you'll need to use `mReactInstanceManager` instance variable of `MainActivity`. It's of class [`RNObject`](https://github.com/expo/expo/blob/master/android/expoview/src/main/java/host/exp/exponent/RNObject.java), which is a reflection-based abstraction over calling methods on unknown classes.
> 
> Try accessing the manager like this:
> 
> ```java
> if (mReactInstanceManager != null && mReactInstanceManager.isNotNull() && !mIsCrashed) {
>     ReactInstanceManager manager = (ReactInstanceManager) mReactInstanceManager.get();
>     // your code
> }
> ```
> 
> Note this straightforward cast to `com.facebook.react.ReactInstanceManager` will only work in SDK30+, in previous versions you would need to cast the object to `abiXX_0_0.com.facebook.react.ReactInstanceManager` or call methods on the manager via `call()` methods on `RNObject`.

Thanks for the reply @sjchmiela, the problem is, on every first install this instance context is null, maybe because of the draw over the app, and I should know if there is some way to start without a null value on first open.

**Comment by killerham** [comment] 2018-12-03 15:54
@iagorm were you able to figure this out? This is screwing up react-push-notifications for me

**Comment by sjchmiela** [comment] 2018-12-03 16:04
Where are you trying to access `mReactInstanceManager`? It may be not initialized yet 🤷‍♂️ . Could you please provide some sample of your `MainActivity` or what you're trying to achieve? 🙂

**Comment by killerham** [comment] 2018-12-03 16:07
When the app is closed, and the app receives a push notification, `react-push-notification` needs to access the manager but its null. You're right that it hasn't been initialized yet.

I have this in the main activity:

```
public ReactInstanceManager getReactInstanceManager(){
    return ((ReactInstanceManager)(Object)mReactInstanceManager.get());
  }
```

Is there a way to initialize it if it doesn't exist yet?

**Comment by iagorm** [comment] 2018-12-03 16:09
Sure, follow my file:

```JAVA
package host.exp.exponent;

import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.util.Log;
import android.widget.Toast;

import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.Arguments;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.bridge.WritableArray;
import com.facebook.react.bridge.WritableMap;
import com.facebook.react.bridge.WritableNativeArray;
import com.facebook.react.modules.core.DeviceEventManagerModule;
import com.jumio.MobileSDK;
import com.jumio.bam.BamCardInformation;
import com.jumio.bam.BamSDK;
import com.jumio.bam.enums.CreditCardType;
import com.jumio.core.exceptions.MissingPermissionException;
import com.jumio.dv.DocumentVerificationSDK;
import com.jumio.nv.NetverifyDocumentData;
import com.jumio.nv.NetverifySDK;
import com.jumio.nv.data.document.NVDocumentType;
import com.jumio.nv.data.document.NVMRZFormat;
import com.jumio.nv.enums.NVExtractionMethod;
import com.jumio.nv.enums.NVGender;
import com.jumio.react.JumioModuleBamCheckout;
import com.jumio.react.JumioModuleDocumentVerification;
import com.jumio.react.JumioModuleNetverify;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import expo.core.interfaces.Package;
import host.exp.exponent.experience.DetachActivity;
import host.exp.exponent.generated.DetachBuildConstants;

public class MainActivity extends DetachActivity {
    public ReactInstanceManager getReactInstanceManager() {
        return (ReactInstanceManager) mReactInstanceManager.get();
    }

    //expokit down here
    @Override
    public String publishedUrl() {. . .}

    @Override
    public String developmentUrl() {
        return DetachBuildConstants.DEVELOPMENT_URL;
    }

    @Override
    public List<String> sdkVersions() {
        return new ArrayList<>(Collections.singletonList("30.0.0"));
    }

    @Override
    public List<ReactPackage> reactPackages() {
        return ((MainApplication) getApplication()).getPackages();
    }

    @Override
    public List<Package> expoPackages() {
        // Here you can add your own packages.
        return super.expoPackages();
    }

    @Override
    public boolean isDebug() {
        return BuildConfig.DEBUG;
    }

    @Override
    public Bundle initialProps(Bundle expBundle) {
        // Add extra initialProps here
        return expBundle;
    }
    //JUMIO DOWN HERE
    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        boolean allGranted = true;
        for (int grantResult : grantResults) {
            if (grantResult != PackageManager.PERMISSION_GRANTED) {
                allGranted = false;
                break;
            }
        }

        if (allGranted) {
            if (requestCode == JumioModuleBamCheckout.PERMISSION_REQUEST_CODE_BAM) {
                startSdk(JumioModuleBamCheckout.bamSDK);
            } else if (requestCode == JumioModuleNetverify.PERMISSION_REQUEST_CODE_NETVERIFY) {
                startSdk(JumioModuleNetverify.netverifySDK);
            } else if (requestCode == JumioModuleDocumentVerification.PERMISSION_REQUEST_CODE_DOCUMENT_VERIFICATION) {
                startSdk(JumioModuleDocumentVerification.documentVerificationSDK);
            } else {
                super.onRequestPermissionsResult(requestCode, permissions, grantResults);
            }
        } else {
            Toast.makeText(this, "You need to grant all required permissions to start the Jumio SDK", Toast.LENGTH_LONG).show();
            super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        }
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);

        if (requestCode == BamSDK.REQUEST_CODE) {
            if (data == null) {
                return;
            }
            if (resultCode == Activity.RESULT_OK) {
                BamCardInformation cardInformation = data.getParcelableExtra(BamSDK.EXTRA_CARD_INFORMATION);

                WritableMap result = Arguments.createMap();
                if (cardInformation.getCardType() == CreditCardType.VISA) {
                    result.putString("cardType", "VISA");
                } else if (cardInformation.getCardType() == CreditCardType.MASTER_CARD) {
                    result.putString("cardType", "MASTER_CARD");
                } else if (cardInformation.getCardType() == CreditCardType.AMERICAN_EXPRESS) {
                    result.putString("cardType", "AMERICAN_EXPRESS");
                } else if (cardInformation.getCardType() == CreditCardType.CHINA_UNIONPAY) {
                    result.putString("cardType", "CHINA_UNIONPAY");
                } else if (cardInformation.getCardType() == CreditCardType.DINERS_CLUB) {
                    result.putString("cardType", "DINERS_CLUB");
                } else if (cardInformation.getCardType() == CreditCardType.DISCOVER) {
                    result.putString("cardType", "DISCOVER");
                } else if (cardInformation.getCardType() == CreditCardType.JCB) {
                    result.putString("cardType", "JCB");
                }
                result.putString("cardNumber", String.valueOf(cardInformation.getCardNumber()));
                result.putString("cardNumberGrouped", String.valueOf(cardInformation.getCardNumberGrouped()));
                result.putString("cardNumberMasked", String.valueOf(cardInformation.getCardNumberMasked()));
                result.putString("cardExpiryMonth", String.valueOf(cardInformation.getCardExpiryDateMonth()));
                result.putString("cardExpiryYear", String.valueOf(cardInformation.getCardExpiryDateYear()));
                result.putString("cardExpiryDate", String.valueOf(cardInformation.getCardExpiryDate()));
                result.putString("cardCVV", String.valueOf(cardInformation.getCardCvvCode()));
                result.putString("cardHolderName", String.valueOf(cardInformation.getCardHolderName()));
                result.putString("cardSortCode", String.valueOf(cardInformation.getCardSortCode()));
                result.putString("cardAccountNumber", String.valueOf(cardInformation.getCardAccountNumber()));
                result.putBoolean("cardSortCodeValid", cardInformation.isCardSortCodeValid());
                result.putBoolean("cardAccountNumberValid", cardInformation.isCardAccountNumberValid());

                WritableArray writableArray = new WritableNativeArray();
                ArrayList<String> scanReferenceList = data.getStringArrayListExtra(BamSDK.EXTRA_SCAN_ATTEMPTS);
                if (scanReferenceList != null && scanReferenceList.size() > 0){
                    for (int i = scanReferenceList.size() - 1; i >= 0; i--){
                        writableArray.pushString(scanReferenceList.get(i));
                    }
                }
                result.putArray("scanReferences", writableArray);

                sendEvent(this.getReactInstanceManager().getCurrentReactContext(), "EventCardInformation", result);
                cardInformation.clear();
            } else if (resultCode == Activity.RESULT_CANCELED) {
                String errorMessage = data.getStringExtra(BamSDK.EXTRA_ERROR_MESSAGE);
                String errorCode = data.getStringExtra(BamSDK.EXTRA_ERROR_CODE);

                WritableArray writableArray = new WritableNativeArray();
                ArrayList<String> scanReferenceList = data.getStringArrayListExtra(BamSDK.EXTRA_SCAN_ATTEMPTS);
                if (scanReferenceList != null && scanReferenceList.size() > 0){
                    for (int i = scanReferenceList.size() - 1; i >= 0; i--){
                        writableArray.pushString(scanReferenceList.get(i));
                    }
                }
                sendErrorObjectWithArray(errorCode, errorMessage, writableArray);
            }
            if(JumioModuleBamCheckout.bamSDK != null){
                JumioModuleBamCheckout.bamSDK.destroy();
            }
        } else if (requestCode == NetverifySDK.REQUEST_CODE) {
            if (data == null) {
                return;
            }
            String scanReference = data.getStringExtra(NetverifySDK.EXTRA_SCAN_REFERENCE) != null ? data.getStringExtra(NetverifySDK.EXTRA_SCAN_REFERENCE) : "";

            if (resultCode == Activity.RESULT_OK) {
                NetverifyDocumentData documentData = data.getParcelableExtra(NetverifySDK.EXTRA_SCAN_DATA);

                WritableMap result = Arguments.createMap();
                result.putString("selectedCountry", documentData.getSelectedCountry());
                if (documentData.getSelectedDocumentType() == NVDocumentType.PASSPORT) {
                    result.putString("selectedDocumentType", "PASSPORT");
                } else if (documentData.getSelectedDocumentType() == NVDocumentType.DRIVER_LICENSE) {
                    result.putString("selectedDocumentType", "DRIVER_LICENSE");
                } else if (documentData.getSelectedDocumentType() == NVDocumentType.IDENTITY_CARD) {
                    result.putString("selectedDocumentType", "IDENTITY_CARD");
                } else if (documentData.getSelectedDocumentType() == NVDocumentType.VISA) {
                    result.putString("selectedDocumentType", "VISA");
                }
                result.putString("idNumber", documentData.getIdNumber());
                result.putString("personalNumber", documentData.getPersonalNumber());
                result.putString("issuingDate", documentData.getIssuingDate() != null ? documentData.getIssuingDate().toString() : "");
                result.putString("expiryDate", documentData.getExpiryDate() != null ? documentData.getExpiryDate().toString() : "");
                result.putString("issuingCountry", documentData.getIssuingCountry());
                result.putString("lastName", documentData.getLastName());
                result.putString("firstName", documentData.getFirstName());
                result.putString("dob", documentData.getDob() != null ? documentData.getDob().toString() : ""); // test format
                if (documentData.getGender() == NVGender.M) {
                    result.putString("gender", "m");
                } else if (documentData.getGender() == NVGender.F) {
                    result.putString("gender", "f");
                } else if (documentData.getGender() == NVGender.X) {
                    result.putString("gender", "x");
                }
                result.putString("originatingCountry", documentData.getOriginatingCountry());
                result.putString("addressLine", documentData.getAddressLine());
                result.putString("city", documentData.getCity());
                result.putString("subdivision", documentData.getSubdivision());
                result.putString("postCode", documentData.getPostCode());
                result.putString("optionalData1", documentData.getOptionalData1());
                result.putString("optionalData2", documentData.getOptionalData2());
                result.putString("placeOfBirth", documentData.getPlaceOfBirth());
                if (documentData.getExtractionMethod() == NVExtractionMethod.MRZ) {
                    result.putString("extractionMethod", "MRZ");
                } else if (documentData.getExtractionMethod() == NVExtractionMethod.OCR) {
                    result.putString("extractionMethod", "OCR");
                } else if (documentData.getExtractionMethod() == NVExtractionMethod.BARCODE) {
                    result.putString("extractionMethod", "BARCODE");
                } else if (documentData.getExtractionMethod() == NVExtractionMethod.BARCODE_OCR) {
                    result.putString("extractionMethod", "BARCODE_OCR");
                } else if (documentData.getExtractionMethod() == NVExtractionMethod.NONE) {
                    result.putString("extractionMethod", "NONE");
                }

                result.putString("scanReference", scanReference);

                //MRZ data if available
                if (documentData.getMrzData() != null) {
                    WritableMap mrzData = Arguments.createMap();
                    if (documentData.getMrzData().getFormat() == NVMRZFormat.MRP) {
                        mrzData.putString("format", "MRP");
                    } else if (documentData.getMrzData().getFormat() == NVMRZFormat.TD1) {
                        mrzData.putString("format", "TD1");
                    } else if (documentData.getMrzData().getFormat() == NVMRZFormat.TD2) {
                        mrzData.putString("format", "TD2");
                    } else if (documentData.getMrzData().getFormat() == NVMRZFormat.CNIS) {
                        mrzData.putString("format", "CNIS");
                    } else if (documentData.getMrzData().getFormat() == NVMRZFormat.MRV_A) {
                        mrzData.putString("format", "MRVA");
                    } else if (documentData.getMrzData().getFormat() == NVMRZFormat.MRV_B) {
                        mrzData.putString("format", "MRVB");
                    } else if (documentData.getMrzData().getFormat() == NVMRZFormat.Unknown) {
                        mrzData.putString("format", "UNKNOWN");
                    }
                    mrzData.putString("line1", documentData.getMrzData().getMrzLine1());
                    mrzData.putString("line2", documentData.getMrzData().getMrzLine2());
                    mrzData.putString("line3", documentData.getMrzData().getMrzLine3());
                    mrzData.putBoolean("idNumberValid", documentData.getMrzData().idNumberValid());
                    mrzData.putBoolean("dobValid", documentData.getMrzData().dobValid());
                    mrzData.putBoolean("expiryDateValid", documentData.getMrzData().expiryDateValid());
                    mrzData.putBoolean("personalNumberValid", documentData.getMrzData().personalNumberValid());
                    mrzData.putBoolean("compositeValid", documentData.getMrzData().compositeValid());
                    result.putMap("mrzData", mrzData);
                }

                // EMRTD data if available
                if (documentData.getEMRTDStatus() != null) {
                    result.putString("emrtdStatus", String.valueOf(documentData.getEMRTDStatus()));
                }

                sendEvent(this.getReactInstanceManager().getCurrentReactContext(), "EventDocumentData", result);
            } else if (resultCode == Activity.RESULT_CANCELED) {
                String errorMessage = data.getStringExtra(NetverifySDK.EXTRA_ERROR_MESSAGE);
                String errorCode = data.getStringExtra(NetverifySDK.EXTRA_ERROR_CODE);
                sendErrorObject(errorCode, errorMessage, scanReference);
            }
            if(JumioModuleNetverify.netverifySDK != null){
                JumioModuleNetverify.netverifySDK.destroy();
            }
        } else if (requestCode == DocumentVerificationSDK.REQUEST_CODE) {
            if (data == null) {
                return;
            }
            String scanReference = data.getStringExtra(DocumentVerificationSDK.EXTRA_SCAN_REFERENCE) != null ? data.getStringExtra(DocumentVerificationSDK.EXTRA_SCAN_REFERENCE) : "";

            if (resultCode == Activity.RESULT_OK) {
                WritableMap result = Arguments.createMap();
                result.putString("successMessage", "Document-Verification finished successfully.");
                result.putString("scanReference", scanReference);

                sendEvent(this.getReactInstanceManager().getCurrentReactContext(), "EventDocumentVerification", result);

            } else if (resultCode == Activity.RESULT_CANCELED) {
                String errorMessage = data.getStringExtra(DocumentVerificationSDK.EXTRA_ERROR_MESSAGE);
                String errorCode = data.getStringExtra(DocumentVerificationSDK.EXTRA_ERROR_CODE);
                sendErrorObject(errorCode, errorMessage, scanReference);
            }
            if(JumioModuleDocumentVerification.documentVerificationSDK != null){
                JumioModuleDocumentVerification.documentVerificationSDK.destroy();
            }
        } else {
            if(this.getReactInstanceManager() != null) {
                this.getReactInstanceManager().onActivityResult(this, requestCode, resultCode, data);
            }
        }
    }

    // Helper methods

    private void sendEvent(ReactContext reactContext, String eventName, WritableMap params) {
        if(reactContext != null) {
            reactContext.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class).emit(eventName, params);
        }
    }

    public void startSdk(MobileSDK sdk) {
        try {
            sdk.start();
        } catch (MissingPermissionException e) {
            showErrorMessage(e.getLocalizedMessage());
        }
    }

    private void sendErrorObject(String errorCode, String errorMsg, String scanReference) {
        WritableMap errorResult = Arguments.createMap();
        errorResult.putString("errorCode", errorCode != null ? errorCode : "");
        errorResult.putString("errorMessage", errorMsg != null ? errorMsg : "");
        errorResult.putString("scanReference", scanReference != null ? scanReference : "");
        sendEvent(this.getReactInstanceManager().getCurrentReactContext(), "EventError", errorResult);
    }

    private void sendErrorObjectWithArray(String errorCode, String errorMsg, WritableArray array) {
        WritableMap errorResult = Arguments.createMap();
        errorResult.putString("errorCode", errorCode != null ? errorCode : "");
        errorResult.putString("errorMessage", errorMsg != null ? errorMsg : "");
        if (array != null){
            errorResult.putArray("scanReferences", array);
        } else {
            errorResult.putString("scanReferences", "");
        }
        sendEvent(this.getReactInstanceManager().getCurrentReactContext(), "EventError", errorResult);
    }

    private void showErrorMessage(String msg) {
        Log.e("Error", msg);
        WritableMap errorResult = Arguments.createMap();
        errorResult.putString("errorMessage", msg != null ? msg : "");
        sendEvent(this.getReactInstanceManager().getCurrentReactContext(), "EventError", errorResult);
    }
}
```

**Comment by iagorm** [comment] 2018-12-03 16:13
> @iagorm were you able to figure this out? This is screwing up `react-push-notifications` for me

@killerham, unfortunately no, this is really sad to not have context in the sub classes of expokit, what I'm doing is to get ride of expokit and start to use pure react native from **react-native init**, which brought to me a lot of problems to integrate.

**Comment by killerham** [comment] 2018-12-03 16:13
@iagorm shucks, your setup doesn't really solve my issue. My issue is that the `getReactInstanceManager()` is always null when the app is not running, which breaks my push notification implementation :(

**Comment by iagorm** [comment] 2018-12-03 16:15
> @iagorm shucks, your setup doesn't really solve my issue. My issue is that the `getReactInstanceManager()` is always null when the app is not running, which breaks my push notification implementation :(

@killerham maybe you'll need to remove expokit too, I realize that for my use case, everytime I install the app and open, it crashes once, then open normally, but it is a horrible user experience.

**Comment by sjchmiela** [comment] 2018-12-03 16:30
1. Are we talking about [`react-native-push-notification`](https://github.com/zo0r/react-native-push-notification)? I don't see any additional setup needed to add to `MainActivity`, where do your instructions come from?
2. If you're trying to send an event to JS, you may need to use (I'm not sure):
    ```java
    KernelProvider.getInstance().addEventForExperience(
        mManifestUrl,
        new KernelConstants.ExperienceEvent(...)
    );
    ```
3. If you're trying to call `onActivityResult` on a React Context, just call it on `super`, it should call the underlying context. If that doesn't work, you can try calling `onActivityResult` on `Exponent.getInstance()`.

Let's go through the problems one by one. 🙂

**Comment by killerham** [comment] 2018-12-03 17:03
@sjchmiela I'm using the instructions in this post: https://github.com/zo0r/react-native-push-notification/issues/846#issuecomment-416083624 to make it work with expo.

My crash happens here: https://github.com/zo0r/react-native-push-notification/blob/ae4f9fd06dc46011e4c25f842f00462d7b4d35d2/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java#L82

**Comment by sjchmiela** [comment] 2018-12-03 17:47
Hm… it would be really strange for the selected line of code to work anytime in Expo. `ExpoApplication`, which is the default superclass of `MainApplication` isn't a `ReactApplication`, so casting it to this class would always fail… 🤔 In order for this line not to fail you'll need to implement `ReactApplication` in your `MainApplication`, have you tried that (you'll need to expose `ReactNativeHost`, the way prescribed in the comment seems ok).

**Comment by killerham** [comment] 2018-12-03 17:50
@sjchmiela Yup, I've exposed ReactNativeHost as suggested in the instructions

**Comment by tsapeta** [comment] 2020-06-30 12:34
SDK30 and ExpoKit are no longer supported so I'm closing this issue.

**Closed by tsapeta** 2020-06-30 12:34 UTC
Labels: Android, project: expokit
