### ISSUE TITLE
[web] Failed to compile - Unknown helper createSuper

### ISSUE THREAD

**Issue by ggunti** [expo/expo#7419] opened 2020-03-20 19:09 UTC
### Environment

  Expo CLI 3.13.8 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.13.8

Target: web

### Steps to Reproduce

Run `expo init <yourProjectName>` and `npm run web` inside `<yourProjectName>` directory.

### Expected Behavior

Run the app for web.

### Actual Behavior

I get 'Failed to compile' error, like here:
<img width="1080" alt="Captură de ecran din 2020-03-20 la 21 04 00" src="https://user-images.githubusercontent.com/26307699/77198079-fc8bc300-6aee-11ea-8290-88179874f195.png">

NOTE THAT IT WORKS ON ANDROID & IOS.

**Comment by FeaturedSpace** [comment] 2020-03-20 22:35
Is there a way we can fix this? I'm in a critical production state due to the corona virus and I'm unable to work.

**Comment by eduardosoller** [comment] 2020-03-20 23:07
Same here, waiting for a solution...

**Comment by FeaturedSpace** [comment] 2020-03-20 23:15
@bbarthec @brentvatne

**Comment by brentvatne** [comment] 2020-03-20 23:16
@EvanBacon will investigate shortly

**Comment by EvanBacon** [comment] 2020-03-20 23:27
https://github.com/babel/babel/pull/11298

**Comment by brentvatne** [comment] 2020-03-20 23:47
this impacted create-react-app as well, we should have a solution soon after the pull request @EvanBacon mentioned is merged and released

**Comment by FeaturedSpace** [comment] 2020-03-21 00:07
I've reinstalled NodeJS, npm, and expo, and I this actually resulted in a successful web compile. I don't know what it was, but a full reset actually helped. If anyone else is having this issue, perhaps try to uninstall nodejs, and delete the npm and npm-cache folders in Roaming. This is what worked for me.

**Closed** 2020-03-21 01:04 UTC
Labels: bug

**Comment by brentvatne** [comment] 2020-03-21 01:20
if you update to `expo-cli@3.15.5` this is resolved - we bumped the babel versions in the webpack config

**Comment by eduardosoller** [comment] 2020-03-21 02:51
After update, i get this error:
app\node_modules\@react-navigation\stack\lib\module\views\Header\HeaderSegment.js: Unknown helper createSuper

**Comment by brentvatne** [comment] 2020-03-21 03:23
can you post a reproducible example? this is working locally for me and that was the error that should have been fixed

**Comment by eduardosoller** [comment] 2020-03-21 04:00
Sorry...NOW I updated and I didn't get any more errors.

**Comment by EvanBacon** [comment] 2020-03-21 20:24
I will be locking this issue now. If Babel breaks again similarly in the future please open a new issue.
