### ISSUE TITLE
Expo SQLite 'PRAGMA user_version' not working

### ISSUE THREAD

**Issue by kestasb** [expo/expo#1489] opened 2018-03-02 15:28 UTC
### Environment

Environment:
  OS: Windows 10
  Node: 6.10.2
  Yarn: 1.3.2
  npm: 5.6.0

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

### Steps to Reproduce

Execute command **tx.executeSql('pragma user_version')**.

### Expected Behavior

It should return database's `user_version` pragma value. 

### Actual Behavior

It works with iOS device/simulator, but does not work with Android device/emulator and throws the following error:
**[Error: unknown error (code 0): Queries can be performed using SQLiteDatabase query or rawQuery methods only.]**

Changing pragma's value, e.g. **tx.executeSql('pragma user_version=1')** works both on iOS and Android.

### Code to reproduce the issue

https://snack.expo.io/ryZiXt5df

**Comment by jesseruder** [comment] 2018-03-03 01:34
Hi! Can you make a Snack of this issue?

**Comment by kestasb** [comment] 2018-03-06 08:37
I've made a Snack to reproduce this issue.

**Comment by kestasb** [comment] 2018-03-21 12:03
Any news?

**Comment by esamelson** [comment] 2018-03-22 20:13
Hi @kestasb - sorry for the delay here. This looks like a bug, and we'll look into it as soon as we can, but as we're a small team I can't promise any specific timeline. In the meantime, is it possible for you to use the workaround of `SELECT * FROM pragma_user_version;` instead? That seemed to work fine for me.

**Comment by kestasb** [comment] 2018-03-23 07:49
Hi @esamelson - I've created another Snack [https://snack.expo.io/Hy3i1Nzqf](url) with your suggested query. 
It works on iOS device, but throws the following error on Android:
`"Error: no such table: pragma_user_version (code 1):, while compiling: SELECT * FROM pragma_user_version"`

**Comment by esamelson** [comment] 2018-03-23 17:51
Hi @kestasb - odd, your snack works just fine on my Android device (Pixel 2) and does not throw any errors. What Android device are you testing on? Wonder if the sqlite implementation is slightly different.

Also, what version of the Android client you are using? (it's in light gray text underneath the project history)

**Comment by kestasb** [comment] 2018-03-26 10:23
@esamelson - I've tried with Nexus 5X (Android 8.1) and it worked, but it doesn't work on Samsung Galaxy S6 (Android 7.0). Both devices use Expo client v2.3.2. Seems to be related to Android version.

**Comment by jichu4n** [comment] 2018-06-03 07:06
Running into similar error. I'm trying to use to conditionally add a column to an existing table, and the relevant PRAGMA query works correctly on iOS, but fails on Android.

Query: `PRAGMA table_info(my_table);` ([SQLite docs](https://www.sqlite.org/pragma.html#pragma_table_info))
Error: `Error: unknown error (code 0): Queries can be performed using SQLiteDatabase query or rawQuery methods only.`

Tested failing on Android devices:
- Pixel 2 (8.1.0)
- HTC 10 (8.0.0)
- Moto RAZR M (4.4.2)

Using Expo SDK version 27.0.2 and Expo client version 2.5.2 on all 3 devices.

**Comment by iffy** [comment] 2018-07-13 02:54
I think the problem is in `@expo/websql/lib/sqlite/SQLiteDatabase.js`.  Particularly this section:

```javascript
  function doNext() {
    var query = queries[i];
    var sql = query.sql;
    var args = query.args;

    // TODO: It seems like the node-sqlite3 API either allows:
    // 1) all(), which returns results but not rowsAffected or lastID
    // 2) run(), which doesn't return results, but returns rowsAffected and lastID
    // So we try to sniff whether it's a SELECT query or not.
    // This is inherently error-prone, although it will probably work in the 99%
    // case.
    var isSelect = /^\s*SELECT\b/i.test(sql);

    if (readOnly && !isSelect) {
      onQueryComplete(i)(new SQLiteResult(READ_ONLY_ERROR));
    } else if (isSelect) {
      runSelect(db, sql, args, onQueryComplete(i));
    } else {
      runNonSelect(db, sql, args, onQueryComplete(i));
    }
```

Instead of restricting us to go through this "inherently error-prone" logic, could we instead have access to choose if we want a result-returning or no-result query?  I'm happy to submit a pull request, but I can't find the source for @expo/websql on GitHub

**Comment by iffy** [comment] 2018-07-13 04:58
I take it back.  The problem is in the various `SQLiteModule.java` files in expo/expo. 
 Particularly, [`isSelect`](https://github.com/expo/expo/blob/master/android/expoview/src/main/java/abi22_0_0/host/exp/exponent/modules/api/SQLiteModule.java#L234):

```java
  private static boolean isSelect(String str) {
    return startsWithCaseInsensitive(str, "select");
  }
```

I think there are at least these possible fixes:

1. Remove all the clause-guessing code from the java files and let the @expo/websql code pass in what the clause is.  This would require adding methods other than `executeSql` or changing it's signature.
2. Improve the clause-guessing code (and maybe consolidate it at the same time?) so that it understands PRAGMAs.  This doesn't require changing Expo's public SQLite interface so it may be the better option.
3. Remove the clause-guessing code and always use `rawQuery` for running queries (making sure to always go through the result so that there isn't [this problem](https://stackoverflow.com/questions/7211158/why-does-a-delete-rawquery-need-a-movetofirst-in-order-to-actually-delete-the-ro)).  I'm not sure what the performance hit would be like, but it would sure simplify the code, I think.  Like 2 above, this also keeps Expo's public SQLite interface as-is.

**Comment by cruzach** [comment] 2019-10-09 19:35
Fixed in [1988](https://github.com/expo/expo/pull/1988)

**Closed by cruzach** 2019-10-09 19:35 UTC
Labels: project: android-runtime
