### ISSUE TITLE
Calendar issue: not able to save an event in ios device

### ISSUE THREAD

**Issue by reactexcel** [expo/expo#4838] opened 2019-07-05 14:31 UTC
i have created  calendar to save events but on calling Calendar.createEventAsync, getting error
Error: Event with id 5BC7E774-2952-4313-82CE-52D379F7C373 was not saved
I spend my whole days but not found any solution anywhere.
Please help to resolve it.
Thanks

**Comment by reactexcel** [comment] 2019-07-05 15:05
Here is my code ;
 await Calendar.createCalendarAsync({
    title:"calendar",
    color:"#8295AF",
    entityType:Calendar.EntityTypes.EVENT,
    sourceId:"98BE309F-FFEF-47A3-B6FC-A6697B757C29",
    allowsModifications:true,
    type:Calendar.CalendarType.LOCAL,
  }).then(async (id)=>{
    console.log(id,'id')
    await Expo.Calendar.createEventAsync("54B646A8-9615-4000-8C74-538CEFFB40BB", {
      startDate: new Date("2019-07-06"),
      endDate: new Date ("2019-06-06"),
      title:item.title,
      timeZone: "GMT-5",
      status:Calendar.EventStatus.CONFIRMED,
      isDetached:true,    
      allDay:true,
      availability:Calendar.Availability.FREE,
      notes:"xfchgvjkvjhvchjvjhvjhvjhvjhv",
      location:`${item.EventPlace}, ${item.EventCity && item.EventCity.name && ","+" "+item.EventCity.name}`,
      url:"https://www.google.com"
    })
  })
I took and calendar id by using Calendar.getCalendarsAsync, as i red somewhere to create an event calendar id must be string so i am passing it manually for the time.

**Comment by cruzach** [comment] 2019-07-05 19:13
Hey @reactexcel, 

The code you shared is really difficult to read, and throws a few parsing errors when pasted into a snack. Please share a snack that reproduces your behavior, that way it'll be much easier and **much** faster to find out the root cause.

**Comment by danish4114** [comment] 2019-07-06 10:33
I have the exactly same issue as @reactexcel  have , **I am getting this error in IOS** 
Calendar is being created fine also getting calendar id but when i am trying to add any event
i am getting error like "Error: event with id ... could not be saved"
i have spend my two days to fix this issue but git not get any solution
also do we have any function to open os calendar in ios as we have for android **openEventInCalendar**
Here is my code 

const calendarDetails= {
    title:"allowsModificationskmklmkml",
    color:"#8295AF",
    entityType:Calendar.EntityTypes.EVENT,
    sourceId:"98BE309F-FFEF-47A3-B6FC-A6697B757C29",
    allowsModifications:true,
    type:Calendar.CalendarType.LOCAL,
   } 

const details ={
      startDate: new Date("2019-07-06"),
      endDate: new Date ("2019-06-06"),
      title:item.title,
      timeZone: "GMT-5",
      status:Calendar.EventStatus.CONFIRMED,
      isDetached:true,    
      allDay:true,
      availability:Calendar.Availability.FREE,
      notes:"this is a problem with adding event",
      location:`xxx`,
      url:"https://www.google.com"
         }

await Expo.Calendar.createCalendarAsync(calendarDetails).then((id)=>{    
     const allCalendars = Calendar.getCalendarsAsync()
      if(allCalendars && allCalendars .length ){
          Expo.Calendar.createEventAsync(allCalendars[0].id, details).then((id)=>{
             console.log(id)
           })
       }
   })

Please help @cruzach  please , i am begging you

**Comment by reactexcel** [comment] 2019-07-08 07:04
@cruzach Thanks for reply
ok i am logging all the codes that is reproduce the issue

`{
  "name": "wellness_front_end",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "axios": "^0.18.0",
    "formik": "^1.5.1",
    "immutability-helper": "^3.0.0",
    "jwt-simple": "^0.5.5",
    "moment": "^2.24.0",
    "node-sass": "^4.12.0",
    "react": "^16.8.2",
    "react-bootstrap": "^1.0.0-beta.8",
    "react-dom": "^16.8.2",
    "react-facebook": "^8.0.4",
    "react-facebook-login": "^4.1.1",
    "react-fb-like": "^0.5.1",
    "react-geocode": "^0.1.2",
    "react-geolocated": "^2.5.0",
    "react-google-login": "^5.0.4",
    "react-loader-spinner": "^2.3.0",
    "react-modal": "^3.8.1",
    "react-redux": "^6.0.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.5",
    "react-share": "^2.4.0",
    "react-star-ratings": "^2.3.0",
    "react-toastify": "^4.5.2",
    "redux": "^4.0.1",
    "redux-actions": "^2.6.4",
    "redux-form": "^8.1.0",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
`

**Comment by cruzach** [comment] 2019-07-08 15:12
@reactexcel and @danish4114 - it's much easier to just share a snack link that reproduces the bug. You can make one [here](https://snack.expo.io/)

**Comment by danish4114** [comment] 2019-07-09 04:42
ok thanks @cruzach  for the reply
Here is my code on stack

`https://snack.expo.io/rky095bZB`

**Comment by reactexcel** [comment] 2019-07-09 11:18
@cruzach  please check the same stack of @danish4114  for me

**Comment by cruzach** [comment] 2019-07-09 13:44
That link doesn't work @danish4114

**Comment by jihyeonjeong11** [comment] 2019-08-08 04:18
@danish4114
 @reactexcel 
I was having the same problem listed above.
I tried to get events using Calendar.getCalendarsAsync('event') to get all events

```
const calendar = await Calendar.getCalendarsAsync('event')
//console.log(JSON.stringify(calendar))
let calendarId = calendar.filter((item) => item.allowsModifications === true)[0].id
//console.log(calendarId)
```

allowsModifications props will determine if event is generated by devices's system, so value false would be custom events calendar, that is default(title: 'Calendar') calendar.
With that CalendarId, I could manage to save custom event.
I tested this with some simulators and it seems to working fine...

**Comment by Webdev259** [comment] 2019-10-09 06:45
Any solution for this? I am facing the same issue with expo 35.0.0

**Comment by Webdev259** [comment] 2019-10-09 11:07
The main issue is with the Date object you are setting. Change the value of ` startDate `and` endDate` to `new Date()` just to test it.

**Comment by reactexcel259** [comment] 2019-10-09 17:37
@jihyeonjeong11 
I  tried to save custom event, did not get luck was facing the same issue 
@Webdev259  i did with 32 and 33 not with 34 and 35 will try soon
and anyone has alternate solution please share i am stucked in last 3 months but did not get any solutions yet thanks in advance.

**Comment by reactexcel259** [comment] 2019-10-09 17:41
Hey!  @cruzach 
can you please check my above code deeply i am not able to give you an another stack for now
bdw i am@danish4114 i just changed my github username
i will very thankful to you.

**Comment by reactexcel259** [comment] 2019-10-09 17:44
@cruzach  and this stack [https://snack.expo.io/rky095bZB](url) is working fine you can check here

**Comment by cruzach** [comment] 2019-12-05 16:23
Hey @reactexcel259 - I made [this snack](https://snack.expo.io/@charliecruzan/createeventcalendar) that uses `createEventAsync` successfully. Hopefully that helps you to debug this issue (looks like in the snack you shared you don't request for Calendar permissions, which might be the source of the issue)

**Comment by wodin** [comment] 2019-12-21 11:22
GitHub's way of handling links in markdown is a bit confusing. [This](https://snack.expo.io/rky095bZB) is the snack that reactexcel was trying to link to.

**Comment by cruzach** [comment] 2019-12-23 16:39
Thanks @wodin for the breakdown 😄 

I'm going to close this, since there's a lot of back-and-forth in this issue and it's not clear where the repro is and what the problem is. If you can make a repro for what is happening, taking all of wodin's points into account, please open a new issue and fill out the entire bug report template

**Closed by cruzach** 2019-12-23 16:39 UTC
Labels: needs repro, status: needs more info
