### ISSUE TITLE
EAS build, screen rotation is not working in iOS

### ISSUE THREAD

**Issue by VivekG03** [expo/expo#17738] opened 2022-06-03 08:27 UTC
### Summary

When we rotate an iOS app which is build in EAS, the app doesn't rotate even the configuration is turned on.

### What platform(s) does this occur on?

iOS

### SDK Version

SDK 45

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      expo: ^45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Reproducible demo

As it is generic behavior hence no code needed

**Comment by brentvatne** [comment] 2022-06-28 02:41
duplicate of https://github.com/expo/expo/issues/17724

**Closed by brentvatne** 2022-06-28 02:41 UTC
Labels: needs review, CLI
