### ISSUE TITLE
App works fine on dev but is unable to run on standalone build

### ISSUE THREAD

**Issue by bill-pairaktaridis** [expo/expo#7190] opened 2020-02-26 08:00 UTC
### Environment
```
  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.7 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.2 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.2.1 => 4.2.1 
    npmGlobalPackages:
      expo-cli: 3.13.1
```

Target: Android & iOS

### Steps to Reproduce

1. `expo build:android --release-channel staging -t app-bundle`
2. Upload to Google Play
3. All automated tests fail because the app crashes on the splash screen

### Expected Behavior

Work the same as the dev environment

### Actual Behavior

App just crashes

### Reproducible Demo

It's very difficult, if not impossible to create a demo for a complex app that's been in development for over a year

### package.json

```
{
  "name": "Nimber",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base)"
    ]
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "@expo/vector-icons": "^10.0.0",
    "@react-native-community/async-storage": "^1.8.0",
    "@react-native-community/datetimepicker": "2.1.0",
    "@react-native-community/netinfo": "4.6.0",
    "@react-navigation/native-stack": "^5.0.1",
    "braces": "^3.0.2",
    "core-js": "^3.1.3",
    "country-telephone-data": "^0.6.0",
    "expo": "^36.0.2",
    "expo-analytics": "^1.0.14",
    "expo-constants": "~8.0.0",
    "expo-facebook": "~8.0.0",
    "expo-file-system": "~8.0.0",
    "expo-gl": "~8.0.0",
    "expo-image-manipulator": "~8.0.0",
    "expo-image-picker": "~8.0.1",
    "expo-localization": "~8.0.0",
    "expo-location": "~8.0.0",
    "expo-media-library": "~8.0.0",
    "expo-permissions": "~8.0.0",
    "expo-pixi": "^1.2.0",
    "expo-print": "~8.0.0",
    "expo-sms": "~8.0.0",
    "expo-task-manager": "~8.0.0",
    "expo-web-browser": "~8.0.0",
    "expokit": "^36.0.1",
    "geolib": "^3.0.3",
    "i18n-js": "^3.5.1",
    "libphonenumber-js": "^1.7.23",
    "lodash.debounce": "^4.0.8",
    "moment": "^2.24.0",
    "prop-types": "^15.6.2",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
    "react-native-app-link": "^1.0.0",
    "react-native-elements": "^0.19.1",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-hyperlink": "0.0.14",
    "react-native-looped-carousel": "^0.1.13",
    "react-native-maps": "0.26.1",
    "react-native-maps-directions": "^1.7.3",
    "react-native-reanimated": "~1.4.0",
    "react-native-safe-area-context": "0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-signature-canvas": "^1.6.0",
    "react-native-signature-pad": "^0.1.0",
    "react-native-svg": "9.13.3",
    "react-native-svg-animated-linear-gradient": "^0.1.9",
    "react-native-swipe-verify": "^0.1.6",
    "react-native-vector-icons": "^6.6.0",
    "react-native-view-shot": "3.0.2",
    "react-native-webview": "7.4.3",
    "react-navigation": "^4.2.1",
    "react-navigation-drawer": "^2.3.4",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.7.0",
    "react-redux": "^5.1.2",
    "redux": "^4.0.5",
    "redux-persist": "^5.10.0",
    "redux-sentry-middleware": "^0.1.6",
    "sentry-expo": "^2.0.2",
    "tiny-emitter": "^2.1.0",
    "ws": "^7.2.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.5",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/preset-flow": "^7.0.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "^6.0.1",
    "eslint-plugin-react": "^7.14.2",
    "flow-bin": "^0.89.0",
    "jest-expo": "^36.0.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "^16.11.0"
  }
}
```

### app.json

```
{
  "expo": {
    "name": "Nimber",
    "description": "Going your way anyway!",
    "slug": "nimber-bringer",
    "privacy": "unlisted",
    "sdkVersion": "36.0.0",
    "version": "1.6.0a",
    "primaryColor": "#ffffff",
    "platforms": [
      "android",
      "ios"
    ],
    "orientation": "portrait",
    "icon": "./assets/images/icons/adaptive-icon.png",
    "notification": {
      "icon": "./assets/images/icons/appicon/Icon-512.png",
      "color": "#eff6ff"
    },
    "updates": {
      "enabled": true,
      "checkAutomatically": "ON_LOAD",
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "assets/images/*",
      "assets/fonts/*"
    ],
    "scheme": "HIDDEN",
    "githubUrl": "HIDDEN",
    "android": {
      "versionCode": 85,
      "package": "HIDDEN",
      "icon": "./assets/images/icons/adaptive-icon.png",
      "adaptiveIcon": {
        "backgroundColor": "#ffffff",
        "foregroundImage": "./assets/images/icons/adaptive-icon.png"
      },
      "config": {
        "googleMaps": {
          "apiKey": "HIDDEN"
        }
      },
      "permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION",
        "CAMERA",
        "MANAGE_DOCUMENTS",
        "VIBRATE",
        "WAKE_LOCK",
        "WRITE_EXTERNAL_STORAGE"
      ],
      "intentFilters": [
        {
          "action": "VIEW",
          "data": [
            {
              "scheme": "https",
              "host": "*.nimber.com",
              "pathPrefix": "/tasks"
            }
          ],
          "category": [
            "BROWSABLE",
            "DEFAULT"
          ]
        }
      ],
      "googleServicesFile": "./google-services.json",
      "splash": {
        "backgroundColor": "#3752d8",
        "mdpi": "./assets/images/splash/mdpi/splash.png",
        "hdpi": "./assets/images/splash/hdpi/splash.png",
        "xhdpi": "./assets/images/splash/xhdpi/splash.png",
        "xxhdpi": "./assets/images/splash/xxhdpi/splash.png",
        "xxxhdpi": "./assets/images/splash/xxxhdpi/splash.png"
      }
    },
    "ios": {
      "bundleIdentifier": "HIDDEN",
      "buildNumber": "3",
      "splash": {
        "userInterfaceStyle": "light",
        "backgroundColor": "#3752d8",
        "image": "./assets/images/splash/xxxhdpi/splash.png"
      },
      "associatedDomains": [
        "applinks:www.nimber.com",
        "applinks:sonar.nimber.com",
        "applinks:*.nimber.com",
        "applinks:nimber.com"
      ],
      "config": {
        "usesNonExemptEncryption": false,
        "googleMapsApiKey": "HIDDEN"
      }
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "nimber",
            "project": "bringer-app",
            "authToken": "HIDDEN"
          }
        }
      ]
    },
    "androidStatusBar": {
      "visible": false,
      "barStyle": "dark-content",
      "backgroundColor": "#eff6ff"
    },
    "androidNavigationBar": {
      "visible": false,
      "barStyle": "dark-content",
      "backgroundColor": "#ffffff"
    }
  }
}
```
This is the error on Firebase and Play Console:

```
Fatal Exception: java.lang.RuntimeException
Expo encountered a fatal error: Invariant Violation: "main" has not been registered. This can happen if: * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project. * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```

As well as this:

```
FATAL EXCEPTION: main
Process: com.nimber.bringerapp, PID: 19667
java.lang.RuntimeException: Expo encountered a fatal error: TypeError: null is not an object (evaluating 'f.hidden=!0'), stack:
supportsNativeFetch@886:761
v@887:1077
p@887:296
addInstrumentationHandler@887:4159
setupOnce@916:2799
s@892:734
<unknown>@892:1024
forEach@-1
setupIntegrations@892:998
s@891:317
p@922:356
initAndBind@895:196
init@924:963
init@861:3
	at host.exp.exponent.experience.a$b.run(BaseExperienceActivity.java:7)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

Worth pointing out that Sentry produces nothing, since it doesn't even get to run. I've tried removing node_modules and .expo/ multiple times to no avail

**Comment by bill-pairaktaridis** [comment] 2020-02-26 08:01
This is the error on Firebase and Play Console:

```
Fatal Exception: java.lang.RuntimeException
Expo encountered a fatal error: Invariant Violation: "main" has not been registered. This can happen if: * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project. * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```

**Comment by bill-pairaktaridis** [comment] 2020-02-26 09:07
Worth pointing out that Sentry produces nothing, since it doesn't even get to run. I've tried removing node_modules and .expo/ multiple times to no avail

**Comment by bill-pairaktaridis** [comment] 2020-02-26 12:12
I figured out that it's related to this issue: https://github.com/getsentry/sentry-react-native/issues/774

Not sure what's causing it but disabling Sentry for now seems to have resolved it. Maybe an issue with the update `fetch`?

**Comment by cruzach** [comment] 2020-02-26 16:43
If you want to integrate sentry in your Expo managed project, you should use our wrapper, `sentry-expo` - https://docs.expo.io/versions/latest/guides/using-sentry/

Aside from that, whenever you see an issue crop up only in standalone builds like this, it's best to run your project locally in production mode with `expo start --no-dev --minify` to see if you can debug further

**Comment by bill-pairaktaridis** [comment] 2020-02-26 21:12
I do use `sentry-expo`. Can't quite pinpoint when this issue cropped up, since I haven't built a standalone build is a while. I tried reverting pretty much all my packages but to no avail. Right now I've disabled Sentry just to get things working.

**Comment by cruzach** [comment] 2020-02-27 19:07
How did you come to the conclusion that that sentry issue you linked is the root cause? If it is, then once they release it we can update `sentry-expo`'s dependency

**Comment by bill-pairaktaridis** [comment] 2020-02-27 19:14
I mean the issue went away once I disabled sentry. I had to look up `hidden!=0` and that led me to `@sentry/browser` and that's what led me to believe it was a sentry issue.

**Comment by cruzach** [comment] 2020-02-27 19:15
It may be a sentry issue, although without a reproducible demo it's really hard to tell

**Comment by bill-pairaktaridis** [comment] 2020-03-04 11:12
Not sure if anyone else is using Expo 36  and Sentry but I guess a lot of people do which would cause more of these issues to crop up. Right now it seems to have gone away, although it seems the error was downgraded to a warning but at least my apps run normally again.

**Comment by cruzach** [comment] 2020-03-05 01:16
I have a few projects using Expo 36 and `expo-sentry`, and haven't seen this 🙁 

Since it's resolved itself I'm going to close this for now, but if you're able to reproduce it consistently I'll reopen

**Closed by cruzach** 2020-03-05 01:16 UTC
Labels: bug, needs repro, status: needs more info

**Comment by hoyame** [comment] 2020-10-21 12:06
same problem :/

**Comment by bill-pairaktaridis** [comment] 2020-10-21 12:10
@hoyame make sure you're on the latest `sentry-expo` version and you're not using any other sentry library.
