### ISSUE TITLE
Google auth redirect opens new instance of app

### ISSUE THREAD

**Issue by jamesphilipps** [expo/expo#9522] opened 2020-08-01 07:40 UTC
### Summary of Issue 

Using the `expo-google-app-auth` authentication from a managed workflow, when running the app on android the redirect after authentication opens a second instance of the app.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.23.1 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.6.0 - /usr/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.6 - /usr/bin/npm
    npmPackages:
      expo: ~38.0.8 => 38.0.8 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.23.1
``` 

### Reproducible Demo
```
  const result = await Google.logInAsync({
    androidClientId: 'CLIENT_ID,
    iosClientId: 'CLIENT_ID,
    scopes: ['profile', 'email'], 
  })
  if (result.type !== 'success') {
    throw Error('sign in with google failed')
  }
```
 
### Steps to Reproduce

- Activate code above
- Successfully sign in with google
- Check application switcher and notice second version of the app is now running. 

### Expected Behavior vs Actual Behavior
The redirect should return to the original version of the app. Instead, a second instance is opened. This is most noticeable when authentication fails as error states are shown on the original (backgrounded) app and not the new (foregrounded) app.

**Comment by jamesphilipps** [comment] 2020-08-01 08:03
After further investigation, this seems to be an issue with upcoming Android API 30. Might be worth keeping an eye on.

**Comment by barthap** [comment] 2020-08-05 11:56
I've noticed the same issue, when displayed a notification on Android, then tapped the notification. Response is handled by `NotificationResponseReceivedListener`, but it also opens new experience instance in Expo client.

[Here is the demo](https://snack.expo.io/@barthap10/dcf7bd) which makes it easier to reproduce. Just set `shouldShowAlert: true`.

It looks like some `Intent` opens new experience activity instead of directing to existing one.

**Comment by snowerem** [comment] 2020-08-16 15:35
> After further investigation, this seems to be an issue with upcoming Android API 30. Might be worth keeping an eye on.

I faced the same issue on AVD with Android API 30.  

When the API is < 30 everything works like a charm.

**Comment by esamelson** [comment] 2020-08-25 21:08
Hi there -- could someone experiencing this issue give it a try on the latest Android 11 beta 3 release? I was not able to reproduce this issue on either an emulator or device running this version, using either expo-google-app-auth or Notifications.

**Comment by esamelson** [comment] 2020-08-25 21:33
Seems like this has been fixed in Android 11 beta 3, so closing this.

**Closed by esamelson** 2020-08-25 21:33 UTC
Labels: Android, Google, Issue needs review
