### ISSUE TITLE
"Could not load app. Can't connect to internet. Please try again" - SDK27-30 w/ ExpoKit

### ISSUE THREAD

**Issue by iuliuvisovan** [expo/expo#1798] opened 2018-05-26 12:15 UTC
I recently updated to SDK27 (am using ExpoKit), and I'm trying to use the offline JS bundle functionality. I followed the instructions from [here]
(https://gist.github.com/janicduplessis/30ec95451733d34ffcf7d5cb27ba0e28), but I keep seeing this screen after rebuilding:

![image](https://user-images.githubusercontent.com/11357552/40575819-9fb8d95c-60f4-11e8-84ea-eb3b563d7bf5.png)

I double-checked that:

- detach-scripts contains both `run-exp.bat` and `run-exp.sh`
- `app/build.graddle` contains `apply from: 'expo.gradle'`
- `android/app` contains `expo.gradle`

And now I'm not sure if I did the right thing, but what I've done is:
- Since I wasn't sure what "my manifest" is and the build was asking for it, I created a `shell-app-manifest.json` in my `android\app\src\main\assets`, with the following content:

```
{
  "android": {
    "publishBundlePath": "android/app/src/main/assets/shell-app.bundle",
    "publishManifestPath": "android/app/src/main/assets/shell-app-manifest.json"
  },
}
```
But it seemed to be the right move since build completes successfully, can confirm it creates a `shell-app.bundle` in `src/main/assets`, and installs on device successfully. But then if I stop wifi and run the app I get the initial blue screen error again.

Is it something that I'm missing?

**Comment by janicduplessis** [comment] 2018-06-13 18:01
Hello @iuliuvisovan, I think the issue is that you need to add the following to your app manifest (app.json) and not a separate file.

```
"android": {
    "publishBundlePath": "android/app/src/main/assets/shell-app.bundle",
    "publishManifestPath": "android/app/src/main/assets/shell-app-manifest.json"
  },
````

**Comment by slorber** [comment] 2018-07-14 14:23
It seems to work for me, but I'm also using these settings:

```js
    "updates": {
      "enabled": true,
      "checkAutomatically": "ON_LOAD",
      "fallbackToCacheTimeout": 0
    },
```


@janicduplessis do you know why on eject these android configs are not here by default? (https://github.com/expo/expo/issues/1802#issuecomment-405024497)

**Comment by ianmartorell** [comment] 2018-10-04 14:00
I'm having this issue on SDK 30, the bundle and manifest lines are present in the `app.json` and the files are generated by `expo publish`, but the generated APK doesn't seem to include the JS bundle on first load. I have the following on my `app.json`:

```javascript
// ...
    "android": {
      "publishBundlePath": "android/app/src/main/assets/shell-app.bundle",
      "publishManifestPath": "android/app/src/main/assets/shell-app-manifest.json"
    },
// ...
    "updates": {
      "enabled": true,
      "checkAutomatically": "ON_ERROR_RECOVERY",
      "fallbackToCacheTimeout": 0
    },
// ...
```

Loading the release app without an internet connection:

![device-2018-10-04-155749](https://user-images.githubusercontent.com/318800/46478949-4810bb00-c7ee-11e8-8068-f2071ab87f26.png)
![device-2018-10-04-155758](https://user-images.githubusercontent.com/318800/46478954-49da7e80-c7ee-11e8-83a9-5e84687a92bf.png)

**Comment by iuliuvisovan** [comment] 2018-10-11 12:03
Pretty sure it's the same issue as [this](https://github.com/expo/expo/issues/1802). You most probably need to `exp publish`, but I've also encountered this after publishing too, so not sure.

**Comment by ianmartorell** [comment] 2018-10-14 18:05
It's definitely not the same issue, at least for me. I've checked that the bundle gets generated when I run `exp publish` and the app still doesn't start offline. I'll be able to do more tests in a couple of days, and I'll try to replicate the behaviour on a new app.

**Comment by ianmartorell** [comment] 2018-10-17 11:41
I did the following:

1. Create a new project with `expo init`
2. Eject to ExpoKit with `expo eject`
3. Test the app works in development mode
4. Publish with `expo publish`
5. Generate a signed release apk

Installing and running the release build without internet connection triggers the error "**Could not load app. Can't connect to internet. Please try again.**" It appears it tries to resolve `exp.host` and obviously fails.

Isn't the expected behaviour to run the JS bundled with the apk?

Here's the repo: https://github.com/ianmartorell/expokit-offline-test/

**Comment by gitsuraj** [comment] 2018-11-01 23:54
Expo 30 same issue as @ianmartorell

**Comment by eaceto** [comment] 2018-11-05 10:57
Expo 31 has the same issue as @ianmartorell 
Did anybody find a way to fix this?

**Comment by ianmartorell** [comment] 2018-11-05 12:51
It'd be great if we could get some feedback from the Expo team, since it seems offline support is basically not working as described [in the docs](https://docs.expo.io/versions/latest/guides/offline-support).

@brentvatne or @anp, can we get some feedback on this? I'm tagging you guys because of your activity on this [feature request](https://expo.canny.io/feature-requests/p/allow-standalone-apps-to-load-and-function-with-no-internet-connection).

**Comment by eaceto** [comment] 2018-11-06 15:08
For me it only works on iOS, but on Android it gives me tones of headaches...

**Comment by sjchmiela** [comment] 2018-11-24 08:09
Hey all! I'm sorry it took so long to get back to this issue. I think this issue is similar to an issue described in https://forums.expo.io/t/could-not-load-embedded-manifest-android/14713/6 which, in fact, has been resolved some time ago!

To fix your project, open `AppConstants.java` and remove the `index.exp` suffix from this line:

https://github.com/ianmartorell/expokit-offline-test/blob/a67e7f2e4ddf4905a243d2f2e60ea7b0094acc8a/android/app/src/main/java/host/exp/exponent/generated/AppConstants.java#L31

This problem should also be fixed by upgrading `expo-cli` to at least 2.2.6 (but as always, I would recommend using the latest version). 🙂

**Closed by sjchmiela** 2018-11-24 08:09 UTC

**Comment by ianmartorell** [comment] 2018-11-24 13:54
Thanks for the reply! Can confirm it works. Publishing the app with `expo-cli` 2.4.0 automatically removes the suffix on that line. Running then the release version of the app for the first time on a device on airplane mode correctly loads the JS bundle. Thank you!

**Comment by ianmartorell** [comment] 2018-11-24 15:08
Actually, it seems I talked too soon. It worked as expected earlier because I published the app using a different Expo account than the one I used when I first made the test repo, so a new Expo Project was created. However, if I publish a new version of the existing app using the original account, I still get the blue error screen. I went back and forth between accounts a few times to make sure, and I checked that the URIs in `AppConstants.java` are correct. Any idea of what could be going on? 😕

**Comment by sjchmiela** [comment] 2018-11-24 15:37
The way app loading works in rough is:
- `static` block in `AppConstants` registers embedded responses, i. e. contents for a sort of a caching proxy, so when the app loader asks for eg. `https://exp.host/@sjchmiela/android292` it doesn't need to do a real network request — the response is embedded right here (`assets://shell-app-manifest.json`).
- a URL to the manifest is being constructed basing on `MainActivity#publishedUrl()` (eg. `exp://exp.host/@sjchmiela/android292` is being turned into `https://exp.host/@sjchmiela/android292` by [`ExponentUrls.java`](https://github.com/expo/expo/blob/d85cf10adb8ce2f381b3492e35857c200fb764e7/android/expoview/src/main/java/host/exp/exponent/kernel/ExponentUrls.java#L32-L40))
- app loader tries to fetch the manifest from this URL (it may hit the embedded response)
- the manifest contains information about the app + bundle URL
- app loader fetches the bundle URL and runs it.

For embedded responses to work, username and app name must match between `MainActivity` and the embedded response defined in `AppConstants`.

When you publish an application on account `@newbetteraccount`, `expo-cli` will register an embedded response for `@newbetteraccount/theapp` and if `MainActivity` still points to `@theoriginalaccount/theapp`, embedded response won't be hit. So if the app works in offline mode when publishing from one account and not from the other, make sure `publishedUrl` reflects the desired change too. 🙂

**Comment by Maxwell2022** [comment] 2018-12-17 01:38
I've updated `expo-cli` to version `2.6.13`, publish the app in the default channel, check that it's published to the correct expo account and the version is here using `expo ph`.

* Running dev and building release on iOS == no issues
* Running dev (with bundler started) on android not issues
* Building release (bundler stopped) on android == `Could not load the app`, it looks like it's looking for the dev URL (not sure if it's a fallback system or a wrong config).

What else should I check? everything looks good to me, I don't have any account miss-match anymore, I've re-published everything and rebuild everything.

**Comment by Maxwell2022** [comment] 2018-12-17 01:47
it looks like I had to delete my `.idea` folder too. It was probably holding some cache there too
