### ISSUE TITLE
Android internal distribution build fail for sdk45

### ISSUE THREAD

**Issue by ramiel1999** [expo/expo#17253] opened 2022-04-28 12:52 UTC
### Summary

I am trying to build an android preview using eas build -p android --profile preview, however, the build fails. The build fails in  "run gradlew". 
Here is the last thing that was outputted: 
```
> Task :expo-manifests:compileReleaseKotlin

w: /home/expo/workingdir/build/node_modules/expo-manifests/android/src/main/java/expo/modules/manifests/core/BaseLegacyManifest.kt: (10, 86): 'getLegacyID(): String' is deprecated. Prefer scopeKey or projectId depending on use case

w: /home/expo/workingdir/build/node_modules/expo-manifests/android/src/main/java/expo/modules/manifests/core/BaseLegacyManifest.kt: (12, 72): 'getStableLegacyID(): String?' is deprecated. Overrides deprecated member in 'expo.modules.manifests.core.Manifest'. Prefer scopeKey or projectId depending on use case

w: /home/expo/workingdir/build/node_modules/expo-manifests/android/src/main/java/expo/modules/manifests/core/Manifest.kt: (28, 12): 'getRawJson(): JSONObject' is deprecated. Prefer to use specific field getters

> Task :expo-manifests:javaPreCompileRelease

> Task :expo-manifests:compileReleaseJavaWithJavac

> Task :expo-manifests:bundleLibCompileToJarRelease

> Task :expo-dev-menu:compileReleaseKotlin

[stderr] e: /home/expo/workingdir/build/node_modules/expo-dev-menu/android/src/main/java/expo/modules/devmenu/modules/internals/DevMenuInternalFontManagerModule.kt: (11, 20): Unresolved reference: loadFonts

> Task :expo-dev-menu:compileReleaseKotlin FAILED

[stderr] FAILURE: Build failed with an exception.

[stderr] * What went wrong:

[stderr] Execution failed for task ':expo-dev-menu:compileReleaseKotlin'.

[stderr] > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

[stderr] > Compilation error. See log for more details

[stderr] * Try:

[stderr] > Run with --stacktrace option to get the stack trace.

[stderr] > Run with --info or --debug option to get more log output.

[stderr] > Run with --scan to get full insights.

[stderr] * Get more help at https://help.gradle.org

[stderr] BUILD FAILED in 12m 17s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^45.0.0-beta.8 => 45.0.0-beta.8
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.1 => 0.68.1
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

It is a full on project. I am not sure I am able to provide a small reproducible. I hope the log from "run gradlew" is enough

**Comment by thespacemanatee** [comment] 2022-04-28 14:37
Getting this on Expo 45 beta too

**Comment by ramiel1999** [comment] 2022-04-28 16:05
> See #17241

alright so how can I fix it from my side?

**Comment by ramiel1999** [comment] 2022-04-28 16:06
it says merged 7 hours ago. Shouldnt I not get an error?

**Comment by wodin** [comment] 2022-04-28 16:29
Looks like it works:

```
[RUN_GRADLEW] > Task :expo-dev-menu:compileReleaseKotlin
[RUN_GRADLEW] w: /private/var/folders/kj/rwm7htb51n18wlz4pbljb75w0000gn/T/eas-build-local-nodejs/08559db0-f534-4b81-84b5-36841617557c/build/node_modules/expo-dev-menu/android/src/main/java/expo/modules/d'
[RUN_GRADLEW] w: /private/var/folders/kj/rwm7htb51n18wlz4pbljb75w0000gn/T/eas-build-local-nodejs/08559db0-f534-4b81-84b5-36841617557c/build/node_modules/expo-dev-menu/android/src/main/java/expo/modules/da
[RUN_GRADLEW] w: /private/var/folders/kj/rwm7htb51n18wlz4pbljb75w0000gn/T/eas-build-local-nodejs/08559db0-f534-4b81-84b5-36841617557c/build/node_modules/expo-dev-menu/android/src/main/java/expo/modules/da
[RUN_GRADLEW] w: /private/var/folders/kj/rwm7htb51n18wlz4pbljb75w0000gn/T/eas-build-local-nodejs/08559db0-f534-4b81-84b5-36841617557c/build/node_modules/expo-dev-menu/android/src/release/java/expo/module.
[RUN_GRADLEW] w: /private/var/folders/kj/rwm7htb51n18wlz4pbljb75w0000gn/T/eas-build-local-nodejs/08559db0-f534-4b81-84b5-36841617557c/build/node_modules/expo-dev-menu/android/src/release/java/expo/module.
[RUN_GRADLEW] w: /private/var/folders/kj/rwm7htb51n18wlz4pbljb75w0000gn/T/eas-build-local-nodejs/08559db0-f534-4b81-84b5-36841617557c/build/node_modules/expo-dev-menu/android/src/release/java/expo/moduled
[RUN_GRADLEW] w: /private/var/folders/kj/rwm7htb51n18wlz4pbljb75w0000gn/T/eas-build-local-nodejs/08559db0-f534-4b81-84b5-36841617557c/build/node_modules/expo-dev-menu/android/src/release/java/expo/moduled
[RUN_GRADLEW] w: /private/var/folders/kj/rwm7htb51n18wlz4pbljb75w0000gn/T/eas-build-local-nodejs/08559db0-f534-4b81-84b5-36841617557c/build/node_modules/expo-dev-menu/android/src/release/java/expo/moduled
[RUN_GRADLEW] > Task :expo-dev-menu:compileReleaseJavaWithJavac
```

**Comment by ramiel1999** [comment] 2022-04-28 16:33
I was kinda trying again when I saw that it was marged, but I understand they need to publish it, but now I got a new error 
```

> Task :react-native-gradle-plugin:compileJava

[stderr] Note: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/java/com/facebook/react/codegen/generator/SchemaJsonParser.java uses or overrides a deprecated API.

[stderr] Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-gradle-plugin:pluginDescriptors

> Task :react-native-gradle-plugin:processResources

> Task :react-native-gradle-plugin:classes

> Task :react-native-gradle-plugin:inspectClassesForKotlinIC

> Task :react-native-gradle-plugin:jar

> Configure project :app

Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.

> Configure project :expo-structured-headers

Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Configure project :react-native-reanimated

****************************************************************************************

[stderr] FAILURE: Build completed with 2 failures.

[stderr] 1: Task failed with an exception.

[stderr] -----------

[stderr] * Where:

[stderr] Build file '/home/expo/workingdir/build/node_modules/react-native-reanimated/android/build.gradle' line: 99

[stderr] * What went wrong:

[stderr] A problem occurred evaluating project ':react-native-reanimated'.

[stderr] > No such property: minor for class: java.lang.String

[stderr] * Try:

[stderr] > Run with --stacktrace option to get the stack trace.

[stderr] > Run with --info or --debug option to get more log output.

[stderr] > Run with --scan to get full insights.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

6 actionable tasks: 6 executed

Unable to list file systems to check whether they can be watched. The whole state of the virtual file system has been discarded. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)

[stderr] ==============================================================================

[stderr] 2: Task failed with an exception.

[stderr] -----------

[stderr] * What went wrong:

[stderr] A problem occurred configuring project ':expo'.

[stderr] > compileSdkVersion is not specified. Please add it to build.gradle

[stderr] * Try:

[stderr] > Run with --stacktrace option to get the stack trace.

[stderr] > Run with --info or --debug option to get more log output.

[stderr] > Run with --scan to get full insights.

[stderr] ==============================================================================

[stderr] * Get more help at https://help.gradle.org
```

**Comment by wodin** [comment] 2022-04-28 17:06
I can confirm that applying the patch with `patch-package` does fix the font issue.

@ramiel1999 Did you use `patch-package` too? Or else how did you get past this issue to the other issue you mention above?

I think it would be better to create a new issue for this new problem.

**Comment by ramiel1999** [comment] 2022-04-28 17:07
actually i didnt get past the first issue. This one suddenly came as soon as run gradlew starts. Will try again and if persists will oepn an issue

**Comment by lukmccall** [comment] 2022-04-29 13:27
This issue was fixed by https://github.com/expo/expo/pull/17241. Version with that fix will be published soon ;)

**Closed by lukmccall** 2022-04-29 13:27 UTC
Labels: needs review

**Comment by mariomurrent-softwaresolutions** [comment] 2022-05-02 09:10
> This issue was fixed by #17241. Version with that fix will be published soon ;)

is it already published? Still getting this error

**Comment by wodin** [comment] 2022-05-02 17:14
hmmm... looks like the change (and another one) are not yet released. @lukmccall, any chance of getting a new release of expo-dev-menu with this change?

**Comment by mariomurrent-softwaresolutions** [comment] 2022-05-02 17:15
Well I'm not using  the expo-dev-menu plugin but I'm getting the same error

**Comment by wodin** [comment] 2022-05-02 17:28
It gets installed automatically when you install `expo-dev-client`:

```
% yarn why expo-dev-menu
yarn why v1.22.18
[1/4] 🤔  Why do we have the module "expo-dev-menu"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "expo-dev-menu@0.10.4"
info Reasons this module exists
   - "expo-dev-client" depends on it
   - Hoisted from "expo-dev-client#expo-dev-menu"
   - Hoisted from "expo-dev-client#expo-dev-launcher#expo-dev-menu"
info Disk size without dependencies: "83.99MB"
info Disk size with unique dependencies: "86.94MB"
info Disk size with transitive dependencies: "92.75MB"
info Number of shared dependencies: 53
✨  Done in 0.30s.
```

```
% npm why expo-dev-menu
expo-dev-menu@0.10.4
node_modules/expo-dev-menu
  expo-dev-menu@"0.10.4" from expo-dev-client@0.9.3
  node_modules/expo-dev-client
    expo-dev-client@"~0.9.3" from the root project
  expo-dev-menu@"0.10.4" from expo-dev-launcher@0.11.3
  node_modules/expo-dev-launcher
    expo-dev-launcher@"0.11.3" from expo-dev-client@0.9.3
    node_modules/expo-dev-client
      expo-dev-client@"~0.9.3" from the root project
```

**Comment by ramiel1999** [comment] 2022-05-02 22:15
@lukmccall I hope we can get  an update to continue testing SDK45 beta. I cant get passed this still

**Comment by wodin** [comment] 2022-05-02 23:06
@ramiel1999 as a temporary workaround until a new version of `expo-dev-menu` is released you can use [`patch-package`](https://www.npmjs.com/package/patch-package).

Basically, put the following file in a `patches` directory:

`patches/expo-dev-menu+0.10.4.patch`:
```diff
diff --git a/node_modules/expo-dev-menu/CHANGELOG.md b/node_modules/expo-dev-menu/CHANGELOG.md
index c520c5b..f99c169 100644
--- a/node_modules/expo-dev-menu/CHANGELOG.md
+++ b/node_modules/expo-dev-menu/CHANGELOG.md
@@ -8,6 +8,8 @@
 
 ### 🐛 Bug fixes
 
+- Fix `unresolved reference: loadFonts` in the release build on Android. ([#17241](https://github.com/expo/expo/pull/17241) by [@lukmccall](https://github.com/lukmccall))
+
 ### 💡 Others
 
 ## 0.10.4 — 2022-04-26
diff --git a/node_modules/expo-dev-menu/android/src/release/java/expo/modules/devmenu/DevMenuManager.kt b/node_modules/expo-dev-menu/android/src/release/java/expo/modules/devmenu/DevMenuManager.kt
index 6ed5309..1eb2a06 100644
--- a/node_modules/expo-dev-menu/android/src/release/java/expo/modules/devmenu/DevMenuManager.kt
+++ b/node_modules/expo-dev-menu/android/src/release/java/expo/modules/devmenu/DevMenuManager.kt
@@ -7,6 +7,7 @@ import android.view.MotionEvent
 import com.facebook.react.ReactInstanceManager
 import com.facebook.react.ReactNativeHost
 import com.facebook.react.bridge.ReadableMap
+import com.facebook.react.bridge.ReactApplicationContext
 import expo.interfaces.devmenu.DevMenuDelegateInterface
 import expo.interfaces.devmenu.DevMenuManagerInterface
 import expo.interfaces.devmenu.DevMenuPreferencesInterface
@@ -114,6 +115,10 @@ object DevMenuManager : DevMenuManagerInterface {
     throw IllegalStateException(DEV_MENU_IS_NOT_AVAILABLE)
   }
 
+  fun loadFonts(applicationContext: ReactApplicationContext) {
+    throw IllegalStateException(DEV_MENU_IS_NOT_AVAILABLE)
+  }
+
   override val coroutineScope: CoroutineScope
     get() = throw IllegalStateException(DEV_MENU_IS_NOT_AVAILABLE)
 }
```

Add a `post-install` script to `package.json`:

```json
"scripts": {
  "postinstall": "patch-package"
}
```

Then install `patch-package` and if you're using `yarn`, also install `postinstall-postinstall`. I'd install these as dev dependencies.

Then you should be able to build.

**Comment by lukmccall** [comment] 2022-05-04 07:44
A new version of the dev menu should be available today or tomorrow. I'm really sorry that you have to wait for that patch.

**Comment by nikodunk** [comment] 2022-05-10 23:31
Hey there! I'm running into this with the current release of a managed Expo 45 project. Any updates on getting this update out by any chance?

**Comment by brentvatne** [comment] 2022-05-10 23:38
@nikodunk - the update is out - what version of expo-dev-client is installed in your project? the latest is 0.9.5

**Comment by nikodunk** [comment] 2022-05-10 23:49
Very sorry for the false alarm! My error looks nearly identical, but I'm all up to date with my dependencies and am not using expo-dev-client. Eas appears to be getting stuck on Maven or Unimodules in my case. Worked perfectly in Expo 44.

I should probably open a new thread, but just in case it's related:
```
> Configure project :app

Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.

[stderr] FAILURE: Build completed with 2 failures.

[stderr] 1: Task failed with an exception.

[stderr] -----------

[stderr] * Where:

[stderr] Build file '/home/expo/workingdir/build/src/mobile/node_modules/@unimodules/core/android/build.gradle' line: 3

[stderr] * What went wrong:

[stderr] A problem occurred evaluating project ':unimodules-core'.

[stderr] > Plugin with id 'maven' not found.

[stderr] * Try:

[stderr] > Run with --stacktrace option to get the stack trace.

[stderr] > Run with --info or --debug option to get more log output.

[stderr] > Run with --scan to get full insights.

[stderr] ==============================================================================

[stderr] 2: Task failed with an exception.

[stderr] -----------

[stderr] * What went wrong:

[stderr] A problem occurred configuring project ':expo'.

[stderr] > compileSdkVersion is not specified. Please add it to build.gradle

[stderr] * Try:

[stderr] > Run with --stacktrace option to get the stack trace.

[stderr] > Run with --info or --debug option to get more log output.

[stderr] > Run with --scan to get full insights.

[stderr] ==============================================================================

[stderr] * Get more help at https://help.gradle.org

[stderr] BUILD FAILED in 2m 23s
```

**Comment by nikodunk** [comment] 2022-05-11 00:33
How peculiar. I removed `expo-screen-capture` and it's now building fine on Android for Managed SDK 45. I can reproducibly get it to fail/succeed by putting it in and taking it out.

Thank you for the awesome work and sorry to hijack the thread. Good luck everyone!

**Comment by nikodunk** [comment] 2022-05-13 16:56
`expo doctor` is what caught it, `expo upgrade` did not. I haven't got the
`expo doctor` output any more right now sorry - we went back to Expo 44 for
now due to https://github.com/expo/expo/issues/17478

**Comment by karlhorky** [comment] 2022-05-14 16:13
@wodin yeah same for me, `expo doctor --fix-dependencies` upgraded the dependencies, where `expo upgrade` missed them.

Wonder if this is maybe because the last upgrade from `expo upgrade` was moving from Expo SDK 44 to 45.... 🤔 Maybe in that case, `expo upgrade` does not also upgrade the dependencies? Maybe it would have done so if I ran it a second time... 🤔

In any case, now I added `expo doctor --fix-dependencies` to my CRON workflow: [upleveled/hotline-bling-codealong@`bacacb2` (#47)](https://github.com/upleveled/hotline-bling-codealong/pull/47/commits/bacacb2c9746fe54cf7149555a56ec5568b5021d)

**Comment by wodin** [comment] 2022-05-15 09:29
> Maybe in that case, `expo upgrade` does not also upgrade the dependencies?

No, it does update Expo dependencies when you upgrade to a new SDK and prints out a list of the upgraded dependencies. But I think there were some things that were updated after the initial SDK 45 release to fix bugs, so if you ran the upgrade again after those fixes it would have updated to the fixed versions. I suspect that's what happened.
