### ISSUE TITLE
Height calculation incorrect with minHeight with wrapped flex items

### ISSUE THREAD

**Issue by Delph** [expo/expo#11619] opened 2021-01-13 18:22 UTC
### Summary of Issue 
When setting `minHeight` on a container which has flex children, it appears as though the final height is `minHeight` plus the height of the children nodes. I noticed this on Android, and it happens Snack with iOS. The problem does not occur in web.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 4.0.17 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 10.19.0 - /usr/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.4 - /usr/bin/npm
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed
```
Android and iOS

### Reproducible Demo
https://snack.expo.io/nK4_KuBiF
 
### Steps to Reproduce
Create a container to hold a set of items, set `flexWrap: 'wrap'` and `flexDirection: 'row'` on the container. Set a `minHeight` on the container.
Containers which have items to make up a height bigger than `minHeight` are larger than the items they contain.

In some testing just now, this doesn't happen if the container is `flexDirection: 'column'` or if there's no wrapping. I suspect when calculating the container size, the items are laid out stacked in a column when they shouldn't be.

### Expected Behavior vs Actual Behavior
In the provided Snack, I expected the height of the second container to be 40px, matching the height of the first container, which it does on web.

**Comment by AdamJNavarro** [comment] 2021-01-18 00:35
hey @Delph, this seems likely to fall under the react-native umbrella rather than being an expo-specific issue. I'm going to close this issue but if you can't reproduce the issue in a vanilla react native project and it only occurs within an expo project we can re-open and investigate!

Cheers,
Adam

**Closed by AdamJNavarro** 2021-01-18 00:35 UTC
Labels: needs review
