### ISSUE TITLE
[iOS] staysActiveInBackground not working

### ISSUE THREAD

**Issue by alejomendoza** [expo/expo#5204] opened 2019-08-06 21:31 UTC
### Environment

 Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - ~/.nodenv/versions/8.9.4/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nodenv/versions/8.9.4/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.19 => 16.8.23 
      @types/react-native: ^0.57.60 => 0.57.65 
      expo: ^34.0.1 => 34.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.21.2

Target: iOS Client

### Steps to Reproduce

Added `staysActiveInBackground: true`:
```
 await Audio.setAudioModeAsync({
        playsInSilentModeIOS: true,
        allowsRecordingIOS: false,
        staysActiveInBackground: true,
        interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DUCK_OTHERS,
        shouldDuckAndroid: true,
        interruptionModeAndroid: Audio.INTERRUPTION_MODE_IOS_DUCK_OTHERS,
        playThroughEarpieceAndroid: false,
      });
```
and

```
"infoPlist": {
   "UIBackgroundModes": ["audio"]
 }
```

### Expected Behavior

When locking the screen on iOS, sound should continue playing. 

### Actual Behavior

When locking the screen on iOS, sound stops. 

### Reproducible Demo

1. https://expo.io/@skyhitz/skyhitz
2. Open the app on an iOS expo client
3. Sign up with any email / password
4. Search for D.S.P
5. Play video
6. Lock screen
7. Audio stops

**Comment by vikash-gupta** [comment] 2019-09-02 15:24
Here is my problem on my audio player app based on 
https://github.com/expo/playlist-example

- Run app from Expo client- audio works

- Lock the screen- audio still works

- [Problem] Now when a audio finishes, next track doesn't start. However when I unlock the screen and open Expo client again it starts.

- [Works fine] If screen is not locked and track finishes, next track starts without problem.

Expected behavior is that on locked screen as well, next track should start.

Additional details- on my iPhone 6, the expo client ->Diagnostics ->Audio Player also stops on screen lock. It resumes as soon as I unlock the phone.

This seems to be bug in Expo. Please advise!

**Comment by cruzach** [comment] 2019-10-15 17:14
Closing since this is a duplicate of https://github.com/expo/expo/issues/5472, which has a Snack repro

**Closed by cruzach** 2019-10-15 17:14 UTC
Labels: Audio, bug, project: ios-runtime
