### ISSUE TITLE
Error Configuration with name 'compileClasspath' not found while trying to create release apk after updating ExpoKit from SDk 32 to SDK 33

### ISSUE THREAD

**Issue by Luckygirlllll** [expo/expo#5064] opened 2019-07-24 15:12 UTC
### Environment

Expo CLI 3.0.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.2.1 => 3.2.1 
    npmGlobalPackages:
      expo-cli: 3.0.2

ExpoKit Android 

### Steps to Reproduce

Upgrade ExpoKit SDK from 32 to 33
Try to create release apk, get an error: "Error Configuration with name 'compileClasspath' not found"

### Expected Behavior

Can create release apk

**Comment by satriapr** [comment] 2019-07-25 04:47
I have the same issue, upgrading expo from 30 to 33 and expokit to 33.0.4

**Comment by Luckygirlllll** [comment] 2019-07-25 08:37
@satriapr I was able to create app bundle, however, when I installed app bundle images aren't displayed in the app, and map doesn't work.

**Comment by cruzach** [comment] 2019-07-26 18:51
Hey guys, 

Could you go over the upgrade steps for [Expo](https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c) **and** [Expokit](https://docs.expo.io/versions/latest/expokit/expokit/#upgrading-expokit) and make sure you've followed each? I've seen a few apps make this same upgrade successfully so I don't think this is a bug with Expo, but I could be wrong so if you go through those steps again and still get the same behavior, let me know how I can reproduce on my end

**Comment by Luckygirlllll** [comment] 2019-07-26 18:55
@cruzach I followed all steps, and I have already checked everything few times, so I‘m pretty sure that there is a problem with Expo/ExpoKit. 

However, I‘m able to create app bundle without any errors, but all images and icons are not displayed in the app after the upgrade.

**Comment by cruzach** [comment] 2019-07-26 18:58
Could you share the fix you found for this issue here and close? Then we will continue with thise problem:

> but all images and icons are not displayed in the app after the upgrade.

on the [other issue you created](https://github.com/expo/expo/issues/5068)

**Comment by Luckygirlllll** [comment] 2019-07-26 19:01
@cruzach this issue is not fixed, it‘s possible to create app bundle, but not possible to create apk.

**Comment by profimedica** [comment] 2020-06-12 01:23
```
configurations {
    compileClasspath
}
buildscript {
    repositories {
        ...
    }

    dependencies {
        ...
    }
}
```

**Comment by tsapeta** [comment] 2020-07-09 08:29
I'm closing this issue since we no longer support using ExpoKit (SDK38 was the last release of ExpoKit) and the bug report was made for pretty old versions SDK32/33. If you're still experiencing this in SDK38 then please open a new bug report, but I encourage you to use bare workflow instead of ExpoKit – it gives you more control on what's being installed, the configuration and so on.

**Closed by tsapeta** 2020-07-09 08:29 UTC
Labels: Android, ExpoKit, needs repro
