### ISSUE TITLE
Error with getExpoPushTokenAsync() only in Android 

### ISSUE THREAD

**Issue by hatim85f** [expo/expo#18628] opened 2022-08-12 15:52 UTC
### Summary

I am still in the development mode and suddenly out of nowhere I got this error with expo-notifications, the device ( android only)

> [expo-notifications] Error encountered while updating server registration with latest device push token., [Error: Fetching the token failed: Please set your Project ID. A valid Firebase Project ID is required to communicate with Firebase server APIs: It identifies your application with Firebase.Please refer to https://firebase.google.com/support/privacy/init-options.]

>[Unhandled promise rejection: Error: Fetching the token failed: Please set your Project ID. A valid Firebase Project ID is required to communicate with Firebase server APIs: It identifies your application with Firebase.Please refer to https://firebase.google.com/support/privacy/init-options.]

Although everything was working fine and I didn't touch or update any of firebase config or installation neither expo SDK

### What platform(s) does this occur on?

Android

### Environment

 System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 26, 28, 29, 30
        Build Tools: 29.0.2, 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Minimal reproducible example

```
 const [expoPushToken, setExpoPushToken] = useState("");
  const [notification, setNotification] = useState(false);
  const notificationListener = useRef();
  const responseListener = useRef();
```

```
export const registerForPushNotificationsAsync = async () => {
  let token;
  if (Device.isDevice) {
    const { status: existingStatus } =
      await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;
    if (existingStatus !== "granted") {
      const { status } = await Notifications.requestPermissionsAsync();
      finalStatus = status;
    }
    if (finalStatus !== "granted") {
      alert("Failed to get push token for push notification!");
      return;
    }
    token = (await Notifications.getExpoPushTokenAsync()).data;
    console.log(token);
  } else {
    alert("Must use physical device for Push Notifications");
  }

  if (Platform.OS === "android") {
    Notifications.setNotificationChannelAsync("default", {
      name: "default",
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: "#FF231F7C",
    });
  }

  return token;
};
```

```
 useEffect(() => {
    registerForPushNotificationsAsync().then((token) =>
      setExpoPushToken(token)
    );
    notificationListener.current =
      Notifications.addNotificationReceivedListener((notification) => {
        setNotification(notification);
      });

    responseListener.current =
      Notifications.addNotificationResponseReceivedListener((response) => {
        handleResponse(response);
      });

    return () => {
      Notifications.removeNotificationSubscription(
        notificationListener.current
      );
      Notifications.removeNotificationSubscription(responseListener.current);
    };
  }, []);
```

**Comment by iM-GeeKy** [comment] 2022-08-12 15:55
Might be a duplicate of https://github.com/expo/expo/issues/18570

**Comment by forki** [comment] 2022-08-12 17:47
duplicate of https://github.com/expo/expo/issues/18570

**Comment by brentvatne** [comment] 2022-08-12 20:22
thanks for the report! indeed a duplicate of #18570 - we will investigate this

**Closed by brentvatne** 2022-08-12 20:22 UTC
Labels: needs review

**Comment by NicolasPotierA** [comment] 2022-08-15 03:25
Pero esto si  se debe al error de la versión de expo, ya que en el otro bug aparece como si este fuera de otra causa?
