### ISSUE TITLE
[expo-web-browser]swiper right turn off WebBrowser, can not open again. This bug still exist since 2017.

### ISSUE THREAD

**Issue by imwilliamxy** [expo/expo#8717] opened 2020-06-08 04:29 UTC
### Summary of Issue  

When use genture swiper right turn off WebBrowser, it can not open again. 
Error message: Another WebBrowser is already being presented
This web brwoser bug since 2017 still exist.

https://github.com/expo/expo/issues/135

### Environment 
Expo CLI 3.15.4 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.15.4

### Steps to Reproduce  (from https://github.com/expo/expo/issues/135#issue-224541880)
1. trigger open WebBrowser
2. swipe right from the left edge
3. notice WebBrowser will go away
4. trigger open WebBrowser again
5. notice warning "Another WebBrowser is already being presented." and WebBrowser cannot open afterwards

code:
```javasctipt
async function openLink(url) {
  try {
    await WebBrowser.openBrowserAsync(url);
  } catch(err) {
    console.log("openLink error:",err)
    try {
      await WebBrowser.dismissBrowser();
    } catch(err) {
      console.log('Could not dismiss  browser:', err);
    }
    try {
      await WebBrowser.openBrowserAsync(url);
    } catch(err) {
      console.log('Could not reopen browser:', err);
    }

}
```

### Expected Behavior vs Actual Behavior
WebBrowser should open again after closed with swiper right gesture.

**Comment by cruzach** [comment] 2020-06-08 15:33
duplicate of https://github.com/expo/expo/issues/6918

**Closed by cruzach** 2020-06-08 15:33 UTC
Labels: Needs triage
