### ISSUE TITLE
Dev Client: No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.

### ISSUE THREAD

**Issue by elitenas** [expo/expo#22336] opened 2023-05-01 01:25 UTC
### Minimal reproducible example

https://github.com/haibert/SplashScreenIssue

### Summary

On Dev Client, we get the following warning on start up:

`No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.`

The application stays stuck on splash screen unless the `await SplashScreen.hideAsync();` is called twice.

This doesn't happen on an actual build but just happens on dev client.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
      Watchman: 2023.02.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.1 
      expo: ~48.0.11 => 48.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
      react-native-web: ~0.18.12 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.1.0
    Expo Workflow: managed

**Comment by Kudo** [comment] 2023-05-02 05:31
hi there! the minimal reproducible example you provided is a sdk 45 project which is inconsistent with the `expo-env-info` information you mentioned. could you double check for the repro?

**Comment by MacPiston** [comment] 2023-05-29 14:05
I have that too, but only during the first launch of the client on particular device - when bottom sheet appears. I just press reload and the problem never comes back on that device.

**Comment by maoryadin** [comment] 2023-06-25 13:59
Also for me..

**Comment by SophieJung7** [comment] 2023-08-11 05:07
Same problem too..I think this is nothing to do with splash screen though.

**Comment by SohelIslamImran** [comment] 2023-09-28 00:17
Same issue ++

**Comment by SohelIslamImran** [comment] 2023-09-28 00:20
@Kudo I have this issue in production ios app, in  "expo": "^49.0.9", "expo-splash-screen": "~0.20.5",
> No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.

**Comment by ph101pp** [comment] 2023-10-10 03:01
Seeing this error when bottom sheet is active. Bottom sheet can be dismissed but splashscreen stays visible. 
expo@49.00 and expo-splash-screen@0.22.0

**Comment by uzaymacar** [comment] 2023-10-30 14:11
Have the same warning with  `"expo-splash-screen": "^0.22.0"` and Expo SDK 49 -- very cryptic warning message too.

**Comment by takacskalman** [comment] 2023-11-07 20:09
The same for me with SDK 49 and splash screen 0.22 in IOS production app. Any updates on this?

**Comment by olarcher** [comment] 2024-02-05 23:10
Same with SDK 50.

**Comment by brian-pinwheel** [comment] 2024-02-22 14:47
I am having the same issue with Expo 50.0.6 and expo-splash-screen@0.26.4

**Comment by zackify** [comment] 2024-02-27 16:44
saaaame here, so many cases of it in our app 
<img width="263" alt="image" src="https://github.com/expo/expo/assets/449136/3dfff4f1-f51c-4d68-85c2-95f69ef0921d">

**Comment by pfcodes** [comment] 2024-03-06 23:28
this is one of the top events being sent to our sentry

<img width="1310" alt="Screenshot 2024-03-06 at 3 28 18 PM" src="https://github.com/expo/expo/assets/26803762/8f7e428b-f447-4542-abc2-79e6cdf451c3">

**Comment by uzaymacar** [comment] 2024-03-10 13:14
Just in case it helps, in our case we've found out that we were calling `hideAsync()` multiple times as opposed to a single time during app startup (when the app is ready).

```
const onLayoutRootView = useCallback(async () => {
    if (isAppReady) {
        await ExpoSplashScreen.hideAsync()
    }
}, [isAppReady])

return (
    <SafeAreaProvider onLayout={onLayoutRootView}>
        // Your app
    </SafeAreaProvider>
)
```

**Comment by cjones26** [comment] 2024-05-14 12:47
Still happening with Expo 51, only calling `hideAsync()` once.

**Comment by skdrew** [comment] 2024-07-10 15:36
I'm seeing this on a brand new project using expo-router (as expo-splash-screen is a dependency). I'm not calling any of the splash screen functions, it just happens.

**Comment by krisgerhard** [comment] 2024-10-08 17:02
Still an issue on production

**Comment by cip123** [comment] 2024-11-07 06:58
Thanks, @Maximization. I think I have the same problem. My Sentry reports show that the error happens in the background. Are you now calling `SplashScreen.preventAutoHideAsync()` conditionally when the app is in the foreground?

**Comment by Maximization** [comment] 2024-11-07 12:35
@cip123 I actually left it as is and marked it as low priority since user doesn't see the error and it doesn't affect the app.

I've just tested your suggestion and it actually seems to be the fix! I've had to add it in two places:

```js
// App.tsx
if (AppState.currentState === "active") {
  SplashScreen.preventAutoHideAsync()
}

function IgniteApp() {
  return <App hideSplashScreen={SplashScreen.hideAsync} />
}
```
```js
// app.tsx
function App(props: AppProps) {
  const { hideSplashScreen } = props

  const { rehydrated } = useInitialRootStore(() => {
    if (AppState.currentState === "active") {
      setTimeout(hideSplashScreen, 500)
    }
  })
}
```

Thanks!

**Comment by trajano** [comment] 2024-11-10 18:00
If @Maximization  your check on App state is the correct one that logic should ideally be embedded in preventAutohideAsync itself.

**Comment by cip123** [comment] 2024-11-11 16:49
@Maximization  there are two possible issues.
1 - In my tests for Android, the Splashscreen starts displaying in the background
2.- If the application goes to the background when the splash screen is loading, it will never be hidden. 

I ended up keeping the original logic but catching the error and sending it to Sentry only if the application was in the foreground.

**Comment by vinmvn** [comment] 2024-11-18 18:05
This issue occurs exclusively on iOS (using Expo version `^51.0.39` and splash screen version `~0.27.7`). It does NOT happen when you quit the simulator and run `npm run ios`, but it consistently occurs every time you refresh the app or run `npm run ios` without quitting the iOS simulator.

**Comment by powderham** [comment] 2024-11-28 10:16
For my my problem was I was returning a `<View />` instead of `null` when the app wasn't ready

From
```
  useEffect(() => {
    if (loaded) {
      SplashScreen.hideAsync();
    }
  }, [loaded]);

  if (!loaded) {
    return <View />;
  }
```

to 

```
  useEffect(() => {
    if (loaded) {
      SplashScreen.hideAsync();
    }
  }, [loaded]);

  if (!loaded) {
    return null;
  }
```

**Comment by robertcreanerel** [comment] 2024-11-28 14:56
I encountered the same warning when trying to handle the splash screen logic within the <AppInner /> instead of the root <App />. 

The warning was related to the asynchronous nature of the splash screen handling, which was not being managed correctly within the component's lifecycle.

Solution:
I moved the splash screen handling logic to the root of the app component. This ensures that the splash screen is managed correctly before the app's main content is rendered.

**Comment by trajano** [comment] 2024-11-28 21:17
@powderham your approach works well in the _layout.tsx

```typescript
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    let mounted = true;
    (async () => {
      // all async stuff
      if (mounted) {
        setLoaded(true);
     }
    })();
    return () => {
      mounted = false; // this ensures that the setLoaded doesn't get called if there's a problem 
         // and the component was unmounted already
    };
  }, [deps for the async stuff]);

  useEffect(() => {
    if (loaded) {
      SplashScreen.hideAsync();
    }
  }, [loaded]);

  if (!loaded) {
    return null;
  }
  return (<Stack>...</Stack>)
```

**Comment by lucksp** [comment] 2024-12-05 22:26
I am seeing this now since updating to:`"expo": "~51.0.39",`

```
export default function Layout() {
  const { fontScale } = useWindowDimensions();

  const [fontsLoaded, fontError] = useFonts({
    Inter_400Regular,
    DMSans_400Regular,
    DMSans_700Bold,
    DMSans_500Medium,
  });
  if (fontError) {
    Bugsnag.notify({ name: 'useFonts error', message: fontError.message });
  }

  useEffect(() => {
    if (fontsLoaded) {
      SplashScreen.hideAsync();
    }
  }, [fontsLoaded]);

  if (!fontsLoaded) return null;

  return (
    <Global>
     <Stack />
   </Global>);
}
```

**Comment by DAVIS-PYTH** [comment] 2024-12-06 14:53
same here with @lucksp 
just updated to `expo@~51.0.39` and I'm getting this error

**Comment by brentvatne** [comment] 2024-12-06 19:36
this is fixed on sdk 52 with https://github.com/expo/expo/pull/33236

@alanjhughes - perhaps worth backporting?

**Closed by brentvatne** 2024-12-06 19:36 UTC
Labels: outdated, needs review

**Comment by trajano** [comment] 2024-12-09 11:45
@lucksp  @DAVIS-PYTH  on simulator or devclient on real device (android or ios)? The fix on #33236 is specifically on iOS Simulator

**Comment by lucksp** [comment] 2024-12-09 13:49
> @lucksp @DAVIS-PYTH on simulator or devclient on real device (android or ios)? The fix on #33236 is specifically on iOS Simulator

Device for me.

**Comment by trajano** [comment] 2024-12-09 13:52
So #33236  won't resolve your problem as it is specifically talking about Simulator https://github.com/expo/expo/pull/33236/files#diff-4cdc193af6471e04ea5d61bc1d5e290504dec6c7fecb4e74c6e94ff95439e54bR74

> this is fixed on sdk 52 with #33236
> 
> @alanjhughes - perhaps worth backporting?

**Comment by frankfuu** [comment] 2024-12-12 02:53
Anyone know if we can suppress this warning until we upgrade to SDK 52?

**Comment by appsgenie** [comment] 2024-12-24 04:09
I see that there is a fix for simulator, but I am still seeing this in Sentry on iOS in production builds sporadically.
Is this still an outstanding issue? Sorry if I was not able to pickup on a summary from all of the above.
`No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first`

**Comment by ps-george** [comment] 2025-01-08 16:21
Got this with `expo-splash-screen=0.27.6` and `expo=51.0.3`.

On iOS simulator, not sure if also on device.

**Comment by ansmlc** [comment] 2025-03-22 15:49
Same here.

> I am seeing this now since updating to:`"expo": "~51.0.39",` from `expo@^51.0.0: version "51.0.36"`
> 
> I based my actual splash screen on the [official Expo Example](https://github.com/expo/examples/tree/master/with-splash-screen)
> 
> ```
> SplashScreen.preventAutoHideAsync();
> 
> 
> export default function Layout() {
>   const { fontScale } = useWindowDimensions();
> 
>   const [fontsLoaded, fontError] = useFonts({
>     Inter_400Regular,
>     DMSans_400Regular,
>     DMSans_700Bold,
>     DMSans_500Medium,
>   });
>   if (fontError) {
>     Bugsnag.notify({ name: 'useFonts error', message: fontError.message });
>   }
> 
>   useEffect(() => {
>     if (fontsLoaded) {
>       SplashScreen.hideAsync();
>     }
>   }, [fontsLoaded]);
> 
>   if (!fontsLoaded) return null;
> 
>   return (
>     <Global>
>      <Stack />
>    </Global>);
> }
> ```
