### ISSUE TITLE
[SDK52][expo-modules] enabling `useFrameworks` causes build issues on iOS

### ISSUE THREAD

**Issue by leonhh** [expo/expo#32142] opened 2024-10-18 08:51 UTC
### Minimal reproducible example

https://github.com/leonhh/expo-use-frameworks

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a standalone app

### Summary

I'm back with another `useFrameworks` issue 😄 

If you enable `useFrameworks` with expo-build-properties the iOS build will fail. This happens when using canary versions of expo.

```json
"plugins": [
  [
    "expo-build-properties",
    {
      "ios": {
        "useFrameworks": "static"
      }
    }
  ]
]
```

The error:
`my-app/node_modules/expo-modules-core/ios/AppDelegates/EXAppDelegateWrapper.mm:11:9 'ReactCommon/RCTHost.h' file not found`

I already tried to modify `ExpoModulesCore.podspec` to make it search for the headers in the right place but had no luck with this yet. 

## Reproducing

Clone the repository, run `npx expo prebuild`, run `npm run ios` 

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.11.0/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.0-canary-20241008-90b13ad => 52.0.0-canary-20241008-90b13ad 
      react: 18.3.1 => 18.3.1 
      react-native: 0.75.2 => 0.75.2 
    npmGlobalPackages:
      eas-cli: 10.0.0
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: expo-build-properties
Advice: 
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
```

**Comment by 0xDing** [comment] 2024-10-18 12:10
@leonhh A temporary hack solution is to edit the `ExpoModulesCore.podspec` file.

Add the following:
```rb
header_search_paths = []

  if ENV['USE_FRAMEWORKS']
    header_search_paths.concat([
      '"${PODS_CONFIGURATION_BUILD_DIR}/React-RuntimeApple/React_RuntimeApple.framework/Headers"',
      '"${PODS_CONFIGURATION_BUILD_DIR}/React-RuntimeCore/React_RuntimeCore.framework/Headers"',
      '"${PODS_CONFIGURATION_BUILD_DIR}/React-performancetimeline/React_performancetimeline.framework/Headers"',
      '"${PODS_CONFIGURATION_BUILD_DIR}/React-runtimescheduler/React_runtimescheduler.framework/Headers"',
      '"${PODS_CONFIGURATION_BUILD_DIR}/React-rendererconsistency/React_rendererconsistency.framework/Headers"',
    ])
  end
```

Then, in the `s.pod_target_xcconfig` section, add:
```rb
'HEADER_SEARCH_PATHS' => header_search_paths.join(' ')
```
This modification adds additional header search paths when using frameworks, which should help resolve some missing header issues in the build process.

**Comment by efstathiosntonas** [comment] 2024-10-22 07:49
@0xDing  thanks for the header paths but unfortunately won't solve the issue, still getting the `'ReactCommon/RCTHost.h' file not found`. I use cli with `expo-modules-core@2.0.0-preview.0`

**Comment by 0xDing** [comment] 2024-10-22 09:12
> @0xDing thanks for the header paths but unfortunately won't solve the issue, still getting the `'ReactCommon/RCTHost.h' file not found`. I use cli with `expo-modules-core@2.0.0-preview.0`
> 
> steps I followed with no luck:
> 
> 1. `pod deintegrate`
> 2. `rm -rf node_modules && rm yarn.lock`
> 3. Cleaned build folder and derived data on Xcode 16
> 4. reinstall everything and build again

If you've used `yarn patch`, it's crucial to verify that the patch has been correctly applied by checking the `node_modules/expo-modules-core/ExpoModulesCore.podspec` file. Keep in mind that `expo-modules-core` is typically an indirect dependency, which can complicate the patching process. There's a significant possibility that the patch hasn't been applied effectively, especially if your `package.json` `resolutions` aren't precisely matching the required versions. This mismatch in resolutions can sometimes prevent patches from being applied correctly to indirect dependencies.


Additionally, for the expo-modules-core@2.0.0-preview.0 version, you need to add the following line to the header_search_paths:

'"${PODS_CONFIGURATION_BUILD_DIR}/React-jserrorhandler/React_jserrorhandler.framework/Headers"',

The complete patch file (`expo-modules-core-npm-2.0.0-preview.0-5a76373981.patch`) is:
```
diff --git a/ExpoModulesCore.podspec b/ExpoModulesCore.podspec
index 246afe0163cf481dfd3381399b432e7826918397..6c46f97000e39bffbbc7bf87f274b97ccfdac9d0 100644
--- a/ExpoModulesCore.podspec
+++ b/ExpoModulesCore.podspec
@@ -6,6 +6,19 @@ unless defined?(install_modules_dependencies)
   require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
 end

+header_search_paths = []
+
+  if ENV['USE_FRAMEWORKS']
+    header_search_paths.concat([
+      '"${PODS_CONFIGURATION_BUILD_DIR}/React-RuntimeApple/React_RuntimeApple.framework/Headers"',
+      '"${PODS_CONFIGURATION_BUILD_DIR}/React-RuntimeCore/React_RuntimeCore.framework/Headers"',
+      '"${PODS_CONFIGURATION_BUILD_DIR}/React-performancetimeline/React_performancetimeline.framework/Headers"',
+      '"${PODS_CONFIGURATION_BUILD_DIR}/React-runtimescheduler/React_runtimescheduler.framework/Headers"',
+      '"${PODS_CONFIGURATION_BUILD_DIR}/React-rendererconsistency/React_rendererconsistency.framework/Headers"',
+      '"${PODS_CONFIGURATION_BUILD_DIR}/React-jserrorhandler/React_jserrorhandler.framework/Headers"',
+    ])
+  end
+
+
 package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

 reactNativeVersion = '0.0.0'
@@ -53,6 +66,7 @@ Pod::Spec.new do |s|
     'DEFINES_MODULE' => 'YES',
     'CLANG_CXX_LANGUAGE_STANDARD' => 'c++20',
     'SWIFT_COMPILATION_MODE' => 'wholemodule',
+    'HEADER_SEARCH_PATHS' => header_search_paths.join(' '),
     'OTHER_SWIFT_FLAGS' => "$(inherited) #{new_arch_enabled ? new_arch_compiler_flags : ''}"
   }
   s.user_target_xcconfig = {

```

**Comment by efstathiosntonas** [comment] 2024-10-22 09:21
@0xDing thanks for the heads up, I was putting this `'HEADER_SEARCH_PATHS' => header_search_paths.join(' '),` on `user_target_xcconfig` instead of `pod_target_xcconfig`. What an epic fail.... 

Now I got a different error, we made some progress haha:

![Screenshot 2024-10-22 at 12 18 32](https://github.com/user-attachments/assets/f4727ee0-5520-4614-8b03-f6e1e69769d7)


I guess I'll remove the `RCTHostDelegate` and set all to false since that's my case 😅 

```c
      [[RCTRootViewFactoryConfiguration alloc] initWithBundleURLBlock:bundleUrlBlock
                                                       newArchEnabled:false
                                                      turboModuleEnabled:false                                                 
                                                      bridgelessEnabled:false];
```

**Comment by 0xDing** [comment] 2024-10-22 14:19
> @0xDing thanks for the heads up, I was putting this `'HEADER_SEARCH_PATHS' => header_search_paths.join(' '),` on `user_target_xcconfig` instead of `pod_target_xcconfig`. What an epic fail....
> 
> Now I got a different error, we made some progress haha:
> 
> ![Screenshot 2024-10-22 at 12 18 32](https://private-user-images.githubusercontent.com/717975/378771888-f4727ee0-5520-4614-8b03-f6e1e69769d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDY5NzcsIm5iZiI6MTcyOTYwNjY3NywicGF0aCI6Ii83MTc5NzUvMzc4NzcxODg4LWY0NzI3ZWUwLTU1MjAtNDYxNC04YjAzLWY2ZTFlNjk3NjlkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxNDE3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzA4NjQ3YzY0ZjJhMDFkODljZjg0YzE5MmMxNzEyNmI3ZTcwM2FkYmJlYWEwOTliNWY2ODViNmUxNzQzYTc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QGb0IbzIkXETN3cw7XxHRumGMXli55lCV72SqV2zt_c)
> 
> I guess I'll remove the `RCTHostDelegate` for now and set all to false since that's my case 😅
> 
> ```c
>       [[RCTRootViewFactoryConfiguration alloc] initWithBundleURLBlock:bundleUrlBlock
>                                                        newArchEnabled:false
>                                                       turboModuleEnabled:false                                                 
>                                                       bridgelessEnabled:false];
> ```

SDK52 require react-native 0.76

**Comment by Kudo** [comment] 2024-10-25 06:45
i'm taking over this because it could be me to introduce the regression.

**Comment by matinzd** [comment] 2024-10-25 08:27
After applying the patch now I am getting this error:

```
at: node_modules/expo-dev-menu/ios/DevClientRootViewFactory.mm:19

'react/performance/timeline/PerformanceEntryReporter.h' file not found
```

**Comment by rorydbain** [comment] 2024-10-25 11:42
> After applying the patch now I am getting this error:
> 
> ```
> at: node_modules/expo-dev-menu/ios/DevClientRootViewFactory.mm:19
> 
> 'react/performance/timeline/PerformanceEntryReporter.h' file not found
> ```
> 
> Suspecting this PR:
> 
> https://github.com/expo/expo/pull/28702/files

You should be able to fix this similarly to how you've done by patching expo-modules-core. If you add `'"${PODS_CONFIGURATION_BUILD_DIR}/React-performancetimeline/React_performancetimeline.framework/Headers"',` to the header_search_paths list inside `expo-dev-menu.podspec`

**Comment by matinzd** [comment] 2024-10-25 11:47
Yep @rorydbain 
The fix is already merged https://github.com/expo/expo/commit/5b87ea295724bf5c5cb21f5e313d54e1250ed71e.

**Closed** 2024-10-28 08:04 UTC
Labels: needs review

**Comment by matinzd** [comment] 2024-10-28 09:20
Thanks @Kudo

**Comment by jaaywags** [comment] 2024-12-30 06:27
I know this is a bit unrelated, but I was getting the error you mentioned

> 'react/performance/timeline/PerformanceEntryReporter.h' file not found

I was able to fix this by removing the dependency, `expo-dev-client`. I had upgrade my expo version and could not get anything to build. Spinning up a new expo project and installing each dependency one at a time lead to me figuring out that package was causing the issue.

**Comment by Kudo** [comment] 2025-01-03 14:09
@jaaywags please help to create a new issue with a minimal repro. i could further investigate then. thanks!

**Comment by jaaywags** [comment] 2025-01-04 17:30
@Kudo I am not sure. I tried reproducing it with a fresh project but could not. Here is what changed in my package.json though.

```diff
{
  "name": "myapp",
  "main": "expo-router/entry",
  "version": "0.0.6",
  "scripts": {
    "clean-prebuild": "npx expo prebuild --clean",
    "prebuild": "npx expo prebuild",
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint",
    "env:local": "node scripts/set-environment.js local",
    "env:prod": "node scripts/set-environment.js prod",
    "env:stage": "node scripts/set-environment.js stage",
    "local-dev-ios-simulator-build": "eas build --profile development-simulator --platform ios --local"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@gorhom/bottom-sheet": "^4.6.4",
    "@invertase/react-native-apple-authentication": "^2.3.0",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-community/datetimepicker": "8.0.1",
    "@react-native-firebase/analytics": "^20.3.0",
    "@react-native-firebase/app": "^20.3.0",
    "@react-native-firebase/auth": "^20.3.0",
    "@react-native-firebase/crashlytics": "^20.3.0",
    "@react-native-firebase/messaging": "^20.3.0",
    "@react-native-google-signin/google-signin": "^12.2.1",
-   "@react-navigation/native": "^6.0.2",
+   "@react-navigation/native": "^7.0.14",
    "@reduxjs/toolkit": "^2.2.7",
    "@shopify/flash-list": "1.6.4",
    "axios": "^1.7.2",
    "buffer": "^6.0.3",
    "dayjs": "^1.11.12",
-   "expo": "^51.0.34",
+   "expo": "^52.0.23",
    "expo-apple-authentication": "~6.4.2",
    "expo-application": "~5.9.1",
-   "expo-build-properties": "~0.12.5",
+   "expo-build-properties": "~0.13.1",
    "expo-clipboard": "~6.0.3",
-   "expo-constants": "~16.0.2",
+   "expo-constants": "~17.0.3",
-   "expo-dev-client": "~4.0.27",
    "expo-device": "~6.0.2",
-   "expo-font": "~12.0.9",
+   "expo-font": "^13.0.2",
    "expo-image-picker": "~15.0.7",
    "expo-linear-gradient": "~13.0.2",
-   "expo-linking": "~6.3.1",
-   "expo-router": "~3.5.23",
-   "expo-splash-screen": "~0.27.6",
-   "expo-status-bar": "~1.12.1",
-   "expo-system-ui": "~3.0.7",
+   "expo-linking": "~7.0.3",
+   "expo-router": "^4.0.15",
+   "expo-splash-screen": "~0.29.18",
+   "expo-status-bar": "~2.0.0",
+   "expo-system-ui": "~4.0.6",
    "expo-updates": "~0.25.25",
-   "expo-web-browser": "~13.0.3",
+  "expo-web-browser": "~14.0.1",
    "flexsearch": "^0.7.43",
    "lodash": "^4.17.21",
    "moti": "^0.29.0",
-   "react": "18.2.0",
-   "react-dom": "18.2.0",
-   "react-native": "^0.75.3",
+   "react": "18.3.1",
+   "react-dom": "18.3.1",
+   "react-native": "0.76.5", 
    "react-native-gesture-handler": "2.20.0",
    "react-native-iap": "^12.15.2",
    "react-native-mime-types": "^2.5.0",
    "react-native-mmkv": "^3.0.2",
    "react-native-paper": "^5.12.5",
    "react-native-reanimated": "3.15.3",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "4.10.5",
-   "react-native-screens": "3.34.0",
+   "react-native-screens": "~4.4.0",
    "react-native-star-rating-widget": "^1.8.0",
    "react-native-svg": "^15.9.0",
    "react-native-toast-message": "^2.2.0",
    "react-native-uuid": "^2.0.2",
    "react-native-web": "~0.19.10",
    "react-redux": "^9.1.2",
    "redux-persist": "^6.0.0",
    "rusha": "^0.8.14",
    "serialize-error": "^11.0.3",
    "validator": "^13.12.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/crypto-js": "^4.2.2",
    "@types/jest": "^29.5.12",
    "@types/lodash": "^4.17.7",
-   "@types/react": "~18.2.45",
-   "@types/react-native": "^0.73.0",
-   "@types/react-test-renderer": "^18.0.7",
+   "@types/react": "~18.3.12",
+   "@types/react-test-renderer": "^18.3.0",
    "@types/rusha": "^0.8.3",
    "@types/validator": "^13.12.0",
    "babel-plugin-module-resolver": "^5.0.2",
    "jest": "^29.2.1",
-   "jest-expo": "~51.0.4",
+  "jest-expo": "~52.0.2",
    "react-native-svg-transformer": "^1.5.0",
-   "react-test-renderer": "18.2.0",
+   "react-test-renderer": "18.3.1",
    "typescript": "~5.3.3"
  },
+ "private": true
- "private": true,
- "expo": {
-   "install": {
-     "exclude": [
-       "react-native@~0.74.0",
-       "react-native-reanimated@~3.10.0",
-       "react-native-gesture-handler@~2.16.1",
-       "react-native-screens@~3.31.1"
-     ]
-   }
- }
}
```

**Comment by jaaywags** [comment] 2025-01-04 18:17
@Kudo I think I have repo steps now!

[The repo I reproduced it in](https://github.com/jaaywags/expo-51-issue)

Env:
- M3 Macbook on latest
- npm 10.5.2
- node v20.13.1
- I use volta for node versioning

Notes:
You may need to connect it to your apple account/expo account to get past some `expo-dev-client` stuff. Not sure.

1. Create a project `npx create-expo-app --template default@sdk-51`
2. Update package.json
```json
{
  "name": "myapp",
  "main": "expo-router/entry",
  "version": "0.0.6",
  "scripts": {
    "clean-prebuild": "npx expo prebuild --clean",
    "prebuild": "npx expo prebuild",
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint",
    "env:local": "node scripts/set-environment.js local",
    "env:prod": "node scripts/set-environment.js prod",
    "env:stage": "node scripts/set-environment.js stage",
    "local-dev-ios-simulator-build": "eas build --profile development-simulator --platform ios --local"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@gorhom/bottom-sheet": "^4.6.4",
    "@invertase/react-native-apple-authentication": "^2.3.0",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-community/datetimepicker": "8.0.1",
    "@react-native-firebase/analytics": "^20.3.0",
    "@react-native-firebase/app": "^20.3.0",
    "@react-native-firebase/auth": "^20.3.0",
    "@react-native-firebase/crashlytics": "^20.3.0",
    "@react-native-firebase/messaging": "^20.3.0",
    "@react-native-google-signin/google-signin": "^12.2.1",
    "@react-navigation/native": "^7.0.14",
    "@reduxjs/toolkit": "^2.2.7",
    "@shopify/flash-list": "1.6.4",
    "axios": "^1.7.2",
    "buffer": "^6.0.3",
    "dayjs": "^1.11.12",
    "expo": "^52.0.23",
    "expo-apple-authentication": "~6.4.2",
    "expo-application": "~5.9.1",
    "expo-build-properties": "~0.13.1",
    "expo-clipboard": "~6.0.3",
    "expo-constants": "~17.0.3",
    "expo-dev-client": "~4.0.27",
    "expo-device": "~6.0.2",
    "expo-font": "^13.0.2",
    "expo-image-picker": "~15.0.7",
    "expo-linear-gradient": "~13.0.2",
    "expo-linking": "~7.0.3",
    "expo-router": "^4.0.15",
    "expo-splash-screen": "~0.29.18",
    "expo-status-bar": "~2.0.0",
    "expo-system-ui": "~4.0.6",
    "expo-updates": "~0.25.25",
    "expo-web-browser": "~13.0.3",
    "flexsearch": "^0.7.43",
    "lodash": "^4.17.21",
    "moti": "^0.29.0",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.5",
    "react-native-gesture-handler": "2.20.0",
    "react-native-iap": "^12.15.2",
    "react-native-mime-types": "^2.5.0",
    "react-native-mmkv": "^3.0.2",
    "react-native-paper": "^5.12.5",
    "react-native-reanimated": "3.15.3",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "~4.4.0",
    "react-native-star-rating-widget": "^1.8.0",
    "react-native-svg": "^15.9.0",
    "react-native-toast-message": "^2.2.0",
    "react-native-uuid": "^2.0.2",
    "react-native-web": "~0.19.10",
    "react-redux": "^9.1.2",
    "redux-persist": "^6.0.0",
    "rusha": "^0.8.14",
    "serialize-error": "^11.0.3",
    "validator": "^13.12.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/crypto-js": "^4.2.2",
    "@types/jest": "^29.5.12",
    "@types/lodash": "^4.17.7",
    "@types/react": "~18.3.12",
    "@types/react-native": "^0.73.0",
    "@types/react-test-renderer": "^18.3.0",
    "@types/rusha": "^0.8.3",
    "@types/validator": "^13.12.0",
    "babel-plugin-module-resolver": "^5.0.2",
    "jest": "^29.2.1",
    "jest-expo": "~52.0.2",
    "react-native-svg-transformer": "^1.5.0",
    "react-test-renderer": "18.3.1",
    "typescript": "~5.3.3"
  },
  "private": true,
  "expo": {
    "install": {
      "exclude": [
        "react-native@~0.74.0",
        "react-native-reanimated@~3.10.0",
        "react-native-gesture-handler@~2.16.1",
        "react-native-screens@~3.31.1"
      ]
    }
  }
}
```
3. Update app.json
```json
{
  "expo": {
    "name": "expo-51",
    "slug": "expo-51",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "scheme": "myapp",
    "userInterfaceStyle": "automatic",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.signalone.expo51"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "package": "com.myapp"
    },
    "web": {
      "bundler": "metro",
      "output": "static",
      "favicon": "./assets/images/favicon.png"
    },
    "plugins": [
      "expo-router",
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ]
    ],
    "experiments": {
      "typedRoutes": true
    },
    "extra": {
      "eas": {
        "projectId": "2b3e4d45-2ad4-4e7e-8764-dd8837aba231"
      }
    }
  }
}
```
4. Clear node modules `rm -rf node_modules package-lock.json`
5. run `npx expo prebuild --clean`
6. run `expo run:ios`

This is when the error shows. To clear it,
1. Run `npm rm expo-dev-client`
2. Clear node modules `rm -rf node_modules package-lock.json`
3. Install modules `npm i`
4. Run `npx expo prebuild --clean`
5. Run `expo run:ios`

**Comment by Kudo** [comment] 2025-01-06 13:21
thanks @jaaywags for the repro. the [expo-dev-client version](https://github.com/jaaywags/expo-51-issue/blob/58a5e9f682fff8d24deb6eb56e76bc35b134447c/package.json#L47) is incompatible with sdk 52. please use `npx expo install --check` to check the incompatible packages.

```sh
$ npx expo install --check
Skipped checking dependencies: react-native@~0.74.0, react-native-reanimated@~3.10.0, react-native-gesture-handler@~2.16.1, and react-native-screens@~3.31.1. These dependencies are listed in expo.install.exclude in package.json. Learn more: https://docs.expo.dev/more/expo-cli/#configuring-dependency-validation
The following packages should be updated for best compatibility with the installed expo version:
  @react-native-async-storage/async-storage@1.24.0 - expected version: 1.23.1
  @react-native-community/datetimepicker@8.0.1 - expected version: 8.2.0
  @shopify/flash-list@1.6.4 - expected version: 1.7.1
  expo-apple-authentication@6.4.2 - expected version: ~7.1.2
  expo-application@5.9.1 - expected version: ~6.0.1
  expo-clipboard@6.0.3 - expected version: ~7.0.0
  expo-dev-client@4.0.29 - expected version: ~5.0.8
  expo-device@6.0.2 - expected version: ~7.0.1
  expo-image-picker@15.0.7 - expected version: ~16.0.3
  expo-linear-gradient@13.0.2 - expected version: ~14.0.1
  expo-updates@0.25.27 - expected version: ~0.26.10
  expo-web-browser@13.0.3 - expected version: ~14.0.1
  react-native-gesture-handler@2.20.0 - expected version: ~2.20.2
  react-native-reanimated@3.15.3 - expected version: ~3.16.1
  react-native-safe-area-context@4.10.5 - expected version: 4.12.0
  react-native-svg@15.10.1 - expected version: 15.8.0
Your project may not work correctly until you install the expected versions of the packages.
? Fix dependencies? › (Y/n)
```
