### ISSUE TITLE
expo install react-native-svg: installs a not working version

### ISSUE THREAD

**Issue by julius-lae** [expo/expo#8722] opened 2020-06-08 07:26 UTC
### Summary of Issue (just a few sentences)
When I install react-native-svg using expo install it installs version 11.0.1 but I get this error from Metro when opening my app:
`Unable to resolve "./LocalSvg" from "node_modules\react-native-svg\src\ReactNativeSVG.ts"`

### Environment
SDK 37

### Expected Behavior vs Actual Behavior
I installed the latest version (12.1.0) now its working but i get the dependencies are not compatible warning.

**Comment by byCedric** [comment] 2020-06-08 14:17
Hi @julius-lae! Thanks for the issue report, but I don't seem to be able to reproduce this issue. `react-native-svg` requires some native code that we ship with the Expo Client. If you are in the managed flow, this might break if you use `12.1.0`. If you are using the bare workflow, you should not run into issues 😄 

I also double-checked the [`./LocalSvg` you mentioned in the source code](https://github.com/react-native-community/react-native-svg/blob/v11.0.1/src/ReactNativeSVG.ts), but I can't find that either. Maybe you have edited the `node_modules` files directly? If not, I would recommend reinstalling the modules (by removing `node_modules` and running `yarn install` or `npm install`).

Hope it helps!

**Comment by lattespirit** [comment] 2020-06-09 08:36
I got the same error when downgrading from 12.1.0 to 11.0.1

remove node_modules folder and reinstall again works for me.

**Comment by FiberJW** [comment] 2020-07-14 19:24
This seems to be resolved, so I'll close this for now. If you run into a similar error that is reproducible, feel free to open up a new issue!

**Closed by FiberJW** 2020-07-14 19:24 UTC
Labels: Svg, needs repro

**Comment by ryekerjh** [comment] 2020-07-22 22:02
@FiberJW I have the same problem, and I tried removing node_modules and running `npm install` again. I am running node v12.16.3 and React Native with Expo ~37.0.3 and react-native-svg 11.0.1

**Comment by FiberJW** [comment] 2020-07-22 22:36
@ryekerjh do you have another dependency that uses react-native-svg 12.X? Maybe pinning the version to 11.0.1 could help solve any mismatches.

It might also help to try upgrading to SDK 38, since we bumped the react-native-svg version in that release: https://github.com/expo/expo/blob/bf7e261cdc06fc9ec84e5f5735e7871901efa340/CHANGELOG.md#3800

**Comment by ryekerjh** [comment] 2020-07-22 23:00
> @ryekerjh do you have another dependency that uses react-native-svg 12.X? Maybe pinning the version to 11.0.1 could help solve any mismatches (using [resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) or something similar).
> 
> It might also help to try upgrading to SDK 38 since we bumped the react-native-svg version in that release: https://github.com/expo/expo/blob/bf7e261cdc06fc9ec84e5f5735e7871901efa340/CHANGELOG.md#3800

Well that was a strange issue, but I figured it out. Thanks for the suggestions @FiberJW. As it turned out, I needed to clear my watchman & expo caches (cachi? cachie?)

[Here's a link](https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352) to the steps I took to do so. I know it's outdated, but the commands to clear the caches worked. Thanks again for your help!
