### ISSUE TITLE
Application Icon appearing before the splash screen on Android

### ISSUE THREAD

**Issue by ceopaludetto** [expo/expo#29440] opened 2024-06-05 01:24 UTC
### Minimal reproducible example

https://github.com/expo/examples/tree/master/blank

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

To be clear, I've added the blank project to reproducible example because any project with native build on android should trigger this issue

---

This was made by using the native build using `expo prebuild` with the following `app.config.ts`:
```ts
import type { ExpoConfig } from "expo/config";

export default {
  name: "***",
  slug: "***",
  version: "1.0.0",
  orientation: "portrait",
  icon: "./assets/icon.png",
  userInterfaceStyle: "automatic",
  ios: {
    bundleIdentifier: "***",
    supportsTablet: true,
    splash: {
      backgroundColor: "#FFFFFF",
      image: "./assets/splash.png",
      resizeMode: "contain",
      dark: {
        backgroundColor: "#000000",
        image: "./assets/splash-dark.png",
        resizeMode: "contain",
      },
    },
  },
  android: {
    package: "***",
    adaptiveIcon: {
      foregroundImage: "./assets/adaptive-icon.png",
      backgroundColor: "#ffffff",
    },
    splash: {
      backgroundColor: "#FFFFFF",
      image: "./assets/splash.png",
      resizeMode: "native",
      dark: {
        backgroundColor: "#000000",
        image: "./assets/splash-dark.png",
        resizeMode: "native",
    },
  },
},
} satisfies ExpoConfig;
```

The application icon appears before the splash screen on the first opening, see the video below:
[Screen recording.webm](https://github.com/expo/expo/assets/30508218/3665c885-2442-49c1-8d89-5aa6dc768d70)

This seems to be incorrect, after some investigation I found the following configuration that should be added to `styles.xml` in the LaunchScreen Theme:
```xml
<item name="android:windowDisablePreview">true</item>
```

But even manually adding this to `styles.xml` didn't work to me. So right now my only available solution is to use a light splash screen for both dark and light modes (which is not optimal)

### Environment
```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.1 - ~/.local/share/mise/installs/node/latest/bin/node
      npm: 10.5.0 - ~/.local/share/mise/installs/node/latest/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.1, 34.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    Expo Workflow: bare
```
### Expo Doctor Diagnostics
```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✖ Check for common project setup issues
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project has native project folders but also has config plugins, indicating it is configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

One or more checks failed, indicating possible issues with the project.
```

**Comment by ceopaludetto** [comment] 2024-06-05 01:28
Additional context, I also tried all three `resizeMode`: `contain | cover | native`

**Comment by brentvatne** [comment] 2024-06-05 15:30
we currently only support this style of splash screens on android in expo-splash-screen ([learn more about android splash screens](https://developer.android.com/develop/ui/views/launch/splash-screen)), but we plan to improve this in sdk 52. you can also use react-native-bootsplash instead, which provides further customization - the beta version of that library has great support for config plugins (https://github.com/zoontek/react-native-bootsplash/pull/578).

**Comment by ceopaludetto** [comment] 2024-06-05 15:40
Hi @brentvatne, thank you for the quick feedback, I'm actually using expo-splash-screen, to be clear I want to remove this part of the startup animation (which is the application icon):
<img width="461" alt="Screenshot 2024-06-05 at 12 34 48" src="https://github.com/expo/expo/assets/30508218/7be97c9a-9aae-4473-a3bb-e8db49015a96">

The example that you sent from the google docs, show the gmail opening animation, which only have the splash screen itself, without the icon (which is my expected behavior). I will give react-native-bootsplash v6 a try, thanks

**Comment by brentvatne** [comment] 2024-06-14 01:10
we are working on this for sdk 52. @Mirthis - you'll have to use sdk 51 to follow those instructions for react-native-bootsplash.

**Comment by Mirthis** [comment] 2024-06-14 11:58
> we are working on this for sdk 52. @Mirthis - you'll have to use sdk 51 to follow those instructions for react-native-bootsplash.

Thanks for your answer. I did in fact switch to v51 and things are working ok now using `react-native-bootsplash`. Thanks!

**Comment by rahXephonz** [comment] 2024-07-01 04:45
Hello, i see many conversation of this issue but i have question, can i use react-native-bootsplash with expo v49 @brentvatne ?

**Comment by brentvatne** [comment] 2024-07-30 20:03
@rahXephonz - you will need to use sdk 51

**Comment by brentvatne** [comment] 2024-07-30 20:04
@alanjhughes is working on resolving this issue in expo-splash-screen, it'll be resolved in sdk 52! we may release a canary version of expo-splash-screen with the changes so that folks can try it out in sdk 51 as well. we'll keep you updated

**Comment by luisguareschi** [comment] 2024-08-09 13:01
Hello! Any updated on this? I dont have an android folder on my project, so Im not how to fix this 😢

**Comment by samducker** [comment] 2024-08-26 22:32
Just wondering if I use android.splash + ios.splash vs using the splash key in my app.config.ts/app.json will this make any difference to this issue on expo SDK 51 or it won't be resolved until SDK 52 any approx eta on that?

**Comment by luisguareschi** [comment] 2024-08-26 22:47
@samducker from what I tested it doesnt fix the issue. But if you manage to fix it please let me know!

**Comment by mikib0** [comment] 2024-08-31 08:29
check this out https://github.com/expo/expo/issues/16084#issuecomment-1119733035 @waelabdrabbo

**Comment by luisguareschi** [comment] 2024-08-31 19:41
@mikib0 but how would I do that in a expo managed workflow? I dont have does files in my project

**Comment by mikib0** [comment] 2024-09-05 08:36
@luisguareschi Copy and paste the code below to `translucent-default-splash-screen-config.js` at the root of your expo project. Then insert `["./translucent-default-splash-screen-config"]` to `expo.plugins` array in your app.json.

<details>
<summary>translucent-default-splash-screen-config.js</summary> 
// Credits: https://github.com/expo/expo/issues/16084#issuecomment-1261330440

const { AndroidConfig, withAndroidStyles } = require('@expo/config-plugins');

const withSplashWindowIsTranslucent = (config) => {
  return withAndroidStyles(config, async (config) => {
    config.modResults = await configureFullScreenDialog(config.modResults);
    return config;
  });
};

async function configureFullScreenDialog(styles) {
  const splashScreen = styles.resources.style.find(
    (style) => style.$.name === 'Theme.App.SplashScreen',
  );

  if (splashScreen) {
    splashScreen.item = splashScreen.item.filter(
      (item) => item.$.name !== 'android:windowIsTranslucent',
    );
    splashScreen.item.push(
      AndroidConfig.Resources.buildResourceItem({
        name: 'android:windowIsTranslucent',
        value: true,
      }),
    );
  }

  return styles;
}

module.exports = withSplashWindowIsTranslucent;
</details>

**Comment by luisguareschi** [comment] 2024-09-05 16:43
@mikib0 omg! Worked like a charm thank you so much!!

**Comment by liquidvisual** [comment] 2024-09-09 04:18
Heads up, I just discovered this plugin breaks native orientation behavior on Android. While it does fix the splash screen issue, for me it prevents landscape orientation from triggering.

**Comment by luisguareschi** [comment] 2024-10-21 16:12
> @luisguareschi @mikib0 Heads up, I just discovered this plugin breaks native orientation behavior on Android. While it does fix the splash screen issue, for me it prevents landscape orientation from triggering.

Oh, our app is only portrait, but good to know. Thanks!

**Comment by krisgerhard** [comment] 2024-10-21 17:34
We saw some crashes on Android 8 (API 26) which  were introduced after using this workaround.

**Comment by brentvatne** [comment] 2024-10-21 19:07
another good option is to use react-native-bootsplash: https://github.com/zoontek/react-native-bootsplash?tab=readme-ov-file#with-expo

we're working on improvements to expo-splash-screen and hope to have that out soon

**Comment by singhayush1403** [comment] 2024-10-28 13:22
Is there any way to remove expo-splash-screen from the app altogether? I have been trying to make a lottie splash screen but the expo one always shows

**Comment by ericpoulinnz** [comment] 2024-11-10 17:09
> @alanjhughes is working on resolving this issue in expo-splash-screen, it'll be resolved in sdk 52! we may release a canary version of expo-splash-screen with the changes so that folks can try it out in sdk 51 as well. we'll keep you updated

@brentvatne I will be migrating to sdk 52 in the next week, but I didn't see this in the changelog, will it still be an issue / should I implement a workaround?

**Comment by alanjhughes** [comment] 2024-11-10 17:10
@ericpoulinnz it won't be an issue

**Comment by Nantris** [comment] 2024-11-14 02:46
@alanjhughes what exactly is necessary to benefit? We're on SDK 52 but this problem persists.

**Closed** 2024-11-14 05:36 UTC
Labels: Android, SplashScreen, Issue accepted

**Comment by ericpoulinnz** [comment] 2024-11-14 20:06
@brentvatne sorry probably not the right place, but you say "in release builds", does this mean in dev client I shouldn't see a splash screen?

Since updating to SDK 52 and replacing my old `splash` configs with the below there is no longer _any_ splash screen showing on iOS or Android.

```
[
  "expo-splash-screen",
  {
    "backgroundColor": "#ffffff",
    "image": "./assets/images/adaptive-icon.png",
    "dark": {
      "image": "./assets/images/adaptive-icon.png",
      "backgroundColor": "#1B1B1F"
    },
    "imageWidth": 200
  }
],
```

**Comment by brentvatne** [comment] 2024-11-14 20:14
@ericpoulinnz - that's right, currently when you reload the app from within a dev build or expo go you will not see the splash screen as configured by expo-splash-screen. the reason for that is that we would need to re-create this screen with 100% accuracy in order for it to be reliable. there isn't a native view on ios/android that we can just drop in to provide the exact same behavior. we're thinking about creating an `developmentLoadingImage` field or something along those lines that will allow you to control what you see there, or possibly just showing the app icon and a bit of text of our own. for now, you can use the `splash` key to show something and then the config from `expo-splash-screen` will be used for the native splash that you see on startup

**Comment by ericpoulinnz** [comment] 2024-11-14 21:08
Thank you for the quick clarification @brentvatne ! It makes sense.

> we're thinking about creating an developmentLoadingImage field or something along those lines that will allow you to control what you see there, or possibly just showing the app icon and a bit of text of our own.

Honestly, just the app icon is fine. But more importantly, a mention of this expected behaviour here would have saved me an hour of scratching my head: https://docs.expo.dev/versions/latest/sdk/splash-screen/

I was unable to find any information on whether this is expected anywhere.

>  for now, you can use the splash key to show something and then the config from expo-splash-screen will be used for the native splash that you see on startup

Can you have both a `splash` and `expo-splash-screen` config? If I'm reading this correctly, the `splash` key will be used in development and the `expo-splash-screen` will be used in production builds?

**Comment by brentvatne** [comment] 2024-11-14 21:36
@ericpoulinnz - sorry about that, we can update the docs accordingly. the `expo-splash-screen` plugin will take precedence over your `splash` config, so you can set it in both places

**Comment by brentforder** [comment] 2024-11-16 23:46
> @ericpoulinnz - that's right, currently when you reload the app from within a dev build or expo go you will not see the splash screen as configured by expo-splash-screen. the reason for that is that we would need to re-create this screen with 100% accuracy in order for it to be reliable. there isn't a native view on ios/android that we can just drop in to provide the exact same behavior. we're thinking about creating an `developmentLoadingImage` field or something along those lines that will allow you to control what you see there, or possibly just showing the app icon and a bit of text of our own. for now, you can use the `splash` key to show something and then the config from `expo-splash-screen` will be used for the native splash that you see on startup


> @ericpoulinnz - sorry about that, we can update the docs accordingly. the `expo-splash-screen` plugin will take precedence over your `splash` config, so you can set it in both places

It's quite strange for release builds to be required for testing an app's UI, and a lot of developers are naturally going to be confused by this decision. Please do update the docs! Thanks!

**Comment by dlee** [comment] 2024-12-11 12:10
> Heads up, I just discovered this plugin breaks native orientation behavior on Android. While it does fix the splash screen issue, for me it prevents landscape orientation from triggering.

Hi @liquidvisual, did you ever figure out a way to unlock the orientation?
