### ISSUE TITLE
[Android][Amplitude] Warning that Amplitude.initialize not initializing on Android devices

### ISSUE THREAD

**Issue by lflores12** [expo/expo#5459] opened 2019-08-27 21:00 UTC
Expo CLI 3.0.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245 

### Steps to Reproduce
Load app 

### Expected behavior 

initialize Amplitude client the way it does with Apple devices and without an unhandled promise rejection error.

### Actual Behavior 

Unhandled promise rejection 
![Screenshot_20190827-170356](https://user-images.githubusercontent.com/48686664/63807966-d7cec480-c8ec-11e9-86e6-d4c88b7626fa.png)

**Comment by sjchmiela** [comment] 2019-11-05 08:50
Hey, @lflores12! Could you please provide us with a code snippet showing how are you initializing and logging events with Amplitude? My guess would be that you're not awaiting the `initialize` Promise and iOS, being usually a little bit faster than Android, resolves the promise in time, while Android does not.

**Comment by matt454** [comment] 2020-06-15 14:53
> expo-analytics-amplitude version 6.0.0.
> also very sure the api key works. When we use an Apple device there is no unhandled promise rejection error. And even though it has that error on android, it still sends off the events to the amplitude dashboard for some reason.

Hey @lflores12 did you ever solve this?

**Comment by cruzach** [comment] 2020-07-14 19:39
I tested this with the code in [this snack](https://snack.expo.io/@charliecruzan/amplitude5459) (running locally) on both iOS and Android, and wasn't able to reproduce the error. Since it's been a while since we've heard from OP here, and there's no repro, I'm going to close this issue

@matt454 if you're seeing this issue, I would make sure you're initializing before logging any events. If you're still having this problem, then please open a new issue with a minimal reproducible demo

**Closed by cruzach** 2020-07-14 19:39 UTC
Labels: Amplitude, Android, needs repro
