### ISSUE TITLE
expo-image stopAnimating() with AVIF does not work on iOS

### ISSUE THREAD

**Issue by andreialecu** [expo/expo#31176] opened 2024-08-26 09:38 UTC
### Minimal reproducible example

https://snack.expo.dev/-nigAhGm4zHjdMK3opUrW

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build, in Expo Go, in a standalone app

### Summary

I believe this is an upstream bug in SDWebImage. I'll open an issue there too.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      Yarn: 4.4.0 - ~/.nvm/versions/node/v20.11.1/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
      Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 28, 29, 30, 31, 33, 34
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11090377
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.17 => 51.0.17 
      react: 18.2.0 => 18.2.0 
      react-native: ^0.74.2 => 0.74.3 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

irrelevant

**Comment by andreialecu** [comment] 2024-08-26 09:46
Upstream report: https://github.com/SDWebImage/SDWebImage/issues/3745

**Comment by dreampiggy** [comment] 2024-08-27 07:43
Can you have a test with APNG/GIF/AWebP as well? Example URL can be founded here:

webp: http://littlesvr.ca/apng/images/SteamEngine.webp
apng: http://apng.onevcat.com/assets/elephant.png
gif: http://assets.sbnation.com/assets/2512203/dogflops.gif
heics: https://nokiatech.github.io/heif/content/image_sequences/starfield_animation.heic

**Comment by andreialecu** [comment] 2024-08-27 08:00
@dreampiggy updated snack with other formats: https://snack.expo.dev/0HsEdxNWBI7Lzk2Wb2BH3

Everything seems fine except AVIF.

Video below:

https://github.com/user-attachments/assets/afa2e996-30b2-4b85-b1e8-71a1edd3c0e2

**Comment by dreampiggy** [comment] 2024-08-27 08:10
Is the AVIF coder generated the `SDAnimatedImage` or `_UIAnimatedImage` (UIKit image ?)

Can you attach a debugger to print the object ? Print a breakpoint at `animatedImageFrameAtIndex:` and check return's object

which has some known limitation. See: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#rendering

> (Note UIImage/NSImage also can represent an animated one using animatedImageWithImages:duration: API)

**Comment by andreialecu** [comment] 2024-08-27 08:16
Will try to check that, perhaps this is relevant? 

https://github.com/expo/expo/blob/1fe71d007c5c5aab676e46257a90727483543bc5/packages/expo-image/ios/AnimatedImage.swift

**Comment by andreialecu** [comment] 2024-08-27 08:18
On a side note, I noticed that having 3 AVIF animations simultaneously completely wrecks app performance on an iPhone 15 Pro Max. I'm not sure if that's what is expected.

**Comment by andreialecu** [comment] 2024-08-27 08:21
Update: It appears that if I download the snack locally and run it in the iOS simulator, the animation stops properly.

https://github.com/user-attachments/assets/35cd1b8c-d28e-4244-b94f-41af821f7412

I initially discovered this issue in our real app, and the Snack confirmed it. I'm not sure why downloading it locally makes the snack work, while it doesn't work via the iOS web simulator at snack.expo.dev.

Investigating...

**Comment by andreialecu** [comment] 2024-08-27 09:06
I suspected there's some interaction with React Navigation so I made a new Snack with it.

Some very bizarre findings here:

https://snack.expo.dev/Sf0Ja0uTG0fDY_R8BU2FI

It appears that when the images are inside react-navigation, the stop/start animation behaves erratically. There are also some messages logged in the Snack:

```
iPhone 15 Pro:
Unhandled promise rejection Error: "Calling the 'startAnimating' function has failed
→ Caused by: The 1st argument cannot be cast to type View<ImageView>
→ Caused by: Unable to find the 'ImageView' view with tag '1597'" in Error: Calling the 'startAnimating' function has failed << → Caused by: The 1st argument cannot be cast to type View<ImageView> << → Caused by: Unable to find the 'ImageView' view with tag '1597'
```

In our real app, we tried to stop animations on background screens and reenable them when the screen was focused. I found that `.stopAnimation()` doesn't do anything if the image is on an inactive screen - it will continue playing and cannot be paused.

Perhaps this is indeed some Expo Image bug? Hopefully, the Snack above should help investigate.



Video:

https://github.com/user-attachments/assets/9ddd12fd-d5e4-48e1-aaa5-b8540d2a5a81

**Comment by dreampiggy** [comment] 2024-08-27 09:15
Need a real demo (upload all contents included the Pods folder), you can upload to some CDN server like AmazonS3/OneDrive/GoogleDriver

Because the expo is the downstream dependencies, it's hard to setup the development environment to debug.

I guess this related some AVIFCoder logic which breaks the SDWebImage's animation design.

(But the strange thing is, AVIFCoder has its [own demo](https://github.com/SDWebImage/SDWebImageAVIFCoder/tree/master/Example), and it shows great without any issue, including start/stop)

See: 
[1.mov.zip](https://github.com/user-attachments/files/16759634/1.mov.zip)

**Comment by dreampiggy** [comment] 2024-08-27 09:18
Did expo register the `SDWebImageAVIFCoder` ? This is not the default coder

Note, from iOS 17, Apple system decoder can render AVIF as well.

**Comment by andreialecu** [comment] 2024-08-27 09:18
@dreampiggy yes, I believe your library is probably working correctly here. As I mentioned in a previous comment, downloading the source and running the code locally with an XCode compiled project works. It's only in Expo Go where it misbehaves. There's probably some old dependency in Expo Go that was buggy, but latest SDWebImage seems fine.

I'll close the issue on your side while we wait for an Expo maintainer to chip in.

**Comment by Kudo** [comment] 2024-08-27 17:34
can confirm this issue on ios dev-build, it's not just expo-go and should be something inside expo-image. it could relate to our customized SDWebImageContextAnimatedImageClass. not sure whether avif coder supports it. will try to investigate further but temporarily assign to @tsapeta for some spotlight.

**Comment by andreialecu** [comment] 2024-08-27 17:38
Hey @Kudo, thanks for looking at this!

I reported a bunch of issues, one of which also happens on Android (the react navigation one)

In my case I was not able to reproduce the main AVIF issue in a full dev build. I shared a video where it seems to work properly.

So I was wondering which one you were referring to.

**Comment by dreampiggy** [comment] 2024-08-28 06:57
> SDWebImageContextAnimatedImageClass

For https://github.com/SDWebImage/SDWebImageAVIFCoder, the latest version 0.11.0 supports the `SDAnimatedImage` one. It should just behaves like the other custom coder including SDWebImageWebPCoder

I guess there are something other cases which cause the issue.

**Comment by Kudo** [comment] 2024-08-28 15:11
@andreialecu i was looking for the first issue that stopAnimating doesn't work on AVIF (ios only). 

having some findings today for the issue. it was because our implementation for [downscaling](https://github.com/expo/expo/blob/e76e061bd6b7490c632be8d46cbd12fff16024ff/packages/expo-image/ios/ImageUtils.swift#L102-L123). SDAnimatedImageView seems not well support `UIImage.animatedImage`. when render the image, SDAnimatedImageView will not create a player. [disable downscale](https://docs.expo.dev/versions/latest/sdk/image/#allowdownscaling) will workaround the issue.

for the solution side, i could fix the issue by converting `UIImage.animatedImage` to GIF Data and create `SDAnimatedImage(data:)`. not sure whether there are any better solutions to resize a SDAnimatedImage? cc @dreampiggy if you have more thought for this.

**Comment by andreialecu** [comment] 2024-08-28 18:35
In our app we already disable downscaling, but we cannot stop the animation. Probably because or react navigation. See my other snack.

We use long avifs, like up to a minute. HD videos. I found that the file size is as good as mp4 or better.

Or is it not recommended to do so, and should instead use expo-video?

I did notice some performance issues so I wanted to work around them by pausing the animation on unfocused screens.

In this case, downscaling, especially to gif, would be a bad idea.

**Comment by dreampiggy** [comment] 2024-08-29 08:39
> SDAnimatedImageView seems not well support UIImage.animatedImage

It should supported. In my initial design. When called with `UIAnimatedImage`, it should always call super (UIImageView itself) implementation.

Is this cause the issue during the recently refractory ? I can have a test on myself

**Comment by dreampiggy** [comment] 2024-08-29 08:45
Well, reproduced.

I tested SDWebImage's own demo, it can use `SDAnimatedImageView` with `UIAnimatedImage`. But yes, the animation start/stop function totally broken.

![image](https://github.com/user-attachments/assets/1aff3d72-0731-48d5-9b80-3ad985eba786)

Let me fix this soon...😂

**Comment by dreampiggy** [comment] 2024-08-29 08:49
Interesting, UIImageView seems to report `self.isAnimating` as false, even it's visible animating...🤔

![image](https://github.com/user-attachments/assets/9330c880-0899-4d18-88ee-0a9faa911a30)

**Comment by dreampiggy** [comment] 2024-08-29 08:52
There are something internal changes after iOS 16.3

https://www.developer.limneos.net/?ios=16.3&framework=UIKitCore.framework&header=UIImageView.h

@Kudo Do you have iOS 15 devices to test again ? I guess this should behave correctly on iOS 15, but broken on iOS 16+ (Since we inherited UIImageView, some UIKit team internal changes cause the issue)

**Comment by dreampiggy** [comment] 2024-08-29 09:46
Is this UIImageView's itself's bug ?

I found even use `UIAnimatedImage` and assign to `UIImageView`, you can not stop the animation as well.

Not just `SDAnimatedImageView`😣

**Comment by andreialecu** [comment] 2024-08-29 09:51
How come everything stops correctly here? 

https://github.com/expo/expo/issues/31176#issuecomment-2311870239

However as soon as the image is put in a navigation container it does indeed stop working.

**Comment by dreampiggy** [comment] 2024-08-29 09:55
> How come everything stops correctly here?

Only your AVIF coder use `_UIAnimatedImage`, others you can see, it use `SDAnimatedImage`

These are two different thing. The `SDAnimatedImage` based animation is implemented by ourselves. Do not use any UIKit solution

**Comment by dreampiggy** [comment] 2024-08-29 09:59
Try yourself. This is Apple's bug, not SDWebImage's bug. UIImageView's `stopAnimating` is broken

[UIImageViewStopAnimatingBug.zip](https://github.com/user-attachments/files/16797211/UIImageViewStopAnimatingBug.zip)

**Comment by dreampiggy** [comment] 2024-08-30 08:11
A stupid workaround if you really really want `UIAnimatedImage`
![image](https://github.com/user-attachments/assets/e17c97bb-5e7c-4f38-ba67-f18e921522fd)

But why not use SDAnimatedImage ? It supports downscale as well. Try pass `SDWebImageContextThumbnailPixelSize: CGSizeMake(100, 100)` to see what happends.

**Comment by andreialecu** [comment] 2024-08-30 10:27
A question regarding downscaling. As mentioned we were trying to use this with long AVIFs. HD and up to a minute and maybe longer.

The downscaling wrecks performance and is unusable. I assume the only solution is to disable it, right? What would be the recommendations there?

Or should we use a video player component instead?

**Comment by dreampiggy** [comment] 2024-08-30 12:29
AVIF is just AV1 video

Use a native video player (Apple supports AV1 from iOS 17) or ffmpeg based player is always the best choice

**Comment by andreialecu** [comment] 2024-08-30 13:40
I see, we just wanted a simpler solution because we wanted to be able to support avif, webp and other formats with the same code.

So SDWebImage is not entirely suited for long form avif playback, correct?

**Comment by dreampiggy** [comment] 2024-08-31 04:06
> So SDWebImage is not entirely suited for long form avif playback, correct?

No. All animated inage which is long than 1 minutes are always bad for customers. Whatever the format.  You drain your customers's bandwidth/ battery and disk storage

This is why all of them like Telegram or https://giphy.com/ convert you image and use video on browser or client to render.

**Comment by Kudo** [comment] 2024-08-31 06:51
@andreialecu the other issue you mentioned in react-navigation is because your `TouchableOpacity` has dynamic width, which then coming with image bound changes and reload all images. please try to add the following code in Image.js to stretch the container:

```js
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    padding: 8,
    alignSelf: 'stretch',
    marginHorizontal: 16,
  },
});
```

@dreampiggy i'm so impressive from your investigation. much appreciated for your help. i guess i would lean toward to use the [workaround](https://github.com/expo/expo/issues/31176#issuecomment-2320437507) you shared. the reason not using SDAnimatedImage is that our downscaling happened after image loading. we calculate desired downscale size based on [original image size and view bounds](https://github.com/expo/expo/blob/810fa61f3413e4e296388471b3cbcd5cd0dedeb8/packages/expo-image/ios/ImageUtils.swift#L58-L83). the `SDWebImageContextImageThumbnailPixelSize` needs to be specified before image loading. also, there's no something like `SDAnimatedImage initWithFrames:(NSArray<SDImageFrame *> * _Nullable)frames ...` that to create a SDAnimatedImage from existing frames.

**Comment by andreialecu** [comment] 2024-08-31 06:53
Thanks for your thoughts.

Sharing my experience.

In this case I tested avif and it's smaller than an equivalent mp4 "video" file.

I guess avif is video too, and can be played as a video, via a video component. The file in this case even though high quality and relatively long, is just about 6MB as an avif an 8MB+ as mp4.

Since it can be cached, bandwidth shouldn't be an issue, except for initial load.

Everything worked fine except for not being able to stop it from playing in background screens, and the downscaling creating problems.

Will note that it's not a supported use case though and swap to dedicated video lib for avif.

**Comment by andreialecu** [comment] 2024-08-31 08:15
> @andreialecu the other issue you mentioned in react-navigation is because your `TouchableOpacity` has dynamic width, which then coming with image bound changes and reload all images. please try to add the following code in Image.js to stretch the container:

I see, so to make sure I understand this correctly, this is caused by the rescaling logic which rescales the image again for a slightly different size? Which in turn refreshes the image. A bit unexpected.

Here's a different repro, more in line with the actual issue we encountered (although not exactly the same):
https://snack.expo.dev/YhY4lpQC8gWn3Efx4paKw

Try stopping the animation in the Home tab, then going to Settings and back to Home. You'll see the animations in Home, which were all started again.

**Comment by Kudo** [comment] 2024-08-31 09:30
> Here's a different repro, more in line with the actual issue we encountered (although not exactly the same):
https://snack.expo.dev/YhY4lpQC8gWn3Efx4paKw

@andreialecu for this case, the tab navigator by default does not keep blurred tabs. please try to add the [`detachInactiveScreens={false}`](https://reactnavigation.org/docs/bottom-tab-navigator#detachinactivescreens).

**Comment by andreialecu** [comment] 2024-08-31 09:38
Oh, indeed. OK.

I'll need to make the full repro later which involves pushing a new screen on top. 

Animations in the background screen did not stop with an effect with useIsFocused, or with setTimeout.

**Comment by dreampiggy** [comment] 2024-09-02 06:25
> @dreampiggy i'm so impressive from your investigation. much appreciated for your help. i guess i would lean toward to use the [workaround](https://github.com/expo/expo/issues/31176#issuecomment-2320437507) you shared. the reason not using SDAnimatedImage is that our downscaling happened after image loading. we calculate desired downscale size based on [original image size and view bounds](https://github.com/expo/expo/blob/810fa61f3413e4e296388471b3cbcd5cd0dedeb8/packages/expo-image/ios/ImageUtils.swift#L58-L83). the `SDWebImageContextImageThumbnailPixelSize` needs to be specified before image loading. also, there's no something like `SDAnimatedImage initWithFrames:(NSArray<SDImageFrame *> * _Nullable)frames ...` that to create a SDAnimatedImage from existing frames.

Sounds like a feature request, some one in 1 years ago already mention this.

They need a `calculateSizeBlock` and passed into context option, which is ugly for Objective-C NSMutableDictionary based API

**Comment by dreampiggy** [comment] 2024-09-02 06:27
> > @dreampiggy i'm so impressive from your investigation. much appreciated for your help. i guess i would lean toward to use the [workaround](https://github.com/expo/expo/issues/31176#issuecomment-2320437507) you shared. the reason not using SDAnimatedImage is that our downscaling happened after image loading. we calculate desired downscale size based on [original image size and view bounds](https://github.com/expo/expo/blob/810fa61f3413e4e296388471b3cbcd5cd0dedeb8/packages/expo-image/ios/ImageUtils.swift#L58-L83). the `SDWebImageContextImageThumbnailPixelSize` needs to be specified before image loading. also, there's no something like `SDAnimatedImage initWithFrames:(NSArray<SDImageFrame *> * _Nullable)frames ...` that to create a SDAnimatedImage from existing frames.
> 
> Sounds like a feature request, some one in 1 years ago already mention this.
> 
> They need a `calculateSizeBlock` and passed into context option, which is ugly for Objective-C NSMutableDictionary based API
> 
> I've previously consider to provide a `scaleMode` based one your size, to use `aspectFill/aspectFit`, but this not been merged: [SDWebImage/SDWebImage#3628](https://github.com/SDWebImage/SDWebImage/pull/3628)

SDAnimatedImage is not `array of frames`, which is the root case.

Decode all frames into memory already cause problem, consider to decode a 200 frame with 4K resolution ? Which will occupy 4GB RAM on iPhone and crash your App

**Comment by dreampiggy** [comment] 2024-10-12 04:15
Anyone here ?

After some consideration, I don't think adding a `AspectFill` into the thumbnail decoding is the correct way.

Aspect Fill needs a background color (typically transparent) and its size, and the image size.

So, consider a JPEG with 1000x800, if you specify the thumbnail size 500x500, it should generate a image with 500x500, but only top and bottom 50pixel shows black (because JPEG does not support transparent)

This sounds really strange compared to normal `fill` (which just scale without aspect ratio) and `aspect fit`. Those processing don't need a background color.

### What's the final solution

For expo-image team, I suggest you to create a subclass or wrapper, inherited from `SDImageCodersManager`)

1. Grab the original full size image without thumbnail
2. Do your custom image transforming on the full size image and return

### Code example

```objective-c
@interface ExpoImageCoder : SDImageCodersManager
@class ExpoImageCoder *sharedCoder;
@property id myContext;
@end

@implementation ExpoImageCoder
- (nullable instancetype)initWithAnimatedImageData:(nullable NSData *)data options:(nullable SDImageCoderOptions *)options {
    self = [super init];
    if (self) {
        // ignore thumbnail size options
        options[SDImageCoderDecodeThumbnailPixelSize] = nil;
        _myContext = options["myContext"];
    }
    return self;
}

- (UIImage *)animatedImageFrameAtIndex:(NSUInteger)index {
    // 1. grab full size image
    UIImage *fullSizeImage = [super animatedImageFrameAtIndex:index];
    if (!fullSizeImage) return nil;
    if (!useThumbnail) return fullSizeImage;
    // 2. do transforming
    CGSize thumbnailSize = ... // Logic by yourself from other information
    SDImageScaleMode scaleMode = ... // Logic by from other information, you can encode anything into `SDWebImageCoderDecodeOptions`
    UIImage *thumbnail = [fullSizeImage sd_resizedImageWithSize:thumbnailSize scaleMode:scaleMode];
    return thumbnail;
}
@end
```

**Comment by Kudo** [comment] 2024-10-12 09:33
much appreciated for your help @dreampiggy!

i also prefer to have custom transformation than using built-in aspect ratio mode in SDWebImage. this flexibility makes our thumbnail implementations aligned between ios and android.
i would try to work on subclassing `SDImageIOAnimatedCoder` as the code you shared (which is neat and thanks again!). it may take me some time because i'm not quite familiar with SDWebImage api but i'll try my best.

**Comment by dreampiggy** [comment] 2024-10-12 09:44
It's a little trick you want to make only `Image Aspect Fill` without the rendering component (`UIImageView on iOS`). If you can control the rendering component part, maybe it's more easier to customize.

Currently `SDAnimatedImage` and `SDAnimatedImageView` is designed to solve RAM/Performance of UIKit animation, but it does not considerate some `post-transformer` about each animated frames. So it's make a little hard to customization

**Comment by Kudo** [comment] 2024-10-12 09:51
that makes sense. let me try how far i can go with subclassing `SDImageIOAnimatedCoder`.

**Comment by Kudo** [comment] 2024-10-15 16:11
ultimately proposing #32053 for a fake animated coder. the main reason is that i don't want to [re-decode](https://github.com/SDWebImage/SDWebImage/blob/0b10fcb54484b618a53386670bff38176a203290/SDWebImage/Core/SDImageIOAnimatedCoder.m#L934-L1003) the image from given NSData. also it's unclear to me how to [have a single coder with generic codec information](https://github.com/SDWebImage/SDWebImage/blob/0b10fcb54484b618a53386670bff38176a203290/SDWebImage/Core/SDImageIOAnimatedCoder.h#L19-L56) to support avif, webp and so on (resized image could originally from avif, webp, ...).
cc @dreampiggy if you have a chance to double check for the solution.

**Closed** 2024-10-19 14:02 UTC
Labels: iOS, Image, Issue accepted
