### ISSUE TITLE
Expo React Native Firebase Analytics fails on some Android devices

### ISSUE THREAD

**Issue by app-arianamini** [expo/expo#9403] opened 2020-07-26 08:52 UTC
## Error Log:
```Attempt to invoke interface method 'java.util.Set java.util.Map.keySet()' on a null object reference```

### Steps to Reproduce
```
import { logEvent } from "expo-firebase-analytics"

const testMethod = async () => {
    try {
         await logEvent("SomeKey")
    } catch (e) {
         consol.log(e) // Error was here 
    }
}
```

**Comment by barthap** [comment] 2020-07-27 06:15
Could you please give a full call stack of error message? This would be helpful to determine, where exactly error happened. Also, to be sure: This error happens only on newer Android versions (8+) and on built apk? (or bare workflow?)

**Comment by app-arianamini** [comment] 2020-07-27 07:05
Actually I am not sure if it was just an Android 8+ issue, I get this issue sometimes on some devices. It happens if I call the method  ```logEvent```. 

It works till now on iOS devices. 

My workaround was, just ignored the exception and put it inside a try-catch block.

**Comment by IjzerenHein** [comment] 2020-07-30 22:19
Duplicate of #8873

**Closed** 2020-08-06 21:52 UTC
Labels: Android, FirebaseAnalytics, status: needs more info
