### ISSUE TITLE
Problem with FCM on Web

### ISSUE THREAD

**Issue by LorhanSohaky** [expo/expo#10094] opened 2020-09-08 02:45 UTC
## 🐛 Bug Report
Since the expo does not yet support web notifications, I made my own version using FCM. But an internal error is occurring

### Reproducible Demo

Notification.web.js
```js
import { initializeFirebase, getToken } from './Firebase'

const registerForPushNotificationsForWeb = async () => {
  return initializeFirebase()
}

export const registerForPushNotificationsAsync = async () => {
    const messaging = await registerForPushNotificationsForWeb()
    const token = await getToken()
    messaging.onMessage(payload => {
      console.log('Manage notification with the app open: ', payload)
    })

    return token
}
```
Firebase.js
```js
/* eslint-env browser */
import firebase from 'firebase'

export async function initializeFirebase () {
  firebase.initializeApp({
    apiKey: '',
    authDomain: '',
    databaseURL: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: '',
    appId: '',
    measurementId: ''
  })

  return firebase.messaging()
}

function checkNotificationPromise () {
  try {
    Notification.requestPermission().then()
  } catch (e) {
    return false
  }

  return true
}

async function requestPermission () {
  const askPermission = checkNotificationPromise()
    ? Notification.requestPermission
    : new Promise(resolve => {
        Notification.requestPermission(permission => resolve(permission))
      })

  const permission = await askPermission()
  if (permission === 'granted') {
    return permission
  } else {
    if ('permissions' in navigator) {
      return new Promise(resolve => {
        navigator.permissions
          .query({ name: 'notifications' })
          .then(notificationPermission => {
            notificationPermission.onchange = function (e) {
              resolve(notificationPermission.state)
            }
          })
      })
    } else {
      throw new Error(
        "It looks like your browser doesn't support sending notifications"
      )
    }
  }
}

export async function getToken () {
  const messaging = firebase.messaging()

  const permission = await requestPermission()

  if (permission === 'granted') {
    const token = await messaging.getToken()
    return token
  } else {
    return undefined
  }
}

```

firebase-messaging-sw.js
```js
/* eslint-env worker */
/* global firebase */
importScripts('https://www.gstatic.com/firebasejs/7.9.3/firebase-app.js')
importScripts('https://www.gstatic.com/firebasejs/7.9.3/firebase-messaging.js')

firebase.initializeApp({
  apiKey: '',
  authDomain: '',
  databaseURL: '',
  projectId: '',
  storageBucket: '',
  messagingSenderId: '',
  appId: '',
  measurementId: ''
})

const messaging = firebase.messaging()

if (Notification.permission === 'granted') {

  messaging.setBackgroundMessageHandler(function (payload) {
    (
      '[firebase-messaging-sw.js] Received background message ',
      payload
    )
    // Customize notification here
    const notificationTitle = 'Background Message Title'
    const notificationOptions = {
      body: 'Background Message body.',
      icon: '/firebase-logo.png'
    }

    return self.registration.showNotification(
      notificationTitle,
      notificationOptions
    )
  })

  self.addEventListener('notificationclick', event => {
    return event
  })
}
```
 
### Steps to Reproduce
Send a notification with the site open

![image](https://user-images.githubusercontent.com/16273730/92427883-0ae49e80-f164-11ea-81f9-ae71a6434225.png)
![expo-notification-error](https://user-images.githubusercontent.com/16273730/92427901-11731600-f164-11ea-90c1-6b5927c9cec4.gif)

# Expo diagnostics

  Expo CLI 3.26.2 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm

**Comment by byCedric** [comment] 2020-10-08 13:18
Hi @LorhanSohaky, thanks for the report and sorry for the delay. Right now, we don't support [web notifications](https://docs.expo.io/versions/v39.0.0/sdk/notifications/), we do support the [core firebase package on web](https://docs.expo.io/versions/v39.0.0/sdk/firebase-core/). I see that you already added an improvement PR to notifications, thanks for that 😄  If you want or need web support, feel free to contribute support for that. 

Because this is a known limitation (for now), and not a bug, I'm going to close this issue.

**Closed by byCedric** 2020-10-08 13:18 UTC
Labels: Issue needs review
