### ISSUE TITLE
Expo React native app doesn´t work standalone when run as stand alone apk

### ISSUE THREAD

**Issue by megahertzon** [expo/expo#6229] opened 2019-11-11 12:30 UTC
My expo app works fine with "expo start" in a real android device, but when the apk generated with "expo build:android -t apk" is installed in the android real device, the app crashes and output this error:

java.lang.RuntimeException: Expo encountered a fatal error: ReferenceError: ReferenceError: Can't find variable: AbortController

This error is located at: in n in p in RCTView in u in RCTView in u in n in o in E in RCTView in n in RCTView in u in PanGestureHandler in n in L in RCTView i at host.exp.exponent.experience.a$2.run(BaseExperienceActivity.java:197) at android.os.Handler.handleCallback(Handler.java:873) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:201) at android.app.ActivityThread.main(ActivityThread.java:6810) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

Please help me!

package.json:

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "base-64": "^0.1.0",
    "expo": "^35.0.0",
    "expo-font": "^7.0.0",
    "native-base": "^2.13.8",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-maps": "^0.25.0",
    "react-native-reanimated": "^1.2.0",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "whatwg-fetch-timeout": "^2.0.2-timeout"
  },
  "devDependencies": {
    "babel-preset-expo": "^7.1.0"
  },
  "private": true
}

The apk crashes in all deveices that i tested:

red mi 7, android 9

Simulator genymotion API 22

**Comment by AdamJNavarro** [comment] 2019-11-11 23:56
Hey @megahertzon,

Can you provide us with a reproducible example of this? A link to the apk would be great. You can email secure@expo.io if you don't want to share publicly.

Cheers,
Adam

**Comment by megahertzon** [comment] 2019-11-13 10:25
Hi, this is the link to the apk:  https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40hertzon/localiza-car-7cbee826842541648ceaac60d4a33be0-signed.apk
Thank you
Best Regards,

Nelson

**Comment by cruzach** [comment] 2019-11-13 15:56
A great way to get more information on errors that you only see in production is to run it locally in production mode with `expo start --no-dev --minify`

From the error message, I'm guessing you're calling AbortController somewhere in your mobile app. This should work when run in the browser, but react-native doesn't support that method until [RN 0.60](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#060), unfortunately. Expo SDK 35 is based on RN0.59, but we will be releasing SDK 36 soon, which will support RN 0.61, so you should be able to use AbortController then.

**Comment by cristiandan** [comment] 2019-11-14 19:00
I've got the same issue, app only crashes as a standalone apk, and the error I get is :` 11-14 17:20:06.804		17228	-	E	AndroidRuntime	 java.lang.RuntimeException: Expo encountered a fatal error: invalid host	`

https://expo.io/artifacts/db065f97-560d-44fc-9872-38a194ec7b8b

**Comment by sheixt** [comment] 2019-11-23 14:55
> ...Expo SDK 35 is based on RN0.59, but we will be releasing SDK 36 soon, which will support RN 0.61, so you should be able to use AbortController then.

Good to have clarification on this. In the meantime, what is the recommended approach to cancelling subscriptions until SDK 36 has been rolled out?

**Comment by cruzach** [comment] 2019-11-25 19:22
I believe there are polyfills, but I haven't used them myself

I'm sure you can search around and find what other react native devs have used before upgrading to RN 0.60

**Comment by kub1x** [comment] 2020-07-08 12:28
I see @megahertzon is using `react-native-maps` in the project. 
The component is crushing my apk build, so maybe it is related. 
https://github.com/expo/expo/issues/9136
https://github.com/react-native-community/react-native-maps/issues/3477

**Comment by cruzach** [comment] 2020-07-08 15:08
@kub1x you should follow the guide we provide [here](https://docs.expo.io/workflow/debugging/#production-errors) for debugging standalone app crashes (specifically, you should run `adb logcat` to get the device logs and search for "fatal", which should identify the relevant logs)

Since we haven't received any updates on this issue like a repro, and Expo now has multiple SDKs released on RN .60 and above, I'm going to close this for now. If you run into a crash in a standalone app, follow the guide I linked to try and identify the root cause

**Closed by cruzach** 2020-07-08 15:08 UTC
Labels: bug, needs repro

**Comment by PatrickEinstein** [comment] 2023-04-16 13:46
i created a pizzapp calculator with react native app with expo and succesfully generated the apk and installed on a real android device but it looks like the states are not even inexistence so even though i could fill in the values, the states never updated and the logic that get the states and use them for calculation did not work

in a nut shell, there is a problem with the states

**Comment by dhaniel073** [comment] 2023-10-25 20:16
Good day guy...i created a  build for my application....the build was successful but after i installed the application it loaded the image of the application and stopped there and isn't moving anymore but when i run it from command prompt it goes smoothly and works well...Please help me out guys
