### ISSUE TITLE
Location.watchHeadingAsync stalls the JS thread

### ISSUE THREAD

**Issue by L-A** [expo/expo#4266] opened 2019-05-20 15:20 UTC
### Environment

Client version on iOS: `2.11.0.6067`

```
$ expo diagnostics

Expo CLI 2.18.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.18.0
```

Currently targeting iOS only, on my personal device (iPhone XS).

### Steps to Reproduce

See lower for a repo + demo.

Basically: Bind anything except the simplest `setState()` to `watchHeadingAsync` and run it on a physical device. As soon as the device rotates, the JS thread drops dramatically.

### Expected Behavior

Since `watchHeadingAsync` offers no built-in throttling (ex. only update on Δ > 5°), it's probably reasonable to expect a minimum of headroom in terms of CPU usage.

### Actual Behavior

As soon as `watchHeadingAsync` is given a callback, the JS thread is at risk of dropping. Currently, writing my own throttling is already too heavy of a callback for a new iPhone XS to manage, and the JS thread can drop to 0 fps when the phone rotates slowly, even on a 20° throttle:

![IMG_99DB1F1112C0-1](https://user-images.githubusercontent.com/861964/58031867-5ac2d080-7aef-11e9-89c5-e9323c9e00d8.jpeg)

### Reproducible Demo

Here is a barebones demo of the behavior. Only `App.js` is modified from `expo init`: https://github.com/L-A/expo-heading-demo/blob/master/App.js#L15-L18

```javascript

export default class App extends React.Component {
  state = { heading: 0 };

  async componentDidMount() {
    let { status } = await Permissions.askAsync(Permissions.LOCATION);
    if (status === "granted") {
      Location.watchHeadingAsync(this.updateHeading);
    }
  }

  updateHeading = headingObject => {
    // console.log("Uncomment me to stall the JS thread on heading events");
    this.setState({ heading: headingObject.trueHeading });
  };

  render() {
    return (
      <View style={styles.container}>
        <Text>Orientation: {this.state.heading}</Text>
      </View>
    );
  }
}

```

I'd love to learn I'm just doing something wrong! However, the same code appeared to run without any issues around february this year. I'm having a hard time investigating what version introduced the issue since it's on the Expo client's side.

Cheers! I'd be happy to provide  _anything_ else that can help.

**Comment by L-A** [comment] 2019-06-01 19:48
Additional info: Seemingly, the issue isn't present on a _published_ application, only in dev mode.

This is all in client version `2.11.0.6067`

**Comment by lukmccall** [comment] 2019-07-15 12:20
Have you observed same issue on different phone with iOS? Also, could you check if `watchHeadingAsync` will stalls thread on SDK 33? I need more information, because I couldn't reproduce same behaviour.

**Comment by L-A** [comment] 2019-07-15 12:30
Hi @lukmccall! I'll be able to test on a different phone and SDK 33 early next week, I'll give you a heads up as soon as I have the info.

**Comment by L-A** [comment] 2019-07-23 13:43
@lukmccall After bumping the same test case to SDK 33 and trying on several devices, I see no more drop-offs using `watchHeadingAsync`. This seems limited specifically to SDK 32 in dev mode.

**Comment by lukmccall** [comment] 2019-07-23 14:52
@L-A Thanks you for checking it. I'm closing this issue. If the same situation will occur in the future, feel free to open issue again.

**Closed by lukmccall** 2019-07-23 14:52 UTC
Labels: Location, project: ios-runtime, status: needs more info
