### ISSUE TITLE
[expo-notification] - bug, variation of the icon and the color.

### ISSUE THREAD

**Issue by t-heu** [expo/expo#10798] opened 2020-10-25 17:01 UTC
## 🐛 Bug Report Expo-Notification

its color and icon are not being applied correctly.

### `expo diagnostics`
SDK Version: 39
Platforms(Android/iOS/web/all): Android
```
Expo CLI 3.28.1 environment info:
System:
OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
Shell: 4.4.20 - /bin/bash
Binaries:
Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
Yarn: 1.22.5 - /usr/bin/yarn
npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
SDKs:
Android SDK:
API Levels: 23, 28, 29
Build Tools: 28.0.3, 29.0.3
System Images: android-29 | Google APIs Intel x86 Atom
npmPackages:
expo: ^39.0.3 => 39.0.3
react: 16.13.1 => 16.13.1
react-dom: 16.13.1 => 16.13.1
react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
react-native-web: ~0.13.7 => 0.13.18
npmGlobalPackages:
expo-cli: 3.28.1
Expo Workflow: managed
```

app.json
```
{
  "expo": {
    "name": "Reveal",
    "slug": "Reveal",
    "version": "1.0.4",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "primaryColor": "#27ae60",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#121212"
    },
    "scheme": "reveal",
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "androidStatusBar": {
      "backgroundColor": "#282828",
      "translucent": false
    },
    "notification": { 
      "icon": "./assets/iconPushNotification.png",
      "color": "#27ae60"
    },
    "android": {
      "package": "com.reveal.reveal",
      "versionCode": 1,
      "useNextNotificationsApi": true,
      "googleServicesFile": "./google-services.json",
      "permissions": [
        "CAMERA_ROLL",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE"
      ]
    },
    "ios": {
      "supportsTablet": true
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
```

1 image - When server push notification with application under development.
2 image - When I send notification directly from firebase to the application.
3 image - When server pushes notification of application in production (apk already generated).

![Screenshot_20201025-134409~2](https://user-images.githubusercontent.com/25287877/97113431-0d299a80-16c9-11eb-90c4-cf7005a0880d.png)
![Screenshot_20201020-141037~2](https://user-images.githubusercontent.com/25287877/97113438-17e42f80-16c9-11eb-82de-ff3d60e7eb3e.png)
![Screenshot_20201020-222020~2](https://user-images.githubusercontent.com/25287877/97113440-1d417a00-16c9-11eb-872f-49645a06f258.png)

**Comment by cruzach** [comment] 2020-10-26 13:49
duplicate of https://github.com/expo/expo/issues/10469

I'm looking into this, but for now there are some easy workarounds:
> The bug with `expo-notifications` (that is not present in the legacy Notifications module, which is still available if you'd like to fall back to that) is that `notification.color` is not applied to notifications. **You can work around this by setting the `color` in your [`NotificationContentInput`](https://docs.expo.io/versions/latest/sdk/notifications/#notificationcontentinput)**

> There is also an issue that your notification icon no longer defaults to your app icon, but **this can be worked around by setting the `notification.icon` attribute in app.json**. We may be able to add in some handling to default to a greyscale of your app icon, but for now relying on `notification.icon` is your best best. Also, when creating that icon, we recommend following [Googles guidelines](https://material.io/design/iconography/product-icons.html#design-principles) (otherwise your app icon may just show up as a blank square).

**Closed by cruzach** 2020-10-26 13:49 UTC
Labels: Android, Issue needs review, Notifications

**Comment by komelabbbas** [comment] 2020-12-11 13:37
Notification icon not showing in Android Platform.
how can I fix it..?
pla help
Expo SDK 40.
expo-notifications latest version
