### ISSUE TITLE
[docs] npm packge expo-splash-screen behind documentation on github

### ISSUE THREAD

**Issue by Astrejoe** [expo/expo#9047] opened 2020-07-01 07:30 UTC
The [npm package for expo-splash-screen](https://www.npmjs.com/package/expo-splash-screen) is behind the [github page documentation](https://github.com/expo/expo-cli/tree/master/packages/configure-splash-screen) and behind the expo-splash-screen script. When I run the expo-splash-screen scripts, it adds `SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, false);` to MainActivity.java. However, when I then try to run the app, I get the following error: `/MainActivity.java:19: error: incompatible types: boolean cannot be converted to Class<? extends ViewGroup>
    SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, false);` I fixed it by replacing `false` as the third argument with `ReactRootView.class`.
This seems to be due to the fact that the newest npm package for expo-splash-screen (version 0.3.1) doesn't include the code for the status-bar configuration yet. This would make sense as this code was added 23 days ago, and the npm package was updated a month ago.

**Comment by byCedric** [comment] 2020-07-01 14:02
Hi @Astrejoe, thanks for your issue report! I can confirm the wrong version of `@expo/configure-splash-screen` is included in `expo-splash-screen`. As a workaround, you can use `npx @expo/configure-splash-screen@0.1.10 '#ffffff' --resize-mode contain`. This adds the proper line to your `MainActivity.java`:

```
SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class);
```

Can we push this update to SDK 38, or rollback `@expo/configure-splash-screen` to `0.1.10`? @bbarthec

**Comment by bbarthec** [comment] 2020-07-02 08:50
@byCedric, I believe rollback is the most desired way of solving this thing right now. I'm not sure though if it's possible to rollback at this point 😞 The other solution would be to publish `expo-splash-screen` with `@expo/configure-splash-screen` dependency set to a specific version number.

**Comment by hardcodet** [comment] 2020-07-07 15:33
Can we just get rid of that dependency altogether again? I had to install it to get it running on android, now had to actually run the config script to get it running on ios, too, which now broke my android setup. and i really don't want that splash screen in the first place :)

**Comment by Astrejoe** [comment] 2020-07-12 17:36
Any updates?

**Comment by hazelf42** [comment] 2020-07-21 20:19
Fixed it by changing to "ReactRootView.class" to "false" , is there a different fix available now?

**Comment by erikhu** [comment] 2020-08-05 20:41
on the other way i have this:
error: incompatible types: Class<ReactRootView> cannot be converted to boolean
    SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class);

could it be solve without change ReactNativeView.class by false?

**Comment by josmas** [comment] 2020-08-06 14:48
I am seeing the same issue as @erikhu which seems to be the **_opposite_** to the original report. The line seems to be correctly inserted as:
```
  SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class); // This line is handled by 'expo-splash-screen' command and it's discouraged to modify it manually
```

while the current error is:
```
  android/app/src/main/java/com/thunkable/live/MainActivity.java:19: error: incompatible types: Class<ReactRootView> cannot be converted to boolean
```

I originally was not using expo-status-bar but after having added it, the error does not change.
"expo": "^38.0.0",
"expo-splash-screen": "^0.3.1",
"expo-status-bar": "^1.0.2",

**Comment by KieranO547** [comment] 2020-08-12 14:28
@josmas Just want to add I also have the same error you are having with it saying `Class<ReactRootView> cannot be converted to boolean`, although I did not upgrade 37 to 38, I started on 38 from the start? 
I'm on: 
```
    "expo": "~38.0.8",
    "expo-splash-screen": "^0.3.1",
```

**Comment by agapaymarlo** [comment] 2020-08-13 04:39
any update how to resolve this?
mine:
`"expo": "^38.0.0",
    "expo-asset": "~8.1.7",
    "expo-constants": "~9.1.1",
    "expo-splash-screen": "^0.3.1",
    "expo-status-bar": "^1.0.0",
    "expo-updates": "~0.2.10",
    "expo-web-browser": "~8.3.1",`

**Comment by wooklym** [comment] 2020-08-14 06:19
same here.
```
incompatible types: Class<ReactRootView> cannot be converted to boolean
    SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class);
```

**Comment by brentvatne** [comment] 2020-08-14 06:21
install the latest version of expo-splash-screen on npm

**Comment by wooklym** [comment] 2020-08-14 06:23
> install the latest version of expo-splash-screen on npm

"expo-splash-screen": "^0.5.0"

this is my version, the latest

**Comment by wooklym** [comment] 2020-08-15 03:19
@brentvatne 
https://github.com/expo/expo/commit/2770008129aef794dcdf5fcdaa35ef5056b6ff29#diff-70eefa11c7e96de30d02e5d069488fe2
It looks like this commit will fix the problem, but it doesn't appear to have been released yet.
It would have been nice if you had spoken properly about this.

**Comment by HarryPaulo** [comment] 2020-08-15 16:12
Olá, eu tive o mesmo problema, porem resolvi seguindo o seguinte a documentação :  https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-installation-in-bare-react-native-projects

eu fiz o eject com o "bare workflow", with v38 and i get this error too, mas eu resolvi aplicando a seguinte linha:

![image](https://user-images.githubusercontent.com/25017988/90316491-ed237100-def8-11ea-92d0-94fc34eed7fa.png)

**Comment by HarryPaulo** [comment] 2020-08-15 16:12
Hello, I had the same problem, but I decided following the following documentation: https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-installation-in-bare-react-native -projects

I made the eject with the "bare workflow", with v38 and i get this error too, but I solved it by applying the following line:

![image](https://user-images.githubusercontent.com/25017988/90316502-04625e80-def9-11ea-8708-63421ab99a00.png)

**Comment by HarryPaulo** [comment] 2020-08-15 16:15
Hello, 
I made the eject with the "bare workflow", with v38 and i get this error too, but I decided following the following documentation: https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-installation-in-bare-react-native -projects

Doc code:
![image](https://user-images.githubusercontent.com/25017988/90316553-4be8ea80-def9-11ea-99d8-d73167fd04cb.png)

My code:
![image](https://user-images.githubusercontent.com/25017988/90316538-35db2a00-def9-11ea-87ea-3d8cc3689f71.png)

**Comment by erikhu** [comment] 2020-08-17 13:21
basically i solve the problem removing the package-lock.json and npm install, after that the MainActivity on line SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class);
i was changing ReactRootView.class by false that's it

**Comment by bbarthec** [comment] 2020-09-28 14:38
Just published https://www.npmjs.com/package/expo-splash-screen/v/0.6.2 contain a fix for the recent version of `expo-splash-screen` module. All you need to is to update your `expo-splash-screen` module to this `v0.6.2`. The fix is coming from also recently published https://www.npmjs.com/package/@expo/configure-splash-screen/v/0.2.0.
I'm closing this issue, but if the problem persists please reopen this issue 😉

**Closed by bbarthec** 2020-09-28 14:38 UTC
Labels: Bare Workflow, SplashScreen, bug

**Comment by Abby9111** [comment] 2020-11-12 05:24
SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN,ReactRootView.class, false);
  it works
