### ISSUE TITLE
[Expo 50] Unable to load dev client bundle on Android device

### ISSUE THREAD

**Issue by stefan-schweiger** [expo/expo#26364] opened 2024-01-11 16:54 UTC
### Minimal reproducible example

https://github.com/stefan-schweiger/expo50-prebuild-bug

### Summary

After upgrading my app from SDK 49 to SDK 50 and building a new dev client my app stopped to correctly load bundles on my physical Android device. It works fine on an iPhone.

When I connect the dev client the development server I don't see the usual `BUNDLE  ./index.js` in the console and I get this error in the app itself:

```
There was a problem loading the project.

This development build encountered the following error.

Unable to load script. Make sure you're either running Metro (run 'npx react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
```

I've [created a reproduction](https://github.com/stefan-schweiger/expo50-prebuild-bug) which is basically just the Expo 50 template with the dev client installed. To build I'm using the following steps:

- `npx expo prebuild -p android --clean`
- `cd ./android`
- `./gradlew app:assembleDebug`
- Install the apk from `./android/app/build/outputs/apk/debug` on your physical device
- `npx expo start`
- Connect to the dev server

The weird thing is if I only do `expo run:android` the app opens up as expected on the emulator and works.

I have reproduced this behavior between a Windows and a Mac as the server host.
The same application works fine with SDK 49.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.5.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - /opt/homebrew/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
```

```
skdmanager --list

  Path                                           | Version      | Description                             | Location                                      
  -------                                        | -------      | -------                                 | -------                                                             
  build-tools;30.0.3                             | 30.0.3       | Android SDK Build-Tools 30.0.3          | build-tools/30.0.3                            
  build-tools;31.0.0                             | 31.0.0       | Android SDK Build-Tools 31              | build-tools/31.0.0                            
  build-tools;33.0.0                             | 33.0.0       | Android SDK Build-Tools 33              | build-tools/33.0.0                            
  build-tools;33.0.1                             | 33.0.1       | Android SDK Build-Tools 33.0.1          | build-tools/33.0.1                            
  build-tools;34.0.0                             | 34.0.0       | Android SDK Build-Tools 34              | build-tools/34.0.0                            
  cmake;3.18.1                                   | 3.18.1       | CMake 3.18.1                            | cmake/3.18.1                                  
  cmake;3.22.1                                   | 3.22.1       | CMake 3.22.1                            | cmake/3.22.1                                  
  cmdline-tools;5.0                              | 5.0          | Android SDK Command-line Tools          | cmdline-tools/5.0                             
  cmdline-tools;latest                           | 12.0         | Android SDK Command-line Tools (latest) | cmdline-tools/latest                          
  emulator                                       | 33.1.24      | Android Emulator                        | emulator                                      
  ndk;21.4.7075529                               | 21.4.7075529 | NDK (Side by side) 21.4.7075529         | ndk/21.4.7075529                              
  ndk;23.1.7779620                               | 23.1.7779620 | NDK (Side by side) 23.1.7779620         | ndk/23.1.7779620                              
  ndk;24.0.8215888                               | 24.0.8215888 | NDK (Side by side) 24.0.8215888         | ndk/24.0.8215888                              
  ndk;25.1.8937393                               | 25.1.8937393 | NDK (Side by side) 25.1.8937393         | ndk/25.1.8937393                              
  patcher;v4                                     | 1            | SDK Patch Applier v4                    | patcher/v4                                    
  platform-tools                                 | 34.0.5       | Android SDK Platform-Tools              | platform-tools                                
  platforms;android-30                           | 3            | Android SDK Platform 30                 | platforms/android-30                          
  platforms;android-31                           | 1            | Android SDK Platform 31                 | platforms/android-31                          
  platforms;android-32                           | 1            | Android SDK Platform 32                 | platforms/android-32                          
  platforms;android-33                           | 3            | Android SDK Platform 33                 | platforms/android-33                          
  platforms;android-34                           | 2            | Android SDK Platform 34                 | platforms/android-34                          
  sources;android-31                             | 1            | Sources for Android 31                  | sources/android-31                            
  sources;android-34                             | 2            | Sources for Android 34                  | sources/android-34                            
  system-images;android-31;default;arm64-v8a     | 4            | ARM 64 v8a System Image                 | system-images/android-31/default/arm64-v8a    
  system-images;android-31;google_apis;arm64-v8a | 11           | Google APIs ARM 64 v8a System Image     | system-images/android-31/google_apis/arm64-v8a
  system-images;android-33;google_apis;arm64-v8a | 15           | Google APIs ARM 64 v8a System Image     | system-images/android-33/google_apis/arm64-v8a
  system-images;android-34;google_apis;arm64-v8a | 12           | Google APIs ARM 64 v8a System Image     | system-images/android-34/google_apis/arm64-v8a
```

```
Android Device:
  Oneplus 6T
  Android 11
```

**Comment by stefan-schweiger** [comment] 2024-01-11 17:06
I can access 'http://192.168.0.10:8081' just fine from the phones browser btw, so I don't think it's any network related issues. I sadly don't have any other android devices on me to test the issue, but maybe it's an incompatibility with Android 11 (even though expo should support 6 and up)?

**Comment by sean-fletching** [comment] 2024-01-12 02:04
I am also experiencing this using a dev-client build installed on a physical Android. Physical iOS build also correct. Also SDK 50 beta.

**Comment by tslater** [comment] 2024-01-13 12:00
I'm seeing the same thing. My iOS build is working fine. Also, I get some logging when I hit "refresh" or initially connect on the dev client:
"Using src/app as the root directory for Expo Router." 
So I'm confident there is network access and that the dev client is connecting to the server.

**Comment by alanjhughes** [comment] 2024-01-13 15:20
Hi @stefan-schweiger - I ran your repro but didn't see the problem. The app loaded correctly. I followed your steps exactly. No changes on my end. What device and OS version are you testing on? Also noticed you are using `Node: 21.5.0` can you try on 18?

**Comment by stefan-schweiger** [comment] 2024-01-13 15:30
@alanjhughes tried the same with node 18 and still running into this error. As mentioned in the original issue I'm running Android 11 on a OnePlus 6T. Not sure if that is helpful but Google Play system update is from "11. November 2023" and security update is from "2021-11-01". Someone else was also mentioning this happening on Android 10. So it might only affect older versions? @tslater what version are you running?

That said the same app works perfectly fine with SDK 49.

**Comment by alanjhughes** [comment] 2024-01-13 15:53
@stefan-schweiger if you use `expo run:adroid -d` and select the physical device, is it the same result?

**Comment by tslater** [comment] 2024-01-13 15:57
My test device is Android 11. I can try another device later.
![Screenshot_20240113-105558](https://github.com/expo/expo/assets/449326/7cdadb8a-7265-4eeb-afca-43d86b1efb4b)

**Comment by stefan-schweiger** [comment] 2024-01-13 16:00
@alanjhughes haven't thought of that, but it actually started working this way. But even more amazingly my method started to work as well. As it turns out it just does not work when you have (wireless) debugging disabled on your device / adb not connected. As soon as I do that it stops working again.

**Comment by alanjhughes** [comment] 2024-01-13 16:16
When you get the error, have you an emulator open? I reproduced but can fix it by running `adb reverse tcp:8081 tcp:8081`

**Comment by stefan-schweiger** [comment] 2024-01-13 16:18
@alanjhughes no also happens when no emulator is running. Also `adb reverse tcp:8081 tcp:8081` just returns this for me

`adb: error: no devices/emulators found`

**Comment by alanjhughes** [comment] 2024-01-13 16:19
@stefan-schweiger  Is your device plugged in? It should detect it?

**Comment by stefan-schweiger** [comment] 2024-01-13 16:26
@alanjhughes no it's not plugged in / wirelessly connected to adb. USB debugging / USB OTG has never worked on this device for whatever reason and when I connect wirelessly via adb I need to enable wireless debugging and then it starts working anyways.

**Comment by alanjhughes** [comment] 2024-01-13 16:32
@stefan-schweiger Ok, there's nothing we do to change wireless debugging behaviour, so this would be an issue in android and adb if it's unreliable.

**Comment by stefan-schweiger** [comment] 2024-01-13 16:34
@alanjhughes and I don't expect you to. I just expect that the dev client is able to run on a android device without having any kind of Android debugging enabled as it did with SDK 49.

**Comment by tslater** [comment] 2024-01-13 16:38
This is how I've been doing my build and install:
`eas build --profile=developmentSimulator  --platform=android --local --clear-cache`
`adb install build-1705142081366.apk`

Gonna try  `npx expo run:android -d`

**Comment by alanjhughes** [comment] 2024-01-13 16:39
@stefan-schweiger I'm just trying to be clear. I'm not suggesting you want us to fix it.

Between 49 and 50, android 14 was released with updates to all android tooling. It's possible there's been a regression somewhere.

**Comment by tslater** [comment] 2024-01-13 16:49
Ok, I can confirm that `npx expo run android -d` gets me past the error

**Comment by tslater** [comment] 2024-01-13 16:56
Subsequent runs of the same binary don't connect back to metro, only the first run.

**Comment by alanjhughes** [comment] 2024-01-13 17:14
@tslater - have you tried the adb command mentioned above?

**Comment by tslater** [comment] 2024-01-13 17:32
@alanjhughes Just tried it and it works when run:
`adb reverse tcp:8081 tcp:8081`

A little surprised though because it was clearly able too access the metro server via that port already?

**Comment by theduardomaciel** [comment] 2024-01-14 20:53
A little off topic but still related, have any of you been having problems with Fast Refresh not working in builds generated in EAS that result in this error, without these workarounds?

**Comment by tslater** [comment] 2024-01-14 22:16
Can confirm that fast refresh is not working when I build with the
workaround

**Comment by brentvatne** [comment] 2024-01-15 01:49
> A little off topic but still related, have any of you been having problems with Fast Refresh not working in builds generated in EAS that result in this error?

is this in SDK 50 beta for Android? we're investigating a related issue right now: https://github.com/expo/expo/issues/26254

**Comment by theduardomaciel** [comment] 2024-01-15 03:05
Yea, yea, running SDK 50.0.0-preview.10. Already tested on some other previous preview versions to see if it was specific to the preview version I was using, but no success.
Anyway, good to know that it's already in your guys knowledge!

**Comment by alanjhughes** [comment] 2024-01-16 09:15
The fast refresh problem is a separate issue so I'll close this. The solution when you encounter this problem when running on a real device is to run `adb reverse tcp:8081 tcp:8081` which is also called out in the [react-native](https://reactnative.dev/docs/running-on-device#method-1-using-adb-reverse-recommended) docs

**Comment by stefan-schweiger** [comment] 2024-01-16 09:24
@alanjhughes the mentioned part in the documents is only in relation for USB debugging. For wireless debugging it's never mentioned that you need to connect your device via ADB. And this is what's not working currently with expo for me.

**Comment by isaachinman** [comment] 2024-01-16 09:28
This issue should not be closed. There is currently a massive regression of functionality between v49 and v50. If ignored now, you will have an influx of bug reports when releasing to stable.

**Comment by sean-fletching** [comment] 2024-01-17 15:59
> @stefan-schweiger When you get the error, have you an emulator open? I reproduced but can fix it by running `adb reverse tcp:8081 tcp:8081` This fixes it for me whether wireless debugging is off or on

Thank you for posting this. It helped me get my dev-client back and operational where I had timeouts connecting to the metro server.

For anyone interested, I am running on ChromeOS, and this requires me to build a dev-client on eas, which then I can adb install and go from there. Previously it did not require this `adb reverse` command.

**Comment by tslater** [comment] 2024-01-18 04:44
@alanjhughes If I build in EAS Build, I should need adb to develop at all, right? Isn't that the point of the dev client. This isn't about usb-debugging, but just running the dev client.

**Comment by josh-** [comment] 2024-01-19 06:27
> This issue should not be closed. There is currently a massive regression of functionality between v49 and v50. If ignored now, you will have an influx of bug reports when releasing to stable.

yep - we've just upgraded from expo 49 to 50 and are we're now encountering this error when attempting to use development builds (wirelessly) via `expo start` on Android, which was working perfectly fine in 49.

**Comment by usmansbk** [comment] 2024-01-19 06:58
Upgraded from 49 to 50 yesterday and encountered this problem.

**Comment by alanjhughes** [comment] 2024-01-19 10:00
> @alanjhughes If I build in EAS Build, I should need adb to develop at all, right? Isn't that the point of the dev client. This isn't about usb-debugging, but just running the dev client.

@tslater - We run `adb` inside the cli, so yes, you do need it, the requirements of react native still apply. Windows and mac both run android studio so the expectation is it is installed. This is how you allow a physical android device to communicate with your local network, there's no way around it unfortunately. I'll investigate further.

**Comment by BrianValente** [comment] 2024-01-19 18:27
Same problem here, dev client is broken on Android

**Comment by theprashant-one** [comment] 2024-01-19 19:29
![Screenshot_20240119_030937_Submind 50.jpg](https://github.com/expo/expo/assets/26407503/18bbf4f8-7cf1-4f21-af96-410c2ff7fed2)

Same problem on Android

**Comment by gjtiquia** [comment] 2024-01-19 23:54
> The fast refresh problem is a separate issue so I'll close this. The solution when you encounter this problem when running on a real device is to run `adb reverse tcp:8081 tcp:8081` which is also called out in the [react-native](https://reactnative.dev/docs/running-on-device#method-1-using-adb-reverse-recommended) docs

Had the same error and this worked for me. But your device has to be connected by USB. Using Expo wirelessly still results in the same error. But this workaround is good enough for me right now though.

**Comment by tslater** [comment] 2024-01-19 23:56
Just to clarify, @alanjhughes, I used to be able to run my expo dev client over wifi, just connecting to my metro server. Is that not going to be supported anymore? We will need to run wired with `adb reverse tcp:8081 tcp:8081` all the time now?

**Comment by usmansbk** [comment] 2024-01-20 05:25
@gjtiquia how is that a solution? I don't use adb at all. I connect with WiFi like Expo Go. If Expo Go can work then Dev Client can definitely work too.

**Comment by wodin** [comment] 2024-01-20 05:58
@alanjhughes this started happening to me last night on Expo SDK 49

This was with Expo Go or a dev client.

Snack still works fine.

Then I upgraded the app to Expo SDK 50 and it started working again. I have not connected my phone via USB or run `adb reverse` since this problem suddenly started happening.

Will see if I can reproduce it again

**Comment by alanjhughes** [comment] 2024-01-20 06:59
Thanks for the info @wodin had a feeling this wasn't isolated to 50 as we've made no changes related to it. It seems like a regression in adb. Still investigating, I haven't nailed down the steps to get it to reproduce reliably.

**Comment by tslater** [comment] 2024-01-20 07:12
Just to clarify a bit more, does running `expo start` also run adb? I swear
that I've been able to connect android devices to my expo server without
adb even being installed. Maybe it was, just being managed by expo? This
only happened once I set up a dev env for Android.  Is it possible that
setting up that env created a separate installation of adb that somehow
messed with what `expo start` does?

**Comment by wodin** [comment] 2024-01-20 07:33
@alanjhughes I'm not sure what `adb` has to do with it. I thought it wasn't involved when talking to e.g. Snack or a remote machine? Isn't it only relevant when connected via USB?

**Comment by wodin** [comment] 2024-01-20 07:39
Anyway, I created a new dev build. I could not install it over the broken one. I first had to uninstall that. After installing the new one I no longer get the error.

Again, I have not connected the phone via USB or run any `adb` commands since I started getting this error.

**Comment by wodin** [comment] 2024-01-20 07:47
@tslater I remember the old `expo-cli` bundling a copy of `adb` in the past, but after a quick look I don't see a bundled version of `adb` in `@expo/cli` or similar.

**Comment by alanjhughes** [comment] 2024-01-20 12:11
> @alanjhughes I'm not sure what `adb` has to do with it. I thought it wasn't involved when talking to e.g. Snack or a remote machine? Isn't it only relevant when connected via USB?

Everything related to android in the cli runs through `adb` so I would think it is related. Using `EXPO_DEBUG=1` you can see what commands the cli is using. Running `EXPO_DEBUG=1 npx expo start` shows this output
```bash
  expo:start:platforms:android:adbServer /Users/alanhughes/Library/Android/sdk/platform-tools/adb devices -l +0ms
  expo:start:platforms:android:adbServer /Users/alanhughes/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu avd name +20ms
  expo:start:platforms:android:adbServer /Users/alanhughes/Library/Android/sdk/platform-tools/adb -s 38111JEHN00796 reverse tcp:8081 tcp:8081 +18ms
```
@tslater Yes, we require the android SDK to be installed and sdk tools, and with that, comes adb. 
[Here](https://github.com/expo/expo/blob/7b2daec86ce0a998264ed6ed4342ca6c6720ba2e/packages/%40expo/cli/src/start/platforms/android/ADBServer.ts#L23) is where we look for the executable. So the issue is, given we are calling it for you, why is `adb reverse` not working in some instances.

**Comment by JustJoostNL** [comment] 2024-01-20 17:24
Same issue on SDK 50 iOS (not simulator) here.

**Comment by wodin** [comment] 2024-01-20 17:33
> Everything related to android in the cli runs through `adb`

@alanjhughes thanks, I think I have figured out our miscommunication :)

To start with, I currently have no emulators running and no phones connected via USB cable:

```console
% adb devices
List of devices attached

%
```

When I run `EXPO_DEBUG=1 npx expo start` with a *working* dev build, I get absolutely no messages related to `adb`. I just run the dev build on my phone and select the auto-detected dev server, or else scan the QR code, or type in the URL and it connects, downloads the bundle, and everything is fine.

Only if I press `a` do I get stuff about `adb`. But that's not what we're talking about. We're talking about just trying to connect to a dev server over the network by scanning the QR code, typing in the URL, etc.

**Comment by wodin** [comment] 2024-01-20 17:41
@stefan-schweiger can you confirm that when you say "Connect to the dev server" you are *not* talking about pressing `a` in the terminal, but rather you mean something like "Scan the QR code", or "Select the detected dev server", or "Type in the URL of the dev server"?

**Comment by stefan-schweiger** [comment] 2024-01-20 17:50
@wodin what I do is:

1. Install the apk
2. run `nox expo start`
3. either scan the QR code or manually enter http://<devserverip>:8081

Not having the phone connected via usb or (wireless) adb, only being on the same network.

Works perfectly fine on SDK 49 but not on 50.

**Comment by wodin** [comment] 2024-01-20 18:17
Thanks for the clarification. By the way, I was getting the problem in Expo SDK 49, but not 50. And after rebuilding the Expo SDK 49 version, uninstalling the broken app from my phone and then installing the newly built one, it worked for me.

**Comment by flygomel** [comment] 2024-01-20 18:34
same error on android SDK 50:

**Comment by serdarde** [comment] 2024-01-20 22:25
I have the same problem and the wireless doesn't work at all, but if you want to run it with a cable you can follow those steps:

- Turn on your android phone's developer mode (make a quick search, it depends on your device type)
- Connect your phone with a cable
- Both of devices will ask for permissions, accept them
- Be sure that you have installed the android's platform-tools
- Run `adb devices`, if you see your device fine, if not be sure that you completed above steps properly
- Run `reverse tcp:8081 tcp:8081` and re-try to start the project

**Comment by rohankm** [comment] 2024-01-21 14:05
im also facing the same problem after upgrading to sdk 50

**Comment by renequez** [comment] 2024-01-21 14:42
had the same problem after upgrading from 49 to 50. what worked for me were following steps (mind that i'm only working with android):

1. clean the android folder: `expo prebuild --clean --platform android`
2. re-build the app: `expo run:android` (at this point it would work fine, but i would eventually get the error on subsequent starts)
3. run: **`adb reverse tcp:8081 tcp:8081`** (THIS is the only new thing that i've changed. i didn't need it on sdk 49)
4. start the app: `expo start -c`

now everything works as before. hope it helps someone else ✌️

**Comment by rainerllera** [comment] 2024-01-21 19:58
also facing this after upgrading to v50

**Comment by floki-92** [comment] 2024-01-21 23:46
for me it only works with cable after adb reverse tcp:8081 tcp:8081
still a regression unfortunately

**Comment by petecoop** [comment] 2024-01-22 10:34
Seeing the same issue, I have to be connected to ADB and reverse 8081 for it to work. Previously I didn't need to be connected to ADB and could use the network IP - it even finds that network IP in the dev client and shows a green online status, but get the same error. It looks like some change when not connecting by "localhost" that is causing this

**Comment by younes0** [comment] 2024-01-24 06:11
Back to SDK 49 after trying expo 50.0.3 & trying adb reverse.
Android logs shows it tries to connect to localhost despite REACT_NATIVE_PACKAGER_HOSTNAME setup properly (no issues with iOS).
```
14:01:06.590  W  Couldn't connect to "ws://localhost:8081/message?device=CPH2449%20-%2014%20-%20API%2034&app=ccom.myproject.app.dev&clientid=DevLauncherDevSupportManager", will silently retry
14:01:06.602  W  Couldn't connect to packager, will silently retry
14:01:06.726  W  The packager does not seem to be running as we got an IOException requesting its status: unexpected end of stream on http://localhost:8081/..
```

**Comment by auchEnia** [comment] 2024-01-24 09:05
I can confirm this was fix, but only for the default port `8081`. When using a different port - e.g. `8082` the same issue as before persists. In that case `adb reverse tcp:8081 tcp:8082` fixes the issue, just like before.

**Comment by younes0** [comment] 2024-01-24 11:37
@brentvatne thanks. indeed, `expo-dev-client` 3.3.7 wasn't published yet on npm when I posted my comment.

**Comment by GProGamer** [comment] 2024-02-07 13:43
@brentvatne I've already installed expo-dev-client 3.3.8 but still getting the same error

**Comment by brentvatne** [comment] 2024-02-07 17:57
@GProGamer - make sure you rebuild the app after updating expo-dev-client. if a similar issue occurs for you still, can you create a new issue and fill out the issue template? i'll close and lock this particular issue since the underlying root cause was confirmed to be resolved and you may be seeing something else

**Closed** 2024-02-07 17:58 UTC
Labels: Issue accepted, Comments on closed issue
