### ISSUE TITLE
Animated node type parameter not supported natively

### ISSUE THREAD

**Issue by Clonescody** [expo/expo#6930] opened 2020-01-31 13:42 UTC
## 🐛 Bug Report

Hello everyone, hopefully this issue belongs here, I am not so sure about it so feel free to tell me if that's the case. 

### Environment

Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 13.7.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.9 => 5.3.9
      expo: ^34.0.3 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.2.tar.gz => 0.59.8
      react-navigation: ^4.0.10 => 4.1.0

My app was built using expo and is now ejected since I implemented `expo-payments-stripe@6.0.0`. 

### Steps to Reproduce

I have absoluetly no idea about how to reproduce this issue, however I've got the feeling this is related to some module using some native animation thingy. 

I currently have those dependencies in my `package.json` ->

```
"dependencies": {
    "@ptomasroos/react-native-multi-slider": "^1.0.0",
    "buffer": "^5.0.7",
    "expo": "^34.0.3",
    "expo-blur": "~6.0.0",
    "expo-cli": "^3.0.4",
    "expo-font": "~6.0.1",
    "expo-linear-gradient": "~6.0.0",
    "expo-payments-stripe": "~6.0.0",
    "expokit": "34.0.2",
    "formik": "^1.5.8",
    "lottie-react-native": "~2.6.1",
    "moment": "^2.19.1",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.2.tar.gz",
    "react-native-checkbox": "^2.0.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-paper": "^2.16.0",
    "react-native-reanimated": "^1.1.0",
    "react-native-render-html": "^4.1.2",
    "react-native-screens": "1.0.0-alpha.22",
    "react-native-section-list-get-item-layout": "^2.2.1",
    "react-native-simple-gauge": "^0.1.12",
    "react-native-svg": "~9.5.1",
    "react-native-svg-charts": "^5.3.0",
    "react-native-swipeable-row-bouncing": "^0.8.1",
    "react-native-tab-view": "https://github.com/fantattitude/react-native-tab-view.git#new",
    "react-native-unimodules": "0.5.2",
    "react-native-webview": "~5.12.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.5.6",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.10.0",
    "redux-saga": "^1.0.3",
    "reselect": "^4.0.0",
    "sentry-expo": "~1.13.0",
    "slack-notify": "^0.1.7",
    "yup": "^0.27.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "@storybook/addon-actions": "^5.1.9",
    "@storybook/addon-links": "^5.1.9",
    "@storybook/addons": "^5.1.9",
    "@storybook/react-native": "^5.1.9",
    "@storybook/theming": "^5.1.9",
    "babel-eslint": "^9.0.0",
    "eslint": "^6.0.1",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.14.2",
    "flow-bin": "^0.102.0-rc",
    "husky": ">=1",
    "jest-expo": "^34.0.0",
    "jetifier": "^1.6.4",
    "lint-staged": ">=8",
    "prettier": "^1.5.3",
    "prettier-eslint": "^9.0.0",
    "react-devtools": "^3.6.1",
    "react-dom": "16.8.3",
    "react-native-scripts": "^2.0.1",
    "react-native-svg-transformer": "^0.13.0",
    "react-test-renderer": "16.0.0-alpha.12",
    "remote-redux-devtools": "^0.5.12"
  },
```

### Expected Behavior

My app starts

### Actual Behavior

I recently started to have issues on my ejected expo app. 

On android and iOS both the builds are made correctly, I don't get any errors during the xCode build, nor during `./gradlew installDebug`, nor when starting the packager ( with -c option ).

On real devices, the app just starts, shows the splashscreen, then shuts down instantly.

On android device, I get the following error in the expo client : 
`Uncaught error : Unsupported node type: param`
On iOS simulator the app juste closes without any expo client error

On simulators : 
The iOS one gives me a `Animated node type param not supported natively`

Following this error, I added the `useNativeDriver: true` in my Animated components, still got the error. 

The Android simulator just crashes without any additional informations. 

### Reproducible Demo

I will try to publish a snack of this problem. However, I have the feeling that those errors just come from a module that uses Animated components. 

As potential failling modules, I have : 

`"react-native-webview": "~5.12.0",` 
`"react-native-screens": "1.0.0-alpha.22",`
`"react-native-reanimated": "^1.1.0",`
`"react-native-gesture-handler": "^1.3.0",`
and the react-navigation stack which I believe is using Animated components as well. 

I looked everywhere in my project and couldn't find any obvious issue so that's why I'm posting here hoping someone had the same issue. 

Thanks a lot in advance guys. And keep up the good work !

**Comment by cruzach** [comment] 2020-01-31 21:21
This seems to be stemming from `react-native-reanimated`, or at least one of the error messages is- https://github.com/software-mansion/react-native-reanimated/blob/master/ios/REANodesManager.m#L247
 I would make sure that you have compatible versions of each library installed (the `expo install` command automatically installs the best version for your Expo SDK), and for any libraries you installed that need linking (since you're ejected), make sure to follow through on all their additional instructions

Otherwise, it's really difficult to help without a minimal repro. A project with quite a few dependencies like this, narrowing the root cause down isn't as straightforward as in an almost-blank project. If you can get this error message in a minimal project, that would help a lot!

**Comment by dereknelson** [comment] 2020-02-01 21:48
@Clonescody I ran into the same issue on my app, both ejected and managed. I tracked it down to being an issue with react-navigation-tabs. It seems dropping the tabs version down to 1.2.0 has it working fine.

**Comment by cruzach** [comment] 2020-02-03 14:49
Closing since it looks like this is related to installing compatible package version depending on the SDK version. To always install the right version, add your dependencies with `expo install [package-name]`

**Closed by cruzach** 2020-02-03 14:49 UTC
Labels: bug, needs repro, project: expokit

**Comment by manthanpl93** [comment] 2020-02-08 11:40
> @Clonescody I ran into the same issue on my app, both ejected and managed. I tracked it down to being an issue with react-navigation-tabs. It seems dropping the tabs version down to 1.2.0 has it working fine.

Follow this, i solved my problem by following this.

**Comment by mikeygbd** [comment] 2020-02-09 18:45
I to ran into the same issue on my app, but I found an easy solution to this. Instead of trying to figure our which package is giving you the issue just Run: `expo update 35.0.0`. Which will automatically set all the correct versions of your packages to run with expo. Fixed the issue for me instantly.

**Comment by Clonescody** [comment] 2020-02-10 09:32
@dereknelson You saved me, thanks so much 🥇

**Comment by BBARLOCCO** [comment] 2020-03-13 19:11
I didn't know which package was creating the problem, and didn't wanted to upgrade expo Sdk version, expo update 34.0.0 (my same version) did the job!
