### ISSUE TITLE
[expo-av] pauseAsync still with delay

### ISSUE THREAD

**Issue by jcrreis** [expo/expo#6851] opened 2020-01-24 13:38 UTC
https://github.com/expo/expo/issues/5297

Can someone tell me if we have any alternative to this?

**Comment by cruzach** [comment] 2020-01-24 21:20
Hi @jcrreis, unfortunately that bug hasn't been prioritized right now. What would help in getting it resolved as quickly as possible is to dig a little bit more into the issue and identify some probable root causes, or even open up a PR with a solution. [Here's the source code for the expo-av package](https://github.com/expo/expo/tree/master/packages/expo-av)

In the meantime, I'm going to close this as a duplicate of the issue you linked

**Closed by cruzach** 2020-01-24 21:20 UTC
Labels: bug

**Comment by haiyo** [comment] 2023-06-11 15:54
Lol 2020 until now still have the same issue. Guess we all can't go with expo anymore. Just go native.
