### ISSUE TITLE
[IOS][PRODUCTION] getAsync is granted, getExpoPushTokenAsync throws error

### ISSUE THREAD

**Issue by muZk** [expo/expo#2648] opened 2018-11-07 13:43 UTC
### Environment

```
Expo CLI 2.3.3 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.6.0 - ~/.nvm/versions/node/v8.6.0/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.3.0 - ~/.nvm/versions/node/v8.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4670197
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.0 => 30.0.2
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
      react-navigation: ^2.5.5 => 2.5.5
    npmGlobalPackages:
      expo-cli: 2.3.3

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/muzk-857feb81-9501-493f-befd-fbc6361bbe21.tar.gz
```

**Target:** iOS Standalone

### Steps to Reproduce

1. Install the standalone iOS application.
2. Open the app and accept push notification permission. After this, you can get expo token as expected.
3. Now, uninstall the application.
4. Install it again.
5. It [won't ask](https://stackoverflow.com/a/34718602/2056593) you for permissions.
6. Now `Permissions.getAsync(Permissions.NOTIFICATIONS)` will return `granted` 😄 while `Notifications.getExpoPushTokenAsync()` throws an exception.

Here is my code:

```
  const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);
  let finalStatus = existingStatus;

  // only ask if permissions have not already been determined, because
  // iOS won't necessarily prompt the user a second time.
  if (existingStatus !== 'granted') {
    // Android remote notification permissions are granted during the app
    // install, so this will only ask on iOS
    const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
    finalStatus = status;
  }

  // Stop here if the user did not grant permissions
  if (finalStatus !== 'granted') {
    return false;
  }

  // Get the token that uniquely identifies this device
  const token = await Notifications.getExpoPushTokenAsync();
```

### Expected Behavior

- In step 6, `getExpoPushTokenAsync()` should return a valid token and not throw an exception because the permission is `granted`.

### Actual Behavior

- In step 6, `getExpoPushTokenAsync()` throws an exception (`This app does not have permission to show notifications`)

Maybe this issue is related to:
- https://github.com/expo/expo/issues/2555
- https://github.com/expo/expo/issues/2381
- https://github.com/expo/expo/issues/1695
- https://forums.expo.io/t/push-notifications-in-standalone-app-unable-to-get-the-expo-push-token/13173
- https://forums.expo.io/t/notifications-getasync-gives-granted-notifications-getexpopushtokenasync-throws-error/15177

**Comment by muZk** [comment] 2018-11-07 23:44
Updated with valid steps to reproduce.

**Comment by techpanga** [comment] 2018-11-12 21:42
+1

**Comment by kristoferlund** [comment] 2018-11-13 05:49
+1

**Comment by techpanga** [comment] 2019-01-09 01:46
Is this issue resolved with milestone 34. I see sdk 32.0.0 is released. Please comment.

**Comment by techpanga** [comment] 2019-03-13 05:10
Hi 

Do we have any update on this issue. I did tried with clearing certificates and recreating. Nothing worked. Please help.

**Comment by techpanga** [comment] 2019-03-13 15:52
Note: I am not even iOS Objective C beginner. As this is blocking our production notifications, I tried to dig down little bit...

In source code: expo/ios/Exponent/Kernel/Services/Notifications/EXRemoteNotificationManager.m

To not to cause the error "This app does not have permission to show notifications", canRegister variable should have "true".

In our environment (iOS Standalone Expo App, Not Ejected, 32.0.0 SDK), Looks like canRegister variable is getting to false. getNotificationSettingsWithCompletionHandler is getting the settings.authorizationStatus with something else other than Authorized | Provisional.

This was working (might be broken after 12.x upgrade, do not remember exactly) Going to test this on iOS 11.x


`- (void)_canRegisterForRemoteNotificationsWithCompletionHandler:(void (^)(BOOL can))handler
{
  dispatch_assert_queue(_queue);

  // When the user has not granted permission to display any type of notification, iOS doesn't
  // invoke the delegate methods and registering for remote notifications will never complete
  [_userNotificationCenter getNotificationSettingsWithCompletionHandler:^(UNNotificationSettings * _Nonnull settings) {
    bool canRegister = settings.authorizationStatus == UNAuthorizationStatusAuthorized;
    if (@available(iOS 12, *)) {
      canRegister |= (settings.authorizationStatus == UNAuthorizationStatusProvisional);
    }
    handler(**canRegister**);
  }];
}`

Any help from experts is appreciated!

**Comment by mikeyyyzhao** [comment] 2019-03-15 20:34
Same problem here, I'm getting granted back from Permissions.getAsync but getting error below when trying to get the token (let token = await Notifications.getExpoPushTokenAsync())

[Unhandled promise rejection: Error: unsupported URL]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:146:41 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:95:55 in <unknown>
- ... 5 more stack frames from framework internals

**Comment by mguay22** [comment] 2019-04-30 23:25
Getting the same error @mikeyyyzhao - did you ever find a fix for this issue?

**Comment by thierryskoda** [comment] 2019-05-15 19:21
@mguay22 @mikeyyyzhao Getting the same error. Anyone of you fixed the issue?

**Comment by mikeyyyzhao** [comment] 2019-05-15 19:58
@thierryskoda it didn't work for me because I already ejected expo and if I think there was an issue with receiving the token. I ended up using [React-native-push-notification](https://github.com/zo0r/react-native-push-notification). Here is a [good YouTube link]([url](https://www.youtube.com/watch?v=8aaAx6VbY9k)) on how to set everything up

**Comment by mguay22** [comment] 2019-05-15 21:00
Cheers @mikeyyyzhao - I'll give it a look.

**Comment by thierryskoda** [comment] 2019-05-15 21:12
I ejected my app too. But I thought Expo still added some fixes to make it work even if the app is ejected. I'm on SDK 32.

I'm still using https://docs.expo.io/versions/v32.0.0/sdk/notifications/#notificationsgetdevicepushtokenasyncconfig to get the device token and https://github.com/node-apn/node-apn to send notification backend. But would love to simply use Expo backend and Frontend.

**Comment by mguay22** [comment] 2019-05-15 21:17
@thierryskoda Same exact situation for me. SDK 32 and ejected using the Expo implementation in the docs. Getting the unsupported URL error.

Judging by the number of open issues regarding push notifications at the moment, it's probably safe to assume the team is aware of the issue.

For now, I'll use @mikeyyyzhao's suggested third-party solution

**Comment by sjchmiela** [comment] 2019-05-15 21:23
Just to clarify — Expo notifications (getting Expo token too) are supposed to not work in ejected apps. 😕 

When a native application is built, for it to receive the notifications we have to add certificates to the bundle, which we know if we build the app in Turtle. Moreover, the certificates are required when we want to send the notification (authentication against APNS).

That's why you can send notifications with Expo servers when the app is Turtle-built (the sender, i. e. Expo server knows what certificate is in the Turtle-built app) and why you cannot use Expo servers to send notifications to ejected apps (you are the one adding the certificate and building the app).

**Comment by saravanapriyan95** [comment] 2019-10-31 15:04
Hi @sjchmiela, I have detached the expo app, In android the expo token generate's, but in IOS it throws 'unsupported URL' error, 

Can you help me to resolve those issue, Because the app in the production stage

**Comment by saravanapriyan95** [comment] 2019-11-01 13:23
Hi @exAspArk @sjchmiela 

I got the Token, and now how to send the push notification to the Current device (Remote Notification )

Note: Iam Using react-native-push notification, OS: IOS

**Comment by sjchmiela** [comment] 2020-09-21 10:10
Hey all,

I have just tried to reproduce this bug on iOS 14 with SDK 39, app installed via TestFlight using `expo-notifications` and I wasn't able to. I think it may have been resolved! 🙂

**Closed by sjchmiela** 2020-09-21 10:10 UTC
Labels: Notifications, iOS, project: notification-service
