### ISSUE TITLE
Android app installed from google play crashes on start

### ISSUE THREAD

**Issue by Kison** [expo/expo#6490] opened 2019-12-11 17:01 UTC
### Environment

  Expo CLI 3.11.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

Android, Ejected application, SDK 35

### Steps to Reproduce
I migrated SDK from 33 to 35, then I made new android build and published it to google play. After aproval I installed application to my device. When I try to run app it crashes. Important, it works on some devices. Another important thing is that app works on all devices if I run it on local env or expo. 

### Expected Behavior
Run android application without crash

### Actual Behavior
When I run application installed from google play I get such error. 

```
019-12-11 18:25:25.071 20254-20336/com.app.pos E/AppLoader: Could not load app: java.net.SocketException: Connection reset
2019-12-11 18:25:25.073 20254-20254/com.app.pos D/AndroidRuntime: Shutting down VM
2019-12-11 18:25:25.073 20254-20254/com.app.pos E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.pos, PID: 20254
    java.lang.RuntimeException: Expo encountered a fatal error: java.net.SocketException: Connection reset
        at host.exp.exponent.experience.BaseExperienceActivity$2.run(BaseExperienceActivity.java:197)
        at android.os.Handler.handleCallback(Unknown Source:2)
        at android.os.Handler.dispatchMessage(Unknown Source:4)
        at android.os.Looper.loop(Unknown Source:139)
        at android.app.ActivityThread.main(Unknown Source:65)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
        at com.android.internal.os.ZygoteInit.main(Unknown Source:338)
```

**Comment by cruzach** [comment] 2019-12-11 23:40
Did you try upgrading to SDK 34 first, then SDK 35? Especially with Expokit, it's best to upgrade just one SDK at a time to decrease the surface area of possible root causes

**Comment by Kison** [comment] 2019-12-12 13:08
@cruzach, thanks for suggestions. I will check it.

**Comment by tsapeta** [comment] 2020-06-30 12:38
ExpoKit is no longer supported by us so I'm closing this. I recommend migrating to bare workflow if you're still hitting this 🙂

**Closed by tsapeta** 2020-06-30 12:38 UTC
Labels: Android, bug, project: expokit
