### ISSUE TITLE
[Android] Unable to update ExpoKit from 24.0.0 to 25.0.0

### ISSUE THREAD

**Issue by riwu** [expo/expo#1503] opened 2018-03-06 17:53 UTC
### Environment

https://exp-xde-diagnostics.s3.amazonaws.com/riwu-a8efd3d2-7c50-4b88-bc2e-30c0abe30ea2.tar.gz

Android / ExpoKit

### Steps to Reproduce

I followed https://docs.expo.io/versions/latest/guides/expokit.html#android-1 and received the error:
> Failed to resolve: host.exp.exponent:expoview:25.0.0

Also, should `.expo-source/android` reside in the root directory? `.expo-source` did not exist previously. 

Why does `app.json` contain the following property if we are already extracting the `.tar.gz` to the `.expo-source` folder?
```
    "detach": {
      "scheme": "expc6486079dbaf497d82b7e09b38adead8",
      "iosExpoViewUrl":
        "https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.3.3-sdk25.0.0-e7a4361a-631d-4caf-9692-1880d71c394a.tar.gz",
      "androidExpoViewUrl":
        "https://s3.amazonaws.com/exp-exponent-view-code/android-v2.3.0-sdk25.0.0-0c32461b-a7c6-4ddc-b85b-32a80c4f18d9.tar.gz"
    }
```

**Comment by nicknovitski** [comment] 2018-03-06 22:15
Hi riwu!  I think that to upgrade you have to put the source of the v25 expo view in whichever directory you were keeping the source of the v24 view, overwriting it.

I don't know the answer to your other question but I hope @terribleben can help.

**Comment by riwu** [comment] 2018-03-09 10:25
The folder is located at `android/maven/host/exp/exponent/expoview` so the docs need to be updated.
I'm getting another weird error `Error:Failed to resolve: com.facebook.react:react-native:25.0.0` now...

**Comment by esamelson** [comment] 2018-03-22 19:58
Hi @riwu - looks like those upgrade docs are indeed out of date for Android. We'll work on fixing them. Currently looking for a solution for you in the meantime. Thanks for bringing this to our attention!

**Comment by michchan** [comment] 2018-03-30 19:53
@riwu 
This can still be reproduce when upgrading from sdk 25 to 26.
In this case `android/maven/host/exp/reactandroid-abi26_0_0` must also be added

**Comment by dooboolab** [comment] 2018-04-03 05:29
@riwu Yeah.. this is a really annoying thing because to upgrade expokit, you need to create new fresh expo project and move all your project files to there and fix the error then linking your libraries again. Very much time-consuming process. Without android, I was able to upgrade from my project dir but it is just too confusing to upgrade android side from my existing project. Hope there are some guidelines provided for upgrade from previous expokit version.

Also, I've written upgrade journey here in [expo forum](https://forums.expo.io/t/hard-hard-upgrade-from-expokit-again/8261/6).

Please provide us proper upgrade guide for android from expokit!

**Comment by esamelson** [comment] 2018-05-01 17:51
Hi -- many apologies for the delay here. We've written a new upgrade guide, and it will be deployed to docs.expo.io soon. In the meantime, you can read it here: https://github.com/expo/expo-docs/blob/master/versions/v27.0.0/expokit/expokit.md#android-1

Also, if you're upgrading to SDK 27, check out our [one-time upgrade guide](https://gist.github.com/janicduplessis/30ec95451733d34ffcf7d5cb27ba0e28) to help you get bundled assets in your ExpoKit project.

Going to close this now -- if you run into any issues with the above instructions, please open a new ticket or post on our [forums](https://forums.expo.io/)! :)

**Closed by esamelson** 2018-05-01 17:51 UTC
Labels: project: expokit
