### ISSUE TITLE
EAS ValidationError: "buildType" is not allowed.

### ISSUE THREAD

**Issue by chrislondon** [expo/expo#11957] opened 2021-02-16 17:56 UTC
**Summary**

I signed up for the EAS service and when I run `eas build -p ios` I get:

```
√ Uploaded to EAS 1s
    ValidationError: "buildType" is not allowed
```

I tried searching the web and github issues but can't find this error anywhere. How do I resolve it?

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

40.0.1

**Environment**

Windows

**Reproducible demo or steps to reproduce from a blank project**

My guess is this will work fine for others. But any help for my scenario?

**Comment by brentvatne** [comment] 2021-02-16 18:01
can you share your eas.json please? and what version of eas-cli are you using?

**Comment by brentvatne** [comment] 2021-02-16 18:04
it looks like this is a regression in managed builds in the latest version of eas-cli, we'll look into it. sorry for the hassle, thanks for trying out managed builds on eas build before they are ready yet! we hope to get a stable preview release for eas build managed support by end of q1

**Comment by chrislondon** [comment] 2021-02-16 18:21
My eas-cli version is 0.4.0 and my eas.json looks like:

```
{
  "builds": {
    "android": {
      "release": {
        "workflow": "managed"
      }
    },
    "ios": {
      "release": {
        "workflow": "managed"
      }
    }
  }
}
```

**Comment by wkozyra95** [comment] 2021-02-16 18:26
Hi, try updating to 0.4.1, it should be fixed there

**Comment by chrislondon** [comment] 2021-02-16 18:29
That worked. Thanks!

**Closed** 2021-02-16 18:32 UTC
Labels: needs review
