### ISSUE TITLE
Could not decrypt the item in SecureStore

### ISSUE THREAD

**Issue by ShMcK** [expo/expo#1459] opened 2018-02-21 18:26 UTC
### Environment

Pixel, Android version 27 with Expo SDK 25.0.0 - Standalone.

### Error

`Could not decrypt the item in SecureStore` when decoding a users preserved password.

**Comment by brentvatne** [comment] 2018-02-21 18:32
did your keystore change?

cc @ide

**Comment by ShMcK** [comment] 2018-02-21 18:32
No change.

**Comment by ShMcK** [comment] 2018-02-21 18:34
I'm thinking I may have to protect against any possible secure store errors.

```js
let item
try {
  item = await SecureStore.getItemAsync('someItem')
} catch (error) {
  item = null
}
```

**Comment by ide** [comment] 2018-02-21 20:41
Could you provide more information about any changes you may have made? Was this on your phone or some arbitrary user's? Did you use or change the `keychainService` field?

**Comment by ShMcK** [comment] 2018-02-21 21:37
It has occurred on one device, which I have access to, but not yet reproduced on other devices.
No changes have been made to the `keychainService` field.

Example

```js
const credentials = await SecureStore.getItemAsync('credentials')
if (credentials) {
  // set credentials back
  SecureStore.setItemAsync('credentials', credentials)
}

// -- elsewhere

const creds = await getItem('credentials') // CRASH
if (creds) {
  // update values with creds
    this.props.form.setFieldsValue(JSON.parse(creds))
}
```

**Comment by ide** [comment] 2018-02-21 23:43
OK, thanks for the report. Not sure what the issue is right now though.

**Comment by ShMcK** [comment] 2018-02-21 23:45
Understandable. Me either. 

One other thing to consider:
- the issue occurred when a user updated versions of the app.

Happy to close the issue for now, if no one else is reporting.

**Comment by ShMcK** [comment] 2018-02-22 01:33
No, also SDK 25.

I think it's time to close.

**Comment by kelvinlawson** [comment] 2018-04-09 11:49
This could be due to transferring apps and data from one Android phone to another during upgrade - perhaps the SecureStore data is transferred but was encrypted on the previous phone.

**Comment by w-** [comment] 2018-06-01 16:29
I am also encountering this.
doing internal testing of android app. 
the only thing that was changed was the notification icon value in app.json

suddenly this is a blocking error.

**Comment by 2DKot** [comment] 2018-07-20 11:34
Same error from standalone android app.
Some info I got from Sentry:
```
sdkVersion: 28.0.0
expoVersion: 2.0.11
expoAppVersion: 2.0.11
os: Android 26
```
app.json:
```
{
  "expo": {
    "name": "******",
    "description": "******",
    "slug": "******",
    "privacy": "unlisted",
    "sdkVersion": "28.0.0",
    "platforms": ["ios", "android"],
    "version": "2.0.11",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "ios": {
      "supportsTablet": false,
      "bundleIdentifier": "******",
      "buildNumber": "1.0.6",
      "icon": "./assets/icons/ios_icon.png"
    },
    "android": {
      "package": "******",
      "config": {
        "googleMaps": {
          "apiKey": "******"
        }
      },
      "permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION"
      ],
      "versionCode": 11
    },
    "androidStatusBar": {
      "backgroundColor": "#0091FF"
    },
    "assetBundlePatterns": [
      "assets/images/*"
    ],
    "updates": {
      "checkAutomatically": "ON_ERROR_RECOVERY"
    }
  }
}
```

**Comment by BrodaNoel** [comment] 2018-11-18 01:18
Guys, this is a bit weird.
I can not understand WHEN this issue happens, but still happening, and with no changes in Expo App, SDK or in any place.

I'm developing the App and sometimes this error happens (iOS and Android, with real devices) and the only solution is removing the Expo App and opening it again.
Really weird.

**Comment by BrodaNoel** [comment] 2018-11-18 01:32
@brentvatne @ide Here I could find important information that I believe it's enough to define that this is a bug.

I have this code in my App:
```js
  return Promise.all([
    SecureStore.getItemAsync('user'),
    SecureStore.getItemAsync('spots')
  ]).then((responses) => {
    let user = responses[0];
    let spots = responses[1];

    if (user) {
      // Do something
    }

    if (spots) {
      // Do something
    }

    return { user, spots };
  });
```

As you can see, I get 2 items from `SecureStore.getItemAsync`.
The weird thing is that if I comment the second "get" (the Spots), it works perfectly, meaning:

**This works**
```js
  return Promise.all([
    SecureStore.getItemAsync('user'),
    // SecureStore.getItemAsync('spots')
  ])
```

**This DOT NOT work**
```js
  return Promise.all([
    // SecureStore.getItemAsync('user'),
    SecureStore.getItemAsync('spots')
  ])
```

So, it seems like the "spots" object is broken.
Honestly, by "spots" object is REALLY HUGE. So, it may be something related with the object size.
The weird thing, is that it works perfectly during a couple of days/weeks, and then, sometimes it just get broken.

Here is another really important thing:
I "set" the "spot" data only 1 time in the App (first time it's opened) and then I never change it again.
Last time that I get this error, it was with an Android device, I did this flow:
* Installed Expo in the Android (Moto G3)
* Opened my App
* The App downloaded the Spots and saved in the secure storage properly
* I used the app (even killed Expo 2 or 3 times) with no problems during ~15 min
* I killed Expo and reopened again and the error appeared

**Comment by BrodaNoel** [comment] 2018-12-23 00:56
Let me continue with my story:
I could fix it getting smaller the object I was storing, but, one day, it got bigger, and the issues appeared again.

So, I decided to: Encrypt the data by myself, save it in `AsyncStorage` (react-native), and save the decrypt keys in SecureStore. 🤷‍♂️ 

Good luck guys!

**Comment by mauriciord** [comment] 2019-01-17 11:48
Same issue here, i'll use as a temporary fix the `AsyncStorage` ?

**Comment by Kikkomann** [comment] 2019-02-07 15:51
The same happens for me. Out of random when I open my app, I get a could not decrypt. I use the SecureStore for a user token, and right now I am just storing the token "1" to make sure it is not too big.

**Comment by andrioid** [comment] 2019-02-08 08:14
I just finished a migration of our redux hydration object into secure-storage a few weeks ago. Now random people are complaining about having to log in all the time.

[Error: Could not decrypt the item in SecureStore]

We also have a relatively large object, that we're serialising and storing.

**Comment by MartinMasek** [comment] 2019-04-09 17:02
It happened to me as well. I started an Android emulator and everything worked fine. I closed the emulator and started it again. Now every time I reload JavaScript, I get this error (as my app saves token to SecureStore).

Can I somehow help to debug this? My data is very small (json with 3 small string fields) so it's not a data issue.

**Comment by otaviogaiao** [comment] 2019-05-09 08:14
It happened to me as well, only on Android so far.  All I am saving is the users credentials so I can login using face or fingerprint scan. 
I'm using ExpoKit 32.

**Comment by trevor-atlas** [comment] 2019-05-21 19:34
We are also running into this issue for our android users on SDK 32

**Comment by bhall2001** [comment] 2019-05-23 15:52
Our app has had this problem so far only with pixel 2 and then only very seldom (last Sentry alert on 2/14/2019). Today we received a Sentry alert from an S9 with this issue. Quick search to see if other expo apps have a fix for this brought me here. Just adding in my report (SDK 32).

Looking at our code we are not storing much in secure store (credentials) so it doesn't look like our object would be too big. If anyone has any ideas how to best work around this we'd appreciate it.

**Comment by b4stien** [comment] 2019-05-25 17:46
Same problem here, SDK 32, Android-only. We are not storing big values (max ~ 40 characters-long strings) nor using big keys.

However we are retrieving values "concurently", with a pattern ressembling:

```
  Promise.all([
    SecureStore.getItemAsync(keyOne),
    SecureStore.getItemAsync(keyTwo),
    SecureStore.getItemAsync(keyThree),
    SecureStore.getItemAsync(keyFour),
  ])
```

Is there anyone having this issue retrieving values sequentially? Would that be a "fix"?

**Comment by RodolfoGS** [comment] 2019-07-07 16:48
Same issue after upgrade from expo SDK 32 to 33

**Comment by qalqi** [comment] 2019-07-20 08:56
+1

**Comment by joshg2k** [comment] 2019-10-18 14:49
Commenting just to keep the thread updated w/ latest SDK versions. This is still occurring in SDK 35.

**Comment by wardjk87** [comment] 2019-11-06 16:42
I'm using Secure Store in production app. I'm getting thousands of these errors in sentry. I think something is fundamentally wrong with this feature. Currently using SDK 32 but upgrading to 35 now. It works fine when testing locally and in own production version of app, but many users are having it break. I'm going to need to find alternative

**Comment by madhenry** [comment] 2019-11-12 14:37
+1 hundreds of SecureStore read / write errors on androids SDK 33 & 34 in sentry

**Comment by wardjk87** [comment] 2019-11-12 18:04
Today confirmed that SecureToken is broken on my app after updating to Expo 35 SDK. It had been working for several months on android using older SDK 33. Now the error happens everytime but only on ANDROID. Ios seems to be working.

**Comment by iamnader** [comment] 2019-12-06 02:49
@ShMcK should this be reopened?  lots of people seeing it.

**Comment by jacky-lee** [comment] 2019-12-16 22:37
We're on Expo SDK 35.  An user reported that he switched from one Pixel 2 phone to another one.  He restored everything from the previous backup.  However, he couldn't login to our app via fingerprint since then.  He tried uninstalling and re-installing the app.  Doesn't help.  Can this ticket be reopened pls?

**Comment by ide** [comment] 2019-12-16 22:56
Re-opening this but we don't have any updates (when there is an update, this issue is where it will be posted).

**Comment by shamilovtim** [comment] 2020-01-05 19:01
Started getting this after uninstalling and reinstalling the same app on Android. Do not get it on iOS.

**Comment by shamilovtim** [comment] 2020-01-05 19:08
The following fixed the issue for me on my device:

Go to the Settings Menu
Click on Apps
Find the All tab (if your system doesn't show you all apps by default)
Choose an app that is taking up a lot of space
Click the button Clear Cache. If you're running Android 6.0 Marshmallow or newer on your device then you'll need to click on Storage and then Clear Cache.
To clear the app data instead of the cache, simply select Clear Data instead

It seems like the keystore gets corrupted and SecureStore instead of cleaning it out just fails and does not empty it. 

@ide My proposal: empty out the keystore when this case is hit. It would at least immediately fix the issue.

**Comment by jacky-lee** [comment] 2020-01-14 18:30
Thanks @shamilovtim  I had a user followed the steps above and he's able to login to the app without any issue.  Yay!  My concern is that most users who ran into this issue would not have contacted us.  Thus they would not be able to access our app, even if they uninstall and reinstall the app.  This is a very big issue.

**Comment by shamilovtim** [comment] 2020-01-14 20:56
@ide IMO this is important enough to provide a hotfix since it completely bricks user's apps. Is it feasible to provide a patch version of expo / securestore?

**Comment by ide** [comment] 2020-01-14 22:03
If this is impacting you I’d recommend using another storage mechanism. We are unlikely to do a hotfix for two reasons: the root cause has not been identified in this issue and the module has behaved this way for multiple SDK releases and nothing material has changed that warrants a hotfix.

The next SDK release is slated to ship by March 31. If you would like a fix to ship with that version, the best way to make that happen is to identify the root cause, which may include pointing to parts of the Android source code to explain this behavior. Without a root cause we can’t develop an acceptable fix.

**Comment by shamilovtim** [comment] 2020-01-14 22:09
@ide In cases of app reinstallation or updates the [keystore needs to be cleared out](https://github.com/expo/expo/issues/1459#issuecomment-570938449). This can be as simple as emptying the keystore when this error case is hit and having the user's application submit to the keystore using the same handling logic that they already have in their application. While I'm not aware of the cause I am aware of the solution. This is a unimodule, correct? So if I submit a PR, this can be hotfixed through the framework/podfile/package.json? Or only through full scale SDK update?

**Comment by ide** [comment] 2020-01-15 00:58
Ideally we wouldn't just blow away the entire keystore. What you're describing sounds like a patch to partially cover up symptoms. We need to identify the actual root cause.

**Comment by shamilovtim** [comment] 2020-01-15 02:13
But we’re not talking about blowing away the keystore at random. We’re taking about blowing away the keystore *only when an error handling case is hit and developer’s apps are completely bricked and users cannot use them no matter how many times they uninstall / reinstall.* This dependency is currently in production and is permanently bricking apps until each user manually clears the keystore. I think this deserves to be treated seriously or the package should be pulled so people know not to use it.

**Comment by ide** [comment] 2020-01-15 02:34
The module is still unreliable if it cleared the keystore at times the developer doesn’t have control of. I’d recommend you choose another storage solution if this isn’t working for you, or fundamentally identify why this issue is happening to help fix this issue.

**Comment by shamilovtim** [comment] 2020-01-15 05:52
I'll see what I can do

**Comment by SimenB** [comment] 2020-01-15 11:42
FWIW, this is the code we have to deal with this

```ts
// SecureStorage is not cleared when the app is uninstalled, but AsyncStorage _is_.
// So keep a key in AsyncStorage for tracking this, and if it's not there, clear all keys in SecureStorage
async function checkForFirstLaunch() {
  Sentry.addBreadcrumb({
    category: 'auth',
    message: 'Checking if first launch',
  });
  const { HAS_LAUNCHED_KEY, ...secureKeys } = storageConstants;

  try {
    const hasLaunched = await AsyncStorage.getItem(HAS_LAUNCHED_KEY);

    if (hasLaunched) {
      Sentry.addBreadcrumb({
        category: 'auth',
        message: 'Has launched app previously',
      });
    } else {
      Sentry.addBreadcrumb({
        category: 'auth',
        message: 'Launching the app for the first time, clear all keys',
      });
      console.log('Launching the app for the first time, clear all keys');
      await AsyncStorage.setItem(HAS_LAUNCHED_KEY, 'hello!');

      for (const key of Object.values(secureKeys)) {
        await SecureStore.deleteItemAsync(key);
      }
    }
  } catch (error) {
    Sentry.addBreadcrumb({
      category: 'auth',
      message: 'unable to check for first launch',
    });
    Sentry.captureException(error);
  }
}
```

**Comment by shamilovtim** [comment] 2020-01-19 02:43
@ide 

https://github.com/adorsys/secure-storage-android/issues/32
https://stackoverflow.com/questions/54552349/can-i-generate-keys-in-android-keystore-that-stays-permanently

preserving the keystore between reinstalls is not supported. thus it is actually correct to wipe it out when we can't decrypt it any longer.

**Comment by shamilovtim** [comment] 2020-01-30 21:29
Here is how we resolved.

```javascript
try {
      token = await SecureStore.getItemAsync('token');
    } catch (e) {
      // this only throws if they reinstall on android
      await SecureStore.deleteItemAsync('token');

        // display an alert: "Cached data from a previous installation was detected and
        // needed to be removed prior to allowing login. Please login again."
        }
      });
    }
```

Rather than having users of SecureStore do this and force the error to throw first it would be good to handle this inside of SecureStore as mentioned farther up the issue.

**Comment by expjess** [comment] 2020-03-04 22:07
Closing the loop on this issue: 

- The expected behaviors on iOS and Android are presently different, as [documented](https://docs.expo.io/versions/latest/sdk/securestore/).
- We would welcome either a [feature request](https://expo.canny.io/feature-requests) or (even better!) a PR to provide this same functionality on Android
- An available workaround would be to store the data off the device, and identify the device by `androidId`, which is unique to each combination of app-signing key, user, and device.

**Closed by expjess** 2020-03-04 22:07 UTC
Labels: status: needs more info

**Comment by Bardiamist** [comment] 2021-09-08 08:29
Feature request created [here](https://expo.canny.io/feature-requests/p/securestore-fix-could-not-decrypt-the-item-in-securestore). Lets vote for this fix.

**Comment by louisbyrne89** [comment] 2022-06-08 10:09
I had this issue immediately after upgrading to expo SDK 45 from SDK 44, testing in an eas development build.
https://github.com/expo/expo/issues/1459#issuecomment-580468780 resolved the issue.

**Comment by BatDroid** [comment] 2022-07-11 19:51
Have the same issue and nothing worked so far

**Comment by hugoh59** [comment] 2022-07-20 14:20
I have the same issue on Android after deleting and reinstallng the Expo app.

**Comment by shamilovtim** [comment] 2022-08-18 15:47
To be clear, I do not recommend my workaround that everyone is using. I do suggest using a different library whether its MMKV or some of the other secure store libraries.

**Comment by stefan-schweiger** [comment] 2022-08-19 07:20
@shamilovtim my biggest issue is that this workaround sadly doesn't even work consistently. Sometimes I have to clear the cache 2-3 times before I get the app working again, and just deleting the key didn't help me at all.

My biggest problem with other libraries is that none of those offers those two things in combination: a key-value based storage and optional biometrics. But expo-secure-storage is nowhere near production ready to be honest :/

**Comment by tlmdouellet** [comment] 2023-06-23 19:59
Got the error after some manual apk instalations, this comment fixed it.
https://github.com/expo/expo/issues/1459#issuecomment-580468780

**Comment by statico** [comment] 2024-06-07 21:21
June 2024 and I'm seeing errors like this:

> Error: Call to function 'ExpoSecureStore.getValueWithKeyAsync' has been rejected. → Caused by: Could not decrypt the value for key 'xxxxxxxx' under keychain 'key_v1'. Caused by: Could not decrypt the value with provided keychain

I guess it's time to try MMKV or something else.

**Comment by abhiskg** [comment] 2024-06-08 07:20
@statico Facing the same issue.

**Comment by stefan-schweiger** [comment] 2024-06-11 15:48
Also again got some of those cases after nothing for a long time. There is also this issue https://github.com/expo/expo/issues/23426 which seems to be related and not closed already
