### ISSUE TITLE
[docs] Theme Selector isn't looking correct

### ISSUE THREAD

**Issue by simplysabir** [expo/expo#24571] opened 2023-09-22 11:39 UTC
### Summary

The theme selector on the docs website isn't looking correct. it is overflowed and background color is also messed up. also additional arrow is also showing up side by side

![image](https://github.com/expo/expo/assets/76485932/fa4f272b-93c4-47cb-9920-fdd1d118beca)

![image](https://github.com/expo/expo/assets/76485932/1642da6a-0dda-4ce9-bde4-9ebe5318e5a1)

### Link to the related docs page

https://docs.expo.dev/

### Anything else?

Can i work on this issue?

**Comment by brentvatne** [comment] 2023-09-22 17:11
which browser and operating system are you using?

**Comment by simplysabir** [comment] 2023-09-22 17:55
> which browser and operating system are you using?

I'm on Windows and Using Chrome

**Comment by amandeepmittal** [comment] 2023-10-02 08:27
@simplysabir, on a Windows machine using chrome, I am unable to reproduce the issue.

![Screenshot 2023-10-02 135156](https://github.com/expo/expo/assets/10234615/831e45e6-7941-4ac5-86b2-a199838648b1)

![Screenshot 2023-10-02 135219](https://github.com/expo/expo/assets/10234615/a2514ff9-e167-41d5-a8db-1046603c0c93)

The only thing that comes to my mind is to make sure Chrome is up to date.

**Comment by amandeepmittal** [comment] 2023-11-13 10:37
Going to close it since we've not been able to reproduce it. Feel free to let me know if you are still facing it.

**Closed by amandeepmittal** 2023-11-13 10:37 UTC
Labels: needs more info, docs
