### ISSUE TITLE
[expo-local-authentication] LocalAuthentication.authenticateAsync

### ISSUE THREAD

**Issue by JeffreyLeeDave** [expo/expo#9846] opened 2020-08-20 00:01 UTC
### Summary of Issue
So I am using the package on Android and I have the passcode fallback enabled. So whether I click on the button that uses the fallback (password, pattern or PIN) or whether the fallback triggers because of a biometrics failure, I get this response before navigating to the screen to enter my fallback:

```
{
	error: "user_cancel",
	message: "Authentication canceled",
	success: false,
}
```

Upon entering the fallback, I get brought back to the app, but I don't get a response letting me know if it was successful or not.

### Environment
Non-expo react-native project
Android version: API 29
Device: Pixel 3XL

### Steps to Reproduce
It's just calling `const response = await LocalAuthentication.authenticateAsync()`

### Expected Behavior vs Actual Behavior
I expect that once I enter the fallback, in my case it was a PIN, I would get a response letting me know that it was entered correctly.

**Comment by byCedric** [comment] 2020-08-20 14:55
Hi @JeffreyLeeDave, thanks for writing in. Unfortunately, I can't reproduce this on my end. I've successfully tested this on an OnePlus 6 (Android 10) device and a Pixel 3 (Android 10) emulator. Could you provide [a repro](https://stackoverflow.com/help/minimal-reproducible-example) for this?

**Comment by JeffreyLeeDave** [comment] 2020-08-20 17:15
Is this what you mean? I am really just calling the one line `LocalAuthentication.authenticateAsync()`. Not doing much complicated with it. Technically I am using this in the `useEffect`. I am really just testing out this package right now.

```
  useEffect(() => {
    async function testingLocalAuthentication() {
      const isEnrolled = await LocalAuthentication.isEnrolledAsync();
      if (isEnrolled) {
        const response = await LocalAuthentication.authenticateAsync();
        console.log('------------------', response);
      }
    }
    testingLocalAuthentication();
  }, []);
```

**Comment by JeffreyLeeDave** [comment] 2020-08-20 19:24
I should also add that I am working on a non-expo react-native app and unimodules was installed correctly

**Comment by JeffreyLeeDave** [comment] 2020-08-24 21:03
I want to give an update...This ended up working on my actual device Pixel 3XL. It did not work for me in the emulator on android studio though

**Comment by florinleu** [comment] 2021-06-15 12:37
I experience the same issue on a Nexus device.
I placed this code in App.js:
try {
    const biometricAuth = await LocalAuthentication.authenticateAsync({
        promptMessage: 'Login with Biometrics',
        cancelLabel: 'Cancel',
        fallbackLabel: 'Fallback'
    })
    console.log('biometricAuth', biometricAuth)
} catch (error) {
    console.log('error', error)
}
There are 3 use cases:
- the device has biometrics enabled (face/touch id) and I'm using them to authenticate => the code runs fine and outputs "biometricAuth {"success": true}"
- the device has biometrics enabled (face/touch id) but I choose to use the passcode/pattern fallback => the code stucks at "await LocalAuthentication.authenticateAsync" and doesn't log anything
- the device has only passcode/pattern enabled, without biometrics and I'm trying to authenticate => like in the example above the code stucks at "await LocalAuthentication.authenticateAsync" and doesn't log anything
Digging a bit deeper in the LocalAuthenticationModule.java it seems that the callback methods are not called at all on the 2 stuck cases described above.

**Comment by pjcaro** [comment] 2021-07-01 19:58
I get the same issue on a Samsung device, Is there any solution for this?

**Comment by jon-nona** [comment] 2021-07-06 08:17
I believe this is still an issue on Android API < 30 . It was referenced by #12353 and then supposedly closed by [#13023](https://github.com/expo/expo/pull/13023), but I am experiencing what you are describing when I try to use a PIN below API < 30. API 30 + works fine @lukmccall

**Comment by thijs-qv** [comment] 2021-09-21 08:51
This looks related to [this Android issue](https://issuetracker.google.com/issues/173198408). Upgrading to `androidx.biometric:biometric:1.2.0-alpha03` doesn't seem to help.

**Comment by deepanshu01399** [comment] 2021-12-16 15:00
{"error":"app_cancel","success":false} i am getting that error when ever i am trying to do login with Passcode/Password without using Biometric Anyone found the solution for the same

**Comment by nachitorf** [comment] 2022-01-23 19:11
I'm having the same issue is there any workaround?

**Comment by jurgenj136** [comment] 2022-01-28 14:56
Seems to be an issue in androidx.biometric
It got fixed in version 1.2.0-alpha04

You can fix it for now by editing the version in "expo-local-authentication/android/src/build.gradle"
I'm using [patch-package](https://github.com/ds300/patch-package) to do this

**Comment by zbagdzevicius** [comment] 2022-03-28 07:59
I reproduce the same, seems like I have created duplicate ticket https://github.com/expo/expo/issues/16705

**Closed** 2022-04-06 07:11 UTC
Labels: Android, LocalAuthentication, Requesting changes to issue

**Comment by alainib** [comment] 2024-07-02 12:08
i have same error in 2024 i guess

```
const result = await LocalAuthentication.authenticateAsync({
      disableDeviceFallback: true,
      requireConfirmation: false,
    });
 
    console.log(result); > 
{"error": "not_available", "success": false, "warning": null}
```

if user click on cancel it's dead

await LocalAuthentication.isEnrolledAsync();
 await LocalAuthentication.hasHardwareAsync();
 will always return false even if they return true before user click "cancel" on `authenticateAsync`. 
 
 tryed on reel iphone 13
 
 how to get out of this ? thanks
