### ISSUE TITLE
Linking event listener not working

### ISSUE THREAD

**Issue by modsoussi** [expo/expo#8279] opened 2020-05-13 01:31 UTC
### Environment

```
 Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.10 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.3
```

- Target: iOS, Standalone

### Steps to Reproduce
I have created a repo: https://github.com/modsoussi/SampleExpo.

### Expected Behavior and Actual Behavior
Once the app is open, click `Press Me` which will open a `WebBrowser`. There you'll see a Stripe Connect onboarding flow in development mode, which you can skip by tapping `Skip this form` on the top. Once you do that, the expected behavior is dismissal of the `WebBrowser` instance and data logging, assuming the `url` listener is working properly, which doesn't seem to be the case.

The app is set up to use Universal Links, which is why I don't have a `scheme` set in `app.json`. The redirect to the app is happening properly because when tested on Safari, you're redirected to the app with the `WebBrowser` instance still up, meaning the redirect itself is not handled. I also know the `redirectHandler` is being registered correctly by logging `Linking.listeners()`.

**Comment by EvanBacon** [comment] 2020-05-14 02:45
If the web browser is not being closed then it means that the URL is not directing back to the app. This may be by design for universal links + the standard iOS web browser. You should try using `SFAuthenticationSession` which is accessible via `WebBrowser.openAuthSessionAsync()`.

Further, `WebBrowser. openBrowserAsync` is not a secure method for performing auth on iOS. Perhaps you could try using the new `expo-auth-session` API instead:

```
const [request, result, promptAsync] = AuthSession.useAuthRequest({
  clientId: '',
  scopes: ['read_write']
}, {
  authorizationEndpoint: 'https://connect.stripe.com/oauth/authorize'
});
```

**Comment by modsoussi** [comment] 2020-05-14 18:15
`WebBrowser.openAuthSessionAsync` has the same redirect behavior as described above, where the browser is not dismissed. I also tried the new `expo-auth-session` API (https://github.com/modsoussi/SampleExpo/blob/master/App.js), and that gives me the following warning:
```
Possible Unhandled Promise Rejection (id: 5):
TypeError: undefined is not an object (evaluating '_ExpoRandom.default.getRandomBytesAsync')
getRandomBytesAsync$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:113003:37
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29893:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30069:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29893:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29969:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29999:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3877:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4041:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3900:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29998:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30003:157
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30020:69
getRandomBytesAsync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:112996:38
getRandomValuesAsync$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:112708:73
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29893:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30069:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29893:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29969:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29999:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3877:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4041:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3900:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29998:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30003:157
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30020:69
getRandomValuesAsync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:112701:38
generateRandomAsync$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:112750:67
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29893:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30069:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29893:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29969:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29999:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3877:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4041:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3900:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29998:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30003:157
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30020:69
generateRandomAsync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:112744:38
buildCodeAsync$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:112798:66
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29893:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30069:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29893:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29969:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29999:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3877:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4041:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3900:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29998:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30003:157
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30020:69
buildCodeAsync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:112792:38
ensureCodeIsSetupAsync$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:112527:70
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29893:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30069:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29893:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29969:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29999:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3877:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4041:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3900:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29998:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30003:157
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30020:69
ensureCodeIsSetupAsync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:112514:42
getAuthRequestConfigAsync$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:112232:78
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29893:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30069:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29893:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29969:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29999:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3877:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4041:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3900:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29998:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30003:157
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30020:69
getAuthRequestConfigAsync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:112222:42
makeAuthUrlAsync$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:112424:81
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29893:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30069:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29893:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29969:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29999:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3877:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4041:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3900:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29998:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30003:157
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30020:69
makeAuthUrlAsync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:112419:42
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:114296:34
commitHookEffectList@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:24708:38
commitPassiveHookEffects@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:24741:37
invokeGuardedCallbackImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:13258:21
invokeGuardedCallback@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:13354:42
flushPassiveEffectsImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:27171:34
flushPassiveEffectsImpl@[native code]
unstable_runWithPriority@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:43316:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:26791:32
```
and the `request` remains `null`?

**Comment by brentvatne** [comment] 2020-05-14 18:26
run `pod install` or rebuild your native project after installing `expo-auth-session` @modsoussi. it pulls in dependencies like expo-crypto that you may not have

**Comment by modsoussi** [comment] 2020-05-14 18:43
Oh, great. No longer giving a `TypeError, ` redirect behavior is still the same as described above though. `SFAuthenticationSession` not dismissed, and nothing is being logged. Thanks @brentvatne

**Comment by modsoussi** [comment] 2020-07-13 11:55
UPDATE: Realized I hadn't included the `application continueUserActivity` `App Delegate` method. Once that was added in, I had to add code to handle redirects because `AuthSession` by itself wasn't dismissing the `WebBrowser` instance for example, and with that everything worked on the XCode Simulator. Now I'm facing another issue where redirects are happening properly on the simulator, but on an actual device. I have **Universal Links** set up properly, but am not using schemes at all. Could that maybe have something to do with unsuccessful redirects on an actual device? Code is now as follows:

```javascript
const [request, resp, promptAsync] = AuthSession.useAuthRequest(
    {
      clientId,
      responseType: 'code',
      scopes: ['read_write'],
      redirectUri,
    }, {
      authorizationEndpoint: 'auth_endpoint',
    },
  );

  const addLinkingListener = () => {
    Linking.addEventListener('url', handleRedirect);
  };

  const removeLinkingListener = () => {
    Linking.removeEventListener('url', handleRedirect);
  };

  const handleRedirect = async ({ url }) => {
    if (Constants.platform.ios) {
      WebBrowser.dismissAuthSession();
    } else {
      removeLinkingListener();
    }

    console.log(url);
  };

  const _openAuthSessionAsync = async () => {
    try {
      addLinkingListener();
      const res = await promptAsync();

      if (res) {
        removeLinkingListener();
      }
    } catch (err) {
      console.error(err);
    }
  };
```

**Comment by EvanBacon** [comment] 2020-08-11 02:58
Closing as this seems like more of a trouble shooting issue.

**Closed by EvanBacon** 2020-08-11 02:58 UTC
Labels: Linking, WebBrowser, bug
