### ISSUE TITLE
Build error: Error while gathering & validating credentials

### ISSUE THREAD

**Issue by casperstr** [expo/expo#1882] opened 2018-06-17 09:49 UTC
Im getting the following error while trying to build an ios:ipa for enterprise even tough I have an admin account.

![image](https://user-images.githubusercontent.com/14292004/41506683-cb167a16-7222-11e8-8fdf-e8a223f0ce10.png)

If i try to provide the certificates myself I instead get a build error: 
![image](https://user-images.githubusercontent.com/14292004/41506761-4455fd6a-7224-11e8-9308-a3ff3e73b047.png)

![image](https://user-images.githubusercontent.com/14292004/41506741-d8846ed2-7223-11e8-8815-be42d87ac92a.png)

Link to build: 
https://expo.io/builds/98d65859-cb0b-4229-bf34-4e2f8ee6f549
  
### Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 6.0.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^27.1.0 => 27.1.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

**Comment by msevestre** [comment] 2018-06-17 12:33
Do you mean adhoc distribution? I read somewhere in the docs that this is not supported...

**Comment by casperstr** [comment] 2018-06-18 07:13
No I am trying to distribute via Enterprise InHouse.

**Comment by nicknovitski** [comment] 2018-06-18 23:17
The `You are not allowed` error comes directly from Apple's api.  I'm not sure exactly which "operation" it's refusing to do.  Could you embed the full output from `EXPO_DEBUG=true exp build:ios`?

The  `unhandled destination metrics` warnings, they are just noise and I believe currently show up in every build, successful or otherwise.

 Segmentation fault 11 is bad.  Could you please link to the page of that build?

(@fson I assume your home directory is in these screenshots because of some sourcemap error?)

**Comment by dhruska** [comment] 2018-06-20 23:15
I've been having similar issues. Documenting what I've tried on the [Expo forums](https://forums.expo.io/t/trouble-building-enterprise-apps-with-expo-managing-the-certificate/10372/5).

**Comment by tcdavis** [comment] 2018-06-21 17:17
Hi all, thanks for the reports!  I believe this is a duplicate of https://github.com/expo/expo/issues/1893, which we are currently investigating

**Closed by tcdavis** 2018-06-21 17:17 UTC
