### ISSUE TITLE
Error in ExpoKit project related to CocoaLumberjack version conflict, after adding background geolocation library. ExpoKit is using old version of CocoaLumberjack

### ISSUE THREAD

**Issue by Luckygirlllll** [expo/expo#5574] opened 2019-09-09 08:57 UTC
### Environment

  Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.2 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.2.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.6

### Steps to Reproduce

I want to use react-native-background-geolocation library in my ExpoKit project version 34.0.0. however, I’m getting an error related to CocoaLumberjack version conflict after adding this library.

Here is my error, it seems that ExpoKit is using old version of CocoaLumberjack. What can I do about it? Can I somehow upgrade version of CocoaLumberjack? will it affect my project?

here is an error:

CocoaPods could not find compatible versions for pod “CocoaLumberjack”:
In snapshot (Podfile.lock):
CocoaLumberjack (= 3.2.1, ~> 3.2.1)

In Podfile:
CocoaLumberjack (= 3.5.3)

ExpoKit/Core (from `http://github.com/expo/expo.git`, tag `ios/2.12.1`) was resolved to 34.0.0, which depends on
  CocoaLumberjack (~> 3.2.1)

RNBackgroundGeolocation (from `../node_modules/react-native-background-geolocation`) was resolved to 3.2.0, which depends on
  CocoaLumberjack (~> 3.5.1)
It seems like you’ve changed the constraints of dependency CocoaLumberjack inside your development pod RNBackgroundGeolocation.
You should run pod update CocoaLumberjack to apply changes you’ve made.

### Expected Behavior

App works

### Actual Behavior

I'm getting an error

**Comment by cruzach** [comment] 2019-09-09 15:37
Duplicate of [4481](https://github.com/expo/expo/issues/4481)

Library has been updated in [this PR](https://github.com/expo/expo/pull/5500)

**Closed by cruzach** 2019-09-09 15:37 UTC
Labels: bug

**Comment by Luckygirlllll** [comment] 2019-09-09 15:52
@cruzach and how can I use this PR in my ExpoKit project now? Should I update version of ExpoKit?
