### ISSUE TITLE
Expo 31 logs to terminal when chrome remote debugger is enabled

### ISSUE THREAD

**Issue by slorber** [expo/expo#2623] opened 2018-11-06 08:23 UTC
Hi,

Before SDK31, when using console.log in my app, the logs would only display in terminal when the chrome remote debugger was disabled.

After SDK31, when using console.log, the logs would display in both the terminal and chrome debugger.

I'd like the ability to revert back to old behavior, and being able to disable logs in terminal (at least when chrome debugger is enabled)

------------------

Having console statements in your code may be a part of a developer's workflow. It is part of my workflow to use logs in dev, and I strip debug logs with babel from production build for perf reasons.

The problem is that when logging to the terminal, I find this annoying for many reasons:

- Logging large JSON objects in string format is not performant, and makes the output very verbose, particularly when you use a lot of logs (for example, using Redux-logger or anything similar...). It is not the case in chrome remote debugger because json objects are folded.
- Logs are melted with packager errors, and errors may be less noticeable. If we encounter any, as the logs are verbose, we have to scroll up a lot to see the packager errors...

For these reasons I always use the remote debugger logs and never the terminal ones. And I'd like the terminal ones to not output any log, because it makes me less productive and makes my computer slow down.

**Comment by rxhivzero** [comment] 2018-11-06 08:38
+1

**Comment by nelsonchen5** [comment] 2018-11-19 18:03
also have this issue

**Comment by slorber** [comment] 2018-11-23 18:05
Hey, don't know if this is totally related but I also get sometimes my chrome debugger reporting "out of memory errors", and it seems to happen when I log a cyclic object (yet it appears correctly and is unfoldable in chrome debugger)

![image](https://user-images.githubusercontent.com/749374/48956253-58bdf180-ef52-11e8-836b-f57485dfac98.png)


Example code that produce this cyclic issue:

```js
const AppNavigationContainer = createAppContainer(MainStackNavigator);

// Ability to access main navigation methods imperatively
const MainNavigationRef = React.createRef();

const MainNavigation = () => <AppNavigationContainer ref={MainNavigationRef} />;

export default MainNavigation;

export const getMainNavigation = () => {
  if (MainNavigationRef.current) {
    // ########## This is the line that produces OOM
    console.debug('MainNavigationRef.current', MainNavigationRef.current);
    return MainNavigationRef.current;
  } else {
    throw new Error(
      'MainNavigationRef should be mounted before you can call imperative navigation methods',
    );
  }
};
```

@sjchmiela @tsapeta @ide you seem to have worked on log files recently, could this be related and fixed by https://github.com/expo/expo/pull/2598 ? 

I think this is related to my main issue because if the logs were not printed to the console, there would be no need to serialize them to show objects in chrome debugger (not sure?). Currently the only workaround I have is to remove all annoying logs in my code. Redux logger and things like that are becoming unusable because everything is in terminal console.

**Comment by sjchmiela** [comment] 2018-11-23 19:50
There seems to be a manual way to solve this problem – one of `expo` exports is a `Logs` module, on which you could call `disableExpoCliLogging` function. I’m writing this from a mobile phone, so I can’t test it, but it may do what its name suggests. 😅 I’m not saying calling this function manually is what we consider should be the way to set up such config, I’m just suggesting a workaround. 😊

**Comment by slorber** [comment] 2018-11-23 20:33
thanks I'm fine with a workaround I'll try that on monday ;)

**Comment by slorber** [comment] 2018-11-26 11:54
Hey thanks @sjchmiela it is working

One subtility is it seems calling `Logs.disableExpoCliLogging()` will not be totally synchronous/immediate. I still get some logs that are related to by js files being loaded/imported, and Metro cyclic dependency warnings too.

That still solves my pain, just reporting this fact :) Thanks

What is this Logs module? Is it something experimental that will appear in doc soon?

**Comment by msevestre** [comment] 2018-11-26 12:56
@slorber how did you get it to work?
I have copied the code snippet, verified that it is being called, but the logs are still being dumped in the terminal window where expo was started. 
Where did you copy that code?

Thanks

**Comment by slorber** [comment] 2018-11-26 17:20
@msevestre I actually had troubles again after re-enabling redux-logger the redux-logger logs were indeed printed to the terminal even when using the code of @sjchmiela 

I figured out this was because my Redux store and my logger middleware are created on app import, and I guess there is some console variable that gets captured in a closure or something, which means the expo logs setting has no effect on it.

A solution I found was to require the app entry point lazily, to ensure that we disable the logging properly before loading any additional JS.

Here's my App.js entry file:

```jsx
import React from 'react';
import { Logs } from 'expo';

// https://github.com/expo/expo/issues/2623#issuecomment-441364587
const isRemoteDebuggingEnabled = typeof atob !== 'undefined';
if (isRemoteDebuggingEnabled) {
  Logs.disableExpoCliLogging();
} else {
  Logs.enableExpoCliLogging();
}

console.disableYellowBox = true;

export default () => {
  const AppStarter = require('AppStarter').default;
  return <AppStarter />;
};
```

**Comment by msevestre** [comment] 2018-11-26 17:37
@slorber This actually works like that!!! Wicked! My issues were also with redux-logger
Well done

**Comment by msevestre** [comment] 2018-11-27 02:33
@slorber A quick warning. If you  publish using the proposed hack, you will get the following error
`'The Expo project manifest must specify `logUrl`

So this code should only be run in dev environment

**Comment by sjchmiela** [comment] 2018-11-27 07:46
Ooh, didn't think about production mode! I wonder if a simple `if (__DEV__) { … }` would solve this problem…

**Comment by maharjanaman** [comment] 2018-12-12 07:31
@sjchmiela couldn't access `Logs` from `expo`. Did something change?
```import { Logs } from 'expo';```

**Comment by jamesnyika** [comment] 2019-01-07 19:57
@slorber : I am experiencing this same problem as you but I am using Clojurescript and I do not use an App.js file as you do. Can I ask you to detail exactly what you mean by "A solution I found was to require the app entry point lazily.." 

 Did you mean you have a file in your project root directory called App.js and those are its only contents ? or where are you requiring it into ? Just a little more clarity on what files are where, what was modified would help me translate it into my clojurescript environment. 


@sjchmiela  - anything you can do to prevent this duality of logging would help. It basically kills my and probably others ability to work with expo especially if they have large object trees as part of their applications. I have a Datascript database in memory that worked perfectly fine in the past with either remote or console logging but now cannot continue in this mode even with console logging only. Perhaps expose it as a switch on the Expo Cli UI and/or an option that can be passed to 'expo start' ? 

 thanks all..

**Comment by pzupan** [comment] 2019-01-08 01:43
I tried @slorber 's code in expo but I'm still getting the redux logs displayed in the terminal:

`import { KeepAwake, registerRootComponent, Logs } from 'expo';
import App from './App';

if (__DEV__) {
  const isRemoteDebuggingEnabled = typeof atob !== 'undefined';
  if (isRemoteDebuggingEnabled) {
    Logs.disableExpoCliLogging();
  } else {
    Logs.enableExpoCliLogging();
  }
  KeepAwake.activate();
}
registerRootComponent(App);`

**Comment by jamesnyika** [comment] 2019-01-08 01:53
@pzupan .. is this file the content of your App.js file ? if anyone can help clarify WHERE this code needs to exist to actually stop logging it would help tremendously ..

**Comment by slorber** [comment] 2019-01-08 23:32
You should put this on your app entry point.

You must disable the logs before importing your JS files, this is why my example is using a require inside a method. If you use an es6 import the JS code you import will run before the disabling of the Expo logs and it won't work in some cases like Redux logger

**Comment by pzupan** [comment] 2019-01-08 23:54
This worked for me...
```
import React from 'react';
import { KeepAwake, registerRootComponent, Logs } from 'expo';
//import App from './App';

if (__DEV__) {
  //https://github.com/expo/expo/issues/2623
  const isRemoteDebuggingEnabled = typeof atob !== 'undefined';
  if (isRemoteDebuggingEnabled) {
    Logs.disableExpoCliLogging();
  } else {
    Logs.enableExpoCliLogging();
  }
}
console.disableYellowBox = true;

const AppEntry = () => {
  const App = require('./App').default;
  KeepAwake.activate();

  return <App />;
};
registerRootComponent(AppEntry);
```

**Comment by jamesnyika** [comment] 2019-01-09 12:33
Thank you @slorber and @pzupan. 
 I will locate the appropriate point and insert there...

**Comment by jamesnyika** [comment] 2019-01-12 15:12
## For clojurescript users: 

In the event that you are seeing out of memory issues in your app due to an attempted logging of large objects in your browser dev tools it is part of this issue.

If you need to solve this for your expo 31 or later releases please use the following fix. 

  Modify figwheel.js 

 at the very top add 

```` 
import {Logs } from 'expo'; 

```` 

and then add this after all the variable declarations 

````
//disable cli logging by expo
console.log("Disabling expo cli logging ...");
Logs.disableExpoCliLogging();

````

**Comment by msevestre** [comment] 2019-01-13 21:42
@alexborton This is not enough. You have to do exactly what @slorber suggested, especially with the hack using required. Otherwise it won't work

**Comment by pzupan** [comment] 2019-01-13 22:05
I found some issues with react-native-formik in Expo, specifically withPickerValues not generating a modal on IOS.  Here's my latest code which doesn't fix the formik issues in dev, but works in production.
AppEntry.js
```
import React from 'react';
import { KeepAwake, registerRootComponent, Logs } from 'expo';
if (__DEV__) {
  const isRemoteDebuggingEnabled = typeof atob !== 'undefined';
  if (isRemoteDebuggingEnabled) {
    Logs.disableExpoCliLogging();
  } else {
    Logs.enableExpoCliLogging();
  }
  KeepAwake.activate();
  const AppEntry = () => {
    const App = require('./App').default;
    return <App />;
  };
  console.disableYellowBox = true;
  registerRootComponent(AppEntry);
} else {
  const App = require('./App').default;
  registerRootComponent(App);
};

```

**Comment by Sotatek-NhuanHoang** [comment] 2019-04-14 09:21
Hey guy, here are code of Logs.js
```
import RemoteConsole from './RemoteConsole';
let _originalConsole;
function enableExpoCliLogging() {
    if (_originalConsole) {
        return;
    }
    _originalConsole = global.console;
    global.console = RemoteConsole.createRemoteConsole(global.console);
}
function disableExpoCliLogging() {
    if (!_originalConsole) {
        return;
    }
    global.console = _originalConsole;
    _originalConsole = null;
}
export default {
    enableExpoCliLogging,
    disableExpoCliLogging,
};
//# sourceMappingURL=Logs.js.map
```

So you need call 'Logs.enableExpoCliLogging();' before 'Logs.disableExpoCliLogging();' to disable cli log
```
Logs.enableExpoCliLogging();
Logs.disableExpoCliLogging();
```

Or goto node_modules/expo/build/logs/Logs.js and comment this line
```
// global.console = RemoteConsole.createRemoteConsole(global.console);
```

**Comment by alexborton** [comment] 2019-06-13 11:22
It looks like this issue still persists in Expo v33.0.4

Still using the workaround suggested above for now...

**Comment by jamesnyika** [comment] 2019-07-05 14:22
## For Clojurescript Users

I am having success doing the following in 
```` 

;; This is my equivalent of app.js or my main.js in javascript
(ns core.app
  (:require ["expo" :as ex]
          ;;... i have a bunch of other imports  here. 
          ;;   but this is one above is the important one
))

   ;; before the registration of the application I call 
   (.disableExpoCliLogging ex/Logs)

   ;;... then at some point the app is mounted
  

````
### Important Environmental things
* Being on Clojurescript, I have to translate the appropriate javascript to the equivalent CLJS calls. So they definately work in a JS environment. 
* I am on Expo 33 and I am not seeing duplicative logging in the console and in the expo console. 
* I have been using this since Expo 32 - at least that same function call. 
* for javascript I suspect the call is ```` logs.disableExpoCliLogging(); ```` where logs is a reference to Expo's Logs object. 

### Package.json
````
{
  "scripts": {
    "watch-cljs": "shadow-cljs watch app",
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "release": "shadow-cljs release app"
  },
  "dependencies": {
    "@babel/core": "^7.4.0",
    "@babel/runtime": "^7.4.2",
    "expo": "^33.0.0",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-calendars": "^1.195.0",
    "react-native-elements": "^1.1.0",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-modal": "^11.0.2",
    "react-native-modal-datetime-picker": "^7.4.2",
    "react-native-modal-selector": "^1.0.3",
    "react-native-parallax-scroll-view": "^0.21.3",
    "react-native-tab-view": "^2.3.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.11.0",
    "sentry-expo": "^1.13.0",
    "victory-native": "^32.0.2"
  },
  "devDependencies": {
    "metro-react-native-babel-preset": "^0.53.1",
    "patch-package": "^6.1.0",
    "shadow-cljs": "^2.8.8"
  },
  "private": true
}
```` 

* Expo CLI Version 2.21.2
* Node v11.4.0
* Yarn v1.17.0

**Comment by sjchmiela** [comment] 2019-11-04 11:10
This should have been fixed by https://github.com/expo/expo/pull/3700. 🙂

**Closed by sjchmiela** 2019-11-04 11:10 UTC

**Comment by slorber** [comment] 2019-11-21 14:04
@sjchmiela just upgraded an app from SDK 28 to SDK 35 and for me it's not fixed in SDK35 because just had the regression, and by default, logs are printed to the console even if remote debugging is turned on

The workaround is still useful

**Comment by alexborton** [comment] 2020-03-09 10:35
I am still not able to remove the workaround in `v36.0.0`

Maybe i am confused by the expected behaviour as this issue was closed a while ago?

I would NOT expect to see all console logging through the terminal when i have `Remote Debugging` enabled.

The workaround does still work.
