### ISSUE TITLE
Audio replays on app reopen iOS

### ISSUE THREAD

**Issue by raphaelrk** [expo/expo#1329] opened 2018-01-25 11:32 UTC
Hi all, swooping in with a possible bug report.

Our app has a button that plays a sound when pressed. If we press this button X times, press the home button, then open the app again, X instances of the sound play simultaneously. We fixed the issue by explicitly stopping playback when `hasFinished` on the playback status is `true`.

Code below:

Import the sound at the top of the file
```
const sound = require('../../../assets/sound/mySound.m4a');
```

Play the sound when button is pressed
```javascript
onPress={() => this.playSound()}
```

Function that plays the sound
```javascript
  playSound = async () => {
    try {
      const soundObject = new Audio.Sound();

      // explicitly stops playback when audio done playing
      // otherwise audio will play again when app left and reopened on iOS
      let _onPlaybackStatusUpdate = status => {
        if (status.didJustFinish) {
          soundObject.stopAsync()
        }
      };

      soundObject.setOnPlaybackStatusUpdate(_onPlaybackStatusUpdate);
      await soundObject.loadAsync(sound);
      await soundObject.playAsync();
    } catch (error) {
        console.log("Playback error: ", error)
    }
  }
```

**Comment by sjchmiela** [comment] 2018-01-26 13:52
Hi there!

I could not replicate the issue you described, I've used https://snack.expo.io/rk4NhoOHM.

What I did:

1. Open the app.
2. Click the button several times.
3. Press the home button.
4. The sounds don't play.
5. I come back to the app.
6. The sounds play.

In this scenario everything works as it should. Before closing we issue a number of play requests, which are not handled while the app is in the background, so when we come back, the sounds play. Every `playSound` call creates a new sound (`new Audio.Sound()`), so there are multiple sounds playing simultaneously.

I also tried exiting the app mid-play (the sounds continued where they paused) and after play (the sounds did not replay on their own).

What is the behavior expected by you, @raphaelrk?

**Comment by steve-prod** [comment] 2018-02-13 19:48
@raphaelrk I observed similar behavior in an app I'm working on.  Upon pressing a button a sound was supposed to play.   The sound would not actually play until the app was closed and re-opened.  

Unlike your situation, my app was creating a sound from a file hosted on a remote server.  The root cause of my problem was that the server hosting the audio file was configured incorrectly and the app thought the sound file was longer than it actually was.  So the app kept try to finish loading the sound file until the app closed.  Then, when the app reopened, the app just played that data it had already loaded.

You may want to check your sound file (mySound.m4a) and make sure it's not corrupted somehow.  Maybe there's something wrong with its metadata? Have you tried using other sound files?  Have you tried using other _types_ of sound files?  Which platform (Android/iOS) was the behavior observed on?

**Comment by sjchmiela** [comment] 2018-02-20 20:31
I'll close this for now, feel free to reopen this issue if it happens again! 🙂

**Closed by sjchmiela** 2018-02-20 20:31 UTC
Labels: project: media, project: sdk, ready, status: needs more info
