### ISSUE TITLE
Reanimated + RNGH: Logging Animated Values causes runaway memory usage, app freeze/crash

### ISSUE THREAD

**Issue by computerjazz** [expo/expo#2988] opened 2018-12-14 18:29 UTC
### Environment

  Expo CLI 2.6.13 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
      Yarn: 1.10.1 - ~/.nvm/versions/node/v10.5.0/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v10.5.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.8 => 3.0.8 
    npmGlobalPackages:
      expo-cli: 2.6.13

iOS sim

### Steps to Reproduce

1. Create `Animated.Value`s in constructor
2. `console.log` values in render()
3. Logging a single, simple value causes app to hang for several seconds. Logging a complex value (nested conditionals, etc) causes app to hang indefinitely, then crash.
4. As the app hung, my memory usage went nuts:
<img width="781" alt="screen shot 2018-12-14 at 9 51 00 am" src="https://user-images.githubusercontent.com/6730148/50018969-e99e5080-ff85-11e8-91f5-bca7c7a280e0.png">

### Expected Behavior

I first created my project via `react native init` and logging `Animated.Value`s within `render` worked fine. then when I realized I could use Expo I simply copied over the files. I expected to see the same behavior as with the react native app.

### Actual Behavior

- App hung indefinitely when navigating to my screens containing `console.log`s of `Animated.Value`s.
- Memory usage went through the roof.
- After a few minutes app crashed.

I ran the profiler for a bit, but stopped after 8sec of unresponsiveness. Here's the output:
![screen shot 2018-12-14 at 9 27 37 am](https://user-images.githubusercontent.com/6730148/50018828-63820a00-ff85-11e8-84bb-4cff3cbb04fe.png)

### Reproducible Demo

There's a commented-out `console.log` at the top of `render()`. Uncomment to break the app.
https://snack.expo.io/@computerjazz/animated-value-logging

**Comment by brentvatne** [comment] 2018-12-17 03:15
i imagine the issue here is that prettyFormat may be attempting to print an object with a recursive reference property.

https://github.com/expo/expo/blob/c6e11a07ac782b7b5f1d7c1b9f708205a4a47fe4/packages/expo/src/logs/LogSerialization.ts#L2

cc @ide

**Comment by ide** [comment] 2018-12-17 18:07
prettyFormat handles recursive objects -- we have several tests for that and it is part of prettyFormat's API. That said, if you try to print an extremely large object tree, prettyFormat may freeze up and there's no good fix for that in prettyFormat. We special-case React node objects to stop trying to print them out and we could do the same for Animated values if we identify the type of problematic object, but the root cause will still persist due to the way prettyFormat works.

**Comment by tsapeta** [comment] 2020-07-11 21:38
The above explanation seems to be enough to close this thread. Also I think logging animated values in reanimated is not a good idea because the actual value is stored on the native side so even if you can get its value, it might be not up-to-date if some animations are running.

**Closed by tsapeta** 2020-07-11 21:38 UTC
