### ISSUE TITLE
onActivityResult not fired in detached Expo app

### ISSUE THREAD

**Issue by gregory90** [expo/expo#651] opened 2017-09-18 08:46 UTC
I have detached Expo app, and not one library which uses `getCurrentActivity().startActivityForResult` works. It returns nothing - no result, no error.
For example https://github.com/tolu360/react-native-google-places or https://github.com/react-community/react-native-image-picker.

I tried to investigate react-native-google-places more closely and it's `onActivityResult` function doesn't get called. (https://github.com/tolu360/react-native-google-places/blob/master/android/src/main/java/com/arttitude360/reactnative/rngoogleplaces/RNGooglePlacesModule.java#L86).

It does work perfectly in app created by `react-native init`

Is that something that needs to be corrected in expo? In specific library? Detached app itself? I'd be happy to provide pull request to make it work, but I really don't know where to start digging:)

Related:
https://github.com/react-community/react-native-image-picker/issues/669
https://github.com/expo/expo/issues/506

**Comment by jimmylee** [comment] 2017-09-19 22:51
Assigning @jesseruder to take a look when he gets a chance, from @terribleben it looks like this may be a duplicate of https://github.com/expo/expo/issues/347?

Thanks for bringing this up @gregory90

**Comment by keeratita** [comment] 2017-12-19 16:24
any updates, please?

**Comment by ide** [comment] 2017-12-20 07:29
Sorry, I don't think we've gotten around to looking into this.

**Comment by keeratita** [comment] 2017-12-24 05:32
Any workaround for me please?

**Comment by dodgecm** [comment] 2018-05-11 16:50
I've run into this issue as well.  @keeratita did you figure out a solution?

**Comment by keeratita** [comment] 2018-05-12 04:15
Hi @dodgecm,

Yes, I found a solution.
 
I used a `host.exp.exponent.ActivityResultListener` to listen an `onActivityResult` event.
for example:

```
private final host.exp.exponent.ActivityResultListener mActivityEventListener = new host.exp.exponent.ActivityResultListener() {
        @Override
        public void onActivityResult(int requestCode, int resultCode, Intent data) {
                // some code here
        }
    };
```

Actually, I can't find its document but I found this from debugging the code myself.
Hope this helps.
Cheers!

**Comment by dodgecm** [comment] 2018-05-12 05:40
you are a gentleman and a scholar, thank you.

**Comment by keeratita** [comment] 2018-05-12 09:09
You’re welcome.

**Comment by mjgallag** [comment] 2018-07-25 17:55
@ide @jesseruder I can't think of any way around this other than having to maintaining a fork of any 3rd party React Native packages we add to ExpoKit that make use of onActivityResult. Any thoughts on a better way, or even better, plans to resolve this issue? Thanks!

**Closed** 2018-11-22 09:38 UTC
Labels: in progress, p1, project: android-runtime

**Comment by sjchmiela** [comment] 2018-11-22 09:40
Hey all! My sincere apologies for taking so long to fix it, I've just landed a PR that should forward `onActivityResult` events to React Native — https://github.com/expo/expo/pull/2768. It will be released in SDK32. Sorry for the inconvenience! 🙏

**Comment by N1ghtly** [comment] 2018-12-11 13:01
That's amazing news sjchmiela! When can we expect v32?

**Comment by sjchmiela** [comment] 2018-12-11 13:22
A rough, but most probably true estimate would be “this month”. 😃
