### ISSUE TITLE
console.error(err) causes standalone app to reload (Android only)

### ISSUE THREAD

**Issue by bengourley** [expo/expo#3719] opened 2019-03-13 11:42 UTC
### Environment

```
  Expo CLI 2.7.0 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 10.4.1 - /usr/local/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.2
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.7.0
```

This bug only affects __Android__ __Standalone__ apps.

### Steps to Reproduce

Calling `console.error()` causes the app to reload in the same way as when there is an unhandled error (e.g. one that is thrown and not caught).

This _only_ happens when the app is running on an __Android__ device (real or virtual) and has been built to __standalone__. It does not occur when the app is running inside the Expo app.

### Expected Behavior

`console.error(err)` writes to the device's log, as per `console.log()`, `console.info()`, `console.warn()` etc. The app remains running in it's current state.

### Actual Behavior

`console.error(err)` writes to the device's log. The app is reloaded and state is lost.

### Reproducible Demo

I created a snack, but since they can't be run in standalone mode it was pointless. Here is the code I was using so that I could trigger the behaviour on-demand (by clicking a button):

```jsx
<Button title='Press me' onPress={() => {
  console.error(new Error('the button was pressed'))
}} />
```

But you can reproduce this simply by adding `console.error()` to an application.

### Related/existing issues
I found this [forum post](https://forums.expo.io/t/production-logging-i-e-on-published-expo-apps/3791/11) which details the same behaviour, but appears to be stale and has no response (regarding the bug, not advice on logging) from the Expo team.

**Comment by brentvatne** [comment] 2019-03-14 04:42
I suspect this is an upstream react-native bug, because in a standalone app there is no difference between how logging works in Expo and in a bare React Native app (see: https://github.com/expo/expo/blob/2de3f90a139d07bffa46046ff10bece66a9fb60c/packages/expo/src/environment/logging.fx.ts#L6-L16 - notice that we only enable logging when a logUrl is present in the manifest, and it is not in a standalone app).

A couple things:
- Can you provide the APK or find the relevant error associated with this in your Android device logs?
- Could you try to reproduce this in a bare React Native app?

**Comment by bengourley** [comment] 2019-03-18 12:04
Here's the first thing you asked for (an apk):

https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40bengourley-bugsnag/console-error-bug-3ad3343074234396adf0fa479024603a-signed.apk

Generated from the slightly tweaked "bare" project template `App.js`:

```js
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Click the button to do a "console.error()"</Text>
        <Button
          title="Click me"
          onPress={
            () => console.error(new Error('button pressed'))
          }
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Interestingly you have to click the button twice before it causes the app to reload. Subsequently it won't cause the app to reload.

The logs from the device's logcat are as follows:

```
03-18 11:53:12.080  5625  5686 E ReactNativeJS: { [Error: button pressed]
03-18 11:53:12.080  5625  5686 E ReactNativeJS:   line: 914,
03-18 11:53:12.080  5625  5686 E ReactNativeJS:   column: 631,
03-18 11:53:12.080  5625  5686 E ReactNativeJS:   sourceURL: '/data/user/0/com.bugsnag.consolebug/files/32.0.0/cached-bundle-experience-%40bengourley-bugsnag%2Fconsole-error-bug682026057-32.0.0' }
```

I haven't reproduced this with a plain React Native project - I will try to at some point, but hopefully this info is helpful.

**Comment by bengourley** [comment] 2019-03-18 15:45
> Could you try to reproduce this in a bare React Native app?

Using the same version of RN (0.57.1) I don't see this behaviour, using `react-native run-android --variant=release` on the same avd.

Logcat output:
```
03-18 15:43:34.393  8448  8469 E ReactNativeJS: [Error: floop]
```

The app does not reload/exit, it just remains interactive.

**Comment by jdanosborne** [comment] 2019-04-05 15:45
I'm seeing this exact error in Expo 29 - an Android app run standalone will reload when it attempts a console.error() of a caught exception.

**Comment by sjchmiela** [comment] 2019-04-17 08:45
I think that's the expected behavior for `console.error` in release/production mode. 🤔 RN treats `console.error` as a fatal exception and reloading JS is a proper behavior for Expo. 😅

**Comment by bengourley** [comment] 2019-04-17 10:14
Hmm, but `console.error()` in a RN app in release mode on Android doesn't result in the `ErrorUtils` global handler being called, let alone with the `isFatal: true` argument…

**Comment by tsapeta** [comment] 2020-07-18 13:49
As nothing has happened here for over a year and we haven't received similar reports, I'm closing it. Let me know if this is still bothering you though.

**Closed by tsapeta** 2020-07-18 13:49 UTC
