### ISSUE TITLE
Expo screen orientation crash

### ISSUE THREAD

**Issue by oromis300** [expo/expo#33376] opened 2024-12-03 09:56 UTC
### Minimal reproducible example

unable

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

--

### Summary

Hi i can't reproduce it on an development build or on my phone but we have a lot a sentry feedback about a crash with the expo screen orientation lib. We are using it to lock the screen in portrait mode in the launch of the app.

```ts
  const useOrientationLock = (): void => {
  const appState = useAppState();

  useEffect(() => {
    if (appState === "active") {
      const currentRouteName = navigationRef.getCurrentRoute()
        ?.name as AllRoutesNames;
      if (
        !currentRouteName ||
        !HORIZONTALLY_ORIENTATED_ROUTES.includes(currentRouteName)
      ) {
        ScreenOrientation.lockAsync(
          ScreenOrientation.OrientationLock.PORTRAIT_UP
        );
      }
    }
  }, [appState]);
};
```

<img width="1136" alt="Capture d’écran 2024-12-03 à 10 46 08" src="https://github.com/user-attachments/assets/8d8cf3e1-829c-4869-a569-1a8d0df373b9">

<img width="1120" alt="Capture d’écran 2024-12-03 à 10 46 19" src="https://github.com/user-attachments/assets/15137c62-e400-41e0-a1e2-c209e1135f55">

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.2.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.9.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.18
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 7.8.1
      expo-cli: 6.3.10
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by chrfalch** [comment] 2024-12-05 12:23
Hi @oromis300 - thanks for submitting the issue! It is hard to debug this without a working reproduction but I understand that it might be a bit hard to make one if this is only happening in production builds.

Could you provide some more information about how you've set up the screen orientation in your app? Especially how you've [configured it in app.json](https://docs.expo.dev/versions/latest/sdk/screen-orientation/#example-appjson-with-config-plugin)?

**Comment by oromis300** [comment] 2024-12-05 15:53
Hi I didn't configure it in the app.json. The only thing i do is the lock the screen in portrait in my parent stackNavigator.
ScreenOrientation.lockAsync(
          ScreenOrientation.OrientationLock.PORTRAIT_UP
        );
        
I try to remove it and replace it in the app.json in the iOS config with 
UISupportedInterfaceOrientations: ["UIInterfaceOrientationPortrait"],
"UISupportedInterfaceOrientations~ipad": ["UIDeviceOrientationPortrait"],

Unfortunately I'm not allowed by my company to publish the app with this modification before january. I will check when it's released if there is nothing more before

**Comment by chunghe** [comment] 2024-12-10 01:26
hi @chrfalch - May I know if it's necessary to add expo-screen-orientation in app.json or it is optional? If I only need to lock the orientation.

**Comment by chrfalch** [comment] 2024-12-10 09:26
Hi @chunghe - only if you want to set the initial orientation (by setting the initialOrientation value in app.json) you need to add the plugin to your app.json file.

**Comment by chrfalch** [comment] 2024-12-10 09:41
@oromis300 I've tried to reproduce it with similar code as you described, but I'm not able to reproduce this one unfortunately. 

Would be great if you could try to create a smaller reproduction to see if we can provoke the same errors as you're seeing. 

I'll close this for now since I've not been able to reproduce - feel free to reopen again if you are able to reproduce.

**Comment by chrfalch** [comment] 2024-12-10 12:14
One more thing @oromis300 - would it be possible to get the full crash report? I'm specifically interested in where the other threads in your crash are at the moment of the crash.

**Closed** 2024-12-11 14:10 UTC
Labels: iOS, ScreenOrientation, Issue accepted

**Comment by oromis300** [comment] 2024-12-17 10:46
Thank you very much to look into this. I will check with the correction you made. Sorry i was off during a few days.
