### ISSUE TITLE
Audio play all sounds on phone unlock

### ISSUE THREAD

**Issue by thomasarbona** [expo/expo#1582] opened 2018-03-30 23:35 UTC
### Environment

Environment:
  OS: Linux 4.10
  Node: 8.4.0
  Yarn: 1.1.0
  npm: 5.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/thomasarbona-b749ff9d-83f3-44b2-9a24-9ea246212ece.tar.gz

Run my app on iOS.

### Steps to Reproduce

1. Open the app and play the sound by clicking on the button
2. Lock your phone
3. Unlock your phone and hear the sound playing

### Expected Behavior

I don't wan't the sounds playing when I unlock the phone on my application.

### Actual Behavior

All the sounds loaded in my app are playing when I unlock my phone on my application.

### Reproducible Demo

https://snack.expo.io/SJVaDB29z

Thank you !

**Comment by sjchmiela** [comment] 2018-04-02 21:22
Hi @thomasarbona, thanks for the report!

Could you, please, try reproducing the issue with the newest iOS client update (and maybe SDK 26)?

I think this issue should have been fixed by https://github.com/expo/expo/commit/3835682976a0ec1c0604654546f5e6f5c77c8de5, which was shipped in Expo Client 2.4.2 and I couldn't reproduce the bug with your Snack on the latest Expo Client update.

**Comment by thomasarbona** [comment] 2018-04-05 23:48
Yes, it works ! Thank you.

**Closed** 2018-04-05 23:48 UTC
