### ISSUE TITLE
[Video][IOS][SDK 33] -- shouldplay behaviour changed?

### ISSUE THREAD

**Issue by jaimereyley** [expo/expo#4661] opened 2019-06-19 19:16 UTC
Hello!

I'm upgrading my app from **SDK 32** to **SDK 33** but my video component is making the app crash. 

I'm using `shouldPlay={this.state.shouldPlay}` to make the video pause and play by listening to changes in the state. 
This approach works fine in SDK32 but in the new SDK any change to **shouldPlay** makes the video start again from the beginning instead of pausing it. It also causes the app to crash if done repeatedly. 

Is there a better approach to do this ?

I've also tried pausing the video `ref` directly with: `playbackObject.pauseAsync()`
and playing it with: `playbackObject.playAsync()` but there is a very noticeable lag before the video responds to any of those actions. This lag is not present in the simulator, only when using the device. 

Are there any video examples for **SDK33** available ?

Thank you very much!

**Comment by cruzach** [comment] 2019-06-19 21:35
Hi @jaimereyley! 

Could you provide a Snack reproducing the issue? Although, I'm not so sure this _is_ an issue. I'd imagine the lag is either due to your connection, OR you may notice a speed up when running in production rather than dev. Also note the message from the docs for changing the value of `shouldPlay`:
> Playback may not start immediately after calling this function for reasons such as buffering.

**Comment by jaimereyley** [comment] 2019-06-19 22:35
Thank you @cruzach!

In [this Snack](https://snack.expo.io/@jaimerey/shouldplay-crash) you can see how making the prop `shouldPlay` listen to changes in the state causes problems like: 

1) Doesn't pause the video, it stops it (unloads it?) and makes it start from the beginning or (sometimes) makes it jump to other positions in the timeline.

2) if done repeatedly crashes the app. 

I believe this code works fine in SDK32
Thanks!

**Comment by cruzach** [comment] 2019-06-20 15:35
Sorry @jaimereyley, I was having some trouble getting your Snack to run, so I jsut put [this one](https://snack.expo.io/@charliecruzan/pauseplayvideoexample) together instead.

Seems to work fine for me, could you try it out on your device? I also did it just by passing the state to the Video's `shouldPlay` prop, and it worked (although a little choppier)

**Comment by jaimereyley** [comment] 2019-06-20 19:57
Thank you @cruzach, your snack works fine for me too when using `setStatusAsync({shouldPlay: !this.state.shouldPlay})`.

Although I think you've also noticed how passing the state to Video's `shouldPlay` prop makes the video flicker and choppier actions. In my case it sometimes causes the app to crash on the simulator.

To make a comparison between **SDK33** and **SDK32**, I slightly changed your code to pass the state to `shouldPlay` in this [Snack](https://snack.expo.io/@jaimerey/pauseplayvideoexample) and published [this project](https://expo.io/@jaimerey/repro32) using SDK32 with the exact same code (except for importing `{ Video } from 'expo'` instead of `'expo-av'`.

You can see how the same code in SDK32 works really well, it's fast and doesn't flicker. 
I'm sorry for linking a project instead of a snack, I wasn't able to make it work in the same way using Snack and version 32.

I could change my app's code to use `setStatusAsync` instead, but in my case listening to the state is the solution with less code required. Also, I'm not sure but I think using `setStatusAsync` in SDK33 is slower than passing the state to `shouldPlay` in SDK32.

Thanks!

**Comment by cruzach** [comment] 2019-06-20 20:42
@jaimereyley I see what you're saying now (although it's mainly an issue with the simulator, as using the method you provided for pausing/playing it seems to work _okay_ on a device (not great))

**Comment by jaimereyley** [comment] 2019-06-20 22:01
Sorry I didn't give details about my device:
iPhone 6s plus
IOS 12.3.1
Latest version of the Expo App for IOS

I've been trying it for a while and see that:
The video flickers **every time** it pauses or plays in the [SDK33 version](https://snack.expo.io/@jaimerey/pauseplayvideoexample) 
Doesn't flicker/is fast and stable on the [SDK32 version](https://expo.io/@jaimerey/repro32).

Thanks!

**Comment by codeplaygoa** [comment] 2019-06-28 07:35
i have a fullscreen horizontal  video slider. Only the active one is played and controlled using shouldplay.
whenever active one comes in view and starts playing i get the same flickering mentioned in above comments. 
Works fine in sdk 32.
This is bugging me now.

**Comment by IjzerenHein** [comment] 2020-08-06 09:45
Closing this issue as this particular problem for iOS was fixed in #5106
Before PR #5106, the source was reloaded on every prop change, causing this problem.
PR for similar problem on Android is also out #9569

**Closed by IjzerenHein** 2020-08-06 09:45 UTC
Labels: AV, Video, iOS
