### ISSUE TITLE
Dont/Ignore playing short sounds on Android (each time randomly sound)

### ISSUE THREAD

**Issue by nicksyndicate** [expo/expo#932] opened 2017-11-07 21:00 UTC
Hello.

I have a lot of short sounds, they are remotely on server.
And I have a problem with them on Android. 

Expo Sound api ignoring playing some sound (one part playing another one - no). I dont know why, I tested different cases. From 20 sounds after playing 5-10 of them other don`t play at all. After reloading app i have the same. Helps only uninstall expo android app. But the problem stays with another sounds. I try different ways, unload sounds, caching them on device but problem stay the same.

I write example https://snack.expo.io/SJkzhqJkz . Here you can see that I have sounds (some of them commented), and by clicking on red button randomply play one of them. After 5-6 plays, some audio ignoring. After reinstall app the same take again but with other sounds.

Could you help me? Thanks!
Maybe I dont know somthing, tell me what i need to fix in snack?

**Comment by jesseruder** [comment] 2017-11-09 23:11
Is this happening on both iOS and Android?

**Comment by justinjoyn** [comment] 2017-11-24 10:49
@jesseruder I have this same issue on Android
SDK Version: 22.0.0
Here's how I'm playing clips:

       `const soundObject = new Audio.Sound();
        try {
            await soundObject.loadAsync(require('../../sfx/finger_snap.mp3'));
            await soundObject.setPositionAsync(0);
            await soundObject.playAsync();
        } catch (error) {
            console.log(error);
        }`

**Comment by nicksyndicate** [comment] 2017-11-27 09:12
Hello!

I have an application with hundreds of short sounds and the user can clap many times over each sound without waiting for the download and the end of playback.
Guys I was able to start it all and it started working.

It took me about 30+ hours.
What would all this have earned on both platforms:

1. If you load the sound it must be unloaded after unloading. But the task becomes more complicated, if you try to unload it at the time of loading, there will be a critical error

2. If you play the audio it must necessarily stop if you need to play 1 more at the time of the first. But the task becomes more complicated if you try to stop it at the moment after playing or before playing. If this is done, there will be a critical error.

3. If you set the callback function _onPlaybackStatusUpdate, you must delete it after playing the sound.

4. In the _onPlaybackStatusUpdate function, you do not always receive a deedJustFinish (sends in time) for IOS so you can not rely on it.

The **general** rule is that when **creating** a sound (loading it, playback, and tracking), it is necessary to perform **reverse operations** if you want to use the new constructor. If you do not do this, everything will be bad.
The tasks are complicated because you do not know exactly when it ended.

**Comment by terribleben** [comment] 2018-01-17 02:30
Hi, can you try updating to SDK 24+ and seeing if the issue persists? We have made a lot of updates to audio playback in the last couple months.

**Comment by sjchmiela** [comment] 2018-11-29 11:37
I'll let myself close this issue tentatively, as Ben said, Audio implementation underwent some major changes since SDK22. I hope the issue is no longer present in recent releases of Expo SDK. 🙂

**Closed by sjchmiela** 2018-11-29 11:37 UTC
Labels: project: media, status: needs more info
