### ISSUE TITLE
Android Location.getCurrentPositionAsync as per sdk32 docs not working, but as per sdk31 docs is working

### ISSUE THREAD

**Issue by techpanga** [expo/expo#4304] opened 2019-05-24 14:23 UTC
## 🐛 Bug Report
Android Location.getCurrentPositionAsync as per sdk32 docs not working, but as per sdk31 docs is working
### Environment
SDK 32, Android

  Expo CLI 2.18.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.6 => 32.0.6
      react: ^16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.1.tar.gz => 0.57.1
      react-navigation: ^3.4.1 => 3.4.1
    npmGlobalPackages:
      expo-cli: 2.18.3

### Steps to Reproduce
Working Code:
let position = await Location.getCurrentPositionAsync({enableHighAccuracy:true});
Not Working Code:
let position = await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Lowest});

**Comment by cruzach** [comment] 2019-05-24 16:20
Hi @techpanga, could you provide the full steps to reproduce? I just tried this on my end and both methods work appropriately

**Comment by techpanga** [comment] 2019-05-25 00:00
Hi @cruzach 

Android version is 7.0.0. Not all android versions has this issue. few versions have this issue.

-Regards, Durga

**Comment by techpanga** [comment] 2019-05-25 16:24
Also in this scenario, the timeout also not working. Please let me know if any more information is needed. I do not have simple app to provide reproduce steps.

**Comment by ch-jung** [comment] 2019-06-10 08:35
same issue too. 
in my case, using android 6.0.1 (samsung galaxy note4)
but same code is working on ios12 (iphoneX)

```
Location.getCurrentPositionAsync({
    accuracy: Location.Accuracy.Lowest
})
```

"expo": "32.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",

**Comment by hutsi** [comment] 2019-06-12 09:08
the same for me - `getCurrentPositionAsync` hangs on with expo `32.0.0`

**Comment by nsdub** [comment] 2019-07-26 16:52
Seeing the same intermittent failures in `expo 33.0.0`. Our workaround right now is to put a timeout on the screen where we use `getCurrentPositionAsync`. If it takes longer than X seconds, reload the app.

**Comment by cruzach** [comment] 2019-07-26 18:23
If you're seeing this issue, please share a repro via snack **and** what device you see this behavior on

**Comment by yunibaek** [comment] 2019-08-28 17:53
Reproducible snack: https://snack.expo.io/@yunibaek/location-bug-android

Device: Samsung Galaxy S8, Android 8.0.0

Error is:
> Error: Location provider is unavailable. Make sure that location services are enabled.

Location services are enabled, yet this error is thrown, as explained here: https://forums.expo.io/t/getcurrentpositionasync-doesnt-return-any-value-infinity-loading/23643/3

This error isn't present in other devices I've used, tested with Pixel 2, android versions 8.1.0, 9.0 
This seems to be a regression because I believe it didn't show this error previously with the mentioned devices.
Could be a device specific thing so would be good to test the galaxy series

**Comment by cruzach** [comment] 2019-08-30 14:21
@yunibaek I believe #5504 is the relevant issue for you (SDK 34, same error message returned)

**Comment by cmacdonnacha** [comment] 2019-11-20 19:50
I am able to reproduce this issue on a OnePlus 3, Android 9.  See snack: https://snack.expo.io/@cmacdonnacha/7b982e

I was not able to reproduce on Google Pixel 3a (Android 10) or Galaxy SM (Android 5)

**Comment by cruzach** [comment] 2019-11-21 14:50
@cmacdonnacha I tried reproducing with your snack on an Android 9 device (a pixel, not a oneplus though) and couldn't

When you call `await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Lowest});` it results in `alert(error.message);`, but calling `await Location.getCurrentPositionAsync({enableHighAccuracy:true});` works correctly?

**Comment by cmacdonnacha** [comment] 2019-11-21 15:37
@cruzach I'll try `await Location.getCurrentPositionAsync({enableHighAccuracy:true});`. I usually just go with `await Location.getCurrentPositionAsync({});`, is that incorrect?

Did you click the button 5 times as it's intermittent?

**Comment by cruzach** [comment] 2019-11-21 17:57
This bug report is saying that 
```
Location.getCurrentPositionAsync({enableHighAccuracy:true})
```
works correctly, but 
```
Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Lowest})
```
results in an error

**Comment by cmacdonnacha** [comment] 2019-11-21 19:42
Ah ok, maybe you guys default to lowest if an empty object is passed in so I could be seeing the same. I'll try using high accuracy.

**Comment by cmacdonnacha** [comment] 2019-11-21 19:43
What's the difference between `enableHighAccuracy` and `accuracy` ?

**Comment by cruzach** [comment] 2019-11-21 19:44
`Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Lowest})` is how it should not be called, `Location.getCurrentPositionAsync({enableHighAccuracy:true})` is from SDK 32

**Comment by cmacdonnacha** [comment] 2019-11-22 09:31
Perfect I'll try `Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Lowest})`

**Comment by cmacdonnacha** [comment] 2019-11-24 18:34
Ok so the issue happened when I chose these :

`Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Lowest})`
`Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced})`

but worked fine when I chose `Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High})`

**Comment by leoceolin** [comment] 2019-11-25 15:21
i have this code
`import * as Location from "expo-location";
import * as Permissions from "expo-permissions";
.
.
.
Permissions.askAsync(Permissions.LOCATION)
        .then(async status => {
          alert("Permissions");
          if (status !== "granted") {
            errorMessage = "Permissão para acesso foi negada.";
          }

          await Location.getCurrentPositionAsync({})
            .then(location1 => {
              alert("get loc");
              // console.log("location lat", location1.coords.latitude);
              // console.log("location long", location1.coords.longitude);
              this.locationCaptured = true;
              this.location = {
                lat: location1.coords.latitude,
                lon: location1.coords.longitude
              };
              console.log("location lat", this.location.lat);
              console.log("location long", this.location.lon);
              alert(`lat ->${this.location.lat} / lon ->${this.location.lon} `)
          
              this.navigation.navigate("SelectOption");
              //this.makeInsert(this.location);
            })
            .catch(error => {
              alert(`ERROR LOCATION - > ${error}`);
              console.log("Error Location: ", error);
            });
        })
        .catch(err => {
          alert(`THE LOCATION - > ${err}`);
          console.log("THE ERROR: ", err);
        });
`

if the device is connected to the internet, it works fine but if i turn off the internet, the location doesn't work and show this message " location provider is unavailable. make sure that location services are enabled"

**Comment by Xerus2000** [comment] 2020-01-21 08:06
For me it doesn't ever return, regardless of whether I use Highest or Low accuracy or anything in between, or whether `enableHighAccuracy` is true. I have only requested the android permission "ACCESS_COARSE_LOCATION" by now though.

**Comment by Xerus2000** [comment] 2020-01-21 08:54
Opened an issue at https://github.com/expo/expo/issues/6816 - for me it was resolved by adding the `ACCESS_FINE_LOCATION` permission

**Comment by appzter** [comment] 2020-04-01 12:15
Also having this issue with expo SDK 36.0.0 running on a Samsung S9 with Android 10 and on a Huawei. Calling 

`const location = await Location.getCurrentPositionAsync({})`

just hangs the app indefinitely on both devices, no error returned. 

Have enabled both `ACCESS_FINE_LOCATION` and `ACCESS_COARSE_LOCATION`

**Comment by faustoct** [comment] 2020-06-12 02:31
**Any workaround to fix it?** It's been hard to deal with. It looks like `Location.getCurrentPositionAsync({})` is not that reliable once we can't guarantee the same behavior on different android decives.

**Comment by faustoct** [comment] 2020-06-18 01:25
Anyone?!? Just stuck in this problem

**Comment by appzter** [comment] 2020-06-18 16:31
> Also having this issue with expo SDK 36.0.0 running on a Samsung S9 with Android 10 and on a Huawei. Calling
> 
> `const location = await Location.getCurrentPositionAsync({})`
> 
> just hangs the app indefinitely on both devices, no error returned.
> 
> Have enabled both `ACCESS_FINE_LOCATION` and `ACCESS_COARSE_LOCATION`



Turned out to be my fault, was missing the google auth token for maps on android in the settings which apparently just crashes the app with no error message.

**Closed** 2020-07-23 12:24 UTC
Labels: Android, Location, needs repro
