### ISSUE TITLE
YA Error: Native splash screen is already hidden. Call this method before rendering any view.

### ISSUE THREAD

**Issue by consciousweb** [expo/expo#11943] opened 2021-02-15 01:52 UTC
**Summary**

Yet another user encountering "Error: Native splash screen is already hidden. Call this method before rendering any view." that many are seeing.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

4.1.6

**Environment**

  Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.3.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.0.14 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

expo team, provide me with an email address and i will provision access to my private git repo.

**Comment by nhuesmann** [comment] 2021-03-17 22:23
I have this issue as well, was losing my mind trying to track down something I'd done wrong. I'm on expo 40 as well.

**Comment by brentvatne** [comment] 2021-03-17 22:24
please provide a minimal reproducible example, we do not want to access your entire project if it can be avoided :)

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by consciousweb** [comment] 2021-03-18 07:19
> I have this issue as well, was losing my mind trying to track down something I'd done wrong. I'm also on expo 40.

@nhuesmann pulling this line from the documented example fixed the issue for me with no found consequence

`await SplashScreen.preventAutoHideAsync();`

> please provide a minimal reproducible example, we do not want to access your entire project if it can be avoided :)
> 
> https://stackoverflow.com/help/minimal-reproducible-example

@brentvatne MRE's are really not a reasonable request despite how often people think they are. It usually takes less time to identify an issue and create a fix yourself than strip an MRE from an application...

**Comment by ioness** [comment] 2021-04-01 20:15
> > I have this issue as well, was losing my mind trying to track down something I'd done wrong. I'm also on expo 40.
> 
> @nhuesmann pulling these lines from the documented example fixed the issue for me with no found consequence so far.
> 
> `await SplashScreen.preventAutoHideAsync();`
> `await SplashScreen.hideAsync()`
> 
> > please provide a minimal reproducible example, we do not want to access your entire project if it can be avoided :)
> > https://stackoverflow.com/help/minimal-reproducible-example
> 
> @brentvatne It usually takes less time to identify an issue and create a fix yourself than strip an MRE from an application...

I fear it works because you're using the Expo client and it is not an standalone App

**Comment by ioness** [comment] 2021-04-01 20:16
I am having this exact problem, have been all day trying to figure out what's wrong...

If I can't fix it I will have to create a minimal reproducible example

**Comment by shamilovtim** [comment] 2021-04-04 21:11
@brentvatne I am experiencing this on bare SDK 40 as well.  I'm just using the recommended / documented code for splash so there's nothing special to point out as far as putting together an example.

```typescript
import { Ionicons } from '@expo/vector-icons';
import AppLoading from 'expo-app-loading';
import { Asset } from 'expo-asset';
import * as Font from 'expo-font';
import React, { useState } from 'react';

const queryClient = new QueryClient();

const App = () => {
  const [isLoadingComplete, setLoadingComplete] = useState(false);

  if (!isLoadingComplete) {
    return (
      <AppLoading
        startAsync={loadResourcesAsync}
        onError={(error) => console.warn(error)}
        onFinish={() => setLoadingComplete(true)}
      />
    );
  } else {
    return (
      <QueryClientProvider client={queryClient}>
        <RxProvider store={store}>
          <PaperProvider theme={theme}>
            <SwitchNavigator />
            <SnackBar />
          </PaperProvider>
        </RxProvider>
      </QueryClientProvider>
    );
  }
};

const loadResourcesAsync = async () => {
  await Promise.all([
    Asset.loadAsync([require('./node_modules/react-native-paper/src/assets/back-chevron.png')]),
    Font.loadAsync({
      ...Ionicons.font,
      TitilliumText250: require('./assets/fonts/TitilliumText22L-250wt.otf'),
      TitilliumText800: require('./assets/fonts/TitilliumText22L-800wt.otf'),
    }),
  ]);
};
```

**Comment by brentvatne** [comment] 2021-04-04 21:24
this warning can happen if `SplashScreen.hideAsync()` is called after fast refresh, where the splash screen is not actually displayed. i think we need to deal with this situation better

**Comment by shamilovtim** [comment] 2021-04-04 21:28
I'm experiencing it after a hard refresh in the metro bundler as well. I've silenced it, so it's not a huge deal at all.

**Comment by shamilovtim** [comment] 2021-04-04 21:31
Have confirmed that it is not present on initial app start, just hard refresh or fast refresh

**Comment by ioness** [comment] 2021-04-06 08:40
> Have confirmed that it is not present on initial app start, just hard refresh or fast refresh

Did you create a iOS standalone to confirm that it happens only when dev refresh ?

**Comment by ioness** [comment] 2021-04-06 08:54
> please provide a minimal reproducible example, we do not want to access your entire project if it can be avoided :)
> 
> https://stackoverflow.com/help/minimal-reproducible-example

Hey, I created a new project and could not reproduce the issue...

Now I got to figure out why on my big project it does not work

**How to reproduce**

npm install --global expo-cli

expo init my-project

expo install expo-app-loading

npm start

App.js:

import { StatusBar } from 'expo-status-bar';
import React, { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';

import AppLoading from 'expo-app-loading';

export default function App() {

  const [ready, setReady] = useState(false);

  if ( !ready ) {

    return (
      <AppLoading 
        startAsync={async () => {
          console.log('before')
          await new Promise(resolve => setTimeout(resolve, 5000))
          console.log('after')
        }}
        onFinish={() => setReady(true)}
        onError={(e) => console.log('App AppLoading', e)}
        />
    )

  } else {

    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <StatusBar style="auto" />
      </View>
    );
  } 
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

**Comment by shamilovtim** [comment] 2021-04-06 23:29
@byCedric I believe this already has repro since me and @brentvatne repro'd it as an HMR issue

**Comment by byCedric** [comment] 2021-04-07 14:11
Oh my bad, I took the wrong issue id here. Thanks for letting me know!

**Comment by yemd** [comment] 2021-04-22 04:14
> I'm experiencing it after a hard refresh in the metro bundler as well. I've silenced it, so it's not a huge deal at all.

How?

**Comment by fschoenfeldt** [comment] 2021-04-23 11:09
> > I'm experiencing it after a hard refresh in the metro bundler as well. I've silenced it, so it's not a huge deal at all.
> 
> How?

Exclude it within your AppContainer:

```
LogBox.ignoreLogs([
  'Native splash screen is already hidden.',
]);
```

**Comment by yemd** [comment] 2021-04-23 14:57
> > > I'm experiencing it after a hard refresh in the metro bundler as well. I've silenced it, so it's not a huge deal at all.
> > 
> > 
> > How?
> 
> Exclude it within your AppContainer:
> 
> ```
> LogBox.ignoreLogs([
>   'Native splash screen is already hidden.',
> ]);
> ```

I came to the same  solution thank you!
Do you know if if ignoreLogs can be used on a component basis? Ignoring only errors from a specific component and not matching the same from another? The documentation is lacking

**Comment by brentvatne** [comment] 2021-04-24 01:08
@yemd - the logs for LogBox are right here: https://reactnative.dev/docs/debugging#logbox

**Comment by brentvatne** [comment] 2021-04-24 01:09
locking this issue b/c we have the info we need to resolve it, and we will work on it.

if you're annoyed by this warning:

```js
LogBox.ignoreLogs([
  'Native splash screen is already hidden.',
]);
```

**Comment by brentvatne** [comment] 2022-11-26 02:34
this should be resolved in sdk 47

**Closed by brentvatne** 2022-11-26 02:34 UTC
Labels: iOS, SplashScreen, needs review
