### ISSUE TITLE
There is a problem with the official website of expo

### ISSUE THREAD

**Issue by Lanceloft** [expo/expo#1826] opened 2018-06-04 01:17 UTC
the official website of expo have some issues and make the app build failed
user-View IPA/APK builds
![broke](http://og683rb19.bkt.clouddn.com/expo.jpg)

**Comment by jimmylee** [comment] 2018-06-04 16:10
Hey @Lanceloft can you share with me the link you're trying to visit?

**Comment by Lanceloft** [comment] 2018-06-08 02:55
https://expo.io/builds @jimmylee

**Comment by ide** [comment] 2019-06-11 19:39
Closing since this issue is a year old and the root cause is likely no longer relevant.

**Closed** 2019-06-11 19:39 UTC
Labels: project: www, status: needs more info
