### ISSUE TITLE
Expo Client App on Android Physical device won't refresh from new bundle

### ISSUE THREAD

**Issue by ortonomy** [expo/expo#4187] opened 2019-05-10 11:28 UTC
### Environment

```bash
  Expo CLI 2.17.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.3.2 => 3.3.2
    npmGlobalPackages:
      expo-cli: 2.17.1
```

Android (physical device, running expo client)
The physical device is a HuaWei ALE-L21 running Android 6 (EMUI 4.0.3) 

### Steps to Reproduce

1. Run expo client on android device
2. Either a) tap project in 'recently opened projects' b) scan QR code from terminal c) scan QR from web portal
3. expo app loads (even if disconnected from packaging server). even try scanning QR code and doesn't reload. 

### Expected Behavior

When I scan the QR code or tap the app the recently open app, the app loads from the latest available JS bundle

### Actual Behavior

The app loads in production mode (which was previously set) and DOES NOT refresh its JS bundle. Proof can be seen when I disconnect the Wifi / wire, and the app still loads from some kind of cache

### Reproducible Demo

I can't really share a snack as the project is too big. The project URL is here: https://expo.io/@ortonomy/CottonMeApp

![experience-HomeActivity-05102019192328](https://user-images.githubusercontent.com/6688676/57524121-74c71b00-7359-11e9-90be-c4311f6a8b9a.png)

**Comment by ortonomy** [comment] 2019-05-10 11:55
pretty sure this is because of the phone's shitty wi-fi, not expo. Sorry.

**Comment by ortonomy** [comment] 2019-05-10 11:59
Interesting, the web view still logs state changes from redux, so there is definitely a network connection between my phone and the packager.

![image](https://user-images.githubusercontent.com/6688676/57525742-1e101000-735e-11e9-9d6b-81104af7711c.png)

**Comment by esamelson** [comment] 2019-10-21 19:25
I'm going to close this as a duplicate of https://github.com/expo/expo/issues/2426. This problem should go away if you switch back to development mode.

**Closed by esamelson** 2019-10-21 19:25 UTC
Labels: Client, project: android-runtime
