### ISSUE TITLE
[expo-dev-client] dev-client does not work with `useFrameworks` and new architecture enabled

### ISSUE THREAD

**Issue by leonhh** [expo/expo#27414] opened 2024-03-04 08:13 UTC
### Summary

When setting `useFrameworks` to either dynamic or static the iOS app won't build. This is also in combination with the new architecture. 

```
"plugins": [
  [
    "expo-build-properties",
    {
      "ios": {
        "useFrameworks": "static",
        "newArchEnabled": true
      }
    }
  ]
],
```

Steps to reproduce:

- Clone the example
- `npm install`
- npm prebuild
- npx expo prebuild --clean
- npm run ios

This build step will cause the error. The issue itself is caused by the expo-dev-menu package.

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

iOS

### Package versions

```
expo-build-properties: 0.11.1
expo-dev-client: 3.3.9
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.11.0/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.8 => 50.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    Expo Workflow: bare

### Reproducible demo

https://github.com/leonhh/expo-reproducer/tree/797a3a3ca8272b67d67160b9d4ce08f05706a13f

### Stacktrace (if a crash is involved)

```
❌  (node_modules/expo-dev-menu/ios/ReactNativeCompatibles/ReactNative/DevClientAppDelegate.mm:19:9)

  17 | #import <React/RCTSurfacePresenter.h>
  18 | #import <React/RCTSurfacePresenterBridgeAdapter.h>
> 19 | #import <ReactCommon/RCTContextContainerHandling.h>
     |         ^ 'ReactCommon/RCTContextContainerHandling.h' file not found
  20 | #import <ReactCommon/RCTHost.h>
  21 | #import <ReactCommon/RCTTurboModuleManager.h>
  22 | #import <react/config/ReactNativeConfig.h>
```

**Comment by leonhh** [comment] 2024-03-04 08:15
Related issue: https://github.com/expo/expo/issues/27383

**Comment by brentvatne** [comment] 2024-03-22 20:57
thanks for the report! we're working on another round of changes for new arch + bridgeless support in sdk 51. cc @gabrieldonadel - can you investigate this along with bridgeless support?

**Comment by ospfranco** [comment] 2024-04-09 08:01
Hit this :) any workaround or waiting for SDK 51 the only option?

**Comment by leonhh** [comment] 2024-05-08 09:31
After upgrading to expo SDK 51 the error has slightly changed:

```
› Preparing expo-dev-menu Pods/expo-dev-menu » expo-dev-menu-Info.plist
› Compiling expo-dev-menu Pods/expo-dev-menu » DevClientAppDelegate.mm

❌  (node_modules/react-native/ReactCommon/cxxreact/JSExecutor.h:15:10)

  13 | #include <cxxreact/NativeModule.h>
  14 | #include <folly/dynamic.h>
> 15 | #include <jsinspector-modern/InspectorInterfaces.h>
     |          ^ 'jsinspector-modern/InspectorInterfaces.h' file not found
  16 | #include <jsinspector-modern/ReactCdp.h>
  17 | 
  18 | #ifndef RN_EXPORT

› Compiling expo-dev-menu Pods/expo-dev-menu » DevMenuLoadingView.m
› Compiling expo-dev-menu Pods/expo-dev-menu » expo-dev-menu-dummy.m
› Compiling expo-dev-menu Pods/expo-dev-menu » EXDevMenu_vers.c
› Compiling expo-dev-menu Pods/expo-dev-menu » EXDevMenuAppInfo.m
› Compiling expo-dev-menu Pods/expo-dev-menu » DevMenuRootView.m
› Compiling expo-dev-menu Pods/expo-dev-menu » DevMenuRCTBridge.mm
› Compiling expo-dev-menu Pods/expo-dev-menu » DevMenuRCTDevSettings.m
› Compiling expo-dev-menu Pods/expo-dev-menu » DevMenuExtensions.m
› Compiling expo-dev-menu Pods/expo-dev-menu » DevClientRootViewFactory.mm

❌  (node_modules/react-native/ReactCommon/cxxreact/JSExecutor.h:15:10)

  13 | #include <cxxreact/NativeModule.h>
  14 | #include <folly/dynamic.h>
> 15 | #include <jsinspector-modern/InspectorInterfaces.h>
     |          ^ 'jsinspector-modern/InspectorInterfaces.h' file not found
  16 | #include <jsinspector-modern/ReactCdp.h>
  17 | 
  18 | #ifndef RN_EXPORT
  ```

**Comment by brentvatne** [comment] 2024-05-08 20:36
duplicate of https://github.com/expo/expo/issues/28209 - we will follow up there!

**Closed by brentvatne** 2024-05-08 20:36 UTC
Labels: Issue accepted, Development Builds

**Comment by ermarin** [comment] 2024-12-13 00:10
Hello, some solution? 😞
