### ISSUE TITLE
addNotificationResponseReceivedListener and useLastNotificationResponse not triggered for killed Standalone  iOS and Android apps

### ISSUE THREAD

**Issue by VeecotechBrandon** [expo/expo#13333] opened 2021-06-18 08:09 UTC
### Summary

SDK Version: 41
Platforms ios/android
Package “expo-notifications”: “~0.11.6”,

If you call Notifications.addResponseReceivedListener or useLastNotificationResponse in useEffect for example, the listener will not be triggered when opening an app from a completely killed state via a notification. 

I tried addNotificationResponseReceivedListener, legacy.addListener (expo 40), useLastNotificationResponse, delay 1~10secs, or async await but all method doesn't work.

app foreground ✅
app backgrounded ✅
app killed 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41

### Environment

 Expo CLI 4.4.3 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.4 => 4.4.4 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. addNotificationResponseReceivedListener
```
useEffect(() => {
    const _notificationSubscription = Notifications.addNotificationResponseReceivedListener(
      (notification) => {
       
             console.log("hi");

      }
    );
    return () => _notificationSubscription.remove();
  }, []);
```

2.  addListener
 ```
_notificationSubscription = Notifications.addListener((notification) => {
      if (notification["origin"] === "selected") {
             console.log("hi");
       }
    });
```

3.  useLastNotificationResponse
```
const lastNotificationResponse = Notifications.useLastNotificationResponse();
  useEffect(() => {
    if (
      lastNotificationResponse &&
      lastNotificationResponse.notification.request.content.data &&
      lastNotificationResponse.actionIdentifier ===
        Notifications.DEFAULT_ACTION_IDENTIFIER
    ) {
      console.log("hi");
    }
    return () => backHandler.remove();
  }, [lastNotificationResponse]);
```

**Comment by cruzach** [comment] 2021-06-18 15:55
hi @VeecotechBrandon , this issue has been reported before and it's usually due to the fact that the listeners aren't being added soon enough after app start. You should add these listeners in _as soon as possible_ to avoid missing notification responses.

Can you build a totally blank app with just the [code from the example snack](https://snack.expo.io/@charliecruzan/13333) and verify for me that you still don't get the responses?

**Comment by cruzach** [comment] 2021-06-21 14:32
Closing for now for lack of reproducible demo, but I'm happy to reopen and investigate if you can provide a full demo using a blank `expo init` project like we ask for

**Closed by cruzach** 2021-06-21 14:32 UTC
Labels: Notifications, needs repro

**Comment by VeecotechBrandon** [comment] 2021-06-22 09:30
> hi @VeecotechBrandon , this issue has been reported before and it's usually due to the fact that the listeners aren't being added soon enough after app start. You should add these listeners in _as soon as possible_ to avoid missing notification responses.
> 
> Can you build a totally blank app with just the [code from the example snack](https://snack.expo.io/@charliecruzan/13333) and verify for me that you still don't get the responses?
> 
> I just tested this myself using that snack code, and [this simulator build](https://expo.io/artifacts/bc76820e-b750-4b00-8976-aa6fe537ed91), and you can see that the response listener is triggered even when the app was killed. Just open the app, click the button, kill the app, then tap the notification.

Alright, I get it.

**Comment by islamouzou** [comment] 2021-11-22 19:58
The issue is still there SDK 42 (managed ), using the addNotificationResponseReceivedListener or the new hook even if it's the first line in App.js , same results , However sometimes it works .

**Comment by felippewick** [comment] 2022-07-20 14:50
I also had the problem with opening the url received from a push notification with SDK 45. I can confirm what @cruzach said that addNotificationResponseReceivedListener triggers correctly. However, opening the url (with `Linking.openUrl`) which I also configured in the Linking Config with react-navigation didn't work. 

Delaying `Linking.openUrl` with setTimeout solved my issue. I'm not an expert and quite new to RN & expo but the problem rather seems to be with react navigation, at least on iOS which I tested on.

You can take a look at the working code here: [https://github.com/felippewick/open_url_pushnotification_killed_app](url). This is my first public repo & reproduction. Let me know if I can improve something to make it easier for you to use it.
