### ISSUE TITLE
Notifications.getExpoPushTokenAsync() does not resolve or reject

### ISSUE THREAD

**Issue by germancardenasm** [expo/expo#7617] opened 2020-04-02 19:56 UTC
### Environment
Expo CLI 3.11.5 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      @testing-library/react-native: ^4.1.0 => 4.2.0 
      @types/react: ^16.9.15 => 16.9.16 
      @types/react-navigation: ^3.4.0 => 3.4.0 
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.0.6 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.5

app's target: iOS, Android

### Steps to Reproduce
The application stops executing when it uses the Notifications API. The app was working fine last tuesday but today it does not work in the expo client.

For example the app stops executing when I use :
let token = await Notifications.getExpoPushTokenAsync();

### Expected Behavior
I expect to receive an expo push token and the code to continue running.

### Actual Behavior
The code stops executing when it has to use the Notification API.

### Reproducible Demo
https://snack.expo.io/@documentation/pushnotifications?platform=ios

**Comment by brentvatne** [comment] 2020-04-02 21:57
the snack you shared (which is on sdk34) works as expected for me.

i updated that snack to sdk 37 and it works as expected: https://snack.expo.io/@notbrent/pushnotifications?platform=ios

here's an example on sdk 36, works as expected:
https://snack.expo.io/@notbrent/tenacious-toffee

and sdk 35, also logs the result as expected:
https://snack.expo.io/@notbrent/arrogant-chips

happy to help but we need steps to reproduce

**Comment by Bashin** [comment] 2020-04-02 23:07
#7606

**Comment by ramonluis1987** [comment] 2020-04-03 00:27
Same Issue. 

android
sdk: 37
expo cli. 3.17.11

any help?

**Comment by ramonluis1987** [comment] 2020-04-03 04:55
@germancardenasm I had the same issue and the reason was that I have updated my expo client to 2.15.0 and got the issue. Solution: if you are using version 36 or below install expo client 2.14.0. You can download it here https://apkpure.com/expo/host.exp.exponent/versions.

Environment. 
Expo 36
Android

**Comment by merikwesterveld** [comment] 2020-04-03 13:48
Having the same issue. Configure Firebase and all but still nog resolving or rejecting the method. Not running on an emulator either using Expo 37 and Expo client 2.15.0 on Anrdoid.

**Comment by sjchmiela** [comment] 2020-04-03 15:06
Hey all, let me close this issue in favor of https://github.com/expo/expo/issues/7606 (this one is a duplicate of #7606).

@Bashin as per your comment at https://github.com/expo/expo/issues/7606#issuecomment-608136327, could you please open another issue? This and #7606 are occurring in managed workflow and you are experiencing issues in bare workflow, which should be a totally different subject. 🙂

**Closed by sjchmiela** 2020-04-03 15:06 UTC
Labels: needs repro

**Comment by kgpasta** [comment] 2020-04-17 23:50
@Bashin @sjchmiela I'm also experiencing this issue on iOS in the bare workflow, did you manage to find a solution for it?

**Comment by Bashin** [comment] 2020-04-18 10:24
@kgpasta The issue is still there for me but it only shows up during development in xcode. The moment I produce a standalone build the promise resolves and remote notifications work again as usual. Kinda hard to develop notification handling this way to be honest.

I use the following workaround so that the app does not hang up while developing:

`const { status } = await Notifications.getPermissionsAsync();
if (status === 'granted') {
  return new Promise((resolve) => {
    Notifications.getExpoPushTokenAsync({ experienceId: '@b4takeoff/bfto' }).then(({ data }) => resolve(data));
    setTimeout(() => resolve(''), 3000);
  });
}`

**Comment by hunterbmt** [comment] 2020-04-18 17:03
@Bashin could you share your config? I'm facing the same problem. I tried to build the test flight but it doesn't resolve the getExpoPushTokenAsync.

**Comment by kgpasta** [comment] 2020-04-19 16:41
@hunterbmt @Bashin I found a solution (at least for my case). You need to set up a firebase config ([details here](https://firebase.google.com/docs/ios/setup)) and then move `GoogleService-Info.plist` into the iOS folder and add it to your xcode project. After I did that, it started working for me.
