### ISSUE TITLE
Some issues with EAS build

### ISSUE THREAD

**Issue by alexandrius** [expo/expo#12791] opened 2021-05-02 10:16 UTC
### Summary

1 - TextInput has weird horizontal padding. You can compare screenshots below. The text "horizontalpadding" starts exactly on the edge in 2nd screenshot.
First picture is eas build sdk41 while second is Expo GO client or expo build 
![Screenshot_Expo_Go_20210502-140435](https://user-images.githubusercontent.com/5978212/116809576-b3120200-ab4f-11eb-85ad-de67f13cd647.png)
![Screenshot_Expo_Go_20210502-140425](https://user-images.githubusercontent.com/5978212/116809578-b5745c00-ab4f-11eb-8687-6102ed3b901e.png)

2 - Translucent status set in app.json is ignored. Setting translucent in runtime doesn't work either and also looks odd
![photo_2021-05-02_14-01-33](https://user-images.githubusercontent.com/5978212/116809659-2ddb1d00-ab50-11eb-9521-3ff6fd5da195.jpg)

3- Splash screen no longer shows up. This happens on iOS as well
![photo_2021-05-02_14-01-29](https://user-images.githubusercontent.com/5978212/116809673-3fbcc000-ab50-11eb-859d-2f12e5723c95.jpg)

4 - If you have expo-branch installed. You get crash when launching the app
![E0NUGWFXEAAl6YU](https://user-images.githubusercontent.com/5978212/116809686-4d724580-ab50-11eb-8467-ba8a77deb0cf.jpeg)

Here's my app.json
```json
{
  "expo": {
    "name": "Stillwhite",
    "slug": "Stillwhite",
    "privacy": "public",
    "facebookScheme": "fb123",
    "facebookAppId": "123",
    "facebookDisplayName": "Stillwhite",
    "backgroundColor": "#000000",
    "androidStatusBar": {
      "barStyle": "light-content",
      "translucent": true
    },
    "platforms": [
      "ios",
      "android"
    ],
    "primaryColor": "#2699FB",
    "version": "1.6.4",
    "scheme": "stillwhite",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "backgroundColor": "#2699FB"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "stillwhite",
            "project": "stillwhite",
            "authToken": "xxxxxxx"
          }
        }
      ]
    },
    "userInterfaceStyle": "automatic",
    "ios": {
      "buildNumber": "28",
      "supportsTablet": false,
      "bundleIdentifier": "com.stillwhite.app",
      "appStoreUrl": "https://apps.apple.com/us/app/stillwhite-wedding-dresses/id1483180828",
      "googleServicesFile": "./GoogleService-Info.plist",
      "config": {
        "branch": {
          "apiKey": "key_live_Xxxxxxxxxxxxx"
        }
      }
    },
    "android": {
      "versionCode": 28,
      "package": "com.stillwhite.app",
      "useNextNotificationsApi": true,
      "playStoreUrl": "https://play.google.com/store/apps/details?id=com.stillwhite.app",
      "adaptiveIcon": {
        "backgroundColor": "#2699FB",
        "foregroundImage": "./assets/adaptive/icon-foreground.png"
      },
      "backgroundColor": "#FFFFFF",
      "googleServicesFile": "./google-services.json",
      "config": {
        "branch": {
          "apiKey": "key_live_Xxxxxxxxxxxxx"
        }
      }
    },
    "notification": {
      "iosDisplayInForeground": true,
      "icon": "./assets/push_icon.png"
    }
  }
}
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 25, 26, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: 41.0.0 => 41.0.0 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

The summary is probably applicable to any blank project

**Comment by giautm** [comment] 2021-05-11 07:45
Related https://github.com/expo/expo/issues/12883

**Comment by kessris** [comment] 2021-05-25 02:17
I'm also seeing some overlapping and non-overlapping issues. Everything works fine with 'expo build:android' but not with EAS build. EAS build for iOS also works fine.

1. TextInput vertical padding
2. translucent status bar not working
3. map cursor size
4. image isn't rendering from URL

![Group 15 (2)](https://user-images.githubusercontent.com/36322619/119429865-95563980-bcc4-11eb-8b8c-c471d0dd7763.png)

**Comment by EvanBacon** [comment] 2021-05-28 22:03
> In my case, `TextInput` usually receives an odd VERTICAL padding, and even gets culled. Of course it looks normal with Expo Go or a normal standalone build. So it's pretty hard to just guess a fix and then wait 8 minutes for EAS to complete the build (and then see what happens).

@luis-si are you able to repro these issues locally with `expo run:[ios|android]`? If so, it should be much faster to debug.

**Comment by brentvatne** [comment] 2021-05-28 23:55
@kessris - not sure what could be causing the snap-carousel and maps issues you're seeing, those seem possibly unrelated and something you could follow up on with those individual repositories, but if you can provide more info and a minimal reproducible example we can look.

**Comment by kessris** [comment] 2021-05-29 01:33
@brentvatne It's interesting because I don't see any of these issues with other builds.

**Comment by kessris** [comment] 2021-05-29 01:37
@brentvatne It's interesting because I don't see any of these issues with other builds (expo build:android -> no issues) (expo build:ios -> no issues) (eas build for ios -> no issues) (eas build for android -> 4 issues mentioned above). I'll try to see if I can create a minimal reproducible example like you suggested, thanks!

**Comment by kessris** [comment] 2021-05-29 08:00
@brentvatne I was able to reproduce the issues except the map one - I'll update here if I manage to reproduce it. 

For the carousel issue, I found out the cause of it. It seems like images with insecure url (http) don't render while https ones do.

Also I found another problem; the default colour for text/icon should be black and they are displayed black in the emulator and iOS but not in EAS android build. 

All the issues here are only present on EAS build for Android.

The repo is here: https://github.com/kessris/Expo-EAS-Android-Build-Issue
![Group 1](https://user-images.githubusercontent.com/36322619/120062732-6fa89780-c018-11eb-90b3-50fac3af988c.png)

**Comment by alexandrius** [comment] 2021-05-29 09:51
To fix paddings in TextInput:
https://stackoverflow.com/a/64387960/2280829

To fix the statusbar:
https://proandroiddev.com/android-full-screen-ui-with-transparent-status-bar-ef52f3adde63

Splash screen is empty if you only use color without real image.

**Comment by kessris** [comment] 2021-08-01 20:21
Hi, any updates on this issue?

**Comment by EvanBacon** [comment] 2021-08-02 20:49
@kessris there are a handful of issues mentioned here. Many of them were fixed in https://github.com/expo/expo/pull/13196

**Comment by brentvatne** [comment] 2021-08-04 21:51
we don't plan on supporting expo-branch on eas build, instead we hope that there will be a config plugin built to support the react-native-branch library. closing this because the other issues discussed here should be resolved, please create a new issue for any specific issue that persists

**Closed by brentvatne** 2021-08-04 21:51 UTC
Labels: needs review

**Comment by brentvatne** [comment] 2021-11-19 23:25
here's a workaround that you can use for react-native-branch for now: https://forums.expo.dev/t/eas-react-native-branch-example-config-plugin-working-on-ios-and-android/56017
