### ISSUE TITLE
[expo-local-authentication] app_cancel bug

### ISSUE THREAD

**Issue by wojciechkrol** [expo/expo#12353] opened 2021-03-30 13:59 UTC
### Summary

Authorization hangs and an `app_cancel` error is thrown. When the application asks for the fingerprint, then we lock the screen and unlock it using a pattern or a pin. After that each `authenticateAsync` call throws an `app_cancel` error. This issue does not happen every time.

I use Xiaomi Mi9.

It seems like there is a problem with Android implementation and property `mIsAuthenticating` is always true after case described above, thats why another call of `authenticateAsync` causes this error.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

10.0.0

### Environment

I use expo-local-authentication with unimodules.

### Reproducible demo or steps to reproduce from a blank project

Look at summary.

**Comment by AdamJNavarro** [comment] 2021-03-31 15:58
Hey @wojciechkrol, any chance you've tested this on other Android devices to see if the issue can be reproduced on devices other than the Mi9?

Cheers,
Adam

**Comment by wojciechkrol** [comment] 2021-04-02 09:35
Hey @AdamJNavarro, right now I don't have an access to other Android device having fingerprint sensor.

**Comment by 1337LutZ** [comment] 2021-04-13 09:18
I had exactly the same issue. I "solved" it by managing an `isAuthenticating` state on my end to make sure I never run the code twice before waiting for it to finish. Annoying, but it works.

**Comment by jon-nona** [comment] 2021-06-10 18:13
@1337LutZ @wojciechkrol @1337LutZ I think this is fixed by https://github.com/expo/expo/pull/13023 , but an update for the package is not released yet.

I had this issue and set out to fix it, and got it working by editing the package in the project I was using it in locally but upon setting out to create a PR I found out that @lukmccall had already created a PR and had it merged.

**Comment by wojciechkrol** [comment] 2021-06-10 19:10
@jon-nona Great news! Thank you for update. Can't wait for this fix to be released.

**Comment by lukmccall** [comment] 2021-06-14 09:06
It seems to be fixed by https://github.com/expo/expo/pull/13023. The patch will be released with the new SDK (42). 

I'm closing this issue for now. However, feel free to reopen it, if this bug will still be present in the SDK 42.

**Closed by lukmccall** 2021-06-14 09:06 UTC
Labels: needs more info, needs review
