### ISSUE TITLE
LegacyNotifications, iOS, "iosDisplayInForeground": true: subscription event not fired on receive notification in foreground

### ISSUE THREAD

**Issue by sa1dai** [expo/expo#9831] opened 2020-08-19 10:49 UTC
## 🐛 Bug Report

LegacyNotifications, iOS, "iosDisplayInForeground": true: 

When send remote notification and app is in foreground, subscription event not fired on receive notification, it fires only on tap, but unexpectedly origin='receive', when I tapped on notification on foreground.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
 Expo CLI 3.24.2 environment info:
    System:
      OS: Linux 5.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.0 - /usr/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ~38.0.8 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.24.2

### Reproducible Demo

See steps to reproduce
 
### Steps to Reproduce

1. expo init --npm
2. choose blank project
3. move to created project folder
4. replace content of App.js to example from snack on this page (you should go through snack link): https://docs.expo.io/versions/latest/sdk/legacy-notifications/
5. expo install expo-permissions
6. expo install expo-constants
7. add  
```
"notification": {
      "iosDisplayInForeground": true
    }
``` 
to app.json
8. expo start
9. open on iOS and press send notification
10. no console output on receive notification

### Expected Behavior vs Actual Behavior

Receive console output on step 10 in steps reproduce vs no output on receive notification

**Comment by cruzach** [comment] 2020-08-24 15:54
@sa1dai this looks like a duplicate of https://github.com/expo/expo/issues/7863, so I'm going to close this issue. If you test the solution I shared there and it doesn't work for you, let me know (and include the steps to reproduce that) and I'll be happy to re-open this issue

**Closed by cruzach** 2020-08-24 15:54 UTC
Labels: Issue needs review, Notifications, iOS
