### ISSUE TITLE
Missing deviceId from the new version of Expo client

### ISSUE THREAD

**Issue by giautm** [expo/expo#2032] opened 2018-07-26 07:13 UTC
`deviceId` became to undefined because `deviceId: ExponentConstants ? ExponentConstants.installationId : undefined` overrider that value. My App is used SDKv28, so the native code was not up-to-date with JS changed.

https://github.com/expo/expo/blob/8870f75883c8d1dd4a258f702876d5e6d961c32a/modules/expo-constants/src/Constants.js#L23-L27

**Comment by elliotstokes** [comment] 2018-07-26 09:48
This is causing us issues. Is there anyway we can move back to the old Expo client at all? Or a workaround until this fix is merged?

**Comment by giautm** [comment] 2018-07-26 10:00
@elliotstokes: I use `uuid` as the temporary solution, no way to get `deviceId` from expo. :'(

**Comment by herdani** [comment] 2018-07-26 12:30
same here :(

**Comment by ide** [comment] 2018-07-26 16:30
We need to know: the platform is this happening on, the version of the native Expo client from the store, the sdkVersion in package.json, and the version of the `expo` package in the project dependencies.

We think the root cause is likely because the new version of the Expo client defines `installationId` from the native side instead of `deviceId` and that change got retroactively applied to older SDK versions, but that root cause doesn't line up with the code snippet in the first post and attached PR.

If our hypothesis is right and you are using an older SDK version (up to and including 28) with the latest Expo client from yesterday, you should be able to work around this by using `Expo.Constants.installationId` instead of `Expo.Constants.deviceId`. We didn't intend to make this retroactive breaking change, though, so if that's the actual issue we'll publish new versions of the JS `expo` package you can install without needing to change your project code or update your SDK version.

**Comment by elliotstokes** [comment] 2018-07-26 17:30
For me:
Client version: 2.7.0.1016186
SDK version: 28.0.0

Thanks. If you need any more info, shout.

**Comment by giautm** [comment] 2018-07-26 17:41
Sorry, I’m on mobile. There is some screenshot and the snack: 
https://snack.expo.io/@giautm/device-id
![189673b9-3417-40d9-8af2-301e5d6cb7f3](https://user-images.githubusercontent.com/12751435/43278598-bf2caf40-9135-11e8-8609-db470c9b18e2.png)
![4d87032a-fb00-47b6-a136-e6a90ee50175](https://user-images.githubusercontent.com/12751435/43278599-bf7b2026-9135-11e8-81c5-ecd4d4f8cba1.png)
![de08e9a5-9241-4250-8f27-d1781ceac631](https://user-images.githubusercontent.com/12751435/43278600-bfbd94ba-9135-11e8-929e-450da57b55c4.png)

**Comment by OmriSama** [comment] 2018-07-26 19:44
+1 This broke my application (we're targeting SDK 27). Is there a way to roll back to an older client version for the simulator?

**Comment by ide** [comment] 2018-07-26 20:06
I don’t think there is a simple way to rollback. Patching in deviceId = deviceId || installationId is probably the simplest workaround until we publish new JS SDKs with that patch.

**Comment by ide** [comment] 2018-07-26 21:56
We've published new versions of the `expo` package with a fix for this that works with the latest client as well as older ones. After installing the new package you shouldn't have to make any changes to your code. These are the versions on npm:

SDK 28: 28.0.1
SDK 27: 27.1.1
SDK 26: 26.1.1
SDK 25: 25.1.1
SDK 24: 24.1.1
SDK 23: 23.1.1
SDK 22 was dropped with the latest Expo client and therefore is unaffected by the breaking change in this issue.

Please give these packages a try and if they address this issue we'll close it out.

**Comment by giautm** [comment] 2018-07-27 01:52
@ide: I confirmed this fix is worked. Tks. Look like the root-cause is missing publish JS version for the old SDK. :)

**Closed** 2018-07-27 01:53 UTC

**Comment by steinnes** [comment] 2018-08-16 13:45
I'm not able to find the `26.1.1` version anywhere.  Was it released?
![screenshot from yarnpkg](https://user-images.githubusercontent.com/1097582/44212319-8d076200-a15a-11e8-8ebf-956c3e2e83c7.png)
(source: https://yarnpkg.com/en/package/expo)

**Comment by ide** [comment] 2018-08-16 18:13
@steinnes good catch - 26.1.1 is now on npm.
