### ISSUE TITLE
[expo-file-system] `copyAsync` fails on file in `tmp` directory on iOS

### ISSUE THREAD

**Issue by jkaufman** [expo/expo#30108] opened 2024-07-01 18:57 UTC
### Minimal reproducible example

Bug prevents simple reproduction

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

`expo-file-system`'s `copyAsync` fails on files in the application `tmp` directory.

Example path: `file:///private/var/mobile/Containers/Data/Application/4D8C0527-4EFB-45D5-A4FF-D74CB5433995/tmp/filename.jpeg`

The following method grants read access to the bundle, caches, and documents directories, but not the `tmp` directory:

https://github.com/expo/expo/blob/ccaefa5b3ece0141709cea14dff4e22aa85a1e04/packages/expo-modules-core/ios/FileSystemUtilities/FileSystemUtilities.swift#L62

Meanwhile, `getInfoAsync` can read from the tmp directory without issue because it does not perform the same check.

A deterministic, minimal repro case requires write access to the tmp directory, which is also not available without dropping to native code.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/username/.rvm/gems/ruby-3.2.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 31, 33, 34
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 33.0.0, 33.0.1, 34.0.0, 34.0.0
        System Images: android-28 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.17 => 51.0.17
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
      react-native-web: ~0.19.12 => 0.19.12
    npmGlobalPackages:
      eas-cli: 9.2.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check for common project setup issues
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by gwashburne** [comment] 2024-07-10 01:16
Is there any update to this? I seem to be having the same issue.

**Comment by jkaufman** [comment] 2024-07-10 01:25
@gwashburne As a temporary workaround, I simply patched out the read permissions check. I’m not using Expo Go and don’t need scoped directories.

**Comment by gvanderclay** [comment] 2024-07-10 14:11
We are encountering this issue as well. I have created a [minimal reproducible example](https://github.com/gvanderclay/CopyAsyncTmpDirIssue) and discovered that `writeStringAsync` is also affected by this problem. It seems that any function reading file contents from the tmp directory might be impacted.

**Comment by gwashburne** [comment] 2024-07-10 15:17
> @gwashburne As a temporary workaround, I simply patched out the read permissions check. I’m not using Expo Go and don’t need scoped directories.

@jkaufman Where is that swift file located? Having some trouble finding it in my project

**Comment by jkaufman** [comment] 2024-07-10 16:56
@gwashburne https://github.com/expo/expo/blob/d44cdaed02892877071be9b720cae951b0a8ead7/packages/expo-file-system/ios/FileSystemModule.swift#L102

**Comment by emilje** [comment] 2024-07-19 21:11
Can confirm I'm having the same issue, I wanna move or delete files from the tmp folder and am not able to do so leading to my app size going into gigabytes rather quickly when making videos.

**Comment by aleqsio** [comment] 2024-08-13 17:10
Yup, can confirm the above fixes it for me in Expo Go – I'll cherrypick it so it goes out for SDK51

**Comment by aleqsio** [comment] 2024-08-14 09:08
It's out in expo@51.0.27 (thanks @brentvatne) – closing this once someone confirms it works for them now :)

**Comment by gvanderclay** [comment] 2024-08-20 20:06
@aleqsio Thanks for the quick turnaround on this! I just confirmed that this works with 51.0.28

**Closed** 2024-08-20 20:34 UTC
Labels: pending closure, Issue accepted

**Comment by bernborgess** [comment] 2024-09-09 16:51
What `expo-file-system` version implements the patch alongslide `expo@51.0.27` ? Apparently i'm still having the issue with `expo@51.0.31` and `expo-file-system@~17.0.1`

**Comment by bernborgess** [comment] 2024-09-17 12:39
Seems to be working now! Thanks for the patch! :rocket: 

> What `expo-file-system` version implements the patch alongslide `expo@51.0.27` ? Apparently i'm still having the issue with `expo@51.0.31` and `expo-file-system@~17.0.1`

**Comment by bernborgess** [comment] 2024-09-17 13:13
> What `expo-file-system` version implements the patch alongslide `expo@51.0.27` ? Apparently i'm still having the issue with `expo@51.0.31` and `expo-file-system@~17.0.1`

What is the supported syntax? I have tried both ways, and the 'not readable' error appears either way:

Absolute path:
```typescript
  // FileSystem.copyAsync:
  // LOG  from:file:///private/var/mobile/Containers/Data/Application/A274E5DE-3906-458C-80D8-E195DE64BA67/tmp/2D9FCD99-92D6-47D5-B0B0-A367FBD8E04F.jpeg
  // LOG  to:file:///var/mobile/Containers/Data/Application/A274E5DE-3906-458C-80D8-E195DE64BA67/Documents/photos/2D9FCD99-92D6-47D5-B0B0-A367FBD8E04F.jpeg
  // ERROR  Error copying file:  [Error: Calling the 'copyAsync' function has failed
  //   → Caused by: File '/private/var/mobile/Containers/Data/Application/A274E5DE-3906-458C-80D8-E195DE64BA67/tmp/672E8AB0-12AC-430E-BABD-AFF6F95C9A7B.jpeg' is not readable]
  //    LOG 

  FileSystem.copyAsync({ from: imageRawPath, to: photoPath })
    .then(() => console.log("File copied successfully!"))
    .catch((err) => console.error("Error copying file: ", err));
```
Relative path:
```typescript


  //  FileSystem.copyAsync:
  //  LOG  from: tmp/4EAD9FB1-7740-4E9F-8792-F21F469E0174.jpeg
  //  LOG  to: 4EAD9FB1-7740-4E9F-8792-F21F469E0174.jpeg
  //  ERROR  Error copying file:  [Error: Calling the 'copyAsync' function has failed
  // → Caused by: File '/tmp/4EAD9FB1-7740-4E9F-8792-F21F469E0174.jpeg' is not readable]

  FileSystem.copyAsync({ from: relativeImagePath, to: photoName })
    .then(() => console.log("File copied successfully!"))
    .catch((err) => console.error("Error copying file: ", err));
```

Note that `imageRawPath` came from "react-native-vision-camera" and is already previewed by the user via this _uri_, so the path is valid.

**Comment by bernborgess** [comment] 2024-09-17 14:01
> > > What `expo-file-system` version implements the patch alongslide `expo@51.0.27` ? Apparently i'm still having the issue with `expo@51.0.31` and `expo-file-system@~17.0.1`
> > 
> > 
> > What is the supported syntax? I have tried both ways, and the 'not readable' error appears either way:
> > Absolute path:
> > ```ts
> >   // FileSystem.copyAsync:
> >   // LOG  from:file:///private/var/mobile/Containers/Data/Application/A274E5DE-3906-458C-80D8-E195DE64BA67/tmp/2D9FCD99-92D6-47D5-B0B0-A367FBD8E04F.jpeg
> >   // LOG  to:file:///var/mobile/Containers/Data/Application/A274E5DE-3906-458C-80D8-E195DE64BA67/Documents/photos/2D9FCD99-92D6-47D5-B0B0-A367FBD8E04F.jpeg
> >   // ERROR  Error copying file:  [Error: Calling the 'copyAsync' function has failed
> >   //   → Caused by: File '/private/var/mobile/Containers/Data/Application/A274E5DE-3906-458C-80D8-E195DE64BA67/tmp/672E8AB0-12AC-430E-BABD-AFF6F95C9A7B.jpeg' is not readable]
> >   //    LOG 
> > 
> >   FileSystem.copyAsync({ from: imageRawPath, to: photoPath })
> >     .then(() => console.log("File copied successfully!"))
> >     .catch((err) => console.error("Error copying file: ", err));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Relative path:
> > ```ts
> >   //  FileSystem.copyAsync:
> >   //  LOG  from: tmp/4EAD9FB1-7740-4E9F-8792-F21F469E0174.jpeg
> >   //  LOG  to: 4EAD9FB1-7740-4E9F-8792-F21F469E0174.jpeg
> >   //  ERROR  Error copying file:  [Error: Calling the 'copyAsync' function has failed
> >   // → Caused by: File '/tmp/4EAD9FB1-7740-4E9F-8792-F21F469E0174.jpeg' is not readable]
> > 
> >   FileSystem.copyAsync({ from: relativeImagePath, to: photoName })
> >     .then(() => console.log("File copied successfully!"))
> >     .catch((err) => console.error("Error copying file: ", err));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note that `imageRawPath` came from "react-native-vision-camera" and is already previewed by the user via this _uri_, so the path is valid.
> 
> @bernborgess For react-native-vision-camera, I recommend taking [a look at this](https://github.com/mrousavy/react-native-vision-camera/issues/893) and avoiding the tmp folder altogether

Thanks for the quick reply! I'm updating the "react-native-vision-camera" and will post here the follow up!
