### ISSUE TITLE
Expo Barcode Scanner crash with Expo SDK43 on Android SDK29 (Android 10)

### ISSUE THREAD

**Issue by barbhackk** [expo/expo#15309] opened 2021-11-26 10:44 UTC
### Summary

Hi,

App crash with latest Expo SDK43 only on Android device with Android 10 (SDK 29). Work perfect on Android 11 (SDK 30).
The app crash with error:

```11-26 11:19:14.974 21843 21973 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
11-26 11:19:14.974 21843 21973 E AndroidRuntime: Process: com.g.gclient, PID: 21843
11-26 11:19:14.974 21843 21973 E AndroidRuntime: java.lang.IllegalArgumentException: Scan output cannot be null
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at expo.modules.barcodescanner.scanners.ZxingBarCodeScanner.scan(ZxingBarCodeScanner.kt:56)
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at expo.modules.barcodescanner.BarCodeScannerViewFinder$scanForBarcodes$1.invokeSuspend(BarCodeScannerViewFinder.kt:194)
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
11-26 11:19:14.974 21843 21973 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
11-26 11:19:14.980  1990 21974 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

```Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      npm: 7.22.0 - ~/.nvm/versions/node/v14.17.6/bin/npm
      Watchman: 2021.11.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 26, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 32.0.0
        System Images: android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.2 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare
```

### Reproducible demo

For test, run `Expo init my-app`, install expo-barcode-scanner with `expo install expo-barcode-scanner`. Integrate like [https://docs.expo.dev/versions/v43.0.0/sdk/bar-code-scanner/](https://docs.expo.dev/versions/v43.0.0/sdk/bar-code-scanner/)

Next step : `npm run android` on device with SDK29 (Android 10).

Try open the app and crash instantly.

EDIT : After several tests on different android emulator, it seems that this is slightly random. Create fresh emulator with API29 and launch the application.

**Comment by barbhackk** [comment] 2021-11-26 13:13
Hi,

Today there are still a lot of devices with Android 10 or less. I don't have the problem with Android 11 ?.

However I applied a fix on the ZxingBarCodeScanner.kt file and it works. See issue [https://github.com/expo/expo/issues/13049#issuecomment-970241633](https://github.com/expo/expo/issues/13049#issuecomment-970241633)

```
+ override fun scan(data: ByteArray, width: Int, height: Int, rotation: Int): BarCodeScannerResult? {
- override fun scan(data: ByteArray, width: Int, height: Int, rotation: Int): BarCodeScannerResult {
    // rotate for zxing if orientation is portrait
    var innerData = data
    var innerWidth = width
    ...

+   return scan(generateSourceFromImageData(innerData, innerWidth, innerHeight));
-   return requireNotNull(
-     scan(generateSourceFromImageData(innerData, innerWidth, innerHeight))
-   ) { "Scan output cannot be null" }
  }
```

**With this fix, work perfect on Android 9, 10 and 11.**

Please correct your version of the package for other users who may have the problem 😁

Thanks

**Comment by barbhackk** [comment] 2021-11-27 08:25
Hello everyone, it's weird this morning I tried again and it works again without any modification ???

I continue my investigations.

**Comment by Simek** [comment] 2021-12-03 15:57
Hi @barbhackk, thank you for the report and proposing a workaround! 👍 

It looks like this issue has been fixed in PR listed below:
* #15394

Please reopen this, or create new issue, when you can reproduce the problem after the new version (which will include the fix) will be released:
* https://github.com/expo/expo/blob/master/packages/expo-barcode-scanner/CHANGELOG.md

**Closed by Simek** 2021-12-03 15:57 UTC
Labels: needs review
