### ISSUE TITLE
barCodeScanner detects barcode when there's nothing to scan

### ISSUE THREAD

**Issue by ludwig-adoria** [expo/expo#9103] opened 2020-07-06 11:49 UTC
## 🐛 Bug Report
Bug on **barCodeScanner**

### Summary :
The barCodeScanner detects barcode when there's nothing to scan. 
it happens with expo-barcode-scanner or expo-camera.

![Screenshot_20200706-133247_Expo](https://user-images.githubusercontent.com/52496289/86589877-c2a3d700-bf8e-11ea-94b0-00bcd371f0e5.jpg)

### Environment
tested on two devices with android 10 ( Samsung SM-T860 & Xiamo Mi 8)
```
  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.4 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.0.6 => 4.3.9 
    npmGlobalPackages:
      expo-cli: 3.21.13
```

### Reproducible Demo
https://snack.expo.io/@lvantours/vengeful-crackers
 
### Steps to Reproduce
- wait 3 sec to 5 minutes and onBarCodeScanned will be trigger

### Expected Behavior vs Actual Behavior
- onBarCodeScanned should be invoke only when there is something to scan

**Comment by byCedric** [comment] 2020-07-06 14:36
Hi @ludwig-adoria, thanks for the issue report. Unfortunately, I don't see any `onBarCodeScanned` handler in the reproducible demo. And when I test it manually, I can't reproduce this. Could you update that with your handler?

**Comment by ludwig-adoria** [comment] 2020-07-06 14:56
Snack updated  => https://snack.expo.io/@lvantours/vengeful-crackers ! Sorry I failed with my snack Copy/Paster 😅.

**Comment by ludwig-adoria** [comment] 2020-07-06 14:59
thanks @byCedric . 
It's can take several minutes to reproduce but it's happen. Just need to play a little bit with real EAN code / dismiss the Alert and tap on Scan Again....

![Screenshot_20200706-165712_Expo](https://user-images.githubusercontent.com/52496289/86607646-d01a8a80-bfa9-11ea-8626-69a53b177f8f.jpg)

**Comment by brentvatne** [comment] 2020-07-16 00:40
we can't reproduce this. if you scan a bar code and then press "tap to scan again" and just put your phone down on your desk it never alerts about a new barcode being scanned. i wonder if maybe you have a barcode somewhere around your desk that you don't notice and occasionally it gets picked up?

i'm not saying that this isn't happening to you, but there isn't anything we can do based on this issue, so i'm going to close it. if you would like to dig into it further, i'd suggest installing the library in a bare project and trying to find the root cause.

**Closed by brentvatne** 2020-07-16 00:40 UTC
Labels: BarCodeScanner, Camera, status: needs more info
