### ISSUE TITLE
Images not loading on iOS using eas update

### ISSUE THREAD

**Issue by james-propaganda3** [expo/expo#18691] opened 2022-08-17 17:30 UTC
### Build/Submit details page URL

https://expo.dev/accounts/james_p3/projects/image-app

### Summary

I'm able to load images and view them in app while developing locally but updates within Expo Go do not display the images on iOS.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.6.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.7 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
    npmGlobalPackages:
      eas-cli: 0.58.0
      expo-cli: 6.0.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I have a repo that displays the issue here: https://github.com/james-propaganda3/image-app

Steps to reproduce:
1. run `expo start` and view the two green star images in the local app
2. run `eas update` and view the update within Expo Go, the stars are visible on Android but not iOS (I'm currently on iOS 15.5)

**Comment by alexlukelevy** [comment] 2022-08-18 16:54
I'm having the exact same issue. I noticed an error being thrown due to the images failing the MD5 check when downloading from the Expo CDN.

**Comment by brentvatne** [comment] 2022-08-18 17:23
@james-propaganda3 - did you possibly forget to push a commit to your reproducible example? there are no green star images in it, it's a blank new app: https://github.com/james-propaganda3/image-app/blob/master/App.js

**Comment by james-propaganda3** [comment] 2022-08-18 17:50
@brentvatne - oops! Yeah, I didn't realize I hadn't actually pushed the commit with my edits. Repo is updated now: https://github.com/james-propaganda3/image-app

**Comment by douglowder** [comment] 2022-08-19 19:33
@james-propaganda3 I'll have a look at this today. I am trying out your project locally to see if I can reproduce the issue.

**Comment by dleunig** [comment] 2022-08-19 20:22
Hey guys. I've the same issue. With Expo start everything looks fine but when I "publish" my app using eas update no images e.g. splash screen or images used in components are shown. How can I handle this issue?

**Comment by douglowder** [comment] 2022-08-19 20:37
@james-propaganda3 I am not able to reproduce the issue on an iOS device. I do see the star image on an iOS device after running `eas update`.

See my fork of your repo at https://github.com/douglowder/image-app

**Comment by douglowder** [comment] 2022-08-19 22:41
When following the right steps and pointing Expo Go on the device to the EAS update QR code, the problem does reproduce reliably. We will investigate this.

**Comment by brentvatne** [comment] 2022-08-26 23:05
this is resolved in the latest version of expo go for ios

**Closed by brentvatne** 2022-08-26 23:05 UTC
Labels: Updates, Issue accepted, SDK 46

**Comment by james-propaganda3** [comment] 2022-09-09 18:37
@brentvatne I had to transition my project to the bare workflow and I ran into this issue again on builds within testflight from eas build. Let me know if I need to provide more details

**Comment by brentvatne** [comment] 2022-09-19 20:43
@james-propaganda3 - can you share a link to your build? did you get a warning about your metro config when running eas build?

**Comment by james-propaganda3** [comment] 2022-09-19 21:11
@brentvatne Here's the link to the [build](https://expo.dev/accounts/propaganda3/projects/kc-mavericks/builds/2d30076e-f738-42ff-8551-785463064631). I don't believe there was any warnings when I was running eas build a few days ago.  My metro.config.js uses the default config from expo/metro-config

**Comment by brentvatne** [comment] 2022-09-19 21:16
are you on our [discord](https://chat.expo.dev/)? could you shoot me a dm on there? i'm brentvatne

**Comment by james-propaganda3** [comment] 2022-09-19 21:54
just joined! dm'ing you now

**Comment by maximilian** [comment] 2022-10-05 20:49
Any luck with this? Currently having the same issue. I am importing an asset using `useAssets` which works perfectly when developing locally. When running `eas update` the asset comes up as "saving" but never actually loads on the app.

**Comment by engineerStuardo** [comment] 2022-10-11 16:08
hey @maximilian did you have any luck with this?? I'm also running in this issue

**Comment by MikSaint** [comment] 2023-10-09 21:35
Running into the same issue. Oct 9, 2023. :/

**Comment by loe-lobo** [comment] 2023-11-01 15:36
@MikSaint Did you get to resolve it? I'm also facing the same issue.

**Comment by hmdNetizen** [comment] 2023-11-16 11:53
Running into this same Issue on Nov 16, 2023

**Comment by daveblaq** [comment] 2023-12-07 22:20
Running the same issue on Dec. 7th, after bundling, splash screen and app icon is blank

**Comment by copper123** [comment] 2024-02-15 09:26
> @james-propaganda3 I am not able to reproduce the issue on an iOS device. I do see the star image on an iOS device after running `eas update`.
> 
> See my fork of your repo at https://github.com/douglowder/image-app
> 
> I ran `eas build --profile=previewdevice --platform=ios` from commit [douglowder/image-app@2ae5b87](https://github.com/douglowder/image-app/commit/2ae5b879ae317c6052612ac6c266c78e365a1d03)
> 
> I ran `eas update --branch=previewdevice --platform=ios` from commit [douglowder/image-app@ded1a62](https://github.com/douglowder/image-app/commit/ded1a629f4f249b2d7329e6a7ccc42741a677c27)
> 
> I'll try a slightly different series of steps to see if I can repro the issue in Expo Go.

Hi Douglowder,

I follow the steps you provided above, but there is no image show up.
I check the deployment page of project in Expo, where the channel and branch with the name previewdevice, the the update is branch is not blank. the runtimeversion is 1.0.0 in app.json and in deployment page.
My test device is android, and I change the platform in your example to android.
If anything I forget to take care? Thanks for your help.

**Comment by copper123** [comment] 2024-02-15 09:58
> @james-propaganda3 I am not able to reproduce the issue on an iOS device. I do see the star image on an iOS device after running `eas update`.
> 
> See my fork of your repo at https://github.com/douglowder/image-app
> 
> I ran `eas build --profile=previewdevice --platform=ios` from commit [douglowder/image-app@2ae5b87](https://github.com/douglowder/image-app/commit/2ae5b879ae317c6052612ac6c266c78e365a1d03)
> 
> I ran `eas update --branch=previewdevice --platform=ios` from commit [douglowder/image-app@ded1a62](https://github.com/douglowder/image-app/commit/ded1a629f4f249b2d7329e6a7ccc42741a677c27)
> 
> I'll try a slightly different series of steps to see if I can repro the issue in Expo Go.

Hi Douglowder,

I follow the steps you provided above, but there is no image show up.
I check the deployment page of project in Expo, where the channel and branch with the same name as "previewdevice", and the update in branch is not blank. The runtimeversion is 1.0.0 in app.json and in deployment page.
My test device is android, and I change the platform in your example to android.
the dependencies in package.json as below
  "dependencies": {
    "expo": "^49.0.22",
    "expo-status-bar": "~1.6.0",
    "expo-updates": "^0.18.19",
    "react": "18.2.0",
    "react-native": "0.72.6"
  }, 

If anything I forget to take care? Thanks for your help.
