### ISSUE TITLE
Web Build Error: /home/ubuntu/environment/node_modules/@aws-amplify/api/node_modules/graphql/index.mjs 49:0-53:205 Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by rodhoff** [expo/expo#6238] opened 2019-11-12 01:05 UTC
### Environment

  Expo CLI 3.4.1 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.4.1

iOS, Android and Web Client, and this issue is basically for the Web client.

### Steps to Reproduce

While running the project with the "w" mode (web), it seems to build very quickly, but at the end triggers an error which seems to be related to Aws-Amplify:

 web  Failed to compile.
/home/ubuntu/environment/node_modules/@aws-amplify/api/node_modules/graphql/index.mjs 49:0-53:205
Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available)

### Expected Behavior

As it works fine on running the same build on an Android emulator, I would expect it would run the same on the web.

### Actual Behavior

After the web build, it actually shows the components on the screen for a brief moment, but then it stops and shows a "failure" page with the error:

/home/ubuntu/environment/node_modules/@aws-amplify/api/node_modules/graphql/index.mjs 49:0-53:205 Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available)

### Reproducible Demo
[src.zip](https://github.com/expo/expo/files/3833838/src.zip)

**Comment by cruzach** [comment] 2019-11-12 15:43
duplicate of https://github.com/expo/expo-cli/issues/1167

**Closed by cruzach** 2019-11-12 15:43 UTC
Labels: bug
