### ISSUE TITLE
expo-application's getIosIdForVendorAsync, androidId is this like device id?

### ISSUE THREAD

**Issue by yoojeen126** [expo/expo#6398] opened 2019-11-28 06:28 UTC
I want to check Identify device when login. 
But expo not supported device_id like react-native-device-info.
I saw expo-application support ios's getIosIdForVendorAsync, and android's androidId.
And checked get id on log.
Is this will unique id even i reinstalled app then same it?

**Comment by cruzach** [comment] 2019-12-02 21:24
Closing this since it's not a bug report. Questions like this are better off posted on our [forums](https://forums.expo.io/)

The id from `getIosIdForVendorAsync`can change if all apps from the current app's vendor have been uninstalled

The `androidId` can change if a factory reset is performed on the device or if an APK signing key changes

The reasons for not including a device ID that tracks across all installations no matter what are laid out in [this issue](https://github.com/expo/expo/issues/825)

**Closed by cruzach** 2019-12-02 21:24 UTC
