### ISSUE TITLE
FirebaseAnalytics not working with flavours (bare)

### ISSUE THREAD

**Issue by Acetyld** [expo/expo#10163] opened 2020-09-12 13:28 UTC
### Summary of Issue 
So we are using flavours to make different variants of our app.
Firebase connection seems to work well
`I/FirebaseInitProvider: FirebaseApp initialization successful`
We put the the google-services.json inside the src/flavor
![afbeelding](https://user-images.githubusercontent.com/55088242/92996458-01fd1f80-f50c-11ea-893b-e0812f09e564.png)

But analytics not working. Debugview stays empty.
Also used:
` adb shell setprop debug.firebase.analytics.app nl.dactec.coffindancesoundboard`

No errors in the logcat. Just nothing happening
Using this code:
```
await Analytics.logEvent('ButtonTapped', {
      name: 'settings',
      screen: 'profile',
      purpose: 'Opens the internal settings',
    }).catch((e)=>{console.log(e,'WERKT NIE')}).then((r)=>console.log(r,'WERKT '));
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 3.27.4 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.0
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ^38.0.10 => 38.0.10
      react: 16.13.1 => 16.13.1
      react-native: 0.63.2 => 0.63.2
    Expo Workflow: bare
```

### Reproducible Demo
This is very hard to show because we are running a bare workflow with 12 flavours. 
But it is a native project only using android.
 
### Steps to Reproduce

1. Create a native react project
2. Add react-native-unimodules and expo and install firebase & analytics (ofcourse connect firebase etc..)
3. Create different flavours in android studio
4. Launch a flavour and test the .logEvent and check the debug view
5. also do: adb shell setprop debug.firebase.analytics.app nl.dactec.coffindancesoundboard


### Expected Behavior vs Actual Behavior

Events should be showing inside the debugView in firebase.

**Comment by IjzerenHein** [comment] 2020-10-26 11:12
It looks like you have already found the cause of this problem.
https://github.com/invertase/react-native-firebase/issues/4249#issuecomment-692333533

Therefore closing :)

**Closed by IjzerenHein** 2020-10-26 11:12 UTC
Labels: Android, FirebaseAnalytics, Issue needs review
