### ISSUE TITLE
IAP – purchaseItemAsync() Never resolves if transaction did not finish

### ISSUE THREAD

**Issue by saeho** [expo/expo#13498] opened 2021-07-05 22:12 UTC
### Summary

Similar to (but different from) issue #11294 

If purchaseItemAsync() is called but if the transaction isn't completed properly with a finishTransactionAsync() call; then the next purchaseItemAsync() call never resolves.

I know finishTransactionAsync() should always be done, but this could happen if server was down at the time of purchase or if something unexpected happened.

In these cases, the next time the user refreshes the app, (or hot refreshes in development), purchaseItemAsync() will not work, presumably because the user has already paid for the product without fulfillment (because the message I get is that this product has already been purchased).

At this point, there is no event handler event and the promise never resolves, making it impossible to make another API call.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

n/a

### Reproducible demo or steps to reproduce from a blank project

n/a

**Comment by cruzach** [comment] 2021-08-03 21:18
If you never call `finishTransactionAsync` for a purchase, it remains in the payment queue and you'll continue to receive events about it via `InAppPurchases.setPurchaseListener`, so you should be taking action (aka calling `finishTransactionAsync`) from there

Closing this since it just seems to be a question, not a bug report (no reproducible demo)

**Closed by cruzach** 2021-08-03 21:18 UTC
Labels: needs review
