### ISSUE TITLE
[expo-updates] Some Bare Android Apps Show Blank Screen on Startup After "expo publish"

### ISSUE THREAD

**Issue by caesar4321** [expo/expo#8480] opened 2020-05-26 00:27 UTC
## 🐛 Bug Report

expo-updates only shows blank screen after "expo publish" commanded executed. When there is no published updates, it is working fine. Calling Updates.reloadasync() also works if it is not executed during the react-native initialization process.

### Environment

W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.checkbox.ReactCheckBoxManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class org.reactnative.maskedview.RNCMaskedViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.swmansion.gesturehandler.react.RNGestureHandlerRootViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.swmansion.gesturehandler.react.RNGestureHandlerButtonViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.th3rdwave.safeareacontext.SafeAreaViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.swmansion.rnscreens.ScreenContainerViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.swmansion.rnscreens.ScreenViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.swmansion.rnscreens.ScreenStackViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.swmansion.rnscreens.ScreenStackHeaderConfigViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.swmansion.rnscreens.ScreenStackHeaderSubviewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class com.reactnativecommunity.webview.RNCWebViewManager
W/unknown:ViewManagerPropertyUpdater( 5915): Could not find generated setter for class org.unimodules.adapters.react.views.SimpleViewManagerAdapter
D/SoLoader( 5915): About to load: libyoga.so
D/SoLoader( 5915): libyoga.so not found on /data/data/com.Koolpeace.KoreanDating/lib-main
D/SoLoader( 5915): libyoga.so found on /data/app/com.Koolpeace.KoreanDating-1/lib/x86
D/SoLoader( 5915): Not resolving dependencies for libyoga.so
D/SoLoader( 5915): Loaded: libyoga.so
D/SoLoader( 5915): init exiting
I/art     ( 5915): Background sticky concurrent mark sweep GC freed 41924(2MB) AllocSpace objects, 1(16KB) LOS objects, 15% free, 11MB/13MB, paused 8.302ms total 42.137ms
D/SoLoader( 5915): About to load: libreactnativeblob.so
D/SoLoader( 5915): libreactnativeblob.so not found on /data/data/com.Koolpeace.KoreanDating/lib-main
D/SoLoader( 5915): libreactnativeblob.so found on /data/app/com.Koolpeace.KoreanDating-1/lib/x86
D/SoLoader( 5915): Not resolving dependencies for libreactnativeblob.so
W/linker  ( 5915): libreactnativeblob.so: unused DT entry: type 0x6ffffffe arg 0x3030
W/linker  ( 5915): libreactnativeblob.so: unused DT entry: type 0x6fffffff arg 0x2
D/SoLoader( 5915): Loaded: libreactnativeblob.so
I/ReactNativeJS( 5915): Running "main" with {"rootTag":1}
W/linker  ( 5915): libwebviewchromium.so: unused DT entry: type 0x6ffffef5 arg 0x4c34
W/linker  ( 5915): libwebviewchromium.so: unused DT entry: type 0x6ffffffe arg 0x4bd4
W/linker  ( 5915): libwebviewchromium.so: unused DT entry: type 0x6fffffff arg 0x3
I/WebViewFactory( 5915): Loading com.google.android.webview version 77.0.3865.92 (code 386509215)

Bare Android app, 5.1 Lollipop.

### Steps to Reproduce

```
const checkForExpoUpdate = async () => {
    if (Platform.OS != 'web') {
        const result = await Updates.checkForUpdateAsync();
        if (result.isAvailable) {
          await Updates.fetchUpdateAsync();
          await Updates.reloadAsync();
        }
    }
  };

useEffect(() => {
    async function loadResourcesAndDataAsync() {
      try {

        await Promise.all([
          checkForExpoUpdate(),
         ....
       finally {
            SplashScreen.hide();
       }
   }, []);
```

[command]
npx react-native run-android --variant=release
expo publish --release-channel test

### Expected Behavior

The bare Android app should start.

### Actual Behavior

Only blank white screen appears and nothing happens. If I close the app and re-open, it works.

### Reproducible Demo

It has to be published every single time to reproduce this bug.

### What happens if you skip this step?

First time users will only see blank screen and most of them will uninstall the app.

**Comment by esamelson** [comment] 2020-05-27 18:44
Hello -- sorry you're having trouble with this! 😞  This behavior does not happen with the blank template projects, and the code snippet you've provided is unfortunately not enough to reproduce the issue. Could you please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us narrow down the interactions that are causing issue? I know reproducing this requires publishing, so a complete, precise set of steps to follow, or a simple project in a GH repo would suffice. It is hard for us to help out effectively without this -- thank you!!

**Comment by caesar4321** [comment] 2020-05-28 01:12
I think I found the cause.

It seems like Updates.reloadAsync() does not completely restart the javascript bundle on Android 5.1 Lollipop.

We had a logic of 
```
if (!isLoadingComplete) {
    return null;
  } else {
// render App
}
```

And isLoadingComplete was set at
```
useEffect(() => {
async function loadResourcesAndDataAsync() {
      try {

        await Promise.all([
          checkForExpoUpdate(),
         ....
} finally {
        setLoadingComplete(true);
        if (Platform.OS != 'web')
          SplashScreen.hide();
      }
}
loadResourcesAndDataAsync();
}, []);
```

setLoadingComplete(true) at finally was interrupted and thereby, the app showed a blank screen.

**Comment by esamelson** [comment] 2020-05-28 01:21
Hey @caesar4321 - glad you found the issue! Could you explain what you mean by "does not completely restart the javascript bundle" on Android 5.1?

Also, be aware that on any Android OS, the bundle may be restarted -- meaning all of your JavaScript will completely reload and restart from the beginning -- at any point after `Updates.reloadAsync` is called, so you should not rely on any logic after `Updates.reloadAsync` ever being executed.

**Comment by caesar4321** [comment] 2020-05-28 01:33
@esamelson Thank you so much for lightening speed reply.

Yes, we expected that after anything `await Updates.reloadAsync` would be ignored and the Javascript bundle will restart from the beginning. But it wasn't the case for Android 5.1. We track the startups of the app at `finally` and can see that even after `await Updates.reloadAsync`, remaining code was executed.  In other words, "AppStarted" event is recorded twice.

So here is how it looks:

```
const checkForExpoUpdate = async () => {
    if (Platform.OS != 'web') {
        const result = await Updates.checkForUpdateAsync();
        if (result.isAvailable) {
          await Updates.fetchUpdateAsync();
          await Updates.reloadAsync();
        }
    }
  };

  useEffect(() => {
    async function loadResourcesAndDataAsync() {
      try {

        await Promise.all([
          checkForExpoUpdate(),
          ...
        ]);
      } catch (e) {
        // We might want to provide this error information to an error reporting service
        console.warn(e);
      } finally {
        setLoadingComplete(true);
        isMountedRef.current = true;
        logEvent({
          eventName: 'AppStarted',
        });
        if (Platform.OS != 'web')
          SplashScreen.hide();
      }
    }

    loadResourcesAndDataAsync();
```

And because `isLoadingComplete` was not set as true, the app appears to be a blank screen.

**Comment by esamelson** [comment] 2020-05-28 02:37
Gotcha, thanks, that makes sense. How `reloadAsync` works behind the scenes is once it verifies that it can reload the app, it sends a message to the native modules thread to resolve the promise and then immediately posts a task to the main thread to reload the React Native app. Therefore, whether or not any other JS code is executed between the promise resolving and the application reloading is entirely dependent on the OS and the amount of other work on these two queues at the specific moment. So it's not safe to make any assumptions about whether or not JS code after `reloadAsync` will be executed.

I'll update the docs to be clearer around this, since I see it was a point of confusion. But as it seems like you've found the cause of the issue in your application code, I'm going to go ahead and close this issue. (Feel free to ping me if it's not resolved and we can reopen!)

**Closed by esamelson** 2020-05-28 02:37 UTC
Labels: Bare Workflow, Updates, needs repro, project: android-runtime
