### ISSUE TITLE
Cant receive a notification while the device is locked and GPS background task is running

### ISSUE THREAD

**Issue by abdullah-abunada** [expo/expo#10111] opened 2020-09-09 11:37 UTC
### Summary of Issue 
Cant receive a notification after a few minutes when the device is locked and the GPS background task is running

### Steps to Reproduce
1) setup notification listener in the home screen.
2) define a background task to track GPS location.
3) active GPS task
4) lock your phone and wait for a few minutes (10m)
5) send notification using the expo tool

### Expected Behavior vs Actual Behavior
Expected Behavior: The Android device receives the notification.
Actual Behavior: The Android device can't receive the notification after a few minutes after locking the screen.

**Comment by abdullah-abunada** [comment] 2020-09-10 17:33
#9037 is not fixed until now?

**Comment by cruzach** [comment] 2020-09-14 16:21
It will be fixed with SDK 39, which we plan to release very soon (probably within the next week or two, pending iOS 14). You can, however, access the fix now and test it in a bare workflow app

Going to close this as a duplicate of https://github.com/expo/expo/issues/9037

**Closed by cruzach** 2020-09-14 16:21 UTC
Labels: Android, Issue needs review, Location, TaskManager
