### ISSUE TITLE
Expo 2.2.0 on Android, ScrollView: Unsupported top level event "topScrollBeginDrag" dispatched 

### ISSUE THREAD

**Issue by xiaocjin** [expo/expo#1118] opened 2017-12-15 03:13 UTC
My app was working fine until I updated to Expo 2.2.0.  I try it on  Expo 2.1.2, it is fine.
Same problem: https://github.com/facebook/react-native/issues/16522
Expo 2.2.0 is still wrong

**Comment by zorobabel** [comment] 2017-12-15 06:01
Have the same issue and it's driving me crazy

![zxd](https://user-images.githubusercontent.com/12666007/34028622-53951046-e132-11e7-974c-36559cd378ec.png)

```javascript
<View style={styles.rect.container}>
    <FlatList
        data={this.state.data}
        extraData={this.state}
        horizontal={true}
        ItemSeparatorComponent={this.renderSeparator}
        keyExtractor={this.keyExtractor}
        renderItem={this.renderItem}
        showsHorizontalScrollIndicator={false}
        style={styles.general.list}
    />
</View>
```
My app was working fine until I [updated](https://blog.expo.io/expo-sdk-v23-0-0-is-now-available-be0a8c655414?source=collection_home---6------4----------------) Expo and its dependencies.

**Comment by zorobabel** [comment] 2017-12-15 11:59
The issue is gone after [update](https://blog.expo.io/expo-sdk-v24-0-0-is-now-available-bfcac3b50d51) Expo.

@xiaocjin I think you have to do the same

**Comment by terribleben** [comment] 2017-12-18 21:16
Continuing to track this unless we're certain we have the fix in our RN fork. Not clear from the above info whether or not we have the fix.

**Comment by ide** [comment] 2017-12-19 01:37
The version of the Expo Client (ex: 2.2.0) affects less than the SDK version. If this isn't working with SDK 24 (based on RN 0.51) I suspect the bug is still in React Native somewhere.

**Comment by ide** [comment] 2018-01-24 01:28
Is this issue still happening with SDK 25 (RN 0.52)? If we don't hear about any reports of this happening with SDK 25 for awhile, we'll close this out.

**Comment by loganwedwards** [comment] 2018-01-25 19:20
I can confirm I am seeing this with SDK 25 via iOS simulator (have not tried Android yet) 
<img width="280" alt="screenshot 2018-01-25 14 19 40" src="https://user-images.githubusercontent.com/2034000/35407702-cf872c0c-01da-11e8-8d37-0e179fba6d84.png">

**Comment by ide** [comment] 2018-01-25 19:22
This issue is for topScrollBeginDrag on Android -- that screenshot shows topTouchStart on iOS and is likely unrelated to the fix that went into RN 0.52.

**Comment by jesseruder** [comment] 2018-02-07 05:03
It sounds like the initial issue here is fixed. @loganwedwards that seems like a different issue. Can you see if anyone else has run into that and if not open a new issue?

**Closed by jesseruder** 2018-02-07 05:03 UTC
Labels: project: android-runtime, project: react-native

**Comment by loganwedwards** [comment] 2018-02-08 13:45
@jesseruder For me, this issue was a red herring. If you can believe it, the error went away after resolving a non-conforming `app.json`.
