### ISSUE TITLE
expo-image-picker 14.5.0 crashes when taking a picture

### ISSUE THREAD

**Issue by kriit24** [expo/expo#26437] opened 2024-01-16 05:04 UTC
### Minimal reproducible example

https://github.com/kriit24/expo-image-picker-example/blob/master/README.md

### Summary

click on button to start camera
click "take picture"
click ok
one out of three the will restart

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: Windows 10 10.0.19045
Binaries:
Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: AI-231.9392.1.2311.11255304
npmPackages:
expo: ^49.0.0 => 49.0.16
react: 18.2.0 => 18.2.0
react-native: 0.72.6 => 0.72.6
Expo Workflow: managed

**Comment by alanjhughes** [comment] 2024-01-16 09:08
Hi @kriit24 - I've tried your repro but the issue does not reproduce for me. I'm taking a photo and displaying it in the UI. It works every time. Are you seeing this on a specific device?

**Comment by kriit24** [comment] 2024-01-17 03:49
Hi.

My device is Samsung A10. Where this happens in every app what uses expo-image-picker.

DEVICE
Model Name: Galaxy A10
Model number: SM-A105FN/DS

SOFTWARE
One UI: 3.1
Android: 11
Kernel: 4.4.177-21848546

**Comment by alanjhughes** [comment] 2024-01-17 06:20
@kriit24 the device and OS version matter to be able to reproduce the problem.

**Comment by kriit24** [comment] 2024-01-17 06:26
so what u need additionally from me or maybe u can help me to debug by myself (somehow)?

**Comment by alanjhughes** [comment] 2024-01-17 06:33
The native error logs ideally. Are you using expo go or a development client? If you could run the app with Android studio, we could get the stacktrace when the crash occurs. This would be very helpful.

**Comment by kriit24** [comment] 2024-01-17 08:11
im running expo go. how i run the app with android studio ?

**Comment by alanjhughes** [comment] 2024-01-17 09:43
The recommended version for `expo-image-picker` on SDK 49 is `14.3.2`. Can you run `npx expo install --fix` to fix the dependency. To run the app from android studio you can follow [these](https://docs.expo.dev/workflow/prebuild/) docs but try fixing the dependencies first.

**Comment by kriit24** [comment] 2024-01-18 03:23
after "npx expo install --fix" - it takes 5-10 pictures and then crashes, earlier was 3-5 pictures

**Comment by alanjhughes** [comment] 2024-01-18 06:38
@kriit24 ok then, can you follow the documentation for prebuild, run the app with Android studio and post the stacktrace when the crash occurs?

**Comment by kriit24** [comment] 2024-01-18 07:54
ill try, but it take time, i let u know

**Comment by brentvatne** [comment] 2024-01-20 02:19
going to close this for now because it's not actionable for us. happy to re-open this issue once we have a reproducible example or some logs that we can act on! :)

**Closed by brentvatne** 2024-01-20 02:19 UTC
Labels: needs more info

**Comment by Vanclief** [comment] 2024-01-28 13:58
I know this is closed, just want to report that I am experiencing the same issue with `expo-image-picker 14.3.2` on Expo 49.
Will post if I get more information on a workaround or a reproducible example.
