### ISSUE TITLE
[expo-barcode-scanner]　 undetectable characters

### ISSUE THREAD

**Issue by sukodai** [expo/expo#22128] opened 2023-04-14 03:49 UTC
### Minimal reproducible example

https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/#supported-formats

### Summary

Does not recognize the following characters.

1: 「ｱ～ﾝｧｨｩｪｫｬｭｮｯﾞﾟｰ｡｢｣､･」 <-- half-width kana
2:「ａＡアイあい亜伊」 <-- 2Byte character

The following libraries are recognized.

https://github.com/moaazsidat/react-native-qrcode-scanner

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nodenv/versions/16.15.0/bin/node
      Yarn: 1.22.19 - ~/.nodenv/versions/16.15.0/bin/yarn
      npm: 8.12.1 - ~/.nodenv/versions/16.15.0/bin/npm
      Watchman: 2022.05.16.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 5.5.1
    Expo Workflow: bare

**Comment by sukodai** [comment] 2023-04-14 03:50
Text QR Code

https://www.cman.jp/QRcode/faq/qa2_character_type/

**Comment by s-kuniyoshi** [comment] 2023-05-12 05:25
oh!I've been having trouble reading QR codes on Android for a while now.
I tried using Arabic, Korean, Thai, and they seem to be scanned successfully. However, when I try to scan a QR code in Japanese, the onBarCodeScanned event doesn't fire.

**Comment by vonovak** [comment] 2024-08-26 10:53
Hello and thanks for reporting,
because the issue is old and because barcode scanning is now part of the camera package, I'm going to close it.
Feel free to create a new issue (please follow the issue template) if the problem persists.
Thank you 🙂

**Closed by vonovak** 2024-08-26 10:53 UTC
Labels: Android, BarCodeScanner, Issue accepted
