### ISSUE TITLE
IllegalArgumentException and App Launch Issues with Expo Router on Android (New Architecture)

### ISSUE THREAD

**Issue by bahadiraraz** [expo/expo#30807] opened 2024-08-04 14:08 UTC
### Minimal reproducible example

https://github.com/bahadiraraz/expo-bug.git

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I'm experiencing critical problems in my React Native application after migrating to the new architecture with Expo Router on Android. These issues were not present in the old architecture. The main problems are:

1. App crashes during tab navigation:
   The app crashes both in production and development modes when switching between tabs. The error I'm encountering is:

   **IllegalArgumentException: androidx.fragment.app.FragmentStateManager in createView**

   This crash occurs consistently during tab navigation.

2. App launch issues after installation:
   Users are unable to open the app from the device's main menu after installation. The app only launches when opened directly from the Google Play Store using the "Open" button.

These problems are significantly impacting the user experience and the app's functionality. They didn't exist in the old architecture, suggesting that the migration to the new architecture has introduced these issues.

IllegalArgumentException: androidx.fragment.app.FragmentStateManager in createView

https://github.com/user-attachments/assets/fec4c5a8-da9c-4e79-9555-e86641cfe549

![image](https://github.com/user-attachments/assets/3ce2baf1-6da2-434c-84ca-3163977f0884)
![image](https://github.com/user-attachments/assets/ae94cdb5-07fa-44a2-9062-dea2633b361f)

### Environment

```  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
      Watchman: 2024.06.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.18.1 => 0.18.4 
      expo: ^51.0.24 => 51.0.24 
      expo-router: ~3.5.18 => 3.5.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.1
    Expo Workflow: bare
```

**Comment by bahadiraraz** [comment] 2024-08-05 10:09
When setting `detachInactiveScreens=false` in the Expo router tabs, the crashing issue when navigating between pages is resolved. However, the problem where the app can only be opened from Google Play still persists.

**Comment by Adil-U** [comment] 2024-08-05 15:41
same problem, but im not using expo-router

**Comment by Kudo** [comment] 2024-08-06 03:43
hi @bahadiraraz! thanks for sharing this problem. we'd love to solve the new architecture issue. i'm trying to reproduce the problem based on your repro. switching tabs couple times and didn't come across the error. could you share your steps for your repro?

**Comment by sejoDjoseon** [comment] 2024-08-06 08:54
Same problem here. Not using expo-router neither. It happens with apk build but not in emulator.

**Comment by Adil-U** [comment] 2024-08-06 09:00
> Same problem here. Not using expo-router neither. It happens with apk build but not in emulator.

I just do some research, can u send me ur version of expo-notifications?

**Comment by Adil-U** [comment] 2024-08-06 09:07
> Same problem here. Not using expo-router neither. It happens with apk build but not in emulator.

the problem was only in Xiaomi phones
EXPO Response: Fix is published in expo-notifications@0.28.15.

**Comment by bayramcinar** [comment] 2024-08-06 09:21
![WhatsApp Image 2024-08-06 at 11 47 28 (1)](https://github.com/user-attachments/assets/5a9c39b1-38f3-40e0-aa8b-7bfc3b3d06c0)
same problem how can I solve it

**Comment by sejoDjoseon** [comment] 2024-08-06 09:38
> > Same problem here. Not using expo-router neither. It happens with apk build but not in emulator.
> 
> I just do some research, can u send me ur version of expo-notifications?

"expo-notifications": "~0.28.14", but I just realised there's a new one.

**Comment by bayramcinar** [comment] 2024-08-06 09:53
my problem is the app is just opening from play store not from main menu just like @bahadiraraz problem

**Comment by bayramcinar** [comment] 2024-08-06 10:05
@bahadiraraz  i could not find the solution. What should I do

**Comment by bahadiraraz** [comment] 2024-08-06 10:11
> @bahadiraraz  i could not find the solution. What should I do

I couldn't find a solution either. Could you send me the `package.json` file you are using so we can investigate the issue by comparing the common libraries? I'm researching it, but this problem is really baffling.

**Comment by bayramcinar** [comment] 2024-08-06 10:13
`{
  "name": "movieapp",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo-google-fonts/poppins": "^0.2.3",
    "@expo/config-plugins": "~8.0.0",
    "@expo/prebuild-config": "~7.0.0",
    "@expo/vector-icons": "^14.0.2",
    "@firebase/app": "^0.10.5",
    "@firebase/auth": "^1.7.4",
    "@firebase/messaging": "^0.12.10",
    "@google/generative-ai": "^0.15.0",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-firebase/app": "^20.3.0",
    "@react-native-firebase/messaging": "^20.3.0",
    "@react-navigation/bottom-tabs": "^6.6.0",
    "@react-navigation/material-bottom-tabs": "^6.2.28",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.3.29",
    "aws-sdk": "^2.1663.0",
    "axios": "^1.7.2",
    "date-fns": "^3.6.0",
    "expo": "~51.0.20",
    "expo-av": "~14.0.6",
    "expo-build-properties": "~0.12.4",
    "expo-dev-client": "~4.0.21",
    "expo-font": "~12.0.9",
    "expo-image-picker": "~15.0.7",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-updates": "~0.25.21",
    "firebase": "^10.12.4",
    "google-auth-library": "^9.11.0",
    "nativewind": "^2.0.11",
    "openai": "^4.53.0",
    "react": "18.2.0",
    "react-native": "^0.74.2",
    "react-native-dotenv": "^3.4.11",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-image-base64": "^0.1.4",
    "react-native-image-picker": "^7.1.2",
    "react-native-modal": "^13.0.1",
    "react-native-openai": "^0.6.1",
    "react-native-paper": "^5.12.3",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-vector-icons": "^10.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.24.0",
    "tailwindcss": "^3.3.2"
  },
  "private": true
}
`


this is my package.json I have not a problem like this about 2 days ago but now. I think I changed some versions of the dependencies but which ones idk

**Comment by bayramcinar** [comment] 2024-08-06 10:14
`{
  "name": "movieapp",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo-google-fonts/poppins": "^0.2.3",
    "@expo/config-plugins": "~8.0.0",
    "@expo/prebuild-config": "~7.0.0",
    "@expo/vector-icons": "^14.0.2",
    "@firebase/app": "^0.10.5",
    "@firebase/auth": "^1.7.4",
    "@firebase/messaging": "^0.12.10",
    "@google/generative-ai": "^0.15.0",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-firebase/app": "^20.3.0",
    "@react-native-firebase/messaging": "^20.3.0",
    "@react-navigation/bottom-tabs": "^6.6.0",
    "@react-navigation/material-bottom-tabs": "^6.2.28",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.3.29",
    "aws-sdk": "^2.1663.0",
    "axios": "^1.7.2",
    "date-fns": "^3.6.0",
    "expo": "~51.0.20",
    "expo-av": "~14.0.6",
    "expo-build-properties": "~0.12.4",
    "expo-dev-client": "~4.0.21",
    "expo-font": "~12.0.9",
    "expo-image-picker": "~15.0.7",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-updates": "~0.25.21",
    "firebase": "^10.12.4",
    "google-auth-library": "^9.11.0",
    "nativewind": "^2.0.11",
    "openai": "^4.53.0",
    "react": "18.2.0",
    "react-native": "^0.74.2",
    "react-native-dotenv": "^3.4.11",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-image-base64": "^0.1.4",
    "react-native-image-picker": "^7.1.2",
    "react-native-modal": "^13.0.1",
    "react-native-openai": "^0.6.1",
    "react-native-paper": "^5.12.3",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-vector-icons": "^10.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.24.0",
    "tailwindcss": "^3.3.2"
  },
  "private": true
}
`


this is my package.json I have not a problem like this about 2 days ago but now. I think I changed some versions of the dependencies but which ones idk

**Comment by sejoDjoseon** [comment] 2024-08-06 10:49
I've update expo-notifications to 0.28.14 and the problem has gone, at least in the apk build. Btw try to run `npx expo install --check` to upgrade to last recommended versions.

**Comment by Adil-U** [comment] 2024-08-06 11:50
Expo just fix the problem in last package update "expo-notifications": "^0.28.15"

**Comment by vonovak** [comment] 2024-10-07 16:02
@bahadiraraz is this issue resolved since you posted it, or what is the status?
Thank you 🙂

**Comment by bahadiraraz** [comment] 2024-10-07 16:06
@vonovak Thank you for following up. The notification issue was resolved with the update to `expo-notifications v0.28.15.` However, I'm still using `detachInactiveScreens=false` on Android as a workaround for the tab navigation crashes. I'm not certain if that underlying issue has been fully resolved yet

**Comment by imtyM** [comment] 2024-11-11 09:21
Hi guys, experiencing the same issue here. Solved with `detachInactiveScreens=false`.

Some extra info to reproduce: The tab that crashes also mounts a Stack navigator. When removed, the tab does not crash. Tested with `detachInactiveScreens=true`. Even an empty screen that just mounts the Stack navigator should crash.

**Comment by marklawlor** [comment] 2024-12-17 18:05
The originally reported issue should be fixed in SDK 52 and running `npx expo install --fix`. This includes the fixes the `expo-notifications` and the freezing issue in `react-native-screens`.

If your still experiencing these issues in SDK 52, please create a new issue

**Closed by marklawlor** 2024-12-17 18:05 UTC
Labels: needs review, Router
