### ISSUE TITLE
Monitor screen noise when taking picture from a phone?

### ISSUE THREAD

**Issue by lincdh** [expo/expo#12752] opened 2021-04-27 15:10 UTC
### Summary

Here is the picture I took from my phone camera:
![cameraCaptured](https://user-images.githubusercontent.com/21136244/116182629-d2232500-a746-11eb-9382-b98fec60c598.jpg)
It has a mixed gray color and waves of screen refreshes i think. Completely contrary to when holding volume + power buttons to screen capturing:

![Screen Shot 2021-04-27 at 10 58 32](https://user-images.githubusercontent.com/21136244/116183343-e0be0c00-a747-11eb-82b8-3c401ab021bc.png)

Is there anything i can do to improve the quality when taking pictures of monitor screen with camera?
Any help is really appreciated. Thanks!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### Environment

No data

### Reproducible demo or steps to reproduce from a blank project

Taking picture of monitor screen or phone screen

**Comment by cruzach** [comment] 2021-04-27 19:47
This is not a bug with the Expo SDK, it's a limitation of the native camera (unless your system camera app has noticeably better quality in the same scenario) so I'm going to close this issue.

**Closed by cruzach** 2021-04-27 19:47 UTC
Labels: needs review
