### ISSUE TITLE
Expo Client iOS freezes on app splash screen when loading project from lan

### ISSUE THREAD

**Issue by evilandfox** [expo/expo#1576] opened 2018-03-30 03:08 UTC
1. I updated expo cli to latest version
2. Then updated expo iOS client to latest version too
3. On expo cli I created new empty project and made `exp start --lan`
4. Then I sent link to my iOS by `exp send`
5. Then opened that link on iOS
6. Expo iOS begins loading project by showing splash screen...
7. And nothing happens after!

What am I doing wrong? (Windows 7 x64, iOS 11.2.5, node 8.9.1, Yarn 1.5.1)
update: all is OK on android
update 2: tested on another iOS device, same issue
<img src="https://user-images.githubusercontent.com/9137261/38122910-7bea0ea4-33f1-11e8-85b8-01bfaa9d8769.PNG" width="320" />

**Comment by terribleben** [comment] 2018-03-30 04:13
Hey there, sorry you're running into this. Does your packager log show that it's building your JS bundle?

**Comment by evilandfox** [comment] 2018-03-30 04:30
@terribleben hi) no, packager log doesn't show that. it only shows some yellow issues (like package version not correct etc). if i use android device instead iOS, all is OK.
I use latest SDK 26.0

**Comment by terribleben** [comment] 2018-03-30 06:00
Thanks for the info. I have not been able to reproduce this behavior. I'll continue to try to figure it out. It seems like either the iPhone can't contact your packager, or the packager isn't acknowledging the iPhone, for some reason.

Can you try these steps and let me know what happens?

1. `exp start --lan`, same as before
2. In a browser on your computer, open your project url followed by `/index.exp?sdkVersion=26.0.0`, you should see a json file

![image](https://user-images.githubusercontent.com/1316332/38126350-de2886d8-33a4-11e8-9548-009b0c6eac17.png)

3. Find the value for `bundleUrl` in that json file, it should be another lan url
4. Try opening that bundle url in your computer's browser

If you follow the above steps, does anything load in the browser? Does your packager log anything when you do that?

**Comment by evilandfox** [comment] 2018-03-30 06:38
After this steps browser begins loading page and packager logs `Building JavaScript bunlde [=....`
then building completes and browser shows js like:
```
var __DEV__=false,__BUNDLE_START_TIME__=this.nativePerformanceNow?nativePerformanceNow():Date.now(),process=this.process||{};process.env=process.env||{};process.env.NODE_ENV='production';
(function (global) {
...
```
I think the problem is in Expo iOS client or, maybe, in my iPhone

**Comment by spanmatej** [comment] 2018-03-30 09:04
I have the same issue as @evilandfox.

I have sent the app link through "exp send -s <phone number>" and opened it on my iPhone. All that is showing in the Expo app is a blank white screen. On Android, everything still works as expected.

 Followed the same procedure of opening the bundle url in the browser and received the same results.

**Comment by dev-fuad** [comment] 2018-03-30 10:05
I had the same issue with new Expo v26.0.0.
I solved it by removing all the spaces in path of my project
like:
~/New Project/new-project
to
~/New_Project/new-project

**Comment by ksesong** [comment] 2018-03-30 10:59
I had the same issue as well, and I solved it as well by removing any space contained in any enclosing directories (as @dev-fuad mentioned). Note that the javascript bundle building did not trigger when the folders had a space character, which may explain the white screen.

**Comment by evilandfox** [comment] 2018-03-30 13:04
@dev-fuad, @ksesong, I have no spaces in path string of project. Only one hyphen (-), other symbols are small latin letters. Anyway, why android device works well then?

**Comment by robertobrogi** [comment] 2018-03-30 14:12
i have the same problem... there is any news?

**Comment by YuriyMaksymets** [comment] 2018-03-30 15:46
Same issue for both `exp start --lan` and `exp start`. The last message I see in the terminal is `[exp] Dependency graph loaded.`.

**Comment by terribleben** [comment] 2018-03-30 15:51
Hey all, I've succeeded in reproducing the error. Here's what's going on:

1. Some error with the React Native packager happens before we can load your bundle
2. There is a bug in our code which never hides your splash screen in this case.

For #1, one possible cause is if the path to your project contains spaces. We found a bug where we are not properly encoding paths with spaces (sorry) and this leads to #1 happening.

So, for some people reading this issue, you may be unblocked by using a project path with no spaces, and making sure the packager doesn't display any errors when it starts.

However, there could be other causes of #1, so that advice won't work for everyone. I'm working on a fix for both #1 and #2 right now.

**Comment by terribleben** [comment] 2018-03-30 17:16
Hey everyone, please update to the newest version of `exp` (released less than an hour ago) and see if it fixes this issue for you.

This fix should help most people, but it may not unblock the issue for everyone. **If you have tried updating to the newest exp and are still seeing the same issue,** please post here with as much information as you can.

Additionally, we have a new iOS simulator build forthcoming, which should help address the issue for more people by displaying clearer error information. I will update this post when that becomes available.

**Comment by jacamera** [comment] 2018-03-30 17:46
Latest exp (51.1.0) fixed the issue for me and I didn't have any spaces in my path. Thanks so much for the quick fix!

**Comment by PrestonStahley** [comment] 2018-03-30 19:00
I have the same issue (app stuck at splash screen) after attempting to upgrade.

1. Followed all steps in the upgrade blog post
2. Upgraded exp to 51.1.0
3. Installed latest XDE
4. Sent link via SMS to iPhone

Windows 10 x64, iPhone X (iOS 11.3)

**Comment by nwactor** [comment] 2018-03-30 19:00
The issue seems to be the iOS app for me. With two iOS devices, one running expo app released yesterday, and one running the previous version (still has the scanner), I am able to open my app with the previous version but not the new one.

**Comment by PrestonStahley** [comment] 2018-03-30 20:24
Probably not related, but I've also started getting this error on XDE startup.

![image](https://user-images.githubusercontent.com/1296828/38152587-cd1973b2-3425-11e8-980e-dbec4fd1bc7b.png)

**Comment by PrestonStahley** [comment] 2018-03-30 22:59
Got it working!

XDE asked to upgrade to the latest version. I did that, removed my node_modules dir and re-ran npm install again. Opened my project in XDE, restarted the project. I'm now able to load over LAN on iphone and ipad in the new client!

**Comment by evilandfox** [comment] 2018-03-31 10:38
No all works! Thanks, @terribleben!

**Comment by xiaosheng-china** [comment] 2018-03-31 15:06
How to solve the problem of how to start my project without QR?
I don't know where I can enter the address

**Comment by oron11** [comment] 2018-04-01 17:06
I have the same problem.
I have iPhone 8 plus with latest iOS 11.3
Expo.client version 2.4.2 
And I can't update the app don't have an option in the Appstore.

**Comment by AdamJNavarro** [comment] 2018-04-01 17:09
Hey @oron11,

Version 2.4.2 is the most up-to-date version of the Client so you are good on that front. I'm thinking you may have gotten the client confused with exp which is what needs to be updated to help fix this issue. Can you update exp and make sure it's running version 51.4.0?

Thanks,

Adam

**Comment by oron11** [comment] 2018-04-01 17:16
Sorry Adam what do you mean by upgrading exp? I don't know what it is.
I followed this guide: https://facebook.github.io/react-native/docs/getting-started.html
Download at first Nodejs, And did the first commands in the cmd

**Comment by tamdao** [comment] 2018-04-02 04:52
I have the same issue with @oron11 . I can't update the version for Client on my iPhone 6. I see the app on appstore is 2.4.2 version and I can't add the project into my phone via barcode. Because the plus button doesn't appear

**Comment by gie3d** [comment] 2018-04-02 05:38
@tamdao It had been removed as to conform to the latest Apple Review Guidelines.

You may read more detail and how to work with it from the links below:
[](https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a)
[](https://blog.expo.io/expo-sdk-v26-0-0-is-now-available-2be6d9805b31)

**Comment by isunilapps** [comment] 2018-04-02 13:56
I too had same issue.. for detail description.. Please refer the below link

https://stackoverflow.com/questions/49612404/expo-version-2-4-2-version-app-running-issue-in-ios

**Comment by isunilapps** [comment] 2018-04-02 14:42
In terminal, Updated "exp" version with latest : 51.4.0
  `sudo npm i -g exp`

and then

`exp login`
`exp start`
`exp send -s <phone number with country code(+91) or mail>`
`In mobile, open the link that received through mail or mobile number`

> Reference

<img width="869" alt="screen_shot_2018-04-02_at_7_56_38_pm" src="https://user-images.githubusercontent.com/17312365/38200417-e4775c7a-36b1-11e8-9a6f-2c2f94ed1e61.png">

_Not sure for the first attempt expo app crashed but successfully opened for the 2nd time._

**Comment by terribleben** [comment] 2018-04-02 17:29
Hey there! I'm going to close this issue because we've had no further reports of the original problem. Thanks everyone for your patience last week.

For those posting about the QR reader, please [read this](https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a).

@isunilapps - it sounds like you're reporting an issue with different symptoms, not related to the original thread. Possibly [this one](https://github.com/expo/expo/issues/1593).

**Closed by terribleben** 2018-04-02 17:29 UTC
Labels: project: ios-runtime
