### ISSUE TITLE
Cannot view app: ::ffff:127.0.0.1 "GET /debug HTTP/1.1" 404 18 "-" "-" Packager is not running at 192.168.1.26:19001

### ISSUE THREAD

**Issue by SpadarShut** [expo/expo#1319] opened 2018-01-24 12:16 UTC
After upgrading to SDK 25 and running `npm start` I see the QR code in console, and every 100ms the following message gets output to console:
```
19:01:04: ::ffff:127.0.0.1 - - [24/Jan/2018:12:01:04 +0000] "GET /debug HTTP/1.1" 404 18 "-" "-"
```
When trying to open the app on the phone it doesn't load with error 

```Packager is not running at 192.168.1.26:19001```

Any Ideas what's wrong here?

**Comment by fozzylyon** [comment] 2018-01-24 17:01
The packager error could be that your phone/simulator doesn't have the latest client to support the sdk.

But I get the same `/debug` stdout.  I don't know what they're about

**Comment by gregbenner** [comment] 2018-01-24 21:22
Same, on Ubuntu after upgrading.
Below is package.json and app.json was upgraded to 25. Upgraded npm i -g exp and just ran npm start with no devices connected.
`{
  "name": "x",
  "version": "0.5.0",
  "private": true,
  "devDependencies": {
    "babel-plugin-module-resolver": "^2.7.1",
    "husky": "^0.14.3",
    "jest-expo": "^25.0.0",
    "lint-staged": "^4.2.1",
    "react-native-scripts": "1.3.1",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch",
    "precommit": "lint-staged"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "lint-staged": {
    "*.{js,json}": ["prettier --write", "git add"]
  },
  "dependencies": {
    "axios": "^0.16.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "expo": "^25.0.0",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.4",
    "mobx": "^3.2.2",
    "mobx-logger": "^0.6.0",
    "mobx-react": "^4.2.2",
    "mobx-remotedev": "^0.2.8",
    "prettier": "^1.7.0",
    "prop-types": "^15.6.0",
    "react": "16.2.0",
    "react-native":
      "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-communications": "^2.2.1",
    "react-native-easy-grid": "^0.1.15",
    "react-native-easy-toast": "^1.0.9",
    "react-native-elements": "^0.16.0",
    "react-native-google-places-autocomplete": "^1.3.6",
    "react-native-keyboard-aware-scroll-view": "^0.4.1",
    "react-native-masked-text-fork":
      "git+https://github.com/gregbenner/react-native-masked-text.git",
    "react-native-modal": "^4.0.0",
    "react-native-progress-circle": "^2.0.0",
    "react-native-ratings": "^4.1.0",
    "react-native-simple-markdown": "^1.0.60-rc.3",
    "react-native-svg-image": "^2.0.0",
    "react-native-svg-uri": "^1.2.1",
    "react-native-swiper": "^1.5.13",
    "react-native-vector-icons": "^4.5.0",
    "react-native-version-check-expo": "^2.0.1",
    "react-navigation": "^1.0.0-beta.27",
    "sentry-expo": "~1.7.0",
    "socket.io-client": "^2.0.4",
    "styled-components": "^2.1.2"
  }
}
`

**Comment by gregbenner** [comment] 2018-01-24 21:25
Trying from Exp GUI results in this also, encase that helps
![screenshot from 2018-01-24 16-23-44](https://user-images.githubusercontent.com/1177690/35357960-08f182b6-0123-11e8-87a4-f6d13443f4dd.png)

**Comment by SpadarShut** [comment] 2018-01-25 01:58
@fozzylyon when client on the phone isn't latest, it says the version is unsupported, but I have the latest client and the error is different.

**Comment by jaaberg** [comment] 2018-01-25 07:43
I also have the problem of the console repeatedly printing out the 404 on /debug in the terminal about 10 times a second. 

```
Logs from serving your app will appear here. Press Ctrl+C at any time to stop.

 › Press a to open Android device or emulator, or i to open iOS emulator.
 › Press q to display QR code.
 › Press r to restart packager, or R to restart packager and clear cache.
 › Press d to toggle development mode. (current mode: development)

8:37:24 AM: ::ffff:127.0.0.1 - - [25/Jan/2018:07:37:24 +0000] "GET /debug HTTP/1.1" 404 18 "-" "-"
8:37:24 AM: ::ffff:127.0.0.1 - - [25/Jan/2018:07:37:24 +0000] "GET /debug HTTP/1.1" 404 18 "-" "-"
(...)
```

There is no error messages or warnings in the app. Remote debugging to chrome works fine. I’ve tried multiple times deleting node_modules, clearing cache, removing all watches from watchman, and what not. I found out that this went away when I switched back to `react-native` version `(...)/sdk-24.0.0.tar.gz`, but that is not a solution.

**Comment by sdstolworthy** [comment] 2018-01-25 19:11
Same problem here

**Comment by sdstolworthy** [comment] 2018-01-25 20:38
This appears to be an issue with yarn. I rm-rf'd node_modules, lowered my npm version to the recommended 4.6.0, then installed modules with npm i. That worked,I'm not getting that error message any more...

**Comment by jaaberg** [comment] 2018-01-26 08:02
Hmm, that didn't work for the repeating 404 to /debug for me. 
```
$ npm -v
4.6.0
$ rm -rf node_modules
$ npm cache clean
$ npm i
```
Still same
```
8:59:04 AM: ::ffff:127.0.0.1 - - [26/Jan/2018:07:59:04 +0000] "GET /debug HTTP/1.1" 404 18 "-" "-"
```

**Comment by fossecode** [comment] 2018-01-29 14:00
I am having this issue as well. Tried clearing cache and reinstalling node modules using npm 4.6.0, but no luck.

**Comment by acvos** [comment] 2018-01-29 14:10
Same problem with iOS emulator.

**Comment by brentvatne** [comment] 2018-01-29 20:26
can someone try to determine where these debug http requests are coming from? expo is not making them and neither is react-native

**Comment by fossecode** [comment] 2018-01-29 20:27
I just got a reply from Brent Vatne on the blog post for expo v25. He suggested that it might be a 3rd party tool or library causing the issue (hitting the /debug endpoint). I compared @gregbenner's package.json with mine, and the overlapping dependencies are:
`{
      "react-test-renderer":"16.0.0-alpha.12"
      "react-native-scripts":"1.3.1",
      "jest-expo":"^25.0.0",
      "babel-plugin-module-resolver":"^2.7.1",
      "expo":"^25.0.0",
      "prettier":"^1.7.0",
      "prop-types":"^15.6.0",
      "react":"16.2.0",
      "react-native":"https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
      "react-native-communications":"^2.2.1",
      "react-native-elements":"^0.16.0",
      "react-native-vector-icons":"^4.5.0",
      "react-navigation":"^1.0.0-beta.27",
      "sentry-expo":"~1.7.0",
   }`

It might however be a sub-dependency or something else. But can some else compare their package.json and look for overlaps with these?

**Comment by brentvatne** [comment] 2018-01-29 20:36
do you have any of the following installed?

- https://github.com/jhen0409/react-native-debugger
- https://github.com/facebook/react-devtools

**Comment by brentvatne** [comment] 2018-01-29 20:38
please overshare any and all information about your development environments!

**Comment by fossecode** [comment] 2018-01-29 20:52
I had react-devtools installed, both as a npm module and the chrome extension. Deleting them did not help.

**Comment by wcandillon** [comment] 2018-01-29 21:05
Removing react-devtools didn't work for me either. 
My overlapping differences with @fossecode are:

```
{ "react-test-renderer":"16.0.0-alpha.12" "react-native-scripts":"1.3.1", "jest-expo":"^25.0.0",  "expo":"^25.0.0", "react":"16.2.0", "react-native":"https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz", "react-navigation":"^1.0.0-beta.27" }
```

**Comment by fossecode** [comment] 2018-01-29 21:10
I think the issue is related to react-native-scripts. I have been running the packager using `npm start`, which in turn runs `react-native-scripts start`. When I tried the running the packager using `exp start` instead, the problem is gone.

**Comment by wcandillon** [comment] 2018-01-29 21:12
I can confirm that as well.

**Comment by brentvatne** [comment] 2018-01-29 21:13
fantastic. can you all try updating react-native-scripts to the latest, please? 1.11.1

**Comment by fossecode** [comment] 2018-01-29 21:16
Yup, that fixed it!

**Comment by wcandillon** [comment] 2018-01-30 08:16
Thank you so much for the support 🎉

**Comment by fson** [comment] 2018-01-30 08:37
Closing this since it sounds like the issue can be fixed by upgrading to the latest `react-native-scripts` version. If this issue comes up in the future, please feel free to open a new issue.

**Closed by fson** 2018-01-30 08:37 UTC
Labels: project: xde/exp/xdl

**Comment by deot** [comment] 2018-02-26 07:07
The same problem here when i use `exp build:android`;

**Comment by SpadarShut** [comment] 2018-02-26 07:08
@deot try aupgrading to latest `react-native-scripts`

**Comment by deot** [comment] 2018-02-26 07:10
I've already done it

`npm i -D react-native-scripts@latest`(1.11.1)

**Comment by ForrestWeiswolf** [comment] 2018-03-19 01:41
I've updated to react-native-scripts@1.11.1 and exp@50.0.1 and am still having this problem.

**Comment by rkbansal** [comment] 2018-03-25 18:48
Updating Expo worked for me!

**Comment by pirple-node-student** [comment] 2018-11-18 16:45
**::ffff:127.0.0.1 - - [18/Nov/2018:15:59:26 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.11.0"**
updating to the latest version of **react-native-scripts** did not work for me.
The app is a brand new app created with react-native init command with the navigation module added to play with the **createDrawer** navigation function.

Versions:
node: **8.11.3**
react-native-cli: **2.0.1**
react-native: **0.57.5**
win-10: **10.0.17744 N/A Build 17744**

Questions
where is the **scripts.js** found and is it removed when installing the new version **2.0.1**, now I have a new module on the devDependencies object in **package.json**

**Comment by krisnailafat** [comment] 2019-01-09 15:30
> **::ffff:127.0.0.1 - - [18/Nov/2018:15:59:26 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.11.0"**
> updating to the latest version of **react-native-scripts** did not work for me.
> The app is a brand new app created with **react-native init** command with the navigation module added to play with the **createDrawer** navigation function.
> 
> Versions:
> node: **8.11.3**
> react-native-cli: **2.0.1**
> react-native: **0.57.5**
> win-10: **10.0.17744 N/A Build 17744**
> 
> Questions
> where is the **scripts.js** found and is it removed when installing the new version **2.0.1**, now I have a new module on the devDependencies object in **package.json**

did you found the solution ?

**Comment by Jovisx** [comment] 2019-05-01 14:10
Just run exp start
