### ISSUE TITLE
EXPO Go last update issue

### ISSUE THREAD

**Issue by Cleanoise** [expo/expo#26555] opened 2024-01-20 17:04 UTC
### Summary

After the latest update of Expo Go on Android, the dependency on expo-linear-gradient has stopped working.

### What platform(s) does this occur on?

Android

### SDK Version

49.0.17

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.18.0 - C:\nvm\nodejs\node.EXE
      npm: 9.8.1 - C:\nvm\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-221.6008.13.2211.9514443
    npmPackages:
      expo: ~49.0.17 => 49.0.22
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: managed

### Minimal reproducible example

![image](https://github.com/expo/expo/assets/157233943/e44171eb-309f-4939-a854-39cdafc9a528)

**Comment by rogalski** [comment] 2024-01-21 11:00
Duplicate of #26531

**Closed** 2024-01-22 19:42 UTC
Labels: CLI
