### ISSUE TITLE
RTL Android phones force RTL layout, even though disabled

### ISSUE THREAD

**Issue by kadoshms** [expo/expo#1205] opened 2018-01-03 23:03 UTC
Hey there.

This is a really annoying issue with Android phones.
Some of my app users have Hebrew based Android phones, and for some unjust reason Android forces the RTL layout, altough my app doesn't support it.

Iv'e added this in `App.js` main

>     I18nManager.forceRTL(false);
>     I18nManager.allowRTL(false);

But it does not work.

I am not sure though if it is an expo or RN issue.

**Comment by fxfactorial** [comment] 2018-01-04 00:03
Hi, thanks for report! 

I have a suspicion that this is at the RN level, need more to double check

**Comment by kadoshms** [comment] 2018-01-04 09:32
@fxfactorial I though so, but I use the Expo fork, so isn't it in the Expo field right now?

**Comment by fxfactorial** [comment] 2018-01-04 21:42
right but expo is built on top of RN.

**Comment by jesseruder** [comment] 2018-02-07 04:54
@kadoshms can you open an issue on the React Native repo if this is an issue there? Going to close this for now if it's not an issue inside Expo code.

**Closed by jesseruder** 2018-02-07 04:54 UTC
Labels: project: android-runtime, project: react-native

**Comment by Yonatani** [comment] 2018-03-04 14:08
Did someone manage to fix this issue? on RN you can already fix it and force it. but not in expo

**Comment by AlexanderPPetrov** [comment] 2018-03-30 14:55
Issue still exists. At first the layout is always RTL no matter these are set:
I18nManager.forceRTL(false);
I18nManager.allowRTL(false);
Second run of application everything is fine.
We need to reload the application programatically.
A library named react-native-restart does the trick but its working with ejected project only.
We need reload method for standalone.

**Comment by FakhruddinAbdi** [comment] 2018-06-24 18:28
this is the issue opened in react-native repo https://github.com/facebook/react-native/issues/11475

the only solution proposed there is to edit native code, but how we should fix it using expo ?

**Comment by esamelson** [comment] 2018-06-25 21:43
@FakhruddinAbdi as of now you'll need to detach in order to edit native code. You can also use `Updates.reload()` to emulate the functionality of react-native-restart if that workaround is okay for you.

**Comment by FakhruddinAbdi** [comment] 2018-06-26 06:43
Thanks @esamelson 
Just could you please let me know how i can use `updates.reload()` api to just reload the experience at the first lunch of the app.

Because the issue appear just in the first lunch and in the next lunches it use  `I18nManager.allowRTL(false);` code  to fix the issue.

**Comment by FakhruddinAbdi** [comment] 2018-07-07 15:05
I tried `Updates.reload()` as the following code in a standalone app, but didn't work

if (I18nManager.isRTL){
      Updates.reload();
    }

**Comment by terribleben** [comment] 2018-07-10 00:13
Hi all, I've opened a followup issue which tracks some of the findings of this thread: https://github.com/expo/expo/issues/1969

In particular, after reading the react-native upstream thread, it looks like it would be really useful if Expo added a native hook to allow RTL to work on the first load.

If you have any other thoughts to contribute, or if I missed any important details, please discuss in the new thread. Thanks!

**Comment by amitneeman** [comment] 2018-08-10 19:13
Hi.
Any news about this issue? making publishing rtl apps really hard

**Comment by kadoshms** [comment] 2018-08-12 07:04
Iv'e noticed that in our case, the app "fixes" itself on the second fresh launch (when the app is killed and then opened).

**Comment by amitneeman** [comment] 2018-08-12 17:37
and you are using 

`Updates.reload() `

on the first load? or letting the user close and open manually?

**Comment by FakhruddinAbdi** [comment] 2018-08-13 05:15
I tied Updates.reload() many times and it didn't work.
You can find in the forums and other places that many others tried and failed using `Updates.reolad()`

I started to programmatically fix it. use `isRTL` to know if it has been changed to RTL layout. if so then use css to fix it.

In the first time you think you should update many codes, but soon you realize by changing less 10, 15 codes you got a desired result.

**Comment by amitneeman** [comment] 2018-08-13 05:29
The issue is with this approach are 3rd party libaries (like react navigation) which do not provide configuration (that i know of) but inherit the device’s rtl layout.

**Comment by 0xori** [comment] 2019-01-31 07:49
@FakhruddinAbdi I've managed to work around the issue and force restart the app using expo error recovery mechanism. By crushing it when we need to reload we're causing expo to reopen the app automatically.

> If your published app encounters a fatal JS error, Expo will immediately reload your app. If the error happens very quickly after reloading, Expo will show a generic error screen with a button to try manually reloading.
https://docs.expo.io/versions/v32.0.0/guides/errors/
instead of using `Updates.reolad()` you can throw an exception.
