### ISSUE TITLE
[dev-client][RN0.64][RN.65] "There was a problem sending log messages to your development environment TypeError: undefined is not a function"

### ISSUE THREAD

**Issue by Yonom** [expo/expo#14187] opened 2021-08-26 11:10 UTC
### Summary

On Android and iOS, on RN versions 0.64 and up, when using expo-dev-client, handling of app errors fails with an additional error:

<img width="364" alt="Screen Shot 2021-08-26 at 12 57 39" src="https://user-images.githubusercontent.com/1394504/130950994-cb48ebc0-d4fd-4644-afc9-9bb532aae93e.png">

### Issue root cause

React Native's `Libraries/Core/Devtools/parseErrorStack.js` signature was changed in RN 0.64, it no longer expects an error but rather just the stack. Commit: https://github.com/facebook/react-native/commit/9edfc43aad2f68be8a37c916779681cd9ad13fee#diff-6c06cffe52fa76adfc945f6d386e1635701525b3299c0f3ce1bdf80a479e3922

The expo package relies on this internal RN API and currently sends the whole error object to parseErrorStack. I was able to fix this issue by changing expo package's /logs/LogSerialization.js as follows: (patch-package)

```patch
diff --git a/node_modules/expo/build/logs/LogSerialization.js b/node_modules/expo/build/logs/LogSerialization.js
index 4e22b7d..ec9dc9f 100644
--- a/node_modules/expo/build/logs/LogSerialization.js
+++ b/node_modules/expo/build/logs/LogSerialization.js
@@ -86,7 +86,7 @@ async function _serializeErrorAsync(error, message) {
     return { message, stack: formattedStack };
 }
 async function _symbolicateErrorAsync(error) {
-    const parsedStack = parseErrorStack(error);
+    const parsedStack = parseErrorStack(error?.stack);
     let symbolicatedStack;
     try {
         // @ts-ignore: symbolicateStackTrace has different real/Flow declaration
```

What's missing in this fix is the version check to use the old behavior on 0.63 and downward (I don't know how to implement this, hence why there is no pull request from me).

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Package versions

"expo-dev-client": "^0.4.7"

### Environment

```
Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.7.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.21.0 - /usr/local/bin/npm
      Watchman: 2021.08.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 23, 24, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 31.0.0, 31.0.0, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.3 => 42.0.3 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: ^0.65.1 => 0.65.1 
      react-native-web: ^0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

- npx create-react-native-app
- npx react-native upgrade
- manually install expo-dev-client following this guide: https://docs.expo.io/clients/installation/
- add the following line in App.js's render function: `throw new Error('test error');`
- expo run:ios

:x: NOK: Two errors appear, one is the error we've thrown, "test error" (expected); another is "There was a problem sending log messages to your development environment TypeError: undefined is not a function" (unexpected)

Expected behavior: Only the first error appears.

**Comment by esamelson** [comment] 2021-08-30 21:50
Hey @Yonom , thanks for the report and for digging into the root cause! We're tracking this internally and will try and get a fix out soon.

**Comment by lukmccall** [comment] 2021-09-07 14:22
Hey @Yonom, this issue was already addressed by this PR https://github.com/expo/expo/pull/13793. Unfortunately, this can't be fixed in the `dev client` codebase. So we can't publish this fix right now. It'll be part of the next SDK release.

However, for now, I will close that issue.

**Closed by lukmccall** 2021-09-07 14:22 UTC
Labels: project: react-native, ⭐️ Root Cause Known, Custom Client
