### ISSUE TITLE
[ANDROID] - Splash screen API flickers

### ISSUE THREAD

**Issue by vdlindenmark** [expo/expo#1620] opened 2018-04-08 15:02 UTC
I have a problem with the splash screen API. It looks like the same issue that's been fixed here https://github.com/expo/expo/issues/542 for iOS, bot not for Android. I've done the following:

1. Inside my app.json i've set an image as splash screen.
2. Inside my App.js i've first cached the same splash screen image and until that's cached i'm using the AppLoading API to still show the splash screen from step 1.
3. When the splash screen image of step 2 is cached, i've stop the AppLoading and show the image of step 2 (which is the exact same image so the user can't noticed that)
4. Now i put an animation on the splash screen and load all of our other stuff.

BUT! On iOS everything goes well, but for Android i see a white background between step 1 and to.
If i changed the background of step 2 to another color, thats the color i've seen between step 1 and 2. So or the caching issn't working very well on Android, or the AppLoading issn't working for Android.

### Expected Behavior

I've expecting the same thing for Android as for iOS.

### Actual Behavior

You see the background of step 2 before it shows the background image (splash screen)

It looks like the exact same thing happens here: https://github.com/expo/expo/issues/542#issuecomment-326386121

**Comment by vdlindenmark** [comment] 2018-04-08 15:04
@terribleben here is the new issue for https://github.com/expo/expo/issues/542

**Comment by ericnograles** [comment] 2018-04-09 12:26
Hey everyone,

Thought I'd pile on here, since I think this is related to either this or #409.

Standalone Android build with a splash screen, when the app loads, the actual splash screen persists

![image](https://user-images.githubusercontent.com/6023705/38497531-69b6fc3e-3bcf-11e8-9cf6-1fd068bd7d04.png)

i.e. that "Now and Zen" with the meditative icon in the middle (the splash screen) should have disappeared when the app loaded...although, now that it did persist, you guys gave me a really cool UI idea 😆 

But, nevertheless, the splash screen should've disappeared.

Code for App.js is as follows

```jsx
import React from 'react';
import background from './assets/mountain-creek.png';
import {
  StyleSheet,
  Text,
  View,
  ART,
  Dimensions,
  TouchableOpacity,
  Animated,
  ImageBackground,
  LayoutAnimation
} from 'react-native';
import { AppLoading, Audio, Asset} from 'expo';
import Pulse from './Pulse';

const window = Dimensions.get('window');
const styles = {
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  }
};

const initialState = {
  direction: 'idle',
  label: 'Touch circle to begin',
  repetitions: 0,
  isReady: false
};

function cacheAssets(assets) {
  return assets.map(asset => Asset.fromModule(asset).downloadAsync());
}

export default class App extends React.Component {
  state = initialState;
  backgroundSound = new Audio.Sound();

  async loadAssetsAsync() {
    const localAssets = cacheAssets([
      require('./assets/mountain-creek.png'),
      require('./assets/mindfulness-bells.mp3')
    ]);

    await Promise.all(localAssets);
  }

  async componentWillMount() {
    let status = await this.backgroundSound.getStatusAsync();
    if (status.isLoaded) {
      await this.backgroundSound.playAsync();
    }
  }

  async componentDidMount() {
    await Audio.setIsEnabledAsync(true);
    await Audio.setAudioModeAsync({
			allowsRecordingIOS: false,
			interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
			playsInSilentModeIOS: true,
			shouldDuckAndroid: true,
			interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DUCK_OTHERS,
		});
    await this.backgroundSound.loadAsync(require('./assets/mindfulness-bells.mp3'));
    await this.backgroundSound.setIsLoopingAsync(true);
    await this.backgroundSound.setVolumeAsync(1);
    await this.backgroundSound.playAsync();
  }

  async componentWillUnmount() {
    await this.backgroundSound.pauseAsync();
  }
  
  onResponderRelease = async event => {
    const { direction, repetitions } = this.state;
    this.setState({
      direction: 'contract',
      label: 'Exhale as the circle contracts...',
      repetitions: repetitions + 1
    });
  };

  onResponderGrant = async event => {
    this.setState({
      direction: 'expand',
      label: 'Breathe in as the circle expands...'
    });
  };

  render() {
    const { repetitions, isReady } = this.state;
    const labelLeft = 
      repetitions < 10 ? 2.11 :
      repetitions < 20 ? 2.23 :
      2.24;

      if (!isReady) {
        return (
          <AppLoading
            startAsync={this.loadAssetsAsync}
            onFinish={() => this.setState({ isReady: true })}
            onError={console.warn}
          />
        );
      }
    return (
      <View
        style={[styles.container]}
        onStartShouldSetResponder={event => true}
        onResponderGrant={this.onResponderGrant}
        onResponderRelease={this.onResponderRelease}
      >
      <ImageBackground source={background} style={{width: '100%', height: '100%', opacity: 0.1}} ></ImageBackground>
        <Text
          style={{
            color: 'gray',
            position: 'absolute',
            left: window.width / labelLeft,
            fontSize: 40
          }}
        >{this.state.repetitions}
        </Text>
        <Pulse
          color="orange"
          numPulses={1}
          diameter={400}
          direction={this.state.direction}
          speed={16}
          duration={2000}
          setIdle={this.setIdle}
          repetitions={this.state.repetitions}
        />
        <Text
            style={{
              fontSize: 25,
              color: 'gray',
              position: 'absolute',
              bottom: 40,
              justifyContent: 'center',
              alignItems: 'center'
            }}
          >
            {this.state.label}
          </Text>
      </View>
    );
  }
}
```

**Comment by aalices** [comment] 2018-05-09 14:01
@ericnograles not sure what `styles.container` could be, but try setting there a `backgroundColor`
still no updates for the flickering, didn't manage te reproduce this yet :(

**Comment by esamelson** [comment] 2018-05-24 05:33
Hi all -- @aalices 's fix has been landed internally and will go out with SDK 28 🎉

**Comment by terrysahaidak** [comment] 2018-06-19 10:34
Hi @aalices, check out this video.
https://photos.google.com/share/AF1QipO7BHUCfthcQtwXhkRVrTRxEHmzGA7YzkKxTOBSVAbMRRQHr_t7KA8AaYZNaOi2Jg/photo/AF1QipMbkkPOow5wgzyQ4ssL4lr8ArfN3qL7brgvXci4?key=QmgtX0Zxd2FNNlpYbDUxNXdPYVdlLTY0aUVRcXV3


It is the code from https://github.com/expo/expo/issues/409#issuecomment-398349803

As you may notice, it shows the background main color, then flicks to white and then shows the splash image. For ios it works as expected.

Here also APK you can install and test: https://exp-shell-app-assets.s3-us-west-1.amazonaws.com/android%2F%40terrysahaidak%2Fblank-apploading-test-31142418-73a6-11e8-adab-0a580a780745-signed.apk

**Comment by barthec** [comment] 2018-07-23 09:58
Hello everyone!
I've tracked down what is really happening on Android devices.
Happily for us upcoming release of `expo-sdk@29` will solve this issue. You can use pre-release channel to have this available right away. Just install `expo@next`.

Here is [snack](https://snack.expo.io/rJ4_ZmQVX) demonstrating solution on Android devices. (Test out that sample with on your local machines as it would fail with snack).

Brief explanation: Android is showing `<Image />`'s content with some delay what is causing white/other colors flicks between `SplashScreen` and it's later continuation. Therefore we need to prevent `SplashScreen` from hiding until `Image` is fully loaded. Fortunately we can use [`Image#onLoadEnd`](https://facebook.github.io/react-native/docs/image#onloadend) to achieve our goal and invoke upcoming `SplashScreen#hide` method in this callback. We also need to set [`Image.fadeDuration`](https://facebook.github.io/react-native/docs/image#fadeduration) prop to `0` as it's default value is `300`

**Closed by barthec** 2018-07-23 09:58 UTC
Labels: in progress, project: android-runtime, project: sdk, status: pending

**Comment by kriskate** [comment] 2018-07-26 12:14
I subscribe to this. Android flickers between AppLoading and the rest of my app.

The app I'm developing got quite big, and before rendering my Main component, I'm rendering another component (Download), like so:
```
export default class App extends React.Component {
  state = { 
    loaded: false,
    downloading: false,
  };

  _loadAssets = async () => {
    // await for async stuff; 
    // if app needs to show download screen, then:
    this.setState({ downloading: true });
  };
  _handleFinishLoading = () => {
    this.setState({ loaded: true });
  };

  _handleFinishDownLoading = ({wiki, profile}) => {
    store = createStore(reducers, { wiki, profile });
    this.setState({ downloading: false });
  };

  render() {
    if (!this.state.loaded) {
      return (
        <AppLoading
          startAsync={this._loadAssets}
          onFinish={this._handleFinishLoading}
          onError={Logger.error}
        />
      );
    } else if(this.state.downloading) {
      return (
        <AppDownloading
          onFinish={this._handleFinishDownLoading}
        />
      )
    } else {
      return (
        <Provider store={store}>
          <AppNavigator />
        </Provider>
      );
    }
  }
}
```

I've tried the following:
1. clear app cache
2. have only a background-colored View/ inside AppDownloading/
3. same happens when this.state.downloading is never set to true

I'm unsure of why it's happening, but the only reason I can think of is that the app is pretty big now.
However, if we could also have a static variable like Splashscreen.hide() it would be great, because we could call it from within child components of App/.
