### ISSUE TITLE
metro bundler crashes at start with error: Error: Must specify expo-platform header or query parameter

### ISSUE THREAD

**Issue by seyaobey-dev** [expo/expo#17495] opened 2022-05-12 21:28 UTC
### Summary

When I start metro bundler with `expo start --dev-client`,  Metro bundler crashes with error:

```
Error: Must specify expo-platform header or query parameter
    at getPlatformFromRequest (.../node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:34:11)
```

I have a valid develop build in `eas.json`:
```
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
    },
 }
```

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### Package versions

expo-dev-client : 0.9.5
expo-updates : 0.13.1

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /var/folders/fs/mgcn9dds60114gl150cz1fk40000gn/T/yarn--1652390571976-0.8778512103665701/node
      Yarn: 1.22.15 - /var/folders/fs/mgcn9dds60114gl150cz1fk40000gn/T/yarn--1652390571976-0.8778512103665701/yarn
      npm: 8.3.0 - ~/.nvm/versions/node/v14.18.1/bin/npm
      Watchman: 2021.11.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2/13C5081f - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.1 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed
```

### Reproducible demo

This crash is not consistent.
1. create a new expo project: `expo init`
2. add dev-client with a development profile
3. run `expo start --dev-client`

### Stacktrace (if a crash is involved)

```

23:18
Error: Must specify expo-platform header or query parameter
    at getPlatformFromRequest (.../node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:34:11)
    at /.../node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:207:19
    at call (/.../node_modules/connect/index.js:239:7)
    at next (/.../node_modules/connect/index.js:183:5)
    at Function.handle (/.../node_modules/connect/index.js:186:3)
    at handle (/.../node_modules/connect/index.js:91:14)
    at call (/.../node_modules/connect/index.js:239:7)
    at next (/.../node_modules/connect/index.js:183:5)
    at Function.handle (/.../node_modules/connect/index.js:186:3)
    at Server.app (/.../node_modules/connect/index.js:51:37)
```

**Comment by niteshkumarniranjan** [comment] 2022-05-25 03:42
Facing a similar issue where nothing is crashing but seeing the same errors on console

**Comment by nandorojo** [comment] 2022-06-18 14:27
Yeah I'm getting this as well on SDK 45.

**Comment by OneHatRepo** [comment] 2022-06-24 20:37
Seeing it on SDK 45.

**Comment by brentvatne** [comment] 2022-06-24 20:42
please ensure you are using the latest version of expo-cli (`npm i -g expo-cli`) then run `EXPO_DEBUG=1 expo start` and copy and paste the full logs here

**Comment by OneHatRepo** [comment] 2022-06-24 21:51
I took those two steps and got this:

Developer tools running on http://localhost:19002
Opening developer tools in the browser...

Expo Metro config:
- Version: 0.3.18
- Bundler target: bare
- Legacy: false
- Extensions: ts, tsx, js, jsx, json
- React Native: /Users/skote/ReactNative/VenPal/node_modules/react-native
- Babel config: /Users/skote/ReactNative/VenPal/babel.config.js
- Resolver Fields: react-native, browser, main
- Watch Folders: 
- Node Module Paths: 
- Exotic: false


Expo Metro config:
- Version: 0.3.18
- Bundler target: bare
- Legacy: false
- Extensions: ts, tsx, js, jsx, json
- React Native: /Users/skote/ReactNative/VenPal/node_modules/react-native
- Babel config: /Users/skote/ReactNative/VenPal/babel.config.js
- Resolver Fields: react-native, browser, main
- Watch Folders: 
- Node Module Paths: 
- Exotic: false

Starting Metro Bundler
Your JavaScript transform cache is empty, rebuilding (this may take a minute).
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▀█▀█▄█▄▀███▄▄█▀▄██ ▄▄▄▄▄ █
█ █   █ █▀▀▀█▄▀▄█▄▀▄▀█▄▀█▀█ █   █ █
█ █▄▄▄█ █▀ █▄ ▀ ▀███▄   ▄██ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄▀ █ █▄█▄█ █ ▀▄█▄█▄▄▄▄▄▄▄█
█  ▄▄▄▀▄▄ ▄▀ ▀ ▀▄▄▄█ ▄██ ▄ ▀▄█ ▀ ▀█
█▀▀▀▄█ ▄█▄█▄█ ██ ▄█ █▀  █ ██ ▀▀▀ ▀█
█▄▀█▀█▀▄▄▄▄▄▀▀ ██▄▄  ▀▀▄▀█▄▀█▄▀▀█ █
█▀▀█▀▀▄▄▀ ▄ █ ▄▄ ▄██▀█▀▀▀█  ██  ███
█ ▄▄█▀▀▄▀  ▀ ▀ ▀▄▄▄▄▀ █▄ ▄█▀▄▄▀█▀▀█
█  ▀▄██▄██▄▀█▀██▄▀▄▄█  ▄█▄ ▄█ ▀▀▄██
█▀ █ █ ▄▄ ▄ █▄ ▀ ▀█▀▀ █▄ ▄▄▀ ▄▄▀▀ █
█ █▄▄█▀▄▄▀██▀▀██▄██▄▀  ▀██▄██ ▀  ██
█▄█▄██▄▄▄▀▄█▀▀ █▄▄▄  ▄▀▄█ ▄▄▄ █▀▄▀█
█ ▄▄▄▄▄ █▄ ▀██▄▄  ██▀     █▄█    ▀█
█ █   █ █  █▀  ▀▄█▄▄ ██▄█▄ ▄  ▀██▄█
█ █▄▄▄█ █ ▀██ █▀▄▀▄ █▀▀▄ ▄▀▄ ▀█ ▄██
█▄▄▄▄▄▄▄█▄████▄█▄████▄█▄▄▄▄█▄▄▄█▄██

› Metro waiting on exp+venpal://expo-development-client/?url=http%3A%2F%2F192.168.88.90%3A8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press r │ reload app
› Press m │ toggle menu
› Press d │ show developer tools
› shift+d │ toggle auto opening developer tools on startup (enabled)

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
Started Metro Bundler
Manifest request: URL "/", Headers {"host":"localhost:8081","connection":"close"}
Error: Must specify expo-platform header or query parameter
    at getPlatformFromRequest (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:36:11)
    at /usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:215:19
    at call (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:239:7)
    at next (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:186:3)
    at handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:91:14)
    at call (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:239:7)
    at next (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:186:3)
    at Server.app (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:51:37)
Manifest request: URL "/", Headers {"host":"localhost:8081","connection":"close"}
Error: Must specify expo-platform header or query parameter
    at getPlatformFromRequest (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:36:11)
    at /usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:215:19
    at call (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:239:7)
    at next (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:186:3)
    at handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:91:14)
    at call (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:239:7)
    at next (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:186:3)
    at Server.app (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:51:37)
Manifest request: URL "/", Headers {"host":"localhost:8081","connection":"close"}
Error: Must specify expo-platform header or query parameter
    at getPlatformFromRequest (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:36:11)
    at /usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:215:19
    at call (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:239:7)
    at next (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:186:3)
    at handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:91:14)
    at call (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:239:7)
    at next (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:186:3)
    at Server.app (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:51:37)
Manifest request: URL "/", Headers {"host":"localhost:8081","connection":"close"}
Error: Must specify expo-platform header or query parameter
    at getPlatformFromRequest (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:36:11)
    at /usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:215:19
    at call (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:239:7)
    at next (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:186:3)
    at handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:91:14)
    at call (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:239:7)
    at next (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:186:3)
    at Server.app (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:51:37)
Manifest request: URL "/", Headers {"host":"localhost:8081","connection":"close"}
Error: Must specify expo-platform header or query parameter
    at getPlatformFromRequest (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:36:11)
    at /usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:215:19
    at call (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:239:7)
    at next (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:186:3)
    at handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:91:14)
    at call (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:239:7)
    at next (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:186:3)
    at Server.app (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:51:37)
Manifest request: URL "/", Headers {"host":"localhost:8081","connection":"close"}
Error: Must specify expo-platform header or query parameter
    at getPlatformFromRequest (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:36:11)
    at /usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:215:19
    at call (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:239:7)
    at next (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:186:3)
    at handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:91:14)
    at call (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:239:7)
    at next (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:186:3)
    at Server.app (/Users/skote/ReactNative/VenPal/node_modules/connect/index.js:51:37)
Manifest request: URL "/", Headers {"host":"localhost:8081","connection":"close"}

**Comment by brentvatne** [comment] 2022-06-24 22:00
```
Manifest request: URL "/", Headers {"host":"localhost:8081","connection":"close"}
```

it looks like you have something open that is making a request to localhost:8081 as soon as you start up the server.

**Comment by OneHatRepo** [comment] 2022-06-30 13:54
@brentvatne Sorry, I was out for a few days... That request to localhost:8081 is a chat functionality that tries to connect to a local socket server. The socket server was not running at the time I ran expo start, so it immediately closed the connection. That socket connection has worked for over a year, and if the socket server is not running, it just closes the connection. So I would not expect this local connection to be relevant.

**Comment by OneHatRepo** [comment] 2022-06-30 18:13
Correction — the socket was supposed to be on localhost:8082, so I'm not sure what the 8081 is all about.

**Comment by brentvatne** [comment] 2022-06-30 19:59
i'm trying to repro this but i'm unable to get it to a place where it will crash.

i followed the steps from op:

> create a new expo project: expo init
> add dev-client with a development profile
> run expo start --dev-client

then i simulate what i've seen here by making a request to localhost:8081:

> Manifest request: URL "/", Headers {"host":"localhost:8081","connection":"close","user-agent":"HTTP%20Client/1.0.3 CFNetwork/1329 Darwin/21.3.0"}

i then see this error, but the app continues running:

```
Error: Must specify expo-platform header or query parameter
    at getPlatformFromRequest (/Users/brentvatne/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:36:11)
    at /Users/brentvatne/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/xdl/src/start/ExpoUpdatesManifestHandler.ts:215:19
    at call (/Users/brentvatne/code/update-example/node_modules/connect/index.js:239:7)
    at next (/Users/brentvatne/code/update-example/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/brentvatne/code/update-example/node_modules/connect/index.js:186:3)
    at handle (/Users/brentvatne/code/update-example/node_modules/connect/index.js:91:14)
    at call (/Users/brentvatne/code/update-example/node_modules/connect/index.js:239:7)
    at next (/Users/brentvatne/code/update-example/node_modules/connect/index.js:183:5)
    at Function.handle (/Users/brentvatne/code/update-example/node_modules/connect/index.js:186:3)
    at Server.app (/Users/brentvatne/code/update-example/node_modules/connect/index.js:51:37)
```

**Comment by craig-ezyvet** [comment] 2022-06-30 22:10
Hi @brentvatne thats correct the app **does not** crash but the error continually outputs

**Comment by brentvatne** [comment] 2022-06-30 22:12
@craig-ezyvet - it seems like there is some process running on your machine that is continuously making a request to localhost:8081, any idea what that might be? do you know how i can reproduce this on my end if you believe it's caused by the app itself?

**Comment by OneHatRepo** [comment] 2022-07-01 17:18
I'm using a development build, and the opening screen for the development build looks like this:

![dev-build](https://user-images.githubusercontent.com/13893545/176940615-c8fe84ec-0254-4068-862c-f800f37ebeb7.png)

So it seems the localhost:8081 is due to using a development build.

**Comment by OneHatRepo** [comment] 2022-07-01 18:14
I don't get the error until I launch Flipper Desktop.

**Comment by brentvatne** [comment] 2022-07-01 20:14
@OneHatRepo - can you provide an example app that I can clone to see this? I tried reproing but I don't see this error

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/90494/176962708-731d9df3-2fbe-44c6-8261-f13c676c6176.png">

**Comment by OneHatRepo** [comment] 2022-07-01 20:26
I was getting the error with my production app.
I'm now trying to create a minimal app that will reproduce the error.

**Comment by OneHatRepo** [comment] 2022-07-01 23:53
I didn't get the error with a minimal app, but I did notice that this time I was using an app generated by **expo run:ios** instead of **eas build --profile dev**, which I was using last time. Both times, I would connect to the server generated with **expo start --dev-client**

I'll leave more info tomorrow if I have a chance.

**Comment by OneHatRepo** [comment] 2022-07-02 15:17
Using the minimal test app, **expo run** _did_ work in generating a development build that could connect to Flipper and debug through the Hermes Debugger, but also threw me into the **bare workflow**, which I did _not_ want. 

Using **eas build** to generate a development build caused the error to return in Metro Bundler when I tried to connect through Flipper. Metro Bundler didn't actually crash, but it continually spit out error messages like the one shown below.

![Metro Bundler](https://user-images.githubusercontent.com/13893545/177005993-b92427ad-edd3-4868-b2bf-a37d4b429bb7.png)

Flipper sees the app but shows the Hermes debugger as unavailable, as shown.

![Flipper](https://user-images.githubusercontent.com/13893545/177006003-f24f97f7-38fc-4b56-9d7e-5ec74f8e1383.png)

Here is the minimal app's code in question: https://github.com/OneHatRepo/MetroBundlerError

**Comment by WNemencha** [comment] 2022-07-08 17:00
Hey guys/ladies, got the error in the console today during maybe 10 minutes (10 dev minutes, with many ctrl+s to save/preview changes), was annoying but i could live with it, then it just crashed with some additionnal logs, not sure what to do with that (yet) so i'll just put that here in case that may hint some of the project's devs =>

```
... 100 more repeatitions ...
CommandError: Must specify "expo-platform" header or "platform" query parameter
CommandError: Must specify "expo-platform" header or "platform" query parameter
/Users/my_project_path/node_modules/metro-hermes-compiler/src/emhermesc.js:77
          throw ex;
          ^

RuntimeError: abort(CommandError: Unexpected response when updating the development session on Expo servers: Bad Gateway.). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/Users/my_project_path/node_modules/metro-hermes-compiler/src/emhermesc.js:402:15)
    at process.emit (node:events:532:35)
    at emit (node:internal/process/promises:133:20)
    at processPromiseRejections (node:internal/process/promises:260:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: node /Users/admin/.yvm/versions/v1.9.2/bin/yarn.js start
```

didn't do crazy stuff tho, was mainly playing with styles, and rive-react-native (which i don't see how it'd be linked to this), is it possible the issue comes from expo-asset's requests not sending the appropriate new headers?

**Comment by felixterpstra** [comment] 2022-07-27 15:01
I'm seeing the same issue, repeated `Error: Must specify expo-platform header or query parameter` errors after opening Flipper, roughly every 4 seconds.

The Flipper Hermes Debugger plugin is unavailable, even though Redux Debugger is available, although I'm unsure if it's related.

**Comment by jakobo** [comment] 2022-07-29 01:56
> I'm starting Metro Bundler with the Node script of **npm run esd** (esd = expo start dev) A development build can be created with **npm run ebd** (ebd = eas build dev)

I was able to reproduce this using @OneHatRepo's example. Local builds using the simulator work, but attempting to use the custom developer client on a physical iOS device generates the `Error: Must specify expo-platform header or query parameter` error. I traced the error to [ExpoUpdatesManifestHandler](https://github.com/expo/expo-cli/blob/main/packages/xdl/src/start/ExpoUpdatesManifestHandler.ts#L32), which seems to be invoked when Flipper asks for the event log [as part of metro connection](https://github.com/facebook/flipper/blob/main/desktop/flipper-server-core/src/devices/metro/metroDeviceManager.tsx).

I don't realistically think we're going to fix this from the flipper side. However, I was able to connect to an on-device Hermes app with the following start command which bypasses the expo update manifest:

`expo start --dev-client --force-manifest-type=classic`

However, I couldn't tell you what the implications of doing this are for a custom dev client since the updates manifest is usually relevant for adhoc/testflight/production updates.

**Comment by hirbod** [comment] 2022-08-10 13:07
I can confirm this issue. Having both flooding the logs when using flipper with simulator:
`Error: Must specify expo-platform header or query parameter`

And random metro crashes:

```
RuntimeError: abort(CommandError: Unexpected response when updating the development session on Expo servers: Bad Gateway.). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/Users/hirbod/GitLab/bub/remy/rmte-retail/node_modules/metro-hermes-compiler/src/emhermesc.js:402:15)
    at process.emit (events.js:412:35)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```

**Comment by rcaraway101** [comment] 2022-08-17 19:56
I started having this issue as well with SDK 46.

![Screen Shot 2022-08-17 at 2 56 13 PM](https://user-images.githubusercontent.com/108430176/185230878-02cf5034-2421-44dd-a567-780a7bbed7c3.png)

**Comment by Av3z** [comment] 2022-09-04 18:09
Try expo start --tunnel

**Comment by MorenoMdz** [comment] 2022-10-19 23:15
Minor bump, still cant get hermes debugger to work with Flipper due to this warning

**Comment by a-eid** [comment] 2022-10-21 18:12
I'm seeing this issue as well, expo 46 

I think it only happen when connecting a physical device.

**Comment by timoisalive** [comment] 2022-10-28 12:56
Yep, on Expo 46 and using `expo-updates`, as soon as I run `expo start --dev-client` I start getting
`Error: Must specify expo-platform header or query parameter` every 5 seconds, without even opening the app. Closing Flipper stops the errors from flooding. Also, as mentioned above, `expo start --dev-client --force-manifest-type=classic` prevents the errors from occurring.

However, with errors or without, I am not able to see my app in Flipper! The device is found and I get device logs. The doctor says all OK except for the iOS IDB, but that's required only for using a real device, right?

What could go wrong in connecting the app!?

**Comment by JNK90** [comment] 2022-11-03 13:15
I get this error when there is already a debugger connected. For me React Native Devtools opened in the background in a new browser window. When I tried to debug with VSCode or Flipper this error occured. Removing the connected debugger resolved that issue.

**Comment by hirbod** [comment] 2023-02-01 20:06
Not stale

**Comment by Veteran112** [comment] 2023-02-13 10:04
> Yeah I'm getting this as well on SDK 45.
did you fix?

**Comment by Veteran112** [comment] 2023-02-13 10:05
I got same error.

**Closed** 2023-02-15 02:12 UTC
Labels: Updates, Issue accepted, CLI
