### ISSUE TITLE
Is there limitation of number to subscribe ExpoToken?

### ISSUE THREAD

**Issue by dlehdanakf** [expo/expo#2019] opened 2018-07-22 05:47 UTC
Hi, Thanks for giving great service with push notification.
I want to know the number of tokens I can send at one time.

In the PHP-SDK example,
```
$expo->subscribe($interestDetails[0], $interestDetails[1]);
```

How many can I subscribe tokens in one request?
Can I subscribe 10,000 tokens?

**Comment by ccheever** [comment] 2018-07-24 18:40
I'm not sure what `subscribe` does. You probably need to read through the source code or find the author of the PHP client (it's community supported).
I made a question on our forum where maybe someone can answer.
https://forums.expo.io/t/php-server-sdk-question-about-subscription-limits/11868

Closing this for now since its not a bug or problem with the Expo software.

**Closed by ccheever** 2018-07-24 18:40 UTC
