### ISSUE TITLE
Android standalone builds don't update JS when APK is updated 

### ISSUE THREAD

**Issue by llamaluvr** [expo/expo#1122] opened 2017-12-17 05:38 UTC
This is my follow-up with a conversation with @brentvatne on Expo Slack on 12/15.

I've experienced this on Expo 22 and Expo 24.

Issue: When I install an APK with an updated JS bundle over the previous APK and then launch the app, the app still reflects the old JS bundle (manifest version numbers will be old, text/ functionality will indicate the previous version).

Brent and others at various points have indicated that I should expect the updated JS bundled locally in the new APK to be applied immediately, so I see the updated JS on first launch after an update. Brent tried this out on 12/15 and found this not to be an issue for him. If it was indeed the expected behavior that users would not see the update enclosed in an APK until the second run, I could live with it if I could use the update listener/ reload to gently guide my users to the new functionality. However, reload is broken for those who need to access images secured by a session cookie (see https://github.com/expo/expo/issues/370).

I've now built maybe 75? APK's over the past week and have experienced this issue almost every time. The updates have spanned two Android devices, two workstations, three Expo accounts, 9 separate projects, and two versions of Expo. I have tried this was traditional updates over the default release channel, and also using separate "version 1" / "version 2" release channels (kind of like the example in https://docs.expo.io/versions/latest/guides/release-channels.html). Release channels in particular seem like a nice avenue for testing this over and over without actually building more APK's, because you don't have to worry about the version 1 APK trying to grab the version 2 JS bundle over-the-air and invalidating the test.

**Repro steps:**
1) Build version 1 APK (I just used the blank template from expo init).
2) Install APK.
3) Run the app. See that it's version 1. (don't close it right away)
4) Change code, build version 2 APK.
5) Install version 2 APK over version 1.
6) Launch app, you'll still see version 1 code.
7) Kill app, launch again, now you'll see version 2 code.

**The two clear exceptions to this (where it works correctly, and you get the new code when you run for the first time after installing the updated APK):**
a) If you install version 1, never run it, then install version 2 and run it.
b) If you install version 1, shut off your network, run version 1, then install version 2, turn the network back on, and run the app.

b) can also happen if you close version 1 sufficiently fast after opening or your network is sufficiently poor to prevent whatever is happening that causes the bad behavior.

**Possible not-so-clear exception?**
See below in my day-in-the-life testing. Almost all of my testing has been on Android 6.0 devices. But I stole a 7.0 device from my wife and it actually worked correctly. But it was also on cellular. So maybe the network was too slow?

**Day-in-the-life Testing**
Just to make it abundantly clear what I'm doing and what I'm seeing, I created a project from scratch, ran it through a v1 and a v2, and installed both on three different devices, including one I hadn't used before.
Log of my day-in-the-life test: https://docs.google.com/document/d/1MwOofflQYUacdpsi5YZsolVDwWH2bUCKM-jxWOX1quQ/edit?usp=sharing
The Galaxy S6 was the device I hadn't used before, and it actually worked, showing the v2 code on first launch after update. However, it's a different version of Android than the others and was on a cellular network, not wifi.

My next step would be to re-run this test, but with the Galaxy S6 on wifi and the Moto G4 Play on cellular. This could isolate if it's cellular, Android 7.0, or both that keeps the issue from occurring. But each of these tests can take at least 45 minutes, so I only have so many in me.

Source code for this test (almost the same as all the others - just a riff on the blank template: https://github.com/llamaluvr/expo-android-apk-update-issue)

**Other related possible bugs**
- There were multiple instances of the app hanging at the splash screen after first install or update in the day of the life test and in my exhaustive notes below - especially when updating to an APK with another release channel.
- On Expo 24, first launch of a newly-installed app can work totally offline. But you get the blue error screen if you launch the app a second time, or on the first launch after update if you're offline. On Expo 22, after install, I can always run my app without a network connection.

**Additional notes**
There was way too much information to stick into this issue. I've tried my best to summarize in the issue, but if you need to see my exhaustive notes, names of accounts, slugs, and links to APK's, here they are.

Notes on my testing of default channel updates: https://docs.google.com/document/d/1pBbCVxqGoWxorGE2RoVSiC121xGCnSJNYAptCMl1Eu8/edit?usp=sharing

Notes on my testing of non-default release channel updates:
https://docs.google.com/document/d/11Ek9j30y4jnmgPHaH0bKi2xqhUzqnN_YFA17pHkWAXg/edit?usp=sharing

**Comment by voshawn** [comment] 2017-12-17 15:20
I believe I am experiencing the same issue running a detached app that I'm trying to upgrade from SDK 23 to SDK 24.

**Comment by llamaluvr** [comment] 2017-12-17 20:04
@voshawn it happened before my testing effort that I logged in the original post, but I also saw the issue when upgrading from an APK targeting SDK 22 to one targeting 24.

**Comment by llamaluvr** [comment] 2017-12-18 13:27
I have more evidence that this may be an issue with pre-Android 7.0 devices. I tried my version 1/ version 2 release channel demos on the Galaxy S6 running Android 7.0 (over wifi this time). The version 2.0 took effect immediately on this device.

Then I tried the same thing on an Android 5.1 (2013 Moto X) device. It behaved just the like the Android 6.0 devices- version 2 was not applied until the second opening of the app after update.

My release channels test APK's in case anyone wants to try this:
release 1: https://exp-shell-app-assets.s3-us-west-1.amazonaws.com/android%2F%40llamaluvr%2Fandroid-update-demo-7-c79a5242-e271-11e7-b5f4-0a580a782d0a-signed.apk
release 2: https://exp-shell-app-assets.s3-us-west-1.amazonaws.com/android%2F%40llamaluvr%2Fandroid-update-demo-7-9a35c09c-e273-11e7-b8d8-0a580a780705-signed.apk

------

I did a little more digging into the network error issue. It definitely seems related to updates, but is more intermittent than I saw previously.
- The Moto G4 Play (Android 6.0) wasn't showing the error at all anymore on the existing install of version 2.0 from my day-in-the-life test.
- When I reinstalled version 1, turned off the network, and launched the app on the Moto G4 Play, it would hang at the splash screen. If I closed and reopened it, it would show the network error. If I turned network back on, closed, and reopened, confirmed it got version 2 OTA, then turned the network off and closed and reopened again, no network error.
- On the original install on the Galaxy S6 (Android 7.0) - v.2 installed over v.1 - it would get the network error if I launched in airplane mode, but not if all the radios are off. If I uninstalled/ reinstalled v.2, no more network error, even in airplane mode. And none of release channel v.2 installs on this phone showed the network error.

**Comment by llamaluvr** [comment] 2017-12-18 14:31
I won't post here every time we validate another test case (unless you want me to), but we were able to reproduce both behaviors on two separate phones with a different user using my release channel example above, and the findings are consistent with Android versions <= 6.0 being problematic:

Galaxy S7 (Android 7.0): worked
Galaxy S5 (Android 4.4.4): did not work correctly

**Comment by Danjavia** [comment] 2017-12-19 03:49
I have The same issue here. My app is not running after updating. And trying in nexus phone it shows my updated content but when it runs for second time, The default Initial react native view is appear. Some idea?. I burn 3 days it. Im so stressed right now.

**Comment by ide** [comment] 2017-12-20 00:55
It seems like the bundle cache across versions needs to be isolated better. It might be awhile before we look at the issue more closely since we have 200+ other open issues and just want to acknowledge we've seen this report but can't make time-sensitive promises.

**Comment by esamelson** [comment] 2018-02-28 19:33
Hey all, I found the root cause of this issue and can confirm it will be fixed in SDK 26 🎉 closing this for now, but feel free to reopen (or open a new issue) if the issue persists after you upgrade to 26, which should be out soon.

**Closed by esamelson** 2018-02-28 19:33 UTC
Labels: project: android-runtime

**Comment by appjitsu** [comment] 2018-03-29 14:30
So to make sure I understand, SDK 26 will have the ability to automagically restart an app deployed through the app stores when you publish an update through the XDE?

**Comment by marcosmartinez7** [comment] 2018-03-30 18:24
+1 to @appjitsu question, what happen if i make a exp build:android or exp build:ios after a few months of a release? the apk/ipa generated will be replaced on stores?

**Comment by esamelson** [comment] 2018-03-31 00:43
Hi there -

@appjitsu - not quite, we don't currently have a way to send notifications out to running app builds when you publish a new version. What will happen is that after you publish an update, users will download the new version the next time they start the app. SDK 26 also includes a method for pinging our servers to see if an update is available, so you could do this periodically to emulate the behavior you want, but be careful you don't use too many network requests.

@marcosmartinez7 - in this case, the actual ipa/apk will not change, but when it's relaunched it will grab the new JS bundle you've published. See [here](http://localhost:3000/versions/latest/workflow/publishing#deploying-to-the-app-store-and-play-store) for more info. This behavior isn't new, the only thing that's new is the ability to control when & how in the app lifecycle these updates are downloaded.

In the future, it would be helpful if you could post questions you have to our [forums](https://forums.expo.io/) rather than an old github issue - that way, it's easier for other people with the same questions to find answers in the future! :) We try to be just as responsive in both places.
