### ISSUE TITLE
Bar code scanner not working reliably at Google Pixel XL, But works on other phones.

### ISSUE THREAD

**Issue by chenzhenxi** [expo/expo#1024] opened 2017-11-29 09:28 UTC
Environment:
SDK 22.0.0 and 23.0.0 
windows 10/high sierra
node 8.4.0/node 8.9.1
Android 8.0.0

I tried the exact same code at multiple devices with 
I have tried different way to install app, using USB and using expo bar code scanner. clean cache, make sure expo have every persimmon.
Bar code scanner works perfect at Nexus 5 and Galaxy S8. (system version lower then Android 8.0.0)
But not working reliably at Google Pixel XL, My phone's camera is working perfect, I tried other apps that's have bar code scanner(e.g. line, wechat), it's working perfect.

Also I tried at snacks example,(SDK 20.0.0) it's work perfect at my pixel xl.

code is something like this.
```
<BarCodeScanner
            style={{ flex: 1 }}
            onBarCodeRead={({ type, data }) => alert(`type ${type} and data ${data}!`)}
/>
```

Actions:
1. open app by using expo app bar code scanner.
2. loaded the app, open camera screen, and guide the camera to bar code

Expect:
1. Should see a camera view
2. Should see a popup with type and data

Result:
1. Camera view looks good, and have auto focus
2. Only successful recognize bar code for once or twice, not reliable, 90%+ chance can't recognize bar code

**Comment by chenzhenxi** [comment] 2017-12-01 23:05
Updated, did more test, I think maybe related to Android 8.0?

**Comment by chenzhenxi** [comment] 2017-12-12 02:59
Tested at Pixel 2 (8.0.0) and Pixel xl (8.1.0), appeal have the same issue.

**Comment by aalices** [comment] 2017-12-14 09:09
@chenzhenxi we're about to change the library used for barcodes recognition - I hope this will help

**Comment by chenzhenxi** [comment] 2017-12-17 12:01
@aalices  working at sdk 24.0.0!!. thank you

**Comment by ledfusion** [comment] 2018-04-25 22:55
It seems that the problem is selectively appearing again.

Both in the Expo Client app and in Standalone binaries:

* iPhones read barcodes well
* Most Androids work as well
* But some Samsung's fail to scan on SDK v26

We have tried everything (clean, reinstall, USB debugging, release binaries, etc). Every alternative QR reader will work, but the Expo client and the compiled Expo apps won't :(

Is anyone else facing the same situation?
Thank you

**Comment by aalices** [comment] 2018-05-18 15:01
I'm planning to create a fallback to zxing (the lib that was used previously), hopefully this will be out with next SDK - you can folow this issue: https://github.com/expo/expo/issues/1591. I'll close this one

**Closed by aalices** 2018-05-18 15:01 UTC
Labels: project: android-runtime
