### ISSUE TITLE
App crashes after update to SDK 37

### ISSUE THREAD

**Issue by jeffersonxavier** [expo/expo#7608] opened 2020-04-02 14:12 UTC
### Environment

Expo CLI 3.17.8 environment info:
    System:
      OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmPackages:
      expo: ~37.0.3 => 37.0.3 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.17.8

1. SDK Version: 37
2. Platforms(Android/iOS/web/all): Android 8.1, Motorola G5 Plus

### Steps to Reproduce

Run: expo start and read the QRCode with expo in device

### Expected Behavior

In Emulator all works fine. But in my device doesn't works.

### Actual Behavior

When finish download app to device throws the exception:

Exception in HostObject::get(propName:NativeUnimoduleProxy): java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=3

### Reproducible Demo

My project on github: https://github.com/jeffersonxavier/clone-apps/tree/master/nubank-clone

**Comment by cruzach** [comment] 2020-04-02 14:22
@jeffersonxavier I tested your project on an android device and wasn't able to reproduce the error message. Could you provide more details as to how to reproduce the problem, maybe it happens on a particular screen?

**Comment by jeffersonxavier** [comment] 2020-04-02 14:42
Hi, thank you so much.
I tested in other device and works fine too, just like in the emulator. But, in this device Android 8.1, Motorola G5 Plus doesn't work.

**Comment by IjzerenHein** [comment] 2020-04-02 14:43
Can you provide us with a full stack trace of the problem ?

**Comment by jeffersonxavier** [comment] 2020-04-02 15:00
I can't see all stacktrace. The exception is show just on device screen.
This post https://forums.expo.io/t/app-crashes-on-certain-device-only/35152 seems to be the same problem.

**Comment by itsadeki** [comment] 2020-04-03 11:59
I fixed the bug by updating the Expo client in the Play store of my mobile device...

**Comment by jeffersonxavier** [comment] 2020-04-03 12:05
This bug happened precisely because I updated the Expo Client from SDK 36 to SDK 37.

**Comment by danilo900** [comment] 2020-04-03 14:32
I am with the same error after upgrading of SDK 36 to SDK 37.
Both simulator/device.

**Comment by danilo900** [comment] 2020-04-03 14:42
It worked here guys

rm -rf node_modules
npm cache clean --force
rm -rf .expo
rm package-lock.json
npm install

**Comment by jonathanstiansen** [comment] 2020-04-03 20:31
@jeffersonxavier can you say which device it was? Was it a simulator or normal device? Can you open Expo (not your app), just the Expo app on the phone - at the bottom it lists three things:
Device Id: xxxxxx
Client version: <client version>
Supported SDKs: <sdk versions>

Can you tell us what Client version it is and what supported SDKs are listed?

**Comment by jeffersonxavier** [comment] 2020-04-05 03:10
@jonathanstiansen thank you for your attention:
Devide Id: 1ff5-2b3c
Client Version: 2.15.0
Supported SDKS: 34, 35, 36, 37

**Comment by ccheever** [comment] 2020-04-06 22:26
@jeffersonxavier I can't reproduce this on my Android phone using the latest version of expo-cli (3.17.17) and the latest version of the Expo app from the Google Play Store

I'm going to close this issue for now. If you can isolate a a [minimal reproducible example]( https://stackoverflow.com/help/minimal-reproducible-example) then please open a new issue with that information.

**Closed by ccheever** 2020-04-06 22:26 UTC
Labels: project: android-runtime, status: needs more info
