### ISSUE TITLE
Facebook Audience Network is not delivering live ads to PRODUCTION build

### ISSUE THREAD

**Issue by Eden-Hazani** [expo/expo#11554] opened 2021-01-07 14:24 UTC
## 🐛 Bug Report

Hi,
The issue is simple When I run FAN requests (such as banner requests) from the expo development the requests go through and I can see test ads.

After building the app and publishing it to the google play store The ads won't show (also Bugsnag will not detect any issues with the ad calls)
On the Facebook ad statistics, I can actually see the number of ad requests that go from my live version but again, all I get is a white screen and no errors (development or production)
 
The one thing that I found online is that old Facebook SDK usage might be the problem here but I'm not sure.
Also, the Facebook monetization manager is saying that my ad units ARE requesting ads but again, not showing them.

Expo CLI 4.0.17 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ~38.0.8 => 38.0.10
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: managed

<FacebookAds.BannerAd
                    placementId={faceBookBannerId }  ---> My actual ad ID
                    type="standard"
                    onError={(error: any) => { logger.log(new Error(JSON.stringify(error.nativeEvent))) }}
  /> 
 
### Steps to Reproduce

Enter the app, no ads are showing

### Expected Behavior vs Actual Behavior

live ads should appear but they don't

**Comment by cruzach** [comment] 2021-01-07 16:17
possible duplicate of https://github.com/expo/expo/issues/10987

**Closed** 2021-01-11 18:10 UTC
Labels: Android, FacebookAds

**Comment by prakashtank** [comment] 2021-05-10 16:26
I'm facing same issue.
