### ISSUE TITLE
Expo.Svg undefined is not an objet

### ISSUE THREAD

**Issue by poptocrack** [expo/expo#682] opened 2017-09-26 08:45 UTC
I did the last SDK update (21.0.0) and when i run my app i got a red screen with the error bellow.

The error is coming from : 

    function MyCustomMarkerView(props) {
     return (
      <Svg width={50} height={50}>
        <Svg.Circle
          cx="25"
          cy="42"
          r={8}
          fill="black"
          />
          <Svg.Circle
            cx="25"
            cy="42"
            r={4}
            fill={COLORS.green}
            />
      </Svg>)
      }

The code was working well with 20.0.0.
Btw, the example from the doc isn't working either. Is there any workaround?

![screenshot_20170926-104130](https://user-images.githubusercontent.com/6168361/30850921-6ba55444-a2a7-11e7-8df5-581a79b215fb.png)

**Comment by fabien0102** [comment] 2017-10-11 15:19
Same case here, but working on 21.0.0 before my last npm install (cache problem so I removed all node_modules)

**Comment by fabien0102** [comment] 2017-10-11 16:44
Fixed! So after a longggggggggg debugging to find the dependency in cause, for my case, it works with `react@16.0.0-alpha.12` but broken with `react@16.0.0` 😉 

@nikki93 can you test this fix on your project?

**Comment by ide** [comment] 2017-10-18 02:02
@fabien0102's diagnosis sounds right. You need to be careful with the version of React you use with React Native. This is a Snack that shows Expo.Svg working with SDK 21. I'm going to close this issue out since I don't believe the cause is Svg.

**Closed by ide** 2017-10-18 02:02 UTC
Labels: project: sdk
