### ISSUE TITLE
`node_modules\metro-hermes-compiler\src\emhermesc.js:77`

### ISSUE THREAD

**Issue by SohelIslamImran** [expo/expo#17729] opened 2022-06-02 18:28 UTC
### Summary

When I start my project by `yarn start`/`expo start --android`/`expo start --android --clear` , the project runs for some time and gets stops and throws this error. I deleted `node_modules` folder and reinstalled packages, cleared caches, etc. But I still, have this error.

```sh
C:\Development\App\OfficeProjects\TillelIApp\node_modules\metro-hermes-compiler\src\emhermesc.js:77
          throw ex;
          ^

Error: EPERM: operation not permitted, lstat 'C:\Development\App\OfficeProjects\TillelIApp\.git\objects\maintenance.lock'       
Emitted 'error' event on NodeWatcher instance at:
    at C:\Development\App\OfficeProjects\TillelIApp\node_modules\jest-haste-map\build\watchers\NodeWatcher.js:275:14
    at FSReqCallback.oncomplete (node:fs:198:21) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path: 'C:\\Development\\App\\OfficeProjects\\TillelIApp\\.git\\objects\\maintenance.lock'
}
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

^45.0.4

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\.yarn\bin\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    Expo Workflow: managed

### Reproducible demo

Nothing

**Comment by brentvatne** [comment] 2022-06-28 02:41
duplicate of https://github.com/expo/expo-cli/issues/2021

**Closed by brentvatne** 2022-06-28 02:41 UTC
Labels: needs review

**Comment by sarib-app** [comment] 2023-03-13 12:39
To solve this problem you should try to reset cache of your metro or you should search if your metro server is running in any other project 
To  reset cache in react native :
npx react-native start --reset-cache

To reset cache in Expo:

Expo start --reset-cache
