### ISSUE TITLE
Expo.Google.logInAsync Does not return back to expo app after login

### ISSUE THREAD

**Issue by shahriar-b** [expo/expo#3238] opened 2019-01-17 08:50 UTC
### Environment

  Expo CLI 2.6.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.12.3 - C:\Users\XXX\AppData\Roaming\npm\yarn.CMD
      npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

Target: Android

### Steps to Reproduce

```
               const fbResult= await Expo.Google.logInAsync({
                    androidClientId: 'CLIENT_ID',
                    scopes: ['profile', 'email'],
                });
```

Use Expo.Google.logInAsync function on expo app running on emulator and device, once it is called the browser login will popup and once it is authenticated with google it will go back to the app but the result will never be sent to fbResult and eventually it will Timeout, and when running on physical device it is same but once it is called back from google it will open up Expo app not our own app.

Tested on a clean Expo init app on latest SDK with following package.json

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}
```

**Comment by vijay2330** [comment] 2019-01-17 10:35
Is this issue is resolved?

**Comment by kusaeva** [comment] 2019-01-17 12:52
duplicate? https://github.com/expo/expo/issues/3157

**Comment by shahriar-b** [comment] 2019-01-30 03:01
> Is this issue is resolved?

No it is not.

**Comment by NativLouie** [comment] 2019-02-18 00:02
i am also having this issue

**Comment by vandrieu** [comment] 2019-03-01 13:54
same issue for me, my Android clients cannot login in my app using their google account anymore...

**Comment by yunjay** [comment] 2019-03-07 02:58
I have this same issue, is there still no fix?

**Comment by EvanBacon** [comment] 2019-03-07 03:00
https://github.com/expo/expo/pull/3617

**Comment by vandrieu** [comment] 2019-03-08 15:14
> I have this same issue, is there still no fix?

Yes there is a fix, the bug was on the Android Expo app. Just update your Android Expo app and it will be fixed.

**Comment by cruzach** [comment] 2019-10-15 18:34
Looks like this was fixed, just tested on both Android and iOS in the most recent version of the Expo Client and confirmed that it navigated back correctly and returned the right `LogInResult`

If you still see this behavior, please make sure you're correctly configuring the [loginConfig](https://docs.expo.io/versions/latest/sdk/google/#methods). If you are, go ahead and open up a new issue with a repro, thanks!

**Closed by cruzach** 2019-10-15 18:34 UTC
Labels: Google
