### ISSUE TITLE
Cannot Run app on device:String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by saipranavrajesh** [expo/expo#1803] opened 2018-05-28 06:49 UTC
### Environment
Android Version:8.0.0
Device:Samsung Galaxy NOTE 8

### Steps to Reproduce

1.Opening snack on browser
2.Scanning QR on device to run the app
3.Expo shows "Something Went Wrong"

### Expected Behavior

App should run on device

### Actual Behavior

![screenshot](https://user-images.githubusercontent.com/33367248/40600819-6b6d3fc6-6270-11e8-87c6-c56b5aeafad5.jpeg)

There was unhandled error:
org.json.JSONException:Value<!DOCTYPE pf the type java.lang.String cannot be converted to JSONObject

**Comment by esamelson** [comment] 2018-06-20 16:49
Hi @saipranavrajesh - really sorry for the long delay here. Could you provide the link for the snack that causes this issue for you? Or is it any new snack?

**Comment by alake2** [comment] 2018-07-04 03:30
I just started getting this issue launching an app on an AVD running Android 7.1.1. One thing to note when I was starting the project Expo told me that the version of expo running on the device was outdated and it updated. Now I only get the error above.

**Comment by esamelson** [comment] 2018-07-04 17:30
Hi @alake2 - this error message suggests that a web request is returning an HTML page when a JSON object is expected. Could you share enough of your app's code to reproduce this issue (ideally in a [snack](https://snack.expo.io))?

**Comment by alake2** [comment] 2018-07-04 20:09
Hey @esamelson, I can see about getting a snack. It works fine when running on my actual device, I just get the error above when running on the emulator so I'm not sure what that means. It was working fine one minute, I got the message about expo being out of date, and then I started seeing the error. The app won't even initially load on the emulator. I uninstalled expo on the emulator and had Expo XDE reinstall it but that didn't fix it either.

**Comment by alake2** [comment] 2018-07-05 16:31
@esamelson, it seems to be working now. Exponent asked me to enable something (I forget what it is atm) but after that it started loading. Weird how it wasn't working for two days and then randomly worked itself out.

**Comment by esamelson** [comment] 2018-07-05 17:14
Hi @alake2 - how odd, but glad it's working now! Perhaps it was a transient caching issue or something 🤔 I'm going to go ahead and close this for now, but do let us know if the problem returns or if you can find a way to reliably reproduce it.

**Closed by esamelson** 2018-07-05 17:14 UTC
