### ISSUE TITLE
'Could not encrypt the value for SecureStore' error on android standalone app

### ISSUE THREAD

**Issue by xcarpentier** [expo/expo#814] opened 2017-10-20 13:46 UTC
**Context**

* Error in standalone app on android
* Work fine in Expo app
* SDK 22

**Android java stack trace**
```
W/SecureStoreModule(23138): java.security.spec.InvalidParameterSpecException: no constructor found!
W/SecureStoreModule(23138): 	at com.android.org.bouncycastle.jcajce.provider.symmetric.AES$AlgParamsGCM.localEngineGetParameterSpec(AES.java:462)
W/SecureStoreModule(23138): 	at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseAlgorithmParameters.engineGetParameterSpec(BaseAlgorithmParameters.java:24)
W/SecureStoreModule(23138): 	at java.security.AlgorithmParameters.getParameterSpec(AlgorithmParameters.java:257)
W/SecureStoreModule(23138): 	at abi22_0_0.host.exp.exponent.modules.api.SecureStoreModule$AESEncrypter.createEncryptedItem(SecureStoreModule.java:429)
W/SecureStoreModule(23138): 	at abi22_0_0.host.exp.exponent.modules.api.SecureStoreModule$HybridAESEncrypter.createEncryptedItem(SecureStoreModule.java:566)
W/SecureStoreModule(23138): 	at abi22_0_0.host.exp.exponent.modules.api.SecureStoreModule.setItemImpl(SecureStoreModule.java:132)
W/SecureStoreModule(23138): 	at abi22_0_0.host.exp.exponent.modules.api.SecureStoreModule.setValueWithKeyAsync(SecureStoreModule.java:93)
W/SecureStoreModule(23138): 	at java.lang.reflect.Method.invoke(Native Method)
W/SecureStoreModule(23138): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/SecureStoreModule(23138): 	at abi22_0_0.com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
W/SecureStoreModule(23138): 	at abi22_0_0.com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
W/SecureStoreModule(23138): 	at abi22_0_0.com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
W/SecureStoreModule(23138): 	at android.os.Handler.handleCallback(Handler.java:739)
W/SecureStoreModule(23138): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/SecureStoreModule(23138): 	at abi22_0_0.com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
W/SecureStoreModule(23138): 	at android.os.Looper.loop(Looper.java:135)
W/SecureStoreModule(23138): 	at abi22_0_0.com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
W/SecureStoreModule(23138): 	at java.lang.Thread.run(Thread.java:818)
```

**Into the code**

https://github.com/expo/expo/blob/45307852a818da7fac7171d1539b3449021d27dc/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/SecureStoreModule.java#L141

**Comment by ide** [comment] 2017-10-20 17:11
That stack trace is helpful, thanks. We are tracking this internally too, it looks like SpongyCastle is not getting registered above BouncyCastle.

**Comment by xcarpentier** [comment] 2017-10-23 08:03
Hello @ide,
Thank you for your return.
Do you have any idea about an ETA?

**Comment by ide** [comment] 2017-10-23 18:17
No ETA, nothing in the short term. In the meantime I would recommend falling back to AsyncStorage.

**Comment by ide** [comment] 2017-10-27 06:37
We think we know the bug and why it's affecting just standalone clients. I have a PR up internally and next it needs to be reviewed and merged and then deployed to the standalone app builders so it'll take sometime but is in motion.

**Comment by felipebraga** [comment] 2017-10-27 13:46
I faced this problem too, but not in standalone app.

**Comment by xcarpentier** [comment] 2017-11-02 15:18
@ide Any news on that?

**Comment by ide** [comment] 2017-11-02 19:08
No update now

**Comment by xcarpentier** [comment] 2017-11-06 08:32
Hello @ide,

I should make a production version with the android standalone app soon (next week) and this SecureStore is really important.

Is that possible to know if it's possible to have the fix build before next week?

**Comment by ide** [comment] 2017-11-09 22:27
Closing this since we updated the standalone builders with a fix for SDK 22 and up. This doesn't affect ExpoKit -- the fix for that will go out with SDK 23.

**Closed by ide** 2017-11-09 22:27 UTC
Labels: project: client-android, project: sdk

**Comment by ShMcK** [comment] 2018-02-21 18:24
Having this issue with SDK 25 on Android Pixel.

**Comment by xcarpentier** [comment] 2018-04-23 06:45
Hi @ide,

I still have this issue for device ALE-L21 on Android 23.

**Comment by ide** [comment] 2018-04-23 21:53
This error gets thrown when there's one of many possible errors in the security implementation the device provides so it's hard to pin down exactly what it could be. If you can get more precise stack traces that show the issue we can maybe fix it.

**Comment by xcarpentier** [comment] 2018-04-24 06:29
Sorry I don't have a full stack trace just this error from sentry:
`Error: Could not encrypt the value for SecureStore`

**Comment by ide** [comment] 2018-05-07 17:40
No, we haven't any news.

**Comment by xcarpentier** [comment] 2018-05-07 21:26
@ide Why expo not fallback to AsyncStorage in case like that one?

**Comment by ide** [comment] 2018-05-07 21:44
I prefer not to hide details like that from developers, especially when a security-related API is failing open. You're welcome to use that code in your own application but I wouldn't feel right making it part of the Expo SDK.

**Comment by xcarpentier** [comment] 2018-05-07 21:53
I understand.
Unfortunatly this issue is real and I’m not sure when I should fallback...

Any ideas ?
Surrond a try catch on every set and get ?

**Comment by ikhilko** [comment] 2018-05-21 19:46
Same error:
```

**Comment by oleonardo** [comment] 2018-05-23 16:29
The issue happened here when I reinstalled the app .apk or expo app. 

Context: 

- SDK 27.0.1

Code: `E_SECURESTORE_DECRYPT_ERROR`
Stack:
`Error: Could not decrypt the item in SecureStore
    at createErrorFromErrorData (blob:http://localhost:19001/67812197-ef47-4492-912e-ed6661ea0201:2342:17)
    at blob:http://localhost:19001/67812197-ef47-4492-912e-ed6661ea0201:2294:27
    at MessageQueue.__invokeCallback (blob:http://localhost:19001/67812197-ef47-4492-912e-ed6661ea0201:2736:18)
    at blob:http://localhost:19001/67812197-ef47-4492-912e-ed6661ea0201:2481:18
    at MessageQueue.__guardSafe (blob:http://localhost:19001/67812197-ef47-4492-912e-ed6661ea0201:2649:11)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:http://localhost:19001/67812197-ef47-4492-912e-ed6661ea0201:2480:14)
    at http://localhost:19001/debugger-ui/debuggerWorker.js:70:58`

**Comment by chansuke** [comment] 2018-06-28 03:12
Same in here.
- Message: `Error: Could not decrypt the item in SecureStore `.
- SDK: 27.0.0
- Env: Expo App (in development)  
- Device: Lenovo pb2-690m (Android 6.0.1)

I tried in `ASUS_Z00AD` too but couldn't reproduce the error.

**Comment by degamer106** [comment] 2018-10-16 18:22
Hi @ide I'm seeing this issue again in Expo 30 but on Android 8.1.0 specifically.  It only happens when we uninstall and re-install the app on specific devices (see this thread: https://forums.expo.io/t/expo-30-stand-alone-app-error-decrypting-keystore-on-a-few-android-devices-running-android-8-1-0/14722).  The current workaround is to go to Device Settings and do a clear data for our app.  However, we require the UUID to be persisted across app installation as our Push Notification backend is dependent on it so this is not really an option.  Is there a solution for this?
