### ISSUE TITLE
[expo-router] Re-rendering after router methods are called from a different _layout route

### ISSUE THREAD

**Issue by cornejobarraza** [expo/expo#27042] opened 2024-02-11 11:13 UTC
### Minimal reproducible example

https://github.com/cornejobarraza/expo-router-issue

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

The router works expected when pushing/replacing a route inside tabs with the same `_layout.tsx` file, however when you go to a screen under a different layout and then push/replace back to the previous route, it causes the screen to be re-rendered every time you call any of the router methods:

https://github.com/expo/expo/assets/106721994/051d530c-ebb4-4635-9d0e-dc1efa65c31f

As you can see, the first two screen renders are normal and expected, I then switch between the tabs using the tab buttons themselves to show it works normally. After that, I click on the `TouchableOpacity` I added that does a `router.push` to the opposite tab when pressing the yellow text.

Initially this does not cause a re-render as demonstrated in the video, however once I go to the `/modal` screen and do a `router.push` back to the `/` route, the `console.warn` inside the `useEffect` added to each tab screen starts to emerge again.

I created the reproducible example using `npx create-expo-app --template navigation` to factor out any user/project error. I also started my local by clearing the bundler cache, that's why it takes a bit to start.

I'm not sure if this is the expected behavior but I don't remember this working like it does now. Please let me know if I should add anything else, thank you!

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
      Watchman: 2023.06.26.00 - /home/linuxbrew/.linuxbrew/bin/watchman
    npmPackages:
      expo: ~50.0.6 => 50.0.6 
      expo-router: ~3.4.7 => 3.4.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.1.3
    Expo Workflow: managed
```

**Comment by marklawlor** [comment] 2024-02-12 21:25
Duplicate of #26669. Should be fixed in next release :+1:

**Closed by marklawlor** 2024-02-12 21:25 UTC
Labels: needs review, Router
