### ISSUE TITLE
[expo-facebook] requestPermissionsAsync model doesn't close

### ISSUE THREAD

**Issue by yenkuan** [expo/expo#13842] opened 2021-07-30 08:30 UTC
### Summary

I was trying to make the facebook authentication on a manage workflow. So i implemented the method as the documentation said. It works perfectly on Expo go.

In standalone app, if safari has not logged in to facebook. The sdk will prompt the screen asking you if you want to make login with facebook app. Once i logged in with facebook app, facebook app redirects back the modal that was previously open never get closed so the authentication never completes.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

```
  Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.16.3/bin/yarn
      npm: 6.14.7 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.9.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

```import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View, TouchableWithoutFeedback, Alert } from 'react-native';
import * as Facebook from 'expo-facebook';

export default function App({props}) {
  
  const fbLogin = async () => {

    try {
      console.log('abc111123')
      await Facebook.initializeAsync({
        appId: 'xxxxxxx',
      });
      const {
        type,
        token,
        expirationDate,
        permissions,
        declinedPermissions,
      } = await Facebook.logInWithReadPermissionsAsync({
        permissions: ['public_profile', 'email']
      });
      
      if (type === 'success') {
        // Get the user's name using Facebook's Graph API

        Alert.alert('Logged in!', `Hi ${token}!`);
      } else {
        // type === 'cancel'
      }
    } catch ({ message }) {
      Alert.alert(`Facebook Login Error: ${message}`);
    }
  
  }

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <TouchableWithoutFeedback onPress={() => {
        fbLogin()
      }}><Text>Login</Text></TouchableWithoutFeedback>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by cruzach** [comment] 2021-08-02 14:19
> It works perfectly on Expo go

This maybe means there's an issue either in your facebook developer dashboard, or you haven't set up app.json properly https://docs.expo.dev/versions/latest/sdk/facebook/#configure--appjson

**Comment by yenkuan** [comment] 2021-08-06 10:05
I am confident that my app.json is set up properly. For more information, I tried to start an empty Expo project with only facebook login function, this problem still exist. When I switch to bare workflow,  I noticed the iOS project is missing FBDSKApplicationDelegate. After I added the FBDSKApplicationDelegate  to the project, it works perfectly on  bare workflow. 

This is the code I added to the bare workflow project
[https://imgur.com/a/UFFCNII](url)

**Comment by hi-paul** [comment] 2021-08-10 14:08
+1 similar issue on expo sdk 42 using EAS build

**Comment by seanlin-kuo** [comment] 2021-08-12 09:13
+1 same issue with me

**Comment by jade-h-kim** [comment] 2021-08-13 04:17
+1 same issue on ios with expo 42 (eas build)

**Comment by cruzach** [comment] 2021-08-13 13:56
I tested this using our test app](https://github.com/expo/expo/tree/master/apps/native-component-list) and it's working for me in Expo Go **and** after building with `eas build` both with the FB app installed and not installed.

I suggest comparing [your app.json setup](https://github.com/expo/expo/blob/master/apps/native-component-list/app.json#L26-L30)

**Comment by hi-paul** [comment] 2021-08-13 16:43
I checked and I think it's not that different.
Note that the production of my app is currently expo 40, and Facebook works well(same code).

**Comment by hi-paul** [comment] 2021-08-18 02:37
As a temporary measure, I modified the facebook app to not run by using the InfoPlist mod plugin and it works as expected.

```javascript
const withInfoPlist = require('@expo/config-plugins').withInfoPlist;
const fbSchemes = ['fbapi', 'fb-messenger-api', 'fbauth2', 'fbshareextension'];

module.exports = function withFacebook(config) {
  return withInfoPlist(config, (config) => {
    const existingSchemes = config.modResults.LSApplicationQueriesSchemes || [];

    for (const scheme of fbSchemes) {
      const index = existingSchemes.findIndex((s) => s === scheme);

      if (index > -1) {
        existingSchemes.splice(index, 1);
      }
    }

    config.modResults.LSApplicationQueriesSchemes = [...existingSchemes];

    return config;
  });
};

```

**Comment by BrodaNoel** [comment] 2021-10-03 09:16
I have the same problems with the same arepa to reproduce (logged out from facebook in safari).

This stuff was always (3 years) working perfectly. And now it doesn't work since I'm using EAS.

Anything we know about it?

https://user-images.githubusercontent.com/1837969/135747431-0d884568-74c2-4e1b-a4da-66a2a2c4804b.MOV

**Comment by BrodaNoel** [comment] 2021-10-03 09:22
@cruzach when you say it's working in the "test app", are you testing it with?:

- logged out in safari Facebook
- logged in in Facebook app

?

I just realized that nobody logged in with Facebook in my app since the first release I made with EAS. So, clearly an EAS related problem (or some breaking change in expo-Facebook I forgot to implement?)

**Comment by BrodaNoel** [comment] 2021-10-03 10:02
This is the code I'm running:

```js
  onContinueWithFacebookClick = async () => {
    this.setState({ isLoading: true });

    try {
      await Facebook.initializeAsync({ appId: '123123123123123' }); // changed the real number here, just for this github comment.

      const { type, token: facebookToken } = await Facebook.logInWithReadPermissionsAsync({
        permissions: ['public_profile', 'email'],
      });

      if (type === 'success') {
        // Try to Login
        const { isLoginOk } = await actions.user().loginWithFacebook({ facebookToken });

        if (isLoginOk) {
          duix.set('currentPage', 'Explore');
        } else {
          // If no Login, let's try to merge, or register
          const { isMergeOk } = await actions.user().tryToMergeWithFacebook({ facebookToken });

          if (isMergeOk) {
            await actions.user().loginWithFacebook({ facebookToken });
            duix.set('currentPage', 'Explore');

            actions.analytics.track('EVENT_MERGE_WITH_FACEBOOK');
          } else {
            this.props.onNext({
              selectedOption: 'username',
              facebookToken,
            });
          }
        }
      }
    } catch (error) {
      if (error.message) {
        actions.snacks.error({ message: error.message });
      }
    }

    this.setState({ isLoading: false });
  };
```

And this is my `app.json` file:

```json
{
  "expo": {
    "name": "NoFilter",
    "description": "NoFilter helps photographers and travelers to find the best photo spots nearby, and all around the world",
    "icon": "src/styles/imgs/nofilter-icon.png",
    "orientation": "portrait",
    "primaryColor": "#ffffff",
    "splash": {
      "backgroundColor": "#000",
      "resizeMode": "cover",
      "image": "src/styles/imgs/splash-screen-ph.png"
    },
    "notification": {
      "icon": "src/styles/imgs/noti-icon.png"
    },
    "version": "10.5.1",
    "slug": "no-filter-asdasdad",
    "scheme": "nofilter",
    "facebookScheme": "fb379133649596384",
    "facebookAppId": "379133649596384",
    "facebookDisplayName": "NoFilter",
    "facebookAutoInitEnabled": true,
    "assetBundlePatterns": [
      "node_modules/@expo/vector-icons/**/MaterialCommunityIcons.ttf",
      "node_modules/@expo/vector-icons/**/MaterialIcons.ttf",
      "node_modules/@expo/vector-icons/**/Feather.ttf",
      "node_modules/@expo/vector-icons/**/SimpleLineIcons.ttf",
      "src/styles/fonts/Montserrat/Montserrat-Regular.ttf",
      "src/styles/fonts/Montserrat/Montserrat-Medium.ttf",
      "src/styles/fonts/Montserrat/Montserrat-SemiBold.ttf",
      "src/styles/imgs/android-adaptive-foreground.png",
      "src/styles/imgs/main-background.jpg",
      "src/styles/imgs/nofilter-icon-android.png",
      "src/styles/imgs/nofilter-icon.png",
      "src/styles/imgs/nofilter-logo-v.png",
      "src/styles/imgs/noti-icon.png",
      "src/styles/imgs/splash-screen-ph.png",
      "src/styles/imgs/splash-screen-ph.jpg",
      "src/utils/translations/*.json",
      "src/drone/*.json"
    ],
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "broda-noel",
            "project": "nofilter",
            "authToken": "asdasdasd"
          }
        }
      ]
    },
    "updates": {
      "enabled": false
    },
    "ios": {
      "buildNumber": "10.5.1",
      "supportsTablet": true,
      "googleServicesFile": "./GoogleService-Info.plist",
      "bundleIdentifier": "app.no-filter.nofilter",
      "appStoreUrl": "https://itunes.apple.com/us/app/nofilter-photo-spots/id1445583976",
      "usesAppleSignIn": true,
      "config": {
        "googleMapsApiKey": "sdfsdf-kM7N37Ho",
        "googleSignIn": {
          "reservedClientId": "com.sdfsfdf707670-sdfsdfsdf"
        }
      },
      "infoPlist": {
        "NSLocationWhenInUseUsageDescription": "NoFilter uses your location to see how far you are from spots, and also to show you your position in the map",
        "NSPhotoLibraryUsageDescription": "NoFilter uses your library when you want to upload a photo to your feed, or a new profile picture",
        "NSPhotoLibraryAddUsageDescription": "NoFilter uses your library when you want to upload a photo to your feed, or a new profile picture",
        "NSUserTrackingUsageDescription": "NoFilter uses tracking only to track feature usage, in order to improve the app. No ADs at all",
        "UIBackgroundModes": [
          "fetch"
        ],
        "CFBundleAllowMixedLocalizations": true
      }
    },
    "android": {
      "versionCode": 105,
      "package": "app.no_filter.nofilter",
      "playStoreUrl": "https://play.google.com/store/apps/details?id=app.no_filter.nofilter",
      "icon": "src/styles/imgs/nofilter-icon-android.png",
      "adaptiveIcon": {
        "foregroundImage": "src/styles/imgs/android-adaptive-foreground.png",
        "backgroundColor": "#000000"
      },
      "config": {
        "googleMaps": {
          "apiKey": "AIzaSysdfsdfsdfoqT3eU"
        }
      },
      "googleServicesFile": "./google-services.json",
      "permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE"
      ],
      "useNextNotificationsApi": true
    },
    "platforms": [
      "android",
      "ios"
    ]
  }
}
```

And this is my Facebook dashboard:

<img width="998" alt="Screen Shot 2021-10-03 at 07 02 11" src="https://user-images.githubusercontent.com/1837969/135748882-3305e08e-502b-4756-bf21-bfb077170924.png">

Are you seeing anything weird here?

**Comment by BrodaNoel** [comment] 2021-10-03 11:10
I think there is a relationship between this bug and this one: https://github.com/expo/expo/issues/14453

I just changed my code to do this:
```
await Facebook.initializeAsync();
```
instead of this:
```
await Facebook.initializeAsync({ appId: '379133649596384' });
```

And I get this error:

[loading photo here...]

And that's weird, because I have that info in my `app.json` file:
```
    "facebookScheme": "fb379133649596384",
    "facebookAppId": "379133649596384",
    "facebookDisplayName": "NoFilter",
```

So, it's probably not even loading the other data, which then may result in this error

**Comment by jkk** [comment] 2021-11-08 21:14
We're also experiencing this issue using expo-dev-client built with EAS, Expo SDK 43, and a newly-created Facebook app. I've spent the last couple days troubleshooting.

I've narrowed it down to AppDelegate.m and openURL.

I was able to fix it by applying the following patch to our app after running `expo prebuild`, then building with EAS. 
The drawback that we have to commit the prebuild files, which we don't want to do.

```diff
 ios/ExampleApp/AppDelegate.m | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/ios/ExampleApp/AppDelegate.m b/ios/ExampleApp/AppDelegate.m
index f1b1f27..7e78a5f 100644
--- a/ios/ExampleApp/AppDelegate.m
+++ b/ios/ExampleApp/AppDelegate.m
@@ -16,6 +16,8 @@
 #import <React/RCTLinkingManager.h>
 #import <React/RCTConvert.h>
 
+#import <FBSDKCoreKit/FBSDKCoreKit.h>
+
 #if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
 #import <FlipperKit/FlipperClient.h>
 #import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
@@ -97,6 +99,9 @@ static void InitializeFlipper(UIApplication *application) {
 
 // Linking API
 - (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
+  if ([[FBSDKApplicationDelegate sharedInstance] application:application openURL:url options:options]) {
+    return YES;
+  }
   #if defined(EX_DEV_LAUNCHER_ENABLED)
   if ([EXDevLauncherController.sharedInstance onDeepLink:url options:options]) {
     return true;
```

(Tipped off by this issue: https://github.com/expo/expo/issues/13336)

I also noticed that, prior to applying this fix, the deep link handler we set up using `Linking.addEventListener` would receive a `"fb<APP_ID>://authorize..."` URL, which it does not after the fix.

expo-facebook has AppDelegate code, but apparently it's not working right. Maybe an ordering issue?

https://github.com/expo/expo/blob/master/packages/expo-facebook/ios/EXFacebook/EXFacebookAppDelegate.m

**Comment by jkk** [comment] 2021-11-12 16:13
Confirming that this is still happening on SDK 43 with the very latest dependencies:

```
expo-updates@0.10.15
expo-facebook@12.0.3
```

We have a workaround, but it means prebuilding on a branch, applying a patch, and building as a bare project in EAS. Not ideal. We are otherwise able to use the managed workflow just fine.

I'm not an expert in expo plugins, but it definitely seems like a bug in the way AppDelegate openURL customizations are applied.

**Comment by jkk** [comment] 2021-11-12 17:42
I've created a minimal reproduction with a fresh Expo install and a new Facebook app:

https://github.com/jkk/expo-facebook-login-bug

The readme has the exact steps to follow. Here's another video of it happening:

https://user-images.githubusercontent.com/5173/141509362-5010288a-a253-46a4-be6d-567929c01cb1.mp4

Would appreciate acknowledgment 🙏  @cruzach @tsapeta @Simek (not sure who is the AppDelegate or expo-facebook expert)

**Comment by jkk** [comment] 2021-11-12 18:24
For good measure I also created an `app_delegate_fix` branch with the fix applied. Here's the relevant commit:

https://github.com/jkk/expo-facebook-login-bug/pull/1/commits/9a2b4f80840a0881ddd3fed94f59c64a2dba8b7b

Video with fix applied:

https://user-images.githubusercontent.com/5173/141516188-cf10fe88-8378-43ed-af8b-8f266b09ecca.mp4

**Comment by Mihai-github** [comment] 2021-11-12 18:35
Hi, this issue is not solved yet or? Because I am facing the problem when I am trying to log in using Facebook I'm getting the following error and can not find a solution...

Error Message: [Error: An error occurred while trying to log in to Facebook]

**Comment by jkk** [comment] 2021-11-12 18:58
@Mihai-github it sounds like that may be a different issue. For this bug, there is no error per se. Expo is not handling the return URL from Facebook and so the login does not complete.

**Comment by Mihai-github** [comment] 2021-11-12 19:00
So the problem may be in my case that I don't provide a **callbacl_uri**?

This is the code that I am trying to use
```
try {
      await Facebook.initializeAsync({
        appId: "APP_ID",
      });

      const { type, token, expirationDate, permissions, declinedPermissions } =
        await Facebook.logInWithReadPermissionsAsync({
          permissions: ["public_profile", "email"],
        });

      //   const data = await Facebook.logInWithReadPermissionsAsync({
      //     permissions: ["public_profile", "email"],
      //   });

      if (data.type === "cancel") {
        return false;
      }
      const response = await fetch(
        `https://graph.facebook.com/me?fields=id,email,birthday,name,first_name,last_name,middle_name,picture&access_token=${data.token}`
      );
      const user = await response.json();
      this.facebookToken = data.token;
      console.log({ facebook: data });
      return { ...user, facebookToken: data.token };
    } catch (err) {
      console.log({ erroare: err });
      return err;
    }
```

**Comment by Mihai-github** [comment] 2021-11-12 19:01
Also for me the modal closes, but I get in the console the error I said above, and is such a generic error that I cannot figure out what's going on...

**Comment by jkk** [comment] 2021-11-12 19:05
@Mihai-github I recommend creating a separate issue or ask in the Expo forums

**Comment by Mihai-github** [comment] 2021-11-12 19:06
:), ok man... hope someone will help you too with your problem.

**Comment by Hello-Ni** [comment] 2021-11-25 17:18
anyone fixed this issue?

**Comment by BrodaNoel** [comment] 2021-11-25 17:20
No.

(Read that “.” with emphasis)

Broda Noel

**Comment by jorexe** [comment] 2021-11-26 11:26
Hey team! Not sure if it's correct to put this here, but have you found a temporary workaround for this? I've tried other libraries, but didn't work :( I don't want to switch to bare workflow.

**Comment by BrodaNoel** [comment] 2021-11-27 06:16
@jkk could you please explain how to implement your workaround? Seems like I will have to implement it, considering that this issue may be here around 2 or 3 more years (that's the average of time I wait for features in Expo. Like the in-app payment).

Thank you so much!

**Comment by hi-paul** [comment] 2021-11-27 16:36
This is my solution for EAS. Hope this helps someone.

```javascript
// plugins/ios/with-facebook.js
const { WarningAggregator, withAppDelegate } = require('@expo/config-plugins');

const linkingBlock =
  '- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {';

function modifyAppDelegate(appDelegate) {
  if (appDelegate.includes(linkingBlock)) {
    const integratedBlock =
      linkingBlock +
      `
      NSString *fbScheme = [NSString stringWithFormat:@"fb%@", NSBundle.mainBundle.infoDictionary[@"FacebookAppID"]];
      if ([[url scheme] isEqualToString:fbScheme]) {
          return [super application:application openURL:url options:options];
      }
    `;
    appDelegate = appDelegate.replace(linkingBlock, integratedBlock);
  }

  return appDelegate;
}

exports.withFacebook = (config) => {
  return withAppDelegate(config, (config) => {
    if (config.modResults.language === 'objc') {
      config.modResults.contents = modifyAppDelegate(
        config.modResults.contents
      );
    } else {
      WarningAggregator.addWarningIOS(
        'withFacebook',
        'Swift AppDelegate files are not supported yet.'
      );
    }
    return config;
  });
};
```
```javascript
// plugins/index.js
const { withFacebook } = require('./ios/with-facebook');

module.exports = function withSodaGift(config, props) {
  config = withFacebook(config);
  return config;
};
```
```javascript
// app.json
{
  ...,
  "plugins": ["./plugins", ...]
}
```

**Comment by jkk** [comment] 2021-11-28 20:21
@hi-paul Thank you for sharing! We've switched to using your plugin instead of a bare workflow branch.

@BrodaNoel @jorexe I recommend using hi-paul's plugin. It will allow you to stay within the managed workflow. Once the Expo team releases a proper fix, the plugin can be removed.

**Comment by BrodaNoel** [comment] 2021-11-28 21:41
@hi-paul I have 2 questions:

1. What is that `withSodaGift` ? hehe
2. Will that works with `await Facebook.logInWithReadPermissionsAsync` ? Or only with hooks?

**Comment by hi-paul** [comment] 2021-11-29 01:51
@BrodaNoel
1. It's mistake😅 and you can change it to any proper name but should be named using the following convention: with<Plugin Functionality> i.e. withMyApp.
2. I think it will works if you add this plugin.
3. No. you don't have to.

**Comment by jorexe** [comment] 2021-11-29 09:06
Thank you very much @hi-paul @jkk ! I will try the plugin today.

**Comment by BrodaNoel** [comment] 2021-11-29 11:44
I just tried it. Created a new version a published in TestFlight. Seems to be working OK.
Will try in production soon!

Thanks! You guys are awesome

**Comment by jorexe** [comment] 2021-12-03 16:33
It worked!!

**Comment by sbichenko** [comment] 2022-01-07 11:05
@hi-paul's [solution](https://github.com/expo/expo/issues/13842#issuecomment-980687705) works perfectly!

**Comment by berkaygurbuz** [comment] 2022-01-24 12:34
> This is my solution for EAS. Hope this helps someone.
> 
> ```js
> // plugins/ios/with-facebook.js
> const { WarningAggregator, withAppDelegate } = require('@expo/config-plugins');
> 
> const linkingBlock =
>   '- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {';
> 
> function modifyAppDelegate(appDelegate) {
>   if (appDelegate.includes(linkingBlock)) {
>     const integratedBlock =
>       linkingBlock +
>       `
>       NSString *fbScheme = [NSString stringWithFormat:@"fb%@", NSBundle.mainBundle.infoDictionary[@"FacebookAppID"]];
>       if ([[url scheme] isEqualToString:fbScheme]) {
>           return [super application:application openURL:url options:options];
>       }
>     `;
>     appDelegate = appDelegate.replace(linkingBlock, integratedBlock);
>   }
> 
>   return appDelegate;
> }
> 
> exports.withFacebook = (config) => {
>   return withAppDelegate(config, (config) => {
>     if (config.modResults.language === 'objc') {
>       config.modResults.contents = modifyAppDelegate(
>         config.modResults.contents
>       );
>     } else {
>       WarningAggregator.addWarningIOS(
>         'withFacebook',
>         'Swift AppDelegate files are not supported yet.'
>       );
>     }
>     return config;
>   });
> };
> ```
> 
> ```js
> // plugins/index.js
> const { withFacebook } = require('./ios/with-facebook');
> 
> module.exports = function withCustomPlugins(config, props) {
>   config = withFacebook(config);
>   return config;
> };
> ```
> 
> ```js
> // app.json
> {
>   ...,
>   "plugins": ["./plugins", ...]
> }
> ```

I follow all the steps but it gives error as follows : 
```\node_modules\@expo\config-plugins\build\plugins\withAndroidBaseMods.js: fs could not be found within the project or in these directories:     
  node_modules\@expo\config-plugins\node_modules
  node_modules

   8 | exports.withAndroidBaseMods = withAndroidBaseMods;
   9 |
> 10 | function _fs() {
     |           ^
  11 |   const data = require("fs");
  12 |
  13 |   _fs = function () {```


```
I am using app.config.js instead of app.json
```
plugins:['./plugins']
```
I am not sure where I am doing wrong thing

**Comment by jorexe** [comment] 2022-01-24 13:42
Try creating something like `with-facebook.js` and then in your config `plugins: ['./with-facebook']`

**Comment by berkaygurbuz** [comment] 2022-01-25 12:30
> Try creating something like `with-facebook.js` and then in your config `plugins: ['./with-facebook']`

It works thank you 🙏

**Comment by RenatoSerra22** [comment] 2022-03-07 02:03
Hello, facing the same issue, how does one solve this in a bare workflow?

Thank you!

**Comment by BrodaNoel** [comment] 2022-03-15 14:54
Anyone tried it in expo@44?

**Comment by RenatoSerra22** [comment] 2022-03-21 20:03
I was having this issue, after fixing it i started getting `Error with Facebook login` from a few users.
Any ideas?

**Comment by berkaygurbuz** [comment] 2022-03-22 14:01
@RenatoSerra22 if your app is in sandbox, be sure your test users in facebook developers page.

**Comment by RenatoSerra22** [comment] 2022-03-24 15:46
@berkaygurbuz  this was in release version

**Comment by bkamrani** [comment] 2022-05-06 02:54
I have this issue in Expo@43. I see @hi-paul has mentioned this solution is for EAS. Is there any alternative for the traditional `expo build`? Our app is crashing with EAS build. Thank you!

**Comment by BrodaNoel** [comment] 2022-05-06 03:17
@bkamrani the issue still there, but there is a workaround which is super simple to implement. Check [some comments above](https://github.com/expo/expo/issues/13842#issuecomment-980687705).

It's just a matter of adding a 2 new files and changing 1 line of code in app.json.
The good thing is that as soon as it gets fixed, the workaround will be easy to remove.

Be careful because SDK45 JUST (1 hour ago) got released, and I'm not sure if this workaround still works in SD45.
I can confirm it still works in SDK44.

**Comment by bkamrani** [comment] 2022-05-06 13:53
Thank you @BrodaNoel for your quick response! Agreed. The workaround worked for me. However, as I am now migrating to EAS (mainly due to this fix), the whole app crashes after the login and navigating to the home screen, which has been a new issue.

**Comment by BrodaNoel** [comment] 2022-05-06 15:49
I would recommend migrating to EAS as soon as possible. Maybe trying to fix the other issue will be simpler than this. Not sure.

Don't forget that legacy 'expo build' will be deprecated soon.

**Comment by tsapeta** [comment] 2022-05-06 17:17
I'm closing this issue as we've officially deprecated some third-party wrapper libraries, including `expo-facebook`. Please refer to the deprecation note on top of the docs page: https://docs.expo.dev/versions/latest/sdk/facebook

**Closed by tsapeta** 2022-05-06 17:17 UTC
Labels: needs more info, Facebook

**Comment by BrodaNoel** [comment] 2022-08-08 21:23
I can confirm this issue is solved after moving from `expo-facebook` to `react-native-fbsdk-next@10.0.0`.

This was broken in Expo SDK 44. I jumped to SDK 46, implemented `react-native-fbsdk-next`, and works.
Not sure what happen in SDK 45.

Thanks to all the devs that cooperated on creating the patch for fixing it while we waited for this official fix.

Thanks!
