### ISSUE TITLE
after using "useNextNotificationsApi": true notification push don't work android

### ISSUE THREAD

**Issue by khelifioussama** [expo/expo#10992] opened 2020-11-11 20:07 UTC
## 🐛 Bug Report
Hello ,
when i push notification using the  Expo Push Notification tool, without Adding "useNextNotificationsApi": true notification push work good but the listener didn't work so I add "useNextNotificationsApi": true then when I use the Expo Push notification tool I got the response from Listener in the log but the notification is not shown, any solution please ?

### Environment 
I am using Expo 39.0.0  and expo notification 0.7.2

**Comment by AdamJNavarro** [comment] 2020-11-11 23:02
Hey @AdamJNavarro, what device are you using to test notifications? Without seeing your code it's also difficult to provide any insights or help. Please provide a repro we can test on our end and make sure you follow our issue template when creating issues in the future.

**Comment by cruzach** [comment] 2020-11-13 14:13
@khelifioussama I'm going to close this report since there's not enough information here for us to investigate. 

If you're having trouble with notifications, I suggest you read through 
- https://docs.expo.io/versions/latest/sdk/notifications/
- https://docs.expo.io/push-notifications/overview/

As Adam mentioned, if you think there's a bug in `expo-notifications`, please include a minimal reproducible demo

**Closed by cruzach** 2020-11-13 14:13 UTC
Labels: Issue needs review, status: needs more info
