### ISSUE TITLE
[expo-in-app-purchases][iOS] TypeError: this._eventEmitter.removeSubscription is not a function

### ISSUE THREAD

**Issue by kesha-antonov** [expo/expo#14360] opened 2021-09-09 08:32 UTC
### Summary

Hi!

I'm getting this error
`TypeError: this._eventEmitter.removeSubscription is not a function`
after calling `setPurchaseListener` second time

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

11.0.1

### Environment

  Expo CLI 3.24.2 environment info:
    System:
      OS: macOS 11.5
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7322048
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: 0.65.1 => 0.65.1

### Reproducible demo or steps to reproduce from a blank project

Call setPurchaseListener 2 times

**Comment by bbarthec** [comment] 2021-09-24 13:07
Hello @kesha-antonov 👋 
Thank you for reporting this issue. It's seems to be similar to #14449. Apparently there's some change in `RN@0.65` affecting EventEmitter. [`react-native-unimodules@0.14.9`](https://www.npmjs.com/package/react-native-unimodules/v/0.14.9) and thus [`@unimodules/react-native-adapter@6.3.8`](https://www.npmjs.com/package/@unimodules/react-native-adapter/v/6.3.8) now contain the respective fix for this regression 🔧 
I'm tentatively closing this issue, but if the problem persists for some reason please be welcome to reopen 😊

**Closed by bbarthec** 2021-09-24 13:07 UTC
Labels: needs more info, InAppPurchases, React Native 0.65
