### ISSUE TITLE
React native - "AssertionError [ERR_ASSERTION]: Wrong number of arguments provided for static config plugin, expected either 1 or 2, got 3 "

### ISSUE THREAD

**Issue by germanmb23** [expo/expo#14180] opened 2021-08-25 19:10 UTC
I get this error and I dont know how to fix it, this is a bare expo project, I build this project before but now when I run "react-native run-android" I get this. I appreciate any help.

![Screenshot from 2021-08-25 16-13-09](https://user-images.githubusercontent.com/32777967/130851089-19fb848f-910e-4d7f-9ee3-e2e917ab2af5.png)

**Comment by cruzach** [comment] 2021-08-30 17:22
Closing because of no reproducible demo

**Closed by cruzach** 2021-08-30 17:22 UTC
