### ISSUE TITLE
Sdk 28 Notifications.getExpoPushTokenAsync() not working on standalone Android

### ISSUE THREAD

**Issue by magnusros** [expo/expo#1881] opened 2018-06-16 16:11 UTC
No response (wait forever) when running Notifications.getExpoPushTokenAsync() for Android standalone. Works fine in Expo and also IOS standalone.
FCM is used for Expo push notifications according to https://docs.expo.io/versions/v28.0.0/guides/using-fcm.

**Comment by magnusros** [comment] 2018-06-17 21:16
I re-tested and today it works without any code change:
https://forums.expo.io/t/sdk-28-notifications-getexpopushtokenasync-not-working-on-standalone-android-build/10696

**Comment by nicknovitski** [comment] 2018-06-19 01:07
From reading that thread, I understand that the app produced by `exp build:ios` and the local test of `exp start --no-dev --minify` both work correctly, but if you install the app created by `exp build:android`, the promise returned from `getEpxoPushTokenAsync` never resolves or rejects, is that correct?

What device are you testing this on? Are you sure that you're getting the `REMOTE_NOTIFICATIONS` permission first?

**Comment by magnusros** [comment] 2018-06-19 15:54
Yes, `exp build:ios` and `exp start --no-dev --minify` worked fine but not if I installed the app via adb after building with `exp build:android`. I used async/await syntax without try/catch. I have today try/catch to my code now to see result if promise rejects. 
But today when I test then I get response from getExpoPushTokenAsync directly with token also for Android standalone build (exp build:android).

**Comment by magnusros** [comment] 2018-06-24 11:00
When getExpoPushToken not working:
1, Logout and login with the same user => Still not working.
2, Restart app => Not working
3, Reinstall app => Not working
4, Logout and login with another google user => I start getting pushTokens again. Then it also works when go back to first user.

**Comment by esamelson** [comment] 2018-06-26 01:01
Hi @magnusros - thanks for letting us know. We haven't received any other reports of this behavior being tied to logging in and out of specific google user accounts but we will look into this. To clarify, you mean you are using `Expo.Google.loginAsync` to log in as a google user in your app?

**Comment by magnusros** [comment] 2018-06-26 14:57
Yes using Expo.Google.loginAsync. 
And I call Notifications.getExpoPushTokenAsync() on every firebase.auth().onAuthStateChanged. 
But I have now changed my code to unsubscribe from onAuthStateChanged on app componentWillUnmount(). Since then I haven't got any problem with getExpoPushTokenAsync(). I will keep you updated...

**Comment by magnusros** [comment] 2018-06-26 20:50
Problem still valid. Got the same problem again after reinstall via adb.

**Comment by magnusros** [comment] 2018-06-28 15:30
If remove my link to google-services.json from app.json it works much better. Does this mean GCM will be used instead of FCM?

**Comment by ide** [comment] 2018-07-02 17:37
If you rebuild your APK without google-services.json I believe it will use the legacy GCM system. However, the delivery rate is very low since we believe AWS or Google changed a policy on their side with regard to delivering notifications to standalone apps and it is common to see your device tokens get immediately unregistered (this is AWS/Google signaling not to use the token again), so we are deprecating - though not removing - support for GCM soon: https://blog.expo.io/upcoming-changes-to-the-expo-push-notification-service-summer-2018-254030da786b

**Comment by esamelson** [comment] 2018-07-02 21:54
Hi @magnusros - we're trying to reproduce your problem ourselves but cannot. It is interesting that the promise neither resolves nor rejects. There are only a couple of ways in which this can happen, so to help us narrow down the cause, could you confirm that internet connectivity is definitely not an issue here? (e.g. you are able to reach expo's servers just fine even when you're unable to get a push token?)

**Comment by magnusros** [comment] 2018-07-03 21:04
Hi @esamelson, no problem with internet connection. I can reproduce the problem when having both WLAN and 4G mobile network. 
I have retested to add "googleServicesFile": "./google-services.json", in app.json under android config and then I get the problem again after reinstall of application with adb. 
If I remove "googleServicesFile": "./google-services.json" the problem disappear.
I have console log to verify that Permission for Notification is granted just before calling Notifications.getExpoPushTokenAsync(). Token never resolve or reject.

   ```
 ...
    console.log('Before getExpoPushTokenAsync', finalStatus)
    Notifications.getExpoPushTokenAsync().then( token => {
      console.log('token', token)
      resolve(token)
    }).catch( err => {
      console.log('token err', err)
      reject('Get pushNotificaion failed')
    })
```

**Comment by ide** [comment] 2018-07-10 00:17
What happens with this code?

```
let statusResponse = await fetch('https://expo.io/status/live');  // DEBUG ONLY
let statusText = await statusResponse();
console.log(statusText);
```

You should see "OK". If you get an error or the request hangs, this may indicate connectivity issues from the device to Expo servers, which is necessary to get an Expo push token.

**Comment by raphaelrk** [comment] 2018-07-11 04:12
Also was running into this issue, with `Notifications.getExpoPushTokenAsync()` sometimes hanging and sometimes not on iOS. I ran @ide's statusResponse code and found my internet connection wasn't working. I switched from wifi to LTE and all of the promises resolved / I got push tokens.

**Comment by magnusros** [comment] 2018-07-11 11:20
If I print statusResponse I get: 
```
{ type: 'default',
07-11 13:13:07.581   589   666 I ReactNativeJS:   status: 200,
07-11 13:13:07.581   589   666 I ReactNativeJS:   ok: true,
07-11 13:13:07.581   589   666 I ReactNativeJS:   statusText: undefined,
07-11 13:13:07.581   589   666 I ReactNativeJS:   headers: 
07-11 13:13:07.581   589   666 I ReactNativeJS:    { map: 
07-11 13:13:07.581   589   666 I ReactNativeJS:       { 'cache-control': [ 'public, max-age=0' ],
07-11 13:13:07.581   589   666 I ReactNativeJS:         'strict-transport-security': [ 'max-age=15724800' ],
07-11 13:13:07.581   589   666 I ReactNativeJS:         vary: [ 'Accept-Encoding, Origin' ],
07-11 13:13:07.581   589   666 I ReactNativeJS:         connection: [ 'keep-alive' ],
07-11 13:13:07.581   589   666 I ReactNativeJS:         'content-length': [ '2' ],
07-11 13:13:07.581   589   666 I ReactNativeJS:         'content-type': [ 'text/plain; charset=utf-8' ],
07-11 13:13:07.581   589   666 I ReactNativeJS:         date: [ 'Wed, 11 Jul 2018 11:13:05 GMT' ],
07-11 13:13:07.581   589   666 I ReactNativeJS:         server: [ 'nginx/1.13.12' ] } },
07-11 13:13:07.581   589   666 I ReactNativeJS:   url: 'https://expo.io/status/live',
07-11 13:13:07.581   589   666 I ReactNativeJS:   _bodyInit: 
07-11 13:13:07.581   589   666 I ReactNativeJS:    { _data: 
07-11 13:13:07.581   589   666 I ReactNativeJS:       { size: 2,
07-11 13:13:07.581   589   666 I ReactNativeJS:         offset: 0,
07-11 13:13:07.581   589   666 I ReactNativeJS:         blobId: 'f272fbb7-58f8-4909-8134-f820c143a967' } },
07-11 13:13:07.581   589   666 I ReactNativeJS:   _bodyBlob: 
07-11 13:13:07.581   589   666 I ReactNativeJS:    { _data: 
07-11 13:13:07.581   589   666 I ReactNativeJS:       { size: 2,
07-11 13:13:07.581   589   666 I ReactNativeJS:         offset: 0,
07-11 13:13:07.581   589   666 I ReactNativeJS:         blobId: 'f272fbb7-58f8-4909-8134-f820c143a967' } } }
```
statusResponse did not resolve so no print of statusText

**Comment by ide** [comment] 2018-07-11 18:40
Sorry, there was a small bug in my code snippet -- `response.text()` is the promise to await. Regardless it looks like you were able to connect to the network successfully so the problem is likely elsewhere.

> If removing google-services.json from app.json it works.

Along with the other symptoms, this indicates the issue is probably related to the FCM implementation on the client side. I'm not sure when we'll get around to looking into this more but I imagine the bug to be somewhere in the notifications Java code.

**Comment by magnusros** [comment] 2018-07-11 18:49
@ide thanks for the help you have provided.

**Comment by magnusros** [comment] 2018-07-14 16:31
@ide, What fields are used in google-services.json for FCM? 
I have the following fields: 
```
{
  "project_info": {
    "project_number": "XXXXXXXXX",
    "firebase_url": "https://XXXXXXXXX",
    "project_id": "XXXXXXXXX",
    "storage_bucket": "XXXXXXXXX"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:XXXXXXXXX:android:XXXXXXXXX",
        "android_client_info": {
          "package_name": "com.XXXXXXXXX.XXXXXXXXX"
        }
      },
      "oauth_client": [
        {
          "client_id": "XXXXXXXXX-XXXXXXXXX.apps.googleusercontent.com",
          "client_type": 1,
          "android_info": {
            "package_name": "com.XXXXXXXXX.XXXXXXXXX",
            "certificate_hash": "XXXXXXXXX"
          }
        },
        {
          "client_id": "XXXXXXXXX-XXXXXXXXX.apps.googleusercontent.com",
          "client_type": 1,
          "android_info": {
            "package_name": "com.XXXXXXXXX.XXXXXXXXX",
            "certificate_hash": "XXXXXXXXX"
          }
        },
        {
          "client_id": "XXXXXXXXX-XXXXXXXXX.apps.googleusercontent.com",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "XXXXXXXXX"
        }
      ],
      "services": {
        "analytics_service": {
          "status": 1
        },
        "appinvite_service": {
          "status": 2,
          "other_platform_oauth_client": [
            {
              "client_id": "XXXXXXXXX-XXXXXXXXX.apps.googleusercontent.com",
              "client_type": 3
            },
            {
              "client_id": "XXXXXXXXX-XXXXXXXXX.apps.googleusercontent.com",
              "client_type": 2,
              "ios_info": {
                "bundle_id": "com.XXXXXXXXX.XXXXXXXXX"
              }
            }
          ]
        },
        "ads_service": {
          "status": 2
        }
      }
    }
  ],
  "configuration_version": "1"
}
```

**Comment by ide** [comment] 2018-07-14 21:37
AFAIK you can use the default google-services.json from your logged-in FCM page on Firebase's developer site.

**Comment by magnusros** [comment] 2018-07-15 13:10
Ok thanks @ide , Thats what i have done. Just wanted to check if something was wrong with the file generated from my Firebase account.

**Comment by randomjunk** [comment] 2018-07-25 16:45
FWIW we've run into this exact same problem now.

This was on a dev device with a standalone build of our app. getExpoPushTokenAsync() just doesn't resolve, so hangs your app if you wait for the response. It works on other installs on other devices, and on the same device running the same app built using a different slug.

This appears to be an expo issue with FCM specifically.
It's very hard to debug as we can't figure out how to reproduce, and we've only seen it once on our own hardware.

**Comment by esamelson** [comment] 2018-07-31 22:30
Hi, we've made some changes to the client-side FCM implementation with SDK 29. Could anyone on this thread try upgrading and see if you continue to experience this issue? We've still been unable to reproduce it, unfortunately 😞

**Comment by aatreya** [comment] 2018-08-01 01:35
Just tested in SDK 29 - still occurring.

**Comment by mcottingham** [comment] 2018-08-03 22:04
I think that I'm experiencing this issue as well.  I'm on SDK 29.

I followed the steps listed in https://docs.expo.io/versions/v29.0.0/guides/push-notifications and https://docs.expo.io/versions/v29.0.0/guides/using-fcm.

```
  const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS)
  if (existingStatus !== 'granted') {
    await Permissions.askAsync(Permissions.NOTIFICATIONS)
  }
  const token = await Notifications.getExpoPushTokenAsync()
```

```
[Unhandled promise rejection: Error: Couldn't get GCM token for device]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:121:42 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:78:57 in <unknown>
- ... 5 more stack frames from framework internals
```

Is this supposed to fetch a token when using expo client on Android?  Or do I need to build a standalone app?

**Comment by magnusros** [comment] 2018-08-04 15:06
@esamelson Thanks, you have solved the issue I experienced in previous versions. I have installed the apk multiple times without any issues.

**Comment by cristiankmb** [comment] 2018-08-05 23:48
Hi guys,
@magnusros  @esamelson 
¿Any solutions?

So, i trying get ExpPushToken too, but when i use the Notifications.getExpoPushTokenAsync() i received the following result:  **Error: The Expo push notification service is supported only for Expo projects. Ensure you are logged in to your Expo developer account on the computer from which you are loading your project.**  

-I'm using the client Exp App on ios real device to run the app
-I'm working with another project and in this use expo V26.0.0 and work fine with push notifications

**CURRENT SETTINGS**
**app.json**
"sdkVersion": "27.0.0",

**package.json**
"dependencies": {
    "base-64": "^0.1.0",
    "eslint-config-rallycoding": "^3.1.0",
    "expo": "^27.0.1",
    "lodash": "^4.17.5",
    "moment": "^2.22.0",
    "native-base": "^2.4.1",
    "prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-router-flux": "^4.0.0-beta.28",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  }

¿Will i need come back to version Expo 26.0.0  ?

**Comment by binki** [comment] 2018-08-06 14:43
@cristiankmb What do you have in `package.json` under `scripts.start`? It seems that expo requires you to use `exp start` instead of `react-native-scripts start`.

To change an existing project, you can do `npm install -D exp` and edit `package.json` `scripts.start` to contain `exp start` and suddenly notifications will start working for you. Have you tried that?

**Comment by cristiankmb** [comment] 2018-08-06 16:35
@binki this is that i have in package.json 

{
 "name": "App",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.14.0",
    "jest-expo": "~27.0.0",
    "react-test-renderer": "16.3.1"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "base-64": "^0.1.0",
    "eslint-config-rallycoding": "^3.1.0",
    "expo": "^27.1.1",
    "lodash": "^4.17.5",
    "moment": "^2.22.0",
    "native-base": "^2.4.1",
    "prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-router-flux": "^4.0.0-beta.28",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  }
}

**Comment by binki** [comment] 2018-08-06 17:00
@cristiankmb Right, that won’t work. Expo produces the error message if you use `react-native-scripts start` instead of `exp start`. To work around this and get things working at all in your development environment, what you can try is to replace

```
"start": "react-native-scripts start",
```

with

```
"start": "exp start",
```

and be sure to run the following command once to add `exp` to your `devDependencies` prior to running `npm start`:

```
npm install -D exp
```

**Comment by cristiankmb** [comment] 2018-08-06 20:55
@binki Thnaks for the help. Work for me !

**Comment by mcottingham** [comment] 2018-08-07 23:28
@binki Worked for me as well!  TYVM!

**Comment by kevinzhangftw** [comment] 2018-08-08 19:15
@binki Thanks. worked for me too, on iOS the logs move to terminal instead of browser inspector console

**Comment by fredrivett** [comment] 2018-08-24 16:09
For any folks reading this and still getting the error message after running `exp start`, make sure to login with the same Expo account on both the computer you run the `exp start` command from, and the device you're testing with.

**Comment by 333f1t51b21c1p69mf86ctw611258** [comment] 2018-09-10 04:54
The issue will be resolved once you logged in expo by command.
`exp login`

**Comment by binki** [comment] 2018-09-23 03:46
@molaga Are you able to show code? What do you mean by “production”? I think you can get the behavior you describe simply by not `await`ing the permissions request which would result in permission being granted after you try to get the token on the first launch but permissions already being granted prior to your second launch. Of course, maybe you are doing things right and there is actually an issue.

**Comment by esamelson** [comment] 2018-09-27 23:02
Hi all -- this thread is becoming very confusing as there are multiple issues being discussed here. As the original poster said that their problem has been solved, I'm going to go ahead and close this issue. If anyone is experiencing issues like this one, please **open a new issue** and follow the template there to the best of your ability instead of posting here. Thanks all!

**Closed by esamelson** 2018-09-27 23:02 UTC
Labels: project: android-runtime
