### ISSUE TITLE
Attempted to get instance of PaymentConfiguration without initialization

### ISSUE THREAD

**Issue by akhilesh-mourya** [expo/expo#5889] opened 2019-10-06 19:28 UTC
I'm using expo-payments-stripe with ExpoKit SDK 33. Users of my application is experiencing the following issue:

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.mypackagename.app/com.stripe.android.view.AddPaymentMethodActivity}: java.lang.IllegalStateException: Attempted to get instance of PaymentConfiguration without initialization.

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eccocar.himobility.app/com.stripe.android.view.AddPaymentMethodActivity}: java.lang.IllegalStateException: Attempted to get instance of PaymentConfiguration without initialization.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2916)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1811)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6694)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Mainly coming in Xiaomi and Samsung Android phone with OS android 8 & 9

**Comment by cruzach** [comment] 2019-10-31 19:13
duplicate of https://github.com/expo/expo/issues/5890

**Closed by cruzach** 2019-10-31 19:13 UTC
Labels: Payments, project: android-runtime, project: expokit
