### ISSUE TITLE
[expo-file-system] uploadAsync() not working

### ISSUE THREAD

**Issue by svm1** [expo/expo#10340] opened 2020-09-23 22:16 UTC
Hello, folks. Hope this is the right place to post about this.
I have been having a great deal of difficulty getting the [`uploadAsync()`](https://docs.expo.io/versions/latest/sdk/filesystem/#filesystemuploadasyncurl-fileuri-options) function to work - invoking it on iOS consistently yields a response that returns an empty body. 

I noticed issue #9165 that mentions this issue, and PR #9166 that fixed the issue - I have upgraded to the latest Expo SDK 39, but am still facing this issue. At this point, I am not sure if it is a recurring bug or if I am invoking the function wrong, though I am following the documentation carefully.

As for my use case, I am following a procedure similar to that outlined in [this wonderful example here](https://github.com/expo/audio-recording-example) to record an audio message - I am now trying to use `uploadAsync()` to upload said audio file to a server.

Just wanted to ask, is the issue with the function confirmed to have been fixed? Also, is there anywhere I can find some sample usage of this functionality to ensure I am following it correctly? Been stuck at this for a good while and would appreciate any advice.

**Comment by barthap** [comment] 2020-09-23 23:09
The issue was fixed then, but it seems that something broke again in the meantime, because [this demo](https://snack.expo.io/@barthap10/expo-file-system-uploadasync-bug-demo) also stopped working. I'll investigate it soon.

**Comment by barthap** [comment] 2020-09-24 06:27
Hello again @svm1 

I tested it more and it works for me in latest Expo Client from App Store (2.17.1), with `sdkVersion` set to 39.0.0 in `app.json`.
I also debugged the native code and works as expected in SDK 39. The only thing that doesn't work for some reason is Snack.

Please try running this example, but without using Snack: https://snack.expo.io/@barthap10/expo-file-system-uploadasync-bug-demo

**Comment by brentvatne** [comment] 2020-09-25 20:08
cc @IjzerenHein because this impacts snack

**Comment by IjzerenHein** [comment] 2020-10-07 12:59
Hi! I've verified this on Snack and confirmed that everything works correctly when using SDK 39.

There was however an issue with Snack, which when changing the SDK version would not always update the QR code and you sometimes unknowingly used a different SDK version. I believe this is the reason why it appeared to not work on Snack, as you were unknowingly still using SDK 38, which contained the `uploadAsync` issue. This issue has not been resolved in Snack. @brentvatne

**Comment by IjzerenHein** [comment] 2020-10-07 13:00
@svm1 Let us know whether `uploadAsync` this is still an issue for you, as it should have been fixed in SDK 39.

**Comment by brentvatne** [comment] 2020-10-07 22:50
thanks @IjzerenHein!

**Closed** 2020-10-07 22:49 UTC
Labels: FileSystem, iOS
