### ISSUE TITLE
Type errors because of types/react~17.

### ISSUE THREAD

**Issue by j3sch** [expo/expo#17101] opened 2022-04-17 22:45 UTC
### Summary

I have created a new project with the typescript template, and I get type errors with the react navigation component. 

`Stack.Navigator' cannot be used as a JSX component.`

Because the current version of react navigation requires types/react~18. 

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### Environment

System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.3.1
    Expo Workflow: managed

### Reproducible demo

https://github.com/expo/expo/tree/main/templates/expo-template-tabs

**Comment by Simek** [comment] 2022-04-18 09:34
Hello @j3sch, I'm not able to reproduce the problem using fresh project generated from `expo init` and tabs template. 

Can you create the minimal reproduction project and share the code?

**Comment by j3sch** [comment] 2022-04-18 10:42
@Simek thank you for your fast response. I have created a new project with the template expo-template-tabs and again got the error in navigation/index.tsx. However, when I opened the project in webstorm, I noticed that these errors were not displayed. I only saw the errors in vscode.

**Comment by Simek** [comment] 2022-04-19 13:50
It looks like this problem is related to this one, which surfaced in navigation repo a few days ago:
* https://github.com/react-navigation/react-navigation/issues/10507

For me, it seems like the editor-specific issue (VS Code in this case), because app builds and works correctly and other editors or IDEs do not report any errors or warnings. 

Unfortunately React types cannot be upgraded to `18` is SDK 44 projects due to React Native version which is underneath, but this might change soon, with new SDK release.

**Comment by j3sch** [comment] 2022-04-20 10:57
Thanks for looking into this issue and for your help.

**Comment by ScreamZ** [comment] 2022-04-25 14:06
This is hell, but this helped: 

"resolutions": { "@types/react": "~17.0.21" },

**Comment by whoisdominic** [comment] 2022-04-26 06:49
Changing to these dependencies worked for me

`  "@types/react": "^17.0.2",
    "typescript": "^4.6.3",
      "react": "17.0.2",
`

**Comment by JohnVidal77** [comment] 2022-04-26 20:01
> This is hell, but this helped:
> 
> "resolutions": { "@types/react": "~17.0.21" },

this solved the problem for me too

**Comment by SrBrahma** [comment] 2022-05-02 04:17
> "resolutions": { "@types/react": "~17.0.21" },

For those who don't know (like me before finding out!), add this line on the package.json, on the first level.

**Comment by owencm** [comment] 2022-05-20 22:29
FYI: for whatever reason the `resolutions` workaround didn't work for me, but I was at least able to suppress the error with `{/* @ts-ignore */ }` on the line above my use of the component in question.

**Comment by pablos91** [comment] 2022-06-29 14:55
> > "resolutions": { "@types/react": "~17.0.21" },
> 
> For those who don't know (like me before finding out!), add this line on the package.json, on the first level.

This is what helped in our project! Remember to do `yarn` afterwards and Reload Window in VS Code. You might also want to `rm -rf node_modules` as well as purging yarn cache with `yarn cache clean`

**Comment by brentvatne** [comment] 2022-07-14 05:50
i believe this was fixed in a recent @types/react-native release: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61081

so, i'm closing this. if you find it is not fixed for you please create a new issue with a minimal reproducible example, thanks!

**Closed by brentvatne** 2022-07-14 05:50 UTC
Labels: project: upstream, ⭐️ Root Cause Known, pending closure
