### ISSUE TITLE
[expo-image-picker] Expo Go crashes, when taking an image.

### ISSUE THREAD

**Issue by LeeviHalme** [expo/expo#21629] opened 2023-03-09 10:24 UTC
### Minimal reproducible example

https://snack.expo.dev/tg7udOuIN

### Summary

Expo Go crashes with no stacktrace on Android 11. This happens when using the example code from `expo-image-picker` documentation.

**Steps to reproduce**
1. Open provided snack on latest Expo Go (2.28.5)
2. Try to take picture by pressing the button (using ´ImagePicker.launchCameraAsync()´)
3. Expo Go crashes, shows splash screen again and finally restarts the app.

**Please check the provided screen recording for reference:**

https://user-images.githubusercontent.com/29179759/223992533-7f63a720-9f2f-43ca-9fe2-1f2994b51109.mp4

### Environment

Expo Snack Environment (can't run `npx expo-env-info` in Snack):
Expo SDK Version: 47.0.0
`expo-image-picker` Version: 14.0.2

Reproduction Environment:
Expo Go Version: 2.28.5
Android Version: 11

**Comment by coroo** [comment] 2023-03-10 07:06
The error also related to https://github.com/expo/expo/issues/21573

**Comment by ferealqq** [comment] 2023-03-13 09:38
Any workaround for this?

**Comment by gabrieldonadel** [comment] 2023-03-15 00:18
This seems to be a duplicate of https://github.com/expo/expo/issues/21544. I'm closing this in favor of that other issue so we focus all comments on a single place

**Closed by gabrieldonadel** 2023-03-15 00:18 UTC
Labels: needs validation, needs review
