### ISSUE TITLE
Unhandled error when using Clipboard.getStringAsync()

### ISSUE THREAD

**Issue by MaciejWiatr** [expo/expo#15180] opened 2021-11-14 00:20 UTC
### Summary

Im getting this error:
```sh
[Unhandled promise rejection: Error: Encountered an exception while calling native method: Exception occurred while executing exported method getStringAsync on module ExpoClipboard: Cannot convert argument of type class android.text.SpannableString]
```
While trying to use Clipboard.getStringAsync() like that
```jsx
	useEffect(() => {
		const checkIfClipboardContainsUrl = async () => {
			const clipboardText = await Clipboard.getStringAsync();
			console.log(clipboardText);
		};
		checkIfClipboardContainsUrl();
	}, []);

```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43.0.2

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~43.0.2 => 43.0.2
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```jsx
	useEffect(() => {
		const checkIfClipboardContainsUrl = async () => {
			const clipboardText = await Clipboard.getStringAsync();
			console.log(clipboardText);
		};
		checkIfClipboardContainsUrl();
	}, []);


```

**Comment by byCedric** [comment] 2021-11-15 12:52
Hi @MaciejWiatr! Unfortunately, I can't reproduce [this error with the code you provided](https://snack.expo.dev/@bycedric/expo-issue-15180). Can you provide a repository or a snack where you run into this issue?

**Comment by Ayush6543** [comment] 2021-11-22 06:27
I am too facing the same issue

**Comment by brentvatne** [comment] 2021-11-23 00:07
appears to be a duplicate of https://github.com/expo/expo/issues/15046

**Closed by brentvatne** 2021-11-23 00:07 UTC
Labels: Android, needs repro, Clipboard

**Comment by marcos8896** [comment] 2021-11-23 06:50
This is also happening to me :(

**Comment by RomanSuvorov** [comment] 2021-11-29 14:06
Have this problem, too
