### ISSUE TITLE
"Invalid request token" when uploading images on iOS after Expo SDK 39 upgrade

### ISSUE THREAD

**Issue by butterfly-valley** [expo/expo#10317] opened 2020-09-23 09:46 UTC
### Summary of Issue
Every single image fails to upload, be it from the camera or from image picker (both managed by Expo Image Picker). This is on iOS 14 and Expo SDK, running on EXPO app for IOS

### Environment
    System:
      OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.18.3 - /usr/bin/node
      npm: 6.14.6 - /usr/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ^39.0.0 => 39.0.2 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.13 
    npmGlobalPackages:
      expo-cli: 3.27.7
    Expo Workflow: managed

### Reproducible Demo
Below is the snack however on snack it seems to run fine, probably the SDK version is different

https://snack.expo.io/@sobrius/invalid-request-token
 
### Steps to Reproduce

Just click on any of the two buttons on iOS device and try uploading an image

### Expected Behavior vs Actual Behavior

Expected behaviour is post the image with no error. Currently on every post attempt I get "error processing request body: Invalid request token"

**Comment by Hirbod** [comment] 2020-09-23 09:49
Duplicate of #10313

**Comment by choby** [comment] 2020-09-23 10:40
you can use FileSystem.uploadAsync() upload file

**Comment by butterfly-valley** [comment] 2020-09-24 07:42
> Duplicate of #10313

thanks, you can close it, there is a workaround in the mentioned thread.

**Closed** 2020-09-24 13:49 UTC
Labels: Issue needs review
