### ISSUE TITLE
[expo-image-picker] Camera not launching (java.lang.NullPointerException: Parameter specified as non-null is null)

### ISSUE THREAD

**Issue by matt-fackler** [expo/expo#21667] opened 2023-03-10 20:58 UTC
### Summary

I am trying to use the expo-image-picker.  I am simulating my app on expo go version 2.28.5 and Android 13.  Using the gallery works just fine.  But when I try to launch the camera, I get this error message:

`Possible Unhandled Promise Rejection (id: 0):
Error: Call to function 'ExponentImagePicker.launchCameraAsync' has been rejected.
→ Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method host.exp.exponent.experience.d.checkSelfPermission, parameter permission
Error: Call to function 'ExponentImagePicker.launchCameraAsync' has been rejected.
→ Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method host.exp.exponent.experience.d.checkSelfPermission, parameter permission
    at construct (native)
    at apply (native)
    at _construct (http://192.168.1.11:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:3348:28)
    at Wrapper (http://192.168.1.11:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:3310:25)
    at _createSuperInternal (http://192.168.1.11:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:97019:322)
    at call (native)
    at CodedError (http://192.168.1.11:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:97027:26)`

I have seen issue #21544 but none of those solutions have solved my problem.  I have no clue what is causing this issue.  Not sure if I need to edit Android permissions but no solutions I have found online work.

Another interesting note:  Once I attempt to use the camera, it will fail and then I can no longer access the gallery.  I press the button to go to gallery and no errors occur, but the gallery won't launch anymore.  Not sure if this is relevant or not but I figured I would mention it.

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^48.0.6 => 47.0.13
      react: ^18.2.0 => 18.1.0
      react-native: ^0.71.3 => 0.70.5
    Expo Workflow: managed

### Minimal reproducible example

Just try running both functions and it should let you use the gallery just fine but not the camera.  It should give the error listed above.  You can display the screen I see by just importing ImageSelect with <ImageSelect/> in a <View> element.

const ImageSelect = () => {
    const [selectedImage, setSelectedImage] = useState(Image.resolveAssetSource(blankPhoto).uri);

    const uploadImage = async (option) => {
        if (option == 1){
            await ImagePicker.requestMediaLibraryPermissionsAsync();
            let result = await ImagePicker.launchImageLibraryAsync({
                allowsEditing: true,
                quality: 1,
            });

            if (!result.canceled){
                setSelectedImage(result.assets[0].uri);
            }
        } else {
            let result = await ImagePicker.launchCameraAsync({
                allowsEditing: true,
                quality: 1,
            });

            if (!result.canceled){
                console.log(result.assets[0].uri);
                setSelectedImage(result.assets[0].uri);
                
                console.log(selectedImage);
            }
        }
    };

    return (
            <View>
                <Image source={{uri: selectedImage}}/>
            <View style={{flexDirection: "row"}}>
                <TouchableOpacity onPress={() => uploadImage(0)}>
                    <Text style={{color: 'white'}}>Take Picture</Text></TouchableOpacity>
                <TouchableOpacity onPress={() => uploadImage(1)}>
                    <Text style={{color:'white'}}>Use Gallery</Text></TouchableOpacity>
            </View>
            </View>
        );

}

**Comment by ibrahimabba** [comment] 2023-03-11 11:31
I couldn't recreate this error as it worked fine as expected, Although i have to Request for camera permission by adding the below line of code just above `await ImagePicker.launchCameraAsync({``

`await ImagePicker.requestCameraPermissionsAsync();`

**Comment by matt-fackler** [comment] 2023-03-11 14:44
I have tried this solution several times.  It does not work.  I even check the return value of requestCameraPermissionsAsync() and the Promise says permission has been granted but it still does not work.

**Comment by venkybavisetti** [comment] 2023-03-12 16:45
> I have tried this solution several times. It does not work. I even check the return value of requestCameraPermissionsAsync() and the Promise says permission has been granted but it still does not work.

+1

**Comment by gabrieldonadel** [comment] 2023-03-13 13:18
This seems to be a duplicate of https://github.com/expo/expo/issues/21544. I'm closing this in favor of that other issue so we focus all comments on a single place

**Closed by gabrieldonadel** 2023-03-13 13:18 UTC
Labels: needs validation, CLI

**Comment by francisch-98** [comment] 2023-06-22 05:16
yo lo solucione bajando la version de android a 11 de mi emulador

**Comment by ExtremixtLocust** [comment] 2023-07-04 18:42
también lo solucioné cambiando de dispositivo, inicié la app en expo en mi android físico y la cámara funcionó sin problemas, debe ser alguna incompatibilidad del emulador
