### ISSUE TITLE
Expo Camera - Incorrect orientation of captured photo if device orientation is locked

### ISSUE THREAD

**Issue by nbonatsakis** [expo/expo#16837] opened 2022-03-30 19:14 UTC
### Summary

When capturing a photo via the Expo Camera component, if the device is orientation locked in Portrait for example, and you then rotate to Landscape, the resulting photo is captured in Portrait. The iOS camera app and native SDK will ignore the system portrait lock setting when capturing photos. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44.0.0

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.4.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
      Watchman: 2022.01.31.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/nick/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.16 
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.39.0
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

Embed this component into any view and then enable rotation lock on your device, then take a photo.
```<Camera autoFocus={'on'}/>
```

**Comment by krschacht** [comment] 2022-03-30 21:02
Yes! This is an issue for us. The only work-around we've found so far is to run the photo through an analysis after being taken to determine if it's rotated incorrectly and update the metadata, but that's a pain. We'd love to fix this within Expo itself.

**Comment by AlexJohnSadowski** [comment] 2022-04-21 19:54
Yup, same thing here on iOS. Cannot find a way to determine if the photo is in landscape mode or not. On iPhone XR If I take a photo in a landscape position, the ScreenOrientation API will not detect it. Surprisingly, it works on an iPhone 13 and the photo will be adjusted and rotated accordingly. Have no idea how to handle that issue though.

**Comment by asicdesign** [comment] 2022-07-08 20:22
I guess the workaround is to detect if Orientation is locked (using ScreenOrientation.getOrientationLockAsync() ), and notify the user to unlock? Not a good user experience, so I really hope the expo Camera team will fix this soon.

**Comment by yohamta** [comment] 2022-10-06 03:02
We've been facing the same issue. We also can not detect if Orientation is locked (even if using ScreenOrientation.getOrientationLockAsync() ) so there's no effective workaround. We really hope this issue will be fixed soon. Does anyone have an idea where the problem might be?

**Comment by asicdesign** [comment] 2022-10-06 03:19
We ended up switching to React Native Camera. It is old and deprecated, but works. You could look at React Native Vision Camera.

**Comment by yohamta** [comment] 2022-10-06 03:39
@asicdesign  Thank you very much! Very helpful.

**Comment by yohamta** [comment] 2022-10-08 08:23
We've tried to switch to React Native Camera / React Native Vision Camera but unfortunately, it did not work for us because our app did not work properly after ejecting from managed workflow with some unresolvable errors. We really hope this issue fixed soon.

**Comment by yohamta** [comment] 2022-11-26 00:36
Any updates on this?

**Comment by Luke20w** [comment] 2022-11-26 01:09
@yohamta Nothing I've seen. I'm thinking of making a Flutter app instead and hoping that doesn't have the same problem

**Comment by adscud** [comment] 2022-11-28 11:00
Who should we mention to get some informations in the expo team ?

**Closed** 2023-02-22 23:12 UTC
Labels: iOS, Camera, incomplete issue: missing or invalid repro

**Comment by krschacht** [comment] 2023-02-23 01:33
But we included the steps to reproduce, it’s simple.

**Comment by yohamta** [comment] 2023-02-23 02:55
Is there anyone who can create a simple reproduction demo? I would love to do it, but I don't have the time. Although the steps for reproduction are simple, it seems necessary to raise the priority for this issue.

**Comment by pratheekhegde** [comment] 2023-03-19 19:08
I was able to fix the orientation by using the `expo-image-manipulator` package as described by @currentoor. All I need to do is check if the  `Orientation` of the image is `-90`. As landscape images captured with the portrait lock in iOS happens to have its `Orientation` set to `-90` in its exif data.

```
  if (Platform.OS === 'ios' && capturedImage.exif.Orientation === -90) {
      const result = await manipulateAsync(uri, [{ rotate: -90 }]);
  }
```

**Comment by scd8418** [comment] 2024-03-24 15:57
Is there anything new on this issue? None of the suggested work-arounds actually work. It's easy enough to rotate the image if you can detect that the orientation is wrong, but the exif data always returns -90 when the orientation is locked, regardless of the actual orientation of the the camera. This makes it impossible to tell when you need to rotate the image. The width and height are also locked and reflect a -90 orientation so they are no help in detection.

Without a reliable fix for this, the camera is useless in a production app.

**Comment by scd8418** [comment] 2024-03-24 15:59
I'd also note that the PixelXDimension and PixelYDimension in the exif data appear to be reversed. It would seem natural for X to represent the image width and Y to represent the image height, but the opposite is true, regardless of the orientation (fixed or floating).

**Comment by normanwilde** [comment] 2024-04-13 10:10
Here's my workaround, it's been working so far for me whether the phone's orientation itself was locked or not.
```
const [orientation, setOrientation] = useState<CameraOrientation>(1)

{...}

 <ExpoCamera
  {...}
  responsiveOrientationWhenOrientationLocked={true}
  onResponsiveOrientationChanged={(e) => onSetOrientation(e.orientation)}
 />
```
Then if `orientation` is `3` or `4` (landscape) I rotate the image with `expo-image-manipulator` by 180 degrees.

**Comment by scd8418** [comment] 2024-04-13 21:59
That does seem to work. Thanks so much for posting. I had no idea those options existed.
