### ISSUE TITLE
can I add expo Kit after ejecting

### ISSUE THREAD

**Issue by firashamila33** [expo/expo#2103] opened 2018-08-13 10:18 UTC
Hello , I ejected my react native project from expo , but seems that FacebookLogin from Expo does not work , so I found out that expo Kit can help me  so how to add Expo Kit to my ejected project , and is this a good choise ?

**Comment by lichenglu** [comment] 2018-08-13 16:29
You probably want to `detach` instead of `eject`:
https://docs.expo.io/versions/latest/expokit/detach#__next

**Comment by firashamila33** [comment] 2018-08-14 14:13
But as I told you I already ejected my project and sone several steps  ,

**Comment by tsapeta** [comment] 2019-09-28 16:42
If you still have some issues with FacebookLogin not working after ejecting, please create a separate issue and provide some more details like which SDK version do you use and some steps that will help us to reproduce the issue.
I'm closing this issue since it's been a long time and I believe it works in the most recent SDK versions.

**Closed by tsapeta** 2019-09-28 16:42 UTC
Labels: status: help wanted
