### ISSUE TITLE
Object doesn't support property or method 'addEventListener' in ExpoScreenOrientation.web.js

### ISSUE THREAD

**Issue by shahrin-14** [expo/expo#5694] opened 2019-09-19 02:12 UTC
TypeError: Object doesn't support property or method 'addEventListener'
../../../../../../../../../../Projects/ey/cloud/daikin-react-04/node_modules/expo/build/ScreenOrientation/ExpoScreenOrientation.web.js
C:/Dev/Projects/ey/cloud/daikin-react-04/node_modules/expo/build/ScreenOrientation/ExpoScreenOrientation.web.js:33
```javascript
  30 |     });
  31 | }
  32 | if (orientation) {
> 33 |     orientation.addEventListener('change', emitOrientationEvent);
  34 | }
  35 | else {
  36 |     window.addEventListener('orientationchange', emitOrientationEvent);
```

**Comment by ide** [comment] 2019-09-19 04:13
What browser is this happening on?

**Comment by shahrin-14** [comment] 2019-09-19 04:15
So sorry. Should have mentioned earlier.

Version 77.0.3865.75 (Official Build) (32-bit)
Any way I can help out?

**Comment by shahrin-14** [comment] 2019-09-19 05:07
Microsoft Edge 41.16299.1004.0
Note that this happens for both blank template and tabbed template for managed workflow.

**Comment by vandre** [comment] 2019-09-25 21:14
Duplicate of #4663

**Comment by FiberJW** [comment] 2019-10-09 20:04
This seems to be resolved, so I'll close this for now. If you have any further related problems, please open another issue. Thanks :)

**Closed by FiberJW** 2019-10-09 20:04 UTC
Labels: project: web
