### ISSUE TITLE
[expo-dev-menu][SDK51] build error with `useFrameworks` and old architecture

### ISSUE THREAD

**Issue by rranjan14** [expo/expo#28666] opened 2024-05-08 02:37 UTC
### Minimal reproducible example

https://github.com/rranjan14/my-app

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Setting `useFrameworks` to `static` causes build errors on iOS.

### app.json:
```
"plugins": [
  [
    "expo-build-properties",
    {
      "ios": {
        "useFrameworks": "static",
        "deploymentTarget": "14.0"
      }
    }
  ]
],
```

### Error:
```
[RUN_FASTLANE] › Compiling expo-dev-menu Pods/expo-dev-menu » expo-dev-menu-dummy.m
[RUN_FASTLANE] › Compiling expo-dev-menu Pods/expo-dev-menu » EXDevMenuAppInfo.m
[RUN_FASTLANE] › Compiling expo-dev-menu Pods/expo-dev-menu » DevMenuRootView.m
[RUN_FASTLANE] › Compiling expo-dev-menu Pods/expo-dev-menu » DevMenuLoadingView.m
[RUN_FASTLANE] › Compiling expo-dev-menu Pods/expo-dev-menu » DevMenuRCTDevSettings.m
[RUN_FASTLANE] › Compiling expo-dev-menu Pods/expo-dev-menu » DevMenuRCTBridge.mm
[RUN_FASTLANE] › Compiling expo-dev-menu Pods/expo-dev-menu » EXDevMenu_vers.c
[RUN_FASTLANE] › Compiling expo-dev-menu Pods/expo-dev-menu » DevMenuExtensions.m
[RUN_FASTLANE] › Compiling expo-dev-menu Pods/expo-dev-menu » DevClientRootViewFactory.mm
[RUN_FASTLANE] 
❌  (node_modules/react-native/ReactCommon/cxxreact/JSExecutor.h:15:10)

  13 | #include <cxxreact/NativeModule.h>
  14 | #include <folly/dynamic.h>
> 15 | #include <jsinspector-modern/InspectorInterfaces.h>
     |          ^ 'jsinspector-modern/InspectorInterfaces.h' file not found
  16 | #include <jsinspector-modern/ReactCdp.h>
  17 | 
  18 | #ifndef RN_EXPORT

[RUN_FASTLANE]     Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency ana
[RUN_FASTLANE] ▸ ** BUILD FAILED **
[RUN_FASTLANE] ▸ The following build commands failed:
[RUN_FASTLANE] ▸        CompileC /var/folders/by/sf7ys4_942792fgdf85gz1000000gn/T/eas-build-local-nodejs/41bd16b2-e71c-412a-ab23-33ebccffed1e/build/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/expo-dev-menu.build/Objects-normal/x86_64/DevClientRootViewFactory.o /var/folders/by/sf7ys4_942792fgdf85gz1000000gn/T/eas-build-local-nodejs/41bd16b2-e71c-412a-ab23-33ebccffed1e/build/node_modules/expo-dev-menu/ios/DevClientRootViewFactory.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'expo-dev-menu' from project 'Pods')
[RUN_FASTLANE] ▸ (1 failure)
[RUN_FASTLANE] ** BUILD FAILED **
[RUN_FASTLANE] 
[RUN_FASTLANE] 
[RUN_FASTLANE] The following build commands failed:
[RUN_FASTLANE]  CompileC /var/folders/by/sf7ys4_942792fgdf85gz1000000gn/T/eas-build-local-nodejs/41bd16b2-e71c-412a-ab23-33ebccffed1e/build/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/expo-dev-menu.build/Objects-normal/x86_64/DevClientRootViewFactory.o /var/folders/by/sf7ys4_942792fgdf85gz1000000gn/T/eas-build-local-nodejs/41bd16b2-e71c-412a-ab23-33ebccffed1e/build/node_modules/expo-dev-menu/ios/DevClientRootViewFactory.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'expo-dev-menu' from project 'Pods')
[RUN_FASTLANE] (1 failure)
[RUN_FASTLANE] Exit status: 65
[RUN_FASTLANE] 
[RUN_FASTLANE] +---------------------------------------+
[RUN_FASTLANE] |           Build environment           |
[RUN_FASTLANE] +-------------+-------------------------+
[RUN_FASTLANE] | xcode_path  | /Applications/Xcode.app |
[RUN_FASTLANE] | gym_version | 2.220.0                 |
[RUN_FASTLANE] | sdk         | iPhoneOS17.4.sdk        |
[RUN_FASTLANE] +-------------+-------------------------+
[RUN_FASTLANE] 
[RUN_FASTLANE] Looks like fastlane ran into a build/archive error with your project
[RUN_FASTLANE] It's hard to tell what's causing the error, so we wrote some guides on how
[RUN_FASTLANE] to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[RUN_FASTLANE] Before submitting an issue on GitHub, please follow the guide above and make
[RUN_FASTLANE] sure your project is set up correctly.
[RUN_FASTLANE] fastlane uses `xcodebuild` commands to generate your binary, you can see the
[RUN_FASTLANE] the full commands printed out in yellow in the above log.
[RUN_FASTLANE] Make sure to inspect the output above, as usually you'll find more error information there
[RUN_FASTLANE] [!] Error building the application - see the log above
[RUN_FASTLANE] Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.

Build failed
The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.
npx exited with non-zero code: 1
    Error: build command failed.
```

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.18.2/bin/yarn
      npm: 10.4.0 - ~/.nvm/versions/node/v18.18.2/bin/npm
      Watchman: 2024.05.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/rahulranjan/.rvm/gems/ruby-2.7.8/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.0 => 51.0.0 
      expo-router: ~3.5.10 => 3.5.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 8.0.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by jingp-ofload** [comment] 2024-05-08 05:26
In my case, even comment out entire ios config from `"expo-build-properties"` the issue remains.

**Comment by jingp-ofload** [comment] 2024-05-08 05:34
remove `expo-dev-client` works for me

**Comment by rranjan14** [comment] 2024-05-08 05:40
@jingp-ofload in my case that's not feasible because I have certain dependencies which won't work on Expo Go.

**Comment by jingp-ofload** [comment] 2024-05-08 05:45
> @jingp-ofload in my case that's not feasible because I have certain dependencies which won't work on Expo Go.

Yeah, I agree. it needs to be fixed.

**Comment by jingp-ofload** [comment] 2024-05-08 07:02
@rranjan14
add 
```
add_dependency(s, "React-jsinspector", :framework_name => 'jsinspector_modern')
```
in both of `node_modules/expo-dev-launcher/expo-dev-launcher.podspec` and `node_modules/expo-dev-menu/expo-dev-menu.podspec` works for me. This is just a temporary workaround just for people who wants to test expo 51.

These are the patches I did

In expo-dev-menu+5.0.13.patch
```
diff --git a/node_modules/expo-dev-menu/expo-dev-menu.podspec b/node_modules/expo-dev-menu/expo-dev-menu.podspec
index 6856304..72ef19c 100644
--- a/node_modules/expo-dev-menu/expo-dev-menu.podspec
+++ b/node_modules/expo-dev-menu/expo-dev-menu.podspec
@@ -103,6 +103,9 @@ Pod::Spec.new do |s|
     main.dependency 'ExpoModulesCore'
     main.dependency 'expo-dev-menu-interface'
     main.dependency "expo-dev-menu/Vendored"
+
+    add_dependency(s, "React-jsinspector", :framework_name => 'jsinspector_modern')
+    
   end
 
   s.subspec 'ReactNativeCompatibles' do |ss|
```
In expo-dev-launcher+4.0.12.patch
```
diff --git a/node_modules/expo-dev-launcher/expo-dev-launcher.podspec b/node_modules/expo-dev-launcher/expo-dev-launcher.podspec
index 3b54c35..a5b784b 100644
--- a/node_modules/expo-dev-launcher/expo-dev-launcher.podspec
+++ b/node_modules/expo-dev-launcher/expo-dev-launcher.podspec
@@ -91,6 +91,8 @@ Pod::Spec.new do |s|
   s.dependency "expo-dev-menu"
   s.dependency "ExpoModulesCore"
 
+  add_dependency(s, "React-jsinspector", :framework_name => 'jsinspector_modern')
+
   unless defined?(install_modules_dependencies)
     # `install_modules_dependencies` is defined from react_native_pods.rb.
     # when running with `pod ipc spec`, this method is not defined and we have to require manually.
```

**Comment by anirudhsama** [comment] 2024-05-08 08:29
I'm also getting the same error after upgrading to SDK 51.

**Comment by H4ck3r-x0** [comment] 2024-05-08 14:25
#28676 i am having smiler issue while building the app using eas.

I got this error!
```
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptValue.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptTypedArray.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptRuntime.mm

❌  (node_modules/expo-modules-core/ios/JSI/EXJavaScriptRuntime.mm:31:8)

  29 | class SyncCallInvoker : public react::CallInvoker {
  30 | public:
> 31 |   void invokeAsync(std::function<void()> &&func) override {
     |        ^ exception specification of overriding function is more lax than base version
  32 |     func();
  33 |   }
  34 | 

› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptObject.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIUtils.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIInstaller.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIConversions.mm
▸ ** BUILD FAILED **
▸ The following build commands failed:
▸ 	CompileC /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/ExpoModulesCore.build/Objects-normal/x86_64/EXJavaScriptRuntime.o /Users/expo/workingdir/build/node_modules/expo-modules-core/ios/JSI/EXJavaScriptRuntime.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'ExpoModulesCore' from project 'Pods')
▸ (1 failure)
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/ExpoModulesCore.build/Objects-normal/x86_64/EXJavaScriptRuntime.o /Users/expo/workingdir/build/node_modules/expo-modules-core/ios/JSI/EXJavaScriptRuntime.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'ExpoModulesCore' from project 'Pods')
(1 failure)
Exit status: 65

+---------------------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.219.0                 |
| sdk         | iPhoneOS17.4.sdk        |
+-------------+-------------------------+

Looks like fastlane ran into a build/archive error with your project
It's hard to tell what's causing the error, so we wrote some guides on how
to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
Before submitting an issue on GitHub, please follow the guide above and make
sure your project is set up correctly.
fastlane uses `xcodebuild` commands to generate your binary, you can see the
the full commands printed out in yellow in the above log.
Make sure to inspect the output above, as usually you'll find more error information there

[!] Error building the application - see the log above
Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.
```

**Comment by brentvatne** [comment] 2024-05-08 20:38
this is a duplicate of #28209 - we'll follow up there. thanks for the report!

**Closed by brentvatne** 2024-05-08 20:38 UTC
Labels: iOS, Development Builds, needs review
