### ISSUE TITLE
[android][calendar] can't add alarms on createEventAsync

### ISSUE THREAD

**Issue by ptsang-hcmus** [expo/expo#5209] opened 2019-08-07 07:31 UTC
### Environment

```
  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.21.2
```

Target: Android
### Steps to Reproduce

I create an event with notification for both Android and IOS using `expo-calendar`. The workflow happens in `componentDidMount` is:
- Ask for permission
- If granted then check if calendar with title `sample-calendar` created yet, if not then create.
- Get the `sample-calendar` `id` into `calendarId`
- Create an event with `calendarId` that goes off after 5 seconds to test.

Here are my event details:
``` Javascript
let eventDetails = {
  title: "sample event",
  startDate: new Date().getTime() + 65000,
  endDate: new Date().getTime() + 100000,
  alarms: [{
    relativeOffset: "-1",
    method: Calendar.AlarmMethod.ALERT,
  }],
  recurrenceRule: {
    frequency: Calendar.Frequency.DAILY,
    occurrence: 1,
  },
};
```

### Expected Behavior

- IOS phone (running that app) will have an event `sample` in the calendar named `sample-calendar`
- Notification in IOS phone will go after 5 seconds

- Android phone (running that app) will have an event `sample` in the calendar named `sample-calendar`
- Notification in Android phone will go after 5 seconds 

### Actual Behavior

- IOS phone (running that app) has an event `sample` in the calendar named `sample-calendar` ✅
- Notification in IOS phone goes after 5 seconds ✅

- Android phone (running that app) has an event `sample` in the calendar named `sample-calendar` ✅
- Notification in the Android phone goes after 5 seconds ❌. The alarm did not work at all, I try all `Calendar.AlarmMethod` and it did not work once in Android.

|Devices|alarms|
|---|---|
|IOS|`[{"relativeOffset":-1}]`|
|Android|`[]`|

### Reproducible Demo

https://snack.expo.io/@sangpt.pascaliaasia/calendarevent

**Comment by cruzach** [comment] 2019-08-07 15:33
Hey @ptsang-hcmus, can you double-check your repro snack? I tried running and both devices `this.state.event` remains null (with permission granted)

**Comment by ptsang-hcmus** [comment] 2019-08-07 17:06
Hi @cruzach, `this.state.event` remain `null` maybe because the snack did not have logged calendar account. I tried this snack on my phone (android) and my coworker phone (ios) and it works fine. I found this problem when I ran the program on my phone. I tried running on the `snack` too but it seems like it doesn't work on `snack's devices`.

Notice that it will create a calendar title `sample-calendar` and an event title `sample` that you will want to remove later, hope that will not inconvenience for you.

### `Event` object created
I just ran the code on my **Android** phone, here is my event object:
```
Object {
  "accessLevel": "default",
  "alarms": Array[],
  "allDay": false,
  "availability": "busy",
  "calendarId": "19",
  "endDate": "2019-08-07T16:52:09.495Z",
  "endTimeZone": "Asia/Ho_Chi_Minh",
  "guestsCanInviteOthers": true,
  "guestsCanModify": false,
  "guestsCanSeeGuests": true,
  "id": "422",
  "location": null,
  "notes": null,
  "organizerEmail": "My calendar",
  "originalId": null,
  "recurrenceRule": Object {
    "frequency": "daily",
  },
  "startDate": "2019-08-07T16:51:34.495Z",
  "timeZone": "Asia/Ho_Chi_Minh",
  "title": "sample event",
}
```
### The `alarms` array in `Event` object:
On the Android, in the code I did pass the `event.alarms` object when I created `event` and here is the `event.alarms`I get from create.
```
event.alarms = Array []
```
On the **IOS** phone however, it will be:
```
event.alarms = Array [{"relativeOffset":-1}]
```

**Comment by davidli3100** [comment] 2019-08-12 00:19
I think there was a PR (yet to be merged/deployed?) that solved the issue of relativeOffsets on android. Apparently it's an int/double casting issue that causes crashes. 

@cruzach do you know if that PR has been merged into Expo? And how should we be updating the calendar or main expo module if it is?

**Comment by cruzach** [comment] 2019-08-12 01:08
@davidli3100 is [this the PR](https://github.com/expo/expo/pull/5134) you're thinking of? It will most likely be released in SDK 35

**Comment by davidli3100** [comment] 2019-08-12 01:13
Yeah that's the one. So when SDK35 comes out I just reinstall expo and expo
calendar right?

Is there a way I can manually apply the fix right now? It's kind of an
important feature

**Comment by cruzach** [comment] 2019-08-12 01:20
If you are using Expokit or are in the bare workflow, you can make those native code changes yourself. Otherwise, You'll have to wait for SDK 35 which will come out in September

**Comment by davidli3100** [comment] 2019-08-12 01:21
Crap ok, any chance it could be pushed by itself or no?

**Comment by davidli3100** [comment] 2019-09-22 02:39
@cruzach have alerts been added to the new version of expo?

**Comment by cruzach** [comment] 2019-09-26 16:50
Yes, you can see in the changelog under `35.0.0 > Bugfixes` https://github.com/expo/expo/blob/master/CHANGELOG.md

**Comment by ptsang-hcmus** [comment] 2019-11-06 07:32
@cruzach I did a test today using my snack repo using
```json
    "expo": "^35.0.0",
    "expo-calendar": "~7.0.0",
    "expo-permissions": "~7.0.0",
```
and the bug still occurs. Can you check again (run repo locally on your phone to test because you have to sign in in order to use the calendar) 
![still bug](https://user-images.githubusercontent.com/43752908/68277651-390bd480-00a2-11ea-9af1-d9747514f934.jpg)

**Comment by cruzach** [comment] 2019-11-06 17:06
Confirmed I see this behavior, seems to be related to how we handle the Id property on Android

For now, a workaround is to first create the event, then update with [updateEventAsync](https://docs.expo.io/versions/latest/sdk/calendar/#calendarupdateeventasyncid-details-recurringeventoptions) like this, for example:
```
Calendar.updateEventAsync(eventId, {
      alarms: [
        {
          relativeOffset: 1,
          method: Calendar.AlarmMethod.ALERT
        }
      ]
    });
```

**Comment by lukmccall** [comment] 2020-03-05 09:59
Hi @ptsang-hcmus, `relativeOffset` should be a `number`, not a `string`. 

So if you change:
```ts
alarms: [{
    relativeOffset: "-1",
    method: Calendar.AlarmMethod.ALERT,
  }],
```
to
```ts 
alarms: [{
    relativeOffset: -1,
    method: Calendar.AlarmMethod.ALERT,
  }],
```
it should work 😉

**Closed by lukmccall** 2020-03-05 09:59 UTC
Labels: Calendar, bug, project: android-runtime

**Comment by mamemam** [comment] 2020-04-19 09:31
> Confirmed I see this behavior
> 
> For now, a workaround is to first create the event, then update with [updateEventAsync](https://docs.expo.io/versions/latest/sdk/calendar/#calendarupdateeventasyncid-details-recurringeventoptions) like this, for example:
> 
> ```

>           method: Calendar.AlarmMethod.ALERT

> ```

That part ,that was missing for me in Create Event

**Comment by ddennis** [comment] 2023-10-20 14:03
Was this ever fixed, since I am having the exact same issue when trying to set alarms on Android.
