### ISSUE TITLE
iPad initial orientation rotates to portrait

### ISSUE THREAD

**Issue by JustynaKK** [expo/expo#9131] opened 2020-07-08 08:42 UTC
## 🐛 Bug Report

Opening the app in the landscape orientation (physical and display is in the landscape), app automatically switches to portrait.
https://vimeo.com/436104636  

Tested on: iPad Pro, iOS: 13.4.1    

It was working in SDK 36, before moving the expo-screen-orientation to the separate module.

### Environment 
  ```
    npmPackages:
      expo: ^37.0.12 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4,
      expo-screen-orientation: 1.1.1
```

**Comment by lukmccall** [comment] 2020-07-08 08:47
Thanks for creating a new issue ;)

**Comment by Blixten84** [comment] 2020-07-08 12:38
I just wanted to say that I'm also facing this issue. When starting up my standalone expo app when the device is physically in landscape mode, the splash screen loads correctly in landscape, but then the screen rotates to a portrait mode.

**Comment by lukmccall** [comment] 2020-07-08 12:52
@Blixten84 are you using an iPad too?

**Comment by Blixten84** [comment] 2020-07-08 13:22
Not iPad, but I’m using both my physical and simulated iPhone X running iOS 13.5.
The same issue happening for both the release build and the dev build (with metro).

**Comment by lukmccall** [comment] 2020-07-08 13:35
And you are using `expo-screen-orientation: 1.1.1`?

**Comment by Blixten84** [comment] 2020-07-08 14:20
> And you are using `expo-screen-orientation: 1.1.1`?

Yes.

And it seems to work as expected when I tested it on an Android emulator. So this seems to be an issue only for iOS.

**Comment by lukmccall** [comment] 2020-07-08 14:30
Ohh, I see. This bug was fixed by https://github.com/expo/expo/pull/8727 and https://github.com/expo/expo/pull/8836. Unfortunately, these changes weren't published yet.

**Comment by lukmccall** [comment] 2020-07-08 14:34
@JustynaKK, I'm not sure if these fixes will help in your case. IPads differently handle screen orientation.

**Comment by JustynaKK** [comment] 2020-07-09 07:15
ok,I will wait for the changes to be published and I will let know if it helped with iPads.

**Comment by lukmccall** [comment] 2020-07-09 09:31
I'll also try to reproduce it with this fix ;)

**Comment by lukmccall** [comment] 2020-07-13 12:46
@JustynaKK, I've tested the unpublished version on iPad Pro and it seems to work ;)
So I'm closing this issue for know. Feel free to reopen it when the bug occurs for you on the next version.

**Closed by lukmccall** 2020-07-13 12:46 UTC
Labels: ScreenOrientation, iOS, iPadOS

**Comment by JustynaKK** [comment] 2020-08-24 08:04
@lukmccall, I just wanted to ask if there is an orientational date for releasing next version of expo-screen-orientation which includes this changes?

**Comment by JustynaKK** [comment] 2020-08-24 08:20
@lukmccall, I have upgraded expo-screen-orientation to version 2.0.0 and unfortunately I am still facing the issue with initial rotation on my iPad

**Comment by lukmccall** [comment] 2020-08-31 09:45
Sorry for my late reply.

Do you use a managed workflow? If yes, you need to wait for the next SDK release (it'll land soon 😄). Why? Because this fix requires changes in the native code. You don't get them until we update the build services.

**Comment by JustynaKK** [comment] 2020-11-03 17:09
With SDK39 everything works perfect, thank you!
