### ISSUE TITLE
AppAuth Error

### ISSUE THREAD

**Issue by jordan-thenumber** [expo/expo#4402] opened 2019-06-04 05:13 UTC
### Environment

  Expo CLI 2.18.3 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.3.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 2.3 AI-162.3871768
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.7 => 3.5.1
    npmGlobalPackages:
      expo-cli: 2.18.3

Android/Standalone

### Steps to Reproduce

call `AppAuth.authAsync`. In my case I'm authenticating to google api:

      issuer: 'https://accounts.google.com',
      clientId: <clientId>,
      scopes: ['https://www.googleapis.com/auth/calendar.events'],
      redirectUrl: 'https://auth.expo.io/@my_team/my_project,

### Expected Behavior

Once authenticated, expected to receive token response.

### Actual Behavior

After successful login/authentication to via webview, the page displays the following:

"Something went wrong trying to finish signing in. Please close this screen to go back to the app"

### Reproducible Demo

No point in creating a snack for something like this since it's basically a single function call.

### Stack Trace

      Shutting down VM
      FATAL EXCEPTION: main
      Process: host.exp.exponent, PID: 29471
      java.lang.RuntimeException: Unable to start activity ComponentInfo{host.exp.exponent/host.exp.exponent.LauncherActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
      at android.app.ActivityThread.-wrap11(Unknown Source:0)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
      at android.os.Handler.dispatchMessage(Handler.java:105)
      at android.os.Looper.loop(Looper.java:164)
      at android.app.ActivityThread.main(ActivityThread.java:6944)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
      Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
      at android.app.Activity.onCreate(Activity.java:1038)
      at host.exp.exponent.LauncherActivity.onCreate(LauncherActivity.java:28)
      at android.app.Activity.performCreate(Activity.java:7183)
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
      ... 9 more
NOTE *** I've also tried using `Expo.AuthSession.startAsync` and the app crashes at the same point. Perhaps this is related.

**Comment by drfenixion** [comment] 2019-06-04 16:10
With Expo.AuthSession and other cases of auth redirect to the app, I get expo crash. I also open an issue about it https://github.com/expo/expo/issues/4394
it worked fine before.

**Comment by sjchmiela** [comment] 2019-06-06 12:21
This should be fixed in latest Expo client 2.11.2. Could you try reproducing the problem on this version?

**Comment by jordan-thenumber** [comment] 2019-06-06 22:52
@sjchmiela Yes I'm getting this error in 2.12.2. I'm also encountering this issue in a standalone app. I've decided to go with GoogleSignIn even though I really wanted to get a refreshToken for offline access which, from my understanding, is not possible with GoogleSignIn in a standalone app.

**Comment by drfenixion** [comment] 2019-06-07 00:39
Confirm, AUTH0 get error - 'Looks like something went wrong!'. (not redirect to app)

Other auth process works fine. Crush fixed.

**Comment by jordan-thenumber** [comment] 2019-06-07 00:42
It looks like auth.expo.io is throwing a 500 for me.

https://auth.expo.io/@thenumber_tech/buzztron?state=t4UlKkjbQq9r9W00hIx5sA&code=4/XQFceza2KPjn-IC1w8obB0SA8LGi8B3MzFJGplv5u8ReBO5fNiUkIXwa8VeSQn__FghAxElzKlFPACe4oCyPTvI&scope=https://www.googleapis.com/auth/calendar.events

**Comment by esamelson** [comment] 2019-10-15 19:55
Hi, we're closing inactive issues that apply to SDK versions we no longer support. It's really hard to look into issues like this without a reproducible demo -- even if it seems small, it helps us quickly narrow down exactly what the problem is. Otherwise we have to spend time creating one in order to debug the problem anyway. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.

**Closed by esamelson** 2019-10-15 19:55 UTC
Labels: AppAuth, bug, project: android-runtime
