### ISSUE TITLE
Audio record bug, Another app is interfering

### ISSUE THREAD

**Issue by 345ml** [expo/expo#6114] opened 2019-10-29 10:01 UTC
### Environment

iOS real machine
```
Expo CLI 3.2.3 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.16.0 - ~/.nodebrew/current/bin/node
      Yarn: 1.16.0 - ~/.nodebrew/current/bin/yarn
      npm: 6.4.1 - ~/.nodebrew/current/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 3.2.3
```

### Steps to Reproduce
I use the recording function of Expo, but I feel that this function is interfering with other applications.

1. Record with our app. Success.
2. ~~For example, play music with Spotify or AppleMusic.~~
3. Record again with our app. It ’s really jammy.

Is there a workaround for this issue?

Sample code.
``` javascript
import { Audio } from 'expo-av';

let recordOptions = Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY;
recordOptions.ios.extension = '.m4a';
recordOptions.ios.outputFormat = Audio.RECORDING_OPTION_IOS_OUTPUT_FORMAT_MPEG4AAC;
recordOptions = JSON.parse(JSON.stringify(recordOptions));

const recordingRef = useRef(null);

useEffect(() => {
  Permissions.getAsync(Permissions.AUDIO_RECORDING).then((status) => {
    if (status !== 'granted') {
      return Permissions.askAsync(Permissions.AUDIO_RECORDING);
    }
    return {};
  }).catch();
}, []);

const startRecord = async () => {
  try {
    await Audio.setAudioModeAsync({
      allowsRecordingIOS: true,
      staysActiveInBackground: false,
      interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
      playsInSilentModeIOS: true,
      shouldDuckAndroid: true,
      interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
      playThroughEarpieceAndroid: true,
    });

    const recording = new Audio.Recording();
    await recording.prepareToRecordAsync(recordOptions);
    await recording.startAsync();
    recordingRef.current = recording;
  } catch (error) {
  }
};

const stopRecord = async () => {
  try {
    await recordingRef.current.stopAndUnloadAsync();
  } catch (error) {
};

```

### Expected Behavior
Succeed audio record.

### Actual Behavior

Noisy sound is generated

**Comment by 345ml** [comment] 2019-10-29 10:01
I don't know if this is related to this phenomenon, but durationMillis may be negative.
In particular, it occurs in the second and subsequent recordings.

``` javascript
recording.setOnRecordingStatusUpdate((e) => {
  console.log(e);
  // durationMillis: -6323350
});
```

**Comment by cruzach** [comment] 2019-10-29 19:59
Can you provide the full code to reproduce this? It's best to share a link to a [snack](https://snack.expo.io/)

**Comment by 345ml** [comment] 2019-10-30 01:47
This is not reproduced in the iOS simulator.
It is reproduced when using the actual machine.

Tested with iOS12.3.1.

**Comment by 345ml** [comment] 2019-10-30 01:48
@cruzach 
Thanks.
OK!

**Comment by 345ml** [comment] 2019-10-30 02:12
@cruzach 
https://snack.expo.io/@horota/audio-record-bug,-another-app-is-interfering

I ported the code to Snack and verified it on the same iOS device, but the phenomenon has not been reproduced.
I will continue the investigation.

**Comment by 345ml** [comment] 2019-10-30 02:19
@cruzach 
Snack's code is a single component, but the actual product is a voice chat app, a screen containing multiple Audio.Sound and one Audio.Recording.

I felt that the problem was whether Audio.Sound existed.
Continue the investigation.

**Comment by 345ml** [comment] 2019-10-30 04:04
@cruzach 
https://snack.expo.io/@horota/audio-record-bug,-another-app-is-interfering

The phenomenon has been reproduced.
This sample is recorded by pressing and holding the button, and the recorded sound is played when the button is released.
Notice the outliers for durationMillis.

During playback, noise is especially seen at the beginning.

Please comment out the useEffect part of Line58.
The abnormal value of durationMillis is eliminated and the noise disappears.

**Comment by 345ml** [comment] 2019-10-31 03:33
@cruzach 
Thank you!!👍
This problem seems to be dark. . .

Can I try it on a real machine instead of a simulator?

**Comment by cruzach** [comment] 2019-10-31 14:44
Not sure what you mean. You cannot use the simulator for audio recording, I tested this on a real device

**Comment by 345ml** [comment] 2019-11-01 02:23
@cruzach 
Thanks.
Not sure...😂

**Comment by 345ml** [comment] 2019-11-17 04:13
I haven't solved this problem yet. . .
The beginning of the recorded audio will be choppy.

**Comment by tsapeta** [comment] 2020-07-27 11:42
We were unable to reproduce this issue so I'm closing it. Let us know if you're still experiencing it in the latest versions 🙂

**Closed by tsapeta** 2020-07-27 11:42 UTC
Labels: Audio, bug, iOS, needs repro

**Comment by pnadj** [comment] 2022-03-09 02:45
I am experiencing this issue, durationMillis is -26774660
