### ISSUE TITLE
navigation.dispatch doesn't work when the action is REPLACE

### ISSUE THREAD

**Issue by DizzasTeR** [expo/expo#27861] opened 2024-03-26 08:43 UTC
### Minimal reproducible example

https://github.com/DizzasTeR/expo-router-navigation-bug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

The file at `app\(pages)\mypage\edit\_layout.tsx` has an effect that subscribes to the _`"beforeRemove"`_ event of navigation listener events. When triggered, default behavior is prevented which stops the navigation action from happening and shows the user an Alert dialog to either stay on the route or proceed with the navigation action.

If the user decides to "Discard" then `navigation.dispatch` is called with the provided dispatch action.

### Expected behavior

- The navigation action is dispatched properly after `preventDefault()` in a `beforeRemove` navigation listener and then invoking `navigation.dispatch` with a replace action manually.

### Current behavior

- The navigation action is NOT dispatched properly after `preventDefault()` in a `beforeRemove` navigation listener and then invoking `navigation.dispatch` with a replace action manually.

***_WORTH NOTING_***: If you comment out `e.preventDefault()` and the Alert code from the useEffect, `router.replace` button works as expected

### Tested on

- Android native build via `npx expo run:android`
- Latest Expo SDK as of now (50) and expo-router v3.4.8

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 31, 33, 34
        Build Tools: 30.0.3, 33.0.1, 34.0.0
        System Images: android-34 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-223.8836.35.2231.10671973
    npmPackages:
      expo: ~50.0.14 => 50.0.14
      expo-router: ~3.4.8 => 3.4.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: bare
```

**Comment by marklawlor** [comment] 2024-05-09 09:17
The issue is that the navigator you are re-dispatching the event form is different to the the navigator that fired the event.

The child event has a `target` attribute that is causing the event to be misconfigured. A workaround is to  simply delete the `target` attribute

```
onPress: () => {
  delete e.data.action.target;
  navigation.dispatch(e.data.action);
},
```

This will work for most circumstances, but might cause issues if are navigating across shared groups.

I'm going to close this, as its probably not something we are going to fix, but I'll consider it for v4 when we move to React Navigation 7

**Closed by marklawlor** 2024-05-09 09:17 UTC
Labels: needs review, Router
