### ISSUE TITLE
Notifications.addNotificationReceivedListener() Does not trigger for server notifications ONLY local Expo SDK 39

### ISSUE THREAD

**Issue by Hudson784** [expo/expo#10357] opened 2020-09-24 14:45 UTC
### Summary of Issue 
I'm trying to get the Notifications listeners to work so I can handle the notification internally on my mobile phone when a notification is received.

### Steps to Reproduce
Use the expo push notification tool. 
Enter the device's push token.
Send a notification.

Code wise just use the official documentation for push notifications.

`useEffect(() => {
    registerForPushNotificationsAsync().then(token => setExpoPushToken(token));

    notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
      setNotification(notification);
    });

    responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
      console.log(response);
    });

    return () => {
      Notifications.removeNotificationSubscription(notificationListener);
      Notifications.removeNotificationSubscription(responseListener);
    };
  }, []);
`

### Expected Behavior vs Actual Behavior

Expected Behavior: 
Listeners are triggered upon receiving notification for both local and ones sent via server.

Actual Behavior
Listeners are not triggered for server/push notification tool ONLY local.

**Comment by Aryk** [comment] 2020-09-28 00:22
I also experiencing issues with addNotificationResponseReceivedListener after the upgrade. Is anyone else having problems also on SDK 39?

When I tried click into the app, the app actually froze everytime. If this is an SDK39 issue, it's pretty serious.

**Comment by cruzach** [comment] 2020-09-30 20:01
>Listeners are not triggered for server/push notification tool ONLY local.

This sounds like a credentials or push token issue. Unfortunately, there's very little to go off of here. In order for us to help you, you need to provide the responses from our push server (the push ticket and push receipt). For a guide on how to get those, please read this doc- https://docs.expo.io/push-notifications/sending-notifications/ 

specifically, you should run 
```
curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '{
  "to": "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]",
  "title":"hello",
  "body": "world"
}'
```
and you'll receive something like
```
{ "status": "ok", "id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" }
```

so then run:
```
curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/getReceipts" -d '{
  "ids": [
    "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  ]
}'
```
to get your push receipt which will contain an error message indicating what you should do next

**Comment by cruzach** [comment] 2020-09-30 20:25
I've reproduced this in the Expo client on android, and will be testing a standalone app soon.

So far, I have not been able to repro this on iOS so I am marking this as android only

**Comment by cruzach** [comment] 2020-10-01 14:25
@Hudson784 and @Aryk  do you have `android.useNextNotificationsApi` set to `true` in app.json?

**Comment by cruzach** [comment] 2020-10-01 15:14
This is probably due to the above configuration step, and if not then I think the same issue as https://github.com/expo/expo/issues/10416 so I'm going to close this for now

**Closed by cruzach** 2020-10-01 15:14 UTC
Labels: Android, Notifications

**Comment by Aryk** [comment] 2020-10-01 15:53
Hey @cruzach - after more deep diving it looks like the "freezing" was causing by the background task (background locations) on Android bug...I thought it was fixed on SDK 39, so I enabled that code and then my app started crashing again due to that.

As far as listeners on standalone Android go for notifications.. I'm only using "setNotificationHandler" and "addNotificationResponseReceivedListener". "addNotificationResponseReceivedListener" appears to be working from a dead start now for both iOS and Android, so I'm ok on this front.

FWIW I do have "useNextNotificationsApi" set to true as well.

**Comment by thedath** [comment] 2020-11-06 16:16
> @Hudson784 and @Aryk do you have `android.useNextNotificationsApi` set to `true` in app.json?

Doing this resolved my issue. Please make sure to add this in the documentation as well. Will save lot of time. Thanks!

**Comment by cruzach** [comment] 2020-11-06 16:40
@thedath it's in there- https://docs.expo.io/versions/latest/sdk/notifications/#android

**Comment by Hudson784** [comment] 2020-11-06 16:41
> @Hudson784 and @Aryk do you have `android.useNextNotificationsApi` set to `true` in app.json?

I forgot to respond sorry about that but the issue was I did not have the useNextNotificationsApi: true in my app.json
