### ISSUE TITLE
I send the notification but it doesn't arrive

### ISSUE THREAD

**Issue by Gustavoohrq** [expo/expo#7384] opened 2020-03-17 15:19 UTC
I do the whole process that is written in the documentation, but when I take the token and send the notification, it does nothing.

Version:

```json
    "expo": "~38.0.0",
    "expo-permissions": "~8.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-web": "~0.11.7"
```

**Comment by cruzach** [comment] 2020-03-17 20:44
`"expo": "~38.0.0",` isn't released yet, so I'm not sure how that dependency was set. 

You can test push notifications and see working code in this snack- https://snack.expo.io/@charliecruzan/pushnotifications36?platform=ios

that should help in debugging your current project. Closing this issue since it's not a bug report. With general questions like this, please post on [forums](https://forums.expo.io/) 😄

**Closed by cruzach** 2020-03-17 20:44 UTC
Labels: bug
