### ISSUE TITLE
[expo-location] watchHeadingAsync → remove() reliably crashes app with "this._eventEmitter.removeSubscription undefined"

### ISSUE THREAD

**Issue by fivecar** [expo/expo#14481] opened 2021-09-20 17:09 UTC
### Summary

If you `watchHeadingAsync` and then `remove()` on its LocationSubscription, the app crashes (at least on iOS).

```
  "dependencies": {
    "expo-location": "^12.1.2",
    "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-unimodules": "^0.14.8"
  },
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.22.5 - ~/.nvm/versions/node/v12.22.5/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.23.0 - ~/.nvm/versions/node/v12.22.5/bin/npm
      Watchman: 2021.09.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2 => 17.0.2 
      react-native: 0.65.1 => 0.65.1 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

1. `npx react-native init MyApp --template react-native-template-typescript`
2. Install unimodules using [official directions](https://docs.expo.dev/bare/installing-unimodules/).
3. Install `expo-location` using [official directions](https://www.npmjs.com/package/expo-location).
4. Secure necessary permissions using `requestForegroundPermissionsAsync()`.
5. Call `watchHeadingAsync`, keeping track of its awaited return value (LocationSubscription)
6. Call the subscription's `remove()`. Whether you do this immediately after, or you do this later, you'll always get a crash on `this._eventEmitter.removeSubscription` being undefined.

See here for code: https://gist.github.com/fivecar/f478e8ef11bc46de58d08c87773702a4

**Comment by darrylyoung** [comment] 2021-09-22 07:22
While I'm not using `expo-location`, I'm also seeing an issue on React Native `0.65.0` that's related to `EventEmitter` in my bare workflow app. In my case, I'm seeing it when I manually trigger an error in Sentry, which is pretty much [broken](https://github.com/getsentry/sentry-react-native/issues/1773) for me since upgrading to `@sentry/react-native` `3.x` and React Native `0.65.0` — this all feels related somehow. My Expo-related dependencies can be seen #14475, my other issue about React Native `0.65.0`.

<img width="564" alt="Screenshot 2021-09-22 at 08 51 44" src="https://user-images.githubusercontent.com/1460800/134299176-9da1695b-0b3c-46fc-88a0-2f9e594ba3d0.png">

**Comment by bbarthec** [comment] 2021-09-24 13:05
Hello @fivecar 👋 
Thank you for reporting this issue. It's seems to be similar to #14449. Apparently there's some change in `RN@0.65` affecting EventEmitter. [`react-native-unimodules@0.14.9`](https://www.npmjs.com/package/react-native-unimodules/v/0.14.9) and thus [`@unimodules/react-native-adapter@6.3.8`](https://www.npmjs.com/package/@unimodules/react-native-adapter/v/6.3.8) now contain the respective fix for this regression 🔧 
I'm tentatively closing this issue, but if the problem persists for some reason please be welcome to reopen 😊

**Closed by bbarthec** 2021-09-24 13:05 UTC
Labels: ⭐️ Root Cause Known, React Native 0.65
