### ISSUE TITLE
[expo-image][IOS] performance UI fps drop with react-native-pager-view

### ISSUE THREAD

**Issue by batuhansahan** [expo/expo#21030] opened 2023-02-01 07:20 UTC
### Summary

Using expo image with bare project with real device and ios emulator in project built with react-native-pager-view. 
I have 10 page each page has simple expo-image views that contains 1080p images. Transition between pages causes UI fps drops 60 to 55.

With fast-image and image from react native its 60 fps, thats why i am opening issue here.

note: android is ok.

### What platform(s) does this occur on?

iOS

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v14.18.0/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
      Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/user/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-native: ^0.70.5 => 0.70.5
    Expo Workflow: bare
```

### Minimal reproducible example

will add.

**Comment by tsapeta** [comment] 2023-02-11 22:04
You wrote that you will add a reproducible example, is this still true? The example would be very helpful and speed up fixing this issue 🙏

**Comment by tsapeta** [comment] 2023-02-20 23:32
I'm closing the issue because it doesn't provide a reproducible demo and I believe it has already been fixed in one of the newer beta versions – possibly as of `1.0.0-beta.6` which got some performance improvements on iOS.

Feel free to report back if the issue still exists in the latest release and if you can provide a minimal reproducible demo that would speed up the process of fixing the bug.

**Closed by tsapeta** 2023-02-20 23:32 UTC
Labels: iOS, Image, needs review
