### ISSUE TITLE
Running "npx create-expo-app@latest" is failing with several errors

### ISSUE THREAD

**Issue by gadgetman2016** [expo/expo#31913] opened 2024-10-08 03:43 UTC
### Summary

When running "npx create-expo-app@latest" to create a react-native-project, fails with permission errors, and exits with a non zero value when trying to install dependencies.

### What platform(s) does this occur on?

Web

### SDK Version

NA

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
```

### Minimal reproducible example

Just run "npx create-expo-app@latest test" and see if it completes without errors.

**Comment by basememara** [comment] 2024-10-08 05:37
I'm getting this too with the latest:

```
babel-plugin-react-compiler: Running postinstall script...
 ELIFECYCLE  Command failed.
Something went wrong installing JavaScript dependencies.
Error: npm install exited with non-zero code: 1
```

**Comment by basememara** [comment] 2024-10-08 06:05
seems related to #31912

**Comment by Brahmveda-PM** [comment] 2024-10-08 08:16
Facing same issue, when trying to create new app, i have tested it with machines, but same issue everywhere.

Command:
`npx create-expo-app`


It fails with below error,
```
npm error code 1
npm error path D:\Jaydeep\Projects\test\my-app\node_modules\babel-plugin-react-compiler
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c ./scripts/link-react-compiler-runtime.sh
npm error '.' is not recognized as an internal or external command,
npm error operable program or batch file.
npm error A complete log of this run can be found in: C:\Users\Admin\AppData\Local\npm-cache\_logs\2024-10-08T08_12_58_442Z-debug-0.log
Something went wrong installing JavaScript dependencies. Check your npm logs. Continuing to create the app.
Error: npm install exited with non-zero code: 1
```

**Comment by arkinvirani25** [comment] 2024-10-08 08:17
Facing same issue, when trying to create new app, i have tested it with machines, but same issue everywhere.

Command:
npx create-expo-app

It fails with below error,

`npm error code 1
npm error path D:\Jaydeep\Projects\test\my-app\node_modules\babel-plugin-react-compiler
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c ./scripts/link-react-compiler-runtime.sh
npm error '.' is not recognized as an internal or external command,
npm error operable program or batch file.
npm error A complete log of this run can be found in: C:\Users\Admin\AppData\Local\npm-cache\_logs\2024-10-08T08_12_58_442Z-debug-0.log
Something went wrong installing JavaScript dependencies. Check your npm logs. Continuing to create the app.
Error: npm install exited with non-zero code: 1`

**Comment by Jooona91** [comment] 2024-10-08 09:32
Same, getting issue with `npx create-expo-app@latest`

Getting error like `npm error code 127
npm error path /Users/ADMIN/Workspace/SeminarConnect/node_modules/babel-plugin-react-compiler
npm error command failed
npm error command sh -c ./scripts/link-react-compiler-runtime.sh
npm error sh: ./scripts/link-react-compiler-runtime.sh: No such file or directory
npm error A complete log of this run can be found in: /Users/ADMIN/.npm/_logs/2024-10-08T09_25_29_986Z-debug-0.log`

**Comment by cross19xx** [comment] 2024-10-08 11:36
I tried running on both a Windows and a Mac. It helps a lot if you can include other than the error message. Details like your node version, and NPM version. Also, you can review the logs specified to confirm if everything is as is.

I won't recommend typing "same" for an issue because it just balloons the conversations and solutions may be easy to miss

**Comment by werk42** [comment] 2024-10-08 11:37
Try installing `babel-plugin-react-compiler@0.0.0-experimental-734b737-20241003`

**Comment by anthonybtedesco** [comment] 2024-10-08 14:34
I had this same issue last night, however it works now.

**Comment by RSS1102** [comment] 2024-10-08 17:02
`npx create-expo-app@latest` after `npm run android`,

The app is always in a loading state

**Comment by gadgetman2016** [comment] 2024-10-08 20:25
Everything works now. Just tested it.

**Comment by jefffabiny** [comment] 2024-10-08 20:40
I am also experiencing this issue.

Node: v20.18.0
NPM: 10.8.2

<img width="658" alt="Screenshot 2024-10-08 at 16 38 57" src="https://github.com/user-attachments/assets/7a076302-c14f-4b0d-9675-70fce3bb77c4">

**Comment by cross19xx** [comment] 2024-10-09 17:11
> I am also experiencing this issue.
> 
> Node: v20.18.0 NPM: 10.8.2
> 
> <img alt="Screenshot 2024-10-08 at 16 38 57" width="658" src="https://private-user-images.githubusercontent.com/1752323/374718134-7a076302-c14f-4b0d-9675-70fce3bb77c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTQxMzgsIm5iZiI6MTcyODQ5MzgzOCwicGF0aCI6Ii8xNzUyMzIzLzM3NDcxODEzNC03YTA3NjMwMi1jMTRmLTRiMGQtOTY3NS03MGZjZTNiYjc3YzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMTcxMDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDhjZThjNzA5NTNjYzU1OWZlYzlhZWExN2I3MmIyMTI4OGZkYjlkZjU3NTcwYTdlMzEzMGYxMjRiNTk4MGI1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rzFy26Y3ChwmtuojTrSOdA2HClkQLSkmoxp9P29XyZk">

I don't see an error in your screenshot

**Comment by jefffabiny** [comment] 2024-10-09 18:10
@cross19xx Sorry, I got my tabs mixed up. I wanted to comment on a issue regarding npm warns for deprecated packages.

**Comment by brentvatne** [comment] 2024-10-10 17:10
dupe of https://github.com/expo/expo/issues/31912 - fixed by locking the react compiler version

**Closed by brentvatne** 2024-10-10 17:10 UTC
Labels: CLI
