### ISSUE TITLE
Error when using Notifications.dismissNotificationsAsync(localNotificationId) on iOS.

### ISSUE THREAD

**Issue by ismaelbarry** [expo/expo#7156] opened 2020-02-22 20:54 UTC
### Environment

Running  Expo SDK version: 36
Platform (Android/iOS/web/all): iOS

### Steps to Reproduce

When using Expo’s Local Notifications for iOS, I’m able to schedule future notifications using `Notifications.scheduleLocalNotificationAsync(localNotification, schedulingOptions)`. However, I get an error when trying to cancel a scheduled notification using `Notifications.cancelScheduledNotificationAsync(localNotificationId)`

The error I’m getting is the following: “Error: Could not find pending notification request to cancel with ID.” Unfortunately, the ID’s I’m getting are in this format: 013A99D3-B3EB-4884-852D-6C9D409238D4.

According to Expo, a number must be passed to the localNotificationId parameter in `Notifications.cancelScheduledNotificationAsync(localNotificationId`). However, there is no way to cast that ID to a number because it contains dashes and letters.

Is there something I’m missing here? Are there other ways to cancel any notification that has been scheduled in the future? Because, it’s not such a good idea for a user to be able to trigger future notifications and then not be able to cancel them if they change their mind.

### Expected Behavior

The `Notifications.cancelScheduledNotificationAsync(localNotificationId)` should cancel any future notification given the correct ID.

### Actual Behavior

The response I get from the error handler, that's printed to the console, is the following: "Error: Could not find pending notification request to cancel with id ="

### Reproducible Demo

Try to use `Notifications.scheduleLocalNotificationAsync(localNotification, schedulingOptions)` to schedule a future notification. Then use `Notifications.cancelScheduledNotificationAsync(localNotificationId)` to try to cancel it before it triggers. You'll get an error.

**Comment by cruzach** [comment] 2020-02-24 18:54
I just tested this, and it works for me

Can you try using this code:
```
try {
      const myid = await Notifications.scheduleLocalNotificationAsync(
        {
          title: "my title",
          body: "here is the body",
          data: { my: "data" },
          categoryId: "myCategoryName"
        },
        { time: new Date().getTime() + 1000 }
      );
      console.log(myid);
      await Notifications.cancelScheduledNotificationAsync(myid);
    } catch (e) {
      console.log(e);
    }
```

**Comment by painforever** [comment] 2020-03-03 22:32
Me too have this issue, I'm using like:

Notifications.cancelScheduledNotificationAsync(***).then(notification => {
                    console.log(`Notification successfully canceled: ${notification}`);
                }).catch(error => {
                    console.log("Cancel single notification error: ", error);
                });

but the catch is triggered always.

**Comment by ismaelbarry** [comment] 2020-03-04 05:18
> I just tested this, and it works for me
> 
> Can you try using this code:
> 
> ```
> try {
>       const myid = await Notifications.scheduleLocalNotificationAsync(
>         {
>           title: "my title",
>           body: "here is the body",
>           data: { my: "data" },
>           categoryId: "myCategoryName"
>         },
>         { time: new Date().getTime() + 1000 }
>       );
>       console.log(myid);
>       await Notifications.cancelScheduledNotificationAsync(myid);
>     } catch (e) {
>       console.log(e);
>     }
> ```

Hey cruzach--thanks for chiming in. Unfortunately, even using your approach, I'm still having problems. I get ` Error: Could not find pending notification request to cancel with id `.

**Comment by ismaelbarry** [comment] 2020-03-04 05:35
> Me too have this issue, I'm using like:
> 
> Notifications.cancelScheduledNotificationAsync(***).then(notification => {
> console.log(`Notification successfully canceled: ${notification}`);
> }).catch(error => {
> console.log("Cancel single notification error: ", error);
> });
> 
> but the catch is triggered always.

Yep, I'm having the same problem. I'm always falling into the catch block.

**Comment by cruzach** [comment] 2020-03-09 14:29
@ismaelbarry could you share a [snack](https://snack.expo.io/) that reproduces this? I've tried to reproduce myself and can't seem to get the same behavior you're describing

**Comment by cruzach** [comment] 2020-07-08 15:54
Hi everyone, I put together [this snack](https://snack.expo.io/@charliecruzan/notifications7156) to try and reproduce this on the new `expo-notifications` module we released with SDK 38, and it looks to be working as expected. Since I wasn't able to reproduce this on the old version either, I'd like to hear if this snack also works for you, so let me know! If it doesn't, please provide details about your device and OS version, and I'll reopen the issue

**Closed by cruzach** 2020-07-08 15:54 UTC
Labels: Notifications, bug, needs repro
