### ISSUE TITLE
iOS FileSystem Unable to save file to local URI

### ISSUE THREAD

**Issue by amowu** [expo/expo#739] opened 2017-10-06 09:51 UTC
I have a FileSystem problem, when I run the example code:

```js
const downloadResumable = FileSystem.createDownloadResumable(
  'http://techslides.com/demos/sample-videos/small.mp4',
  FileSystem.documentDirectory + 'small.mp4'
);

downloadResumable.downloadAsync()
  .then(({ uri }) => console.log(uri))
  .catch((error) => console.error(error));
```

I got a `Unable to save file to local URI` error.

My device is iPhone 7 iOS 10.0, and this is my packages:

```
"dependencies": {
  "expo": "^21.0.0",
  "react": "16.0.0-alpha.12",
  "react-native": "^0.48.4"
}
```

**Comment by jimmylee** [comment] 2017-10-06 21:07
Assigning to @nikki93 to take a look.

**Comment by peterlazar1993** [comment] 2017-10-10 03:30
I am also facing the same issue. It works fine on Android. This seems to be a regression in sdk 21, since it works on sdk 20

**Comment by inspireui** [comment] 2017-10-11 10:07
i've the same issue, please help to fix it

**Comment by thangvo9x** [comment] 2017-10-11 10:08
Hi, I've the same issue, please help to fix it, I tried many way but not can't

**Comment by nikki93** [comment] 2017-10-11 23:35
Hey all — looking at this issue now. Does it work when using FileSystem.downloadAsync without resumable?

**Comment by amowu** [comment] 2017-10-12 01:31
@nikki93 `downloadAsync()` is work.

**Comment by nikki93** [comment] 2017-10-12 01:37
Ok, figured out the issue. We should have a fix out in the next version. 😄

**Comment by peterlazar1993** [comment] 2017-10-12 05:35
@nikki93 Any idea when the next version is out?

**Comment by nicib83** [comment] 2017-10-12 08:43
@peterlazar1993 was it enough for you to do npm install expo@20.0 ?

**Comment by peterlazar1993** [comment] 2017-10-12 09:03
@nicib83 It's probably a little more involved than that. I'm going to do the same now, will report back how it goes. 
BTW take a look here https://forums.expo.io/t/how-to-downgrade-to-a-lower-expo-sdk-version/2099

**Closed** 2017-10-12 18:01 UTC
Labels: project: sdk

**Comment by nikki93** [comment] 2017-10-12 18:03
We landed a fix for this and the new version will be out soon (next 2-3 weeks, depends on Apple review process also). Feel free to continue discussing here!

**Comment by thangvo9x** [comment] 2017-10-13 08:12
In the future of expo version, you can update your Audio Component to get status for Data of audio when dowloading , because sometimes audio was be downloaded with isLoaded property clearly, but it have isBuffering should can not play immediately , I must waiting   isBuffering was be set to false . Thanks nikki93 !

**Comment by kaulsalil88** [comment] 2018-01-30 06:55
In what version of expo was this bug fixed ?? wanted to know .

**Comment by ironyee** [comment] 2018-07-28 19:00
I can not write files with filenames longer than 255. However, I can write such files only when I use `FileSystem.downloadAsync`. It is inconsistent.

**Comment by ironyee** [comment] 2018-07-29 02:48
[This](https://gist.github.com/ironyee/7b3432b8c846b671c25c232782c4e6be) is a CachedAudio I wrote.
