### ISSUE TITLE
[MapView][Android] getCamera results in "null is not an object `AirMapModule.getCamera`"

### ISSUE THREAD

**Issue by dtroydev** [expo/expo#4791] opened 2019-07-02 03:04 UTC
### Environment

Expo CLI 2.21.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.2 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.21.1

react-native-maps: 0.24.2

### Steps to Reproduce

MapView getCamera() method is not working on android but is fine on IOS

### Expected Behavior

Should work for both platforms

### Actual Behavior

When I use this code (on ios and android) it produces an error  on android (but is fine on ios):

  async getCamera() {
    const camera = await this.map.getCamera();
    console.log('Current camera', JSON.stringify(camera));
  }

The error is:
[Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNative.NativeModules.AirMapModule.getCamera')]

It appears to me that AirMapModule is missing inside of NativeModules

**Comment by dtroydev** [comment] 2019-07-02 06:05
I had to use fitToCoordinates method as a workaround because this works on both platforms, however it is not as good as animateCamera which gives you more control over what you can do.

**Comment by cruzach** [comment] 2019-07-02 18:54
Hey @dtroydev- since Expo provides a wrapper around `react-native-maps`'s Mapview, could you confirm for me that this behavior **doesn't** occur in a plain `react-native` app? That way we know it's a problem specific to Expo

**Comment by gabycasper007** [comment] 2019-07-23 04:19
Same problem here

**Comment by Omi-Navagis** [comment] 2019-08-14 00:33
"expo": "^33.0.5"
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz"
"react-native-maps": "^0.23.0",

I am using Expo and I got a same problem.
It occurs only for Android.

This is happening also in standalone app building via `expo build:android`.

**Comment by vyacheslav-o** [comment] 2019-09-03 09:04
Same problem.

**Comment by LudoLamerre** [comment] 2019-09-10 13:48
Same problem.

**Comment by heysailor** [comment] 2019-09-11 03:07
Same issue. [It's mentioned here as occuring only with expo](https://github.com/react-native-community/react-native-maps/issues/2679#issuecomment-463040601) on an issue in react-native-maps.

The solution proposed by @rborn, RNM collaborator, is to update the maps module - it's currently at 0.25.0, whereas expo 34 is using RNM 0.24.2.

**Comment by cruzach** [comment] 2019-09-11 15:47
`react-native-maps` was upgraded in [this commit](https://github.com/expo/expo/commit/42d90606cd210d431e6258cf3e4fcc599f94f7ab#diff-59a32acf8ffdd71c9795fd9bed65de0b), and will be released with SDK 35

**Comment by DDexster** [comment] 2019-09-23 13:58
Expo SDK 35 is on, `react-native-maps` is 0.25.0, but Error on Android still occurs:
```
[Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNative.NativeModules.AirMapModule.getCamera')]
```
IOS works fine!

**Comment by kkemple** [comment] 2019-10-04 16:55
I'm also still getting this error with version 0.25.0

**Comment by cruzach** [comment] 2019-10-07 15:24
@DDexster can you share the code you have that works for iOS but doesn't work for Android?

**Comment by DDexster** [comment] 2019-10-07 15:30
@cruzach, sure:

```
animateToLocation = async (region, heading, speed) => {
    if (this.state.userFollowEnabled) {
      let center = { latitude: region.latitude, longitude: region.longitude };
      if ([tripStatuses.arriving, tripStatuses.arrived, tripStatuses.enRoute].includes(this.props.tripStatus)) {
        const point = await this.mapRef.getCamera();
        console.log({ point });         // Breaks on Android
      }
      const camera = {
        center,
        pitch: 0,
        heading: this.state.rotationEnabled ? heading : 0,
        zoom: this._defineZoomBySpeed(speed)
      };
      this.mapRef.animateCamera(camera, { duration: 400 });
    }
  };
```

Diagnostics output: 
```
Expo CLI 3.2.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      npm: 6.11.3 - ~/.nvm/versions/node/v10.16.3/bin/npm
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 3.2.3
```

**Comment by cruzach** [comment] 2019-10-07 17:37
Confirmed that. Looks due to [this line](https://github.com/react-native-community/react-native-maps/blob/0f35b5da97d9367fd5496ae410314072f8c646c7/lib/components/MapView.js#L642)

Best to open a new github issue, consolidating this information, and a small repro, and we can get that assigned 😀

**Comment by oschade** [comment] 2019-11-02 11:48
Any updates on this?

**Comment by gabycasper007** [comment] 2019-11-10 04:31
Why is this closed? It's not solved. The problem still happens even after update.

**Comment by muz786** [comment] 2019-11-28 10:51
@cruzach Can you please reopen this issue. I have upgraded to expo sdk 35 and react-native-maps version is 0.25.0 but still getCamera() is giving error on Android.

**Comment by cruzach** [comment] 2019-12-02 15:21
It looks like it only occurs on Android, as mentioned by DDexster

Like I said above, best to open a new github issue, consolidating this information, and a small repro, and we can get that assigned

**Comment by cruzach** [comment] 2019-12-02 16:43
Just tested this in a bare react native project, and running into missing AirMap module as well (this issue actually https://github.com/react-native-community/react-native-maps/issues/3099) with `"react-native-maps": "^0.26.1"`

This may be an upstream issue, unrelated to the Expo SDK

**Comment by franciscailleAstus** [comment] 2019-12-05 14:58
Any idea when this fix will be coming out ?

**Comment by Saifadin** [comment] 2019-12-10 18:38
This is a really critical issue with anyone using Maps :/ any ETA?

**Comment by cruzach** [comment] 2019-12-10 23:18
@Saifadin it's still not clear that this is an issue with expo, and not with `react-native-maps`, as I said above. If you can provide more information that indicates the issue lies with Expo and not `react-native-maps`, that would be a big help!

**Comment by Saifadin** [comment] 2019-12-11 09:47
> @Saifadin it's still not clear that this is an issue with expo, and not with `react-native-maps`, as I said above. If you can provide more information that indicates the issue lies with Expo and not `react-native-maps`, that would be a big help!

I was not sure if maybe the AirMapModule is not properly linked on the Expo side. But it is a long running issue as it looks like.

**Comment by bautrukevich** [comment] 2020-01-22 16:45
Any updates?

**Comment by cruzach** [comment] 2020-01-22 17:02
Looks like this and https://github.com/expo/expo/issues/5996 are the same issue, I'm taking a look into this

**Closed** 2020-01-24 16:28 UTC
Labels: MapView, project: android-runtime

**Comment by cruzach** [comment] 2020-01-28 00:04
Patch has just been deployed, you'll need to rebuild your app with `expo build:android` to get the fix
