### ISSUE TITLE
Back button closes standalone Android apps after being closed due to memory pressure in the background

### ISSUE THREAD

**Issue by victorgoya** [expo/expo#1786] opened 2018-05-23 15:57 UTC
Hello!

No Snack because it works great in Expo, however I built a version of the NavigationPlayground app where I can reproduce the issue : https://expo.io/@phorque/NavigationPlayground (the APK is here https://exp-shell-app-assets.s3-us-west-1.amazonaws.com/android%2F%40phorque%2FNavigationPlayground-dfc90ac0-5e97-11e8-9603-0a580a780605-signed.apk )

I also made a small test app with Sdk 27 here https://expo.io/@phorque/lol2 (the code can be found here https://github.com/phorque/test-expo-navigation-bug and the APK is here https://exp-shell-app-assets.s3-us-west-1.amazonaws.com/android%2F%40phorque%2Flol2-42cbd554-5ea1-11e8-bb3e-0a580a780305-signed.apk )

### Environment

```
Environment:
  OS: Linux 4.13
  Node: 8.11.1
  Yarn: 1.2.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: 26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/phorque-a3331f72-2433-4d7a-8181-8d4487f63e7b.tar.gz
```

The issue occurs on Android standalone app, I couldn't test it on iOS.

### Steps to Reproduce

Every time the application reloads after it was backgrounded the back button always close the app. The best way to reproduce it is to:

* set the background process limits to "No background process" in developper options ;
* open the app (ex NavigationPlayground)
* switch to another app to put the first one in background
* go back to the first app 
* click on a subroute (for example the "Stack example" in NavigationPlayground)
* press the back button.

The process is pretty much the same with my small test app : 

##### Before background

* open the app
* click on profile
* click on the back button
* the app goes back to users

##### After the app is reloaded from background

* click on profile
* click on the back button
* the app closes

### Expected Behavior

I'd expect the app to goes back to the main menu.

### Actual Behavior

The app close and never goes back to the main menu.

### Reproducible Demo

https://expo.io/@phorque/NavigationPlayground and https://expo.io/@phorque/lol2 

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { createStackNavigator, createBottomTabNavigator } from 'react-navigation';

class Users extends React.Component {
  render() {
    return (<Text>Users</Text>)
  }
}

class Profile extends React.Component {
  render() {
    return (<Text>Profile</Text>)
  }
}


const Home = createBottomTabNavigator(
  {
    Users,
    Profile
  }
);

const MainNavigator = createStackNavigator(
  {
    Home,
  }
);

export default MainNavigator;
```

### Stuff I already tried

I tried a lot of stuff x)

* pretty much all combinations of navigators
* setting the `BackHandler` event by hand to make it always return true
* setting the `BackHandler` event in a setInterval and make it always return true so I'm sure I wasn't hijacked by another library (of course react-navigation stops working with this solution, it was just to investigate)
* make the `BackHandler` event of react-navigation always return true
* I tried react-navigation ~1.5 and ~2.0
* I tried with Expo SDK26 and Expo SDK27

Before the application is backgrounded the `BackHandler` events are fired and I can successfully prevent the app from closing at all (it's not the behavior I intended at first, but I was pretty desperate), however if the application reloads after being backgrounded the `BackHandler` doesn't seem to fire at all and the app always close, whatever I do.

AFAIK, all people who tested the app had the same behavior. I also can reproduce this issue in an emulator. Also, the NavigationPlayground on the PlayStore works great, so I'm really confused :c 

Please let me know if you need more explanations or tests from me! Thanks a lot for your great work :3

**Comment by Freeminderus** [comment] 2018-05-25 13:02
I have same problem, my setup:
react-navigation: 2.0.0
expo: sdk 27
react: 16.3.1
react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz

**Comment by phorque** [comment] 2018-06-07 13:31
After some discussion here https://github.com/react-navigation/react-navigation/issues/4329 I'm pretty sure this issue is related to Expo and not react-navigation.

It may also be related to this issue https://github.com/react-navigation/react-navigation/issues/4364

**Comment by brentvatne** [comment] 2018-06-07 23:17
minimal repro

```js
import React from 'react';
import { View, Text, BackHandler } from 'react-native';

class App extends React.Component {
  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', function() {
      return true;
    });
  }

  render() {
    return (
      <View><Text>I am a text</Text></View>
    );
  }
}

export default App;
```

needs to be run in standalone app

**Comment by phorque** [comment] 2018-06-13 18:51
More clues: I tried to detach my app and I tested both a debug build and a release build, on the debug build I couldn't reproduce the issue.

**Comment by jichu4n** [comment] 2018-06-21 18:50
Running into the same issue as well - after app is backgrounded for a while and resumed, the back button always closes the app, and does not trigger React-Navigation or a custom back handler.

Any known workarounds?

**Comment by esamelson** [comment] 2018-06-25 18:22
Hi all, just want to acknowledge we've seen and reproduced this error. We will try to look into a fix as soon as we can but cannot promise it on any certain timeline.

**Comment by phorque** [comment] 2018-06-25 18:24
Let me know if you want more tests and stuff like that :) thanks for you efforts!

**Comment by gnumarcelo** [comment] 2018-06-29 13:57
Don't know if this is related but I'm having the same issue when I import firebase (no in an Stand Alone App).
Like this issue: [react-navigation#4364](https://github.com/react-navigation/react-navigation/issues/4364)

**Comment by cristiantx** [comment] 2018-07-17 11:45
Same here. When running the application in debug mode it works as expected, but when running in non-dev mode. It just closes the app, it just ignores all the Back button handlers. I'm also importing Firebase, so it must be related to the issue. I can't imagine how!

**Comment by karlas** [comment] 2018-07-17 11:46
Just for the record, my project is also using Firebase

**Comment by karlas** [comment] 2018-07-26 11:38
Tried solution provided by @gnumarcelo and worked! Weird...

**Comment by themakerman** [comment] 2018-08-02 06:32
+1.....please fix it.....i am facing this on detached expo app and that too both with dev mode turned on and off. Using firebase as well.. @esamelson

**Comment by themakerman** [comment] 2018-08-02 06:44
I downgraded to firebase@5.0.2 and suddenly everything worked........

**Comment by themakerman** [comment] 2018-08-03 02:26
looks like derz a huge messup. One of my projects uses firebase@5.0.2 but still facing this problem.

**Comment by cristiantx** [comment] 2018-08-03 13:35
Workaround provided by @gnumarcelo on https://github.com/expo/expo/issues/1786#issuecomment-401362246 worked for me.

**Comment by themakerman** [comment] 2018-08-08 04:59
@om1 try downgrading firebase to different versions?

**Comment by gutoleao2** [comment] 2018-08-22 14:35
Funcionou 
[https://github.com/expo/expo/issues/1786#issuecomment-401362246](url)

Thanks! #

**Comment by om1** [comment] 2018-08-22 14:48
[@gnumarcelo](https://github.com/expo/expo/issues/1786#issuecomment-401362246) still not works for me. To which version should i downgrade firebase or what version are u guys using?

**Comment by phorque** [comment] 2018-08-22 14:53
I'm actually tempted to import Firebase in my project that doesn't need Firebase at all just to see if it makes things better x)

**Comment by cristiantx** [comment] 2018-08-22 14:53
@om1 `"firebase": "^5.0.4"`

**Comment by om1** [comment] 2018-08-22 14:54
Alright i'm using "firebase": "^5.3.0". I try to downgrade and report again.

**Comment by om1** [comment] 2018-08-22 15:02
Nothing has changed. App still closes after pressing the android back button.

**Comment by gutoleao2** [comment] 2018-08-22 15:07
@om1 
react-native init --version="0.55.4" <nome_do_app> 
npm install --save firebase
"_from": "firebase@latest",
  "_id": "firebase@5.3.1",
  "_inCache": true,
  "_location": "/firebase",
  "_nodeVersion": "8.11.1",
  
1 - CREATE A EXTERNAL FILE:

```
import firebase from "@firebase/app"
import "firebase/auth"
import "firebase/database"

var config = {
  apiKey: "",
  authDomain: "",
  databaseURL: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: ""
};

const Firebase = firebase.initializeApp(config);

export default Firebase;
```

2 - IN YOUR CLASS
import firebase from '../ YOUR FOLDER /firebase';

**Comment by om1** [comment] 2018-08-23 10:18
Still facing this issue. Maybe i'm doing something wrong with the imports...

**Folder structur:**

firebase/
   firebase.js
   auth.js  
   db.js
   index.js	
	
pages/
   HomePage.js
   Settings.js
	
This is what my **firebase.js** looks like:

```
import firebase from "@firebase/app"
import 'firebase/auth';
import 'firebase/database';

const config = {
    apiKey: "",
    authDomain: "",
    databaseURL: "",
    projectId: "",
    storageBucket: "",
    messagingSenderId: ""
};

if (!firebase.apps.length) {
    firebase.initializeApp(config);
}

const db = firebase.database();
const auth = firebase.auth();

export {
    db,
    auth,
    firebase
};
```
	
`auth.js` just imports auth from `firebase.js` and exports some firebase auth operations:

```
import {auth} from './firebase';

// Sign Up
export const doCreateUserWithEmailAndPassword = (email, password) =>
    auth.createUserWithEmailAndPassword(email, password);
...
```


`db.js` is importing db and firebase from `firebase.js` and exports some db operations:

```
import {db, firebase} from './firebase';

export const doCreateUser = (userId, username, email) =>
    db.ref(`users/${userId}`).set({
        username,
        email
    });
...	
```
and my `index.js ` is just exporting auth, db and firebase for later use:

```
import * as auth from './auth';
import * as db from './db';
import * as firebase from './firebase';

export {
    auth,
    db,
    firebase,
};
```
Then in my `HomePage.js` and `Settings.js` i import db and auth from `index.js` and go on with my app logic...

`import {db, auth} from "../firebase";`

Would be grateful if someone can give me a hint.

**Comment by om1** [comment] 2018-08-23 12:03
Finaly got it to work! Downgrade firebase to "^5.0.3" did it!  This whole mess up begins with firebase "^5.0.4". At least for me...

**Comment by alexcittadini** [comment] 2018-08-26 05:36
having this issue on SDK 27. I don't use firebase. Any updates for later sdks?

**Comment by gerardo15** [comment] 2018-09-04 15:30
I was having the same issue, i had to downgrade firebase to version 5.0.3

**Comment by fserafa** [comment] 2018-09-06 18:08
Got this problem and foud out that some lines of codes that include "Moment" package was the source of the problem

**Comment by themakerman** [comment] 2018-09-10 06:09
Does firebase has dependency on moment package? How is downgrading firebase solving the issue?

**Comment by fserafa** [comment] 2018-09-10 12:51
I don't think so, I'm not using firebase in my project. @themakerman

I did more research and moment is not the reason, I had some imports working together with moment and after I removed everything the problem was gone then I added it all again and started removing one by one and the problem is with this import :

`import 'core-js/es6/symbol'; `

Can't remember why I used this import, or maybe it was a coworker, I don't know yet, but now the problem is gone and I still using moment.

**Comment by Bunkerbewohner** [comment] 2018-09-10 13:38
I got the same problem using 

```json
  "dependencies": {
    "expo": "^29.0.0",
    "expokit": "1.5.0",
    "firebase": "^5.4.2",
    "react": "^16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz",
    "react-navigation": "^2.11.2",
  },
```

The hardwareBackPress event handler on BackHandler is never called. :-/

**Comment by praveenp-od** [comment] 2018-09-21 07:08
Even i changed the firebase version, this issue still there

**Comment by karlas** [comment] 2018-09-22 19:27
I think this can be very useful:

As I said, @gnumarcelo 's solution works. However, upgrading @firebase/auth from 0.7.5 to 0.7.6 and/or @firebase/database from 0.3.5 to 0.3.6 makes error come back.

So, I guess changed introduced in this last version can provide a very good clue about what's going on

**Comment by cmacdonnacha** [comment] 2018-10-07 11:17
Any update on this? Or a workaround? It's a pretty bad issue. I can reproduce and don't have firebase installed.

**Comment by victorgoya** [comment] 2018-10-07 12:13
Same here, I think it's the most common bug users of our app report :c

**Comment by arzola** [comment] 2018-10-09 19:30
I still have the same issue @victorgoya I did all of the steps that you performed and It's crazy, and I don't used firebase as well

**Comment by sk-publy** [comment] 2018-11-07 11:21
I'm not using firebase as well, but have the same problem.

Digging this BackHandler problem long long time, I found default expo app(sample app that you can install through 'expo init') has the same problem.

See the videos first.

Initial Launch(or restart app after manually kill the app using task manager)
https://youtu.be/espHwOxplvk
-> back button works well by moving to previous tab navigation.

Restart after android kill the app due to resource lack
https://youtu.be/H9hxjkNXslo
-> back button always sends the app to the background.

default project doesn’t use firebase at all.

Some more test detail:

- I tried to add event handler manually by ‘BackHandler.addEventListner’ after restart. but when I press back button, the event handlers are all skipped(I never removed the handler).
- I have tested on real devices such as Galaxy S9, Galaxy S4, and Mi5.

-> I concluded this is not a specific code/device issue, but Expo or React Navigation Issue(if anyone has used React Navigation without Expo, please let me know!).

**Comment by rahamin1** [comment] 2018-11-09 11:10
The workaround described by @gnumarcelo worked for me for some screens, but not for tab screens, where the default behaviour (going to the first tab) is kept. If anyone has an idea on how to make this work...

**Comment by Phredward** [comment] 2018-11-25 00:44
Just wanted to chime in that I am seeing this issue on expo 31.0.5, react-navigation 2.18.0.  Background processes set to 0 means back button exits the app on resume.

**Comment by npike** [comment] 2018-11-26 22:21
Also experiencing this on a brand new app made via expo.  Definitely don't use firebase in this app (yet).  Hoping for a quick resolution, as its visible enough to consider abandoning expo mere days after starting development.

**Comment by brentvatne** [comment] 2018-11-26 22:45
@npike - can you provide an apk?

**Comment by brentvatne** [comment] 2018-11-26 22:46
also can you describe the exact problem that you are seeing @npike? it sounds like people in this thread are describing a variety of similar but distinct issues

**Comment by npike** [comment] 2018-11-26 22:56
Sure. Bear with me as I am new to expo/react.  Is there a way I can share the APK privately?

```
    "expo": "^31.0.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "react-native-image-view": "^2.1.1",
    "react-native-material-textinput": "^1.1.0",
    "react-navigation": "^3.0.0"
```

On a fresh start of the app, when navigating from the first screen to a second screen, pressing the physical back button exits the app instead of navigating backwards.

**Comment by faozi07** [comment] 2018-11-28 10:05
just downgrade using firebase@5.0.3 it's work for me

**Comment by ljuborados** [comment] 2018-12-06 23:55
I'm having the same problem with back button exiting app on Android.
Steps to reproduce: 

1. expo init (select tab example)
2. replace createSwitchNavigator with createStackNavigator, add another screen to the stack navigator
3. add a button which should navigate to the new screen on press
4. build APK, install and launch, tap on button to navigate to next screen, tap back button - everything works as expected
5. either open few RAM intensive apps, or go to developer settings on Android and disable background processes, launch your app again
6. navigate to next screen, tap back button (Android system one, not the one in the status bar) - app exits

Repo with the code: https://github.com/ljuborados/back_handler_test
APK built with expo build:android: https://ufile.io/mw6ec
Video of the issue with the same APK, running on Note 9: https://youtu.be/tAK-Q0yiAcM

Thank you for your hard work, if I can do anything more to help please let me know!

**Comment by degamer106** [comment] 2018-12-11 00:32
@brentvatne @ide @AdamJNavarro 

I'm also seeing this issue with the default "Tabs" project and our App, which we just released to our customers through iOS/Android app stores.  Leaving the app in the background for something like 1-2 hours and them coming back will cause the Back Button to close the app.  All calls to react-navigation don't work.

Here's a more reliable way to reproduce this issue with the default "Tabs" project (Android v7.0+, Expo 31 SDK):
1. Open your app.
2. Click on the different tabs to navigate to the different screens and press the Back Button.  It should behave as expected.
3. Activate split-screen mode by long pressing the Square button at the bottom of the Android device.  This will cause the app to reload (I believe this can simulate the "memory pressure" scenario that everyone else in this thread mentioned)
4. Exit split-screen mode.  This will again cause the app to reload.
5. Click on the different tabs to navigate to the different screens.
6. Press the Back button.  App will close.

I also posted on the Expo forums here: https://forums.expo.io/t/expo-bug-after-a-crash-the-android-back-button-causes-standalone-app-to-be-put-into-the-background/16709

**Comment by ScottDikowitz** [comment] 2018-12-13 15:53
Did detaching to ExpoKit solve this for anybody?

**Comment by ljuborados** [comment] 2018-12-13 16:55
@ScottDikowitz I forgot to mention, my main project is on ExpoKit, same problem.

**Comment by esamelson** [comment] 2018-12-19 21:24
@gerardo15 - thank you for your clear explanation, this thread has gotten a bit out of hand. We will look into this as soon as we can.

To everyone else -- please do not comment on this thread further unless you're adding information that will directly help us fix this problem. I think we have plenty to go on now. Thank you!

**Comment by ruiwei** [comment] 2019-01-17 01:13
I have the problem on sdk30.

**Comment by lamipaul** [comment] 2019-01-21 12:19
> @brentvatne @ide
> 
> I can confirm there is a couple of issues in this post because I suffered from both.
> 
> One issue wich is not the one related to the main post is that using newer versions of firebase will not allow the back button to work. It will always Close the app, even on Expo, downgrading would fix it.
> 
> The issue that really needs to be fixed is that an standalone app that has been placed in the background and then opened up again. The back button will Close the app.
> 
> Its easy reproducible by the instructions given on the main post.

Hi all, 
Just a detail but for the standalone app issue : 
even without having placed the app in background, the back button closes the app (whereas it behaves as expected when run in expo).

**Comment by ruiwei** [comment] 2019-01-21 12:43
> > @brentvatne @ide
> > I can confirm there is a couple of issues in this post because I suffered from both.
> > One issue wich is not the one related to the main post is that using newer versions of firebase will not allow the back button to work. It will always Close the app, even on Expo, downgrading would fix it.
> > The issue that really needs to be fixed is that an standalone app that has been placed in the background and then opened up again. The back button will Close the app.
> > Its easy reproducible by the instructions given on the main post.
> 
> Hi all,
> Just a detail but for the standalone app issue :
> even without having placed the app in background, the back button closes the app (whereas it behaves as expected when run in expo).

Workaround the first issue: npm install firebase@5.0.3 (even you do not use firebase, no idea why).
For wake from the background, anyone has a workaround?

**Comment by FMCorz** [comment] 2019-01-27 19:10
I experienced the same issue with:

- Android 8.1.0
- Expo 31.0.2
- Expo CLI 2.6.14

When tapping the back button, the app would exit instead of navigating back.

I also found the following in `logcat`, which seems to coincide with the app exiting.

```
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: Error inserting period=4742000 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService required_network_type=0 runtime=1548614445128 source=4 target_package=com.google.android.gms source_version=14799000 last_runtime=0 user_id=0 job_id=-1 requires_charging=0 tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG flex_time=2370000 task_type=0 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}}
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:783)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1548)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1417)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at yxb.a(:com.google.android.gms@14799019@14.7.99 (040400-223214910):148)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at yzt.a(:com.google.android.gms@14799019@14.7.99 (040400-223214910):136)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at yzt.a(:com.google.android.gms@14799019@14.7.99 (040400-223214910):6)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at yzt.a(:com.google.android.gms@14799019@14.7.99 (040400-223214910):127)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at ywz.run(:com.google.android.gms@14799019@14.7.99 (040400-223214910):4)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at rab.run(:com.google.android.gms@14799019@14.7.99 (040400-223214910):21)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at rgd.run(Unknown Source:7)
01-28 02:40:45.146  4394 17682 E SQLiteDatabase: 	at java.lang.Thread.run(Thread.java:764)
```

The app does not use Firebase, but as suggested in other comments I added it. Though I did not install the older version as suggested. I simply ran `yarn add firebase` which installed the version `5.8.1`.

That fixed the problem... \o/

**Comment by hectorchu** [comment] 2019-02-08 12:25
@esamelson Any idea when this bug will get fixed? It's a serious problem.

**Comment by esamelson** [comment] 2019-02-12 02:21
Hi all, sorry for the super long followup time here. Finally had some time to dig into this, have a fix and am testing it now. It will almost certainly go out with the next SDK release but we might be able to backport it to SDK 32 as well.

Note that this issue has nothing to do with Firebase. If the issue you're seeing is fixed by or related to installing a certain version of Firebase, it's probably a different issue than the original one described here (which only occurs when "No background processes" is selected in the phone's Developer options).

I'm going to go ahead and lock this thread as it has become very noisy. If your issue has different repro steps than what's described in the original post, please open a new ticket as it probably won't be fixed by my change.

**Comment by esamelson** [comment] 2019-02-20 00:38
Hey all -- I've deployed the fix to our standalone app builders for SDK 32. You'll just need to rerun `expo build:android` (make sure you're on SDK 32) to get the fix. If you continue to experience similar issues, please go ahead and open a new ticket and fill out the details completely. I'm going to go ahead and close this as the issue is resolved.

**Closed by esamelson** 2019-02-20 00:38 UTC
Labels: project: android-runtime, status: pending
