### ISSUE TITLE
[SDK52] [expo/fetch] Error consuming streamed json response

### ISSUE THREAD

**Issue by matthiasbayer** [expo/expo#32953] opened 2024-11-15 17:09 UTC
### Minimal reproducible example

https://docs.expo.dev/versions/v52.0.0/sdk/expo/#expofetch-api

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

Consuming a stream of json objects seems to throw off the `expo/fetch` implementation.

Example

```ts
      const response = await fetch('https://httpbin.org/stream/1', {
        headers: { Accept: 'text/event-stream' },
      });

      const reader = response.body.getReader();
      await reader.read();
```

This will result in the following errors

<img width="658" alt="image" src="https://github.com/user-attachments/assets/01e4e374-f2c7-4f14-be1d-9ca095197bed">

I'm not sure if the actual content (JSON) matters in this case, but the /stream/ endpoint reliably provokes the error. Surprisingly, the response data is completely available and can be used regardless of these errors.

Right now this issue blocks compatibility with the Vercel AI SDK, since every network request produces these errors. See https://github.com/vercel/ai/issues/3705

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/Library/Caches/fnm_multishells/7155_1731685240576/bin/node
      npm: 10.2.4 - ~/Library/Caches/fnm_multishells/7155_1731685240576/bin/npm
      Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by brentvatne** [comment] 2024-11-15 23:04
i ran this in expo go for ios and it worked as expected:

```
import { Text, View, Button } from "react-native";
import { fetch } from 'expo/fetch';

async function fetchData() {
  const resp = await fetch('https://httpbin.org/drip?numbytes=512&duration=2', {
    headers: { Accept: 'text/event-stream' },
  });
  if (!resp.ok || !resp.body) {
    console.error('Error fetching data');
    return;
  }

  const reader = resp.body.getReader();
  const chunks = [];
  while (true) {
    const { done, value } = await reader.read();
    if (done) {
      break;
    }
    chunks.push(value);
  }
  const buffer = new Uint8Array(chunks.reduce((acc, chunk) => acc + chunk.length, 0));
  console.log(buffer.length); // 512
}

export default function Index() {
  return (
    <View
      style={{
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <Text>Edit app/index.tsx to edit this screen.</Text>
      <Button onPress={fetchData} title="Fetch data" />
    </View>
  );
}
```

**Comment by brentvatne** [comment] 2024-11-15 23:08
i was able to reproduce this with the exact code above using a development build

**Comment by matthiasbayer** [comment] 2024-11-15 23:11
The `/drip` endpoint worked fine for me, but the `/stream` endpoint reliably causes the error on both Go and a development build for me.

> we released 2.32.9 last night

let me double check that!

**Comment by brentvatne** [comment] 2024-11-15 23:12
i see, i just followed the instructions you provided for a minimal repro:

```
Minimal reproducible example
https://docs.expo.dev/versions/v52.0.0/sdk/expo/#expofetch-api
```

**Comment by matthiasbayer** [comment] 2024-11-15 23:13
Sorry I should've been more clear about what the good and bad code was.

**Comment by wcastand** [comment] 2024-11-18 11:45
getting the same issues trying to use it in an urql setup using streaming for subscription.

**Comment by Kudo** [comment] 2024-11-18 15:49
@brentvatne's issue for `Invalid state - currentState[4] validStates[2,3]` would be resolved by #33021. the root cause is to access response.body twice ([#1](https://github.com/brentvatne/testing-fetch-stream/blob/cafa2d45a454a879851cd88b5ab338c91f7f42de/app/index.tsx#L8) and [#2](https://github.com/brentvatne/testing-fetch-stream/blob/cafa2d45a454a879851cd88b5ab338c91f7f42de/app/index.tsx#L13))

but i think that's different to the original issue of `The stream is not in a state that permits close` which comes from `web-streams-polyfill`. @matthiasbayer could you upload a minimal repro project? i didn't see the problem from the following code. not sure if i have something different to your setup?

```tsx
import { fetch } from 'expo/fetch';

async function fetchData() {
  const response = await fetch('https://httpbin.org/stream/1', {
    headers: { Accept: 'text/event-stream' },
  });

  const reader = response.body.getReader();
  await reader.read();
}

export default function Index() {
  return (
    <View
      style={{
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <Text>Edit app/index.tsx to edit this screen.</Text>
      <Button onPress={fetchData} title="Fetch data" />
    </View>
  );
}
```

**Comment by matthiasbayer** [comment] 2024-11-19 06:16
Here is a minimal reproduction example: https://github.com/matthiasbayer/expo-fetch-bug

<img width="1519" alt="image" src="https://github.com/user-attachments/assets/0d04b527-35f8-4d66-a04c-645c45a1cafe">

Clicking the button triggers the described error.

**Comment by Kudo** [comment] 2024-11-19 11:10
@matthiasbayer cool thanks for the nice repro. looks like #33021 could resolve the issue as well. let's try again once we publish hotfix including #33021

**Comment by matthiasbayer** [comment] 2024-11-19 12:43
Sounds good! Any ETA on that?

**Comment by Kudo** [comment] 2024-11-20 10:36
> Sounds good! Any ETA on that?

should be available in `expo@52.0.8`. please give it a try and let me know whether it helps.

**Comment by wcastand** [comment] 2024-11-20 11:08
works for me !

**Comment by wcastand** [comment] 2024-11-20 12:19
i'm not 100% sure it's related but it seems to be related to expo/fetch 
but getting in dev mode a `stream was reset: INTERNAL_ERROR`

i can't manage to reproduce so can't really open an issue. seems random after a while it's happening.

using graphql subscriptions for streaming with expo/fetch

![Screenshot 2024-11-20 at 13 19 08](https://github.com/user-attachments/assets/9c9fbcab-c5d1-463b-94a7-a8f957e353b0)

**Comment by matthiasbayer** [comment] 2024-11-20 21:44
I can confirm that this is fixed by https://github.com/expo/expo/pull/33021. Great work 🙏

**Comment by brentvatne** [comment] 2024-11-20 21:48
@wcastand - if you manage to come up with a minimal repro, please post an issue with it! thanks

**Closed** 2024-11-20 21:47 UTC
Labels: incomplete issue: missing or invalid repro, needs review

**Comment by brentvatne** [comment] 2025-03-15 22:46
@ahmedrowaihi - if you manage to come up with a minimal repro, please post an issue with it! thanks
