### ISSUE TITLE
New update doesnt work on Android version 4.4.4

### ISSUE THREAD

**Issue by WeaVaer** [expo/expo#400] opened 2017-07-22 16:48 UTC
Expo client was working happily on my Samsung Galaxy Note (android 4.4) until I see the dreaded 'updating' sign for Expo client yesterday (07/20/2017) and ...
Wham!
it doesnt work anymore.

New updated Expo client just keeps stopping when I try to launch it, whilst it works on ios.
I have tried to uninstall it, clear app data and cache, reinstall but it doesnt work.

My work is clearly disrupted and I'm feeling bad about this.
I can't debug on my Android anymore.

**Comment by Aleksandern** [comment] 2017-07-24 11:54
the same problem. Expo client doesn't work on Android 4.4

**Comment by satya164** [comment] 2017-07-24 13:13
Duplicate of #395

**Closed by satya164** 2017-07-24 13:13 UTC
