### ISSUE TITLE
[expo-MapView] Can't get custom map style to work in Expo app

### ISSUE THREAD

**Issue by Derewith** [expo/expo#7140] opened 2020-02-21 11:33 UTC
## 🐛 Bug Report
Can't get custom map styling to work for my Expo iOS app. Example code below
### Environment
```
Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.2/11B52 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.13.1
```

app target: iOS TestFlight app

### Steps to Reproduce

In the Map component:
```import React from "react"  
import MapView, { PROVIDER_GOOGLE } from "react-native-maps" 
export const Map = () =&gt; {  
  return (  
    &lt;MapView  
      customMapStyle={mapStyle}  
      provider={PROVIDER_GOOGLE}  
    /&gt;  
  )  
}
const mapStyle = [ ...generated JSON from https://mapstyle.withgoogle.com  ]
```
and in my app.json:
```{
  "expo": {
    ....
    "ios": {
      ....
     "config": {
       "googleMapsApiKey": MY_API_KEY,
      }
    },
  }
}
```
### Expected Behavior
I've made sure i've enabled the Google Maps SDK for iOS service in the developer console, and have an unrestricted API key that allows both these services.

### Actual Behavior
Result is the Google Maps map shows but without the custom styling 

### Reproducible Demo
Ask me for the testflight link.
Anybody know anything about this? Haven't yet managed to test on Android so i'm not sure if it's something to do with iOS, or both, (or just something wrong in my code)

**Comment by expjess** [comment] 2020-02-21 23:23
Hey @Derewith - can you keep us posted on what you see if you manage to test on Android over the weekend? 🙏

**Comment by Derewith** [comment] 2020-02-23 11:19
Hey @expjess i am unable to build the apk to test in android this week, i 'll do it next week ..

**Comment by cruzach** [comment] 2020-02-24 18:16
@Derewith but this works correctly in the Expo client, the only issue is with a standalone iOS app?

**Comment by Derewith** [comment] 2020-02-24 18:37
@cruzach yes! You're right

**Comment by cruzach** [comment] 2020-02-24 22:05
Looks like the map isn't rendering, you might want to give this issue a look https://github.com/expo/expo/issues/5591

**Comment by Derewith** [comment] 2020-02-25 09:54
@cruzach i have looked at the issue you have posted and it seems that everyone is having an issue with googleMapsApiKey... what can u say?

**Comment by cruzach** [comment] 2020-02-25 15:22
Yeah, looks like this is a duplicate of the issue I linked, so I'm going to close this

It seems like this is a fix https://github.com/expo/expo/issues/2580#issuecomment-496321484 but I'll need to double-check that

**Comment by Derewith** [comment] 2020-02-25 16:01
@cruzach if you consider the problem as a duplicate remember that the other issue was on Android..

**Comment by cruzach** [comment] 2020-02-25 16:01
Ah you're right, sorry about that

**Comment by cruzach** [comment] 2020-02-25 16:08
When you built your app, was the apiKey present in app.json? Or did you add it in after running `expo build:ios`?

**Comment by Derewith** [comment] 2020-02-25 16:47
So the first build i had on TestFlight was with the problem of the apiKey missing ( making the app crash ), then the last build i am using have the apiKey added.
I've also done expo build:ios --clear-provisioning-profile --revoke-credentials..

**Comment by cruzach** [comment] 2020-02-25 16:53
so it's working since you rebuilt?

**Comment by Derewith** [comment] 2020-02-25 17:05
nope

**Comment by cruzach** [comment] 2020-02-25 18:13
sorry, you said no problem with the second build so I wasn't sure.

So just to confirm- the most recent build has the API key, so lack of an API key is definitely not the issue? I'm not able to reproduce this on my end, so investigating this is difficult. You're reporting that the custom map style isn't working- if you remove `customStyle`, does the map show up in the standalone app?

**Comment by Derewith** [comment] 2020-02-25 18:29
I think the problem is the ApiKey. 
Maybe I explained myself in a wrong way.

I've obtained the ApiKey only with in the _expo-cli_ in the Expo iOS Client.
In the iOS standalone app and in the published expo app i can't find any ApiKey using the alert from this code.
```
const manifestExtra = Constants.manifest.ios || {};
const config = manifestExtra.config || {};
const googleMaps = config.googleMapsApiKey || null;
alert(googleMaps+"[googleMapsApiKey]")
```

_With or without customStyle nothing change._

**Comment by cruzach** [comment] 2020-02-25 18:56
Can you double-check in https://console.developers.google.com/apis that you have enabled the google maps SDK for **iOS**

**Comment by Derewith** [comment] 2020-02-25 19:06
@cruzach checked, enabled for iOS/JavaScript/Android

**Comment by Derewith** [comment] 2020-02-26 15:43
Good news! I finally can say that the bug is fixed. 
How? I've had to create a new Api Key that is a RESTRICT KEY for iOS with the bundleIdentifier.
Thanks for everything @cruzach !

**Comment by cruzach** [comment] 2020-02-26 16:00
Thanks for taking a look at the new guide in that PR! Hopefully it helps others who run into the same issue 👍

**Closed by cruzach** 2020-02-26 16:00 UTC
Labels: MapView, bug, needs repro, project: ios-runtime

**Comment by soullivaneuh** [comment] 2020-10-15 17:44
> Thanks for taking a look at the new guide in that PR! Hopefully it helps others who run into the same issue

It does for me, but with this solution: https://github.com/expo/expo/issues/7140#issuecomment-591011320

Thanks @cruzach! :+1:
