### ISSUE TITLE
Jest fails on Expo projects upgraded to v31

### ISSUE THREAD

**Issue by FabianOMB** [expo/expo#2717] opened 2018-11-13 09:53 UTC
## Description
Testing with Jest fails with message "SyntaxError: Unexpected token {" on Expo projects upgraded to v31

## Expected Behavior
Tests to run 

## Observed Behavior
When running npm test on the upgraded project the following error is presented 

```
 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/fabian/TaBort2/node_modules/expo/build/environment/logging.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Constants } from 'expo-constants';
                                                                                                    ^

    SyntaxError: Unexpected token {

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.require (node_modules/expo/build/Expo.js:280:1)
```

## Environment
  Expo CLI 2.3.8 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.5 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.2 
    npmGlobalPackages:
      expo-cli: 2.3.8

## Reproducible Demo

To reproduce:
1. Create new Expo project 
expo init TaBort2  (select template tabs)

2. Test - It works fine
npm test

3. Remove folder node_modules

4. Reinstall all node_modules
npm install

5. Try to run and test
npm test
=> I get an error saying that it can't find jest.
"Cannot find module '/Users/fabian/TaBort2/node_modules/jest/bin/jest.js'"

6. install jest
npm install jest --save

7. Run test again
npm test
I now get the same behavior as in the upgraded projects with error "SyntaxError: Unexpected token {"

**Comment by FabianOMB** [comment] 2018-11-15 18:36
I checked the version of my npm, but I was already running the latest version of npm (6.4.1). 

I tried again with the same error. Then I tried running yarn in the same directory, and this solved the problem. 

A lot of warnings about mixing package managers but everything worked. 

Then I ran npm install again just to test, and this broke the code so the test stopped working again.

So I guess I just have to switch to yarn for a while...

Thank you for the solution.

**Comment by metz0r** [comment] 2018-11-19 11:38
Duplicate of https://github.com/expo/expo/issues/2595

**Closed** 2018-11-19 12:54 UTC

**Comment by Rajdeepc** [comment] 2019-03-06 09:34
I am getting error for all mock functions after upgrading to Expo 32.

Package.json:

```
"scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest-expo/bin/jest.js --coverage"
  },
  "jest": {
    "preset": "jest-expo"
  },
```

```
 "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.7.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-react": "^7.11.1",
    "jest-expo": "^32.0.0",
    "redux-mock-store": "^1.5.3"
  }
```

babel.config.js
```
module.exports = function (api) {
    api.cache(true);
    return {
        presets: ['babel-preset-expo'],
    };
};
```

jest.config.js
```
module.exports = {
    preset: 'jest-expo',
    transform: {
      '\\.js$': '<rootDir>/node_modules/react-native/jest/preprocessor.js',
    }
  };

```
Unit Test:
```
import configureStore from 'redux-mock-store';
import thunk from 'redux-thunk';

import { queryBuilder, getProductListHome, getListFormatted, prepareFacetData, getHeroSearchFacets, clearProductsListHome, getBannerData } from '@homeComponent/home.action';
import HttpClient from '@util/httpClient';
import { LOAD_PLP_DATA_CARS, SET_LOADING_CARS, SET_LOADING_BANNER, CLEAR_PRODUCT_LIST_CARS, LOAD_HEROSEARCH_FACETS, GET_BANNER_DATA }
    from '@homeComponent/home.types';

jest.mock('@util/httpClient');

  it('Dispatches SET_LOADING_BANNER true', async () => {
        HttpClient.ApiGet.mockResolvedValue({ bannerData });
        await store.dispatch(getBannerData());
        const actions = store.getActions();
        expect(actions[0]).toEqual({ type: SET_LOADING_BANNER, payload: { loading: true } });
    });

```
Error:

```
  ● Testing getBannerData() › Dispatches SET_LOADING_BANNER true

    TypeError: _httpClient.default.ApiGet.mockResolvedValue is not a function

      425 | 
      426 |     it('Dispatches SET_LOADING_BANNER true', async () => {
    > 427 |         HttpClient.ApiGet.mockResolvedValue({ bannerData });
          |                                        ^
      428 |         await store.dispatch(getBannerData());
      429 |         const actions = store.getActions();
      430 |         expect(actions[0]).toEqual({ type: SET_LOADING_BANNER, payload: { loading: true } });

      at _callee7$ (src/home/__test__/home.action.test.js:427:40)
      at tryCatch (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
      at tryCatch (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
      at invoke (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:152:20)
      at node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:187:11
      at tryCallTwo (node_modules/promise/lib/core.js:45:5)
      at doResolve (node_modules/promise/lib/core.js:200:13)
      at new Promise (node_modules/promise/lib/core.js:66:3)
```
