### ISSUE TITLE
Video doesn't have right dimensions on iOS 12

### ISSUE THREAD

**Issue by charlietango** [expo/expo#2286] opened 2018-09-24 20:43 UTC
Started to encounter issues with video dimensions on iOS 12. (on iOS 11 we've never faced this issue)

#### Implementation details:
video component is initialized with screen dimensions and a listener updates its dimensions when orientation changes. Changing screen orientation actually updates the dimensions and solves the issue.

### Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

### Expected Behavior

![simulator screen shot - iphone x - 2018-09-24 at 23 19 06](https://user-images.githubusercontent.com/7480480/45976743-473e9300-c050-11e8-90cf-3877d9cef660.png)

### Actual Behavior

![simulator screen shot - iphone x - 2018-09-24 at 22 41 41](https://user-images.githubusercontent.com/7480480/45976671-12324080-c050-11e8-9197-6ffa53677e03.png)

**Comment by esamelson** [comment] 2018-09-25 01:02
Hi @charlietango - thanks for the report. We'll look into this. Could you provide a simple [snack](https://snack.expo.io) that reproduces the issue?

**Comment by charlietango** [comment] 2018-09-25 12:14
@esamelson I've written a snack but the issue doesn't reproduce. I guess there is an issue with our app

**Comment by esamelson** [comment] 2018-09-25 21:48
Ok, thanks for the update. I'm going to close this for now, but if it turns out it is a general Expo issue and you can find a repro case, then let us know and we'll reopen.

**Closed by esamelson** 2018-09-25 21:48 UTC
Labels: project: media, project: sdk
