### ISSUE TITLE
DateTimePicker: Not showing spinner Date Picker in android in standalone apk

### ISSUE THREAD

**Issue by gypsicoder** [expo/expo#8200] opened 2020-05-07 17:56 UTC
## 🐛 Bug Report
Not showing spinner Date Picker in android in standalone apk. It's showing the spinner when I run the app in debug. But, when I make the apk it's not showing the spinner date picker.
### Environment

Expo CLI 3.8.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v12.8.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.8 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.3.1 => 4.3.9 

Android Standalone apk.

For Date picker I am using this package "@react-native-community/datetimepicker": "2.2.2"
Here are the codes
`<DateTimePicker
timeZoneOffsetInMinutes={0}
value={this.state.birthday === '' ? new Date() : new Date(this.state.birthday)}
mode={"date"}
is24Hour={true}
display={"spinner"}
onChange={this.onBirthdayChange}
style={{width:'100%', backgroundColor: 'white', position: 'absolute', bottom: 0, zIndex: 10}}/>`
### Steps to Reproduce

Build the standalone apk and test in android device. It will show default date picker though display is set to "spinner".

### Expected Behavior

It should show spinner type date picker in android in standalone version also.

### Actual Behavior

It's showing default date picker in the standalone android version.

**Comment by byCedric** [comment] 2020-05-11 16:27
Hi @gypsicoder, thanks for the issue report. Unfortunately, I can't reproduce this issue. I tried adding the date picker to a bare project and built an APK out of it. In both cases, the spinner was used. Could you provide [a small repro](https://stackoverflow.com/help/minimal-reproducible-example) for this?

**Comment by hasithaWalpola** [comment] 2020-05-15 12:50
Same issue happen for me, it showing default one
  <DateTimePicker
         value={new Date()}
         mode="date"
         onChange={this.handleDatePickerAndroid}
         onCancel={this.hideDatePicker}
         display="spinner"  />

**Comment by hasithaWalpola** [comment] 2020-05-18 04:51
@gypsicoder Hi, did you find any solution for this issue?

**Comment by gypsicoder** [comment] 2020-05-18 08:25
@hasithaWalpola Nope, I didn't found any solution. I just ejected expo and I am doing my project in bare react native. Totally removed expo.

**Comment by LucaRed** [comment] 2020-07-07 10:26
This issue happens for me too.

It correctly shows as spinner mode in Expo client, but when generating a standalone apk the "normal" calendar appears.

**Comment by karanmartian** [comment] 2020-07-20 18:47
Same issue here! Can you please fix this. Because I want my users to select birthdate and the normal calender mode is very cumbersome if one does not know that you can click on the year to change it. Its not user friendly in that sense greatly affecting signup time.

**Comment by karanmartian** [comment] 2020-07-20 18:49
> This issue happens for me too.
> 
> It correctly shows as spinner mode in Expo client, but when generating a standalone apk the "normal" calendar appears.

@LucaRed did you find any solution to this problem? I am really in a very urgent need.

**Comment by LucaRed** [comment] 2020-07-21 09:40
Unluckily, no. I'm also in a urgent need and I have the same problem (let users select a birthdate).

I had to implement a rather ugly custom picker made with three [React Native Picker](https://github.com/react-native-community/react-native-picker)s for day, month and year. Not an ideal solution at all.

**Comment by karanmartian** [comment] 2020-07-21 15:55
Check this out @LucaRed , this seems to be a repo that has the problem fixed, let me know:

https://github.com/Rejsal/react-native-datepicker

The corresponding source thread:
https://github.com/xgfe/react-native-datepicker/issues/414

**Comment by cruzach** [comment] 2020-11-10 21:03
This was fixed in SDK 39 by https://github.com/expo/expo/commit/2dd6dd04a5104642f7282debf5cc5a56a6d8262a, so I'm going to close this

**Closed by cruzach** 2020-11-10 21:03 UTC
Labels: Android, DateTimePicker
