### ISSUE TITLE
[expo-camera] Camera records black screen the first few seconds of recording on iOS.

### ISSUE THREAD

**Issue by gurugutten** [expo/expo#17884] opened 2022-06-16 10:58 UTC
### Summary

When start recording on iOS device > iPhone 12, camera records black screen the first 1-2 seconds. This works as expected on Android and older iPhones.

Expected result: after calling recordAsync() camera records video without black screen.

**Tested on:** 
- iPhone 12 Pro Max (iOS 15.4) - Not working as expected
- iPhone 13 Pro Max (iOS 15.4) - Not working as expected
- iPhone 11 - Working as expected

Possible related unresolved issue: #16698 

**Screencast of problem:**
https://hiof.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=9183690c-12ac-4232-ba91-aeb600b24ea0

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

Managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
      npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
    npmPackages:
      expo: ^45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.53.1
      expo-cli: 5.4.9
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@gurugutten/testcam

**Comment by brentvatne** [comment] 2022-06-17 17:51
Duplicate of #1057

Some possible workarounds discussed there. You might also want to try https://github.com/mrousavy/react-native-vision-camera with [development builds](https://docs.expo.dev/development/introduction/) and EAS Build

**Closed by brentvatne** 2022-06-17 17:51 UTC
Labels: needs review
