### ISSUE TITLE
Expokit 36 upgrade - Android build error. Manifest Merger.

### ISSUE THREAD

**Issue by owenhope** [expo/expo#6907] opened 2020-01-29 23:43 UTC
I am upgrading my detached expo app and I am stuck on android trying to build my project after following the instructions.

There seems to be an issue with the AndroidManifest.xml and appComponentFactory

```
`> Task :app:processDebugManifest FAILED
.../android/app/src/main/AndroidManifest.xml:26:1-78 Warning:
	Element uses-permission#com.google.android.c2dm.permission.RECEIVE at AndroidManifest.xml:26:1-78 duplicated with element declared at AndroidManifest.xml:13:3-80
.../android/app/src/main/AndroidManifest.xml:47:1-63 Warning:
	Element uses-permission#android.permission.INTERNET at AndroidManifest.xml:47:1-63 duplicated with element declared at AndroidManifest.xml:15:3-65
.../android/app/src/main/AndroidManifest.xml:55:3-342:17 Error:
	tools:replace specified at line:55 for attribute android:appComponentFactory, but no new value specified
.../android/app/src/main/AndroidManifest.xml Error:
	Validation failed, exiting

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs`
```

Has anyone else experienced this? Know any solutions?

**Comment by TristanGodal** [comment] 2020-01-31 08:51
Got something strange and similar too : 

`Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [host.exp.exponent:expoview:36.0.0] /Users/Koust/.gradle/caches/transforms-1/files-1.1/expoview-36.0.0.aar/84767f02cd824e0f70199264ad30dc23/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="host.exp.expoview" to force usage (may lead to runtime failures)
`

Any update on this ? I use minSdkVersion = 21 in my build.gradle file.

**Comment by cruzach** [comment] 2020-01-31 21:08
Hey @owenhope , if you're looking for help from others who have ugpraded their expokit projects to SDK 36, you're better off posting on our [forums](https://forums.expo.io/), since we keep Github reserved mainly for bug reports. Have you taken a look at your `AndroidManifest`? 

Closing since this is probably not a bug with the Expo SDK, but if you provide a reliable repro I'm happy to reopen

**Closed by cruzach** 2020-01-31 21:08 UTC
Labels: bug
