### ISSUE TITLE
[SDK37] FCM notification causes Expo built Android app to reload

### ISSUE THREAD

**Issue by Rafnexx** [expo/expo#9417] opened 2020-07-27 11:03 UTC
### Summary of Issue 
I have app with properly configured push notifications. I'm assuming it's properly configured because I'm getting notifications on development version (through explo client) and production version (app bundle and apk). My problem is that every time phone receives notification on production mode (installed with apk or from google play) app is reloading. If the app is in the foreground, the notification is not displayed and the apps just reloads as soon as the notification is received, when app is in the background and user taps the notifications - app opens and immediately reloads. When I say the app reloads I mean it looks like the app is being opened from a closed state (splash screen appears and initial page is displayed).

Since all works fine when connected to my local Expo CLI, I thought maybe production mode was what would trigger the issue, but things continue to work fine after switching my local Expo CLI to production mode.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
Expo CLI 3.22.3 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
    npmPackages:
      expo: ^37.0.0 => 37.0.3
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7
      react-navigation: ^4.0.10 => 4.0.10
```

### Reproducible Demo
I don't have demo cause problem occurs only when app is built.
 
### Expected Behavior vs Actual Behavior
Phone should receive notification and waits for user to interact with it - instead it's forcing app to reload.

**Comment by cruzach** [comment] 2020-07-27 13:42
You can still provide the code to reproduce this in a standalone APK, otherwise it is unlikely this issue will get much attention. I've tested a standalone Android app on SDK 38 with the new notification API, and SDK 37 with the legacy Notification api, and both worked for me. It's likely this issue is specific to your code and not a bug with the Expo SDK, so please provide a reproducible demo if you think otherwise. [Here](https://docs.expo.io/versions/latest/sdk/legacy-notifications/#api) is a sample app using the legacy notifications module (since you're on SDK 37 that is the only module available to you) to help get you started on a repro

**Comment by imdeepakchahar** [comment] 2020-07-27 19:17
Is app refreshing when the app is closed and starting after clicking on push notification?
Or refreshing when the app is in the background and you opening it by clicking on push notification.

And can you provide a sample of how you used `Notifications.addListener(handleNotification);` function and where you used this function or you did not handling notifications.

**Comment by cruzach** [comment] 2020-08-03 14:18
hey @Rafnexx I'm going to close this issue since we can't properly investigate without a reproducible demo, and we haven't received other reports of something similar happening. If you're able to provide us with the minimal code and steps to reproduce this issue, I can re-open

**Closed by cruzach** 2020-08-03 14:18 UTC
Labels: Android, Notifications, Requesting changes to issue, needs repro
