### ISSUE TITLE
IDFA tool(s) in Expo project are compromising projects for kids [docs] 

### ISSUE THREAD

**Issue by dogotaru** [expo/expo#7400] opened 2020-03-18 23:39 UTC
I get that from time to time there is a request to clear out things related to Apple's IDFA requirements, or remove IDFA related code altogether. And I am aware that the devs are advised what to do about IDFA when submitting the app, which I totally followed.
I guess after February, this year, at Apple they became stricter regarding apps for kids. What I've got is:
"We noticed that your Kids Category app includes analytics, advertising and collects, transmits, or has the ability to share personal information or device information with third parties.". This is already in reply to my other reply explaining the framework's Segment limitations.
Notice "has the ability" part? It doesn't really matter if our app is making any use of such functionality at all and just bundling this kind of functionality is enough to reject the app.
It can only worsen for other age ratings too, in the future.
Ejecting to bare workflow is surely possible, but would have been so nice to know in advance that Managed workflow's limitation is the inability to easily build apps for kids.
Cheers

**Comment by cruzach** [comment] 2020-03-20 13:36
Hi! Since this isn't a bug report, I'm going to close this issue. Although, I'd like to understand a little more about the situation, and we have a similar conversation going on [here](https://forums.expo.io/t/idfa-usage-explanation-on-the-website/34697). Could you explain a little more there about what you said to Apple regarding the IDFA code essentially never being used in your app, and what their response was? Thanks!

**Closed by cruzach** 2020-03-20 13:36 UTC
Labels: project: docs

**Comment by padrisimo** [comment] 2020-07-18 12:31
This is not a bug???!! How dare you!

Is dramatic, **you just cant use expo to create kids games or educational apps** because IDFA use of Segment Api embed in the core of Expo.

You don't care about kids I get it but at least don't be sarcastic.
