### ISSUE TITLE
Schedule a notification from api

### ISSUE THREAD

**Issue by mufaddalhamidofficial** [expo/expo#6377] opened 2019-11-26 11:40 UTC
The schedule notification can only be sent using `scheduleLocalNotificationAsync` but I want to schedule the notification by using api(In my server). Is their any other api to schedule a notification or any argument needed in previous api(https://exp.host/--/api/v2/push/send)

**Comment by cruzach** [comment] 2019-11-26 14:45
Hi! I'm going to close this since it's not a bug report. For questions like these, you're better off posting on our [forums](https://forums.expo.io/)

You can use the `expo-server-sdk` [here it is in Node](https://github.com/expo/expo-server-sdk-node). As for scheduling Notifications server-side, you'd have to implement your own logic for that.

**Closed by cruzach** 2019-11-26 14:45 UTC
