### ISSUE TITLE
Duplicate Contact objects returned when a single contact has multiple phone numbers

### ISSUE THREAD

**Issue by joshg111** [expo/expo#877] opened 2017-10-28 22:59 UTC
expo.Contacts.getContactsAsync() returns duplicate contacts. If a contact has multiple numbers a duplicate contact object is returned in the data array equal to the number of phone numbers that contact has. 

I'm using expo 22.0.0 and testing on android 7.1.1 and android 8.0.

**Comment by btk** [comment] 2017-10-29 18:42
This sounds like an expected behaviour. You should group that duplicate numbers in your end as you need them.

What was your expectation for this setup, if you think that is a design issue Expo's wrapper based on this; https://github.com/rt2zz/react-native-contacts

Also check this issue from that repository: https://github.com/rt2zz/react-native-contacts/issues/96

It is tagged as won't fix.

**Comment by joshg111** [comment] 2017-10-29 22:50
Thanks for your response. The observation I made for my app is different than the behavior mentioned in the issue you referenced. I can't say if this is expected behavior. Before I fix it in my app it would be good to get a definitive answer regarding expected behavior here.

**Comment by terribleben** [comment] 2017-10-31 17:13
@jesseruder is this expected behavior on Android? On iOS, all the phone numbers come back as an array on a single contact object.

**Comment by mathieumg** [comment] 2017-12-07 22:10
I have the same issue here, some contacts come back multiple times (and with the same ID), even though they each have multiple phone numbers listed. Here is an anonymized version of an occurence:

```js
// ...
{
  "firstName": "Jane",
  "id": "14",
  "imageAvailable": false,
  "lastName": "Doe",
  "name": "Jane Doe",
  "phoneNumbers": [
    {
      "id": "283",
      "label": "home",
      "number": "1 111-111-1111",
    },
    {
      "id": "284",
      "label": "mobile",
      "number": "1 222-222-2222",
    },
  ],
  "thumbnail": {
    "uri": null,
  },
},
{
  "firstName": "Jane",
  "id": "14",
  "imageAvailable": false,
  "lastName": "Doe",
  "name": "Jane Doe",
  "phoneNumbers": [
    {
      "id": "283",
      "label": "home",
      "number": "1 111-111-1111",
    },
    {
      "id": "284",
      "label": "mobile",
      "number": "1 222-222-2222",
    },
  ],
  "thumbnail": {
    "uri": null,
  },
},
// ...
```

**Comment by tiny-dancer** [comment] 2017-12-29 23:38
the issue here lies in the query being [executed on phone numbers](https://github.com/expo/expo/blob/master/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/ContactsModule.java#L79) and not contacts

this leads to expo contacts being created out of phone numbers, meaning:
- contacts without a phone number are not retrieved
- contacts with X amount of phone numbers are duplicated X times. 

a side effect is performance issues: 
- base query is pulling phone numbers, any additional data is additional queries.
- querying phone numbers leads to a larger than necessary query response (phones numbers vs contacts)

following react-native-contact's approach of base query [targeting the contact data uri](https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java#L125) led to retrieving all contacts faster than current default 100 item paged expo query.

working on some updates here that the expo team can evaluate.

**Comment by ide** [comment] 2017-12-30 09:54
@tiny-dancer Thanks for digging in and identifying what looks like the root cause and a possible performance improvement :)

**Comment by aalices** [comment] 2018-01-02 15:40
@tiny-dancer thanks for commitment! Duplicated contacts sound crazy! Actually it seems that changing query won't actually fix this (but will include contacts without a phone number).  `ContactsContract.Data.CONTENT_URI` will create an entry for every available contact info (phone, mail, name, whatever) so where's going to be even more duplicates :( what react-native-contacts does is actually storing "visited" ids and do not include the entry in response if it has been read earlier. That would make a performance enhancement for Expo :)

**Closed** 2018-01-11 10:23 UTC
Labels: in review, project: android-runtime, project: sdk

**Comment by kaulsalil88** [comment] 2018-03-05 09:58
@aalices  in which version of expo sdk is this fixed or do I need to do some thing else to solve this issue .

**Comment by kaulsalil88** [comment] 2018-03-05 10:35
@aalices  in which version of expo is this fixed ?

**Comment by brentvatne** [comment] 2018-03-05 19:46
sdk 25
