### ISSUE TITLE
[docs] Deprecated AsyncStorage usage in docks

### ISSUE THREAD

**Issue by uladzimir-masla-itechart** [expo/expo#4117] opened 2019-05-02 09:50 UTC
Async storage is now deprecated as mention in [react native docks](https://facebook.github.io/react-native/docs/asyncstorage).
But expo [documentation](https://docs.expo.io/versions/v32.0.0/react-native/asyncstorage/) doesn't mention this.

**Comment by edoantonioco** [comment] 2019-05-26 01:18
From RN perspective the one that is included into RN core its deprecated. But isnt Expo going to include the latest of this version react-native-community/react-native-async-storage and include it inside expo?

Because in that case, the asyncstorage in expo wont be deprecated. Same as WebView

**Comment by ankhzet** [comment] 2019-06-17 09:40
It is not deprecated, it is just moved to separate package.

Still, expo's fork of RN pollutes console with annoying warning `Async Storage has been extracted from react-native core and will be removed in a future release`. The issue is with some other expo packages, that are still using the internal version of AsyncStorage package (Notifications, f.e.), thus yielding a console warning even if developer himself already switched to react-native-community version.

**Comment by copleykj** [comment] 2019-07-01 12:48
Are there any plans to add AsyncStorage to the Expo API? I think since it's used by other parts of the API it would be a good idea. I also use AsyncStorage for just about every project so having to eject every project to get access to AsyncStorage would be ridiculous.

**Comment by cruzach** [comment] 2019-07-01 14:05
@copleykj- Why would you have to eject to use Async Storage? 

Closing this issue, we will provide an alternative before this becomes a problem!

**Closed by cruzach** 2019-07-01 14:05 UTC
Labels: project: docs

**Comment by copleykj** [comment] 2019-07-02 11:38
@cruzach The use of `@react-native-community/async-storage` replacement module requires the use of `react-native link` to build native modules. As far as I know this requires detaching to expokit.

> we will provide an alternative before this becomes a problem!
That would be fantastic, thanks!

**Comment by cruzach** [comment] 2019-07-02 14:06
Ahh okay you meant in the future, I thought you meant you'd have to eject using the current version (my mistake)

Yeah, we definitely want to provide another alternative for the managed workflow! That way, no need for you to eject any projects for that functionality

**Comment by epinnock** [comment] 2019-09-18 16:50
@cruzach is there an open ticket to upgrade async storage

**Comment by cruzach** [comment] 2019-10-02 18:26
@epinnock no open ticket just yet, but we won't leave you with no option! In the short-term we plan to continue supporting the currently shipped library, while we work on a long-term replacement

**Comment by ryan2clw** [comment] 2019-12-20 14:19
I've been using expo-secure-store for some limited client side storage, which has been working great, but that AsyncStorage in the Notifications module causes some problems on low quality android devices.  It would be great if that was refactored to use the community edition.  Thanks in advance.

**Comment by chiechelski** [comment] 2020-01-21 19:05
@cruzach , any idea when the upgrade is going to be included on the dev roadmap?

**Comment by cruzach** [comment] 2020-01-21 19:20
still no concrete plan on it yet, we are prioritizing a few other things for this next SDK release. What are some of the main issues you're seeing with the deprecated AsyncStorage module from `react-native`?

**Comment by chiechelski** [comment] 2020-01-21 20:01
I don't have any issue. I am just upgrading all libraries and trying to remove all deprecated ones, but I guess I can leave that one until you guys make the change anyway. Thanks mate.
