### ISSUE TITLE
Start up error not tracked by Sentry

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#3216] opened 2019-01-15 03:54 UTC
### Environment
```
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.10.1 - ~/.nvm/versions/node/v9.10.1/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v9.10.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.2.0 => 16.3.0
    npmGlobalPackages:
      expo-cli: 2.6.14
```

Error only seen in iPhone 8 Plus, iOS 12.1.2

### Steps to Reproduce
* I created an App standalone build with Sentry
* An user installed the app in an iPhone 8 Plus with iOS 12.1.2
* App get frizzed in the splash page
* After a couple of seconds, I get the white page (check screenshot)
* Sentry never tracks the issue

![img_1266](https://user-images.githubusercontent.com/1837969/51159404-db36a380-1867-11e9-834e-b5422bd56644.PNG)

### Expected Behavior
* Sentry should track the issue

### Actual Behavior
* Sentry is not tracking the error

### Reproducible Demo
* This is the app that is failing: https://itunes.apple.com/us/app/nofilter-photo-spots/id1445583976
Version 1.5.1. But I'm not sure if this is reproducible in all the iPhones 8 Plus. I only know that in one device (a friend device) is doesn't work

# Important comment
The app was crashing even before I added Sentry.
I added Sentry just to track that error and been able to fix it.

*package.json*
```json
{
  "name": "no-filter-app",
  "version": "1.5.1",
  "private": true,
  "devDependencies": {
    "jest-expo": "^32.0.0",
    "react-native-scripts": "1.14.0",
    "react-test-renderer": "16.3.1"
  },
  "main": "./node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "eject": "expo eject",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/react-native-action-sheet": "^1.1.2",
    "@turf/center-median": "^6.0.1",
    "@turf/clusters": "^6.0.1",
    "@turf/clusters-dbscan": "^6.0.1",
    "duix": "^1.0.2",
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-snap-carousel": "^3.7.5",
    "sentry-expo": "^1.11.2"
  }
}
```

*app.json*
```json
{
  "expo": {
    "name": "NoFilter",
    "icon": "src/styles/imgs/nofilter-icon.png",
    "splash": {
      "backgroundColor": "#000",
      "resizeMode": "cover",
      "image": "src/styles/imgs/splash-screen-ph.png"
    },
    "version": "1.5.1",
    "slug": "xxxxx",
    "sdkVersion": "32.0.0",
    "scheme": "nofilter",
    "assetBundlePatterns": [
      "node_modules/@expo/vector-icons/fonts/MaterialCommunityIcons.ttf",
      "node_modules/@expo/vector-icons/fonts/MaterialIcons.ttf",
      "node_modules/@expo/vector-icons/fonts/Feather.ttf",
      "node_modules/@expo/vector-icons/fonts/SimpleLineIcons.ttf",
      "src/styles/fonts/Montserrat/Montserrat-Regular.ttf",
      "src/styles/fonts/Montserrat/Montserrat-Medium.ttf",
      "src/styles/fonts/Montserrat/Montserrat-SemiBold.ttf",
      "src/styles/fonts/Montserrat/Montserrat-Bold.ttf",
      "src/styles/imgs/nofilter-icon.png",
      "src/styles/imgs/nofilter-logo-v.png",
      "src/styles/imgs/splash-screen-ph.png",
      "src/styles/imgs/splash-screen-ph.jpg"
    ],
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "broda-noel",
            "project": "nofilter",
            "authToken": "xxxxx"
          }
        }
      ]
    },
    "ios": {
      "buildNumber": "1.5.1",
      "bundleIdentifier": "app.no-filter.nofilter",
      "config": {
        "googleMapsApiKey": "xxxxxxx"
      },
      "infoPlist": {
        "NSLocationWhenInUseUsageDescription": "NoFilter uses your location to see how far you are from spots, and also to show you your position in the map"
      }
    },
    "android": {
      "versionCode": 17,
      "package": "app.no_filter.nofilter",
      "config": {
        "googleMaps": {
          "apiKey": "xxxxx"
        }
      },
      "permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION"
      ]
    }
  }
}
```

*App.js*
```js
import React, { Component } from 'react';
import { View, StatusBar, BackHandler, AsyncStorage, StyleSheet } from 'react-native';
import { Font, AppLoading } from 'expo';
import { ActionSheetProvider } from '@expo/react-native-action-sheet';
import Sentry from 'sentry-expo';
import { MaterialCommunityIcons, MaterialIcons, Feather, SimpleLineIcons } from '@expo/vector-icons';
import duix from 'duix';
import Login from './src/pages/Login';
import Explore from './src/pages/Explore';
import Profile from './src/pages/Profile';
import Collections from './src/pages/Collections';
import NavBar from './src/components/NavBar';
import Snackbar from './src/components/Snackbar';
import BlockerAlert from './src/components/BlockerAlert';
import { CATEGORY, HALF_DAY } from './src/utils/consts';
import drone from './src/drone';
import { isiPhoneX } from './src/utils/devices';
import base from './src/styles/base';

// Remove this once Sentry is correctly setup.
// Sentry.enableInExpoDevelopment = true;

Sentry.config('https://xxxxxx@sentry.io/xxxx').install();

duix.set('snackbars', []);
duix.set('isLoadingSpots', false);
duix.set('isModalShown', false);
duix.set('user', null);
duix.set('lastPage', null);
duix.set('currentPage', 'Loading');
duix.set('filters', Object.values(CATEGORY).map(x => ({ ...x, isSelected: true })));
duix.set('spots', []);

class App extends Component {
  unsubscribe = [];

  state = {
    currentPage: 'Loading',
    spotsCount: 0
  };

  componentDidMount() {
    let proms = [];
    proms[0] = Font.loadAsync({
      'montserrat-regular': require('./src/styles/fonts/Montserrat/Montserrat-Regular.ttf'),
      'montserrat-medium': require('./src/styles/fonts/Montserrat/Montserrat-Medium.ttf'),
      'montserrat-semibold': require('./src/styles/fonts/Montserrat/Montserrat-SemiBold.ttf'),
      'montserrat-bold': require('./src/styles/fonts/Montserrat/Montserrat-Bold.ttf'),
    });
    proms[1] = Font.loadAsync(MaterialCommunityIcons.font);
    proms[2] = Font.loadAsync(MaterialIcons.font);
    proms[3] = Font.loadAsync(Feather.font);
    proms[4] = Font.loadAsync(SimpleLineIcons.font);

    BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
    drone.page.listen();

    this.unsubscribe[0] = duix.subscribe('currentPage', this.onCurrentPageChange);
    this.unsubscribe[1] = duix.subscribe('spots', this.onSpotsChange);

    AsyncStorage.getItem('spots-date').then((lastUpdate) => {
      const isFirstTime = !lastUpdate;

      if (isFirstTime) {
        drone.db.user.listen();
        drone.db.spots.listen();
        drone.spots.update();

        Promise.all(proms).finally(() => {
          duix.set('currentPage', 'Login');
        });

      } else {
        // Load data
        drone.db.load().then((data) => {
          drone.db.user.listen();
          drone.db.spots.listen();

          Promise.all(proms).finally(() => {
            if (data.user && data.user.token) {
              duix.set('currentPage', 'Explore');
            } else {
              duix.set('currentPage', 'Login');
            }
          });

          // Async update Spots
          const noSpots = !data.spots || !Array.isArray(data.spots) || !data.spots.length;
          lastUpdate = Number(lastUpdate);
          if ((Date.now() - lastUpdate) > HALF_DAY || noSpots) {
            drone.spots.update();
          }
        });
      }
    });
  }

  componentWillUnmount() {
    this.unsubscribe[0]();
    this.unsubscribe[1]();
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
  }

  onBackPress = () => {
    const lastPage = duix.get('lastPage');

    if (lastPage && lastPage !== 'Loading') {
      duix.set('currentPage', lastPage);
      return true;
    }

    return false;
  };

  onCurrentPageChange = (currentPage) => {
    this.setState({ currentPage });
  };

  onSpotsChange = (spots) => {
    this.setState({ spotsCount: spots.length });
  };

  render() {
    if (this.state.currentPage === 'Loading') {
      return <AppLoading />;
    }

    if (this.state.currentPage === 'Login') {
      return <Login />;
    }

    return (
      <ActionSheetProvider>
        <View style={[{ flex: 1 }]}>
          <StatusBar
            translucent={true}
            backgroundColor="#FFF"
            barStyle="dark-content" />

          <View style={[{ flex: 1 }]}>
            {
              {
                Explore: <Explore hideChildren={this.state.spotsCount === 0} />,
                Collections: <Collections />,
                Profile: <Profile />
              }[this.state.currentPage]
            }
          </View>

          <View style={[base.shadowTop, styles.navbar]}>
            <NavBar />
          </View>

          {
            this.state.spotsCount === 0 &&
            <BlockerAlert />
          }

          <Snackbar iAmModal={false} />
        </View>
      </ActionSheetProvider>
    );
  }
}

const styles = StyleSheet.create({
  navbar: {
    height: isiPhoneX() ? 65 : 50,
    paddingBottom: isiPhoneX() ? 15 : 0
  }
});

export default App;
```

# Alternative question:
Besides Sentry is not catching the errors, do you have any idea why could the app be crashing? It's working Ok on all android and iOS I tested, less than one iPhone 8 Plus.
Any recomendation about how to fix it?

**Comment by BrodaNoel** [comment] 2019-01-15 23:42
I see that Sentry tracks the error the second time the App is opened, but my friend did it more than 1 time, and it was never reported.

What do you mean with `expo --no-dev --minify`? `--no-dev` is an unknown option on my terminal.

**Comment by tcdavis** [comment] 2019-01-16 23:15
Sorry, `expo start --no-dev --minify`
If you use the web interface, there is a Production toggle in the left gutter that does the same

**Comment by BrodaNoel** [comment] 2019-01-17 00:17
@tcdavis Clould you please give more details about what should I do, and what is the expected thing that should happens?

I could not get what do you recomend to do, and why.

**Comment by tcdavis** [comment] 2019-01-17 00:49
Sure :)
Since it sounds like sentry is configured correctly and sending events except for this particular case I don't think we can be particularly helpful with why this particular error is not being reported.  (You may have more luck talking to someone at sentry directly)

But you still have a crash you need to reproduce.  It sounds like the error is in some way device specific and you're lucky enough to have access to one of the specific devices that is hitting it, so I'm recommending you get that device and try to reproduce it.
One place a bug might be hiding is there are small differences between the development environment and how your app runs in production.  The --no-dev flag removes the development options and --minify runs a transform to shrink the size of your javascript.  Passing both gets you as close to the production environment as possible and will give you the best chance of successfully reproducing the issue.

Once you have it reproduced, you'll have a chance to understand what is going wrong and how to fix it.

**Comment by BrodaNoel** [comment] 2019-01-17 17:24
@tcdavis I get your point.
My problem is that actually, my friend is not close to me at all.

I just installed the app in another iPhone 8 Plus and everything work as expected. That's a problem because my friend still having the same issue.
I'm worried about it because I don't actually know if that error is happening in more devices :/

Thank you a lot for your long explanation.

**Comment by BrodaNoel** [comment] 2019-02-13 00:25
@sjchmiela @ide I just saw you made a commit with a reference to this issue. Was it a reference mistake?

**Comment by ide** [comment] 2019-02-14 00:59
@BrodaNoel - yes, the issue number is referring to that of another repo and is unrelated to this issue.

**Comment by tsapeta** [comment] 2020-07-18 15:03
Expo SDK32 that you referred to is no longer supported and I'm afraid we can't do anything without more details and especially without reproducible example 😞 
I'm closing it as there hasn't been any activity recently, but feel free to open a new issue once you get more details about the issue you encountered.

**Closed by tsapeta** 2020-07-18 15:03 UTC
