### ISSUE TITLE
application main has not been registered SDK35

### ISSUE THREAD

**Issue by anniekvandijk** [expo/expo#5836] opened 2019-10-02 14:31 UTC
## 🐛 Bug Report

Tried to update Expo SDK 34 > 35 and publish. 
Open in expo on Iphone X
error: application main has not been registered

package.json 34
```
 "dependencies": {
    "@expo/vector-icons": "^10.0.3",
    "expo": "^34.0.4",
    "expo-font": "^6.0.1",
    "expo-localization": "^6.0.0",
    "firebase": "^6.3.4",
    "i18next": "^17.0.10",
    "native-base": "^2.13.5",
    "prop-types": "^15.7.2",
    "react": "^16.8.3",
    "react-dom": "^16.8.6",
    "react-i18next": "^10.11.5",
    "react-native": "^0.59.8",
    "react-native-dotenv": "^0.2.0",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-reanimated": "~1.1.0",
    "react-native-unimodules": "~0.5.2",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.1"
  },
```

package.json 35
```
"dependencies": {
    "@expo/vector-icons": "^10.0.3",
    "expo": "^35.0.0",
    "expo-font": "^7.0.0",
    "expo-localization": "^7.0.0",
    "firebase": "^6.3.4",
    "i18next": "^17.0.10",
    "native-base": "^2.13.5",
    "prop-types": "^15.7.2",
    "react": "^16.8.3",
    "react-dom": "^16.8.6",
    "react-i18next": "^10.11.5",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-dotenv": "^0.2.0",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-reanimated": "^1.2.0",
    "react-native-unimodules": "~0.5.2",
    "react-native-web": "^0.11.4",
    "react-navigation": "^4.0.6"
  },
```

app.json 34 
```
... "name": "ShowringHelperReactNative",
  "displayName": "Showring helper",
  "expo": {
    "name": "Showring helper",
    "owner": "anniekvandijk",
    "description": "Showring helper app helps you and your customers to be ready for the showring",
    "slug": "showring-helper",
    "privacy": "unlisted",
    "sdkVersion": "34.0.0",
    "version": "0.10.0",
....
```
app.json 35
```
 ... "name": "ShowringHelperReactNative",
  "displayName": "Showring helper",
  "expo": {
    "name": "Showring helper",
    "owner": "anniekvandijk",
    "description": "Showring helper app helps you and your customers to be ready for the showring",
    "slug": "showring-helper",
    "privacy": "unlisted",
    "sdkVersion": "35.0.0",
    "version": "0.10.0",
...
```

index.js
```
import { AppRegistry } from 'react-native';
import App from './App';
import { name as appName } from './app.json';

AppRegistry.registerComponent(appName, () => App);
```

**Comment by cruzach** [comment] 2019-10-02 15:59
Your SDK version in `app.json` is still set to 34. Besides that, I would take a look at [this page of our docs](https://docs.expo.io/versions/latest/sdk/register-root-component/), since it looks like you're trying to manually set the root component of your app

**Comment by anniekvandijk** [comment] 2019-10-02 16:18
@cruzach no and no 

app.json is set to 35
I do not set root manually. Import from app.json

**Comment by cruzach** [comment] 2019-10-02 16:22
Oh sorry for the confusion, in your original post it showed `"sdkVersion": "34.0.0",` under app.json.
What do you have for the `main` key in `package.json`?

**Comment by anniekvandijk** [comment] 2019-10-02 16:26
No main key. And I do not now what to put in there. Not in any manual for Expo

**Comment by veleda3** [comment] 2019-10-07 20:57
any update on this bug, would like some help, app works fine in dev. when publish it or build a new binary, the app crashes.

sdk35
package.json 
`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "env": "expo-env --env=development",
    "start:env": "expo start expo-env --env=development",
    "env:prod": "expo-env --env=prod",
    "lint": "eslint app -c .eslintrc.json --ext js,jsx",
    "test": "jest --watch --coverage=false --changedSince=origin/master",
    "testDebug": "jest -o --watch --coverage=false",
    "testFinal": "jest",
    "updateSnapshots": "jest -u --coverage=false"
  },`

App.js
`import React from 'react';
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/es/integration/react';
import Sentry from 'sentry-expo';
import AppContainer from './app/index';
import storeFunc from './app/config/store';
import ErrorBoundary from './app/config/sentryConfig/errorBoundary';

let activeStore;
let SentryErrorHandler;
if (!__DEV__) {
  console.log = () => {};
  Sentry.enableInExpoDevelopment = true;
  const storeConfig = {
    sentry: Sentry,
  };
  SentryErrorHandler = ErrorBoundary;
  activeStore = storeFunc(storeConfig).store;
} else {
  console.log('In Development');
  activeStore = storeFunc().store;
  SentryErrorHandler = ({ children }) => children;
}
const { persistor } = storeFunc();

const App = () => (
  <Provider store={activeStore}>
    <SentryErrorHandler>
      <PersistGate loading={null} persistor={persistor}>
        <AppContainer />
      </PersistGate>
    </SentryErrorHandler>
  </Provider>
);

export default App;`

AppEntry.js in node_modules/expo/AppEntry.js

`import { registerRootComponent } from 'expo';
import { activateKeepAwake } from 'expo-keep-awake';

import App from '../../App';

if (__DEV__) {
  activateKeepAwake();
}

registerRootComponent(App);`

**Comment by Saifadin** [comment] 2019-10-08 19:39
I am encountering the same issue. App used to build and run just fine in Expo Snack, but now it just complains, that the App can not be registered. When I run it in minify mode and production and through lan, no errors are thrown. Only when i publish it.

```
Running application "dropfriends" with appParams: {"rootTag":21,"initialProps":{"exp":{"manifest":{"developer":{"projectRoot":"/Users/osamah/Projects/dropfriends","tool":"expo-cli"},"mainModuleName":"node_modules/expo/AppEntry","privacy":"public","assetBundlePatterns":["**/*"],"hostUri":"192.168.0.38:19000","xde":true,"env":{},"appKey":"dropfriends","sdkVersion":"35.0.0","orientation":"portrait","bundleUrl":"http://192.168.0.38:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false","id":"@saifadin/dropfriends","name":"DropFriends","iconUrl":"http://192.168.0.38:19001/assets/./assets/icon.png","description":"","loadedFromCache":false,"version":"1.0.0","hooks":{"postPublish":[{"config":{"organization":"dropfriends","project":"dropfriends","authToken":"35499f499b304f9c91cdba2a9fe441ed7f28d4ce9a254370aedadd5630554eb8"},"file":"sentry-expo/upload-sourcemaps"}]},"platforms":["ios","android","web"],"icon":"./assets/icon.png","logUrl":"http://192.168.0.38:19000/logs","ios":{"supportsTablet":true,"infoPlist":{"NSFaceIDUsageDescription":"We will use FaceID to Login into the App"}},"isVerified":true,"splash":{"resizeMode":"cover","backgroundColor":"#ffffff","image":"./assets/splash.png","imageUrl":"http://192.168.0.38:19001/assets/./assets/splash.png"},"updates":{"fallbackToCacheTimeout":0},"slug":"dropfriends","packagerOpts":{"urlRandomness":"iw-w4y","https":false,"minify":true,"hostType":"lan","dev":false,"lanType":"ip"},"debuggerHost":"192.168.0.38:19001"},"appOwnership":"expo","initialUri":"exp://192.168.0.38:19000","shell":0}}}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
```

**Comment by yarapolana** [comment] 2019-10-10 15:00
I am facing the same issue, this morning everything was fine, then this started happening.

Did not make any updates meaning using the same expo sdk version 33.0.0
Did not change any name so registerRootComponent is still calling the same file App.js
Didn't install any libraries.

Not sure how to go around this with expo managed apps, most solutions I see are for ejected/unmanaged or RN apps.

**Comment by anniekvandijk** [comment] 2019-10-16 12:12
I did update expo-cli to the latest version (3.4.0) did publish a working app. 

After updating expo-cli i did get some errors from react-navigation which I did not get before. After fixing that all seams up and running

**Comment by cruzach** [comment] 2019-10-16 13:49
I've tried to repro this, and haven't been able to so far. Please provide a method for us to reproduce this bug on our end, without that it's tough to say what the cause is. Searching for this error yields quite a few results/solutions so I recommend doing that.

**Comment by thanh90** [comment] 2019-10-22 05:59
I got this problem too when upgrade from SDK 34 to 35. debug mode is ok, but when publish and run on release mode, app just crashed silently with this log
```
Application main has not been registered.
    
    Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
    If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').
    
    This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.
    java.lang.RuntimeException: Expo encountered a fatal error: undefined is not an object (evaluating 't.default.config')
```

**Comment by Julienblc** [comment] 2019-10-31 17:41
Hello all,

I have the same issue.

My package.json : 
`{
	"main": "node_modules/expo/AppEntry.js",
	"scripts": {
		"start": "expo start",
		"android": "expo start --android",
		"ios": "expo start --ios",
		"web": "expo start --web",
		"eject": "expo eject",
		"test": "jest --watchAll"
	},
	"jest": {
		"preset": "jest-expo"
	},
	"dependencies": {
		"@expo/samples": "~3.0.3",
		"@expo/vector-icons": "^10.0.0",
		"@react-navigation/web": "^1.0.0-alpha.9",
		"@types/history": "^4.7.2",
		"@types/react": "^16.8.23",
		"@types/react-dom": "^16.9.0",
		"axios": "^0.19.0",
		"babel-preset-env": "^1.7.0",
		"expo": "^35.0.0",
		"expo-asset": "~7.0.0",
		"expo-constants": "~7.0.0",
		"expo-font": "~7.0.0",
		"expo-web-browser": "~7.0.0",
		"js-base64": "^2.5.1",
		"mobx": "^5.13.0",
		"mobx-react": "^6.1.2",
		"mobx-react-router": "^4.0.7",
		"moment": "^2.24.0",
		"react": "16.8.3",
		"react-dom": "16.8.3",
		"react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
		"react-native-awesome-alerts": "^1.2.0",
		"react-native-calendars": "^1.212.0",
		"react-native-credit-card-input": "^0.4.1",
		"react-native-elements": "^1.2.3",
		"react-native-flash-message": "^0.1.15",
		"react-native-gesture-handler": "~1.3.0",
		"react-native-modal-selector": "^1.1.1",
		"react-native-paper": "^2.16.0",
		"react-native-web": "^0.11.7",
		"react-native-webview": "7.0.5",
		"react-navigation": "^3.11.0",
		"react-navigation-material-bottom-tabs": "^2.1.2",
		"react-router": "^5.0.1",
		"sentry-expo": "~2.0.0",
		"stripe-client": "^1.1.5"
	},
	"devDependencies": {
		"babel-preset-expo": "^7.0.0",
		"jest-expo": "^35.0.0"
	},
	"private": true
}
`

Here my app.json : 
`{
  "expo": {
    "name": "Weedoo It",
    "slug": "weedooapp",
    "privacy": "unlisted",
    "sdkVersion": "35.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "splash": {
      "image": "./assets/splash_screen_wdi.png",
      "resizeMode": "cover"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "packagerOpts": {
      "assetExts": [
        "ttf",
        "otf"
      ]
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "package": "com.weedooit.app"
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
           "blabla" : "blabla"
          }
        }
      ]
    }
  }
}
`

Do you need any informations ?

**Comment by Julienblc** [comment] 2019-10-31 17:44
Hello all,

I have the same issue. When I use my app in local, everything is fine. Then i expo doctor, still fine. Then expo publish, still good. And I flash the QR code of the project -> error.

My package.json :
```
	"main": "node_modules/expo/AppEntry.js",
	"scripts": {
		"start": "expo start",
		"android": "expo start --android",
		"ios": "expo start --ios",
		"web": "expo start --web",
		"eject": "expo eject",
		"test": "jest --watchAll"
	},
	"jest": {
		"preset": "jest-expo"
	},
	"dependencies": {
		"@expo/samples": "~3.0.3",
		"@expo/vector-icons": "^10.0.0",
		"@react-navigation/web": "^1.0.0-alpha.9",
		"@types/history": "^4.7.2",
		"@types/react": "^16.8.23",
		"@types/react-dom": "^16.9.0",
		"axios": "^0.19.0",
		"babel-preset-env": "^1.7.0",
		"expo": "^35.0.0",
		"expo-asset": "~7.0.0",
		"expo-constants": "~7.0.0",
		"expo-font": "~7.0.0",
		"expo-web-browser": "~7.0.0",
		"js-base64": "^2.5.1",
		"mobx": "^5.13.0",
		"mobx-react": "^6.1.2",
		"mobx-react-router": "^4.0.7",
		"moment": "^2.24.0",
		"react": "16.8.3",
		"react-dom": "16.8.3",
		"react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
		"react-native-awesome-alerts": "^1.2.0",
		"react-native-calendars": "^1.212.0",
		"react-native-credit-card-input": "^0.4.1",
		"react-native-elements": "^1.2.3",
		"react-native-flash-message": "^0.1.15",
		"react-native-gesture-handler": "~1.3.0",
		"react-native-modal-selector": "^1.1.1",
		"react-native-paper": "^2.16.0",
		"react-native-web": "^0.11.7",
		"react-native-webview": "7.0.5",
		"react-navigation": "^3.11.0",
		"react-navigation-material-bottom-tabs": "^2.1.2",
		"react-router": "^5.0.1",
		"sentry-expo": "~2.0.0",
		"stripe-client": "^1.1.5"
	},
	"devDependencies": {
		"babel-preset-expo": "^7.0.0",
		"jest-expo": "^35.0.0"
	},
	"private": true
}
```
Here my app.json :
```
  "expo": {
    "name": "Blabla",
    "slug": "blabla",
    "privacy": "unlisted",
    "sdkVersion": "35.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "splash": {
      "image": "./assets/splash_screen_wdi.png",
      "resizeMode": "cover"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "packagerOpts": {
      "assetExts": [
        "ttf",
        "otf"
      ]
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "package": "com.blabla.app"
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
           "blabla" : "blabla"
          }
        }
      ]
    }
  }
}
```
Do you need any informations ?

**Comment by Saifadin** [comment] 2019-10-31 17:44
@Julienblc did you run `expo start --minify --no-dev` locally? It might give you more of an idea, whats wrong.

**Comment by Julienblc** [comment] 2019-10-31 18:00
@Saifadin alright, so : 
- with `expo start` -> everything is fine
- with `expo start --minify --no-dev` -> not working
- with `expo start` -> not working anymore :'(

The problem : 'application main has not been registerd'

**Comment by Julienblc** [comment] 2019-10-31 18:14
Ok, I just found my problem. I used local variables, and there were accessible only in local. And changed the scope, and everything is good now !

**Comment by cruzach** [comment] 2019-10-31 18:27
I'm going to close this issue for now, since most of these reports seem to be due to certain specific configurations, and have posted their fixes here
If you see this issue, go through a few of the causes/solutions here, and check our [forums](https://forums.expo.io/). Barring that, please open up a new issue with a full reproducible demo

**Closed by cruzach** 2019-10-31 18:27 UTC
Labels: bug, needs repro, status: needs more info

**Comment by thanh90** [comment] 2019-11-01 07:11
> Ok, I just found my problem. I used local variables, and there were accessible only in local. And changed the scope, and everything is good now !

What did you mean 'local variables' ? @Julienblc

**Comment by Julienblc** [comment] 2019-11-02 10:00
I have a simple js file not tracked by got, and inside it I have a function that return my env variables, like keys etc..
This file didn't return me the var in the prod situation. When I fixed that, everything was fine after

**Comment by mastahed** [comment] 2019-11-07 05:55
> I have a simple js file not tracked by got, and inside it I have a function that return my env variables, like keys etc..
> This file didn't return me the var in the prod situation. When I fixed that, everything was fine after

How did you fixed it? I have env.js file not tracked by git..

**Comment by Julienblc** [comment] 2019-11-07 08:53
My js file return variables depending on the environment, which is given with argument. Like when I used the `expo start` command, the variables were the good ones. But when I was in prod, I return the wrong one. 
So now I beware that the arguments return to good variables. And if you are not going to push in prod, like me in the beginning, just return the dev variables without checking the command arguments ;)

**Comment by mastahed** [comment] 2019-11-08 00:18
@Julienblc sorry I deleted my comment, i was able to figure it out same thing on what you did.
It so happen that it didn't read the correct environment variables when in prod. :)

`if (__DEV__) {
    return ENV.dev;
  } else {
    // When publishing to production, change this to `ENV.prod` before running an `expo build`
    return ENV.prod;
  }`

**Comment by thanh90** [comment] 2019-11-08 02:27
I finally figured out my problem, in my case I had an error when returning a Sentry instance in prod mode that never happen in debug mode.
