### ISSUE TITLE
[expo 34]Android only: get duplicate push notification when use react-native-firebase with Expokit

### ISSUE THREAD

**Issue by changLiuUNSW** [expo/expo#5304] opened 2019-08-13 03:45 UTC
My app is ejected from expokit 34 and we installed react-native-firebase for push notification and analytics.
Currently we have an issue that for each push notification we get it twice in Android:
![20190813_133844](https://user-images.githubusercontent.com/7379922/62913761-b5a75380-bdd0-11e9-83e3-6ae567baeedb.jpg)
I suspect expokit may have some code for the notification which is duplicated with ```react-native-firebase```.
Is there any solution or workaround for now? This issue has blocked us from release, please help !

**Comment by changLiuUNSW** [comment] 2019-08-13 03:54
I know you guys are focusing on Bare Workflow currently but we cannot use it due to OTA feature. I really hope someone can help us with this issue ...

**Comment by changLiuUNSW** [comment] 2019-08-13 05:00
After research, I think I found out the solution now.
in ```AndroidManifest.xml```, we have to comment out (disable) the GCM-part as below
```
   <!-- GCM -->
    <receiver
      android:name="com.google.android.gms.gcm.GcmReceiver"
      android:exported="true"
      android:permission="com.google.android.c2dm.permission.SEND">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
        <action android:name="com.google.android.c2dm.intent.REGISTRATION"/>

        <category android:name="com.prospa.mobile"/>
      </intent-filter>
    </receiver>

    <service
      android:name=".gcm.ExponentGcmListenerService"
      android:exported="false">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
      </intent-filter>
    </service>
    <service
      android:name=".gcm.ExponentInstanceIDListenerService"
      android:exported="false">
      <intent-filter>
        <action android:name="com.google.android.gms.iid.InstanceID"/>
      </intent-filter>
    </service>
    <service
      android:name=".gcm.GcmRegistrationIntentService"
      android:exported="false">
    </service>
```

**Comment by changLiuUNSW** [comment] 2019-08-13 05:01
Not sure whether we should update document to add this step in.
https://docs.expo.io/versions/v34.0.0/guides/using-fcm/

**Comment by derekstavis** [comment] 2019-08-13 06:48
Hey. I had the same issue. If you are sending the notification using FCM by yourself you can't send title and body. You need to send data-only notifications. Make sure your body includes:

```
"notification": null,
"data": {
  "experienceId",
  "title": "Your title",
  "message": "Your body",
  "body": "{\"your\": \"JSON data\"}",
  "channelId": "default",
},
```

**Comment by derekstavis** [comment] 2019-08-13 06:53
Please close this as a duplicate of #4450.

**Comment by changLiuUNSW** [comment] 2019-08-13 10:49
@derekstavis I do not think it is duplicate. My issue is related to ```GCM``` code above ```AndroidManifest.xml```.
It has been documented in this thread.
https://forums.expo.io/t/solved-android-receive-data-from-a-fcm-push-notification-in-detached-app/12940/3
```
After detaching
in AndroidManifest.xml
comment (disable) the GCM-part
keep the FCM-part untouched
```
In official doc, it miss the first step ```comment (disable) the GCM-part``` which causes duplicate push notification in my app

**Comment by changLiuUNSW** [comment] 2019-08-13 10:52
@derekstavis I can confirm that I can send "notification" body without duplicate notifications. 
BTW, I also comment out FCM section in ```AndroidManifest.xml``` because I use React-native-firebase instead.
```
    <!-- FCM -->
    <service
      android:name=".fcm.ExpoFcmMessagingService">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
      </intent-filter>
    </service>
    <meta-data
      android:name="com.google.firebase.messaging.default_notification_icon"
      android:resource="@drawable/shell_notification_icon" />
    <meta-data
      android:name="com.google.firebase.messaging.default_notification_color"
      android:resource="@color/iconBackground" />
    <service
      android:name=".fcm.FcmRegistrationIntentService"
      android:exported="false">
    </service>
``

**Comment by cruzach** [comment] 2019-08-14 17:28
@changLiuUNSW can you confirm that **without** the changes you are making to the manifest, the change suggested above regarding format for the notifications payload doesn't fix the issue?

**Comment by changLiuUNSW** [comment] 2019-08-14 21:27
@cruzach I do not have a change to test it, because my app is ejected and I do not use Expo to manage the push notification anymore.
Basically as I mentioned above, the root cause is the GCM code is conflict with FCM code. 
For ejected app, if you are using FCM for Push Notifications, you need to  remove  GCM code in the manifest. I just created a PR to add this additional step.
https://github.com/expo/expo/pull/5308
However, I think this issue also exists in standalone app if you are using FCM for Push Notifications

**Comment by cruzach** [comment] 2019-10-15 13:22
Closed via https://github.com/expo/expo/pull/5308

**Closed by cruzach** 2019-10-15 13:22 UTC
Labels: bug
