### ISSUE TITLE
[Android][emulator] Expo Go often crashes on launch on M1 Chips

### ISSUE THREAD

**Issue by Vercjames** [expo/expo#16471] opened 2022-02-28 16:26 UTC
### Summary

Expo 41-44 crashes immediately and judiciously on the Android emulator M1 Chips Macs. I actively teach a React Native Course and worked with several students each with their own environment and none of them could get up and running with using the react native and expo documentation to the letter. I would provide an error log however, the metro bundler doesn't output anything. I simply get an Expo Crash popup on the android Emulator. and YES I had the students use the correct M1 compatible ADV.  

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Run "expo start" on any blank template project 

### Reproducible demo

yarn global add expo-cli
expo init testingblank
cd testingblank
expo start

**Comment by michaloslav** [comment] 2022-02-28 23:49
Similar issue over here. I reinstalled both Expo CLI and Android Studio to make sure there isn't something wrong with my installation.

Steps to reproduce:
1. Get an M1 MacBook
2. Download the Apple Silicon version of Android Studio
3. `yarn global add expo-cli`
4. `expo init test`
5. `cd test && yarn android`

Output:
`Couldn't start project on Android: Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://172.23.218.235:19000 flg=0x10000000 }`

**Comment by sathwik77** [comment] 2022-03-02 03:58
I use expo on M1 Mac pro, Instead of using an emulator I connect an android device and run the project. AVD manager still shows some warnings while installing new devices.

**Comment by michaloslav** [comment] 2022-03-05 12:18
> I use expo on M1 Mac pro, Instead of using an emulator I connect an android device and run the project. AVD manager still shows some warnings while installing new devices.

That's not really ideal for people like me who are iPhone users though, it means I have to bring my old Android phone to the office with me just because Expo doesn't work with the emulator

**Comment by karlhorky** [comment] 2022-04-11 19:23
Wonder if this is related at all to https://github.com/expo/expo-cli/issues/3595 by @brentvatne ...

**Comment by karlhorky** [comment] 2022-04-11 19:35
Seems like there is more discussion and some suggestions over in https://github.com/expo/expo/issues/15199 too

**Comment by karlhorky** [comment] 2022-04-12 08:19
I was also getting these confusing "empty" child process `onexit` error messages mentioned [in expo/expo-cli#3595](https://github.com/expo/expo-cli/issues/3595#issuecomment-981664409):

```
$ yarn start --android
...
Error
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

After trying a bunch of things unsuccessfully, carefully following the Android Studio Emulator guide in the Expo docs worked: https://docs.expo.dev/workflow/android-studio-emulator/

**Comment by douglowder** [comment] 2022-06-24 23:16
I'm not able to reproduce this -- testing on M1 laptop with a recent Android Studio arm64  installation and with Pixel 3a API 32 arm64 emulator.

**Comment by douglowder** [comment] 2022-06-24 23:19
It does seem as this is being tracked in the expo-cli issue above, so closing this as a duplicate.

**Comment by brentvatne** [comment] 2022-06-29 00:45
@michael-gates-techngs - there isn't anything particularly useful in those adb logs. are you seeing this crash in a brand new app? i have no idea about that react-native-expo-examples app and it's quite possible it is just crashing on startup for anyone. try running `expo init` and choosing a blank project then running that

**Comment by michael-gates-techngs** [comment] 2022-06-29 17:10
> @michael-gates-techngs - there isn't anything particularly useful in those adb logs. are you seeing this crash in a brand new app? i have no idea about that react-native-expo-examples app and it's quite possible it is just crashing on startup for anyone. try running `expo init` and choosing a blank project then running that
> 
> also, have you tried creating a new emulator virtual device?

Yeah sadly I also scanned through the logs hoping it'd be something obvious, but alas couldn't find anything. 

I tried creating a new project with `expo init` and upon starting it and sending it to the emulator, the emulator began at a cold boot and successfully opened expo go and bundled the app then opened the app as it should. I closed the app and expo go. Upon the second attempt to send the app to the emulator, it crashed upon opening the expo go app. 

So, I created another new project again with `expo init`. Upon starting it and sending it to the emulator, the emulator was already open, it successfully opened expo go and bundled the app, and then opened the app. I closed the app and expo go. Then I attempted to send the app to the emulator again, this time it crashed upon opening the expo go app (Exact same behavior as last time).

I tried a third time (new project, etc.). Upon sending the app to the emulator, expo crashed instantly. Upon sending it a second time, it bundled and worked.

It seems that it's not consistent in when it crashes, but it's guaranteed to crash a majority of the time.

I have tried creating various other new virtual devices and using different API levels, but they all seem to have the same result.

**Comment by pelakk** [comment] 2022-07-12 17:06
I have the same problem, keeps crashing only on android, ios works completely fine. Anyone have a solution?

**Comment by farzd** [comment] 2022-08-17 05:14
same, just crashes 99% of the time, no logs. M1 mac, android studio - pixel 4a emulator

**Comment by ahmadrafidev** [comment] 2022-08-24 13:48
> > Similar issue over here. I reinstalled both Expo CLI and Android Studio to make sure there isn't something wrong with my installation.
> > Steps to reproduce:
> > 
> > 1. Get an M1 MacBook
> > 2. Download the Apple Silicon version of Android Studio
> > 3. `yarn global add expo-cli`
> > 4. `expo init test`
> > 5. `cd test && yarn android`
> > 
> > Output: `Couldn't start project on Android: Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://172.23.218.235:19000 flg=0x10000000 }`
> 
> Hi, I have the same problem as this. My solution is to lowering my Android Emulator API, in my case is from API 32 to API 29. I just doing this and working as fine, but i do not know if this way will works long or not. Hope it helps!

update around 20 minutes developed. Android keep crashing when reload app, so I run expo start android again and again :)

**Comment by alessandrocapra** [comment] 2022-10-17 07:59
Same issue here, very frustrating and unreliable to use for demoes with stakeholders

**Comment by matyunya** [comment] 2022-11-09 07:20
same here

**Comment by mikealche** [comment] 2022-12-21 22:06
Why is this issue closed? It's a real bug

**Comment by brentvatne** [comment] 2022-12-21 22:48
this is indeed an issue. @Kudo has investigated it and the root cause appears to be related to JSC and Android emulators, perhaps a bug in Android emulators. I would recommend switching to using [development builds](https://docs.expo.dev/development/introduction/) and possibly [Hermes as well](https://docs.expo.dev/guides/using-hermes/), where you will not encounter this issue. Expo Go is a great way to get started and experiment, but development builds are much more flexible and closer to the production environment, so we recommend using them for any real application.

**Comment by PrimeTimeTran** [comment] 2023-04-03 21:54
I feel compelled to add I'm also experiencing this problem on expo SDK 46.

**Comment by pagecow** [comment] 2023-05-02 11:48
Expo Go crashes on my M1 Mac Android Emulator too. A year ago, this was not happening. Now I can't even open the app on Expo Go Android Emulator without it crashing.

Maybe try to revert back to however Expo Go was set up 6 months to a year ago. 

This is a huge deal. I can't test my Expo apps anymore.

**Comment by Kudo** [comment] 2023-05-02 13:32
from the expo sdk 48, we've set the default javascript engine to hermes. that would reduce the crash frequency a little bit on macos m1 + android emulator. if someone using sdk 48 + hermes and having expo go crashes, please let me know. thanks!

**Closed** 2023-05-08 09:13 UTC
Labels: Android, Expo Go, Issue accepted

**Comment by chimiWangchukWangdi** [comment] 2024-07-24 07:35
> Re-opening as I am experiencing a related issue on an M1 Mac. I can start the expo server just fine, and I am able to send the app to Android. However, upon the Expo Go client opening on the Android emulator, it crashes almost immediately approximately 99% of the time. the 1% of the time it doesn't crash, the app will load and then crash. And on the very slight chance the expo go app doesn't crash _and_ the app doesn't crash, it _might_ work or it may be frozen or it may crash after just a few seconds. There's no consistency in the crashing.
> 
> I tried reproducing with [this project](https://github.com/robinhuy/react-native-expo-examples) and the issue persists, so it's not just my own.
> 
> Machine info: macOS Monterey 12.4 on the 16" MacBook Pro M1 Max. Emulator device: Pixel 4 API 29 Expo Go version: 2.24.4 Expo version: 5.4.12
> 
> [Here is all I can see in the ADB logs when the crash happens](https://pastebin.com/raw/Qiz8F3DN). I looked through and see a few warnings/errors but googling around didn't seem to lead me to any solutions.
> 
> Running expo with debug logging yields nothing out of the ordinary.
> 
> ```
> Logs for your project will appear below. Press Ctrl+C to exit.
> Started Metro Bundler
> › Opening on Android...
> /Users/michaelgates/Library/Android/sdk/platform-tools/adb devices -l
> /Users/michaelgates/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu avd name
> /Users/michaelgates/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse tcp:19000 tcp:19000
> /Users/michaelgates/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse tcp:19000 tcp:19000
> /Users/michaelgates/Library/Android/sdk/platform-tools/adb devices -l
> /Users/michaelgates/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu avd name
> /Users/michaelgates/Library/Android/sdk/platform-tools/adb devices -l
> /Users/michaelgates/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu avd name
> › Opening exp://10.2.190.2:19000 on Pixel_4_API_29
> /Users/michaelgates/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm list packages host.exp.exponent
> /Users/michaelgates/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell dumpsys package host.exp.exponent
> /Users/michaelgates/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell monkey -p host.exp.exponent -c android.intent.category.LAUNCHER 1
> /Users/michaelgates/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.VIEW -d exp://10.2.190.2:19000
> › Press ? │ show all commands
> ```

I am facing the same issue, I am using development build and expo 50 but still my app immediately crashes without any error log or any kind of log.

**Comment by chimiWangchukWangdi** [comment] 2024-07-24 07:59
> from the expo sdk 48, we've set the default javascript engine to hermes. that would reduce the crash frequency a little bit on macos m1 + android emulator. if someone using sdk 48 + hermes and having expo go crashes, please let me know. thanks!

Facing the same issue:
 expo 50, development build
