### ISSUE TITLE
reopening app from background leading to getting 'url' event with expo.io address as event.url

### ISSUE THREAD

**Issue by sylenien** [expo/expo#6865] opened 2020-01-27 08:28 UTC
### Environment

its **standalone app** on Android and iOS.
`Expo CLI 3.11.2 environment info:

    System:

      OS: macOS 10.15.1

      Shell: 3.2.57 - /bin/bash

    Binaries:

      Node: 12.3.1 - ~/.nvm/versions/node/v12.3.1/bin/node

      Yarn: 1.17.3 - ~/.nvm/versions/node/v12.3.1/bin/yarn

      npm: 6.9.0 - ~/.nvm/versions/node/v12.3.1/bin/npm

    IDEs:

      Android Studio: 3.4 AI-183.6156.11.34.5522156

      Xcode: 10.3/10G8 - /usr/bin/xcodebuild

    npmPackages:

      expo: ^36.0.2 => 36.0.2 

      react: 16.9.0 => 16.9.0 

      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 

    npmGlobalPackages:

      expo-cli: 3.11.2`

### Steps to Reproduce

1. Build app, add listener:
`
Linking.addEventListener('url', listener)
`

where listener is:
`handleRedirect = (event) => {

    const { path, queryParams } = Linking.parse(event.url)

    const expoLink = path.includes('redirect') ? path : get(queryParams, 'expoLink')

    if (expoLink && expoLink.includes('redirect')) {

      const type = get(queryParams, 'type') || get(Linking.parse(expoLink), 'queryParams.type')

      const [postType, id] = type.split('Z')

      actions.fetchPosts(undefined, true)

      this.findRedirectToArticle(id, postType)

    } else {

      throw new Error(JSON.stringify(Linking.parse(event.url)))

    }

  }`

2. open an app, do something there
3. then open other app(i.e browser)
4. return to the app

### Expected Behavior
application opening and nothing happening.

### Actual Behavior
redirect handler firing with https://expo.io/@USER/APP as **event.url**, then it fails to **else** case

### Reproducible Demo
you can find my while app here on github, last occurance of this bug happened on this branch: https://github.com/sylenien/hsl/tree/fix/titles

if required, I can try to provide a Snack, but its pointless as bug can only be reproduced in standalone app.

_Im sorry for my english, if there anything I can fix or add any info, please say so_

**Comment by cruzach** [comment] 2020-01-27 22:15
Hi @sylenien , I tried reproducing this on a standalone iOS app, but wasn't able to get the Linking event listener to fire (without opening the app via a link to `myscheme://`

Could you provide more details about this? You open the app, send it to the background, and open it again and for some reason the linking event listener fires?

I appreciate you linking your app's source code, but it's much easier to have as minimal amount of code as possible so we can narrow down the root cause - see [here](https://stackoverflow.com/help/minimal-reproducible-example) for why

**Comment by sylenien** [comment] 2020-02-12 11:59
Hello and sorry for the late answer!

I tried to build simple app to reproduce an error but was unable to do so.
Error also has gone somehow after clean reinstall of node_modules and I guess this issue can be closed now?
I know it was strange, but I still have some screenshots of this issue I believe, but cant reproduce it with the same lib versions and code structure.

**Comment by cruzach** [comment] 2020-02-12 13:17
No worries, glad to hear it seems like it resolved itself!

Will close this just to keep things clean, if you see this behavior again then I can re-open once we know how to reproduce it 😃

**Closed by cruzach** 2020-02-12 13:17 UTC
Labels: Linking, bug, needs repro, status: needs more info
