### ISSUE TITLE
[iOS][SDK33]Works on Expo but not on TestFlight

### ISSUE THREAD

**Issue by ru88s** [expo/expo#4507] opened 2019-06-09 01:02 UTC
## 🐛 Bug Report
Works with Expo but not with TestFlight.
Do I only?

https://github.com/expo/expo/issues/4444
I also have this problem.
Is there a relationship?

### Environment

  Expo CLI 2.19.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.19.0

### Steps to Reproduce
![IMG_2959](https://user-images.githubusercontent.com/42270511/59153722-404f9780-8a9c-11e9-8c4f-0be5fd2f942c.PNG)

**Comment by tsapeta** [comment] 2019-06-10 07:07
Hey @ru88s,
In SDK33 we also enabled a feature that removes unimodules from your build that you don't have listed in your dependencies. Could you make sure that you have installed all your `expo-*` dependencies using `expo install` command? In other words, if you import a module like this:
`import { Camera } from 'expo-camera';`
then you must have `expo-camera` in your package.json's dependencies to include this dependency into your build.

**Comment by ru88s** [comment] 2019-06-10 08:29
Thank you for your reply.

I ran exp install.
However, I get an error on TestFlight.

Also, there are modules not used in the project.
I installed it just in case, but the error does not disappear.
Is there a relationship?

![スクリーンショット 2019-06-10 17 17 59](https://user-images.githubusercontent.com/42270511/59182657-3a91a900-8ba5-11e9-8f9b-1200ef3da242.png)
<img width="627" alt="スクリーンショット 2019-06-10 17 19 49" src="https://user-images.githubusercontent.com/42270511/59182658-3b2a3f80-8ba5-11e9-91ed-2a6db6bc6f4e.png">
<img width="216" alt="スクリーンショット 2019-06-10 17 18 14" src="https://user-images.githubusercontent.com/42270511/59182660-3b2a3f80-8ba5-11e9-9e7b-2447eb4d02b9.png">
<img width="215" alt="スクリーンショット 2019-06-10 17 18 05" src="https://user-images.githubusercontent.com/42270511/59182661-3b2a3f80-8ba5-11e9-9386-c9c289623587.png">

**Comment by tsapeta** [comment] 2019-06-10 11:46
Well, these three imports come from your dependencies: `ex-react-native-i18n` and `react-native-expo-image-cache`. You don't have to worry about them as you already added `expo-localization`, `expo-file-system` and `expo-blur` to your dependencies so the problem must be somewhere else. Can you try to narrow down what your app does to see exactly which thing is causing this error?

**Comment by ru88s** [comment] 2019-06-11 03:52
solved.
The cause was somehow Analytics being loaded was not initialized.
There was no problem up to SDK32.
Changed the order of execution during loading.
I do not understand well, but I was able to solve it.
really sorry, and Thank you!

![スクリーンショット 2019-06-11 10 46 36](https://user-images.githubusercontent.com/42270511/59242695-8137df80-8c47-11e9-8d20-9b6f4ae07651.png)

<img width="376" alt="スクリーンショット 2019-06-11 10 46 49" src="https://user-images.githubusercontent.com/42270511/59242709-90b72880-8c47-11e9-9e48-fe6edde5ade0.png">

**Comment by ide** [comment] 2019-06-11 20:02
Closing because the issue at hand was solved, and similar symptoms are likely to have different root causes.

**Closed by ide** 2019-06-11 20:02 UTC
Labels: bug
