### ISSUE TITLE
The useSegments hook is causing an extra re-render when navigating to index pages from nested navigators

### ISSUE THREAD

**Issue by davifelix5** [expo/expo#31192] opened 2024-08-27 12:47 UTC
### Minimal reproducible example

https://github.com/davifelix5/use-segments-bug-mcve

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When setting up an `useSegments` hook on the `_layout.tsx` of a stack of navigators, the `useSegments` hook causes an extra re-render when navigating to an `index` page from a different navigator. The expected behavior would be that of the `usePathname` hook, which triggers an effect depending on its value only one time. The bug occurs on Android and iOS and only if the `layout` with the `useSegments` hook includes nested navigators. In the [reproduction repo](https://github.com/davifelix5/use-segments-bug-mcve), there is detailed information about the bug.

### Environment

env-info:
```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
      npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
      Watchman: 2024.04.29.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/myuser/.rvm/gems/ruby-3.0.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.31 => 51.0.31 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    npmGlobalPackages:
      eas-cli: 11.0.1
    Expo Workflow: managed
```

**Comment by marklawlor** [comment] 2024-09-09 06:59
I'm going to close this as expected behaviour, but we might update this in the future.

For reference, both hooks are practically identical, they just access a different attribute from the same hook. https://github.com/expo/expo/blob/001e69a4ce49d09f4c63fa272f8d1482025ae323/packages/expo-router/src/hooks.ts#L72-L83

The actually issue is your `useEffect` dependency array. `useSegments` does not return a stable array reference (a new array is created every time). You only get one `console.log` for the pathname because a string is a stable reference.

A simple fix is to provide your use effect a stable key such as 

```
  React.useEffect(() => {
    console.log('Segments: ', segments)
  }, [segments.join('/')])
  ```

**Closed by marklawlor** 2024-09-09 06:59 UTC
Labels: needs review, Router
