### ISSUE TITLE
On android video not rotating to landscape while using expo-av

### ISSUE THREAD

**Issue by nitingupta220** [expo/expo#6864] opened 2020-01-27 07:32 UTC
I am using ```expo-av``` to play a video. But I'm experiencing an issue when I tried to fullscreen the video it works perfectly fine on IOS the video rotated to landscape mode and running perfectly fine.
But when I tried the same thing on Android nothing happens at that time. Really a big issue I think. Can anyone help? @cruzach

**Comment by nitingupta220** [comment] 2020-01-27 07:33
If you need the code for the Video component to understand better here it is.
```
<Video
              source={{
                uri: this.state.video
              }}
              rate={1.0}
              volume={1.0}
              isMuted={false}
              resizeMode="cover"
              isLooping
              // shouldPlay
              useNativeControls={true}
              onReadyForDisplay={params => {
                params.naturalSize.orientation = "landscape";
                console.log("params---->", params.naturalSize.orientation);
              }}
              style={{ height: 300, margin: 10 }}
            />
```

I'm even setting the orientation to landscape when video is ready to display but still nothing happen. Please help @cruzach

**Comment by cruzach** [comment] 2020-01-27 15:42
Hi @nitingupta220 , no need to @-mention people in your github issues, we do our best to work through them as fast as we can.

The best way to get your issue handled as quickly as possible is to fill out the entire issue template, be as clear and concise as possible, and provide a snack that reproduces the issue

**Comment by nitingupta220** [comment] 2020-01-27 16:31
Hello, @cruzach thanks for letting me know that you are doing your work well. Also, I think I have explained my concern and issue above clearly. But if you need any more details. Please let me know.

**Comment by cruzach** [comment] 2020-01-27 16:33
The bug report template specifies all the details we need, so if you fill that out you should be good to go

**Comment by nitingupta220** [comment] 2020-01-31 08:15
[Link to Snack](https://snack.expo.io/@nitinchalopadho/thoughtful-bananas)

Hey, I have created a snack for my issue. The problem here is when I tried to do fullscreen and tilted the phone the video changes to landscape mode in Ios but the same thing is not happening on android.

Let me know if you need any more details regarding my issue.

In order to reproduce just run the snack on your phone and add a video by clicking on the button and then press the fullscreen button and tilt your phone to landscape. 

P.S: - It works perfectly fine on IOS but the main issue is on Android.

Please help @cruzach

**Comment by bapjiws** [comment] 2020-02-02 23:18
Having the same issue with Android, works fine on iOS.

**Comment by nitingupta220** [comment] 2020-02-03 08:31
Hey, @bapjiws Thanks for the help. Works with this approach. But I just wonder why we won't be able to do it as mentioned in the document. It works perfectly fine on IOS but having problems with Android.

Btw thanks for the help.

**Comment by bapjiws** [comment] 2020-02-03 09:44
Hey @nitingupta220 , you're very welcome. However, I just had a colleague test this on another version of Android than mine (I'm running 9, he's running 10), and my solution didn't work for him :) So yes, let's hope it's fixed soon, it's a pretty big deal.

**Comment by nitingupta220** [comment] 2020-02-03 10:39
Yes @bapjiws Yes, it's a pretty big deal if we are seeing how Expo is developing very fast. Also, do you know any workflow so that I can use any react-native dependency in the Expo project? Like there is one dependency named `react-native-camera-roll`. I want to use it in my project which is running with Expo but I can't always getting this error `[Unhandled promise rejection: TypeError: null is not an object (evaluating '_nativeInterface.default.getPhotos')]`
Let me know if you know any workaround. Also, I tried linking the dependency by running `react-native link` but still getting the same error.

Let me know if you can help.
Thanks

**Comment by bapjiws** [comment] 2020-02-04 12:13
@nitingupta220 You mean, using native code with Expo? As far as I understand, you'd have to eject from a managed Expo app so you can link such libraries (and essentially be able to use *any* libraries from then on), but I haven't tried it yet, so can't advice. But if it helps, I use [JS.coach](https://js.coach/?collection=React+Native) and [Native Directory](https://www.native.directory/) to find libraries and check if they are available for Expo.
@cruzach Any updates on this issue? Thanks!

**Comment by cruzach** [comment] 2020-02-04 15:32
I updated the Snack because it wasn't clear what to do to replicate the problem- [this new snack](https://snack.expo.io/@charliecruzan/thoughtful-bananas) has just a video component in it. It is rotating the same for me on both iOS and Android, so it's not clear to me what the bug is. If you can provide a clearer explanation of the problem, that would be a big help 🙂

**Comment by nitingupta220** [comment] 2020-02-11 12:06
Hey, @bapjiws I have one question if you can answer it that would be great.
There is an app called firework which is a storytelling app. You can check it on the website for more info: [Firework](https://fireworktv.com/)
In this app what happens is when you rotate the phone the video rotates too.

My question is how can we achieve that functionality. It is pretty cool. If you can help me in this that would be great.

Hey, @cruzach if you know how to achieve this please tell me.

**Comment by techdiary** [comment] 2020-03-30 10:44
@nitingupta220 I hope charile update on snack has your answer to original question, for transforming and scaling video on rotating screen [this](https://docs.expo.io/versions/latest/sdk/screen-orientation/) link should help.
I think this ticket can be closed as its' title was giving me idea that enpo-av do not support android landscape mode.
@cruzach

**Closed** 2020-03-31 17:24 UTC
Labels: AV, bug, status: needs more info

**Comment by joranb** [comment] 2022-10-16 20:10
We are on the latest version now and the problem still persists. Here is an update to @mleister97 fix:

```
  const onFullscreenUpdate = async ({ fullscreenUpdate }: VideoFullscreenUpdateEvent) => {
    if (fullscreenUpdate === VideoFullscreenUpdate.PLAYER_DID_PRESENT) {
      await ScreenOrientation.unlockAsync();
    } else if (fullscreenUpdate === VideoFullscreenUpdate.PLAYER_WILL_DISMISS) {
      await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT);
    }
  };

```

They have moved the enums, this change did the trick for us. Now the video rotates in landscape on Android as expected.

**Comment by yavuzakyazici** [comment] 2024-06-17 08:59
> New working version inspired by @bapjiws (typescript):
> 
> ```js
> import * as ScreenOrientation from 'expo-screen-orientation';
> 
> const videoRef = useRef<any>() // Note: No idea which type i should use here
> 
> const onFullscreenUpdate = async ({fullscreenUpdate}: VideoFullscreenUpdateEvent) => {
>     switch (fullscreenUpdate) {
>         case Video.FULLSCREEN_UPDATE_PLAYER_DID_PRESENT:
>             await ScreenOrientation.unlockAsync() // only on Android required
>             break;
>         case Video.FULLSCREEN_UPDATE_PLAYER_WILL_DISMISS:
>             await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT) // only on Android required
>             break;
>     }
> }
> 
> const showVideoInFullscreen = async () => { await videoRef.current.presentFullscreenPlayer() }
> 
> <Button title="Play video" onPress={showVideoInFullscreen} />
> 
> <Video
>     ref={videoRef}
>     source={{uri: videoSource}}
>     resizeMode={ResizeMode.CONTAIN}
>     useNativeControls={true}
>     onFullscreenUpdate={onFullscreenUpdate}
> />
> ```
> 
> Anyways, I think this is a bug and should be fixed.

This solution suggested above did NOT work at first.
However, after a short session as debugging, I realized it did not work because now in 2024,
Video.FULLSCREEN_UPDATE_PLAYER_DID_PRESENT and
Video.FULLSCREEN_UPDATE_PLAYER_WILL_DISMISS comes as undefined from Video class.
Either these static class methods do not exist or they were replaced with something else.

I traced the fullscreenUpdate event and noticed that it fires twice in the switch statement.
Once it comes as 0 and second time as 1 when video enters full screen mode.
And when the video is taken out of fullscreen mode the event fires and this time ( again twice ) comes as 2 and 3.
So I modified the event as 
```js
const onFullscreenUpdate = async ({ fullscreenUpdate }) => {
    switch (fullscreenUpdate) {
      case 0 || 1:
        // should have been Video.FULLSCREEN_UPDATE_PLAYER_DID_PRESENT
        // but Video.FULLSCREEN_UPDATE_PLAYER_DID_PRESENT comes undefined
        // console.log("Video.FULLSCREEN_UPDATE_PLAYER_DID_PRESENT:");
        await ScreenOrientation.unlockAsync(); // only on Android required
        break;
      case 2 || 3:
        await ScreenOrientation.lockAsync(
          ScreenOrientation.OrientationLock.PORTRAIT
        ); // only on Android required
        break;
    }
  };
```
So now, the working code if you want to be able to rotate video on Android in fullscreen mode, should look like this in regular javascript ( not TypeScript ):
```js
import * as ScreenOrientation from "expo-screen-orientation";

  const onFullscreenUpdate = async ({ fullscreenUpdate }) => {
    switch (fullscreenUpdate) {
      case 0 || 1:
        await ScreenOrientation.unlockAsync(); // only on Android required
        break;
      case 2 || 3:
        await ScreenOrientation.lockAsync(
          ScreenOrientation.OrientationLock.PORTRAIT
        ); // only on Android required
        break;
    }
  };
      <Video
        ref={video}
        source={{
          uri: www.example.com,
        }}
        useNativeControls
        resizeMode={ResizeMode.CONTAIN}
        isLooping
        onFullscreenUpdate={onFullscreenUpdate}
      />
```
On another solution possibility, I had changed app.json..
from 
```js
  "expo": {
    "scheme": "com.jazzaminute",
    "name": "j.a.m",
    "slug": "jam",
    "version": "1.0.0",
    "orientation": "portrait",
```
to ...
```js
    "orientation": "default",
```
this solves the video not rotating problem but and then the whole app rotates to landscape.
This has undesirable results if you are not ready for landscape CSS corrections.
So, I eliminated this option and used the above solution.

**Comment by lsarni** [comment] 2024-08-14 12:56
Instead of `case(0, 1)` it's possible to use `VideoFullscreenUpdate.PLAYER_WILL_PRESENT` and for `case(2, 3)` to use `VideoFullscreenUpdate.PLAYER_WILL_DISMISS`. Coming from `import { VideoFullscreenUpdate } from 'expo-av';`
