### ISSUE TITLE
Facebook mediation bidding

### ISSUE THREAD

**Issue by luisfer901** [expo/expo#13134] opened 2021-06-02 20:03 UTC
### Summary

Audience Network is using bidding only to fill ads in apps. 

Facebook SDK and expo-ads-facebook package need to be updated. It's mandatory to move any apps from waterfall to bidding by the following dates to continue monetizing with Audience Network:

iOS apps: 31 May (extended from 31 March)

Android apps: 30 September

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.4.1 environment info:
    System:
      OS: Windows 10 10.0.17763
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ^41.0.0 => 41.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

More about Facebook audience network switching to bidding [https://www.facebook.com/audiencenetwork/resources/blog/audience-network-to-become-bidding-only-beginning-with-ios-in-2021](url)

**Comment by cruzach** [comment] 2021-06-07 14:32
closing as duplicate of https://github.com/expo/expo/issues/13185

**Closed by cruzach** 2021-06-07 14:32 UTC
Labels: needs review
