### ISSUE TITLE
[Android] Image URL requests do not have session cookies attached after calling Util.reload()

### ISSUE THREAD

**Issue by llamaluvr** [expo/expo#370] opened 2017-07-14 17:46 UTC
Posted this in Slack, recommended that I bring it here:
Sometimes when I’m running an app on Expo in Android, images displayed through a URL in an <Image> tag stop showing up. I run the network traffic through a sniffer, and I notice that all the image requests are failing with a 403 forbidden, because my session cookie isn’t on the request. Further, I see that all the image requests have a user-agent of “Dalvik/2.1.0 (Linux; U; Android 6.0.1; Moto G Play Build/MPIS24.241-2.35-1-13)“, instead of “okhttp” like all other requests. It happens most frequently when I switch between viewing an app served on my computer vs one I published. If I kill all Expo windows, sometimes it fixes itself. Sometimes I have to reboot my phone entirely. When it is working again, all image requests have the “okhttp” user agent. It’s like Expo/ RN flips itself to a different network stack just for image requests sometimes.

----
I've been trying to think of a reliable way to reproduce this and haven't come up with one so far.
It seemed to happen pretty frequently when I was serving the app from my computer via the CRNA scripts (react-native-scripts) but then switching to using a version I published via the exp command line. When I used one and then the other, image network requests that required a cookie per our API would fail. Closing both apps and Expo and restarting would usually fix the issue.

However, by yesterday, I had switched over to fully using the exp command for everything, but it happened once again. This time, only a reboot of the phone would fix things.

I am on Expo 18.0.0.6. My phone apps are up-to-date.

**Comment by dikaiosune** [comment] 2017-08-25 01:00
Hi! Sorry for the delay here. Can you try this again with the SDK 20 version of the client app?

**Comment by llamaluvr** [comment] 2017-08-30 12:56
Hi, apologies on my end- took me a while to find time to upgrade. Anyway, I just tried it on SDK 20 and I still have the issue. I notice it basically every time I switch from serving the app from exp start on my Mac to my Android phone, and then switch to using a deployed link. Then, if I kill Expo and the expo app on the phone and restart it, again using my deployed link, things start working again.

**Comment by unao** [comment] 2017-09-28 19:41
I am experiencing the same or very similar issue. Rebooting phone does not help much - the app consistently stops to show up images after around 12 bigger images + some icons. Then even app internal icons stop to show up :cry:

**Comment by llamaluvr** [comment] 2017-12-12 15:17
I figured out a reliable way to reproduce this. It seems to happen anytime you switch between two JS bundles. I can reproduce it with only a standalone app on the phone. When I publish a new JS bundle, I close the Android app, then reopen. The update checker finds the current bundle, and my callback reloads the experience. When I reload, image requests don't have cookies attached to them anymore.

**Comment by llamaluvr** [comment] 2017-12-19 03:10
Since another issue has me particularly paranoid about differences between versions of Android, I checked and confirmed I could reproduce the issue on Android 6.0 and 7.0 devices.

**Comment by ide** [comment] 2017-12-19 22:36
I suspect that OkHttp (what React Native currently uses for Android networking including image downloads) isn't persisting cookies. In the short term I'd recommend working around this by setting up an intermediate server that looks at a query param instead of a cookie (ex: `https://example.com/image.png?cookie=value`) since React Native's treatment of cookies isn't part of a strict public API.

**Comment by llamaluvr** [comment] 2017-12-20 01:13
@ide Are you sure this is okhttp? Cookies work just fine for image and other fetch requests that go through okhttp usually. It’s only when I call Expo.Util.reload() do image requests stop going though okhttp and the user agent changes to “Davlik”, and then cookies stop working.

**Comment by ide** [comment] 2017-12-20 01:15
I think it's OkHttp (but haven't read the code in awhile) since images are handled by Fresco and there's a Fresco-OkHttp library used by RN.

**Comment by llamaluvr** [comment] 2017-12-20 01:31
Right, I agree that okhttp is the normal user agent for RN image requests, but, if you try my snack, you’ll see that okhttp suddenly isn’t the user agent anymore for image requests after calling Expo.Util.reload(). I suspect that this imposter user agent doesn’t have my cookie because the cookie was set in a response handled by okhttp. 

I’m happy open an issue on the RN side if it’s definitely an RN issue, except I can’t reproduce this issue without using Expo-specific functionality. Is there anything I can do to simulate what Expo.Util.reload() is doing without using an Expo API?

**Comment by ide** [comment] 2017-12-20 03:10
To my knowledge Expo isn't doing much to `<Image>` components so investigating more in RN would be helpful. That is strange that sometimes the requests go through OkHttp and other times they don't. We do make some Expo-specific modifications to the Fresco/OkHttp library used, but I would expect the behavior (of whether the UA contains okhttp) to be consistent. You could simulate Expo's reloading by closing the Android activity for an RN app and then launching it again.

**Comment by llamaluvr** [comment] 2017-12-20 06:32
@ide RE: "closing the Android activity for an RN app and then launching it again"? This is like when you open an app in Expo, swipe it closed in the app switcher, and then open it again from Expo?

Because, actually, that causes the same issue I now see.

I take it I need to write a custom native module to reproduce such a thing outside of Expo. Maybe instead of that, could you point me to the code that actually does the reload? I've traced it as far as:
https://github.com/expo/expo/blob/6aecae5895b88549d26c9c5ac01a03ed05d8c35c/android/expoview/src/main/java/host/exp/exponent/kernel/ExpoViewKernel.java . But that just shows the empty abstract method- surely there's an actual implementation somewhere. If I can point to that code and say, "look at this very normal thing Expo does and the weird behavior it causes in RN images," maybe that's enough info for an RN bug.

**Comment by ide** [comment] 2017-12-20 06:45
I don't know if you'd need to write a native module. You might be able to terminate the app (that would close the activity) and launch it again. The code for reloading is here: https://github.com/expo/expo/blob/cc97d38952925b83e11805b91d33e159b754c558/android/expoview/src/main/java/host/exp/exponent/kernel/Kernel.java#L880. Since you're seeing the same behavior when you manually close your project activity in the Android task switcher, it seems like the bug is not specific to `Util.reload()`.

The RN repo has a lot of issues and the best way to get attention on one is to identify exactly what the problem is in RN and do the debugging and investigation up front. If you find that you can't reproduce the bug with bare RN, it probably makes more sense to investigate it from the Expo side.

**Comment by llamaluvr** [comment] 2017-12-20 16:59
You're right - it's not specific to Util.reload(), but appears to happen anytime Expo launches a new activity. So this covers launching one from the Expo app, or calling Util.reload() from an app hosted in the Expo client or a standalone app.

**I cannot reproduce this by completely killing the app and relaunching it**. Googling around, it appears that the default behavior of an Android app is to run separate activities within the same process. So, killing a process by swiping closed all open activities is different from closing a single activity in an app with multiple activities open. The multiple-activities-in-a-process can be overridden in AndroidManifest.xml. I'm guessing it's not- that would explain why killing the app fixes but killing a single open activity doesn't.

**To be totally clear on what's happening when launching a new activity from the Expo app, here's my reproduction steps:**
1. Setup your HTTP proxy sniffer on your device.
2. Launch Expo client on Android
3. Launch an app from a URL or QR code. This creates a new activity hosting the app. Now there are two Expo activities.
4. In the app activity, a request for an image that isn't already cached goes through the okhttp user agent, includes any HTTP headers, including cookies.
5. Close the app activity (now you're down to one Expo activity).
6. Reopen the **same** app from URL/ QR Code/ Expo's "recent list". Now they're are two Expo activities.
7. In the app activity, a request for an image that isn't already cached goes through the Davlik user agent, doesn't include any custom headers/ cookies.

----

Looking at the code you linked to, while it wouldn't surprise me there's something in base RN that's contributing to this, it seems really difficult to untangle this from Expo-specific code. The manifest URL loading stuff comes into play, the activity runner is custom, the activity class itself is custom, there's even several layers of Expo-specific network stack code. The fact that it has to be same slug that has its activity loaded twice (it can't be just any two slugs) tells me that Expo may behave differently the second time it loads an activity for the same slug after the process is first launched.

My one longshot idea for trying this in base RN was to modify RN's autogenerated code to launch a second activity running off the same JS. I thought MainApplication.java was the entry point and the place where it would be best to try this. I had never looked at this code before and I was hoping to find something that looked like a simplified version of the Expo activity loading code, but it looks nothing like that, and I have no idea how to launch a new activity based on the same JS from there. If you have any suggestions on that, I'm happy to give it a shot. Given that https://github.com/expo/expo/issues/1122 is not likely to be fixed anytime soon, I'm desperate to try just about anything to facilitate a better app upgrade experience for users with Android 6.0 and earlier devices (if reloading worked, even though local JS bundles don't get applied after APK updates, I could at least prompt the user to reload).

**Comment by llamaluvr** [comment] 2018-01-24 16:38
@ide a few updates:
- this is still an issue as of Expo SDK 25 / RN 52
- I ran `adb logcat` during the initial load and again during a reload to see if I could spot any differences. The logs are attached here. The one difference between the two is that a "Fresco has already been initialized!" warning shows up much earlier on reload than it does on the initial load - before any of the `ReactInstanceManager` calls setting up the React context. Could it be possible that the okhttp / fresco stuff is happening too early to be applied to the reloaded activity, and Android/ Fresco is falling back to the default network layer?
[logcat initial load.txt](https://github.com/expo/expo/files/1660625/logcat.initial.load.txt)
[logcat reload.txt](https://github.com/expo/expo/files/1660626/logcat.reload.txt)

Any ideas on reproducing this with vanilla React Native? I'm happy to try stuff, but I really have no idea where to start. I don't doubt that this issue stems from something in vanilla RN, but the reload code seems rather unique to Expo and there's a lot of layers to it- there doesn't seem to be any fairly self-contained code I could place into a vanilla RN project to reproduce.

I'd really like to avoid moving all of our session stuff to the URL because that reduces security against session hijacking attacks. This issue not only prevents cookies from being transmitted, but anything that one would add to an HTTP header (like a JWT in an authorization header). This bug would pose problems for almost any app with user-created image content that's secured behind a login, so I'm surprised it hasn't come up more often. Thanks for your help!

**Comment by km16** [comment] 2018-08-27 08:26
Facing the same issue in a vanilla react-native(0.55.4) project. Cookies are being sent for all the api's, but not for images.

**Comment by devlinb** [comment] 2018-10-29 02:15
This is a huge issue in development, it is impossible to develop with secure APIs if all the headers are going to vanish.

**Comment by ide** [comment] 2018-10-29 23:07
I don't have an update here but for some general advice - historically RN has not made guarantees around cookies and session lifecycles and it is not part of the API and moving your tokens from the Cookie header to a query parameter will probably work much more reliably since query parameters are supported.

**Comment by llamaluvr** [comment] 2018-10-30 04:02
I'd like to perhaps reframe the issue a bit. It's not that big of an issue on it's own that the cookie isn't passed to the image request in this scenario. If RN didn't understand set-cookie headers at all on any requests, I could still pretty easily read the original set-cookie response header, save the cookie to local storage, and attach it to outgoing requests.

The primary issue is that Android Image components don't pass any headers at all after a `Util.reload()`. Even if you set the header manually by passing it as part of the source (e.g., `source={{ uri: '...', headers: [...]}}`). So, whether it's a cookie I'm expecting to go automatically due to set-cookie, or a cookie I store myself, or a JWT, I can't pass it as a header. I know passing it in the URL is theoretically an option, but it isn't always possible or practical. It's weaker on the security front, so some organizations or frameworks may disable it. It's cautioned against in the [RFC for OAuth2 Bearer token usage](https://tools.ietf.org/html/rfc6750#section-2.3). Some JWT's are too long for the URL.

Oh I wish I kept the information on this, but many SDK's ago, I actually noticed the issue *not* happening after a Util.reload() on an ExpoKit development build. In logcat, it seemed like some of the Fresco init messages were at least in a different order. I'll see if I can produce some useful logs next time I'm in there.

I actually haven't paid much attention to this lately because the OTA update experience has improved so dramatically that I've had little need or desire to use `Util.reload()`. We can now set things such that most Android users will get the latest JS bundle on first load of the app regardless of what's inside the APK, and are always one restart away from the latest after that. Great stuff!

**Comment by tsapeta** [comment] 2020-07-11 21:13
A lot of time has passed since this issue was reported, so I'm closing this as we haven't heard similar reports referring to newer SDK versions. Feel free to comment here or open a new issue if you're still facing this in the latest SDK version 🙂

**Closed by tsapeta** 2020-07-11 21:13 UTC
Labels: Android

**Comment by JoseTeque** [comment] 2021-02-20 05:35
Good estimates, I am presenting a similar problem, the images are not displayed, I pass the cookie and they are not seen, you will have a solution in this regard, thank you very much. sorry for my English

**Comment by JoseTeque** [comment] 2021-02-20 05:38
Good estimates, I am presenting a similar problem, the images are not displayed, I pass the cookie and they are not seen, I am using expo sdk 40, do you have a solution in this regard? Thanks a lot. sorry for my English

**Comment by antoniogoulao** [comment] 2021-05-03 17:26
> Good estimates, I am presenting a similar problem, the images are not displayed, I pass the cookie and they are not seen, I am using expo sdk 40, do you have a solution in this regard? Thanks a lot. sorry for my English

Same here with SDK 41

**Comment by Codelica** [comment] 2021-08-11 21:29
Seeing the same behavior developing in with Expo 42 via Expo Go.   At some point image requests that were working fine will fail and the agent moves to "Dalvik/2.1.0".  There is some good info this 4 year old report.  Can it be re-opened or should there be a fresh report ?

**Comment by llamaluvr** [comment] 2022-05-03 01:54
I don't know why I thought of this issue today, but, since a few have commented on it since it was closed, let me add that I tried this again when switching our app to use the full Updates API (loading quickly and downloading any updates in the background), and everything is working great under Expo 44 (i.e., headers keep getting passed after reload and secured images get downloaded)!
