### ISSUE TITLE
`__fbBatchedBridge is undefined` when loading a project with HMR in iOS simulator

### ISSUE THREAD

**Issue by tomaash** [expo/expo#321] opened 2017-06-30 13:22 UTC
Steps to reproduce:

1. Open Expo XDE
2. Create new tab-based project
3. Run on iOS Simulator
(app now works)
4. Enable hot reload
(hot reload now works)
5. Exit simulator
6. Run on iOS Simulator again

Expected result:
Application will run

Actual result:
App crashes with `Unable to execute JS call: _fbBatchedBridge is undefined`
<img width="363" alt="screen shot 2017-06-30 at 15 16 57" src="https://user-images.githubusercontent.com/19360/27737264-cb3044e0-5da7-11e7-8425-3887a8ceee1c.png">

The only way to fix Expo client on simulator is to delete it from home screen and install again. Also, if you disable Hot Reload before quitting simulator, this problem will not appear. So to sum up, it really seems that exiting iOS Simulator with Hot Reload enabled is the sole trigger of this problem.

**Comment by lsps9150414** [comment] 2017-07-11 09:22
Have been facing this issue too.

**Comment by shettyrahul8june** [comment] 2017-07-12 08:22
I am facing this issue too. This occurs when you enable hot reload.

**Comment by schettino** [comment] 2017-07-13 13:47
Same here, and just like shettyrahul8june said, this occurs when you enable Debug JS Remotely.

**Comment by terribleben** [comment] 2017-07-18 23:35
I've identified the cause of this bug but it's really nasty and I don't have an ETA for a fix yet yet.

This is a race condition that occurs when the React Native root view starts trying to enqueue JS methods before the React Native bridge has finished setting up. This doesn't ordinarily happen, but when you enable HMR, the bridge takes a lot longer to set up, so this bug is more likely to occur.

**Comment by terribleben** [comment] 2017-07-19 00:20
Posting this here for reference as well: https://github.com/facebook/react-native/commit/59378f71dbc059bb6d8eb75cf86148012a20ba09

**Comment by javidjamae** [comment] 2017-07-24 21:08
FWIW - I upgrade from Expo XDE 2.19.1 to 2.19.2 today and I haven't had this issue or the connection timeout issue that I was getting constantly. I'm not sure if the problem is resolved or if I've just lucked out and haven't encountered it since I've upgraded, but I'm keeping my fingers crossed! :-)

**Comment by terribleben** [comment] 2017-07-24 22:04
It's not resolved yet sadly. I'll post here when I think I have a fix.

**Comment by terribleben** [comment] 2017-07-25 00:34
Tentative fix is here: https://github.com/expo/expo/commit/b383dc4add1f7112de8b67bbaaa3e96c523507cb

I'm double checking with the original author to make sure I'm not breaking something else. Assuming this is ok, I'll ship this asap.

**Comment by terribleben** [comment] 2017-07-25 17:49
iOS Expo Client v1.18.2 is going out today (simulator and ExpoKit) and later this week (app store). It includes the aforementioned fix for this issue. Let me know if you're still seeing any trouble here.

**Closed by terribleben** 2017-07-25 17:49 UTC

**Comment by williamwlchan** [comment] 2017-08-03 12:01
I updated to the latest version of expo client and did not get this error. However, when I put my debug mode on, the app is popped out to the iphone main screen.
