### ISSUE TITLE
Incompatibility of Expo react-native-web with AWS Amplify & GraphQL/Apollo: module not defined error

### ISSUE THREAD

**Issue by cdcv** [expo/expo#4665] opened 2019-06-19 22:20 UTC
## 🐛 Bug Report
I have an expo app that uses AWS Amplify/GraphQL/Apollo.  These are important technologies for the react native ecosystem, that need to be compatible across platforms.  However, when trying to run the app on web using react-native-web, the errors shown below are produced.

Using these technologies produces a dependency on the npm package immutable-tuple which causes the problem (see issue):
https://github.com/benjamn/immutable-tuple/issues/4
The app works fine on ios/android.

DEPENDENCY:
$ npm ls immutable-tuple
/code/myapp
└─┬ aws-appsync@1.8.0
 └─┬ apollo-cache-inmemory@1.3.10
   └─┬ optimism@0.6.9
     └── immutable-tuple@0.4.10

ERROR:
bundle.js:140912 Uncaught ReferenceError: module is not defined
   at Module.../../../../../../../../../code/myapp/node_modules/immutable-tuple/dist/tuple.mjs (bundle.js:140912)
   at __webpack_require__ (bundle.js:725)
   at fn (bundle.js:102)
   at Object.../../../../../../../../../code/myapp/node_modules/optimism/lib/index.js (bundle.js:174120)
   at __webpack_require__ (bundle.js:725)
   at fn (bundle.js:102)
   at Module.../../../../../../../../../code/myapp/node_modules/apollo-cache-inmemory/lib/optimism.js (bundle.js:47234)
   at __webpack_require__ (bundle.js:725)
   at fn (bundle.js:102)
   at Module.../../../../../../../../../code/myapp/node_modules/apollo-cache-inmemory/lib/readFromStore.js (bundle.js:47426)
   at __webpack_require__ (bundle.js:725)
   at fn (bundle.js:102)
   at Module.../../../../../../../../../code/myapp/node_modules/apollo-cache-inmemory/lib/inMemoryCache.js (bundle.js:46854)
   at __webpack_require__ (bundle.js:725)
   at fn (bundle.js:102)
   at Module.../../../../../../../../../code/myapp/node_modules/apollo-cache-inmemory/lib/index.js (bundle.js:47137)
   at __webpack_require__ (bundle.js:725)
   at fn (bundle.js:102)
   at Object.../../../../../../../../../code/myapp/node_modules/aws-appsync/lib/client.js (bundle.js:65093)
   at __webpack_require__ (bundle.js:725)
   at fn (bundle.js:102)
   at Object.../../../../../../../../../code/myapp/node_modules/aws-appsync/lib/index.js (bundle.js:66186)
   at __webpack_require__ (bundle.js:725)
   at fn (bundle.js:102)
   at Object.../../../../../../../../../code/myapp/node_modules/aws-appsync-react/lib/rehydrated.js (bundle.js:64799)
   at __webpack_require__ (bundle.js:725)
   at fn (bundle.js:102)
   at Object.../../../../../../../../../code/myapp/node_modules/aws-appsync-react/lib/index.js (bundle.js:64670)
   at __webpack_require__ (bundle.js:725)
   at fn (bundle.js:102)
   at Module.../../../../../../../../../code/myapp/App.js (bundle.js:824)
   at __webpack_require__ (bundle.js:725)
   at fn (bundle.js:102)
   at Module.../../../../../../../../../code/myapp/node_modules/expo/AppEntry.js (bundle.js:114414)
   at __webpack_require__ (bundle.js:725)
   at fn (bundle.js:102)
   at Object.0 (bundle.js:281583)
   at __webpack_require__ (bundle.js:725)
   at bundle.js:792
   at bundle.js:795

### Environment

  Expo CLI 2.20.2 environment info:
    System:
      OS: macOS 10.14.1
      Shell: Unknown - /usr/local/bin/fish
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.3 => 5.1.3 
      expo: ^33.0.0 => 33.0.5 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.0.9 => 3.9.1 
    npmGlobalPackages:
      expo-cli: 2.20.2

web produces error (ios, android work ok)

### Steps to Reproduce
Expo app with dependency on package shown, run for web.
Here is example code from the app.js:
import {ApolloProvider} from "react-apollo";
import {Rehydrated} from "aws-appsync-react";

    render(){
        return (
            <ApolloProvider client={appsync}>
                <Rehydrated>
                    {this.state.fontsReady ? <AppContainer /> : <Expo.AppLoading />}
                </Rehydrated>
            </ApolloProvider>
        )
    }

See above.

### Expected Behavior
App compiles correctly/identically across platforms.

### Actual Behavior
App produces error when running for web.

-->

**Comment by ide** [comment] 2019-06-20 02:14
Does .mjs inclusion in https://github.com/expo/expo-cli/pull/731 fix the root cause?

**Comment by cdcv** [comment] 2019-06-20 03:19
> Does .mjs inclusion in [expo/expo-cli#731](https://github.com/expo/expo-cli/pull/731) fix the root cause?
Thanks for your help.
Is there a straightforward way to test / find out?

**Comment by arrygoo** [comment] 2019-07-11 23:13
@ide @cdcv Any workarounds for this one? :( Not having apollo on Expo's WEB is a big blocker for a lot of apps

**Comment by xtraVanilla** [comment] 2019-08-04 20:38
With the same error, I was able to make my app run in the browser by deleting tuple.mjs file.

**Comment by nikolamar** [comment] 2019-08-11 11:12
Hey @xtraVanilla can you share path with us, where you deleted this file?

**Comment by cdcv** [comment] 2019-08-11 11:39
Workaround that seems to fix it: remove the reference to the mjs file in the package.json from the immutableTuple package.  This has produced a working version on both web and mobile.

That said... there is danger for ye who enter here... we ultimately gave up on using it do to other problems.

We ended up removing AWS AppSync/Auth/Dynamo from our app after a *lot* of lost time as this stack was causing the mobile version of the app to have native-code crashes at unreproducible times in complicated ways that were very difficult to debug as the app would just crash to home screen with no error msg, etc.  The only way to troubleshoot it that we found, if you have the same problem, was to try to track what was going on using logcat of the device error logs, but even with that approach we ultimately gave up.  The crash seemed to be due to a complex, load-based interaction of the AWS infrastructure/database with other native functionality (audio in our case).

We ended up switching to Firebase/Firestore JS and had the whole thing up and running in a small fraction of the time that we'd spent trying to use AWS.  Also, the console mgmt is a great deal simpler.

That said, here is the solution we came up with if it's helpful to others...

Here is a script that will overwrite the package.json with a patched version:

cp ./scripts/immutable-tuple-package.tmp node_modules/immutable-tuple/package.json

and here is the patched version (which is the original with one line removed that references the mjs file):

{
  "_args": [
    [
      "immutable-tuple@0.4.10",
      "/Users/cdecharms/code/Brainful/BrainfulAppReactNative"
    ]
  ],
  "_from": "immutable-tuple@0.4.10",
  "_id": "immutable-tuple@0.4.10",
  "_inBundle": false,
  "_integrity": "sha512-45jheDbc3Kr5Cw8EtDD+4woGRUV0utIrJBZT8XH0TPZRfm8tzT0/sLGGzyyCCFqFMG5Pv5Igf3WY/arn6+8V9Q==",
  "_location": "/immutable-tuple",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "immutable-tuple@0.4.10",
    "name": "immutable-tuple",
    "escapedName": "immutable-tuple",
    "rawSpec": "0.4.10",
    "saveSpec": null,
    "fetchSpec": "0.4.10"
  },
  "_requiredBy": [
    "/optimism"
  ],
  "_resolved": "https://registry.npmjs.org/immutable-tuple/-/immutable-tuple-0.4.10.tgz",
  "_spec": "0.4.10",
  "_where": "/Users/cdecharms/code/Brainful/BrainfulAppReactNative",
  "author": {
    "name": "Ben Newman",
    "email": "ben@benjamn.com",
    "url": "https://github.com/benjamn"
  },
  "bugs": {
    "url": "https://github.com/benjamn/immutable-tuple/issues"
  },
  "description": "Immutable finite list objects with constant-time equality testing (===) and no memory leaks",
  "devDependencies": {
    "docco": "^0.8.0",
    "mocha": "^5.0.0",
    "reify": "^0.13.7",
    "rollup": "^0.55.1",
    "rollup-plugin-buble": "^0.18.0",
    "rollup-plugin-uglify": "^3.0.0"
  },
  "homepage": "https://github.com/benjamn/immutable-tuple#readme",
  "keywords": [
    "immutable",
    "tuple",
    "sequence",
    "persistent",
    "data",
    "data structure",
    "functional",
    "intern",
    "interned",
    "internalized",
    "memoization",
    "equality",
    "deep equality",
    "weakmap"
  ],
  "license": "MIT",
  "main": "dist/tuple.js",
  "name": "immutable-tuple",
  "reify": {
    "cache-directory": "test/.cache"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/benjamn/immutable-tuple.git"
  },
  "scripts": {
    "docs": "docco src/*.js",
    "prepublish": "./scripts/build.sh",
    "test": "mocha --require reify --full-trace --reporter spec test/tests.js"
  },
  "version": "0.4.10"
}

**Comment by EvanBacon** [comment] 2019-10-09 00:16
Fixed in https://github.com/expo/expo-cli/pull/1075

**Closed by EvanBacon** 2019-10-09 00:16 UTC
Labels: bug

**Comment by cdcv** [comment] 2019-10-09 00:29
Thank you!!!

**Comment by davidbiller** [comment] 2019-10-29 10:27
How can u use this fix?
