### ISSUE TITLE
Offline support in expo client?

### ISSUE THREAD

**Issue by OliverCole** [expo/expo#1800] opened 2018-05-27 10:51 UTC
### Environment

Environment:
  OS: Linux 4.4
  Node: 8.11.2
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.2
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

### Issue

Despite reading various pages about offline support in Expo that implies this should work, I can't get this to work with my brand new app.

1. create-react-native-app
1. Publish app
1. Sign in to Expo client on iOS
1. Run app
1. Kill expo client
1. Put phone in airplane mode
1. Open expo client
1. Open app from recent:

> There was a problem loading "my-app"

Isn't this supposed to work?

**Comment by terribleben** [comment] 2018-06-13 17:39
Hey there, yeah, this is supposed to work. We had a regression in this workflow. We've [landed a fix](https://github.com/expo/expo/commit/0c5b721f8f2ae0e40f2ccf84caee45d44fbcbcda) but it won't go out until our next minor Expo Client release. The issue won't affect a build you create with `exp build:ios`.

Sorry for the delay in getting back to you here.

**Comment by OliverCole** [comment] 2018-06-13 20:12
Thanks - what's the release cycle for the iOS client? Is there a ticket I should watch?

**Comment by brentvatne** [comment] 2018-06-13 20:16
@OliverCole - it's fixed, was included in our release yesterday :)

**Comment by brentvatne** [comment] 2018-06-13 20:16
oh sorry my bad, I misunderstood what this issue was about

**Comment by terribleben** [comment] 2018-06-13 20:29
To be clear-- the fix was included in our `exp build` builders with the  release yesterday, and with ExpoKit projects. But it's not yet in Expo Client. We're expecting to do a minor Expo Client release in about 1.5 weeks, though it could happen sooner.

**Comment by OliverCole** [comment] 2018-06-26 21:16
How's the release looking?

**Comment by brentvatne** [comment] 2018-11-01 19:28
cc @esamelson

**Comment by brentvatne** [comment] 2018-11-06 21:32
cc @esamelson - I imagine this is working?

**Comment by esamelson** [comment] 2018-11-06 23:08
@OliverCole this is working with the latest Expo client and `expo-cli` (2.3.0 at the time of writing). Note that if you are signed in you need to pass in the additional `--offline` flag to `expo start`. We'll work on removing that.

**Comment by esamelson** [comment] 2018-11-06 23:15
@OliverCole sorry for the slow follow up here. It looks like this is indeed broken for signed in users -- we'll look at fixing it ASAP. In the meantime a workaround is to sign out of expo cli (`expo logout`) before trying to develop offline. You can sign out while offline.

**Comment by esamelson** [comment] 2018-11-09 02:46
`expo-cli@2.3.7` includes fixed offline support by running `expo start --offline`.

**Closed by esamelson** 2018-11-09 02:46 UTC
Labels: project: ios-runtime, status: pending
