### ISSUE TITLE
`protocol: exp` in Expo XDE has garbage after `exp` in URI

### ISSUE THREAD

**Issue by christiangenco** [expo/expo#840] opened 2017-10-23 15:34 UTC
In the past with this project, and currently in other projects, the Expo XDE share URL with `protocol: exp` has given a URI prefixed with `exp://`, but recently it's been prefixed with `exp{RANDOMHEXCHARS}://`, like `exp7b82227d5d4447b0b699308ec1db44f6://h9-x23.christiangenco.APPNAME.exp.direct:80`, which the iOS client can't read from either the QR code or sending the link via sms:

<img width="537" alt="screen shot 2017-10-23 at 10 29 56 am" src="https://user-images.githubusercontent.com/179361/31897962-7c816f32-b7dd-11e7-87db-a5507306c5c2.png">

I can fix this by sending the URI via sms, and then deleting the characters between `exp` and `://` - that altered URI is read by iOS Expo clients just like before.

Why are those random hex characters appearing?

I originally reported this on #828, but after more investigation I agree with @terribleben that these are separate issues.

**Comment by terribleben** [comment] 2017-10-23 17:10
Hi, this is because your app is [detached](https://docs.expo.io/versions/latest/guides/expokit.html). In particular, because detached apps contain custom native code, they can no longer run in Expo Client. Instead you can run the app directly from Xcode or Android Studio. Your detached iOS/Android projects will support the `exp<uuid>` url shown in XDE. See [iOS: Configure, build and run](https://docs.expo.io/versions/latest/guides/expokit.html#3-ios-configure-build-and-run).

Closing because I believe this is intended behavior. Please follow up if you think there's still an issue.

**Closed by terribleben** 2017-10-23 17:10 UTC

**Comment by christiangenco** [comment] 2017-10-24 02:01
Ahh got it - I understand. Thank you! It would've taken me a super long time to figure that out on my own 😜
