### ISSUE TITLE
expo-av Video component does not load

### ISSUE THREAD

**Issue by hhopkins95** [expo/expo#17400] opened 2022-05-08 23:29 UTC
### Summary

Video from expo-av does not load or play as expected. In the example provided, a green view with the listed dimensions is rendered, but no video. The functions onLoad and onLoadStart never fire.

Issue began when SDK was updated to 45

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Package versions

package.json dependencies : 

"dependencies": {
    "@types/react-dom": "~17.0.11",
    "date-fns": "^2.28.0",
    "expo": "~45.0.0",
    "expo-av": "~11.2.3",
    "expo-dev-client": "~0.9.5",
    "expo-notifications": "~0.15.2",
    "expo-status-bar": "~1.3.0",
    "expo-task-manager": "~10.2.1",
    "onesignal-expo-plugin": "^1.0.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.1",
    "react-native-onesignal": "^4.3.9",
    "react-native-web": "0.17.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.66.13",
    "typescript": "~4.3.5"
  },

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.0
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /opt/homebrew/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.5.5 - /opt/homebrew/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.1 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed

### Reproducible demo

import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View, TouchableOpacity, ScrollView } from 'react-native';
import { Video } from 'expo-av';
import { useRef, useState } from 'react';
import { useEffect } from 'react';

export default function App() {

  return (
    <ScrollView >
      <View style={styles.container}>

      <Video
        style={{ height: 100, width: 300, backgroundColor: "green" }}
        source={{
          uri: "https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
        }}
        useNativeControls
        shouldPlay
        isLooping
        onLoadStart={() => console.log('on load start')}
        onLoad={() => console.log('on load')}
        />
     <View style={{flex: 1, padding: 20, flexDirection : 'row'}}>
       <TouchableOpacity onPress={scheduleLocalNotification}>
          <Text> Set Local Notification </Text>
       </TouchableOpacity>
       <TouchableOpacity onPress={() => scheduleAlarmNotification(1,2)}>
          <Text> Set OneSignal Notification </Text>
       </TouchableOpacity>
     </View>
        </View>
    </ScrollView>
  );
}

**Comment by zhiqingchen** [comment] 2022-05-09 02:10
Duplicate with #17395

**Comment by brentvatne** [comment] 2022-05-09 05:04
agreed,

Duplicate of #17395

**Closed by brentvatne** 2022-05-09 05:04 UTC
Labels: needs review

**Comment by hirbod** [comment] 2022-05-09 06:42
I found the cause. Video is not loading via source prop. Looks like a regression from the last PR. Only happens in dev-client though, my testings in Expo Go have been fine.

Loading the Video via `loadAsync` is the workaround for now.
