### ISSUE TITLE
Font.loadAsync throws exception on SDK30/31. App shows a blank screen because further rendering is dependent on a successful response.

### ISSUE THREAD

**Issue by edwardchen** [expo/expo#2909] opened 2018-12-04 19:27 UTC
### Environment
  Expo CLI 2.2.6 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.11.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.4 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1
      react-navigation: ^2.18.2 => 2.18.2

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/eaterpad-83174f29-d483-42f3-a09c-fe8e6f763027.tar.gz

It is an ejected App

### Steps to Reproduce
These are the steps I took that resulted in the bug.
1. Upgraded from SDK28 -> SDK31
2. Eject app
3. Use Font.loadAsync using Font from the Expo library

You might be able to recreate simply by creating a new app running SDK30/31 and calling Font.loadAsync but I haven't tested it.

### Expected Behavior
Font.loadAsync should return without throwing an exception.

### Actual Behavior

caught exception thrown from Font.loadAsync - [Error: File ‘file:///Users/edwardchen/Library/Developer/CoreSimulator/Devices/F7D13047-C94B-41E7-8E2E-80726AEBC433/data/Containers/Bundle/Application/F79874FF-716E-4B45-BF94-5492357A280B/eaterpad.app/asset_7695aeab83089e2ceacc05dfa159a17f.ttf’ for font ‘59825C1F-B24B-4DE1-AA38-7CA2F42CB18D-comfortaa-bold’ doesn’t exist]

My app doesn't render unless Font.loadAsync returns successfully so it displays a blank screen.

I'm not sure if the fact that it was an ejected app is relevant or not, but I had done the SDK upgrade and the ejection together so that is what I'm documenting. I think that it's likely just an issue with SDK30/31. I downgraded to SDK29 on my ejected app and everything seems to be working fine so far. 

I created this post in the expo forum https://forums.expo.io/t/font-loadasync-throws-exception-on-ejected-app/16624 and was asked to create this issue.

**Comment by sjchmiela** [comment] 2018-12-07 15:36
Hm… I just used the following code (both in Expo Client and ejected) and there was no exception raised:
```jsx
import React from 'react'
import { StyleSheet, Text, View } from 'react-native'
import { Font } from 'expo'

export default class App extends React.Component {
  state = {
    fontLoaded: false
  }

  async componentDidMount () {
    await this._loadAssets()
  }
  
  async _loadAssets () {
    await Font.loadAsync({
      'lato-bold-extra': require('./assets/fonts/Lato-Black.ttf'),
      'lato-bold': require('./assets/fonts/Lato-Bold.ttf'),
      'lato-bold-italic': require('./assets/fonts/Lato-BoldItalic.ttf'),
      'roboto': require('./assets/fonts/Roboto-Regular.ttf'),
    })
    console.log('fonts loaded!')
    this.setState({fontLoaded: true})
  }

  render () {
    let text = null
    if (this.state.fontLoaded) {
      text = <View>
        <Text adjustsFontSizeToFit numberOfLines={1} style={{width: 40, height: 200, backgroundColor: "red", fontFamily: 'lato-bold-extra'}}>
          Hello, SDK31!
        </Text>
        <Text adjustsFontSizeToFit style={{fontSize: 24, fontFamily: 'lato-bold'}}>
          Hello, SDK31!
        </Text>
        <Text adjustsFontSizeToFit style={{fontSize: 24, fontFamily: 'lato-bold-italic'}}>
          Hello, SDK31!
        </Text>
        <Text adjustsFontSizeToFit numberOfLines={1} style={{fontSize: 24, fontFamily: 'roboto'}}>
          Hello, SDK31!
        </Text>
      </View>
    }
    return (
      <View style={styles.container}>
        {text}
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center'
  },
})
```

How are you calling your `Font.loadAsync`? 🙂

**Comment by edwardchen** [comment] 2018-12-07 16:08
Yeah...after I wrote up this issue have upgraded to SDK31, deleted ios/android directories then re-ejected and everything appears to be fine now.

I think maybe the problem was some dependency issue from upgrading an already ejected project improperly. I'm new to upgrading/ejecting so I think I must have missed something there. I'm not sure what though...

**Comment by edwardchen** [comment] 2018-12-07 16:09
Might be worth closing this issue since I am unable to reproduce but I think it's possible other people might run into the same problem.

**Comment by sjchmiela** [comment] 2018-12-07 16:12
Ok, I'll close this issue then, thanks for responding! 🙂

**Closed** 2018-12-09 06:51 UTC

**Comment by edwardchen** [comment] 2018-12-12 22:04
I think the issue only appeared in development. And it appears that setting production mode to false fixes the issue. I think the hashed asset file only exists in my production build so using production mode with a debug build fails. 

Sorry for the confusion! I'm still trying to understand how everything in expo is working but I think this is the answer.

**Comment by mtford90** [comment] 2019-01-22 14:48
@edwardchen I just spent an hour trying to figure out what on earth was going on and i'd done the same as you. Looks like I accidentally pressed "p" at some point and placed everything in production mode. Eurgh.

**Comment by jirwong** [comment] 2019-03-31 07:07
Oh man @mtford90 @edwardchen thanks for that info about this issue only appearing in development with production mode on.

I legit lost my mind for the past few hours trying to figure out what's going on. Out of coincidence I actually added a new font in my assets, and instantly assumed that was the cause.

Panicked, & did everything from changing gradle versions, to upgrading/downgrading different sdk versions (to no avail) and it turned out to be as simple as pressing "p".

That wasn't... very fun.

**Comment by ilyausorov** [comment] 2019-05-28 17:02
Wanted to quickly add that for anyone running an ejected project via the CLI, you have to make sure that you are running your local expo bundle with the --dev flag (e.g. expo start --dev).

It is kind of annoying though that after having your assets optimized, you can no longer run your local bundle with the --no-dev and --minify flags.

**Comment by adamsythe** [comment] 2019-06-19 12:37
Hi there are several issues with using --dev mode, is there any way to fix this without using dev mode?
