### ISSUE TITLE
Android AppLoading is blank

### ISSUE THREAD

**Issue by joshwils82** [expo/expo#409] opened 2017-07-24 16:31 UTC
I am seeing a blank (all white) AppLoading screen after upgrading to 18.0.0.  I have AppLoading as the root component.  This appears to be an Android only issue as it is still working on iOS.

**Comment by jesseruder** [comment] 2017-07-25 21:21
Can you upload your code or reproduce on snack?

**Comment by joshwils82** [comment] 2017-07-26 01:37
Sure, here is some code you can put into snack that will show the issue.  Notice how after the "Waiting for code.." message, the screen is blank for 5 seconds while it is showing the AppLoading component.
`import React, { Component } from 'react';
import { Text, View, StyleSheet } from 'react-native';
import { Constants, AppLoading } from 'expo';

export default class App extends Component {
  
  constructor() {
    super();
    this.state = { pending: true};
  }
  
  componentWillMount() {
    setTimeout(() => {
      this.setState({pending: false});
    }, 5000);
  }
  
  render() {

      if (this.state.pending) {
        return (<AppLoading/>);
      }

    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>
          Change code in the editor and watch it change on your phone!
          Save to get a shareable url. You get a new url each time you save.
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#34495e',
  },
});
`

**Comment by benhannel** [comment] 2017-08-21 15:20
I'm having the same issue on SDK 19

**Comment by jbakerdev** [comment] 2017-09-11 15:49
+1 SDK 19

**Comment by wenbolovesnz** [comment] 2017-09-15 07:56
+1 SDK 20

**Comment by mamal72** [comment] 2017-09-28 05:43
Had the same problem with `20.0.0`. Just updated to `21.0.0` and it's fixed! 🎉🎈 
Thank you! 👍🙏

**Comment by dikaiosune** [comment] 2017-10-11 20:31
Hi! I think without specifying a loading/splash config in `app.json` I think it's supposed to default to a blank screen. If we've specified differently elsewhere, please post back and I'll reopen. Thanks!

Side note: I observed the same behavior on iOS and Android in the latest release.

**Comment by outaTiME** [comment] 2017-10-13 00:10
Same here, in iOS works as expected and in android white screen ...

I leave a comparison side by side:
https://cl.ly/0K382g2W103V/Screen%20Recording%202017-10-12%20at%2009.05%20PM.gif

Im running 21 SDK with last cli on both devices also here I leave the `app.json`:

```json
{
  "expo": {
    "name": "foo",
    "description": "An empty new project",
    "slug": "foo",
    "privacy": "unlisted",
    "sdkVersion": "21.0.0",
    "version": "1.0.0",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app-icon.png",
    "loading": {
      "icon": "./assets/icons/loading-icon.png"
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    }
  }
}
```

thanks !!!

**Comment by kadoshms** [comment] 2017-10-21 11:44
Looking at the source code of `AppLoading.android.js` in `19.0.0`:

**Comment by 3axap4eHko** [comment] 2017-11-27 19:20
+1 SDK 23

**Comment by sermagnus** [comment] 2017-12-01 16:36
+1 width SDK 23

**Comment by 3axap4eHko** [comment] 2017-12-05 21:03
I found solution with following config. It will show splash on standalone application (not in development)
``` json
"expo": {
  ...
  "splash": {
     "backgroundColor": "#424242",
     "image": "./images/icon_512.png"
  }
  ...
}
```

**Comment by nikki93** [comment] 2017-12-05 21:16
@outaTiME's issue is this other one https://github.com/expo/expo/issues/1068 -- that issue tracks the similar issue for development mode live reloading, please discuss it there.

The issue on this page should be addressed in the minor update https://blog.expo.io/expo-for-android-sdk23-minor-update-daf5847ae0a7 and has worked for at least one user https://forums.expo.io/t/sdk-23-only-white-screen-on-android/4944/9 -- let us know if you still face it.

**Comment by arrygoo** [comment] 2017-12-13 22:35
@nikki93 I'm having this issue with a detached app (just updated from expo22 to 23). How can I fix it?

**Comment by gfleetwood** [comment] 2017-12-25 13:32
Having this issue with the latest expo. Worked well for most of yesterday and then started with this problem out of the blue.

**Comment by kadoshms** [comment] 2017-12-31 17:54
I am not sure weather this issue is fixed or not.
Anyway, doesnt seem like it does in both sdk 23 and 24

**Comment by MaybeRex** [comment] 2018-01-01 01:10
Same issue on sdk 24

**Comment by kadoshms** [comment] 2018-01-01 07:30
Now I can confirm that this is not fixed in 23 nor 24.

Could someone please reopen?

**Comment by mauroporrasp** [comment] 2018-01-01 15:38
Same issue on Android.

**Comment by MedinaGitHub** [comment] 2018-01-04 02:23
Same issue on Android.

**Comment by arrygoo** [comment] 2018-01-04 03:47
@kadoshms @MaybeRex @mauroporrasp @MedinaGitHub 
Try adding a png to the following:
```
mobile/android/app/src/main/res/drawable-hdpi/shell_launch_background_image.png  mobile/android/app/src/main/res/drawable-ldpi/shell_launch_background_image.png  mobile/android/app/src/main/res/drawable-mdpi/shell_launch_background_image.png  mobile/android/app/src/main/res/drawable-xhdpi/shell_launch_background_image.png  mobile/android/app/src/main/res/drawable-xxhdpi/shell_launch_background_image.png  mobile/android/app/src/main/res/drawable-xxxhdpi/shell_launch_background_image.png
```

**Comment by brentvatne** [comment] 2018-01-04 22:55
for people who have this issue -- are you using create-react-native-app? does this happen in development only or also when you publish?

**Comment by mauroporrasp** [comment] 2018-01-05 05:05
@brentvatne for me, it happened after I detached with Expo. Thanks.

**Comment by kadoshms** [comment] 2018-01-05 07:17
@brenvatne 1.yes 2. only in standaolne

**Comment by MedinaGitHub** [comment] 2018-01-09 12:24
when I exported an APK it still happens to me

**Comment by YKSing** [comment] 2018-01-16 09:43
@arrygoo I tried and it still not work

@brentvatne 
1. Yes and detached Expo
2. Both

**Comment by wrsx** [comment] 2018-01-28 17:16
I was having this issue when configuring splash options under the Android key. Moving it out seems to fix the issue

**Comment by ChristianTucker** [comment] 2018-02-02 12:48
I created a new application today with create-react-native-app and detached to expo kit. I then copied my assets/source folders over and made sure the app.json was configured properly.

White screen on development and production builds.

**Comment by sermagnus** [comment] 2018-02-02 17:20
I think I've solved the problem for my App.

This is my experience:
  - Expo =< v23: in app.json the "loading" settings has never worked
  - Expo >= 24: the problem is related to wrong settings "app.json" (or missing use of "splash" section)
    In addition, using <Expo.AppLoading /> and the preloading of assets, i have encountered issues with too many images of heavy assets that cause a delay of app startup.



This is my app.json
`{
  "expo": {
    "version": "1.0.8",
    "sdkVersion": "25.0.0",
    "name": "***",
    "slug": "***",
    "privacy": "unlisted",
    "orientation": "portrait",
    "primaryColor": "#3E7535",
    "icon": "./assets/icons/app-icon.png",
    "notification": {
      "icon": "./assets/icons/android-notification-grayscale.png",
      "color": "#08005D"
    },
    "loading": {
      "icon": "./assets/icons/app-loading.png",
      "backgroundColor": "#ffffff",
      "hideExponentText": false
    },
    "splash": {
      "image": "./assets/images/startup-splash.png",
      "backgroundColor": "#ffffff",
      "resizeMode": "cover"
    },
    "packagerOpts": {
      "assetExts": ["ttf"]
    },
    "android": {
      "versionCode": 5,
      "package": "***",
      "config": {
        "googleMaps": {
          "apiKey": "***"
        }
      }
    },
    "ios": {
      "buildNumber": "5",
      "loadJSInBackgroundExperimental": true,
      "bundleIdentifier": "***",
      "icon": "./assets/icons/app-icon_ios.png",
      "supportsTablet": false,
      "config": {
        "usesNonExemptEncryption": false,
        "googleMapsApiKey": "***"
      },
      "infoPlist": {
        "CFBundleLocalizations": [
          "en",
          "it"
        ]
      }
    },
    "assetBundlePatterns": [
      "./assets/images/**",
      "./assets/fonts/**",
      "node_modules/react-navigation/src/**/*.png",
      "node_modules/@expo/vector-icons/fonts/*.ttf"
    ]
  }
}`

**Comment by falloutcoder** [comment] 2018-02-03 12:56
Expo == 23
Used CRNA and detached to expo.
Works fine on IOS but on android white screen. White screen on android occurs on development and published version both.

**Comment by ide** [comment] 2018-02-05 19:36
Hi all - we've created an internal issue to investigate this issue. We don't have an ETA and are currently focused on other issues for SDK 26 but do have this tracked internally.

**Comment by EsdrasEtrenne** [comment] 2018-02-18 06:47
+1 

my app is not detached. It is just a standalone app and the android version also has only a white screen


```
{
  "expo":{
    "name": "xxxx",
    "description": "Messenger",
    "slug": "xxxx",
    "privacy": "public",
    "sdkVersion": "23.0.0",
    "version": "1.5.3",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/icon_android.png",
    "notification":{
      "icon": "./assets/icons/notification.png"
    },
    "splash": {
      "backgroundColor": "#4988dd",
      "resizeMode": "cover",
      "image": "./assets/images/lynxBackground.png",
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "xxxxx",
      "buildNumber": "xxx",
      "icon": "./assets/icons/icon_lynx.png",
      "loadJSInBackgroundExperimental": true,
      "usesIcloudStorage": true
    },
    "android": {
      "package": "xxxxx",
      "config": {
        "googleMaps": {
          "apiKey": "xxxxxxxxxxxxxxxxxxx"
        },
      },
      "splash": {
        "ldpi": "./assets/images/lynxBackground.png",
        "mdpi": "./assets/images/lynxBackground.png",
        "hdpi": "./assets/images/lynxBackground.png",
        "xhdpi": "./assets/images/lynxBackground.png",
        "xxhdpi": "./assets/images/lynxBackground.png",
        "xxxhdpi": "./assets/images/lynxBackground.png",
        "resizeMode": "cover",
        "backgroundColor": "#4988dd",
      },
      "versionCode": 7
    }
  }
}

```

**Comment by machester4** [comment] 2018-02-21 23:07
the problem is that the image file does not exist, what you can do is use the icon of the app, editing the file `splash_background.xml` replacing the line 
`<item><bitmap android:gravity="center" android:src="@drawable/shell_launch_background_image"/> </item>`
 for 
` <item><bitmap android:gravity="center" android:src="@drawable/ic_launcher" /></item>`
verify that the ic_launcher image exists in the directories **drawable-hdpi** **drawable-mdpi** **drawable-xhdpi** **drawable-xxhdpi** **drawable-xxxhdpi** if it does not exist you can obtain the **mipmap** folders. **FOR ONLY DETACHED PROJECTS**

**Comment by alanlanglois** [comment] 2018-03-04 21:34
Same issue, using expo 25 and detached app.

**Comment by alanlanglois** [comment] 2018-03-05 23:12
Got it working,
Added a png file named "shell_launch_background_image.png" all the drawable-xxxx folders.
I had an error when building saying "duplicate files in dev19", I removed the file and build again. 
It did the trick.
![image](https://user-images.githubusercontent.com/712986/37004989-99bce136-20d2-11e8-9861-c5f0fbd96c5e.png)

Also make sure you have a splash_background.xml file in your res/drawable folder.
```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">

    <item android:drawable="@color/splashBackground"/>

    <item><bitmap android:gravity="center" android:src="@drawable/shell_launch_background_image" /></item>

</layer-list>```

**Comment by aalices** [comment] 2018-03-21 11:59
@alanlanglois @machester4  it shouldn't be a problem if you specify all the dpis in your `app.json` did you do that?
@EsdrasEtrenne there might have been an issue... can you try upgrading to SDK 24 ?

**Comment by terrysahaidak** [comment] 2018-03-22 22:35
Hello @aalices, I've faced the same issue with the non-detached app. Splash screen works fine for me, but AppLoading doesn't. It shows the blank screen.

And the actual problem – just a single line `export default () => null;` in `AppLoadingNativeWrapper.android.js` file. So it shows a navigator card background and blinks because it doesn't show a `NativeAppLoading` like iOS does.

So, the fix will be at least an ability to render just something instead of just a null. Or implementing a real `NativeAppLoading` which will be much better.

**Comment by davidbuckleyni** [comment] 2018-03-22 23:41
I have the same problem I added entity framework into a shared libary and created a context but when I launch the master detail app I get a blank white screen I am on api level 27

**Comment by eeeman1** [comment] 2018-04-23 10:48
I confirm, the problem persists, what are the solutions?
"expo": "^25.0.0"
"sdkVersion": "25.0.0"

**Comment by davidbuckleyni** [comment] 2018-04-23 11:09
last .4 release appears to be working fine

**Comment by eeeman1** [comment] 2018-04-23 11:11
version of what?

**Comment by aalices** [comment] 2018-05-10 11:59
Anyone still having the issue on a detached or standalone app? I can confirm there's a white flash inside Expo client that is going to be fixed and want to know if someone's still having issues.

**Comment by eeeman1** [comment] 2018-05-10 12:01
the problem is relevant, because of this I refused to use AppLoading and made my logic

**Comment by bakaa99** [comment] 2018-05-11 11:37
"sdkVersion": "26.0.0",
working perfectly for ios

but for android:
after the splash screen in android
using apploading to check for permissions in construtor

the interval between it starts to check for permissions and the time the isReady(to render apploading or not) is set to true ,
i'm getting the white screen

**Comment by mnemotiv** [comment] 2018-06-15 08:40
sdk 28, same issue on Android

**Comment by aalices** [comment] 2018-06-18 07:08
Anyone reporting the issue, please include your `app.json` configuration, point out where the issue occurs (Expo client / standalone / detached). This would help us a lot!

**Comment by davidbuckleyni** [comment] 2018-06-18 07:11
We attached the xamrian logs if their not sufficent why not it should be !!!

**Comment by anp** [comment] 2018-06-18 21:39
@davidbuckleyni I'm not seeing any Xamarin logs attached to your messages. Also, I'm not sure how Xamarin logs would help as Expo is built on top of React Native, not Xamarin.

**Comment by terrysahaidak** [comment] 2018-06-19 10:18
Anyone reporting the issue, I've just tried to reproduce. Everything works as expected with SDK 28 (and even 27 in my production app). The issue doesn't reproduce using builded app, but does reproduce in Expo.

Here is the video: https://photos.app.goo.gl/3CABxs5mmj7fFTC16

And here is the code:

```
import React from 'react';
import { Image, Text, View, StyleSheet } from 'react-native';
import { Asset, AppLoading } from 'expo';

const delay = (shouldReject, timeout = 2000) =>
  new Promise((res, rej) =>
    setTimeout(shouldReject ? rej : res, timeout));

export default class App extends React.Component {
  state = {
    isReady: false,
  };

  render() {
    if (!this.state.isReady) {
      return (
        <AppLoading
          startAsync={this.asyncJob}
          onFinish={() => this.setState({ isReady: true })}
          onError={console.warn}
        />
      );
    }

    return (
      <View style={styles.container}>
        <Text>Hello world</Text>
      </View>
    );
  }

  asyncJob() {
    return Promise.all([
      delay(),
      delay(true, 1000), // even with rejecting
      // everything else
    ]);
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by Pavel-Mishin** [comment] 2018-06-25 06:59
@terrysahaidak Could you attach your app.json, please?

**Comment by FakhruddinAbdi** [comment] 2018-06-29 06:04
Same issue on sdk version 28

app.json

    {
          "expo": {
            "name": "App name",
            "description": "Some descrption",
            "slug": "App slug",
            "privacy": "public",
            "sdkVersion": "28.0.0",
            "version": "1.0.4",
            "orientation": "portrait",
            "primaryColor": "#5a227e",
            "icon": "./assets/icons/app-icon.png",
            "notification": {
              "icon": "./assets/icons/notification-icon.png",
              "color": "#000000"
            },
            "splash": {
              "image": "./assets/splash-screen.png",
              "backgroundColor": "#5a227e",
              "resizeMode": "cover"
            },
            "packagerOpts": {
              "assetExts": ["ttf"]
            },
            "ios": {
              "bundleIdentifier": "com.package.app",
              "supportsTablet": true
            },
            "android": {
              "versionCode": 7,
              "package": "com.package.app",
              "icon": "./assets/icons/app-icon-android.png",
              "config": {
                "fabric": {
                  "apiKey": "[API KEY HERE]",
                  "buildSecret": "[BUILD SECRET]"
                }
              }
            },
            "androidStatusBar": {
              "backgroundColor": "#34323"
            },
            "hooks": {
              "postPublish": [
                {
                  "file": "sentry-expo/upload-sourcemaps",
                  "config": {
                    "organization": "orginizatino",
                    "project": "App",
                    "authToken": "[AUTH TOKEN]"
                  }
                }
              ]
            }
          },
        }

works fine with ios.

In android -> standalone app when i lunch the app, i see a blank white screen with spinner for some seconds then the splash screen appear and the rest goes fine.

**Comment by Pavel-Mishin** [comment] 2018-06-29 06:31
I'm not sure but it seems like the problem is caused by "./" in splash image path. If you'll see to the expo console, there will be paths like `"xxhdpiUrl": "http://localhost:19001/assets/./assets/icons/icon.png"` if in app.json 
`"xxhdpi": "./assets/icons/icon.png"`, so try to replace it with `"xxhdpi": "assets/icons/icon.png"`. Also it may required to write splash config in android section, for each resolution.
It seems worked for me, but unfortunately i can't check it right now.

**Comment by FakhruddinAbdi** [comment] 2018-07-07 14:16
I have change my app.json icon path to yours, But it didn't works . same as before @Pavel-Mishin

**Comment by nuyulcore** [comment] 2018-07-12 23:22
I got same problem

**Comment by rmushtaq21** [comment] 2018-07-17 19:31
I'm experiencing the same issue:

`{
 "expo": {
  "name": "App Name",
  "version": "0.1.0",
  "slug": "App Slug",
  "sdkVersion": "28.0.0",
  "privacy": "unlisted",
  "ios": {
    "bundleIdentifier": "xxx"
  },
  "android": {
    "package": "xxx"
  }}
}`

**Comment by FakhruddinAbdi** [comment] 2018-07-18 05:50
Same issue `sdkVersion": "28.0.0"`
I just decided to detach and go ahead with native codes :(
Despite the simplicities expo brought to react native development, But it has some deal breakers which forced me to detach.
The next step after detach would be removing expo sdk completely to reduce app size.

**Comment by esamelson** [comment] 2018-07-18 19:22
Hi all -- really sorry this has been a pain point. Unfortunately it's very hard for us to provide any sort of help on an issue like this that has been open for almost a year. Lots of things have changed since this issue was opened, and it's nearly impossible to pinpoint anyone's problem without more context.

For all those who are still having an issue resembling this one, please first make sure you have followed @aalices 's suggestion from earlier in the thread, setting the `android.splash` images for every DPI in app.json (see https://docs.expo.io/versions/latest/guides/configuration.html#android at the very bottom of the page).

If that still doesn't help, please open a new issue and fill out the template there as completely as you can -- the more information you give, the more likely we'll be able to help.

Thanks!

**Closed by esamelson** 2018-07-18 19:22 UTC
Labels: project: android-runtime, project: sdk, status: needs more info

**Comment by Symyon** [comment] 2019-04-17 16:27
Looks like Expo AppLoading on Android is looking for the file with a specific name: "shell_launch_background_image.png" in Android drawable folders,  even if you specify another one in app.json (I had "./assets/splash.png" in my app.json). 

**So by placing "shell_launch_background_image.png" in xxxhdpi folder should be enough, file name is what matter here.**

 But you can do that for all the other density folders as well if you like to provide a better quality. Also this is only for the AppLoading splash screen. For the the native splash screen you have to make the xml file.

My projectL: sdkVersion: 32 / detached (ExpoKit)
