### ISSUE TITLE
Custom TabTrigger is broken even when identical to expo code

### ISSUE THREAD

**Issue by affectful** [expo/expo#33752] opened 2024-12-19 05:54 UTC
### Minimal reproducible example

https://github.com/affectful/expo-repros

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Creating custom TabTrigger with nearly identical code to expo-router causes error `Couldn't find any screens for the navigator. Have you defined any screens as its children?`. In the (tabs) folder of the example

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v22.11.0/bin/yarn
      npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.19 => 52.0.19 
      expo-router: ~4.0.13 => 4.0.13 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: managed
```

**Comment by marklawlor** [comment] 2024-12-19 13:00
Hi, the code used in the example repro is using `<Tabs />` via a method we did not intend.

The intended usage is

```
import { TabList, TabSlot, Tabs, TabTrigger } from "expo-router/ui";

import React from "react";
import { Pressable, PressableProps, Text } from "react-native";

export function MyCustomButton(props: PressableProps) {
  return <Pressable {...props}>{props.children}</Pressable>;
}

export default function TabLayout() {
  return (
    <Tabs>
      <TabSlot />
      <TabList>
        <TabTrigger name="explore" href="/explore" asChild>
          <MyCustomButton>
            <Text>Explore</Text>
          </MyCustomButton>
        </TabTrigger>
      </TabList>
    </Tabs>
  );
}
```

I'm going to close this issue, as this is expected behaviour, but can you please respond either on this issue or via the "Share your feedback" link at the bottom of https://docs.expo.dev/router/advanced/custom-tabs/ to help us understand how we can improve these docs.

**Closed by marklawlor** 2024-12-19 13:00 UTC
Labels: needs review, Router

**Comment by affectful** [comment] 2024-12-19 16:35
Hey @marklawlor, I don't understand why it's not an intended usage to use the hook version. It's documented here: https://docs.expo.dev/router/advanced/custom-tabs/#hooks

**Comment by marklawlor** [comment] 2024-12-19 19:04
`<TabTrigger />` has two use cases. It can be used in `<TabList />` as configuration for the `<Tabs />` or anywhere else in your application as a means to change tabs.

The hook usage is aimed at the second use case and as a escape hatch when using the component, or the `asChild` prop is not ideal.

I can see how the paragraph here makes this slightly confusing, I'll adjust the docs https://docs.expo.dev/router/advanced/custom-tabs/#hooks

**Comment by affectful** [comment] 2024-12-20 06:10
I think it is not sufficient to change the docs to say to make a custom TabList. The `<Tabs>` component is the one that parses triggers from children. To use the hooks API would require changing `useTabsWithChildren` to use a custom `parseTriggersFromChildren` which then would need a custom `isTabTrigger`. It seems to be a flaw of API design to have three hidden requirements to use the hooks API
