### ISSUE TITLE
expo-image-picker freezes after selecting an image and hitting the "choose" button( M1 chip Macbook running Big Sur)

### ISSUE THREAD

**Issue by webdevike** [expo/expo#11291] opened 2020-12-09 18:08 UTC
### Summary of Issue 
expo-image-picker freezes after selecting an image and hitting the "choose" button. It works as expected on a physical device and on a 2018 macbook pro. However it does not work in the IOS simulator on an M1 Chip Macbook Air(Big Sur). I have tried restarting my device, re-downloaded xcode, change some settings etc. Nothing seems to work. I replicated this issue in 2 different project now.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 4.0.11 environment info:
    System:
      OS: macOS 11.0
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.4.0 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 4.0.11
    Expo Workflow: managed

### Reproducible Demo
```js
import * as ImagePicker from 'expo-image-picker'

export default function App() {

  useEffect(() => {
    (async () => {
      if (Platform.OS !== 'web') {
        const { status } = await ImagePicker.requestCameraRollPermissionsAsync()
        console.log(status)
        if (status !== 'granted') {
          alert('Sorry, we need camera roll permissions to make this work!')
        }
      }
    })()
  }, [])

  const _pickImage = async (screen: string) => {
    try {
      const result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.All,
        allowsEditing: true,
        aspect: [4, 3],
        quality: 1,
      })
    } catch (error) {
    }
  }
  
  return (
    <View style={styles.container}>
      <Button title="pick Image" color="black" onPress={_pickImage}/>
    </View>
  );
}
```

 
### Steps to Reproduce
* `expo init camera-test`
* open project
* `yarn add expo-image-picker`
* add the code to ask permission and code to launch image picker
* `yarn start`
* press I key when loaded for IOS simulator
* project loads on IOS simulator device(Iphone 12 pro)
* click button to open image library
* click a picture from the library
* Image cropping tool comes up(I am able to crop the image and click cancel button)
* click the "choose" button
* BUG --> IOS simulator freezes(unable to click anything or do anything at all)

### Expected Behavior vs Actual Behavior
Expected Behavior:  Able to choose an image from the image library.
Actual Behavior: Choosing an image causes the IOS simulator to freeze and I am unable to do anything.

**Comment by brentvatne** [comment] 2020-12-09 23:30
this is probably a bug with the ios simulator on m1

**Comment by jamesloper** [comment] 2020-12-15 18:02
The console is nonsense to me, perhaps others can have a crack at it?

When you trigger `ImagePicker.launchImageLibraryAsync`...
```
2020-12-15 12:59:53.312483-0500 hotspot[26616:647219] [db] _LSSchemaConfigureForStore failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x35effaa3 2bab3fa8 68f8c96b cd17d15e ... 9bf8f6b7 fd486754 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe14e0f7b 39a9580e 8e4762c4 846107dc ... 21618def 3c69a5ae }}
2020-12-15 12:59:53.312697-0500 hotspot[26616:647219] [db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x35effaa3 2bab3fa8 68f8c96b cd17d15e ... 9bf8f6b7 fd486754 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe14e0f7b 39a9580e 8e4762c4 846107dc ... 21618def 3c69a5ae }}
2020-12-15 12:59:53.312979-0500 hotspot[26616:647219] [ls] unable to get LSApplicationExtensionRecord: Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x35effaa3 2bab3fa8 68f8c96b cd17d15e ... 9bf8f6b7 fd486754 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe14e0f7b 39a9580e 8e4762c4 846107dc ... 21618def 3c69a5ae }}
2020-12-15 12:59:53.346316-0500 hotspot[26616:648505] [db] _LSSchemaConfigureForStore failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x35effaa3 2bab3fa8 68f8c96b cd17d15e ... 9bf8f6b7 fd486754 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe14e0f7b 39a9580e 8e4762c4 846107dc ... 21618def 3c69a5ae }}
2020-12-15 12:59:53.346483-0500 hotspot[26616:648505] [db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x35effaa3 2bab3fa8 68f8c96b cd17d15e ... 9bf8f6b7 fd486754 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe14e0f7b 39a9580e 8e4762c4 846107dc ... 21618def 3c69a5ae }}
```

When you pic an image...
```
2020-12-15 13:01:00.446663-0500 hotspot[26616:648681] [db] _LSSchemaConfigureForStore failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x35effaa3 2bab3fa8 68f8c96b cd17d15e ... 9bf8f6b7 fd486754 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe14e0f7b 39a9580e 8e4762c4 846107dc ... 21618def 3c69a5ae }}
2020-12-15 13:01:00.446804-0500 hotspot[26616:648681] [db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x35effaa3 2bab3fa8 68f8c96b cd17d15e ... 9bf8f6b7 fd486754 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe14e0f7b 39a9580e 8e4762c4 846107dc ... 21618def 3c69a5ae }}
2020-12-15 13:01:00.447305-0500 hotspot[26616:648681] [db] _LSSchemaConfigureForStore failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x35effaa3 2bab3fa8 68f8c96b cd17d15e ... 9bf8f6b7 fd486754 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe14e0f7b 39a9580e 8e4762c4 846107dc ... 21618def 3c69a5ae }}
2020-12-15 13:01:00.447439-0500 hotspot[26616:648681] [db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x35effaa3 2bab3fa8 68f8c96b cd17d15e ... 9bf8f6b7 fd486754 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe14e0f7b 39a9580e 8e4762c4 846107dc ... 21618def 3c69a5ae }}
2020-12-15 13:01:00.447871-0500 hotspot[26616:648681] [db] _LSSchemaConfigureForStore failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x35effaa3 2bab3fa8 68f8c96b cd17d15e ... 9bf8f6b7 fd486754 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe14e0f7b 39a9580e 8e4762c4 846107dc ... 21618def 3c69a5ae }}
2020-12-15 13:01:00.451503-0500 hotspot[26616:648681] [db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x35effaa3 2bab3fa8 68f8c96b cd17d15e ... 9bf8f6b7 fd486754 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe14e0f7b 39a9580e 8e4762c4 846107dc ... 21618def 3c69a5ae }}
2020-12-15 13:01:00.451944-0500 hotspot[26616:648681] [db] _LSSchemaConfigureForStore failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x35effaa3 2bab3fa8 68f8c96b cd17d15e ... 9bf8f6b7 fd486754 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe14e0f7b 39a9580e 8e4762c4 846107dc ... 21618def 3c69a5ae }}
2020-12-15 13:01:00.452061-0500 hotspot[26616:648681] [db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x35effaa3 2bab3fa8 68f8c96b cd17d15e ... 9bf8f6b7 fd486754 }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0xe14e0f7b 39a9580e 8e4762c4 846107dc ... 21618def 3c69a5ae }}
2020-12-15 13:01:00.454045-0500 hotspot[26616:648681] [xpc.exceptions] <NSXPCConnection: 0x60000229eb20> connection on anonymousListener or serviceListener from pid 26630: Warning: Exception caught during invocation of selector didSelectMediaWithInfoDictionary:, dropping incoming message and invalidating the connection.
Exception: *** -[NSURL URLByAppendingPathExtension:]: component, components, or pathExtension cannot be nil.
*** -[NSURL URLByAppendingPathExtension:]: component, components, or pathExtension cannot be nil.
(
	0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   Foundation                          0x00007fff2085f900 -[NSURL(NSURLPathUtilities) URLByDeletingPathExtension] + 0
	3   PhotosUI                            0x00007fff3f7074be -[PUPhotoPickerExtensionHostContext _UIImagePickerControllerInfoDictionaryFromPhotoPickerInfoDictionary:] + 2177
	4   PhotosUI                            0x00007fff3f706aaf -[PUPhotoPickerExtensionHostContext didSelectMediaWithInfoDictionary:] + 34
	5   Foundation                          0x00007fff209280e3 __NSXPCCONNECTION_IS_CALLING_OUT_TO_EXPORTED_OBJECT_S1__ + 10
	6   Foundation                          0x00007fff20926e1b -[NSXPCConnection _decodeAndInvokeMessageWithEvent:flags:] + 2268
	7   Foundation                          0x00007fff20928412 message_handler + 206
	8   libxpc.dylib                        0x00007fff20055cac _xpc_connection_call_event_handler + 56
	9   libxpc.dylib                        0x00007fff2005603e _xpc_connection_mach_event + 905
	10  libdispatch.dylib                   0x000000010a68da68 _dispatch_client_callout4 + 9
	11  libdispatch.dylib                   0x000000010a6a7ba8 _dispatch_mach_msg_invoke + 550
	12  libdispatch.dylib                   0x000000010a6940ad _dispatch_lane_serial_drain + 307
	13  libdispatch.dylib                   0x000000010a6a8a76 _dispatch_mach_invoke + 563
	14  libdispatch.dylib                   0x000000010a6940ad _dispatch_lane_serial_drain + 307
	15  libdispatch.dylib                   0x000000010a694f9d _dispatch_lane_invoke + 493
	16  libdispatch.dylib                   0x000000010a6a0de2 _dispatch_workloop_worker_thread + 882
	17  libsystem_pthread.dylib             0x00007fff60c8e499 _pthread_wqthread + 314
	18  libsystem_pthread.dylib             0x00007fff60c8d467 start_wqthread + 15
)
```

**Comment by jamesloper** [comment] 2020-12-15 18:04
Maybe it's fixable actually. Looks like it's trying to generate a URI in the delegate didSelectMediaWithInfoDictionary to send over the RN bridge, but there is a reference error.

**Comment by hyochan** [comment] 2021-01-02 04:16
Nice issue. I was just suffering from this.

**Comment by aakdari** [comment] 2021-01-03 21:55
Am also running into the same problem, simulating an iphone 12 on an m1 processor mac pro

**Comment by slvtrs** [comment] 2021-01-04 20:09
Same issue on an M1. Definitely an iOS simulator issue rather than specific to expo-image-picker though.
I tried selecting a photo in the stock Messages app and that just resulted in a black screen.

**Comment by snehjogani** [comment] 2021-01-22 14:56
I'm facing the same thing on iPhone 12 simulator on M1 chip mac. Any updates/fixes on this issue?

**Comment by meronix** [comment] 2021-02-03 16:55
same issue with M1, Xcode 12.4, simulator iOS 14.4


Exception: *** -[NSURL URLByAppendingPathExtension:]: component, components, or pathExtension cannot be nil.
*** -[NSURL URLByAppendingPathExtension:]: component, components, or pathExtension cannot be nil.
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   Foundation                          0x00007fff20860900 -[NSURL(NSURLPathUtilities) URLByDeletingPathExtension] + 0
	3   PhotosUI                            0x00007fff3faf656a -[PUPhotoPickerExtensionHostContext _UIImagePickerControllerInfoDictionaryFromPhotoPickerInfoDictionary:] + 2177
	4   PhotosUI                            0x00007fff3faf5b5b -[PUPhotoPickerExtensionHostContext didSelectMediaWithInfoDictionary:] + 34
	5   Foundation                          0x00007fff209290e3 __NSXPCCONNECTION_IS_CALLING_OUT_TO_EXPORTED_OBJECT_S1__ + 10
	6   Foundation                          0x00007fff20927e1b -[NSXPCConnection _decodeAndInvokeMessageWithEvent:flags:] + 2268
	7   Foundation                          0x00007fff20929412 message_handler + 206

**Comment by planetmall** [comment] 2021-03-13 20:15
Same issue. M1 iOS 12 Max

**Comment by RRaideRR** [comment] 2021-03-15 18:27
same problem here - M1 iOS 12

**Comment by kei95** [comment] 2021-03-17 21:06
Same issue here. M1 version 11.2.3, simulator iOS 14.4

**Comment by brentvatne** [comment] 2021-03-17 21:10
my comment from above:

> this is probably a bug with the ios simulator on m1, but if you have more information to indicate that it is a bug in expo's code then please let us know

i'm going to lock this issue because it appears to be unrelated to expo but rather with the m1. there are many documented m1 simulator issues. such is the risk of opting in to first gen processors :) if you do find that there is some cause that can be tied back to expo code, please open a pull request or another issue with specific information about it. we'll leave this issue open as a psa

**Comment by vonovak** [comment] 2024-08-23 08:40
Hello 👋 ,
this issue is not reproducible any more.

With that, I'm closing the issue.
Thank you! 🙂

**Closed by vonovak** 2024-08-23 08:40 UTC
Labels: needs more info
