### ISSUE TITLE
EXPO SDK 37. Push Token - ERROR on Android device. - Couldn't get GCM token on device

### ISSUE THREAD

**Issue by diegolaciar** [expo/expo#7785] opened 2020-04-09 19:52 UTC
### Environment

System:
OS: macOS 10.15.3
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
npm: 6.14.2 - ~/.nvm/versions/node/v12.16.1/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
npmPackages:
expo: ^37.0.0 => 37.0.6
react: 16.9.0 => 16.9.0
react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
react-navigation: ^3.13.0 => 3.13.0

### Steps to Reproduce

try {
      const pushToken = await Notifications.getExpoPushTokenAsync();
    } catch (error) {
      console.log(error);
    }
### Expected Behavior

get the value on pushToken constant.

Expo 36 works just fine. 

error debug:
```
error:  Error: Couldn't get GCM token on device.
    at Object.fn [as getExponentPushTokenAsync] (NativeModules.js:99)
    at Object.getExpoPushTokenAsync (Notifications.js:131)
    at registerForPushNotificationsAsync$ (VM13 registerForPushNotificationsAsync.bundle:66)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:145
    at tryCallOne (core.js:37)
```

**Comment by rphlmr** [comment] 2020-04-09 23:11
I start a fresh project today and it's working.
But i had some trouble with expo cli authentication. I log out log in and that fixed the issue.
Like here : https://github.com/expo/expo/issues/5900#issuecomment-548053485

**Comment by diegolaciar** [comment] 2020-04-10 03:52
@rphlmr 

thanks for your response.

Just tried that.  
the issue persist.  Couldn't get GCM token on device.
Previous version expo 36 was working, with the same device.

```
expo logout
Success.

 expo login
? Username/Email Address: diegolaciar
? Password: [hidden]

Success. You are now logged in as diegolaciar.
```

**Comment by brentvatne** [comment] 2020-04-10 04:00
@diegolaciar - make sure you have the latest version of the client from expo-cli - it hasn’t been updated on the play store yet

**Comment by diegolaciar** [comment] 2020-04-10 04:10
yes, the mobile have the latest version. with expo 37 support says.
Client version 2.15.0

**Comment by partitect** [comment] 2020-04-10 09:38
+1 issue
it working on three days ago but not work now.
expo login -- OK
expo-cli -- Latest(3.17.21)
Expo Client -- Latest
sdk -- 37.0.0

**Comment by rphlmr** [comment] 2020-04-10 09:41
Is it FCM (Android push notifications) or just push notification ?

There is a breaking change for FCM in sdk 37 : https://github.com/expo/expo/blob/master/CHANGELOG.md#3700

**Comment by partitect** [comment] 2020-04-10 11:03
> Is it FCM (Android push notifications) or just push notification ?
> 
> There is a breaking change for FCM in sdk 37 : https://github.com/expo/expo/blob/master/CHANGELOG.md#3700

just expo notification

when install expo-client 2.15.1 problem solved

**Comment by cruzach** [comment] 2020-04-10 18:16
Closing this as a duplicate of 
- Expo Client: https://github.com/expo/expo/issues/7653  (see this issue for solution)
- Standalone APK: https://github.com/expo/expo/issues/7727

**Closed by cruzach** 2020-04-10 18:16 UTC
Labels: Needs triage
