### ISSUE TITLE
Camera.recordAsync flickers with black frames before recording starts and finishing

### ISSUE THREAD

**Issue by watanabeyu** [expo/expo#1505] opened 2018-03-07 07:00 UTC
Hi
I created a video recording App, and use {Camera} from expo;
But flicker will appears before camera.recordAsync() and camera.stopRecording().

Expo's v23.0.0 will not appears , v25.0.0 will appear.

V23.0.0 Camera (flicker not appear)
https://snack.expo.io/SJb0sW6df

V25.0.0 Camera (flicker appear)
https://snack.expo.io/SJRm2W6_M

Is there a way to solve it?

**Comment by watanabeyu** [comment] 2018-03-07 07:11
v24.0.0 will apper also.
https://snack.expo.io/SJaLgGadz

**Comment by aalices** [comment] 2018-03-13 08:34
This probably a duplicate of https://github.com/expo/expo/issues/1057
Sorry, there's no fix yet

**Closed by aalices** 2018-03-13 08:34 UTC
Labels: project: sdk
