### ISSUE TITLE
Can't open file read with FileSystem.readAsStringAsync

### ISSUE THREAD

**Issue by boboci9** [expo/expo#2045] opened 2018-07-30 16:28 UTC
Hi,

I am trying to send a file from react-native to my meteor app and the send it to azure for storing.
The issue is I can't open the string I get with FileSystem.readAsStringAsync as an image.
Do you know what can be the issue what am I doing wrong? The description of the readAsStringAsync says read the file as a string but doesn't say how will that string be formated. I tried creating buffers with both base64 and utf8, binary format but none worked.
```
result = await FileSystem.readAsStringAsync("file:///data/user/0/host.exp.exponent/files/Experi…3-4bb9-8426-ff323f59d2e7/photos/1532683401346.jpg");
```
I am sending this result to my application but when I download and open this string as a jpg on ubuntu I get:
`Error interpreting JPEG image file (Not a JPEG file: starts with 0x22 0xef)`

Thank you for your help in advance.

**Comment by ide** [comment] 2018-07-30 17:43
`FileSystem.readAsStringAsync` expects the bytes to be a valid UTF-8 string, so reading a JPEG-encoded image won't work. For this use case, depending on how the photo was taken (e.g. with ImagePicker), you may be able to get a base64-encoded version of the photo and then could base64-decode it off the device.

**Comment by boboci9** [comment] 2018-07-30 18:18
I only have the image uri from the file system, photos are taken by the camera and saved on the device then the user can select several and send it to an application for upload. What external package could I use to get the images from the device? Any suggestions?

**Comment by sjchmiela** [comment] 2018-07-31 16:01
If you'd like to send images to server you probably don't need to read the images to strings. React Native supports blobs and uploading them to servers, check out this article — https://snowball.digital/Blog/Uploading-Images-in-React-Native.

The most important part is this:

```js
    var data = new FormData();
    data.append('picture', {
      uri: picturePath,
      name: 'selfie.jpg',
      type: 'image/jpg'
    });

    // Create the config object for the POST
    // You typically have an OAuth2 token that you use for authentication
    const config = {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'multipart/form-data;',
        Authorization: 'Bearer ' + 'SECRET_OAUTH2_TOKEN_IF_AUTH'
      },
      body: data
    };
```

Just create `FormData` and fill it with the URI you get from the image picker. 🙂

**Comment by quinlanj** [comment] 2018-07-31 18:00
Closing this issue because it is not a bug and has sufficient answers. If you have any additional questions, feel free to post to the forums, thanks!

**Closed by quinlanj** 2018-07-31 18:00 UTC
