### ISSUE TITLE
Font download from google fonts not working on Android

### ISSUE THREAD

**Issue by kopax** [expo/expo#8020] opened 2020-04-26 15:33 UTC
## 🐛 Bug Report

I have downloaded all the following font from google fonts and try to load then using expo-font 8.0.0 within expo SDK36

```jsx
          Raleway: require('../assets/fonts/Raleway/Raleway-Regular.ttf'),
          'Raleway-medium': require('../assets/fonts/Raleway/Raleway-Medium.ttf'),
          'Raleway-light': require('../assets/fonts/Raleway/Raleway-Light.ttf'),
          'Raleway-thin': require('../assets/fonts/Raleway/Raleway-Thin.ttf'),
          Roboto: require('../assets/fonts/Roboto/Roboto-Regular.ttf'),
          Vollkorn: require('../assets/fonts/Vollkorn/Vollkorn-Regular.ttf'),
          Montserrat: require('../assets/fonts/Montserrat/Montserrat-Regular.ttf'),
          AbrilFatface: require('../assets/fonts/Abril_Fatface/AbrilFatface-Regular.ttf'),
          Lato: require('../assets/fonts/Lato/Lato-Regular.ttf'),
          PTserif: require('../assets/fonts/PT_Serif/PTSerif-Regular.ttf'),
```

### Environment

```
  Expo CLI 3.19.2 environment info:
    System:
      OS: Linux 5.3 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 13.11.0 - ~/.nvm/versions/node/v13.11.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v13.11.0/bin/yarn
      npm: 6.14.4 - ~/workspace/git.kopaxgroup.com/momagroup/icimatin-native/node_modules/.bin/npm
    npmPackages:
      expo: ~36.0.2 => 36.0.2 
      react: ^16.13.1 => 16.13.1 
      react-native: file:expo/react-native-sdk-36.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.17.18
```

Android/Web/Ios

### Steps to Reproduce

- Download from google fonts all those fonts and load them with `Fonts.loadAsync`.

### Expected Behavior

I expect to be able to use the style `fontFamily: 'Montserrat'` and see this fonts used by my text.

### Actual Behavior

It does not change the font on android.

I have tried to set the value using the react-native-paper  `theme`, it works on android only within one page, but on others it doesn't show anything, this is how I have applied the fonts in `one` case in my app because of Android:

```jsx
                <TextInput
                  style={styles.input}
                  theme={{
                    ...theme,
                    fonts: {
                      ...theme.fonts,
                      ...(!getFontKeyFromId(input.value) ? {} : configureFonts({
                        web: {
                          regular: {
                            fontFamily: getFontKeyFromId(input.value),
                            fontWeight: 'normal',
                          },
                        },
                        ios: {
                          regular: {
                            fontFamily: getFontKeyFromId(input.value),
                            fontWeight: 'normal',
                          },
                        },
                        android: {
                          regular: {
                            fontFamily: getFontKeyFromId(input.value),
                            fontWeight: 'normal',
                          },
                        },
                      })),
                    },
                  }}
                  icon="chevron-down"
                  mode="outlined"
                  label={label}
                  editable={false}
                  disabled={loading > 0}
                  value={list?.find((d) => d.id === input.value)?.description || ''}
                  error={meta.error && meta.touched}
                  {...buttonProps}
                />
```

Strangly, on another page with the same idea, it doesn't work.

**Comment by byCedric** [comment] 2020-04-27 13:48
Hi @kopax! Could you provide a [small repro](https://stackoverflow.com/help/minimal-reproducible-example)? Without that, I can't check if and where the issue originates from.

**Comment by kopax** [comment] 2020-04-27 17:11
I've started to work on it, but google is only offering `.ttf` to download, no CDN.

**Comment by brentvatne** [comment] 2020-04-27 17:25
@kopax - i use google fonts all the time, can you share a running example rather than the steps? in the snack repro you're loading from a remote url, you should download it to local file instead and use `require`

waiting for a repro that i can clone from github

**Comment by kopax** [comment] 2020-04-27 20:13
I am actually downloading it and importing from the file system.
I will prepare a repository that you can close asap

**Comment by brentvatne** [comment] 2020-04-27 20:22
@kopax - you can upload files to snack and refer to them, here is your example with the ttf loaded locally: https://snack.expo.io/@notbrent/funny-soylent?platform=ios

**Comment by Jongkeun** [comment] 2020-07-21 14:07
I have the same problem.
IOS works well. But android was weird.
It's the same code and I don't think I should do extra something for the only android.
Is there anything checked or processed?

**Comment by Jongkeun** [comment] 2020-07-21 14:20
> @kopax - you can upload files to snack and refer to them, here is your example with the ttf loaded locally: https://snack.expo.io/@notbrent/funny-soylent?platform=ios

@brentvatne, you can check the snack which you mentioned.
You can see it looks different ios and android.
 
### ios adjust an example font
![Screenshot 2020-07-21 at 11 15 36 PM](https://user-images.githubusercontent.com/33743343/88066124-5e952b80-cba8-11ea-9d9f-9b1e60f632cd.png)

### ios default font
![Screenshot 2020-07-21 at 11 16 00 PM](https://user-images.githubusercontent.com/33743343/88066186-6fde3800-cba8-11ea-9b55-7676d3ec0c51.png)

### android adjust an example font and default font are the same
![Screenshot 2020-07-21 at 11 16 21 PM](https://user-images.githubusercontent.com/33743343/88066350-9d2ae600-cba8-11ea-9920-4e84297861ae.png)

**Comment by Jongkeun** [comment] 2020-07-23 13:07
omg, I found out the reason!
It was fixed after removing `font-weight` attribute.
I think, if I want to use bold fonts, I have to load bold font of that in Android.
It seems like that anyway.

**Comment by anandchakru** [comment] 2020-09-21 07:33
> omg, I found out the reason!
> It was fixed after removing `font-weight` attribute.
> I think, if I want to use bold fonts, I have to load bold font of that in Android.
> It seems like that anyway.

Thank you, there was only `Parisienne_400Regular` available and `fontWeight: 'bold'` was in my styles. It worked in ios, only android had trouble loading it. Thank you

**Comment by IjzerenHein** [comment] 2021-01-19 11:28
Yes that's right. Android has limitations for using `font-weight` and `font-style`. You have to load the font by its full name (e.g. "Parisienne_400Regular" and refer to it by that name in `font-family` without using the font-weight.
This issue seems to have been resolved, so I'm going to close it :)

**Closed by IjzerenHein** 2021-01-19 11:28 UTC
Labels: Android, Font, needs repro

**Comment by zealmurapa** [comment] 2022-10-15 23:07
Some font names are reserved in Android and won't work. I wish there was a list somewhere to obtain the full list. Naming a font 'normal' etc will not work

**Comment by GBPeters** [comment] 2024-07-05 20:56
> omg, I found out the reason! It was fixed after removing `font-weight` attribute. I think, if I want to use bold fonts, I have to load bold font of that in Android. It seems like that anyway.

I know this issue is ancient and don't want to reopen anything, just wanted to say THANK YOU @Jongkeun for sharing this I have been pulling my hair out on this issue 😂
