### ISSUE TITLE
[expo-notifications] category dont gets displayed when app is killed / in background

### ISSUE THREAD

**Issue by basti4557** [expo/expo#31503] opened 2024-09-16 18:22 UTC
### Minimal reproducible example

https://github.com/basti4557/expo-notification-category-bug

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Before when sending a categoryId to the expo servers in your request the app loaded the category, which was set before over "setNotificationCategoryAsync".

Now this works when the app is in foreground, but if the app is in background / killed the category dont gets shown in the notification (for example buttons).

Parameters sent to the expo backend: 
`  {
  "title": "Your title here",
  "body": "Your message here",
  "data": {
    "title": "Your title here",
    "body": "Your message here",
    "answerUserId": "YourAnswerUserIdHere",
    "layout": "YourLayoutHere"
  },
  "channelId": "default",
 "categoryId": "myAnswerNotification"
}
`

Notification when app is in foreground:
![Screenshot_20240916-200947](https://github.com/user-attachments/assets/08efa829-43bd-432b-a817-82c18b12a5fa)

Notification when app is in background/killed:
![Screenshot_20240916-201007](https://github.com/user-attachments/assets/2de80205-0019-4c00-bf45-c7d0685098b9)

Received notification while app is in foreground:
`{"date": 1726510181074, "request": {"content": {"autoDismiss": true, "badge": null, "body": "Your message here", "categoryIdentifier": "myAnswerNotification", "data": [Object], "sound": "default", "sticky": false, "subtitle": null, "title": "Your title here"}, "identifier": "XXXXXXXX", "trigger": {"channelId": "default", "remoteMessage": [Object], "type": "push"}}}`

Received notification while app is in background/killed:
`{"date": 1726510496996, "request": {"content": {"autoDismiss": true, "badge": null, "body": "Your message here", "categoryIdentifier": "myAnswerNotification", "data": [Object], "sound": "default", "sticky": false, "subtitle": null, "title": "Your title here"}, "identifier": "XXXXXXXXX", "trigger": {"channelId": "default", "remoteMessage": [Object], "type": "push"}}}`

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
      npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12169540
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.32 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    npmGlobalPackages:
      eas-cli: 12.3.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by Yury-Shevchenko** [comment] 2024-09-23 07:55
I have exactly the same issue. The action buttons are not shown on Android in production as well. It would be great if there is a solution to that or a workaround that can be used before the issue is fixed? Thank you!

**Comment by RohovDmytro** [comment] 2024-09-26 20:06
> I have exactly the same issue. The action buttons are not shown on Android in production as well (except when the app is open). It would be great if there is a solution to that or a workaround that can be used before the issue is fixed? Thank you!

How do you even define the category id while scheduling the notification for Android? I can't find the relevant information in the docs and I've just tried many possible combos. Nothing works.

Relevant issue: https://github.com/expo/expo/issues/31711

**Comment by basti4557** [comment] 2024-09-26 21:12
> @Yury-Shevchenko @basti4557
> 
> > I have exactly the same issue. The action buttons are not shown on Android in production as well (except when the app is open). It would be great if there is a solution to that or a workaround that can be used before the issue is fixed? Thank you!
> 
> How do you even define the category id while scheduling the notification for Android? I can't find the relevant information in the docs and I've just tried many possible combos. Nothing works.
> 
> Relevant issue: #31711

https://docs.expo.dev/push-notifications/sending-notifications/
<img width="859" alt="image" src="https://github.com/user-attachments/assets/b15630ef-5ea3-4948-b17b-1a83f078b89b">

**Comment by basti4557** [comment] 2024-10-29 17:00
@vonovak I saw that there is an potential fix in 0.29.0 for that issue, sadly it seems that 0.29.0 is only for the new SDK 52. Will this this fix also get ported on SDK 51 and the 0.28.x build series ?

**Comment by vonovak** [comment] 2024-10-29 17:03
hello @basti4557,
> sadly it seems that 0.29.0 is only for the new SDK 52

what makes you think that? It should work also in 51 AFAICT.

Thanks :)

**Comment by basti4557** [comment] 2024-10-29 17:09
`what makes you think that? It should work also in 51 AFAICT.`
For testing purposes i already installed 0.29.1, 0.29.2 and 0.29.3 in my app in an production apk build, every version crashed when trying to start the app immediately, so i thought it should be because of the "old" SDK 51 🤔 

So:
Building the same app with 0.28.19 -> app and notifications work
Build the same app with 0.29.x -> app is crashing at startup

**Comment by basti4557** [comment] 2024-10-29 17:57
<img width="385" alt="image" src="https://github.com/user-attachments/assets/e4f4b940-e695-47ca-bab7-58992c56d2ef">
This error is in 0.29.4

**Comment by vonovak** [comment] 2024-10-30 15:49
Okay, so I circled back to this. @basti4557 there's no change in `0.29.0` that addresses this issue (correct me if I'm wrong). You can send a data-only notification which will display the buttons if you specify a `categoryId` in the `data` field (along with `title` and `message` probably: see https://github.com/expo/expo/blob/1f2028e5df1d7aa7ed32e3767262e8057ca9d818/packages/expo-notifications/android/src/test/java/expo/modules/notifications/NotificationDataTest.kt#L18)

However, when the app is killed and people press those action buttons without launching the app, you will never learn about that user action taking place. We are actively working on resolving this _and_ updating the docs. If everything goes well, it'll work when the SDK 52 goes out of beta.
Hope this at least gives some context. TY! :)

**Comment by basti4557** [comment] 2024-10-30 19:51
@vonovak I thought `[android] fix notifications actions not being presented (https://github.com/expo/expo/pull/31795 by [@vonovak](https://github.com/vonovak))` would be the fix, because of the title well fitted my problem 🤔 

For me its very difficult to really understand (also out of the docs) how this all should be handled together. For example i never used the background task or the data only notifications up to now and it all worked well. The only downside was that every action opened the app to really execute instead of just staying closed / in background.

After changing my payload to data only and adding the background task (which should be triggered from docs if the app is in background / foreground) it indeed get triggered there in the development build. after building an production apk it only triggers in the background, not the foreground.

Im really grateful that your investing the time in fixing the notifications, but indeed i dont think im the only person hardly struggling with adding / porting the expo notifications to the changes :/

<img width="981" alt="image" src="https://github.com/user-attachments/assets/3d4d99ac-36e8-475e-81a4-40d2365cd827">

**Comment by vonovak** [comment] 2024-10-30 22:55
@basti4557 `[android] fix notifications actions not being presented` is released in [0.28.18](https://github.com/expo/expo/blob/sdk-51/packages/expo-notifications/CHANGELOG.md#02818--2024-10-01) for SDK 51. You can see SDK-51 releases being done on the `sdk-51` branch of the repository.

Thank you for the feedback! You can expect features and also the docs to get better over the course of SDK 52. Just keep in mind notifications have a lot of features and it's a large ground to cover. There's not only the client-side libraries but the Expo push service that we work on. That's why it can take a bit of time :)

> after building an production apk it only triggers in the background, not the foreground.

That sounds like a separate issue then. If you can reproduce it, please open an issue and we can take a look. I'd also encourage you to debug the issue and contribute a fix - that's the fastest way to get a bug resolved.
Thank you!

**Comment by rranjan14** [comment] 2024-10-31 02:51
> @basti4557 `[android] fix notifications actions not being presented` is released in [0.28.18](https://github.com/expo/expo/blob/sdk-51/packages/expo-notifications/CHANGELOG.md#02818--2024-10-01) for SDK 51. You can see SDK-51 releases being done on the `sdk-51` branch of the repository.
> 
> Thank you for the feedback! You can expect features and also the docs to get better over the course of SDK 52. Just keep in mind notifications have a lot of features and it's a large ground to cover. There's not only the client-side libraries but the Expo push service that we work on. That's why it can take a bit of time :)
> 
> > after building an production apk it only triggers in the background, not the foreground.
> 
> That sounds like a separate issue then. If you can reproduce it, please open an issue and we can take a look. I'd also encourage you to try debug the issue and contribute a fix - that's the fastest way to get a bug resolved. Thank you!

I am on 0.28.19, the category isn't displayed in background. In fact not even title was being displayed. Once I added title, body, sound and channelId in the notification object rather than in data object as mentioned [here](https://docs.expo.dev/push-notifications/sending-notifications-custom/#payload-formats) I could see that in the the notification and sound was working too. I guess properties for creating notification are not being read from the data object.

**Comment by basti4557** [comment] 2024-10-31 07:50
@vonovak correct me if im wrong, but my understanding (at the moment) is the following:

Background task data only notifications are not handled by the underlaying firebase package and instead get directly processed by the react native app, which then can trigger manual notifications. 

So if i assume that the only thing the expo notifications package should do for displaying normal notifications (not data only) in foreground / background is at least "nothing", because the expo servers send a payload to the firebase servers and the firebase servers to the client which will get directly processed by the original firebase package (?)

So if i assume that completely a change in the expo-notifications package also should not do the trick because it just could be the payload from the expo servers to the firebase servers which makes the behaviour faulty?

if im wrong with my understanding please correct me, i looked a little bit in the expo-notifications folder in the repo and couldnt really find a place where notifications should get processed when not working with the background tasks or notificationListener (with indeed works except of categories)

**Comment by vonovak** [comment] 2024-11-01 14:14
Hello @basti4557,

> Background task data only notifications are not handled by the underlaying firebase package and instead get directly processed by the react native app, which then can trigger manual notifications.

yes

> if i assume that the only thing the expo notifications package should do for displaying normal notifications (not data only) in foreground / background is at least "nothing"

when the app is in foreground, the app is responsible for handling the notification any way it likes. In other states, the notification will be delivered automatically and the app doesn't control that.

---
Of course, the payload which you're sending to expo push servers matters too. I suggest you tell me what behavior you want to achieve, and I can tell you how to get there.

**Comment by basti4557** [comment] 2024-11-01 16:27
@vonovak I want to archive that my category set over "setNotificationCategoryAsync" is getting displayed in the notification in foreground / background / killed. Actually it is getting displayed in Foreground State, but not killed and background - like it did before July with the same code.

The App Code is built like here [https://github.com/basti4557/expo-notification-category-bug/blob/main/ExpoNotificationChannelBug/App.tsx](https://github.com/basti4557/expo-notification-category-bug/blob/main/ExpoNotificationChannelBug/App.tsx)

And the payload sent to the expo servers is like this:
`{
    "title": "<title>",
    "body": "<message>",
    "data": {
        "title": "<title>",
        "body": "<message>",
        "answerUserId": "<answerUserId>",
        "layout": "<layout>",
        "channelId": "default"
    },
    "channelId": "default",
    "categoryId": "<layout>"
}`

**Comment by vonovak** [comment] 2024-11-01 16:36
I believe you should be sending a data-only notification, like you did [here](https://github.com/expo/expo/issues/31503#issuecomment-2448234964).

Definitely do not send title and etc in the top-level notification object, because that will result in notification message that won't contain action buttons (as defined by `categoryId`).

Hope this helps! :)

**Comment by basti4557** [comment] 2024-11-01 16:48
When sending a data only notification the received result (with the actual code) is an empty notification with no title, message and category (an empty bubble). This bubble is shown when the app is in foreground, but nothing if it is in background or killed. 

Like i see in the docs there is also no state that would get triggered where i can sneak in when the app is killed.
<img width="603" alt="image" src="https://github.com/user-attachments/assets/88b99301-f541-4abe-97f2-7510acc900cf">

**Comment by vonovak** [comment] 2024-11-04 09:18
@basti4557 the notification title is taken from [here](https://github.com/expo/expo/blob/001ecb0bb73af35571b6f6429d046f552cf0ffcd/packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/model/RemoteNotificationContent.kt#L34). It originates either from the `notification` payload or the `data` payload. 

> there is also no state that would get triggered where i can sneak in when the app is killed with data-only.

we're working on that: https://github.com/expo/expo/pull/32531

**Comment by vonovak** [comment] 2024-11-25 13:10
> I only experience the side effect that when the app is in foreground also an empty notification spawns beside the created one with the background task.

Remember that when app is in foreground, it is _you_ who is in charge of presenting it with [setNotificationHandler](https://docs.expo.dev/versions/latest/sdk/notifications/#setnotificationhandlerhandler).

You probably need to do something like this: https://github.com/expo/expo/issues/31184#issuecomment-2374188145

Tweak the conditions to your liking and remember 

>  when app is in foreground, it is _you_ who is in charge of handling the notification

Does this help?
V.

**Comment by basti4557** [comment] 2024-12-04 08:44
> Remember that when app is in foreground, it is you who is in charge of presenting it with [setNotificationHandler](https://docs.expo.dev/versions/latest/sdk/notifications/#setnotificationhandlerhandler).
You probably need to do something like this: https://github.com/expo/expo/issues/31184#issuecomment-2374188145

Your snippet is indeed hiding the empty notification, but also the notification i want to schedule over scheduleNotificationAsync

It seems that also in data-only notifications a notification gets triggered with no content, when the app is in foreground. 
![image](https://github.com/user-attachments/assets/38f77a4d-73ba-4ed1-b1e6-7f6663807d08)

```
Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: true,
    shouldSetBadge: false,
    priority: Notifications.AndroidNotificationPriority.MAX,
  }),
});

  const BACKGROUND_NOTIFICATION_TASK = 'BACKGROUND-NOTIFICATION-TASK';
  TaskManager.defineTask(BACKGROUND_NOTIFICATION_TASK, ({ data, error, executionInfo }) => {
    const notificationData = JSON.parse(data.data.body);

    Notifications.scheduleNotificationAsync({
      content: {
        title: "this is a test",
        body: "another test",
        channelId: 'default',
      },
      trigger: null,
    });
  });

  Notifications.registerTaskAsync(BACKGROUND_NOTIFICATION_TASK);
```

When i apply your #31184 no notification is shown in foreground, not the empty one and also not the scheduled one - which might be excepted with your code ?

**Comment by vonovak** [comment] 2024-12-04 08:52
Hello and thanks for asking,
I apologize but this thread has become too long for me to follow, with screenshots and code snippets that don't give much context. It's not clear any more what issue is being handled.

Please open a new issue with a full runnable repro (not just code snippets) and please be very detailed in what is your expected behavior / what you want, and what instead is the behavior you see, and also include exactly how you're sending a notification from the server.
Then I'll be able to help.

Apologies and thank you for your understanding 🙂

**Closed by vonovak** 2024-12-04 08:52 UTC
Labels: Notifications, Issue accepted
