### ISSUE TITLE
Gradle re-downloads expo-modules-core dependencies again each time a new npm module is installed

### ISSUE THREAD

**Issue by robertolaru** [expo/expo#19422] opened 2022-10-05 20:03 UTC
### Summary

Using expo in a bare React Native app. Each time I install a new npm module, if I build the app for Android, Gradle starts re-downloading dependencies for `expo-modules-core`. Specifically, these are the Gradle tasks:
```
> Task :expo-modules-core:downloadBoost
Download https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz

> Task :expo-modules-core:downloadDoubleConversion
Download https://github.com/google/double-conversion/archive/v1.1.6.tar.gz

> Task :expo-modules-core:downloadFolly
Download https://github.com/facebook/folly/archive/v2021.07.22.00.tar.gz
```
The thing that really makes this a tedious problem is that Boost weighs approx. 120 MB to download.

## Reason
I believe this issue is due to the fact that when installing an npm package, npm/yarn reset all `node_modules` packages to their original "fresh install" state. Therefore, those 3 downloaded packages (located in `node_modules/expo-modules-core/android/build/downloads`) get deleted after every package install.

## Temporary workaround
A temporary workaround is to copy those 3 dependencies to another location and re-paste them when they get deleted.

### What platform(s) does this occur on?

Not Applicable

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
      Shell: 3.1.0 - /usr/bin/fish
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: AI-211.7628.21.2111.8193401
    npmPackages:
      expo: ^46.0.14 => 46.0.14 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.1 => 0.70.1 
    npmGlobalPackages:
      expo-cli: 5.4.12
    Expo Workflow: bare
```

### Minimal reproducible example

I'm using yarn.

Create a bare React Native app:
`npx react-native init RNApp`

Add expo as dependency and do the necessary configurations (manual installation, see https://docs.expo.dev/bare/installing-expo-modules/#manual-installation):
`yarn add expo`

Try running the app on Android:
`yarn run android`

When Gradle finished building, try adding another npm dependency to the project.

Run `yarn run android`. During this Gradle build, it will redownload those packages I mentioned before.

**Comment by raajnadar** [comment] 2022-10-06 09:26
You can check this forum post, once the PR is released we don't need a patch package https://forums.expo.dev/t/android-expo-sdk-46-local-eas-build-is-slow/66633

**Comment by hailiangcock** [comment] 2022-12-28 11:37
expo-modules-core   app/build.gradle has next

`def customDownloadsDir = System.getenv("REACT_NATIVE_DOWNLOADS_DIR")`

you can set  system environment variable fix it .

**Comment by Just4Ease** [comment] 2023-01-02 15:47
@hailiangcock I'm trying your suggestion now.

Also, Happy new year :)

**Comment by rafakwolf** [comment] 2023-01-03 19:45
In my case, the **downloadDoubleConversion** and **downloadFolly** downloads fail every time. I tried to cleanup npm and gradle cache, no success

**Comment by danieltgfischer** [comment] 2023-01-04 12:27
It's very annoying. I tried to create a folder and add to the path in a .env file how @hailiangcock said but without success.
Every time that I run yarn android, the build spend 10 minutes or more.

**Comment by danieltgfischer** [comment] 2023-01-05 14:02
Ok, I resolved it.

1. After downloading and building the app  go to ```node_modules\expo-modules-core\android\build\downloads```
2. Copy the folder downloads and move them to a safe folder, in my case I saved them in the android folder
3. Create a .env file and add a variable ```REACT_NATIVE_DOWNLOADS_DIR``` with the path of ```donwloads```

In my case I config like that, I'm using Windows: 
// .env file
```REACT_NATIVE_DOWNLOADS_DIR = C:\Users\<your_user>\Desktop\<your_project>\android\downloads```
Now each build takes 2 or 3 minutes.

**Comment by danieltgfischer** [comment] 2023-01-10 14:53
My steps do not resolve the problem of re-download every time you install a new lib in your project. Every time that I install a new library the project cleans the folder ```node_modules\expo-modules-core\android\build\downloads``` and then re-download starts again. 

What I do is stop the build and paste the files that I save when this folder is created by the build and restart the build, so it prevents the re-download.

Saving the path in a .env file only resolves when you do not need to install a new lib and just work on your project. 

If everyone finds a solution I would like to know.

**Comment by next6leo** [comment] 2023-01-11 06:16
why is this happening?? why is not include when npm install for expo-modules-core?

**Comment by herarya** [comment] 2023-01-11 07:22
yes same also, me takes 40 minutes, my connection also good :(

**Comment by next6leo** [comment] 2023-01-11 07:52
it redownload even i have it inside node_modules\expo-modules-core\android\build some one pls solve this issue

**Comment by git-lucky** [comment] 2023-01-17 18:01
> Ok, I resolved it.
> 
> 1. After downloading and building the app  go to `node_modules\expo-modules-core\android\build\downloads`
> 2. Copy the folder downloads and move them to a safe folder, in my case I saved them in the android folder
> 3. Create a .env file and add a variable `REACT_NATIVE_DOWNLOADS_DIR` with the path of `donwloads`
> 
> In my case I config like that, I'm using Windows: // .env file `REACT_NATIVE_DOWNLOADS_DIR = C:\Users\<your_user>\Desktop\<your_project>\android\downloads` Now each build takes 2 or 3 minutes.

Where does this .env live in relation to the project root?

**Comment by danieltgfischer** [comment] 2023-01-17 18:29
> > Ok, I resolved it.
> > 
> > 1. After downloading and building the app  go to `node_modules\expo-modules-core\android\build\downloads`
> > 2. Copy the folder downloads and move them to a safe folder, in my case I saved them in the android folder
> > 3. Create a .env file and add a variable `REACT_NATIVE_DOWNLOADS_DIR` with the path of `donwloads`
> > 
> > In my case I config like that, I'm using Windows: // .env file `REACT_NATIVE_DOWNLOADS_DIR = C:\Users\<your_user>\Desktop\<your_project>\android\downloads` Now each build takes 2 or 3 minutes.
> 
> Where does this .env live in relation to the project root?

root

**Comment by mkhib** [comment] 2023-01-22 18:19
This is so annoying. Is there anything we can do about it besides backing up the files and restoring them every time we install a new package?

**Comment by Irfanwani** [comment] 2023-01-23 05:45
I did the thing manually, downloaded the boost from https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/ and placed the downloaded zip file in node_modules\expo-modules-core\android\build\download (help from other answers, thanks for the help)

**Comment by Zeeshan404** [comment] 2023-01-23 14:10
Is this issue resolved yet? It's too annoying to download and the source of downloadBoost is also slow.

**Comment by jagamypriera** [comment] 2023-01-26 11:18
do we have solution for this?
https://github.com/software-mansion/react-native-reanimated/issues/3638 already solved it on their package

**Comment by danieltgfischer** [comment] 2023-01-26 12:07
> do we have a solution for this? [software-mansion/react-native-reanimated#3638](https://github.com/software-mansion/react-native-reanimated/issues/3638) already solved it on their package

Yes! The download finishes in less than a minute. I don't know if it's because of the update but I installed ```react-native-animated @2.11.0``` and the build was quick.

**Comment by lukmccall** [comment] 2023-02-02 17:45
It will be fixed by https://github.com/expo/expo/pull/21000. It'll be a part of the next `expo-modules-core` version.

**Closed by lukmccall** 2023-02-02 17:45 UTC
Labels: needs review, Expo Modules Core

**Comment by Irfanwani** [comment] 2023-02-05 16:20
> Is this issue resolved yet? It's too annoying to download and the source of downloadBoost is also slow.

not yet, it still downloads the boost everytime there is a change in the native code, but you can follow my steps to save some time.

**Comment by kreaeeh** [comment] 2023-02-07 16:46
The issue is still there. I have a very good connection and the server is very slow which cause a build failure

**Comment by alvinMemphis** [comment] 2023-02-15 17:54
> why is this happening?? why is not include when npm install for expo-modules-core? why https://boostorg.jfrog.io download so slow?

same .Expo team should  use another download source

**Comment by iamromec** [comment] 2023-03-18 08:22
Facing the same issue...it takes hours to complete and mostly doesn't complete at all.

Please help

<img width="685" alt="Screenshot 2023-03-18 at 1 50 04 PM" src="https://user-images.githubusercontent.com/50284628/226094278-f230d4bd-1302-4e12-b9e2-7bcf4b3e0e39.png">

**Comment by Irfanwani** [comment] 2023-03-18 08:32
> I did the thing manually, downloaded the boost from https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/ and placed the downloaded zip file in node_modules\expo-modules-core\android\build\download (help from other answers, thanks for the help)

@iamromec you can follow these steps for now

**Comment by iamromec** [comment] 2023-03-18 08:45
I've already added this file to this location bust still it tries downloads again when I run `npx expo run:android`

<img width="300" alt="Screenshot 2023-03-18 at 2 13 38 PM" src="https://user-images.githubusercontent.com/50284628/226095239-8d97c35f-e69f-4b43-9872-5d3c886ff47d.png">
<img width="673" alt="Screenshot 2023-03-18 at 2 13 42 PM" src="https://user-images.githubusercontent.com/50284628/226095242-8d4b2b45-c546-458e-bf4b-f6198f1c854f.png">

**Comment by Irfanwani** [comment] 2023-03-18 08:46
you need to do it everytime you add a new package or make any change to the native code or clean the gradle

**Comment by Irfanwani** [comment] 2023-03-18 08:49
Actually it gets removed everytime you add a new package or change the native code and build the app. Please check that again. Not sure why is it downloaded again after the changes

**Comment by iamromec** [comment] 2023-03-18 08:51
I didn't add any new packages or make changes. I simply added the file and then ran: `npx expo run:android`

And then it gets stuck at this download stage. And the server is **** slow!

**Comment by Irfanwani** [comment] 2023-03-18 08:52
can you share the file which you added?

**Comment by iamromec** [comment] 2023-03-18 08:54
boost_1_76_0.tar.gz

cannot attach here.

**Comment by Irfanwani** [comment] 2023-03-18 08:55
Oh, I don't understand why this happens. Infact, I solved this problem by doing so, by manually downloading boost_1_76_0.tar.gz and placing it in the destination folder

**Comment by iamromec** [comment] 2023-03-18 08:59
No help with this...tried.

**Comment by harsh3401** [comment] 2023-03-24 15:42
Same Issue the download begins again despite the file being present on the path

**Comment by westoque-wizest** [comment] 2023-04-07 16:43
> REACT_NATIVE_DOWNLOADS_DIR

This solution worked for me. I'm using Ubuntu/PopOS. I created the directory and re-built. Building on android is so much faster now.

```
# Create directory for react-native-downloads
mkdir $HOME/.react-native-downloads

# Set the constant in ~/.bashrc
export REACT_NATIVE_DOWNLOADS_DIR=$HOME/.react-native-downloads

# Reload ~/.bashrc with new value
source ~/.bashrc

# Run the build
yarn expo run:android

# Check the downloads dir. Downloads should be there.
ls -al ~/.react-native-downloads/
boost_1_76_0.tar.gz  double-conversion-1.1.6.tar.gz  folly-2021.07.22.00.tar.gz

# Re-build. Should be super fast.
yarn expo run:android
```

**Comment by westoque** [comment] 2023-04-07 16:44
> REACT_NATIVE_DOWNLOADS_DIR

This solution worked for me. I'm using Ubuntu/PopOS. I created the directory and re-built. Building on android is so much faster now.

```
# Create directory for react-native-downloads
mkdir $HOME/.react-native-downloads

# Set the constant in ~/.bashrc
export REACT_NATIVE_DOWNLOADS_DIR=$HOME/.react-native-downloads

# Reload ~/.bashrc with new value
source ~/.bashrc

# Run the build
yarn expo run:android

# Check the downloads dir. Downloads should be there.
ls -al ~/.react-native-downloads/
boost_1_76_0.tar.gz  double-conversion-1.1.6.tar.gz  folly-2021.07.22.00.tar.gz

# Re-build. Should be super fast.
yarn expo run:android
```

**Comment by nsexpert** [comment] 2023-06-19 01:14
@iamromec , how did you solve it ?

**Comment by dr1verrr** [comment] 2023-07-30 15:52
VPN helps a lot
