### ISSUE TITLE
'ACTION_SET_ALARM' is not exported from 'expo-intent-launcher'

### ISSUE THREAD

**Issue by jose-donato** [expo/expo#6839] opened 2020-01-23 16:55 UTC
### Environment

  Expo CLI 3.11.7 environment info:
    System:
      OS: Linux 5.0 Linux Mint 19.3 (Tricia)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.13.2 - ~/.nvm/versions/node/v12.13.1/bin/npm
    npmPackages:
      @types/react: ~16.9.0 => 16.9.19 
      @types/react-native: ~0.60.23 => 0.60.31 
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.11.7
 -->

I'm trying to target android and web.

### Steps to Reproduce

1. import * as IntentLauncher from "expo-intent-launcher";
2. IntentLauncher.startActivityAsync(IntentLauncher.ACTION_SET_ALARM);

### Expected Behavior

Open the alarm/clock app and if possible set an alarm.

### Actual Behavior

Attempted import error: 'ACTION_SET_ALARM' is not exported from 'expo-intent-launcher' (imported as 'IntentLauncher').

### Reproducible Demo
https://snack.expo.io/HyUFJ8DbU

For some reason I am not getting the same error on snack. But nothing happens as well.

**Comment by jose-donato** [comment] 2020-01-23 17:07
I saw in this [link](https://github.com/expo/expo/blob/master/packages/expo-intent-launcher/src/IntentLauncher.ts) that no action related to Alarm/Clock is exported. Is there any workaround to achieve the functionality I asked?

> Open the alarm/clock app and if possible set an alarm.

**Comment by cruzach** [comment] 2020-01-27 16:41
Depending on the behavior you're looking for, you can implement this in a couple of ways.

If you just want to notify the user of an event at a specific time, then I think setting a LocalNotification is the easiest option. see [these docs](https://docs.expo.io/versions/latest/sdk/notifications/#notificationsschedulelocalnotificationasynclocalnotification-schedulingoptions)

If you specifically want the user to set an alarm using the native clock app, then you can open that app with its specific URL, if it has one (not sure it does)

Closing this since it's not a bug report with the Expo SDK, but rather a feature request (we like to keep our feature requests here-> https://expo.canny.io/feature-requests)

**Closed by cruzach** 2020-01-27 16:41 UTC
Labels: bug
