### ISSUE TITLE
I use expoclient to scan the QR code of my published project, which is always wrong

### ISSUE THREAD

**Issue by yrjwcharm** [expo/expo#8299] opened 2020-05-14 06:17 UTC
![image](https://user-images.githubusercontent.com/34397383/81899450-70c57d00-95ed-11ea-8ffe-4ca5a7bb57d7.png)

**Comment by yrjwcharm** [comment] 2020-05-14 06:19
![image](https://user-images.githubusercontent.com/34397383/81899621-e0d40300-95ed-11ea-8c10-43a600166600.png)

**Comment by yrjwcharm** [comment] 2020-05-14 06:20
![c9020021e934638c9fe5e09740414ec8](https://user-images.githubusercontent.com/34397383/81899754-17aa1900-95ee-11ea-9ad8-6d3a27937e16.jpg)

**Comment by brentvatne** [comment] 2020-05-14 06:23
what do you see if you press “view error log”?

**Comment by yrjwcharm** [comment] 2020-05-14 07:25
![image](https://user-images.githubusercontent.com/34397383/81905175-f1d54200-95f6-11ea-8b4c-1981c77ac62c.png)
I already solve it. 


---code---

![image](https://user-images.githubusercontent.com/34397383/81905356-2cd77580-95f7-11ea-8c96-cd553b22a1f4.png)

**Comment by byCedric** [comment] 2020-05-14 11:23
Awesome, thanks for sharing the answer 😄 I can confirm that it also works for me, so I'll close this one!

**Closed by byCedric** 2020-05-14 11:23 UTC
