### ISSUE TITLE
BaseUrl reload redirects incorrect

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [expo/expo#26565] opened 2024-01-21 18:28 UTC
### Minimal reproducible example

https://github.com/rocket-meals/expo-baseUrl-reload-error

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

As described i am setting up the experimental `baseUrl` in `app.json`. In my example its named `rocket-meals`.
So as i start up the app and open the browser using `npm run deploy:local` which calls `expo export -p web`.

when i then route to `http://localhost:3000/rocket-meals/` in my case it redirects me to the login page since it is called in `(app)/_layout.js` to `return <Redirect href="/(auth)/login" />`

# The problem:
this works just fine as the url in the browser changes to `http://localhost:3000/rocket-meals/login` nice. But when i enter the url and hit enter to visit `http://localhost:3000/rocket-meals/login` it now redirects me to: `http://localhost:3000/login` but displays the correct conent. The problem is that this redirect seems wrong as it does not use the `baseUrl`
Now it comes the the critical place as i enter the url again it well tells me that this page do not exist.
Using the `expo start --web`brings the problem that the baseUrl it ommited completly.

# The second related problem
The next problem is: `let url = createURL("/login");` creates me a link without the `baseUrl` at all. 

# The third related problem
Using: `<ExternalLink href={url} style={styles.link}>` somehow creates a link with the url of the app before but only in production mode and not in dev mode.

At first visit of the page:
<img width="1988" alt="Bildschirmfoto 2024-01-21 um 19 28 08" src="https://github.com/expo/expo/assets/33295329/48673d0c-0e30-4bab-a455-e918f0548c42">

When i hit enter at the url: `http://localhost:3000/rocket-meals/login` it redirects me wrong:
<img width="1988" alt="Bildschirmfoto 2024-01-21 um 19 28 50" src="https://github.com/expo/expo/assets/33295329/bf056dcd-6a20-4a16-a9e2-320304649f76">

### Environment

    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
      Watchman: 2023.11.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 6.0.0
    Expo Workflow: managed

**Comment by NilsBaumgartner1994** [comment] 2024-01-22 11:58
I also encounter not being able to set search params when i load the specific page directly.
Might be related to: https://github.com/react-navigation/react-navigation/issues/10046

**Comment by NilsBaumgartner1994** [comment] 2024-01-22 22:58
> Tracking in [ENG-11108](https://linear.app/expo/issue/ENG-11108)

Is it correct that I can’t login there with Google ?

**Comment by NilsBaumgartner1994** [comment] 2024-01-22 23:00
Do you want me to do something ? Sorry if i did not understand that directly

**Comment by marklawlor** [comment] 2024-01-23 02:25
> Do you want me to do something ? Sorry if i did not understand that directly

No, I was just linking this issue to our internal issue tracker.

**Comment by NilsBaumgartner1994** [comment] 2024-01-23 22:49
Tested in latest version 50.0.3 problem still exists.

**Comment by NilsBaumgartner1994** [comment] 2024-02-09 15:20
Version: 50.0.6 the error still occurs

**Comment by yougikou** [comment] 2024-02-18 13:59
Do we know any work around about this? I also face the same issue. The github oauth callback url cannot work properly.

**Comment by NilsBaumgartner1994** [comment] 2024-02-18 14:02
> Do we know any work around about this? I also face the same issue. The github oauth callback url cannot work properly.

What I found that when the user clicks on the drawer to another route the url is somehow fixed. But I don’t know how we could adapt that. 

My idea would be after first start to reroute the user to the same page. But nothing tested, since a workaround is not what I like

**Comment by yougikou** [comment] 2024-02-19 12:53
@NilsBaumgartner1994 Thanks. I upgrade to 50.0.7. Yes, it is fixed now. the base url show after navigating to different page.
But I am still facing trailing slash issue that github page will automatically add / at the end of the url and it breaks expo router.
like "https://host/auth" -> https://host/auth/  and of course it will be 404 error... Of course, it is a different topic,

**Comment by NilsBaumgartner1994** [comment] 2024-02-19 12:59
> @NilsBaumgartner1994 Thanks. I upgrade to 50.0.7. Yes, it is fixed now. the base url show after navigating to different page.
> But I am still facing trailing slash issue that github page will automatically add / at the end of the url and it breaks expo router.
> like "https://host/auth" -> https://host/auth/ and of course it will be 404 error... Of course, it is a different topic,

Nice to hear, will check that out :-) can you please post the link to the follow up issue, so I can get updates on that?

**Comment by yougikou** [comment] 2024-02-19 13:10
@NilsBaumgartner1994 Oh, thanks. The follow up issue is known issue.
That github page will add / at the end because it is static site.
This is one guide 
https://github.com/slorber/trailing-slash-guide

but I follow up it to change js file name to build file align router path.
My understanding - if I have home.html in root folder, then /home will work (no slash auto add)
So, I change my homescreen.js to home.js, so metro can build a home.html for me.
But even I have home.html, it still now work. /home will be /home/
I am looking for a solution for expo web deploy to gh-page.

**Comment by NilsBaumgartner1994** [comment] 2024-02-19 13:43
> @NilsBaumgartner1994 Thanks. I upgrade to 50.0.7. Yes, it is fixed now. the base url show after navigating to different page. But I am still facing trailing slash issue that github page will automatically add / at the end of the url and it breaks expo router. like "https://host/auth" -> https://host/auth/ and of course it will be 404 error... Of course, it is a different topic,

Oh i upgraded but i am facing still the same problem: https://rocket-meals.github.io/rocket-meals

@yougikou What are your seetings at?:

```
    "experiments": {
      "typedRoutes": true,
      "baseUrl": "/rocket-meals"
    },
```

**Comment by NilsBaumgartner1994** [comment] 2024-02-19 13:45
> @NilsBaumgartner1994 Oh, thanks. The follow up issue is known issue. That github page will add / at the end because it is static site. This is one guide https://github.com/slorber/trailing-slash-guide
> 
> but I follow it to change js file name to build file align router path. My understanding - if I have home.html in root folder, then /home will work (no slash auto add) So, I change my homescreen.js to home.js, so metro can build a home.html for me. But even I have home.html, it still now work. /home will be /home/ I am looking for a solution for expo web deploy to gh-page.

Oh when i route to "home" i get "/home" and not "/home/". But yes having the slash at the end breaks with github pages.

**Comment by NilsBaumgartner1994** [comment] 2024-02-19 13:48
> @NilsBaumgartner1994 Thanks. I upgrade to 50.0.7. Yes, it is fixed now. the base url show after navigating to different page. But I am still facing trailing slash issue that github page will automatically add / at the end of the url and it breaks expo router. like "https://host/auth" -> https://host/auth/ and of course it will be 404 error... Of course, it is a different topic,

Ah yes, the baseUrl is shown after navigating to a different page, but thats not the problem. The problem is that at the first call the url changes wrong:

Opens: ".com/base/test" --> url changes to ".com/test" but shows content correctly. But this brings the problem, that we cant reload the page with that wrong url.

**Comment by yougikou** [comment] 2024-02-24 09:03
@NilsBaumgartner1994 I solve issue with below setting.
1. app.json - with this setting, navigation based on expo router will add baseUrl, basically it will solve auth callback issue.
  "expo": {
    "web": {
      "basePath": "**baseurl**"

BUT, when refresh the page, it still will delete base url, and with second refresh it will show 404 error

2. For refresh issue, I added below redirect element on each route destination screen, finally everything seems fine.
```
import React from 'react';
import { Redirect } from 'expo-router';

const Redirector = () => {
  if (process.env.NODE_ENV === 'production') {
    const currentPath = window.location.pathname;
    if (!currentPath.startsWith("/baseurl")) {
      const newPath = `/baseurl/${currentPath}`;
      return <Redirect href={newPath} />;
    }
  }
  return null
};

export default Redirector;
```

**Comment by NilsBaumgartner1994** [comment] 2024-02-27 23:35
> @NilsBaumgartner1994 I solve issue with below setting.
> 
>     1. app.json - with this setting, navigation based on expo router will add baseUrl, basically it will solve auth callback issue.
>        "expo": {
>        "web": {
>        "basePath": "**baseurl**"
> 
> 
> BUT, when refresh the page, it still will delete base url, and with second refresh it will show 404 error
> 
>     2. For refresh issue, I added below redirect element on each route destination screen, finally everything seems fine.
> 
> 
> ```
> import React from 'react';
> import { Redirect } from 'expo-router';
> 
> const Redirector = () => {
>   if (process.env.NODE_ENV === 'production') {
>     const currentPath = window.location.pathname;
>     if (!currentPath.startsWith("/baseurl")) {
>       const newPath = `/baseurl/${currentPath}`;
>       return <Redirect href={newPath} />;
>     }
>   }
>   return null
> };
> 
> export default Redirector;
> ```

It sadly breaks when my user redirects to another screen. The url then gets compromised: `http://localhost:3000/rocket-meals/undefined/rocket-meals/housing`

**Comment by msamirma** [comment] 2024-03-07 10:23
Hi @marklawlor I saw that you already worked on PR for this issue, Do you know when it will be available?

**Comment by NilsBaumgartner1994** [comment] 2024-05-23 00:05
Is this completed or still open @marklawlor ?

**Closed** 2024-06-01 12:34 UTC
Labels: Issue accepted, Router

**Comment by tmricardo7** [comment] 2024-06-12 16:45
@NilsBaumgartner1994 Were you able to see a fix for this?

**Comment by adr-iova** [comment] 2024-10-29 11:57
> Yes

any details on how?

**Comment by samtsai** [comment] 2024-11-21 19:42
@NilsBaumgartner1994 could you share what resolved the issue for you?

**Comment by obsidianart** [comment] 2024-11-26 01:05
following

**Comment by marklawlor** [comment] 2024-11-26 02:29
If you still have this issue please open a new ticket with a reproduction of your issue. While you may have the same symptoms, we cannot identify if its the same or a new issue unless you create an issue report.
