### ISSUE TITLE
RSA decrypt huge performance drop after updating from SDK 47 to 50

### ISSUE THREAD

**Issue by ArtoszBart** [expo/expo#27818] opened 2024-03-22 22:04 UTC
### Minimal reproducible example

https://github.com/ArtoszBart/expo-rsa-issue

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

I was developing mobile app with expo 47.0.0, and debugging with Expo Go on my iPhone 13 Pro Max. One day my phone decided to update Expo Go, and then i was not able to run my app. I have upgrated project to SDK 50.0.14, and then problem appeared.

With SDK 47, decrypting single message took 0.6-0.7 seconds, whereas with SDK 50, it takes almost 5 seconds!!!

I did even tried changing jsencrypt to node-forge, to check if it's package fault - but no.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.14.1 - D:\Software\NodeJS\node.EXE
      npm: 9.3.1 - D:\Software\NodeJS\npm.CMD
    npmPackages:
      expo: ~50.0.14 => 50.0.14
      react: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by byCedric** [comment] 2024-03-23 23:38
Hi @ArtoszBart, thanks for reporting the issue. If it was faster in SDK 47, and you did not change the JS engine, it's likely that the JS code is executing significantly slower on Hermes compared to JSC. Since SDK 47's default engine was still JSC, and SDK 50's default engine is Hermes.

I think there are two options here:
1. You can try switching your SDK 50 project to JSC to see if the performance improves a bit ([docs](https://docs.expo.dev/versions/latest/config/app/#jsengine)). This would also help confirming this.
2. Algorithms like these are faster executed natively. You could try running RSA natively and see the performance comparison. Something like [`react-native-fast-rsa`](https://github.com/jerson/react-native-fast-rsa) could be interesting to try. _(Note, you can't use this library in Expo Go since it contains native code, use an [Expo dev build](https://docs.expo.dev/develop/development-builds/introduction/) instead.

Hope this helps!

**Comment by ArtoszBart** [comment] 2024-03-24 20:37
Ok, so far I've managed to prebuild and switched SDK 50 to JSC as you mentioned in point one.

The performance has indeed increased to the level from SDK 47 (0.6-0.7s), but only while debugging on the iOS simulator. While debugging via Expo Go, the result is the same, which is frustrating since I have to wait a few minutes for decryption every time I reload JS.

However, the most significant issue arises when I use eas build -p ios. After uploading the .ipa file to TestFlight and running it on my iPhone, the load time increases again to almost 5 seconds, despite configuring "expo.jsEngine": "jsc" in Podfile.properties.json.

**Comment by brentvatne** [comment] 2024-03-30 18:27
@ArtoszBart - can you share a link to your build page so I can investigate? my guess is that your build is not actually using JSC (perhaps it's a bare project, where configuring in app.json is not sufficient, or something else), and what you're experiencing here is likely a regression in performance somewhere in Hermes

**Comment by brentvatne** [comment] 2024-04-06 00:15
@ArtoszBart - i'll close this issue for now, if you get back to us with more information it would be useful

**Closed by brentvatne** 2024-04-06 00:15 UTC
Labels: Android, iOS
