### ISSUE TITLE
Can anyone change StatusBar backgroundColor?

### ISSUE THREAD

**Issue by niawinter** [expo/expo#6270] opened 2019-11-14 14:49 UTC
Hi everyone,

it seems **backgroundColor** property of StatusBar doesn't work, in expo snack too.
Please check: https://snack.expo.io/@niawinter/statusbar_backgroundcolor

What do i wrong?

Properties **barStyle**, **hidden** and **translucent** work well.

**Comment by cruzach** [comment] 2019-11-14 18:57
Closing as a duplicate of https://github.com/expo/expo/issues/2813

A good workaround for this is to configure status bar through app.json, just add

```
"androidStatusBar": {
      "backgroundColor": "#ffc0cb"
    },
```
to app.json (although you'll need to run your project locally for that)

**Closed by cruzach** 2019-11-14 18:57 UTC

**Comment by niawinter** [comment] 2019-11-15 14:16
> Closing as a duplicate of #2813
> 
> A good workaround for this is to configure status bar through app.json, just add
> 
> ```
> "androidStatusBar": {
>       "backgroundColor": "#ffc0cb"
>     },
> ```
> 
> to app.json (although you'll need to run your project locally for that)

Hi @cruzach , thanks for your reply. I tried to change app.json, but nothing has changed, backgroundColor prop still inactive

**Comment by niawinter** [comment] 2019-11-15 14:49
I restarted all, and now it works well. Thanks again!
