### ISSUE TITLE
Android apk Release build crash.

### ISSUE THREAD

**Issue by ektasahu027** [expo/expo#7336] opened 2020-03-11 09:31 UTC
![Screenshot 1398-12-21 at 14 58 56](https://user-images.githubusercontent.com/41745899/76402245-28010600-63a9-11ea-9b62-e8495bfb683d.png)

**Comment by cruzach** [comment] 2020-03-11 21:33
Closing since this isn't a valid bug report. If you'd like to report a bug, please fill out the entire github bug report template, and provide a reproducible demo

**Closed by cruzach** 2020-03-11 21:33 UTC
