### ISSUE TITLE
ReferenceError: Can't find variable: Expo

### ISSUE THREAD

**Issue by morghan102** [expo/expo#13758] opened 2021-07-23 23:22 UTC
### Summary

on expo start, I'm getting this error.
I recently updated my expo from 39, so I beleive this is the reason for it. I see no way to resolve except to downgrade.

![Screenshot from 2021-07-23 15-14-51](https://user-images.githubusercontent.com/48462502/126849776-c422ef30-ad93-4dea-afe6-a8792c349415.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (4.8.1).                 │
│   You are currently using expo-cli 4.7.3                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘

  Expo CLI 4.7.3 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.9.0 - ~/.nvm/versions/node/v14.9.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.9.0/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v14.9.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: 4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

start with expo version 39. Upgrade to 42.

**Comment by cruzach** [comment] 2021-07-26 14:14
Closing because no reproducible demo was provided- we can re-open if you do provide it. Maybe you are importing `Expo` somewhere (which is deprecated in favor of the individual packages now, and has been for some time), so you should search your project for that (check the files from your stack trace)

**Closed by cruzach** 2021-07-26 14:14 UTC
Labels: needs review
