### ISSUE TITLE
android: font loading doesn't work directly

### ISSUE THREAD

**Issue by inyono** [expo/expo#111] opened 2017-04-15 04:38 UTC
When previewing a CRNA on Android, fonts aren't displayed after their `loadAsync` (although react-native does not complain that the font does not exist). It works fine after some time, though (probably after restarting Expo / the app / the packager). We only have this issue on Expo for Android, iOS works fine.

**Comment by dikaiosune** [comment] 2017-04-15 16:59
cc @nikki93 

Presumably you're `await`ing on the loadAsync call? Do you have a small demo for this, maybe on snack.expo.io?

**Comment by inyono** [comment] 2017-04-15 20:03
> Presumably you're awaiting on the loadAsync call?

Yes, I am.

> Do you have a small demo for this?

Yes, that's basically the code in our app (simplified): https://snack.expo.io/Bk1U2llCg. Although I don't know how require a font in Snack.

**Comment by nikki93** [comment] 2017-05-08 20:51
@inyono What's the font file you are trying to use? May be an issue with that particular one and I could try.

**Comment by inyono** [comment] 2017-05-09 01:01
@nikki93 [serlo.ttf](https://github.com/serlo-org/serlo-abc/blob/master/src/assets/fonts/serlo.ttf) and [norddruck.ttf](https://github.com/serlo-org/serlo-abc/blob/master/src/assets/fonts/norddruck.ttf)

**Comment by danielweinmann** [comment] 2017-05-19 11:39
Hey, @inyono, did you solve this issue? I'm having the same problem here with custom fonts on Android.

**Comment by danielweinmann** [comment] 2017-05-19 11:48
Sorry, my bad. I was using a `fontWeight` that wasn't present in the font. Working like a charm now!

**Comment by inyono** [comment] 2017-05-19 13:42
Nope, unfortunately not. Though it is not really an issue for us since it works the second time ;)

**Comment by nikki93** [comment] 2017-05-23 22:48
Will try to hit this for next SDK cycle.

**Comment by nikki93** [comment] 2017-05-24 19:55
@inyono when you get a chance, could you jump on our slack at http://slack.expo.io and ping me (I'm 'nikki' on there)? May be a quicker way to communicate.

**Comment by nikki93** [comment] 2017-06-02 02:54
@inyono https://github.com/nikki93/custom-font-test tried both fonts on this and they seem to work. The 'serlo' font looks a bit weird though, maybe it has to do with the format of the '.ttf' file?

**Comment by inyono** [comment] 2017-06-02 12:55
It worked for us after restarting Expo. So no, we don't really have this issue now anymore, but we had it again when we imported the second font. Probably super hard to debug (and maybe not an issue in the new Expo versions anymore)

**Comment by nikki93** [comment] 2017-06-02 22:51
Ok I will close this for now since I'm not able to reproduce at all too. Totally feel free to make a new one or ping me on Slack to reopen if this happens reproducably!

**Closed by nikki93** 2017-06-02 22:51 UTC
Labels: Status: Needs More Info, Status: Pending, Type: Bug
