### ISSUE TITLE
[ios] Notifications.getDevicePushTokenAsync() does not resolve in bare workflow

### ISSUE THREAD

**Issue by Speedy1991** [expo/expo#8757] opened 2020-06-10 12:33 UTC
Looks related to #8084 which should have fixed this bug

```
"expo-notifications": "0.3.2",
"expo-permissions": "8.1.0",
"react-native-unimodules": "0.9.1",
```

Pods:
```
pod install
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Detected React Native module pods for RNCAsyncStorage, RNCMaskedView, RNDateTimePicker, RNDeviceInfo, RNFBAnalytics, RNFBApp, RNFBInAppMessaging, RNFBPerf, RNGestureHandler, RNReanimated, RNSVG, RNScreens, RNSentry, react-native-safe-area-context, and rn-fetch-blob
Installing unimodules:
 expo-application@2.2.1 from ../node_modules/expo-application/ios
 expo-av@8.1.0 from ../node_modules/expo-av/ios
 expo-constants@9.1.1 from ../node_modules/expo-constants/ios
 expo-file-system@8.1.0 from ../node_modules/expo-file-system/ios
 expo-font@7.0.0 from ../node_modules/expo-font/ios
 expo-image-loader@1.0.1 from ../node_modules/expo-image-loader/ios
 expo-in-app-purchases@8.1.0 from ../node_modules/expo-in-app-purchases/ios
 expo-keep-awake@8.1.0 from ../node_modules/expo-keep-awake/ios
 expo-linear-gradient@7.0.0 from ../node_modules/expo-linear-gradient/ios
 expo-localization@8.1.0 from ../node_modules/expo-localization/ios
 expo-notifications@0.3.2 from ../node_modules/expo-notifications/ios
 expo-permissions@8.1.0 from ../node_modules/expo-permissions/ios
 expo-web-browser@8.2.0 from ../node_modules/expo-web-browser/ios
 unimodules-app-loader@1.0.2 from ../node_modules/unimodules-app-loader/ios
 unimodules-barcode-scanner-interface@5.1.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
 unimodules-camera-interface@5.1.0 from ../node_modules/unimodules-camera-interface/ios
 unimodules-constants-interface@5.1.0 from ../node_modules/unimodules-constants-interface/ios
 unimodules-core@5.1.2 from ../node_modules/@unimodules/core/ios
 unimodules-face-detector-interface@5.1.0 from ../node_modules/unimodules-face-detector-interface/ios
 unimodules-file-system-interface@5.1.0 from ../node_modules/unimodules-file-system-interface/ios
 unimodules-font-interface@5.1.0 from ../node_modules/unimodules-font-interface/ios
 unimodules-image-loader-interface@5.1.0 from ../node_modules/unimodules-image-loader-interface/ios
 unimodules-permissions-interface@5.1.0 from ../node_modules/unimodules-permissions-interface/ios
 unimodules-react-native-adapter@5.2.0 from ../node_modules/@unimodules/react-native-adapter/ios
 unimodules-sensors-interface@5.1.0 from ../node_modules/unimodules-sensors-interface/ios
 unimodules-task-manager-interface@5.1.0 from ../node_modules/unimodules-task-manager-interface/ios
Found some duplicated unimodule packages. Installed the ones with the highest version number.
Make sure following dependencies of your project are resolving to one specific version:
 expo-constants
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 71 dependencies from the Podfile and 94 total pods installed.

```
Example code:
```
try {
  const settings = await Notifications.getPermissionsAsync()
  console.log('SETTINGS', settings)
  console.log('REQUEST TOKEN')
  const {data: token} = await Notifications.getDevicePushTokenAsync() // << STUCK
  console.log('TOKEN TOKEN', token)
} catch (err) {
  console.log('ERROR', err)
}
```

Output:
```
[Wed Jun 10 2020 14:19:14.570]  LOG      SETTINGS {"canAskAgain": true, "expires": "never", "granted": true, "ios": {"alertStyle": 1, "allowsAlert": true, "allowsBadge": true, "allowsCriticalAlerts": null, "allowsDisplayInCarPlay": null, "allowsDisplayInNotificationCenter": true, "allowsDisplayOnLockScreen": true, "allowsPreviews": 1, "allowsSound": true, "providesAppNotificationSettings": false, "status": 2}, "status": "granted"}
[Wed Jun 10 2020 14:19:14.572]  LOG      REQUEST TOKEN
```

- Wifi is up and running
- Permission is already granted
- No error is thrown

**Comment by martinezguillaume** [comment] 2020-06-11 21:41
Same problem here !q

**Comment by Speedy1991** [comment] 2020-06-15 06:18
Thanks for the hint @martinezguillaume 

Unfortunately, this doesn't work for me :/ still stuck at the async call

**Comment by martinezguillaume** [comment] 2020-06-15 06:52
@Speedy1991 are you sure you enable notification push capability in your Xcode project ? Sometimes we forgot this

**Comment by Speedy1991** [comment] 2020-06-15 06:59
> (This issue happened again with another phone, I juste rebooted and it worked, maybe try with another phone ?)

Only have one dev phone :/ - next I'll create a testflight build and check if the error persists on a released build - if it's working in the production environment I'm convinced it's a dev/cache problem

>are you sure you enable notification push capability in your Xcode project ? Sometimes we forgot this

Yes - I switched from [react-native-firebase notifications (5.x.x)](https://v5.rnfirebase.io/docs/v5.x.x/notifications/introduction) because support is dropped for local notifications in ^6.x.x. Everything was working fine.

**Comment by AdamJNavarro** [comment] 2020-06-15 20:38
Hey all, if someone could provide us a reproducible example of this it would be very appreciated so that we can further investigate on our end.

**Comment by VadimCpp** [comment] 2020-06-26 13:26
In my expo project same issue.
It works perfect during testing in expo app.
Only in release mode is does not work:
registerForPushNotificationsAsync never back  

Reproducible source:
https://github.com/VadimCpp/events4friends-mobile/blob/fix/92_push_notifications/App.tsx#L20

**Comment by jamesholcomb** [comment] 2020-09-25 22:44
I am experiencing the same issue as well for iOS 13. `getDevicePushTokenAsync` never returns using bare workflow.

"react-native-unimodules": "0.11.0",
"expo-notifications": "0.7.2",

From the doc

> In the bare workflow, you'll need to use the expo credentials:manager command to upload your push notification credentials to Expo's servers 

Is that step really necessary if my app does not need to _send_ push notifications?  Sending of PNs happens on the backend.

Also:

> Make sure your ios.bundleIdentifier key in app.json is set.

My understanding was that app.json is not used in bare workflow?

**Comment by jonathanstiansen** [comment] 2020-09-27 18:54
You will definitely have to still follow those steps. It's because you are registering with Expos push servers, unless you are totally not using expos push service then you'll have to. App.Json is used for expo updates and some related stuff. Specifically the bundle is one of the few things required.

**Comment by sjchmiela** [comment] 2020-10-01 16:24
Hey all, let me try to respond to mentioned issues one by one:

### `getDevicePushTokenAsync` never resolves

1. Sometimes it may take long time for app (iOS system) to register at Apple servers in which case the Promise may not fulfil for sometime. See [this StackOverflow answer](https://stackoverflow.com/a/34332047/1123156). Please try etc. switching off your Wi-Fi connection.
2. If it doesn't resolve… maybe it rejects? Ensure that you're listening for exceptions and logging them appropriately.

### When do I need to upload push notification credentials to Expo servers?

One needs to upload push notification credentials to Expo servers if and only if one wants to send push notifications to your app via Expo servers (which I seriously recommend). If you have your own backend communicating with APNS/FCM you probably don't need to upload credentials to Expo (you've already uploaded them to your backend). [This guide](https://docs.expo.io/push-notifications/sending-notifications-custom/) explains how to send notifications yourself.

However, if you plan to use `getExpoPushTokenAsync` (to retrieve Expo push token) and Expo servers to send notifications (see [this guide](https://docs.expo.io/push-notifications/sending-notifications/)), ensure you have the credentials set up properly (otherwise Expo server cannot authorize notification at Apple/Firebase servers).

### Do I need to set `ios.bundleIdentifier` in bare workflow?

No, you don't need to in order to use `expo-notifications` properly.

### Arguments to `getDevicePushTokenAsync`

As [the documentation states](https://docs.expo.io/versions/latest/sdk/notifications/#getdevicepushtokenasync-devicepushtoken), `getDevicePushTokenAsync` does not accept/use any arguments.

**Comment by sjchmiela** [comment] 2020-10-22 15:53
I'll let myself close this issue tentatively, hopefully believing my previous answer cleared all the misconceptions. If not, please feel free to reopen this issue or open a new one. 🙂

**Closed by sjchmiela** 2020-10-22 15:53 UTC
Labels: Bare Workflow, Notifications, iOS, needs repro

**Comment by CyrilEngineering** [comment] 2024-09-08 13:52
I'm encountering this on Ventura with xcode 15.2 and simulator 17.2. 

I was certain to dig through every link and component referenced [here](https://docs.expo.dev/versions/latest/sdk/notifications/)
- getDevicePushTokenAsync hangs indefinitely
- requestPermissionsAsync stated configuration is ignored as requested [here](https://docs.expo.dev/versions/latest/sdk/notifications/#requestpermissionsasyncpermissions)

Tested on Android and iOS hardware. Is simulator NA, the docs are hard to interpret for this nuance. Notifications or registration and notifications?: "Check out the example Snack below to see Notifications in action, make sure to use a physical device to test it. Push notifications don't work on emulators/simulators."

**Comment by scarlac** [comment] 2024-11-27 01:43
I have just debugged this, and the resolution is fairly straight forward.  
If you have this issue you may need to disable Firebase. Expo and Firebase cannot both register as push notification handling libraries. Expo only registers itself explicitly via JS calls, but Firebase does it automatically when your app starts and calls `[FIRApp configure]` in your `AppDelegate.mm` file.

The following code is the hang:
![image](https://github.com/user-attachments/assets/053c42fe-f600-4faf-99b3-b6db10bd46df)


The call to `registerForRemoteNotifications` never triggers Expo's own delegate (callback methods), instead it triggers Firebase's delegate, which means Expo never resolves the promise - ie. it hangs. There are a multitude of ways you can work around this, but you should probably consider disabling Firebase's "Swizzling" functionality, which is what is overwriting Expo's callbacks. This is done in 2 steps:

1. Disable Firebase's "Swizzling" in your `ios/Info.plist` file to include:  
   ```
   <key>FirebaseAppDelegateProxyEnabled</key>
   <false/>
   ```
2. Disable Firebase's automatic registration in your root `firebase.json` file, add the following:
   ```
   {
     "$schema": "./node_modules/@react-native-firebase/app/firebase-schema.json",
     "react-native": {
       "messaging_ios_auto_register_for_remote_messages": false /* add this */
     }
   }
   ```

Expo would ideally auto-detect this situation by checking if the delegate is itself when calling register. If not, it should issue a warning.
