### ISSUE TITLE
[SDK 52] - NativeBase Input not working on iOS

### ISSUE THREAD

**Issue by ThiagoMunich** [expo/expo#32907] opened 2024-11-14 12:52 UTC
### Minimal reproducible example

https://github.com/ThiagoMunich/Input

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

I'm working with NativeBase on a current project and I noticed that Input component it's not working on iOS (even on real device).

I created a new project from scratch to test, which is the one on the minimal example, and it didn't work as well. See the video below.

https://github.com/user-attachments/assets/4947cf87-f1b4-4219-b71c-3a0655d48074

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.1/bin/yarn
      npm: 10.8.2 - ~/.nvm/versions/node/v20.15.1/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.6 => 52.0.6 
      expo-router: ~4.0.5 => 4.0.5 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.2.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Validate packages against React Native Directory package metadata
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by 504knight** [comment] 2024-11-14 19:47
Also experiencing this same issue. However, in my case the keyboard seems to start to open and then immediately close.

**Comment by 504knight** [comment] 2024-11-14 21:41
Interestingly enough this only occurs if I run the app via Expo Go or do a Development build. If I do a preview build with the `eas cli` then the inputs work as expected

**Comment by 504knight** [comment] 2024-11-14 22:59
And as a follow up to my last comment, when I set `newArchEnabled: false` it started to work on Development builds. Looks like this must have something to do with the new architecture.

**Comment by AndranikT** [comment] 2024-11-15 06:46
What is happen ?? I have same problem with Input from "native-base" but "textInput" from "ract-native" is correctly working.
Who can tell me how resolve ??? @ThiagoMunich @504knight ,,,

**Comment by brentvatne** [comment] 2024-11-15 20:23
nativebase is not maintained anymore, the authors have moved on to another library called gluestack-ui

<img width="1239" alt="image" src="https://github.com/user-attachments/assets/240dbcd0-2d98-43f7-b3ef-0f7630624ab6">

i'd recommend following any migration advice that they provide

that said, this looks like something we could follow up on to find why we are observing this with new arch only

**Comment by Wei102193** [comment] 2024-11-15 22:32
i mean bro, nativebase is trash, get rid of it

**Comment by brentvatne** [comment] 2024-11-15 22:51
@ThiagoMunich @504knight @AndranikT @spenavajr  - what would be incredibly helpful here is for one of you to dig into what exactly is the root cause here. you can do this by going into your node_modules and modifying things in nativebase, removing pieces until the textinput is working as expected with the react-native textinput. then if you can reproduce this in a new app without nativebase, i'm sure we could send a pr to react-native to fix the underlying issue (assuming that is indeed an issue there, it's possible that nativebase was depending on previously incorrect behavior). patching nativebase itself at this point seems unlikely to happen because it is not maintained and hasn't been for a year.

**Comment by brentvatne** [comment] 2024-11-19 22:45
whenever we have a minimal reproducible example, folks on the expo team and the react-native team at meta can investigate!

**Comment by AndranikT** [comment] 2024-11-20 20:01
Dear @brentvatne  I agree with you,, but at this time I am in production of my app and meeting with this bug I am very angry. because I use "native-base" in my app. Can you help me how can I resolve this with bypassing or changing the library․․․․I don't have big experience with "mobile" development and this app is a first work with mobile devices.

**Comment by brentvatne** [comment] 2024-11-20 20:13
@AndranikT - your options:

- use sdk 51
- use old architecture

in either case, you should be using a dev build. see: https://expo.fyi/expo-go-usage

**Comment by edgarscr** [comment] 2024-12-06 01:30
+1

**Comment by brentvatne** [comment] 2024-12-06 02:11
@ThiagoMunich - you can move out of Expo Go and disable the new architecture in a development build: https://docs.expo.dev/guides/new-architecture/#disable-the-new-architecture-in-an-existing-project

it isn't a good longterm solution to disable the new architecture, but it is definitely good to move away from expo go. https://expo.fyi/expo-go-usage

**Comment by brentvatne** [comment] 2024-12-06 02:12
closing this thread because nativebase is unmaintained and nobody has provided a way to reproduce this without nativebase. 

to resolve this issue for your app, see:
- https://github.com/expo/expo/issues/32907#issuecomment-2489459056
- https://github.com/expo/expo/issues/32907#issuecomment-2521933931

**Closed by brentvatne** 2024-12-06 02:12 UTC
Labels: needs review
