### ISSUE TITLE
Crash in InAppPurchases.getProductsAsync when product is Apple rejected

### ISSUE THREAD

**Issue by billychasen** [expo/expo#6858] opened 2020-01-25 14:03 UTC
If Apple rejects a product, InAppPurchases.getProductsAsync will crash.

Steps to reproduce:
- Create a non-consumable product (I don't know if it needs to be that type, just mine was).
- Have Apple reject it.
- Try to call InAppPurchases.getProductsAsync.

The crash appears to be deep inside the library. A javascript try/catch around the call did not prevent the crash.

I was able to fix it by creating a new product with a fresh product id.

**Comment by cruzach** [comment] 2020-01-27 20:59
Is this with the most recent SDK? It's a little easier to debug in this scenario since you're in the bare workflow and you can poke around into the native iOS code to see exactly where the error is getting thrown

**Comment by billychasen** [comment] 2020-01-27 23:54
sdk 36.0.0. I removed the items and made them with new ids so I could continue with the appreview process. unfortunately that killed any debugging.

**Comment by Phillip-Cognativ** [comment] 2020-02-27 04:17
This is definitely a real problem. This happened to me with an auto-renewing subscription.

After the product is rejected any calls to `getProductsAsync` crash with the following error:

```
NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
```

**Comment by GeoffAbbott** [comment] 2020-03-20 20:06
Same issue getProductsAsync crashes app after product has been rejected.

Initialize gesture handler for root view <RCTRootContentView: 0x10779a720; reactTag: 1; frame = (0 0; 375 812); gestureRecognizers = <NSArray: 0x282ba8720>; layer = <CALayer: 0x282518b20>>
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by GeoffAbbott** [comment] 2020-03-20 21:32
Quick fix for me was to make a small modification to the getProductData

not sure why but product.localizedTitle causes the app to crash. I didn't really dig to deep into but rejected products can be purchased now and doesn't crash the app when your on the phone with the review team lol.

EXInAppPurchasesModule.h

- (NSDictionary *)getProductData:(SKProduct *)product
{
  // Use with caution: P0D also implies non-renewable subscription.
  NSString *subscriptionPeriod = [self getSubscriptionPeriod:product];
  NSNumber *type = [subscriptionPeriod isEqualToString:kEXInAppSubPeriod] ? @(0) : @(1);
  
  NSDecimalNumber *oneMillion = [[NSDecimalNumber alloc] initWithInt:1000000];
  NSDecimalNumber *priceAmountMicros = [product.price decimalNumberByMultiplyingBy:oneMillion];
  NSString *price = [NSString stringWithFormat:@"%@%@", product.priceLocale.currencySymbol, product.price];
  NSString *description = product.localizedDescription ?: @"";
  NSString *title = product.localizedTitle ?: @"";
  
  return @{
           @"description": description,
           @"price": price,
           @"priceAmountMicros": priceAmountMicros,
           @"priceCurrencyCode": product.priceLocale.currencyCode,
           @"productId": product.productIdentifier,
           @"subscriptionPeriod": subscriptionPeriod,
           @"title": title,
           @"type": type
           };
}

**Comment by TristanH** [comment] 2020-04-15 22:44
Just ran in to this exact issue on version `8.1.0`

Same error as @Phillip-Cognativ above.

**Comment by pearup** [comment] 2020-04-26 12:52
I can confirm that I ran into this problem as well. The app started crashing after apple reject. Then they approved it so I lost the repo. But it's still very concerning.

**Comment by patrick-gleeson** [comment] 2020-04-29 09:15
Has happened to us several times recently, both with subscription products and consumables.

**Comment by Strate** [comment] 2020-05-01 06:36
The origin error is:
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[6]'
```

https://github.com/expo/expo/blob/master/packages/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m#L340

product.localizedTitle is nil

**Comment by whusterj** [comment] 2020-07-15 18:41
FWIW, we also just encountered this issue. It may be tied to the app being rejected (ours just was) or it may be that there is a new payments agreement that needs to be accepted. We are seeing the following in AppStore Connect:

<img width="959" alt="Screen Shot 2020-07-15 at 2 29 31 PM" src="https://user-images.githubusercontent.com/1354713/87582781-ebbc1a00-c6a8-11ea-9532-d70e33d8edca.png">

Note the error message "An in-app purchase has been returned..." I am not sure what 'returned' means in this context.

When attempting to create a new product this pop-up appears:

<img width="630" alt="Screen Shot 2020-07-15 at 2 31 10 PM" src="https://user-images.githubusercontent.com/1354713/87582910-17d79b00-c6a9-11ea-88e5-46e51f13e2e8.png">

Same error message shown in XCode as reported by others:

    Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[6]'

**Comment by swider** [comment] 2020-07-21 22:56
This happened to me when at least one of the products passed to `getProductsAsync` is in 'Developer Action Needed' and after that rejected product had been fixed and was back in 'Waiting for Review'. It does not happen with an empty array, or, obviously, when all the products passed in are in 'Ready to Submit', 'Waiting for Review' the first time, or 'Approved'.

Had to recreate the products.

**Comment by jasontproject** [comment] 2020-08-24 17:05
I just set up [patch-packages](https://www.npmjs.com/package/patch-package) in my project and fixed this. Here is my patch file, thanks @Strate:
```
diff --git a/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m b/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m
index 3ef03cc..9c00048 100644
--- a/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m
+++ b/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m
@@ -324,6 +324,7 @@ - (NSDictionary *)getProductData:(SKProduct *)product
   NSDecimalNumber *priceAmountMicros = [product.price decimalNumberByMultiplyingBy:oneMillion];
   NSString *price = [NSString stringWithFormat:@"%@%@", product.priceLocale.currencySymbol, product.price];
   NSString *description = product.localizedDescription ?: @"";
+  NSString *title = product.localizedTitle ?: @"";
 
   return @{
            @"description": description,
@@ -332,7 +333,7 @@ - (NSDictionary *)getProductData:(SKProduct *)product
            @"priceCurrencyCode": product.priceLocale.currencyCode,
            @"productId": product.productIdentifier,
            @"subscriptionPeriod": subscriptionPeriod,
-           @"title": product.localizedTitle,
+           @"title": title,
            @"type": type
            };
 }
```

**Comment by bharadwajsampath** [comment] 2020-09-04 07:10
Thanks a lot @jasontproject , this solution worked for me. But I am still trying to figure out why the title of the products are coming empty after the app has been rejected. Now instead of relying on the titles from the appstore , I use the product Ids to map the titles which makes it more flexible for me.

**Comment by jeloagnasin** [comment] 2020-09-11 08:22
I've tried adding a new localization and that worked for me. I didn't have to patch the expo iap module.

**Comment by patrick-gleeson** [comment] 2020-09-11 08:39
@jeloagnasin what you'll find is that if your IAPs are rejected again, your app will crash again when it tries to load them, until you change the localization again. Tweaking localizations every time is a workaround, for sure, but only a temporary one.

**Comment by jeloagnasin** [comment] 2020-09-11 22:30
That's true 😢 I hope the expo team can get this patched soon.

**Comment by FrenchBully** [comment] 2020-11-25 18:29
any progress on this issue? I'm experiencing this very thing and probably caused tons of people ripping out their hair trying to sort this out.

**Comment by Strate** [comment] 2020-11-25 18:31
@FrenchBully use advice from comment here: https://github.com/expo/expo/issues/6858#issuecomment-679251209

This is most straightforward way to resolve issue

**Comment by ARMATAV** [comment] 2021-01-15 22:11
Yes, my hair was ripped out with this as well - upon rejection of app this will throw an exception

**Comment by jaquan1227** [comment] 2021-06-22 08:43
I solve this problem by updating in app purchase item's display name . 
after updating the name, just save the item. after few minutes, it will work :)

**Comment by cruzach** [comment] 2021-08-03 21:22
Looks like this was fixed by https://github.com/expo/expo/pull/11523 but never closed, so I'm closing it now. Lmk if you're still seeing this issue!

**Closed by cruzach** 2021-08-03 21:22 UTC
Labels: InAppPurchases, bug, iOS
