### ISSUE TITLE
Bad Gateway (502) errors for push notifications.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [expo/expo#7189] opened 2020-02-26 06:27 UTC
## 🐛 Bug Report

Not sure if the repo is the appropriate place to report continued issues with the Expo service... This may be related to a [push notification availability](https://status.expo.io/incidents/zq8b8mk26h5r) incident, except it says it's resolved but we're still seeing issues...

### Environment

```
  Expo CLI 3.2.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.0.11 - /usr/local/bin/bash
    Binaries:
      Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.0
```

### Steps to Reproduce

Send a push notification via the exponent-server-sdk for Ruby gem.

### Expected Behavior

It sends a push notification.

### Actual Behavior

Getting a Bad Gateway 502 error.

![image](https://user-images.githubusercontent.com/5187404/75317740-91b3d880-581d-11ea-9c7b-246f97894400.png)

This started happening at the time the incident occurred, and hasn't gone away since then.

### Reproducible Demo

Might be able to put something together, but I'm curious if you're seeing issues on the backend first?

**Comment by AndrewSouthpaw** [comment] 2020-02-26 06:39
Or, I'll get a 504 Gateway timeout.

![image](https://user-images.githubusercontent.com/5187404/75318650-bd37c280-581f-11ea-9f31-201ed7ee2933.png)

**Comment by cruzach** [comment] 2020-02-26 16:41
Hi! We did have an incident last night, which last about 15 minutes, where users were seeing an elevated error rate of push notifications- see more details here https://status.expo.io/incidents/zq8b8mk26h5r

Everything is back up and operational, but if you're still seeing these errors then please let me know! 

Closing since this should be resolved now

**Closed by cruzach** 2020-02-26 16:41 UTC
Labels: bug

**Comment by AndrewSouthpaw** [comment] 2020-02-27 00:26
Hi @cruzach, thanks for the response. I was aware of the incident, and did link to it in the original post. It happened at 3 PM PST, we continued seeing errors around 10pm PST, and thus I was letting you know. :-)

If there's a more appropriate place to check in on operational issues I'm happy to take the issue elsewhere, just let me know.

As it stands, we still get these errors on roughly a daily basis, and aside from the incident yesterday, they do no line up with any outages declared by Expo.

![image](https://user-images.githubusercontent.com/5187404/75400610-9e374000-58b4-11ea-9caa-e048827b1d88.png)

**Comment by AndrewSouthpaw** [comment] 2020-03-03 19:17
Hey @cruzach just wanted to check in and see if you had any thoughts? We are continuing to get these errors.

![Search_results_-_andrew_transparentclassroom_com_-_Transparent_Classroom_Mail](https://user-images.githubusercontent.com/5187404/75811020-87736c00-5d40-11ea-8f87-f4c29354b90d.png)

**Comment by cruzach** [comment] 2020-03-04 23:15
Hey @AndrewSouthpaw, It looks like this can happen when[ you overload the SDK server with requests](https://github.com/expo/expo/issues/564). Other devs have resolved this by using the latest version of our [node server SDK](https://github.com/expo/expo-server-sdk-node), which automatically throttles for you.

**Comment by AndrewSouthpaw** [comment] 2020-03-06 04:47
Thanks! We'll looking to the option of throttling. We use the rails SDK, so looks like we'll need to roll our own.

**Comment by AndrewSouthpaw** [comment] 2020-03-06 05:06
Hmm actually I'm curious... what kinds of numbers would overwhelm the SDK server? We send ~5,200 notifications per day, which probably spreads out to ~ 400 notifications / hr over 12 hr periods per day. Is that too much?

I just want to confirm that an overloaded SDK server is indeed the issue before we build some backoff logic.

**Comment by AndrewSouthpaw** [comment] 2020-04-08 00:16
Ping on this?

**Comment by AndrewSouthpaw** [comment] 2020-10-14 16:08
We're still getting this error on a regular basis. Any thoughts?

**Comment by cruzach** [comment] 2020-10-14 19:08
@AndrewSouthpaw we've been digging into this issue a little more recently, and actually deployed a potential fix just now. We weren't able to reproduce this consistently though, so we can't be absolutely sure, but if you can let me know if there's any significant change in the number of 502s you're receiving that would be really helpful!

**Comment by AndrewSouthpaw** [comment] 2020-10-14 19:29
Nice! Thanks for the quick reply, @cruzach. Should I be looking to update any of the libraries, e.g. expo or our sdk? Or was your change a backend thing and I should start keeping an eye on it right now?

**Comment by cruzach** [comment] 2020-10-14 19:38
The change was purely server-side so you can start keeping an eye on it now, no need to update any libraries

**Comment by AndrewSouthpaw** [comment] 2020-10-14 19:41
Groovy, thanks! I'll report back.

**Comment by cruzach** [comment] 2020-10-29 17:55
heya @AndrewSouthpaw , just wondering if you noticed any reduction in those 502 responses over the past 2 weeks?

**Comment by ryokurosu** [comment] 2020-11-03 06:34
I'm still getting an error.

```Server error: POST https://exp.host/-/api/v2/push/send resulted in a 502 Bad Gateway response:
<html>
<head> <title> 502 Bad Gateway </ title> </ head>
<body>
<center> <h1> 502 Bad Gateway </ h1> </ center>
<hr> <center> ngin (truncated ...)
```

**Comment by AndrewSouthpaw** [comment] 2020-11-03 21:46
Hey @cruzach, we appear to not be seeing any change in frequency. Here's a snapshot of the error from Rollbar, which shows occurrences over the last 60 days.

![image](https://user-images.githubusercontent.com/5187404/98043987-055daa80-1ddb-11eb-912e-7e08d8e4232b.png)

**Comment by ryokurosu** [comment] 2020-11-10 16:52
ping on this?

**Comment by arveenkumar55** [comment] 2020-11-27 06:04
Hey @cruzach  I am getting this error while sending a push notification

Expo responded with an error with status code 502: 

<html>

<head><title>502 Bad Gateway</title></head>

<body>

<center><h1>502 Bad Gateway</h1></center>

<hr><center>nginx/1.17.8</center>

</body>

</html>

**Comment by arveenkumar55** [comment] 2020-12-03 11:25
Hey @cruzach I am getting this error while sending a push notification.
Expo responded with an error with status code 502:
<title>502 Bad Gateway</title> 

@cruzach  please reply

**Comment by cruzach** [comment] 2020-12-03 13:54
@arveenkumar55 if there is not additional “error” code in the “details” object, then you should retry the request. We recommended adding retry logic and throttling to your push server in our docs (the [Node server SDK](https://github.com/expo/expo-server-sdk-node) we provide actually does throttling for you)

**Comment by ryokurosu** [comment] 2020-12-06 08:37
@cruzach 

Does that mean you can't handle more than the server's capacity and retransmit?

Are there any changes planned to resolve the 502 error or respond with error details?

**Comment by cruzach** [comment] 2020-12-06 14:35
> Does that mean you can't handle more than the server's capacity and retransmit?

Not sure I understand what you mean by this, so if you could expand on your suggestion that would be helpful. Our servers will not retry requests that result in 502s for you, which is why we recommend adding in your own retry logic.

As for resolving the 502s, since they’re just indicative of an intermittent issue, you should retry the request and it should succeed (adding some throttling to your server may help too).
