### ISSUE TITLE
SVG not working in Snacks

### ISSUE THREAD

**Issue by sospedra** [expo/expo#27109] opened 2024-02-15 17:10 UTC
### Minimal reproducible example

https://snack.expo.dev/@sospedra/github.com-sospedra-holo-card

### Summary

Cannot use react-native-svg in Snacks when using Expo SDK v49 or v50.
Using v48 does work - but the latest Expo Go app does not support v48 anymore.

The error in question is:
```
View config getter callback for component 'RNSVGRect' must be a function (received 'undefined').
```

Here's a similar ticket on the other side: https://github.com/software-mansion/react-native-svg/issues/2214 - tho I think it's an Expo SDK problem.

### Environment

Expo Snack env:

v49 or v50

**Comment by brentvatne** [comment] 2024-02-15 17:14
duplicate of #26263

**Closed by brentvatne** 2024-02-15 17:14 UTC
Labels: needs review
