### ISSUE TITLE
TaskManager remaining Socket

### ISSUE THREAD

**Issue by lecamit83** [expo/expo#7029] opened 2020-02-12 11:35 UTC
### Actual Behavior

I have defined foreground service, and defineTask but
Socket connection was died when devices go on deep sleep.

How can I remain socket's connection

**Comment by cruzach** [comment] 2020-02-14 22:03
Closing since the bug report is mostly empty

Without all the information we ask for, it's really difficult to help you debug and identify what the problem is 🙁 

You may want to look through the [open issues for TaskManager](https://github.com/expo/expo/labels/TaskManager) and see if any of those match your current behavior. I also suggest going through the closed issues to see if anyone has solved your issue already!

**Closed by cruzach** 2020-02-14 22:03 UTC
Labels: bug
