### ISSUE TITLE
iOS archive "main.jsbundle does not exist" in bare workflow

### ISSUE THREAD

**Issue by tafelito** [expo/expo#6435] opened 2019-12-04 16:58 UTC
## 🐛 Bug Report

Creating a new bare app from the cli fails when generating ipa. 

xcode failes with this error

```
error The resource `/Users/jonathantafel/xxx/pm2/ios/index.js` was not found.. Run CLI with --verbose flag for more details.
```

I'm not sure why is it trying to look for the index.js inside the ios folder

### Environment

```
Expo CLI 3.9.1 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.9.1
```

Trying to cpmpile for iOS

### Steps to Reproduce

generate a new minimal bare app, try to archive it

### Expected Behavior

ipa file should be generated

### Actual Behavior

This is the complete error log

```
+ DEST=/Users/jonathantafel/Library/Developer/Xcode/DerivedData/pm2-evforavtawwxyqhepyuhyvcuvsuy/Build/Intermediates.noindex/ArchiveIntermediates/pm2/BuildProductsPath/Release-iphoneos/pm2.app
+ [[ Release = *Debug* ]]
+ [[ -n '' ]]
+ case "$CONFIGURATION" in
+ DEV=false
+++ dirname ../node_modules/react-native/scripts/react-native-xcode.sh
++ cd ../node_modules/react-native/scripts/..
++ pwd
+ REACT_NATIVE_DIR='/Users/jonathantafel/xxx/pm2/node_modules/react-native'
+ PROJECT_ROOT='/Users/jonathantafel/xxx/pm2/node_modules/react-native/../..'
+ cd /Users/jonathantafel/xxx/pm2/node_modules/react-native/../..
../node_modules/react-native/scripts/react-native-xcode.sh: line 60: cd: /Users/jonathantafel/xxx: No such file or directory
+ '[' -z '' ']'
+ export NVM_DIR=/Users/jonathantafel/.nvm
+ NVM_DIR=/Users/jonathantafel/.nvm
+ [[ -s index.ios.js ]]
+ ENTRY_FILE=index.js
+ [[ -s /Users/jonathantafel/.nvm/nvm.sh ]]
++ command -v brew
+ [[ -x /usr/local/bin/brew ]]
++ brew --prefix nvm
+ [[ -s /usr/local/Cellar/nvm/0.35.1/nvm.sh ]]
+ [[ -x /Users/jonathantafel/.nodenv/bin/nodenv ]]
++ command -v brew
+ [[ -x /usr/local/bin/brew ]]
++ brew --prefix nodenv
+ [[ -x /usr/local/Cellar/nodenv/1.3.1/bin/nodenv ]]
+ [[ ! -x node ]]
+ [[ -d /Users/jonathantafel/.anyenv/bin ]]
+ '[' -z node ']'
+ '[' -z '' ']'
+ export NODE_ARGS=
+ NODE_ARGS=
+ '[' -z '' ']'
+ export 'CLI_PATH=/Users/jonathantafel/xxx/pm2/node_modules/react-native/cli.js'
+ CLI_PATH='/Users/jonathantafel/xxx/pm2/node_modules/react-native/cli.js'
+ '[' -z '' ']'
+ BUNDLE_COMMAND=bundle
+ [[ -z '' ]]
+ CONFIG_ARG=
+ type node
+ BUNDLE_FILE=/Users/jonathantafel/Library/Developer/Xcode/DerivedData/pm2-evforavtawwxyqhepyuhyvcuvsuy/Build/Intermediates.noindex/ArchiveIntermediates/pm2/BuildProductsPath/Release-iphoneos/pm2.app/main.jsbundle
+ node '/Users/jonathantafel/xxx/pm2/node_modules/react-native/cli.js' bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/jonathantafel/Library/Developer/Xcode/DerivedData/pm2-evforavtawwxyqhepyuhyvcuvsuy/Build/Intermediates.noindex/ArchiveIntermediates/pm2/BuildProductsPath/Release-iphoneos/pm2.app/main.jsbundle --assets-dest /Users/jonathantafel/Library/Developer/Xcode/DerivedData/pm2-evforavtawwxyqhepyuhyvcuvsuy/Build/Intermediates.noindex/ArchiveIntermediates/pm2/BuildProductsPath/Release-iphoneos/pm2.app
warning: the transform cache was reset.
error The resource `/Users/jonathantafel/xxx/pm2/ios/index.js` was not found.. Run CLI with --verbose flag for more details.
+ [[ false != true ]]
+ [[ ! -f /Users/jonathantafel/Library/Developer/Xcode/DerivedData/pm2-evforavtawwxyqhepyuhyvcuvsuy/Build/Intermediates.noindex/ArchiveIntermediates/pm2/BuildProductsPath/Release-iphoneos/pm2.app/main.jsbundle ]]
+ echo 'error: File /Users/jonathantafel/Library/Developer/Xcode/DerivedData/pm2-evforavtawwxyqhepyuhyvcuvsuy/Build/Intermediates.noindex/ArchiveIntermediates/pm2/BuildProductsPath/Release-iphoneos/pm2.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/jonathantafel/Library/Developer/Xcode/DerivedData/pm2-evforavtawwxyqhepyuhyvcuvsuy/Build/Intermediates.noindex/ArchiveIntermediates/pm2/BuildProductsPath/Release-iphoneos/pm2.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2
```

**Comment by cruzach** [comment] 2019-12-05 17:08
Same version of Xcode, brand new `expo init` bare project using `expo-cli` version 3.9.1, and I didn't have any issues archiving. Maybe this is related to [this issue](https://github.com/facebook/react-native/issues/15432), which has the same error message. regarding `main.jsbundle does not exist`.

Not sure this is a bug with Expo

**Comment by tafelito** [comment] 2019-12-05 17:19
if I actually run the same command from the terminal it does not fail, neither running with expo

```
node '/Users/jonathantafel/xxx/pm2/node_modules/react-native/cli.js' bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output '/Users/jonathantafel/Library/Developer/Xcode/DerivedData/testfb-ckhxgagbltkofpclecgrefaelwhl/Build/Intermediates.noindex/ArchiveIntermediates/testfb/BuildProductsPath/Release-iphoneos/Priority Member 2.app/main.jsbundle' --assets-dest '/Users/jonathantafel/Library/Developer/Xcode/DerivedData/testfb-ckhxgagbltkofpclecgrefaelwhl/Build/Intermediates.noindex/ArchiveIntermediates/testfb/BuildProductsPath/Release-iphoneos/Priority Member 2.app'
```

Btw the reason why I'm trying to build the app myself is because when I add facebook to an app and I build through expo , even tho it runs, something is not working and is messing app with the navigation. I don't know exactly the issue and that's why I'm trying to debug it building it my self but I can get past that point

Anything else you might suggest me to try?

**Comment by cruzach** [comment] 2019-12-05 18:09
what do you mean by adding facebook? We provide [this facebook module](https://docs.expo.io/versions/latest/sdk/facebook/), but I believe most others would require native code changes, and as a result, the bare workflow

Just to make sure- this is happening on an plain `expo init` bare project, no changes whatsoever?

**Comment by tafelito** [comment] 2019-12-05 19:29
> what do you mean by adding facebook? We provide this facebook module, but I believe most others would require native code changes, and as a result, the bare workflow

that's what I meant, just by adding the expo-facebook module and adding the fb id to the app.json, I don't know how and why, but my switch navigator from react-navigation seems to be loading all screens no matter what. And since I'm not logged in I get a bunch of errors on my app. I know this is very specific but the way I tested it was by adding the expo-facebook module to a working app. Without the module, the app works as it's supposed, go to the log in when not logged in. By simple adding the module, the app does what I just said. 
And by the way, this app I'm testing, doesn't use facebook at all, I was just trying to figure out if the issue was related to the facebook module or not


> Just to make sure- this is happening on an plain expo init bare project, no changes whatsoever?

Yes

**Comment by tafelito** [comment] 2019-12-09 18:53
Update: There is definitely an issue with the managed workflow when adding the expo-facebook module. In order to build and run the app properly we had to eject the app and do this facebook [fix](https://github.com/expo/expo/issues/6256#issuecomment-554748629) 

The xcode error is still happening in my computer but it does not happen if I try somewhere else but I still haven't figured it out why

**Comment by cruzach** [comment] 2019-12-11 00:10
What SDK version were you trying this on? SDK 35?

As I said above, I tested this myself and didn't have issues, but maybe you were using an older SDK version?

**Comment by dineshmatta** [comment] 2020-06-01 02:34
Hey @cruzach 

I am using SDK 37 but still getting the issue after eject. My Xcode version is also the latest(11.5)

**Comment by cruzach** [comment] 2020-06-01 13:42
@dineshmatta could you provide steps to reproduce the issue?

**Comment by EvanBacon** [comment] 2022-01-07 01:13
Since we've completely rewritten how the bare workflow works between the last comment and now, I'll be closing. If the issue persists, please reopen (preferably in [expo/expo-cli](https://github.com/expo/expo-cli)).

**Closed by EvanBacon** 2022-01-07 01:13 UTC
Labels: iOS, Bare Workflow
