### ISSUE TITLE
[Android] Route audio to phone receiver/earpiece when recording

### ISSUE THREAD

**Issue by James2516** [expo/expo#5879] opened 2019-10-05 00:42 UTC
## 🐛 Bug Report

Original issue: https://github.com/expo/expo/issues/1610
The landed fix did not resolve the issue as `playThroughEarpieceAndroid`'s behavior is not identical to `allowsRecordingIOS`.

When `allowsRecordingIOS` is true, playback is always routed to the *phone receiver* (earpiece if available).

However, when `playThroughEarpieceAndroid` is true, playback is always route to the *speaker* (earpiece if available). Setting it to false will route playback to the *phone receiver* , but it does not get routed to earpiece even if it's available.

@sjchmiela

**Comment by cruzach** [comment] 2019-10-07 17:58
duplicate of #3689

**Closed by cruzach** 2019-10-07 17:58 UTC
Labels: bug
