### ISSUE TITLE
Expo Router is not rendering correct screens/paths

### ISSUE THREAD

**Issue by ilyadynin** [expo/expo#32764] opened 2024-11-10 21:48 UTC
### Minimal reproducible example

https://github.com/ilyadynin/expo-router-bug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Hey guys I have an issue with expo-router, so I am using MaterialTopTabs and render the screens as MaterialTopTabs.Screens in the order I want them to be in the layout, however they just render in a random order? 

Also now I removed most screens but it stays the same, I thought it is some caching issue but I tried cleaning caches and also pushed an eas update to my preview to check how it turns out there and it has the same wrong order there, I am confused

On Android I have the same wrong behavior, it's both for the dev client & preview app. First it rendered the screens in the wrong order, now I added some screens that I deleted to get back to the old set-up because I wanted to figure out how to fix it later, but it does not even remove the newly added skins and they are still there (in wrong order)

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 10.8.3 - ~/.nvm/versions/node/v20.13.1/bin/npm
      Watchman: 2024.08.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.18.8 => 0.18.11 
      expo: ^51.0.38 => 51.0.38 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    npmGlobalPackages:
      eas-cli: 13.1.1
    Expo Workflow: managed
```

**Comment by qureshikaif** [comment] 2024-11-12 20:40
I'm also facing the same issue. Even with the screens removed from the code. My app is still showing the same set of screens. Does anyone have a fix for it?

**Comment by marklawlor** [comment] 2024-12-17 16:19
I'm unable to reproduce this issue and a full reproduction was not included so I'm going to close this issue.

My assumption is that you missed the installation step for [Material Top Tabs](https://reactnavigation.org/docs/material-top-tab-navigator/#installation) that requires you to run `npx expo install react-native-pager-view`

**Closed by marklawlor** 2024-12-17 16:19 UTC
Labels: needs review, Router
