### ISSUE TITLE
Notifications.getExpoPushTokenAsync() is giving stale value after upgrading phone

### ISSUE THREAD

**Issue by travislang** [expo/expo#6658] opened 2020-01-02 18:12 UTC
I ran into an issue where I have a standalone app that requests the expo push token on every startup and saves it in a backend database. I received a new iPhone for Christmas and transfered over all apps and data to my new phone with my apple ID.

I realized I wasn’t receiving notifications from my app on this new phone and checked the notification logs; which where showing “ok” for both tickets and receipts.

Turns out I had to delete the app from my phone and reinstall it which forced Notifications.getExpoPushTokenAsync() to generate a different push token for this new device.

Notifications now work again so it seems like Notifications.getExpoPushTokenAsync() doesnt check the underlying device API every time it is called and only on app install?

Is this a bug or is there a way to check for this?

🐛 Bug Report

**Environment**
verified issue on iOS (probably an issue with android as well)

**Steps to Reproduce**
Install app on phone. Call Notifications.getExpoPushTokenAsync() to get push token. Transfer apps to new iPhone (this is very common when someone gets a new phone), call Notifications.getExpoPushTokenAsync() again. The push tokens will be the same, so the new phone will not receive notifications.

**Expected Behavior**
Notifications.getExpoPushTokenAsync() should give the correct pushToken based on the underlying device API every time it is called.

**Actual Behavior**
Notifications.getExpoPushTokenAsync() seems like it only checks the underlying device on app install, so when you upgrade iPhones and transfer over all apps it gives a stale value that doesn't work.

**Reproducible Demo**
I can't really provide a demo as the bug stems from transferring all apps to a new device

**Comment by cruzach** [comment] 2020-01-03 20:15
Going to close this as a duplicate of https://github.com/expo/expo/issues/2824 

Can you double-check that you have the same notifications permissions set for the standalone app on the *new* phone?

**Closed by cruzach** 2020-01-03 20:15 UTC
Labels: Notifications, bug, project: android-runtime, project: ios-runtime

**Comment by outaTiME** [comment] 2020-01-07 16:44
Great news @cruzach it will be released on SDK37? or hot fixed on SDK36?
