### ISSUE TITLE
Changes are not deployed to app when running expo publish --release-channel staging

### ISSUE THREAD

**Issue by woba-ko** [expo/expo#11421] opened 2020-12-21 08:35 UTC
### Summary of Issue 
When I make changes to my JS/TS code it is not deployed to the app when publishing to my staging envinronment.

### Environment 

#Output of diagnostics:
  Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2

Trying to deploy iOS/Android staging app.

### Reproducible Demo
Unable to produce demo ATM. I have found multiple other issues of this nature reported but they have all been closed without a solution.
 
### Steps to Reproduce
1. Make changes to existing react code (JS/TS). 
2. Save changes.
3. run 'NODE_ENV=staging expo publish --release-channel staging'.

### Expected Behavior vs Actual Behavior
#Expected: 
I should see my changes in the app when i open it from the expo app.

#Actual:
No changes are published at all.

**Comment by cruzach** [comment] 2020-12-21 15:52
> I should see my changes in the app when i open it from the expo app.

The expo app shows you the `default` release channel in the Projects list. If you want to open a specific release channel of a project in the Expo client app, then you should 
- get the project url, i.e. `https://exp.host/@username/slug?release-channel=staging`
- replace `https` with `exp`
- paste that resulting url into https://www.qr-code-generator.com/
- scan the qr code from your phone, and it should prompt you to open the URL in the expo app

Without a reproducible demo, there's not really any way for us to investigate this further, so I'm going to close the issue. If you can provide a repro, I'm happy to reopen it

**Closed by cruzach** 2020-12-21 15:52 UTC
Labels: needs review

**Comment by JosephLep** [comment] 2020-12-30 21:47
This issue should not be closed.  I have been working on an app - got it approved by apple - but while it was in review i made some changes.  Now that the app is live on the store and I run expo publish - the production app from the store does not show any changes.

**Comment by brentvatne** [comment] 2020-12-30 22:33
@JosephLep - this is almost certainly due to a misunderstanding of ota update behavior. please refer to https://docs.expo.io/workflow/publishing/#what-version-of-the-app-will-my

if you convinced that you have found a bug, please create a new issue and provide more info. otherwise post to https://forums.expo.io to try to some help in understanding your problem and provide as much info as you can to help people debug it with you
