### ISSUE TITLE
Weird Video Native Controls Behaviour on Android

### ISSUE THREAD

**Issue by alialaa** [expo/expo#929] opened 2017-11-07 11:25 UTC
Hello, I am having an issue with the Video component when using native controls on android, I am not sure if this is a bug or it's android's default behaviour but when the controls are showing and you scroll the page, the buttons will not move with the video and will keep floating around on the entire page.

Here is a snack: https://snack.expo.io/HkEUOMyyf

### Before Scrolling:
![whatsapp image 2017-11-07 at 13 16 59](https://user-images.githubusercontent.com/324106/32491294-d8f7e81c-c3be-11e7-9614-7d7b96287be9.jpeg)

### After Scrolling:
![whatsapp image 2017-11-07 at 13 16 54](https://user-images.githubusercontent.com/324106/32491303-dbf37c8e-c3be-11e7-8fb7-58193a54e574.jpeg)

**Comment by ahmed-wagdi** [comment] 2017-11-14 11:29
Any updates on the cause of this or fixes?

**Comment by nikki93** [comment] 2017-12-04 22:11
Fixed by https://github.com/expo/expo/commit/e229282219edb0a789df4feb751a4131d04449b2 which will most likely come out in SDK 24.

**Closed by nikki93** 2017-12-04 22:11 UTC
Labels: in review, project: media
