### ISSUE TITLE
expo-image has an inconsistent border radius

### ISSUE THREAD

**Issue by andresribeiro** [expo/expo#26863] opened 2024-02-01 21:16 UTC
### Minimal reproducible example

https://snack.expo.dev/@andresribeiro/f217c7

### Summary

If you have an image with `style={{ width: 50, height: 50 }}`, you theoretically should add `borderRadius: 25` to create a perfect rounded circle. But if you use `borderRadius: 50`, the result is the same using React Native's Image, but not using Expo Image.

Actually on some devices Expo Image creates a perfect rounded circle, while in others it creates kind of a rhombus
![image](https://github.com/expo/expo/assets/63297375/cd3b8b1c-1b1f-4c8b-b623-b2e04ae2d628)
![image](https://github.com/expo/expo/assets/63297375/96f9b365-9a21-42d6-851e-b6d86fd1e5d5)

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.5 Linux Mint 21.2 (Victoria)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 4.0.2 - ~/.nvm/versions/node/v20.11.0/bin/yarn
      npm: 10.3.0 - ~/.nvm/versions/node/v20.11.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0
        System Images: android-34 | Google APIs Intel x86_64 Atom, android-34 | Google Play Intel x86_64 Atom
    npmPackages:
      expo: ~50.0.4 => 50.0.4 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    npmGlobalPackages:
      eas-cli: 7.1.1
    Expo Workflow: managed
```

**Comment by lukmccall** [comment] 2024-05-06 09:47
Thank you for reporting the issue. Unfortunately, I wasn't able to reproduce it. Could you please let me know the name of the device you used during testing? I believe this may be related to screen density.

**Comment by andresribeiro** [comment] 2024-05-12 13:43
On ZenFone 3 Zoom occurs this Rhombus

**Comment by andresribeiro** [comment] 2024-08-10 15:35
Not stale.

**Comment by andresribeiro** [comment] 2024-11-08 21:32
not stale.

**Comment by lukmccall** [comment] 2024-11-20 13:58
I'm closing this issue because it should be fixed by https://github.com/expo/expo/pull/33078. If the issue still exists in SDK 52, feel free to open a new one.

**Closed by lukmccall** 2024-11-20 13:58 UTC
Labels: needs review
