### ISSUE TITLE
[SDK 44] [expo-file-system] after SDK update createDownloadResumable downloadAsync () does not download large video files. 

### ISSUE THREAD

**Issue by OctagonDS** [expo/expo#15797] opened 2022-01-05 06:59 UTC
### Summary

Updated to SDK 44 and now videos are not cached if they are larger than ~ 15 MB. That is, an 80 MB file is downloaded only a couple of MB and that's it. The file itself is created.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^44.0.4 => 44.0.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

https://github.com/OctagonDS/demo

**Comment by OctagonDS** [comment] 2022-01-05 07:42
The same thing happens when loaded into documentDirectory. I have not checked the minimum upload size, but for example the video from the documentation 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' is cached and loaded, if the video is larger then not.

**Comment by kbrandwijk** [comment] 2022-01-05 07:57
I imported your repo into a Snack, and loaded that to my device. The video downloads fully, and plays completely: https://snack.expo.dev/@agartha/github.com-octagonds-demo

Could you give the Snack a try on your device. Were you testing this on iOS or Android?

**Comment by OctagonDS** [comment] 2022-01-05 09:18
> I imported your repo into a Snack, and loaded that to my iOS device. The video downloads fully, and plays completely: https://snack.expo.dev/@agartha/github.com-octagonds-demo. I also tried on the Android Appetize emulator in the browser. The video downloads completely.
> 
> Could you give the Snack a try on your device? Were you testing this on iOS or Android?

In the answer you dropped, you said that you checked in snack. But snack.expo.dev only supports SDK 43, doesn't it? 
It's just that in SDK 43 everything worked for me on the phone too)
The problem appears only after updating to SDK 44.

**Comment by kbrandwijk** [comment] 2022-01-05 09:20
Oh right, I missed that detail. I'll install locally instead.

**Comment by OctagonDS** [comment] 2022-01-05 09:21
I have tested this on my android phone. And in Android studio and Xcode emulators. The problem is there and there.

**Comment by kbrandwijk** [comment] 2022-01-05 10:30
After testing, swapping out expo-file-system versions, I can reproduce the issue on Android only when switching between SDK 43 and SDK 44.0.3 and 44.0.4, both with the most recent expo-file-system@13.1.0.

On SDK 43, the download progress is there, the download completes, the file is available, the video plays. On SDK 44, expectedBytes is a weird value (sometimes -1, sometimes a different low value), there's only a single progress event, and the file is never properly saved and the video doesn't play because of it.

**Comment by OctagonDS** [comment] 2022-01-10 12:21
Hello! Are there any suggestions for solving the problem?

**Comment by OctagonDS** [comment] 2022-01-26 03:11
Are there any suggestions for solving the problem?

**Comment by OctagonDS** [comment] 2022-02-09 12:18
?

**Comment by brentvatne** [comment] 2022-02-09 21:50
@OctagonDS - no update on this at the moment but i have pinged folks that have recently worked on this module and asked them to investigate

**Comment by barthap** [comment] 2022-02-10 09:05
Hello, 
I couldn't reproduce this issue on iOS in any way.

Regarding Android, I believe that this was recently fixed in https://github.com/expo/expo/pull/15934
I think that it depends on how video host server handles that invalid `Range: bytes=null-` HTTP header. For instance, the 80MB video from your demo failed, but [this 150MB vid](http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4) was downloaded successfully.

**Comment by OctagonDS** [comment] 2022-02-10 12:23
> Hello, I couldn't reproduce this issue on iOS in any way.
> 
> Regarding Android, I believe that this was recently fixed in #15934 I think that it depends on how video host server handles that invalid `Range: bytes=null-` HTTP header. For instance, the 80MB video from your demo failed, but [this 150MB vid](http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4) was downloaded successfully.

Hey! With IOS, I also double-checked after that, and saw that there was no such problem there. And unfortunately there is an androyd, although it was not in SDK 43. I correctly understood that now you can try to update and check again, or you yourself need to change something in the code somewhere. I just did not quite understand what solution is in this thread #15934, due to the fact that the language barrier. Sorry for my English.

**Comment by barthap** [comment] 2022-02-10 16:38
Ok, I'll try to explain it:
- I'm glad that iOS works for you 😁 
- On Android, somebody fixed your issue in #15934 - at least I hope this was the problem 😉 But most likely this fix will be brought to Expo Go in SDK 45, so in about two months. 
- What was the problem? There was a bug that FileSystem incorrectly requested for video to download and some servers didn't understand it correctly, but others did.
   For example, server `abc.com/video1.mp4` worked, but server `xyz.com/video1.mp4` with the same video couldn't download the same video.
- I don't know if video size really matters in this case. I didn't note the correlation between video size and this problem.
- You can check this by replacing the link to 80MB "Entwicklung eines Trading-Planes" video with e.g. [this 150MB bunny video](http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4) and it should work, because the second video hosting server is able "understand" the invalid request from FileSystem anyway.

**Comment by brentvatne** [comment] 2022-02-10 22:21
I released expo-file-system@13.1.4 with this fix. It will not work in Expo Go or with the classic build service, but it will work with EAS Build / bare apps. The fix will become available in Expo Go and classic build service in SDK 45.

**Closed by brentvatne** 2022-02-10 22:21 UTC
Labels: FileSystem, SDK 44

**Comment by OctagonDS** [comment] 2022-02-11 02:54
Thanks a lot. I'll check today.

**Comment by elliotdickison** [comment] 2022-03-14 16:28
@brentvatne Any chance you could publish 13.2.x with this fix? No worries if that's a hassle, I can try pinning at 13.1.4 for now.
