### ISSUE TITLE
Permissions.askAsync never resolves on iOS Standalone app

### ISSUE THREAD

**Issue by ricklove** [expo/expo#1354] opened 2018-01-29 15:55 UTC
With out recent app release, we have found an apparent bug in Expo in the standalone app which caused Apple to reject the submission. It turns out that the Pemissions.askAsync is often not resolving the promise when the user clicks "Allow" or "Don't Allow" on the native dialog popup.

We were able to resolve this in two ways:

- Change the screen automatically in the background and don't wait for a resolved response.
- Use a timeout around the permissions dialog (calling Permissions.getAsync to attempt to get the response).

### Ensure the promise resolved with a timeout:

Note: You should probably not let the UI wait for this response.

```
    askNotificationPermissions_withTimeout = () => {
        // NOTE: Permissions.askAsync seems to never resolve sometimes, so using a timeout to check status

        return new Promise((resolve, reject) => {
            const timeoutId = setTimeout(async () => {
                const { status } = await Permissions.getAsync(
                    Permissions.NOTIFICATIONS
                );
                resolve(status === 'granted');
            }, 5000);

            const promise = Permissions.askAsync(
                Permissions.NOTIFICATIONS
            );

            promise.then(r => {
                clearTimeout(timeoutId);

                const { status } = r;
                resolve(status === 'granted');
            });
        });

    };
```

### Context

- Expo SDK 24.0.0
- iOS Standalone

**Comment by terribleben** [comment] 2018-01-29 19:39
A couple things:

- Can you try generating a new build with `exp build:ios` and testing the new build on Testflight? This is possibly related to a push notifications issue that was affecting all new builds last week (which we resolved on Saturday).
- It's always good to check `getAsync` first before deciding whether to call `askAsync`, as given in [this example](https://docs.expo.io/versions/latest/guides/push-notifications.html).

**Comment by kevinjdolan** [comment] 2018-01-31 19:59
Can confirm -- I observed the same time on an app I released around the same time. Problem disappeared with a new build. Bites that it required re-approval, but it worked!

**Comment by terribleben** [comment] 2018-02-01 23:05
Tentatively closing based on the fix we deployed. Sorry for the disruption, and let me know if you're still running into issues.

**Closed by terribleben** 2018-02-01 23:05 UTC
Labels: project: ios-runtime

**Comment by rmushtaq21** [comment] 2018-04-08 03:07
Hi, we just ran into the same issue with the latest version of Expo. Here are the steps to reproduce the issue:

1) Ask the user for notifications permissions using `askAsync`
2) Allow notification permissions
3) Go to Expo settings and turn off notifications permissions
4) Ask the user for notifications permissions again using `askAsync`

At that point, the app hangs waiting for the promise `askAsync` returns to resolve.

**Comment by Elijen** [comment] 2018-04-17 12:41
@terribleben I can confirm that this is happening on current builds too as @rmushtaq21 described. Should the issue be re-opened?

**Comment by colinyoung** [comment] 2018-05-09 15:46
I'm experiencing this on iOS client 2.5.0, running an SDK 25 app.

**Comment by watadarkstar** [comment] 2018-06-11 18:32
Still experiencing this. @terribleben

**Comment by wassgha** [comment] 2018-08-28 22:54
Just experienced this.

**Comment by mahesh8488** [comment] 2018-08-30 00:02
me too. I have a thread in expo forums for this: https://forums.expo.io/t/push-notifications-in-standalone-app-unable-to-get-the-expo-push-token/13173

**Comment by jordyvanraaij** [comment] 2019-01-22 15:20
> Hi, we just ran into the same issue with the latest version of Expo. Here are the steps to reproduce the issue:
> 
> 1. Ask the user for notifications permissions using `askAsync`
> 2. Allow notification permissions
> 3. Go to Expo settings and turn off notifications permissions
> 4. Ask the user for notifications permissions again using `askAsync`
> 
> At that point, the app hangs waiting for the promise `askAsync` returns to resolve.

I still experience this problem with SDK30 in the Expo Client, can this issue be reopened? Or is there a solution?

**Comment by Serguzest** [comment] 2019-02-06 07:53
updated to sdk32, It works now!

**Comment by samuelcwl** [comment] 2019-02-16 16:58
Can confirm that SDK32 removes the hang. 

However, I'm running into the issue where if the user declines the first time, `askAsync` will not prompt the user a second time. Is this still the standard iOS behavior as discussed here: https://forums.expo.io/t/asking-for-permissions-again-when-denied-the-first-time/10218?

**Comment by Serguzest** [comment] 2019-02-16 19:36
> Can confirm that SDK32 removes the hang.
> 
> However, I'm running into the issue where if the user declines the first time, `askAsync` will **not** prompt the user a second time. Is this still the standard iOS behavior as discussed here: https://forums.expo.io/t/asking-for-permissions-again-when-denied-the-first-time/10218?

yes it is

**Comment by mindpalaces** [comment] 2019-02-24 21:35
Just updated to 32 and having this issue, although I've never denied the permission (it's never prompted)

```await Permissions.askAsync(Permissions.NOTIFICATIONS)```

doesn't do anything, no prompt to user

**Comment by Serguzest** [comment] 2019-02-24 22:46
> Just updated to 32 and having this issue, although I've never denied the permission (it's never prompted)
> 
> `await Permissions.askAsync(Permissions.NOTIFICATIONS)`
> 
> doesn't do anything, no prompt to user

I would still check expo's notification permisson from settings, or just uninstall/install expo app and try again.

**Comment by dinnerparty** [comment] 2019-02-25 05:29
@Serguzest thanks for the tip - if I enable notifications for expo app in the iOS settings it's able to grab the token, so that's cool

when calling askAsync() nothing is returned, no prompt to the user

is the prompt not supposed to happen when using the expo app in development? 
sorry just unsure what is the expected behavior

**Comment by kalinchuk** [comment] 2019-03-14 01:21
I'm having the same issue where `await Permissions.askAsync` hangs. On expo 32.0.0. Any updates on this issue?

**Comment by brentvatne** [comment] 2019-03-14 02:00
@dinnerparty - it will only prompt you once. this is the ios behavior. if it has ever prompted you before you need to go into settings to change it or uninstall / reinstall the app to see the prompt again (just rebuilding or updating on testflight won't work). i suspect you are encountering the same thing @kalinchuk - read the comments above for more info. if this is not the case and on the first install of the app (from not having the app at all on your phone) you don't see a prompt then open a new issue and provide a simulator build that reproduces it (`expo build:ios -t simulator`)

**Comment by dapicester** [comment] 2019-03-14 03:08
I just updated to expo 32.0.0 and `await Permissions.askAsync` hangs on Android too (Android 7.0) if after installing the app the user turns off permissions. I believe it is the same behavior as iOS.

**Comment by brentvatne** [comment] 2019-03-14 03:24
as far as i know this is not anything we fix, it is how the operating systems work. if you use `Permissions.getAsync` first then you can determine if it has been denied, if it has then the user needs to enable it manually in settings

**Comment by kalinchuk** [comment] 2019-03-14 21:03
@brentvatne I get the prompt, but after I tap "allow", the code hangs on `await Permissions.askAsync` and does not allow me to persist the token.

**Comment by farzd** [comment] 2019-04-05 11:11
@brentvatne this issue seems to have propped up again https://github.com/expo/expo/issues/2099
the code hangs at ```const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS)```
even if its the first time its prompted

**Comment by brentvatne** [comment] 2019-04-06 13:53
there is an open WIP PR to fix this issue: https://github.com/expo/expo/pull/3737

**Comment by jSkrills** [comment] 2019-04-06 14:21
@brentvatne is this issue different than #3510 ? Also what version of expo will #3510 be in and where can I see that from the merged pr?

**Comment by brentvatne** [comment] 2019-04-06 14:50
i'm personally not familiar with it but @bbarthec can let you know!

**Comment by jSkrills** [comment] 2019-04-13 23:45
@bbarthec Can you hit me with some knowledge on this issue pretty please? :) Thanks in advance!

**Comment by joraniedemagit** [comment] 2019-08-16 12:29
@brentvatne @bbarthec just to note: this issue was re-introduced in `'expo-permissions'` (at least 6.0.0).

**Comment by WouterFlorijn** [comment] 2019-09-05 12:36
@brentvatne @bbarthec additionally, with expo-permissions, when you deny notifications, the promise resolves with 'granted'.

**Comment by bbarthec** [comment] 2019-09-06 09:08
`expo-permissions` are under refactor right now: #4972 😉

**Comment by exAspArk** [comment] 2019-11-21 16:03
Experiencing the same issue with Expo v35:

```js
const detectCameraPermission = async (setHasCameraPermission) => {
  const { status } = await Permissions.askAsync(Permissions.CAMERA)
}
```

It hangs waiting for `await` when the permission was granted.

**Comment by kulikalov** [comment] 2019-12-13 19:34
Expo 35, 36. The same issue. Tried everything, including weird solutions like [long polling](https://github.com/expo/expo/issues/1354#issuecomment-557152300) and `onPress`...

@exAspArk could you post your code? Just to ensure I got it right.

**Comment by kulikalov** [comment] 2019-12-13 19:36
@terribleben  @watadarkstar pls reopen this issue, it's not resolved.

**Comment by exAspArk** [comment] 2019-12-13 19:49
@kulikalov yeah, sure. Here is the example of my custom workaround:

```js
import { useCameraPermission } from '../hooks/useCameraPermission'

const MyComponent = () => {
  // use the variable in your component (null - still polling, true - granted, false - not granted)
  const hasCameraPermission = useCameraPermission()
  ...
}
```

Implementation:

```js
import { useState, useEffect } from 'react'
import * as Permissions from 'expo-permissions'

const STATUS_GRANTED = 'granted'
const PERMISSION_CHECK_INTERVAL = 500 // ms
var PERMISSION_INTERVAL = null // HACK

const clear = () => {
  if (PERMISSION_INTERVAL) {
    clearInterval(PERMISSION_INTERVAL)
    PERMISSION_INTERVAL = null
  }
}

const checkStatus = ({ status, setHasCameraPermission }) => {
  const hasCameraPermission = status === STATUS_GRANTED
  if (hasCameraPermission) clear()
  setHasCameraPermission(hasCameraPermission)
}

const detectCameraPermission = async ({ setHasCameraPermission }) => {
  // check if permissions were given previously
  const { status: initialStatus } = await Permissions.getAsync(Permissions.CAMERA)

  if (initialStatus === STATUS_GRANTED) {
    setHasCameraPermission(true)
  } else {
    // set "long polling" interval first
    PERMISSION_INTERVAL = setInterval(async () => {
      const { status } = await Permissions.getAsync(Permissions.CAMERA)
      checkStatus({ status, setHasCameraPermission })
    }, PERMISSION_CHECK_INTERVAL)

    // this one hangs
    const { status } = await Permissions.askAsync(Permissions.CAMERA)
    // doesn't hit this line
    checkStatus({ status, setHasCameraPermission })
  }
}

export const useCameraPermission = () => {
  const [hasCameraPermission, setHasCameraPermission] = useState(null)

  useEffect(() => {
    detectCameraPermission({ setHasCameraPermission })
    return () => clear()
  }, [])

  return hasCameraPermission
}
```

**Comment by kulikalov** [comment] 2019-12-14 09:51
found a bit more elegant solution here:
https://www.gitmemory.com/issue/expo/expo/1354/480237688

**Comment by exAspArk** [comment] 2020-02-26 16:13
Not sure if it works on all devices, but from my initial testing it seems to be working on iOS and Android with Expo v36 and the new `expo-camera`:

```js
// custom React Hook
import { useState, useEffect } from 'react'
import { Camera } from 'expo-camera'

const STATUS_GRANTED = 'granted'

const detectCameraPermission = async ({ setHasCameraPermission }) => {
  const { status: initialStatus } = await Camera.requestPermissionsAsync()
  setHasCameraPermission(initialStatus === STATUS_GRANTED)
}

export const useCameraPermission = () => {
  const [hasCameraPermission, setHasCameraPermission] = useState(null)

  useEffect(() => {
    detectCameraPermission({ setHasCameraPermission })
  }, [])

  return hasCameraPermission
}
```
