### ISSUE TITLE
Incorrect styles after building expo app

### ISSUE THREAD

**Issue by arunpugahz** [expo/expo#8258] opened 2020-05-12 06:47 UTC
## 🐛 Bug Report
 I'm having background as Image. The image is working fine as required while developing, but when I build the app and check in TestFlight the styles are different.

I think the problem is with the `transform` property, but am not sure

### Environment

Expo CLI 3.17.24 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.8 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.17.24

### Steps to Reproduce
Expo Snack Repo: 
https://snack.expo.io/fxgUYmEhP

### Expected Behavior

The PatternBackground should come as small checkboxes. Works fine while developing.
<img width="415" alt="Screenshot 2020-05-12 at 11 24 52 AM" src="https://user-images.githubusercontent.com/53349433/81644203-ee9a5480-9444-11ea-8aae-12c75bd0842e.png">

### Actual Behavior
Instead it shows like this after building.
![IMG_65F1A28EDA36-1](https://user-images.githubusercontent.com/53349433/81644298-1689b800-9445-11ea-9cc7-06304351e326.jpeg)

Component Code:
```
(
   <View style={styles.patternContainer}>
   <Image source={pattern} style={styles.patternStyle} />
   </View>
)
const patternScale = 0.5;
const styles: any = StyleSheet.create({
  patternContainer: {
    alignSelf: 'flex-start',
    height: deviceHeight,
    left: -deviceWidth / 2,
    position: 'absolute',
    resizeMode: 'repeat',
    top: -deviceHeight / 2,
    width: deviceWidth,
  },
  patternStyle: {
    flex: 1,
    height: deviceHeight * 2,
    opacity: 0.2,
    position: 'absolute',
    resizeMode: 'repeat',
    transform: [{ scaleX: patternScale }, { scaleY: patternScale }],
    width: deviceWidth * 2,
  },
});
```

Thanks in advance :)

**Comment by brentvatne** [comment] 2020-05-12 21:32
I'm a bit confused - why is the tab bar on the bottom in one and on the top in the other? It seems like the code may be significantly different between the two environments

**Comment by arunpugahz** [comment] 2020-05-13 07:51
> I'm a bit confused - why is the tab bar on the bottom in one and on the top in the other? It seems like the code may be significantly different between the two environments.

**Comment by arunpugahz** [comment] 2020-05-13 07:56
> I'm a bit confused - why is the tab bar on the bottom in one and on the top in the other? It seems like the code may be significantly different between the two environments.

sorry, closed by accident.

@brentvatne I just changed from topNavigator to bottomNavigator. but the code is same for that component

**Comment by brentvatne** [comment] 2020-05-13 18:39
I cannot reproduce this in the example you provided.

## Appearance in Expo client

<img width="495" alt="Screen Shot 2020-05-13 at 11 30 34 AM" src="https://user-images.githubusercontent.com/90494/81851415-42bd3b80-950e-11ea-8d46-113ea47c5e0e.png">

## Appearance in simulator build

<img width="495" alt="Screen Shot 2020-05-13 at 11 37 47 AM" src="https://user-images.githubusercontent.com/90494/81851431-4a7ce000-950e-11ea-86cb-df59e108c8ee.png">

You can download the simulator build here: https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/ios/%40notbrent/snack-3074a728-7693-476f-88e1-1b9231b05994-e096bb4e-20f8-443c-a284-dea04d54c41b-simulator.tar.gz

If you can provide a reproducible example on GitHub and the matching simulator build that shows the problem, please do. Until then I will close the issue

**Closed by brentvatne** 2020-05-13 18:39 UTC
Labels: Needs triage
