### ISSUE TITLE
MediaLibrary createAssetAsync not able to save videos on iOS (physical iPhone 12 on iOS 17.6.1) with codecs "avc1" or "hvc1"

### ISSUE THREAD

**Issue by kupilikula** [expo/expo#33667] opened 2024-12-14 14:45 UTC
### Minimal reproducible example

https://github.com/kupilikula/video-record/tree/main

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

When recording a video using either expo-camera or expo-image-picker and calling MediaLibrary.createAssetAsync to save the video to the phone's media library, on iPhone 12 running iOS 17.6.1, the create asset call throws an error:

"Error saving video: [Error: This URL does not contain a valid asset type: file:///var/mobile/Containers/Data/Application/87A60355-135E-44C0-8971-FA7D4919B556/Documents/video.mp4]"

and ERR_UNSUPPORTED_ASSET_TYPE.

This happens with either codec: "avc1" or "hvc1"  both of which are included in the supported codecs on my device returned by CameraView.getAvailableVideoCodecsAsync() . 
When I use "avc1" as codec option in recordAsync({codec: "avc1"}), I get this error: 

"ERROR  Error recording video: [Error: Video Codec 'Optional("avc1")' is not supported on this device]"

even though these are very common codecs supported by iPhone. Any ideas what I am missing? Thank you very much!

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 23.3.0 - /opt/homebrew/bin/node
      npm: 10.9.0 - /opt/homebrew/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.18 => 52.0.18 
      expo-router: 4.0.11 => 4.0.11 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.4.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Validate packages against React Native Directory package metadata
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by behenate** [comment] 2024-12-18 22:37
Hi!
This is related/duplicate of https://github.com/expo/expo/issues/33537

fixed in
https://github.com/expo/expo/pull/33589

which should be publish in the next few days 😄 

P.S. Thanks for an excellent repro, I wish the original issue had a repo this good

**Closed by behenate** 2024-12-18 22:37 UTC
Labels: needs review

**Comment by kupilikula** [comment] 2024-12-19 01:13
Awesome!! You can thank chatgpt for the repro 🤪
