### ISSUE TITLE
Exiting the app with back button (triangle shaped) throws error on next launch.

### ISSUE THREAD

**Issue by vinay-khatri** [expo/expo#15367] opened 2021-12-01 10:04 UTC
### Summary
Expo is shipping this error out of box.

Exiting the app with back button (triangle shaped) throws error on next launch.

Possible Unhandled Promise Rejection (id: 0): 
Error: Unable to deactivate keep awake. However, it probably is deactivated already.

I tried this on fresh empty project and it still returned the same error.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.18.1 - /usr/bin/node
      npm: 6.14.15 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    npmPackages:
      expo: ~43.0.2 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

1. Create new app project with `expo init --template bare-minimum`
2. Attach a physical android device to computer.
3. Run app with `npm run android`
4. Launch app on your android device.
5. Exit by pressing back button (triangle shaped).
6. Launch app again 
7. Thats it.

**Comment by brentvatne** [comment] 2021-12-01 21:36
duplicate of https://github.com/expo/expo/issues/12584

we will look into landing https://github.com/expo/expo/pull/13432 shortly. you can pull in the patch until then

**Closed by brentvatne** 2021-12-01 21:36 UTC
Labels: needs review, incomplete issue: missing or invalid repro

**Comment by brentvatne** [comment] 2021-12-01 21:47
also, you can pull in the diff from https://github.com/expo/expo/pull/15378 to your project to make it so pressing back from your app does not result in finishing the activity and moves it to background instead. that will get rid of this warning in the case that you describe here
