### ISSUE TITLE
Camera crash when do RecordAsync() Expokit SDK30

### ISSUE THREAD

**Issue by iCueto** [expo/expo#2579] opened 2018-11-03 15:12 UTC
Expo CLI 2.2.4 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.0 => 30.0.1
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
      react-navigation: ^1.5.11 => 1.5.12
    npmGlobalPackages:
      expo-cli: 2.2.4

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/kastaco-fe093420-5a04-4865-9d78-88c34ac3c564.tar.gz

### Issue Description

Camera for Record Video dont Work on Android Devices, when I do RecordAsync() crash and show a screen saying "Stop Failed", on IOS work perfertly, but Android nope... Here some screenshots.

![a805b880-954a-446d-8ce7-043332780a09](https://user-images.githubusercontent.com/7944032/47953835-2293e000-df59-11e8-8b36-fe43444fe26b.jpg)
![5c0b6ef5-2279-4bbe-84c2-3d25bdcad5f3](https://user-images.githubusercontent.com/7944032/47953836-2293e000-df59-11e8-9ee4-52ff1e2c9743.jpg)

Thanks!!!

**Comment by Szymon20000** [comment] 2018-11-12 12:41
Could you provide your code? I could not reproduce the error.

**Comment by tsapeta** [comment] 2019-09-28 17:12
SDK30 that this issue refers to is no longer supported, so I'm gonna close this issue. Please create a new one if this still happens in any of the currently supported SDK versions.

**Closed by tsapeta** 2019-09-28 17:12 UTC
Labels: Camera, project: android-runtime
