### ISSUE TITLE
Experience needs permissions on first run when ios standalone app upgrade from sdk 32 to 33 

### ISSUE THREAD

**Issue by imwilliamxy** [expo/expo#4680] opened 2019-06-21 16:09 UTC
Hi,all

I'm upgrade my app from sdk 32 to 33.
But got a distressing popup box on first run when ios standalone app upgrade from sdk 32 to 33.
The content in the popup box is:
Experience needs permissions. <@my-expo-name/app-slug>  needs permission for notification.You’ve granted permission to another expo experience.Allow <@my-expo-name/app-slug>  use it also?

The source code related to notification is NOT changed.
And all these NEVER happend when I doing upgrade process on older version,.
Maybe this is a new bug in SDK33?
How to get rid off the popup box?
node: 12.1.0
npm:6.9.0
expo-cli: 2.20.2
macOS:10.13.6

![popup](https://user-images.githubusercontent.com/37765549/59935948-bc829d00-9403-11e9-9253-567e671ec2f0.png)

**Comment by cruzach** [comment] 2019-06-21 21:02
Hi @imwilliamxy! If you're using Notifications, why is this distressing?

This doesn't look like a bug, so I'm going to go ahead and close the issue.

**Comment by imwilliamxy** [comment] 2019-06-22 08:53
> Hi @imwilliamxy! If you're using Notifications, why is this distressing?
> 
> This doesn't look like a bug, so I'm going to go ahead and close the issue.

Hi @cruzach ! Thank you for your reply!
Sorry for my english. I'll try describe  more  detail.
My app using Notifications in all versions.
In the past,When upgrade expo SDK from old to new version, the popup box NEVER display.
I understand it is doesn't look like a bug.
But maybe there are some settings to disable the popup box?
Or I can write some code in app to hide the popup box?
I REALLY  don't want to show it to my app user.
Again,Thank you for your help!

**Comment by cruzach** [comment] 2019-06-22 14:45
In order to have access to notifications, the user **must** provide their permission. As far as I know, there's no way around that

**Comment by imwilliamxy** [comment] 2019-06-23 05:34
> In order to have access to notifications, the user **must** provide their permission. As far as I know, there's no way around that

I know that notifications need user provide permission.
But, this popup box is more like **debug info** than a common prompt message box to app user.
I really don't want my app to be considered as amateur quality.

**Comment by physixfan** [comment] 2019-06-24 16:03
There is another place for users to grant push notification permission for the app, and this is my only expo app on my phone, therefore I think this is indeed a bug.

**Comment by YoshiYo** [comment] 2019-06-28 14:05
@imwilliamxy @physixfan @cruzach 
There is clearly something wrong. In the past the user accepted the permissions. 
So I checked again the permissions and this dialog came up only on SDK 33. And I think, this window should not be displayed in a production app, even if the developer failed.

## 🐛 Bug Report

### Environment

Build: iOS SDK 33

### Steps to Reproduce

Upgrading an app from SDK 32 to SDK 33 and ask the permission to the user to allow notifications.

### Expected Behavior

Give the native iOS dialog to allow notification or don't display anything.

### Actual Behavior

Give a weird native iOS dialog like expo handle notifications in the production build.

![expo-problem](https://user-images.githubusercontent.com/8858857/60346967-a3a65880-99bc-11e9-93f0-2642442dabe9.png)


### Reproducible Demo

It's very complicated to reproduct this bug. But it exists.
I didn't experience this issue when the user download directly the build from SDK 33.

**Comment by cem2ran** [comment] 2019-07-05 08:48
I too believe this is a regression or something that has changed and has not been documented.

**Comment by tsapeta** [comment] 2019-07-05 09:10
Hello guys,

We might have misunderstood this issue previously, so I'm sorry we closed it. I'm reopening it and we will try to investigate it asap.

Just to clarify what's wrong in my opinion: This alert should never appear on standalone apps as it references Expo and actually only makes sense in Expo client which, as opposed to standalone apps, can open any experience and the permission needs to be granted separately for each one. This is not the case in standalone apps, so when we're asking for the permission, the system alert should appear there instead of this custom Expo client-specific alert.

**Comment by cem2ran** [comment] 2019-07-05 09:13
@tsapeta Thanks. Feel free to reach out if you need more info.

**Comment by RodolfoGS** [comment] 2019-07-07 00:20
Same issue after upgrade from SDK 32 to 33

**Comment by kirsantov** [comment] 2019-07-16 13:28
It's problem hasn't been resolve in 34.0.0-rc.0 with this commit https://github.com/expo/expo/commit/be06a1a566549d76d14837be619649bb82cc0bf8
It still showing dialog with unclear message for localized app

**Comment by bbarthec** [comment] 2019-07-17 07:45
@kirsantov, this problem would not just go away if you use `expo-permissions@34.0.0-rc.0` 😞 The problem would be solved upon next SDK release (when turtle builder would be updated to use fixed codebase).

**Comment by partyordie** [comment] 2019-07-26 09:31
Is it possible to resolve the issue with a local turtle builder?

**Comment by bbarthec** [comment] 2019-07-26 11:22
@partyordie, yeah, definitely - deciding on setting up local turtle builder you decide on handling building native code of each package on your own (to some extend) and as the initial problem is connected with native code of `expo-permissions` you can replace failing part.
But apart from above release of SDK34 turtle builders would fix failing part in SDK33 as well.

**Comment by partyordie** [comment] 2019-07-30 14:58
I might be wrong but it seems the bug hasn't gone in SDK 34, and the message is still there.

Building it with local turtle does not help either.

**Comment by thanh90** [comment] 2019-08-07 02:44
confirm that it still stands on SDK 34, so annoying

**Comment by thanh90** [comment] 2019-08-12 05:53
any update about this issue ???

**Comment by thanh90** [comment] 2019-08-12 09:23
the issue is fixed with :tag => "ios/2.12.4"

**Closed** 2019-09-05 23:03 UTC
Labels: Permissions

**Comment by creditcoder** [comment] 2019-12-04 01:24
Any news about this issue?
I'm using SDK version 35.0.0, and my app used to crash after alerting notification, even before I could click any buttons 'allow', 'deny'.
![1](https://user-images.githubusercontent.com/53688893/70104022-c0d00900-1677-11ea-9032-0f389f8d8b91.png)
![2](https://user-images.githubusercontent.com/53688893/70104033-c9284400-1677-11ea-9f78-141fd6d7d62e.png)

**Comment by bbarthec** [comment] 2019-12-04 12:19
@creditcoder as the original is fixed according to @thanh90, please open new one that demonstrates your scenario 😉 that would speed up the whole process of fixing it 😊
