### ISSUE TITLE
[SDK 46] EAS Build Failed

### ISSUE THREAD

**Issue by joshauh46** [expo/expo#18445] opened 2022-08-01 18:07 UTC
### Summary

Hi,

I just upgraded my SDK 45 Project to SDK 46 and the EAS Cloud build failed to compile

Build URL: https://expo.dev/accounts/assetalert/projects/AssetAlert/builds/d946938f-7629-465c-94b7-503cc7189759

I have narrowed down the logs to this two errors

```
CompileC /Users/expo/Library/Developer/Xcode/DerivedData/Project-fuxfauwgickftudldgeiazjrcmng/Build/Intermediates.noindex/ArchiveIntermediates/Project/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/ExpoModulesCore.build/Objects-normal/arm64/EXReactNativeAdapter.o /Users/expo/workingdir/build/node_modules/expo-modules-core/ios/Services/EXReactNativeAdapter.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'ExpoModulesCore' from project 'Pods')

CompileC /Users/expo/Library/Developer/Xcode/DerivedData/Project-fuxfauwgickftudldgeiazjrcmng/Build/Intermediates.noindex/ArchiveIntermediates/Project/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/ExpoModulesCore.build/Objects-normal/arm64/EXReactNativeEventEmitter.o /Users/expo/workingdir/build/node_modules/expo-modules-core/ios/Services/EXReactNativeEventEmitter.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'ExpoModulesCore' from project 'Pods')
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.2 => 46.0.2 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.3 => 0.69.3 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.56.0
      expo-cli: 6.0.1
    Expo Workflow: bare

### Reproducible demo

 https://expo.dev/accounts/assetalert/projects/AssetAlert/builds/d946938f-7629-465c-94b7-503cc7189759

**Comment by lisong996** [comment] 2022-08-02 02:36
Same question in 45.0.6, I'm sure it didn't exist last week

**Comment by brentvatne** [comment] 2022-08-02 03:23
@lisong996 - if you believe you have found an issue, please create a new issue and fill out the template

@joshauh46 - the error in your build appears to be:

```
/Users/expo/workingdir/build/node_modules/expo-modules-core/ios/JSI/EXJSIUtils.h:15:111: error: use of undeclared identifier 'Promise'
void callPromiseSetupWithBlock(jsi::Runtime &runtime, std::shared_ptr<CallInvoker> jsInvoker, std::shared_ptr<Promise> promise, PromiseInvocationBlock setupBlock);
```

this was resolved in the latest version of expo-modules-core, which is used by expo@46. however, i noticed the following in your project:

```
Installing ExpoModulesCore (0.9.2)
```

can you run `npm why expo-modules-core` locally to see where this is coming from? that will help you resolve the issue. you  appear to have a dependency that is pulling in an older version of this library

**Comment by brentvatne** [comment] 2022-08-02 03:24
closing this because it does't appear to be a bug in our code and is likely caused by some other dependency, but let me know what you find when you follow the above @joshauh46 :)

**Closed** 2022-08-02 03:23 UTC
Labels: needs more info

**Comment by lisong996** [comment] 2022-08-02 03:54
react-native: 0.69.3 => 0.69.0  solved the problem
