### ISSUE TITLE
Facebook ads"The SDK version in the ad request is no longer supported for new apps. Please upgrade to one of the latest versions of the SDK

### ISSUE THREAD

**Issue by knightkhan** [expo/expo#5860] opened 2019-10-03 16:14 UTC
I  am using expo 35
expo -ads-facebook 7.0.0
error SyntheticEvent {
  "_dispatchInstances": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "_dispatchListeners": [Function onError],
  "_targetInst": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "bubbles": undefined,
  "cancelable": undefined,
  "currentTarget": 219,
  "defaultPrevented": undefined,
  "dispatchConfig": Object {
    "registrationName": "onAdError",
  },
  "eventPhase": undefined,
  "isDefaultPrevented": [Function functionThatReturnsFalse],
  "isPropagationStopped": [Function functionThatReturnsFalse],
  "isTrusted": undefined,
  "nativeEvent": Object {
    "errorCode": 1203,
    "errorMessage": "The SDK version in the ad request is no longer supported for new apps. Please upgrade to one of the latest versions of the SDK",
  },
  "target": undefined,
  "timeStamp": 1570118992960,
  "type": undefined,
}

**Comment by cruzach** [comment] 2019-10-03 17:36
closing, duplicate of #5797

**Closed by cruzach** 2019-10-03 17:36 UTC
