### ISSUE TITLE
SDK35 - iOS13 - Exception was thrown while calling ExpoCalendar.getCalendarsAsync

### ISSUE THREAD

**Issue by linaia** [expo/expo#8956] opened 2020-06-25 08:22 UTC
### Summary of Issue (just a few sentences)

This code on a real device iOS 13.1.2 (iPhone XR)

`const calendars = await Calendar.getCalendarsAsync(Calendar.EntityTypes.EVENT);`

generates the following issue (catched by bugsnag) : 
```
Error: An exception was thrown while calling ExpoCalendar.getCalendarsAsync with arguments `(
   event
)`: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]

```
### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.21.10 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 3.10.10 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.1 => 35.0.1
      react: 16.8.3 => 16.8.3
      react-dom: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: 3.11.1 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.21.10
```

Real device  iOS 13.1.2 iPhone XR

### Reproducible Demo

No, sorry.

### Expected Behavior vs Actual Behavior

Exception should not be thrown

Currently updating the app to SDK37, so just for the record.

**Comment by lukmccall** [comment] 2020-06-25 14:23
Hi @linaia, does this bug occurs in the newer SDK?

**Comment by linaia** [comment] 2020-06-25 14:30
Hi @lukmccall, I wrote : 
> Currently updating the app to SDK37, so just for the record.

So I don't know yet if this occurs in SDK37, otherwise I would have written it here. But I'll let you know if it appears again or not with sdk37.

**Comment by lukmccall** [comment] 2020-06-25 14:33
Ohh, I didn't see this 🤦‍♂️ Sorry. Let me know if it will appear again ;) I think, I fixed a similar issue to this before.

**Comment by lukmccall** [comment] 2020-07-16 14:31
I'm closing this issue because I believe it was fixed in SDK 38. If this is still a problem for you and it's reproducible using the latest SDK version, feel free to open up a new issue!

**Closed by lukmccall** 2020-07-16 14:31 UTC
Labels: Calendar, iOS, status: needs more info
