### ISSUE TITLE
[Expo 49, Router v2] Unable to run with no-dev/prod build on Expo Go or Web: MIME type ('text/html') is not executable

### ISSUE THREAD

**Issue by kennethstarkrl** [expo/expo#24577] opened 2023-09-22 16:20 UTC
### Minimal reproducible example

https://github.com/kennethstarkrl/expo-49-router-v2-no-dev-issues

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

When attempting to run an Expo app with Expo 49 and Expo Router v2 with the --no-dev flag or a production build an error occurs preventing the app from running on Web and/or Expo Go. A minimal reproduceable example is to just create the base expo app with template tabs. `npx create-expo-app@latest --template tabs@49` and do `npx expo start --web --no-dev`

On Android the app flashes for a second then just shows the white loading splash.
On Web the following error is returned in the console.
`Refused to execute script from 'http://localhost:8081/_expo/static/js/web/node_modules%5Cexpo-router%5Centry-76417b5cc57580ab3a59e1861ddf0b1f.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

When doing an expo export:web, looking at the JS file, it seems to be named incorrectly. It looks like somewhere along the line parts of the file path folder structure for the js file are getting URI encoded and put into the file name.

How the file path is exported:
`_expo/static/js/web/node_modules%5Cexpo-router%5Centry-76417b5cc57580ab3a59e1861ddf0b1f.js`

What it looks like it should be:
`_expo/static/js/web/node_modules/expo-router/entry-76417b5cc57580ab3a59e1861ddf0b1f.js`

I attempted to fix the file path to by creating the /expo-router folder inside the /node_modules folder and renaming the js file to  entry-76417b5cc57580ab3a59e1861ddf0b1f.js and manually updating the index.html file, however after doing that I get the following error:
`Uncaught SyntaxError: Unexpected token '<'  entry-76417b5cc57580ab3a59e1861ddf0b1f.js:1`

Any help would be appreciated! Thanks.

### Environment

react-native: 0.72.4 => 0.72.4
react-native-web: ~0.19.6 => 0.19.9
Expo Workflow: managed

Node Version: `v18.16.0`
Packages:
```js
{
  "name": "expo-49-router-v2-no-dev-issues-repo",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-navigation/native": "^6.0.2",
    "expo": "~49.0.11",
    "expo-font": "~11.4.0",
    "expo-linking": "~5.0.2",
    "expo-router": "^2.0.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-system-ui": "~2.4.0",
    "expo-web-browser": "~12.3.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.4",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "jest": "^29.2.1",
    "jest-expo": "~49.0.0",
    "react-test-renderer": "18.2.0",
    "typescript": "^5.1.3"
  },
  "overrides": {
    "react-refresh": "~0.14.0"
  },
  "resolutions": {
    "react-refresh": "~0.14.0"
  },
  "private": true
}

```

**Comment by darkosimon** [comment] 2023-09-24 18:42
@brentvatne Same issue for me.
Made a build with `npx expo export -p web` the file generated is:
node_modules%5Cexpo-router%5Centry-9ba53a97fccf94483a8058d6eb81b08e.js

Temporary fixed by creating a dir 'node_modules/expo-router' in 'dist\_expo\static\js\web' and place the 'entry-9ba53a97fccf94483a8058d6eb81b08e.js' inside

**Comment by marklawlor** [comment] 2023-09-25 02:33
@kennethstarkrl There's a couple of things in your issue and I'm not able to verify all of it

Firstly, can you please complete the issue template and post the results of `npx expo-env-info`

***Web***

`npx create-expo-app@latest --template tabs@49` and do `npx expo start --web --no-dev`

Confirmed, same error. I'll investigate this.

`expo export:web`

This command should fail with the error `expo export:web can only be used with Webpack. Use expo export for other bundlers`.  I'm going to assume this is typo and you meant `expo export -p web`. However I'm unable to reproduce your issue. Running `npx expo export -p web; npx server dist` correctly serves the website. I'm going to assume this could be an issue with your environment and I'll need to see the result of `expo-env-info`

**Android**

I tested your repo in a clean Android simulator running `npx expo start --android --no-dev` and encountered no error. Can you please provide more information?

**Comment by kennethstarkrl** [comment] 2023-09-25 21:13
Ah yea you're correct it is `expo export -p web`

Ok I got the web app running. I am using express to serve the app and forgot to update the static file paths since they changed from Expo 47 to Expo 49. I did have to rename the js file to entry.js and then update all the html files but that seemed to work around the weird file name.

```js
const express = require('express');
const app = express();
app.use('/_expo/static',  express.static(__dirname + '/_expo/static'));
app.use('/assets',  express.static(__dirname + '/assets'));
```

As for running on Android, I don't run it on the simulator only Expo Go, I do `npx expo start --no-dev` and scan the QR code. I can try the simulator soon and see if that works. Expo Go on Android without the `--no-dev `works fine.

@marklawlor here is the full expo-env-info
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.8.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: 49.0.11 => 49.0.11
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.8
    Expo Workflow: managed

**Comment by kennethstarkrl** [comment] 2023-09-25 22:11
@marklawlor I can confirm `npx expo --android --no-dev` works fine in an Android simulator. So it seems to be limited to Expo Go.

**Comment by kennethstarkrl** [comment] 2023-09-26 18:12
@marklawlor @EvanBacon I noticed my project wasn't running with the Hermes js engine, with that now `npx expo --no-dev` is working in Expo Go.

**Comment by kennethstarkrl** [comment] 2023-11-28 20:19
Just an update. --no-dev is now working on Android Expo Go. I sometimes have to clear Expo Go's cache to get it to run the latest build but it works.

So the issue is just the web for --no-dev and exporting.

**Comment by marklawlor** [comment] 2023-11-29 05:09
It is expected with `--no-dev` and Expo Go that you may need reset Expo Go's cache. As its name implies, `--no-dev` does not bundle any development code, including the code that would cache bust Expo Go. Think of it as a quick sanity check before you test with a production build.

I can replicate the issue when running `npx expo start --web --no-dev`. The best workaround is to simply run `npx expo export -p web`. Like Expo Go vs building, `export` is the final step for deploying your production site, so its mostly version you'd want to test  against.

**Comment by leggomuhgreggo** [comment] 2023-12-18 02:47
I was running into this error in an Nx monorepo. There was no project-level `node_modules` (just root).

Seems to be working fine using the index.js + import [approach](https://docs.expo.dev/router/installation/#setup-entry-point) from previous versions. 

```diff
// package.json
{
-  "main": "expo-router/entry"
+  "main": "index.js"
}
```
 
```diff
// index.js
+ import 'expo-router/entry';
```

<details>

<summary>screenshot</summary>

![image](https://github.com/expo/expo/assets/2213636/5b56c895-ec60-4fad-b29f-60e40fb769f2)

</details>

**Comment by darkosimon** [comment] 2024-01-10 13:23
@marklawlor
still issue with url encoded entry file. (npm script: **expo export -p web**)

**Env setup:**
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11076708
    npmPackages:
      expo: ~49.0.8 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.7 
    Expo Workflow: managed

![screen-shot1](https://github.com/expo/expo/assets/19530379/e9ba3409-4751-4efa-bd0b-71f20823ddc7)

package.json -> "main": "expo-router/entry"

I need to manually tweak the path to:
**node_modules\expo-router** and renamte the file to **entry-8fcecd9a4795476d7a03c23ab33da9d3.js**

so the final path be like (windows/IIS correct path):
\_expo\static\js\web\node_modules\expo-router\entry-8fcecd9a4795476d7a03c23ab33da9d3.js

**Comment by marklawlor** [comment] 2024-11-04 11:59
I'm going to close this issue as expected behaviour for now. Due to the multiple output formats of web, running a production with a non-exported project is out of scope for Expo CLI. This may change in a future SDK version.


If you have the other issue of URL encoded entry points in a monorepro, please follow the monorepro setup instructions https://docs.expo.dev/guides/monorepos/#change-default-entrypoint and try setting `EXPO_USE_METRO_WORKSPACE_ROOT` or changing the entry point.

**Closed by marklawlor** 2024-11-04 11:59 UTC
Labels: Issue accepted, Router
