### ISSUE TITLE
[SDK 37] Expo Icons display as [ ? ] only in standalone iOS and published iOS

### ISSUE THREAD

**Issue by jacobjohn90** [expo/expo#8107] opened 2020-04-30 23:09 UTC
Recently upgraded to SDK 37 from 35 by using expo cli (expo upgrade 36, then expo upgrade 37). Fixed breaking changes. Checked how the apps looked in the simulators for both iOS and android. Both looked great. Did a build with expo cli for both platforms. Android in production (from play store) looks fine. For iOS in production (app store), all icons are undefined/ boxed out with a question mark. Checked out the published version of the iOS app within the expo client app, same undefined icons throughout the application. Not entirely sure whats wrong here. Any help?

How the icons are being imported/used:

`import { MaterialIcons } from '@expo/vector-icons'`

`<MaterialIcons name={'close'} size={35} color={colors.blue} />`

Noticed similar issue when people upgraded from 33 to 34. Bug was due to a bug in expo-fonts, which required an update to expo itself to fix. Any help here? 
https://github.com/expo/expo/issues/5110

**Comment by brentvatne** [comment] 2020-04-30 23:26
did you eject your app?

**Comment by jacobjohn90** [comment] 2020-04-30 23:58
We did not eject it out of expo. Sadly, cannot share the app, but I can share the publication id from expo?

**Comment by brentvatne** [comment] 2020-04-30 23:59
1) check your babel.config.js - are you using babel-preset-expo or not?
2) in your metro.config.js (if you have one) are you overriding sourceExts?

share contents of both of those if possible. anyhow this is not a bug unless you can demonstrate isolation so i'll close the issue but let me know and i'll continue to help

**Closed by brentvatne** 2020-04-30 23:59 UTC

**Comment by jacobjohn90** [comment] 2020-05-01 00:57
quick question if this isn't a bug - Why does it only affect published iOS version of my application (on app store or published in expo client app) but local version (on simulator) and all android versions work just fine? Also, icons were displaying just fine prior to the SDK37 update. 

here's my babel.config.js - 
`module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};
`
Do not have a metro.config.js
app.json is -
`
{
  "expo": {
    "name": "Transitiv",
    "slug": "transitiv",
    "privacy": "public",
    "platforms": ["ios", "android", "web"],
    "sdkVersion": "37.0.0",
    "version": "1.0.43",
    "orientation": "portrait",
    "icon": "./src/assets/icon.png",
    "splash": {
      "image": "./src/assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 5000
    },
    "assetBundlePatterns": ["**/*"],
    "packagerOpts": {
      "assetExts": ["png", "js", "jpg", "tts"]
    },
    "entryPoint": "./src/app/entry.js",
    "scheme": "transitiv",
    "ios": {
      "bundleIdentifier": "com.transitiv.transitivmobile",
      "associatedDomains": [
        "applinks:auth.transitiv.io",
        "applinks:*.auth.transitiv.io",
        "applinks:auth-dev.transitiv.io",
        "applinks:*.auth-dev.transitiv.io"
      ],
      "infoPlist": {
        "NSCalendarsUsageDescription": "Allow Transitiv to access your calendar",
        "NSMotionUsageDescription": "Allow Transitiv to access your device's accelerometer",
        "NSCameraUsageDescription": "Allow Transitiv to use your camera",
        "NSMicrophoneUsageDescription": "Allow Transitiv to access your microphone",
        "NSRemindersUsageDescription": "Allow Transitiv to access your reminders",
        "NSContactsUsageDescription": "Allow Transitiv to access your contacts",
        "NSPhotoLibraryUsageDescription": "Give Transitiv permission to access your photos",
        "NSPhotoLibraryAddUsageDescription": "Give Transitiv permission to save photos.",
        "NSLocationWhenInUseUsageDescription": "Allow Transitiv to use your location"
      },
      "supportsTablet": false
    },
    "android": {
      "versionCode": 1038,
      "package": "com.transitiv.transitivmobile",
      "intentFilters": [
        {
          "action": "VIEW",
          "autoVerify": true,
          "data": [
            {
              "scheme": "https",
              "host": "auth.transitiv.io",
              "pathPrefix": "/authreturn/*"
            },
            {
              "scheme": "https",
              "host": "auth-dev.transitiv.io",
              "pathPrefix": "/authreturn/*"
            }
          ],
          "category": ["BROWSABLE", "DEFAULT"]
        }
      ]
    }
  }
}
`

**Comment by jacobjohn90** [comment] 2020-05-01 01:04
here's that app entry file- 
```
import { registerRootComponent } from 'expo';
import { activateKeepAwake } from 'expo-keep-awake';
import App from './App';

if (__DEV__) {
  activateKeepAwake();
//   global.XMLHttpRequest = global.originalXMLHttpRequest ?
//   global.originalXMLHttpRequest :
//   global.XMLHttpRequest;
// // global.FormData = global.originalFormData ?
// //   global.originalFormData :
// //   global.FormData;
// global.Blob = global.originalBlob ?
//   global.originalBlob :
//   global.Blob;
// global.FileReader = global.originalFileReader ?
//   global.originalFileReader :
//   global.FileReader;
}

registerRootComponent(App); 
```

**Comment by jacobjohn90** [comment] 2020-05-01 04:08
Update info: I joined into this project/app midway. Found out that originally, this app was ejected out of expo but then was put back into it/ ejected project was undone because it wasn't need to be ejected in the first place. Could this cause an issue?

**Comment by aaronbdixon** [comment] 2020-05-01 15:51
Having what appears to be the same issue. on iOS everything works in the simulator and when I open in Expo from a link. When we publish and view in TestFlight all fonts are are not loading. We upgraded from 34 to 37.

**Comment by brentvatne** [comment] 2020-05-01 17:51
@jacobjohn90 - yes, maybe you still have an ios and android directory

if you are having this issue it's quite possible that you are in an ejected project. how do you verify that if you're not sure what that means? check if you have an `ios` and `android` directory. delete those if you don't use them.

**Comment by brentvatne** [comment] 2020-05-01 17:51
@aaronbdixon - can you share your project privately?

**Comment by jacobjohn90** [comment] 2020-05-01 17:54
@brentvatne was correct. We still had the iOS and Android folders within our directory. We deleted them, did a new build, and now the icons are back in both TestFlight and published app within expo client. Thanks for your help!!

**Comment by brentvatne** [comment] 2020-05-01 17:57
some context on why this is happening with ios and android directories present:

- we recently released support for `expo-updates` in bare react-native apps
- `expo-cli` needs some way to know if it should publish for a bare app or for usage in expo client / a standalone app built by expo build service
- so we look for ios and android directories to guess that
- then we set the `target` flag accordingly, so `expo publish --target bare` is the default if you have ios and android directories, otherwise it's `expo publish --target managed`

we should let people know what target is being used explicitly in the publish output to be more clear about this

**Comment by jacobjohn90** [comment] 2020-05-01 18:00
ahhh, interesting. I figured that was the case. I thought the cli was looking for the <detached> key within app.json to determine if the app was bare or not. Thanks for explaining this for me.

**Comment by aaronbdixon** [comment] 2020-05-01 18:30
The -t managed option fixed this for us. Thank you. We haven't ejected.

**Comment by brentvatne** [comment] 2020-05-01 20:19
@aaronbdixon - can you share more info about your project? do you have an `ios` and `android` directory?

**Comment by aaronbdixon** [comment] 2020-05-01 22:14
> @aaronbdixon - can you share more info about your project? do you have an `ios` and `android` directory?

Yes we had those directories. We had not ejected though. We did migrate from an ejected app long ago so it’s possible those got copied over in the migration.

**Comment by gabrielnaoto** [comment] 2020-05-06 23:48
I'm also having this issue as well.

In my case though, the app was actually ejected and I can't delete android/ios folders due to specific changes made.

Then what should the solution be?

**Comment by jamesst20** [comment] 2020-09-23 12:56
> @jacobjohn90 - yes, maybe you still have an ios and android directory
> 
> if you are having this issue it's quite possible that you are in an ejected project. how do you verify that if you're not sure what that means? check if you have an `ios` and `android` directory. delete those if you don't use them.

Thanks ! That did it for me. I was ejected without knowing it because of lack of experiences with react-native.
