### ISSUE TITLE
 Speech.speak is not working when I re-enter the app (Android)

### ISSUE THREAD

**Issue by bkioshn** [expo/expo#8543] opened 2020-05-28 17:16 UTC
### Environment
```
{
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.6",
    "@react-native-community/voice": "^1.1.0",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",
    "expo": "^37.0.0",
    "expo-av": "~8.1.0",
    "expo-camera": "^8.2.0",
    "expo-face-detector": "~8.1.0",
    "expo-permissions": "^8.1.0",
    "expo-speech": "~8.1.0",
    "expo-splash-screen": "^0.2.3",
    "expo-updates": "~0.2.0",
    "moment": "^2.24.0",
    "react": "~16.9.0",
    "react-dom": "16.9.0",
    "react-native": "~0.61.5",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-gifted-chat": "^0.13.0",
    "react-native-image-resizer": "^1.2.2",
    "react-native-permissions": "^2.0.9",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-sound": "^0.11.0",
    "react-native-unimodules": "~0.9.0",
    "react-native-web": "^0.11.7",
    "rxjs": "^6.5.5"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "@types/react": "^16.9.11",
    "@types/react-native": "^0.60.22",
    "@types/uuid": "^7.0.0",
    "babel-jest": "~25.2.6",
    "babel-preset-expo": "^8.1.0",
    "jest": "~25.2.6",
    "jest-expo": "^37.0.0",
    "react-test-renderer": "~16.9.0",
    "typescript": "^3.8.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}

```

Speech.speak works for the first time when I entered the app, but when I quit the app and re-enter it again, it doesn't work.
`
Speech.speak(text, {
      language: 'th',
    onStart: () => {console.log('hi')}})
`
I tried to debug and it turns out that Speech.speak only invoke for the first time I enterd the app. No error logs are provided for me even when I use onError.

I need to clear the app cache to make it works again. If anyone knows how to clear the application cache (with code) when quitting the app without manually doing it, I would be really thankful for the help.

**Comment by cruzach** [comment] 2020-06-01 16:07
Is this in the Expo client from the google play store, or in a standalone apk?

**Comment by bkioshn** [comment] 2020-06-02 14:31
> Is this in the Expo client from the google play store, or in a standalone apk?

A standalone apk

**Comment by barthap** [comment] 2020-07-17 06:22
Sorry, I cannot reproduce it neither building standalone apk locally from bare workflow nor using Turtle to build it. I didn't clear any cache and Speech is working all the time, even after resetting the app.

**Comment by cruzach** [comment] 2021-05-03 15:46
Closing this issue since we aren't able to reproduce the bug

**Closed by cruzach** 2021-05-03 15:46 UTC
Labels: Android, Speech, needs repro
