### ISSUE TITLE
Android IllegalThreadStateException with SDK 44

### ISSUE THREAD

**Issue by claudiofus** [expo/expo#15708] opened 2021-12-25 11:01 UTC
### Summary

Unfortunately I don't know where is the problem, I got this error in Google Play Developer Console in 3 different apps, built with EAS and SDK 44. Could it be a problem with `expo-updates` package?
```
java.lang.IllegalThreadStateException: 
  at java.lang.Thread.start (Thread.java:872)
  at expo.modules.updates.UpdatesController.initializeDatabaseHandler (UpdatesController.kt:59)
  at expo.modules.updates.UpdatesController.start (UpdatesController.kt:205)
  at expo.modules.updates.UpdatesController$Companion.initialize (UpdatesController.kt:448)
  at expo.modules.updates.UpdatesPackage$createReactNativeHostHandlers$handler$1.onWillCreateReactInstanceManager (UpdatesPackage.kt:41)
  at expo.modules.ReactNativeHostWrapper.createReactInstanceManager (ReactNativeHostWrapper.kt:28)
  at com.facebook.react.ReactNativeHost.getReactInstanceManager (ReactNativeHost.java:39)
  at expo.modules.updates.UpdatesUtils.sendEventToReactNative (UpdatesUtils.kt:139)
  at expo.modules.updates.UpdatesController$start$1.onBackgroundUpdateFinished (UpdatesController.kt:254)
  at expo.modules.updates.loader.LoaderTask$launchRemoteUpdateInBackground$1$1.onFailure (LoaderTask.kt:282)
  at expo.modules.updates.loader.Loader.finishWithError (Loader.kt:142)
  at expo.modules.updates.loader.Loader.access$finishWithError (Loader.kt:18)
  at expo.modules.updates.loader.Loader$start$1.onFailure (Loader.kt:94)
  at expo.modules.updates.loader.FileDownloader$downloadManifest$1.onFailure (FileDownloader.kt:266)
  at expo.modules.updates.loader.FileDownloader$downloadData$1.onFailure (FileDownloader.kt:343)
  at okhttp3.RealCall$AsyncCall.execute (RealCall.java:211)
  at okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:923)
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

```
 Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1
      expo: ^44.0.0 => 44.0.0
      react: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: managed
```

### Reproducible demo

This problem occurred on Android 11 and Android 10, with Samsung Galaxy A12, Galaxy A50, Galaxy A71, Galaxy S9, Galaxy S10, Galaxy S20+ 5G.

Command used to build and submit: `eas build -p all --profile my-profile --auto-submit`

**UPDATE:** I've deployed a new build with `expo build:android --no-wait -t app-bundle` and I don't have this problem so maybe the problem is due to EAS build or specifically to `expo-updates`.

**Comment by sheppard** [comment] 2021-12-28 13:12
I can confirm that this happens when expo-updates checks for an update but there is no network connection (e.g. due to airplane mode).  Depending on configuration, the crash can happen immediately at startup, potentially making the app unusable when offline.

**Comment by jparkrr** [comment] 2021-12-28 16:13
I'm getting this with expo-updates@0.11.3. Unlike @sheppard, this is happening for me with an active network connection.

**Comment by claudiofus** [comment] 2021-12-28 16:33
I think @jparkrr is right, I had a lot of errors like this and I don't think that every user has launched the app without network connection. IMHO there's something in the package or in SDK 44 that's not working properly with EAS, due to the [Removed most remaining default dependencies from managed projects](https://blog.expo.dev/expo-sdk-44-4c4b8306584a).

**Comment by JouHouFin** [comment] 2021-12-29 09:07
I'm also getting crash reports to Play Store Developer Console with identical stack traces to one in the issue summary. So far only one affected device (S10/Android 11), but I just tested with my own device and the app seems to crash immediately on startup if network access is disabled completely.

**Comment by foolem** [comment] 2021-12-29 12:28
I'm also having this crash on Android devices using SDK 44 and hermes.

Stacktrace:
``
<a class="DataTable" data-interactive="true" style="box-sizing: border-box; background-color: rgb(248, 248, 248); color: rgb(0, 0, 0); text-decoration: none; font-feature-settings: &quot;tnum&quot;, &quot;lnum&quot;; display: block; position: relative; outline: 0px; font-family: kievit, serif, avenir, &quot;lucida grande&quot;, &quot;gill sans&quot;, &quot;helvetica neue&quot;, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;">

java.lang.IllegalThreadStateException         at java.lang.Thread.start(Thread.java:868)         at expo.modules.updates.UpdatesController.initializeDatabaseHandler(UpdatesController.kt:59)         at expo.modules.updates.UpdatesController.start(UpdatesController.kt:205)         at expo.modules.updates.UpdatesController$Companion.initialize(UpdatesController.kt:448)         at expo.modules.updates.UpdatesPackage$createReactNativeHostHandlers$handler$1.onWillCreateReactInstanceManager(UpdatesPackage.kt:41)         at expo.modules.ReactNativeHostWrapper.createReactInstanceManager(ReactNativeHostWrapper.kt:28)         at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)         at expo.modules.updates.UpdatesUtils.sendEventToReactNative(UpdatesUtils.kt:139)         at expo.modules.updates.UpdatesController$start$1.onBackgroundUpdateFinished(UpdatesController.kt:254)         at expo.modules.updates.loader.LoaderTask$launchRemoteUpdateInBackground$1$1.onFailure(LoaderTask.kt:282)         at expo.modules.updates.loader.Loader.finishWithError(Loader.kt:142)         at expo.modules.updates.loader.Loader.access$finishWithError(Loader.kt:18)         at expo.modules.updates.loader.Loader$start$1.onFailure(Loader.kt:94)         at expo.modules.updates.loader.FileDownloader$downloadManifest$1.onFailure(FileDownloader.kt:267)         at expo.modules.updates.loader.FileDownloader$downloadData$1.onFailure(FileDownloader.kt:344)         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)         at java.lang.Thread.run(Thread.java:919)
--


</a>
``

**Comment by Lopoi** [comment] 2022-01-06 12:47
> Edit2: just pushed an update to Play Store with `updates.enabled` set to `false`. The app launches just fine without network access.

This works, but you can keep `updates.enabled` on `true` and set `checkAutomatically` to `ON_ERROR_RECOVERY` and do a manual check for updates with the `expo-updates` functions. But apparently `Updates.reloadAsync` crashes the app, and I assume thats why the `ON_LOAD` crashes immediatly on start.

I use the following code to check for updates on my apps:

```javascript
Updates.checkForUpdateAsync()
.then((response)=>{
    if(response.isAvailable){
        Updates.fetchUpdateAsync()
        .then((result)=>{
            if(result.isNew){
                //Updates.reloadAsync().catch((e)=>{ This is commented cause it crashes the app
                    //navigate to app
                //})
            }else{
                //navigate to app
            }
        }).catch((e)=>{
            //navigate to app
        })
    }else{
        //navigate to app
    }
}).catch((e)=>{
    //navigate to app
})
```

This wont update the app on start, but at least will download the update for when the user restarts the app, which should be helpfull for some minor updates

**Comment by jnoleau** [comment] 2022-01-06 15:45
Same problem with Android + SDK44, setting `updates.enabled` to false resolves the issue but OTA is disabled :(, 

@Lopoi Thanks for your solution, this is the default behaviour of setting `updates.enabled` to true and `updates.fallbackToCacheTimeout` to 0, I will try it as a temporary patch !

Hope a member from the expo team looks at this issue, OTA is just a critical feature for us ^^

**Comment by stephenlaughton** [comment] 2022-01-07 04:40
Can confirm this is also an issue for us on Android with SDK 44.
```
Fatal Exception: java.lang.IllegalThreadStateException
       at java.lang.Thread.start(Thread.java:872)
       at expo.modules.updates.UpdatesController.initializeDatabaseHandler(UpdatesController.kt:59)
       at expo.modules.updates.UpdatesController.start(UpdatesController.kt:205)
       at expo.modules.updates.UpdatesController$Companion.initialize(UpdatesController.kt:448)
       at expo.modules.updates.UpdatesPackage$createReactNativeHostHandlers$handler$1.onWillCreateReactInstanceManager(UpdatesPackage.kt:41)
       at expo.modules.ReactNativeHostWrapper.createReactInstanceManager(ReactNativeHostWrapper.kt:28)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
       at expo.modules.updates.UpdatesUtils.sendEventToReactNative(UpdatesUtils.kt:139)
       at expo.modules.updates.UpdatesController$start$1.onBackgroundUpdateFinished(UpdatesController.kt:254)
       at expo.modules.updates.loader.LoaderTask$launchRemoteUpdateInBackground$1$1.onFailure(LoaderTask.kt:282)
       at expo.modules.updates.loader.Loader.finishWithError(Loader.kt:142)
       at expo.modules.updates.loader.Loader.access$finishWithError(Loader.kt:18)
       at expo.modules.updates.loader.Loader$start$1.onFailure(Loader.kt:94)
       at expo.modules.updates.loader.FileDownloader$downloadManifest$1.onFailure(FileDownloader.kt:266)
       at expo.modules.updates.loader.FileDownloader$downloadData$1.onFailure(FileDownloader.kt:343)
       at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.onFailure(InstrumentOkHttpEnqueueCallback.java:63)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:180)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by foolem** [comment] 2022-01-07 13:12
Downgrading expo-updates solves the problem temporarily

**Comment by StevePhuc** [comment] 2022-01-09 12:34
> Downgrading expo-updates solves the problem temporarily

@foolem which version you use

**Comment by jparkrr** [comment] 2022-01-10 18:13
I wasn't able to reproduce this in a new sdk 44 app (with expo-updates).

I will try to narrow down why it's still happening in my app, but if anyone who works on expo-updates gets any ideas from the stacktrace, please let us know. It is blocking us from shipping a new version.

**Comment by zeulb** [comment] 2022-01-10 19:07
I got the same error when I enabled Hermes in our bare SDK 44 app, works totally fine when hermes is disabled

**Comment by chris-snow** [comment] 2022-01-10 20:36
We received the following output just prior to our app crashing:

```
Failed to download manifest from URL: xxxxx
01-10 13:26:24.813 17448 17586 E Loader  : java.lang.Exception: {"message":"Experience \"xxxxx" for platform \"android\" and release channel \"4.10.0\" does not exist or is not published.","errorCode":"EXPERIENCE_NOT_FOUND","metadata":{"fullName":"xxxxx","platform":"android","sdkVersions":["44.0.0"],"releaseChannel":"4.10.0","availableSDKVersions":[]}}
01-10 13:26:24.813 17448 17586 E Loader  : 	at expo.modules.updates.loader.FileDownloader$downloadManifest$1.onResponse(FileDownloader.kt:277)
01-10 13:26:24.813 17448 17586 E Loader  : 	at expo.modules.updates.loader.FileDownloader$downloadData$1.onResponse(FileDownloader.kt:351)
01-10 13:26:24.813 17448 17586 E Loader  : 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
01-10 13:26:24.813 17448 17586 E Loader  : 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
01-10 13:26:24.813 17448 17586 E Loader  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-10 13:26:24.813 17448 17586 E Loader  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-10 13:26:24.813 17448 17586 E Loader  : 	at java.lang.Thread.run(Thread.java:764)
01-10 13:26:24.814 17448 17586 E LoaderTask: Unexpected error encountered while loading this app
01-10 13:26:24.814 17448 17586 E LoaderTask: java.lang.Exception: {"message":"Experience \"xxxxx" for platform \"android\" and release channel \"4.10.0\" does not exist or is not published.","errorCode":"EXPERIENCE_NOT_FOUND","metadata":{"fullName":"xxxxxx","platform":"android","sdkVersions":["44.0.0"],"releaseChannel":"4.10.0","availableSDKVersions":[]}}
```

Not sure if relevant but thought I'd share.

**Comment by jparkrr** [comment] 2022-01-10 21:02
> I got the same error when I enabled Hermes in our bare SDK 44 app, works totally fine when hermes is disabled

Ah right, thanks!

The issue **does** reproduce in a new expo sdk 44 app with hermes enabled. 

You must turn on airplane mode (or turn off wifi for emulator). Sometimes it launches but usually it crashes for me. Try it a few times.

APK: https://github.com/jparkrr/expo-android-crash/raw/main/build-10-01-2022-15:31.apk
Repo: https://github.com/jparkrr/expo-android-crash

**Comment by cloudhary** [comment] 2022-01-11 02:25
> Downgrading expo-updates solves the problem temporarily

@foolem downgrade to which version? Thanks!

**Comment by esamelson** [comment] 2022-01-12 19:01
Hi all, thanks for the report and sorry for the delay on our end. We've got a fix in the works that should be out by the end of the week (hopefully sooner). Many thanks to @jparkrr for the repo which was very helpful in finding the cause and testing a fix quickly.

**Comment by foolem** [comment] 2022-01-12 20:26
@cloudhary @StevePhuc 0.10.15

**Comment by esamelson** [comment] 2022-01-13 04:59
expo-updates@0.11.4 has been released with a fix for this issue; you'll need to make a new build to get the fix. Going to go ahead and mark this as closed. Thanks all for the report, and apologies for the trouble!

**Closed by esamelson** 2022-01-13 04:59 UTC
Labels: bug, Updates
