### ISSUE TITLE
Speech.speak not working in Expo Client

### ISSUE THREAD

**Issue by awinograd** [expo/expo#4733] opened 2019-06-26 16:31 UTC
### Environment

https://snack.expo.io/@awinograd/healthy-cashew

Android Expo Client 2.11.4. I've given all permissions to the expo client app in settings, not sure if there's anything else I need to enable.

speak() is working in my iOS simulator

### Steps to Reproduce

Press the button on the screen

### Expected Behavior

Pressing the button should speak the text

### Actual Behavior

Pressing the button does not produce any TTS audio

### Reproducible Demo

https://snack.expo.io/@awinograd/healthy-cashew

**Comment by cruzach** [comment] 2019-06-26 17:25
Hey @awinograd- can you make sure your device isn't set to `silent`? We had a similar report of this on forums and that ended up being the issue 😄

**Comment by awinograd** [comment] 2019-06-26 17:25
@cruzach my phone is on full media volume and the ringer is on as well. I can successfully play the TTS test in settings

**Comment by cruzach** [comment] 2019-06-26 17:30
Okay, thanks for making sure! Just wanted to rule that out

What Android device is this happening on? I tested on an Android emulator and it works fine (don't have a physical Android device on me)

**Comment by awinograd** [comment] 2019-06-26 17:47
Definitely open to other ideas of where my device might be set incorrectly.

I have a Pixel 1 on android 9 with patch level june 5 2019

**Comment by cruzach** [comment] 2019-06-26 18:31
Hm that's the exact emulator device I tested on (successfully) client version 2.11.4

There shouldn't be any other settings you'd have to configure to get this working

Can you check if `Speech.isSpeakingAsync()` returns true during the time you'd expect it to return true?

**Comment by awinograd** [comment] 2019-06-26 18:45
It's returning `false` on my android device and `true` in the same place on my iOS simulator. I haven't gotten the android simulator running but I'll try to and see what the behavior is there

**Comment by awinograd** [comment] 2019-06-26 19:21
My Android emulator is working as expected. Just the physical android device that' having issues

**Comment by LuckyLuke19** [comment] 2019-08-30 17:46
You need to have this package installed on Android: https://play.google.com/store/apps/details?id=com.google.android.tts

**Comment by mczernek** [comment] 2020-03-04 16:21
I believe there are two problems in here. First, we do not resolve with proper error message once we cannot initialize TextToSpeach. We just pretend nothing happens, which is confusing.

Second, we have to figure out what to do if we're unable to use TTS. This is whole other issue and discussion, far bigger than this.

**Comment by efiul** [comment] 2020-03-22 12:24
Hi,
I am having the same issue.
I am trying to use expo-speech in my react-native app and I am getting the following error on my Android:

[Unhandled promise rejection: Error: Encountered an exception while calling native method: Exception occurred while executing exported method speak on module ExponentSpeech: null]
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:155:41 in createErrorFromErrorData
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:104:55 in <unknown>
- ... 5 more stack frames from framework internals

The code is the following:

speak = async text => {
  Speech.speak(convertHTMLstring(text), {
    language: 'he',
    pitch: '1',
    rate: '0.9',
  })
}

Do you have an idea what am I doing wrong?
On iOS it works just fine.

**Comment by tsapeta** [comment] 2020-07-27 11:49
@awinograd are you still encountering this issue? I'm gonna close it because we wasn't able to reproduce it and we didn't get similar reports, but let me know if it's still bothering you! 🙂

**Closed by tsapeta** 2020-07-27 11:49 UTC
Labels: Speech, bug, needs repro

**Comment by awinograd** [comment] 2020-07-27 15:19
@tsapeta I switched to the bare workflow a while back and haven't tested the speech module in the client for a while. Happy to keep it closed. Thanks!
