### ISSUE TITLE
Saving audio on AWS s3

### ISSUE THREAD

**Issue by Rhjulskov** [expo/expo#214] opened 2017-05-27 12:16 UTC
I'm trying to record and save Audio to AWS S3. 

I'm able to record and play the newly recorded audio in the App, but when trying to save using https://github.com/benjreinhart/react-native-aws3, the file turns up empty in S3.

I'm trying to save the complete sound object returned by createNewLoadedSound: 
`
const { sound, status } = await this.recording.createNewLoadedSound()
`
That sound can be played local with .playAsync(), but the file is empty on S3 with the following file settings:

`
const file = {
  uri: sound,
  name: `${name}.caf`,
  type: "audio/x-caf"
};
`
Has anyone solved this? :)

**Comment by Rhjulskov** [comment] 2017-06-06 16:10
It seems like, i'm not the only one with this issue. Has anyone resolved it?

**Comment by Rhjulskov** [comment] 2017-06-11 17:30
Where and how are people saving these files in production?

**Comment by Rhjulskov** [comment] 2017-06-22 09:19
@terribleben @gkufera Have anyone had success with saving the .caf format on ANY cloud providers? The demo with a working local example only gets you this far.

**Comment by dariocravero** [comment] 2017-06-27 20:14
@Rhjulskov we're sending them to a backend for further processing and storage in S3. We pretty much followed this example @brentvatne made a while ago https://github.com/expo/image-upload-example and it just worked.

**Comment by dikaiosune** [comment] 2017-06-28 21:27
@Rhjulskov would you be able to provide a minimal reproduction of this problem as a gist or github repo?

**Comment by maludwig** [comment] 2017-07-21 09:18
Turns out we're all crazy overthinking it. Turns out you can just make a normal fetch. Here's a function that does what we all want, just makes a perfectly normal multipart/formdata POST upload to an arbitrary http endpoint, obviously replace "YOUR_SERVER_HERE" with your server's FQDN, and obviously code the upload URL to handle a file upload. This example clearly has no authentication or any frills or gimmicks along the edges. I'm not trying to make bank:

```

async function uploadAudioAsync(uri) {
  console.log("Uploading" + uri);
  let apiUrl = 'http://YOUR_SERVER_HERE/upload';
  let uriParts = uri.split('.');
  let fileType = uriParts[uriParts.length - 1];

  let formData = new FormData();
  formData.append('file', {
    uri,
    name: `recording.${fileType}`,
    type: `audio/x-${fileType}`,
  });

  let options = {
    method: 'POST',
    body: formData,
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'multipart/form-data',
    },
  };

  console.log("fetching" + uri + " as " + apiUrl);
  return fetch(apiUrl, options);
}
```

**Comment by terribleben** [comment] 2017-07-31 19:24
Tentatively closing this because of the solution posted above - feel free to comment if there is something left unresolved here!

**Closed by terribleben** 2017-07-31 19:24 UTC

**Comment by ceefour** [comment] 2017-12-09 07:42
@maludwig's workaround (https://github.com/expo/expo/issues/214#issuecomment-316950941) won't work for PUT/presigned URLs due to bug https://github.com/facebook/react-native/issues/8237

**Comment by ceefour** [comment] 2017-12-09 08:07
How did I unassigned @gkufera (I have no privileges)? Seems like a GitHub bug ?

**Comment by horiuchie** [comment] 2017-12-10 08:04
Alternatively [createPresignedPost](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createPresignedPost-property) could be available.
This is also a way that we don't have to code a server side.

e.g.
```
import * as R from 'ramda';
import * as AWS from 'aws-sdk';
const path = require('path');

︙

async function uploadAudioAsync(uri) {
  
  // create presigned post data
  const s3 = new AWS.S3();
  const key = path.basename(uri);
  const params = {
    Bucket: 'YOUR_BUCKET_NAME',
    Fields: { key, /* 'Content-Type': 'CONTENT_TYPE' */ }
  };
  const { url, fields } = s3.createPresignedPost(params);

  // set them to form data
  const formData = new FormData();  
  R.forEachObjIndexed((value, key) => formData.append(key, value), fields);
  formData.append('file', { uri });

  // fetch options
  const options = {
    method: 'POST',
    body: formData,
    headers: { 'Content-Type': 'multipart/form-data' }
  };

  // request
  return fetch(url, options);
}

// Do a recording
let uri = await this.recording.getURI();
await uploadAudioAsync(uri);
```
