### ISSUE TITLE
Android standalone app just restarts itself

### ISSUE THREAD

**Issue by Dmendoza99** [expo/expo#4492] opened 2019-06-08 03:20 UTC
## 🐛 Bug Report
I'm currently working in an app for a client of mine, and i need to create the apk for them to see the updates, the problem is that when i built it, i just got an self-restarting apk

### Environment
OS: Windows 10
SDK: 33
Expo-cli: 2.19.4
Node: v10.15.3
Npm: 6.9.0

### Expo diagnostics
  Expo CLI 2.19.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

### App target
Android and IOS

### Steps to Reproduce
I updated my project with latest SDK 33, and after that i just ran "expo build:android" on my powershell and it all when like it suppose too, but the apk just restart itself

### Expected Behavior
It should be working just like in the expo client app

### Actual Behavior
App just restarts itself like 20 times and then i get an error

### Reproducible Demo
At the moment i don't even know where the error comes from because in development the app works perfectly, but if you build it, it just do the same

### Actual Error info

1) Uncaught Error: Application main has not been registered.

2) Uncaught Error: undefined is not an object (evaluating 'u.default.EVENT_NAME')

**Comment by brentvatne** [comment] 2019-06-08 03:34
duplicate of https://github.com/expo/expo/issues/4474

**Closed by brentvatne** 2019-06-08 03:34 UTC
Labels: bug
