### ISSUE TITLE
Fonts loaded with expo-fonts not available to react-native-screens/native-stack: Unrecognized font family ...

### ISSUE THREAD

**Issue by olapersson** [expo/expo#9795] opened 2020-08-17 15:09 UTC
### Summary of Issue
Expo loaded fonts not available to `react-native-screens/native-stack`, an error is logged and custom fonts does not render: `Unrecognized font family 'Inter_900Black'`. The `@react-navigation/stack` navigator works fine and fonts are usable elsewhere in the app.

Could potentially be a problem with `react-native-screens/native-stack`, there's an issue open at their tracker as well: https://github.com/software-mansion/react-native-screens/issues/572

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
**Target**: iOs
```
  Expo CLI 3.24.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.24.0
```

### Reproducible Demo
Minimal reproduction with a managed workflow: https://github.com/olapersson/expo-font-issue
 
### Steps to Reproduce
Load a font with `expo-fonts` or `@expo-google-fonts` (`useFonts` hook). It will work fine for `<Text />` but not when passed into Screen.options:
```tsx
<Screen
    options={{
        headerTitleStyle: {
            fontFamily: 'Inter_900Black'
        }
    }}
     ...
    />
```

### Expected Behavior vs Actual Behavior
Expected: Custom fonts available for `react-native-screens`
Actual: Custom fonts are not available for `react-native-screens` 

<img width="487" alt="Screen Shot 2020-08-17 at 17 05 47" src="https://user-images.githubusercontent.com/1655608/90411479-25b77c00-e0ac-11ea-894c-e55cc129511e.png">

**Comment by IjzerenHein** [comment] 2021-01-19 11:36
This appears to be an issue with react-native-screens, which has been fixed in https://github.com/software-mansion/react-native-screens/pull/622

**Comment by IjzerenHein** [comment] 2021-01-19 11:41
It looks like this was fixes in `react-native-screens@2.12.0` https://github.com/software-mansion/react-native-screens/releases/tag/2.12.0 SDK 40 contains `react-native-screens@2.15.0` which should resolve this issue.

@olapersson I'm going to close this issue as we believe this should be fixed. Feel free to re-open with additional reproduction info if this is still a problem for you.

**Closed by IjzerenHein** 2021-01-19 11:41 UTC
Labels: Font, needs review

**Comment by olapersson** [comment] 2021-01-19 17:16
Yes, I can confirm it's fixed 👍

**Comment by IjzerenHein** [comment] 2021-01-20 08:52
@olapersson Great!
