### ISSUE TITLE
app is crashing in launchImageLibraryAsync

### ISSUE THREAD

**Issue by supertrank** [expo/expo#2084] opened 2018-08-08 09:07 UTC
open launchImageLibraryAsync again after the click the cancel button in launchImageLibraryAsync, app is crashing.
any solutions?

**Comment by AdamJNavarro** [comment] 2018-08-08 14:46
Hey @supertrank,

When reporting an issue please make sure you provided an appropriate amount of information. Some things that would help this report out would be:

- What platform? On a physical device and or simulator?
- A Snack or Github repo with the minimal amount of relevant code to reproduce the crash
- What SDK you are running?
- What your error or crash logs are showing?

Can you provide that information so we can get to helping you out?

Cheers,

Adam

**Comment by tsapeta** [comment] 2019-09-28 15:48
This seems to be pretty old and probably the SDK version that you used when creating this issue is no longer supported, so I'm gonna close this issue. Please create a new issue if this still happens in any of the currently supported SDK versions.

**Closed by tsapeta** 2019-09-28 15:48 UTC
