### ISSUE TITLE
'Could not encrypt/decrypt the value for SecureStore' error on android app

### ISSUE THREAD

**Issue by Simranjits11** [expo/expo#23426] opened 2023-07-10 07:32 UTC
### Minimal reproducible example

https://snack.expo.dev/@simranjits11/error-with-securestorage

### Summary

**Context**

When trying to get item using `await SecureStore.getItemAsync('mobile')`. It throws an error saying `Could not encrypt/decrypt the value for SecureStore`. The error is very device specific and happens occasionally.

- Message: Error: Could not encrypt/decrypt the value for SecureStore .
- SDK: 47.0.12
- Device: OnePlus 8T (Android 13)

**Stack Trace**

```
Could not encrypt/decrypt the value for SecureStore 
at .construct([native code]:0:0) at .construct([native code]:0:0) 
at .p(index.android.bundle:50:360) 
at .s(index.android.bundle:48:363) 
at .construct([native code]:0:0) 
at .<unknown>(index.android.bundle:395:595) 
at .h(index.android.bundle:395:731)
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.7 - ~/Documents/Projects/realmagic/node_modules/.bin/npm
      Watchman: 2023.02.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/simranjitsingh/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
    npmGlobalPackages:
      eas-cli: 3.15.0
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by nicolascavallin** [comment] 2023-07-13 14:24
Same error on a series of devices like SM-A127F, Pixel 7, SM-F926B, Note 9P, SM-S918B, SM-M135F, etc... with Expo SDK 49 and RN 0.72.1

**Comment by behenate** [comment] 2023-07-19 11:17
@nicolascavallin You managed to reproduce the issue on a lot of devices, do you have any specific steps for reproduction?

**Comment by nicolascavallin** [comment] 2023-07-19 13:45
@behenate I didn't reproduce the error in those devices, I've just extracted the models from Sentry.

We have no specific implementation, just like @Simranjits11 provided repro. We are storing a JSON with 3 keys parsed as a string.

In so many other Android devices everything is working.

I don't know how can I help

**Comment by Simranjits11** [comment] 2023-07-19 14:55
@behenate 
I have noticed that this issue mostly come up if i install a new build (apk) without clearing the app data (by going to app info in device settings) of the previously installed build.

If i clear the app data and then uninstall the previous build before installing the new build, then i don't see the issue. I haven't tested a lot of devices for this behaviour so not sure if this is consistent across all devices but found this interesting. It might help you pin point the issue.

Seems like the previously present app data/cache is causing the issue in the new build.

**Comment by Simranjits11** [comment] 2023-07-19 14:55
> Are you saving the keys with `requireAuthentication` set to `true`?

No

**Comment by lecksfrawen** [comment] 2023-07-19 15:37
I can also repro this issue in SM-T220. 
I'm getting: `Could not encrypt/decrypt the value for SecureStore` in Sentry on these devices.

I have this configuration:
```typescript
const secureOptions = {
  requireAuthentication: false,
  authenticationPrompt: 'Authenticate to Verify Your Identity',
  keychainAccessible: SecureStore.ALWAYS_THIS_DEVICE_ONLY, //
};

const saveAccessToken = async (value: string) => {
  await SecureStore.setItemAsync(
    'accessToken', 
    value,
    secureOptions
  );
  // Do something with the token
}
```

**Comment by carbonatedcoder** [comment] 2023-07-24 15:17
Is there any update or a resolution to this issue? We're seeing this issue on Android devices. At a minimum, Samsung Galaxy S23 and Pixel 7a. No specific secure options used, just the default config. On `expo-secure-store` version 12.1.1, but I'm unsure if it's happening on other versions. Android only issue. Does not happen on iOS.

**Comment by mccraveiro** [comment] 2023-07-30 13:51
@behenate any updates? Our users keep complaining that our app signs them off because of this bug 😢

**Comment by behenate** [comment] 2023-07-31 12:34
I've tried to reproduce the issue on similar devices to the ones mentioned above (Galaxy S22 and Pixel 6), but couldn't reproduce the issue. Using @Simranjits11's suggestion also didn't produce the issue. 
Is it possible for any of you to share the native Android logs, which are created when the issue occurs? There should be a warning logged under "ExpoSecureStore" tag.

**Comment by kirtikapadiya** [comment] 2023-08-02 05:22
Same issue found after upgrading to "expo-secure-store": "~12.1.1" and expo SDK 48 on android device

**Comment by KaisAhmad** [comment] 2023-08-05 00:53
Same issue here after upgrading expo to: 49.0.3 and expo-secure-store to: 12.3.1. It seems like the issue goes away when restarting the app but returns randomly

**Comment by DavidRG13** [comment] 2023-08-18 08:29
Hi,
We are also experiencing this issue, thanks for looking into it
is there a version where the issue happens less frequently or a workaround? I guess an ETA for the fix can not be provided yet, correct?

**Comment by RdC1965** [comment] 2023-09-05 17:21
This issue appears in SM-A146P/DSN and SM-A307FN/DS.

As pointed out by [@behenate](https://github.com/expo/expo/issues/23426#issuecomment-1642246470), the issue disappears if you delete data and cache in the app's Settings.

**Comment by KaisAhmad** [comment] 2023-09-05 17:33
I have not yet tried to downgrade. What has worked for me is to create a function that tries 5 times before failing as a workaround

**Comment by RdC1965** [comment] 2023-09-07 10:00
> I have not yet tried to downgrade. What has worked for me is to create a function that tries 5 times before failing as a workaround.

Ahmad,

I am going to create a function similar to yours, but having emptied the cache+data in my devices I am not able to reproduce the error any longer. Could you please tell me what the response to the secureStore promise is when it is not working properly?

Thank you in advance!

**Comment by edmbn** [comment] 2023-09-14 16:32
I can confirm the same issue on Android. Exact the same error and fixed by deleting data and cache in the app's settings as @behenate described. So if a user uninstalls and then installs again it will always throw the error and force the user to go to app settings to clear data.

**Comment by edmbn** [comment] 2023-09-18 16:30
Ok, so apparently it is normal behavior not to delete Secure Storage and also It is normal not being able to decrypt old data after reinstalling. The solution is to return null in a try/catch and save new data inside the same key. You can always save new data inside the same key but you cannot read old data from an old installation.

**Comment by AJGeel** [comment] 2023-09-27 06:40
Also experiencing this issue. 

Using `expo ~48.0.0`, `expo-secure-store ~12.1.1` and `react-native 0.71.3`. 
Device: OnePlus 5t, still on Android 10. 

Experiencing this error when (manually) installing a new APK of our app. I believe this may be device-related: this issue seems to be a lot more prevalent on the device I test with.

**Comment by edmbn** [comment] 2023-09-27 11:36
> Also experiencing this issue. 
> 
> 
> 
> Using `expo ~48.0.0`, `expo-secure-store ~12.1.1` and `react-native 0.71.3`. 
> 
> Device: OnePlus 5t, still on Android 10. 
> 
> 
> 
> Experiencing this error when (manually) installing a new APK of our app. I believe this may be device-related: this issue seems to be a lot more prevalent on the device I test with. 

As I explained in the comment just before,this is not considered an issue. This is normal behavior. Expo cannot control nor delete secure storage once app is uninstalled, this is handled by the operative system after uninstall. If you had an old version/apk and used secure storage expo cannot and will not delete it when you uninstall the app. Later on if you try to read to the same key/value the data is encrypted from the old version so you cannot read it. The solution is tu just return null inside a try/catch and write again inside the same key/value. Works perfectly.

**Comment by filipecatraia** [comment] 2023-09-27 16:05
Could you at least throw or return a specific, typed error, so we know **that's** what happened? Because otherwise we're seeing this thousands of time on Sentry, and I have to investigate manually to make sure it's “the expected behavior” and not some other issue in that `try/catch` block.

**Comment by KaisAhmad** [comment] 2023-09-27 16:23
> > Also experiencing this issue. 
> > 
> > 
> > 
> > Using `expo ~48.0.0`, `expo-secure-store ~12.1.1` and `react-native 0.71.3`. 
> > 
> > Device: OnePlus 5t, still on Android 10. 
> > 
> > 
> > 
> > Experiencing this error when (manually) installing a new APK of our app. I believe this may be device-related: this issue seems to be a lot more prevalent on the device I test with. 
> 
> As I explained in the comment just before,this is not considered an issue. This is normal behavior. Expo cannot control nor delete secure storage once app is uninstalled. If you had an old version/apk and used secure storage expo cannot and will not delete it when you uninstall the app. Later on if you try to read to the same key/value the data is encrypted from the old version so you cannot read it. The solution is tu just return null inside a try/catch and write again inside the same key/value. Works perfectly. 

This behavior also occurs after an app has been updated (iOS).

**Comment by edmbn** [comment] 2023-09-27 20:34
> Could you at least throw or return a specific, typed error, so we know **that's** what happened? Because otherwise we're seeing this thousands of time on Sentry, and I have to investigate manually to make sure it's “the expected behavior” and not some other issue in that `try/catch` block.

I'm just telling you what I found after some research. I don't work neither maintain any Expo package. That said, if there is any error in the catch section you should return null since the value for the given key couldn't be found, doesn't matter the error. Of course would be great to know the error and of course have a typed error, but that won't change how you should handle it.

**Comment by brianwachira** [comment] 2023-10-17 17:21
Getting the same error on a series of devices like SM-A225F, SM-A307FN and Redmi Note 9 Pro.

Currently trying the `try/catch` fix suggested

**Comment by EugeneKostrikov** [comment] 2023-10-19 19:44
> Ok, so apparently it is normal behavior not to delete Secure Storage and also It is normal not being able to decrypt old data after reinstalling. The solution is to return null in a try/catch and save new data inside the same key. You can always save new data inside the same key but you cannot read old data from an old installation.

Experience the same issue. So far proves to be exactly that. Started to happen after the new install. Though it affected only one of two otherwise identical devices. Also Android.
One alternative way to clear the error is to flush all app data through device settings. It surely isn't a solution for production, but handy if you need to clear it fast and have access to the device.

**Comment by KaisAhmad** [comment] 2023-10-20 14:07
> We are also getting reports of this issue. Can anyone share a code sample of the solution. What operation is to be in the try block?

Not the cleanest solution but it does the job for now.

```js
export const getFromSecureStore = async (key) => {
    let attempts = 0;
    while (attempts < 5) {
        try {
            return await SecureStore.getItemAsync(key);
        } catch (error) {
            attempts++;
        }
    }
    return false;
};

```

**Comment by patrickomeara** [comment] 2023-10-20 14:18
I see. Thanks @KaisAhmad

**Comment by KarlaSaenz** [comment] 2023-11-03 19:47
Also encountering this problem.

Using Expo version 48.0.10, expo-secure-store version 12.1.1, and react-native 0.71.14. This issue seems to be specific to Android 10.

**Comment by AlexMachin1997** [comment] 2023-11-05 17:22
I've just encountered this issue after upgrading to expo sdk version ^49.0.16

**Comment by robertoyoc** [comment] 2023-11-22 19:47
Same with expo sdk 49, expo secure store 12.3.1.
75% percent of our events are android 13.

**Comment by AJGeel** [comment] 2023-12-07 08:08
Hi @behenate, thank you for the update!

> The thing is, if the data has been saved with a previous version of expo-secure-store the chances of similar errors occuring are still the same.

Say, there are devices that have data stored with a previous version of secure-store. If the app updates the data stored in secure-store with the `>= 12.5.0` version, would that resolve / improve the issue?

**Comment by behenate** [comment] 2023-12-07 09:46
@AJGeel If this issue is solved by `12.5.0` (we are still not sure what causes it, but 12.5.0 introduces improvements in areas that are very likely to cause this issue) then yes, re-saving the value with the new version of secure-store should help.

**Comment by git2illa** [comment] 2023-12-09 09:39
- Operating System 

| Kernel  Version | Name  | Rooted | Version |
|-----------|--------------------------------------------------------------|----------------|------------|
| 4.14.116 | Android | no |10(LYA-L09 10.1 .e.289(C432E7RIP5)) |
 
Sentry reported. can't be reproducible... Struggling with it, haven't tried 12.5.0 yet, cause it only happened on the specific physical device which I don't have...

**Comment by jayasme** [comment] 2023-12-20 09:25
Works for me

```typescript
const ATTEMPTS_LIMIT = 3;

const fetchKeychain = async (): Promise<Data | undefined> => {
  let attempts = 0;
  while (attempts < ATTEMPTS_LIMIT) {
    try {
      // eslint-disable-next-line no-await-in-loop
      const data = await SecureStore.getItemAsync(KEY);

      return data;
    } catch (err) {
      if (attempts === 0) {
        logger.error('Failed to fetch keychain', err);
      }
      attempts += 1;
    }
  }
  // reset the keychain if failed too many times and return empty
  await resetKeychain();
  return undefined;
};

const resetKeychain = async (): Promise<void> => {
  await SecureStore.deleteItemAsync(KEY);
};
```

**Comment by DavidAPears** [comment] 2024-02-21 10:25
We have hit this same issue. Any update from Expo? Sentry is reporting 1.6k instances of this now...

**Comment by behenate** [comment] 2024-02-21 11:16
@DavidAPears If you are using `expo-secure-store` >= 12.5.0 can you share a minimal code example in a form of a snack or a repo that replicates what your app is doing (preferably in the same order that your app is doing it)? (e.g. setting a value with/without authentication, overwriting, reading it).

**Comment by NazarDevsMedia** [comment] 2024-02-26 10:04
I've experienced same behaviour and got many sentry errors. As @edmbn already mentioned in https://github.com/expo/expo/issues/23426#issuecomment-1723901477 you shoud use try/catch and delete your entry on error because secure store cant not read the value. After doing so I got zero sentry errors.
here code sample:

```
export const setStoreItemAsync = async (key: SecureStoreKeys, value: string): Promise<void> => {
  try {
    await SecureStore.setItemAsync(key, value)
  } catch (error) {
    console.error('secure store set item error: ', error)
  }
}
```

```
export const deleteStoreItemAsync = async (key: SecureStoreKeys): Promise<void> => {
  try {
    await SecureStore.deleteItemAsync(key)
  } catch (error) {
    console.error('secure store delete item error: ', error)
  }
}
```

```
export const getStoreItemAsync = async (key: SecureStoreKeys): Promise<string | null> => {
  try {
    const item = await SecureStore.getItemAsync(key)
    if (item) {
      console.log(`${key} was used 🔐 \n`)
    } else {
      console.log('No values stored under key: ' + key)
    }
    return item
  } catch (error) {
    console.error('secure store get item error: ', error)
    await deleteStoreItemAsync(key)
    return null
  }
}
```

**Comment by hanyufoodles** [comment] 2024-03-20 08:51
We too have encountered many cases where the store returns null while there was a value stored in.

We store JWT auth tokens with redux thunk action:
```typescript

export const tokensReceived = createAsyncThunk(
  'auth/tokenReceived',
  async ({ access, refresh }: TokenResponse) => {
    await setItemAsync(ACCESS_TOKEN, access);
    await setItemAsync(REFRESH_TOKEN, refresh);
  },
);
```

And retrieve it:
```typescript

export const baseQuery = fetchBaseQuery({
  baseUrl: API_ENDPOINT_URL,
  prepareHeaders: async (headers) => {
    const accessToken = await getItemAsync(ACCESS_TOKEN);
    if (accessToken) {
      headers.set('Authorization', `Bearer ${accessToken}`);
    }
    headers.set('Accept-Language', getLocale());
    return headers;
  },
});
```
The token maybe `null` without throwing error after installing an update of the app.

**Comment by finaldie** [comment] 2024-04-19 17:30
Same issue occurred today, whatever how many times I restart the app, the same error occurred, from read above, I believe delete all storage data would be a workaround solution, but this is totally NOT acceptable for users, could you help to check again and give some advices?

- Device: Google Pixel 8
- expo-secure-store: 12.8.1

Logs from adb shell
```bash
04-19 10:21:59.006 24678 24744 I ReactNativeJS: → Caused by: Could not decrypt the value for key 'SECURE_AUTH_ACCESS_TOKEN_KEY' under keychain 'key_v1'. Caused by: Could not decrypt the value with provided keychain ] code: 'ERR_DECRYPT' }
04-19 10:21:59.029 24678 24744 I ReactNativeJS: '2024-04-19T17:21:59.028Z [ERROR] -', 'In getItemAsync: ', { [Error: Call to function 'ExpoSecureStore.getValueWithKeyAsync' has been rejected.
```

**Comment by finaldie** [comment] 2024-04-30 18:20
After reinstalling the app (Android here), the underlying data is still there, but when we see the above errors, it means the secure store itself cannot self-recover by itself, the developer needs to have a logic to delete those bad records manually.

For user, the above case, they would have the experience that after installing a new version, then everything is gone, they have to re-login, re-store the state whatever they previous done, this sounds like not a good user experience.

That would be great if the secure store can handle it gracefully without interacting with a developer/user. (The best case would be: self-recover by itself and be able to read the data back correctly) Thanks.

**Comment by Alexandros13** [comment] 2024-05-01 08:25
So you are basically telling that the client is forced to retype all the data and configuration that he has done to the app after every install or update?

**Comment by karanmartian** [comment] 2024-05-03 12:20
@Alexandros13 no i don't think that's the case here. unless the securestore library is updated again and becomes incompatible to the current library then only this would be needed. Expo users can correct me if i am wrong here. Hopefully future releases of securestore should account for backwards compatibility.

**Comment by matteo-globe-protocol** [comment] 2024-05-23 15:50
are there any new updates about this issue? It seems to happen after user installs new apk. Only restoring app cache and storage fixes it, but it's not really feasible in production.

**Comment by statico** [comment] 2024-05-23 22:05
Definitely seeing this as well:
![CleanShot 2024-05-23 at 15 04 36](https://github.com/expo/expo/assets/137158/371450da-a2b8-4ced-8908-8e55e6f7937b)

**Comment by achou11** [comment] 2024-06-03 15:21
Not sure if helpful for others, but I found that setting [`android.allowBackup`](https://docs.expo.dev/versions/v50.0.0/config/app/#allowbackup) to `false` in `app.json` led to the error not occuring on my Pixel 2 (Android 11) and Pixel 6 (Android 14).

Wonder if there's something about Expo's dev client workflow that doesn't play well with what's described here: https://developer.android.com/identity/data/autobackup#RestoreSchedule. Haven't looked into it enough to really know but in case someone may have a better idea

**Comment by AlejandroRM-DEV** [comment] 2024-06-04 19:48
We are having the same error, so far only with a single user:

Call to function 'ExpoSecureStore.getValueWithKeySync' has been rejected.
→ Caused by: Could not decrypt the value for key 'password' under keychain 'key_v1'. Caused by: Could not decrypt the value with provided keychain 

OPPO Reno5 Lite CPH2205

I don't know what could be causing it.

**Comment by vishaldhanotiyadev** [comment] 2024-06-05 05:38
I am also facing the same issue but I don't know why I am receiving this error because I am not using `expo-secure-store`. I am using `@react-native-async-storage/async-storage`.

**Comment by NazarDevsMedia** [comment] 2024-06-05 09:14
@behenate IMHO you can close issue and link my comment as right answer.

**Comment by mccraveiro** [comment] 2024-06-05 16:35
@NazarDevsMedia if this catch must always be added, it should be added on expo side and not rely on each developer to know/remember it.

**Comment by behenate** [comment] 2024-06-05 16:58
@mccraveiro This is not that simple. You need a correct keychain to decrypt a value, if you get this error `Caused by: Could not decrypt the value for key 'password' under keychain 'key_v1'. Caused by: Could not decrypt the value with provided keychain` we can't just delete the key-value pair from the store, it's possible that you used an incorrect keychain and using a different one would successfully decrypt the value. Depending on what's the cause for your exceptions it might be possible to implement automatic handling for that specific case, but no one has provided reliable repro instructions so far.

I also believe that returning the exception is better than just returning `null` (as would be the case when handling the error automatically) in most cases as it gives the developer more context as to what is going on.
Nevertheless, I agree that we should add a section to the docs regarding error handling, but I want to make sure that unhandled exceptions here are caused by expected behaviour and not a bug before I do that.

**Comment by ddematheu** [comment] 2024-06-11 06:05
Also seeing this issue.



> I've experienced same behaviour and got many sentry errors. As @edmbn already mentioned in [#23426 (comment)](https://github.com/expo/expo/issues/23426#issuecomment-1723901477) you shoud use try/catch and delete your entry on error because secure store can not read the value. After doing so I got zero sentry errors. here code sample:
> 
> ```
> export const setStoreItemAsync = async (key: SecureStoreKeys, value: string): Promise<void> => {
>   try {
>     await SecureStore.setItemAsync(key, value)
>   } catch (error) {
>     console.error('secure store set item error: ', error)
>   }
> }
> ```
> 
> ```
> export const deleteStoreItemAsync = async (key: SecureStoreKeys): Promise<void> => {
>   try {
>     await SecureStore.deleteItemAsync(key)
>   } catch (error) {
>     console.error('secure store delete item error: ', error)
>   }
> }
> ```
> 
> ```
> export const getStoreItemAsync = async (key: SecureStoreKeys): Promise<string | null> => {
>   try {
>     const item = await SecureStore.getItemAsync(key)
>     if (item) {
>       console.log(`${key} was used 🔐 \n`)
>     } else {
>       console.log('No values stored under key: ' + key)
>     }
>     return item
>   } catch (error) {
>     console.error('secure store get item error: ', error)
>     await deleteStoreItemAsync(key) // HERE!
>     return null
>   }
> }
> ```

This solution didn't work for me. Is there a way to clear the secure store when the app is uninstalled?

**Comment by behenate** [comment] 2024-06-19 12:07
Hi everyone, just an update. We found an issue related to SharedPreferences being backed up by automatic backup and being restored when re-installing the app, which would cause decryption errors as after uninstalling the app the KeyStore is cleared, which makes them impossible to decrypt.

You can expect a PR with a fix this week, next week at the latest. 
Until the fix is out I think the best workaround is to delete the value when the error is thrown as suggested by some users above

**Comment by mwmcode** [comment] 2024-06-19 12:21
That's great! Appreciate the effort and the update!

**Closed** 2024-06-27 10:55 UTC
Labels: Issue accepted

**Comment by behenate** [comment] 2024-07-11 10:26
The fix has been backported to SDK 51 and you can use it with `expo-secure-store 13.0.2` let me know if you are still facing any issues after updating 😄

**Comment by mccraveiro** [comment] 2024-07-11 13:07
@behenate Shouldn't this be reflected on the changelog? 🤔 
https://github.com/expo/expo/blob/main/packages/expo-secure-store/CHANGELOG.md

**Comment by behenate** [comment] 2024-07-11 13:16
@mccraveiro Hmm afaik it should 🕵️ , it seems like something went a bit wrong. It's reflected correctly in the [SDK-51 changelog](https://github.com/expo/expo/blob/sdk-51/packages/expo-secure-store/CHANGELOG.md) though, and the changes are present on npm, so it should work just fine

**Comment by phanvanphuhn** [comment] 2024-07-26 14:17
So that does we need to upgrade expo sdk to version 51 in order to use expo-secure-store 13.0.2?

**Comment by behenate** [comment] 2024-07-26 15:10
@phanvanphuhn It depends which SDK you're on right now. In general `secure-store` doesn't use any new features from `expo-modules-core`, so you should be good to go even with a slightly older SDK version.

**Comment by phanvanphuhn** [comment] 2024-07-26 15:34
![Screenshot 2024-07-26 at 22 31 25](https://github.com/user-attachments/assets/a3cb9b65-af4f-48b7-b321-63f92fdbf569)
![Screenshot 2024-07-26 at 22 31 37](https://github.com/user-attachments/assets/8be21b84-f043-4967-89bb-21d98d593d76)

I am using expo 49.0.0, I was using "expo-secure-store": "~12.3.1", but when upgrade to "~13.0.2" I facing this issue.

A problem occurred evaluating project ':expo-secure-store'.
> Could not find method useCoreDependencies() for arguments [] on project ':expo-secure-store' of type org.gradle.api.Project.

**Comment by phanvanphuhn** [comment] 2024-07-26 15:37
{
  "name": "@impt-io/mobile",
  "version": "1.0.0",
  "main": "expo-router/entry",
  "scripts": {
    "prebuild": "yarn dotenv:decrypt",
    "build": "EXPO_USE_METRO_WORKSPACE_ROOT=1 expo export --output-dir ./build --platform all",
    "dev": "yarn start",
    "doctor": "npx expo-doctor",
    "format": "prettier --write",
    "lint": "eslint --cache --cache-location=\".eslint-cache\" --fix",
    "start": "EXPO_USE_METRO_WORKSPACE_ROOT=1 expo start --dev-client",
    "start2": "EXPO_USE_METRO_WORKSPACE_ROOT=1 expo start --dev-client --$(jq -r '.apps.mobile.emulator' ../../impt.json)",
    "eas-build-pre-install": "cd ../../ && CI=1 yarn install && yarn turbo run build --filter=mobile",
    "// DOTENV": "echo 'used for managing the dotenv vaults, these scripts are the same across all projects in the workspace'",
    "dotenv:pull": "../../pull-dotenv.sh",
    "dotenv:decrypt": "../../decrypt-dotenv-key.sh",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "buildDev": "eas build --platform all --profile development",
    "buildProd": "eas build --platform all --profile production"
  },
  "dependencies": {
    "@ethersproject/shims": "^5.7.0",
    "@expo/prebuild-config": "~6.2.4",
    "@expo/vector-icons": "^13.0.0",
    "@gluestack-ui/themed-native-base": "^0.1.107-alpha2",
    "@gorhom/bottom-sheet": "^4",
    "@hookform/resolvers": "^3.0.1",
    "@impt-io/consts": "*",
    "@impt-io/lib": "*",
    "@impt-io/singular-expo": "*",
    "@impt-io/tsconfig": "*",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/datetimepicker": "7.2.0",
    "@react-native-masked-view/masked-view": "0.2.9",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "@tanstack/query-async-storage-persister": "^4.27.1",
    "@tanstack/react-query": "^4.29.19",
    "@tanstack/react-query-persist-client": "^4.28.0",
    "axios": "^1.2.0",
    "base-64": "^1.0.0",
    "convert-units": "^2.3.4",
    "country-code-emoji": "^2.3.0",
    "date-fns": "^2.29.3",
    "dotenv-vault-core": "^0.7.0",
    "eslint-config-universe": "^12.0.0",
    "expo": "^49.0.0",
    "expo-av": "~13.4.1",
    "expo-constants": "~14.4.2",
    "expo-dev-client": "~2.4.13",
    "expo-device": "~5.4.0",
    "expo-font": "~11.4.0",
    "expo-image-manipulator": "~11.3.0",
    "expo-image-picker": "~14.3.2",
    "expo-linear-gradient": "~12.3.0",
    "expo-linking": "~5.0.2",
    "expo-local-authentication": "~13.4.1",
    "expo-location": "~16.1.0",
    "expo-notifications": "~0.20.1",
    "expo-router": "2.0.0",
    "expo-secure-store": "~13.0.2",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-tracking-transparency": "~3.1.0",
    "expo-updates": "~0.18.19",
    "immer": "^10.0.2",
    "native-base": "^3.4.28",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.40.0",
    "react-native": "0.72.10",
    "react-native-codegen": "^0.71.5",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-google-places-autocomplete": "^2.5.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-maps": "1.7.1",
    "react-native-open-maps": "^0.4.3",
    "react-native-reanimated": "~3.3.0",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-share": "^10.0.2",
    "react-native-svg": "13.9.0",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-webview": "13.2.2",
    "singular-react-native": "^3.1.19",
    "use-debounce": "^9.0.3",
    "utility-types": "^3.10.0",
    "uuid": "^3.4.0",
    "zod": "^3.21.4",
    "zustand": "^4.3.8"
  },
  "devDependencies": {
    "@babel/core": "^7.18.13",
    "@impt-io/eslint-config-custom": "*",
    "@types/convert-units": "^2.3.6",
    "@types/react": "^18.0.25",
    "esbuild": "^0.19.2",
    "eslint": "^8.47.0",
    "metro-minify-esbuild": "^0.2.0",
    "prettier": "^2.8.8",
    "typescript": "^5.1.3"
  }
}

I am using "expo": "^49.0.0", with "expo-secure-store": "~12.3.1" but when I upgrade to "expo-secure-store": "~13.0.2". I am facing android issue:

Build file '../node_modules/expo-secure-store/android/build.gradle' line: 9

A problem occurred evaluating project ':expo-secure-store'.
> Could not find method useCoreDependencies() for arguments [] on project ':expo-secure-store' of type org.gradle.api.Project.

**Comment by behenate** [comment] 2024-07-29 08:26
@phanvanphuhn Oh yes, we changed the way gradle dependencies are handled in sdk 50 and dropped the legacy way in 51, can you try to replace the contents of expo-secure-store `build.gradle` with the contents of the one from the sdk-49 branch
https://github.com/expo/expo/blob/sdk-49/packages/expo-secure-store/android/build.gradle (remember to replace `version` and `versionName` with 13.0.2)
This should work, although the recommended way would be to bump expo to sdk-51 when possible

**Comment by blackstalk** [comment] 2024-10-11 19:24
Hi All I fixed this issue with MMKV

 ```
 const tokenCache = {
    async getToken(key) {
      try {
        return storage.getString(key);
      } catch (err) {
        return null;
      }
    },
    async saveToken(key, value) {
      try {
        return storage.set(key, value);
      } catch (err) {
        return;
      }
    },
  };
```

**Comment by timmyjose** [comment] 2024-10-15 04:25
> Hi All I fixed this issue with MMKV
> 
> ```
> const tokenCache = {
>    async getToken(key) {
>      try {
>        return storage.getString(key);
>      } catch (err) {
>        return null;
>      }
>    },
>    async saveToken(key, value) {
>      try {
>        return storage.set(key, value);
>      } catch (err) {
>        return;
>      }
>    },
>  };
> ```

@blackstalk `react-native-mmkv` does not encrypt the values though, right?

**Comment by statico** [comment] 2024-10-15 16:00
`react-native-mmkv` offers an encrypted store, yes. But we found their encrypted option to be less reliable than SecureStore. This was 6-8 months ago, however, and things might have improved since then.

**Comment by wobsoriano** [comment] 2024-10-30 15:53
> @mccraveiro Hmm afaik it should 🕵️ , it seems like something went a bit wrong. It's reflected correctly in the [SDK-51 changelog](https://github.com/expo/expo/blob/sdk-51/packages/expo-secure-store/CHANGELOG.md) though, and the changes are present on npm, so it should work just fine

> Data saved with expo-secure-store is no longer lost upon ejecting, if you first upgrade your app to SDK 41 before ejecting

Looks like a typo, should be SDK 51 right?

**Comment by behenate** [comment] 2024-10-31 00:55
@wobsoriano Yes that's a typo sorry

**Comment by behenate** [comment] 2024-10-31 00:59
@wobsoriano Hi I'm not sure what you mean, that is a changelog note from three years ago 🤔

**Comment by DanielAnoka** [comment] 2024-12-06 10:07
i keep getting this error 
 (NOBRIDGE) LOG  No values stored under key: __clerk_client_jwt
 (NOBRIDGE) LOG  __clerk_client_jwt was used 🔐
 (NOBRIDGE) ERROR  {
  "status": 400,
  "clerkError": true,
  "errors": [
    {
      "code": "captcha_missing_token",
      "message": "Missing CAPTCHA token",
      "longMessage": "Missing CAPTCHA token",
      "meta": {}
    }
  ]
}

**Comment by Doojy-cg** [comment] 2025-03-24 08:38
How do i fix this error

ta": {}\n}'
03-24 11:29:44.742  8051  8129 E ReactNativeJS: 'SecureStore get item error: ', { [Error: Call to function 'ExpoSecureStore.getValueWithKeyAsync' has been rejected.
03-24 11:29:44.742  8051  8129 E ReactNativeJS: → Caused by: The 2nd argument cannot be cast to type expo.modules.securestore.SecureStoreOptions (received class com.facebook.react.bridge.ReadableNativeMap)
03-24 11:29:44.742  8051  8129 E ReactNativeJS: → Caused by: java.lang.NullPointerException] code: 'ERR_UNEXPECTED' }
03-24 11:29:44.747  8051  8129 W ReactNativeJS: { [Error: Call to function 'ExpoSecureStore.deleteValueWithKeyAsync' has been rejected.
03-24 11:29:44.747  8051  8129 W ReactNativeJS: → Caused by: The 2nd argument cannot be cast to type expo.modules.securestore.SecureStoreOptions (received class com.facebook.react.bridge.ReadableNativeMap)
03-24 11:29:44.747  8051  8129 W ReactNativeJS: → Caused by: java.lang.NullPointerException] code: 'ERR_UNEXPECTED' }
03-24 11:29:44.748  8051  8129 I ReactNativeJS: 'eeorrr', '{\n  "pathRoot": "/client/sign_ins",\n  "status": null,\n  "supportedIdentifiers": [],\n  "supportedFirstFactors": [],\n  "supportedSecondFactors": null,\n  "firstFactorVerification": {\n    "pathRoot": "",\n    "status": null,\n    "strategy": null,\n    "nonce": null,\n    "message": null,\n    "externalVerificationRedirectURL": null,\n    "attempts": null,\n    "expireAt": null,\n    "error": null,\n    "verifiedAtClient": null\n  },\n  "secondFactorVerification": {\n    "pathRoot": "",\n    "status": null,\n    "strategy": null,\n    "nonce": null,\n    "message": null,\n    "externalVerificationRedirectURL": null,\n    "attempts": null,\n    "expireAt": null,\n    "error": null,\n    "verifiedAtClient": null\n  },\n  "identifier": null,\n  "createdSessionId": null,\n  "userData": {}\n}'

**Comment by arika79** [comment] 2025-05-30 06:58
@Doojy-cg 
I just ran into the exact same issue when I enabled both `minifyEnabled = true` and `shrinkResources = true`.

My app crashed with the following errors:

```
The 2nd argument cannot be cast to type expo.modules.securestore.SecureStoreOptions  
(received class com.facebook.react.bridge.ReadableNativeMap)

The 3rd argument cannot be cast to type expo.modules.securestore.SecureStoreOptions  
(received class com.facebook.react.bridge.ReadableNativeMap)
```

Both SecureStore.getItemAsync and SecureStore.setItemAsync failed with these errors in my case as well.

After trying several things, the issue was resolved by adding the following entries to my `proguard-rules.pro` file:

```
-keep class expo.modules.securestore.** { *; }
-keep class expo.modules.core.** { *; }
-keep class expo.modules.kotlin.** { *; }
-keep class com.facebook.react.bridge.** { *; }
-keep class com.facebook.react.bridge.ReadableNativeMap { *; }

```

As a temporary workaround, I also confirmed that disabling both minifyEnabled and shrinkResources avoids the crash. But since I wanted to keep the benefits of code and resource optimization, adding the proper Proguard rules was the better solution in my case.

**Comment by hadassaplotnik** [comment] 2025-07-24 18:38
I am getting this error now when i updated expo SDK from 52 to 53.
Any ideas?
