### ISSUE TITLE
WebRTC support

### ISSUE THREAD

**Issue by merrittholmes7** [expo/expo#6347] opened 2019-11-21 13:15 UTC
Hi,

Please can we get an idea of when WebRTC will be supported in expo. This has been a request for 2 years now and is 7th in the top list and yet there appears to be no replies of any kind around when to expect it. Some guidance . on this would be appreciated as at the moment its the single reason why I can't leverage expo.

Thanks

Mike

### Please note that feature requests opened in the core Expo repository will be closed.

  Thanks for helping us make Expo even better! 😀
  Unfortunately, this is not the right place for feature requests. Please find and upvote your feature (or create a new one) at https://expo.canny.io instead.

**Comment by cruzach** [comment] 2019-11-21 14:57
Hi! Good news is right now, you can use the bare workflow for this since you can bring in any native module you need. We're working hard to bring the bare workflow into feature parity with the managed workflow. This is probably the best option for you since we don't have plans surrounding WebRTC support yet. Once we do, we'll be sure to update the canny!

Closing this as it's not a bug report, and it says in the template feature requests will be closed

**Closed by cruzach** 2019-11-21 14:57 UTC
