### ISSUE TITLE
No member named 'iterateOverValues' in 'facebook::react::RawProps' error on react-native 0.76 new architecture

### ISSUE THREAD

**Issue by ustuncem** [expo/expo#32345] opened 2024-10-25 10:51 UTC
### Minimal reproducible example

https://github.com/ustuncem/expo-modules-bug

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

I created a bare React Native project and added Expo modules. The project fails to compile in Xcode due to an error in the ExpoViewProps.cpp file.

`/node_modules/expo-modules-core/common/cpp/fabric/ExpoViewProps.cpp:20:12: No member named 'iterateOverValues' in 'facebook::react::RawProps'`

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.10.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.9.0 - /opt/homebrew/bin/npm
      Watchman: 2024.10.21.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.38 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.0 => 0.76.0 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✖ Check native tooling versions
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check Expo config (app.json/ app.config.js) schema
✖ Check that native modules use compatible support package versions for installed Expo SDK
✖ Check that packages match versions required by installed Expo SDK

Detailed check results:

Expected package metro@~0.80.8
Found invalid:
  metro@0.81.0
  (for more info, run: npm why metro)
Expected package metro-resolver@~0.80.8
Found invalid:
  metro-resolver@0.81.0
  (for more info, run: npm why metro-resolver)
Expected package metro-config@~0.80.8
Found invalid:
  metro-config@0.81.0
  (for more info, run: npm why metro-config)
Advice: Upgrade dependencies that are using the invalid package versions.

Error: Problem validating fields in /Users/logo/Desktop/AwesomeProject/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • should NOT have additional property 'displayName'.

Cocoapods version check failed. Cocoapods may not be installed or there may be an issue with your Cocoapods installation. Installing version 1.15.2 or higher is recommended.

(node:79795) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The following packages should be updated for best compatibility with the installed expo version:
  react@18.3.1 - expected version: 18.2.0
  react-native@0.76.0 - expected version: 0.74.5
  @types/react@18.3.12 - expected version: ~18.2.79
  typescript@5.0.4 - expected version: ~5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```

**Comment by Gnative** [comment] 2024-10-25 11:07
Looks like this could already be resolved and merged into #main https://github.com/expo/expo/pull/31580/files ?

**Comment by ustuncem** [comment] 2024-10-25 11:40
> Looks like this could already be resolved and merged into #main https://github.com/expo/expo/pull/31580 ? 

I tested it like an hour or two ago. Do I need add expo from github main repo to package.json?

**Comment by Gnative** [comment] 2024-10-25 11:53
Hi @ustuncem I'm just looking. It is in Expo SDK 52 which is in beta preview for the next 2 weeks and looks to have more support for new architecture. https://expo.dev/changelog/2024/10-24-sdk-52-beta , see end of page for upgrade instructions. 

I think the truth is with any big upgrade like that there is time for the update to settle before looking to use it in properly.

**Comment by ustuncem** [comment] 2024-10-25 11:55
@Gnative yeah you are right. Ok then I will keep my original project in v0.75 for now and test the beta version on my free time. Thanks for the help!

**Comment by Gnative** [comment] 2024-10-25 11:56
We are all excited about the new updates..

**Comment by gabrieldonadel** [comment] 2024-10-25 20:06
Hi @ustuncem , it seems that you shared a project that does not use expo, can you provide a valid reproducible example?

**Closed** 2024-10-25 20:06 UTC
Labels: incomplete issue: missing or invalid repro, needs review

**Comment by ustuncem** [comment] 2024-10-25 20:15
@gabrieldonadel hello, project is using bare react native flow and it added expo as modules. I encountered with the error on this setup.

**Comment by gabrieldonadel** [comment] 2024-10-25 23:39
> @gabrieldonadel hello, project is using bare react native flow and it added expo as modules. I encountered with the error on this setup.

Can you provide a link to a minimal reproducible example that includes Expo as a dependency?

**Comment by Yurii-Lutsyk** [comment] 2024-11-04 18:51
+1

**Comment by vineyardbovines** [comment] 2024-11-06 22:34
Still seeing this in both SDK 52 and 51 with new architecture, fresh projects.

[Repro](https://github.com/vineyardbovines/expo-iterateOverValues-bug). 

Steps:
1. `npx create-expo-app@latest -e with-new-arch` 
2. `npx expo prebuild -p ios`
3. Build in xcode to get full error

**Comment by Yurii-Lutsyk** [comment] 2024-11-06 22:42
@vineyardbovines 
I've also had this error on the latest expo version 52, but i fixed it somehow. Please check your ruby and gem versions are updated to the latest stable versions, also make sure you set up everything properly and installed the pods properly. Or migrate from old expo version to the 52 properly

**Comment by VanyaShumilo1** [comment] 2024-11-29 09:45
i changed my expo version from 51 to 52 and it works for me.
"expo": "^52.0.0",

**Comment by dominictobias** [comment] 2024-12-05 03:24
I created a brand new project just now as per https://docs.expo.dev/tutorial/create-your-first-app/ with 0 changes (already have RN running on machine on another project) and ran into this issue too. Tried prebuild and running from XCode not lucj either.

**Comment by dominictobias** [comment] 2024-12-05 03:39
My issue was that I installed a new Expo 52 into a monorepo with one that's still on 51. For some reason (maybe Bun's fault), the sub dependencies weren't correct (as revealed by `expo-doctor`)
