### ISSUE TITLE
iOS min SDK requirement - March 2019

### ISSUE THREAD

**Issue by mnemotiv** [expo/expo#3125] opened 2019-01-05 21:03 UTC
Just published and updated few apps on appstore and receiving this email after uploading IPA files.

Seems like Expo build servers will need update.

```
Dear Developer,
We identified one or more issues with a recent delivery for your app, "Secret". Your delivery was successful, but you may wish to correct the following issues in your next delivery: 
SDK Version Issue - This app was built with the iOS 12.0 SDK. Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later. 
After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect. 
Best regards,
The App Store Team
```

**Comment by sjchmiela** [comment] 2019-01-07 16:13
Thank you for submitting the issue! We will update our Xcode builders on time. 🙂

For the record—this is a non-critical message, just a warning from Apple, so if your (or anyone else's) app triggers such notification, one can still submit it to Testflight or App Store.

**Comment by dsokal** [comment] 2019-01-08 15:01
@mnemotiv should be fixed now, all you need to do is to rebuild your app (`expo build:ios`) and upload .ipa again - the warning should go away.

**Closed by dsokal** 2019-01-08 15:01 UTC
Labels: project: turtle

**Comment by SimenB** [comment] 2019-01-08 15:08
I got the warning an hour ago when uploading a version build with sdk 32. Maybe I did something wrong?

**Comment by dsokal** [comment] 2019-01-08 15:10
@SimenB I deployed the fix 15 minutes ago (just before writing my previous message), so that's the reason why you got the warning an hour ago :)

**Comment by SimenB** [comment] 2019-01-08 15:11
Hah, I thought it was part of the build from my side. But it of course makes sense that this required a change in your build server, not on my side. Thanks!

**Comment by dsokal** [comment] 2019-01-08 15:14
@SimenB Also, make sure you're using SDK 32.

**Comment by JB-CHAUVIN** [comment] 2019-01-19 19:32
@dsokal, I built my app 5 minutes ago and got the same problem...

SDK Version Issue - This app was built with the iOS 12.0 SDK. Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later.

Are you saying that to fix this problem, SDK need to be 32 ? It won't work for SDK 31 ?

**Comment by rthernes** [comment] 2019-01-24 17:44
I just did a build using SDK 32 and got the warning again. I was not getting it yesterday.

**Comment by msevestre** [comment] 2019-01-24 19:11
@dsokal I just did a build as well using SDK 32 and I received the warning upon submitting for testing via TestFlight. I think there is still something funky going on

**Comment by dsokal** [comment] 2019-01-25 13:44
Hello,
the regression which you were experiencing should be fixed now. We also updated SDK 30 and 31. All you need to do now is to build your apps again Sorry for the inconvenience!

**Comment by rakibtg** [comment] 2019-03-06 11:46
Hello @dsokal 
Will Expo SDK 29.0.0 has this fix as well? We are facing same warning message as of today 6 March! 
I hope SDK 29 is good to go with this CLI patch?

**Comment by dsokal** [comment] 2019-03-06 11:47
Hello, 
we don't have plans to fix this in any SDK version < 30. Sorry!

**Comment by rakibtg** [comment] 2019-03-07 06:43
Hi @dsokal, is there any possible workaround or the only option would be to upgrade the SDK to 31?

**Comment by dsokal** [comment] 2019-03-07 09:17
Hey,
you should upgrade SDK to the latest, which is 32 at the moment. I'm afraid i don't know any workaround for this warning.
