### ISSUE TITLE
LocationTaskConsumer.maybeStartForegroundService ( android.app.ForegroundServiceStartNotAllowedException - startForegroundService() not allowed due to mAllowStartForeground )

### ISSUE THREAD

**Issue by MenamAfzaal** [expo/expo#26783] opened 2024-01-30 05:50 UTC
### Minimal reproducible example

https://github.com/frizhub-repo/crash_reports.git

### Summary

# Steps to reproduce

The problem is not present in debug mode; it's specifically happening in production.
Based on your Crashlytics report these are the stats

<img width="1787" alt="Screenshot 1402-11-10 at 10 41 28 AM" src="https://github.com/expo/expo/assets/122887940/1bfa0d18-f11e-4db4-a4e8-ca7b2c6ac88f">

<img width="1790" alt="Screenshot 1402-11-10 at 10 41 43 AM" src="https://github.com/expo/expo/assets/122887940/ee92019a-8188-4ca5-a11d-e1163a7feda5">

It happens on real devices and as the 100% of stats show that this happens when device is in background state

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.6.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.8.1 - /usr/local/bin/npm
      Watchman: 2024.01.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.22 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    Expo Workflow: bare

**Comment by brentvatne** [comment] 2024-02-01 02:56
this appears to be a duplicate of #26782, given that you provided the same repository link

**Closed by brentvatne** 2024-02-01 02:56 UTC
Labels: needs review
