### ISSUE TITLE
[Audio][Android] sound.playAsync results in "AudioTrack init failed" after couple of successful tries

### ISSUE THREAD

**Issue by LukasNavickas** [expo/expo#5376] opened 2019-08-18 17:42 UTC
I have a game that uses many, very small audio files (.wav).
At the beginning of the game, the sounds play perfectly fine, but couple of minutes after, I start getting the following issue:
![image](https://user-images.githubusercontent.com/13028072/63228214-41b1e480-c1f0-11e9-9439-f0173f5bf6e8.png)
My code:
![image](https://user-images.githubusercontent.com/13028072/63228217-52625a80-c1f0-11e9-935d-33e84baded4f.png)
Can you tell me what is the issue and if there is a workaround?

P.S. I'm getting the following warning/error on the phone:
Possible Unhandled Promise Rejection (id: 0)L
Error: com.google.android.exoplayer2.b.h$b:
AudioTrack Init failed. 0

**Comment by cruzach** [comment] 2019-08-19 15:56
Hi! we need a little more information here

- the SDK you're using (running `expo diagnostics` in your project directory and pasting the output here will do)
- a reproducible demo that shows this behavior (you can share a repo that can then be cloned and run locally, or even better create a [snack](https://snack.expo.io/)

**Comment by LukasNavickas** [comment] 2019-08-19 16:25
Please find the following snack: https://snack.expo.io/@lukis/audio-issues
Try clicking fast between the three buttons (for 1-3 min). For me, it stops after a couple of successful sounds.

Results from expo-diagnostics:
![image](https://user-images.githubusercontent.com/13028072/63282230-a469b580-c2ae-11e9-8624-4d4a8b3c6c9c.png)

**Comment by cruzach** [comment] 2019-08-19 17:54
And this is Android-only, right?

**Comment by LukasNavickas** [comment] 2019-08-20 07:15
Yes, Android only. It happens on my Ulefone Armor 6E (Android 9.0). Let me test on other devices.

**Comment by HeathSilcox** [comment] 2019-08-29 09:51
Hey

I've got the same issue.

Here's the code : 
```Javascript
export default () => {
    const handlePress = async () => {
        const soundObject = new Audio.Sound();
        try {
            await soundObject.loadAsync(require('../../assets/hihat.mp3'));
            await soundObject.playAsync();
        } catch (error) {
            console.warn(error);
        }

    };

    return (
        <TouchableHighlight style={styles.buttons.btn} onPress={handlePress} underlayColor="#D44848">
            <Text style={[styles.text.whiteBold, styles.text.large, styles.text.center]}>Start</Text>
        </TouchableHighlight>
    );
};
```
Here's the console log : 
```sh
com.google.android.exoplayer2.b.h$b: AudioTrack init failed: 0, Config(44100, 4, 42464)
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:4 in __invokeCallback
- ... 4 more stack frames from framework internals
```
Here's the warning displayed on my mobile : 
```
{"framesToPop":1,"nativeStackAndroid":[],"userInfo":null,"code":"E_LOAD_ERROR","line":2720,"column":26,"sourceURL":"http://packager.7g-xpq.anonymous.native-metronome.exp.direct/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false"}
```

And the expo diagnostics : 
```sh
  Expo CLI 3.0.10 environment info:
    System:
      OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.10
```

My mobile is a Samsung A5 2016 (SM-A510F), Android Version : 7.0.

**Comment by BJW** [comment] 2019-09-04 18:01
I am having the same problem. @sjchmiela @mczernek is there a timeframe on a fix for this issue ? Or could you provide any suggestions for an alternate solution ?

**Comment by sjchmiela** [comment] 2019-09-04 18:27
Sorry, I don't think we can estimate fixing this issue anyhow reliably. I've heard of people running WebViews playing audio through browser Audio API — that worked well for them as a workaround (even though it sounds silly)

**Comment by BJW** [comment] 2019-09-06 16:35
@sjchmiela thanks for the quick reply. Just so I'm sure I understand this. As of right now the expo-av audio functionality is completely broken for Android ? Is that correct ? or is there another method of implementation that will avoid Android dropping the files ? I saw the WebView solution on some other threads. Thanks for the suggestion. I'm not sure it's a sustainable long term solution though ?

**Comment by sjchmiela** [comment] 2019-09-06 17:07
I would phrase it a little different — its functionality is flaky. The process of reimplementing `expo-av` in a more error-prone way is undergoing, unfortunately it's a huge project and takes some time.

**Comment by BJW** [comment] 2019-09-06 17:16
@sjchmiela thanks for the info. Totally understandable that it's a huge undertaking. Unfortunately I need to fix the issue immediately so I guess I'll have to look at detaching the project. That was the decision I was trying to make. Thanks for working on it. I'll look forward to a new and imporved expo-av in the future.

**Comment by pixel-rain** [comment] 2019-10-06 09:44
I have the very same error, my app plays single notes, it stops playing them after few minutes and gives that `com.google.android.exoplayer2.b.h$b: AudioTrack init failed: 0, Config(44100, 4, 28288)` error. Android too, I ran it on my Xiaomi Redmi 4X, Android 7.1.2

  Expo CLI 2.19.4 environment info:
    System:
      OS: Windows 7
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501

Apparently I will have to eject too because I doubt that WebView workaround would help me here...

**Comment by creativemind1** [comment] 2019-10-08 16:30
I'm also facing the same issues

**Comment by BJW** [comment] 2019-10-08 18:30
In the end detaching wasn't so bad. For me much better than a potentially hacky. WebView solution. I detached and have been using react-native-sound & react-native-video with good results.

**Comment by obellce** [comment] 2019-10-11 09:27
It seems this issue occurs if you load too many sound objects, but don't unload them after use.

If you're playing the sound just once, you can do something like:
```
const status = await sound.playAsync();

setTimeout(() => {
  sound.unloadAsync();
}, status.playableDurationMillis + 1000);
```
Wait until just after the sound has finished, then unload (the extra 1s ensures it won't clip the end of the audio off).

If you have concerns about this happening due to the sound playing too many times in quick succession (e.g. tapping a button way too fast), best you can do is either:
- Use a single sound object, so it can't be playing more than once (you'll need to work out managing when to set its progress back to zero).
- Throttle the sound event, with something like Lodash's `throttle()`, so that it can't be triggered too quickly.

**Comment by creativemind1** [comment] 2019-10-11 13:48
> In the end detaching wasn't so bad. For me much better than a potentially hacky. WebView solution. I detached and have been using react-native-sound & react-native-video with good results.

I have also detached expo in order to use react-native-sound but unfortunately that is also causing issues like _duration object getting in negative.

**Comment by creativemind1** [comment] 2019-10-11 13:49
> It seems this issue occurs if you load too many sound objects, but don't unload them after use.
> 
> If you're playing the sound just once, you can do something like:
> 
> ```
> const status = await sound.playAsync();
> 
> setTimeout(() => {
>   sound.unloadAsync();
> }, status.playableDurationMillis + 1000);
> ```
> 
> Wait until just after the sound has finished, then unload (the extra 1s ensures it won't clip the end of the audio off).
> 
> If you have concerns about this happening due to the sound playing too many times in quick succession (e.g. tapping a button way too fast), best you can do is either:
> 
> * Use a single sound object, so it can't be playing more than once (you'll need to work out managing when to set its progress back to zero).
> * Throttle the sound event, with something like Lodash's `throttle()`, so that it can't be triggered too quickly.

Sounds good but in case of component unmounting there will not be a chance to unload the playing audio.

**Comment by juanriglos** [comment] 2019-10-12 01:36
i need help with this, please any solution means a lot

**Comment by BJW** [comment] 2019-10-12 01:43
@juanriglos there are several options for a solution in the comments above.

**Comment by juanriglos** [comment] 2019-10-12 03:31
please give me one, i dont understand the solution

**Comment by pixel-rain** [comment] 2019-10-13 10:29
> It seems this issue occurs if you load too many sound objects, but don't unload them after use.
> 
> If you're playing the sound just once, you can do something like:
> 
> ```
> const status = await sound.playAsync();
> 
> setTimeout(() => {
>   sound.unloadAsync();
> }, status.playableDurationMillis + 1000);
> ```
> 
> Wait until just after the sound has finished, then unload (the extra 1s ensures it won't clip the end of the audio off).
> 
> If you have concerns about this happening due to the sound playing too many times in quick succession (e.g. tapping a button way too fast), best you can do is either:
> 
> * Use a single sound object, so it can't be playing more than once (you'll need to work out managing when to set its progress back to zero).
> * Throttle the sound event, with something like Lodash's `throttle()`, so that it can't be triggered too quickly.

thank you! it worked! <3

p.s. i use typescript though and it displays a type error there, but it still works, anyway i already know the expected duration and can set it manually, but still, wanted to note
![typescript](https://user-images.githubusercontent.com/49060938/66714275-0e5a9300-edf8-11e9-8a06-8bef0fd1b9a0.png)

**Comment by obellce** [comment] 2019-10-14 09:00
> Sounds good but in case of component unmounting there will not be a chance to unload the playing audio.

@creativemind1 If it's unloaded in the same function like in the example, it'll still complete that async function, and unload as intended. If the sound object is stored on the component, you can unload it either in `componentWillUnmount()` or with `useEffect()` if using hooks.

**Closed** 2019-11-19 08:37 UTC
Labels: Audio, project: android-runtime
