### ISSUE TITLE
Plugin with id ‘maven’ not found.

### ISSUE THREAD

**Issue by mantu-designersx** [expo/expo#12774] opened 2021-04-29 05:41 UTC
### Summary

I Just upgraded react-native from 0.62.0 to 0.63.0 and all was working fine. But after I integrated expo unimodules in my bare expo project when I try to make the build for android then expo dependencies give me the below error.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

React-native : 0.63.0
Expo Unimodules : 0.13.3
Gradle version : 7.0
Project : Typescript

buildToolsVersion = "30.0.0"
minSdkVersion = 21
compileSdkVersion = 30
targetSdkVersion = 30

### Reproducible demo or steps to reproduce from a blank project

- Integrate it for the bare project after upgrading to 0.63.0 from 0.62.0 .

### Error

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/ios/Desktop/Old MacMini Data/Desktop/React Live Projects/afridom/node_modules/expo-constants/android/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':expo-constants'.
> Plugin with id 'maven' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':expo-constants'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
```

**Comment by mantu-designersx** [comment] 2021-04-29 05:43
Here is the error.

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/ios/Desktop/Old MacMini Data/Desktop/React Live Projects/afridom/node_modules/expo-constants/android/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':expo-constants'.
> Plugin with id 'maven' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':expo-constants'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
```

**Comment by byCedric** [comment] 2021-04-29 11:50
Hi @mantu-designersx! Could you provide a reproducible example with this error? It seems like this is unrelated to unimodules, but more related to incorrect gradle version or missing gradle system features. If you can't provide a repro, it might be useful to compare the gradle differences with a new project using `npx create-react-native-app`.

**Comment by gilons** [comment] 2021-05-03 01:40
me too I'm currently stuck with the same issue.
I'm on Mac book pro 2020 Catalina 10
node 16
gradle 7 

any help will be highly appreciated

**Comment by brentvatne** [comment] 2021-05-03 01:41
@gilons, the same comment that @byCedric shared above also applies to you :)

> Hi @mantu-designersx! Could you provide a reproducible example with this error? It seems like this is unrelated to unimodules, but more related to incorrect gradle version or missing gradle system features. If you can't provide a repro, it might be useful to compare the gradle differences with a new project using npx create-react-native-app.

**Comment by gilons** [comment] 2021-05-03 01:43
Ok thanks 
Let me see what to do.

**Comment by gilons** [comment] 2021-05-03 01:57
Hi @brentvatne  thanks for your suggestion. à
The problem actually was with the Gradle version. I just had to downgrade my Gradle version to version 6.4.1 using [sdk-manager](http://sdkman.io/) while following this [guide](https://medium.com/@czerwinb/how-to-install-a-specific-gradle-version-on-your-mac-beab35051ee8)

then, `gradle wrapper` command worked

**Comment by officialkirill** [comment] 2021-05-04 16:24
I stumbled here via google search and just wanted to let you guys know that the 'maven' plugin was deprecated in gradle 7. The suggested replacement is maven-publish. I belive the previous plugin had a bit different purpose. I could be wrong, though.

**Comment by gilons** [comment] 2021-05-04 16:31
Yep, but react native has not yet updated with that plugin 😔

**Comment by jailsonpaca** [comment] 2021-05-08 02:17
+1

**Comment by RupamShaw** [comment] 2021-05-12 03:15
how to start android studio 4.2 with
``` A problem occurred evaluating project ':expo-application'.
> Plugin with id 'maven' not found.
```

**Comment by seanraad123** [comment] 2021-05-20 15:20
@gilons this worked for me ty

**Comment by gilons** [comment] 2021-05-20 15:24
Good - I think that's the only way to go for the moment

**Comment by EwaTrzemzalska** [comment] 2021-05-25 19:08
Same issue here :(

**Comment by brentvatne** [comment] 2021-05-25 19:15
> android studio 4.2 with gradle 7.0.1 gives below error
> 
> ```
> > Plugin with id 'maven' not found.
> ```
> 
> downgraded gradle-6.8.1-all.zip in gradle-wrapper.properties ..
> working good

this is a good solution. locking thread for now because we don't support gradle 7. https://github.com/expo/expo/blob/11ca6a28857a2b75a9d0ecdd6fcaa4e3f97b42f3/templates/expo-template-bare-minimum/android/gradle/wrapper/gradle-wrapper.properties#L3

**Comment by djeanaraujo** [comment] 2021-06-22 11:37
For those using gradle 7, **maven** plugin has been removed, now you should use **maven-publish**, as described in official site at this link: https://docs.gradle.org/7.0/userguide/upgrading_version_6.html?_ga=2.21245883.1883799052.1624281891-1948725710.1624281891#removal_of_the_legacy_maven_plugin
So, instead of using:
`apply plugin: 'maven'`
you should use
`apply plugin: 'maven-publish'`

**Comment by gauravgg** [comment] 2021-07-02 08:05
> Hi @brentvatne thanks for your suggestion. à
> The problem actually was with the Gradle version. I just had to downgrade my Gradle version to version 6.4.1 using [sdk-manager](http://sdkman.io/) while following this [guide](https://medium.com/@czerwinb/how-to-install-a-specific-gradle-version-on-your-mac-beab35051ee8)
> 
> then, `gradle wrapper` command worked

After installing gradle6.4.1 using sdk manager and setting gradle wrapper

> Good - I think that's the only way to go for the moment

I have used your method. I have used sdk manager and downgrade my gradle to 6.4.1 but my android studio artic fox  supports only gradle 7.0 and my react-native modules do not support gradle 7.0. I am using macbook pro m1 chip. The error which i am getting is this:

Minimum supported Gradle version is 7.0.2. Current version is 6.4.1.

Please help me out on the same.

**Comment by pjeremymalouf** [comment] 2021-07-31 05:28
> > Hi @brentvatne thanks for your suggestion. à
> > The problem actually was with the Gradle version. I just had to downgrade my Gradle version to version 6.4.1 using [sdk-manager](http://sdkman.io/) while following this [guide](https://medium.com/@czerwinb/how-to-install-a-specific-gradle-version-on-your-mac-beab35051ee8)
> > then, `gradle wrapper` command worked
> 
> After installing gradle6.4.1 using sdk manager and setting gradle wrapper
> 
> > Good - I think that's the only way to go for the moment
> 
> I have used your method. I have used sdk manager and downgrade my gradle to 6.4.1 but my android studio artic fox supports only gradle 7.0 and my react-native modules do not support gradle 7.0. I am using macbook pro m1 chip. The error which i am getting is this:
> 
> Minimum supported Gradle version is 7.0.2. Current version is 6.4.1.
> 
> Please help me out on the same.


In the build.gradle file I changed this line:
`classpath 'com.android.tools.build:gradle:7.0.0'` to  `classpath 'com.android.tools.build:gradle:4.2.2'`

And it started working!

**Comment by BenGroot** [comment] 2021-08-19 07:07
Android Studio Artic Fox is promoting to upgrade to Gradle 7+. Almost everyone who is using the bare workflow with the latest Android Studio will get this issue. Mirgating to "maven-publish" will save a lot of hassle for developers who haven't had this issue yet. Is this migration very complex?

**Comment by BenGroot** [comment] 2021-08-19 07:21
To summarise for those running into this issue:

Change gradle build tools in the main build.gralde to: 
`classpath 'com.android.tools.build:gradle:4.2.2'`

Change distribution url in the yourproject/gradle/wrapper/gradle-wrapper.properties file to: 
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.8-all.zip`

The jump between the 7.0 version and the versions mentioned above is so huge because they are aligning the version numbers with the Gradle version number. The versions mentioned above just before the 7.0 versions.

**Comment by raybotha** [comment] 2021-08-20 09:13
What's the plan for supporting Gradle 7? Now that React Native supports it.

**Comment by robertying** [comment] 2021-08-22 05:37
Temporary workaround:

For any expo package, go to its `android/build.gradle` and modify to use `maven-publish` plugin:

```diff
 apply plugin: 'com.android.library'
 apply plugin: 'kotlin-android'
-apply plugin: 'maven'
+apply plugin: 'maven-publish'
 
 group = 'host.exp.exponent'
 version = '9.2.2'
 buildscript {
   }
 }
 
-// Upload android library to maven with javadoc and android sources
-configurations {
-  deployerJars
-}
-
 // Creating sources with comments
 task androidSourcesJar(type: Jar) {
-  classifier = 'sources'
+  archiveClassifier = 'sources'
   from android.sourceSets.main.java.srcDirs
 }
 
-// Put the androidSources and javadoc to the artifacts
-artifacts {
-  archives androidSourcesJar
-}
-
-uploadArchives {
-  repositories {
-    mavenDeployer {
-      configuration = configurations.deployerJars
-      repository(url: mavenLocal().url)
+publishing {
+  publications {
+    maven(MavenPublication) {
+      artifact androidSourcesJar
     }
   }
 }
```

**Comment by Guilhemfuel** [comment] 2021-08-30 14:38
> android studio 4.2 with gradle 7.0.1 gives below error
> 
> ```
> > Plugin with id 'maven' not found.
> ```
> 
> downgraded gradle-6.8.1-all.zip in gradle-wrapper.properties ..
> working good

If I try to do this I get error : Unsupported class file major version 60

Anyone same ?

**Comment by lejager** [comment] 2021-09-03 00:55
> To summarise for those running into this issue:
> 
> Change gradle build tools in the main build.gralde to:
> `classpath 'com.android.tools.build:gradle:4.2.2'`
> 
> Change distribution url in the yourproject/gradle/wrapper/gradle-wrapper.properties file to:
> `distributionUrl=https\://services.gradle.org/distributions/gradle-6.8-all.zip`
> 
> The jump between the 7.0 version and the versions mentioned above is so huge because they are aligning the version numbers with the Gradle version number. The versions mentioned above just before the 7.0 versions.

This results in a number of No signature of method errors for certain react native packages.

```No signature of method: build_1pnz21phoowefc22xejnoeuib.android() is applicable for argument types: (build_1pnz21phoowefc22xejnoeuib$_run_closure1) values: [build_1pnz21phoowefc22xejnoeuib$_run_closure1@23db40cd]```

Anyone facing this? 

+1 for gradle 7 support

**Comment by bombillazo** [comment] 2021-09-28 05:40
> 
> 
> Temporary workaround:
> 
> For any expo package, go to its `android/build.gradle` and modify to use `maven-publish` plugin:
> 
> ```diff
>  apply plugin: 'com.android.library'
>  apply plugin: 'kotlin-android'
> -apply plugin: 'maven'
> +apply plugin: 'maven-publish'
>  
>  group = 'host.exp.exponent'
>  version = '9.2.2'
>  buildscript {
>    }
>  }
>  
> -// Upload android library to maven with javadoc and android sources
> -configurations {
> -  deployerJars
> -}
> -
>  // Creating sources with comments
>  task androidSourcesJar(type: Jar) {
> -  classifier = 'sources'
> +  archiveClassifier = 'sources'
>    from android.sourceSets.main.java.srcDirs
>  }
>  
> -// Put the androidSources and javadoc to the artifacts
> -artifacts {
> -  archives androidSourcesJar
> -}
> -
> -uploadArchives {
> -  repositories {
> -    mavenDeployer {
> -      configuration = configurations.deployerJars
> -      repository(url: mavenLocal().url)
> +publishing {
> +  publications {
> +    maven(MavenPublication) {
> +      artifact androidSourcesJar
>      }
>    }
>  }
> ```

This in conjunction with `patch-package` solved it for me! Also be aware you may have to update this inside unimodule dependencies too.

**Comment by nibblesnbits** [comment] 2021-11-04 02:52
Is there any movement on this?

**Comment by enigmablue** [comment] 2021-11-20 02:01
unable to upgrade to gradle 7 too, which is required but some other packages. :(

**Comment by brentvatne** [comment] 2021-11-22 21:00
here's a related issue about gradle 7: https://github.com/facebook/react-native/issues/29829

**Comment by ardyfeb** [comment] 2021-12-06 15:51
Error message is very clear, expo project still using `maven` repository it should `maven-publish` on gradle 7. The ony solution is replacing each expo package `build.gradle`

**Comment by brentvatne** [comment] 2021-12-07 20:48
react-native doesn't support gradle 7 yet. i'm going to close and lock this because we are stuck with the version of gradle that react-native supports.

**Comment by brentvatne** [comment] 2022-01-19 17:18
react-native 0.67 ships with gradle 7.2

**Comment by brentvatne** [comment] 2022-01-27 20:07
fixed by https://github.com/expo/expo/pull/16080
will likely be released some time next week for sdk 44 packages

**Comment by Kudo** [comment] 2022-01-28 09:22
i'll update here once we release these packages.

**Closed** 2022-01-28 09:21 UTC
Labels: Android, needs repro

**Comment by Kudo** [comment] 2022-02-02 13:44
[we've published various expo packages](https://github.com/expo/expo/commit/ffccdd21af6aa5f8e965a56910a16466e4ce244d). this should fix the gradle 7 issue. thanks!
