### ISSUE TITLE
Type checking throws internal expo router type errors

### ISSUE THREAD

**Issue by hichemfantar** [expo/expo#25213] opened 2023-11-04 12:02 UTC
### Minimal reproducible example

Couldn't reproduce the issue for now with a fresh expo app

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Running `tsc --noEmit` throws internal expo router errors alongside project type errors.
Entry file is defined `package.json` `"main": "index.ts"`
Entry file content:
```ts
// setup sentry then import the router
import "./sentry-setup";
// This is the entry point for the Expo app.
// It is responsible for setting up the router, root component and loading pages.
import "expo-router/entry";

```
Currently using a [t3-turbo setup](https://github.com/t3-oss/create-t3-turbo) with yarn.

```
Found 61 errors in 16 files.

Errors  Files
     1  app/(authed)/chat.tsx:996
     1  app/(authed)/cvWizard/educationStep.tsx:70
     3  app/(authed)/cvWizard/experienceStep.tsx:68
     1  app/(authed)/cvWizard/languageStep.tsx:73
     1  app/(authed)/cvWizard/skillStep.tsx:62
     2  node_modules/expo-router/src/LocationProvider.tsx:24
     4  node_modules/expo-router/src/Route.tsx:99
     1  node_modules/expo-router/src/exports.ts:26
     2  node_modules/expo-router/src/fork/findFocusedRoute.tsx:8
    19  node_modules/expo-router/src/fork/getPathFromState.ts:50
    12  node_modules/expo-router/src/fork/getStateFromPath.ts:240
     5  node_modules/expo-router/src/getRoutes.ts:62
     2  node_modules/expo-router/src/global-state/routing.ts:166
     4  src/components/Switch/index.tsx:34
     1  src/components/myJobs/Card/index.tsx:333
     2  src/constants/jobs.ts:22
```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      Yarn: 3.6.0 - ~/.nvm/versions/node/v18.18.2/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    npmPackages:
      expo: ^49.0.16 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: managed
```

### tsconfig.json
```json
{
	"extends": "expo/tsconfig.base",
	"compilerOptions": {
		"strict": true,
		"skipLibCheck": true,
		"baseUrl": ".",
		"types": ["node", "nativewind/types"],
		"useUnknownInCatchVariables": false,
		"paths": {
			"@fonts": ["./assets/fonts"],
			"@images": ["./assets/images"],
			"@apis": ["./src/utils/api.tsx"],
			"@assets": ["./src/assets/index.ts"],
			"@components": ["./src/components/index.ts"],
			"@configs": ["./src/configs/index.ts"],
			"@constants": ["./src/constants/index.ts"],
			"@hooks": ["./src/hooks/index.ts"],
			"@layouts": ["./src/layouts/index.ts"],
			"@screens": ["./src/screens/index.ts"],
			"@services": ["./src/services/index.ts"],
			"@utils": ["./src/utils/index.ts"],
			"@skeleton": ["./src/skeleton/index.ts"],
			"@navigation": ["./src/navigation/index.ts"],
			"@types": ["./src/types/index.ts"],
			"@store": ["./src/store/index.tsx"],
			"@translation": ["./src/translation/index.ts"]
		},
		"target": "es2017",
		"lib": ["dom", "dom.iterable", "esnext"],
		"allowJs": true,
		"checkJs": true,
		"forceConsistentCasingInFileNames": true,
		"noEmit": true,
		"esModuleInterop": true,
		"module": "esnext",
		"moduleResolution": "node",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"jsx": "react-native",
		"incremental": true,
		"noUncheckedIndexedAccess": true,
		"noImplicitAny": false,
		"strictNullChecks": true
	},
	"include": [
		"app",
		"expo-plugins",
		"src",
		"*.ts",
		"*.tsx",
		"*.js",
		"*.jsx",
		".expo/types/**/*.ts",
		"expo-env.d.ts"
	]
}

```

**Comment by EvanBacon** [comment] 2023-11-06 22:14
Duplicate of https://github.com/expo/expo/issues/24933 -- we've fixed types in v3 by changing the main field to `build`. This is a breaking change so we can't backport. Please use ts-ignore and skip checking expo-router if this is blocking.

**Closed by EvanBacon** 2023-11-06 22:14 UTC
Labels: needs review, Router

**Comment by hichemfantar** [comment] 2023-11-07 06:25
@EvanBacon I get the type errors when I import tabs for some reason.

**Comment by hichemfantar** [comment] 2023-11-07 06:50
This line causes the type errors but why is this happening if I'm ignoring node_modules.
import { Tabs } from 'expo-router/tabs';

**Comment by hichemfantar** [comment] 2023-11-07 07:46
Seems like this issue can only be solved by upgrading to v3
https://github.com/microsoft/TypeScript/issues/41883

**Comment by hichemfantar** [comment] 2023-11-17 13:32
Created a [temporary fix](https://github.com/expo/expo/issues/24933#issuecomment-1816428488) until sdk50 is released which should fix the type issues.
