### ISSUE TITLE
Expo version of React-Native is not able to render `FlatList` or `SectionList ` with in the Jest tests.

### ISSUE THREAD

**Issue by robertovg** [expo/expo#2806] opened 2018-11-25 21:26 UTC
Hi guys, I have a problem with your version of [React-Native of expo](https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz), basically I have a project where I try to write unit testing and the `FlatList` never calls the `renderItem` with the collection I'm calling it, because of that, I can't make proper tests of my application and I would like to.

I have a project up created and running with the configuration provided out of the box by `expo init`  [here](https://github.com/robertovg/React-Native-Testing-Library-Flat-List), where you can see the issue isolated, especially in one file called `SmallIsolatedSample.test.js`.

There we have this component.

```jsx
class AppWithFlatList extends React.Component {
  state = {
    projects: [
      { name: 'Super Important Project A', id: '01' },
      { name: 'Super Important Project B', id: '02' },
      { name: 'Super Important Project C', id: '03' },
    ],
  };

  render() {
    const Project = ({ name }) => <Text>{name}</Text>;
    return (
      <View>
        <Button
          title="remove last"
          onPress={() => this.setState(state => ({ projects: state.projects.slice(0, 2) }))}
        />
        <FlatList
          data={this.state.projects}
          renderItem={({ item }) => <Project name={item.name} />}
          keyExtractor={({ id }) => id}
          ListEmptyComponent={<Text>There are no projects</Text>}
        />
      </View>
    );
  }
}
```

And the result of it, Is displayed (with `debug`) as:

```jsx
<View>
      <View
        accessibilityRole="button"
        accessibilityStates={Array []}
        accessible={true}
        isTVSelectable={true}
        onResponderGrant={[Function bound touchableHandleResponderGrant]}
        onResponderMove={[Function bound touchableHandleResponderMove]}
        onResponderRelease={[Function bound touchableHandleResponderRelease]}
        onResponderTerminate={[Function bound touchableHandleResponderTerminate]}
        onResponderTerminationRequest={[Function bound touchableHandleResponderTerminationRequest]}
        onStartShouldSetResponder={[Function bound touchableHandleStartShouldSetResponder]}
        style={
          Object {            "opacity": 1,
          }
        }
      >
        <View
          style={
            Array [
              Object {},
            ]
          }
        >
          <Text
            style={
              Array [
                Object {
                  "color": "#007AFF",
                  "fontSize": 18,
                  "padding": 8,
                  "textAlign": "center",
                },
              ]
            }
          >
            remove last
          </Text>
        </View>
      </View>
    </View>
```

As you can see after the `remove last` Button the `FlatList` is not rendered.

I changed the version of `react-native` in the `package.json` from `https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz` to `0.57.5` and it renders out perfectly the items in the test environment.

```jsx
<View>
        <View
          accessibilityRole="button"
          accessibilityStates={Array []}
          accessible={true}
          isTVSelectable={true}
          onResponderGrant={[Function bound touchableHandleResponderGrant]}
          onResponderMove={[Function bound touchableHandleResponderMove]}
          onResponderRelease={[Function bound touchableHandleResponderRelease]}
          onResponderTerminate={[Function bound touchableHandleResponderTerminate]}
          onResponderTerminationRequest={[Function bound touchableHandleResponderTerminationRequest]}
          onStartShouldSetResponder={[Function bound touchableHandleStartShouldSetResponder]}
          style={
            Object {
              "opacity": 1,
            }
          }
        >
          <View
            style={
              Array [
                Object {},
              ]
            }
          >
            <Text
              style={
                Array [
                  Object {
                    "color": "#007AFF",
                    "fontSize": 18,
                    "padding": 8,
                    "textAlign": "center",
                  },
                ]
              }
            >
              remove last
            </Text>
          </View>
        </View>
        <RCTScrollView
          ListEmptyComponent={
            <Text>
              There are no projects
            </Text>
          }
          data={
            Array [
              Object {
                "id": "01",
                "name": "Super Important Project A",
              },
              Object {
                "id": "02",
                "name": "Super Important Project B",
              },
              Object {
                "id": "03",
                "name": "Super Important Project C",
              },
            ]
          }
          disableVirtualization={false}
          getItem={[Function anonymous]}
          getItemCount={[Function anonymous]}
          horizontal={false}
          initialNumToRender={10}
          keyExtractor={[Function anonymous]}
          maxToRenderPerBatch={10}
          numColumns={1}
          onContentSizeChange={[Function anonymous]}
          onEndReachedThreshold={2}
          onLayout={[Function anonymous]}
          onMomentumScrollEnd={[Function anonymous]}
          onScroll={[Function anonymous]}
          onScrollBeginDrag={[Function anonymous]}
          onScrollEndDrag={[Function anonymous]}
          renderItem={[Function anonymous]}
          scrollEventThrottle={50}
          stickyHeaderIndices={Array []}
          updateCellsBatchingPeriod={50}
          viewabilityConfigCallbackPairs={Array []}
          windowSize={21}
        >
          <View>
            <View
              onLayout={[Function onLayout]}
              style={null}
            >
              <Text>
                Super Important Project A
              </Text>
            </View>
            <View
              onLayout={[Function onLayout]}
              style={null}
            >
              <Text>
                Super Important Project B
              </Text>
            </View>
            <View
              onLayout={[Function onLayout]}
              style={null}
            >
              <Text>
                Super Important Project C
              </Text>
            </View>
          </View>
        </RCTScrollView>
      </View>
```

I thought the problem was because of the testing library used and I posted the bug first on the [`react-native-testing-library` repo](https://github.com/callstack/react-native-testing-library/issues/68) but it's not the case, as using also the `react-test-renderer` we find the same issue.

I want to continue using `expo` in my projects, but I also want to not be restricted on the testings I can do because of it. 

- **How could I make this `FlatList` to be rendered as it should be in the testing environment?**
-  If this is not possible, maybe there could be a way to use `facebook/react-native` version for testing and `expo/react-native` for unit testing executed by jest somehow, **could you explain or teach how to be able to approach this?**

I hope to find a nice solution, and thanks for `Expo`, is a game-changing tool for react-native developments 🙌.

**Comment by sjchmiela** [comment] 2018-11-29 16:18
Just a long shot, may it be related somehow to https://github.com/expo/expo/issues/2484#issuecomment-435498469? 🤔

**Comment by robertovg** [comment] 2018-12-03 10:16
Right now I'm doing the second "dirty-solution"  which I don't like at all, basically, I added 2 scripts to my `package.json`

```
    "expoUpdate": "npm install react-native@https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz; expo publish",
    "testUpdate": "npm install react-native@0.57.7; jest --watchAll"
```

And because of that I usually use the official `react-native` while coding new functionalities and then before publishing to update the expo version the expo fork.

But this is a workaround 😿, I would like expo to be able to render `FlatList` or `SectionList ` in the jest test environment... 

So really would like someone from expo to explain why this is happening like that.

**Comment by ide** [comment] 2018-12-04 02:56
This isn't intentional behavior so we don't have an explanation without investigating this deeper. This isn't a high-priority task for us right now so I'd recommend debugging the jest preset if this is important to you, otherwise we'll update this issue when there is something new to share.

**Comment by rflorence** [comment] 2019-01-15 15:56
I'm experiencing this issue in SDK 32 as well, but not in https://github.com/expo/react-native/archive/v0.57.5.tar.gz. FlatList does not appear in `component.toJSON()`, but surprisingly, `component.root.findByType(FlatList)` still works.

**Comment by clarkcutler** [comment] 2019-02-20 00:51
We ran into this issue as well. For us, a work-around was adding the following mock to the top of our test file that needed `FlatList` to render:
```
jest.mock('ScrollView', () => require.requireMock('ScrollViewMock'))
```

The commit in the `expo` fork of `react-native` that seems to have introduced the issue is:
https://github.com/expo/react-native/commit/dbddbbf9830403e1665fe44d3c17d836291c0bef#diff-606adbd6a8c97d177b17baee5a69cdd9R46

**Comment by kaloianm** [comment] 2019-04-13 02:35
I just hit this problem with the SDK version 32.0.3 and spent 2 hours trying to figure out what is. The workaround of running my Jest tests with react-native@0.57.7 works, but it is really inconvenient and slow.

**Comment by brentvatne** [comment] 2019-04-13 22:03
@clarkcutler's workaround is good for now, we're looking into why expo/react-native@dbddbbf#diff-606adbd6a8c97d177b17baee5a69cdd9R46 is not working as expected

**Comment by evanlesmez** [comment] 2019-07-13 00:19
Also just ran into this

**Comment by ide** [comment] 2019-07-13 22:58
This will be likely addressed in a future release when we upgrade our third-party dependencies -- namely React Native to 0.61. In versions prior to 0.61, React Native has a Jest config that works in some scenarios but is not fundamentally correct. When we upgrade to the fixed Jest config (along with the removal of Haste), I suspect this issue will go away.

**Comment by ide** [comment] 2019-11-12 23:21
Running the repro case with master - which will go out with SDK 36 when the time comes - the tests now print the output with RCTScrollView as you were expecting:

```jsx
<View>
        <View
          accessibilityRole="button"
          accessibilityStates={Array []}
          accessible={true}
          focusable={true}
          isTVSelectable={true}
          onClick={[Function bound touchableHandlePress]}
          onResponderGrant={[Function bound touchableHandleResponderGrant]}
          onResponderMove={[Function bound touchableHandleResponderMove]}
          onResponderRelease={[Function bound touchableHandleResponderRelease]}
          onResponderTerminate={[Function bound touchableHandleResponderTerminate]}
          onResponderTerminationRequest={[Function bound touchableHandleResponderTerminationRequest]}
          onStartShouldSetResponder={[Function bound touchableHandleStartShouldSetResponder]}
          style={
            Object {
              "opacity": 1,
            }
          }
        >
          <View
            style={
              Array [
                Object {},
              ]
            }
          >
            <Text
              style={
                Array [
                  Object {
                    "color": "#007AFF",
                    "fontSize": 18,
                    "padding": 8,
                    "textAlign": "center",
                  },
                ]
              }
            >
              remove last
            </Text>
          </View>
        </View>
        <RCTScrollView
          ListEmptyComponent={
            <Text>
              There are no projects
            </Text>
          }
          data={
            Array [
              Object {
                "id": "01",
                "name": "Super Important Project A",
              },
              Object {
                "id": "02",
                "name": "Super Important Project B",
              },
              Object {
                "id": "03",
                "name": "Super Important Project C",
              },
            ]
          }
          disableVirtualization={false}
          getItem={[Function anonymous]}
          getItemCount={[Function anonymous]}
          horizontal={false}
          initialNumToRender={10}
          keyExtractor={[Function anonymous]}
          maxToRenderPerBatch={10}
          numColumns={1}
          onContentSizeChange={[Function anonymous]}
          onEndReachedThreshold={2}
          onLayout={[Function anonymous]}
          onMomentumScrollEnd={[Function anonymous]}
          onScroll={[Function anonymous]}
          onScrollBeginDrag={[Function anonymous]}
          onScrollEndDrag={[Function anonymous]}
          removeClippedSubviews={false}
          renderItem={[Function anonymous]}
          scrollEventThrottle={50}
          stickyHeaderIndices={Array []}
          updateCellsBatchingPeriod={50}
          viewabilityConfigCallbackPairs={Array []}
          windowSize={21}
        >
          <View>
            <View
              onLayout={[Function onLayout]}
              style={null}
            >
              <Text>
                Super Important Project A
              </Text>
            </View>
            <View
              onLayout={[Function onLayout]}
              style={null}
            >
              <Text>
                Super Important Project B
              </Text>
            </View>
            <View
              onLayout={[Function onLayout]}
              style={null}
            >
              <Text>
                Super Important Project C
              </Text>
            </View>
          </View>
        </RCTScrollView>
      </View>
```

Closing this since it has been fixed on master.

**Closed by ide** 2019-11-12 23:21 UTC
Labels: project: react-native
