### ISSUE TITLE
[expo-av] Bare React Native app _reactNative.UIManager.getViewManagerConfig is not a function

### ISSUE THREAD

**Issue by Pines-Cheng** [expo/expo#4737] opened 2019-06-27 11:33 UTC
### Environment

```
  Expo CLI 2.20.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.8.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.55.4 => 0.59.8
    npmGlobalPackages:
      expo-cli: 2.20.10
```

```
"react-native-unimodules": "0.4.1"
"expo-av": "^5.0.2",
```

### Steps to Reproduce

add code in js under :

```
import { Audio } from 'expo-av'
console.log(Audio)
```

### Expected Behavior

run normal

### Actual Behavior

![image](https://user-images.githubusercontent.com/9441951/60263051-481f9080-9912-11e9-8cfd-26431363380c.png)

**Comment by cruzach** [comment] 2019-06-27 15:41
Not able to repro this with your provided steps.

Try upgrading to the most recent `expo-cli`, start a fresh bare `expo init` project, and see if you get the same behavior.

**Comment by Pines-Cheng** [comment] 2019-07-02 01:35
I have tried again , RN  version 0.59.8 is fine , RN version 0.55.4 will theow this error.

**Comment by ide** [comment] 2019-07-02 17:53
> RN version 0.59.8 is fine , RN version 0.55.4 will theow this error.

This is likely the root cause -- make sure to use a compatible version of React Native.

**Comment by Pines-Cheng** [comment] 2019-07-03 07:40
Accessing view manager configs directly off UIManager via `UIManager[ ]` is no longer supported from React Native 0.58. Use `UIManager.getViewManagerConfig()` instead.

**Comment by Pines-Cheng** [comment] 2019-07-15 05:54
When are you going to release?

**Comment by ide** [comment] 2019-07-15 16:10
Sometime this week or the next, most likely.

**Comment by viewerw** [comment] 2019-08-12 10:16
> Sometime this week or the next, most likely.
Hi, have you release a new version to fix it ?

**Comment by cruzach** [comment] 2019-08-12 13:19
I believe this fix has been released, have you updated dependencies and are still seeing the issue?

**Comment by tsapeta** [comment] 2020-07-11 21:00
Looks like this issue has been fixed and released long time ago, so I'm gonna close it 🙂

**Closed by tsapeta** 2020-07-11 21:00 UTC
Labels: needs repro
