### ISSUE TITLE
ImagePicker android returns invalid base64 string with line breaks

### ISSUE THREAD

**Issue by linkev21** [expo/expo#1522] opened 2018-03-11 14:17 UTC
Hello guys!

I got a problem with the ImagePicker and the base64 option.

This is the code :

`ImagePicker.launchImageLibraryAsync({mediaTypes: 'Images', allowsEditing: true, base64: true})
            .then(source =>{console.log('source', source)
                if(!source.cancelled){
                 this.setState({source})
                }
        });
`

When I use an Iphone (ios9 4S), the console log of the result is :

![image](https://user-images.githubusercontent.com/32356792/37254410-b26d98f0-253d-11e8-8de5-704561a907c1.png)

I can perfectly send this to my backend (I use Intervention with PHP) and everything is fine.

But with android, I got this :

![image](https://user-images.githubusercontent.com/32356792/37254440-2982eeea-253e-11e8-87bf-5032b9289fd4.png)

We see the string is very different than the first one. And when I pass this to my backend, Intervention gives me an Exception "Image source not readable".

I tried to process the base64 string result but with no success.

I repeat, everything is fine with IOS.

The base64 result of the ImagePicker is not good with android.

My problem came from only the base64 result.

Thanks for your answer!

**Comment by leaphawk** [comment] 2018-03-11 20:13
base64 indeed has problems on android.[https://github.com/expo/expo/issues/1521](url) there's already one issue here.

**Comment by esamelson** [comment] 2018-03-13 17:08
Closing as a duplicate of #1521.

**Comment by aalices** [comment] 2018-03-14 10:26
I think it is a separate problem. Will this work if you remove new line symbols from the string?

**Comment by Slaskefar** [comment] 2018-03-19 14:38
I'm having the same issue.  I'm currently testing on iOS vs Android with the same image file.
On iOS the base64 string I get is 1108 characters long. On Android it is 738. The library I use for decoding base64 (base64-js) also throws an exception when running on Android.

I've tried decoding the strings on https://www.base64decode.org/ and they both decode successfully. They are obviously not the same image byte for byte, but they look the same. I have no clue how they manage to decode it when I cannot.

**Comment by Slaskefar** [comment] 2018-03-21 11:58
I've come up with a workaround until the issue gets resolved. Using the ImageStore from React Native, it is possible to get a base64 encoding from the uri returned from ImagePicker. Coincidentally the ImageStore base64 encoding doesn't work on iOS, but it works on Android.

This means that I can use the ImagePicker as intended on iOS, but I need to use ImageStore to extract the base64 encoding on Android.

This is the resulting code from my project, hopefully it is helpful.

```javascript
if (!result.cancelled) {
        let uriParts = result.uri.split("/");
        let fileName = uriParts[uriParts.length - 1];
        let fileType = fileName.split(".");
        fileType = fileType[fileType.length - 1];
 if (Constants.platform.ios) {
          this.props.setProfileImage(result.base64, fileName, fileType);
        } else {
          ImageStore.getBase64ForTag(
            result.uri,
            base64 => {
              this.props.setProfileImage(base64, fileName, fileType);
            },
            error => console.log(error)
          );
        }
}
```

**Comment by conradjonp** [comment] 2018-10-31 04:37
@Slaskefar this work around doesnt work with images, specifically with jpg. I'm getting corrupted files on the other end :/

**Comment by Slaskefar** [comment] 2018-10-31 07:18
> @Slaskefar this work around doesnt work with images, specifically with jpg. I'm getting corrupted files on the other end :/

I'm not working on the project anymore, and it is a faint memory for me at this point, but I used the workaround for handling images. Maybe your corrupted file issue is caused by something else?

**Comment by dlcardozo** [comment] 2018-11-06 20:52
Follow @aalices tip, just remove the new lines with something like:

`base64image = base64image.replace(/(?:\r\n|\r|\n)/g, '');`

**Comment by linkev21** [comment] 2019-05-03 09:56
Always the same problem guys, impossible to send my base64, the format is incorrect with android due to this shit blank in the string.

**Comment by ahlechandre** [comment] 2019-06-06 19:44
> Follow @aalices tip, just remove the new lines with something like:
> 
> `base64image = base64image.replace(/(?:\r\n|\r|\n)/g, '');`

Thanks, it's working now!

**Closed** 2019-09-28 15:34 UTC
Labels: project: android-runtime

**Comment by khaladj** [comment] 2019-12-20 14:21
> Follow @aalices tip, just remove the new lines with something like:
> 
> `base64image = base64image.replace(/(?:\r\n|\r|\n)/g, '');`

Excellent Your are a star!
