### ISSUE TITLE
[iOS 13] Fetching calendars not working

### ISSUE THREAD

**Issue by jordy-wijman** [expo/expo#5809] opened 2019-09-30 11:05 UTC
### Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.8 => 16.8.22
      @types/react-native: ^0.57.41 => 0.57.65
      @types/react-navigation: ^3.0.6 => 3.0.7
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.1.2

This issue only happens whenever you are testing on an iOS 13 device (I could not test the bug on the simulator, because this gave me another bug with Localization that has already been reported)

### Steps to Reproduce

* Create a new project with SDK 35 and test on an iPhone with > iOS 13.
* Add `expo-calendar` to your `package.json` with version `~7.0.0`.
* Write code to ask for permissions
* After permission has been given, write code to fetch all calendars.

import * as ExpoCalendar from 'expo-calendar';

```
await ExpoCalendar.requestPermissionsAsync();
const localCalendars = await ExpoCalendar.getCalendarsAsync();
console.log(localCalendars);
```

* Notice how this either sometimes gives you an empty array, but most of the time results into the following error. 

```
An exception was thrown while calling `ExpoCalendar.getCalendarsAsync` with arguments `(
    "<null>"
)`: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:104:55 in <unknown>
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:414:4 in __invokeCallback
- ... 4 more stack frames from framework internals
```

### Expected Behavior

A list of all the calendars that are there

### Actual Behavior

The error as shown above

### Reproducible Demo

https://snack.expo.io/@jordywijman/calendars-issue

Litterarly just run it on the snack itself, and you'll see it works, then try to run it on your device with > iOS 13 and you get nothing back.

**Comment by jordy-wijman** [comment] 2019-09-30 11:50
Oh one more addition to this issue, I just tested it on the simulator (in a small project, and here it DOES work properly, so it ONLY seems to do this on physical devices!)

**Comment by lukmccall** [comment] 2019-09-30 12:30
Hi @jordy-wijman, did you test it on iOS 13.1?
I need more information because I've just run your snack and everything worked fine.

**Comment by jordy-wijman** [comment] 2019-09-30 12:31
@lukmccall yes I have, updated to 13.1 yesterday. Did you run the snack on your actual device?

**Comment by lukmccall** [comment] 2019-09-30 12:40
Yes, I've run it on a physical device with iOS 13

**Comment by jordy-wijman** [comment] 2019-09-30 12:42
@lukmccall Okay I've got some more information, my agenda was being fetched from Google. It all works fine in the Calendar app, but I thought let's just remove the Google account and reconnect it. And well, it actually worked... now I don't really know if we're able to reproduce this issue and if it's an issue in the Expo SDK or if it's an Apple bug...

What do you think?

**Comment by lukmccall** [comment] 2019-09-30 13:48
It's hard to say if it's SDK or Apple fault. I assume it could be caused by sync issue with google account. Unfortunately, is's just a guess :\

**Comment by jordy-wijman** [comment] 2019-09-30 13:50
@lukmccal, is it possible to maybe enhance the promise rejection a little bit with some more information? Because there are more people having this issue, and the error basically says nothing.

That’s the only thing I can think of for now, because indeed, the issue is a little vague.

**Comment by lukmccall** [comment] 2019-09-30 14:27
@jordy-wijman, Unfortunately, it isn't possible to enhance the promise rejection which comes from react-native. 

For now, I've closed this issue. If this bug appears again, feel free to open this issue again.

**Comment by SilenceDogood1984** [comment] 2019-10-16 03:08
We're running into a similar issue with Expo 34. The Calendar functionality previously worked fine, but with iOS 13, for certain users, they're on a screen that shows a list of open jobs, but on tap, they're redirected to the home screen. 

Same message:
[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]

**Comment by lukmccall** [comment] 2019-10-16 06:27
Hi @SilenceDogood1984, I'll try to investigate this problem again.

**Closed** 2019-10-23 12:49 UTC
Labels: Calendar, bug
