### ISSUE TITLE
[SDK38] Android notifications stop after 5 minutes

### ISSUE THREAD

**Issue by RodolfoGS** [expo/expo#9037] opened 2020-06-30 13:26 UTC
### Summary of Issue

On expo SDK38 bare workflow Android notifications stop after 5 minutes when the device is locked. Even when the notifications have `priority: max`.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.1 => 38.0.4
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.13
```

package.json
```
{
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~38.0.1",
    "expo-constants": "~9.1.1",
    "expo-notifications": "~0.3.3",
    "expo-permissions": "~9.0.1",
    "expo-splash-screen": "~0.3.1",
    "expo-status-bar": "^1.0.0",
    "expo-task-manager": "^8.3.0",
    "expo-updates": "~0.2.10",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "~0.62.2",
    "react-native-gesture-handler": "~1.6.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-screens": "~2.9.0",
    "react-native-unimodules": "~0.10.1",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.11.0",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true,
  "name": "test-notifications",
  "version": "1.0.0"
}
```

### Reproducible Demo

I cannot create a snack as it doesn't seem to allow for modifying the app.json.

Repository: https://github.com/RodolfoGS/android-pn-stops

#### How to run the demo
1. Clone https://github.com/RodolfoGS/android-pn-stops
2. `yarn install`
3. Connect your device
4. `yarn android`
5. Copy your Expo token from the console
6. Disconnect and lock your device
7. `watch -n 30 node push.js "__YOUR_EXPO_TOKEN_HERE__"`

You will receive a notification every 30 seconds. Don't touch your phone and keep it locked and disconnected. After 5 minutes you will stop receive notifications.
It happen when you have `useNextNotificationsApi: true` or when you are in bare workflow. If you put it in false (managed only) it works.

### Steps to Reproduce

If you want to reproduce it creating a new project just follow the next steps:

1. expo init
2. expo eject
3. `expo install expo-notifications`
4. `expo install expo-permissions`
5. `expo install expo-constants`
6. run on your Android device (only affect Android devices)
7. disconnect from the energy and lock your device
8. send a push notification with `priority: max`, the notification appears.
9. keep the phone locked and wait 5 minutes...
10. send a push notification with `priority: max`, the notification doesn't appear.
11. send more notifications, don't appear.
12. when you unlock the device, all pending notifications appear at that moment.

### Expected Behavior vs Actual Behavior

Expected Behavior: the notifications appear at the moment that has been pushed
Actual Behavior: the notifications don't appear and when the user unlock the phone, the notifications come all at that time.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/870365/86130245-7e559a00-baa9-11ea-9682-00ab5087de7f.gif)

---
On expo sdk 36 with expokit works as expected, even when the device has been locked for hours.

**Comment by gggdomi** [comment] 2020-07-01 12:20
FYI I'm witnessing the exact same behavior in managed workflow, sending notifications to the expo client. No problem on iOS.

**Comment by RodolfoGS** [comment] 2020-07-01 16:17
I found what is generating the bug, and is the `useNextNotificationsApi` flag in app.json

Steps to reproduce with managed workflow:
1. Uninstall Expo client from your device if it's already installed
2. `expo init test-notifications`
3. select `blank`
4. `cd test-notifications`
5. `expo install expo-constants`
6. `expo install expo-notifications`
7. `expo install expo-permissions`
8. Copy code of App.js from the docs: https://docs.expo.io/versions/latest/sdk/notifications/
9. Connect your android device
10. `yarn android`
11. Copy expo token from the console
12. Disconnect and lock the device
13. Send a push notification, that works
14. Wait 5 minutes and will continue working perfectly

**But this has a problem**, listeners don't work (`addNotificationReceivedListener` nor `addNotificationResponseReceivedListener`)
Why?, Because the `useNextNotificationsApi` flag is required to use the new notifications api.
Ok, I'll add that flag to my app.json. And it's when the bug appears.

1. Uninstall Expo client from your device
2. Add the follow lines to your app.json
```
"android": {
  "useNextNotificationsApi": true
}
```
3. `yarn android`
4. Copy expo token from the console
5. Disconnect and lock the device
6. Send a push notification, that works
7. **ERROR**: Wait 5 minutes and... the notifications don't appear in your device


I think that it has a relation with another bug that I reported a couple of days ago: https://github.com/expo/expo/issues/8990
If you send a notification without the `useNextNotificationsApi` and make long press over the notification, you will see that the notification is in the *default* channel.

Now, when you add the flag, remove the app and make `yarn android` again, you will see that the notifications come to the Miscellaneous channel. Even when I send the notifications to the default channelId.

---
Script used to send notifications:

```
const fetch = require('node-fetch');

const TOKEN = '__YOUR_TOKEN_HERE__';

const message = {
  to: TOKEN,
  sound: 'default',
  title: `This is a title: ${new Date()}`,
  body: 'MESSAGE...',
  priority: 'high',
  data: { foo: 'bar' },
};

fetch('https://exp.host/--/api/v2/push/send', {
  method: 'POST',
  headers: {
    Accept: 'application/json',
    'Accept-encoding': 'gzip, deflate',
    'Content-Type': 'application/json',
  },
  body: JSON.stringify(message),
})
  .then(response => response.json())
  .then(console.log)
  .catch(console.error);
```

**Comment by RodolfoGS** [comment] 2020-07-02 14:22
Hi guys, I created a repository with a demo.
It's super simple to reproduce and I think that this issue must have the max priority, so the notifications don't work in the current version. That is crazy!

### Reproducible Demo

I cannot create a snack as it doesn't seem to allow for modifying the app.json.

Repository: https://github.com/RodolfoGS/android-pn-stops

#### How to run the demo
1. Clone https://github.com/RodolfoGS/android-pn-stops
2. `yarn install`
3. Connect your device
4. `yarn android`
5. Copy your Expo token from the console
6. Disconnect and lock your device
7. `watch -n 30 node push.js "__YOUR_EXPO_TOKEN_HERE__"`

You will receive a notification every 30 seconds. Don't touch your phone and keep it locked and disconnected. After 5 minutes you will stop receive notifications.
It happen when you have `useNextNotificationsApi: true` or when you are in bare workflow. If you put it in false (managed only) it works.

Of course I'm sending the notifications with `priority: 'high'`

---
@gggdomi Could you tell me please if you can reproduct the bug with my example? Thanks!

**Comment by lukmccall** [comment] 2020-07-03 14:24
I was able to reproduce it using your last demo ;) 
**Note**
It only happens when you're using the client from the store. It works as expected when you build the `expo-client` locally (debug version).

**Comment by RodolfoGS** [comment] 2020-07-03 14:45
@lukmccall I don't know how to build the expo client locally, but I can reproduce it just removing the expo client app from the device and installing it with `yarn android`. It also happen in bare workflow.

**Comment by mczernek** [comment] 2020-07-06 14:15
We're having troubles addressing the issue. We suspect it is manufacturer-dependant. @RodolfoGS would you please share your device specifics? Manufacturer, model and Android version?

**Comment by RodolfoGS** [comment] 2020-07-06 14:20
@mczernek sure, I'm testing in a Nexus 6P with Android 8.1.0

**Comment by lukmccall** [comment] 2020-07-06 14:26
I've used Samsung Galaxy s8. However, it's pretty hard to reproduce, cause in most cases it works :/

**Comment by RodolfoGS** [comment] 2020-07-06 14:35
I can reproduce always and easy, I just disconect the device and lock (turn of the screen), then I send a push notification every 30 seconds (with `push.js` that is in my demo) and ALWAYS at 5 minutes (exact) the notifications stop. Always when I test, always fails. Remember don't unlock, nor connect, nor touch the notifications when came.

And on the other hand, always when I change the flag of new notifications api to false, in the 100% of the tests the notifications continue working for hours without touch the phone.

This also happen in the bare workflow, but is most simple to test in a managed because you can use the old api.

**Comment by mczernek** [comment] 2020-07-06 14:53
Surprising as it is, you're right.

I haven't paid enough attention to the fact whether my phone is connected or not, but was easiy able to reproduce that even on development client. That's good news, hopefully we'll be able to address the issue.

Thanks a lot for your cooperation so far!

**Comment by RodolfoGS** [comment] 2020-07-11 13:03
@lukmccall @mczernek Hi guys, any update about this?

**Comment by mczernek** [comment] 2020-07-13 08:30
Hey @RodolfoGS!

We found the root cause, but it turned to be more complicated than we anticipated. We need to do some major refactor of core notifications functionality in order to address this issue. We're on it and it should land soon.

**Comment by BeKnowDo** [comment] 2020-07-17 20:39
clients don't like this kind of news lol

**Comment by mczernek** [comment] 2020-07-20 08:01
Good news is we already have a PR that fixes that. We will need a discussion for that, so it won't be merged right away, but we're on it :)

**Comment by gggdomi** [comment] 2020-07-20 10:22
Great, thank you ! :)

Is this the kind of changes that require a full App Store build and update with the new 38.0.x expo package if we already have a build with 38.0.3 deployed in the App Store ?

**Comment by RodolfoGS** [comment] 2020-07-20 12:04
@mczernek how can I test your PR? Are any way to install via npm?

**Comment by mczernek** [comment] 2020-07-20 12:24
No, you cannot do that with npm until we marge the PR. You could clone our repo and link to `packeges/expo-notifications` from your `packages.json`, while on my branch. That's given you're on bare workflow.

When in managed, that would require you to build the Expo Client on your own. That is not so straightforward, but certainly doable.

**Comment by mczernek** [comment] 2020-07-30 08:56
[Fix has landed](https://github.com/expo/expo/pull/9287) on master and will be published with new version od expo-notifications and on SDK39.

**Closed by mczernek** 2020-07-30 08:56 UTC
Labels: Android, Notifications

**Comment by SimenB** [comment] 2020-07-30 09:39
That means the fix won't be available for SDK 38?

**Comment by mczernek** [comment] 2020-07-30 10:13
We're considering backporting this change, stay tuned ;) For now, official message is: It will be part of SDK39.

**Comment by RodolfoGS** [comment] 2020-08-03 00:32
@mczernek It would be awesome if this fix could be included in the SDK38. I really appreciate your time and effort on this ❤️

**Comment by robertobrogi** [comment] 2020-08-11 07:49
Hi @mczernek, i have the same problem with standalone app in the store...
you have a timeline for the fix?

thanks a lot

**Comment by abdullah-abunada** [comment] 2020-09-10 17:44
Hello, thanks for your efforts, @mczernek can you help me to solve this issue in my project? also please provide me the repo link?

**Comment by SleeplessByte** [comment] 2020-09-10 17:53
SDK 39 is planned to come out this month.

**Comment by brunoaduarte** [comment] 2020-09-30 03:26
> SDK 39 is planned to come out this month.

Bug still exists on SDK 39

**Comment by RodolfoGS** [comment] 2020-09-30 12:39
@brunoaduarte I tested on SDK 39 and works perfect. Maybe you could create a new issue with a reproducible demo.

**Comment by Ibrahim-Arif** [comment] 2024-08-08 09:46
This issue is happening again on Expo SDK 51. Need urgent help. @brunoaduarte

**Comment by SleeplessByte** [comment] 2024-08-08 13:47
I recommend you create a new issue.

**Comment by douglowder** [comment] 2024-08-08 17:28
@SleeplessByte @Ibrahim-Arif I created #30899 and will investigate.
