### ISSUE TITLE
LocalAuthentication.authenticateAsync is returning  { "error": "unknown", "message": "", "success": false }

### ISSUE THREAD

**Issue by pagarfloyd** [expo/expo#4976] opened 2019-07-17 01:39 UTC
### Environment
  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      npm: 6.10.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.19 => 16.8.23 
      @types/react-native: ^0.57.60 => 0.57.65 
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.21.2

### Steps to Reproduce

expo init test-app
expo install expo-local-authentication
copy below code to App.tsx
expo start

```javaScript
import React, { Component } from "react";
import { View, Text, Button } from "react-native";
import * as LocalAuthentication from "expo-local-authentication";

export default class App extends Component {
  async authenticate(): Promise<void> {
    const hasHardwareAsync: boolean = await LocalAuthentication.hasHardwareAsync();
    const supportedAuthenticationTypesAsync: number[] = await LocalAuthentication.supportedAuthenticationTypesAsync();
    const isEnrolledAsync: boolean = hasHardwareAsync ? await LocalAuthentication.isEnrolledAsync() : false;
    console.log(hasHardwareAsync);
    console.log(supportedAuthenticationTypesAsync);
    console.log(isEnrolledAsync);
    if (hasHardwareAsync && isEnrolledAsync && supportedAuthenticationTypesAsync.indexOf(1) !== -1) {
      const authenticateAsync = await LocalAuthentication.authenticateAsync({
        promptMessage: "This message only shows up on iOS",
        fallbackLabel: ""
      });
      console.log(authenticateAsync);
    }
  }

  render(): JSX.Element {
    return (
      <View style={{ marginTop: 100 }}>
        <Button title="Authenticate Me" onPress={this.authenticate} />
      </View>
    );
  }
}
```

When I test it on IOS its working fine, but when I try it on Android MI Max 3 Android V9, ```const authenticateAsync ```   log is  ``` { "error": "unknown", "message": "", "success": false }```. It didn't wait for user to authenticate fingerprint it just log ``` { "error": "unknown", "message": "", "success": false }```. Please advise. Thanks.

**Comment by vapao** [comment] 2019-09-03 05:16
same issue

**Comment by esamelson** [comment] 2019-10-21 19:43
Hi there, this appears to be an issue with the underlying device/hardware as the Android system API is returning an error here. I'm keeping this open because we might be able to provide more information about the error in the returned object, but either way you'll need to have some sort of fallback or error handling mechanism in place in case LocalAuthentication fails on the device.

**Comment by Bardiamist** [comment] 2019-11-26 02:46
I have empty message on couple Android devices.

**Comment by Bardiamist** [comment] 2019-11-26 07:35
It is big problem for me now. Couple Android 9 devices (Xiaomi Mi 9 and Redmi 7) can't have `success: true`. And have `message: ''`. But these devices woks well with fingerprint in another applications. Any suggestion?

**Comment by Bardiamist** [comment] 2019-11-26 08:54
`FingerprintManagerCompat` [is depricated](https://developer.android.com/reference/androidx/core/hardware/fingerprint/FingerprintManagerCompat).

**Comment by ajimenezdev** [comment] 2020-01-13 15:35
I'm facing a very similar issue but with some differences
**Environment**
```
"expo": "36.0.2",
"expo-local-authentication": "8.0.0",
```

on iOs the app is working fine, but on some Android the error is thrown as soon as the `LocalAuthentication.authenticateAsync` is requested

The error received on my case is:
```
{
  "error": "user_cancel",
  "success": false,
}
```

Also, as we offer an alternative login on our app when a fingerprint is not working, I have found the following pattern.

If the app is started from the background (coming from a previous success login), the Fingerprint auth is working fine without problems.
When I kill the app and start the app from fresh (not coming from background), the `LocalAuthentication.authenticateAsync` is returning immediately the above error.

If running the app from expo on development mode, the issue is not happening.
But if I start the app with `expo start --no-dev --minify` and kill both expo app and my app, when it is open from a clean state, the issue is reproduced.

Again not sure if it is the same exact error, but the underline issue could be the same.

One more detail to provide is that this issue is not happening on all devices, so far I have tested on multiple devices and only reproduced on two of them:

Android 9
- OnePlus 5 ❌
- OnePlus 3 ✅
- BqAquarisX ✅
- Xiaomi mi A3 ✅

Android 10
- Samsung Galaxy S10+ ❌

And the issue started after upgrading our libraries from
```
“expo”: “35.0.1",
“expo-local-authentication”: “7.0.0",
```
Has anyone found a workaround for it?

**Comment by LinusU** [comment] 2020-01-23 22:25
Here is a PR to switch to `BiometricPrompt`, should hopefully fix a lot of the issues here!

https://github.com/expo/expo/pull/6846

**Comment by lukmccall** [comment] 2020-02-27 14:30
Hi everyone, that'll be fixed in SDK 37 (special thanks to @LinusU). 

For now, I'm closing this issue. Feel free to reopen it if this bug still occurs in the newest SDK.

**Closed by lukmccall** 2020-02-27 14:30 UTC
Labels: LocalAuthentication, project: android-runtime

**Comment by deepanshu01399** [comment] 2021-12-16 14:56
{"error":"app_cancel","success":false} i am getting that error when ever i am trying to do login with Passcode/Password without using Biometric
