### ISSUE TITLE
[Bug] Expo push notification badge not display in galaxy s9/s8 with newly launched samsung one UI devices?

### ISSUE THREAD

**Issue by chintansavjiyani1996** [expo/expo#4024] opened 2019-04-18 14:08 UTC
### Environment

Mobile OS Version :- Android P with 'samsung one ui '
Expo sdk-32.0.0

 for push service

Standalone Android App

### Expected Behavior
Whenever phone receive new notification it should display badge on application icon 
### Actual Behavior

I have standalone Android and IOS App build with Expo ,In the App I am implementing push notification and its also working Properly in all devices but in galaxy s9/s8 with newly launched samsung ‘one UI’ does not show badge when notification arrived.I am also added notification channel.Here is my code

```await Expo.Notifications.createChannelAndroidAsync('chat-messages', { name: 'Chat messages', sound: true, badge: true });```

 Find an attachment

![Screen Shot 2019-04-18 at 6 57 03 PM](https://user-images.githubusercontent.com/29792985/56365880-7e081080-620f-11e9-9460-db5d6dea5569.png)
![Screen Shot 2019-04-18 at 6 57 20 PM](https://user-images.githubusercontent.com/29792985/56365881-7ea0a700-620f-11e9-817a-5387ea02b3d8.png)
![Screen Shot 2019-04-18 at 6 59 01 PM](https://user-images.githubusercontent.com/29792985/56365882-7ea0a700-620f-11e9-8379-09e04d33e507.png)

### Reproducible Demo
I have prepare one Test notification app you can test via this app
[testNotification-78ea9118cf1040109abb640ba24ea4cd-signed.apk.zip](https://github.com/expo/expo/files/3094694/testNotification-78ea9118cf1040109abb640ba24ea4cd-signed.apk.zip)
(source-https://github.com/sameesiddiqui/expo-notifications-example
)

Thanks for helping us 

> 

>

**Comment by cruzach** [comment] 2019-04-19 23:33
Hey @chintansavjiyani1996,

Just for clarity- it's only on the specific Android devices you mentioned that this behavior occurs? You've tested on other devices (both Android/iOS) and it works as intended?

Thanks!
Charlie

**Comment by chintansavjiyani1996** [comment] 2019-04-20 09:49
Hey@cruzach
Thanks for the reply
Yes, I have tested with other devices also and it is working fine in all other devices but the issue is only with all samsung devices which got recent update of samsung one UI (i.e samsung S9,S10,S8),And also this devices got notification but badge is not displayed  on home screen as well as icon Grid.Can you please revert me back ASAP.

**Comment by EdGaz** [comment] 2019-04-23 15:15
Same problem here with Galaxy S8,
the badge is not showing even if i created the channel with badge set to "true".
(i'm sending the notifications with the right channel Id) 

`let channel = {
      name: "Alerts",
      description: "Ricevi una notifica all'attivazione di un alert",
      sound: true,
      vibrate: true,
      badge: true
    };
    Notifications.createChannelAndroidAsync(channelId,channel);`

![Screenshot_20190423-171006_Samsung Experience Home](https://user-images.githubusercontent.com/31928019/56592401-e3cb1280-65ea-11e9-879f-6df5c4389c98.jpg)

**Comment by chintansavjiyani1996** [comment] 2019-06-06 14:00
@EvanBacon  Is there any update on this?

**Comment by cruzach** [comment] 2020-03-31 20:15
Hi @chintansavjiyani1996 and @EdGaz , it seems like this is probably has to do with the launcher used on the device- it's possible that the "one UI" launcher doesn't show badges, or that it uses a launcher that [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger) (the library we use for badges) doesn't support

**Comment by sjchmiela** [comment] 2020-09-21 10:18
I will tentatively close the issue — this problem is [mentioned in the documentation](https://github.com/expo/expo/blob/8969f87c1e2a7e880736a123d92e997c0565ce83/docs/pages/versions/unversioned/sdk/notifications.md#L575) and we can't really do anything about it. 😕

**Closed by sjchmiela** 2020-09-21 10:18 UTC
Labels: Android, Notifications

**Comment by StefanusChristian** [comment] 2020-09-24 04:32
@chintansavjiyani1996 if you go to `Settings > Notifications` in your devices (mine was S10), you will see option `App Icon Badges`. You might want to enable that to see the app icon badges, I don't know if it disabled by default but in my case it was turned off. 

Hopefully this will be helpful to you 👍🏻
