### ISSUE TITLE
Adding paddingTop to TextInput causes Expo App to crash

### ISSUE THREAD

**Issue by jbakerdev** [expo/expo#655] opened 2017-09-19 14:02 UTC
What it says on the tin. Leaving this for the next poor soul. Merrily coding along and suddenly the Expo app on Genymotion Android 7.0 starts giving the dreaded "Expo has stopped." message over and over. 

The cause: 
`
<TextInput style={[MyOtherStyles, {paddingTop:20}]} />`

I can't say whether it's the fact that I was overriding a padding setting in MyOtherStyles object or what but removing the paddingTop made everything work again.

Genymotion Nexus 5x
Expo 19.0
RN 0.46

**Comment by jimmylee** [comment] 2017-09-19 19:57
I'm having difficult reproducing this, can you tell me how `MyOtherStyles` was defined? Thanks for sharing this!

**Comment by jimmylee** [comment] 2017-09-19 20:01
Here is a Snack I created to try to reproduce this: https://snack.expo.io/HkLiwlko-

**Comment by jbakerdev** [comment] 2017-09-19 21:23
The style object in question: 
`input:{
        width: '100%',
        height: 30,
        backgroundColor: 'rgba(255,255,255,0.1)',
        padding: 3,
        paddingLeft: 6,
        borderRadius: 3,
        overflow: 'hidden'
    }`

**Comment by terribleben** [comment] 2017-09-21 17:33
If you have time, can you please modify jimmy's snack above ^ to reproduce the crash?

**Comment by terribleben** [comment] 2018-07-09 23:31
Going to close this since we haven't been able to repro. Let us know if you're still seeing it.

**Closed by terribleben** 2018-07-09 23:31 UTC
Labels: status: needs more info
