### ISSUE TITLE
Inside React Native WebView, Freeze after "Take Photo" / Unable to select a photo from Photo Library

### ISSUE THREAD

**Issue by ejimenez93** [expo/expo#1879] opened 2018-06-15 18:25 UTC
## Environment
Expo SDK v28
iOS
Client / Standalone / ExpoKit v2.6.5

## Reproducible Demo
**Snack Link**: https://snack.expo.io/S1U4Xv-ZQ

## Freeze after "Take Photo" Steps to Reproduce (use Snack Link below on an actual iOS device)
1. After app loads In iOS, tap on "Choose File" button to upload a file. Choose the "Take Photo or Video" option
2. If prompted, allow the camera permission
3. Take a photo and tap on "Use Photo"

#### Expected Behavior
The camera view controller should dismiss and populate the file input field with the recently taken photo

#### Actual Behavior
App completely freezes and user is unable to use the recently taken photo. 

## Unable to select a photo from Photo Library Steps to Reproduce
1. After app loads In iOS, tap on "Choose File" button to upload a file. Choose the "Photo Library" option
2. Select any photo to use

#### Expected Behavior
Cancel button should change to "Done" to allow user photo selection

#### Actual Behavior
Note that the "Cancel" button doesn't change to "Done" on the navigation bar, so there's no way to select what photo you want to use

## Additional Notes
*Browse Option* does work as expected
This _was_ working correctly in Expo v27.0.2 / ExpoKit v2.5.4. Were there any breaking changes to the Camera/ImagePicker libraries that would cause this?

**Comment by EvanBacon** [comment] 2018-06-15 19:36
Pretty important to mention that this is all within a `ReactNative.WebView` and not any `Expo` APIs. Possibly an error with the version of RN 28 is using. https://github.com/facebook/react-native/releases/tag/v0.55.4

**Comment by EvanBacon** [comment] 2018-06-15 20:04
Now that I think about it, you prolly confused `Expo.WebBrowser` with `ReactNative.WebView` Have you tried using: [`Expo.WebBrowser`](https://docs.expo.io/versions/v28.0.0/sdk/webbrowser)? 
Example of your thing working with it: https://snack.expo.io/@bacon/file-upload-with-expo

**Comment by ejimenez93** [comment] 2018-06-15 20:35
Hi @EvanBacon,

Thanks for the quick response. No I meant to use `ReactNative.WebView` as I need it embedded within the app, not opening up an external web browser. I think you might be right about the React Native version. I'll try a few tests with different versions and let you know what I find.

**Comment by johisco** [comment] 2018-06-19 13:20
Im experiencing the exact same issue here on Expo V26.

**Comment by crazywako** [comment] 2018-06-21 10:12
When using RN's WebView and pressing fileupload field and after taking a photo the app freezes and I can't press "Use Photo"

On Android nothing happens when trying to press fileupload.

iPhone X
iOS 12.0 beta 1
React Native ~0.55.2
Expo 27.1.0

**Comment by ironyee** [comment] 2018-07-23 12:41
How to reproduce the problem:

```
$ exp init test
$ cd test
$ exp start
```

<App.js>
```
export default class App extends React.Component {
  render() {
    return (
      <WebView source={{ uri: 'https://formstack-jiujc.formstack.com/forms/file_upload' }}/>
    );
  }
}
```

1. Click <Choose File>
2. Select <Take Photo or Video>
3. Take a photo
4. Click <Use Photo>
5. Freeze

or

1. Click <Choose File>
2. Select <Photo Library>
3. Check any photo
4. You can see that the Cancel button does not change to Done

**Comment by ironyee** [comment] 2018-07-24 01:36
```
$ react-native init test
$ cd test
$ react-native run-ios
```

<App.js>
```
export default class App extends React.Component {
  render() {
    return (
      <WebView source={{ uri: 'https://formstack-jiujc.formstack.com/forms/file_upload' }}/>
    );
  }
}
```

You can see that It works.
It's not React Native's fault. (0.56.0)

**Comment by ejimenez93** [comment] 2018-07-30 22:32
@EvanBacon @terribleben has there been any update on this? I can confirm the same use-case as @ironyee. Changing the Expo version on Snack doesn't seem to fix this

**Comment by crazywako** [comment] 2018-08-07 07:35
It works on React Native after ejecting Expo away. Needed to add Camera permissions to Info.plist. So it's definitely Expo specific problem.

**Comment by barthec** [comment] 2018-08-07 09:30
I've tracked down the problem and found the cause. Fix for this issue is currently being developed.

**Comment by ru88s** [comment] 2018-08-10 13:02
I have the same bug. Please fix a bug. I appreciate everyone.

**Closed** 2018-08-17 15:08 UTC
Labels: in progress, in review, project: sdk

**Comment by jeremy-dimasuay** [comment] 2018-08-18 16:53
@barthec Thanks in advance for helping with this bug.

Is this the commit that addresses this issue?
https://github.com/expo/expo/commit/6c0ca3f0cd2898b02b0d365f472587c92e23bd21

**Comment by barthec** [comment] 2018-08-20 13:19
@jeremy-dimasuay yes, it is.

**Comment by jeremy-dimasuay** [comment] 2018-08-25 16:46
`29.0.1-rc.0` doesn't seem to be include this fix. Any chance that this commit eventually makes it into `29.0.1` or even a release candidate sooner that `29.0.1`?

**Comment by ru88s** [comment] 2018-08-26 03:26
Thank you for contacting me.
Yes, we plan to release the application after correction.
I hope that the problem will be healed as soon as possible.

**Comment by aglio** [comment] 2018-09-04 01:30
Is this bug fixed not yet? I use Expo SDK v29. I have the same issue yet.
Will it be fixed in `v29.0.1`?

**Comment by tsapeta** [comment] 2018-09-04 01:44
From what I see the fix for this landed in the newest Expo Client that was released together with `v29.0.1`. Are you still experiencing this issue?

**Comment by T0mi** [comment] 2018-09-04 07:34
Hey @tsapeta , when will the SDK 29.0.1 be out? Because i only see rc1 of 29.0.1. Thanks!

**Comment by ru88s** [comment] 2018-09-13 07:07
Became expo ver 30, fixed the Webview bug [input type = "file"]. 
Everyone at expo, I really appreciate it. It is impressive.
<img width="391" alt="279e64e0b6e3c71e4dd3c7396a1ad3c6" src="https://user-images.githubusercontent.com/42270511/45472369-05b80900-b76f-11e8-888c-8ed75b453f36.png">

**Comment by aaronbesson** [comment] 2018-11-05 17:24
Any idea when this may be fixed on Android? Thanks

**Comment by asdw741111** [comment] 2018-12-19 06:14
still not working on Android with ExpoV31.0.2

**Comment by jsanchezs** [comment] 2019-01-16 11:48
Still not working on Android with ExpoV32.0.0

**Comment by JamesLivengood** [comment] 2019-04-11 15:38
Has anyone found a fix for this? Or knows a completely different uploader that works in React Native?
