### ISSUE TITLE
[expo-av][iOS 10] Video player shows native controls in iOS even with setNativeControls={false}

### ISSUE THREAD

**Issue by robbie-c** [expo/expo#5907] opened 2019-10-08 17:27 UTC
### Environment

 Expo CLI 3.2.3 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.7.0 - /tmp/yarn--1570555357461-0.6163389707700286/node
      Yarn: 1.19.0 - /tmp/yarn--1570555357461-0.6163389707700286/yarn
      npm: 6.10.0 - ~/.nvm/versions/node/v12.7.0/bin/npm
    npmPackages:
      @types/react: ^16.8.19 => 16.9.2 
      @types/react-native: ^0.57.60 => 0.57.65 
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.12.1 

Running through the Expo app in iOS 10.3.3. Client version 2.13.0.107059

### Steps to Reproduce

I'm using the Video component like this:

```javascript
                <Video
                  ref={this.onVideoRef}
                  source={getVideo(stepVideoId)}
                  rate={1.0}
                  volume={1.0}
                  isMuted={false}
                  resizeMode={ResizeMode.COVER}
                  isLooping={false}
                  style={styles.video}
                  shouldPlay={false}
                  onPlaybackStatusUpdate={this.onPlaybackStatusUpdate}
                  useNativeControls={false}
                  usePoster={false}
                  progressUpdateIntervalMillis={
                    VIDEO_PLAYBACK_STATUS_UPDATE_INTERVAL_MS
                  }
                />
```
I get a flash of the native controls, and am able to pause or enter full screen.

### Expected Behavior
The native controls should be completely hidden

### Actual Behavior
The native controls are present, even when not in full screen

### Reproducible Demo

See code

**Comment by cruzach** [comment] 2019-10-08 18:57
Have you tested this on more recent iOS versions? I made [this snack](https://snack.expo.io/@charliecruzan/curious-popcorn) to test this out, and if I set `useNativeControls={false}`, I don't see any native controls (but that's on iOS 12)

Let me know if you are able to see the native controls on running that snack

**Comment by robbie-c** [comment] 2019-10-14 14:14
Sorry for the delay. On the same device I do see native controls. Unfortunately I don't have a device with a more recent version of iOS to test on, but if that snack works for you on iOS 12 and doesn't for me on iOS 10 that's pretty good evidence.

**Comment by cruzach** [comment] 2019-10-14 15:17
That snack has `useNativeControls={true}` by default, so make sure you manually change that to see the difference. Also, just to rule out other possibilities, can you:
- make sure you're on the most recent version of the Expo Client app?
- make sure you're not in full screen mode (on full screen, native controls will be shown)

**Comment by robbie-c** [comment] 2019-10-14 16:14
> That snack has `useNativeControls={true}` by default, so make sure you manually change that to see the difference.

Yep, see native controls either way

>     * make sure you're on the most recent version of the Expo Client app?

2.13.0.107059, which I believe is the latest

>     * make sure you're not in full screen mode (on full screen, native controls will be shown)

Definitely not in full screen

**Comment by IjzerenHein** [comment] 2020-07-24 13:10
I've had a closer look at this and tested it on iOS 10 just to be sure this problem no longer exists. I cannot reproduce it it any form or way and the current code for enabling useNativeControls looks really solid.

I think this problem has been resolved already. @robbie-c can we close this?

**Comment by robbie-c** [comment] 2020-07-27 21:55
Heya, due to lockdown I'm pretty unlikely to get access any time soon to the phone I had this problem on. Thanks for trying so hard to reproduce this, I really appreciate it.

No objections to closing it from me, given that.

**Comment by IjzerenHein** [comment] 2020-07-28 09:49
Okay in that case I'll close this as we are unable to reproduce it with the latest code-base. Feel free to re-open with additional details if the problem still exists 👍

**Closed by IjzerenHein** 2020-07-28 09:49 UTC
Labels: AV, Video, bug, iOS
