### ISSUE TITLE
Android - onActivityCreated never called on detached project

### ISSUE THREAD

**Issue by daominhsangvn** [expo/expo#347] opened 2017-07-08 02:50 UTC
I'm trying to use https://github.com/wix/react-native-keyboard-input in my detached android (exp detach) project and it's not working but the project that created by `$ react-native init` does.
So I diged into the android project and found out that the `onActivityCreated` method of `Application.ActivityLifecycleCallbacks` never called.
Here the code:
```
public class KeyboardInputPackage implements ReactPackage {
   public KeyboardInputPackage(Application application) {
     application.registerActivityLifecycleCallbacks(new Application.ActivityLifecycleCallbacks() {
            @Override
            public void onActivityCreated(Activity activity, Bundle savedInstanceState) {
                sCurrentActivity = activity; // never trigger
            }

            @Override
            public void onActivityStarted(Activity activity) {
                sCurrentActivity = activity; // trigger when I turn off the screen then turn on again
            }

            .....
     })
   }
}
```
The `onActivityCreated` never trigger make the module entirely not working. 
How can I fix it?

**Comment by khacanh** [comment] 2017-11-11 17:34
The problem is that in Expo app (even after detaching)
```
public class MainActivity extends ExponentActivity {
  ...
}
```
`ExponentActivity` extends from `ReactNativeActivity`, which is something defined by Expo SDK. 

Meanwhile, apps created with `react-native init` has
```
public class MainActivity extends ReactActivity {
  ...
}
```

The way `ReactNativeActivity` handles activity events are very different from `ReactActivity`. It will not call the methods defined and passed in `addActivityEventListener` 

That means, the official way to create call back in android bridge, as it is documented here https://facebook.github.io/react-native/docs/native-modules-android.html, will no longer work. 

I think this is a big issue as all of the bridge packages that needs callback will not work. 
Would be great if the author can help address this. 

Thanks.

**Comment by Amit4Saini** [comment] 2017-11-26 12:55
@terribleben @jesseruder Any update on this. Can you please suggest any workaround.

**Comment by jesseruder** [comment] 2018-01-17 21:26
This should be fixed in SDK 24!

**Closed by jesseruder** 2018-01-17 21:26 UTC
Labels: project: android-runtime, project: expokit

**Comment by LoongerBuxus** [comment] 2018-02-08 11:32
I'm facing similar problem with SDK 24, onActivityResult never gets called when trying to use native camera.

**Comment by lookagit** [comment] 2018-07-13 00:11
Still nothing on this @jesseruder

**Comment by JulianKingman** [comment] 2018-08-10 17:49
@lookagit did you figure this out?
@jesseruder seems like this issue should remain open, no?

**Comment by N1ghtly** [comment] 2018-09-25 20:33
Is there any workaround for this? We can't use react-native-google-signin on a detached app because of this.

**Comment by N1ghtly** [comment] 2018-09-25 20:37
For future reference: this is a known workaround. Not usable in most situations though.

https://github.com/expo/expo/issues/651
