### ISSUE TITLE
iOS Facebook login with behavior="native" crashes the app

### ISSUE THREAD

**Issue by ArsenyYankovsky** [expo/expo#1327] opened 2018-01-25 00:50 UTC
Hi,

I'm running a standalone app with sdk 25. I'm trying to switch my `Expo.Facebook.logInWithReadPermissionsAsync` behavior to `native`. It works fine on Android, but on the iOS it crashes the app and the error is not a javascript one because Sentry doesn't report it. If I switch it back to `web` it works fine on both iOS and Android.

Thanks.

**Comment by peferb** [comment] 2018-01-26 08:09
I have the same problem, but when I removed 'behavior' Facebook login still crashes on IOS. I've added FB app id and display name. Still crashes.

**Comment by mikesholiu** [comment] 2018-01-26 23:17
Thanks @esamelson for taking a look. 

Getting the same behavior. I just wanted to mention here that in my case I haven't previously modified the `logInWithReadPermissionsAsync`.

**Comment by dackom** [comment] 2018-01-26 23:23
For me crashes always, even if I put explicitly behavior:”web” (web is default, so it’s probably not even needed). Anyway, in expo 24 everything worked well.

**Comment by mikesholiu** [comment] 2018-01-27 01:55
Tested this out again using an older version of a build on expo 24 and seeing this issue too, so it seems to be some issue with Expo native code.

**Comment by verzil** [comment] 2018-01-29 22:47
So far I am only able to reproduce this error on IOS sdk 25, there is no way for me to see the logs on a standalone app for ios so i'm not able to debug further

**Comment by aalices** [comment] 2018-01-30 12:17
Hello all, this is very possible that the issue is related to iOS 11 lack of Facebook/Twitter built-in support (Fb/Twitter account settings no more available in device's settings). However, I am still trying to make sure this is the reason and if so find a workaround or just mention that `native` option is not available for iOS > 10 anymore :(

**Comment by dackom** [comment] 2018-01-30 12:20
Thats ok, but what happens with us who didn’t even try to use “native”? :-) I’m usibg default or web, but still app crashes since sdk 25.

**Comment by aalices** [comment] 2018-01-30 12:26
@dackom oh okay, sorry - I missed that. I'll also take a look at this case.

**Comment by mikesholiu** [comment] 2018-01-30 16:13
Thanks @aalices — please see the additional context I’ve given here if helpful: https://forums.expo.io/t/standalone-ios-app-crashes-upon-pressing-fb-login-button/6770/4

The crashes happen with FB login on iOS regardless of setting behavior to native so this issue is somewhat mistitled.

**Comment by chownation** [comment] 2018-02-02 17:41
Tested in latest build successfully - looks resolved with exp `49.1.0`

**Comment by aalices** [comment] 2018-02-05 10:01
Closing for now, feel free to reopen if this still exists

**Closed by aalices** 2018-02-05 10:01 UTC
Labels: in progress, project: ios-runtime, project: sdk

**Comment by w-** [comment] 2018-02-08 04:38
@chownation when you say
> Tested in latest build successfully - looks resolved with exp 49.1.0

do you mean if we build ios with latest exp this issue is resolved? or does it just work on the simulator using exp 49.1.0?

**Comment by bschwartz10** [comment] 2018-02-14 21:20
@chownation @aalices I built with 49.1.0 and expo 20 and it's still crashing in live app. Works fine in simulator
