### ISSUE TITLE
Error: Pakager is not running at IP+:19001

### ISSUE THREAD

**Issue by MelquiasRibeiro** [expo/expo#7366] opened 2020-03-14 17:08 UTC
hey guys i'm very frustrated with this problem, I've tried many things like:

1. disable firewall;
2. set my IP on React Native variables ;
3. I've tried  all possibilities to conect (LAN, Local, Tunel), in my  physical device and on emulator;

please, help me 

these are the errors :

![2020-03-14](https://user-images.githubusercontent.com/54459438/76686806-026c3a80-65fd-11ea-9f77-1b3c969756d0.png)
![2020-03-12](https://user-images.githubusercontent.com/54459438/76686807-039d6780-65fd-11ea-8e29-0a13cdd4eef4.png)

**Comment by cruzach** [comment] 2020-03-16 18:36
Are you on the same network as the physical device you're testing on? I'd also check that you can access localhost:19001 from your phone's web browser

This has been reported before and several people have shared their solutions in [this thread](https://github.com/expo/expo/issues/1381), so I encourage you to check through that. I'm going to close this issue since it's not a bug with the Expo SDK. If you believe this is a bug with Expo CLI, please open an issue and fill out the entire bug report template at the [`expo-cli` repo](https://github.com/expo/expo-cli)

**Closed by cruzach** 2020-03-16 18:36 UTC
