### ISSUE TITLE
Location always instantly returns with a timeout

### ISSUE THREAD

**Issue by ciokan** [expo/expo#54] opened 2017-02-06 00:47 UTC
`Location request timed out` this is the error I get whenever I'm trying to access the user's location.

Here's my code:

```
import Exponent from 'exponent';

export async function getPosition() {
	const {Location, Permissions} = Exponent;
	const {status} = await Permissions.askAsync(Permissions.LOCATION);

	if (status === 'granted') {
		return Location.getCurrentPositionAsync({enableHighAccuracy: true});
	} else {
		throw new Error('Location permission not granted');
	}
}
```

some component

	componentDidMount() {
		getPosition().then((position) => {
			if (position) {
				console.log(position);
			}
		}).catch((e) => {
                        // this one is firing the error instantly
			alert(e + ' Please make sure your location (GPS) is turned on.');
		});
	}

Android 6.0.1

**Comment by jesseruder** [comment] 2017-02-09 18:48
@nikki93

**Comment by andrewrd** [comment] 2017-02-16 05:31
I've tried watchPositionAsync() too with the same code and it doesn't seem to be working either.

**Comment by jesseruder** [comment] 2017-02-18 01:40
Thanks for the information. We're heard multiple reports of this but don't hit it on our devices. Will try your code.

**Comment by jesseruder** [comment] 2017-02-23 22:37
Ok we figured out how to reproduce this. Will fix it in the next release.

**Comment by alexprice91** [comment] 2017-03-12 03:49
@jesseruder I am getting the error:
```
{"framesToPop":1,"code":"E_TIMEOUT"}
```

Is this related?

**Comment by jesseruder** [comment] 2017-03-13 18:35
I think that's the same error @alexprice91. We're doing a release this week and we'll see if that fixes these issues.

**Comment by jesseruder** [comment] 2017-03-27 17:21
Should be fixed. Can you try it out and let me know?

**Comment by ChenLi0830** [comment] 2017-03-30 18:23
@jesseruder It works for me for ios and Android > 6, but for Android < 6, `Location.getCurrentPositionAsync({enableHighAccuracy: true})` will timeout if the location on the phone is turned off. 

Not sure if it is the intended behavior, but we ended up setting a timeout for this situation. 
````
      await Promise.race([
          Location.getCurrentPositionAsync({enableHighAccuracy: true}),
          // 2s Timeout for Android phones system version < 6
          new Promise((resolve, reject) => setTimeout(()=>reject(new Error('timeout')), 2000)),
      ])
          .then(result => {
            console.log("location", location);
            location = result
          })
          .catch(error => {
            console.log("get location timed out", error);
          });
````

**Comment by nikki93** [comment] 2017-06-16 00:44
This should be fixed in SDK 18, will close once released and confirmed by users.

**Comment by nikki93** [comment] 2017-06-23 00:42
Released! @ciokan @andrewrd @alexprice91 @ChenLi0830 Let me know if this is still happening for you in SDK 18.

**Closed by nikki93** 2017-06-23 00:42 UTC
Labels: Status: Accepted, Status: In Progress

**Comment by atinder** [comment] 2017-06-30 18:03
still happening on sdk 18.0.4

**Comment by skbogner** [comment] 2017-07-12 13:30
Same happens to me.
Android 5.1.1
expo 18.0.9

**Comment by jesusmgg** [comment] 2017-07-26 21:49
Reporting same error, Android 6.0.0, expo 1.18.4, xde 19
https://exp-xde-diagnostics.s3.amazonaws.com/jesusmg-b629d5cc-72ed-4ea3-86a2-0459e06f9c90.tar.gz

**Comment by san17ap93** [comment] 2018-12-19 00:59
> Same happens to me.
> Android 5.1.1
> expo 18.0.9
> 
> Edit:
> It happens when the location in android settings is set to GPS only, but it works if it's set to use both wi-fi, gps, ...

same here!
