### ISSUE TITLE
Expo Facebook.logInWithReadPermissionsAsync not redirecting to app ( IOS Production app && Testflight app only )

### ISSUE THREAD

**Issue by waseemtsd** [expo/expo#6085] opened 2019-10-25 14:04 UTC
### Environment

Expo CLI 3.1.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501

EXPO SDK VERSION: 35.0.0
IOS version 13.1.0, 13.1.2, 13.1.3

### Steps to Reproduce

1. Use Facebook.logInWithReadPermissionsAsync to make a facebook login.
2. Choose to log in with the Facebook native app(not in the browser)
3. Press continue to get back to your app.

### Expected Behavior

User should be successfully logged in after getting redirected back to the app.

### Actual Behavior

Facebook login modal is not closed & user is not redirected to the app

### Reproducible Demo

In the view I have:

 <TouchableOpacity onPress={this._loginFacebookAsync }>
           <Image source={facebookLogo} style={styles.facebookLogo}/>
   </TouchableOpacity>

The function called:

     _loginFacebookAsync = async () => {
         const {type, token,} = await Facebook.logInWithReadPermissionsAsync('fbAPPid',{
      permissions: ['public_profile', 'email'] 
    });
    if (type === 'success') {
console.log("Facebook login success!")
        this._handleFacebookLoginSuccess(token)
    } else { 
console.log("Facebook login failed!")
        alert("There was an error")
    }
}

**Comment by cruzach** [comment] 2019-10-25 19:14
@waseemtsd looks like you found a very similar [issue](https://github.com/expo/expo/issues/4701#issuecomment-546361417), is this different than that or can I close it to keep the conversation consolidated in one place?

**Comment by ImAbhishekTomar** [comment] 2019-10-28 01:14
same issue with me after upgrade my expo version 35...... any solution?

**Comment by cruzach** [comment] 2019-10-28 15:22
Closing as duplicate of 4701

**Closed by cruzach** 2019-10-28 15:22 UTC
Labels: bug
