### ISSUE TITLE
Barcode Scanner Issues

### ISSUE THREAD

**Issue by AlexMachin1997** [expo/expo#3831] opened 2019-03-24 13:27 UTC
Hi,

So I've just added the expo barcode scanner to my application and with some minor issues. When I navigate away from the barcode scanner tab it continues to scan items which is weird. See the image below for a demonstration of the issue in my application.

![Screenshot_20190324_132333_com food](https://user-images.githubusercontent.com/29917195/54880028-32dd2680-4e38-11e9-8377-9e8d5f3a2b50.jpg)

I've also noticed the barcode scanner continues to scan items after they have been scanned.

Would appreciate any help with this problem as its annoying when items are being randomly picked up.

Thanks,
Alex

**Comment by AdamJNavarro** [comment] 2019-03-25 15:46
Hey @AlexMachin1997,

Could you create a [Snack](snack.expo.io) that reproduces this for us to test on our end?

Cheers,
Adam

**Comment by AlexMachin1997** [comment] 2019-03-25 16:20
How would I make it as a bare minimum wirkflow?

**Comment by AlexMachin1997** [comment] 2019-03-25 20:53
Hi @AdamJNavarro ,

When I tried to import my app into a snack environment I kept getting this error

![image](https://user-images.githubusercontent.com/29917195/54953420-16c4ac80-4f40-11e9-9380-10f51f14e021.png)

**Comment by cruzach** [comment] 2019-03-26 17:21
Hey @AlexMachin1997,

See [this comment](https://github.com/expo/expo/issues/345#issuecomment-344847834) on a previous issue that dealt with the same situation you're experiencing. After the user scans, you can set this to undefined and it won't continually scan. There are details on the implementation in the comments of that issue, so be sure to look through there!

Thanks,
Charlie

This is a duplicate of #345, so going to go ahead and close.

**Closed by cruzach** 2019-03-26 17:21 UTC
Labels: BarCodeScanner, needs repro

**Comment by AdamJNavarro** [comment] 2019-03-26 18:10
Hey @AlexMachin1997,

Just wanted to follow up about the issue you had trying to import your repo into Snack. Was it by chance a private repo? If so, that's likely the reason for the error. If it's public, would you mind sharing the repo with us so we can investigate what could be causing the import error? You can email us at secure@expo.io to continue discussions privately.

All the best,
Adam

**Comment by AlexMachin1997** [comment] 2019-03-26 18:44
Hey @AdamJNavarro ,

The repo is public, so it should be accepting it technically, unless its because its a bare-minimum workflow.

Heres the link to the repo https://github.com/AlexMachin1997/Food-Allergy-Mobile-Application , it's on the master branch.

Cheers,
Alex

**Comment by AlexMachin1997** [comment] 2019-03-26 19:10
Hey @cruzach ,

I tried something like that the other day but didn't seem to work.

**Comment by cruzach** [comment] 2019-03-26 19:30
I just tried it and it worked for me. Stay tuned for a little, I'm working on updating our docs right now to make that feature clear, and will update the example shown to illustrate it as well.

**Comment by AlexMachin1997** [comment] 2019-03-26 23:37
Cheers @cruzach , once I know I will be sure to spread the solution within the discord server.

**Comment by AlexMachin1997** [comment] 2019-03-27 20:56
@cruzach problem solved now.

I forgot to add a ternary operator to the onBarCodeScanned prop, works fine now. Just got to remember to set it back to false when the user closes the message box/modal.

**Comment by AlexMachin1997** [comment] 2019-04-13 11:05
So today I've just started messing around with my barcode scanner again, and yet it is still scanning when I go to another screen.

Doesn't it unmount the event listener when I leave the screen where the barcode module is used ?

**Comment by cruzach** [comment] 2019-04-14 15:29
@AlexMachin1997 so you're setting the prop to undefined when navigating to another screen, and the Barcode scanner still scans even when you do that?

**Comment by AlexMachin1997** [comment] 2019-04-14 18:29
Oh not when Im navigating to another screen, currently it's only when I scan an item.

I would use componentWllUnmount() but the component actually doesn't unmount. Let me explain. So when I'm on my main screen which is the tab navigator, an then navigate to a separate screen like edit-profile or settings I'm able to still scan items.

This is a weird bug as I can't seem to find any solution to this issue I'm facing.

**Comment by Amirjab21** [comment] 2019-07-18 10:25
@AlexMachin1997 I may have missed your point so apologies if so but I think this is to do with the fact that when you navigate between tabs, you're not unmounting components, instead you need to use React Navigation's listeners that detect when the tab is focused or blurred.
