### ISSUE TITLE
Invariant Violation: "main" has not been registered.

### ISSUE THREAD

**Issue by tashanemclean** [expo/expo#9407] opened 2020-07-26 23:19 UTC
I've followed all steps found in the closed issue: 9042 and I am still receiving this error.

`App.js

import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import * as React from 'react';
import { Platform, StatusBar, StyleSheet, View } from 'react-native';

import { Provider } from 'react-redux';
import { createStore, applyMiddleware } from "redux";
import thunk from 'redux-thunk';

import reducers from './components/reducers';

import useCachedResources from './hooks/useCachedResources';
import BottomTabNavigator from './navigation/BottomTabNavigator';
import LinkingConfiguration from './navigation/LinkingConfiguration';
import Pools from './components/pools/pools';

const store = createStore(reducers, applyMiddleware(thunk))

const Stack = createStackNavigator();

export default function App(props) {
  const isLoadingComplete = useCachedResources();

  if (!isLoadingComplete) {
    return null;
  } else {
    return (
      <Provider store={ store }>
        <View style={styles.container}>
        {Platform.OS === 'ios' && <StatusBar barStyle="dark-content" />}
        <NavigationContainer linking={LinkingConfiguration}>
          <Stack.Navigator headerTransparent='false'>
            <Stack.Screen 
              name="Root" 
              component={BottomTabNavigator} 
            />
            <Stack.Screen 
              name="Public Pools" 
              component={Pools}
            />
          </Stack.Navigator>
        </NavigationContainer>
      </View>
      </Provider>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
});
`
`package.json

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "~38.0.8",
    "expo-splash-screen": "~0.3.1",
    "expo-status-bar": "^1.0.2",
    "expo-updates": "~0.2.10",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "~0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-screens": "~2.9.0",
    "react-native-unimodules": "~0.10.1",
    "react-native-web": "~0.11.7",
    "@expo/vector-icons": "^10.0.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.6.1",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",
    "expo-asset": "~8.1.7",
    "expo-constants": "~9.1.1",
    "expo-font": "~8.2.1",
    "expo-linking": "^1.0.1",
    "expo-web-browser": "~8.3.1",
    "moment": "^2.27.0",
    "native-base": "^2.13.13",
    "patch-package": "^6.2.2",
    "react-native-agora": "^3.0.1-rc.2",
    "react-native-comments": "^1.1.7",
    "react-native-safe-area-context": "~3.0.7",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.11.0",
    "@types/react": "~16.9.23",
    "@types/react-native": "~0.62.13",
    "babel-preset-expo": "~8.1.0",
    "jest-expo": "~38.0.0",
    "typescript": "~3.9.5"
  },
  "private": true,
  "name": "susuappfrontend",
  "version": "1.0.0"
}
`
Upon creating a new project and only installing the dependencies I continue seeing this error. Are there any documented solutions for this? I've followed steps found on all of the responses I have come across for this issue.

**Comment by cruzach** [comment] 2020-07-27 13:21
@tashanemclean I'm not able to reproduce this on a fresh project created with `expo init`. What version of `expo-cli` are you using? The code you've shared is not a blank project, and there isn't enough information here for us to help you, so I'm going to close the issue for now- if you can provide all the info we ask for in the bug report template, I'll be happy to reopen it

**Closed by cruzach** 2020-07-27 13:21 UTC

**Comment by tashanemclean** [comment] 2020-07-27 20:38
expo-cli 3.22.3

**Comment by tashanemclean** [comment] 2020-07-27 21:18
I've created a new project several times and copy my component folder to the new project, but this error persists even then. The only solution was to RN init and exclude expo from my project. In the future I would like to use expo for my managed projects if I am able to figure out what is causing this error.

**Comment by cruzach** [comment] 2020-07-27 21:22
@tashanemclean your version shown of "react-native" was "~0.62.2", which indicates this is happening in the bare workflow (which is, essentially, a vanilla RN project). We'd love to help but we need a minimal reproducible demo to do so. In new managed workflow projects on SDK 38, react-native should be :
```
"react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz"
```
 and this will result in you seeing the actual error that is causing this issue, rather than the `"main" has not been registered` message

**Comment by tashanemclean** [comment] 2020-07-27 21:25
I will keep that in mind! Thank you very much for assist me! Now I am aware that this is not an expo issue, I will continue the debugging process until I resolve this issue!
