### ISSUE TITLE
Clarification On Camera Api

### ISSUE THREAD

**Issue by verzil** [expo/expo#886] opened 2017-10-30 22:27 UTC
##### After fiddling with the camera Api I need further clarification on how the camera module uses the native camera Apis. The two major problems i've encountered
- First it is unclear when the camera access control is being requested. It appears to be whenever the component that require the camera module is mounted. Camera access as asked, the access privilege is never relinquished.

##### for example if i request the camera module on a root component, and have a modal that uses the camera module again. The previous component will freeze
**Demonstrated by this snack**
https://snack.expo.io/BJUC0GSCb

this can be overcame with by re importing the camera module each time the component mounts
**Demonstrated by this snack**
https://snack.expo.io/H1_rEQH0W
(I extracted the Camera code into a separate module, that only mount one camera at a time)
(By you can use the toggle button to achieve the same effect as previous snack)

However on some phones, when you flip the camera, and go back the application freezes. I believe it is because the state of the camera within the native module is not cleared explicitly, and it can vary depending on the phone's native api.

- Second, I'd like to have more control over the Camera Api, at least further clarification in particular on how to fully relinquish control over the Camera module. Hopefully by the previous demonstration, you have see that it is unclear when did we have access of the native Camera module. There is another issue on some Android phones when using native phone camera.

For example when you open a expo application that use the Camera Api, exits the application, use the native phone camera application, and reopen the expo application. The expo application would crash due to unable to reclaim camera access. I believe this is the same case with my previous issue With ImagePicker api and Camera api being used together #870.

 I believe it would be a lot better to be able to explicitly destroy the Camera when we no longer need it. 

Thanks in advance.

**Comment by terribleben** [comment] 2017-10-31 17:34
Hey there - maybe @aalices can provide some clarification here. Also, all of this is open source so you may be able to just check out the source code for that component to see what it's doing.

My suspicion is that we should just track #870 and close this as a duplicate, unless you think there is a second issue here, and you can add this information as support to that thread.

**Comment by verzil** [comment] 2017-11-01 02:29
hey thanks for the reply. I have found and resolved my particular issue which is not really related to this module. It is because I was using react navigation which all of my views are loaded when app is loaded, caused collision with a later navigation.

However the issue I presented using snacks still exists which I feel still needs to be addressed.

I have looked into the java side of the code and saw that the module releases the camera upon surface view destroy. However I donno if that is a reliable way to destroy the camera. I feel there is too much 'magic' involved for a shared resources that can cause issues not only with your application, and maybe even with other applications that use the camera module.

I think I will close #870 just because i feel this issue is more generic, and could potentially solve #870 as well

Thank you for your time.

P.S. does my snack demo break as expected? i've only tested on my phone.

**Comment by aalices** [comment] 2017-11-02 11:54
Hello @verzil as you have noticed many of the issues are related to navigation. This is also discussed [here](https://forums.expo.io/t/camera-unable-to-take-2nd-picture-fail-to-connect-to-camera-service-error/3886). Camera is released when the component is unmounted - probably we have to say it clearly in the docs? Do you suggest exposing an ability to start/stop the Camera? So the problem is when you are navigating the previous screens are not really disappearing and Camera does not unmount -> it is not released. For now, there's not much we can do besides maybe recommending to "nullify" Camera when navigating (just like you did in the Snack rendering `null` instead of `Camera` based on current state). I will also investigate your ImagePicker issue (worked on my Huawei P10 - I have to find a device it crashes on). Thanks for a great feedback!

**Comment by verzil** [comment] 2017-11-04 02:00
Hy @aalices Thanks for clearing it out for me. I have read the Android code and deduced that the camera is let go when the view is unmounted. However the behavior is rather inconsistent. It seems that the file that imports the module needs to be unmounted, rather than just simply not render the Camera Component. 

For example if I was to use the same Camera component within the same component. It doesn't matter if i render the first one to ```null``` or not the second would still fail to request camera.

I just feel that it is very unpredictable when involved in a complex (with navigation and modal) situation.

With a explicit calls to open and close the camera Api, we will have more control over the module, and know how to deal with it rather than having an unexpected Application has crashed.

Thanks again for Helping me out!

**Comment by dikaiosune** [comment] 2017-11-06 19:34
Looks like this is a feature request now, so I'm migrating this over to https://expo.canny.io/feature-requests/p/explicit-openclose-methods-for-camera

Thanks!

**Closed by dikaiosune** 2017-11-06 19:34 UTC

**Comment by sibelius** [comment] 2017-12-14 13:46
you can check this PR lwansbrough/react-native-camera#859
