### ISSUE TITLE
[android] client errors frequently when using live reload, especially over tunnel

### ISSUE THREAD

**Issue by esamelson** [expo/expo#2435] opened 2018-10-16 21:48 UTC
Brent reported seeing these errors pretty frequently when developing over tunnel (and occasionally over LAN, as well) and live reloading: https://imgur.com/a/ADZPvLT . There may be a race condition when live reload triggers multiple times in a row. These errors are especially not helpful because they don't give the user much information about how to solve them.

Additionally, the client got in a weird state once when opening an experience for the first time,  where it would get to 10% and then restart the experience.

**Comment by Szymon20000** [comment] 2019-03-07 12:34
I couldn't reproduce the issue. Do I have to perform any specific actions?

**Comment by esamelson** [comment] 2019-03-08 00:14
@Szymon20000 thanks for taking a look at this. Have you tried turning live reloading on over a slow connection (e.g. tunnel) triggering a live reload by modifying a file, and then triggering another one right away while the first reload is still happening? IIRC this happened when multiple live reloads were triggered quickly in succession. But it's possible this has been fixed in newer RN versions.

(cc @brentvatne who originally reported this to me)

**Comment by Szymon20000** [comment] 2019-03-08 12:36
Yes, I have tried under the tunnel setting. Everything was fine.

**Comment by brentvatne** [comment] 2019-03-08 20:13
ok let's close this and i'll reopen if i encounter it again and will try to provide very clear instructions to reproduce

**Closed by brentvatne** 2019-03-08 20:13 UTC
Labels: project: android-runtime
