### ISSUE TITLE
expo-notifications: monthly notifications on Android and iOS

### ISSUE THREAD

**Issue by HristoEftimov** [expo/expo#10705] opened 2020-10-16 15:24 UTC
With the `Notifications` module from `Expo`  I was able to schedule simple monthly notifications on Android and iOS:

```
Notifications. scheduleLocalNotificationAsync(
    localNotification : {
        title: "Hello!",
        body: "This is a monthly notification",
    },
    schedulingOptions: {
        time: timestamp,
        repeat: "month",
    }
});
```

With the new module `expo-notifications` it looks impossible for Android. It supports TimeInterval and Daily triggers, but not weekly or monthly.

It will be good if `expo-notifications` support and monthly/weekly notifications.

**Comment by cruzach** [comment] 2020-10-19 18:24
closing as a duplicate of https://github.com/expo/expo/issues/9584

**Closed by cruzach** 2020-10-19 18:24 UTC
Labels: Android, Issue needs review, Notifications
