### ISSUE TITLE
Exit status: 65 error while building 51 sdk app using eas.

### ISSUE THREAD

**Issue by H4ck3r-x0** [expo/expo#28676] opened 2024-05-08 11:57 UTC
### Minimal reproducible example

https://github.com/rranjan14/my-app

### Did you reproduce this issue in a development build?

Yes

### Summary

Hello there, just upgraded from 50 to 51 sdk. 
and when i ran new build 
```
eas build --profile=preview --platform=ios
```

in the fastlane i got this error!
```
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptValue.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptTypedArray.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptRuntime.mm

❌  (node_modules/expo-modules-core/ios/JSI/EXJavaScriptRuntime.mm:31:8)

  29 | class SyncCallInvoker : public react::CallInvoker {
  30 | public:
> 31 |   void invokeAsync(std::function<void()> &&func) override {
     |        ^ exception specification of overriding function is more lax than base version
  32 |     func();
  33 |   }
  34 | 

› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptObject.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIUtils.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIInstaller.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIConversions.mm
▸ ** BUILD FAILED **
▸ The following build commands failed:
▸ 	CompileC /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/ExpoModulesCore.build/Objects-normal/x86_64/EXJavaScriptRuntime.o /Users/expo/workingdir/build/node_modules/expo-modules-core/ios/JSI/EXJavaScriptRuntime.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'ExpoModulesCore' from project 'Pods')
▸ (1 failure)
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/ExpoModulesCore.build/Objects-normal/x86_64/EXJavaScriptRuntime.o /Users/expo/workingdir/build/node_modules/expo-modules-core/ios/JSI/EXJavaScriptRuntime.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'ExpoModulesCore' from project 'Pods')
(1 failure)
Exit status: 65

+---------------------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.219.0                 |
| sdk         | iPhoneOS17.4.sdk        |
+-------------+-------------------------+

Looks like fastlane ran into a build/archive error with your project
It's hard to tell what's causing the error, so we wrote some guides on how
to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
Before submitting an issue on GitHub, please follow the guide above and make
sure your project is set up correctly.
fastlane uses `xcodebuild` commands to generate your binary, you can see the
the full commands printed out in yellow in the above log.
Make sure to inspect the output above, as usually you'll find more error information there

[!] Error building the application - see the log above
Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.
```

but when i ran the app locally everything works fine.

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 12.7.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.10.0 - /usr/local/bin/node
      npm: 10.2.3 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.0
      expo-router: ~3.5.10 => 3.5.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.6 => 0.19.11
    npmGlobalPackages:
      eas-cli: 8.0.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

❯ npx expo-doctor@latest
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by RogierZeebregts** [comment] 2024-05-08 12:46
Yes, had to remove it to be able to build again

**Comment by H4ck3r-x0** [comment] 2024-05-08 13:12
@RogierZeebregts can you tell me what did you remove? And what's the steps? Thanks

**Comment by RogierZeebregts** [comment] 2024-05-08 13:54
> @RogierZeebregts can you tell me what did you remove? And what's the steps? Thanks

@H4ck3r-x0 Sorry.... wasn't clear... had to remove `expo-dev-client` to make it work again.
Simply removed it, installed packages again, ran `pod install` and ran `run:ios`

**Comment by H4ck3r-x0** [comment] 2024-05-08 14:48
@RogierZeebregts Thank you a lot, okey what i've done is this.

```
npm remove expo-dev-client
```

and then  install it again, and i've rebuild it.
```
eas build --platform ios --profile preview --clear-cache
```

but in the eas dashboard at the fastlane i got this error again!

 ```
 › Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptValue.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptTypedArray.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptRuntime.mm

❌  (node_modules/expo-modules-core/ios/JSI/EXJavaScriptRuntime.mm:31:8)

  29 | class SyncCallInvoker : public react::CallInvoker {
  30 | public:
> 31 |   void invokeAsync(std::function<void()> &&func) override {
     |        ^ exception specification of overriding function is more lax than base version
  32 |     func();
  33 |   }
  34 | 

› Compiling expo-modules-core Pods/ExpoModulesCore » EXJavaScriptObject.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIUtils.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIInstaller.mm
› Compiling expo-modules-core Pods/ExpoModulesCore » EXJSIConversions.mm
▸ ** BUILD FAILED **
▸ The following build commands failed:
▸ 	CompileC /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/ExpoModulesCore.build/Objects-normal/x86_64/EXJavaScriptRuntime.o /Users/expo/workingdir/build/node_modules/expo-modules-core/ios/JSI/EXJavaScriptRuntime.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'ExpoModulesCore' from project 'Pods')
▸ (1 failure)
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/ExpoModulesCore.build/Objects-normal/x86_64/EXJavaScriptRuntime.o /Users/expo/workingdir/build/node_modules/expo-modules-core/ios/JSI/EXJavaScriptRuntime.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'ExpoModulesCore' from project 'Pods')
(1 failure)
Exit status: 65

+---------------------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.219.0                 |
| sdk         | iPhoneOS17.4.sdk        |
+-------------+-------------------------+

Looks like fastlane ran into a build/archive error with your project
It's hard to tell what's causing the error, so we wrote some guides on how
to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
Before submitting an issue on GitHub, please follow the guide above and make
sure your project is set up correctly.
fastlane uses `xcodebuild` commands to generate your binary, you can see the
the full commands printed out in yellow in the above log.
Make sure to inspect the output above, as usually you'll find more error information there

[!] Error building the application - see the log above
Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.
```

i do not really know what to do! the app locally works fine on the simulator.

**Comment by brentvatne** [comment] 2024-05-08 20:37
this is a duplicate of #28209, we'll follow up there! thanks for the report

**Closed by brentvatne** 2024-05-08 20:37 UTC
Labels: Android, Expo Modules Core, needs review

**Comment by H4ck3r-x0** [comment] 2024-05-09 05:34
i had smiler issue yesterday, #28676, and what i did is i installed fresh expo app, and i looked at the package.json file and i had to remove some of i think it is not unnecessary, that i do not really know what they are.
```
  "resolutions": {
    "react-refresh": "~0.14.0",
    "expo-modules-core": "~1.11.0"
  },
  "overrides": {
    "react-refresh": "~0.14.0",
    "expo-modules-core": "~1.11.0"
  },
  "expo": {
    "install": {
      "exclude": [
        "react-native-safe-area-context"
      ]
    }
  },
  ```
  the above code is from my old package.json so i removed them, and rebuild the app 
  ```
  eas build --platform ios --profile preview
  ```
  and the build went smoothly.
  
  so this is my old package.json,
  ```
  {
  "name": "here is my app name :)",
  "version": "1.0.0",
  "scripts": {
    "android": "expo start --android",
    "format": "eslint \"**/*.{js,jsx,ts,tsx}\" --fix && prettier \"**/*.{js,jsx,ts,tsx,json}\" --write",
    "ios": "expo start --ios",
    "start": "expo start",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@react-native-picker/picker": "2.7.5",
    "@react-navigation/native": "^6.1.7",
    "axios": "^1.6.5",
    "expo": "^51.0.0",
    "expo-font": "~12.0.4",
    "expo-image-picker": "~15.0.4",
    "expo-linking": "~6.3.1",
    "expo-localization": "~15.0.3",
    "expo-location": "~17.0.1",
    "expo-router": "~3.5.10",
    "expo-secure-store": "~13.0.1",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.4",
    "expo-updates": "~0.25.9",
    "expo-web-browser": "~13.0.3",
    "moment": "^2.30.1",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.1",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-reanimated": "3.10.0",
    "react-native-safe-area-context": "^4.6.3",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "@typescript-eslint/eslint-plugin": "^6.7.2",
    "@typescript-eslint/parser": "^6.7.2",
    "eslint": "^8.50.0",
    "eslint-config-universe": "^12.0.0",
    "prettier": "^3.0.3",
    "tailwindcss": "3.3.2",
    "typescript": "~5.3.3"
  },
  "eslintConfig": {
    "extends": "universe/native"
  },
  "resolutions": {
    "react-refresh": "~0.14.0",
    "expo-modules-core": "~1.11.0"
  },
  "overrides": {
    "react-refresh": "~0.14.0",
    "expo-modules-core": "~1.11.0"
  },
  "expo": {
    "install": {
      "exclude": [
        "react-native-safe-area-context"
      ]
    }
  },
  "private": true
}
``` 

the new package.json
```
{
  "name": "this is my app name :)",
  "version": "1.0.0",
  "scripts": {
    "android": "expo start --android",
    "format": "eslint \"**/*.{js,jsx,ts,tsx}\" --fix && prettier \"**/*.{js,jsx,ts,tsx,json}\" --write",
    "ios": "expo start --ios",
    "start": "expo start",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@react-native-picker/picker": "2.7.5",
    "@react-navigation/native": "^6.1.7",
    "axios": "^1.6.5",
    "expo": "~51.0.0",
    "expo-font": "~12.0.4",
    "expo-image-picker": "~15.0.4",
    "expo-linking": "~6.3.1",
    "expo-location": "~17.0.1",
    "expo-router": "~3.5.10",
    "expo-secure-store": "~13.0.1",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.4",
    "expo-updates": "~0.25.9",
    "expo-web-browser": "~13.0.3",
    "moment": "^2.30.1",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.1",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-safe-area-context": "^4.6.3",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.6",
    "react-native-reanimated": "3.10.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "@typescript-eslint/eslint-plugin": "^6.7.2",
    "@typescript-eslint/parser": "^6.7.2",
    "eslint": "^8.50.0",
    "eslint-config-universe": "^12.0.0",
    "prettier": "^3.0.3",
    "tailwindcss": "3.3.2",
    "typescript": "~5.3.3"
  },
  "eslintConfig": {
    "extends": "universe/native"
  },
  "private": true
}
```

also i changed the eas.json file 
```
{
  "cli": {
    "version": ">= 9.0.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "channel": "development"
    },
    "preview": {
      "distribution": "internal",
      "ios": {
        "simulator": true
      },
      "channel": "preview"
    },
    "production": {
      "channel": "production"
    }
  },
  "submit": {
    "production": {}
  }
}
```

to use the version of eas cli to 9.0.0 it was something like 7.0.
