### ISSUE TITLE
Bare Workflow - expo-updates crashes on iOS and error on Android.

### ISSUE THREAD

**Issue by Edai** [expo/expo#7846] opened 2020-04-15 02:50 UTC
# 👇 The answer to this issue 👇

Please read this comment: https://github.com/expo/expo/issues/7846#issuecomment-629720280

<hr />

# The original report

### Environment

  Expo CLI 3.17.24 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.6 => 37.0.7 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.17.24

### Steps to Reproduce

- `expo init`
- Pick "minimal" in Bare Workflow
-  `yarn install expo-updates expo-asset`
- Add in **App.js** in a `useEffect` hook : `const update = await Updates.checkForUpdateAsync();`
- `expo publish`
- run`yarn ios` or `yarn android`.

### Expected Behavior

The app should run normally without any issue.
Indeed my folder ios/PROJECT/Supporting/ contains`app.bundle, app.manifest, Expo.plist` filled up and `AppDelegate.h` and `AppDelegate.m `are updated.

### Actual Behavior

It crashes on iOS with "*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[OS_dispatch_data writeToFile:options:error:]: nil file argument'"

I get an error on Android: [Error: The updates module controller has not been properly initialized. If you're using a development client, you cannot check for updates. Otherwise, make sure you have called the native method UpdatesController.initialize().]

### Reproducible Demo

- `expo init`
- Pick "minimal" in Bare Workflow
-  `yarn install expo-updates expo-asset`
- Add in **App.js** in a `useEffect` hook : `const update = await Updates.checkForUpdateAsync();`
- `expo publish`
- run`yarn ios` or `yarn android`.

### Questions

Does it crash on iOS because it is in "development mode" ?
Is `releasing the app` the only way to test both apps?

**Comment by byCedric** [comment] 2020-04-16 13:22
Hi @Edai! On iOS the `Updates.checkForUpdateAsync` should not crash your app. Instead, it should reject just like Android. Unfortunately, I couldn't reproduce this crash on iOS. When I use this in development, I see `Error: unsupported URL`. Could you provide a minimal reproducible repo for this?

About the updates on development, the short answer is yes; Updates can only check if there are updates available in production ([docs](https://github.com/expo/expo/tree/master/packages/expo-updates#updatescheckforupdateasync)). This is mostly because the "local" app is running a different bundle, the one from Metro. The best thing you can do is check if your app is running a local/development build and handle the updates accordingly.

Hope it helps!

**Comment by manoj-makkuboy** [comment] 2020-04-21 05:11
I am facing the same issue. If I remove *await Updates.checkForUpdateAsync()* Things work fine else I am getting the same exception [OS_dispatch_data writeToFile:options:error:]: nil file.

**Comment by manoj-makkuboy** [comment] 2020-04-21 21:11
updating expo-updates 0.1.2 fixes this.

**Comment by manoj-makkuboy** [comment] 2020-04-24 07:26
> updating expo-updates 0.1.2 fixes this.

momentarily It seemed to work, but now it's not working.

**Comment by nicwhitts** [comment] 2020-05-15 07:26
Did you find a fix for this? Im having same problem

**Comment by EdmundMai** [comment] 2020-05-16 23:29
I'm having this problem too

**Comment by brentvatne** [comment] 2020-05-16 23:42
# how to test manual update checking easily

if you would like to test manual updates on your machine, do a release build: `yarn ios --configuration Release` or `yarn android --variant Release` - you don't have to submit that to the store to test it.

checking for updates on debug builds doesn't make much sense because what version do you compare against? you need to have a local version of the app and a remote version of the app with some concept of which one is the "latest" version.

# what we will do to make this more obvious

that said, we absolutely should not crash in this context. instead we should just return some noop value, and provide some information in docs about how to test this flow.

@esamelson - here is an easy to follow reproducible example for you: https://github.com/brentvatne/issues-7846 - just run `yarn ios` to see app will crash.

**Closed** 2020-05-20 00:32 UTC
Labels: Updates, needs repro, project: ios-runtime
