### ISSUE TITLE
Android: There was an error with this build

### ISSUE THREAD

**Issue by tjunxiang92** [expo/expo#945] opened 2017-11-10 10:25 UTC
Hi, I'm having trouble compiling the android version. It produced the following.
Running `exp build:android` got me `Android: There was an error with this build.`

Build ID: cf5d720e-4757-43f8-a75f-ab8e70c15310

app.json
```json
{
  "expo": {
    "name": "Gratitude",
    "description": "Gratitude was created for one purpose, bring us through our toughest time through recording our best times.",
    "slug": "gratitude",
    "privacy": "public",
    "sdkVersion": "22.0.0",
    "version": "1.0.0",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.im-juxyz.gratitude"
    },
    "android": {
      "package": "com.im-juxyz.gratitude",
      "config": {
        "googleMaps": {
          "apiKey": "..."
        }
      },
      "versionCode": 1,
      "permissions": []
    }
  }
}
```

Appreciate any form of help :)

**Comment by jimmylee** [comment] 2017-11-13 20:20
Hey @tjunxiang92 I'm really sorry it took me a while to get to you

Here are some errors that appeared in your logs:

`Execution failed for task ':expoview:processReleaseResources'`
`"/src/exponent/android-shell-app/expoview/build/intermediates/manifests/aapt/release/AndroidManifest.xml:23: Tag <uses-permission> attribute name has invalid character '-'.",`
`"message": "Unable to download manifest from undefined: Can't read JSON file: /src/exponent/dev-home-config.json",`

Let us know if these errors make any sense to you, and if not, we'll continue to work with you to find a solution.

**Comment by ide** [comment] 2017-11-17 00:07
Java package names can't have hyphens in them (`com.im-juxyz.gratitude`) -- this lines up with the error message above. Closing this since I suspect that is the cause.

**Closed by ide** 2017-11-17 00:07 UTC
