### ISSUE TITLE
expo-yarn-workspaces not working with hooks?

### ISSUE THREAD

**Issue by amirmishani** [expo/expo#6287] opened 2019-11-15 16:04 UTC
I'm trying to get an expo mono repo to work. I feel like I finally setup everything correctly but now I'm seeing this error:

 Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)

**Comment by cruzach** [comment] 2019-11-15 16:38
Could you follow the full bug report? 

My guess here is that it's a [duplicate react issue](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react)

**Comment by ide** [comment] 2019-11-20 20:50
Hooks and expo-yarn-workspaces should be very separate from each other. The error message makes it sound like you're calling hooks in the wrong place. This issue needs more investigation to identify the root cause.

**Comment by SebSchwartz** [comment] 2020-01-27 17:12
I got the same error with a fresh install of expo and a new expo project inside a monorepo :(

**Comment by SebSchwartz** [comment] 2020-01-28 14:43
@cruzach 
Not a resolution problem... Already tried to fix it with react version resolution but still got the issue.

**Comment by SebSchwartz** [comment] 2020-01-28 14:47
Here is the full error log:
`
Running "main" with {"initialProps":{"exp":{"initialUri":"exp://192.168.70.108:19000","manifest":{"env":{},"id":"@xxx/mobile","privacy":"public","assetBundlePatterns":["**/*"],"primaryColor":"#023C69","bundleUrl":"http://192.168.70.108:19003/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false","slug":"mobile","name":"mobile","icon":"./assets/images/icon.png","xde":true,"loadedFromCache":false,"splash":{"resizeMode":"contain","backgroundColor":"#ffffff","image":"./assets/images/splash.png","imageUrl":"http://192.168.70.108:19003/assets/./assets/images/splash.png"},"orientation":"portrait","iconUrl":"http://192.168.70.108:19003/assets/./assets/images/icon.png","isVerified":true,"version":"1.0.0","developer":{"tool":"expo-cli","projectRoot":"/Users/xxxx/Documents/Dev/xxxx/packages/mobile"},"mainModuleName":"__generated__/AppEntry","debuggerHost":"192.168.70.108:19003","logUrl":"http://192.168.70.108:19000/logs","packagerOpts":{"https":false,"dev":true,"lanType":"ip","hostType":"lan","minify":false,"urlRandomness":"eq-2zc"},"sdkVersion":"36.0.0","platforms":["ios","android","web"],"hostUri":"192.168.70.108:19000","ios":{"supportsTablet":true},"updates":{"fallbackToCacheTimeout":0}},"shell":false}},"rootTag":21}
`
```
ExceptionsManager.js:44 Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

This error is located at:
    in ExpoRoot (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)```

**Comment by SebSchwartz** [comment] 2020-01-28 16:08
I resolved it with the react version in the whole workspace.
When it was > 16.9.0 it breaks with the error.
So I changed in all packages.json the react and react-dom to fit version "16.9.0" (**NOT with a "^16.9.0"**) and now it works.

Hope react version can be updated soon.

**Comment by SebSchwartz** [comment] 2020-01-28 16:09
> @cruzach
> Not a resolution problem... Already tried to fix it with react version resolution but still got the issue.

Resolution doesn't work inside yarn workspace in packages (it should in yarn V2)

**Comment by taylorlapeyre** [comment] 2020-02-19 01:20
Ean into this today. Definitely an issue!

**Comment by taylorlapeyre** [comment] 2020-02-19 01:53
@SebSchwartz did you just ensure that every workspace used version `16.9.0`, or did you add react to the root node_modules at that version?

**Comment by Slapbox** [comment] 2020-04-05 20:37
Working through this now. I can't guarantee this will fix it for anyone, but use `yarn why react` to ensure you've only got one version used throughout the monorepo.

Fingers crossed...

**Comment by tomcorey26** [comment] 2020-04-10 19:54
Making everything in the workspace the same version of React fixed it for me :)

**Comment by EvanBacon** [comment] 2022-01-07 01:16
It appears the issue is entirely related to having multiple versions of react (and probably react-native has a similar issue),. Short of an intrusive operation to force react versions on postinstall, there isn't much we can do in `expo-yarn-workspaces` to ensure this doesn't happen so I'll be closing this issue.

**Closed by EvanBacon** 2022-01-07 01:16 UTC
Labels: yarn-workspaces

**Comment by jwtong** [comment] 2024-12-11 04:04
Adding a note here that this is still the case with monorepos. On my Turbo monorepo I had to specify all React versions to 
"18.3.0" to resolve the `"Invalid Hook Call"` error.

**Comment by Nantris** [comment] 2024-12-11 05:56
I'm pretty sure you're not supposed to be using expo-yarn-workspaces anymore. Does the issue resolve if you remove it? And are there any other ill effects of doing so? Removing it worked for us.

**Comment by jwtong** [comment] 2024-12-11 07:24
@Nantris  No this is for a turbo monorepo using pnpm as the package manager. There were issues even when removing node_modules and reinstalling if the react version was not explicitly specified.

**Comment by jwtong** [comment] 2024-12-14 05:38
Ignore what I mentioned, the fix is here

https://github.com/expo/expo/issues/18038#issuecomment-1734833421
