### ISSUE TITLE
iOS Build Crash on Expo Name Change

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [expo/expo#30679] opened 2024-07-29 10:15 UTC
### Summary

So i was just changing in `app.json` the field `expo.name` from `"Rocket Meals Demo"` to `"SWOSY"`. Just normal ASCII chars.

Before (everything works):
```
{
  "expo": {
    "name": "Rocket Meals Demo",
    "slug": "rocket-meals-swosy",
```

After (error):
```
{
  "expo": {
    "name": "SWOSY",
    "slug": "rocket-meals-swosy",
```

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

https://expo.dev/accounts/baumgartner-software/projects/rocket-meals-swosy/builds/6cd69812-cb61-4b8f-b18f-49c946a2f09b

It crashes at the fastlane, see Stacktrace

The build before ONLY the change of the name works: https://expo.dev/accounts/baumgartner-software/projects/rocket-meals-swosy/builds/d77b0c21-0a74-464b-9730-204eaf38f4bb

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
      Watchman: 2024.07.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.14 => 51.0.14
      expo-router: ~3.5.16 => 3.5.16
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
      react-native-web: ~0.19.6 => 0.19.10
    npmGlobalPackages:
      eas-cli: 7.4.0
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/rocket-meals/expo-ios-name-change-error

As we believe that this error has something to do with the Fastlane and expo, we dont know if that reproduceable demo can help. 

### Stacktrace (if a crash is involved)

Here is the XCODE Log:

[xcode-build-6cd69812-cb61-4b8f-b18f-49c946a2f09b.log](https://github.com/user-attachments/files/16411166/xcode-build-6cd69812-cb61-4b8f-b18f-49c946a2f09b.log)

```
 Compiling SWOSY » SplashScreen.storyboard

› Preparing SWOSY » Info.plist

› Compiling SWOSY » main.m

› Compiling SWOSY » SWOSY_vers.c

› Compiling SWOSY » AppDelegate.mm


⚠️  (../../../../../../Headers/Public/ExpoModulesCore/ExpoModulesCore/EXFileSystemInterface.h:21:43)

- (BOOL)ensureDirExistsWithPath:(NSString *)path;
                                          ^ pointer is missing a nullability type specifier [-Wnullability-completeness]

› Linking   SWOSY » SWOSY

⚠️  ld: ignoring duplicate libraries: '-lc++'

› Generating debug SWOSY » SWOSY.app.dSYM

› Executing SWOSY » Bundle React Native code and images

    Bundler cache is empty, rebuilding (this may take a minute)

▸ ** ARCHIVE FAILED **

▸ The following build commands failed:

▸ 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/SWOSY-aznfegfgiindftdwfmjiqzokcqyz/Build/Intermediates.noindex/ArchiveIntermediates/SWOSY/IntermediateBuildFilesPath/SWOSY.build/Release-iphoneos/SWOSY.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'SWOSY' from project 'SWOSY')

▸ (1 failure)

** ARCHIVE FAILED **

The following build commands failed:

	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/SWOSY-aznfegfgiindftdwfmjiqzokcqyz/Build/Intermediates.noindex/ArchiveIntermediates/SWOSY/IntermediateBuildFilesPath/SWOSY.build/Release-iphoneos/SWOSY.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'SWOSY' from project 'SWOSY')

(1 failure)

+---------------------------------------+

|           Build environment           |

+-------------+-------------------------+

| xcode_path  | /Applications/Xcode.app |

| gym_version | 2.220.0                 |

| sdk         | iPhoneOS17.5.sdk        |

+-------------+-------------------------+

Looks like fastlane ran into a build/archive error with your project

It's hard to tell what's causing the error, so we wrote some guides on how

to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/

Before submitting an issue on GitHub, please follow the guide above and make

sure your project is set up correctly.

fastlane uses `xcodebuild` commands to generate your binary, you can see the

the full commands printed out in yellow in the above log.

Make sure to inspect the output above, as usually you'll find more error information there

[!] Error building the application - see the log above

Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.
```

In the Xcode logs it seems to be this problem:

```
riting bundle output to: /Users/expo/Library/Developer/Xcode/DerivedData/SWOSY-aznfegfgiindftdwfmjiqzokcqyz/Build/Intermediates.noindex/ArchiveIntermediates/SWOSY/BuildProductsPath/Release-iphoneos/main.jsbundle
Copying 35 asset files
Error: ENOTDIR: not a directory, mkdir '/Users/expo/Library/Developer/Xcode/DerivedData/SWOSY-aznfegfgiindftdwfmjiqzokcqyz/Build/Intermediates.noindex/ArchiveIntermediates/SWOSY/BuildProductsPath/Release-iphoneos/SWOSY.app/swosy/assets/node_modules/@react-navigation/elements/src/assets'
Error: ENOTDIR: not a directory, mkdir '/Users/expo/Library/Developer/Xcode/DerivedData/SWOSY-aznfegfgiindftdwfmjiqzokcqyz/Build/Intermediates.noindex/ArchiveIntermediates/SWOSY/BuildProductsPath/Release-iphoneos/SWOSY.app/swosy/assets/node_modules/@react-navigation/elements/src/assets'
Command PhaseScriptExecution failed with a nonzero exit code
```

So my guess is that the change of the name leads that a directory is not created correctl.y

**Comment by NilsBaumgartner1994** [comment] 2024-07-29 11:56
Maybe it has something to do with the pregenereated ios and android folders?
Trying to run prebuild --clean
https://www.reddit.com/r/reactnative/comments/12bwawp/how_to_rename_a_expo_managed_project/

```
Rename in app.json
npx expo prebuild --clean
```

**Comment by NilsBaumgartner1994** [comment] 2024-07-29 12:13
> Maybe it has something to do with the pregenereated ios and android folders? Trying to run prebuild --clean https://www.reddit.com/r/reactnative/comments/12bwawp/how_to_rename_a_expo_managed_project/
> 
> ```
> Rename in app.json
> npx expo prebuild --clean
> ```

Nope, that does not helped, since extra files are only generated

**Comment by NilsBaumgartner1994** [comment] 2024-07-29 12:13
Maybe eas is using cache? https://docs.expo.dev/build-reference/caching/
Trying with eas build --clear-cache

**Comment by NilsBaumgartner1994** [comment] 2024-07-29 12:27
> Maybe eas is using cache? https://docs.expo.dev/build-reference/caching/ Trying with
> 
> ```
> eas build --clear-cache
> ```

Did not help either.

**Comment by NilsBaumgartner1994** [comment] 2024-07-29 12:47
Trying to change to a slightly different name only: "Rocket Meals Demo" -> "Rocket Meals SWOSY"

**Comment by NilsBaumgartner1994** [comment] 2024-07-29 13:05
> Trying to change to a slightly different name only: "Rocket Meals Demo" -> "Rocket Meals SWOSY"

This works: https://expo.dev/accounts/baumgartner-software/projects/rocket-meals-swosy/builds/d0ced355-f539-4f44-b0b1-271ebe518c5c

Now changing "Rocket Meals SWOSY" to "R SWOSY"

**Comment by NilsBaumgartner1994** [comment] 2024-07-29 13:17
> > Trying to change to a slightly different name only: "Rocket Meals Demo" -> "Rocket Meals SWOSY"
> 
> This works: https://expo.dev/accounts/baumgartner-software/projects/rocket-meals-swosy/builds/d0ced355-f539-4f44-b0b1-271ebe518c5c
> 
> Now changing "Rocket Meals SWOSY" to "R SWOSY"

This worked too: https://expo.dev/accounts/baumgartner-software/projects/rocket-meals-swosy/builds/abde0ab0-17e9-4f7c-8089-b6691c871bc9

Now changing the name "R SWOSY" to "SWOSY"

**Comment by NilsBaumgartner1994** [comment] 2024-07-29 13:28
> > > Trying to change to a slightly different name only: "Rocket Meals Demo" -> "Rocket Meals SWOSY"
> > 
> > 
> > This works: https://expo.dev/accounts/baumgartner-software/projects/rocket-meals-swosy/builds/d0ced355-f539-4f44-b0b1-271ebe518c5c
> > Now changing "Rocket Meals SWOSY" to "R SWOSY"
> 
> This worked too: https://expo.dev/accounts/baumgartner-software/projects/rocket-meals-swosy/builds/abde0ab0-17e9-4f7c-8089-b6691c871bc9
> 
> Now changing the name "R SWOSY" to "SWOSY"

That crashed: https://expo.dev/accounts/baumgartner-software/projects/rocket-meals-swosy/builds/d21e11f5-365a-495b-86f1-096bf94a7e82

**Comment by NilsBaumgartner1994** [comment] 2024-07-29 15:13
I believe that the problem might result due that we have already an App with the name "SWOSY". With the already existing app maybe some problem exist with the certificate.

**Comment by brentvatne** [comment] 2024-07-31 00:31
(closing this for now because it's not actionable without a minimal reproducible example)

**Closed** 2024-07-31 00:31 UTC
Labels: Development Builds, needs review

**Comment by NilsBaumgartner1994** [comment] 2024-07-31 08:21
Sorry, haven though about this:

Here is the EAS Build with name "SWOSYr" which runs successfull: https://expo.dev/accounts/baumgartner-software/projects/expo-ios-name-change-error/builds/84239a67-874a-4b42-ab53-b748025f5d56

Here is the EAS Build with the name "SWOSY" which fails: https://expo.dev/accounts/baumgartner-software/projects/expo-ios-name-change-error/builds/d4fbbb0b-08b6-4cb1-b23e-61f1b77685b5

Here is (again) the link to the minimal reproducible example: https://github.com/rocket-meals/expo-ios-name-change-error
As you can see in the commit: https://github.com/rocket-meals/expo-ios-name-change-error/commit/8bbe2f478915579caf2fe25ffd120aa9a4ee64ce

Only the name
```
-    "name": "SWOSYr",
+    "name": "SWOSY",
```

And the version bumb increase
```
-      "buildNumber": "21"
+      "buildNumber": "22"
```

happend.

**Comment by NilsBaumgartner1994** [comment] 2024-08-15 15:10
@brentvatne Sorry, haven though about this. Please reopen this issue:

Here is the EAS Build with name "SWOSYr" which runs successfull: https://expo.dev/accounts/baumgartner-software/projects/expo-ios-name-change-error/builds/84239a67-874a-4b42-ab53-b748025f5d56

Here is the EAS Build with the name "SWOSY" which fails: https://expo.dev/accounts/baumgartner-software/projects/expo-ios-name-change-error/builds/d4fbbb0b-08b6-4cb1-b23e-61f1b77685b5

Here is (again) the link to the minimal reproducible example: https://github.com/rocket-meals/expo-ios-name-change-error
As you can see in the commit: https://github.com/rocket-meals/expo-ios-name-change-error/commit/8bbe2f478915579caf2fe25ffd120aa9a4ee64ce

**Comment by brentvatne** [comment] 2024-08-15 17:27
hi @NilsBaumgartner1994 - can you please make the example minimal? it includes a bunch of unrelated code. more info: https://stackoverflow.com/help/minimal-reproducible-example
