### ISSUE TITLE
[expo-notifications] notification.request.content.data is null in push notifications setup

### ISSUE THREAD

**Issue by brandon-kyle-bailey** [expo/expo#27503] opened 2024-03-07 17:54 UTC
### Minimal reproducible example

https://github.com/brandon-kyle-bailey/expo-notifications-bug

### What platform(s) does this occur on?

Android, iOS, Web

### Did you reproduce this issue in a development build?

Yes

### Summary

Following documentation to [set up push notifications](https://docs.expo.dev/push-notifications/push-notifications-setup/) and utilizing https://expo.dev/notifications to send push notifications with a data object in the message, the data object is null.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
      npm: 9.2.0 - ~/.nvm/versions/node/v18.13.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.11 => 50.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 7.1.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by brandon-kyle-bailey** [comment] 2024-03-08 14:32
@vladica86 is your setup the same as the one in the repo i posted with this issue? in my case, im not able to get the data object on IOS either. wondering if theres something different about our environments. Hopefully the devs confirm if this is an internal issue soon

**Comment by vladica86** [comment] 2024-03-08 14:40
@brandon-kyle-bailey - I'm on managed expo 49.0.7 and react-native 0.72.10. 

It is most probably internal issue, since it doesn't contain data even if you test it from Expo push notification tool, and console log it immediately when notification is received.

**Comment by KMathisGit** [comment] 2024-03-13 15:08
@brandon-kyle-bailey I also am facing this issue. In fact I have noticed a few oddities around notifications recently:

1. The actual JSON data determines if notification is even received or not.

- `{"foo": "bar"}` _notification is received_
- `{"foo": "bar", "myObj": {"testKey": "testVal"}}` _notification is NOT received_
- `{"foo": 123}`  _notification is NOT received_

2. Notifications that are "received" still have prop data set to `null` - but I did notice that the JSON data can be found inside of `notification.request.trigger.remoteMessage.data`. It appears to be flattened amongst other key-values though and is not ideal.

3. The notification alert pop-up for android is not showing when app is backgrounded (this is likely unrelated to above issues but still something I feel worth mentioning)

**Comment by arjayosma** [comment] 2024-03-13 16:22
> @brandon-kyle-bailey I also am facing this issue. In fact I have noticed a few oddities around notifications recently:
> 
> 1. The actual JSON data determines if notification is even received or not.
> 
> * `{"foo": "bar"}` _notification is received_
> * `{"foo": "bar", "myObj": {"testKey": "testVal"}}` _notification is NOT received_
> * `{"foo": 123}`  _notification is NOT received_
> 
> 2. Notifications that are "received" still have prop data set to `null` - but I did notice that the JSON data can be found inside of `notification.request.trigger.remoteMessage.data`. It appears to be flattened amongst other key-values though and is not ideal.
> 3. The notification alert pop-up for android is not showing when app is backgrounded (this is likely unrelated to above issues but still something I feel worth mentioning)

This is exactly what my team is facing right now. We have to resort to adding a conditional (device-specific: iOS or Android) for your `myObj` or our `messageData` from our backend so as to trigger a notification for both devices. Problem is that we're depending on `messageData` object for additional information and redirection when opening the app.

**Comment by vladica86** [comment] 2024-03-13 16:32
I hope someone will look at this soon, since it's breaking issue for many apps that using push notifications

**Comment by wen-kai** [comment] 2024-03-13 21:45
our team is also facing this for android on expo sdk 49 and expo-notifications@~0.20.1
`addNotificationReceivedListener` is always a null `data` payload
`addNotificationResponseReceivedListener` is never called when pressing the notification from background

**Comment by vladica86** [comment] 2024-03-26 07:52
Is there any plan to fix this, or should we look for other solution for push notifications out of the expo?

**Comment by appsgenie** [comment] 2024-04-01 04:17
Seeing the same issue here.
Client app in production works fine with legacy API.
When I send with useFcmV1=true, tapping the notification just takes me to the main page instead of the screen that used to work.
I also noticed that the custom app icon is missing in the android notification next to the app name. Switching back to legacy show the icon fine.

**Comment by nemoneph** [comment] 2024-04-04 10:01
Facing the same problem on Android only with useFcmV1=true.
Only workaround I have is to switch back to legacy.

**Comment by therealrinku** [comment] 2024-04-07 12:08
same problem for me too 

{"date": 171249139631, "request": {"content": {"autoDismiss": true, "badge": null, "body": null, "data": null, "sound": "default", "sticky": false, "subtitle": null, "title": "testing there"}, "identifier": "0:171599%9d63da97f9fd7ecd", "trigger": {"channelId": null, "remoteMessage": [Object], "type": "push"}}}

content.data and content.body both are null even though they are sent from the push notification provider.

push notification only shows title, if I delete expo-notifications package then notification body is visible

**Comment by appsgenie** [comment] 2024-04-07 18:31
@nemoneph and @therealrinku , are you guys also seeing any changes with the app icon that shows on the incoming notification?

**Comment by douglowder** [comment] 2024-04-09 02:57
Testing this today with SDK 50, FCMv1, and using the web notifications tool at  https://expo.dev/notifications

I'm not able to reproduce the issue on iOS or Android development builds.

I started with the code in https://github.com/brandon-kyle-bailey/expo-notifications-bug , and my modifications are in https://github.com/douglowder/expo-notifications-bug

WIll test Android release build next.

**Comment by douglowder** [comment] 2024-04-09 18:09
So far, I am not able to reproduce this issue on either platform, with either release or debug builds. See above for my client-side code.

**Comment by douglowder** [comment] 2024-04-09 19:02
Closing this since it is not reproducible currently. I'm happy to reopen this if these issues appear again, or if there is a specific type of notification payload that is causing problems.

**Comment by KMathisGit** [comment] 2024-04-09 19:09
> So far, I am not able to reproduce this issue on either platform, with either release or debug builds. See above for my client-side code.

If you are sure that you using new FCM V1 API when sending push notification? This code you wrote here [App.js](https://github.com/douglowder/expo-notifications-bug/blob/9f6f777a20367e5b83fe25eb9d901c147c33cb5b/App.js#L18) does not include query parameter `useFcmV1` to force use the new FCM V1 API (default behavior would still use legacy if applicable).

**Comment by vladica86** [comment] 2024-04-09 19:32
I still have an issue on SDK 49, no FCM V1, and it is very reproducible

**Comment by appsgenie** [comment] 2024-04-09 22:50
@douglowder please please do not close as this is really impacting us in production. 
we can't force update all clients on a new SDK (currently the application is using SDK 48 if this matters).
so we are hoping for a server-side only fix here, which is what [this ](https://expo.dev/blog/expo-adds-support-for-fcm-http-v1-api)is referring to and sounded very promising.

like @KMathisGit mentioned, it ONLY happens when `https://exp.host/--/api/v2/push/send?useFcmV1=true` is called.
so literally everything stays the same and only this flag gets set to true/false and it causes 2 issues: 1) no data passed via the notification and 2) the notification icon is OS default gray circle.

**Comment by christopherwalter** [comment] 2024-04-09 23:08
Hi all, sorry for the thrash here. I'm investigating and will get a fix landed ASAP. Expect an update in the next day or two.

**Comment by vladica86** [comment] 2024-04-10 06:17
@christopherwalter - Just one thing to note here, not only that data received with notification is null, but addNotificationResponseReceivedListener doesn't get triggered anymore.

**Comment by luccaroli** [comment] 2024-04-10 21:54
same problem here, listeners don't work on android

**Comment by briazzi64** [comment] 2024-04-12 01:14
![code](https://github.com/expo/expo/assets/9169076/16c9049c-d8bc-48ee-8e7a-76bf67b85c67)

I'm also getting the same problems. Followed the directions in the documentation and even took the code example from @douglowder example comment [here](https://github.com/expo/expo/issues/27503#issuecomment-2044065073) and android notifications don't work if the app is killed or in the background. I press the notification and it loads the app but `addNotificationResponseReceivedListener` is never fired. `addNotificationReceivedListener` works if the app is in the foreground.

I've tried it with a development client and without. Nothing works.

```
"expo": "~50.0.14",
"expo-notifications": "0.27.6",
"expo-router": "3.4.8",
```

**Comment by christopherwalter** [comment] 2024-04-12 20:39
Hi all, I'm still investigating. Sorry again for the trouble here. I'll have an update as soon as I can.

**Comment by christopherwalter** [comment] 2024-04-15 19:35
Hi folks, could anyone share more about what devices you're seeing this behavior on? For some reason I'm having difficulty reproducing this brokenness and while I don't think the device type should matter, I'm inquiring anyway. 

For reference I haven't been able to reproduce this on Pixel devices (so far). Thanks again for your patience!

**Comment by vladica86** [comment] 2024-04-15 19:44
I see it on both iPhone 12 mini and Samsung Galaxy S

**Comment by nanmon** [comment] 2024-04-15 19:52
I'm seeing it on Samsung Z Flip 4

**Comment by briazzi64** [comment] 2024-04-15 20:25
I have a Pixel 6.

I guess a few other notes in case they matter.

- The application is wrapped in Sentry per the documentation [here](https://docs.expo.dev/guides/using-sentry/#example-configuration-that-instruments-sentry-for-expo).
- The app use react query and Expo Fonts
- My testing has all been with builds done through EAS Build and the distribution was set to `internal` so I just download and install the APK directly from Expo

Thanks for looking into this @christopherwalter

**Comment by christopherwalter** [comment] 2024-04-15 20:32
@briazzi64 could you send me a sample payload that's failing for you? Either here on GH or via email (chriswalter@expo.io). You can redact the push token and any other sensitive info, I just need the structure of the `data` field and any other fields you're including.

**Comment by nanmon** [comment] 2024-04-15 20:38
I'm seeing a different behavior now, when I open the notification I get the payload correctly now but the dev build of my app reloads. The minimal example provided here works fine for me now too

**Comment by christopherwalter** [comment] 2024-04-15 20:44
@nanmon are you seeing the data payload on a production build or a dev build? I'm wondering if the issue here is related to a development client vs a production build - I've been unable to repro with a dev build, but maybe that was the problem the whole time.

Not sure about the reloads, I'll look into that.

**Comment by nanmon** [comment] 2024-04-15 20:46
I'm seeing the data on a dev build, I'll try now with a prod build

**Comment by nanmon** [comment] 2024-04-15 23:56
So far I'm not getting anything on the prod build
- `getLastNotificationResponseAsync` returns null
- `addNotificationReceivedListener` and `addNotificationResponseReceivedListener` never get called

**Comment by briazzi64** [comment] 2024-04-16 01:10
> @briazzi64 could you send me a sample payload that's failing for you? Either here on GH or via email ([chriswalter@expo.io](mailto:chriswalter@expo.io)). You can redact the push token and any other sensitive info, I just need the structure of the `data` field and any other fields you're including.

I'm using the push notification tool to test: https://expo.dev/notifications

Recipient: `ExponentPushToken[pushTokenGoesHere]`
Access Token: none
Message Title: `Title`
Message Body: `Body`
Data (JSON): `{"url":"test"}`
TTL: 1
Channel Id: `default`
Force FCM Protocol: Both default and force FCM V1

With a dev client when I get the push notification and tap it then the app reloads and I get no data, regardless if the app is in the foreground, background or killed.. Without the dev client if I background the app or kill it, send the notification, and then press said notification the app opens and I still get no data. When the app is in the foreground, I get the notification, and press said notification, I do the get expected data.

**Comment by appsgenie** [comment] 2024-04-16 03:42
Old device for me: Pixel 2XL. 
But like I mentioned before, the production app from the Play Store works fine without the useFcmV1 parameter (notification icon shows and listeners are fire and data is passed).
Once useFcmV1=true is added, we see the issues mentioned above.

**Comment by christopherwalter** [comment] 2024-04-16 17:22
Thanks everyone for the added detail, it sounds like we need to investigate production versus dev builds as a potential influencing factor here. I'll have an update by tomorrow.

**Comment by vladica86** [comment] 2024-04-16 19:29
@christopherwalter - I dont think that production vs dev build matters here, since I have this issue even without build, while developing the app and running it through Expo Go

**Comment by christopherwalter** [comment] 2024-04-16 20:22
@vladica86 yeah that's our conclusion too - we can't think of a way that production vs dev could change the outcome here.

You're seeing this on Expo Go? That's a new one. Are you running latest everything?

**Comment by vladica86** [comment] 2024-04-16 20:31
I'm on "expo": "^49.0.7" and "expo-notifications": "^0.20.1"

**Comment by muminbhat** [comment] 2024-04-17 07:34
Hi, Guys. I am also experiencing the same issue.

When remote notifications are sent
Listeners don't work on android
Data is null, So routing doesn't work

However Listeners do work and routing works when notification is triggered locally.

**Comment by muminbhat** [comment] 2024-04-19 06:30
> Thanks everyone for the added detail, it sounds like we need to investigate production versus dev builds as a potential influencing factor here. I'll have an update by tomorrow.

Any updates ...

**Comment by christopherwalter** [comment] 2024-04-19 20:35
Still investigating, appreciate the patience. I may need to request some folks from this thread to hop on a zoom call so we can debug together. I'll have an update next week.

**Comment by joeoh1997** [comment] 2024-04-20 13:07
Also experiencing the same thing on an app I'm just about to release to the play store, thought I better switch it to V1 rather than needing to update later.  
I have 2 versions of the app because I recently updated to expo 50.

Ive tested sending a push from an ios simulator running the app with:
"expo-notifications": "~0.20.1",
"expo": "^49.0.16",
"react-native": "0.72.10",
"react": "18.2.0",

legacy: getLastNotificationResponseAsync receives response with valid data.
v1: getLastNotificationResponseAsync receives null response
(on a real samsung s22)

On on an android simulator with:
"expo": "~50.0.17",
"react-native": "0.73.6",
"react": "18.2.0",

with the same result - 
legacy: getLastNotificationResponseAsync receives response with valid data.
v1: getLastNotificationResponseAsync receives null response
(on a real samsung s22)


And on an

this is received on a real samsung s22 where getLastNotificationResponseAsync receives a null response

**Comment by jnoleau** [comment] 2024-04-24 08:10
Experiencing the same issue (very critical for us because the main feature of our app is based on the notification system). 

Tested with Android production builds (made with eas-build)  with
- expo-notifications@0.20.1
- expo@49.0.22
- react-native@0.73.2

The `addNotificationResponseReceivedListener` is called outside any component and the notification is pushed in a temporary array

```js
// Outside of any component https://github.com/expo/expo/issues/9866
Notifications.addNotificationResponseReceivedListener((r) => {
  pastNotificationResponses.unshift(r)

  // avoid mem leak
  if (pastNotificationResponses.length > 5) {
    pastNotificationResponses.pop()
  }

  DeviceEventEmitter.emit('NotificationResponseReceived', r)
})
```

With FCM legacy -> it works as a charm
With FCMv1 forced -> it only works when the app is in foreground and focused else no payload (or maybe no call of the listener I don't know, it only opens the app)

**Comment by DSp4wN** [comment] 2024-04-24 11:25
@christopherwalter, I am using an android 12 device and whenever I am running my app in expo go along with my useFCMv1 true it works in there in foreground as well as background, but when I put the production build on playstore and try checking with a push notification be it in foreground or background or killed state none of it works.

    "expo": "^50.0.17",
    "expo-constants": "^15.4.6",
    "expo-device": "^5.9.4",
    "expo-notifications": "^0.27.7",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-native": "^0.73.6",
    
 These are the package versions that I am using currently and I also tried using all of the following methods but none worked in production
 
 useLastNotificationResponse
 getLastNotificationResponseAsync
 addNotificationResponseReceivedListener

**Comment by christopherwalter** [comment] 2024-04-24 21:32
Hi all, thanks for staying tuned to this thread. We're working to confirm behaviors ourselves in a production app, so that's taking a bit of time. Rest assured I will have a fix for you as soon as I can - in the meantime please keep using FCM Legacy in production and feel free to comment here if you see any changes related to V1 behaviors.

**Comment by christopherwalter** [comment] 2024-04-25 06:39
@DSp4wN are you able to add the Legacy Key into EAS via the command line (EAS credentials) or the website (same page as FCM V1 credentials)? That should be all that's necessary. We may have removed the option from the website but I'm not sure, I'll check tomorrow and re-enable it if that's the case. Sorry for the difficulty, appreciate your patience!

**Comment by DSp4wN** [comment] 2024-04-25 06:54
@christopherwalter yes I added the legacy key through eas credentials and it is reflected on the website as well above FCM v1 credentials, but when I am trying to send the legacy notification using the expo notification tool it wont appear in the production build but it appears in the expo go app.

**Comment by Benisy** [comment] 2024-04-27 18:04
Hi all, I get a similar problem, but only when sending notification from APNs using [@parse/node-apn](https://github.com/parse-community/node-apn) to app iOS in production. However, when sending notification from FCM using [firebase-admin](https://github.com/firebase/firebase-admin-node) works fine.

The iOS app crashes when opened by clicking on a notification. When I added **try/catch** to `getInitialURL()` and `subscribe()`, it solved the app crashing problem, but did not solve the problem with notification.request.content.data is null. 

```javascript
const linking = {
    prefixes: ['myawesomeapp://'],
    config: {},
    async getInitialURL() {
        try {
            const url = await Linking.getInitialURL();
            if (url != null) return url;

            const response = await Notifications.getLastNotificationResponseAsync();
            const urlFromNotification = getUrlFromNotificationResponseSync(response);
            return urlFromNotification;
        } catch (error) {
            return null;
        }
    },
    subscribe(listener: (arg0: string) => void) {
        const onReceiveURL = ({ url }: { url: string }) => listener(url);
        const urlListener = Linking.addEventListener("url", onReceiveURL);
        const subscription = Notifications.addNotificationResponseReceivedListener((response) => {
            try {
                const url = getUrlFromNotificationResponseSync(response);
                if (url) listener(url);
            } catch (error) {
                return;
            }
        });
        return () => {
            urlListener.remove();
            subscription.remove();
        };
    },
};
```

<details>
  <summary>Code getUrlFromNotificationResponseSync()</summary>
  

  
  ```javascript
import * as Linking from 'expo-linking';

  function getUrlFromNotificationResponseSync(response) {
    let mainUrl = Linking.createURL('/');
    if (!response || !response.notification || !response.notification.request || !response.notification.request.content || !response.notification.request.content.data) return mainUrl
    const { screen, object_id } = response?.notification.request.content.data;
    switch (screen) {
        case "SHOW_BOOK":
            return Linking.createURL('books', { queryParams: { id: object_id} })
        case "SHOW_COLLECTION":
            return Linking.createURL('collections', { queryParams: { id: object_id } })
        case "SHOW_USER":
            return Linking.createURL('user', { queryParams: { id: object_id } })
        default:
            return mainUrl
    }
}
  ```
</details>

What I use in the project:
```
"expo": "^50.0.17",
"expo-constants": "~15.4.6",
"expo-device": "~5.9.4",
"expo-linking": "~6.2.2",
"expo-notifications": "~0.27.7",
"react": "18.2.0",
"react-native": "0.73.6",
"@react-navigation/native": "^6.1.7",
"react-native-gesture-handler": "~2.14.0",
```
Application is created using the command `expo prebuild` then I build it in Android Studio and in XCode.

**Comment by Abhisflyingsoon** [comment] 2024-05-02 12:03
Experiencing the same issue with the V1 google-services.json. I have another project with the legacy google-services.json and there it seems to be working. The main problem I am having is, that the addNotificationResponseReceivedListener() is not getting triggered after opening the app through the notification. When its in foreground state everything works as expected. I wanted to try it with the legacy api google-services.json, but firebase is not allowing me to generate it as its already disabled for that project...

**Comment by appsgenie** [comment] 2024-05-05 01:37
Meanwhile, could we somehow collectively ask google to give us more time, before taking down the Legacy API? is that even possible? 
With a little over a month left, I am worried it might not be enough time to fully test any fixes..

**Closed** 2024-05-07 17:32 UTC
Labels: project: notification-service, Notifications

**Comment by appsgenie** [comment] 2024-05-24 01:45
hi, should we track all the updates about all this issue in https://github.com/expo/expo/issues/28656, or here as well?

**Comment by christopherwalter** [comment] 2024-05-24 06:11
Hi @appsgenie, please follow along in #28656. Thanks!

**Comment by renatodv** [comment] 2024-08-18 13:39
Hello, so I spent a day debugging this, and I think the issue on Android is that "data" sometimes it can be called "dataString"

**Comment by DSp4wN** [comment] 2024-08-20 06:03
> Hello, so I spent a day debugging this, and I think the issue on Android is that "data" sometimes it can be called "dataString"

so we have to make a check for both of them for safety and it will work in all cases? @renatodv

**Comment by DSp4wN** [comment] 2024-08-21 09:29
> @renatodv @DSp4wN are you both using the `useLastNotificationResponse()` hook rather then registering listeners? AFAIK that is the _only_ way to reliably get deserialized data from the notifications across all app states in Android currently. The main tracking issue will have more info about this, but is quite long at this point.

Yes I am using useLastNotificationResponse hook, do u have example for the listener one if that is working as u mentioned?

**Comment by Codelica** [comment] 2024-08-21 17:00
@DSp4wN I'm using the `useLastNotificationResponse()`hook which I believe is currently the only route to getting notification data across all Android app states.  I also set `defaultChannel` and a couple other things as discussed here:

https://github.com/expo/expo/issues/28656#issuecomment-2164019362

**Comment by DSp4wN** [comment] 2024-08-21 17:02
> @DSp4wN I'm using the `useLastNotificationResponse()`hook which I believe is currently the only route to getting notification data across all Android app states. I also set `defaultChannel` and a couple other things as discussed here:
> 
> [#28656 (comment)](https://github.com/expo/expo/issues/28656#issuecomment-2164019362)

I have it set using setNotificationChannelAsync function

**Comment by Codelica** [comment] 2024-08-21 17:29
> I have it set using setNotificationChannelAsync function

Yes, but I'm not convinced that is being honored in some Android app states unfortunately, and when it isn't then the message goes to the default fallback "miscellaneous" channel that Expo creates which affects things.   I'd add the `defaultChannel` setting set to the channel you use just to be safe, as described in one of those links above. I believe that will then be used instead of Expo's default fallback channel in those app states.   You could also look in the app notification settings on your device for the Miscellanous channel and change it's alert settings to confirm that's where those alerts are actually going I guess.

**Comment by baldrich97** [comment] 2024-08-21 20:11
I've discovered that for the dev environment, Expo just sends the raw data you pass it from wherever you're generating the push notifications (PHP in my case) as an object keyed "data". In prod in my case, it was JSON stringified and passed as "dataString". 

Added in a if block that checks typeof on the data that I'm extrapolating via setting a data var to equal notification.request.content.data if it exists, or notification.request.content.dataString otherwise. I check if that data var is a string and if it is I just JSON.parse() it and everything works as intended.

Hope this helps!

**Comment by statico** [comment] 2024-11-01 18:01
Possibly change the type of `data` to `Record<string, any> | null` so that users are aware of this issue? This bit us in that users of our app started getting "can't read property X of undefined" errors.

**Comment by radulescuandrew** [comment] 2024-11-20 11:30
```
"expo": "51.0.39",
"expo-notifications": "0.28.19"
 "@react-native-firebase/messaging": "21.5.0",
```

1. ✅ Foreground [Android/iOS] - I receive message on `messaging().onMessage`, schedule a local notification and catch it in `Notifications.addNotificationResponseReceivedListener`
2. ✅ Background [Android/iOS] - using `@react-native-firebase/messaging` in my case and catch it in `messaging().onNotificationOpenedApp`
3. ❌ COLD START (Killed): Inconsistent data payload on Android and iOS. `getLastNotificationResponseAsync` returns the data in `request.trigger.payload` **on iOS** and **on Android** can be found on `request.content.data` .
```
{
  "actionIdentifier": "expo.modules.notifications.actions.DEFAULT",
  "notification": {
    "date": 1732101862.136058,
    "request": {
      "content": {
        .....
        **"data": null,**
        "title": "Test notification",
        "body": "This is a test notification from the /notifications/test endpoint."
      },
      "identifier": "8609BA3A-257E-4374-90DB-32359FAEAB41",
      "trigger": {
        "payload": {
          "formId": "144",
          "google.c.sender.id": "1093326068146",
          "google.c.a.e": "1",
          "id": "1",
          "formType": "Feedback",
          "eventId": "791",
          "type": "form"
        },
        "type": "push",
        "class": "UNPushNotificationTrigger"
      }
    }
  }
}```


In my case, using Firebase Messaging I'm using `getLastNotificationResponseAsync` (consistent on Android ColdStart) in conjunction with `messaging().getInitialNotification()` (consistent on iOS ColdStart). 

We have to release the app, but I will probably come back to check the updates in couple months and refactor. GL HF
