### ISSUE TITLE
Contacts.getContactByIdAsync hangs on android

### ISSUE THREAD

**Issue by dor6** [expo/expo#8848] opened 2020-06-17 08:15 UTC
### Summary of Issue (just a few sentences)
same code using Contacts.getContactByIdAsync works on ios but on android it just hangs and the code wont continiue executing (using await)
**while on both Contacts.getContactsAsync works**

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
heppened on 2 different android phones with different versions one was android 10 the other unknown. expo version 37

### Expected Behavior vs Actual Behavior

after executing
`
console.log(1);
const phoneContact = await Contacts.getContactByIdAsync(phoneContactId);
console.log(2);
`
expected: 
console to write "1"
phoneContact to either be a contact object or a null value
console to write "2"

actual behevior:
console writes "1"
never wirtes "2"

**Comment by byCedric** [comment] 2020-06-17 11:53
Hi @dor6, thanks for the issue report! Could you share a small repro for us to investigate this? Without that, it's hard for us to determine the exact cause here. I don't think we have other (recent) related issues about this, so there might be something going on in your project. But again, without repro it's hard for us to check this out.

**Comment by dor6** [comment] 2020-06-17 18:18
the code is littelrally calling: 
`Contacts.getContaqctByIdAsync(contactId);`
i can say contactId in my case is a mock id and not a real id. 
i create a mock id to handle the fact that i cant create a contact in expo enviroment on android ( when will this be fixed?! ).

i create the mock id in the following way: 
`contactId = 'A' + Date.now();`

**Comment by dor6** [comment] 2020-06-23 14:40
Issue needs review

**Comment by dor6** [comment] 2020-06-24 08:51
After a simple check i found out the problem.
if you give and id that does not exists GetContactById Async will hang and wont return a value.
this is problematic and should be fixed.

**Comment by barthap** [comment] 2020-07-23 12:07
Sorry, I cannot reproduce your issue. Tried this code:
```ts
        const { data } = await Contacts.getContactsAsync({
          fields: [Contacts.Fields.Emails],
        });

        const contact = data[0];
        console.log('First', contact); //first existing contact
        
        const info = await Contacts.getContactByIdAsync(contact.id);
        console.log('Info:', info); //Info: Object Contact {...}

        const nonExistingInfo = await Contacts.getContactByIdAsync('A' + Date.now());
        console.log('Non existing:', nonExistingInfo);   //Non existing: undefined
```

**Comment by lukmccall** [comment] 2020-07-23 12:22
Hi @dor6, it was fixed by https://github.com/expo/expo/pull/8976.

**Closed by lukmccall** 2020-07-23 12:22 UTC
Labels: Android, Contacts, needs repro
