### ISSUE TITLE
Android - Notifications.addListener does not work on SDK 36 when app is closed

### ISSUE THREAD

**Issue by empregourgente-4** [expo/expo#7492] opened 2020-03-27 05:37 UTC
## 🐛 Bug Report

**Issue:**
I've noticed that notifications.addListener event does not trigger when the app is closed. It works fine if it's on the foreground.

**Expected behaviour:**
notifications.addListener should fire even if the app is closed.

**Workaround**
- Rollback to SDK 35

Code:
```
   Notifications.addListener(async notification => {
        PushNotificationHelper.handleNotification(notification);
      });

[...]

  public static async handleNotification(notification) {
    const { toScreen, params } = notification.data;
    console.log("Received push data...");
    console.log(toScreen);
    console.log(params);

    // get current route name
    const { routeName } = await NavigationHelper.getCurrentRoute();

    if (routeName !== toScreen) {
      console.log(`Navigating to ${toScreen}`);
      // If we're currently in a route that's different than the push one, redirect the user
      NavigationHelper.navigate(toScreen, params);
    }
  }
`
```
### Environment

  Expo CLI 3.13.8 environment info:
    System:
      OS: Linux 5.3 KDE neon 5.18
      Shell: 5.4.2 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.13.8

TARGET: Android
### Steps to Reproduce
- trigger a push notification when the app is closed.
- click on it
- see that Notifications.addListener does not trigger

### Expected Behavior

- trigger Notifications.addListener even with app closed.

### Actual Behavior

- Nothing is triggered on Notifications.addListener

**Comment by cruzach** [comment] 2020-03-27 19:56
This looks like a duplicate of https://github.com/expo/expo/issues/6529

If you can find a reliable way to reproduce the issue, please share it there!

**Closed by cruzach** 2020-03-27 19:56 UTC
Labels: bug
