### ISSUE TITLE
android: sounds are played on load

### ISSUE THREAD

**Issue by inyono** [expo/expo#110] opened 2017-04-15 04:34 UTC
When previewing a CRNA on Android, all sounds are played directly after their `loadAsync`. We only have this issue on Expo for Android, iOS works fine. Observable at [serlo-abc](https://github.com/serlo-org/serlo-abc) (I can also build a smaller example if that helps).

**Comment by dikaiosune** [comment] 2017-04-15 16:59
cc @gkufera

**Comment by inyono** [comment] 2017-04-21 09:50
Btw: this is still a problem with the current Expo (running Expo SDK 16). Please let me know if I can help with that issue in any way.

**Comment by gkufera** [comment] 2017-05-02 23:37
Hey @inyono! Sorry about the delay getting back to you regarding this.

I ran the current version of [serlo-abc](https://github.com/serlo-org/serlo-abc) today on my Android device using the Expo app currently available on the app store (SDK16). I wasn't able to reproduce this bug on my Nexus 5X running Android 6.0 (I tested using the "Apfel" missing letter portion of the app). Can you send over the details of the Android device on which you are experiencing this bug?

For a temporary fix, I might try something like this (it's not ideal, but it should work until we fix the bug!):

```
async play(sound) {
  await sound.loadAsync();
  await sound.playAsync();
  await sound.unloadAsync();
}
```

We are in the process of moving to an Android media playback library that has a better track record for stability across Android devices, so hopefully strange audio bugs like this will stop popping up then! In the meantime, if you send me your device info we might be able to fix the bug in our current implementation.

Thanks!

**Comment by skevy** [comment] 2017-05-04 21:30
@inyono just wanted to follow up and see if you could provide more information to @gkufera :)

**Comment by skevy** [comment] 2017-05-04 21:31
Scratch that :) @gkufera is working on this, and we recommend using his workaround for now.

**Comment by inyono** [comment] 2017-05-05 00:22
@gkufera Sorry about the late response. I checked again with the current Expo and the problem persists. Steps to reproduce:

1. `git clone git@github.com:serlo-org/serlo-abc.git`
2. `yarn install`
3. `yarn start`
4. Open app in Expo
5. Open Storybook, http://localhost:19001
6. Select story `exercises/ShowWord`

On selecting the story, both sound files are played directly, although they should only be played when pressing the speaker button. Selecting back and forth between two stories with sounds also has this behaviour.

Device: Nexus 5X, Android 7.1.2, Expo 1.15.1

**Comment by eryshev** [comment] 2017-07-21 06:42
HI I still have this issue with **expo 18** and **nexus 5x** + **android 7.1.2**.
I am doing 
`sound.loadAsync(source, { shouldPlay: false })`

**Comment by Babazon** [comment] 2017-08-01 08:21
I can't get the sound to play if I don't load it where I play. But loading it each time I want to play it is laggy. Here is what I'm doing (Es7 syntax)


```
class MealScreen extends Component {

  soundLeft = new Audio.Sound();
  soundRight = new Audio.Sound();
  soundFetch = new Audio.Sound();

  async componentDidMount() {
    try {
      await Audio.setIsEnabledAsync(true);
      await this.soundRight.loadAsync(require('../../assets/sounds/accept.wav'));
      await this.soundLeft.loadAsync(require('../../assets/sounds/reject.wav'));
      await this.soundFetch.loadAsync(require('../../assets/sounds/fetch.wav'));
    } catch (reason) { console.log(error); }
  }

  onSwipeRight = async (recipe) => {
    try {
      await this.soundRight.playAsync();
      console.log('playing', this.soundRight); // PRINTS EACH TIME, BUT PLAYS ONLY AT FIRST CLICK!! 
    } catch (reason) {
      console.log(reason);
    } finally {
      //
    }
  };
```

I have no choice but to loadAsync each time I want to play (and if the USER spams that button which plays the sound, it will lag, pretty bad user experience)

**Comment by ide** [comment] 2017-08-01 08:28
I believe that might have been fixed with SDK 19, but before you used to need to call sound.setPositionAsync(0) after it finished playing since its position was at the end.

**Comment by Babazon** [comment] 2017-08-01 08:52
Beautiful. Thank you. Works now. I am a little doc-reading-handicapped it seems.

**Comment by gkufera** [comment] 2017-08-16 02:43
Fantastic @Babazon!

I believe that this issue should be gone in SDK20 @inyono, since we have moved to a more robust Android audio backend. Please let me know if the issue persists and we can reopen the issue.

Thanks!

Greg

**Closed by gkufera** 2017-08-16 02:43 UTC
Labels: project: client-android, project: sdk, status: needs more info

**Comment by inyono** [comment] 2017-08-20 15:31
Just updated to SDK 20 and the issue is resolved. Thanks! 👍

**Comment by joshbalfour** [comment] 2018-02-02 22:34
I'm experiencing this on iOS with SDK 25
