### ISSUE TITLE
Notifications suppressed in iOS Dev Client and Expo Go when remote debugging enabled

### ISSUE THREAD

**Issue by OneHatRepo** [expo/expo#18690] opened 2022-08-17 22:43 UTC
### Summary

In SDK 46, when an iOS dev client has Dev Tools enabled, it cannot receive push notifications. Notifications once again appear when Dev Tools is disabled. This doesn't happen on Android at all.

The push notification handler as defined in Notifications.addNotificationReceivedListener() never even gets called. Nor does handleNotification in Notifications.setNotificationHandler(), so debugger statements never trigger.

I want to debug what happens when I receive a notification on iOS and I can’t do it!

[This post](https://forums.expo.dev/t/expo-sdk-46-no-notifications-with-local-dev-tools-enabled/65656/2) shows that I'm not the only one experiencing this.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

    "expo-dev-client": "~1.2.1"
    "expo-updates": "~0.14.3",
    "expo-notifications": "~0.16.1",

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/opt/node@16/bin/node
      npm: 8.15.0 - /usr/local/opt/node@16/bin/npm
      Watchman: 2022.08.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.18 => 0.3.22
      babel-preset-expo: ~9.2.0 => 9.2.0
      expo: ~46.0.2 => 46.0.7
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.4 => 0.69.4
      react-native-web: ~0.18.7 => 0.18.7
    npmGlobalPackages:
      eas-cli: 0.60.0
      expo-cli: 6.0.2
    Expo Workflow: managed

### Reproducible demo

- Use [this repo's codebase](https://github.com/OneHatRepo/notifications-broken)
- Build an iOS development client "npm run ebd" (ebd = eas build dev)
- Run the metro server "npm run esd" (esd = expo start dev)
- Run the dev client. The app immediately tells you what its ExponentPushToken is.
  - Use the Expo push notification tool to send a notification to this ExponentPushToken. It works.
  - Try to trigger a manual push notification. It works.
- Enable "Local dev tools" from the developer menu.
  - Resend the notification. **Nothing happens. No notification is received or triggered.**
  - Try to trigger a notification manually. **It doesn't work even though an alert pops up telling you it tried.**
- Close the app, and re-send a notification. It works again.

**Comment by OneHatRepo** [comment] 2022-08-18 15:29
Also, in iOS dev client, triggering a manual notification via `Notifications.scheduleNotificationAsync()` does nothing.

**Comment by OneHatRepo** [comment] 2022-08-18 19:50
Fails with both the standard and hermes js engines.

**Comment by esamelson** [comment] 2022-08-23 02:14
Thanks for the report and the repro, @OneHatRepo . I think this is an issue with expo-notifications, because I was able to reproduce this in both a dev build and Expo Go. Also tried the notifications screen in native-component-list in Expo Go, and when debugging remotely, notifications do still show up, but the app does not seem to receive an event when the user taps on a notification.

**Comment by ndrabins** [comment] 2022-08-23 18:59
This happens to my app as well, seemed to have started occurring when upgrading to expo 46. 

Not sure if related to this issue as well, but I no longer receive push notifications on a test flight build as well.

**Comment by OneHatRepo** [comment] 2022-08-23 19:04
@ndrabins I am not experiencing the suppression of notifications when remote debugging is disabled, which would be the case for builds bound for Test Flight, so that makes me think it's probably a separate issue.

**Comment by OneHatRepo** [comment] 2022-11-21 20:12
Still an issue.

**Comment by OneHatRepo** [comment] 2022-12-07 22:01
Still an issue

**Comment by C3sarRC** [comment] 2022-12-30 17:05
still an issue

**Comment by janziemba** [comment] 2023-07-01 12:11
Did you check the permissions? Because I had to request the permissions first, then it works.

**Comment by vonovak** [comment] 2024-09-25 14:33
Hello and thanks for reporting,
I'm going to close this because remote debugging is a concept that is no longer supported.
Thank you 🙂

**Closed by vonovak** 2024-09-25 14:33 UTC
Labels: Expo Go, Notifications, Issue accepted, Development Builds
