### ISSUE TITLE
LocalAuthentication.authenticateAsync() is returning unknown error

### ISSUE THREAD

**Issue by michael-erwin** [expo/expo#3832] opened 2019-03-24 16:34 UTC
### Environment

  Expo CLI 2.13.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

Client

### Steps to Reproduce

I was following the documentation for usage of [LocalAuthentication](https://docs.expo.io/versions/v32.0.0/sdk/local-authentication/) API. I'm testing on real device (Xaomi Max 2) running Android 7.1.1. Reproduce by running on fresh project install using expo cli:

1. run: expo init test
2. select blank option
3. cd to test folder and open App.js
4. replace content with the following code:
```Javascript
import React from 'react';
import { Button, Text, View, StyleSheet } from 'react-native';
import { LocalAuthentication } from 'expo';

export default class App extends React.Component {

  state = {
    auth_status: 'none' // none, pending, success, failed
  }

  render() {
    const { auth_status } = this.state;
    switch (auth_status) {
      case 'pending':
        return (
          <View style={styles.container}>
            <Text>Local auth pending...</Text>
            <Button title="Cancel" onPress={this._cancel} />
          </View>
        );
      case 'success':
        return (
          <View style={styles.container}>
            <Text>Local auth success</Text>
            <Button title="Reset" onPress={this._reset} />
          </View>
        );
      case 'failed':
        return (
          <View style={styles.container}>
            <Text>Local auth failed</Text>
            <Button title="Reset" onPress={this._reset} />
          </View>
        );
      default:
        return (
          <View style={styles.container}>
            <Button title="Authenticate Me" onPress={this._start} />
          </View>
        );
    }
  }

  // Methods
  _start = async ()=> {
    this.setState((state) => ({auth_status: 'pending'}));
    const result = await LocalAuthentication.authenticateAsync('Verify your bio id');
    console.log(result); //<-- {"error": "unknown", "message": "", "success": false}
    if(result.success){
      this.setState((state) => ({auth_status: 'success'}));
    } else {
      this.setState((state) => ({auth_status: 'failed'}));
    }
  }
  _cancel = ()=> {
    LocalAuthentication.cancelAuthenticate();
    this._reset();
  }
  _reset = ()=> {
    this.setState((state) => ({auth_status: 'none'}));
  }
}

// Styles
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  }
});
```
5. save and run: yarn start 
6. press the "authenticate me" button.

### Expected Behavior

Center of screen should have a waiting UI with text that reads "Local auth pending..." with cancel button below and change only happens by either (1) cancel button is pressed or (2) fingerprint is fully scanned.

### Actual Behavior

Displays directly to failed text with result of the following object:

```Javascript
Object {
  "error": "unknown",
  "message": "",
  "success": false,
}
```

### Reproducible Demo

https://snack.expo.io/HJV9lES_E

**Comment by sjchmiela** [comment] 2019-03-25 15:08
Duplicate of https://github.com/expo/expo/issues/3832. Sorry! 😕

**Closed by sjchmiela** 2019-03-25 15:08 UTC
Labels: project: sdk

**Comment by michael-erwin** [comment] 2019-03-25 18:52
@sjchmiela Can you please review the issue number? #3832 refers to this same issue I submitted.

**Comment by sjchmiela** [comment] 2019-03-25 19:09
Whoops, sorry! Here’s the proper one: https://github.com/expo/expo/issues/663

**Comment by michael-erwin** [comment] 2019-03-26 02:17
Thanks!
