### ISSUE TITLE
jest-expo cannot pick up custom tsconfig.test.json, can't do top-level await and fail on .*test.web.ts tests

### ISSUE THREAD

**Issue by jin-qin** [expo/expo#30702] opened 2024-07-30 02:32 UTC
### Minimal reproducible example

https://github.com/jin-qin/expo-jest-ts-test

### Where did you reproduce the issue?

in a development build

### Summary

Hi Expo team,

I am having three issues while using `jest-expo`:
1. `jest-expo` cannot let me do top-level await functions.
2. `jest-expo` cannot pick up my custom tsconfig file `tsconfg.test.json`
3. `jest-expo` will fail on `.web.ts`.

> [!IMPORTANT]
> Before running the minimal reproducible example, run `npx firebase emulators:start` first.

#### Case 1
In the minimal reproducible example, if you directly run `npx jest`, will give an error:
```
SyntaxError: await is only valid in async functions and the top level bodies of modules
```

#### Case 2
If you comment out `await testAsyncFunc();` in `lib/firebase/firebase.ts`, then run `npx jest`, will give another error:
```
SyntaxError: Cannot use import statement outside a module
```
It basically indicates the `jest` doesn't load `tsconfig.test.json`, it will work if you remove the below configuration from `tsconfig.json`:
```
"@firebase/auth": [
  "./node_modules/@firebase/auth/dist/index.rn.d.ts"
]
```

#### Case 3
If you change `example-test.node.ts` to `example-test.web.ts`, it will pass on `Node` but fail on `Web`.

Kindly ask if you can take a look? Man thanks!

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
      Watchman: 2024.05.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.23 => 51.0.23 
      expo-router: ~3.5.19 => 3.5.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by jin-qin** [comment] 2024-08-14 21:01
Hello team, it's been 2 weeks, any updates? Thanks!

**Comment by aleqsio** [comment] 2024-08-19 14:04
Hi @jin-qin,

I think the 1st case is expected behavior – the error seems to describe the issue quite well. I don't think the top-level await would work when running the code, so it's expected to fail in tests. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_await

The 2nd case seems to be a misconfiguration of your tsconfig files – there is nothing special about tsconfig.test.json that makes it apply to jest, I think you need to configure it using `composite` and `include` parameters so it applies to correct folders. https://kettanaito.com/blog/one-thing-nobody-explained-to-you-about-typescript.

I'm closing the issue for now – if you still consider this to be a problem with `jest-expo` after reviewing the links I'd appreciate a more minimal repro with a single issue to focus on.

**Closed by aleqsio** 2024-08-19 14:04 UTC
Labels: needs review
