### ISSUE TITLE
Stack breaks typescript in v2

### ISSUE THREAD

**Issue by lhguerra** [expo/expo#24933] opened 2023-10-18 23:54 UTC
### Minimal reproducible example

https://github.com/lhguerra/expo-router-stack-typescript-bug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

When adding Stack component to the _layout, it breaks the type check with a bunch of errors in expo-router lib.

Just download the repository above, install the dependencies and run `npm run lint:ts`

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    npmPackages:
      expo: ^49.0.3 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.0.2
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by lhguerra** [comment] 2023-10-19 00:00
The repo was missing one commit, just sent it

**Comment by lhguerra** [comment] 2023-10-20 13:52
I'll have to roll everything back to react navigation :/

**Comment by lhguerra** [comment] 2023-10-20 16:05
This page should have a warning sayng that expo router is still beta and not production ready
https://docs.expo.dev/routing/introduction/

**Comment by buraks** [comment] 2023-10-21 17:54
I cloned the repo, ran npm install, there is no type error. You might want to check your local setup

**Comment by buraks** [comment] 2023-10-21 18:23
I just saw that it's when you run `npm run lint:ts`, I made the lint work ok by adding bunch of types to dev dependencies:

```
    "@expo/config": "^8.1.2",
    "@expo/config-plugins": "^7.2.5",
    "@types/react": "^18.0.25",
    "@types/react-native": "^0.70.6",
    "@types/url-parse": "^1.4.10"
    ```
    
not sure which ones are actually useful

**Comment by lhguerra** [comment] 2023-10-23 17:28
I tried it but still get the same errors :/

**Comment by hichemfantar** [comment] 2023-11-07 06:19
I get the type errors when I import tabs for some reason #25213

**Comment by hichemfantar** [comment] 2023-11-17 13:25
I created a script to ignore expo-router type errors when type checking:
`		"build": "tsc -v && (tsc --noEmit --pretty > tsc_output.txt) || (cat tsc_output.txt; echo \"\ntsc failed, attempting manual resolution...\"; bash tsc_check.sh)",
`
```sh
#!/bin/bash

# Check if the "Errors  Files" line exists at the start
if grep -q "Errors  Files" tsc_output.txt; then
    # Save the number of lines containing "expo-router" errors
    expo_router_error_count=$(awk '/Errors  Files/ {flag=1; next} flag && /expo-router/ {count++} END {print count}' tsc_output.txt)
    
    # Save the number of lines after "Errors  Files"
    lines_after_errors_files=$(awk '/Errors  Files/ {flag=1; next} flag {count++} END {print count}' tsc_output.txt)
    
    # Check if the counts are equal
    if [ "$expo_router_error_count" -eq "$lines_after_errors_files" ]; then
        echo "Number of 'expo-router' errors is equal to the number of lines after 'Errors  Files'. Proceeding with 'tsc' command."
        exit 0
    else
        echo "Number of 'expo-router' errors is not equal to the number of lines after 'Errors  Files'. Exiting 'tsc' command."
        exit 1
    fi
else
    echo "The 'Errors  Files' line does not exist. Proceeding with 'tsc' command."
    exit 0
fi

```

**Comment by EvanBacon** [comment] 2023-11-27 23:13
Duplicate of https://github.com/expo/expo/issues/25478 -- we've published the alpha of v3, if you're truly blocked then you can try upgrading today.

**Comment by lhguerra** [comment] 2023-12-19 23:12
how can this be the duplicate if it is way older?

**Comment by abumalick** [comment] 2023-12-21 09:03
@EvanBacon It is very strange to be forced to upgrade to an alpha version to fix types checks from node_modules folder.
We are ignoring "node_modules" folder and have `skipLibCheck` to true. How come we have errors like that?

**Comment by abumalick** [comment] 2023-12-21 09:35
All right, I fixed the errors by changing my import from 
```
import {Stack} from "expo-router/stack";
```
to 
```
import {Stack} from "expo-router";
```

I believe I was importing a ts file and it was causing the problems.

This comment helped me: https://github.com/microsoft/TypeScript/issues/40426#issuecomment-1774231789

**Comment by hichemfantar** [comment] 2023-12-21 17:30
> I created a script to ignore expo-router type errors when type checking (sdk49) it's a bit hacky but it'll have to do until we upgrade to sdk50 which should have the problem fixed, I had to do this because I couldn't ignore the errors using tsconfig exclude and ts-ignore: package.json script:
> 
> ```json
> "build": "tsc -v && (tsc --noEmit --pretty > tsc_output.txt) || (cat tsc_output.txt; echo \"\ntsc failed, attempting manual resolution...\"; bash tsc_check.sh)"
> ```
> 
> tsc_check.sh file:
> 
> ```shell
> #!/bin/bash
> 
> # Check if the "Errors  Files" line exists at the start
> if grep -q "Errors  Files" tsc_output.txt; then
>     # Save the number of lines containing "expo-router" errors
>     expo_router_error_count=$(awk '/Errors  Files/ {flag=1; next} flag && /expo-router/ {count++} END {print count}' tsc_output.txt)
>     
>     # Save the number of lines after "Errors  Files"
>     lines_after_errors_files=$(awk '/Errors  Files/ {flag=1; next} flag {count++} END {print count}' tsc_output.txt)
>     
>     # Check if the counts are equal
>     if [ "$expo_router_error_count" -eq "$lines_after_errors_files" ]; then
>         echo "Number of 'expo-router' errors is equal to the number of lines after 'Errors  Files'. Proceeding with 'tsc' command."
>         exit 0
>     else
>         echo "Number of 'expo-router' errors is not equal to the number of lines after 'Errors  Files'. Exiting 'tsc' command."
>         exit 1
>     fi
> else
>     echo "The 'Errors  Files' line does not exist. Proceeding with 'tsc' command."
>     exit 0
> fi
> ```

I built this script specifically to ignore the router type errors

**Comment by hichemfantar** [comment] 2023-12-21 17:33
> All right, I fixed the errors by changing my import from
> 
> ```
> import {Stack} from "expo-router/stack";
> ```
> 
> to
> 
> ```
> import {Stack} from "expo-router";
> ```
> 
> I believe I was importing a ts file and it was causing the problems.
> 
> This comment helped me: [microsoft/TypeScript#40426 (comment)](https://github.com/microsoft/TypeScript/issues/40426#issuecomment-1774231789)

this doesn't fix tabs for me
https://docs.expo.dev/router/advanced/tabs/

**Comment by marklawlor** [comment] 2024-02-23 01:13
Should be resolved in Expo Router v3.

If you are still having this issue with version 3, can you please create a new issue with a reproduction repo

**Closed by marklawlor** 2024-02-23 01:13 UTC
Labels: needs review, Router
