### ISSUE TITLE
VideoThumbnails.getThumbnailAsync on Expo 35.0.0 fails to get thumbnail on Android

### ISSUE THREAD

**Issue by mritzman-dg** [expo/expo#7832] opened 2020-04-13 23:15 UTC
### Environment

Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.1 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.13.1

**App's Target**: Android Emulator and Pixel 2 Mobile Device via Expo app

### Steps to Reproduce

On Android only with version Expo 35.0.0 I'm getting the following error when trying to get a thumbnail from a _local_ video selected from the ImagePicker.  Note that I do NOT get the error on iOS and a thumbnail is generated.

`{"framesToPop":1,"nativeStackAndroid":[],"userInfo":null,"code":"E_VIDEO_THUMBNAILS"}`

### Expected Behavior

I expect to be able to generate a thumbnail on Android with throwing an error.

### Actual Behavior

On Android an error is thrown when calling `await VideoThumbnails.getThumbnailAsync(result.uri)` even with a valid uri pointing to a local video file.

### Reproducible Demo

https://snack.expo.io/@mritzman-dg/video-thumbnail-(expo-v35.0.0)

**Comment by lukmccall** [comment] 2020-04-14 09:45
Hi @mritzman-dg, I believe that was fixed in SDK 36 by this PR: https://github.com/expo/expo/pull/5711.
Could you check it? If you don't want to upgrade your app you also can try to decode URI and then call the `getThumbnailAsync` function:
```ts
await VideoThumbnails.getThumbnailAsync(decodeURI(result.uri))
```

**Comment by rkbhochalya** [comment] 2020-07-06 17:01
For me it throws error for content URIs (`content://`) returned by `react-native-document-picker`. The same URI works with `react-native-video` so it's not a permissions issue.

**Comment by lukmccall** [comment] 2020-07-07 07:58
Hi @rkbhochalya, `VideoThumbnails` doesn't support `content` schema. Please create a new issue with a future request ;)

**Comment by FiberJW** [comment] 2020-07-14 19:28
Due to inactivity from the OP, I'm going to close this. If this is still a problem for you and it's reproducible using the latest SDK version, feel free to open up a new issue!

**Closed by FiberJW** 2020-07-14 19:28 UTC
Labels: Android, VideoThumbnails, status: needs more info
