### ISSUE TITLE
getExpoPushTokenAsync returns same token on 2 disincts iPhone 

### ISSUE THREAD

**Issue by jnoleau** [expo/expo#11257] opened 2020-12-07 17:35 UTC
### Summary of Issue 

When calling getExpoPushTokenAsync from a new iPhone set up with Apple tool "Transfer from iPhone", the expo push token stays the same as the legacy iPhone (and as a consequence, only the first one receives the notifications). The only way to resolve this issue is to ask the user to uninstall / reinstall the App.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
 expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.16
    Expo Workflow: managed

Platform : iOS
 
### Steps to Reproduce

- Call getExpoPushTokenAsync  from a first iPhone device (for example an iPhone X) 
- Get another iPhone (for example an iPhone 12) start it from factory settings and choose "Transfer from iphone" to clone the first one (this is the default choice)
- Call getExpoPushTokenAsync (after Permissions.askAsync(Permissions.NOTIFICATIONS)) on the new iPhone -> the expo push token you got on the iPhone 12 is the same of the expo push token you got on the iPhone X

### Debug info

It seems there is a problem of "cached data" on expo `https://exp.host/--/api/v2/push/getExpoPushToken` endpoint  with what you called the `deviceId`, the constant returned with `Contants.installationId`

**Indeed the `Contants.installationId` is also the same on the new fresh iPhone when cloned from another (and maybe this is the real bug !!) (the only thing different is the deviceToken returned by `getDevicePushTokenAsync`)**

getExpoPushTokenAsync make a POST request to`https://exp.host/--/api/v2/push/getExpoPushToken` with deviceId, deviceToken, and other params so I try to call manually this endpoint with the same deviceId but 2 distincts deviceToken and expo server gives me the same ExpoPushToken 

Thank you for your help

**Comment by cruzach** [comment] 2020-12-07 19:09
hi @jnoleau , this is a duplicate of https://github.com/expo/expo/issues/6051 and https://github.com/expo/expo/issues/2824, which we've landed a fix for in SDK 40. if you'd like to get your hands on the fix out right now- you can [try out the SDK 40 beta](https://blog.expo.io/expo-sdk-40-beta-is-now-available-2e98264f66b2)

**Closed by cruzach** 2020-12-07 19:09 UTC
Labels: needs review
