### ISSUE TITLE
[expo-notification] events are fired twice

### ISSUE THREAD

**Issue by reft** [expo/expo#12417] opened 2021-04-05 14:31 UTC
### Summary

Events are fired twice when using addNotificationReceivedListener and other events.

Tested on:

"expo-notifications": "0.11.3",
"expo-notifications": "0.9.0",

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

4.2.1

### Environment

  Expo CLI 4.2.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 15.2.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.0.8 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
import React from 'react'
import * as Notifications from 'expo-notifications'

export default function App() {
  React.useEffect(() => {
    console.log('logs once here as it should')

    const subscription = Notifications.addNotificationReceivedListener((notification) => {
      console.log('LOGS TWICE HERE?!')
    })
    return () => subscription.remove()
  }, [])

  return null
}

```

Post to: https://exp.host/--/api/v2/push/send
Body:
```

{
    "to": "ExponentPushToken[LZHGudKJuLn_431Twj1y1V]",
    "sound": "default",
    "title": "Original Title",
    "body": "And here is the body!", 
    "data": { "someData": "goes here"}
  }
```

**Comment by cruzach** [comment] 2021-04-05 14:59
I tested this on SDK 40 and 41 and could not reproduce the same behavior. I think what's happening here is that you have accidentally mounted 2 listeners, and thus it looks like the events are fired twice. For instance, take the example snack code [here](https://docs.expo.io/versions/latest/sdk/notifications/#api), run your project locally, and you'll see the events are only fired once

**Comment by reft** [comment] 2021-04-05 15:32
@cruzach If you add a console log in your snack to the addNotificationReceivedListener event you can actually see the console.log being shown twice.

https://snack.expo.io/xqx8sDXdY

**Comment by cruzach** [comment] 2021-04-05 15:34
Yeah, that does happen in Snack (and that's not good), but like i said above, if you run your project locally, and you'll see the events are only fired once

**Comment by reft** [comment] 2021-04-05 15:37
@cruzach Are you sure? What if you copy my snack to your local, do you see just one 'TEST' in your console log? I'm seeing two logs after I click the 'Press to schedule a notificaiton'

**Comment by cruzach** [comment] 2021-04-05 15:38
I'm seeing one `TEST`

**Comment by reft** [comment] 2021-04-05 16:22
I've tried this on two different comps now, (same phone tho), and they both return two console logs when running addNotificationReceivedListener event.

* blank with typescript
* expo install expo-notifications
* pasted in snack code (replaced entire app.tsx)
* connected using Tunnel/LAN

=

(2) console.log('TEST') when posting just once.

**Comment by cruzach** [comment] 2021-04-05 21:10
Hm, that's odd, I was able to reproduce it in a brand new project 🤔 

that being said, after upgrading to SDK 41 beta, this issue went away. Could you try running `EXPO_BETA=1 expo upgrade` (make sure you're on the most recent `expo-cli` version), following the prompts to upgrade to 41, and then rerunning? You can get the Expo Go testflight build [here](https://testflight.apple.com/join/GZJxxfUU).

**Comment by reft** [comment] 2021-04-06 07:38
Don't have an invite to testflight so I'm not able to confirm

**Comment by cruzach** [comment] 2021-04-06 13:21
It's a [public beta](https://blog.expo.io/expo-sdk-41-beta-is-now-available-958edcd78991), you don't need an invite. You can also test this in a simulator with local notifications instead of remote ones

**Comment by reft** [comment] 2021-04-11 08:00
I can confirm that the SDK 41 beta fixed it

**Comment by cruzach** [comment] 2021-04-11 14:52
Great! Thanks for following up, in that case I'll close the issue

**Closed by cruzach** 2021-04-11 14:52 UTC
Labels: Notifications, iOS, pending closure
