### ISSUE TITLE
[expo-device] isDevice returns true when app is running in emulator

### ISSUE THREAD

**Issue by yakupyazicioglu** [expo/expo#16165] opened 2022-02-02 13:45 UTC
### Summary

What I'm expecting is to detect what kind of device the app is running on and then open/close notification service based on this. In simulator, expo-device detects correctly and isDevice returns -> false, but in an android emulator it's true. It should be false as well.

I'm running project Mac M1 chip, this can be another reason why I see this. 

Here is another link about this problem but from the other way around.
[https://forums.expo.dev/t/expo-device-package-api-bug/56802](url)

![Screenshot 2022-02-02 at 14 41 27](https://user-images.githubusercontent.com/17622121/152165500-7681fd83-e41a-4a8e-bf32-5cb472095a50.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 32.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.2 => 43.0.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

It works with snacks as normal.

**Comment by kbrandwijk** [comment] 2022-02-02 21:39
If you have `adb` installed, could you run `adb shell getprop ro.build.fingerprint` and see what it returns?

**Comment by yakupyazicioglu** [comment] 2022-02-03 08:54
Hi @kbrandwijk, I run the command and the result is 
google/sdk_gphone64_arm64/emulator64_arm64:12/SE1A.211012.001/7818354:userdebug/dev-keys

**Comment by kbrandwijk** [comment] 2022-02-03 13:58
> Hi @kbrandwijk, I run the command and the result is google/sdk_gphone64_arm64/emulator64_arm64:12/SE1A.211012.001/7818354:userdebug/dev-keys

Thank you, that confirms my suspicion. I have a fix in the works that I linked above to address this issue.

**Comment by sajadghawami** [comment] 2022-02-03 14:45
same issue here

**Comment by kbrandwijk** [comment] 2022-02-03 14:48
> same issue here

If you could run the same command `adb shell getprop ro.build.fingerprint`, then I can verify the fix will work for you as well. Thank you!

**Comment by yakupyazicioglu** [comment] 2022-02-04 08:34
As a workaround, I added this line, but I hope it won't be necessary in the future

` else if (isAndroid && Device.productName?.includes("emulator")) {
      Alert.alert("Must use physical device for Push Notifications");}
`

**Comment by RRaideRR** [comment] 2022-02-05 20:36
Having the same issue here @kbrandwijk. The command `adb shell getprop ro.build.fingerprint` returns:

`google/sdk_gphone64_arm64/emulator64_arm64:12/SE1A.211012.001/7818354:userdebug/dev-keys`

Thanks for investing your time on this - very much appreciated 🙏

**Comment by kbrandwijk** [comment] 2022-02-06 04:35
> Having the same issue here @kbrandwijk. The command `adb shell getprop ro.build.fingerprint` returns:
> 
> `google/sdk_gphone64_arm64/emulator64_arm64:12/SE1A.211012.001/7818354:userdebug/dev-keys`
> 
> Thanks for investing your time on this - very much appreciated 🙏

Yes, your case will also be solved by this, currently the fingerprint is checked for the occurence of 'generic', which used to be enough in the past. The new check is more extensive, and will cover yours.

**Comment by hyochan** [comment] 2022-02-06 05:06
> As a workaround, I added this line, but I hope it won't be necessary in the future
> 
> `else if (isAndroid && Device.productName?.includes("emulator")) { Alert.alert("Must use physical device for Push Notifications");}`

IMO, this looks like a good patch.

**Comment by louiechristie** [comment] 2022-02-09 14:45
productName didn't include "emulator" for me on my M1 Mac, I had to use osBuildFingerprint instead i.e:
```javascript
else if (isAndroid && Device.osBuildFingerprint?.includes("emulator")) { Alert.alert("Must use physical device for Push Notifications");}
```

**Comment by kbrandwijk** [comment] 2022-02-09 15:56
> productName didn't include "emulator" for me on my M1 Mac, I had to use osBuildFingerprint instead i.e:
> 
> ```js
> else if (isAndroid && Device.osBuildFingerprint?.includes("emulator")) 
>   { Alert.alert("Must use physical device for Push Notifications");}
> ```

Could you share what your fingerprint looks like, to validate it will be detected correctly by the patch?

**Comment by louiechristie** [comment] 2022-02-09 22:06
> Could you share what your fingerprint looks like, to validate it will be detected correctly by the patch?
```
osBuildFingerprint: google/sdk_gphone64_arm64/emulator64_arm64:12/XX0X.000000.000/0000000:user/release-keys
```
Where XX0X.000000.000/0000000 is an alpha numeric code (obfuscated).

**Comment by ryan-case-ml** [comment] 2022-05-13 18:19
@kbrandwijk any movement on this? i am having the same issue as well. here is my osBuildFingerprint
`google/sdk_gphone_arm64/emulator_arm64:11/RSR1.210722.003/7604015:user/release-keys`

**Comment by majugurci** [comment] 2022-07-03 09:11
If it will help with solving issue, running `adb shell getprop ro.build.fingerprint` gives me this:

`google/sdk_gphone64_x86_64/emu64xa:13/TPB3.220513.017/8678579:userdebug/dev-keys`

Notice there is no word "emulator", only "emu".

**Comment by keith-kurak** [comment] 2022-08-01 20:29
A fix for this issue has been merged: https://github.com/expo/expo/pull/18394

**Closed by keith-kurak** 2022-08-01 20:29 UTC
Labels: bug, Device, Issue accepted

**Comment by dylanclements** [comment] 2022-08-04 00:58
Same issue here `adb shell getprop ro.build.fingerprint` returns:
`google/sdk_gphone64_arm64/emulator64_arm64:12/S2B2.211203.006/8015633:userdebug/dev-keys`

**Comment by Norfeldt** [comment] 2022-08-17 06:31
@keith-kurak @kbrandwijk the issue is still present (2022 August).

> console.log( { Device } )

```
Object {
  "Device": Object {
    "DeviceType": Object {
      "0": "UNKNOWN",
      "1": "PHONE",
      "2": "TABLET",
      "3": "DESKTOP",
      "4": "TV",
      "DESKTOP": 3,
      "PHONE": 1,
      "TABLET": 2,
      "TV": 4,
      "UNKNOWN": 0,
    },
    "brand": "google",
    "designName": "emu64a",
    "deviceName": "sdk_gphone64_arm64",
    "deviceYearClass": 2013,
    "getDeviceTypeAsync": [Function getDeviceTypeAsync],
    "getMaxMemoryAsync": [Function getMaxMemoryAsync],
    "getPlatformFeaturesAsync": [Function getPlatformFeaturesAsync],
    "getUptimeAsync": [Function getUptimeAsync],
    "hasPlatformFeatureAsync": [Function hasPlatformFeatureAsync],
    "isDevice": true,
    "isRootedExperimentalAsync": [Function isRootedExperimentalAsync],
    "isSideLoadingEnabledAsync": [Function isSideLoadingEnabledAsync],
    "manufacturer": "Google",
    "modelId": null,
    "modelName": "sdk_gphone64_arm64",
    "osBuildFingerprint": "google/sdk_gphone64_arm64/emu64a:13/TPB4.220624.004/8808248:user/release-keys",
    "osBuildId": "TPB4.220624.004",
    "osInternalBuildId": "TPB4.220624.004",
    "osName": "Android",
    "osVersion": "13",
    "platformApiLevel": 33,
    "productName": "emu64a",
    "supportedCpuArchitectures": Array [
      "arm64-v8a",
    ],
    "totalMemory": 2057662464,
  },
}
Android Running app on sdk_gphone64_arm64
```

```sh
❯ adb shell getprop ro.build.fingerprint
google/sdk_gphone64_arm64/emu64a:13/TPB4.220624.004/8808248:user/release-keys
```

no "emulator" in any names

**Comment by stri8ed** [comment] 2022-09-19 21:59
Experiencing this issue with Expo 46.

```
Object {
  "DeviceType": Object {
    "0": "UNKNOWN",
    "1": "PHONE",
    "2": "TABLET",
    "3": "DESKTOP",
    "4": "TV",
    "DESKTOP": 3,
    "PHONE": 1,
    "TABLET": 2,
    "TV": 4,
    "UNKNOWN": 0,
  },
  "brand": "google",
  "designName": "emulator64_x86_64_arm64",
  "deviceName": "sdk_gphone64_x86_64",
  "deviceYearClass": 2015,
  "getDeviceTypeAsync": [Function getDeviceTypeAsync],
  "getMaxMemoryAsync": [Function getMaxMemoryAsync],
  "getPlatformFeaturesAsync": [Function getPlatformFeaturesAsync],
  "getUptimeAsync": [Function getUptimeAsync],
  "hasPlatformFeatureAsync": [Function hasPlatformFeatureAsync],
  "isDevice": true,
  "isRootedExperimentalAsync": [Function isRootedExperimentalAsync],
  "isSideLoadingEnabledAsync": [Function isSideLoadingEnabledAsync],
  "manufacturer": "Google",
  "modelId": null,
  "modelName": "sdk_gphone64_x86_64",
  "osBuildFingerprint": "google/sdk_gphone64_x86_64/emulator64_x86_64_arm64:12/SE1A.220630.001/8789670:userdebug/dev-keys",
  "osBuildId": "sdk_gphone64_x86_64-userdebug 12 SE1A.220630.001 8789670 dev-keys",
  "osInternalBuildId": "SE1A.220630.001",
  "osName": "Android",
  "osVersion": "12",
  "platformApiLevel": 31,
  "productName": "emulator64_x86_64_arm64",
  "supportedCpuArchitectures": Array [
    "x86_64",
    "arm64-v8a",
  ],
  "totalMemory": 4006215680,
}
```

```
$ adb shell getprop ro.build.fingerprint
google/sdk_gphone64_x86_64/emulator64_x86_64_arm64:12/SE1A.220630.001/8789670:userdebug/dev-keys
```

**Comment by jameslporter** [comment] 2022-10-05 18:19
I'm not sure how to get the recent changes from the earlier merged fix. I did expo upgrade and allowed it continue although on current. It bumped up the constants package one micro. Still getting false for isDevice.

**Comment by bucky-badger-gesmer** [comment] 2022-10-13 21:11
@jameslporter 
> Still getting false for isDevice.

Same here! We have upgraded expo to `"expo": "^46.0.15"` and get `false` for `isDevice`. For the time being we are going to stick to `"expo": "^45.0.0"` and keep the logic:

``` 
const isSimulator = !Device.isDevice || !!Device.productName?.includes('emulator');

**Comment by xydian** [comment] 2022-11-04 22:25
For me the isDevice flag is also not working. For me isDevice is true on an iOS simulator. Please reopen this issue. Can provide more details if you need it

**Comment by iway1-hstk** [comment] 2023-03-15 16:16
still getting this issue

**Comment by RobinBobin** [comment] 2023-06-12 11:35
The same here.
