### ISSUE TITLE
[AV] Audio does not play when not connected to Metro Bundler on Android standalone Bare Workflow app.

### ISSUE THREAD

**Issue by Jkkarr2015** [expo/expo#7323] opened 2020-03-10 12:29 UTC
### Environment

I'm running Expo version 36.0.0 with an ejected project that has been changed to Bare Workflow. The app is targeting iOS and Android devices. 

### Steps to Reproduce

Have an application using Expo-AV Audio that can play sounds. In a Bare Workflow project run `react-native run-android` with an Android device. At this point, the audio should work. Now unplug the device from the computer, swipe the app away and reopen the app on the device. The sound will no longer play.

### Expected Behavior

I would expect it to be able to run standalone and when I press the button to play sounds I expect to hear sounds. 

### Actual Behavior

When I build a standalone version of the app for Android and disconnect from the Metro Bundler and reopen the app on my device the sound does not play. This behavior is exclusive to the Android version. The iOS version has no problems playing the sounds after it has disconnected from the Metro Bundler.

### Reproducible Demo

**Sound.js:**

```javascript
import React, { Component } from 'react';
import { View, Button } from 'react-native';
import { Audio } from 'expo-av';

export default class SoundButton extends Component {
    constructor(props) {
        super(props);
    }

    componentDidMount() {
        //Setup Audio async mode
        Audio.setAudioModeAsync({
            allowsRecordingIOS: false,
            staysActiveInBackground: false,
            interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_MIX_WITH_OTHERS,
            playsInSilentModeIOS: true,
            shouldDuckAndroid: false,
            interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
            playThroughEarpieceAndroid: false
        });
    }

    async playSound() {
        try{
            const newSound = new Audio.Sound();
            await newSound.loadAsync(require('./assets/anySound.mp3'));
            await newSound.playAsync();
        }
        catch(error){
            console.log(error);
        }
    }

    render() {
        return (
            <View>
                <Button
                onPress={this.playSound}
                title="Play Sound!">
                </Button>
            </View>
        );
    }
}
```

**App.js:**

```javascript
import React from 'react';
import { StyleSheet, View } from 'react-native';
import Sound  from './Sound';

export default function App() {

  return (
    <View style={styles.container}>
      <Sound/>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

If you need any more info from me please let me know.

**Comment by cruzach** [comment] 2020-03-11 21:40
> When I build a standalone version of the app for Android and disconnect from the Metro Bundler and reopen the app on my device the sound does not play.

By standalone, do you mean an APK? I think if you disconnect your device from the development server during development, that may result in unexpected behavior. If this is happening by running an apk, however, that is odd

**Comment by Jkkarr2015** [comment] 2020-03-12 11:33
@cruzach Yes, I do mean an APK. Sorry about that not being clear. I found that it does not work properly when I build a debug APK, but it does work with a release APK. Is that normal?

**Comment by cruzach** [comment] 2020-03-12 13:53
Why do you need a debug build that's not running a packager instance?  There must be a way to do this, I would look into the `react-native bundle` command and make sure you're passing the flags/args you need

Closing this since it's not a bug with the Expo SDK

**Closed by cruzach** 2020-03-12 13:53 UTC
Labels: Audio, Bare Workflow, bug, project: android-runtime, status: needs more info
