### ISSUE TITLE
[SDK 50] Android development builds crash

### ISSUE THREAD

**Issue by benjaminkomen** [expo/expo#26605] opened 2024-01-22 23:42 UTC
### Minimal reproducible example

https://github.com/benjaminkomen/expo-sdk50-android-dev-error

### Summary

Android development builds crash upon scanning the QR code in the terminal. See the attached minimal reproducible example for details and a build to test.

The issue does NOT occur when:
- using an iOS Simulator, development or preview build
- using an Android Emulator
- using an Android preview build on a physical device

In other words, it ONLY occurs with the Android development build on a physical device.

I only tested with the latest Expo Go app (2.30.8) and a Google Pixel 6 phone with Android 14. So it could be an issue with this specific device or app version as well.

<img src="https://github.com/expo/expo/assets/12815582/19c8ae4d-753a-4b1a-b9af-87c255be677c" width="300" />

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 34
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-30 | ARM 64 v8a, android-30 | Intel x86_64 Atom, android-30 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.2 => 50.0.2
      react: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
    npmGlobalPackages:
      eas-cli: 7.0.0
    Expo Workflow: managed
```

**Comment by brentvatne** [comment] 2024-01-22 23:43
duplicate of https://github.com/expo/expo/issues/26364

you can work around this by using `npx expo run:android -d` to build and run on device, or by running `adb reverse tcp:8081 tcp:8081`

we suspect something changed internally in react-native that is causing it to incorrectly try to load the bundle from localhost instead of the url provided

**Closed by brentvatne** 2024-01-22 23:43 UTC
Labels: needs review

**Comment by benjaminkomen** [comment] 2024-01-22 23:48
Ok, thanks for the quick response and sorry for the duplicate issue, I didn't find that issue when searching for the error from the stacktrace, I added the error as text to my issue so it's easier to google for other people!

**Comment by pencilcheck** [comment] 2024-03-12 01:24
I tried all the instructions but it still doesn't work.

**Comment by pencilcheck** [comment] 2024-03-12 01:25
Having issues like
```
Android internal error

configureTlsExtensions
Android10SocketAdapter.kt
```

**Comment by benjaminkomen** [comment] 2024-03-12 01:50
@pencilcheck I would advise to open a new issue

**Comment by jetaggart** [comment] 2024-03-25 18:01
@pencilcheck did you figure this out? having the same issue

**Comment by pencilcheck** [comment] 2024-03-28 08:44
> @pencilcheck did you figure this out? having the same issue

no, revert back to 49.

**Comment by arthur-fontaine** [comment] 2024-07-05 14:56
@pencilcheck @jetaggart Have you launched Expo through a tunnel? If so, does your subdomain of the tunnel URL contain an underscore? In my case, this seems to be the cause of the error, and I have found [an issue](https://github.com/square/okhttp/issues/5840) reporting a similar error.

**Comment by Aer0-17** [comment] 2024-11-13 06:35
> Using the EXPO_TUNNEL_SUBDOMAIN env variable and removing any underscores worked for me.

Thanks! this works for me.
