### ISSUE TITLE
[SDK34] - launchCameraAsync image not found in android

### ISSUE THREAD

**Issue by zapcriativo** [expo/expo#6674] opened 2020-01-04 22:01 UTC
Hello, I am trying to use launchCameraAsync, but I find the following problem on android.

When taking the photo, save the uri in a state and send via fetch to the server, in ios works, but in android the preview appears, but the url image is not found. I checked in android file explorer and it really doesn't have the folders inside the cache folder.

My function code 

` _pickImage = async () => {
    let result = await ImagePicker.launchCameraAsync({
      allowsEditing: true,
      aspect: [4, 3],
    });

    this.RBSheet.close();
    console.log(result);

    if (!result.cancelled) {
      this.setState({ image: result.uri });
    }

    this.props.SendProfilePictureURL(result.uri );
  }`

Return in console..

![image](https://user-images.githubusercontent.com/7153803/71772133-8d0d2b00-2f24-11ea-85ad-7601ae51158b.png)

App.json Android permissions 

![image](https://user-images.githubusercontent.com/7153803/71772137-9a2a1a00-2f24-11ea-994b-ca219de6d4d9.png)

**Comment by esamelson** [comment] 2020-01-06 20:55
Hey there @zapcriativo - could you please provide a full example we can use to reproduce this issue? A [snack](https://snack.expo.io) or a minimal GH repro would be great. It's really hard for us to help you out efficiently without this. Thanks!

**Comment by zapcriativo** [comment] 2020-01-08 13:27
Hi

I was able to solve by setting the quality parameter

     let result = await ImagePicker.launchCameraAsync ({
       allowsEditing: true,
       aspect: [4,3],
       **quality: 0.2**
     });

**Comment by lukmccall** [comment] 2020-01-27 10:21
Hi @zapcriativo, I think this was fixed in SDK 36. However, I'm not sure. I couldn't reproduce this on any version (tried 34 and 36). 
So, it'll be nice if you provide me with a snack or a GH repo to double-check it ;)

**Comment by prosenjitgit** [comment] 2020-04-23 13:59
I'm using 36 sdk but after apk build camera is not open...

const _takePhoto = async (getImage) => {
  try {
      const camera = await Permissions.askAsync(Permissions.CAMERA);
      const camera_roll = await Permissions.askAsync(Permissions.CAMERA_ROLL);
      if (camera.status === 'granted' && camera_roll.status==='granted') {
              let pickerResult = await ImagePicker.launchCameraAsync();
              if(!pickerResult.cancelled){
                alert('success!');
              }
      }
  } catch (e) {
      alert(JSON.stringify(e));
  }
};

**Comment by lukmccall** [comment] 2020-04-27 09:11
Hi @prosenjitgit, does it work in expo-client? Could you also post more information about your environment? For example, which workflow you are using or your android version. Did you test it on a physical device or with the simulator?

**Comment by lukmccall** [comment] 2020-07-13 17:32
We already made a lot of changes in this module since that time, so let me close it :D  Feel free to open a new report if it still happens to you in the latest SDK.

**Closed by lukmccall** 2020-07-13 17:32 UTC
Labels: ImagePicker, needs repro, status: needs more info

**Comment by nknaveen007** [comment] 2021-04-11 09:30
@zapcriativo i am also facing the same issue. in my case also uri not uploaded to the server.
my SDK version is 40. and this is my code.

  (async () => {
    
      if (Platform.OS !== 'web') {
        const { status } = await ImagePicker.requestMediaLibraryPermissionsAsync();
        const {status1} = await ImagePicker.requestCameraPermissionsAsync();
        if (status !== 'granted') {
          alert('Sorry, we need Image roll permissions to make this work!');
        }
       
      }
    })();

const pickCamera = async () => {

setVisiblepic(false)

let result = await ImagePicker.launchCameraAsync({

  mediaTypes: ImagePicker.MediaTypeOptions.Images,

  allowsEditing: true,

  aspect: [4, 3],

  quality: 0.5,

             

});



if (!result.cancelled) {

  console.log('camera image',result.uri)

  let name= imgstr()

 setimagename(name)

 setImage(result.uri);

  }
};

**Comment by zapcriativo** [comment] 2021-04-12 11:49
Hi hello, 

I change to base64 and solve the problem for me. Thanks for help
