### ISSUE TITLE
iOS push notifications don't work

### ISSUE THREAD

**Issue by azzozhsn** [expo/expo#2294] opened 2018-09-26 11:55 UTC
My problem is that Push notifications work on Android not iOS, I re-uploaded aps.p12 and certificate.p12 and mobileprovision file. I’m sending notifications from PHP code and getting response like this:

```
[
  [
    'status' => 'ok',
    'id' => '1e08c22f-3c5c-XXXX-XXXX-11571b61a091',
  ],
]
```

but doesn’t show on devices.

I checked the status by receipt id, the error message every time is: **“The Apple Push Notification service unexpectedly dropped the connection. Retry sending the notification later.”**

I'm using Apple Enterprise Program for this app.

**Comment by esamelson** [comment] 2018-09-29 00:46
Hi @azzozhsn - the fact that you received `status: 'ok'` means that Apple's Push Notification service received the notification from Expo and had no trouble with the push credentials, and considered the device token valid at the time of receiving the notification. This means the issue is most likely between Apple and your app. Is this continuing to happen (e.g. not a transient issue)?

**Comment by azzozhsn** [comment] 2018-09-29 04:27
Yes, it is still happening starting from creating the app. Android devices receive notifications but not iOS.

**Comment by EvanBacon** [comment] 2018-10-02 00:59
does _in-house_ mean Enterprise/B2B? Have you tried again later? was it working??

**Comment by azzozhsn** [comment] 2018-10-02 08:43
Yes, in-house means Enterprise (app for employees only).

I detach the app to use OneSignal, and I noticed xcode had me to replace one of the certificates in order to code sign it. Now, it is working with OneSignal.

I'm not sure was the problem because the certificate, or just the private key didn't mach at the time because I'm using two machines (work & home).

**Comment by Fantasim** [comment] 2018-11-02 12:08
Hi,

I've problem with iOS too to make working push notifications.
What the process you did with certificates in the order ?

Thank you

**Comment by SMESH-MC** [comment] 2018-11-09 16:58
> Yes, in-house means Enterprise (app for employees only).

Have a look at the Note at [https://docs.expo.io/versions/v31.0.0/guides/building-standalone-apps.html#if-you-choose-to-build-for-ios](url), if I get your problem right, you need an Enterprise Developer Account, it won't work with your standard apple dev account.

**Comment by azzozhsn** [comment] 2018-11-09 17:48
I have an Enterprise Developer Account but the problem is when I chose "Expo handles all credentials" it fails to get the certificate and when I provided certificate files I'm not sure if there was something wrong with those files.

Any way I couldn't wait so, I used onesignal for push notifications.

**Comment by FiberJW** [comment] 2019-10-28 19:56
This seems to be resolved, so I’ll close this for now. See [Bare Workflow](https://docs.expo.io/versions/latest/bare/exploring-bare-workflow/) for a cleaner way to use Expo in with custom native dependencies. If you need further support, please make a topic on our [forums](https://forums.expo.io) :)

**Closed by FiberJW** 2019-10-28 19:56 UTC
