### ISSUE TITLE
[iOS] Images under `assetBundlePatters` not appearing on first-load-offline

### ISSUE THREAD

**Issue by kr31n3r** [expo/expo#2060] opened 2018-07-31 22:23 UTC
### TL;TR

iOS standalone (image) assets are properly bundled but won't show up offline (first).

See also: https://forums.expo.io/t/ios-standalone-assetbundlepatterns-regression/12103

### Environment:
  OS: macOS Sierra 10.12.6
  Node: 10.7.0
  Yarn: 1.9.2
  npm: 6.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

  Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

  App target: iOS standalone

## Steps to Reproduce

1. configure `assetBundlePatterns` in `app.json` to bundle some image assets 
2. run `exp build:ios -t simulator` to create an iOS standalone simulator build
3. wait for build to finish then download and unpack `YourAppName.tar.gz`
4. start iOS simulator and run `xcrun simctl install booted YourAppName.app`
5. disable internet connection
6. start `YourAppName` inside iOS simulator
7. your bundled images won't show up

### Expected Behavior

Bundled image assets should work offline (first).
The same codebase works as expected for android standalone builds.

### Actual Behavior

iOS bundled images won't show up.

### Reproducible Demo

Any recent iOS standalone build should face this issue.

**Comment by terribleben** [comment] 2018-08-02 17:43
Thanks for the report, we have reproduced the issue and somebody is looking at it.

**Comment by ankit992** [comment] 2018-08-06 04:00
The issue also happens on Android in addition to iOS.

**Comment by drpancake** [comment] 2018-08-06 04:13
I'm also seeing this issue on both Android and iOS.

Reverting to SDK 28 fixed Android for me, but not iOS.

**Comment by terribleben** [comment] 2018-08-06 16:17
Fix landed internally for iOS. We'll roll it out to our `exp build` service early this week.

**Comment by sukso96100** [comment] 2018-08-10 02:14
Hi, Was the fix rolled out for `exp build` service? I'm also experiencing this issue on Android.

This is what i expected to see on first run with the apk file built with `exp build:android`.
![screenshot_20180810-104456](https://user-images.githubusercontent.com/1916739/43935313-4b2c021c-9c8e-11e8-906d-2c24fa9a7b41.jpg)

And this is what i actually see at first run.
![screenshot_20180810-110743](https://user-images.githubusercontent.com/1916739/43935300-3fd35866-9c8e-11e8-839b-2b4e178f0279.jpg)

If i stop by some other screens, then i can see the images like the screenshot.
![screenshot_20180810-111116](https://user-images.githubusercontent.com/1916739/43935351-7e6d223c-9c8e-11e8-9ac5-78b2c3c3b256.jpg)

**Comment by sjchmiela** [comment] 2018-08-13 11:48
When it comes to iOS, the fix has been deployed 6 days ago and I just confirmed it fixed the problem on iOS (I also had to add these two lines at the top of the `App.js` file):

```js
import { Asset } from 'expo';
Asset;
```

Please try to rebuild your apps and see whether the issue is fixed. If it's not, please open a new issue (the underlying reason of this issue has been fixed). 🙂

**Closed by sjchmiela** 2018-08-13 11:48 UTC
Labels: in review, project: sdk, project: xde/exp/xdl, status: pending

**Comment by riwu** [comment] 2018-08-13 11:55
Why is it necessary to add these 2 lines? It wasn't needed before.
Is it mandatory now due to the changes related to Universal Modules?

**Comment by sjchmiela** [comment] 2018-08-13 11:59
It's a bug introduced while moving `Asset` to `expo-asset`. The following lines have to be called prior to loading any assets by React Native. Including `Asset` like in 
https://github.com/expo/expo/issues/2060#issuecomment-412492285 executes those lines.

https://github.com/expo/expo-asset/blob/6698f2a6dc657a0b12bf29a22e62c83c9fd8ed3a/src/Asset.js#L186-L190

**Comment by riwu** [comment] 2018-08-13 12:03
So this workaround will not be necessary in the next Expo release (in which the bug will be fixed)?
Could you also confirm if the issue is resolved on Android too?
Thanks!

**Comment by sukso96100** [comment] 2018-08-13 13:56
@riwu I just tried a new build after adding two lines from [this comment](https://github.com/expo/expo/issues/2060#issuecomment-412492285) and it's fixed.
