### ISSUE TITLE
[bug] Standalone Android getDevicePushTokenAsync exception

### ISSUE THREAD

**Issue by joenoon** [expo/expo#719] opened 2017-10-03 20:14 UTC
First noticed in sdk 19.  Sounds like bug still exists in sdk 21 (per @johnnietirado).

```
const deviceToken = await Expo.Notifications.getDevicePushTokenAsync();

{ [Error: Cannot convert argument of type
class com.facebook.react.bridge.WritableNativeMap]
framesToPop: 1, code: 'EUNSPECIFIED' }
```

@miho7031 fixed in their own ExpoKit build.

Notes on their fix is here: https://forums.expo.io/t/standalone-android-sdk-19-0-0-getdevicepushtokenasync-exception/2915/6

For those not detached and using ExpoKit, would someone be able to make this change upstream?

**Comment by johnnietirado** [comment] 2017-10-03 20:26
Snack that can be used to reproduce error.

https://snack.expo.io/SJIdGOW2W

**Comment by saimemre1** [comment] 2017-10-05 08:58
I am not detached and I could reproduce the error, too. Work on iOS but throws error on android.

**Comment by Josh-ES** [comment] 2017-10-08 17:39
Also not detached but running my application as a standalone app, and I'm experiencing the same issue.

**Comment by joenoon** [comment] 2017-10-20 18:21
Anyone know if any fix made it into sdk v22?

**Comment by Josh-ES** [comment] 2017-10-20 18:33
The Android version of my app is now sending something from Android devices to our notifications service upstream, so I believe this is now fixed. Will confirm when I actually manage to send a push notification to the device.

**Comment by fxfactorial** [comment] 2018-01-24 02:43
@Josh-ES were you able to confirm?

**Comment by Josh-ES** [comment] 2018-01-24 10:07
@fxfactorial This one became a bit of a saga, because the call:

```
const deviceToken = await Expo.Notifications.getDevicePushTokenAsync();
```

Used Expo's GCM sender ID under the hood, so even though the code worked, you still couldn't send push notifications using it. I managed to make a change, although Expo themselves don't really publicise it, so that you can make the following call instead, using your own sender ID:

```
const { data: token, type: platform } = await Notifications.getDevicePushTokenAsync({
  gcmSenderId: "<your GCM sender ID>",
});
```

Which will create usable native device push tokens on both Android and iOS. We have this working in production!

@anp I think this should be good to close.

**Comment by sjchmiela** [comment] 2018-11-29 11:14
Following @Josh-ES's suggestion and closing. Thanks! 🙂

**Closed by sjchmiela** 2018-11-29 11:14 UTC
Labels: project: android-runtime, project: notification-service
