### ISSUE TITLE
ERROR  ReferenceError: Property 'SkiaApi' doesn't exist, js engine: hermes

### ISSUE THREAD

**Issue by ovidb** [expo/expo#23670] opened 2023-07-21 19:00 UTC
### Summary

This seems to be a regression and this issue was addressed in the past

Previously raised issue on the Skia repo: https://github.com/Shopify/react-native-skia/issues/106

and was addressed as part of this fix: https://github.com/expo/expo/pull/17780

For us the issue started happening after we upgraded to Expo SDK 49

Same behaviour as before - intermittently happening, fixed by pressing `r`

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo-dev-client": "~2.4.6",
"expo": "~49.0.3",
"@shopify/react-native-skia": "0.1.196",

### Environment

❯ npx expo-env-info

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
      Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/ovidb/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.1.1 => 18.1.1 
      expo: ~49.0.3 => 49.0.3 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.6 
    npmGlobalPackages:
      eas-cli: 3.16.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Reproducible demo

N/A

### Stacktrace (if a crash is involved)

 ERROR  ReferenceError: Property 'SkiaApi' doesn't exist, js engine: hermes

**Comment by gwendall** [comment] 2023-07-31 10:48
+1

**Comment by Kudo** [comment] 2023-08-01 01:56
sorry that i can not really reproduce the problem and would like to close this issue. if anyone can provide a reproducible example, i am happy to reopen and investigate this.

**Closed by Kudo** 2023-08-01 01:56 UTC
Labels: Issue accepted, Development Builds

**Comment by gretzky** [comment] 2023-08-17 18:10
This error comes at random, it's hard to determine the reproducible steps. This is still an issue, however, and you had to quit a development app and metro server to prevent it from occurring.

**Comment by sravis02** [comment] 2023-08-26 20:39
i also have this problem on my development builds. i can confirm that it happens randomly. reloading the app / restarting the server some times helps but it slows down the development :O

**Comment by felsey** [comment] 2023-09-20 10:16
I'm also running into this issue. It seems to be pretty intermittent, which is making it much harder to debug.

**Comment by felsey** [comment] 2023-09-20 10:20
This is what the error looks like on my dev build when it happens:
![IMG_1576](https://github.com/expo/expo/assets/3254330/0398a2ad-6662-435a-b6d7-99bd8af0a830)

And this is the error I'm seeing in my terminal:

```ERROR  ReferenceError: Property 'SkiaApi' doesn't exist, js engine: hermes 
    at ContextNavigator (http://192.168.4.44:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:159039:24)
    at ExpoRoot (http://192.168.4.44:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:159010:30)
    at App
    at withDevTools(App) (http://192.168.4.44:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:137150:27)
    at ErrorToastContainer (http://192.168.4.44:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:137051:24)
    at ErrorOverlay
    at RCTView
    at View (http://192.168.4.44:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:63018:43)
    at RCTView
    at View (http://192.168.4.44:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:63018:43)
    at AppContainer (http://192.168.4.44:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:62875:36)
    at main(RootComponent) (http://192.168.4.44:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:109805:28)
```

**Comment by mvaivre** [comment] 2023-10-02 06:24
I can confirm that this happens. It's indeed quite random... maybe some kind of race condition?

**Comment by WildesPiva** [comment] 2023-10-11 13:16
This happens to me, and this started after I ran the expo's fix dependencies, it changed the installed version of
  from "@shopify/react-native-skia": "^0.1.212" to "@shopify/react-native-skia": "0.1.196" after that this error happens randomly.

**Comment by GabrielDierks** [comment] 2023-10-27 11:00
+1

**Comment by kevinmcalear** [comment] 2023-10-31 09:22
Same issue for me with the lastest expo (49.0.16), react-native-skia (0.1.214), and expo-dev-client (2.4.11)

**Comment by yoann84** [comment] 2023-11-07 10:27
Why this ticket is closed ? We still experience the problem

**Comment by aniqueali** [comment] 2023-11-14 17:55
The same is happening with my code. Sometimes it runs, sometimes it doesn't.
Anyone found a solution for this?

**Comment by johnbindel** [comment] 2023-11-14 19:39
This is also happening for me still with react-native-skia 0.1.196

**Comment by jdponomarev** [comment] 2023-11-28 23:48
this is still happening

**Comment by i-mighty** [comment] 2023-12-04 12:50
Still happening. Now everything breaks.

**Comment by vpctorr** [comment] 2024-01-19 11:34
I used to run into this issue on a daily basis, SDK50 seems to have fixed the issue

**Comment by ovidb** [comment] 2024-03-05 08:13
@Kudo I think we should reopen this issue. I'm struggling to create a repro but it's super random and it usually happens when you press `r` to refresh the clients. 

I will try to put together a repro repo this week but let's please reopen this issue as it seems a lot of people are getting it and we stated getting it again

**Comment by MarcHbb** [comment] 2024-08-01 11:54
On expo SDK 51 still happening randomly 
`"@shopify/react-native-skia": "1.2.3"`

**Comment by AdzeB** [comment] 2024-08-03 10:13
Experiencing the same issue has well

**Comment by Fungusjuice** [comment] 2024-08-11 13:26
why is this closed? problem still happening

**Comment by maukoese** [comment] 2024-09-04 20:25
Fresh install, still getting this error

**Comment by deelo55** [comment] 2024-09-09 19:51
I'm getting this error as well

**Comment by ilies-space** [comment] 2024-10-01 04:49
Works for me:

**1)  Kill metro server
2) Close expo go / app
3) Run `npx expo start -c`
4) Problem goes 👌**

note: still the cause of this is unknown i believe the last thing i did was changing some .env variables and problem shows.

**Comment by akodkod** [comment] 2024-10-18 09:41
+1 for this issue

**Comment by aabmar** [comment] 2024-11-05 09:24
This happened to me today. Killing the DevClient and starting it again, made it go away. Now I'm worried that will this happen on users devices at random times.
