### ISSUE TITLE
Replacing JCenter with MavenCentral

### ISSUE THREAD

**Issue by mcrombie** [expo/expo#16079] opened 2022-01-26 15:20 UTC
### Summary

I am attempting to build an apk of my react-native project with turtle, but the repository it relies on (for some reason it is under exoplayer) returns a 502 error: https://google.bintray.com/exoplayer/com/facebook/react/react-native/maven-metadata.xml. I would like to replace this repository with maven central because JCenter has been decommissioned. 

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

{
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest",
    "install-expo-dependencies": "expo install react-native-safe-area-context"
  },
  "dependencies": {
    "@babel/runtime": "^7.13.10",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/slider": "3.0.0",
    "@react-navigation/bottom-tabs": "^5.11.15",
    "@react-navigation/native": "^5.9.8",
    "@react-navigation/stack": "^5.14.9",
    "expo": "38.0.0",
    "expo-screen-orientation": "~1.1.1",
    "expo-splash-screen": "^0.8.1",
    "formik": "^2.2.6",
    "react": "16.11.0",
    "react-dom": "16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz",
    "react-native-chart-kit": "^6.10.0",
    "react-native-device-detection": "^0.2.1",
    "react-native-elements": "^2.0.0",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-phone-call": "^1.0.9",
    "react-native-picker-select": "^7.0.0",
    "react-native-pure-chart": "^0.0.24",
    "react-native-reanimated": "~1.9.0",
    "react-native-responsive-screen": "^1.4.1",
    "react-native-screens": "~2.9.0",
    "react-native-svg": "12.1.0",
    "react-native-svg-charts": "^5.4.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-switch-selector": "^2.0.4",
    "react-native-tab-view": "^2.15.0",
    "react-native-unimodules": "~0.10.1",
    "react-native-vector-icons": "^6.7.0",
    "react-native-web": "~0.11.7",
    "victory-native": "^35.3.3",
    "yup": "^0.32.8"
  },
  "devDependencies": {
    "@babel/core": "~7.6.0",
    "babel-jest": "~24.9.0",
    "jest": "~24.9.0",
    "metro-react-native-babel-preset": "~0.56.0",
    "react-test-renderer": "~16.9.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}

### Environment

  Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3, 31.0.0
        System Images: android-24 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: 38.0.0 => 38.0.0 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    Expo Workflow: managed

### Reproducible demo

See the turtle building guide I used here: https://www.robincussol.com/build-standalone-expo-apk-ipa-with-turtle-cli/ 

Initialize expo project with SDK 38 and dependencies above. 

Setup turtle CLI:
npm install -g turtle-cli
turtle setup:ios
turtle setup:android

Create a keystore.jks (store in a "certs" folder at the root of the app) and a keyalias 

Host on python in a terminal tab:
sudo python https.py

Launch app from a terminal tab:
expo start

Export the app:
expo export --public-url=https://127.0.0.1 in a terminal tab

Build the app:
NODE_TLS_REJECT_UNAUTHORIZED=0 EXPO_ANDROID_KEYSTORE_PASSWORD="INSERT_PASSWORD" EXPO_ANDROID_KEY_PASSWORD="INSERT_PASSWORD" turtle build:android --type apk --keystore-path "./certs/keystore.jks" --keystore-alias "keyalias" --public-url https://127.0.0.1/android-index.json -o ./app.apk

EXPECTED: An apk is created
ACTUAL: the process crashes because it gets a 502 error:
"Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/facebook/react/react-native/maven-metadata.xml"

I am aware of this thread - https://github.com/expo/expo/issues/12226 but did not find a way of transitioning to maven central for my environment. 

### Stacktrace (if a crash is involved)

Jan 26 10:17:32 turtle[51022] INFO:  FAILURE: Build failed with an exception.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:  * What went wrong:
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:  Could not determine the dependencies of task ':app:processReleaseResources'.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:  > Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:     > Could not resolve com.facebook.react:react-native:+.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:       Required by:
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:           project :app
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:           project :app > org.unimodules:unimodules-react-native-adapter:5.4.0
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:        > Failed to list versions for com.facebook.react:react-native.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:           > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/facebook/react/react-native/maven-metadata.xml.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:              > Could not get resource 'https://google.bintray.com/exoplayer/com/facebook/react/react-native/maven-metadata.xml'.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:                 > Could not GET 'https://google.bintray.com/exoplayer/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:  * Try:
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:  * Get more help at https://help.gradle.org
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:  BUILD FAILED in 19s
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 26 10:17:32 turtle[51022] INFO:  Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
  platform: "android"
  buildPhase: "running gradle"
  source: "stdout"
Jan 26 10:17:32 turtle[51022] INFO:  Use '--warning-mode all' to show the individual deprecation warnings.
  platform: "android"
  buildPhase: "running gradle"
  source: "stdout"
Jan 26 10:17:32 turtle[51022] INFO:  See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
  platform: "android"
  buildPhase: "running gradle"
  source: "stdout"
Jan 26 10:17:33 turtle[51022] ERROR: Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    ...
    at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@59.1.0/src/detach/ExponentTools.ts:111:19)
    at buildShellAppAsync (/@expo/xdl@59.1.0/src/detach/AndroidShellApp.js:1476:11)
    at Object.createAndroidShellAppAsync (/@expo/xdl@59.1.0/src/detach/AndroidShellApp.js:380:5)
    at runShellAppBuilder (/usr/local/lib/node_modules/turtle-cli/src/builders/android.ts:91:5)
    at buildAndroid (/usr/local/lib/node_modules/turtle-cli/src/builders/android.ts:23:26)
    at /usr/local/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
    at Command.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "android"
Jan 26 10:17:33 turtle[51022] ERROR: Failed to build standalone app
  err: Error: ./gradlew exited with non-zero code: 1
      at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:422:26)
      at ChildProcess.emit (events.js:315:20)
      at ChildProcess.EventEmitter.emit (domain.js:486:12)
      at maybeClose (internal/child_process.js:1048:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
      ...
      at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at spawnAsyncThrowError (/@expo/xdl@59.1.0/src/detach/ExponentTools.ts:111:19)
      at buildShellAppAsync (/@expo/xdl@59.1.0/src/detach/AndroidShellApp.js:1476:11)
      at Object.createAndroidShellAppAsync (/@expo/xdl@59.1.0/src/detach/AndroidShellApp.js:380:5)
      at runShellAppBuilder (/usr/local/lib/node_modules/turtle-cli/src/builders/android.ts:91:5)
      at buildAndroid (/usr/local/lib/node_modules/turtle-cli/src/builders/android.ts:23:26)
      at /usr/local/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
      at Command.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "android"

**Comment by brentvatne** [comment] 2022-01-26 18:13
duplicate of #14185

we plan on upgrading exoplayer to pull from the google maven repo

**Closed by brentvatne** 2022-01-26 18:13 UTC
Labels: needs review
