### ISSUE TITLE
Duplicate screen when open app iOS Standalone

### ISSUE THREAD

**Issue by hai2014bk** [expo/expo#837] opened 2017-10-23 10:39 UTC
Hi guys, thanks for powerful Expo, but when i build standalone app, i got this bug, and only on iOS. 
That after loading screen, my first screen have been duplicated,(twice time open, sometimes it's three), and i truly don't know why, not even a clue.

Here is my code for my setup.js 

`Import * as Expo from "expo";
import React, { Component } from "react";
import { Provider } from "react-redux";
import { StyleProvider, Root  } from "native-base";
import * as mConstants from './utils/Constants'
import {
	AsyncStorage,
	BackHandler
  } from "react-native";
import App from "./pFood";
import configureStore from "./configureStore";
import getTheme from "../native-base-theme/components";
import variables from "../native-base-theme/variables/commonColor";

export default class Setup extends Component {
	constructor() {
		super();
		this.state = {
			isLoading: false,
			store: configureStore(),
			isReady: false,
			isLogined: false
		};
	}
	async componentWillMount() {
		await Expo.Font.loadAsync({
			Roboto: require("native-base/Fonts/Roboto.ttf"),
			Roboto_medium: require("native-base/Fonts/Roboto_medium.ttf"),
			Helvetica: require("../fonts/HLTr.ttf"),
			Ionicons: require("@expo/vector-icons/fonts/Ionicons.ttf"),
		});
		const loginInfo = await AsyncStorage.getItem(mConstants.USER_INFO);
		console.log('login 111112221', loginInfo)
		if (loginInfo !== null) {
			console.log('login 11212111', loginInfo)
			var user = JSON.parse(loginInfo)
			var date = new Date()
			console.log('2138921803213',user.date,date)
			var msPerMinute = 60 * 1000;
			var msPerHour = msPerMinute * 60;
			var msPerDay = msPerHour * 24;				
			var oldDate = new Date(user.date).getTime()
			var nowDate =  date.getTime()
			var elapsed = nowDate - oldDate;				
			var diff =  Math.round(elapsed/msPerHour );   
			if (diff < 24) {
				this.setState({ isLogined: true, isReady:true })					
			} else {
				let keys = [mConstants.CART, mConstants.USER_INFO, mConstants.USER_DETAIL];
				await AsyncStorage.multiRemove(keys)
				this.setState({ isLogined: false, isReady:true })
			}
		} else {
			this.setState({ isLogined: false, isReady:true })
		}
	}

	render() {
		if (!this.state.isReady) {
			return null;
		} else {
		var initialRoute = this.state.isLogined ? "Drawer":"Login"
			return (
				<StyleProvider style={getTheme(variables)}>
					<Provider store={this.state.store}>
						<Root>
							<App initialRouteName={initialRoute} />
						</Root>
					</Provider>
				</StyleProvider>
			);
		}
	}
}`

Help me PLEASE :(

**Comment by iuliuvisovan** [comment] 2017-10-24 14:18
> my first screen have been duplicated,(twice time open, sometimes it's three), and i truly don't know why, not even a clue.

What does that mean? You see it open multiple times?

**Comment by brentvatne** [comment] 2017-10-24 17:37
thanks for sharing the code! this must be frustrating. can you try creating a minimal example of this happening? for more information on how to submit a good issue that will get you helped more quickly, read https://www.snoyman.com/blog/2017/10/manipulating-maintainers

**Comment by wlwg** [comment] 2017-10-26 08:10
I'm having the same issue when running my expo standalone iOS app on an iPhone simulator. Basically when the app starts, it first shows the home screen as configured, then it immediately navigates to the home screen again, which caused the route stack to be [home, home]. 

My config:
exp sdk: 21.0.0
react navigation: 1.0.0-beta.15

**Comment by wlwg** [comment] 2017-10-31 23:08
Looks it's a duplicate of @ #818

**Comment by terribleben** [comment] 2017-11-21 19:02
Hi, this is a known issue with the react-navigation library, for now I think the best bet is to follow the workaround given in this [comment](https://github.com/expo/expo/issues/818#issuecomment-338279588), or contribute a fix upstream to react-navigation.

**Closed by terribleben** 2017-11-21 19:02 UTC
Labels: status: needs more info
