### ISSUE TITLE
[SDK 50] [expo-location] java.lang.NullPointerException: it must not be null

### ISSUE THREAD

**Issue by kamui545** [expo/expo#26620] opened 2024-01-23 10:05 UTC
### Minimal reproducible example

Sadly I cannot reproduce it consistently yet...

### Summary

The crash happened on Android v12, after this code which is basically similar to the doc:

```ts
async function onLocationPress() {
  const { status } = await Location.requestForegroundPermissionsAsync();

  if (status !== 'granted') {
    Alert.alert(
      t('Permission required'),
      t('You need to allow location services.'),
    );

    return;
  }

  const position = await Location.getCurrentPositionAsync({});

  // ...  
}
```

```
java.lang.NullPointerException: it must not be null
    at expo.modules.location.LocationHelpers$Companion$requestSingleLocation$1.invoke(LocationHelpers.kt:73)
    at expo.modules.location.LocationHelpers$Companion$requestSingleLocation$1.invoke(LocationHelpers.kt:72)
    at expo.modules.location.LocationHelpers$Companion.requestSingleLocation$lambda$1(LocationHelpers.kt:72)
    at expo.modules.location.LocationHelpers$Companion.$r8$lambda$W5SDDof5VIeQJZEkzL27bikXea4
    at expo.modules.location.LocationHelpers$Companion$$ExternalSyntheticLambda0.onSuccess
    at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:233)
    at android.os.Looper.loop(Looper.java:344)
    at android.app.ActivityThread.main(ActivityThread.java:8212)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 3.7.0 - /opt/homebrew/bin/fish
    Binaries:
      Node: 21.6.1 - /opt/homebrew/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11005911
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.2 => 50.0.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    npmGlobalPackages:
      eas-cli: 7.0.0
    Expo Workflow: bare
```

**Comment by efstathiosntonas** [comment] 2024-01-23 11:02
@Kudo Hi, this needs some attention, unfortunatelly it's really hard to reproduce and it affects several android devices. I believe this should be opened since adding a repro repo has no sense. 

I've been facing this issue in production with all versions > `16.4.0`. It's impossible for me to reproduce on my devices/emulators.

**Comment by efstathiosntonas** [comment] 2024-01-23 11:54
cc: @lukmccall

**Comment by efstathiosntonas** [comment] 2024-01-23 14:03
thanks @lukmccall 

Adding the devices that have the issue, I got a Samsung S22 with Android and I cannot reproduce it 🤷‍♂️ 

<details>
  <summary>Click me</summary>
  
![Screenshot 2024-01-23 at 16 02 27](https://github.com/expo/expo/assets/717975/2900cc2f-5b0d-45d8-b960-5f09e9659807)


</details>

**Comment by efstathiosntonas** [comment] 2024-01-23 14:32
@lukmccall keep in mind that this might be reproducible only in prod mode, we really don't know....

**Comment by kamui545** [comment] 2024-01-24 16:17
I made a minimal app to request location every 3s: https://github.com/kamui545/expo-location-issues

I doubt it's going to be helpful to reproduce the error but I will let it run for a while on my OnePlus Nord where I initially got the error, who knows...

**Comment by contactsimonwilson** [comment] 2024-01-25 02:59
I just pushed out an update with Expo 50 and have a couple of users running into the same issue with the upgrade. It's fine for me on a Mi 12 with Android 13 but is crashing on a Pixel 7 Pro with Android 14.

**Comment by efstathiosntonas** [comment] 2024-01-25 11:00
@lukmccall it seems that this kicks in when location is turned off in the device. Did some digging and found these stackoverflow questions:

* https://stackoverflow.com/questions/75566637/fused-location-provider-method-getlastlocation-returning-null-values
* https://stackoverflow.com/questions/67621866/fusedlocationproviderclient-not-working-correctly-when-location-turned-on-off
* https://stackoverflow.com/questions/70658610/fusedlocationproviderclient-crash-with-java-lang-nullpointerexception-parameter

Will turn off location on S22 and check it out. I think that's why we think it's "random".

**Comment by efstathiosntonas** [comment] 2024-01-25 11:17
@lukmccall can verify, my S22 insta crashed when I turned off the GPS.

**Comment by efstathiosntonas** [comment] 2024-01-25 11:30
Patch that fixes the issue, the app catches the error just fine: 

```patch
diff --git a/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationHelpers.kt b/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationHelpers.kt
index a3fe07d..b25f0b5 100644
--- a/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationHelpers.kt
+++ b/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationHelpers.kt
@@ -66,22 +66,29 @@ class LocationHelpers {
       }.build()
     }

-    fun requestSingleLocation(locationProvider: FusedLocationProviderClient, locationRequest: CurrentLocationRequest, promise: Promise) {
-      try {
-        locationProvider.getCurrentLocation(locationRequest, null)
-          .addOnSuccessListener {
-            promise.resolve(LocationResponse(it))
+      fun requestSingleLocation(locationProvider: FusedLocationProviderClient, locationRequest: CurrentLocationRequest, promise: Promise) {
+          try {
+              locationProvider.getCurrentLocation(locationRequest, null)
+                      .addOnSuccessListener { location ->
+                          if (location != null) {
+                              // Since `it` is not null, creates a LocationResponse instance.
+                              promise.resolve(LocationResponse(location))
+                          } else {
+                              // If location is null (meaning GPS is turned off), rejects promise.
+                              promise.reject(LocationRequestRejectedException(NullPointerException("Location is null, possibly because GPS is off")))
+                          }
+                      }
+                      .addOnFailureListener {
+                          // Passes the exception to the Promise.
+                          promise.reject(LocationRequestRejectedException(it))
+                      }
+                      .addOnCanceledListener {
+                          promise.reject(LocationRequestCancelledException())
+                      }
+          } catch (e: SecurityException) {
+              promise.reject(LocationRequestRejectedException(e))
           }
-          .addOnFailureListener {
-            promise.reject(LocationRequestRejectedException(it))
-          }
-          .addOnCanceledListener {
-            promise.reject(LocationRequestCancelledException())
-          }
-      } catch (e: SecurityException) {
-        promise.reject(LocationRequestRejectedException(e))
       }
-    }

     fun requestContinuousUpdates(locationModule: LocationModule, locationRequest: LocationRequest, watchId: Int, promise: Promise) {
       locationModule.requestLocationUpdates(
```

**Comment by lukmccall** [comment] 2024-01-25 13:22
Thanks, @efstathiosntonas, for your help on that issue. I was able to reproduce it. Also, I've modified the proposed solution, and it should be merged soon.

**Comment by efstathiosntonas** [comment] 2024-01-25 13:26
Perfect, thanks @lukmccall!

**Closed** 2024-01-25 14:12 UTC
Labels: incomplete issue: missing or invalid repro

**Comment by forki** [comment] 2024-01-29 11:10
what do we need to get this fixed in our app? Is there a new expo-location npm package?

**Comment by contactsimonwilson** [comment] 2024-01-29 11:11
@forki no new package yet. I'm using patch-package with the details in the post above yours as a fix in the meantime

**Comment by behenate** [comment] 2024-02-01 10:35
@Shofol If you need a fix right away you can use patch-package with changes from this PR: https://github.com/expo/expo/pull/26688

**Comment by a-eid** [comment] 2024-02-04 23:21
it still crashing after applying the PR: #26688

**Comment by lukmccall** [comment] 2024-02-05 15:22
@a-eid, are you sure that you applied the packet correctly? The line numbers in the posted exception don't align with a patched version of the file.

**Comment by kamui545** [comment] 2024-02-06 15:04
`expo-location@16.5.3` is available with the patch

**Comment by boxman0617** [comment] 2024-02-06 20:19
I fixed this right now by opening Google Maps on the emulator and having it lock on my location (which i set in the settings of the emulator), restarted the app and it worked!
