### ISSUE TITLE
ScrollView is not rendering in react-test-renderer snapshots

### ISSUE THREAD

**Issue by mslavik2** [expo/expo#2484] opened 2018-10-23 17:04 UTC
### Environment
Environment:
  OS: Windows 10
  Node: 8.11.2
  Yarn: 1.10.1
  npm: 6.3.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4907809

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/dmsi-31b81f4e-984a-4a3a-a8e2-735f6a2d5142.tar.gz

We use the expo client for testing but ultimately make standalone builds to put in stores. 

### Steps to Reproduce

ScrollView is not rendering in snapshots when upgrading from sdk 28 to 30. I think I tracked down the change that broke this but I am not sure why it would have broken the snapshots. (Removing that change fixes the snapshots)

https://github.com/expo/react-native/commit/d2194e12b288d61b6ebea758da7205f15f61f278#diff-606adbd6a8c97d177b17baee5a69cdd9

1. Start with a brand new project (expo init)
2. Use this package.json
https://gist.github.com/mslavik2/cd1808ef981a49afbac5c2bfef750973
3. Run npm install / yarn
4. Change App.js to
https://gist.github.com/mslavik2/6004fcde5ab1238cc631d01dbc85bc52
5. Add a file of App.spec.js to the root of your project
https://gist.github.com/mslavik2/49ffb0ae581a758410fbf8371548fb1d
6. Run npm test/yarn test
7. View __snapshots__/App.spec.js.snap

### Expected Behavior

ScrollView to be rendered in the snapshot. Like in this gist:
https://gist.github.com/mslavik2/e128a63533b08a23d64f156b643a3a08

### Actual Behavior

ScrollView is not rendered in react-test-renderer snapshot. Actual output of the snapshot currently:
https://gist.github.com/mslavik2/e8b6034b3a36d4f7fe9124de15c9be9b

### Reproducible Demo

(See steps to reproduce)

**Comment by brentvatne** [comment] 2018-10-23 17:59
this uses the same testing setup as react-native upstream: https://github.com/facebook/react-native/blob/master/jest/setup.js#L44

the reason the path is different is because react-native upstream uses a module system called haste which doesn't work very well outside of facebook (the project is moving away from it). not sure what you mean by 'scrollview to be rendered in snapshot' - you should see this: https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/__mocks__/ScrollViewMock.js

**Comment by mslavik2** [comment] 2018-10-24 12:16
@brentvatne I have included gists in the original post of the expected and actual snapshots. Sorry for any confusion I caused by not including them earlier.

**Comment by taranda** [comment] 2018-10-30 20:15
I can confirm that this is happening in pure React Native without Expo:
  react-native: 0.56.0
  react: 15.4.1
  react-test-renderer: 16.3.1

The `<ScrollView>` component and all of its children get ignored completely in the snapshot.

**Comment by taranda** [comment] 2018-10-31 21:58
This also appears to have been fixed by React Native 0.57.1 and react 16.5

**Comment by mslavik2** [comment] 2018-11-01 12:20
Thanks for the info @taranda, looks like I will just need to wait for sdk 31 (or which ever ends up pulling in react-native 0.57.1).

**Comment by taranda** [comment] 2018-11-01 20:19
I just updated to React Native 0.57 and I am still experiencing this issue.  It must be another configuration problem.  I would recommend reopening this issue.

**Comment by sjchmiela** [comment] 2018-11-27 08:17
Great news, @taranda, thanks for the information! I'll close this issue tentatively, feel free to reopen it anytime if you encounter this problem again. 🙂

**Closed by sjchmiela** 2018-11-27 08:17 UTC

**Comment by clems36** [comment] 2019-01-09 16:10
I'm also experiencing this issue with sdk 32 (react-native 57.1) and `react-native-jest-mocks` is not a part of my `node_modules`.

**Comment by rflorence** [comment] 2019-01-15 15:54
I'm experiencing this in SDK 31 and 32 (not 30). It works if I replace my react-native dependency with `https://github.com/expo/react-native/archive/v0.57.5.tar.gz` like in #2806, but that breaks other things in runtime. Can you reopen this issue?

As a workaround, I've switched my ScrollView usage to this component that renders ScrollView at runtime and View in tests. Then I can access the ScrollView's children in the tests with `findByType` or `findByProps`.

```
import React, { Component } from 'react';
import { ScrollView as RNScrollView, View } from 'react-native';

const isRunningTest = () => {
  return process.env.NODE_ENV === 'test';
};

export class ScrollView extends Component {
  render() {
    return isRunningTest() ? (
      <View {...this.props} />
    ) : (
      <RNScrollView {...this.props} />
    );
  }
}
```

**Comment by sergioalvz** [comment] 2019-02-06 21:53
I would say this is still happening... Everything under `ScrollView` just get ignored.

```
Environment:
OS: MacOS 10.14.2
Node: v8.11.4
Yarn: 1.13.0
npm: 5.6.0

Packages: (wanted => installed)
expo: ^32.0.0 => 32.0.4
react: 16.5.0 => 16.5.0
react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
```

**Comment by artur513** [comment] 2019-02-07 03:54
I am also having the same issue and do not have the `react-native-jest-mocks` as part of the `node_modules`. SDK 32 does not work, but changing the react-native dependency to `https://github.com/expo/react-native/archive/v0.57.5.tar.gz` does work.

```
Environment:
OS: MacOS 10.12.6
Node: 10.9.0

Packages:
expo: 31.0.4
react: 16.5.0
react-native: https://github.com/expo/react-native/archive/sdk-32.0.1.tar.gz
```

**Comment by marcusstenbeck** [comment] 2019-02-11 14:12
I was able to make it work by mocking `ScrollView` with, wait for it... `ScrollView`. Maybe there's going to be issues with this too, but for the time being it seems to work as a temporary bandaid-solution.

```json
// in your jest config

"setupFiles": [
  "path/to/uglyScrollViewHack.js"
]
```

```js
// uglyScrollViewHack.js

jest.mock("react-native/Libraries/Components/ScrollView/ScrollView", () =>
    jest.requireActual("react-native/Libraries/Components/ScrollView/ScrollView")
);
```
