### ISSUE TITLE
[expo-notifications] Crash in a development build

### ISSUE THREAD

**Issue by tabitta** [expo/expo#30775] opened 2024-08-02 10:15 UTC
### Minimal reproducible example

https://github.com/tabitta/my-app-notif-test

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Hello,
We have an app that sends local daily notifications. After upgrading to Expo SDK 50, I noticed that the application crashes after a notification is scheduled and the app calls getAllScheduledNotificationsAsync or the app is opened from a notification. The same behavior happens both on a real device and on an emulator. And it happens in a build created locally, but also in a build created with EAS Build.

The following error is thrown:
ERROR  Your app just crashed. See the error below.
java.lang.ClassCastException: expo.modules.notifications.notifications.triggers.DailyTrigger cannot be cast to expo.modules.notifications.notifications.model.triggers.FirebaseNotificationTrigger
  expo.modules.notifications.notifications.NotificationSerializer.toBundle(NotificationSerializer.java:62)
  expo.modules.notifications.notifications.scheduling.NotificationScheduler.serializeScheduledNotificationRequests(NotificationScheduler.kt:233)
  expo.modules.notifications.notifications.scheduling.NotificationScheduler$definition$1$1$1.invoke(NotificationScheduler.kt:54)
  expo.modules.notifications.notifications.scheduling.NotificationScheduler$definition$1$1$1.invoke(NotificationScheduler.kt:48)
  expo.modules.notifications.UtilsKt$createDefaultResultReceiver$1.onReceiveResult(Utils.kt:16)
  android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
  android.os.Handler.handleCallback(Handler.java:942)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loopOnce(Looper.java:201)
  android.os.Looper.loop(Looper.java:288)
  android.app.ActivityThread.main(ActivityThread.java:7872)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

I managed to reproduce the error by just creating a new project following the steps:
npx create-expo-app@latest
npx expo install expo-dev-client
npx expo install expo-notifications
npx expo run:android
It seems that it happens when you are using a development build, I did not reproduce it with Expo Go app.

I have created a repository to reproduce the issue. If you press on Schedule Notification from home screen, then on Get Notifications, the app will crash.

Any help with resolving this problem would be greatly appreciated. Thank you!

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-241.18034.62.2411.12071903
    npmPackages:
      expo: ~51.0.24 => 51.0.24
      expo-router: ~3.5.20 => 3.5.20
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: bare

It outputs Expo Workflow as bare, but actually it is a managed workflow. I made no changes inside the android/ folder. I only run the command npx expo run:android

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by altany** [comment] 2024-08-02 10:25
I am having a similar issue with scheduleNotificationAsync. It started crashing since upgrading to expo-notifications 0.28.14 from 0.28.12

**Comment by giiilees** [comment] 2024-08-02 11:47
I had the same issue after updating to expo-notifications 0.28.14 while on SDK 50
Then tried to update to SDK 51 which comes by default with expo-notifications 0.28.14 but crashes my app as soon as it starts without any log.

**Comment by tabitta** [comment] 2024-08-02 11:48
Just a short correction, I upgraded incrementally from Expo SDK 48 to Expo SDK 51, not 50 and tested only with SDK 51.

**Comment by altany** [comment] 2024-08-02 11:51
Downgraded back to 0.28.12 but it still crashes :/

**Comment by giiilees** [comment] 2024-08-02 11:51
I saw in #28656 that expo-notifications 0.28.14 was just released 2 days ago 
So I think there's some kinda bug in there.

**Comment by douglowder** [comment] 2024-08-02 17:48
This is a dupe of #30738 -- fix is in the works.

**Closed by douglowder** 2024-08-02 17:48 UTC
Labels: needs review

**Comment by yellow-umbrella-studio** [comment] 2024-08-04 15:14
Is there an esitmate on when the fix will be done? Also, should i just update the expo-notifications library when the fix is ready? or is there another way? not sure how fixes are done
