### ISSUE TITLE
addNotificationResponseReceivedListener does not work when the application is fully closed

### ISSUE THREAD

**Issue by georgeMorales** [expo/expo#11340] opened 2020-12-14 09:07 UTC
## 🐛 Bug Report

The notification event handler addNotificationResponseReceivedListener does not work when the application is fully closed, if it works when it is in the background. Only tested on Android.

SDK 40

`responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
       console.log('response', response);        
}`
SOLVED ON ANDROID
Thanks to @maurohmartinez I have been able to solve it with the useLastNotificationResponse hook in Android but now I have tried in the expo client with the iPhone device and it does not work when it is completely closed

**Comment by maurohmartinez** [comment] 2020-12-14 09:38
I think SDK 40 fixed that issue for me on Android. Have a look at [9866](https://github.com/expo/expo/issues/9866).

**Comment by georgeMorales** [comment] 2020-12-14 09:58
@maurohmartinez  
Thank you, I see that it is a problem that many people have, but it has not been very clear to me how to fix it.
What do I have to use useLastNotificationResponse? or put addNotificationResponseReceivedListener in other component?
I am quite confused

**Comment by maurohmartinez** [comment] 2020-12-14 10:36
> @maurohmartinez
> Thank you, I see that it is a problem that many people have, but it has not been very clear to me how to fix it.
> What do I have to use useLastNotificationResponse? or put addNotificationResponseReceivedListener in other component?
> I am quite confused

As far as I understand, useLastNotificationResponse is a hook that lets you get the lastest user's interaction with a push notification (even if the app was killed). This has recently been introduced on SDK 40 and it works perfect on Android for me. This is the way I implemented based on the documentation:

```
export default function App() {
    const lastNotificationResponse = Notifications.useLastNotificationResponse();

    useEffect(() => {
            if (lastNotificationResponse && lastNotificationResponse.actionIdentifier === Notifications.DEFAULT_ACTION_IDENTIFIER) {
            handlePush(lastNotificationResponse);
        }
    }, [lastNotificationResponse]);

const handlePush = async ({ notification }) => {
        // ... you code  <<<-------------------------- do whatever with your push
    }
}
```

When it comes to iOS the `Notifications.addNotificationResponseReceivedListener` had been fixed on SDK 39, but now that I updated to SDK 40 it doesn't work anymore. I am confused as well, as you see.

I was planing on working based on platforms, loading the new `Notifications.useLastNotificationResponse` for Android and `Notifications.addNotificationResponseReceivedListener` only for iOS.

Does any of this help?

**Comment by georgeMorales** [comment] 2020-12-14 11:11
@maurohmartinez 
Yes, it has helped me a lot ... It works on android, but not on iOS.
It tells me that Notifications.useLastNotificationResponse works for android and Notifications.addNotificationResponseReceivedListener works for iOS in Expo sdk 40?
Thank you!

**Comment by maurohmartinez** [comment] 2020-12-14 11:16
@ georgeMorales
Yes, at least for me... BUT, `Notifications.addNotificationResponseReceivedListener` that worked on SDK 39 for iOS now it doesn't on SDK 40 :/

**Comment by georgeMorales** [comment] 2020-12-14 11:23
What a big mess, the previous Notifications API worked very well but I'm already on sdk 40.
For me it is a big problem because I need you to function this feature so that when the application is completely closed and the user interacts with the notification, it can be handled, in android and iOS.
I hope a solution soon.
Thank you very much @maurohmartinez

**Comment by maurohmartinez** [comment] 2020-12-14 11:24
> What a big mess, the previous Notifications API worked very well but I'm already on sdk 40.
> For me it is a big problem because I need you to function this feature so that when the application is completely closed and the user interacts with the notification, it can be handled, in android and iOS.
> I hope a solution soon.
> Thank you very much @maurohmartinez

Same here! And same for many people. So, let's hope it is finally fixed soon.

**Comment by cruzach** [comment] 2020-12-14 14:51
closing as a duplicate of https://github.com/expo/expo/issues/11343 (which provides more info)

As a workaround, you can use the [`useLastNotificationResponse` hook](https://docs.expo.io/versions/latest/sdk/notifications/#uselastnotificationresponse-undefined--notificationresponse--null)

**Closed by cruzach** 2020-12-14 14:51 UTC
Labels: Notifications, iOS, needs review
