### ISSUE TITLE
Android TextInput Crash SDK 28

### ISSUE THREAD

**Issue by SleeplessByte** [expo/expo#2137] opened 2018-08-24 01:10 UTC
### Environment
(exp diagnositcs crashes powershell)

### Steps to Reproduce

1. https://snack.expo.io/BJ2qw02UX (it works)
2. Run on Device (OnePlus 5)
3. Nothing

### Expected Behavior

The snack and device experience are equal.

### Actual Behavior

Fatal error
```
Uncaught Error: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.new Drawable(android..content.res.Resources)' on a null object reference
```

Note: it takes a while to get into this state. See the related thread. Once you're in this state you have to Clear the data from the Expo app in order to go back to something that is working.

### Reproducible Demo
https://snack.expo.io/BJ2qw02UX

### Related
This is probably an upstream issue:
https://github.com/facebook/react-native/issues/17530

**Comment by AGIsmail** [comment] 2019-02-07 17:36
Does anyone know of a workaround that doesn't involve ejecting?

**Comment by mikaelwecode** [comment] 2019-08-08 17:05
I have the same problem.  Is there any workaround? I don't want to eject to expi-cli to fix this.

**Comment by mikaelwecode** [comment] 2019-08-08 17:50
It does not crash when you build a standalone app.

**Comment by AGIsmail** [comment] 2019-08-08 21:51
@mikaelwecode Because the issue is upstream, I believe the only current fix is to eject and apply the patch manually.

**Comment by bouchezb** [comment] 2019-11-13 15:39
Hi everyone,

Facing this issue last night on expo v.33 with native-base text inputs, i finally performed a full upgrade of my expo platform to v.34 and then v.35, hoping it was a patched React Native issue.
This did not solved the issue.

Patching all styles.xml files i found in `./node_modules` for my project did not fixed it either.

But i noticed that @SleeplessByte suggested to
> Clear the data from the Expo app

So i deleted the Expo cache from my computer and also the Expo App from my phone.
Re Installing the Expo Mobile App and running a --clear build fixed my problem.

Hope this can help someone with this weird and annoying bug.

**Comment by tsapeta** [comment] 2020-07-11 18:18
Closing the issue as SDK28 is no longer supported and we didn't get similar issue reports referring to currently supported SDKs 🙂 Feel free to open a new issue if you're still encountering this.

**Closed by tsapeta** 2020-07-11 18:18 UTC
Labels: Android, project: react-native, project: upstream

**Comment by SleeplessByte** [comment] 2020-07-11 20:25
I've not seen this error, FWIW!

**Comment by EmmanuelSkapple** [comment] 2021-02-09 01:03
I have the same problem, SDK 40
