### ISSUE TITLE
Latest version causing crash: `exp init` & `npm i` causes an immediate crash `can't find variable: self`

### ISSUE THREAD

**Issue by jasekiw** [expo/expo#2197] opened 2018-09-12 13:54 UTC
### Environment

```
Environment:
  OS: Windows 10
  Node: 8.11.1
  Yarn: 0.21.3
  npm: 5.8.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4408382

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/jasekiw-e8fb1bed-a1bc-4dd1-9741-c061b24feacf.tar.gz
```

Target: `Android 6.0.1`

### Steps to Reproduce

Follow these steps or clone the reproduceable demo.

1. Setup the project
```
exp init test-project
cd test-project
npm install # this is required for the dependencies of expo to get updated to the latest version.
```
2. Open the app with XDE and you will get an error `can't find variable: self`.

### Expected Behavior

The app will run normally

### Actual Behavior
An error displays in the error window.

`can't find variable: self`

### Reproducible Demo

https://github.com/jasekiw/expo-fetch-issue

Follow the instructions in the readme.

**Comment by abn-volk** [comment] 2018-09-13 07:36
The workaround in #2193 seems to work for me.

**Comment by abn-volk** [comment] 2018-09-13 08:16
It seems like the problem is due to the new version of `whatwg-fetch` (see #2192, #2193). The solution in #2193 doesn't work for me. I use Yarn for package management, so I added this under `dependencies` to lock the library to an old version and it works.

```
"resolutions": {
  "whatwg-fetch": "2.0.4"
}
```

**Comment by devautor** [comment] 2018-09-13 09:58
@abn-volk I can't get it working; can you please share your steps in detail?

**Comment by tsapeta** [comment] 2018-09-13 14:50
Closing this issue as the correct solutions have already been posted here
https://github.com/expo/expo/issues/2197#issuecomment-420923111 and here https://github.com/expo/expo/issues/2192#issuecomment-420342527

**Comment by jasekiw** [comment] 2018-09-13 18:04
@tsapeta This is unacceptable solution as all of the new users coming to use this software will hit this error out of the box. That will greatly reduce their confidence in the software which will cause some to go else were. The product should work out of the box for `exp init` and `npm install` and the fact is it doesn't. So I would definitely not consider this resolved until a user can both run `exp init` and `npm install` and have a working scaffolded project.

This problem can easily be fixced by polyfilling the `self` variable. ex. `if(!global.self) global.self = global;`. This should be done on expo's side and not the user.

**Comment by tsapeta** [comment] 2018-09-14 14:01
@jasekiw Alright, we decided to fix this on our end. I've just published a new project templates that uses `expo@^30.0.1` which depends on `whatwg-fetch@^2.0.4` so the new project should not cause a crash with `Can't find variable: self`.

**Closed by tsapeta** 2018-09-14 14:01 UTC
