### ISSUE TITLE
JSC::linkPolymorphicCall(JSC::ExecState*, JSC::CallLinkInfo&, JSC::CallVariant)

### ISSUE THREAD

**Issue by kamalpandey** [expo/expo#9242] opened 2020-07-16 05:46 UTC
I am getting following issues in play store.

backtrace:
  #00  pc 00000000002aa114  /data/app/com.xyz.xyz_android-XXYfgipuar_WAkyDReo0Q==/lib/arm64/libjsc.so (JSC::linkPolymorphicCall(JSC::ExecState*, JSC::CallLinkInfo&, JSC::CallVariant)+6416)
  #01  pc 00000000002700c0  /data/app/com.xyz.xyz_android-XXYfgipuar_WAkyDReo0Q==/lib/arm64/libjsc.so (operationLinkPolymorphicCall+48)
  #02  pc 0000000000002ec0  <anonymous>

Sdk: 35
Android

How can is solve this?

**Comment by cruzach** [comment] 2020-07-16 13:42
Hi! Sorry, but there's not much we garner from the information you've provided 🙁 

If you think you're experiencing a bug in the Expo SDK, please fill out the entire bug report template including all the information we ask for in it, since this allows us to help you much more effectively! The most helpful thing you can provide is a reliable way of reproducing the bug, that way we can isolate and fix it

Closing this for now, but if you can provide what we ask for in the bug report template, I can re-open

**Closed by cruzach** 2020-07-16 13:42 UTC
