### ISSUE TITLE
"orientation: portrait" in app.json does not prevent orientation change on iPad- iOS 12.4

### ISSUE THREAD

**Issue by mymattcarroll** [expo/expo#5339] opened 2019-08-15 05:29 UTC
### Environment

```
  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.1 
```

### Steps to Reproduce

1. Create template expo app

```
npm i -g expo-cli@3.0.9
expo init (picking the tabs template)
```

`app.json`

```json
{
  "expo": {
    "name": "expo-template",
    "slug": "expo-template",
    "privacy": "public",
    "sdkVersion": "34.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  }
}
```

2. Start app in portrait orientation on iPad 5th Generation (WiFi) - iOS 12.4
3. Turn device to landscape orientation

### Expected Behavior

Screen should not change orientation

### Actual Behavior

Screen does change orientation

### Reproducible Demo

Sorry, please dont close this issue, but I can't work out a way to change the orientation of a snack. If it is possible, please let me know how and I will make one ASAP. :)

**Comment by mymattcarroll** [comment] 2019-08-15 05:50
### Update

This is only an issue in the expo client. After building the app and installing the `.ipa` file on the same iPad, the orientation is locked to portrait.

**Comment by cruzach** [comment] 2019-08-15 15:11
```
await ScreenOrientation.lockAsync(
    ScreenOrientation.OrientationLock.LANDSCAPE_LEFT
  );
```
also doesn't lock the orientation on iPads (does work on iPhone, as does the app.json `orientation` key)

**Comment by MehmetKaplan** [comment] 2019-08-27 13:53
Same problematic behaviour with portrait lock:
`
	async componentWillMount(){
		await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT);
	}
`
[Issue 68](https://github.com/expo/expo/issues/68) seems related but somehow same problem seems reoccured.

to reproduce the behaviou, snack is here:
https://snack.expo.io/@mehmetkaplan/ec9bab

When you run from iphones the screen is correctly locked but when you run from ipads, it is not correctly locked.

**Comment by MehmetKaplan** [comment] 2019-08-29 12:54
One more update, above code works correct with iPhone 6s but behaves like iPads in iPhone XS max.

This makes me think that expo application tries to get screen sizes and behaves differently according to those. (Just a dummy guess).

**Comment by lukmccall** [comment] 2020-02-26 13:47
Hi everyone. This was fixed by this PR. Unfortunately, it won't work out of the box. You need to add the additional configuration for iPads (the documentation will be updated by this PR).

This fix will be available in SDK 37.

For now, I'm closing this issue. Feel free to repone it if this bug will occur in the newest SDK.

**Closed by lukmccall** 2020-02-26 13:47 UTC
Labels: Client, ScreenOrientation, bug, project: ios-runtime

**Comment by DanJamesH** [comment] 2021-03-23 16:06
This bug is still present on SDK 40

**Comment by georgeMorales** [comment] 2021-06-10 11:19
sdk 41 on android too

**Comment by markvolkov** [comment] 2021-07-25 21:58
Has this been fixed?

**Comment by stdavis** [comment] 2021-08-19 20:31
I'm seeing this in v42. Was it really fixed?

**Comment by undeaDD** [comment] 2022-05-13 12:26
still not fixed in v45 :(

**Comment by apedroferreira** [comment] 2022-11-09 01:45
Looks like there's a special orientation property for iPad that Expo isn't setting. 
You can use plugins to set this property in the Info.plist file for iOS, try this if you're using EAS:

Create a `withCustomInfoPlist.js` file with something like this code (in this case it enables the "portrait" orientation only):
```
const { withInfoPlist } = require('@expo/config-plugins')

module.exports = config =>
  withInfoPlist(config, config => {
    // Only enable portrait orientation in iPad
    config.modResults['UISupportedInterfaceOrientations~ipad'] = ['UIInterfaceOrientationPortrait']

    return config
  })
```

Use the path to this custom plugin in your `app.json` or `app.config.js` like:
```
plugins: [
    ...otherPlugins,
    ['./plugins/withCustomInfoPlist'],
  ],
```

Create a new build and at least for the me the issue was fixed.

**Comment by SimeonShulhin** [comment] 2023-08-02 09:42
> Looks like there's a special orientation property for iPad (`UISupportedInterfaceOrientations~ipad`) that Expo isn't setting. You can use plugins to set this property in the Info.plist file for iOS, try this if you're using EAS (managed flow):
> 
> Create a `withCustomInfoPlist.js` file with something like this code (in this case it enables the "portrait" orientation only):
> 
> ```
> const { withInfoPlist } = require('@expo/config-plugins')
> 
> module.exports = config =>
>   withInfoPlist(config, config => {
>     // Only enable portrait orientation in iPad
>     config.modResults['UISupportedInterfaceOrientations~ipad'] = ['UIInterfaceOrientationPortrait']
> 
>     return config
>   })
> ```
> 
> Use the path to this custom plugin in your `app.json` or `app.config.js` like:
> 
> ```
> plugins: [
>     ...otherPlugins,
>     ['./plugins/withCustomInfoPlist'],
>   ],
> ```
> 
> Create a new build and at least for me the issue was fixed.

Not working for me(

**Comment by AdamGerthel** [comment] 2023-10-04 20:03
Does not seem to be working. I'm on SDK 49 and `orientation: 'portrait'` leads to this result:

<img width="277" alt="Screenshot 2023-10-04 at 22 02 24" src="https://github.com/expo/expo/assets/1490370/d8e760b4-a14e-46f7-982d-282bff974eab">

**Comment by ridwansameer** [comment] 2024-01-23 13:04
@AdamGerthel Do you happen to know how we could set different Orientation for different devices? Ex: Landscape for iPad and Portrait for mobile

**Comment by AdamGerthel** [comment] 2024-01-23 13:07
> @AdamGerthel Do you happen to know how we could set different Orientation for different devices? Ex: Landscape for iPad and Portrait for mobile

As long as `ios.requireFullScreen` is false, you should be able to use `infoPlist` to set the values you want.
