### ISSUE TITLE
[expo-router] Stack group pages ignore screenOptions animation with Slot component in group layout

### ISSUE THREAD

**Issue by danieljimeneznz** [expo/expo#24867] opened 2023-10-14 05:12 UTC
### Minimal reproducible example

https://github.com/danieljimeneznz/expo-router-stack-animations

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When creating pages within a group `(public)` that utilize the `Slot` component, and setting up a top-level application layout with animated stacks, the presence of the `Slot` component disrupts the animations between pages within the same group. 

This issue can be replicated in a project generated using `npx create-expo-app@latest --template tabs@49`, with minimal modifications applied in this [commit](https://github.com/danieljimeneznz/expo-router-stack-animations/commit/135a716c9f766fe532c26be488540eae9d92006b).

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Linux Mint 21.2 (Victoria)
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.18.1 - ~/.nvm/versions/node/v18.18.1/bin/node
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.1/bin/npm
    SDKs:
      Android SDK:
        API Levels: 33, 33
        Build Tools: 30.0.3, 33.0.0, 33.0.2
        System Images: android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-231.9392.1.2311.10680768
    npmPackages:
      expo: ~49.0.13 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
      react-native-web: ~0.19.6 => 0.19.9 
    Expo Workflow: managed
```

**Comment by myle-sens** [comment] 2023-11-16 06:45
I'm facing the same problem. When checking *Logcat* in Android Studio, the screen frame rate drops by around 30-60 FPS during each screen navigation.

**Comment by FlavioScimeca** [comment] 2023-12-27 11:26
same , any updates ?

**Comment by kishieel** [comment] 2024-01-14 22:27
+1

**Comment by marklawlor** [comment] 2024-02-23 03:10
I'm going to close this issue as "working as intended", but I'm interested to people's thoughts on the subject and I'm going to think about possible improvements.

All `_layout` files are Navigators, including the `<Slot />` component. You can think of it a navigator with no visual appearance. But it still set a `<NavigationContext />`

So when you load the app and you traverse from `/` to `/one`, it display the stack animation because the `<Stack />` navigator is changing. From then onwards, moving between `/one` / `/two` is not changing the `<Stack />` navigator. Its changing the `children` prop of the `<Slot />` navigator.

This is how generally you'd expect a `<Slot />` navigator to function, but I can understand why its frustrating in this instance. I'm going to think about better ways we can implement this pattern.

For the time being, you can either use a nested `<Stack />` or have your layout as a component, and not a `_layout` file.

**Closed by marklawlor** 2024-02-23 03:10 UTC
Labels: needs review, Router

**Comment by danieljimeneznz** [comment] 2024-02-28 23:53
> I'm going to close this issue as "working as intended", but I'm interested to people's thoughts on the subject and I'm going to think about possible improvements.
> 
> All `_layout` files are Navigators, including the `<Slot />` component. You can think of it a navigator with no visual appearance. But it still set a `<NavigationContext />`
> 
> So when you load the app and you traverse from `/` to `/one`, it display the stack animation because the `<Stack />` navigator is changing. From then onwards, moving between `/one` / `/two` is not changing the `<Stack />` navigator. Its changing the `children` prop of the `<Slot />` navigator.
> 
> This is how generally you'd expect a `<Slot />` navigator to function, but I can understand why its frustrating in this instance. I'm going to think about better ways we can implement this pattern.
> 
> For the time being, you can either use a nested `<Stack />` or have your layout as a component, and not a `_layout` file.

Yeah I guess that's a fair call - I think initially my problem was that we were layering a background behind the slot so that the user could navigate between pages without us having to redefine the background, at the time I couldn't get this working but after some research I've found that utilizing the `<ThemeProvider` with transparent colors works how I want it to.
