### ISSUE TITLE
Branch.io integration in expo managed workflow

### ISSUE THREAD

**Issue by Winnie16** [expo/expo#9471] opened 2020-07-29 11:48 UTC
### Summary of Issue 
I am using expo SDK version 36. In my code Branch.subscribe() is not getting triggered on Android Emulator.  When I run the app via expo client, I get this error : null is not an object (evaluating RNBranch.STANDARD_EVENT_ADD_TO_CART. When I try running it as standalone app,it crashes
Could anybody help me with correct procedure to integrate branch?
### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo SDK 36.0.0
Android Emulator

**Comment by cruzach** [comment] 2020-07-30 17:12
duplicate of https://github.com/expo/expo/issues/5349

Refer to this comment to solve the issue- https://github.com/expo/expo/issues/5349#issuecomment-567633221. Branch is only available in standalone APKs, not the Android Expo client app  (this is mentioned in the docs)

**Closed by cruzach** 2020-07-30 17:12 UTC
Labels: Issue needs review

**Comment by Winnie16** [comment] 2020-07-30 19:50
I have gone through that comment. Could you please elaborate on function emulation in code snippet provided in the above comment? @cruzach

**Comment by cruzach** [comment] 2020-07-30 19:56
You can only use Branch in standalone apps, so you check `Constants.appOwnership`

**Comment by SirPhemmiey** [comment] 2021-02-16 06:36
Bro @cruzach , even in standalone, it's crashing!
