### ISSUE TITLE
Build Failed in new app created with react-native init

### ISSUE THREAD

**Issue by firofame** [expo/expo#15821] opened 2022-01-06 16:22 UTC
### Summary

```

✔ Installed pods and initialized Xcode workspace.
› Planning build
› Compiling react-native Pods/RCT-Folly » FileUtil.cpp
› Compiling react-native Pods/FlipperKit » FBCxxFollyDynamicConvert.mm

❌  (node_modules/expo-modules-core/ios/Swift/Views/ConcreteViewProp.swift:42:55)

  40 |     }
  41 |     guard let value = try propType.cast(value) as? PropType else {
> 42 |       throw Conversions.CastingError<PropType>(value: value)
     |                                                       ^ variable declared in 'guard' condition is not usable in its body
  43 |     }
  44 |     setter(view, value)
  45 |   }


❌  (node_modules/expo-modules-core/ios/Swift/Arguments/Types/EnumArgumentType.swift:46:58)

  44 |   static func create<ArgType>(fromRawValue rawValue: ArgType) throws -> Self {
  45 |     guard let rawValue = rawValue as? RawValue else {
> 46 |       throw EnumCastingError(type: RawValue.self, value: rawValue)
     |                                                          ^ variable declared in 'guard' condition is not usable in its body
  47 |     }
  48 |     guard let enumCase = Self.init(rawValue: rawValue) else {
  49 |       throw EnumNoSuchValueError(type: Self.self, value: rawValue)


❌  (node_modules/expo-modules-core/ios/Swift/Modules/ModuleDefinitionComponents.swift:212:27)

  210 |    Creates the view manager definition that scopes other view-related definitions.
  211 |    */
> 212 |   public func viewManager(@ViewManagerDefinitionBuilder _ closure: @escaping () -> ViewManagerDefinition) -> AnyDefinition {
      |                           ^ unknown attribute 'ViewManagerDefinitionBuilder'
  213 |     return closure()
  214 |   }
  215 | 

› Compiling react-native Pods/FlipperKit » SKViewDescriptor.mm
› Compiling react-native Pods/FlipperKit » SKSwizzle.mm
› Compiling react-native Pods/FlipperKit » SKViewControllerDescriptor.m
› Compiling react-native Pods/FlipperKit » SKTouch.m
› Compiling react-native Pods/FlipperKit » SKTapListenerImpl.m
› Compiling react-native Pods/FlipperKit » SKStateUpdateCPPWrapper.mm
› Compiling react-native Pods/RCT-Folly » SysUio.cpp
› Compiling react-native Pods/RCT-Folly » NetOps.cpp
› Compiling react-native Pods/FlipperKit » SKSearchResultNode.m
› Compiling react-native Pods/FlipperKit » SKScrollViewDescriptor.m

› 3 error(s), and 0 warning(s)

Failed to build iOS project. "xcodebuild" exited with error code 65.

```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.0.1 - /opt/homebrew/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.1.0 - /opt/homebrew/bin/npm
      Watchman: 2021.11.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.4 => 44.0.4 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.4 => 0.66.4 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

$ npx react-native init MyApp
$ cd MyApp
$ npx install-expo-modules
$ npx pod-install
$ yarn ios

**Comment by tsapeta** [comment] 2022-01-06 18:16
Looks like you use the old version of Xcode (12.4) whereas 13.2.1 is already available. Could you try after updating it?

Also it's a duplicate of https://github.com/expo/expo/issues/14948 so I'm closing this one, but if updating Xcode doesn't help then let me know and I'll reopen it 😉

**Closed by tsapeta** 2022-01-06 18:16 UTC
Labels: needs review

**Comment by firofame** [comment] 2022-01-07 01:03
@tsapeta I'm stuck with Xcode 12.4 due to some dependencies. My project is on react native  version 0.61.1. Do I have any other options to install expo modules?

**Comment by vitorpereiira** [comment] 2022-03-19 20:57
alguma solução para isso ?
