### ISSUE TITLE
error: cannot find symbol BasePackageList when compiling MainApplication.java

### ISSUE THREAD

**Issue by yanickrochon** [expo/expo#7373] opened 2020-03-16 15:17 UTC
### Environment

```
  Expo CLI 3.13.8 environment info:
    System:
      OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
      Yarn: 1.19.1 - ~/.nvm/versions/node/v12.10.0/bin/yarn
      npm: 6.13.7 - ~/.nvm/versions/node/v12.10.0/bin/npm
    npmPackages:
      react: 16.9.0 => 16.9.0 
      react-native: 0.61.5 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.13.8
```

Application target: Android

### Steps to Reproduce

Brand new project, `react-native` and all, I followed the steps to install the `expo-keep-awake` package.

### Expected Behavior

The application should compile.

### Actual Behavior

The compilation fails with 

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
253 actionable tasks: 220 executed, 33 up-to-date
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /home/...path_to_project.../node_modules/expo-app-loader-provider/android/src/main/java/expo/loaders/provider/AppLoaderProvider.java uses unchecked or uns
afe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /home/...path_to_project.../node_modules/expo-constants/android/src/main/java/expo/modules/constants/ConstantsService.java uses or overrides a deprecated 
API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/...path_to_project.../node_modules/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java uses unchecked or unsafe ope
rations.
Note: Recompile with -Xlint:unchecked for details.
Note: /home/...path_to_project.../node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/services/UIManagerModuleWrap
per.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/home/...path_to_project.../android/app/src/main/java/com/statscan/MainApplication.java:4: error: package com.doingmything.generated does not exist
import com.doingmything.generated.BasePackageList;
                                 ^
/home/...path_to_project.../android/app/src/main/java/com/statscan/MainApplication.java:24: error: cannot find symbol
  private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(new BasePackageList().getPackageList(), Arrays.<SingletonModule>asList());
                                                                                                          ^
  symbol:   class BasePackageList
  location: class MainApplication
2 errors

FAILURE: Build failed with an exception.
```

#### `android/settings.gradle`

```
...
apply from: '../node_modules/react-native-unimodules/gradle.groovy'
includeUnimodulesProjects()
```

#### `android/app/build.gradle`

```
...
apply from: '../../node_modules/react-native-unimodules/gradle.groovy'
...
dependencies {
   ...
   addUnimodulesDependencies()
}
...
```

#### `android/build.gradle`

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        ...
   }
}
```

#### `android/app/src/main/java/com/statscan/MainApplication.java` file is

```java
package com.statscan;

// "com.doingmything" should be your app package name
import com.doingmything.generated.BasePackageList;

import android.app.Application;
import android.content.Context;

import org.unimodules.adapters.react.ModuleRegistryAdapter;
import org.unimodules.adapters.react.ReactModuleRegistryProvider;
import org.unimodules.core.interfaces.SingletonModule;

import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import java.lang.reflect.InvocationTargetException;
import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(new BasePackageList().getPackageList(), Arrays.<SingletonModule>asList());

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());

          // Add unimodules
          List<ReactPackage> unimodules = Arrays.<ReactPackage>asList(
            new ModuleRegistryAdapter(mModuleRegistryProvider)
          );
          packages.addAll(unimodules);

          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
      };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this); // Remove this line if you don't want Flipper enabled
  }

  /**
   * Loads Flipper in React Native templates.
   *
   * @param context
   */
  private static void initializeFlipper(Context context) {
    if (BuildConfig.DEBUG) {
      try {
        /*
         We use reflection here to pick up the class that initializes Flipper,
        since Flipper library is not available in release mode
        */
        Class<?> aClass = Class.forName("com.facebook.flipper.ReactNativeFlipper");
        aClass.getMethod("initializeFlipper", Context.class).invoke(null, context);
      } catch (ClassNotFoundException e) {
        e.printStackTrace();
      } catch (NoSuchMethodException e) {
        e.printStackTrace();
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      } catch (InvocationTargetException e) {
        e.printStackTrace();
      }
    }
  }
}
```

**Comment by cruzach** [comment] 2020-03-16 19:15
Hi! I just tested this on an `expo init -t bare-minimum` project, after `expo install expo-keep-awake`, and it compiled successfully. If you aren't using `expo-cli` to initialize your bare project, then make sure you've configured `react-native-unimodules` correctly

**Comment by yanickrochon** [comment] 2020-03-16 19:27
Hi! Well then I have no idea how I can reproduce this without copying this copyrighted project. Bummer. Will try to reset the project and re-install if something changes...

**Comment by aalbaharnah** [comment] 2020-06-02 04:14
you need to change  `import **com.doingmything**.generated.BasePackageList;`
"com.doingmything" should be your app package name.
in your case in particular it's com.statscan

**Comment by dipeshkoirala21** [comment] 2020-10-19 12:05
change your import com.doingmything.generated.BasePackageList; in MainApplication.java to com.statscan.generated.BasePackageList;

**Comment by cruzach** [comment] 2020-10-19 13:41
Closing this since there's no reproducible demo- if you're having this problem please try the solutions shared above and if that doesn't help open a new issue with a reproducible demo, thanks!

**Closed by cruzach** 2020-10-19 13:41 UTC
Labels: Android, Bare Workflow, bug, needs repro
