### ISSUE TITLE
Animations preventing the entire page from being pre-rendered to static html with "output": "static"

### ISSUE THREAD

**Issue by guiopen** [expo/expo#31409] opened 2024-09-11 03:46 UTC
### Minimal reproducible example

https://github.com/guiopen/expo-static-issue

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Expected behaviour:

The index.html (or any other page) during a static npx expo export --platform web should be prerendered with content like  text and links for better seo

Actual behaviour:

If there is an animated component inside the page, it prevents the entirecontent of page from being prerendered. In the example build created with npx create-expo-app@latest, the component HelloWave in the index.jsx prevents the html from being pre-rendered with actual content, even if most of the content is pure text like "When you're ready, run". Even if the animated component cant be rendered without javascript running in the client, it shouldnt prevent the rest of the page from being pre-rendered. If we remove the HelloWave from index.jsx, then the pre-rendered page is filled with content as expected. 

Images displaying the result:
![Captura de tela de 2024-09-11 00-38-00](https://github.com/user-attachments/assets/4cc2c832-280d-41e3-a4c7-5a6876dfd073)
![Captura de tela de 2024-09-11 00-38-42](https://github.com/user-attachments/assets/116d5608-0abf-449b-8bff-ea9e2c9379f0)

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.8 Linux Mint 22 (Wilma)
      Shell: 5.2.21 - /bin/bash
    Binaries:
      Node: 18.19.1 - /usr/bin/node
      npm: 9.2.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    npmPackages:
      expo: ~51.0.28 => 51.0.32 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: bare

**Comment by marklawlor** [comment] 2024-09-17 08:44
I'm unable to reproduce your issue.

Steps taken:

- Clone repo
- cd `teste1`
- `npm install`
- `npx expo export --platform web`
- cd `dist`
- `npx serve`
- Open `http://localhost:300`. Observe website appears correct. Animation runs as expected
- Remove lines as specified.
- Rebuild project and open again. Obverse website still appears correct.

I'm going to close this issue as I cannot reproduce the problem. If your able to provide more instructions you can respond to this issue.

**Closed by marklawlor** 2024-09-17 08:44 UTC
Labels: needs review, Router

**Comment by guiopen** [comment] 2024-09-17 11:23
Hello @marklawlor, the test should be done by opening the html file directly, not by accessing the localhost address. One step i forgot to mention is, to build the website statically, the web output in the app.json should be changed from single to static. The problem is not the animation not being present (that is expected as we are opening only the .html file), but the animated component preventing the entire page from being pre-rendered when it should prevent only itself, harming SEO and user experience on slow connections.
