### ISSUE TITLE
Auto-layout/Orientation/split-screen does not work for iOS in expo 43 production builds

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo#14967] opened 2021-10-30 02:36 UTC
### Summary

We recently updated out app to expo 43 from expo 42. In dev everything looked good, so we did a build and submitted to Apple. Once the build was approved we found that the iPad app no longer resized correctly when rotating the iPad (the app seemed to keep the same dimensions and a gray area was added to the empty area. We found this to be turn when using split screen and when having our app float to the side. We're not sure how to debug because the issue does not preset at all in dev on device or in the simulator. It also isn't reproducible in a snack as far as we can tell.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS (both iPhone and iPad)

### SDK Version (managed workflow only)

43

### Environment

production app on iOS

### Reproducible demo or steps to reproduce from a blank project

Just create a blank project and submit to TestFlight or the App Store. Here is what I used:

https://github.com/tiltshift/expo43ipad

**Comment by nbjorling** [comment] 2021-11-02 07:54
Have you had a look at the updated docs for Orientation: https://docs.expo.dev/versions/latest/sdk/screen-orientation/

There is a **Warning** header there explaining your problem I believe.  Try using this flag and see if that fixes the problem: 

`{
  "expo": {
    ...
    "ios": {
      ...
      "requireFullScreen": true,
    }
  }
}`

**Comment by chrisdrackett** [comment] 2021-11-02 15:42
We do not want to require full screen. Our app in question is designed to work at multiple sizes both on iPad and Mac (M1). In expo 42 this works fine, but in expo 43 the app never resizes when the iPad orientation changes.

There is a strong possibility as well that this is also an issue with `requireFullScreen` set to `true` as in the test app you can see that changing from landscape to portrait will not work correctly and a good portion of the app will be completely cut off and unusable.

**Comment by jkk** [comment] 2021-11-02 17:02
We're seeing this too, with `requireFullScreen` set to `true`, using an ad-hoc production build. Does not happen in dev-client.

**Comment by trevsmit** [comment] 2021-11-03 02:27
We too have seen this issue in an ad hoc build.  As it does not occur in Android I wonder if it is caused by the different ways ios and android report screen dimensions?  Android reports the dimensions for the current orientation, iOS always reports dimensions for portrait mode.  Maybe this is no longer being handled?

**Comment by nbjorling** [comment] 2021-11-03 08:25
Ok, then it seems to be the same issue as we are having with our mobile-app. We see the same problem on iOS production builds only. dev-client works fine, aswell as android in both dev and prod. I have also made an issue for that one: https://github.com/expo/expo/issues/15000

**Comment by chrisdrackett** [comment] 2021-11-03 21:24
I can update this to cover the iPhone as well, I'm sure its the same issue!

**Comment by jaaberg** [comment] 2021-11-03 21:45
We also experience this. I've discovered that the app actually resizes correctly if I have an active modal open (from `react-native`-package), but everywhere else the same thing happens, screen gets cut off.

**Comment by nbjorling** [comment] 2021-11-04 14:54
We have downgraded our app to run SDK 42 again and now it works fine again. We will do our production builds from this SDK until this is resolved.

**Comment by sjusaitis** [comment] 2021-11-08 06:48
I also experienced this in my newly updated SDK 43 iPhone project.

#15085 is related. And can confirm that screen rotation again works as expected when setting `EXUpdatesAutoSetup` to `false` in Expo.plist.

**Comment by Kudo** [comment] 2021-11-12 04:27
hi there! we've published `expo-updates@0.10.15` with #15100 fix. this issue should be fixed then. please try to upgrade expo-updates and let us know if it works for you. i am sorry to introduce this issue.

**Closed by Kudo** 2021-11-12 04:27 UTC
Labels: iOS, needs review

**Comment by cheeaun** [comment] 2021-11-12 09:32
🙏 Thanks! confirmed fixed on my [project](https://github.com/cheeaun/hackerweb-native-2) - had to make a new build instead of publish as updates.

**Comment by Braden1996** [comment] 2021-11-19 16:21
It seems the `expo prebuild` command automatically downgrades `expo-updates` from `0.10.15` to `0.10.13`. Passing in the argument `--skip-dependency-update expo-updates` circumvents this. Unfortunately, however, this isn't possible on EAS Build as the pre-build step isn't accessible (AFAIK). The `yarn.lock` immutability causes the build to fail - which is good in this case.

Is there a way to utilise this version (i.e. `0.10.15`) via EAS Build? @cheeaun did you happen to run into this?

**Comment by cheeaun** [comment] 2021-11-20 03:40
@Braden1996 I don't seem to have this issue. Mine is a Managed workflow, using `npm` instead of `yarn` and the command used to build is `eas build -p ios --profile=preview --non-interactive --auto-submit`
