### ISSUE TITLE
SDK37: __fbBatchedBridgeConfig is not set, cannot invoke native modules

### ISSUE THREAD

**Issue by jjg77** [expo/expo#7677] opened 2020-04-06 02:38 UTC
### Environment

  Expo CLI 3.17.15 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.4 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-navigation: 3.9.2 => 3.9.2 
    npmGlobalPackages:
      expo-cli: 3.17.15

### Steps to Reproduce

Upgraded from SDK36 to SDK37.  Only thing I changed was react-native-web@11.0.7 due to the need for asynstorage.

### Warnings

 web  Compiled with warnings.
/Users/xxxx/Sites/xxxx/node_modules/expo/build/Expo.js
Attempted import error: 'ScreenOrientation' is not exported from './removed'.

/Users/xxx/Sites/xxx/node_modules/expo/build/logs/LogSerialization.js
Attempted import error: 'react-native/Libraries/Core/Devtools/symbolicateStackTrace' does not contain a default export (imported as 'symbolicateStackTrace').

/Users/xxxx/Sites/xxxx/node_modules/react-native/Libraries/Performance/Systrace.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### Errors

__fbBatchedBridgeConfig is not set, cannot invoke native modules
▶ 3 stack frames were collapsed.
__webpack_require__
/Users/xxxx/Sites/xxxx/webpack/bootstrap:726
  723 | };
  724 | 
  725 | // Execute the module function
> 726 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  727 | 
  728 | // Flag the module as loaded
  729 | module.l = true;

**Comment by theeko** [comment] 2020-04-06 17:05
I am getting this error too,
i tried uninstalling and installing expo-cli (npm and yarn uninstall and installing it again),
now master gets these errors too which means it is related to cli.
Sometimes it works, sometimes i am getting just the first error about ScreenOrientation, sometimes all 3 and `__fbBatchedBridgeConfig is not set, cannot invoke native modules` error

**Comment by cruzach** [comment] 2020-04-06 20:52
Hey I just tested this on a blank SDK 37 web project and didn't hit this or any other error. Could you provide a repro?

**Comment by chanonroy** [comment] 2020-04-06 21:27
Getting a similar issue after scaffolding a project with expo-cli version `3.16.1`. 

<img width="939" alt="Screenshot 2020-04-06 at 10 25 53 pm" src="https://user-images.githubusercontent.com/16366896/78606730-b3a96d80-7855-11ea-87d5-6fb02be6ffe8.png">

Going to bump the global expo-cli and see if it resolves it. Happened with [this](https://github.com/chanonroy/expo-module-test) project just now.

**Comment by brentvatne** [comment] 2020-04-06 21:31
indeed you should update to the latest expo-cli to resolve the issue :)

**Comment by brentvatne** [comment] 2020-04-06 21:32
closing this issue because the fix is to update to the latest expo-cli. if you are using expo-cli@3.17.17 or greater and you run into an error that looks like the one described in this thread then please create a new issue and fill out the template! thanks!

**Closed by brentvatne** 2020-04-06 21:32 UTC
Labels: Platform: web, needs repro

**Comment by Vn-ChemGio** [comment] 2020-05-31 01:24
I found that error in expo-cli 3.20.3 @brentvatne

**Comment by brentvatne** [comment] 2020-05-31 01:41
3.21.3 is latest.

this error usually means that something in your project is breaking webpack and it's not using the proper alias for react-native-web. you might want to go back to your last working version of your app and then add things back slowly until you find what package or code is causing problems

**Comment by kwoxer** [comment] 2020-06-04 07:01
Adding `"expo-cli": "~3.21.3"` did NOT help me.

Error still remains. 

So I have now these both. Maybe you have an idea about what's my issue? The error was not existing yesterday. Just cam this morning without changing any line of code.


```
    "expo": "~37.0.12",
    "expo-cli": "~3.21.3",
```

**Comment by brentvatne** [comment] 2020-06-04 07:04
why did you install that in the project? install it globally

**Comment by brentvatne** [comment] 2020-06-04 07:05
and yes you’re right i have no idea because it could be any number of things. this is why we ask for reproducible examples, so please go create a new issue and follow the template and provide a reproducible example as it requests :) we would be very happy to help if so

**Comment by brentvatne** [comment] 2020-06-04 07:07
locked because it’s not useful to continue posting on closed issues. users encountering a similar symptom should create a new issue and follow the issue template
