### ISSUE TITLE
Expo Crypto's randomUUID function sometimes returns promises

### ISSUE THREAD

**Issue by Braden1996** [expo/expo#24021] opened 2023-08-18 14:25 UTC
### Minimal reproducible example

N/A

### Summary

We've had an illusive issue in our production mobile app for the past few months: the problem was hard to describe as there were a multitude of things not working in bizarrely unexpected ways.

After a pretty extensive campaign of debugging efforts, we discovered that calls to [`uuid`'s `v4()` function](https://github.com/uuidjs/uuid/blob/main/src/v4.js#L6-L8) would return a Promise Object, which would resolve to a UUID, rather than the underlying `string`. Part of what made this incredibly hard to discover was that Sentry uses `uuid`s internally; so it was effectively broken.

At a guess, this issue only seems to occur 1/50 times after a user updates the native binary of their app. Once they enter this "corrupt boot" situation, a simple restart of the app would resolve the issue. We've not been able to reproduce the issue deterministically despite a ton of efforts.

I was wondering if anybody has any insight on how this could be possible? Shouldn't the [Expo Modules API](https://docs.expo.dev/modules/module-api/#function) always resolve synchronously? Maybe there could be something wrong with our project configuration? Any intuition as to what we should look at?

Screenshot of what our logging was able to capture:
![image](https://github.com/expo/expo/assets/5165963/92c4fb85-35e1-4f5c-9792-5a3986e0ce96)
- Looks like this: https://stackoverflow.com/questions/57410321/async-await-function-returning-40-0-65-0-55-null-72-null
- Note: some of our log dumps were failing because `JSON.stringify` throws when you give it an unresolved promise (but works once resolved).

We polyfill the global object like this:
![CleanShot 2023-08-18 at 15 21 05](https://github.com/expo/expo/assets/5165963/9ae0269a-624e-4944-af94-f6b4bece5d57)

Other bits:
- React Native's polyfillGlobal: https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Utilities/PolyfillFunctions.js
- We didn't use [expo-standard-web-crypto](https://github.com/expo/expo/tree/main/packages/expo-standard-web-crypto) as it doesn't seem to provide `randomUUID` - why is this?

Relevant package versions:
- `expo-crypto`: `~12.4.1`
- `expo`: `~49.0.5`
- `uuid`: `^9.0.0`
- `expo-updates`: `~0.18.11`

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 3.4.1 - ~/.nvm/versions/node/v16.15.1/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2023.05.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 30, 31, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by gustavoharff** [comment] 2023-08-18 14:55
Had the same issue while upgrading to Expo 48.

- `expo`: 48.0.20
- `expo-crypto`: 12.2.1

It is very difficult to reproduce, and when it happens, just restarting the application to get it working again.

**Comment by brentvatne** [comment] 2023-08-18 21:31
are you observing this on iOS or Android?

**Comment by Braden1996** [comment] 2023-08-18 21:38
> are you observing this on iOS or Android?

Hey Brent!
This has only ever occurred on iOS for us (our analytics suggest it's happened hundreds of times; so this doesn't seem to be an issue at all on Android).

**Comment by aleqsio** [comment] 2023-08-21 10:35
I'll also try to reproduce this – it's the only closure in the module, so perhaps this has something to do with it?

**Comment by Braden1996** [comment] 2023-08-29 10:27
Minor update: a week ago we switched from using `expo-crypto` to `react-native-get-random-values` and have had **no** more occurrences of this issue (we've also rolled out a few native updates, to try mimic the conditions as much as possible).

**Comment by scd8418** [comment] 2023-12-14 15:21
This problem just occurred for me and I've been able to reproduce it and trace it using the debugger. The call always returns a promise. I can't tell what's going on in proxy code I'm tracing into, but it ends up here:

[NativeModulesProxy.native.js]
NativeProxy[exportedMethodsKey][moduleName].forEach((methodInfo) => {
            NativeModulesProxy[moduleName][methodInfo.name] = (...args) => {
                // Use the new proxy to call methods on legacy modules, if possible.
                if (ExpoNativeProxy?.callMethod) {
                    return ExpoNativeProxy.callMethod(moduleName, methodInfo.name, args);
                }
                // Otherwise fall back to the legacy proxy.
                // This is deprecated and might be removed in SDK47 or later.
                const { key, argumentsCount } = methodInfo;
                if (argumentsCount !== args.length) {
                    return Promise.reject(new Error(`Native method ${moduleName}.${methodInfo.name} expects ${argumentsCount} ${argumentsCount === 1 ? 'argument' : 'arguments'} but received ${args.length}`));
                }
                return LegacyNativeProxy.callMethod(moduleName, key, args);
            };
        });
        
       this calls LegacyNativeProxy.callMethod which ends up here with a "type" of "promise" (which seems wrong).
       
[NativeModules.js]
       function genMethod(moduleID: number, methodID: number, type: MethodType) {
  let fn = null;
  if (type === 'promise') {
    fn = function promiseMethodWrapper(...args: Array<mixed>) {
      // In case we reject, capture a useful stack trace here.
      /* $FlowFixMe[class-object-subtyping] added when improving typing for
       * this parameters */
      const enqueueingFrameError: ExtendedError = new Error();
      return new Promise((resolve, reject) => {
        BatchedBridge.enqueueNativeCall(
          moduleID,
          methodID,
          args,
          data => resolve(data),
          errorData =>
            reject(
              updateErrorWithErrorData(
                (errorData: $FlowFixMe),
                enqueueingFrameError,
              ),
            ),
        );
        

        It seems like the JS wrappers for the native code has decided that the return value is a promise (for whatever reason. I don't know if this helps, but thought I'd pass it along.

**Comment by skdrew** [comment] 2024-03-08 15:14
Thought I'd add an extra comment here - this issue was causing our production app to have a serious error that has resulted in a large number of negative reviews on the app store. In order to work around it we've replaced expo-crypto with react-native-get-random-values and uuid.

This issue is _not_ resolved. It should be re-opened until it's been confirmed to be fixed.

**Comment by martinezleoml** [comment] 2024-03-18 10:57
Hi there,
We're facing the same issue (on iOS only) with expo-crypto v12.8.1, Expo SDK 50.

**Comment by tsapeta** [comment] 2024-03-18 11:06
Could someone provide a simple repro to help me narrow down the issue?

**Comment by martinezleoml** [comment] 2024-03-18 11:10
Indeed the behaviour is random and pretty rare, but I'm using the following code to get an UUID:

```typescript
import * as Crypto from 'expo-crypto';

export const generateUuid = (): string => Crypto.randomUUID();
```

Sometime I get an promise (on iOS only), resulting in this kind of value being returned:
```
{"_40": 0, "_55": "c5725881-b7ba-4d3f-82c9-8715cac3876b", "_65": 1, "_72": null}
```

**Comment by martinezleoml** [comment] 2024-03-18 11:18
*We're using Expo SDK 49, not SDK 50, sorry for the mistake.

**Comment by tsapeta** [comment] 2024-03-18 11:26
@martinezleoml Could you try on SDK 50? My PR that autoclosed this issue landed in SDK 50.

**Comment by skdrew** [comment] 2024-03-18 12:33
@tsapeta Hi, we're on SDK 50 and it's definitely still occurring. We've also found two other bugs in other libraries that exhibit similar issues, which is the expected data isn't available when it should be (in secure-store and localization).

I might be making a huge presumption, but that's three expo native modules that exhibit very similar issues. Is it possible there's an underlying issue in Expo's native module implementation somewhere? It's very random to trigger it, which suggests a race condition somewhere to me, but I'm not an expert in the underlying Expo code :)

While I've not tried to figure out the conditions for triggering this bug (or the localization one we've also run afoul of), the only way we're able to trigger the bug in secure-store is when the app is closed, and is opened from cold-start by pressing on a notification alert. And even then, it only happens randomly. Hence it's _really_ difficult to prepare a minimal reproduction of it!

I am absolutely willing to help track down this issue as it's become the cause of much hair tearing here. I can submit crash logs wherever possible and test out anything you need me to.

**Comment by martinezleoml** [comment] 2024-03-20 08:37
> @martinezleoml Could you try on SDK 50? My PR that autoclosed this issue landed in SDK 50.

We're planning to upgrade to SDK 50 in the coming weeks, I'll keep you posted. But as mentioned by @skdrew, the issue occurs very randomly.

**Comment by Braden1996** [comment] 2024-03-20 10:38
> > @martinezleoml Could you try on SDK 50? My PR that autoclosed this issue landed in SDK 50.
> 
> We're planning to upgrade to SDK 50 in the coming weeks, I'll keep you posted. But as mentioned by @skdrew, the issue occurs very randomly.
> 
> Btw thanks for re-opening the issue. :)

If you're looking for a relatively easy fix in the meantime, try migrate away from `expo-crypto` to `react-native-get-random-values`. It worked for us at the time! Although we're now on SDK 50 and are using `expo-crypto` perfectly fine.

**Comment by AndrewJSchoen** [comment] 2024-03-22 15:57
I am currently experiencing this issue on Expo 50, but only in the web version of the build. Not sure if it is related. Note, it is a mono repo, and the `expo-crypto` module is being used in one of the packages and is consumed in the `native` app.

```
Failed to parse source map from '/path/to/project/node_modules/@mediapipe/tasks-vision/vision_bundle_mjs.js.map' file: Error: ENOENT: no such file or directory, open '/path/to/project/node_modules/@mediapipe/tasks-vision/vision_bundle_mjs.js.map'
@org/native:dev: 
@org/native:dev: ERROR in ../../node_modules/expo-modules-core/build/uuid/uuid.web.js:9:8
@org/native:dev: Module not found: Can't resolve 'crypto'
@org/native:dev:    7 |   const cryptoObject =
@org/native:dev:    8 |     typeof crypto === 'undefined' || typeof crypto.randomUUID === 'undefined'
@org/native:dev: >  9 |       ? require('crypto')
@org/native:dev:      |        ^
@org/native:dev:   10 |       : crypto;
@org/native:dev:   11 |
@org/native:dev:   12 |   if (!cryptoObject?.randomUUID) {
@org/native:dev: 
@org/native:dev: web compiled with 1 error and 1 warning
```

**Comment by BradRyan** [comment] 2024-05-23 15:45
Yikes this isn't fun. Just went down a rabbit hole for a user reported bug only to find `randomUUID` was returning an object instead, well, a random UUID. 

```
"expo": "^50.0.17",
"expo-crypto": "~12.8.1",
```

I'll create a fallback but wanted to report here and tune in to see if it's fixed.

**Comment by TomasSestak** [comment] 2024-05-30 15:07
Same thing happened to us after we migrated to **expo-crypto**:

`"ApplicantID": {
			"_x": 0,
			"_y": 0,
			"_z": null,
			"_A": null
		},`

**Comment by tsapeta** [comment] 2024-06-02 22:41
I really hope this has been fixed in SDK 51. Could someone help me to confirm that?

**Comment by obasille** [comment] 2024-06-25 08:51
Got the same issue on iOS
`{"_40":0,"_65":1,"_55":"f74b23a0-d0ea-43eb-8451-5f98a495cd40","_72":null}`
expo-crypto: 12.8.1
expo: 50.0.19

This bug created serious issues on my production app.

**Comment by penicillin0** [comment] 2024-06-30 13:15
Same here

**Comment by cleggypdc** [comment] 2024-08-22 10:32
Same problem here
`{"_h":0,"_i":1,"_j":"44844cdf-xxxx-xxxx-xxxx-xxxxxxxxxxx","_k":null}`

iOS 17.6
expo-crypto@~12.8.1
expo@50.0.7

**Comment by Braden1996** [comment] 2024-10-07 17:31
@cleggypdc, @obasille, @TomasSestak, @BradRyan we've been running `expo-crypto` `~13.0.2` for ~5 months and haven't encountered this issue since (previously encountered it daily). I see you all are still running version 12.x, have you tried upgrading?

**Comment by obasille** [comment] 2024-10-08 10:23
Good to know @Braden1996 !
I've also updated to v13 but I can't tell if the issue is still happening because my code checks for the returned value and fixes it if it's not a string.
I'm adding a log to Sentry so I'll know if it sometimes returns a promise.

**Comment by tsapeta** [comment] 2024-10-22 13:35
There were no reports about this issue happening in SDK 51, so I'm going to close it. Let me know if you're still experiencing it!

**Closed by tsapeta** 2024-10-22 13:35 UTC
Labels: iOS, Issue accepted, Crypto
