### ISSUE TITLE
[Splash Screens]I hope the Splash Screen is not cached

### ISSUE THREAD

**Issue by dajohnny** [expo/expo#3741] opened 2019-03-14 13:59 UTC
Hi, All.

I am very sorry, I have encountered a special problem today. Since it is not convenient, the project does not want to be open to the public. Please allow me to simply describe the problem and do not provide a simple example for the time being.

Problem process:
In the morning, I submitted `expo.splash.image:"./assets/images/screenA.png" ` and then packaged it. In the afternoon, I changed it to `expo.splash.image:"./assets/images/screenB.png" `and packaged it several times. However, it is found that when the program starts, It would flash screenA.png then display screenB.png.

I hope that when I update expo.splash.image, I will show the latest startup image after packaging. I don't want to flash the old splash screen.

If you can tell me more information, I would be grateful!

**Comment by sjchmiela** [comment] 2019-03-14 18:53
IIRC, iOS caches splash screen for some time, try restarting-your-device-after-the-upgrade/uninstalling-app-restarting/waiting a day. 🤔

**Comment by AdamJNavarro** [comment] 2019-03-14 19:00
As @sjchmiela mentioned, iOS can cache the splash screen. A fellow Expo developer encountered this and mentioned the following, "The old image persisted through various debug and test flight distributed release builds, but power cycling my phone seemed to finally purge the haunting splash image."

As this is a known and expected behavior, I'm going to close this issue. If the problem persists after a day or two and trying the aforementioned steps, let me know and I'll be happy to reopen the issue.

Cheers,
Adam

**Closed by AdamJNavarro** 2019-03-14 19:00 UTC
Labels: SplashScreen

**Comment by dajohnny** [comment] 2019-03-18 03:56
Okay. Thank you very much.
Today, I found it was resolved.

**Comment by sjchmiela** [comment] 2020-02-27 15:38
FWIW, it looks like you can clear the splash screen cache, if you want!

https://rambo.codes/posts/2019-12-09-clearing-your-apps-launch-screen-cache-on-ios

**Comment by sjchmiela** [comment] 2020-02-27 15:49
FWIW, it looks like you can clear the splash screen cache, if you want!

https://rambo.codes/posts/2019-12-09-clearing-your-apps-launch-screen-cache-on-ios
