### ISSUE TITLE
Unhandled Rejection (Error): Expected font asset of type `string | FontResource | Asset` (number is not supported on web) instead got: null

### ISSUE THREAD

**Issue by JUDOKICK** [expo/expo#9135] opened 2020-07-08 11:36 UTC
### Summary of Issue 
Unable to load any fonts using Font.loadAsync or useFonts

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```bash
Expo CLI 3.22.0 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
    npmPackages:
      expo: ~38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7

```

### Reproducible Demo

```javascript
Font.loadAsync({
                // This is the font that we are using for our tab bar
                //...Icon.Ionicons.font,
                // We include SpaceMono because we use it in HomeScreen.js. Feel free
                // to remove this if you are not using it in your app
                'CenturyGothic': require('./assets/fonts/CenturyGothic.ttf'),
                'CenturyGothicRegular': require('./assets/fonts/CenturyGothic-Regular.ttf'),
                'Roboto': require('native-base/Fonts/Roboto.ttf'),
                'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf'),
                ...Ionicons.font,
            }).then((result) => {
                console.log("Fonts Loaded");
                this.setState({fontLoaded: true});

            })
```
 
### Expected Behavior vs Actual Behavior

Expecting the fonts to load in the web expo, currently does not. Using latest Expo SDK 38.0.8

**Comment by JUDOKICK** [comment] 2020-07-08 11:39
I suspect this has to do with something how the expo/webpack packs the fonts for use in the Web version. But i cant seem to pinpoint the issue. It claims that the fonts being loaded resolve to a number rather than the string that is provided.

**Comment by byCedric** [comment] 2020-07-08 12:14
Hi @JUDOKICK, thanks for the issue! Could you create a small example or repo where this happens for you? I can't seem to reproduce this in a new blank project. Just for my understanding, this is working for you in Android/iOS but not on Web right?

**Comment by JUDOKICK** [comment] 2020-07-08 12:26
Hey @byCedric 

Thanks for the reply. Yes, I can load fonts in Android and iOS but not Web. I also cannot reproduce it in a new project.

I've tried the usual, removing node_modules, reinstalling packages, etc. No dice. Even cleared caches.

**Comment by byCedric** [comment] 2020-07-08 12:42
Hmm, if we can't reproduce this it's not really possible for us to find the issue here. You can try debugging this yourself by removing all fonts and render a placeholder. After that, you can add the fonts back 1 by 1 to see from when this issue occurs. But again, without being able to reproduce this we can't help that much.

**Comment by JUDOKICK** [comment] 2020-07-08 15:13
Here's a flat boilerplate that demonstrates the issue perfectly. Its completely unable to open in Web due to the fonts not loading.

https://github.com/mcnamee/react-native-expo-starter-kit

**Comment by JUDOKICK** [comment] 2020-07-08 16:18
I've also created a barebones app demonstrating the issue.

https://github.com/JUDOKICK/expo-font-loadasync

It recreates no problem. Seems to be consistent now.  When you run ```expo start:web``` It gives the unhandled rejection error.

**Comment by JUDOKICK** [comment] 2020-07-08 17:15
I seemed to have created a fix for it. Seems to fix it.

if you import like so. Then it runs.

```javascript
import Roboto from '../node_modules/native-base/Fonts/Roboto.ttf';
import Roboto_medium from '../node_modules/native-base/Fonts/Roboto_medium.ttf';
import Ionicons from '../node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Ionicons.ttf';

class App extends React.Component {
  constructor() {
    super();
    this.state = { loading: true };
  }

  async componentDidMount() {
    await Font.loadAsync({
      Roboto: {
        uri: Roboto,
        fontDisplay: FontDisplay.SWAP,
      },
      Roboto_medium: {
        uri: Roboto_medium,
        fontDisplay: FontDisplay.SWAP,
      },
      Ionicons: {
        uri: Ionicons,
        fontDisplay: FontDisplay.SWAP,
      },
    });

    this.setState({ loading: false });
  }
```

Can't explain why, but this pattern seems to satisfy the requirements for the Expo Web build.

**Comment by jsilvao** [comment] 2020-07-08 18:30
Sometimes It's amazing how regular users are more helpful than maintainers. Really good work @JUDOKICK .

**Comment by byCedric** [comment] 2020-07-08 18:56
Awesome, thanks for digging into this. I think I might know why this is happening, inline `require` might be handled as dynamic import in Webpack. If this happens, the `require` method returns a promise instead of the icon resource itself. This is something we can investigate and work on, thanks! The workaround looks great, it shouldn't behave differently on native as well so good find!

Let's keep this open until it's resolved.

**Comment by danmaas** [comment] 2020-07-08 21:15
This also seems to affect sound and image assets. JUDOKICK's work-around fixes those too.

**Comment by rickerp** [comment] 2020-07-09 00:12
I too had this problem. Thanks for the fix @JUDOKICK.

I then found the problem is in `require`.

Not related I think, but I realized that my images stopped loading. I then replaced where I'm using `require` with `import` in the top, and now its working.
Very weird...

**Comment by Blkc** [comment] 2020-07-09 19:47
I ran into this issue when I have `import { FontAwesome5 } from '@expo/vector-icons'` and `<FontAwesome5 name="comment-dollar" size={22} color="rgba(0,0,0,0.35)" />`. Not sure how to fix at the moment.

**Comment by EvanBacon** [comment] 2020-07-09 20:43
This has been fixed in https://github.com/expo/expo-cli/pull/2346 we will publish the fix promptly.

**Closed by EvanBacon** 2020-07-09 20:43 UTC
Labels: Font, OS: Windows, Platform: web, bug

**Comment by EvanBacon** [comment] 2020-07-09 20:51
Tested that `with-custom-fonts` example works with `expo-cli@3.22.1` in web.

**Comment by Albert-Gao** [comment] 2020-07-09 22:37
Tried, works now, thanks!

**Comment by sbrighiu** [comment] 2020-07-16 10:52
Please not to also update to at least
    "@expo/webpack-config": "^0.12.20",
in your package.json file.

**Comment by kopax** [comment] 2020-08-20 00:33
I have the same issue after upgrading my expo-cli, I am still on expo sdk 36, is it save to upgrade parts of the sdk like : `@expo/webpack-config": "^0.12.20` ?

Please let me know how you would handle that. Thanks

**Comment by vrinch** [comment] 2020-12-08 14:08
has anyone been able to find a solution to this?
it is still happening, and the solution proposed is not working for me

**Comment by miamiappmachine** [comment] 2021-01-28 22:14
> has anyone been able to find a solution to this?
> it is still happening, and the solution proposed is not working for me

If you're using expo-vector-icons, FontAwesome5 triggers it

**Comment by dincozdemir** [comment] 2021-02-28 23:17
I am building a Next.js expo integrated project. Ionicons or Fontawesome work fine, only Fontawesome5 breaks.

**Comment by aindong** [comment] 2021-05-19 01:40
issue is still happening on FontAwesome5

**Comment by conor909** [comment] 2021-07-16 10:25
I'm getting this in my test environment with `jest-expo/web`

**Comment by gilsonviana** [comment] 2022-02-01 15:22
thanks to @JUDOKICK reply I was able to get this to work on the web.

I've created the following **custom hook** for loading the resources.

`useResources.ts`
```
import * as Font from 'expo-font';
import { useEffect, useState } from 'react';

import YOUR_FONT_FILE_HERE from '/path/to/fonts/FONT_NAME.ttf';

export const useResources = () => {
  const [isFontReady, setIsFontReady] = useState(false);

  const loadFontAsync = async () => {
    try {
      await Font.loadAsync({
        HindRegular: {
          uri: YOUR_FONT_FILE_HERE as any,
          display: Font.FontDisplay.SWAP,
        }
      });
    } catch (error) {
      console.log('Font Load Error:', error)
    } finally {
      setIsFontReady(true);
    }
  }

  useEffect(() => {
    loadFontAsync();
  }, []);

  return {
    isFontReady
  }
};
```

### Usage

```
export default function App() {
  const { isFontReady } = useResources();

  if (!isFontReady) {
    return (
      <View>
        <Text>Resources are loading...</Text>
      </View>
    )
  }
  
  return (
    <View style={styles.container}>
      <Text style={styles.text}>Welcome to Expo + Next.js 👋</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    fontSize: 16,
    fontFamily: 'YOUR_FONT_NAME_HERE' <----- HERE
  },
});
```
