### ISSUE TITLE
ImagePicker.launchImageLibraryAsync seems to ignore quality option on iOS

### ISSUE THREAD

**Issue by smalldarks** [expo/expo#2708] opened 2018-11-14 09:17 UTC
"expo": "30.0.1",
"sdkVersion": "30.0.0",
"react": "16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",

device: Ipad 5th Gen (2017)

os: ios11

I try to compress the image, so I add "quality: 0.1" in ImagePicker.launchImageLibraryAsync, but it not works.
I have checked the size of base64 with "quality: 0.1" and "quality: 1", the size are the same.

let result = await ImagePicker.launchImageLibraryAsync({
    allowsEditing: false,
    base64: true,
    quality: 0.1
})

**Comment by Szymon20000** [comment] 2018-11-14 11:31
Which mobile OS are you using?

**Comment by Szymon20000** [comment] 2018-11-14 11:51
On Android is seems to work fine.

**Comment by smalldarks** [comment] 2018-11-15 01:22
Ipad 5th Gen (2017)

**Comment by sjchmiela** [comment] 2018-11-16 09:55
I couldn't reproduce the issue, I used this Snack to try — https://snack.expo.io/@sjchmiela/image-picker-quality. Do you see the issue when running this Snack too?

**Comment by yodaheis** [comment] 2019-04-03 07:28
Facing same issue with expo v32.0.6. 'quality' field on launchCameraAsync and imageLibraryAsync doesn't seem to work. 
As a workaound I am resizing using ImageManipulator.

**Comment by AdamJNavarro** [comment] 2019-08-08 00:19
Hey @yodaheis,

Are you still encountering this issue, whether on SDK32 as you mentioned before or a newer version?

**Comment by lukmccall** [comment] 2019-10-11 14:33
I've tried to reproduce your bug. Sadly, I've failed. 
I not only compered sizes of base64 strings, but I've also checked the real size of files. Everything was working like a charm.  

So I'm closing this issue. Feel free to reopen this if you still facing this type of behaviour.

**Closed by lukmccall** 2019-10-11 14:33 UTC
Labels: ImagePicker, needs repro, project: ios-runtime, status: needs more info
