### ISSUE TITLE
SQLite directory does not exist

### ISSUE THREAD

**Issue by arpecop** [expo/expo#2119] opened 2018-08-18 11:02 UTC
Seems like expo apps is using "/host.exp.exponent/files/ExperienceData/%2540anonymous%252" ...
it's not the case when you push your app to productions and apk is generated 
in this scenario the working directory looks something like this:
/data/data/com.appname.name/
in this directory:
`app_webview
cache
code_cache
databases
files
lib
lib-main
no_backup
shared_prefs
`
However no SQLite , 
I am trying to download pre-filled db and save it to "SQLite" 
It works only with expo testing environment

**Comment by arpecop** [comment] 2018-08-19 07:39
Here is "adb" logging from the produced apk, 
![1](https://user-images.githubusercontent.com/168974/44306642-fcb85f80-a39b-11e8-81f8-fc273b098cee.png)

**Comment by sjchmiela** [comment] 2018-08-20 09:59
Hi @arpecop! Sorry for the trouble, fix for this behavior already landed on `master` ([`89b9048`](https://github.com/expo/expo/commit/89b9048fb58083f7558449738d400d2120963909#diff-86e7954c9ca33fc7d3b8b2f2bcd3c2e2R32)) and it will be pushed to the Android builders soon. 🙂 Are you using `exp build` to build the APK or have you detached your project?

**Comment by arpecop** [comment] 2018-08-20 18:10
Thank you for the reply
No, I am cowerdly refusing to detach , maybe its device-specific issue
Android 4.4. in this case 
Building with exp build:android

**Comment by arpecop** [comment] 2018-08-21 17:43
The following code works on Expo App dev environment:
[https://gist.github.com/arpecop/a00b964e9c2ca3c75916a8b80c34ec21](url)
  it seems its not only "SQLite" directory issue  , I can see "cached" with "adb logcat" running the .apk, but the functionality is gone, cannot find the downloaded file either 
 here is the apk:
[https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40arpecop/vicove-13a7cb0c5645de34ef84d22dbc15bcac-signed.apk](url)

**Comment by sjchmiela** [comment] 2018-10-11 10:46
Hey, I believe the issue is resolved—the fix has landed on `master` and should be already released in SDK 30. If not, please file a new issue. 🙂

**Closed by sjchmiela** 2018-10-11 10:46 UTC
Labels: project: sdk
