### ISSUE TITLE
SDK33&34: Orientation change (portrait<->landscape) breaks the app layout and makes the app unusable

### ISSUE THREAD

**Issue by martin-ecatch** [expo/expo#5285] opened 2019-08-10 05:53 UTC
## 🐛 Bug Report
A new bug introduced in SDK33 breaks screen orientation change on Android.
What happens:
- start the app in portrait, then change to landscape -> scrolling doesn't work, half of the content is rendered outside of the screen.
- start the app in landscape, then change to portrait -> app is limited to using only top half of the screen.
The only way to fix it is to kill the app and start it in the orientation that you want to use.

Broken in SDK33, SDK34.
Works fine in SDK32 and older.
Only breaks in android standalone app. Works perfectly fine inside Expo. Weird!

This is a big deal, it is no longer possible to build an app that works on both orientations.

### Environment
  Expo CLI 3.0.9 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.16.2 - /usr/bin/node
      npm: 6.10.3 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^33.0.7 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 3.0.9

### Steps to Reproduce

1. use the included code below
2. expo build:android
3. install the apk on your emulator or device (both show the same issue)

Then:
1. start app in portrait
2. flip device to landscape
3. only half of the screen is visible, can't scroll (if you have a ScrollView)

Or:
1. start app in landscape
2. flip device to portrait
3. only top half of the screen is used

### Expected Behavior
Content should be rendered utilising the whole screen, just like it worked in SDK32 and older.

### Actual Behavior
Described in Steps to Reproduce
The demo code also displays screen size. After changing orientation, the screen becomes square! Not sure if that's the cause or a symptom.

### Reproducible Demo
This demo draws a blue thick border around the screen, so you can see the issue.
It also listens to "onLayout" and shows the screen size. Note that width=height after you change orientation!
Remember, it works fine in Expo, it only breaks in standalone app!

```
export default class Root extends React.Component {
  state = {};

  render() {
    return (
      <View style={{flex: 1, borderWidth: 3, borderColor: 'blue',}}
        onLayout={(evt) => {
          if (evt && evt.nativeEvent) {
            this.setState(evt.nativeEvent.layout);
          }
          console.log(evt);
        }}>
        <Text>Yo!</Text>
        <Text>Width: {this.state.width}</Text>
        <Text>Height: {this.state.height}</Text>
      </View>
    );
  }
}

```

Screenshots:
Start in Portrait:
![Screenshot_20190810_174726](https://user-images.githubusercontent.com/47770056/62818150-3d098280-bb97-11e9-8765-4c7d40a18df1.png)
Then switch to Landscape:
![Screenshot_20190810_174804](https://user-images.githubusercontent.com/47770056/62818151-3da21900-bb97-11e9-8b65-7f069526cb99.png)

Kill the app, start in Landscape:
![Screenshot_20190810_174848](https://user-images.githubusercontent.com/47770056/62818152-3da21900-bb97-11e9-8b34-852422b00d90.png)
Then switch to Portrait:
![Screenshot_20190810_174908](https://user-images.githubusercontent.com/47770056/62818153-3da21900-bb97-11e9-8f9c-4eaffcc39c52.png)

May be related to this issue https://github.com/expo/expo/issues/5033 but I'm not sure if it's the same thing. The above code is super simple and easily reproducible so I thought I'd raise it separately.

**Comment by cruzach** [comment] 2019-08-12 01:03
duplicate of #5033

**Closed by cruzach** 2019-08-12 01:03 UTC
Labels: bug
