### ISSUE TITLE
[expo-media-library] get/request permission always returns undetermined / denied

### ISSUE THREAD

**Issue by iKoru** [expo/expo#15273] opened 2021-11-22 15:17 UTC
### Summary

MediaLibrary.getPermissionsAsync() always returns status:undetermined when granted(denied when denied), 
and when canAskAgain:true, requestPermissionsAsync() always returns granted:false immediately without asking.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43.0.3

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 2.4.2 - /usr/local/bin/yarn
      npm: 8.1.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.3 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

install bare workflow project, 
add dependencies expo 43.0.3, expo-media-library 

> let permission = await MediaLibrary.getPermissionsAsync();
>       if (!permission.granted) {
>         if (permission.canAskAgain || permission.status === "undetermined") {
>           permission = await MediaLibrary.requestPermissionsAsync(false);
>           if (!permission.granted) {
>             //denied
>             return;
>           }
>         } else {
>           //denied
>           return;
>         }
>       }

**Comment by aderiushev** [comment] 2021-11-23 19:44
same for me starting from expo 43

**Comment by emmbyiringiro** [comment] 2021-11-24 21:52
This happens when the user is denied permission and set to never ask again. Next time you tried to ask permission it resolve into `denied`.

You can handle this situation like this 

```
const permission = await MediaLibrary.getPermissionsAsync();

// Detect if you can request this permission again

if (!permission.canAskAgain || permission.status === "denied") {
  /**
   *   Code to open device setting then the user can manually grant the app
   *  that permission
   */

  Linking.openSettings();
} else {
  if (permission.status === "granted") {
    // Your actually code require this permission
  }
}

```
[PermissionResponse Type Definition](https://github.com/expo/expo/blob/master/packages/expo-modules-core/build/PermissionsInterface.d.ts)

**Comment by iKoru** [comment] 2021-11-25 08:47
@emmbyiringiro 
thanks for your comment.
But it doesn't work as we want, unfortunately.
EVEN THOUGH access is allowed in android settings, the return value for the function getPermissionAsync is 

`{isGranted:false, canAskAgain:false, status:"undetermined"}` 

where I expect as follows :
`{isGranted:true, canAskAgain:false, status:"granted"}`

**Comment by anthonywebster** [comment] 2021-11-26 07:35
same for me starting from expo 43

**Comment by tryheirloom-matheus** [comment] 2021-11-29 13:10
having the same issue (sdk 43)

**Comment by pablaber** [comment] 2021-12-01 19:56
Something I noticed in the docs for MediaLibrary: https://docs.expo.dev/versions/latest/sdk/media-library/#medialibraryrequestpermissionsasyncwriteonly

It says that it returns a [PermissionsResponse](https://docs.expo.dev/versions/latest/sdk/media-library/#permissionresponse) object, which is stated to be an extension of [EXPermissionsResponse](https://docs.expo.dev/versions/latest/sdk/media-library/#expermissionresponse).

To me it looks like the status may be "undetermined" because there is now more information provided in the PermissionsResponse object under the optional `accessPrivileges` key which can have values "all", "limited" or "none". 

I am unable to reproduce this in Expo as the status is coming back as "granted", but I'm running a new build for the Android store that has more exposure to what is being returned and I can update when that goes out, but I would guess that the root cause of the issue is that the response looks like:

```js
{
  granted: false,
  canAskAgain: false,
  status: 'undetermined',
  accessPrivileges: 'all'
}
```

**Comment by alfpicapike** [comment] 2021-12-13 15:13
Hi!
I have this problem with SDK 42.
I am developing a managed expo app.
The problem only occurs on published app in play store. When using expo go it works as expected.
MediaLibrary.requestPermissionsAsync(false) returns status denied even though the user never gets an UI.
Also to be noted is that in app settings there are no media only camera and location. 
In app.json I have added the following permissions: ["CAMERA", "WRITE_EXTERNAL_STORAGE", "READ_EXTERNAL_STORAGE",  "ACCESS_COARSE_LOCATION", "ACCESS_FINE_LOCATION", "MEDIA_LIBRARY"]

I have also looked at the output of logcat but I can not see anything related to this issue.

Any input of what I might have done wrong is welcome but I believe somthing is wrong with MediaLibrary.

Best,
Alf

**Comment by natysoz** [comment] 2021-12-16 13:41
well im in too

my case is the same 👍🏻 
I have this problem with SDK 43.0.4

1.user Deny the access , cool , i show him button to go to settings...
2.im using appState to know when he comes back to the app so i cna reload the permissions 
and now i try again to load his permissions

so i try first get, and not request , but get show that the permissions are 

currentPermissions Object {
  "canAskAgain": true,
  "expires": "never",
  "granted": false,
  "status": "denied",
}

and request while "denied" throw an error...

while i just changed that in my settings....

the weird is , even if i go back to other screen and again go in , it gives me the same

currentPermissions Object {
  "canAskAgain": true,
  "expires": "never",
  "granted": false,
  "status": "denied",
}

while i definitely allow all settings, (camera , images , location , all...)

**Comment by natysoz** [comment] 2021-12-17 13:19
[Error: Encountered an exception while calling native method: Exception occurred while executing exported method requestPermissionsAsync on module ExponentMediaLibrary: String resource ID #0xffffffff]

**Comment by natysoz** [comment] 2021-12-17 14:20
issue is that 👍🏻 

when u first enter and Allow permissions = ALL GOOD
you can also deny them and re allow them all will work

when u first enter and Decline permissions = ALL BAD
from now on

getPermissionsAsync() =>
result denied also if u restart the app and of course make settings permissions allowed

requestPermissionsAsync() => 
return [Unhandled promise rejection: Error: Encountered an exception while calling native method: Exception occurred while executing exported method requestPermissionsAsync on module ExponentMediaLibrary: String resource ID #0xffffffff]


thats not good , sometimes users Decline permissions by mistake , when we show them button that leads to Settings
and they allow it manually , and return the app , (using appState to knows when)

at this point we must get the permissions (updated onces!)

it does work with instagram as i just tested.
on expo with android and ios emulators it doesnt work.

**Comment by natysoz** [comment] 2021-12-17 14:26
@barthap do you have time to look into this one ?

**Comment by natysoz** [comment] 2021-12-17 15:59
video show the issue
https://youtu.be/mMCiNvZguL4

snack
https://snack.expo.dev/@natysoz/permissions-reask

**Comment by barthap** [comment] 2021-12-20 12:02
We've been investigating this issue now, a bunch of updates:
- We've been able to reproduce it, but yet in **Expo Go** (managed workflow).
- As far as we found out, there's an issue in Expo Go, but should not happen on Android 9 and older. Affected SDKs are 43 and 44.
- The reason is that in Expo Go, each app you develop can have a separate set of permissions and there is a bug in code handling them - this screen is missing (where "Expo APIs" is your app name):
<img alt="Screenshot 2021-12-20 at 12 36 50" src="https://user-images.githubusercontent.com/278340/146763506-317f8d97-7b11-4ddb-ace0-1dab8c856aba.png" width="200"/>
- We're not sure about solving the root cause, but it definitely solved the `Unhandled promise ... String resource ID #0xffffffff`

**Comment by natysoz** [comment] 2021-12-20 12:40
amazing you found the bug so fast ! Thanks !
waiting for the update so i can upgrade my   expo-images-picker package :)

**Comment by zhujingfa** [comment] 2021-12-25 12:00
Same issue. my project ejected.
Add   <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" /> to  src/main/AndroidManifest.xml, then it behaved as expected

**Comment by natysoz** [comment] 2021-12-25 12:36
@barthap do u know when expo release new version that includes your fix ?

**Comment by natysoz** [comment] 2021-12-31 14:09
any idea when this fix will arrive ? is it suppose to be in next sdk 44.0.4 ?

**Comment by natysoz** [comment] 2022-01-03 10:53
people actually stop using my npm package because of this issue

**Comment by barthap** [comment] 2022-01-03 14:10
Hello, sorry for late reply, I am on holiday. I believe my fix is only related to Expo Go so it happens in development only. If I'm wrong and you say it happens in standalone (built with expo build) apps too, try using EAS Build to build a new version of the app - this will omit the whole buggy Expo Go code.

I don't know if it will be published before SDK 45 and I cannot promise that, I am not allowed to publish new versions of Expo Go, sorry

**Comment by natysoz** [comment] 2022-01-03 23:54
nothing to sorry about , you help a lot and this is much appreciated !

**Comment by humqn** [comment] 2022-01-04 15:23
> Same issue. my project ejected. Add `<uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />` to src/main/AndroidManifest.xml, then it behaved as expected

Thank you so much, you made my day!

**Comment by barthap** [comment] 2022-01-05 07:20
To conclude possible problems and solutions:
- If the permission is denied in **Expo Go** or it crashes, the fix will be published in SDK 45 (see my comments above). If it happens in apps built with `expo build`, the best workaround would be to use EAS Build.
- If it happens in EAS Build or when using `expo prebuild` / `expo run:android` (the prebuild/config plugins workflow), make sure you've followed [this configuration instruction](https://docs.expo.dev/versions/v44.0.0/sdk/media-library/#configuration-in-appjson--appconfigjs) - especially the `isAccessMediaLocationEnabled` property.
- In **ejected/bare workflow**, apply the answer above about adding `<uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />` to `AndroidManifest.xml`. It looks like the [installation instructions for this](https://github.com/expo/expo/tree/master/packages/expo-media-library#configure-for-android) are not updated 🙄 

I'll keep this open for a while until it's tracked internally or finally fixed.

**Comment by humqn** [comment] 2022-01-05 09:24
@barthap I have a bare workflow and I confirm the add of `ACCESS_MEDIA_LOCATION` permission in Android Manifest fix the issue. I will test on various Android version today and I will keep you in touch.

**Comment by StampixSMO** [comment] 2022-01-11 04:29
Duplicate of #11504

**Closed** 2022-01-26 07:22 UTC
Labels: Android, MediaLibrary, Permissions

**Comment by andrey-grach** [comment] 2022-02-02 20:07
> The root issue cause should be fixed now, it will be published with new version (`> 14.0.0`) of the `expo-media-library` package (along with SDK 45, but it might be sooner).
> 
> When the fix is published, adding `ACCESS_MEDIA_LOCATION` to `AndroidManifest.xml` or setting `isAccessMediaLocationEnabled` in config plugin will **not** be necessary **unless** you're accessing `location.latitude` / `location.latitude` properties returned by `getAssetInfoAsync()`.

Just tried version 14.0.1 still have problem with permissions . Works fine in Expo Go but not in standalone Android App. With Android v. 8.0.0 works fine,  with Android v. 11.0.0 doesn't work.

**Comment by barthap** [comment] 2022-02-02 20:12
My post you quoted applies to _bare workflow_.

For standalone apps built with legacy `expo build`, the fix will be applied with SDK 45, because it requires extra effort to apply changes there. The workaround for now is to use EAS Build.

**Comment by endruuu** [comment] 2022-02-03 04:12
Adding `ACCESS_MEDIA_LOCATION` in `AndroidManifest.xml` still doesn't work on Android 12, Expo 43, ejected app.

**Comment by endruuu** [comment] 2022-02-09 21:23
It turns out that a library in my project set the `android:maxSdkVersion` to 28. This is the merged manifest if you open the APK file in Android Studio.
```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="28" />
```

I need to use this in my project's AndroidManifest.xml file to get rid of that and it works properly now.
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    ...
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:remove="android:maxSdkVersion"/>
```

**Comment by natysoz** [comment] 2022-03-10 09:49
i think there wont be sdk 45 we should wait firectly for sdk 46  ?

**Comment by barthap** [comment] 2022-03-10 09:54
there will be, April/May approx. We will now have 3 SDK cycles per year, instead of 4

**Comment by natysoz** [comment] 2022-03-10 09:59
will updating to lastest expo-media-library help on managed ?

**Comment by professorkolik** [comment] 2022-03-21 19:39
This package is not usable anymore in bare workflow, any hotfix we can do to make it work?

**Comment by endruuu** [comment] 2022-03-22 05:07
@professorkolik how about this, at the last item?
https://github.com/expo/expo/issues/15273#issuecomment-1005440392

It works on my bare workflow. Perhaps you encountered the same issue as mine?
https://github.com/expo/expo/issues/15273#issuecomment-1034205379

**Comment by professorkolik** [comment] 2022-03-22 11:12
@endruuu thank you for reaching out, tried both separately and together, no success, all permissions are given in settings but `MediaLibrary.getPermissionsAsync` always respond with `granted: false`

**Comment by Leo-RASPAUD** [comment] 2022-05-06 22:08
Hi,
I'm also having the issue of getting "undertermined" when using EAS build, it's working with expo go though so I'm wondering if there's any fix available or not yet (SDK 44).

Thanks!

**Comment by realjjaveweb** [comment] 2022-06-22 20:16
I have a similar issue, that is _only_ happening on Android 11:
In code, I have following check `permissionResult.granted === false` , which works great in Expo Go on real devices and works great on emulated devices through Expo Go too.
However when I do the EAS .aab build and actually _deploy_ the application - when downloaded&installed on Android 7 everything works great, but when downloaded&installed on Android 11, this is apparently suddenly resolved as true (that the granted is false) even though the permission was requested, granted I even tried to manually allow all permissions through app settings and still nothing.

**Comment by StampixSMO** [comment] 2022-10-27 15:47
This is happening for me on Android SDK 33 (13), Expo 46.0.16, Media Library 14.2.0 and with both the permissions:
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
```

Can this issue be re-opened?

**Comment by Assimilate** [comment] 2023-02-27 20:09
I seem to have a similar issue. Asking for camera permissions works fine for me but asking for image media library permissions always returns (even if I tinker with my app permission through the Android OS settings menu),

`{
  "canAskAgain": false,
  "expires": "never",
  "granted": false,
  "status": "denied",
}`

and I never get any prompt. I've skimmed over the documentation and noticed that for some reason it may not be necessary to ask for permissions to launch the image library? If this is true, why is there still code that handles media library permissions? What am I missing?

Any help is greatly appreciated. @barthap

**Comment by BRUT4LxD** [comment] 2023-03-20 00:36
Hi guys, 
I had the same issue with `MEDIA_LIBRARY` permission. I solved it by not using the `askAsync()` method from `expo-permissions`, instead, I used `requestPermissionsAsync()` from `expo-media-library`. I also updated expo to v. ^48.0.0

**Comment by hotaryuzaki** [comment] 2023-03-29 04:26
> I used to fix this with the `ACCESS_MEDIA_LOCATION` permission, but it resurfaced. This is happening again for me on Android SDK 33 (13), Expo 46.0.16, Media Library 14.2.0 and with both the permissions:
> 
> ```
> <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
> <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
> ```
> 
> Can this issue be re-opened?

same here, the issue recurs after i upgrade the target SDK to 33

**Comment by hotaryuzaki** [comment] 2023-03-29 08:11
for android 13 there is a permission issue that has already been fixed [here](https://github.com/expo/expo/pull/20907)
you have to update to the latest version.
but note that you must upgrade the expo SDK to 48 version

my Expo SDK version is still 47 maybe to fix this issue we have to change using a patch package.

**Comment by benjaminmerchin** [comment] 2023-05-12 15:43
I had the same issue, solved it after updating to expo 48.
It was a problem of compatibilities between package.

**Comment by omerjamshed8** [comment] 2024-01-03 10:26
i am facing this issue in android 13 and above where i cant see the permissions popup to grant the media library permissions but there is no issue in devices lower than android 13.

**Comment by Productivix** [comment] 2024-03-22 17:15
hi still the bug in expo 50 !
solution : 
```
useEffect(() => {
    console.log("permission camera :", permission);
    if (permission && !permission.granted) {
      Camera.requestCameraPermissionsAsync();
    }
  }, [permission]);
```
