### ISSUE TITLE
Find a way to bust the iOS Launch Image cache in standalone apps

### ISSUE THREAD

**Issue by terribleben** [expo/expo#1918] opened 2018-06-25 22:53 UTC
We have a few scattered reports of a **black screen** showing instead of a launch image when an iOS standalone app loads. Powering down the device (or for a simulator, resetting content and settings) makes the bug go away.

It seems to happen only on some devices after the author changes their splash image and rebuilds. As far as we can tell, it's related to the OS cache of the launch image.

Behind the scenes, Expo reuses the same `xib` file and same image filename for everybody's launch screen. I suspect that we might need to provide a nonce or some other randomness when we regenerate the xib file in order to tell the OS that the asset has changed.

Relevant thread: https://forums.expo.io/t/black-screen-before-splash-screen-shows-on-standalone-app/10881/9

Relevant code: https://github.com/expo/xdl/blob/de4534ddca162c258f48c3e76b12a306032d3172/src/detach/IosLaunchScreen.js#L246-L251

**Comment by ssrballin** [comment] 2018-07-16 21:36
Are there any temporary workarounds for this while a solution is implemented? My app has a new name, icon, and launch screen. They all seem to be jumbled up when I update the standalone app with the new TestFlight build (which has the new assets). Any help would be greatly appreciated! :-)

**Comment by audiolion** [comment] 2018-07-26 13:42
I am seeing this issue in our standalone builds, as far as I can tell it hasn't gone away no matter what happens, on App launch the screen goes black, before launching the actual splash image

**Comment by benlonsdale** [comment] 2018-09-06 08:47
Having the same issue on a test flight app, haven't pushed to production yet 

- uninstalling & test flight doesn't fix the issue 
- Turning the phone off and on again doesn't fix the issue
- uninstalling the app, then restarting the phone, then reinstalling seems to have cleared the cache

**Comment by gyurobenjamin** [comment] 2018-09-24 19:55
I can confirm this. Uninstall the app, restart the device, reinstall the app "solves the issue".

**Comment by tiagob** [comment] 2018-12-21 06:09
I had the same issue. I don't why this is marked as closed. Confirmed uninstalling the app, restarting the device, reinstalling the app "solves the issue".

**Comment by charlyBerthet** [comment] 2019-06-06 10:36
Same issue, same "fix": Uninstall the app > Restart device > Install the app.

**Comment by mrsnow-git** [comment] 2019-07-10 12:18
it's not ok for production user.

**Comment by rolinger** [comment] 2019-08-21 20:21
Even the fix isn't working on my iPhone 6s (12.3).  I replaced the splash screen image...deleted the app, rebooted the phone, reinstalled the app and it still shows the cached (big & warped with edges cut off) for a few seconds before showing the new correctly sized splash screen.  I can't get rid of it.

**Comment by marchingband** [comment] 2019-12-13 00:17
I am experiencing this as well, I see a black rectangle (not quite the whole screen) for about 300ms before the splash screen appears.

**Comment by fa-ashwinee** [comment] 2020-04-13 08:59
we cannot ask a number of live users to uninstall the previous app and install the new build.

**Comment by tsapeta** [comment] 2020-07-09 08:32
Closing this issue because we no longer support ejecting to ExpoKit. I encourage you to use bare workflow instead of ExpoKit.

**Closed by tsapeta** 2020-07-09 08:32 UTC
Labels: ExpoKit, iOS
