### ISSUE TITLE
Please set your project ID. A valid Firebase project ID is required

### ISSUE THREAD

**Issue by pfalcetti** [expo/expo#10591] opened 2020-10-07 09:00 UTC
### Summary of Issue 
Hello everyone,
I'm getting this error only on Android production app.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 3.27.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 27, 29
        Build Tools: 28.0.3, 29.0.0
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.3 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
    Expo Workflow: managed

### Reproducible Demo

 Unable to provide.
It only happens on production App.

### Expected Behavior vs Actual Behavior

I'm expecting to get the token, but the call for get it throws error:

![Schermata 2020-10-07 alle 10 51 33](https://user-images.githubusercontent.com/66679563/95309185-18886380-088b-11eb-8d1e-6c7671c15ce0.png)

This is the function that should return the token, but Notifications.getExpoPushTokenAsync() throw error.

The error is 👍 

`Encountered an exception while calling native method: Exception occurred while executing exported method getDevicePushTokenAsync on module ExpoPushTokenManager: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: it identifies your project with google.
`

I'm not using Firebase. So i have no idea where to take this ID.

I thought that the params in the getExpoPushTokenAsync() function, were optional.

The weird is that if i run the App through the command Expo start, in dev. the function correctly returns the token.

How to solve this ? 

Thanks in advance

**Comment by byCedric** [comment] 2020-10-07 11:26
Hi @pfalcetti! Thanks for the issue report. I think you are missing [this step](https://docs.expo.io/push-notifications/using-fcm/#uploading-server-credentials) to fully set up your production app with FCM (Firebase Cloud Messaging or push notifications on Android). Could you try that to see if it's working as expected?

Hope this helps!

**Comment by pfalcetti** [comment] 2020-10-07 12:06
Hello @byCedric ,
Do i need to configure FCM even if i'm sending the notifications with Expo'push API ?

**Comment by byCedric** [comment] 2020-10-07 12:46
Yes, that's required when you are creating a standalone app. You want all push notifications being tied to your app, instead of the Expo Client app :) For Google, that basically means "your app owns all these push notifications tokens".

**Comment by pfalcetti** [comment] 2020-10-07 12:56
Thank you @byCedric .

Expo documentation says to give to the FireBase project the same name of the app.json "android.package" key.

Is it necessary or is it a "good advice" ? 
Because my "android.package" key, is something like "aaa.bbb.ccc", and in the Firebase name project it says : Can only contain letters, numbers, spaces, and these characters: -!'"

So if it need to be the same, i've a problem.

**Comment by byCedric** [comment] 2020-10-08 12:46
The Firebase project and your app identifier don't need to match, do you have a link to the docs where it says that? You still have to set a package identifier in your Firebase project when connecting it to Android app or push notifications. But that should be pretty straight forward and relevant only when asked. 

I'm going to close this now because I don't think this is a bug or an issue with the notifications. If you still have questions about this, feel free to ask them on [Slack](https://slack.expo.io/) or [the forums](https://forums.expo.io/).

Hope this helps!

**Closed by byCedric** 2020-10-08 12:46 UTC
Labels: Android, Issue needs review, Notifications

**Comment by imran1992** [comment] 2020-11-03 18:13
same issue occur here now.

**Comment by ger88555** [comment] 2021-02-13 06:46
I'm experiencing the same issue, having followed [the steps in the documentation](https://docs.expo.io/push-notifications/using-fcm/).  My _google-services.json_ file contains the Firebase Project ID, it's located on the root directory, and is referenced by _app.json_ like this:

```
{
	"expo": {
                ...
		"android": {
                        ...
			"googleServicesFile": "./google-services.json"
                }
                ...
         }
}
```

Nontheless, I keep getting:

```
Encounter an exception while calling native method:
Exception occurred while executing exported method getDevicePushTokenManager:
Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
```

when I run the standalone APK.

Is it normal to keep getting this message at this point? I already set up the Firebase Project and uploaded the secret key to Expo (then built the app again). What's missing?

**Comment by vinaciotm** [comment] 2022-08-04 17:50
1. At the top of the sidebar, click the gear icon to the right of Project Overview to go to your project settings.
2. Click on the Cloud Messaging tab in the Settings pane.
3. Copy the token listed next to Server key.
4. Run expo push:android:upload --api-key <your-token-here>, replacing <your-token-here> with the string you just copied. We'll store your token securely on our servers, where it will only be accessed when you send a push notification.


`function* getNewToken() {
  if (Platform.OS === "android")
    ExpoNotifications.setNotificationChannelAsync("default", {
      name: "default",
      importance: ExpoNotifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: THEME.default.colors.danger,
    });

  const res = yield ExpoNotifications.getExpoPushTokenAsync();
  const token = res?.data;
  if (!token) throw { ui_message: "Não foi possível obter o token de push" };
  return token;
}`

**Comment by humblesami** [comment] 2023-01-06 10:56
Its a duplicate of [issues#18570](https://github.com/expo/expo/issues/18570)
And the problem is with expo go version=>2.25
And the solution is
1. Probably short and recommended by other (not tested by me) => Downgrade to Expo 2.24.6 if you can
2. If you have usb cable and you can attach device to dev computer then get rid of expo at all
2.1 use command "expo eject" => Go to react-native project
2.2 build again with command "npx react-native run-android"
2.3 Run "npx react-native start"
