### ISSUE TITLE
Error Domain=kCLErrorDomain Code=0 error in iOS when upgraded to expo sdk 34 - Location.getCurrentPositionAsync 

### ISSUE THREAD

**Issue by cjahfar1** [expo/expo#5487] opened 2019-08-29 09:35 UTC
### Environment

Expo CLI 3.0.4 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.3 => 32.0.13 
      @types/react: ^16.5.0 => 16.9.2 
      @types/react-native: 0.57.34 => 0.57.34 
      @types/react-navigation: ^3.0.1 => 3.0.8 
      expo: ^34.0.3 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.4

### Steps to Reproduce

Recently I upgraded from expo sdk 32 to 34 version. As part of this changes, changed the references to expo-location library. expo-location version is 6.0.0. After this upgrade, Location.getCurrentPositionAsync function throws error "Cannot obtain current location: Error Domain=kCLErrorDomain Code=0(null)" from iOS devices (Not simulators) intermittently. In android, its working without any issues. This function was working perfectly when we were using expo sdk 32.

### Expected Behavior
Return location coordinates.

### Actual Behavior

Its throwing error "Cannot obtain current location: Error Domain=kCLErrorDomain Code=0"

**Comment by yusufkinatas** [comment] 2019-08-29 12:31
I got the same issue on real ios device. getCurrentPositionAsync takes too much time (like 10 seconds)

**Comment by cruzach** [comment] 2019-08-29 17:33
Is it happening in the Expo Client, or standalone? It's best if you provide a reproducible demo in your bug report

**Comment by sagomezza** [comment] 2019-10-30 21:04
I have the same issue in both development and production environments.

**Comment by cruzach** [comment] 2019-10-30 21:29
If you are having this issue, please provide a reproducible demo

Is it only SDK 34, or SDK 35 as well?

**Comment by arvenjadeaguilar** [comment] 2019-11-28 12:17
I also have this issue..  I use 
"expo-location": "^7.0.0",
"expo-permissions": "~7.0.0",
"expo": "^35.0.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",

//function to get location
_getLocationAsync = async () => {
    let { status } = await Permissions.askAsync(Permissions.LOCATION);
    if (status !== 'granted') {
      this.setState({
        locationResult: 'Permission to access location was denied',
      });
      console.log('Permission to access location was denied')
      return;
    }else{
      let location = await Location.getCurrentPositionAsync({});
      return location;
    }
  };

It doesnt have a problem fetching the location in android but when it is used in IOS
it will this error 
Cannot obtain current location: Error Domain=kCLErrorDomain Code=0 "(null)"

this issue occurs on both testing in expo app or in testflight...

I hope you can help

**Comment by cruzach** [comment] 2019-12-02 15:59
Just tested this on my device with the [example snack](https://docs.expo.io/versions/latest/sdk/location/ from the docs), and it seems to work fine on iOS.

Are you testing this on a device, or simulator?

**Comment by webmasterdragon** [comment] 2019-12-23 15:52
I got same issue.
You can enable iOS simulator location setting none->custom ...
![image](https://user-images.githubusercontent.com/29256561/71367148-cf567400-25d6-11ea-8b4a-2dfff9c0564a.png)

**Comment by cruzach** [comment] 2019-12-23 17:03
Please share a snack that reproduces this issue

**Comment by faustoct** [comment] 2020-03-10 17:21
I got the same problem running on iphone and android in production. It sometimes happen and look like intermittent issue under certain condition I haven't figured out yet.

**Comment by sbichenko** [comment] 2020-05-05 16:02
Same thing happening to me.
```
        "expo": "^36.0.0",
        "expo-location": "~8.0.0",
```

**Comment by Infinitism** [comment] 2020-05-15 11:50
I think this has to do with this issue: https://github.com/expo/expo/issues/5504#issuecomment-564140121

And setting the Location.getCurrentPositionAsync to High should solve it. I had the same issue when I set it to Balanced and it looks like that might be the reason why the error is not consistent because this setting doesn't always fail. 

When it does fail, the linked error is what I got on Android and this issue on iOS. 

I'd like someone from Expo to verify this association just to be sure though:)

**Comment by sebastianekstrom** [comment] 2020-05-21 16:37
Same issue here with:

```
"expo-location": "~8.1.0",
"expo": "^37.0.0",
```

Setting `Location.getCurrentPositionAsync({accuracy: Location.Accuracy.High})` does not help.

**Comment by alexandersandberg** [comment] 2020-06-08 17:40
I'm also experiencing this issue with:
```
"expo": "~37.0.3",
"expo-location": "~8.1.0",
```

It seemed to be working fine yesterday and today suddenly stopped. Running on a physical iPad device.

**Comment by juzerdhinoj** [comment] 2020-06-14 22:48
I am also experiencing this unexpected issue, assumed its something to do with the location permission so gave the permission 'Always' but that also didn't seem to rectify it. 

Versions:
"expo": "~37.0.3",
"expo-location": "^8.1.0",

Came across this issue few days back as well, but it seemed to work again after awhile. Please look into this error.

**Comment by tsapeta** [comment] 2020-07-11 16:14
We were not able to successfully reproduce this issue and it refers to SDK that we no longer support, so I'm closing it.
Feel free to open a new issue with updated details and repro steps if it's still happening in newer SDK versions.

**Closed by tsapeta** 2020-07-11 16:14 UTC
Labels: Location, bug, iOS, needs repro

**Comment by Infinitism** [comment] 2020-07-13 13:31
This is an issue I experience with SDK 37 as well. Can we open this back up please?

**Comment by tsapeta** [comment] 2020-07-16 17:26
@Infinitism could you please provide some repro steps or create a minimal app that we could use to reproduce this issue? As far as I know this issue is not related with the app, but with your device and especially network settings (WiFi and cellular). Do you have them enabled?
Does other apps that tracks your location work fine?

**Comment by phoenix214** [comment] 2020-07-17 16:39
I am having this issue while I'm testing on iPhone with iOS 13.4.1. 
But it's working on my other iPhone with iOS 13.2.

**Comment by jpaulomotta** [comment] 2020-10-06 13:59
Having the same issue on an Ipad:

"expo": "^37.0.0",
"expo-location": "~8.1.0",

```

[Unhandled promise rejection: Error: Cannot obtain current location: Error Domain=kCLErrorDomain Code=0 "(null)"]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:99:50 in fn
- node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.js:15:46 in moduleName.methodInfo.name
- node_modules/expo-location/build/Location.js:63:48 in getCurrentPositionAsync
```

**Comment by georgiosd** [comment] 2020-11-03 16:53
We're getting such sentries in SDK 39 also

**Comment by djvistasa** [comment] 2020-11-04 14:12
Ditto, sdk 39 and expo-location 9.0.0 still persists

**Comment by Bielik20** [comment] 2021-03-09 16:17
I think this may be connected with simulator: https://stackoverflow.com/questions/32543754/ios-9-error-domain-kclerrordomain-code-0-null

**Comment by odama626** [comment] 2021-08-24 18:55
Just got this same error from test flight expo 40 expo-location 10

**Comment by Dakuan** [comment] 2022-01-12 19:34
ditto expo 44

**Comment by gabrieljoelc** [comment] 2022-02-14 23:51
my guess is it's the timeout issue from #10756

**Comment by itsramiel** [comment] 2022-11-02 06:27
got this on expo 46

**Comment by rgdSolutions** [comment] 2023-03-15 13:34
I can confirm it is still happening on expo 46 and expo-location 14.

**Comment by Saad-Bashar** [comment] 2023-05-10 01:10
Yup this is still happening unfortunately.

**Comment by JairajJangleSLIOT** [comment] 2023-10-03 04:10
Still facing this issue, this issue should be re-opened.

**Comment by tsapeta** [comment] 2023-10-04 19:48
Hey, this issue was opened for SDK 34, a very old version. If you're still experiencing this, could someone open a new issue that links to this one and provides a minimal reproducible example? 🙏

**Comment by 233devs** [comment] 2024-02-06 12:03
> Hey, this issue was opened for SDK 34, a very old version. If you're still experiencing this, could someone open a new issue that links to this one and provides a minimal reproducible example? 🙏

I opened a new [issue](https://github.com/expo/expo/issues/24798) and nobody responded to it. Please can someone check it out.
