### ISSUE TITLE
attempt to invoke virtual method 'boolean java.lang.string.endtswith(java.lang.string) on a null object reference" ==> when i use linking from react-native 

### ISSUE THREAD

**Issue by AbdelhalimAhmed** [expo/expo#1733] opened 2018-05-07 20:06 UTC
# android only, iso working perfect 

i upgrade my expo project to "expo": "^27.0.0",
and when useing linking to open Url or tel:number that issue shown to me: 

 **attempt to invoke virtual method 'boolean java.lang.string.endtswith(java.lang.string) on a null object reference**

> using: 
``` 
"expo": "^27.0.0",
"react": "16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz"
```

> my code: 
```
console.log('Trying to access url')
let url = "https://expo.io"

try {
  Linking.canOpenURL(url).then(supported => {
     if (!supported) {
     console.log('Can\'t handle url: ' + url)
     } else {
        return Linking.openURL(url)
     }
  }).catch(err => console.error('An error occurred', err))
  }catch(err) {
     console.log('why this fucken not working', err)
  }
```

**Comment by FakhruddinAbdi** [comment] 2018-05-08 09:02
I have same issue.. I think its a permission error. Because we can not set android permission `call_phone` using expo 
https://github.com/expo/expo/issues/1729

**Comment by AbdelhalimAhmed** [comment] 2018-05-09 18:41
@FakhruddinAbdi your solution fixed the issue ?

**Comment by FakhruddinAbdi** [comment] 2018-05-09 18:43
as `we can not set android permission call_phone using expo` so there's no solution in my side @AbdelhalimAhmed  yet

**Comment by WillemLabu** [comment] 2018-05-14 12:00
+1

- Android on device crashes. (RedBox)
- iOS throws `Unhandled promise rejection`. (YellowBox)

```
React: 16.3.1
RN: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz (0.55.2)
Expo: ^27.0.0 (27.0.1)
```

<details>
<summary>On my Android device:</summary>

![Stack Trace](https://i.imgur.com/BIEugQX.png)

</details>

<details>
<summary>iOS Simulator:</summary>

![Stack Trace](https://i.imgur.com/vzt1Ymv.jpg)

</details>

Error details seem to point to [this method](https://github.com/expo/expo/blob/8732d23433ac1f1b2c2db3893df45f77f8091d3b/android/expoview/src/main/java/versioned/host/exp/exponent/modules/internal/ExponentIntentModule.java#L54)

**Comment by terribleben** [comment] 2018-05-14 16:51
Hi, I believe this may be a duplicate of [this issue](https://github.com/expo/expo/issues/1711), which has a fix pending. Are they the same?

**Comment by WillemLabu** [comment] 2018-05-14 18:26
Hey @terribleben, yep. Seems to be a duplicate.
Sorry about that.

Please feel free to close this.

**Comment by terribleben** [comment] 2018-05-14 21:20
No problem - we'll continue tracking in the other thread. I believe a fix is pending.

**Closed by terribleben** 2018-05-14 21:20 UTC
Labels: project: sdk
