### ISSUE TITLE
Expo jest: Cannot read property 'BarCodeType' of undefined

### ISSUE THREAD

**Issue by gdaunton** [expo/expo#1441] opened 2018-02-18 01:47 UTC
I'm running into an issue trying to run a jest test.
```json
"scripts": {
  "test": "node_modules/.bin/jest"
},
"jest": {
  "transformIgnorePatterns": [
      "node_modules/(?!(react-native|Expo|expo|native-base-shoutem-theme|react-native-easy-grid|react-native-drawer|react-router-native|@expo/vector-icons|native-base/node_modules/react-native-vector-icons))"
  ],
  "preset": "jest-expo"
},
"devDependencies": {
    "babel-eslint": "^7.1.1",
    "enzyme": "^3.0.0",
    "enzyme-adapter-react-16": "^1.0.2",
    "enzyme-to-json": "^3.0.0",
    "jest": "^22.3.0",
    "jest-expo": "^25.1.0",
    "jest-serializer-enzyme": "^1.0.0",
    "react-addons-test-utils": "^15.6.2",
    "react-devtools": "^2.5.2",
    "react-dom": "^16.0.0-0"
}
```

The error is happening when I try to read `BarCodeType` from the barcode scanner component:
```js
import { BarCodeScanner } from 'Expo';
const QR_BARCODE_TYPE = BarCodeScanner.Constants.BarCodeType.qr;
```

I'm just running a standard enzyme render of the entire app:
```jsx
it('renders without crashing', () => {
  const rendered = shallow(<App />);
  expect(rendered).toMatchSnapshot();
});
```

I think this is a bug because when I don't even reference the property and just import `BarCodeScanner`, the error persists.

**Comment by sjchmiela** [comment] 2018-11-29 11:43
I think this problem may have been caused by outdated mocks in `jest-expo`. This should be resolved in recent versions of Expo SDK and `jest-expo`. In such case I'll let myself close this issue, but feel free to reopen this issue if the problem is still present! 🙂

**Closed by sjchmiela** 2018-11-29 11:43 UTC
Labels: project: misc-libraries, project: sdk, status: needs more info
