### ISSUE TITLE
Error installing or running app. Error: Process exited with non-zero code: 60

### ISSUE THREAD

**Issue by jpca999** [expo/expo#653] opened 2017-09-18 11:19 UTC
any idea what this error is about ?  and why is it happening ?

![image](https://user-images.githubusercontent.com/1026325/30539695-b5565cb2-9c41-11e7-83fd-293635b6fde2.png)

**Comment by ide** [comment] 2017-09-19 18:51
Seems like this happens when the simulator takes a long time to start. @fson or @davepack what do you think about splitting this step in two - launch the simulator and then open the URL?

**Comment by terribleben** [comment] 2017-09-21 17:37
Hi, this is an issue with Apple's tooling and is typically fixed by hitting "Reset Content and Settings" on your simulator.

Closing as a duplicate of https://github.com/expo/expo/issues/169 but please comment again if you're still blocked.

**Closed by terribleben** 2017-09-21 17:37 UTC

**Comment by MeKyleH** [comment] 2018-04-16 01:42
I had this issue today. I resolved by opening xCode. It appears an update was downloaded but not fully installed which was breaking the simulator. I let it finish installing and it worked!

**Comment by MuhammadUmairghufran** [comment] 2019-01-19 11:45
> I had this issue today. I resolved by opening xCode. It appears an update was downloaded but not fully installed which was breaking the simulator. I let it finish installing and it worked!

My Xcode updated but it's not seems to resolved ? Any suggestion

**Comment by fson** [comment] 2019-04-15 15:01
Locking this closed thread because Expo CLI issues are now handled in the [expo-cli](https://github.com/expo/expo-cli) repository.

If you have issues with Expo CLI, please report them in https://github.com/expo/expo-cli/issues with as much information (see the issue template) as possible. Thanks!
