### ISSUE TITLE
Using _layout to control the router style can cause some components to not work properly

### ISSUE THREAD

**Issue by RongDuJiKsp** [expo/expo#25308] opened 2023-11-10 01:39 UTC
### Minimal reproducible example

https://github.com/RongDuJiKsp/IssueToExpoCamera

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When I used stack and _layout on the expo router, I found that when I modified the style with _layout, the expo camera could not update the preview normally after returning from switching the page. However, when I delete the _layout file and switch the page back, it will not cause the expo camera to fail. I submitted a minimal sample that contains only the code necessary to switch pages.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.3.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~49.0.15 => 49.0.17
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
      react-native-web: ~0.19.6 => 0.19.9
    Expo Workflow: managed

**Comment by EvanBacon** [comment] 2023-11-13 22:25
Possible duplicate of https://github.com/expo/expo/issues/25262

**Comment by RongDuJiKsp** [comment] 2023-11-14 11:05
https://github.com/expo/expo/assets/110959752/f8a6b990-a355-4c7a-85bf-763bc886c024

This is a video to show the detailed operation of the error encountered .I deleted almost all unnecessary dependencies.

**Comment by marklawlor** [comment] 2023-11-29 06:57
This isn't an Expo Router issue, as you can also replicate it with React Navigation. Seems to be related to a interaction between Expo Camera and the Stack component.

A hotfix solution is simple to unmount the camera when its not being focused

```diff
+ import { useIsFocused } from "@react-navigation/native";

export default function App() {
   ...
   return (
    <View>
+      {useIsFocused() && (
+        <Camera style={{ height: "100%" }} ref={(e) => setCamera(e)} />
+      )}
    <View>
  );
}

```

@lukmccall Are you able to provide any additional advise?

**Comment by lukmccall** [comment] 2023-11-29 12:00
Unfortunately, I wasn't aware of that behavior, but unmounting it seems like a good idea. We're currently working on a new camera implementation. It might fix that issue. If not, we will take a closer look later. For now, you can use the provided workaround.

**Comment by RongDuJiKsp** [comment] 2024-01-28 04:57
The good news: the new version of CameraView solves this problem

**Comment by RongDuJiKsp** [comment] 2024-01-28 05:03
It works very well.
```tsx
export default function App() {
    const [isShowing,setShowing]=useState<boolean>(false);
    return <View>
        <Button title={"GETPERMMISION"} onPress={() => {
            Camera.requestCameraPermissionsAsync().then();
        }}/>
        <Button title={"GETPERMMISION"} onPress={() => {
            Camera.requestCameraPermissionsAsync().then();
        }}/>
        <Button title={"TO PAGE"} onPress={() => {
            router.push("/other");
        }}/>

        {isShowing&&  <CameraView style={{height: "100%"}}/>}
    </View>
}
```

**Comment by marklawlor** [comment] 2024-01-28 23:56
This issue appears to be resolved so I'll close this issue

If you experience this issue on SDK <=49: please follow the workaround https://github.com/expo/expo/issues/25308#issuecomment-1831320266

If you are on SDK 50+ please create an new issue so we can track it with the new SDK version.

**Closed by marklawlor** 2024-01-28 23:56 UTC
Labels: Camera, needs review
