### ISSUE TITLE
[docs] [expo-auth-session/providers/google]

### ISSUE THREAD

**Issue by victorpicaud** [expo/expo#10656] opened 2020-10-13 11:54 UTC
Hello,
After a lot of tries, I could not find an answer to the following question:
using the explanations here: https://docs.expo.io/guides/authentication/#google
to setup a proper google auth, I can't find any way to revoke the session (aka logout)

I use so far the exact same code as provided in the docs, it seems that with this Google provider there is no access to the revokeAsync() AuthSession method which is created.
Is there any way to do that and if not, could it be implemented?

**Comment by cruzach** [comment] 2020-10-13 20:46
Hi! I'm going to close this issue, since we keep github reserved for bug reports. It looks like the method you're looking for is here- https://docs.expo.io/versions/latest/sdk/auth-session/#authsessionrevokeasync. If you think you've found a bug with `expo-auth-session`, please fill out the full bug report template including a reproducible demo. thanks!

**Closed by cruzach** 2020-10-13 20:46 UTC
