### ISSUE TITLE
getInfoAsync throws when file doesn't exist

### ISSUE THREAD

**Issue by derekstavis** [expo/expo#5408] opened 2019-08-21 21:12 UTC
### Environment

```
  Expo CLI 2.19.4 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.0.0 - /usr/local/bin/fish
    Binaries:
      Node: 10.15.3 - /var/folders/t_/7yjdv9157q79st_zkznmr7dm0000gn/T/yarn--1566419214536-0.039177485703587145/node
      Yarn: 1.17.3 - /var/folders/t_/7yjdv9157q79st_zkznmr7dm0000gn/T/yarn--1566419214536-0.039177485703587145/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
```

The issue happens in both Android and iOS.

### Steps to Reproduce

1. Call `getInfoAsync` on an inexistent file

### Expected Behavior

1. Should resolve to `{ exists: false }` instead of throwing

### Actual Behavior

1. `getInfoAsync` throws an error `File <file path> isn't readable`

### Reproducible Demo

https://snack.expo.io/@charliecruzan/getinfoasyncerror

**Comment by sjchmiela** [comment] 2019-08-22 07:20
Actually this is a good path (it follows `[scheme]://[path]` pattern), but it tries to access filesystem outside of allowed directories (in Expo client those are `FileSystem.documentDirectory` and `.cacheDirectory`) — and thus it triggers a permissions error.

Resolving with `exists: false` when the file does not exist even though it is out of the permitted scope could be a security concern, allowing people to infer information about other apps used in Expo client.

**Comment by derekstavis** [comment] 2019-08-23 06:21
This also happens in the case of iOS wiping files from camera caches, which my current issue with the error -- We do copy the files to a cache directory, but during background fetch we also check if the original source file exists, which when iOS has wiped the cached file makes the function throw.

**Comment by sjchmiela** [comment] 2019-08-23 06:29
Are you sure you provide a valid URL to `getInfoAsync` in that background fetch task? Is it possible that it's `null` or sth? The error is raised only in

https://github.com/expo/expo/blob/7a0e6bb94bd3edb2bc2dc501d6c09ad6edccd1bb/packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m#L188-L193

so when the permissions don't allow reading the file. The implementation first checks schemas and then delegates to local filesystem permissions manager

https://github.com/expo/expo/blob/7a0e6bb94bd3edb2bc2dc501d6c09ad6edccd1bb/packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m#L762-L776

Maybe your URL's scheme is unsupported? What is the URL you're providing to `getInfoAsync`?

**Comment by derekstavis** [comment] 2019-08-23 20:24
Yeah, directly from a Sentry error:

```
File 'file:///var/mobile/Containers/Data/Application/872381C8-7346-479D-A245-2EC797230C48/Library/Caches/Camera/13D9B0FE-B1B1-9CD6-83B0-D0F189288318.jpg' isn't readable.
```

**Comment by QiYuNew** [comment] 2021-02-16 19:24
Yes, I want the functionality of checking a file/folder whether is existing. But it throw an error.

**Comment by nomi9995** [comment] 2021-06-10 08:35
same error when I try to read files from the cache directory. why `react-native-fs` have access any file from everywhere?

**Comment by nomi9995** [comment] 2021-06-10 10:45
fixed by #13232 PR. before merge you can use this [patch-package](https://www.npmjs.com/package/patch-package)
make this file `patches/expo-file-system+11.0.2.patch`
```
diff --git a/node_modules/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java b/node_modules/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java
index 3001bb6..cf09406 100644
--- a/node_modules/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java
+++ b/node_modules/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java
@@ -234,9 +234,14 @@ public class FileSystemModule extends ExportedModule implements ActivityEventLis
   public void getInfoAsync(String uriStr, Map<String, Object> options, Promise promise) {
     try {
       Uri uri = Uri.parse(uriStr);
-      ensurePermission(uri, Permission.READ);
+      Uri absoluteUri = uri;
       if ("file".equals(uri.getScheme())) {
-        File file = uriToFile(uri);
+        uriStr = uriStr.substring(uriStr.indexOf(':') + 3);
+        absoluteUri=Uri.parse(uriStr);
+      }
+      ensurePermission(absoluteUri, Permission.READ);
+      if ("file".equals(uri.getScheme())) {
+        File file = uriToFile(absoluteUri);
         Bundle result = new Bundle();
         if (file.exists()) {
           result.putBoolean("exists", true);

```

**Closed** 2021-06-16 10:59 UTC
Labels: FileSystem, bug

**Comment by joshhogg** [comment] 2021-06-17 22:17
Is this something that may apply to all of the functions inside of `FileSystemModule.java` ? 

I am struggling with an issue with `readAsStringAsync`, which looks similar. However, I am not entirely sure how to debug the java. Grokking what I can, it looks related to file:/ vs file:/// prefixes, is that true? Or is absolutePath checking for something else?

**Comment by nomi9995** [comment] 2021-06-18 06:27
@joshhogg can you provide reproducible example so i can fix it by patch or PR

**Comment by joshhogg** [comment] 2021-06-22 17:03
@nomi9995 I have added a repository here which shows the issue:

https://github.com/joshhogg/AndroidExpoAssetIssue/tree/main

Please note, the issue is with published builds being loaded by Expo Go

**Comment by nomi9995** [comment] 2021-06-22 19:38
@joshhogg it is [empty project](https://github.com/joshhogg/AndroidExpoAssetIssue/blob/6c6db6ea120d9160c22c167cecf7a9c811a28e69/App.js#L8) not a reproducible example

**Comment by joshhogg** [comment] 2021-06-22 19:51
My mistake, forgot to push. Can you check again?

**Comment by nomi9995** [comment] 2021-06-23 18:16
it is not reproducing on my side
<img src="https://user-images.githubusercontent.com/36044436/123147807-eb133280-d478-11eb-9b55-82e37d2f61d1.jpeg" width="300" />

**Comment by joshhogg** [comment] 2021-06-23 19:01
Hmm, is this on a published build, by running the publish script in the package.json? 

Have you modified any permissions for Expo Go or other settings on the phone?

**Comment by nomi9995** [comment] 2021-06-24 10:19
@joshhogg no i checked with ejected expo

**Comment by clemwo** [comment] 2023-04-17 15:12
I'm also running into this issue. On react native iOS I'm checking whether a file exists in the documentsDir for implementing downloads from a WebView. If it does exist I append a suffix ' - Copy' to the file name stem and call the function recursively so that until a filename gets found that doesnt exist the function returns this name.

The idea of this is to handle user downloads. If a user downloads an already existing file called 'example.jpg' I dont want to replace the file but rather save the new download as 'example - Copy.jpg. If 'example - Copy.jpg' also exists it should be downloaded as 'example - Copy - Copy.jpg' and so on.

I could easily catch the error but that doesn't feel right to me as the API docs say it should simply return "exists: false"
