### ISSUE TITLE
[ Deeplink - Universal links] => Sentry Capture: undefined is not an object (evaluating 'p.options')

### ISSUE THREAD

**Issue by HVHMobileDeveloper** [expo/expo#12434] opened 2021-04-07 03:23 UTC
### Summary

undefined is not an object (evaluating 'p.options'), the exception: Non-Error exception captured with keys: componentStack

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

expo sdk 40,         "@react-navigation/native": "5.7.2",         "@react-navigation/stack": "5.8.0",

### Environment

standalone

### Reproducible demo or steps to reproduce from a blank project

- Killed app
- Tap on the Universal linking
- I have followed on the React navigation article

**Comment by cruzach** [comment] 2021-04-12 13:50
Hi! I'm closing this issue because you haven't provided a minimal reproducible demo we can use to confirm this behavior. If this error happened with a template from an article, please link either the template or the article

**Closed by cruzach** 2021-04-12 13:50 UTC
Labels: needs review
