### ISSUE TITLE
Multiple `_layout.tsx` Re-renders (most-recent version)

### ISSUE THREAD

**Issue by barrownicholas** [expo/expo#29163] opened 2024-05-28 01:16 UTC
### Minimal reproducible example

https://github.com/barrownicholas/expo-router-rerender-example

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

`_layout.tsx` is once again experiencing multiple, un-expected / unnecessary re-renders. This was an issue about a year ago (https://github.com/expo/router/issues/320) but this was later resolved. As some users started pointing out, Expo `50` seemed to re-introduce this. I created a minimal reproducible example demonstrating that the issue has returned: https://github.com/barrownicholas/expo-router-rerender-example. 

#### Steps to Take in Reproducible Example

1. Start expo: `npm run start`
2. Open web browser (+ console)
3. Notice that the function `superExpensiveLoadingFunction` (in `/app/_layout.tsx`) is called once
4. Press the `Login` button (notice that `superExpensiveLoadingFunction` is **not** re-called, as expected)
5. Toggle back and forth between the "Dashboard" and "Settings" buttons. Notice that the function `expensiveInitdLoadingTask` **is erroneously/unexpectedly** being recalled on each and every click

### Environment

  ```
  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.5 Ubuntu 20.04.6 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 20.13.1 - ~/nvm/current/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 10.5.2 - ~/nvm/current/bin/npm
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      expo-router: ~3.5.14 => 3.5.14 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed
```

**Comment by marklawlor** [comment] 2024-05-29 01:19
The issue is that you have not provided a navigator to `initd/_layout`. When a route changes, the navigators will re-render the minimum amount required. But your structure is `_layout (with a navigator) => initd/_layout (no navigator) => route`

So when a route changes, it has to rerender `initd/_layout` because it does not contain a navigator (the closest is it parent).

The simple fix is to add a navigator

```diff
import {Slot, router} from "expo-router";
import { useEffect } from "react";
import {View, Button} from "react-native";

export default function Layout() {

    const expensiveInitdLoadingTask = async () => {
        console.log("expensiveInitdLoadingTask: ran")
    };

    useEffect(() => {
        expensiveInitdLoadingTask();
    }, []);

    return (
        <View>
            <Button title="Dashboard" onPress={() => router.push("/initd/dashboard")} />
            <Button title="Settings" onPress={() => router.push("/initd/settings")} />
+           <Slot />
        </View>
    )
}
```

I'm going to close this issue, as it resolves the reported issue, but I have a feeling that maybe the example repo misrepresented your issue? If so, please create a new issue with an updated repo

**Closed by marklawlor** 2024-05-29 01:19 UTC
Labels: needs review, Router
