### ISSUE TITLE
[expo-notification] The application is running but the title is not displayed

### ISSUE THREAD

**Issue by onlystard** [expo/expo#13490] opened 2021-07-05 07:46 UTC
### Summary

The application is running but the notification title is not displayed, but when exiting the application the notification works again

![z2588277875340_6ae57de6895a5590aa288d8396406401](https://user-images.githubusercontent.com/38348745/124435757-7eb10100-dd9f-11eb-81a5-ab44d79f4df0.jpg)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

 Expo CLI 4.7.2 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Kay\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ^41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

n

**Comment by cruzach** [comment] 2021-07-07 14:16
Closing because no reproducible demo was provided, can reopen and investigate with a minimal repro

**Closed by cruzach** 2021-07-07 14:16 UTC
Labels: Android, Notifications, needs repro

**Comment by onlystard** [comment] 2021-07-08 01:03
> Closing because no reproducible demo was provided, can reopen and investigate with a minimal repro

what do u need

**Comment by onlystard** [comment] 2021-07-08 06:50
My config 
![image](https://user-images.githubusercontent.com/38348745/124875787-7e10a880-dff3-11eb-84ed-9d87c167a787.png)

**Comment by onlystard** [comment] 2021-07-08 13:52
Sr bro, this project in private, Is there any other solution?

**Comment by cruzach** [comment] 2021-07-08 13:57
Create a new project from scratch with only the code required to reproduce the issue (this will also probably help you in figuring out the root cause if it happens to be an issue with your JS code and not with the Expo SDK)

**Comment by onlystard** [comment] 2021-07-08 14:32
Okey, i will try it
