### ISSUE TITLE
[iOS] [SDK52] Some weird animation happening on inputs and buttons when switching screens

### ISSUE THREAD

**Issue by mbackonja** [expo/expo#33247] opened 2024-11-25 21:11 UTC
### Minimal reproducible example

https://github.com/mbackonja/animation-issue

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

I’m not entirely sure if this issue is related to Expo SDK 52 or the new React Native version, but it was not happening in Expo SDK 51, so I’m posting it here. Please feel free to close this if the issue is more relevant to React Native.

When switching between screens using simple unmount/mount logic like this:
```
      {activeTab === 1 && <TabOne />}
      {activeTab === 2 && <TabTwo />}
```
it seems like Expo (or React Native) is trying to "reuse" some inputs or components in some way.

**Result:** This causes strange animations or transitions between screens (and screen components like TextView or Button)

https://github.com/user-attachments/assets/ebb66e45-2f8d-4edc-b75f-ea72dabb8853

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
      npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
      Watchman: 2024.11.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.11 => 52.0.11
      react: 18.3.1 => 18.3.1
      react-native: 0.76.3 => 0.76.3
    npmGlobalPackages:
      eas-cli: 13.2.3
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Validate packages against React Native Directory package metadata
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by brentvatne** [comment] 2024-12-02 23:43
hi there! if you try this outside of expo go with new arch disabled, can you reproduce it?

**Comment by chrfalch** [comment] 2024-12-13 09:42
I've tested this on Expo Go 2.23.12 and it seems to be working as expected:


https://github.com/user-attachments/assets/7fa6fe6b-0951-4cbe-8763-731d4f3fd4d1

Closing. Please re-open or create new issue if this continues.

**Closed by chrfalch** 2024-12-13 09:42 UTC
Labels: needs review
