### ISSUE TITLE
Image from ImagePicker.launchCameraAsync weirdly cropped when clicked after turning iPad 180 degrees

### ISSUE THREAD

**Issue by RonilM** [expo/expo#20699] opened 2023-01-04 10:41 UTC
### Summary

Photos clicked after launching camera using ImagePicker.launchCameraAsync are weirdly cropped when clicked after turning the iPad by 180 degrees. The top part of the picture is cropped and is replaced by a black fill.

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2 
      babel-preset-expo: ~9.2.0 => 9.2.0 
      expo: ^46.0.0 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 1.1.1
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

const { status } = await ImagePicker.requestCameraPermissionsAsync();
const mediaPermissions = await ImagePicker.requestMediaLibraryPermissionsAsync()

if (status === PERMISSIONS.GRANTED && mediaPermissions.status == PERMISSIONS.GRANTED) {
    let result = await ImagePicker.launchCameraAsync({
        quality: 1,
    });
}

**Comment by brentvatne** [comment] 2023-01-07 00:17
duplicate of https://github.com/expo/expo/issues/19081 and many other similar issues

**Closed** 2023-01-07 00:16 UTC
Labels: needs review
