### ISSUE TITLE
Bug: iOS InAppPurchases - Crash when In App Purchases exist in AppStoreConnect but have been revoked/declined.

### ISSUE THREAD

**Issue by 3mmali** [expo/expo#11010] opened 2020-11-13 00:41 UTC
**In-App Purchases crashes the application when products have been declined/revoked in the App Store.**

This edge case should be handled gracefully by returning an error to the app that can be caught and handled by the developer, rather than crashing the app.

I have a React Native application that was recently ejected from Expo, so it's using the **bare workflow**. This error is only seen on iOS (we have an Android app, but product IDs in Google Play are still in place). Everything was working fine until we tried to submit our app to Apple and it was rejected. When Apple rejected the app, they declined/revoked all of our In-App Purchases and the app started crashing.

So, in order to use In-App Purchasing, you're supposed to first create a connection (which we do successfully and even capture if the user is already connected) and then pull in available products from the App Store. Products need to be pulled in (per [Expo documentation](https://docs.expo.io/versions/latest/sdk/in-app-purchases/)) before a user selects and attempts to purchase them. We are also using the response object to show user's pricing and product titles as pricing could differ depending on the user's country, and the app store handles this for us.

For this particular issue, we're trying to create a subscription. This has to be in-app because we offer a 2-week promotional period. Also, other in-app purchases are broken in the same way.

You are supposed to set up your product ids that you'd like to pull (per OS):
`let itemList = Platform.select({
        ios: [
          'OneMonthSub',
          '1YearMemberSubscription',
        ],
        android: ['1month', '1year'],
      });`

And then you pull the products from the store like this:
`const { responseCode, results } = await InAppPurchases.getProductsAsync(itemList);`

This used to work when we had all products approved in AppStoreConnect. There were absolutely no changes to the application aside from the products being revoked that could've caused this crash. Before products were declined, we were able to pass incorrect product IDs or empty arrays without crashes or failure. This bug should behave the same way. 

**The following line caused the app to crash:**
`const { responseCode, results } = await InAppPurchases.getProductsAsync(itemList);`

I was able to narrow it down to this line by wrapping it in a try/catch statement and placing `console.log()` statements before and after the API call. I can't get to the logs after the call at all, and it's not caught in my try/catch (it should be). It attempts to execute and crashes the application (everything goes white and then the app closes). 

This is the error that XCode reports upon crashing:
`[40534:3608447] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[6]'
*** First throw call stack:
(0x18cb5e5ac 0x1a0c4c42c 0x18cbcd4cc 0x18cbd9608 0x18ca52c8c 0x18ca45840 0x10238b1e4 0x102389604 0x102389bec 0x1a99ba06c 0x108797b68 0x1087995f0 0x10879bf68 0x1087ac2ec 0x1087acc94 0x1d4a4f8cc 0x1d4a5677c)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[6]'
terminating with uncaught exception of type NSException`

In Visual Studio Code, it just reports `ERROR`.

Applicable `package.json` values:
"expo": "^39.0.0",
"expo-in-app-purchases": "^9.1.0",
"react": "16.13.1",
"react-native": "0.63.3"

**Comment by mykolat** [comment] 2020-11-23 16:06
Same for me
Debuging swift code and getting issue in product data formating 

I do receive product so I dont get why it fails here
https://github.com/expo/expo/blame/0751f3b0a71be8e1a5ba4de9757680c46a42c81e/packages/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m#L332

**Comment by ajsmth** [comment] 2020-12-02 00:07
I can confirm that the product has empty fields when its rejected, I managed to fix this in an override by returning empty strings / 0 value numbers for these properties when the accessors in the formatting method mentioned above fails

**Comment by 3mmali** [comment] 2020-12-02 14:36
> I can confirm that the product has empty fields when its rejected, I managed to fix this in an override by returning empty strings / 0 value numbers for these properties when the accessors in the formatting method mentioned above fails. The result is an array after getProductsAsync() with the invalid products missing from this array

The product having empty fields when rejected makes sense! I'm not sure I've seen any documentation where you can override what this method returns unless you're saying this is an update we'll see in a future version. For me, calling the function just crashes and all I was able to pass it was the list of product ids

**Comment by ajsmth** [comment] 2020-12-02 14:38
I am using my own fork of the lib and override on the native side - sorry for confusion!

**Comment by 3mmali** [comment] 2020-12-02 14:40
> I am using my own fork of the lib and override on the native side - sorry for confusion!

That makes sense!! Your solution sounds like it should behave anyway. I would think if a product is revoked it should just not be returned in the array (like you did, similar to if a user inputs an incorrect productId).

**Comment by hardcodet** [comment] 2020-12-16 15:22
This happened to me because my IAP was marked during the review ("An in-app purchase has been returned and is highlighted in the table below." - don't ask me what idiots craft those error messages ;).

While not being a big deal, this causes a hard crash on my app's side. Anybody from expo aware of this? @brentvatne 

Repro on my side is as trivial as it gets:

```
// connect to the store
...
// get products
InAppPurchases.getProductsAsync(items));
```

**Comment by hardcodet** [comment] 2020-12-22 09:13
I _might_ have found a solution. To my surprise, unchecking the "clear for sale" button in Connect seems to have fixed the issue, even after I set the flag again. Let's see whether it makes it through the review. I'll post back here, but may take a while until I get the results due to holidays.

**Comment by dawntommm** [comment] 2021-01-14 05:55
getting same issues here, wondering if theres any solution to it

**Comment by ajsmth** [comment] 2021-01-26 18:21
@dawntommm #6858  i believe this issue has a patch-package solution for this - it also looks like the pr with the fix has been merged!

**Comment by cruzach** [comment] 2021-08-03 21:23
Looks like this was fixed by https://github.com/expo/expo/pull/11523 but never closed, so I'm closing it now. Lmk if you're still seeing this issue!

**Closed by cruzach** 2021-08-03 21:23 UTC
