### ISSUE TITLE
'SplashScreen.show' has already been called for given view controller. && Error: No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.

### ISSUE THREAD

**Issue by haibert** [expo/expo#17589] opened 2022-05-20 22:42 UTC
### Summary

As you can tell from the code I am following the font loading guide provided from Expo and not calling 
``` javascript
            await SplashScreen.hideAsync()
```
twice. 

I have provided a repo that reproduces this issue. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2022.02.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.3 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed

### Reproducible demo

https://github.com/haibert/SplashScreenIssueRepo

**Comment by raajnadar** [comment] 2022-05-21 19:05
Try this https://github.com/expo/expo/issues/17296 maybe the mentioned fix solves the issue for you.

**Comment by haibert** [comment] 2022-05-21 23:19
> Try this https://github.com/expo/expo/issues/17296 maybe the mentioned fix solves the issue for you.

Do you mean this fix ? 

Clear the metro cache
Delete node_modules & yarn.lock file and reinstall the packages
Run ./gradlew clean
Try running code on android studio for any lint issues and any typo. (I had 2 issues)
Make sure EAS & expo cli are at latest version

**Comment by apedroferreira** [comment] 2022-06-10 18:18
same here, and i'm just using `expo-splash-screen` as in the documentation, in a managed app

**Comment by haibert** [comment] 2022-06-11 14:34
@apedroferreira I forgot I had opened an issue about this already, follow this one it's where the discussions are happening https://github.com/expo/expo/issues/14824

**Comment by brentvatne** [comment] 2022-06-28 03:04
closed because duplicate of #14824

**Closed by brentvatne** 2022-06-28 03:04 UTC
Labels: iOS, SplashScreen, needs review, SDK 45
