### ISSUE TITLE
Fatal JS error on Android after auth (causing automatic app refresh)

### ISSUE THREAD

**Issue by smnodame** [expo/expo#880] opened 2017-10-29 20:26 UTC
I set everything like in this example
https://github.com/expo/auth0-example
it works fine in IOS.
but in Android, it refresh everytime after login
which I cannot handle anything after login
Can someone help me TT

**Comment by terribleben** [comment] 2017-10-31 17:19
Hi there, it sounds like you're having an issue with the AuthSession API on Android. Can you explain what you mean by refresh? Do you think you can provide some code to reproduce the behavior you're seeing?

**Comment by mgscreativa** [comment] 2017-11-30 23:24
Hi! the same happens to me! 

With the code from the examples repo from here https://github.com/expo/examples/blob/master/with-facebook-auth/App.js in iOS it works just fine, I can login and see user details on screen, but on android makes the app to refresh! (like refreshing from expo app menu) The app starts running again from the begining as first launch! Like just launched from expo app. 

The refresh is so bad that I can't either get the result of AuthSession.startAsync logged on the console!

Currently I’m using expo v23.0.0 with CRNA created app (but it happens with exp start and expo desktop app)

I have published a test app to expo here https://expo.io/@mgscreativa/with-facebook-auth and it fails as described on android

My android device is Galaxy S4 with android v 4.4.4. iPhone 7+ works just fine.

**Comment by jesseruder** [comment] 2017-11-30 23:25
Sounds like there's a native error and the app is reloading after a crash. Can you post the device logs?

**Comment by mgscreativa** [comment] 2017-11-30 23:29
Please tell me how to look at those device logs on the phone. My Galaxy S4 is rooted. Tanks!

**Comment by mgscreativa** [comment] 2017-11-30 23:57
Found it!, there are lots of this error:

> E/chromium( 8666): [ERROR:android_provider_backend.cc(860)] Can not find favicon's page url

Here's the log from button tap to app starts refresh https://pastebin.com/DbcqzZBR

**Comment by mgscreativa** [comment] 2017-12-01 11:15
I mean, found it...the android device log (using adb shell and logcat), the error persists!. I'm preparing a repo to showcase the issue...

**Comment by mgscreativa** [comment] 2017-12-02 19:50
Hi! Finally I've done it, here's the repo to test https://github.com/mgscreativa/auth-session-expo-v23-issues. The issue appears on old android 4.4 (API 19) as my Galaxy S4 with Android 4.4.4. Tested on brand new Sony Xperia Xa1 (Model G3123 Android 7.0)

Here's a expo test app to try it out https://exp.host/@mgscreativa/authsessionexpov23issues

I don't know if RN and Expo would support such old devices.

Thanks!

**Comment by terribleben** [comment] 2018-01-17 02:36
Updating this and reposting the repro link: https://exp.host/@mgscreativa/authsessionexpov23issues

**Comment by nikoootine** [comment] 2018-04-11 09:29
I'm just wondering if there is a suggested workaround for this one? This is a major blocker for our app as users can't even get passed the login session.

**Comment by nikoootine** [comment] 2018-04-22 16:09
Thanks @esamelson! Just wondering, I've re-attached to Expo recently and tried doing an AuthSession on an Android standalone app. After signing in, it doesn't redirect back to the app. Is this by any chance related to this issue as well?

It worked on iOS standalone app btw but just not one Android.

**Comment by esamelson** [comment] 2018-04-23 19:27
Hi @nikoootine - it's hard to know for sure without more information, but it's certainly plausible that's a symptom of the same issue. Did you defined a valid `scheme` in app.json before running `exp build:android`? If so, I would suggest just upgrading to SDK 27 when it's out (very soon) and seeing if that fixes things.

**Comment by nikoootine** [comment] 2018-04-23 19:54
A scheme is defined in app.json. As like what I said, the redirect works on an iOS standalone just not on Android. Anyways, thanks for the update @esamelson . Looking forward to SDK 27

**Comment by mgscreativa** [comment] 2018-04-23 20:05
Hi! @esamelson and @nikoootine, would you guys be so kind to explain me that sheme thing of app.json...is that needed to use facebook and google login?

Thanks!

**Comment by nikoootine** [comment] 2018-04-23 23:14
@mgscreativa scheme is a url that is used to open your app. This is needed for fb login since you need a redirect scheme, not sure about google

You can read more:
https://docs.expo.io/versions/latest/workflow/linking#content
https://docs.expo.io/versions/v26.0.0/workflow/configuration#schemestandalone-apps-only-url-scheme-to-link

**Comment by mgscreativa** [comment] 2018-04-24 11:07
Great thanks!

**Comment by esamelson** [comment] 2018-04-26 18:49
Closing as this has been fixed with SDK 27 🎉

**Closed** 2018-04-26 18:48 UTC
Labels: project: android-runtime, project: sdk, ready
