### ISSUE TITLE
Live refresh and console.log logging stop working in the expo start server when @babel/plugin-proposal-class-properties is included

### ISSUE THREAD

**Issue by mrflip** [expo/expo#19290] opened 2022-09-28 19:25 UTC
### Summary

With @expo/cli at v0.3.1, I get no console logs and no live refresh (and possibly other maladies, but that's enough.) Attached is a patch to yarn.lock and package.json that turns the following yarn.lock: 

   https://gist.github.com/mrflip/3669852a03f124829d17c456823edd88

from a working state (@expo/cli 0.2.11) to one that doesn't (0.3.1)

I experience this when using expo go or a dev client. I've ripped out every damn thing in sight (see below) figuring this out, but I can switch the problem on and off again by:

* making the change to the package.json alone
* running `yarn install && USE_EXPO_GO=true STAGE=prod BRAND=kiwi npx expo start --ios`

I can give limited access to a private repo if that helps to debug this. My nuke-it-from-orbit-it's-the-only-way-to-be-sure script:

```bash
#!/usr/bin/env bash
SCRIPT_DIR=${SCRIPT_DIR-$(realpath `dirname $0`)}
APP_DIR=${MEARTH_DIR-$(realpath $SCRIPT_DIR/..)}
MEARTH_DIR=${MEARTH_DIR-$(realpath $SCRIPT_DIR/../..)}

set -euo pipefail; trap 'lcmd_=${ccmd_-}; ccmd_=$BASH_COMMAND' DEBUG ; trap 'code_=$?; [ $code_ -ne 0 ] && echo -e "\\n***\\nERR \"${lcmd_}\" failed code $code_, while running $(basename $0); see lines above this"' EXIT

watchman watch-del-all                  || true
rm -fr $TMPDIR/haste-map-*              || true
rm -rf $TMPDIR/metro-cache              || true
rm -rf android/app/build                || true
rm -rf ios                              || true
rm -rf .expo                            || true

echo
echo "  We have cleared all the expo artifacts, but NOT the yarn/npn/node_modules stuff or XCode stuff"
echo
echo "  If the nuke'ing so far doesn't help, quit the simulator and XCode and also run these:"
echo
echo "(cd $APP_DIR;     yarn cache clean; rm -rf package-lock.json node_modules; echo > yarn.lock)"
echo
echo "rm -rf ~/Library/Developer/Xcode/DerivedData || true"
echo "xcrun simctl erase all                       || true"
echo "xcrun simctl list devices"
echo
echo "Then use simctl delete to remove the devices"
echo
echo "  When you are all set, run"
echo ""
echo "(cd $APP_DIR;     yarn install)"
echo "(cd $APP_DIR/ios; pod update)"
echo "(cd $MEARTH_DIR;             yarn ready)"
echo "(cd $APP_DIR;     expo start --dev-client --clear)"
echo
```

### What platform(s) does this occur on?

iOS

### SDK Version

46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.9.0 - /usr/local/bin/node
      Yarn: 3.2.3 - /usr/local/bin/yarn
      npm: 8.19.1 - /usr/local/bin/npm
      Watchman: 2022.09.12.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.0 
      expo: ~46.0.13 => 46.0.13 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

Before (with the resolutions) works, after is broken:

```patch
quickbeam 20220922-flip-PeregrinPhoenix ~/code/mearth/zumthor$ git diff HEAD
diff --git a/package.json b/package.json
index 996ef53..0feec96 100644
--- a/package.json
+++ b/package.json
@@ -16,9 +16,6 @@
   },
   "resolutions": {
     "expo-font": "~10.2.0",
-    "expo-cli": "0.2.11",
-    "@expo/cli": "0.2.11",
-    "@expo/dev-server": "0.1.119",
     "react-native-safe-area-context": "4.3.1",
     "husky": "4.3.8"
   },
diff --git a/yarn.lock b/yarn.lock
index ff8e5e7..f9358df 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -4680,18 +4680,18 @@ __metadata:
   languageName: node
   linkType: hard
 
-"@expo/cli@npm:0.2.11":
-  version: 0.2.11
-  resolution: "@expo/cli@npm:0.2.11"
+"@expo/cli@npm:0.3.1":
+  version: 0.3.1
+  resolution: "@expo/cli@npm:0.3.1"
   dependencies:
     "@babel/runtime": ^7.14.0
     "@expo/code-signing-certificates": ^0.0.2
     "@expo/config": ~7.0.1
     "@expo/config-plugins": ~5.0.1
-    "@expo/dev-server": ~0.1.119
+    "@expo/dev-server": ~0.1.120
     "@expo/devcert": ^1.0.0
     "@expo/json-file": ^8.2.35
-    "@expo/metro-config": ~0.3.18
+    "@expo/metro-config": ~0.4.0
     "@expo/osascript": ^2.0.31
     "@expo/package-manager": ~0.0.53
     "@expo/plist": ^0.0.18
@@ -4746,7 +4746,7 @@ __metadata:
     wrap-ansi: ^7.0.0
   bin:
     expo-internal: build/bin/cli
-  checksum: f5ac9815e98f5ad068f3b612ff8a117dd43d0432a209e0aa6f369de404e7698b22dd2f07ab16e67a5f87f95a60e76e02652d8d736dd358c2d6504281fa48666b
+  checksum: c2b75359bd0437992e4a0693ac1deff48e731acfdfc7ac9c70dbfe648f78baed763a9e7bf694a1027e302f4d969a43c82ef2bdd10e86262da17e686a465489a2
   languageName: node
   linkType: hard
 
@@ -4828,12 +4828,12 @@ __metadata:
   languageName: node
   linkType: hard
 
-"@expo/dev-server@npm:0.1.119":
-  version: 0.1.119
-  resolution: "@expo/dev-server@npm:0.1.119"
+"@expo/dev-server@npm:~0.1.120":
+  version: 0.1.120
+  resolution: "@expo/dev-server@npm:0.1.120"
   dependencies:
     "@expo/bunyan": 4.0.0
-    "@expo/metro-config": ~0.3.18
+    "@expo/metro-config": ~0.4.0
     "@expo/osascript": 2.0.33
     body-parser: 1.19.0
     chalk: ^4.0.0
@@ -4845,7 +4845,7 @@ __metadata:
     semver: 7.3.2
     serialize-error: 6.0.0
     temp-dir: ^2.0.0
-  checksum: 1b80fef6e36ca9aba7eb6c3443873de2a137ea9d4fac8475c940a6aa6e35380594484296d283f099a0d4c6bb0dc36b42c1edc2a47f4a258e1168afb9d9c30679
+  checksum: cc4e42203a4dfaf1d0d0b165ec147bd98840eaad697d8f97a41fed28c38459f8d3800475fbf7f0ef83af23ce050881c13817daba7ccea4f9d201f425607d6b5d
   languageName: node
   linkType: hard
 
@@ -4900,22 +4900,6 @@ __metadata:
   languageName: node
   linkType: hard
 
-"@expo/metro-config@npm:~0.3.18":
-  version: 0.3.22
-  resolution: "@expo/metro-config@npm:0.3.22"
-  dependencies:
-    "@expo/config": 7.0.1
-    "@expo/json-file": 8.2.36
-    chalk: ^4.1.0
-    debug: ^4.3.2
-    find-yarn-workspace-root: ~2.0.0
-    getenv: ^1.0.0
-    resolve-from: ^5.0.0
-    sucrase: ^3.20.0
-  checksum: f0084def2a88fde7aba6044e1680af5e4dfd0f5d201cc2f6402f1febfc2e2f5c489f43fa98792993622e045c2a503a694115c7d469b91bc985126253962ca6ba
-  languageName: node
-  linkType: hard
-
 "@expo/metro-config@npm:~0.4.0":
   version: 0.4.0
   resolution: "@expo/metro-config@npm:0.4.0"
```

**Comment by brentvatne** [comment] 2022-09-30 22:27
hi @mrflip! thank you for the detailed (and humorous) issue report.

i have confirmed that this is indeed occurring, and i also tried it in a new react native app without any expo tools installed and confirmed that it has the same behavior there. i suspect what is happening here is that using this plugin against the internals of react native makes some unexpected transformation that breaks the intended behavior. unfortunately, react native ships untranspiled, and so the same babel transforms that you use on your app code are also used on the react-native code.

there is nothing we can do about it within this repository, but you may want to create an issue on https://github.com/facebook/react-native/issues about. to be frank, i think it's unlikely someone will get to resolving it soon because there are many other higher priorities for the team, so if you do want to dig in deeper and send a pr that would be the best way to move it forward. until then, you may need to avoid using this babel plugin.

cheers

**Closed by brentvatne** 2022-09-30 22:27 UTC
Labels: needs review, CLI
