### ISSUE TITLE
Crash -> SDK 35 ClassNotFoundException: ...SharedCookiesDataSourceFactoryProvider

### ISSUE THREAD

**Issue by briefjudofox** [expo/expo#6206] opened 2019-11-07 22:54 UTC
### Environment

```
  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v12.6.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.4.1
```
Targeting ejected Android (expokit).  This happened after we upgraded to SDK35.  I'd never seen this before on previous versions.

### Steps to Reproduce

😬 I don't have a reproducible case to share, but it seems like this happened when our app was in the background or closed and was trying to respond to a background task (see `TaskBroadcastReceiver`).  After an attempt to bring up the headless app, I saw the crash dialog.  This happened to me several times in a short period.  

### Expected Behavior

The app should be able come up in a headless state and do work in the background.

### Actual Behavior

Crash.  Here's the stack:
```2019-11-06 17:05:52.534 1278-1320/? I/ActivityManager: Killing 19271:com.acme.app/u0a341 (adj 900): excessive cpu 39530 during 300127 dur=721859 limit=10
2019-11-06 17:05:52.660 1278-3692/? I/WindowManager: WIN DEATH: Window{3a404f9 u0 com.acme.app/host.exp.exponent.MainActivity}
2019-11-06 17:52:44.384 1278-1321/? I/ActivityManager: Start proc 30495:com.acme.app/u0a341 for broadcast {com.acme.app/expo.modules.taskManager.TaskBroadcastReceiver}
2019-11-06 17:52:44.709 30495-30522/? I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.acme.app
2019-11-06 17:52:44.720 30495-30495/? D/SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.acme.app-YRJptJBcnJ3W8EbF_4rPTg==/lib/arm64 flags = 0]
2019-11-06 17:52:44.721 30495-30495/? D/SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/com.acme.app/lib-main flags = 1]
2019-11-06 17:52:44.722 30495-30495/? D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.acme.app-YRJptJBcnJ3W8EbF_4rPTg==/lib/arm64 flags = 0]
2019-11-06 17:52:44.723 30495-30495/? D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.acme.app/lib-main flags = 1]
2019-11-06 17:52:44.723 30495-30495/? V/fb-UnpackingSoSource: locked dso store /data/user/0/com.acme.app/lib-main
2019-11-06 17:52:44.731 30495-30495/? I/fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.acme.app/lib-main
2019-11-06 17:52:44.731 30495-30495/? V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.acme.app/lib-main
2019-11-06 17:52:44.906 2645-2847/? I/GeofencerStateMachine: addGeofences called by com.acme.app
2019-11-06 17:53:16.762 30495-30699/? D/SoLoader: libreactnativejni.so not found on /data/data/com.acme.app/lib-main
2019-11-06 17:53:16.762 30495-30699/? D/SoLoader: libreactnativejni.so found on /data/app/com.acme.app-YRJptJBcnJ3W8EbF_4rPTg==/lib/arm64
2019-11-06 17:53:16.809 30495-30699/? D/SoLoader: libfb.so not found on /data/data/com.acme.app/lib-main
2019-11-06 17:53:16.809 30495-30699/? D/SoLoader: libfb.so found on /data/app/com.acme.app-YRJptJBcnJ3W8EbF_4rPTg==/lib/arm64
2019-11-06 17:53:16.810 30495-30699/? D/SoLoader: libfb.so not found on /data/data/com.acme.app/lib-main
2019-11-06 17:53:16.810 30495-30699/? D/SoLoader: libfb.so found on /data/app/com.acme.app-YRJptJBcnJ3W8EbF_4rPTg==/lib/arm64
2019-11-06 17:53:16.810 30495-30699/? I/ksoinc.rivet_r: Thread[5,tid=30699,Native,Thread*=0x7496c97800,peer=0x12dc0018,"create_react_context"] recursive attempt to load library "/data/app/com.acme.app-YRJptJBcnJ3W8EbF_4rPTg==/lib/arm64/libfb.so"
2019-11-06 17:53:16.812 30495-30699/? D/SoLoader: libjscexecutor.so not found on /data/data/com.acme.app/lib-main
2019-11-06 17:53:16.812 30495-30699/? D/SoLoader: libjscexecutor.so found on /data/app/com.acme.app-YRJptJBcnJ3W8EbF_4rPTg==/lib/arm64
2019-11-06 17:53:16.853 30495-30699/? E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.acme.app, PID: 30495
    java.lang.NoClassDefFoundError: Failed resolution of: Lexpo/modules/av/player/datasource/SharedCookiesDataSourceFactoryProvider;
        at versioned.host.exp.exponent.ExponentPackage.createDefaultModuleRegistryAdapterForPackages(ExponentPackage.java:230)
        at versioned.host.exp.exponent.ExponentPackage.<init>(ExponentPackage.java:99)
        at versioned.host.exp.exponent.VersionedUtils.getReactInstanceManagerBuilder(VersionedUtils.java:17)
        at java.lang.reflect.Method.invoke(Native Method)
        at host.exp.exponent.RNObject.callWithReceiver(RNObject.java:162)
        at host.exp.exponent.RNObject.call(RNObject.java:113)
        at host.exp.exponent.RNObject.callRecursive(RNObject.java:117)
        at host.exp.exponent.headless.HeadlessAppLoader.startReactInstance(HeadlessAppLoader.java:300)
        at host.exp.exponent.headless.HeadlessAppLoader.access$1200(HeadlessAppLoader.java:46)
        at host.exp.exponent.headless.HeadlessAppLoader$4.onSuccess(HeadlessAppLoader.java:270)
        at host.exp.expoview.Exponent.testPackagerStatus(Exponent.java:628)
        at host.exp.exponent.headless.HeadlessAppLoader.startReactInstance(HeadlessAppLoader.java:267)
        at host.exp.exponent.headless.HeadlessAppLoader.access$600(HeadlessAppLoader.java:46)
        at host.exp.exponent.headless.HeadlessAppLoader$3.execute(HeadlessAppLoader.java:200)
        at host.exp.exponent.utils.AsyncCondition.notify(AsyncCondition.java:48)
        at host.exp.exponent.headless.HeadlessAppLoader$2.run(HeadlessAppLoader.java:183)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: expo.modules.av.player.datasource.SharedCookiesDataSourceFactoryProvider
        at versioned.host.exp.exponent.ExponentPackage.createDefaultModuleRegistryAdapterForPackages(ExponentPackage.java:230) 
        at versioned.host.exp.exponent.ExponentPackage.<init>(ExponentPackage.java:99) 
        at versioned.host.exp.exponent.VersionedUtils.getReactInstanceManagerBuilder(VersionedUtils.java:17) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at host.exp.exponent.RNObject.callWithReceiver(RNObject.java:162) 
        at host.exp.exponent.RNObject.call(RNObject.java:113) 
        at host.exp.exponent.RNObject.callRecursive(RNObject.java:117) 
        at host.exp.exponent.headless.HeadlessAppLoader.startReactInstance(HeadlessAppLoader.java:300) 
        at host.exp.exponent.headless.HeadlessAppLoader.access$1200(HeadlessAppLoader.java:46) 
        at host.exp.exponent.headless.HeadlessAppLoader$4.onSuccess(HeadlessAppLoader.java:270) 
        at host.exp.expoview.Exponent.testPackagerStatus(Exponent.java:628) 
        at host.exp.exponent.headless.HeadlessAppLoader.startReactInstance(HeadlessAppLoader.java:267) 
        at host.exp.exponent.headless.HeadlessAppLoader.access$600(HeadlessAppLoader.java:46) 
        at host.exp.exponent.headless.HeadlessAppLoader$3.execute(HeadlessAppLoader.java:200) 
        at host.exp.exponent.utils.AsyncCondition.notify(AsyncCondition.java:48) 
        at host.exp.exponent.headless.HeadlessAppLoader$2.run(HeadlessAppLoader.java:183) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2019-11-06 17:53:17.836 1278-1312/? I/ActivityManager: Showing crash dialog for package com.acme.app u0
2019-11-06 17:54:24.762 1278-3692/? E/InputDispatcher: Window handle Window{4d4954a u0 Application Error: com.acme.app} has no registered input channel
2019-11-06 17:54:24.778 1278-3688/? I/ActivityManager: Process com.acme.app (pid 30495) has died: cch+15 CEM 
2019-11-06 17:54:24.864 30047-30047/? I/Finsky: [2] com.google.android.finsky.activities.AppCrashProxy.onCreate(16): Sending feedback for crashed com.acme.app to com.google.android.gms
```

### Reproducible Demo
Sorry.  This one is tricky to reproduce, but I think the stack describes it. 

I see that [ExpoModuleRegistryAdapter](https://github.com/expo/expo/blob/eda7dbdba31fb4edc838f6c8f5ef36b56e8a0579/android/expoview/src/main/java/versioned/host/exp/exponent/modules/universal/ExpoModuleRegistryAdapter.java#L48) imports and uses [SharedCookiesDataSourceFactoryProvider](https://github.com/expo/expo/blob/eda7dbdba31fb4edc838f6c8f5ef36b56e8a0579/android/versioned-abis/expoview-abi33_0_0/src/main/java/abi33_0_0/host/exp/exponent/modules/universal/av/SharedCookiesDataSourceFactoryProvider.java#L13) which extends `expo.modules.av.player.datasource.SharedCookiesDataSourceFactoryProvider` which is in the expo-av module and not included by default.  Could this be the issue?

In an attempt to work around this I added `expo-av` via `yarn add expo-av` and I can now see that module and the class in question.  After syncing gradle everything seems happy.  If I see the crash again I'll update here.  

I also wonder if this issue could be related: https://github.com/expo/expo/issues/5542

**Comment by alexbuicescu** [comment] 2019-11-08 16:47
We also experience the same problem (similar logcat), I think it's been a few months since we first noticed (not sure about this, but it was some time ago). It happens very often in our end to end tests when the app crashes unexpectedly. And no matter we do, there is no way to bring up the app again (both closing the app and force stopping it won't work). Our only option was to clear the storage/cache of the app and then it would work again. It happens on both release and debug .apks. We also have a background task (location tracking) and are using an ejected app (using expokit)

**Comment by briefjudofox** [comment] 2019-11-08 17:07
Hi @alexbuicescu , did you try adding the `expo-av` to your ejected build?

**Comment by alexbuicescu** [comment] 2019-11-08 17:46
I just did (saw that you suggested it in your comment). I'll come back with updates if this still manifests (it happens daily, so hopefully by monday I'll have an answer)

**Comment by briefjudofox** [comment] 2019-11-08 17:50
@alexbuicescu great.  Keep me posted.

**Comment by alexbuicescu** [comment] 2019-11-11 12:18
It looks like the problem is gone, but now the app started to crash with something related to expo-secure-store, so I also did a npm install for it, and again it seems to not happen anymore. The odd thing is that we don't even use expo-av or expo-secure-store and it is really weird to have to install them only to prevent random crashes. The app shouldn't have compiled in the first place.

**Comment by briefjudofox** [comment] 2019-11-12 00:23
Hi @alexbuicescu we also do not use `expo-av`.  We do use `expo-secure-store` so we already had that as a dependency.  I'm guessing these modules were not intended to be required?  @cruzach , any thoughts on this one?

**Comment by EKoetsjarjan** [comment] 2019-11-12 09:28
did you tried deleting the android/build folder, and rebuilding again?

**Comment by alexbuicescu** [comment] 2019-11-12 12:11
@EKoetsjarjan yes, we remove the android/app/build folder every time we build an app

**Comment by tsapeta** [comment] 2020-07-09 09:07
Because of inactivity for longer period of time and the fact that we no longer support ejecting to ExpoKit, I'm gonna close this issue. I recommend migrating your apps to managed or bare workflow instead, and if it still happens to you reopen a new bug report with some more and up-to-date details.

**Closed by tsapeta** 2020-07-09 09:07 UTC
Labels: Android, ExpoKit, bug
