### ISSUE TITLE
problem with victory-native and react-native-svg

### ISSUE THREAD

**Issue by robertobrogi** [expo/expo#1422] opened 2018-02-14 15:04 UTC
Hi, I have a problem with EXPo 25.0.0 and victory-native 0.17.1....

EXPO used react-native-svg 5.5.1 but victory-native need a react-native-svg > 6.0.0

if i try update the "react-native-svg": "https://github.com/expo/react-native-svg/archive/5.5.1-exp.1.tar.gz" with latest version in node_modules espo folder the app crash...

there is any update version?

Thanks

**Comment by esamelson** [comment] 2018-02-15 18:32
Hi there - we're working on an update for `react-native-svg` in SDK 26, which should be out soon. In the meantime, you'll just need to downgrade `victory-native`. You probably already saw the responses to your comment in #1393 but referencing them here in case you did not. Going to close this as a duplicate of that issue.

**Closed by esamelson** 2018-02-15 18:32 UTC
