### ISSUE TITLE
[SDK49.0.2][expo-blur] BlurView with reanimated doesn't render correctly 

### ISSUE THREAD

**Issue by Nasseratic** [expo/expo#23539] opened 2023-07-14 15:44 UTC
### Minimal reproducible example

https://github.com/Nasseratic/react-native-hold-menu-upgrade-expo-49/pull/1

### Summary

The latest `expo-blur 12.4.1` doesn't animate with `react-native-reanimated 3.3.0`

I am trying to upgrade [react-native-hold-menu](https://github.com/enesozturk/react-native-hold-menu) to expo 49. But the backdrop using ExpoBlur + Reanimated. Dosn't render correctly anymore. 

This library is used to animate position and opacity. I removed opacity as mentioned [here](https://github.com/expo/expo/pull/22783#issuecomment-1606149821) but that didn't work.
So I think the issue is with Animating the `top` position. Same for any transforming. 

Please check `src/components/backdrop/Backdrop.tsx`

To reproduce:
```
npm i
cd example
npm i
npm start
```
Open the project and select WhatsApp

https://github.com/expo/expo/assets/18466484/43f18d81-edb6-464b-bb60-6af111175a84

### Environment

System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
      Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 32
        Build Tools: 32.0.0, 32.1.0
        System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
    npmGlobalPackages:
      eas-cli: 3.15.0
    Expo Workflow: managed

**Comment by behenate** [comment] 2023-07-21 09:07
@Nasseratic Hi, we changed the way the animated props are passed to the blur view and that's why you are experiencing the issue, for now I would suggest wrapping the `BlurView` into `Animated.View` and applying the `opacity` and `top` animations to the view and the `intensity` animations to the `BlurView` until we can resolve the issue 

From `Backdrop.tsx`
```javascript
    <Animated.View style={[styles.container, animatedContainerStyle]}>
        <AnimatedBlurView
          // @ts-ignore
          tint="default"
          animatedProps={animatedContainerProps}
          style={[styles.container]}
        >
          <Animated.View
            style={[{ ...StyleSheet.absoluteFillObject }, animatedInnerContainerStyle]}
          />
        </AnimatedBlurView>
    </Animated.View>```

**Comment by lukmccall** [comment] 2023-07-28 12:40
The above snippet fixes the problem. I'll close the issue for now. However, if you still face problems, feel free to open a new one.

**Closed by lukmccall** 2023-07-28 12:40 UTC
Labels: needs review

**Comment by Nasseratic** [comment] 2023-07-28 13:42
Just tried it! It works!! Thanks a lot ❤️

**Comment by FlemingVincent** [comment] 2023-07-29 16:51
@Nasseratic Were you ever able to get react-native-hold-menu working as intended in Expo 49?

**Comment by Nasseratic** [comment] 2023-07-31 07:12
Most of it Yes. At least this issue.
But there is another problem related to reanimated (a function reference is always just an empty object). Need to wait a bit to get a newer version of expo-dev-client so I can upgrade to reanimated v3.4.0 ( which has the fix ) 
Then will open a pr  with the fixes on `react-native-hold-menu` as soon as possible

**Comment by VadymBezsmertnyi** [comment] 2023-08-06 21:03
In the Android Studio simulator, after updating "expo-blur": "~12.4.1", the application completely crashed even without starting due to "expo": "^49.0.6". The application does not crash, but now BlurView does not work, you can replace it with something else:
`//
TODO
      <Animated.View>
        <BlurView
          intensity={intensityShow}
          style={StyleSheet.flatten([
            styles.blurStyle,
            styles.blurStyleApp,
            !isOpacityType ? styles.fullOpacity : null,
          ])}
        >
          <Animated.View />
        </BlurView>
      </Animated.View>
      `
      
      My package.json:
      `
      {
  "name": "motonavigation",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "set NODE_OPTIONS=--openssl-legacy-provider && expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "start_server": "nodemon server/server.ts",
    "lingui:add": "lingui add-locale",
    "lingui:extract": "lingui extract --clean",
    "lingui:compile": "lingui compile --typescript",
    "lingui:compile:ci": "lingui compile --strict",
    "svgr": "svgr",
    "icons": "svgr -d src/icons/components src/icons/svg --template src/icons/icon-template.js --typescript --native --no-dimensions",
    "build:icons": "svgr -d src/icons/components src/icons/svg --template src/icons/icon-template.js --typescript --no-dimensions --prettier-config .prettierrc --svgo-config svgo.config.js --no-index",
    "eslint": "eslint --max-warnings=500 --quiet --ext .js,.jsx,.ts,.tsx,.mjs 'src/**/*' --cache --cache-location './node_modules/.cache/eslint/.eslintcache'",
    "eslint:warning": "eslint --max-warnings=500 --ext .js,.jsx,.ts,.tsx,.mjs 'src/**/*' --cache --cache-location './node_modules/.cache/eslint/.eslintcache'",
    "eslint:ci": "npm run eslint -- --quiet"
  },
  "dependencies": {
    "@babel/plugin-transform-typescript": "^7.22.3",
    "@babel/preset-env": "^7.22.2",
    "@babel/preset-typescript": "^7.21.5",
    "@expo/config-plugins": "~7.2.2",
    "@getify/eslint-plugin-proper-arrows": "^11.0.3",
    "@lingui/cli": "^4.3.0",
    "@lingui/conf": "^4.3.0",
    "@lingui/macro": "^4.3.0",
    "@lingui/react": "^4.3.0",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@svgr/core": "^7.0.0",
    "@types/react": "~18.2.14",
    "@typescript-eslint/eslint-plugin": "^5.59.8",
    "@typescript-eslint/parser": "^5.59.8",
    "@typescript-eslint/utils": "^5.59.7",
    "axios": "^1.3.4",
    "bcrypt": "^5.1.0",
    "classnames": "^2.3.2",
    "cors": "^2.8.5",
    "country-telephone-data": "^0.6.3",
    "dotenv": "^16.1.4",
    "eslint": "^8.41.0",
    "eslint-config-memcrab": "^2.0.3",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jsdoc": "^45.0.0",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-no-loops": "^0.3.0",
    "eslint-plugin-only-warn": "^1.1.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-perf": "^3.3.1",
    "expo": "^49.0.6",
    "expo-application": "~5.3.0",
    "expo-auth-session": "~5.0.2",
    "expo-blur": "~12.4.1",
    "expo-build-properties": "~0.8.3",
    "expo-crypto": "~12.4.1",
    "expo-google-app-auth": "~8.3.0",
    "expo-linear-gradient": "~12.3.0",
    "expo-local-authentication": "~13.4.1",
    "expo-localization": "~14.3.0",
    "expo-location": "~16.1.0",
    "expo-random": "~13.2.0",
    "expo-status-bar": "~1.6.0",
    "expo-web-browser": "~12.3.2",
    "express": "^4.18.2",
    "jest": "^29.2.1",
    "jsonwebtoken": "^9.0.0",
    "mongoose": "^7.0.2",
    "pino": "^8.11.0",
    "prettier": "^2.8.8",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.3",
    "react-native-config": "^1.5.0",
    "react-native-confirmation-code-field": "^7.3.1",
    "react-native-country-flag": "^1.1.9",
    "react-native-fbsdk-next": "^11.2.1",
    "react-native-path": "^0.0.5",
    "react-native-phone-input": "^1.3.7",
    "react-native-root-toast": "^3.4.1",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-svg": "13.9.0",
    "react-native-web": "~0.19.6",
    "react-router-dom": "^6.10.0",
    "setimmediate": "^1.0.5",
    "ts-node": "^10.9.1",
    "twilio": "^4.11.2",
    "typescript": "^5.1.3",
    "unraw": "^3.0.0",
    "uuid": "^9.0.0",
    "zod": "^3.21.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@svgr/cli": "^7.0.0",
    "@types/bcrypt": "^5.0.0",
    "@types/cors": "^2.8.13",
    "@types/country-telephone-data": "^0.6.1",
    "@types/debug": "^4.1.8",
    "@types/jsonwebtoken": "^9.0.2",
    "babel-plugin-macros": "^3.1.0",
    "babel-plugin-module-resolver": "^5.0.0",
    "react-native-dotenv": "^3.4.8"
  },
  "private": true
}

      `
