### ISSUE TITLE
Screen freezes when navigating back and forth between screens inside tab screen

### ISSUE THREAD

**Issue by mlalitthapa** [expo/expo#33398] opened 2024-12-03 14:59 UTC
### Minimal reproducible example

https://github.com/mlalitthapa/navigation-sample

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

https://github.com/user-attachments/assets/66e432a6-6c3d-4b83-9524-c1fdce48a073

I have a simple tab layout with two tabs Home and Settings. Inside settings I have stack screens of index and security screen. Here are the steps to replicate the issue as shown in the video above.

1. Go to settings tab.
2. Click on the `Go to security settings`.
3. Click on the `Go to settings page`.
4. Repeat step 2 and 3 few times then you can no longer click the texts or any other pressable elements in the screen.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.12.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
      Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 33, 34, 35
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 33.0.3, 34.0.0, 35.0.0
        System Images: android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.11 => 52.0.11 
      expo-router: ~4.0.9 => 4.0.9 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 12.3.0
    Expo Workflow: managed
```

**Comment by mlalitthapa** [comment] 2024-12-06 11:57
Thanks @marklawlor for looking into this.

I am using iPhone 15 simulator with IOS 17.4. Here is the device info.
<img src="https://github.com/user-attachments/assets/05121769-774b-4713-8087-91aeae9be5a6" width="200" />

I tried by clearing the simulator data and metro cache but still having the same issue. I also tried this in an android emulator and have the same issue. Here is the android emulator device info.
<img src="https://github.com/user-attachments/assets/711d32e1-e045-4df3-9ae7-685581c0d97c" width="200" />

I have the same issue even with my physical android device.

**Comment by mountainash** [comment] 2024-12-06 12:01
I'm also experiencing this as @mlalitthapa is - also on device using Expo Go.

**Comment by marklawlor** [comment] 2024-12-12 12:26
I'm having trouble replicating this issue, and this issue is receiving minimal public reaction (no reactions, comments) which suggests this may be a machine specific issue.

Expo Router wraps React Navigation, who build and maintain the Tab component. Normally I replicate the problem and create the issue in the React Navigation repro for you, but since I'm unable to replicate the issue it makes it difficult for me to be the man-in-the-middle.

I'm going to close this issue and ask that you create an issue in the React Navigation [repro](https://github.com/react-navigation/react-navigation), so the maintainers of that component can provide better troubleshooting than I can.

**Closed by marklawlor** 2024-12-12 12:26 UTC
Labels: needs more info, Router

**Comment by mountainash** [comment] 2024-12-13 11:14
@mlalitthapa I swapped out the use of `<Link href="` for `onPress={() => router.push('/path')}` on the child element and found this to make my similar problem go away.

**Comment by mlalitthapa** [comment] 2024-12-13 14:21
@mountainash Yes using `.push` works but I don't want to always push the screens on top.

@marklawlor I have opened a new issue with reproduction - https://github.com/expo/expo/issues/33658

**Comment by marklawlor** [comment] 2024-12-16 21:14
Confirmed issue, please follow #33658 for updates
