### ISSUE TITLE
Updates.checkForUpdateAsync() crashes when phone disk space is full

### ISSUE THREAD

**Issue by Aryk** [expo/expo#10623] opened 2020-10-09 15:54 UTC
I use polling (every minute) to determine if I should auto-download a new revision for the user. 

I got 40,000 Sentry errors over the past few days because of this issue:

Could not write to path /var/mobile/Containers/Data/Application/A4BE71DA-1234-4043-AC73-D14E491234C0B/Library/Application Support/.expo-internal/manifestPublicKey.pem: You can’t save the file “manifestPublicKey.pem” because the volume “Data” is out of..."

I spoke with @cruzach about it and he said that it was coming from some file "crypto.m" file or something like that (sorry he told me on our call but my memory faded :) ).

In any case, I don't think if the user is out of space on their phone (which is *very* common), that this call should error on it. So I think either:

1) Have it continue erroring out but add to the documentation that for Updates that this can occur so we code around it.
2) Modify Updates.checkForUpdateAsync so that it doesn't need to write to a file.
3) Have it not throw an error but return a value of "diskFull: true" so that users can check for that and know that the check didn't happen.

Managed 39.0 SDK

**Comment by cruzach** [comment] 2020-10-09 16:05
Thanks @Aryk ! It looks like this could be stemming from [this block](https://github.com/expo/expo/blob/master/packages/expo-updates/ios/EXUpdates/AppLoader/EXUpdatesCrypto.m#L61-L72), but I'm not 100% sure, will leave that to @esamelson 👍

**Comment by Aryk** [comment] 2020-10-12 10:51
@cruzach, @esamelson  - I am now getting flooded from the same call with "Manifest verification failed" (on checkforUpdatesAsync). Do you think this is related? Or should I file another ticket?

**Comment by esamelson** [comment] 2020-10-13 21:26
Thanks for the report, @Aryk -- we'll look into this as soon as we can. Regarding the new issue with "Manifest verification failed", if you are able to find a way to consistently reproduce the issue, it would be really helpful if you could open a new ticket and provide that information!

**Comment by changLiuUNSW** [comment] 2020-11-05 23:06
Our Sentry also gets flooding with all these errors, but I cant reproduce on my machine.
![image](https://user-images.githubusercontent.com/7379922/98306263-94ef9d00-2017-11eb-9f06-0ddc8d046931.png)

**Comment by ide** [comment] 2021-02-17 07:14
Closing as the cause of this instance of the problem should have been resolved.

**Closed by ide** 2021-02-17 07:14 UTC
Labels: Updates, iOS

**Comment by ceafive** [comment] 2022-09-06 08:31
It has not been resolved. I just got this error in Sentry on an iPhone 11

<img width="846" alt="Screenshot 2022-09-06 at 8 30 56 AM" src="https://user-images.githubusercontent.com/43540435/188586831-f7093d88-29d6-43c4-8aa4-9a7718424385.png">
