### ISSUE TITLE
[Expo 49, Router v2] Functions/API Fetching Blocks UI Intractability 

### ISSUE THREAD

**Issue by kennethstarkrl** [expo/expo#24579] opened 2023-09-22 19:43 UTC
### Minimal reproducible example

https://github.com/kennethstarkrl/expo-49-router-v2-func-fetch-blocks-ui
repo is basically fresh `npx create-expo-app@latest --template tabs@49`

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I've been upgrading my app from Expo 47 to Expo 49 and am running into some performance issues. Normally I do a fetch API request in a useEffect on a screen to load data. In Expo 47 Screen navigation can continue while one screen is fetching data/ running a function. In the minimal reproduceable example, its merely a function that runs a while loop and counts to 100k. The results are the same for doing a fetch req.

```js
export default function TabOneScreen() {
  const [myData,setMyData] = useState('');
  const loadData = () =>{
    let data = 0;
    while(data < 150000){
      data = data+1;
      console.log(data);
    }
    setMyData(data);
  }
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Tab One</Text>
      <View style={styles.separator} lightColor="#eee" darkColor="rgba(255,255,255,0.1)" />
      <TouchableOpacity onPress={()=>loadData()}>
      <Text style={[styles.title,{maxWidth:300}]}>Press here to load data, then click the modal 'Open while loading' in the top right or try navigating to other tabs</Text>
      </TouchableOpacity>
      <Text style={{color:'white'}}>{myData ? myData : ''}</Text>
    </View>
  );
}
```

It seems in Expo 49 with Expo Router v2, the whole UI is blocked until the fetch/function finishes. Really no difference on how I fetch data from 47 to 49, with the exception now it's file based routing for screens. Could be related to some of the performance regression others are having with Expo 49 here: https://github.com/expo/expo/issues/24537

I have an Expo 47 app in prod running the same fetch API requests in the same way with no UI blocking. Unfortunately I can't provide the repo for that. 

Figured I'd just report my findings. Side note I've also found using Hermes things like JSON.stringify() and Date() calculations are dramatically slower than before, but that's an issue with Hermes.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.8.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~49.0.11 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.9
    Expo Workflow: managed

**Comment by marklawlor** [comment] 2023-09-25 02:11
I'm interested in investigating this, but your reproduction does not seem to reflect your reported issue.

JavaScript is single threaded, so running a looping `while()` loop will block UI events. This is true for all React (both Native and Web) apps. You can also observe this with vanilla JavaScript:

```html
<div onclick="javascript:data = 0;while(data < 150000){data = data+1;console.log(data);}">start loop</div>
<div onclick="javascript:console.log('clicked');">While loop is running, clicking this will queue the events. Logs will not appear until after the loop has finished</div>
```

I'm going to close this issue as there's not enough information here for me to investigate, but I would really love to so if you comment back with a reproduction I'll reopen the issue.

**Closed by marklawlor** 2023-09-25 02:11 UTC
Labels: needs review, Router

**Comment by kennethstarkrl** [comment] 2023-09-25 21:53
@marklawlor Ok yea the while loop is a bad example it occurs when I do a fetch inside a useEffect.
```js
  useEffect(()=>{
    const loadData = () => {
        setIsLoading(true);
        const controller = new AbortController();
        const body = new FormData();
        fetch(`https://someapp.com/api/data`,{
            method:'POST',
            body:body,
            signal: controller.signal,
        })
        .then((res)=>res.json())
        .then((json)=>setMyData(json))
        .finally(()=>{setIsLoading(false)})
        .catch((error)=>{
            if(error.name === 'AbortError'){}
            else{console.log(error)}
        });
        return () => {
            controller.abort();
        }
    }
    loadData();
  },[]);
```

 I forgot to mention that I was only experiencing this running it in Expo Go on Android. Web works fine. Since I was having the issues running with `npx expo start --no-dev` I have not been able to test it with no dev mode on Android so it's very possible and probable that it's slower because it's in dev mode. Once I am able to run it out of dev mode on Android I'll let you know if I still experience this. Thanks for your help!

**Comment by kennethstarkrl** [comment] 2023-09-25 22:44
@marklawlor I ran my app in the Android simulator with --no-dev and the lag is much reduced, but it's still there somewhat. I was able to record it happening. Don't mind the minor UI flashes that the simulator acting up because show taps is enabled, it doesn't do that without it.


https://github.com/expo/expo/assets/53270830/f20711eb-cdc1-4b2c-9d50-0c4d00aec88c

**Comment by marklawlor** [comment] 2023-09-26 01:27
Can you please provide a MVP example, as s I cannot reproduce your results and I really need more information so investigate this.

**Comment by kennethstarkrl** [comment] 2023-09-26 18:08
@marklawlor I'm working on updating the repo to reproduce the issue. I also noticed my project wasn't running with the Hermes engine, that helped a bit. Also trying to move most of the useEffect logic out of sub components leveraging useContext to avoid refreshing. It's looking like my main screen that loads the data gets rendered 3-4 times. I have not had time to build react vanilla version. I'll keep you posted. Thanks again for the help
