### ISSUE TITLE
[expo-image-picker] NotSerializableException expo.modules.imagepicker.contracts.CameraContractOptions

### ISSUE THREAD

**Issue by jrnp97** [expo/expo#23447] opened 2023-07-11 02:22 UTC
### Minimal reproducible example

N/A

### Summary

When using image-picker in combination with `Don't keep activities` enabled at the moment of opening the camera it crashes

there are some threads about failures when the android destroy the activities on background and were the incentive to create the `getPendingResultAsync` method, so it will be a long list if I list everything here

this time it's not even opening the camera, because it can't not serialize the `CameraContractOptions` in the `ImagePickerOptions` object because it has a `Uri` which is not serializable 
![image](https://github.com/expo/expo/assets/26009859/9d735009-be3c-4b7b-b66d-78e11e68b360)

sentry traceback messages

```
BadParcelableException
Parcelable encountered IOException writing serializable object (name = expo.modules.imagepicker.contracts.CameraContractOptions)

NotSerializableException
android.net.Uri$HierarchicalUri
```

### Environment

``` 
 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
    npmPackages:
      expo: ^48.0.0 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.7 => 0.18.12 
      react-navigation: ^4.4.2 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 3.13.3
      expo-cli: 6.3.8
    Expo Workflow: managed
```
---
Expo packages
```
"expo": "^48.0.0",
    "expo-application": "~5.1.1",
    "expo-av": "~13.2.1",
    "expo-background-fetch": "~11.1.1",
    "expo-camera": "~13.2.1",
    "expo-constants": "~14.2.1",
    "expo-dev-client": "~2.2.1",
    "expo-device": "~5.2.1",
    "expo-font": "~11.1.1",
    "expo-image-loader": "~4.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-location": "~15.1.1",
    "expo-notifications": "~0.18.1",
    "expo-sqlite": "~11.1.1",
    "expo-status-bar": "~1.4.0",
    "expo-task-manager": "~11.1.1",
    "expo-updates": "~0.16.4",
```

**Comment by brentvatne** [comment] 2023-07-12 20:29
closing this for now because no minimal reproducible example. if someone can provide one, @alanjhughes can help to investigate

**Comment by jrnp97** [comment] 2023-07-17 01:58
> closing this for now because no minimal reproducible example. if someone can provide one, @alanjhughes can help to investigate

Minimal reproducible example [https://github.com/expo/expo/issues/23447#issuecomment-1633171152, you n](https://snack.expo.dev/@dgranel/imagepickerserializerfailure), steps

1. Click on `Tap to play` in the android emulator.
2. Enable the `Don't keep activies` on the `developer options` settings.
3. Open the app give the requested permissions.
4. Take a picture.
5. Click on the camara `check` icon.

The app restart without any reason and that is because of the serialization problem, don't use the `run on device` option since the expo has problem opening the camera.

please re-open this @brentvatne

**Comment by pdandradeb** [comment] 2023-08-04 13:03
Same here. `ImagePicker.launchCameraAsync` always crash if "Don't keep activities" is enabled.

**Closed** 2023-12-08 16:49 UTC
Labels: ImagePicker, Issue accepted
