### ISSUE TITLE
Recommended size splash screens crash Android app

### ISSUE THREAD

**Issue by HR** [expo/expo#4020] opened 2019-04-17 20:32 UTC
### Environment

```
  Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.6 => 32.0.6 
      react: 16.5.1 => 16.5.1 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.8.1 => 3.8.1 
    npmGlobalPackages:
      expo-cli: 2.14.0
```

Target: **Android**

### Steps to Reproduce

Running ` expo build:android --release-channel production`

With the splash images of different Android DPIs sizes specified in the `app.json`:
```json
"splash": {
  "image": "assets/splash.png",
  "resizeMode": "cover",
  "backgroundColor": "#FFFFFF"
},
"android": {
  "versionCode": 1,
  "package": "com.me.myApp",
  "splash": {
    "mdpi": "assets/splash/mdpi/splash.png",
    "hdpi": "assets/splash/hdpi/splash.png",
    "xhdpi": "assets/splash/xhdpi/splash.png",
    "xxhdpi": "assets/splash/xxhdpi/splash.png",
    "xxxhdpi": "assets/splash/xxxhdpi/splash.png"
  }
}
```
Of the recommended sizes and file size:
```
mdpi: 1242x2436 (278 KB),
hdpi: 1863x3654 (146 KB),
xhdpi: 2484x4872 (438 KB),
xxhdpi: 3726x7308 (846 KB),
xxxhdpi: 4968x9744 (1.34 MB)
```
Successfully produces an `apk`

### Expected Behavior

It should run fine

### Actual Behavior

It **crashes** when it is run on a `xxxhdpi` Android device with the following error

```
04-16 23:21:52.037 27573 27573 D AndroidRuntime: Shutting down VM
04-16 23:21:52.038 27573 27573 E AndroidRuntime: FATAL EXCEPTION: main
04-16 23:21:52.038 27573 27573 E AndroidRuntime: Process: com.me.myApp, PID: 27573
04-16 23:21:52.038 27573 27573 E AndroidRuntime: java.lang.RuntimeException: Canvas: trying to draw too large(108918432bytes) bitmap.
04-16 23:21:52.038 27573 27573 E AndroidRuntime:     at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
04-16 23:21:52.038 27573 27573 E AndroidRuntime:     at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:101)
04-16 23:21:52.038 27573 27573 E AndroidRuntime:     at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
04-16 23:21:52.038 27573 27573 E AndroidRuntime:     at android.widget.ImageView.onDraw(ImageView.java:1360)
04-16 23:21:52.038 27573 27573 E AndroidRuntime:     at android.view.View.draw(View.java:21882)
```
It is saying that my splash image size is `108.918432 MB` large when it actually is just `1.34MB`

However it runs fine when I scale it back from the default `1242x2436` but I get the following warning when building it
```
[dpi: provided (expected)] mdpi: 320x628 (1242x2436), hdpi: 480x942 (1863x3654), xhdpi: 640x1256 (2484x4872), xxhdpi: 960x1884 (3726x7308), xxxhdpi: 1280x2512 (4968x9744)
```

### Reproducible Demo
https://snack.expo.io/@hrx/splash-screen-test

**Comment by chrisjim316** [comment] 2019-04-17 20:35
This has proven to be quite an annoying issue for my app release as well.

@expo

**Comment by pataiadam** [comment] 2019-05-26 19:37
I can confirm, I am facing this as well. Have you been able to find a workaround?

**Comment by HR** [comment] 2019-05-28 17:16
@pataiadam I scaled it back from the default 1242x2436:
```
mdpi: 320x628,
hdpi: 480x942,
xhdpi: 640x1256,
xxhdpi: 960x1884,
xxxhdpi: 1280x2512
```

**Comment by mastepanoski** [comment] 2019-06-11 17:55
Same. Running an App on Android 7 Nougat (Samsung A5), crashes. 

 E AndroidRuntime: FATAL EXCEPTION: main
06-11 14:40:00.668  4964  4964 E AndroidRuntime: Process: com.sampleapp, PID: 4964
06-11 14:40:00.668  4964  4964 E AndroidRuntime: java.lang.RuntimeException: Canvas: trying to draw too large(108918432bytes) bitmap.
06-11 14:40:00.668  4964  4964 E AndroidRuntime:        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:260)
06-11 14:40:00.668  4964  4964 E AndroidRuntime:        at android.graphics.Canvas.drawBitmap(Canvas.java:1420)
06-11 14:40:00.668  4964  4964 E AndroidRuntime:        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
06-11 14:40:00.668  4964  4964 E AndroidRuntime:        at android.widget.ImageView.onDraw(ImageView.java:1286)
06-11 14:40:00.668  4964  4964 E AndroidRuntime:        at android.view.View.draw(View.java:18394)
06-11 14:40:00.668  4964  4964 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:17372)
06-11 14:40:00.668  4964  4964 E AndroidRuntime:        at android.view.View.draw(View.java:18156)

**Comment by mastepanoski** [comment] 2019-06-11 18:32
It worked. I modified the app.json, and I resized the splash:
- mdpi: 320x628,
- hdpi: 480x942,
- xhdpi: 640x1256,
- xxhdpi: 960x1884,
- xxxhdpi: 1280x2512

**Comment by trev91** [comment] 2019-07-01 22:53
@mastepanoski 
When you say you modified the app.json, what did you do?
I was able to get my app building again by manually changing the sizes like you mentioned. But I'm wondering if you added those modified splash images to your app.json

**Comment by mastepanoski** [comment] 2019-07-05 18:25
@trev91 
The extract of app.json:
`...,"android": {
      "package": "com.uketer.uketerapp",
      "googleServicesFile": "./google-services.json",
      "versionCode": 54,
      "icon": "./assets/images/icon1024x1024.png",
          "splash": {
            "mdpi": "assets/splash/mdpi/splash.png",
            "hdpi": "assets/splash/hdpi/splash.png",
            "xhdpi": "assets/splash/xhdpi/splash.png",
            "xxhdpi": "assets/splash/xxhdpi/splash.png",
            "xxxhdpi": "assets/splash/xxxhdpi/splash.png"
          }, ...`

That makes sense if you build on the Expo Cloud. I didn't try ejecting to ExpoKit.

**Comment by brettdh** [comment] 2020-04-27 04:42
I fixed this issue as @mastepanoski described, when my app was using ExpoKit. Now that I've migrated back to managed and then ejected to bare, I'm encountering it again. I'm using expo-splash-screen now, which manages some of the related assets, so I'm concerned about repeating the workaround, since apparently the new [`expo-splash-screen`](https://www.npmjs.com/package/expo-splash-screen-command) tool is doing something that breaks the Android app on certain devices.

**Comment by tsapeta** [comment] 2020-07-11 18:38
@brettdh, this new module `expo-splash-screen` is not yet integrated with managed workflow, especially with the client app but also with standalone builds. We're targeting to finish the integration in the next SDK (39). So far you can safely use it only in bare workflow. I'm closing this thread because the original issue seems to be resolved but feel free to open a new issue with some more details if you're still experiencing this with the old SplashScreen API.

**Closed by tsapeta** 2020-07-11 18:38 UTC
Labels: Android, project: turtle

**Comment by brettdh** [comment] 2020-07-11 18:40
@tsapeta in my last comment, I mentioned that I encountered this in the bare workflow using the new API and command-line tool.

**Comment by tsapeta** [comment] 2020-07-11 18:44
Ahh, sorry, I've read it too fast 🙈 Anyway, could you open a new issue for this and provide as much info as you can?

cc @bbarthec who works on the new splash screen

**Comment by eyalyoli** [comment] 2020-11-25 16:19
if you are on bare workflow, as instructed you can use `npx expo-splash-screen` to install the splash screen for native android/ios.
Once installed to solve the issue, just use [Image Bake](https://www.img-bak.in/) to scale down the splash and then paste the `drawable-mdpi, ..., drawable-xxxhdpi` to `res` subfolder of your android native app.
