### ISSUE TITLE
password reset not working

### ISSUE THREAD

**Issue by vonwao** [expo/expo#2960] opened 2018-12-11 22:21 UTC
I keep getting this message, but I get no email:

![image](https://user-images.githubusercontent.com/377000/49833948-fdf90800-fd4f-11e8-8382-40b14baa112c.png)

**Comment by ide** [comment] 2018-12-17 23:23
We had an email deliverability issue last week and fixed the root cause. Closing off this thread and believe this incident has been resolved.

**Closed by ide** 2018-12-17 23:23 UTC
