### ISSUE TITLE
Double Header while navigating to stacked screen from tab navigation screen in Android

### ISSUE THREAD

**Issue by sreeshdev** [expo/expo#25840] opened 2023-12-10 16:02 UTC
### Minimal reproducible example

navigating to stack screen from tab navigation

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

PFA for the issue. I added `headerShown: false`. Header not showing in tab screen, when I navigating to a stackScreen with header, the header is padded down.

# Tab _layout code: 
``` import { MaterialCommunityIcons } from "@expo/vector-icons";
import { Tabs, usePathname, useRouter } from "expo-router";
import { Button } from "tamagui";
import { Image } from "expo-image";

export default function Layout() {
  return (
    <Tabs
      initialRouteName="Home"
      screenOptions={{
        tabBarActiveTintColor: "#008666",
        tabBarLabelStyle: { fontWeight: "bold", fontSize: 10 },
        headerStatusBarHeight: 0,
        headerShown: false,
        unmountOnBlur: true,
        tabBarStyle: {
          paddingBottom: 5,
          paddingTop: 10,
          height: 60
        }
      }}
    >
      <Tabs.Screen
        name="home"
        options={{
          tabBarLabel: "Home",
          headerShown: false,
          tabBarIcon: ({ color, size }) => (
            <Image
              style={{ width: 27.5, height: 27.5 }}
              source={require("../../assets/home.svg")}
              alt="home"
              contentFit="contain"
            />
          )
        }}
      />
      <Tabs.Screen
        name="homeWork"
        options={{
          tabBarLabel: "Home Work",
          title: "Home Work",
          headerShown: true,
          headerStyle: {
            backgroundColor: "#22b693"
          },
          headerTintColor: "#fff",
          headerTitleStyle: {
            fontWeight: "bold"
          },
          headerShadowVisible: false,
          // headerBackTitleVisible: false,
          tabBarIcon: ({ color, size }) => (
            <Image
              style={{ width: 27.5, height: 27.5 }}
              source={require("../../assets/homeWork.svg")}
              alt="HomeWork"
              contentFit="contain"
            />
          )
        }}
      />
      <Tabs.Screen
        name="notification"
        options={{
          tabBarLabel: "Notifications",
          headerStyle: {
            backgroundColor: "#22b693"
          },
          title: "Notifications",
          // tabBarBadge: notificationCount ? true : null,
          tabBarBadgeStyle: {
            maxHeight: 7,
            maxWidth: 5
          },
          headerShown: true,
          headerTintColor: "#fff",
          headerTitleStyle: {
            fontWeight: "bold"
          },
          headerShadowVisible: false,
          tabBarIcon: ({ color, size }) => (
            <Image
              style={{ width: 27.5, height: 27.5 }}
              source={require("../../assets/notification.svg")}
              alt="Notifications"
              contentFit="contain"
            />
          )
        }}
      />
      <Tabs.Screen
        name="more"
        options={{
          tabBarLabel: "More",
          headerShown: false,
          tabBarIcon: ({ color, size }) => (
            <Image
              style={{ width: 27.5, height: 27.5 }}
              source={require("../../assets/more.svg")}
              alt="home"
              contentFit="contain"
            />
          )
        }}
      />
    </Tabs>
  );
}
```

# Contact page _Layout code:

```import { Stack } from "expo-router";

export default function Layout() {
  return (
    <Stack
      screenOptions={{
        headerShown: true
      }}
    />
  );
}
 ```
![Screenshot_1702180548](https://github.com/expo/expo/assets/45986028/98781204-f925-416d-83ac-4db1c6ecff91)

### Environment

``` expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.10.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.4 - ~/Desktop/tamagui-expo-main/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 31, 32, 33
        Build Tools: 30.0.3, 33.0.1
        System Images: android-33 | Google APIs ARM 64 v8a, android-UpsideDownCakePrivacySandbox | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: 49.0.9 => 49.0.9
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    npmGlobalPackages:
      eas-cli: 5.9.1
      expo-cli: 6.3.10
    Expo Workflow: managed```

**Comment by marklawlor** [comment] 2023-12-14 06:40
I'm closing this issue as we need a full reproduction to troubleshoot. The issue seems to be coming from a clashing of `<Stack />` but without seeing the entire project I cannot assist you further.

If you reply with a reproduction then I can reopen this issue

**Closed by marklawlor** 2023-12-14 06:40 UTC
Labels: needs review, Router
