### ISSUE TITLE
NetInfo listener not working in Android

### ISSUE THREAD

**Issue by sebas5384** [expo/expo#492] opened 2017-08-13 23:53 UTC
I'm using Redux to set in the store if it's offline or not:

```js
      NetInfo.isConnected.fetch().then(isConnected => {
        store.dispatch(setOfflineAction(!isConnected))
      })

      NetInfo.addEventListener('change', reach => {
        const isOffline = /^none$/i.test(reach)
        store.dispatch(setOfflineAction(isOffline))
      })
```

It works perfectly on iOS, but on Android only works when the App is bootstrapping.
It seems is ignoring the `change` listener.

I'm using the last version of Expo `19.0.0` and Android `6.0`.

Help? :)

BTW, since I don't have an emulator for Android I'm using my phone, and it needs to publish in order to test the offline mode, little annoying.

**Comment by skevy** [comment] 2017-08-14 18:24
@jesseruder this seems like it may be an upstream bug. Will add to backlog.

**Comment by sebas5384** [comment] 2017-08-15 19:25
@skevy thanks! I hope it get fixed 👍 
btw, what do you mean by `upstream bug` ?

**Comment by tofoli** [comment] 2017-08-16 20:36
+1

I have the same problem.

It seems to be the lack of permission on android, see the [documentation](https://facebook.github.io/react-native/docs/netinfo.html#android)

> To request network info, you need to add the following line to your app's `AndroidManifest.xml:`
> `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />`

**Comment by sebas5384** [comment] 2017-08-17 20:22
@tofoli I thought it was that, but after searching in the codebase I found that the permission is there, but I don't know maybe there is something missing.

https://github.com/expo/expo/search?utf8=%E2%9C%93&q=ACCESS_NETWORK_STATE&type=

**Comment by tofoli** [comment] 2017-08-18 12:43
You're right @sebas5384

**Comment by dikaiosune** [comment] 2017-10-11 19:24
Hi! From the [RN docs for NetInfo](https://facebook.github.io/react-native/docs/netinfo.html) it looks like the `change` event has been deprecated in favor of the `connectionChange` event. Can you try with that event listener?

There are a couple unconfirmed reports of the listener not working upstream:

https://github.com/facebook/react-native/issues/15735
https://github.com/facebook/react-native/issues/15729

Since this is almost certainly a React Native issue, I'll close this in favor of tracking and resolving the problem upstream. If you have an Expo-specific reproduction, please post back and we'll reopen this! Thanks!

**Closed by dikaiosune** 2017-10-11 19:24 UTC
Labels: project: client-android

**Comment by ahmedsamyabdelhay** [comment] 2018-02-26 07:00
Is the issue still stands ... on my android phone the event handler is only executed when the internet is connected when I turn off WiFi ... I get nothing.

**Comment by ivanxtr** [comment] 2018-03-16 18:57
For Android : 
  have a look at the phone settings 
![image](https://user-images.githubusercontent.com/32345257/37539435-50e4a1ca-2919-11e8-8fcf-8340652d03e6.png)
  once you turn off the mobile data the listener is working.

For IOS : 
  just unplugged the LAN cable or turn off the wifi and automatically runs the listener

**Comment by ToshKoevoets** [comment] 2018-07-07 14:55
I also had problems with React Native android build, but it worked to listen to the isConnected event, like so:



```
NetInfo.isConnected.fetch().then(isConnected => {
  console.log('First, is ' + (isConnected ? 'online' : 'offline'));
});
function handleFirstConnectivityChange(isConnected) {
  console.log('Then, is ' + (isConnected ? 'online' : 'offline'));
  NetInfo.isConnected.removeEventListener(
    'connectionChange',
    handleFirstConnectivityChange
  );
}
NetInfo.isConnected.addEventListener(
  'connectionChange',
  handleFirstConnectivityChange
);
```

https://facebook.github.io/react-native/docs/netinfo.html

**Comment by bonham000** [comment] 2018-10-28 09:35
Has this been resolved? I'm seeing the same issue for Android builds where network connection changes are not registered. I suspect it has to do with the Android permission:

```
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

mentioned in the RN documentation. Is there a way for us to provide this permission in the Expo project configuration? It's not listed in the `permissions` options in the Expo documentation.

**Comment by mepritam** [comment] 2019-01-04 14:50
> +1
> 
> I have the same problem.
> 
> It seems to be the lack of permission on android, see the [documentation](https://facebook.github.io/react-native/docs/netinfo.html#android)
> 
> > To request network info, you need to add the following line to your app's `AndroidManifest.xml:`
> > `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />`

Works Thanks
