### ISSUE TITLE
[Android][Notifications] Delayed Scheduled Local Notifications on Android

### ISSUE THREAD

**Issue by ehesketh** [expo/expo#5799] opened 2019-09-28 20:54 UTC
### Environment

  Expo CLI 3.0.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.7.0 
      npm: 6.4.1
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501

Target OS: Android

### Steps to Reproduce

Schedule a Local Notification to be triggered a few minutes in the future. Then compare the scheduled time with the actual time it gets triggered. The problem seems to replicate more reliably if a notification is scheduled while at least one other is pending.

### Expected Behavior

Scheduled Local Notifications to trigger at the time scheduled.

### Actual Behavior

Notifications are often delayed, typically up to a minute and sometimes longer. This seems to only replicate consistently when multiple notifications are scheduled.

### Reproducible Demo

https://snack.expo.io/@solarr/scheduled-notification-delay

On Android, click the button to schedule a 5 minutes notification (click the button subsequent times to schedule multiple 5 minute notifications). When the notification is triggered compare the scheduled time with the actual time.

**Comment by cruzach** [comment] 2019-09-30 19:19
I tried and haven't seen any delayed Notifications, have you tried this on multiple devices?

**Comment by ehesketh** [comment] 2019-09-30 23:07
I've tried that snack on only one physical device but a few different emulated devices. It does only seem to happen consistently when multiple notifications are scheduled. For example using the in-browser emulator now, I scheduled a 5 min notification, then scheduled one again 1 min later. In this case both notifications got triggered together at the time the second notification was due to be displayed (i.e. the first notification seemed to be delayed by 1 minute).

**Comment by cruzach** [comment] 2019-10-01 20:41
Ah I see it, thanks for explaining!

**Comment by arnaud-cortisse** [comment] 2020-03-11 09:41
I still encounter this issue. 
It's not systematic and it happens even if I have only scheduled a single notification. 

Here is a snack I created that allows for easy testing: 
[https://snack.expo.io/@acortisse/delayed-local-push-notifications](url)

Here is how to use it:
1. Open the app. 
2. Background the app. A push notification is scheduled 30 seconds later. 
3. Wait until the push notification appears and click on it ASAP (this is definitely important that you click on it as soon as it appears, otherwise the results you get will be wrong). 
4. The application shows how much time elapsed between the scheduled notification and the moment you reopened the app. 

I had those results at some point (about 10 seconds late): 
![Screenshot_20200311-102840](https://user-images.githubusercontent.com/28689103/76402875-528c9800-6384-11ea-8fbe-293d1caae3e2.jpg)

**Comment by arnaud-cortisse** [comment] 2020-03-11 09:52
Don't know whether or not it matters, but I managed to have the problem on both a OnePlus 6T and a Galaxy S4.

**Comment by NYDino** [comment] 2020-06-30 15:01
I'm having the same problem

**Comment by cruzach** [comment] 2020-07-01 13:13
Can you guys give this a go using the new `expo-notifications` module that landed in SDK 38? It's a total rework of the module and is a lot more predictable and consistent - https://docs.expo.io/versions/latest/sdk/notifications/

**Comment by NYDino** [comment] 2020-07-01 13:28
> Can you guys give this a go using the new `expo-notifications` module that landed in SDK 38? It's a total rework of the module and is a lot more predictable and consistent - https://docs.expo.io/versions/latest/sdk/notifications/

the project in which I found this problem is in SDK 36
I will update and test, thanks for responding

**Comment by cruzach** [comment] 2020-07-07 18:21
I created a Snack here to try and reproduce this: https://snack.expo.io/@charliecruzan/notifications5799

To test it, run the app on your device and tap `Press to send notification` -> all 3 notifications come in at their scheduled times (as evidenced by the logs)

I'm going to close this since it seems like the new `expo-notifications` module has fixed this issue 🎉 but if you do still see this bug, lmk how I can change the snack to reproduce and I'll reopen the issue

**Closed by cruzach** 2020-07-07 18:21 UTC
Labels: Android, Notifications, bug

**Comment by arnaud-cortisse** [comment] 2020-10-01 16:00
> I created a Snack here to try and reproduce this: https://snack.expo.io/@charliecruzan/notifications5799
> 
> To test it, run the app on your device and tap `Press to send notification` -> all 3 notifications come in at their scheduled times (as evidenced by the logs)
> 
> I'm going to close this since it seems like the new `expo-notifications` module has fixed this issue 🎉 but if you do still see this bug, lmk how I can change the snack to reproduce and I'll reopen the issue

I've updated my app and I'm now using the new notification module --> I no longer have a delay 🥳

**Comment by artsnr1** [comment] 2021-01-25 15:13
> I created a Snack here to try and reproduce this: https://snack.expo.io/@charliecruzan/notifications5799
> 
> To test it, run the app on your device and tap `Press to send notification` -> all 3 notifications come in at their scheduled times (as evidenced by the logs)
> 
> I'm going to close this since it seems like the new `expo-notifications` module has fixed this issue  but if you do still see this bug, lmk how I can change the snack to reproduce and I'll reopen the issue

It's not working when I am setting minutes. I am receiving only first notification on time. The other two triggers late and simultaneously 

```
CPH1911:
Notification scheduled for: Mon Jan 25 2021 20:07:47 GMT+0500 (PKT)
CPH1911:
Notification scheduled for: Mon Jan 25 2021 20:08:47 GMT+0500 (PKT)
CPH1911:
Notification scheduled for: Mon Jan 25 2021 20:09:47 GMT+0500 (PKT)
CPH1911:
Notification received at: Mon Jan 25 2021 20:07:47 GMT+0500 (PKT)
CPH1911:
ExponentPushToken[NmECbXMqBlCq4nyVeqYFxK]
CPH1911:
Notification received at: Mon Jan 25 2021 20:10:01 GMT+0500 (PKT)
2
```

I edited your snack. Check it out if it reproduces at your end 
https://snack.expo.io/@rabiarashid/notifications5799

**Comment by cruzach** [comment] 2021-01-25 16:49
@artsnr1 your snack was running on an older sdk version (38), so that would explain your behavior. Here are the logs from me running the snack on SDK 40 (i accidentally duplicated listeners which is why there's a double notification for 08:46:22 and 08:47:22

<img width="621" alt="Screen Shot 2021-01-25 at 11 47 36 AM" src="https://user-images.githubusercontent.com/35579283/105736752-211cac80-5f03-11eb-9613-5bfc415f2190.png">

**Comment by artsnr1** [comment] 2021-01-25 17:18
@cruzach Thank you for responding. I tried that before locally on my system having sdk 40 and expo-notifications version 0.8.2. The problem is that the outputs are not consistent. At times they are on time and at times they aren't. Any reason for inconsistency? I ran it first time, it worked fine. I ran it again and then the first two notifications were on time but the 3rd one was delayed: 
```
CPH1911:
ExponentPushToken[NmECbXMqBlCq4nyVeqYFxK]
6
CPH1911:
Notification scheduled for: Mon Jan 25 2021 22:05:37 GMT+0500 (PKT)
CPH1911:
Notification scheduled for: Mon Jan 25 2021 22:04:37 GMT+0500 (PKT)
CPH1911:
Notification scheduled for: Mon Jan 25 2021 22:06:37 GMT+0500 (PKT)
CPH1911:
Notification received at: Mon Jan 25 2021 22:04:37 GMT+0500 (PKT)
5
CPH1911:
ExponentPushToken[NmECbXMqBlCq4nyVeqYFxK]
CPH1911:
Notification received at: Mon Jan 25 2021 22:05:37 GMT+0500 (PKT)
6
CPH1911:
ExponentPushToken[NmECbXMqBlCq4nyVeqYFxK]
CPH1911:
Notification received at: Mon Jan 25 2021 22:08:43 GMT+0500 (PKT)
7
CPH1911:
ExponentPushToken[NmECbXMqBlCq4nyVeqYFxK]
```
I have also updated the snack to expo 40. Try it 2,3 times (you can decrease the time interval for saving you time)
https://snack.expo.io/@rabiarashid/notifications5799
