### ISSUE TITLE
Android FileSystem unable to read files and cache directories

### ISSUE THREAD

**Issue by sameesiddiqui** [expo/expo#767] opened 2017-10-11 20:46 UTC
Attempting to perform actions such as reading files from `FileSystem.documentDirectory` and `FileSystem.cacheDirectory` throws errors for invalid file uri on android. Reading from these directories works on iOS. 

Reading from a child directory also works, just not these top level ones:
```javascript
// throws error, 'invalid filesystem uri, make sure its in the app's scope'
FileSystem.readDirectoryAsync(FileSystem.documentDirectory) 

// success, returns a promise
FileSystem.readDirectoryAsync(FileSystem.documentDirectory + 'child_folder') 
```

**Comment by alexrussell** [comment] 2017-10-12 08:21
This is a dupe of #716, so one of these should really be closed. This one provides the correct context and description of the issue in the issue description, so I say close #716.

**Comment by nikki93** [comment] 2017-10-12 18:05
@sameesiddiqui you mean just reading the file list (`readDirectoryAsync`) of those root directories right? Are you able to `readAsString` the contents of a file at the top level? (just checking)

**Comment by nikki93** [comment] 2017-10-12 18:12
@sameesiddiqui does this work if you add `/` to the end of the directory path?

**Comment by sameesiddiqui** [comment] 2017-10-12 18:26
Yes, reading a file under the directory works:
```javascript
// prints contents of example.json
FileSystem.readAsStringAsync(FileSystem.documentDirectory + 'example.json')
    .then(info => console.log(info))
```

But trying to do any task with the top directories fails, not just readDirectory:
```javascript
// fails, invalid filesystem uri
FileSystem.getInfoAsync(FileSystem.documentDirectory)
    .then((info) => console.log(info))
```

Also tried appending `/` to the end of the path, but no dice. Looks like the path already has a trailing slash

**Comment by sameesiddiqui** [comment] 2017-10-12 18:28
dependencies in case you are wondering:
```javascript
  "dependencies": {
    "expo": "^21.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz"
  }
```

**Comment by alexrussell** [comment] 2017-10-13 09:46
If this is about readDirectoryAsync on the root of the filesystem and #716 is about files in the root of the filesystem maybe I'm wrong about the dupe (though #716 is specifically about using `createDownloadResumable`, which may perform a directory read, and therefore be back in dupesville).

**Comment by nikki93** [comment] 2017-10-13 18:32
This is a little tricky since we want to be able to read and write under but not delete the root directory itself in each case. 🤔 Tracking a new issue to granularlize FS permissions here: https://github.com/expo/expo/issues/776 This will also allow stuff like copying from RN's CameraRoll -> Expo FS.

**Comment by nikki93** [comment] 2017-10-13 18:34
Let me know if you think that other issue sufficiently covers this case, I will also try to solve this issue while getting at that one. Then we can close this one and just track that. As a workaround for now @sameesiddiqui you can just create a subdirectory inside the root and create and list your files in that.

**Comment by sameesiddiqui** [comment] 2017-10-13 19:00
Interesting, on iOS there are permissions to delete these root directories. Just tested by deleting `FileSystem.documentDirectory` (throws no error) and tried to read it's contents, which then tells me the directory doesn't exist. Is this unintended behavior on iOS? 

My understanding right now is that iOS root directories have r/w and Android root directories have neither. Is the end goal to make both have only read?

**Comment by nikki93** [comment] 2017-10-16 18:52
I guess it's a little weird @sameesiddiqui since they need to be not deleteable but they do need to be writeable (create new entries under) and definitely readable (list entries). I guess deletion requires write access on both the file and its parent directory (since the listing of the parent directory is being changed), in which case the conditions work out (since the parent of root is not read or writeable). Anyways, let's track this discussion on https://github.com/expo/expo/issues/776 now since I think we can tackle this issue as part of that. Closing this to unify discussion, feel free to comment here though if something makes sense to be said here.

**Closed by nikki93** 2017-10-16 18:52 UTC
Labels: project: sdk, ready

**Comment by kaulsalil88** [comment] 2018-02-02 07:15
i know this is very late in the day but i have the following configuration in my package.json
"expo": "^21.0.0",
"expo-env": "^1.1.0",
"react": "16.0.0-alpha.12",
"react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",
. On android I need to create a sub folder and able to use both downloadAsync and createDownloadResumable . On IOS when using createDownloadResumable i am getting the following error on ios :
[EXFileSystem _downloadResumableCreateSessionWithUrl:withScopedPath:withUUID:withOptions:withResumeData:withResolver:withRejecter:]_block_invoke.298 + 418',
'3 hcl-concerts 0x000000010186d5cb -[EXDownloadDelegate URLSession:downloadTask:didFinishDownloadingToURL:] + 155',
'4 CFNetwork 0x000000010c0d20b2 __82-[NSURLSession delegate_downloadTask:didFinishDownloadingToURL:completionHandler:]_block_invoke + 38',
Do I need to upgrade my expo version , want to avoid that as the release date is very close . Please help .
