### ISSUE TITLE
SDK 35 - Push Notifications Permissions is never granted (even when it does) on iOS 13

### ISSUE THREAD

**Issue by 0xori** [expo/expo#6013] opened 2019-10-17 08:06 UTC
### Environment

Expo CLI 3.2.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809

Please also let us know about your app's target:
Standalone

### Steps to Reproduce

```
async function registerForPushNotificationsAsync(userId, deviceInfo) {
    const {status: existingStatus} = await Permissions.getAsync(
        Permissions.NOTIFICATIONS
    );
    let finalStatus = existingStatus;

    // only ask if permissions have not already been determined, because
    // iOS won't necessarily prompt the user a second time.
    if (existingStatus !== 'granted') {
        // Android remote notification permissions are granted during the app
        // install, so this will only ask on iOS
        const {status} = await Permissions.askAsync(Permissions.NOTIFICATIONS);
        finalStatus = status;
    }

    // Stop here if the user did not grant permissions
    if (finalStatus !== 'granted') {
        console.log("push notifications permission not granted");
        return;
    }

    // Get the token that uniquely identifies this device
    let token = await Notifications.getExpoPushTokenAsync();

    // POST the token to your backend server from where you can retrieve it to send push notifications.
    registerDeviceForPushNotifications(userId, token, deviceInfo);
}
```

### Expected Behavior

I should get permission and the token.

### Actual Behavior

I'm running this function (according to documentation)
At the first run of the app I'm getting the message that asks me to allow notifications permissions, I click on allow, but not getting the token.
On the next run - I see that the permission is not granted according to expo. (i'm getting 'undetermined')
When I go to my app notification settings I see this:
![File (2)](https://user-images.githubusercontent.com/2307798/66989737-9e852a80-f0cd-11e9-8cc7-e73cbb1c0309.jpg)

It used to work before iOS 13.

**Comment by 0xori** [comment] 2019-10-17 17:50
No, I don't have it enabled, is it something new? It used to work before
(not sure when it stopped)

**Comment by cruzach** [comment] 2019-10-17 17:52
Hm.. when did you last create your build with `expo build:ios`? Actually, can you email secure@expo.io with your Expo username and the build ID (if you have it)?

**Comment by 0xori** [comment] 2019-10-17 17:55
Last week, sure I'll send it.

**Comment by CarterBland** [comment] 2019-10-23 18:42
@cruzach I am ejected and having this same issue, it looks like my mobile provision has the Push Notification capabilities, but still seeing it.

**Comment by sjchmiela** [comment] 2020-09-21 15:56
I have been recently reproducing this scenario and everything worked well. I'll let myself close this issue, but if it arises again, please let me know, I'd be happy to assist you!

**Closed by sjchmiela** 2020-09-21 15:56 UTC
Labels: Notifications, bug, iOS
