### ISSUE TITLE
[notifications] displayInForeground results in inconsistent behavior ios vs android

### ISSUE THREAD

**Issue by dakairus** [expo/expo#6693] opened 2020-01-07 01:47 UTC
Hi all, I got an issue with my current project witch is working properly in production, but we are up to release a new version of it. We upgraded from SDK 33 to SDK 36 as the only change and the listener for the notification while the app is in the foreground stopped of been triggered on notifications arrival. The curious part is if the app is in the background, the traditional notification pop up is displayed properly, so I guess is just an issue with the listener or how it deals with the notification while in the foreground.

Environment: IOS expo client (latest) - standalone app built for TestFlight
SDK version: 36 (upgraded from 33)
Expected Behaviour: If app is in the background, displays notification pop up. If app is in the foreground, the app triggers the notification handler.
Current Behaviour:  If app is in the background, displays notification pop up. If app is in the foreground, not notification handler is triggered.
Code Sample:
```
async componentDidMount() {
  this._notificationSubscription = Notifications.addListener(this._handleNotification);
}
_handleNotification(notification) {
  Alert.alert('New Message', notification.data.message);
}
```
Notification origin: from server side or expo test push notification tool

**Comment by cruzach** [comment] 2020-01-07 20:16
In the case of the app being backgrounded, and then you select the notification, is the notification listener fired then?

I haven't seen other reports of this so it's hard to say what could cause it. Also it might be a good idea to get the push notification receipt and inspect that (see [here](https://docs.expo.io/versions/latest/guides/push-notifications/) for a guide on how to do that)

**Comment by dakairus** [comment] 2020-01-07 21:01
In the case of pressing over the notification when background doesn't trigger the listener either. Is really a weird issue. Our system is based in a web app + api + 1 iphone/android app (customers) + 1 ipad app (venues). In the moment I reported this issue I only upgraded the iPad app from SDK 33 to 36 getting the problem. Then after that I upgraded our iPhone app getting the same result.

I end up downgrading the SDK version to 34 and all is working normally again.

**Comment by cruzach** [comment] 2020-01-07 21:27
I suggest taking a look at the SDK 35 release notes- https://blog.expo.io/expo-sdk-35-is-now-available-beee0dfafbf4

That will give you a good idea of what changed

Can you make sure that you're `componentDidMount` method is firing? Might be worth testing on Android, as well

**Comment by dakairus** [comment] 2020-01-08 20:48
Hi, I just upgraded back to SDK 36, followed all the changes from the SDK 35 guidelines (nothing to change from the current work) and still got the issue.

The componentDidMount is definitively running, put some console.log before and after the handler declaration, also there is some api calls in that part working perfectly. If I console.log the handler it prints a instance of the listener, so I guess the problem is calling it, not the declaration.

**Comment by patrickomeara** [comment] 2020-01-09 01:55
I also have this issue on ios only.

Initially I thought it was something to do with running through the expo app, but even after I have released through the app store is was still happening. The deep linking is now working well and doesn't trigger on any other events.

For now I have added `|| Platform.OS === 'ios'`

```ts
    componentDidMount(): void {
        this._notificationSubscription = Notifications.addListener(this._handleNotification);
    }

    _handleNotification = (notification: Notification) => {
        if (notification.origin === 'selected' || Platform.OS === 'ios') {
            rootStore.authStore.processLink(notification.data.url);
        }
    };
```

**Comment by cruzach** [comment] 2020-01-09 15:56
I still haven't been able to reproduce this. Can you let me know if [this example snack](https://snack.expo.io/@charliecruzan/pushnotifications36) exhibits the same behavior for you?

**Comment by patrickomeara** [comment] 2020-01-12 22:26
@cruzach I have edited your snack here https://snack.expo.io/@patrickomeara/pushnotifications37

when tapping the in app notification nothing changes (on my device), but it should as `origin` should be `selected`. However if the app is backgrounded the `selected` works fine.

**Comment by cruzach** [comment] 2020-01-13 16:05
Ah yeah seems like you're right. Looks like when `_displayInForeground: true,`, and the app is foregrounded & you select the notifications, the `origin` is `received`, not `selected`

Let me see if I can debug this further, thanks for the report!

**Comment by patrickomeara** [comment] 2020-01-13 22:33
Thanks for looking into it, it's different behaviour between ios and android.

### Android
When the app is open and the notification comes in: `origin: received`
When selecting the notification: `origin: selected`

### iOS
When the app is open and the notification comes in: `(nothing happens)`
When selecting the notification: `origin: received`

I have updated the snack to show this clearly https://snack.expo.io/@patrickomeara/pushnotifications37

So the only time the handler is called when `_displayInForeground: true` is when the notification is selected, hence my ` || Platform.OS === 'ios'` workaround above.

**Comment by PavlezT** [comment] 2020-02-10 23:13
Upper message describes my issue too.
Hope it will be updated (or fixed) as soon as possible =)

**Comment by YahiaBadr** [comment] 2020-04-16 12:24
any update?

**Comment by cruzach** [comment] 2020-07-09 15:46
This is fixed now in SDK 38, with the new [`expo-notifications` module](https://docs.expo.io/versions/latest/sdk/notifications/) 🎉 

In the new module, you configure how the app handles notifications that come in while the app is foregrounded through the `setNotificationHandler` method, which allows you to set whether notifications will show an alert, play a sound, etc. Additionally, the notion of `origin: selected` vs `origin: received` is gone, and instead you handle all received notification events (i.e. the user gets a notification while the app is foregrounded) through the `addNotificationReceivedListener`, and all notification response events (such as the user tapping on the notification when the app is foregrounded or backgrounded) through the `addNotificationResponseReceivedListener`

If you'd like to try out an example of this, check out [this snack](https://snack.expo.io/@charliecruzan/notifications6693)

If you find discrepancies in how notifications or notification responses are handled on iOS vs Android, please open up a new issue with details and we'll investigate it ASAP

**Closed by cruzach** 2020-07-09 15:46 UTC
Labels: Notifications, bug, iOS

**Comment by patrickomeara** [comment] 2020-07-12 23:27
Thanks @cruzach 👍

**Comment by cruzach** [comment] 2020-07-13 13:16
anytime 😄 

let me know if there's anything unclear about the new way of configuring this behavior, and we can update the documentation
