### ISSUE TITLE
Expo Barcode Scanner Hangs App on IOS 

### ISSUE THREAD

**Issue by ChrisOliverFD** [expo/expo#19199] opened 2022-09-21 00:27 UTC
### Summary

Repeatedly scanning barcodes eventually hangs app

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.11.1 - /usr/local/bin/node
      npm: 8.5.5 - /usr/local/bin/npm
      Watchman: 2022.09.12.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 19, 21, 24, 27, 28
        Build Tools: 28.0.3
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 5.5.1

### Minimal reproducible example

https://snack.expo.dev/@unktomi/barcode-scanner

To reproduce the problem you will need to repeatedly push the scan button and scan a barcode (or not, scanning an actual barcode isn't necessary to reproduce the problem), and then dismiss the popup with Cancel or Done. You will need to do this many, many times. It will start to seem unlikely to you that there is a real problem, but eventually the expo go app will hang.

**Comment by delventhalz** [comment] 2022-11-06 00:52
Nice example!

I have had the same issue in my project. Unfortunately, I have not found any solution, nor any workaround.

**Comment by delventhalz** [comment] 2022-11-06 02:15
@ChrisOliverFD I have a workaround! Your example was a huge help. I noticed the one thing both of our apps have besides the scanner itself: _the modal_.

It looks like `expo-bar-scanner` cannot properly handle being mounted while the iOS modal is animating in. Triggers a complete crash every dozen mounts or so. The fix?

**Do not mount the BarCodeScanner until the modal is done animating.**

Did a quick test in my own app just by putting a 1 second delay before I mounted the scanner. No freezes on ~80 attempts. I'm going to bring that delay down as low as I can and add a fade-in animation so it does not look so weird, but the fix sees workable.

**Comment by delventhalz** [comment] 2023-01-22 16:47
For anyone finding this issue here, a workaround is discussed over on https://github.com/expo/expo/issues/19060. It would appear that if you use `expo-camera` directly instead of `expo-barcode-scanner`, the crashes disappear. It is a fairly painless swap to make, at least for basic use cases.

**Comment by animaonline** [comment] 2023-10-17 07:20
Any updates on this?

**Comment by holmesjr** [comment] 2023-10-17 09:10
I can confirm the expo-camera workaround is the best thing to do for now.

**Comment by AndyS007** [comment] 2024-01-05 03:15
Same, switch to expo-camera fixed my problem.

**Comment by vonovak** [comment] 2024-08-23 08:47
Hello 👋 ,
barcode scanner is no longer shipped in the SDK and switching to expo camera is the right approach now.

With that, I'm closing the issue.
Thank you! 🙂

**Closed by vonovak** 2024-08-23 08:47 UTC
Labels: BarCodeScanner, Camera, Issue accepted
