### ISSUE TITLE
AuthSession doesn't redirect back to Android standalone app SDK 27

### ISSUE THREAD

**Issue by nikoootine** [expo/expo#1703] opened 2018-04-27 07:32 UTC
I created this issue since I couldn't re-open: https://github.com/expo/expo/issues/1683

Basically, Issue still persists for SDK 27 after I follow the exact same steps below. I've also updated the diagnostics. If this will be counted as a duplicate then feel free to close!

Doing an auth session on an android standalone app does not redirect back to the app. I have defined my scheme in app.json. On an iOS standalone auth session works perfectly fine.

It is also worth noting that I've tried detaching but then I encountered this exact same issue: #880. This issue might be related to that but I'm creating this issue in case this is a different one.

I'm hoping you could add this fix for SDK 27 as this auth session is an important aspect of our app!

Environment:
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  expo: ^27.0.0 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/nikoootine-50ea7ad2-fca6-423e-8e18-eb11e7c0add2.tar.gz

Steps to Reproduce
- Fork this repo: https://github.com/expo/auth0-example
- Make sure you have Auth0 client set up
- Make sure you define a scheme in app.json
- Change the redirect url to the defined scheme in app.json
- exp build:android
- Once installed, open the app
- Login with Auth0, a browser should open and an auth session should initiate
- Sign in with valid credentials

Expected Behavior
User gets successfully authenticated. AuthSession browser window will get closed and redirect back to the app.

Actual Behavior
Browser window does not get closed and does not redirect back to the app.

Reproducible Demo
A good reproducible demo is expo's own example: https://github.com/expo/auth0-example but try building an android standalone apk

**Comment by nikoootine** [comment] 2018-04-27 23:58
Hi @esamelson , I just wanna ask if this is a confirmed bug on the Expo side? So that I and my client can make further decisions on what to do with our app? Sorry if I sound dragging!

**Comment by nikoootine** [comment] 2018-04-28 22:47
@esamelson I'm curious how the redirect back to the app works for you. I'm using @brentvatne 's auth0 example. 

I tested both a hardcoded url and AuthSession.getRedirectUrl() as the redirect_uri. Both did not work produce same result. :

app.json:
![screen shot 2018-04-28 at 3 20 50 pm](https://user-images.githubusercontent.com/15661253/39401363-332ef95e-4af8-11e8-99e5-d1b30caeafa2.png)

code:
![screen shot 2018-04-28 at 3 24 39 pm](https://user-images.githubusercontent.com/15661253/39401368-57d84fee-4af8-11e8-95e1-ae6b42ee5810.png)

result (Redirect back doesn't work. Web browser does not close. auth0 freezes on loading):
![31495334_1948108585201607_204129822664818688_n](https://user-images.githubusercontent.com/15661253/39401397-1bc05dac-4af9-11e8-85e5-375bc21204a0.jpg)

**Comment by dodgecm** [comment] 2018-04-30 21:47
I'm having the same issue for a detached Android app.  It's actually opening a completely new instance of the app every time I complete my auth flow.  

Logcat shows the oauth redirect URI is set as the `initialUri` inside `initialProps` FWIW.

**Comment by esamelson** [comment] 2018-05-01 17:29
Hi @nikoootine -- I am unable to reproduce this. The same auth0 example works perfectly for me after I update the JS code to use `access_token` instead of `id_token` (which it looks like you've already done). Would you be able to share the output of `adb logcat | grep "ReactNativeJS"` when running your app?

@ryanmr - your issue looks like it might be slightly different. Could you share the code you're using to generate the redirectUrl back into your app?

**Comment by ryanmr** [comment] 2018-05-01 18:00
@esamelson I am using this `AuthSession.getRedirectUrl()`. I can make a new issue if needed with more/other details. Let me know.

**Comment by nikoootine** [comment] 2018-05-02 01:51
@esamelson  I'm not sure how to share you the log outputs. The way I'm testing this is I do exp build:android everytime and install it on an android device.

**Comment by esamelson** [comment] 2018-05-02 16:41
@ryanmr - thanks for the report. So just to clarify, this was working on the previous version of the Expo client (2.4.0), but after upgrading to version 2.5.0 of Expo client the SDK 26 behavior regressed? Will look into that if that is the case.

@nikoootine - can you run your standalone android apk, repro the issue above, and send me the output of `adb logcat | grep "ReactNativeJS"`? If you don't want to post it here you could send it to me on expo slack https://slack.expo.io/ (I'm @ eric)

**Comment by esamelson** [comment] 2018-05-03 00:05
Hi @ryanmr - thanks very much for the detailed info. That was indeed a regression; I've landed a fix which will go out in the next minor release. Sorry that you had to do an unplanned upgrade ☹️ but thank you so much for reporting this anyway -- we really appreciate it!!

Going to keep this open as I believe your issue was unrelated to the original one.

**Comment by jhalborg** [comment] 2018-05-04 10:41
@esamelson - What was the regression, and when will the next minor release be out?

I ran into a similar issue, but I'm using `Expo.Webbrowser` for my auth flow instead. On Android on Expo 2.5 i started seeing the error screen saying "No experience available at...", and it seems that it replaced the `+` sign with a space. I'm asking to confirm that this is indeed the same issue? I tried loading the app using Expo 2.4 from apkpure, and it works again 🙌

**Comment by esamelson** [comment] 2018-05-04 16:28
@jhalborg - yes, that is the same issue. I would recommend following our [blog](https://blog.expo.io/) as we will announce there as soon as the minor release is out. Also note that the issue is not present in SDK 27, so another potential workaround is upgrading your SDK version. Sorry again for the trouble!

**Comment by dlndev** [comment] 2018-06-25 14:02
Hi, I have the same problem, after detaching the project. The social media authentication works against the server fine (internal logic), but then the response that redirects to the app (the return url) does not redirect, and the app is stuck on the screen "return to app".
checking the emulator logs shows the error: 
I chromium: [INFO:CONSOLE(0)] "Navigation is unreachable: expe3d1afcbafc44b40b3550fcb48ff955a://expo-auth-session?userId=****&regToken=*****", source: https://auth.expo.io/@*****/*****-app?userId=*****&regToken=***** (0)

the return url from the  are AuthSession:
getDefaultReturnUrl: expe3d1afcbafc44b40b3550fcb48ff955a://expo-auth-session
getRedirectUrl: https://auth.expo.io/@*****/*****-app

Before detaching it worked perfectly.
Started with sdkVersion 26 and upgraded to 27.

**Comment by esamelson** [comment] 2018-06-25 19:58
Hi @dlndev . Could you verify that the `expe3d1afcbafc44b40b3550fcb48ff955a` string can be found in your AndroidManifest.xml, in an intent-filter inside of the MainActivity `<activity>...</activity>` tags?

**Comment by dlndev** [comment] 2018-06-27 06:45
Thanks @esamelson . 
The string was indeed missing, on the AndroidManifest.xml we had this block 
```
<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="com.****.*******" android:path="oauthredirect"/>
      </intent-filter>
    </activity>
```

and now changed to:
```
<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
      <intent-filter>
        <data android:scheme="expe3d1afcbafc44b40b3550fcb48ff955a"/>

        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
      </intent-filter>
    </activity>
```

It made a difference, but now the app **crashes** after the server finishes the auth with Facebook and returns the response to the  auth.expo.io url (attached), 
from the logs (adb logcat -v time)
the error is: 
Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference

![capture](https://user-images.githubusercontent.com/34474428/41957159-b452a966-79ee-11e8-8263-322aad6213fc.JPG)

**Comment by esamelson** [comment] 2018-06-28 00:07
Hi @dlndev - could you try keeping both the old and the new intent filter in your AndroidManifest file? So something like
```
<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
      <intent-filter>
        <data android:scheme="expe3d1afcbafc44b40b3550fcb48ff955a"/>

        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="com.****.*******" android:path="oauthredirect"/>
      </intent-filter>
    </activity>
```

If that doesn't work, could you open a new issue with more information and a repro case? I think what you're experiencing is a different issue than the one this thread was originally about. Thanks!

**Comment by esamelson** [comment] 2018-06-28 00:12
In fact, I'm going to go ahead and close this issue due to a lack of activity from the original poster, and because there are multiple different things going on in this thread and it's confusing. As far as I know, the original issue here is solved. If you're still experiencing trouble with AuthSession (or any other APIs), please open a new issue and follow the template there to the best of your ability. Thanks!

**Closed by esamelson** 2018-06-28 00:12 UTC
Labels: project: android-runtime, status: pending
