### ISSUE TITLE
[LocalAuthentication]Detect biometric changed

### ISSUE THREAD

**Issue by Bardiamist** [expo/expo#6343] opened 2019-11-21 08:43 UTC
### LocalAuthentication.hasBiometricChangedAsync
Please, add something like `LocalAuthentication.hasBiometricChangedAsync`. That should return `true` if fingerprints or face changed.

**Comment by cruzach** [comment] 2019-11-21 15:14
Hi! I'm going to close this since it's not a bug report. We keep all our feature requests [here](https://expo.canny.io/)

Just curious- what do you need to check if the the biometric has changed for? If the biometric changes, then `authenticateAsync` will automatically authenticate in reference to the new fingerprint(s)/face

**Closed by cruzach** 2019-11-21 15:14 UTC

**Comment by Bardiamist** [comment] 2019-11-22 03:49
This feature required for security improvements. I want to logout user if biometric changed.

[I created feature request](https://expo.canny.io/feature-requests/p/localauthenticationdetect-biometric-changed).
