### ISSUE TITLE
Invariant Violation when publishing

### ISSUE THREAD

**Issue by lucfranken** [expo/expo#196] opened 2017-05-18 10:33 UTC
First time I click publish I get an error (see below).

Second time it just works. Without any code changes. I think it even may have published twice but I do click again on publish because it looks like a fatal error to me as user.

I have seen this on 2 different projects. 

```
ON FIRST CLICK ON PUBLISH

Invariant Violation: Minifying source code requires the `generateSourceMaps` option to be `true`
    at invariant (/Users/xxxxx/node_modules/fbjs/lib/invariant.js:44:15)
    at transformCode (/Users/xxxxx/node_modules/react-native/packager/src/JSTransformer/worker/worker.js:71:3)
    at exports.transformAndExtractDependencies (/Users/xxxxx/node_modules/react-native/packager/src/JSTransformer/worker/worker.js:148:3)
    at handle (/Users/xxxxx/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/xxxxx/node_modules/worker-farm/lib/child/index.js:47:3)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
12:27:04
WARN: Output exceeds 32000 characters
12:27:05
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters

HERE I CLICK PUBLISH SECOND TIME, no changes made, AND IT WORKS
12:27:20
Publishing...
12:27:20
Building iOS bundle
12:27:20
Building Android bundle


12:27:36
WARN: Output exceeds 32000 characters
12:27:36
WARN: Output exceeds 32000 characters
12:27:36
WARN: Output exceeds 32000 characters
12:27:36
WARN: Output exceeds 32000 characters
12:27:36
WARN: Output exceeds 32000 characters
12:27:36
WARN: Output exceeds 32000 characters
12:27:37
WARN: Output exceeds 32000 characters
12:27:38
WARN: Output exceeds 32000 characters

```

**Comment by brentvatne** [comment] 2017-05-31 16:34
Yeah this is a weird one, it is some underlying problem in the react-native packager. There is some shared state in the packager that throws warnings the second time you try to fetch a `dev=false&minify=true` bundle (if you make changes to it since the first time you fetch it). Would really appreciate if someone was willing to dig into this, you should be able to reproduce it on react-native without Expo.

**Comment by tiaaaa123** [comment] 2017-05-31 19:29
I'm having this issue with `dev=true` and `minify=false`. Can't build Standalone app anymore...

**Comment by brentvatne** [comment] 2017-05-31 21:55
> I'm having this issue with dev=true and minify=false

🤔 ? seems backwards

**Comment by easadler** [comment] 2017-06-14 04:18
I'm having the same issue when publishing with dev=true and minify=false. I am still able to build standalone apps.

**Comment by brentvatne** [comment] 2017-06-14 04:29
@easadler - is it possible to share your project?

**Comment by Superpencil** [comment] 2017-06-15 08:40
+1

**Comment by fson** [comment] 2017-06-26 15:35
I was able to reproduce this with my project using Expo v16 and also v17 (by publishing twice in a row), but upgrading to Expo v18.0.0 fixed the issue. It seems that the underlying problem in metro-bundler has been fixed in the latest React Native release.

**Comment by brentvatne** [comment] 2017-06-26 19:45
woop! thanks @fson

**Closed by brentvatne** 2017-06-26 19:45 UTC
Labels: Status: Help Wanted, Type: Bug
