### ISSUE TITLE
Error: Couldn’t get GCM token on device

### ISSUE THREAD

**Issue by agostinhodev** [expo/expo#7714] opened 2020-04-07 14:19 UTC
SDK Version: 37.0.0
Platforms(Android/iOS/web/all): Android
I’m trying to get a notification token to use in Expo Notifications, but i’m getting the following error:

“Error: Couldn’t get GCM token on device”.
I’ve already tried to update expo-cli . I updated my SDK version and nothing works!
I did the expo login in Expo Client App and in terminal and nothing too.
I restart my PC, SmartPhone, clean cache and nothing want to work!
I configurate the firebase like this -> https://docs.expo.io/versions/latest/guides/using-fcm/ and nothing

i see all the probaly resolutions in forum and i try all, but no success.

**Comment by sjchmiela** [comment] 2020-04-07 16:56
I will close this issue as it is a duplicate of https://github.com/expo/expo/issues/7653 — let's keep all the information there!

**Closed by sjchmiela** 2020-04-07 16:56 UTC
Labels: Needs triage
