### ISSUE TITLE
Expo 47: `console.log` in `app.config.ts` crashes build in `expo-updates/scripts/createManifest.js`

### ISSUE THREAD

**Issue by phryneas** [expo/expo#19997] opened 2022-11-11 11:47 UTC
### Summary

Adding a `console.log` inside `app.config.ts` will have `expo-updates/scripts/createManifest.js` interpret that console output as part of the `entryFile` file name - crashing the whole `eas build`.

I detected this by replacing this error:
https://github.com/expo/expo/blob/78cca68c09c345e35634d9353cb2a9c4bc854c30/packages/expo-updates/scripts/createManifest.js#L37
with
```js
'Error loading application entry point ' + entryFile + ' relative to ' + possibleProjectRoot + ' or ' + possibleProjectRoot + '/..'
```
which then resulted in the error message
```
[RUN_GRADLEW] Error loading application entry point configured app for {
[RUN_GRADLEW]   bundleIdentifier: 'xxx',
[RUN_GRADLEW]   extra: {
[RUN_GRADLEW]     apiDomain: 'https://xxx.dev',
[RUN_GRADLEW]     eas: { projectId: 'xxx' }
[RUN_GRADLEW]   }
[RUN_GRADLEW] }
[RUN_GRADLEW] index.js relative to /tmp/circleci/eas-build-local-nodejs/16db90bf-ef45-4ddd-8d07-3f6958b1aa87/build/apps/web4/android or /tmp/circleci/eas-build-local-nodejs/16db90bf-ef45-4ddd-8d07-3f6958b1aa87/build/apps/web4/android/..
```

We were logging those values (`{ bundleIdentifier, extra }`) to see if all environment variables are handled correctly in all builds, since there are some slight differences between normal EAS builds and EAS update builds - and it helped us a ton debugging those. Unfortunately, it also breaks builds now.

### SDK Version

47

This did not happen in SDK 46.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.18 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 16.18.0 - /usr/bin/node
      Yarn: 3.2.1 - /usr/local/bin/yarn
      npm: 6.14.14 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 28, 30, 31
        Build Tools: 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0
    Expo Workflow: bare

### Minimal reproducible example

Just add a `console.log("something")` to the configuration file of any working expo project and try to EAS build it.

**Comment by EvanBacon** [comment] 2022-11-11 22:00
I cannot reproduce using:
- `yarn create expo-app`
- `yarn add expo-updates`
- `eas build -p ios`

with an `app.config.js`:

```js
console.log("disruptive\n\nthing");
module.exports = ({ config }) => {
  console.log("disruptive-internal");
  return {
    ...config,
  };
};
```
Packages:

```
 "expo": "~47.0.3",
 "expo-updates": "^0.15.4",
```

Perhaps you're using a version that doesn't have [this patch](https://github.com/expo/expo/commit/5f1639221c9d06f9b4eab56489e615bdc1d8823e).

**Comment by phryneas** [comment] 2022-11-11 22:06
Huh, that looks like it should address it.

I *did* update to Expo 47 and the problem just appeared after that - so I would have assumed I am on the newest packages, but I will take a look on monday - maybe somehow an old version did get tangled up in there.

I will report back.

**Comment by PedroBern** [comment] 2022-11-13 20:56
Same issue. The 47.0.3 patch didn't work for me. Removing the logs from app.config.js works (I will add the logs back when possible)

**Comment by phryneas** [comment] 2022-11-14 07:48
I can confirm that I am on these versions:
```
circleci@lenz-work:/workspaces/web4/apps/web4$ yarn why expo
└─ web4@workspace:apps/web4
   └─ expo@npm:47.0.3 (via npm:^47.0.0)
circleci@lenz-work:/workspaces/web4/apps/web4$ yarn why expo-updates
└─ web4@workspace:apps/web4
   └─ expo-updates@npm:0.15.4 [a239d] (via npm:~0.15.4 [a239d])
```

I'll try to create a reproduction.

**Comment by phryneas** [comment] 2022-11-14 08:48
I have created a minimal reproduction at https://github.com/phryneas/reproduction-expo-19997  
Just run
```sh
yarn eas build --platform android --local
```

**Comment by phryneas** [comment] 2022-11-18 21:06
@garrettg123 I read the source code of pretty much every involved package and started adding `console.log` statements in a lot of different places in my `node_modules` 😅

**Comment by brentvatne** [comment] 2022-11-25 02:34
@phryneas - thank you for the repro! the key thing here is that it works as expected on ios but not on android. i was able to reproduce it locally with your project by running `npx expo run:android --variant release`

<hr />

as an aside, i'd recommend against installing eas-cli to your project dependencies. we display this warning when you do:

```
Found eas-cli in your project dependencies.
It's recommended to use the "cli.version" field in eas.json to enforce the eas-cli version for your project.
Learn more: https://github.com/expo/eas-cli#enforcing-eas-cli-version-for-your-project
```

**Comment by brentvatne** [comment] 2022-11-25 02:38
related: https://github.com/expo/expo/pull/18906

**Comment by phryneas** [comment] 2022-11-25 07:56
> as an aside, i'd recommend against installing eas-cli to your project dependencies. we display this warning when you do:

We usually work in immutable/readonly environments so we cannot do any global package installations - and this allows it to be part of the local yarn cache that we can share more easily. 
I understand the recommendation, but without a global installation or `npx` always downloading a new copy, it's pretty much the best solution we have at this point, even if not recommended.

---
It's great that you could reproduce the problem - thanks for the fix :)

**Comment by raphaeltm** [comment] 2022-12-11 22:04
I'm glad I came across this issue. I was beating myself up trying to figure out why my build was broken after upgrading to Expo 47. Removing `console.log`s in my `app.config.js` fixed it. A bit annoying because I've had weird caching issues in the past accessing environment variables passed through the `extra` field, so I console log to see what the correct value is in `app.config.js` and then again in the application code to see if there's any discrepancies.

**Comment by zivc** [comment] 2022-12-13 00:24
Gosh, such a strange error but also happens to be a fix for me also.

Thank you for putting the effort in @phryneas

**Comment by igorcesarcode** [comment] 2022-12-13 13:49
@EvanBacon  I don't know if it has to do with the same problem, but I believe it does.

I'm having problems with app.config.ts as well.

I'm using this framework to configure my app.

When I give a command

```bash
   npx expo prebuild
```

the app compiles normally, but the hot reloading stops working.

I confirmed that it is in dev mode by setting " __DEV__ " to true.

using app.json with the same settings, hot reloading works normally.

Does it have something related?


```javascript
import dotenv from "dotenv";
import { ConfigContext, ExpoConfig } from "expo/config";
const APP_VARIANT = process.env.APP_VARIANT;

const IS_PROD = APP_VARIANT === undefined;
const PATH = IS_PROD ? `env/.env` : `env/.env.${process.env.APP_VARIANT}`;
dotenv.config({
  path: PATH,
});

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: process.env.APP_NAME,
  slug: process.env.SLUG,
  scheme: process.env.SCHEME,
  version: process.env.APP_VERSION,
  description: process.env.APP_NAME,
  privacy: "hidden",
  platforms: ["ios", "android"],
  userInterfaceStyle: "light",
  orientation: "portrait",

  ios: {
    bundleIdentifier: process.env.BUNDLE_PACKAGE,
    supportsTablet: false,
    buildNumber: process.env.BUILD_NUMBER,
    userInterfaceStyle: "light",
    icon: IS_PROD
      ? "./assets/icon.png"
      : `./assets/icon-${process.env.APP_VARIANT}.png`,
    backgroundColor: process.env.ICON_BACKGROUND,
    infoPlist: {
      NSCameraUsageDescription:
        "Este aplicativo usa a câmera para digitalizar códigos de barras e envio de notas.",
    },
  },
  android: {
    package: process.env.BUNDLE_PACKAGE,
    permissions: ["CAMERA", "RECORD_AUDIO"],
    versionCode: process.env.VERSION_CODE as unknown as number,
    userInterfaceStyle: "light",
    adaptiveIcon: {
      foregroundImage: IS_PROD
        ? "./assets/adaptive-icon.png"
        : `./assets/adaptive-icon-${process.env.APP_VARIANT}.png`,
      backgroundColor: process.env.ICON_BACKGROUND,
    },
  },
  assetBundlePatterns: ["**/*"],
  splash: {
    image: IS_PROD
      ? `./assets/splash.png`
      : `./assets/splash-${process.env.APP_VARIANT}.png`,
    resizeMode: "contain",
    backgroundColor: process.env.SPLASH_BACKGROUND,
  },
  plugins: [
    [
      "expo-image-picker",
      {
        photosPermission:
          "A imagem será usada para validar as suas missões e conceder os pontos correspondentes a tarefa realizada.",
      },
    ],
  ],
  extra: {
    eas: {
      projectId: process.env.PROJECT_ID,
    },
    apiEndpoint: process.env.API_ENDPOINT,
  },
});

```




Steps to reproduce

```bash
yarn create expo-app
```


Create app.config.ts with the informed settings

```bash
npx expo prebuild
```

```bash
yarn start 
```

Expected behavior: hot reloading does not work

**Comment by igorcesarcode** [comment] 2022-12-16 18:01
@EvanBacon after several tests identify a way to solve this problem
using the prefix REACT_APP


Ex: REACT_APP_BUILD_NUMBER=1


```javascript
import dotenv from "dotenv";
import { ConfigContext, ExpoConfig } from "expo/config";
const APP_VARIANT = process.env.REACT_APP_APP_VARIANT;
const IS_PROD = APP_VARIANT === undefined;
const PATH = IS_PROD
  ? `env/.env`
  : `env/.env.${process.env.REACT_APP_APP_VARIANT}`;
dotenv.config({
  path: PATH,
});

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: process.env.REACT_APP_APP_NAME,
  slug: process.env.REACT_APP_SLUG,
  scheme: process.env.REACT_APP_SCHEME,
  version: process.env.REACT_APP_APP_VERSION,
  description: process.env.REACT_APP_APP_NAME,
  privacy: "hidden",
  platforms: ["ios", "android"],
  userInterfaceStyle: "light",
  orientation: "portrait",

  ios: {
    bundleIdentifier: process.env.REACT_APP_BUNDLE_PACKAGE,
    googleServicesFile: "./GoogleService-Info.plist",
    supportsTablet: false,
    buildNumber: process.env.REACT_APP_BUILD_NUMBER,
    userInterfaceStyle: "light",
    icon: IS_PROD
      ? "./assets/icon-qa.png"
      : `./assets/icon-${process.env.REACT_APP_APP_VARIANT}.png`,
    backgroundColor: process.env.REACT_APP_ICON_BACKGROUND,
    infoPlist: {
      NSCameraUsageDescription:
        "Este aplicativo usa a câmera para digitalizar códigos de barras e envio de notas.",
    },
  },
  android: {
    package: process.env.REACT_APP_BUNDLE_PACKAGE,
    googleServicesFile: "./google-services.json",
    permissions: ["CAMERA", "RECORD_AUDIO"],
    versionCode: process.env.REACT_APP_VERSION_CODE as unknown as number,
    userInterfaceStyle: "light",
    adaptiveIcon: {
      foregroundImage: IS_PROD
        ? "./assets/adaptive-icon-qa.png"
        : `./assets/adaptive-icon-${process.env.REACT_APP_APP_VARIANT}.png`,
      backgroundColor: process.env.REACT_APP_ICON_BACKGROUND,
    },
  },
  assetBundlePatterns: ["**/*"],
  splash: {
    image: IS_PROD
      ? `./assets/splash-qa.png`
      : `./assets/splash-${process.env.REACT_APP_APP_VARIANT}.png`,
    resizeMode: "contain",
    backgroundColor: process.env.REACT_APP_SPLASH_BACKGROUND,
  },
  plugins: [
    [
      "expo-build-properties",
      {
        ios: {
          useFrameworks: "static",
        },
      },
    ],
    "@react-native-firebase/app",
    "@react-native-firebase/perf",
    "@react-native-firebase/crashlytics",
    [
      "expo-image-picker",
      {
        photosPermission:
          "A imagem será usada para validar as suas missões e conceder os pontos correspondentes a tarefa realizada.",
      },
    ],
    ["./plugins/withDisableForcedDarkModeAndroid.js", {}],
  ],
  extra: {
    eas: {
      projectId: process.env.REACT_APP_PROJECT_ID,
    },
    apiEndpoint: process.env.REACT_APP_API_ENDPOINT,
  },
});

```

**Comment by atajadod** [comment] 2022-12-20 19:22
Thank you. This post saved me lots of time. 
Removing the console.log fixed the issue.
Regards.

**Comment by moygoca1** [comment] 2023-01-25 00:58
Im having a similar issue where after upgrading from SDK 45 to Expo SDK 47, the app crashes when adding `console.error("message")` If I comment this line then it works fine.

In my case `eas build` works fine the problem is when I do `eas update` then it crashes the app.

**Comment by brentvatne** [comment] 2023-04-19 19:56
this is resolved in SDK 48

**Closed by brentvatne** 2023-04-19 19:56 UTC
Labels: Issue accepted, CLI

**Comment by bkamrani** [comment] 2023-05-05 21:10
@EvanBacon I'm pulling my hair as after the 47 -> 48 upgrade, Fast Refresh has stopped working on both the simulator and device. Do you know what could be wrong or how to debug it? I see in the build logs that CI=1 for dev profile build where the fast refresh is working. 

Also, FWIT, console.log only works if placed before functional component definition. i.e., 

```
console.log('foo');  // logs foo
export default function ProfileScreen( { navigation, route } )  {
console.log('bar');  // logs nothing
...
}
```
