### ISSUE TITLE
[SDK50][expo-router 3] Tabs no longer respect bottom insets in pwa iOS

### ISSUE THREAD

**Issue by rifaldhiaw** [expo/expo#26011] opened 2023-12-19 02:25 UTC
### Minimal reproducible example

https://github.com/rifaldhiaw/expo-router-asyncRoute

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

In SDK 49 the Tabs component was working just fine. It respects bottom insets in PWA iOS. But in SDK50 expo router 3, it no longer respects the bottom insets, and even if I try to set it manually somehow it still does not work.

Deployed example: https://expo-sdk50-test.pages.dev 
- Add to home screen in iOS
- Open it and you will see the bottom tabs overlap with the iOS UI Navigation

Screenshot:
<img src="https://github.com/expo/expo/assets/7936061/d5832e9b-be14-4d6e-a3e7-5fae2c395921" width=40% height=40%>

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.volta/tools/image/node/18.12.1/bin/node
      Yarn: 1.22.11 - ~/.volta/tools/image/yarn/1.22.11/bin/yarn
      npm: 8.19.2 - ~/.volta/tools/image/node/18.12.1/bin/npm
    Managers:
      CocoaPods: 1.13.0 - /Users/ruangguru/.gem/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.1
        System Images: android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.0-preview.3 => 50.0.0-preview.3
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.0 => 0.73.0
      react-native-web: ~0.19.6 => 0.19.9
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by marklawlor** [comment] 2023-12-19 03:03
No changes were made between v2 and v3 with Tabs and/or the use of SafeAreaContext, so this may be an upstream issue with React Navigation / SafeArea

For reference Expo Router sets the `SafeAreaProvider` automatically https://github.com/expo/expo/blob/44d03f59e25b01fbfee82075da18dd7f8ce44e96/packages/expo-router/src/ExpoRoot.tsx#L42-L48

And the Tabs component simply modifies its children: https://github.com/expo/expo/blob/main/packages/expo-router/src/layouts/Tabs.tsx

Do you experience the same issue with an vanilla React Navigation project? If not, can you please provide a copy of your lockfile from both projects so we can compare the version differences

**Comment by rifaldhiaw** [comment] 2023-12-19 03:21
I haven't tried it yet with react-navigation. But here is my yarn lock from my main project. 

https://gist.github.com/rifaldhiaw/799be19c281402e8f992fec3b3bcee80
https://gist.github.com/rifaldhiaw/3416bbfce2c8292cbbaea3ccc4b290de

It seems the only version changes is just 
from: react-native-safe-area-context@4.6.3
to: react-native-safe-area-context@4.7.4

**Comment by rifaldhiaw** [comment] 2023-12-19 03:40
Tried to downgrade it to react-native-safe-area-context@4.6.3, still no luck.
The repro source code and the deployed version use the 4.6.3 version now. The insets show 0 value

![IMG_0905](https://github.com/expo/expo/assets/7936061/a059a47c-8b7a-4b16-a3d1-6aecbe32772b)

**Comment by marklawlor** [comment] 2024-01-15 12:38
I'm going to close this issue as Expo Router modify any logic how `react-navigation` renders its layouts. Until the issue is isolated to Expo Router, this appears to be an upstream issue with either `react-navigation` or `react-native-safe-area-context`

**Closed by marklawlor** 2024-01-15 12:38 UTC
Labels: needs review, Router
