### ISSUE TITLE
[localization][ios] methods not available if user hasn't defined language

### ISSUE THREAD

**Issue by cesconix** [expo/expo#5127] opened 2019-07-31 16:56 UTC
### Environment

```
  Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.0/11M362v - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.6
```

### Steps to Reproduce

Import expo-localization in your app: `import * as Localization from 'expo-localization'` and try to execute with an iOS Simulator.

### Expected Behavior

The app is up and running.

### Actual Behavior

The following error occurs (screenshot below): `undefined is not an object (evaluating 'locale.replace')`

**If I try to run the same app on my iPhone, it works regularly.**

Analyzing the code inside `node_modules/expo-localization/build/ExpoLocalization.js `, seems that "**locale**" property inside "**NativeModulesProxy**" (**@unimodules/core**) does not exist on iOS Simulator.

I show you the list of `Object.keys(NativeModulesProxy)` both in the simulator and in my real device:

Simulator -> Object.keys(NativeModulesProxy):
```
Array [
  "getLocalizationAsync",
  "addListener",
  "removeListeners",
]
```

Real Device -> Object.keys(NativeModulesProxy):
```
Array [
  "locales",
  "timezone",
  "isRTL",
  "country",
  "locale",
  "isoCurrencyCodes",
  "getLocalizationAsync",
  "addListener",
  "removeListeners",
]
```

![Screenshot 2019-07-31 at 18 46 34](https://user-images.githubusercontent.com/244004/62231499-75090c80-b3c4-11e9-9a2b-02e678d23a41.png)

**Comment by cesconix** [comment] 2019-07-31 19:13
I solved changing the default system language on Settings -> General -> Language & Region.

**Comment by eveningkid** [comment] 2019-08-06 06:39
I encounter the exact same problem but defining a default system language does not do it.

What could be the reason of the problem to appear only under some conditions?

**Comment by mskg** [comment] 2019-09-19 07:51
I can confirm, changing the language once solves the problem.

**Comment by bit-scrambler** [comment] 2019-09-26 09:07
I don't think it should be closed... the problem is that if the phone (either device or simulator) has the default language because the user didn't set it, all the language properties like timezone, country, currency and so on are undefined raising the exception
I'm able to reproduce the issue with iOS13.

**Comment by sharnik** [comment] 2019-09-30 08:56
It's easy to reproduce just creating a new iOS simulator with iOS13 and trying to access `Localization.locale`. 

@cesconix The problem might be "solved" for you, but probably not for your users. I'd suggest re-opening it, so it can be examined by the Expo team.

**Comment by cesconix** [comment] 2019-09-30 08:58
Yes, you're right. I open the ticket again.

**Comment by LucaRed** [comment] 2019-11-15 16:15
This bug affects real devices too, not only the simulator!

I have a recently formatted iPad, on iOS 13.2.2. If I import `expo-localization` I can't run the app inside Expo Client, and compiled IPAs crash immediately on startup.

After changing the language once in iPadOS Settings the problem doesn't appear anymore. But that's not a solution...

**Comment by amkisko** [comment] 2019-12-11 14:16
Temporary workaround:
```javascript
export const detectLanguage = () => {
  let locale = "en";
  try {
    const Localization = require("expo-localization");
    [locale] = Localization.locale.split("-");
  } catch (error) {
    // TODO: Show pop-up with language selection?
    console.log(error);
  }
  return locale;
};
```

**Comment by FiberJW** [comment] 2020-07-14 19:54
I can't reproduce this on a fresh iPhone 11 simulator on SDK 38 by importing expo-localization and `console.log(Localization.locale)`.

This may have been fixed with this commit https://github.com/expo/expo/commit/ed1edcc5b1452bff0f3a7d691ca442a90907a004#diff-83dc1ff5af2424b1de2fc7c3259dfdf8, so I'm going to close this for now.

If you can reproduce this with the current SDK version, feel free to open up a new issue report!

**Closed by FiberJW** 2020-07-14 19:54 UTC
Labels: Localization, iOS
