### ISSUE TITLE
[expo-image]: Expo Image not showing up like React Native Image

### ISSUE THREAD

**Issue by VNDRN** [expo/expo#27783] opened 2024-03-21 08:53 UTC
### Minimal reproducible example

https://snack.expo.dev/@itpocket/expo-image-vs-rn-image

### What platform(s) does this occur on?

Android, iOS, Web

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

I wanted to replace all occurrences of RN Image with the Expo Image component, but noticed that some of my images disappeared. I wanted to report this in case it's a bug, or know why they do not appear with Expo Image. 

### Environment

Reproducable snack: 
https://snack.expo.dev/@itpocket/expo-image-vs-rn-image

### Expo Doctor Diagnostics

/

**Comment by VNDRN** [comment] 2024-03-26 08:49
I'd expect the expo image component to be a drop in replacement for the React Native Image. So it should take the same default styling as that one. 

I noticed in my snack that removing the flex: 1 makes the image show up as a pink background but the image itself is still invisible.

**Comment by andresribeiro** [comment] 2024-06-12 22:15
+1

`background-color` works on iOS and Web, but not on Android

**Comment by IcyFeVA** [comment] 2024-06-23 06:18
+1 
I had my view set up with react-native Image, where it was working perfectly fine. Switching to expo-image looks wrong and the styles seem to not be working. Also, I noticed content that is visually below the image, is also not there anymore.

**Comment by Nicklas-17** [comment] 2024-07-23 14:05
+1

**Comment by VNDRN** [comment] 2024-09-19 11:09
@tsapeta , any update on this?

**Comment by Jocelino7** [comment] 2024-10-06 09:32
I'm facing the same problem, Expo-Image won't render, In my case, I'm using Expo Go.

**Comment by aleqsio** [comment] 2024-10-08 14:14
This doesn't seem to happen on the latest version of expo-image, so it should probably be fixed in Expo Go on SDK52.

Remember that adding `flex: 1` causes the container to have `flex-basis: 0` which makes the image not appear.
This follows how a view would behave so it's expected behavior IMO.

```
<ExpoImage
    source={require('./assets/icon.png')}
    style={{
      width: 100,
      height: 100,
    }}
/>
```

Renders correctly on iOS, Web and Android in a development build. Expo Go for SDK52 is coming soon.

**Closed** 2024-11-07 17:03 UTC
Labels: Image, pending closure, Issue accepted

**Comment by aman-marstracktechnology** [comment] 2025-01-07 13:21
<Image
        style={styles.image}
        source={{
          uri: "https://.s3.amazonaws.com/68583999c___some__link",
        }}
        //  placeholder={{ blurhash }}
        contentFit="cover"
      />
      i am not able to view this in the android but it can be viewed into the ios
      
      style
       image: {
    marginLeft: 10,

    width: "90%", 
    height: 200, 
    borderRadius: 20,
  },

**Comment by DiegoBistro** [comment] 2025-01-10 09:35
same issue on latest version
```
"expo": "~52.0.24",
"expo-image": "~2.0.3"
```

on Expo Go my images (local and from url) are displayed correctly if I use react-native Image

But they are not displayed if I use expo-image.

on the browser the images work correctly with both.

```
import { Image } from "expo-image";    // Work only on Browser

import {Image } from "react-native";   // Work on Expo Go and Browser
```

**Comment by mattwkelly** [comment] 2025-01-28 23:16
We're having this issue too. Migrating back to react-native Image fixes it.

**Comment by DiegoBistro** [comment] 2025-01-29 18:05
Ok, in my case the problem was that Expo Image is not getting the style I was setting with Tailwind (called Nativewind in React Native).

**The problem is that Nativewind only works with React native components and Expo Images is not recognized by Nativewind and does not translate Tailwind class to css.**

So all Expo images have wrong css like heigh: 0 or something like that.

SO:
**if you are using Nativewid**, you need to call

```
import { Image } from "expo-image";
import { cssInterop } from "nativewind";

cssInterop(Image, { className: "style" });
```

this utility function tells Nativewind that Expo Image is a component and should translate Tailwind classes correctly

**Comment by cupid20103** [comment] 2025-04-07 11:19
That's right, the latest expo-image doesn't work with nativewind, so you have to use another way to add styles.
For example:

```
<Image
        style={{ height: "100%", width: "100%" }} // No tailwind css
        source={image}
        placeholder={title}
        contentFit="cover"
        transition={1000}
      />
```

**Comment by MouraNYuri** [comment] 2025-08-30 20:08
Guys, try it on the image: style={{ width: 100, height: 100 }}, it works fine on Android
