### ISSUE TITLE
Local Notifications should work in ExpoKit

### ISSUE THREAD

**Issue by terribleben** [expo/expo#891] opened 2017-10-31 18:24 UTC
- Remote notifications are _not_ expected to work in ExpoKit projects, for now.
- Local Notifications should work.
- Unfortunately the codepaths for these two things overlap significantly, and we do not always do a good job disambiguating.
- We should make sure LocalNotifications (and the associated permissions methods) work in all situations (client, Stanalone, and ExpoKit), while continuing to prevent Remote Notifications from working in ExpoKit.

**Comment by sjchmiela** [comment] 2018-01-08 13:21
## iOS

Local notifications work out-of-the-box in detached projects, the only problems I found are:
- `askAsync` doesn't resolve, because [`[RCTSharedApplication() registerForRemoteNotifications]`](https://github.com/expo/universe/blob/master/exponent/ios/Exponent/Versioned/Core/Api/Permissions/EXRemoteNotificationRequester.m#L44) fails to register for remote notifications by default, because detached applications aren't configured to handle remote notifications immediately and the default `AppDelegate` provided in detached projects doesn't implement
    ```objective-c
    - (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
    {
        [[ExpoKit sharedInstance] application:application didFailToRegisterForRemoteNotificationsWithError:error];
    }
    ```
- `status` of notification permissions (both local and remote) is `undetermined` (probably unless remote notifications are configured), because:

    ```objective-c
      EXPermissionStatus status = (RCTSharedApplication().isRegisteredForRemoteNotifications) ?
        EXPermissionStatusGranted :
        EXPermissionStatusUndetermined;
    ```

How can we fix it?

- We could extract managing `userNotificationSettings` from `EXRemoteNotificationRequester` and put it into `EXLocalNotificationRequester`. Then we could set [`Permissions.NOTIFICATIONS`](https://github.com/expo/universe/blob/master/libraries/exponent-sdk/src/Permissions.js#L52) to some specific value, forward the call to a new `EXNotificationRequester` that would call one or both of the `NotificationRequesters` basing on the type of notifications required.
- Unfortunately, `getAsync(Permissions.Notifications)` will be tricky, we would have to use [`RCTSharedApplication().currentUserNotificationSettings`](https://developer.apple.com/documentation/uikit/uiapplication/1623092-currentusernotificationsettings?language=objc) which contains `types` property — “A bitmask of the notification types that your app is allowed to use.” There are four types, [as documented by Apple](https://developer.apple.com/documentation/uikit/uiusernotificationtype?language=objc). However, anyone using `Permissions` module would expect return to be either `granted`, `denied` or `undetermined`, so we could either:
  - expand return values to `granted, onlySound, onlyAlert, onlyBadge, noSound, noAlert, noBadge, denied`,
  - return `granted` when all the types have been granted, `denied` when none of the types is granted, `undetermined` otherwise and return types values as different properties: `{ status: 'granted', sound: 'granted', alert: 'denied', badge: 'granted'}`,
  - pick alert as “the behavior developers ask for” and return `granted`/`denied` based only on this property,
  - mix the previous two solutions.

I'll go on and split the `EXRemoteNotificationRequester` and later we can decide how to handle `getAsync`. 🙂

**Comment by sjchmiela** [comment] 2018-01-10 14:58
## Android

On Android, however, it looks like remote notifications just work (in detached project). Also, `{get, ask}Async` return `status = granted` even when the notifications are disabled. The source suggests that this is expected behavior,

https://github.com/expo/universe/blob/master/exponent/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/PermissionsModule.java#L54-L57

however, [this] Stackoverflow answer suggested it is possible to get the real status of notification permissions, which worked. Fix is included in https://github.com/expo/universe/pull/1805.

**Comment by sjchmiela** [comment] 2018-03-20 10:06
All the associated PRs were merged, so I think we can safely close this issue. 🙂

**Closed by sjchmiela** 2018-03-20 10:06 UTC
Labels: in review, project: android-runtime, project: docs, project: expokit, project: ios-runtime
