### ISSUE TITLE
Build Failure: android.support.annotations missing for bare Expo - AV

### ISSUE THREAD

**Issue by ecexplorer** [expo/expo#5474] opened 2019-08-28 20:07 UTC
### Environment

Android
Bare (standalone) usage of expo-av module

### Steps to Reproduce

- Make a React Native CLI project
- Add react-native-unimodules
- Add expo-av
- Attempt to build Android project (you'll get errors from expo av that Nullable & android.support.annotations is missing)
It looks like from the gradle comments that having it conflicts with another part of expo, but not having definitely breaks the bare workflow.

### Expected Behavior

The project should build, and gradle should include android.support.annotations.

### Actual Behavior

15 build errors due to Nullable not being found as a result of android.support.annotations missing

**Comment by cruzach** [comment] 2019-08-28 21:46
I believe this is a duplicate of [5310](https://github.com/expo/expo/issues/5310)

If there's something different about this just let me know and add those details, otherwise we can close this issue

**Comment by sjchmiela** [comment] 2019-09-24 11:16
On `expo-av@7.0.1` this bug should be fixed, thanks @lgraubner!

**Closed by sjchmiela** 2019-09-24 11:16 UTC
Labels: bug
