### ISSUE TITLE
Possible Unhandled Promise Rejection (id:0) expoKeepAwake ^7.0.0

### ISSUE THREAD

**Issue by onebuck-code** [expo/expo#5944] opened 2019-10-11 04:06 UTC
### Environment

 Expo CLI 2.19.5 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.2.0 => 5.2.0 
      @types/react: ^16.9.2 => 16.9.2 
      @types/react-native: ^0.60.14 => 0.60.14 
      react: 16.8.6 => 16.8.6 
      react-native: 0.60.5 => 0.60.5 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 2.19.5

Target: Android

### Steps to Reproduce

In the very beginning of the app, I put something like below: 
"
activateKeepAwake();
AppRegistry.registerComponent(name, () => App);"

### Expected Behavior
This is to keep the app awake all the time.

### Actual Behavior

It doesn't work, the screen went off as per the Display setting of the android device.
In the logkitty, I saw the below error:

[11:46:24] W | ReactNativeJS ▶︎ Possible Unhandled Promise Rejection (id: 0):
                             │ Error: Unable to activate keep awake
                             │ createErrorFromErrorData@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:1735:26
                             │ http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:1694:51
                             │ __invokeCallback@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2259:23
                             │ http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:1985:34
                             │ __guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2173:15
                             │ invokeCallbackAndReturnFlushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:1984:21
                             └ invokeCallbackAndReturnFlushedQueue@[native code]

**Comment by cruzach** [comment] 2019-10-11 15:04
This in a bare workflow project, I'm assuming, since you're using `react-native v0.60.5`?

It's best practice to use the version of RN associated with the most recent Expo SDK release (v0.59 as of right now)

**Comment by vvscode** [comment] 2019-12-27 07:38
@cruzach  I have the same issue. `unimodules` are installed. 

```
YellowBox.js:71 Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'activate' of undefined
TypeError: Cannot read property 'activate' of undefined
    at activateKeepAwake (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:168754:32)
    at AppContainer.componentDidMount$ (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:168540:54)
```

When I add breakpoint inside `ExpoKeepAwake.js` I see next picture (No Expo Keep Awake): 

![Screenshot 2019-12-27 at 09 36 41](https://user-images.githubusercontent.com/6904368/71507229-7d3e7880-288c-11ea-83fa-9fba9a31d92c.png)

For me it means that unimodules configured properly, but something is wrong with kee-awake. Am  I wrong? 

```json
    "expo-keep-awake": "^8.0.0",
    "react-native": "0.61.4",
```

**Comment by vvscode** [comment] 2019-12-27 07:41
tried to downgrade to v7 and got  in metro console

```
WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating '_ExpoKeepAwake.default.activate')
activateKeepAwake@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:168819:27
componentDidMount$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:168540:54
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29439:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29614:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29439:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29515:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29525:21
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3343:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3444:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30768:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30804:19
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31023:33
callImmediates@[native code]
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2753:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2530:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2736:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2529:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
```

**Comment by vvscode** [comment] 2019-12-27 11:37
Looks like in my case it was caused by wrong patching some of ios files (AppDelegate.m)

**Comment by cruzach** [comment] 2019-12-27 14:58
Thanks for the info @vvscode ! 

@onebuck-code I'm going to close this for inactivity, and I tested this on SDK 36 and keep awake works no problem. Let me know if you still have issues

**Comment by kopax** [comment] 2020-01-02 13:28
I have the same error with `SDK36`:

```javascript

[Unhandled promise rejection: Error: Unable to activate keep awake]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:99:50 in fn
- node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.js:15:52 in moduleName.methodInfo.name
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/regenerator-runtime/runtime.js:170:17 in Promise$argument_0
- node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:23 in doResolve
- node_modules/promise/setimmediate/core.js:66:12 in Promise
- node_modules/regenerator-runtime/runtime.js:169:27 in Promise$argument_0
- node_modules/regenerator-runtime/runtime.js:192:38 in enqueue
- node_modules/regenerator-runtime/runtime.js:216:8 in exports.async
- node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.js:10:62 in moduleName.methodInfo.name
- node_modules/expo-keep-awake/build/index.js:10:58 in activateKeepAwake
- node_modules/expo/AppEntry.js:8:2 in <global>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:201:45 in guardedLoadModule
* http://192.168.0.16:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:188462:4 in global code
```

And `expo diagnostics`:

```javascript
 expo diagnostics

  Expo CLI 3.11.3 environment info:
    System:
      OS: Linux 5.3 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 13.5.0 - ~/.nvm/versions/node/v13.5.0/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v13.5.0/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v13.5.0/bin/npm
    npmGlobalPackages:
      expo-cli: 3.11.3
```

Could we please reopen this?

**Comment by Lpaydat** [comment] 2020-01-07 20:03
I have the same issue but under a condition.

After scan QR code, at the moment the expo will finish building process, expo client must open as the active app on mobile screen (not in the background and the device screen is not turn off).

If the above condition is met (expo client is active while the building process finish), this error will not appear. But if not, it will generate this issue the moment the expo client is active again.

P.S.: Sorry for my bad english, it's not my mother tongue but I hope it's understandable.

**Comment by ramisalem** [comment] 2020-07-01 10:31
Same for me

**Comment by beygi** [comment] 2020-07-01 15:02
same here

**Comment by cruzach** [comment] 2020-07-01 19:39
I haven't been able to reproduce this so far with a blank project (tried both managed and bare workflows), after running `yarn add expo-keep-awake` and putting 

```
import { activateKeepAwake } from "expo-keep-awake";

activateKeepAwake();
```

in the root component file (for me, `App.tsx`). If you can, please provide a minimal reproducible demo

**Comment by RodrigoFraga** [comment] 2020-09-01 00:34
I have the same problem

**Comment by omerdn1** [comment] 2020-09-02 11:50
We're facing the same issue - running a bare RN 0.61.5 project

**Comment by cruzach** [comment] 2020-09-10 14:53
If you're having this issue, please provide a minimal reproducible demo we can use to investigate

**Comment by jamt0** [comment] 2020-09-16 02:46
The same error, in termux

**Comment by fabio-alvarenga** [comment] 2020-10-14 14:18
I'm having the same issue with Expo `SDK 39`.

**Comment by n9** [comment] 2020-10-15 10:52
@cruzach 
I have got same error. What I did:
- Generated new expo app (non-bare, with typescript, with tabs). (No code modifications.)
- Run `npm start`.
- Scan QR code using Expo client on Android 10.

`expo diagnostics`:
```
  Expo CLI 3.28.0 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
    npmPackages:
      expo: ~39.0.2 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```


Then after app started it showed 3 error logs:

```
[Unhandled promise rejection: Error: Unable to activate keep awake]
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:103:50 in promiseMethodWrapper
- node_modules\@unimodules\react-native-adapter\build\NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
- node_modules\expo-keep-awake\build\index.js:10:58 in activateKeepAwake
- node_modules\expo\build\launch\registerRootComponent.expo.js:6:4 in <global>
- node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
- node_modules\expo\AppEntry.js:1:0 in <global>
- node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
- node_modules\metro\src\lib\polyfills\require.js:201:44 in guardedLoadModule
* http://192.168.253.202:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:149454:3 in global code
```

```
[Unhandled promise rejection: Error: Current activity not found. Make sure to call this method while your application is in foreground.]
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:103:50 in promiseMethodWrapper
- node_modules\@unimodules\react-native-adapter\build\NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
- node_modules\expo-splash-screen\build\SplashScreen.js:23:7 in preventAutoHideAsync
- node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
- node_modules\regenerator-runtime\runtime.js:293:29 in invoke
- node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
- node_modules\regenerator-runtime\runtime.js:154:27 in invoke
- node_modules\regenerator-runtime\runtime.js:189:16 in PromiseImpl$argument_0
- node_modules\react-native\node_modules\promise\setimmediate\core.js:45:6 in tryCallTwo
- node_modules\react-native\node_modules\promise\setimmediate\core.js:200:22 in doResolve
- node_modules\react-native\node_modules\promise\setimmediate\core.js:66:11 in Promise
- node_modules\regenerator-runtime\runtime.js:188:15 in callInvokeWithMethodAndArg
- node_modules\regenerator-runtime\runtime.js:211:38 in enqueue
- node_modules\regenerator-runtime\runtime.js:238:8 in exports.async
- node_modules\expo-splash-screen\build\SplashScreen.js:23:7 in preventAutoHideAsync
* hooks\useCachedResources.ts:11:4 in loadResourcesAndDataAsync
- node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
- node_modules\regenerator-runtime\runtime.js:293:29 in invoke
- node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
- node_modules\regenerator-runtime\runtime.js:154:27 in invoke
- node_modules\regenerator-runtime\runtime.js:189:16 in PromiseImpl$argument_0
- node_modules\react-native\node_modules\promise\setimmediate\core.js:45:6 in tryCallTwo
- node_modules\react-native\node_modules\promise\setimmediate\core.js:200:22 in doResolve
- node_modules\react-native\node_modules\promise\setimmediate\core.js:66:11 in Promise
- node_modules\regenerator-runtime\runtime.js:188:15 in callInvokeWithMethodAndArg
- node_modules\regenerator-runtime\runtime.js:211:38 in enqueue
- node_modules\regenerator-runtime\runtime.js:238:8 in exports.async
* hooks\useCachedResources.ts:11:4 in loadResourcesAndDataAsync
* http://192.168.253.202:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:128815:31 in <unknown>
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15561:31 in commitHookEffectListMount
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15618:35 in commitPassiveHookEffects
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:265:4 in invokeGuardedCallbackImpl
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:476:2 in invokeGuardedCallback
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18795:29 in flushPassiveEffectsImpl
- node_modules\scheduler\cjs\scheduler.development.js:653:23 in unstable_runWithPriority
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17650:21 in performSyncWorkOnRoot
* [native code]:null in performSyncWorkOnRoot
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5321:31 in runWithPriority$argument_1
- node_modules\scheduler\cjs\scheduler.development.js:653:23 in unstable_runWithPriority
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5316:21 in flushSyncCallbackQueueImpl
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5304:28 in flushSyncCallbackQueue
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17125:30 in scheduleUpdateOnFiber
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:20527:14 in updateContainer
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:21068:17 in render
- node_modules\react-native\Libraries\ReactNative\renderApplication.js:54:4 in renderApplication
- node_modules\react-native\Libraries\ReactNative\AppRegistry.js:117:25 in runnables.appKey.run
- node_modules\react-native\Libraries\ReactNative\AppRegistry.js:213:4 in runApplication
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:416:4 in __callFunction
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:109:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue
```

```
[Unhandled promise rejection: Error: Current activity not found. Make sure to call this method while your application is in foreground.]
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:103:50 in promiseMethodWrapper
- node_modules\@unimodules\react-native-adapter\build\NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
- node_modules\expo-splash-screen\build\SplashScreen.js:29:7 in hideAsync
- node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
- node_modules\regenerator-runtime\runtime.js:293:29 in invoke
- node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
- node_modules\regenerator-runtime\runtime.js:154:27 in invoke
- node_modules\regenerator-runtime\runtime.js:189:16 in PromiseImpl$argument_0
- node_modules\react-native\node_modules\promise\setimmediate\core.js:45:6 in tryCallTwo
- node_modules\react-native\node_modules\promise\setimmediate\core.js:200:22 in doResolve
- node_modules\react-native\node_modules\promise\setimmediate\core.js:66:11 in Promise
- node_modules\regenerator-runtime\runtime.js:188:15 in callInvokeWithMethodAndArg
- node_modules\regenerator-runtime\runtime.js:211:38 in enqueue
- node_modules\regenerator-runtime\runtime.js:238:8 in exports.async
- node_modules\expo-splash-screen\build\SplashScreen.js:29:7 in hideAsync
* hooks\useCachedResources.ts:24:27 in loadResourcesAndDataAsync
- node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
- node_modules\regenerator-runtime\runtime.js:293:29 in invoke
- node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
- node_modules\regenerator-runtime\runtime.js:154:27 in invoke
- node_modules\regenerator-runtime\runtime.js:164:18 in PromiseImpl.resolve.then$argument_0
- node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
- node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue
```

**Comment by cruzach** [comment] 2020-11-03 15:38
@n9 so you're getting this error without even having `expo-keep-awake` installed?

I still haven't been able to reproduce this. **If you would like this issue investigated, please provide:**

- whether it's happening in the bare workflow or the managed workflow
- whether it's iOS or Android (and the OS version)
- a link to a [snack](https://snack.expo.io/) with all the code I need to reproduce this 

otherwise, there's not enough information here for us to try and help. Please refrain from just commenting "having this issue too" since it doesn't provide us with any useful information

**Comment by n9** [comment] 2020-11-03 16:02
@cruzach I think the requested information is already provided my in comment:)

*"whether it's happening in the bare workflow or the managed workflow"*
- Generated new expo app (**non-bare**, with typescript, with tabs). (**No** code **modifications.**)
- =managed

*"whether it's iOS or Android (and the OS version)"*
- Scan QR code using Expo client on **Android 10**.

*"a link to a snack with all the code I need to reproduce this"*
- it's not my code - just *empty* generated project

PS: Feel free to close the issue. It is no longer issue for me. I was evaluating Expo in that time. (I have switched to Xamarin.)

**Comment by cruzach** [comment] 2020-11-03 16:05
Yes, but every other comment here stated that it was in the **bare** workflow, so I wanted to get some clarity on which it was. I followed your steps exactly and didn't see the error (`expo-keep-awake` is not installed in the tabs template project so I'm not sure how that error could've ever happened)

**Comment by kopax** [comment] 2020-11-03 17:06
I was having this error in the managed workflow. I have no clue how I solved it (I upgraded to expo SDK38), and that's a shame since I see how many people are having this issue now. Did people try to run `expo start -c` ? Also try to simplify the root component to see if you have this error still as it could be a side effect. 

I agree with Charlie, if no one can give a repro, this will be hard for expo team to invistigate.

**Comment by cruzach** [comment] 2020-11-04 16:11
Closing this for now, will reopen if the following is provided

> 
> I still haven't been able to reproduce this. **If you would like this issue investigated, please provide:**
> 
> * whether it's happening in the bare workflow or the managed workflow
> * whether it's iOS or Android (and the OS version)
> * a link to a [snack](https://snack.expo.io/) with all the code I need to reproduce this
> 
> otherwise, there's not enough information here for us to try and help. Please refrain from just commenting "having this issue too" since it doesn't provide us with any useful information

**Closed by cruzach** 2020-11-04 16:11 UTC
Labels: Bare Workflow, KeepAwake, needs repro

**Comment by andersoncscz** [comment] 2021-04-17 00:06
I'm having the same issue: Error: **Unhandled promise rejection: Error: Unable to activate keep awake** on Android.
I tried the following templates without changing, just running them:
- expo-template-bare-minimum
- expo-template-bare-typescript

**Steps to reproduce:**
- Run the app, App.ts will be mount.
- Press back button so that the app will be waiting in background, App.ts will be unmount.
- Open it again by pressing its icon, not listing opened apps to maximized it, (the app is already opened, but in background).
- Promise appears.

Doing that I noticed that the app tries to mount again, like it does the first time the app opens.
This behavior does not happen with: npx react-native init MyApp --template react-native-template-typescript.

The app created by the react-native init is mount just once, no matter if I try to open again, by
pressing its icon, by or maximizing it again from the list of opened apps.

I don't know if it's a expo behavior, but using the react-native init, the app stayed awake all the time.

**Comment by joseocabarcas** [comment] 2021-04-22 20:29
I'm having the same issue with expo-template-bare-typescript

**Comment by brentvatne** [comment] 2021-04-22 20:36
are you using npm 7 by chance?

**Comment by joseocabarcas** [comment] 2021-04-22 20:39
6.14.5, This error started to happen to me when I updated to SDK 41

**Comment by brentvatne** [comment] 2021-04-22 20:41
@joseocabarcas - so you initialized a new sdk 41 project or you upgraded one and found this problem?

**Comment by joseocabarcas** [comment] 2021-04-22 20:44
I started with expo-template-bare-typescript (sdk 40) and the error started to occur when updating to 41

**Comment by andersoncscz** [comment] 2021-04-22 20:49
I was using a raw new project without any changes, here are some additional informations:
- Expo SDK 41
- NPM 7.10.0
- NodeJS: 14.16.0
Thanks in advance.

**Comment by brentvatne** [comment] 2021-04-22 20:54
so you ran `expo init` and chose are bare template then ran an ios (? or android?) build and saw the error that the op posted "Possible Unhandled Promise Rejection (id:0) expoKeepAwake"?

**Comment by andersoncscz** [comment] 2021-04-23 00:11
That's right. I didn't run on ios, just on android. The warning is shown doing the steps I described in the beginning.

**Comment by brentvatne** [comment] 2021-04-23 00:22
i tried those exact steps and it worked for me, can you try cloning my repo? https://github.com/brentvatne/andersoncscz

```
╭─~/code
╰─$ expo init andersoncscz
✔ Choose a template: › minimal (TypeScript)  same as minimal but with TypeScript configuration
✔ Downloaded and extracted project files.
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Installed JavaScript dependencies.
✔ Installed pods and initialized Xcode workspace.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following yarn commands.

- cd andersoncscz
- yarn android
- yarn ios
- yarn web

💡 You can also open up the projects in the ios and android directories with their respective IDEs.
🚀 expo-updates has been configured in your project. If you publish this project under a different user account than notbrent, you'll need to update the configuration in Expo.plist and AndroidManifest.xml before making a release build.
╭─~/code
╰─$ cd andersoncscz
╭─~/code/andersoncscz ‹main›
╰─$ yarn android
```

<img width="487" alt="Screen Shot 2021-04-22 at 5 21 27 PM" src="https://user-images.githubusercontent.com/90494/115800296-2cab3280-a38f-11eb-9e22-3ea618ee1349.png">

**Comment by brentvatne** [comment] 2021-04-23 00:27
i also tried with npm 7.1 and it worked as expected:

```
╭─~/code
╰─$ expo init andersoncscz-npm --npm                                                                                                                                                                                                                      1 ↵
✔ Choose a template: › minimal (TypeScript)  same as minimal but with TypeScript configuration
✔ Downloaded and extracted project files.
📦 Using npm to install packages.
✔ Installed JavaScript dependencies.
✔ Installed pods and initialized Xcode workspace.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following npm commands.

- cd andersoncscz-npm
- npm run android
- npm run ios
- npm run web

💡 You can also open up the projects in the ios and android directories with their respective IDEs.
🚀 expo-updates has been configured in your project. If you publish this project under a different user account than notbrent, you'll need to update the configuration in Expo.plist and AndroidManifest.xml before making a release build.
╭─~/code
╰─$ cd andersoncscz-npm
╭─~/code/andersoncscz-npm ‹main›
╰─$ yarn android
yarn run v1.22.10
$ react-native run-android
```

what am i missing here?

**Comment by andersoncscz** [comment] 2021-04-24 03:47
That was a good question :D . I'll take a look at tomorrow and left a feed back here.

**Comment by andersoncscz** [comment] 2021-04-28 02:50
Sorry, I just have time to test your repo today. After running it, I got the same Promise rejection warning I described.
Here are the screenshots.
![Screenshot_2021-04-27-23-44-02-420_com andersoncscz](https://user-images.githubusercontent.com/21967016/116339102-3d0a4580-a7b3-11eb-8175-2ca51d9c6f0f.jpg)
![Screenshot_2021-04-27-23-44-08-217_com andersoncscz](https://user-images.githubusercontent.com/21967016/116339106-3e3b7280-a7b3-11eb-8bd2-7c37aa2b27c2.jpg)

**Comment by brentvatne** [comment] 2021-04-28 05:56
what device is that? as much info about it as possible would be good.

we don't do anything fancy here :O we just call this code:

https://github.com/expo/expo/blob/e04a7cc0b04823870b98a755be6c922a5008f652/packages/expo-keep-awake/android/src/main/java/expo/modules/keepawake/ExpoKeepAwakeManager.java#L36-L48

with this:
https://github.com/expo/expo/blob/e04a7cc0b04823870b98a755be6c922a5008f652/packages/expo-keep-awake/android/src/main/java/expo/modules/keepawake/KeepAwakeModule.java#L35-L42

perhaps there is something we didn't anticipate on your specific device / settings configuration. can you repro it on an emulator or another device?

**Comment by andersoncscz** [comment] 2021-04-28 11:39
Just tested it in an emulator and everything worked as expected:
- Pixel 3 XL API 29

This issue is happening in my physical device:
- **Xioami Redmi Note 7**
- Android 10 QKQ1.190910.002. Api 29 according to https://developer.android.com/studio/releases/platforms?hl=pt-br#10

**Comment by brentvatne** [comment] 2021-05-19 21:59
maybe xiamoi redmi node 7 doesn't support `WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON`?

**Comment by computerjazz** [comment] 2021-08-05 00:17
I'm also seeing this bug on a variety of devices including a few Pixels when the app closes due to a hardware back button press or swipe (KeepAwake as well as ScreenOrientation both error out on re-foreground). Even though it appears as if the app is just backgrounded when this happens I notice that my zero-dep effects re-run on foreground, which suggests React thinks it's launching from scratch.

https://github.com/expo/expo/blob/9cd697533d64cdee216c641b792fda7952d1afcf/packages/expo-screen-orientation/android/src/main/java/expo/modules/screenorientation/ScreenOrientationModule.kt#L73

ScreenOrientation error:
```
Error: Could not find activity.
Error: Could not find activity.
    at promiseMethodWrapper (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2596:45)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:97384:40)
    at lockAsync$ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:110085:87)
```

KeepAwake error:
```
Possible Unhandled Promise Rejection (id: 1):
Error: Unable to activate keep awake
Error: Unable to activate keep awake
    at promiseMethodWrapper (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2596:45)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:97384:40)
    at activateKeepAwake (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:106340:73)
```

**Comment by CMadden8** [comment] 2021-11-01 22:55
I've also been getting this error - but then I realised it was only ever happening when I clicked the 'got it' button that appears after the initial run of `expo run:android`. Ie the dismiss button for 'hello there, friend' expo help text.

The error hasn't appeared at any other point in the app.
