### ISSUE TITLE
[expo-store-review] not working on iOS in production

### ISSUE THREAD

**Issue by maxizhukov** [expo/expo#20918] opened 2023-01-22 20:09 UTC
### Summary

Rating popup is not opening on iOS in production and expo Go app (Published in App Store), but works fine on Android

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 1.0.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

```
"expo-store-review": "~6.0.0"
"expo": "^47.0.0"
"expo-linking": "~3.3.0"
"react": "18.1.0"

[
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 33,
            "targetSdkVersion": 33,
            "buildToolsVersion": "33.0.0"
          },
          "ios": {
            "deploymentTarget": "13.0"
          }
        }
      ]

```

```

import * as StoreReview from "expo-store-review"

useEffect(() => {
		showRating();
	}, []);

	const showRating = async () => {
		await StoreReview.requestReview();
	}

```

**Comment by amrjmd1** [comment] 2023-01-23 08:21
To fix your issue check If the app config (app.json) does not contain store URLs

Here's how to add the URL for iOS👇🏻
https://docs.expo.dev/versions/latest/config/app/#appstoreurl

If the link is added and the feature does not work, the native store review capabilities are not available, then the user must be redirected outside the application to write a review

**Comment by gloredo** [comment] 2023-02-24 13:49
### Minimal reproducible example

1. `npx create-expo-app my-app`
2. `npx expo install expo-store-review expo-linking`
3. add in `app.json`: 
```json
"ios": {
  "appStoreUrl": "https://apps.apple.com/us/app/[...]"
},
"android": {
  "playStoreUrl": "https://play.google.com/store/apps/[...]"
}
```
4. call `StoreReview.requestReview()`
```js
import * as React from 'react';
import * as StoreReview from 'expo-store-review';

export default function App() {
  React.useEffect(() => {
    try {
      StoreReview.requestReview();
    } catch (e) {
      console.error(e)
    }
  }, []);

  return null;
}
```
5. `eas build -e release -p ios`
6. store review modal is not displayed and `console.error` is not thrown

**Comment by gloredo** [comment] 2023-02-24 13:55
@brentvatne can you reopen this issue please? or can i create a new one?

**Comment by gloredo** [comment] 2023-02-24 14:08
@brentvatne can you reopen pls? thx

**Comment by dancamdev** [comment] 2023-03-11 16:14
> ### Minimal reproducible example
> 1. `npx create-expo-app my-app`
> 2. `npx expo install expo-store-review expo-linking`
> 3. add in `app.json`:
> 
> ```json
> "ios": {
>   "appStoreUrl": "https://apps.apple.com/us/app/[...]"
> },
> "android": {
>   "playStoreUrl": "https://play.google.com/store/apps/[...]"
> }
> ```
> 
>  4. call `StoreReview.requestReview()`
> 
> ```js
> import * as React from 'react';
> import * as StoreReview from 'expo-store-review';
> import * as Sentry from 'sentry-expo';
> 
> export default function App() {
>   React.useEffect(() => {
>     try {
>       StoreReview.requestReview();
>     } catch (e) {
>       Sentry.Native.captureException(e);
>     }
>   }, []);
> 
>   return null;
> }
> ```
> 
>  5. `eas build -e release -p ios`
> 6. store review modal is not displayed and Sentry caught nothing

Same thing happening for me - Expo SDK 48

**Comment by solonik1** [comment] 2023-04-15 17:53
Hey, i have the same issue. Are there any news? Thanks in advance

**Comment by bratelefant** [comment] 2023-04-15 18:03
In my case the reason was that I was requesting the review in a TestFlight build; seems like in app reviews are suppressed there: https://stackoverflow.com/questions/46770549/skstorereviewcontroller-requestreview-popup-is-not-showing-in-testflight-build

I could also notice that once a review was performed, the popup will not reappear.

**Comment by zfrankdesign** [comment] 2023-07-07 14:32
So I have iOS working fine, but Android does nothing when calling `requestReview`. I added store urls to the app.json and still nothing. I am testing our build from play store internal testing track kinda following these docs https://developer.android.com/guide/playcore/in-app-review/test and nothing. The google account on my test phone has not left a review for this app before either. Not really sure what else to do..

**Comment by huynhducduy** [comment] 2023-10-31 08:43
I'm still having the issue, does anyone happen to know the fix? 

I already add `appStoreUrl` and `playStoreUrl`. 

Everything works fine on Android and iOS development builds, but nothing appears on iOS Production (on App Store, I tried switching to a new device and new iCloud account too)

**Comment by alanjhughes** [comment] 2023-11-01 15:41
Hi - I have created builds on SDK 48 and 49 using the repro provided and built a production build using EAS. The modal is being presented in both cases.  I've also tested on expo go and it also works on both SDK versions. @huynhducduy what sdk version are you on?

**Comment by brentvatne** [comment] 2023-11-01 23:12
closing until we get a minimal reproducible example

**Closed** 2023-11-01 23:12 UTC
Labels: incomplete issue: missing or invalid repro
