### ISSUE TITLE
IntentLauncher open file doesnt work properly from a FileSystem Download

### ISSUE THREAD

**Issue by mgcostaParedes** [expo/expo#5808] opened 2019-09-30 10:31 UTC
### Environment

Expo SDK 35.0
Android 9.0

### Steps to Reproduce

When i download a file from a remote url and then i get the content from the URI the IntentLaucher cant properly open the intent file, for example if it´s a image, it shows a black screen, if it´s an PDF, it shows something like "the file is damaged"

### Reproducible Demo
``` 
FileSystem.downloadAsync(
            `${constants.apiUrl}download-file/task/${item.id}`,
            FileSystem.documentDirectory + item.name_with_extension
        ).then(({uri}) => {
            FileSystem.getContentUriAsync(uri).then(cUri => {
                IntentLauncher.startActivityAsync('android.intent.action.VIEW', {
                    data: cUri.uri,
                    flags: 1,  
                });
            });
     })
```

**Comment by AdamJNavarro** [comment] 2019-09-30 20:16
Hey @mgcostaParedes,

Could you please provide a [Snack](snack.expo.io) that contains all the relevant code here and reproduces the issue you mention? This way we can reliably test it on our end and begin investigating. A small snippet of the code unfortunately isn't enough.

Cheers,
Adam

**Comment by mgcostaParedes** [comment] 2019-10-02 15:49
Hello @AdamJNavarro 
You can follow the example in: https://snack.expo.io/@miguelcostainsertpage/intent-launcher-bug

However i have some more details about this problem, for example, if you provide an url where the pdf is automatically exposed on the browser (content-disposition:inline) the IntentLauncher works fine, you can use this pdf (http://www.orimi.com/pdf-test.pdf), if i provide an url where the pdf is download to the device (content-disposition:attachment) the IntentLauncher says something like "PDF is damaged"

Thank you,
Cheers,
Miguel

**Comment by lukmccall** [comment] 2020-02-26 15:51
Hi @mgcostaParedes. 

I've tested two codes:
```js
FileSystem.downloadAsync(
  `https://drive.google.com/u/0/uc?id=1qyb8mZ6H7y-78fUilzIEyKpB7mTus5hd&export=download`,
  FileSystem.documentDirectory + 'test.pdf'
).then(({ uri }) => {
  console.log(uri);
  FileSystem.getContentUriAsync(uri).then(cUri => {
    IntentLauncher.startActivityAsync('android.intent.action.VIEW', {
      data: cUri.uri,
      flags: 1,
    });
  });
});
```
```js
FileSystem.downloadAsync(
  `http://www.fundacionsgae.org/Lists/FSGAE_SalaPrensa_Recursos/Attachments/1/dummy.pdf`,
  FileSystem.documentDirectory + 'test.pdf'
).then(({ uri }) => {
  console.log(uri);
  FileSystem.getContentUriAsync(uri).then(cUri => {
    IntentLauncher.startActivityAsync('android.intent.action.VIEW', {
      data: cUri.uri,
      flags: 1,
    });
  });
});
```

The first one doesn't work. However, the second one works fine. The only difference between these two snippets is the pdf URL (these URLs pointe to the same file). 

So, why the first one doesn't work? The answer is pretty simple. `FileSystem.downloadAsync` downloads the contents at a remote URI. Hence, when your URI looks like this: `https://drive.google.com/u/0/uc?id=1qyb8mZ6H7y-78fUilzIEyKpB7mTus5hd&export=download`, the `FileSystem` will download **the HTML content**, not the pdf file. In the second case, URI points to file - so the module will download it correctly.

I believe that you struggle with this because you provided an indirect URL to the pdf. To fix it, you need to change the URL.  I'm closing this issue right now. However, if what I describe here is not applied in your case, feel free to reopen it 😉

**Closed by lukmccall** 2020-02-26 15:51 UTC
Labels: IntentLauncherAndroid, bug, project: android-runtime
