### ISSUE TITLE
Permissions.askAsync is not resolving on Android only

### ISSUE THREAD

**Issue by mi-mazouz** [expo/expo#5938] opened 2019-10-10 14:34 UTC
### Environment

  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild

Target: Android

### Problem

Hello, I'm trying to get permissions for camera_roll on android. The problem is that Permissions.askAsync is not resolving...

### Reproducible Demo

```
const handlePermission = async (permissions) => {
    const { status } = await Permissions.getAsync(permissions);

    console.log(status); // denied
    if (status === 'denied') {
        const { status: askStatus } = await Permissions.askAsync(permissions);

        console.log(askStatus); 
        // I have never seen this console log...
    }

    return null;
};

handlePermission(Permissions.CAMERA_ROLL);
```

**Comment by lukmccall** [comment] 2019-10-10 14:44
Hi @mi-mazouz, I've tried testing this and everything worked fine.  

So could you provide more information - Android version, SDK version, which workflow do you use, it happens only on real devices or maybe this also applies to simulators.

**Comment by mi-mazouz** [comment] 2019-10-10 18:11
@lukmccall 

Can you please remove need more info label?

**Comment by lukmccall** [comment] 2019-10-11 07:10
@mi-mazouz, could you also provide an implementation of `useActionSheet` function?

**Comment by mi-mazouz** [comment] 2019-10-11 15:42
@lukmccall 
useActionSheet is from:

```
import { useActionSheet } from '@expo/react-native-action-sheet';
```

**Comment by lukmccall** [comment] 2019-10-14 07:43
@mi-mazouz, I've checked your code again. Unfortunately, I wasn't able to reproduce this bug. I've tested it on two devices with Android 8 and 9. Also, I've run it on a simulator. Everything was working like a charm. 

However, please check [this snack](https://snack.expo.io/@lukaszkosmaty/github---permissions.aksasync-is-not-resolving-on-android) and test it. Maybe, I missed something important in code.

**Comment by cruzach** [comment] 2019-10-31 19:12
@mi-mazouz were you able to find the cause of this? If you did, let us know what the fix was and we can close the issue

**Comment by mi-mazouz** [comment] 2019-10-31 20:15
@cruzach I didn't rework on it yet... You can close the issue if you want and I'll open a new one if the problem persist.

**Closed** 2019-10-31 20:18 UTC
Labels: Permissions, bug, project: android-runtime, status: needs more info
