### ISSUE TITLE
`createAnimatedComponent` does not support stateless functional components; use a class component instead.

### ISSUE THREAD

**Issue by anmol-raj** [expo/expo#8202] opened 2020-05-07 20:25 UTC
hi 
I'm having this issue in the Expo web only in simulator & mobile it works fine I'm having this issue on the web browser only..

`createAnimatedComponent` does not support stateless functional components; use a class component instead.

https://downloads.intercomcdn.com/i/o/206106436/05c5d3db8e34e334c8f5856a/image.png

**Comment by cruzach** [comment] 2020-05-11 15:38
maybe this is due to the version of reanimated that is installed? Can you provide theSDK version and a snack that reproduces this?

**Comment by anmol-raj** [comment] 2020-05-12 19:12
![image](https://user-images.githubusercontent.com/61791716/81735357-8eda9280-94b2-11ea-92e8-3516846c1a8a.png)

**Comment by cruzach** [comment] 2020-05-18 13:37
Can you provide a snack that reproduces this?

**Comment by EvanBacon** [comment] 2020-05-22 07:16
Related: https://github.com/necolas/react-native-web/issues/1495

**Comment by EvanBacon** [comment] 2020-08-11 02:50
Closing because it's upstream and we can't do much from this repo.

**Closed by EvanBacon** 2020-08-11 02:50 UTC
Labels: Platform: web, needs repro, status: needs more info
