### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by kafkas** [expo/expo#6000] opened 2019-10-16 15:26 UTC
While building the standalone IOS app my entire project folder got deleted for some reason. I cloned it back from Github (my most recent commit worked without an issue) but I am now getting the following strange error after running `expo start` and running for IOS simulator.

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-16 at 18 04 24](https://user-images.githubusercontent.com/36949216/66931983-9088c880-f03f-11e9-8be2-9044006a299e.png)

The issue is resolved when I change `node_modules/expo/AppEntry.js` from

```
import { registerRootComponent } from 'expo';
import { activateKeepAwake } from 'expo-keep-awake';

import App from '../../App';

if (__DEV__) {
  activateKeepAwake();
}

registerRootComponent(App);
```
to 
```
import { registerRootComponent } from 'expo';
import { activateKeepAwake } from 'expo-keep-awake';

import Root from '../../src/Root';

if (__DEV__) {
  activateKeepAwake();
}

registerRootComponent(Root);
```
and also my root (entry) file which is located at `src/Root` from

```
...
function Root(): ReactElement {
  return <App />;
}

registerRootComponent(React.memo(Root));
```
to

```
...
export default function Root(): ReactElement {
  return <App />;
}

registerRootComponent(React.memo(Root));
```
I did not previously have to do this as my entry file is already specified in `package.json` as `"main": "src/Root",` and it used to build without a problem. I also tried changing the expo version in `package.json` from `"expo": "^35.0.0"` to `"expo": "35.0.0"` as I thought a patch or minor update by expo may have caused the issue but to no luck. I am not sure what's causing it.

**Comment by cruzach** [comment] 2019-10-16 15:34
What version of `expo-cli` are you using?

**Comment by cruzach** [comment] 2019-10-16 15:40
This is most likely due to these issues:  https://github.com/expo/expo-cli/issues/875 https://github.com/expo/expo-cli/issues/191

Is your App file `.jsx`?

**Comment by anarkafkas** [comment] 2019-10-16 15:49
I am using 3.4.0. I had just updated it actually so you may be right. Entry file is `.tsx`

**Comment by cruzach** [comment] 2019-10-16 17:11
Does the workaround in 191 resolve the issue? (setting `packagerOpts.sourceExts: [ "js", "json", "ts", "tsx", "jsx" ]` in app.json)

**Comment by anarkafkas** [comment] 2019-10-17 21:28
> Does the workaround in 191 resolve the issue? (setting `packagerOpts.sourceExts: [ "js", "json", "ts", "tsx", "jsx" ]` in app.json)

Nope, still the same..

**Comment by cruzach** [comment] 2020-07-22 15:13
hey @kafkas , you can now better customize the metro config for expo-cli, we provide some docs for that [here](https://docs.expo.io/guides/customizing-metro/)! The duplicate issues for this (linked above) in `expo-cli` were closed, so I'm going to close this issue as well. If you still run into this issue, please open a new issue with a reproducible demo and we'll investigate 😃

**Closed by cruzach** 2020-07-22 15:13 UTC
Labels: bug
