### ISSUE TITLE
[expo-image-picker][Android] App crashes at startup - No static method loadLibrary(Ljava/lang/String;)V in class Lcom/facebook/soloader/SoLoader;

### ISSUE THREAD

**Issue by Pines-Cheng** [expo/expo#4990] opened 2019-07-18 01:36 UTC
## 🐛 Bug Report

when use `expo-image-picker`,App crashes at starup on Android and throw error:

```
No static method loadLibrary(Ljava/lang/String;)V in class Lcom/facebook/soloader/SoLoader;
```
both in simulator and real device on Android , and iOS is fine.

### Environment

```
  Expo CLI 2.20.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.8.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.55.4 => 0.59.8
    npmGlobalPackages:
      expo-cli: 2.20.10
```

```
"expo-image-picker": "^5.0.2",
"react-native-unimodules": "^0.4.1"
```

### Steps to Reproduce

Just use :
```
import * as ImagePicker from 'expo-image-picker'
```

### Expected Behavior

Use 'expo-image-picker' normal and not be crashed.

### Actual Behavior

App crashes at starup on Android and throw error.

**Comment by Pines-Cheng** [comment] 2019-07-18 01:38
According to this issue https://github.com/facebook/react-native/issues/20251 ,It sames the problem of `facebook.fresco:fresco` and `facebook.fresco:animated-gif `:

> According to Maven Repository facebook.fresco:fresco and facebook.fresco:animated-gif v 1.10.0 were released 2 days ago, I can confirm it is what causing the issue.

**Comment by Pines-Cheng** [comment] 2019-07-18 01:40
I change the code in  `node_modules/expo-image-picker/android/build.gradle`

```
77:  api 'com.facebook.fresco:fresco:1.10.0' 
```

to 

```
77:  api 'com.facebook.fresco:fresco:1.9.0' 
```

and everything is ok now.

**Comment by Pines-Cheng** [comment] 2019-07-18 01:46
It same has been fixed ?

![image](https://user-images.githubusercontent.com/9441951/61423053-e2d32400-a940-11e9-9b11-0ba5291ee2ed.png)

**Comment by cruzach** [comment] 2019-07-18 14:12
Hey @Pines-Cheng - so this is in an Expokit project? Or a bare project? Please provide all the steps involved under `Steps to Reproduce`, from starting the project to getting the error

**Comment by Pines-Cheng** [comment] 2019-07-19 02:01
It is a bare project .

#  Steps to Reproduce

1. init  bare project with expo-cli
2. import expo-image-picker
3. run android in simulator or real device use Android Studio

App will crashes at startup and throw this error.

PS: the React Native version is 0.55.4

**Comment by cruzach** [comment] 2019-07-19 13:31
> PS: the React Native version is 0.55.4

So this is probably the cause. It's usually best to use the same version of RN as we use for the current SDK. Have you tried with version 0.59.8?

**Comment by Pines-Cheng** [comment] 2019-07-22 02:27
It's very likely to work normally under version 0.59.8, but our project is useing RN version 0.55.4 and It's hard to upgrade. So it bests that the lib is compatible with 0.59.8 and 0.55.4 simultaneously.

**Comment by cruzach** [comment] 2019-07-22 18:10
In order to make sure you're RN version is compatible with your unimodules, we simply recommend using the RN version included in our current SDK. Your mileage may vary if using an older react-native version

**Comment by lukmccall** [comment] 2019-10-01 12:32
I'm closing this issue because I believe it was fix earlier. Moreover, `image-picker` doesn't depend anymore on `fresco`.

**Closed by lukmccall** 2019-10-01 12:32 UTC
Labels: ImagePicker, bug, status: needs more info
