### ISSUE TITLE
Axios API, work when development process, but failed after build apk and install on my device

### ISSUE THREAD

**Issue by fhdyt** [expo/expo#10074] opened 2020-09-05 09:35 UTC
When i develop my app, api request work fine, but when i build to apk and install on my device, Network Error.

Can anyone help me, i deploy my server to heroku so url using HTTPS

**Comment by superyarik** [comment] 2020-09-06 14:46
Need more information. We moved from fetch to axios our applications and its works perfect.

**Comment by dotfelixb** [comment] 2020-09-06 19:53
Have you enable internet in your Manifest 

 <uses-permission android:name="android.permission.INTERNET" />

**Comment by byCedric** [comment] 2020-09-07 17:43
Hi @fhdyt! Unfortunately, there are a lot of factors possibly causing this issue. If you can create a [small repro](https://stackoverflow.com/help/minimal-reproducible-example), we can help investigate. Right now, there is no context or example which makes it really hard to help you.

**Comment by alexeymolchan** [comment] 2020-09-12 22:15
In my case the problem was with ssl certificates

**Comment by mukeshmadikai** [comment] 2020-11-08 16:57
What was the issue with certificates?

**Comment by cruzach** [comment] 2020-12-18 16:29
Closing since this isn't a bug with Expo

**Closed by cruzach** 2020-12-18 16:29 UTC
Labels: Requesting changes to issue
