### ISSUE TITLE
Android client 2.3.1+ sometimes fails to fetch manifest provided from `exp android`

### ISSUE THREAD

**Issue by carloscpda** [expo/expo#1508] opened 2018-03-07 22:16 UTC
### Environment

  OS: macOS High Sierra 10.13.3
  Node: 9.6.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4408382

expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

### Steps to Reproduce

1. Start Pixel 8.0 emulator
2. `exp android`

### Expected Behavior

Start app on Android without problem

### Actual Behavior

When I start the app on the emulator I am obtaining this error: 

`ErrorActivity: ErrorActivity message: Timed out, no manifest in cache`

I cannot reproduce it on my physical device.
Full log:

```
03-07 21:46:41.714  2715  2715 I sh      : type=1400 audit(0.0:1209): avc: denied { execute_no_trans } for path="/system/bin/pm" dev="sda6" ino=517 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=file permissive=1
03-07 21:46:41.718  2715  2715 I app_process: type=1400 audit(0.0:1210): avc: denied { read write } for path="socket:[48248]" dev="sockfs" ino=48248 scontext=u:r:zygote:s0 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1
03-07 21:46:41.952  2715  2715 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
03-07 21:46:41.989  2715  2715 W app_process: Unexpected CPU variant for X86 using defaults: x86
03-07 21:46:42.015  2715  2715 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
03-07 21:46:42.018   117   117 I servicemanager: type=1400 audit(0.0:1216): avc: denied { search } for name="2715" dev="proc" ino=45356 scontext=u:r:servicemanager:s0 tcontext=u:r:zygote:s0 tclass=dir permissive=1
03-07 21:46:42.028  2715  2723 W MessageQueue: Handler (android.os.Handler) {600f40} sending message to a Handler on a dead thread
03-07 21:46:42.028  2715  2723 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {600f40} sending message to a Handler on a dead thread
03-07 21:46:42.028  2715  2723 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
03-07 21:46:42.028  2715  2723 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:661)
03-07 21:46:42.028  2715  2723 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:630)
03-07 21:46:42.028  2715  2723 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:600)
03-07 21:46:42.028  2715  2723 W MessageQueue: 	at android.os.Handler.post(Handler.java:356)
03-07 21:46:42.028  2715  2723 W MessageQueue: 	at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:57)
03-07 21:46:42.028  2715  2723 W MessageQueue: 	at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
03-07 21:46:42.028  2715  2723 W MessageQueue: 	at android.os.Binder.execTransact(Binder.java:674)
03-07 21:46:42.029  2715  2715 I app_process: System.exit called, status: 0
03-07 21:46:42.029  2715  2715 I AndroidRuntime: VM exiting with result code 0.
03-07 21:46:42.120   117   117 E SELinux : avc:  denied  { find } for service=activity pid=2729 uid=0 scontext=u:r:init:s0 tcontext=u:object_r:activity_service:s0 tclass=service_manager
03-07 21:46:42.124   437   449 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=exp://localhost:80 flg=0x10000000 cmp=host.exp.exponent/.LauncherActivity} from uid 0
03-07 21:46:42.155   437   777 I ActivityManager: Start proc 2731:host.exp.exponent/u0a68 for activity host.exp.exponent/.LauncherActivity
03-07 21:46:42.156  2731  2731 W zygote  : Unexpected CPU variant for X86 using defaults: x86
03-07 21:46:42.205   437   451 E memtrack: Couldn't load memtrack module
03-07 21:46:42.205   437   451 W android.os.Debug: failed to get memory consumption info: -1
03-07 21:46:42.226  2731  2747 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libGLES_emulation.so from the current namespace instead.
03-07 21:46:42.227  2731  2747 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libEGL_emulation.so from the current namespace instead.
03-07 21:46:42.242  2731  2747 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libGLESv1_CM_emulation.so from the current namespace instead.
03-07 21:46:42.273  2731  2747 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libGLESv2_emulation.so from the current namespace instead.
03-07 21:46:42.332  2731  2731 I MultiDex: VM with version 2.1.0 has multidex support
03-07 21:46:42.332  2731  2731 I MultiDex: install
03-07 21:46:42.332  2731  2731 I MultiDex: VM has multidex support, MultiDex support library is disabled.
03-07 21:46:42.409  2731  2731 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
03-07 21:46:42.436  2731  2731 W InstanceID/Rpc: Found 10069
03-07 21:46:42.438   437   451 E memtrack: Couldn't load memtrack module
03-07 21:46:42.438   437   451 W android.os.Debug: failed to get memory consumption info: -1
03-07 21:46:42.440  2731  2731 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
03-07 21:46:42.468  2731  2731 I FA      : App measurement is starting up, version: 9877
03-07 21:46:42.468  2731  2731 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
03-07 21:46:42.492  2731  2731 I FA      : To enable faster debug mode event logging run:
03-07 21:46:42.492  2731  2731 I FA      :   adb shell setprop firebase.analytics.debug-mode host.exp.exponent
03-07 21:46:42.497  2731  2731 I FirebaseInitProvider: FirebaseApp initialization successful
03-07 21:46:42.606  2731  2751 D NetworkSecurityConfig: No Network Security Config specified, using platform default
03-07 21:46:42.653  2731  2742 I zygote  : Background concurrent copying GC freed 9777(1042KB) AllocSpace objects, 5(100KB) LOS objects, 56% free, 1171KB/2MB, paused 13.096ms total 67.975ms
03-07 21:46:42.654  2731  2736 I zygote  : Do partial code cache collection, code=7KB, data=31KB
03-07 21:46:42.675  2731  2736 I zygote  : After code cache collection, code=7KB, data=31KB
03-07 21:46:42.675  2731  2736 I zygote  : Increasing code cache capacity to 128KB
03-07 21:46:42.846  2731  2731 I CrashlyticsCore: Initializing Crashlytics 2.3.8.97
03-07 21:46:42.897  2731  2731 D b       : Finding badger
03-07 21:46:42.899  2731  2731 D b       : Current badger:me.leolin.shortcutbadger.impl.DefaultBadger
03-07 21:46:42.920  2731  2731 V fb-UnpackingSoSource: locked dso store /data/user/0/host.exp.exponent/lib-main
03-07 21:46:42.930  2731  2731 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/host.exp.exponent/lib-main
03-07 21:46:42.931  2731  2731 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/host.exp.exponent/lib-main
03-07 21:46:42.936  2731  2742 I zygote  : Background concurrent copying GC freed 14381(1153KB) AllocSpace objects, 2(40KB) LOS objects, 50% free, 2MB/4MB, paused 425us total 105.138ms
03-07 21:46:43.002  2731  2731 I zygote  : Thread[1,tid=2731,Native,Thread*=0xeaa4a000,peer=0x72590568,"main"] recursive attempt to load library "/data/app/host.exp.exponent-ZOpincGVYBqrn2EMXL4LQw==/lib/x86/libfb.so"
03-07 21:46:43.005   437   687 I ActivityManager: START u0 {flg=0xc080000 cmp=host.exp.exponent/.experience.ExperienceActivity (has extras)} from uid 10068
03-07 21:46:43.012   437   485 W System  : ClassLoader referenced unknown path: 
03-07 21:46:43.077  2731  2785 D OpenGLRenderer: HWUI GL Pipeline
03-07 21:46:43.165   437   446 I zygote  : Background concurrent copying GC freed 38574(2MB) AllocSpace objects, 17(448KB) LOS objects, 42% free, 7MB/12MB, paused 295us total 108.292ms
03-07 21:46:43.194   304   304 E hw-IPCThreadState: binder thread pool (1 threads) starved for 120 ms
03-07 21:46:43.230   437   485 D         : HostConnection::get() New Host Connection established 0xe1825d00, tid 485
03-07 21:46:43.234   262   262 I netd    : type=1400 audit(0.0:1265): avc: denied { getopt } for path="/dev/socket/fwmarkd" scontext=u:r:netd:s0 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1
03-07 21:46:43.259   437   485 W         : Unrecognized GLES max version string in extensions: 
03-07 21:46:43.259   437   485 W         : Process pipe failed
03-07 21:46:43.272  2731  2785 D         : HostConnection::get() New Host Connection established 0xcd1bfe00, tid 2785
03-07 21:46:43.300  2731  2785 W         : Unrecognized GLES max version string in extensions: 
03-07 21:46:43.310  2731  2785 W         : Process pipe failed
03-07 21:46:43.446   304   304 E hw-IPCThreadState: binder thread pool (1 threads) starved for 146 ms
03-07 21:46:43.462  2731  2731 I logThread: type=1400 audit(0.0:1272): avc: denied { read } for name="databases" dev="sdb3" ino=81921 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:system_data_file:s0:c512,c768 tclass=dir permissive=1
03-07 21:46:43.466  2794  2794 I adbd    : type=1400 audit(0.0:1274): avc: denied { execute_no_trans } for path="/system/bin/sh" dev="sda6" ino=556 scontext=u:r:init:s0 tcontext=u:object_r:shell_exec:s0 tclass=file permissive=1
03-07 21:46:43.574  2794  2794 I dumpsys : type=1400 audit(0.0:1275): avc: denied { call } for scontext=u:r:init:s0 tcontext=u:r:servicemanager:s0 tclass=binder permissive=1
03-07 21:46:43.630   117   117 I servicemanager: type=1400 audit(0.0:1276): avc: denied { sendto } for path="/dev/socket/logdw" scontext=u:r:servicemanager:s0 tcontext=u:r:init:s0 tclass=unix_dgram_socket permissive=1
03-07 21:46:43.635   117   117 E SELinux : avc:  denied  { find } for service=package pid=2794 uid=0 scontext=u:r:init:s0 tcontext=u:object_r:package_service:s0 tclass=service_manager
03-07 21:46:43.641   304   304 E hw-IPCThreadState: binder thread pool (1 threads) starved for 121 ms
03-07 21:46:43.644  2731  2785 I OpenGLRenderer: Initialized EGL, version 1.4
03-07 21:46:43.644  2731  2785 D OpenGLRenderer: Swap behavior 1
03-07 21:46:43.648  2731  2785 D EGL_emulation: eglCreateContext: 0xdfd5d340: maj 2 min 0 rcv 2
03-07 21:46:43.710   307   307 I batteryd: type=1400 audit(0.0:1279): avc: denied { write } for name="capacity" dev="tmpfs" ino=11106 scontext=u:r:init:s0 tcontext=u:object_r:device:s0 tclass=fifo_file permissive=1
03-07 21:46:43.727  2731  2762 D b       : Loaded exp.host status page.
03-07 21:46:43.739  2731  2750 I zygote  : Deoptimizing int org.spongycastle.asn1.ASN1InputStream.b(java.io.InputStream, int) due to JIT inline cache
03-07 21:46:43.866  2731  2736 I zygote  : Do partial code cache collection, code=44KB, data=62KB
03-07 21:46:43.933   437   558 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
03-07 21:46:44.042  2731  2750 I FA      : This instance being marked as an uploader
03-07 21:46:44.043  2731  2736 I zygote  : After code cache collection, code=40KB, data=62KB
03-07 21:46:44.043  2731  2736 I zygote  : Increasing code cache capacity to 256KB
03-07 21:46:44.079  2731  2742 I zygote  : Background concurrent copying GC freed 46516(2MB) AllocSpace objects, 11(220KB) LOS objects, 50% free, 2028KB/3MB, paused 925us total 247.547ms
03-07 21:46:44.741  2731  2731 W a       : Could not find listener for key: openOptimisticExperienceActivity
03-07 21:46:44.748  2731  2731 W a       : Could not find listener for key: openExperienceActivity
03-07 21:46:44.806  2731  2785 E EGL_emulation: tid 2785: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)
03-07 21:46:44.806  2731  2785 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdf2ff280, error=EGL_BAD_MATCH
03-07 21:46:44.834   437  1896 I ActivityManager: START u0 {flg=0x24000000 cmp=host.exp.exponent/.experience.ErrorActivity (has extras)} from uid 10068
03-07 21:46:44.861  2731  2731 D f       : Using remote Expo kernel manifest: {"android":{"package":"host.exp.exponent","publishBundlePath":"..\/android\/app\/src\/main\/assets\/kernel.android.bundle"},"description":"","extra":{"amplitudeApiKey":"081e5ec53f869b440b225d5e40ec73f9"},"icon":"https:\/\/s3.amazonaws.com\/exp-brand-assets\/ExponentEmptyManifest_192.png","iconUrl":"https:\/\/s3.amazonaws.com\/exp-brand-assets\/ExponentEmptyManifest_192.png","ios":{"bundleIdentifier":"host.exp.exponent","publishBundlePath":"..\/ios\/Exponent\/Supporting\/kernel.ios.bundle","supportsTablet":true},"isKernel":true,"kernel":{"androidManifestPath":"..\/android\/app\/src\/main\/assets\/kernel-manifest.json","iosManifestPath":"..\/ios\/Exponent\/Supporting\/kernel-manifest.json"},"loading":{"hideExponentText":false,"icon":"https:\/\/s3.amazonaws.com\/exp-brand-assets\/ExponentEmptyManifest_192.png","iconUrl":"https:\/\/s3.amazonaws.com\/exp-brand-assets\/ExponentEmptyManifest_192.png"},"locales":{},"name":"exponent-home","notification":{"color":"#000000","icon":"https:\/\/s3.amazonaws.com\/exp-us-standard\/placeholder-push-icon-blue-circle.png","iconUrl":"https:\/\/s3.amazonaws.com\/exp-us-standard\/placeholder-push-icon-blue-circle.png"},"orientation":"portrait","packagerOpts":{"config":".\/_universe\/rn-cli.config.js"},"primaryColor":"#cccccc","privacy":"unlisted","scheme":"exp","sdkVersion":"UNVERSIONED","slug":"home","version":"26.0.0","id":"@exponent\/home","revisionId":"26.0.0-r.M69GPaJxbd","publishedTime":"2018-02-16T22:52:29.105Z","bundleUrl":"https:\/\/exp.host\/@exponent\/home\/bundle","releaseChannel":"default","isVerified":true}
03-07 21:46:44.950  2731  2731 I Choreographer: Skipped 77 frames!  The application may be doing too much work on its main thread.
03-07 21:46:45.057  2731  2774 W zygote  : Long monitor contention with owner Queue (2770) at boolean android.os.BinderProxy.transactNative(int, android.os.Parcel, android.os.Parcel, int)(Binder.java:-2) waiters=0 in io.fabric.sdk.android.services.common.b io.fabric.sdk.android.services.common.IdManager.k() for 2.113s
03-07 21:46:45.116  2731  2776 W zygote  : Long monitor contention with owner Queue (2770) at boolean android.os.BinderProxy.transactNative(int, android.os.Parcel, android.os.Parcel, int)(Binder.java:-2) waiters=1 in io.fabric.sdk.android.services.common.b io.fabric.sdk.android.services.common.IdManager.k() for 2.154s
03-07 21:46:45.151  2731  2803 D b       : Using cached or embedded response.
03-07 21:46:45.157  2731  2803 D b       : Got cached OkHttp response for https://exp.host/@exponent/home/bundle?versionName=2.3.1
03-07 21:46:45.157  2731  2803 D b       : Have cached source file for https://exp.host/@exponent/home/bundle?versionName=2.3.1
03-07 21:46:45.350   437   452 W ActivityManager: Activity pause timeout for ActivityRecord{2b88423 u0 host.exp.exponent/.experience.ExperienceActivity t48}
03-07 21:46:45.365   437   485 I WindowManager: Failed to capture screenshot of Token{da21d31 ActivityRecord{4a225d8 u0 host.exp.exponent/.LauncherActivity t47 f}} appWin=Window{7b8154e u0 host.exp.exponent/host.exp.exponent.LauncherActivity} drawState=4
03-07 21:46:45.454  2731  2785 E EGL_emulation: tid 2785: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)
03-07 21:46:45.454  2731  2785 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xcaf7fae0, error=EGL_BAD_MATCH
03-07 21:46:45.531  2731  2731 D ReactNative: ReactInstanceManager.ctor()
03-07 21:46:45.560  2731  2731 D ReactNative: ReactInstanceManager.createReactContextInBackground()
03-07 21:46:45.560  2731  2810 W InstanceID/Rpc: Found 10069
03-07 21:46:45.560  2731  2731 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
03-07 21:46:45.560  2731  2731 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
03-07 21:46:45.560  2731  2731 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
03-07 21:46:45.560  2731  2731 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
03-07 21:46:45.562  2731  2731 W a       : Could not find listener for key: experienceActivityKernelDidLoad
03-07 21:46:45.562  2731  2731 D j       : Kernel started running.
03-07 21:46:45.571  2731  2812 D ReactNative: ReactInstanceManager.createReactContext()
03-07 21:46:45.621  2731  2731 E ErrorActivity: ErrorActivity message: Timed out, no manifest in cache
```

### Reproducible Demo

Project [link](https://github.com/thinger-io/Mobile-App)
Expo app [link](https://exp.host/@cepeda/thingerio)

**Comment by Kida007** [comment] 2018-03-08 19:49
Same problem after updating Expo android Client.  
I have restarted Packager, still the problem persists. 

To continue Developing with Expo,  you can use **Localhost** as 'Host' section of Expo XDE settings, it is slow, but I cant find a better way. 

There was another update today, but it didn't help.

**Comment by jimmylee** [comment] 2018-03-08 21:11
Thanks for your suggestion @Kida007, we'll look into this.

**Comment by LordLyng** [comment] 2018-03-09 09:57
Tunnel mode is way too slow on my physical device...
Any info regarding what app versions this affect? I am ready to downgrade to get my LAN mode working on my physical device again.

**Comment by Kida007** [comment] 2018-03-09 10:06
nice suggestion, I never thought of Downgrading mobile client. 
**Expo Android version 2.3.0** was working just fine. 
you can download it from [Here](https://apkpure.com/expo/host.exp.exponent/download/76-APK?from=details%2Fversion)
I didn't test it, please let us know if it is working fine. 
Thanks

**Comment by Kida007** [comment] 2018-03-09 21:29
localhost Working Perfect with Expo Android Client Version 2.3.0 as usual.
Affected App Versions: **2.3.1** and **2.3.2**.

**Comment by jurosh** [comment] 2018-03-10 12:46
Oh hack, same issue on Windows  "expo": "^25.0.0" & "react-native-scripts": "^1.11.1" :(

No code change, app just stopped working. (Android Expo Client 2.3.2)

So dirty solution is to install expo android client manually from APK ?

How it's possible that already 2 expo versions are containing bug which cripple development :o or is it working for someone ?

**Comment by montao** [comment] 2018-03-10 12:55
Same problem here. Expo stopped working. @Kida007 It doesn't even work if I downgrade. I get another different error message. This must be the world record of breaking a trivial "Hello World!" into incomprehensible errors.

**Comment by Kida007** [comment] 2018-03-10 13:10
Hello montao sorry to Hear about that
can you please tell us about the different error after Downgrading .

Apparently it is working fine for me !

**Comment by jurosh** [comment] 2018-03-10 13:11
Oh I've got issues with IP address, which I needed to configure manually with: `cross-env REACT_NATIVE_PACKAGER_HOSTNAME='192.168.1.51' react-native-scripts start`

Now it's working for me even with latest Expo client.

**Comment by Kida007** [comment] 2018-03-10 13:24
I think that might be the case

**Comment by montao** [comment] 2018-03-10 13:41
Not working.

**Comment by shu-iro** [comment] 2018-03-10 13:58
Same problem.

**Comment by montao** [comment] 2018-03-10 16:41
Solved! It is working now. The solution was to change the priorities of the network adapters. I had installed Virtual Box and that Virtual Box also installs a virtual network adapter which gets a higher automatic priority, and I could succesfully change that priority to make it work.

**Comment by montao** [comment] 2018-03-10 16:42
@Kida007 It's working now. thanks for the help

**Comment by Kida007** [comment] 2018-03-11 15:06
@montao  welcome .

@jimmylee I think this issue has something to do with hostname/ IP. When we use USB for the connection, it gives this error (The Latest Version ). 

but you can get it Working by : 
1) going to **'Explore Section'** on your expo mobile client
2) type **exp://your-ipAddress:port**
3) open Project 

But I am not Sure whats causing this.

**Comment by dobrysmak** [comment] 2018-03-11 20:33
Having same issue trying to run the app on physical device via Expo mobile app in the same wifi network.
```
Os: MacOS
npm: 4.6.1
create-react-native-app: 1.0.0
node: 9.0.0
```

Any ideas how to resolve this issue?

**Comment by Kida007** [comment] 2018-03-11 20:40
@dobrysmak please try opening the app using **explore Section**  mentioned above

**Comment by Shivanshmundra** [comment] 2018-03-12 03:42
@Kida007  I tried as you said but same error is showing each time. 
Are there any server issues right now?

**Comment by susiwen8** [comment] 2018-03-12 06:38
Same problem here, Expo version is 2.3.2. I have tried 2.3.0, still timed out(both QR Code and Explore) @Kida007

**Comment by shu-iro** [comment] 2018-03-12 08:55
I have the same problem with physical device but VM work.
I'd tried the fix just above but doesn't work.
Windows -> Android 6.0.1

**Comment by Kida007** [comment] 2018-03-12 10:33
oh sorry, that didn't work for you! 

But I think it should work if you follow these properly , even with the latest Expo Android Client :

1) Open Project Through **XDE** or command line **exp**  . 
2) Connect your physical Device with USB   . (usb debugging enabled) . 
3) open the app on your Device using XDE or command line . 
4) You will see the Error 'Timed out, no manifest in cache '. 
5) now press Expo Home Icon from error screen itself.
6) Now go to **Explore Section** and try adding this in **search Bar** : 
     `exp://your-private-ip/port`  

Make Sure that this is your Private IP  (192.168 . * . * ) not Virtual IP , and port number on which Expo is running (19000 probably).

Also, your Machine and Device should be on the same WIFI network. 
Sorry, I can't find a Proper Solution. 

If  you can work on slow Debugging than change **host**  in Expo XDE from _localhost_ to **Tunnel** .

**Comment by juanpatrono** [comment] 2018-03-12 19:19
@montao thanks, that was my problem too

**Comment by jurosh** [comment] 2018-03-14 17:43
It's probably happening mostly because of some network issues - eg. blocking firewall, wrong network interface or so... I think would be good to add more meaningful message for developers instead of just "missing manifest".
As I don't think current message make sense for developers - maybe for someone, but not sure - definitely it can be more user/developer friendly.

**Comment by esamelson** [comment] 2018-03-14 21:31
Hi there, unfortunately it sounds like there are multiple issues at play here, as the message "Timed out, no manifest in cache" is a symptom rather than a cause. If you are getting this error but **also received an error in 2.3.0 or below** (even if it's a different error message), please open a different ticket as that is a separate issue.

I've been trying to reproduce this, and have had no luck on either an emulator or a real device. If you've had this issue **starting in client version 2.3.1** (e.g. you need to use @Kida007 's workaround), could you provide some more information about your dev environment - e.g. what steps you're taking to start the app, what OS are you on, are you using VirtualBox, any unusual network settings? Also, does the issue happen only when remote debugging is turned on?

Thanks very much, all, and sorry for any inconvenience this has caused!

**Comment by ljuborados** [comment] 2018-03-15 13:07
Same issue here, just updated the client app on Android device (emulator) - after that the app can't run unless I manually specify ip and port in explore section (@Kida007 's workaround).

Starting the app from Expo app on mac
OS: macOS High Sierra 10.13.3
Not using VirtualBox - but using Docker
No unusual network settings - connected to WiFi using DHCP
Can't even get to the menu for disabling remote debugging so can't say.
Note: this is using an Android emulator, can't test with actual device currently.

**Comment by ljuborados** [comment] 2018-03-15 13:28
Tried downgrading to Expo client v2.3.0, getting  
 `java.net.ConnectException: Failed to connect to localhost/127.0.0.1:19000`  
even though it was working correctly 30 minutes ago without any changes to the code or setup, except for updating to v2.3.2.
So was working on v2.3.0, updated to v2.3.2 - didn't work, downgraded back to v2.3.0 - doesn't work again.

**Comment by Kida007** [comment] 2018-03-15 22:42
@ljuborados
I got the same error after downgrading. 

Please try the following  ( if XDE ) : 
`REACT_NATIVE_PACKAGER_HOSTNAME='your_private_ip' xde .`

**Comment by bamne123** [comment] 2018-03-16 07:19
Change host to LAN, it should work.

**Comment by jhalborg** [comment] 2018-03-20 09:02
Same issue, client 2.3.2. Using the 'expore - enter IP' does not work. Have not tried downgrading/setting hostname, just using tunnel to test on physical device for now and hoping for a quick fix. 

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^24.0.0 => 24.0.2
  react: 16.0.0 => 16.0.0
  react-native: https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz => 0.51.0

```

**Comment by Kida007** [comment] 2018-03-24 13:38
Bug fixed by expo team, update your XDEs.

**Closed** 2018-04-03 22:05 UTC
Labels: project: android-runtime
