### ISSUE TITLE
Util.reload() in an iOS Standalone build should force a refresh even when no updates are available

### ISSUE THREAD

**Issue by sonaye** [expo/expo#253] opened 2017-06-12 00:47 UTC
SDK Version: 17.0.0.

**Comment by terribleben** [comment] 2017-06-12 15:58
Which platform? What is the behavior you expect and what is the behavior you are observing?

**Comment by sonaye** [comment] 2017-06-12 16:04
@terribleben IOS, I expect the app to reload/restart the js bundle, instead calling Util.reload() doesn't trigger anything, it works on the Expo client however perfectly.

**Comment by terribleben** [comment] 2017-06-16 19:16
Hi, I tested this and it does work.

Perhaps you are trying to reload after making zero changes to your app? In that case, Expo is checking for an update, seeing that there is no update, and doing nothing. Try publishing a change and then invoking `Util.reload()`.

If that was it, maybe we need to be clearer about that behavior.

**Comment by sonaye** [comment] 2017-06-19 21:55
> Perhaps you are trying to reload after making zero changes to your app?
That is the case indeed.

What is expected from `Util.reload()` is to force reload/reset the experience regardless of whether a new version has been pushed or not, reloading the experience will force the checking for updates anyway.

I suggest that you add a parameter that is false by default to not break any apps that use this tool with the current behavior. `Util.reload(true)` would force reloading the app no matter what, this is needed for some cases when using I18nManager to apply yoga layout rtl/ltr presets.

**Comment by terribleben** [comment] 2017-06-19 21:58
If you just want to force your React Native bridge to reload (without checking for Expo updates), [React Native includes that functionality](https://github.com/facebook/react-native/blob/master/React/Modules/RCTDevSettings.mm#L222-L225).

**Comment by sonaye** [comment] 2017-06-19 22:03
`NativeModules.RCTDevSettings.reload()`?

**Comment by terribleben** [comment] 2017-06-20 00:49
Actually that is a bad recommendation because RCTDevSettings isn't necessarily present in production. I'll go back to my earlier comment: I'm updating the docs to clarify this behavior and when I get a chance I'll make it consistent with Android.

**Comment by sonaye** [comment] 2017-06-20 05:54
A method to force reload is still needed, would be great if you added that functionality, the current behaviour is more of a check for update than a reload, the two can be combined without breaking anything by adding a force = true flag to the current utility.

**Comment by terribleben** [comment] 2017-06-20 23:25
Yep, I agree, this is something i'll work on when I get a chance. Sorry about the confusion. I renamed the issue title in case other people are searching for a similar thing.

**Comment by terribleben** [comment] 2017-07-11 23:25
A fix for this is scheduled to ship with SDK 19: https://github.com/expo/expo/commit/37dcd3f02da96a45481b04881a7b33cb95a7bb4b

**Comment by terribleben** [comment] 2017-07-21 18:38
Shipped. Let me know if you see further issues.

**Closed by terribleben** 2017-07-21 18:38 UTC
Labels: Status: Pending

**Comment by AlexanderPPetrov** [comment] 2018-03-30 14:44
Unfortunately it's not working in Android standalone.
Trying to
......
I18nManager.allowRTL(false);
I18nManager.forceRTL(false);
.....
Then Expo.Util.reload()
The first time I run the application layout is RTL(**not expected behaviour**). After closing the application and reopening the RTL is disabled as per the values passed to the I18nManager (**expected behaviour**)
I've really lost quite much time trying to fix that without result. I've found libraries like react-native-restart but they are not compatible with expo project if it is not ejected.
