### ISSUE TITLE
React native, mapview is not loading ANDROID (High priority)

### ISSUE THREAD

**Issue by da45** [expo/expo#18618] opened 2022-08-12 07:15 UTC
### Summary

I can't display map with SDK46, 

### What platform(s) does this occur on?

Android

### Environment

I tried with android studio, my own  device and finally https://snack.expo.dev/

![Untitled](https://user-images.githubusercontent.com/19927289/184303903-9cf6e093-b7fd-450d-b033-53308730adae.jpg)

### Minimal reproducible example

just go to https://docs.expo.dev/versions/latest/sdk/map-view/ and click 'try this example on snack'

**Comment by forki** [comment] 2022-08-12 12:15
probably duplicate of https://github.com/expo/expo/issues/18554

**Comment by da45** [comment] 2022-08-12 19:45
blocking issue but still not assigned !!

**Comment by brentvatne** [comment] 2022-08-12 19:52
indeed duplicate of https://github.com/expo/expo/issues/18554

you can use development builds to work around this for the moment: https://github.com/expo/expo/issues/18554#issuecomment-1213380927

in general, we recommend development builds instead of expo go for anyone building a serious app

**Closed by brentvatne** 2022-08-12 19:52 UTC
Labels: needs review

**Comment by hanamurayuki** [comment] 2023-01-29 07:35
I also face same problem. 
IOS is ok, but blank map on android with `eas build`.
Reason is google map api authorization. (logo exists, but map is brank)

Document was updated on Fri Nov 25 2022.
https://docs.expo.dev/versions/latest/sdk/map-view/

> # [Deploy app with Google Maps](https://docs.expo.dev/versions/latest/sdk/map-view/#deploy-app-with-google-maps)
> ## [Android](https://docs.expo.dev/versions/latest/sdk/map-view/#android)
> 
> 2. [Copy your app's SHA-1 certificate fingerprint](https://docs.expo.dev/versions/latest/sdk/map-view/#copy-your-apps-sha-1-certificate-fingerprint)
> For development builds
> - If you have already created a [development build](https://docs.expo.dev/development/introduction/), your project will be signed using a debug keystore.
> - After the build is complete, go to your [project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D), then, under Configure > click Credentials.
> - `Under Application Identifiers, click your project's package name and under Android Keystore copy the value of SHA-1 Certificate Fingerprint.`

Not only uploading `Google Play Store's SHA-1 certificate fingerprint` on GCP's google map api, 
but we need to upload  `Expo's SHA-1 certificate fingerprint` on GCP ([project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D) > Configure > click Credentials >  Application Identifiers > click your project's package name and under Android Keystore), 

After uploading `Expo's SHA-1 certificate fingerprint on GCP`, app loads map successfully.

**Comment by Chosen2730** [comment] 2023-10-25 18:01
> I also face same problem. IOS is ok, but blank map on android with `eas build`. Reason is google map api authorization. (logo exists, but map is brank)
> 
> Document was updated on Fri Nov 25 2022. https://docs.expo.dev/versions/latest/sdk/map-view/
> 
> > # [Deploy app with Google Maps](https://docs.expo.dev/versions/latest/sdk/map-view/#deploy-app-with-google-maps)
> > ## [Android](https://docs.expo.dev/versions/latest/sdk/map-view/#android)
> > 
> > 2. [Copy your app's SHA-1 certificate fingerprint](https://docs.expo.dev/versions/latest/sdk/map-view/#copy-your-apps-sha-1-certificate-fingerprint)
> >    For development builds
> > 
> > 
> > * If you have already created a [development build](https://docs.expo.dev/development/introduction/), your project will be signed using a debug keystore.
> > * After the build is complete, go to your [project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D), then, under Configure > click Credentials.
> > * `Under Application Identifiers, click your project's package name and under Android Keystore copy the value of SHA-1 Certificate Fingerprint.`
> 
> Not only uploading `Google Play Store's SHA-1 certificate fingerprint` on GCP's google map api, but we need to upload `Expo's SHA-1 certificate fingerprint` on GCP ([project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D) > Configure > click Credentials > Application Identifiers > click your project's package name and under Android Keystore),
> 
> After uploading `Expo's SHA-1 certificate fingerprint on GCP`, app loads map successfully.

Please do you mind elucidating on this? I have copied the SHA-1 fingerprint and pasted on Google cloud console under the API key as instructed by the documentation, for some strange reasons, my app still crashes when it reaches the map view screen

**Comment by id-linksoluciones** [comment] 2024-09-25 11:29
> I also face same problem. IOS is ok, but blank map on android with `eas build`. Reason is google map api authorization. (logo exists, but map is brank)
> 
> Document was updated on Fri Nov 25 2022. https://docs.expo.dev/versions/latest/sdk/map-view/
> 
> > # [Deploy app with Google Maps](https://docs.expo.dev/versions/latest/sdk/map-view/#deploy-app-with-google-maps)
> > ## [Android](https://docs.expo.dev/versions/latest/sdk/map-view/#android)
> > 
> > 2. [Copy your app's SHA-1 certificate fingerprint](https://docs.expo.dev/versions/latest/sdk/map-view/#copy-your-apps-sha-1-certificate-fingerprint)
> >    For development builds
> > 
> > 
> > * If you have already created a [development build](https://docs.expo.dev/development/introduction/), your project will be signed using a debug keystore.
> > * After the build is complete, go to your [project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D), then, under Configure > click Credentials.
> > * `Under Application Identifiers, click your project's package name and under Android Keystore copy the value of SHA-1 Certificate Fingerprint.`
> 
> Not only uploading `Google Play Store's SHA-1 certificate fingerprint` on GCP's google map api, but we need to upload `Expo's SHA-1 certificate fingerprint` on GCP ([project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D) > Configure > click Credentials > Application Identifiers > click your project's package name and under Android Keystore),
> 
> After uploading `Expo's SHA-1 certificate fingerprint on GCP`, app loads map successfully.


I uploaded theExpo's SHA-1 certificate fingerprint in Android restriction, now I have both sha-1, google play store and expo, but it still doesn't show the map. Did I make any mistakes?
