### ISSUE TITLE
GoogleSignIn.signInAsync() doesn't return idToken or accessToken even with a SHA1 Signature

### ISSUE THREAD

**Issue by davidli3100** [expo/expo#4768] opened 2019-06-28 23:16 UTC
## 🐛 Bug Report

As per a [previous issue](https://github.com/expo/expo/issues/4762) filed, I went about the steps of adding a support email address and SHA1 signature to my Firebase project so standalone google sign in could work in my app. 

(Note: my sign in code was all from the guide that Evan Bacon posted on the Expo docs)

I built an android APK using the expo-cli, got the keys and hashes for that apk and uploaded the hashes to firebase. 

Even after that, whenever I log the results of `GoogleSignIn.GoogleSignInAsync()`, this is the output:

```
Object {
  "auth": Object {
    "accessToken": null,
    "accessTokenExpirationDate": null,
    "idToken": null,
    "refreshToken": null,
  },
  "displayName": "David Li",
  "email": "my email",
  "firstName": "David",
  "hostedDomain": undefined,
  "lastName": "Li",
  "photoURL": null,
  "scopes": Array [
    "https://www.googleapis.com/auth/userinfo.profile",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/drive.metadata.readonly",
  ],
  "serverAuthCode": null,
  "uid": "redacted",
}

type: 'success'
```
idToken and accessToken are all null, the thing is, I need these two to be able to create firebase credentials for user login. 

### Environment

  Expo CLI 2.20.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

Target: Standalone Android

### Steps to Reproduce

Follow the guide for the GoogleSignIn Expo package. Then build an app in android using `expo build:android`, and upload the SHA hashes returned by `expo fetch:android:hashes` after the build process is complete.

### Expected Behavior

`GoogleSignIn.signInAsync()` should return a valid idToken and accessToken on a per-user basis

### Actual Behavior

See output above

### Reproducible Demo

I'm not able to share a snack since this is on the standalone apps

**Comment by cruzach** [comment] 2019-07-01 15:47
Hey @davidli3100, this looks like the same issue that you've already posted (and linked in this issue's description). Is there a reason you've opened a new issue?

**Comment by davidli3100** [comment] 2019-07-01 20:07
@cruzach I built a managed app with Expo, got the certificate onto firebase, but Google Sign In still doesn't return a non-null idToken. 

Any idea why?

**Comment by cruzach** [comment] 2019-07-01 20:59
Follow the steps I provided in [this comment](https://github.com/expo/expo/issues/4762#issuecomment-507423267), that *should* work. Closing this issue since it's a duplicate of #4762

**Closed by cruzach** 2019-07-01 20:59 UTC
Labels: bug
