### ISSUE TITLE
BarcodeScanner truncates data if QR code in PDF417 format contains null characters in iOS

### ISSUE THREAD

**Issue by gabzim** [expo/expo#4817] opened 2019-07-04 02:27 UTC
### Environment

Expo CLI 2.19.4 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.9.0 - ~/.npm-packages/bin/npm
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.1 => 32.0.6 
      react: 16.3.1 => 16.3.1 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.19.4

iOS (works fine in Android)

### Steps to Reproduce

1. Scan a QR code in PDF417 format (this might extend beyond this format), that has a non readable sequence encoded in it, I'm scanning a barcode that begins with:
`40 0a 1e 0d 41 4e 53 49 20 39 39 30 38 37 36 30 33 30 30 30 31 44 4c 1f 00 00 00 c3 85 00 00 00 44 4c 44 43 ...`
This belongs to an Ontario Driver License, and my guess is that the offending sequence is: `1f 00 00 00 c3 85 00 00 00` (a Unit Separator Character, followed by three nulls, then a Next Line, then three nulls). I've created a QR linked at the end of the description that you can scan in Android and iOS and it shows how the character `\0x00` truncates the output in iOS.

2. The iOS object returned by the `onBarCodeScanned` callback has the `data` attributed truncated when that sequence begins. That means I can only read the first few characters of that Barcode. The behavior in Android works well, it reads the entire barcode.

### Expected Behavior

The entire content of the QR code is returned in the data field.

### Actual Behavior

Only the characters before the offending sequence are returned.

### Reproducible Demo

```javascript
import React, { Component } from 'react';
import {StyleSheet, Text, View} from 'react-native';

import {Permissions} from 'expo-permissions';

import {BarCodeScanner} from 'expo-barcode-scanner';
import {SplashScreen} from "expo";

export default class App extends Component {
  constructor(props) {
    super(props);
  }

  state = {
    hasCameraPermission: null
  };

  async componentDidMount() {
    SplashScreen.hide();
    this.getPermissionsAsync();
  }

  getPermissionsAsync = async () => {
    const {status} = await Permissions.askAsync(Permissions.CAMERA);
    this.setState({hasCameraPermission: status === 'granted'});
  };

  render() {
    const {hasCameraPermission} = this.state;

    if (hasCameraPermission === null) {
      return <Text>Requesting for camera permission</Text>;
    }
    if (hasCameraPermission === false) {
      return <Text>No access to camera</Text>;
    }
    return (
        <View
            style={{
              flex: 1,
              flexDirection: 'column',
              justifyContent: 'flex-end',
            }}>

          <BarCodeScanner
              onBarCodeScanned={this.handleBarCodeScanned}
              style={StyleSheet.absoluteFillObject}
          />
        </View>
    );
  }

  handleBarCodeScanned = (barcode) => {
    console.log(barcode.data)
  }
}
```
[QR code to test](https://imgur.com/c2rEZ1V)

This was already reported: https://forums.expo.io/t/null-characters-are-breaking-the-data-when-using-barcode-scanner-on-ios/10923

**Comment by gabzim** [comment] 2019-07-04 02:36
Here's what Android logs:`HELLO`, here's what iOS logs: `H`

**Comment by bbarthec** [comment] 2019-07-08 11:26
Hello @gabzim, I've investigated the cause of the problem and it seems that iOS SDK does not provide barcode scanning function that works accordingly to expectations 😞.
According to many topics on forums and StackOverflow (like [this one](https://stackoverflow.com/questions/46820518/swift-4-avmetadataobject-stringvalue-has-incomplete-information-when-reading-p)) we can (a) extract raw bytes data from barcode scanner, but then there's need to (b) parse these obtained bytes into string and that (b) part should be delegated to some library or method.
There is number of libraries for iOS doing that, but each is paid and that prevents us from using them for now. Nevertheless I'm going to discuss the matter internally.

**Comment by gabzim** [comment] 2019-07-08 13:47
@bbarthec I suppose giving a base64 encoded alternative isn't a viable option. But my guess is that if you have access to the raw byte data, maybe running a quick sanitizing of control characters (or actually, I think it's just the `NULL 0x00` char) might help. Would it break the contract to drop NULL (or all control characters) from the string output? Since you're trying to display as text, null chars do not really belong in there.

**Comment by bbarthec** [comment] 2019-07-08 14:13
@gabzim, raw data that is obtained from iOS barcode scanner API is not that easily convertible to string 😞 data is somehow encoded by some algorithm that, from what I know, depends on barcode type that is being used. Despite the fact that each barcode specification is open, I haven't found (as for now) any solid library handling these encoded bytes into string 😞

**Comment by gabzim** [comment] 2019-07-08 14:28
@bbarthec Sounds good, although if while investigating your solution you could avoid one that requires an active internet connection that would be best (by no means trying to impose requirements on you, just that I'm sure there are many use cases, mine included, where we can't assume the user will have internet connectivity when scanning).

**Comment by gabzim** [comment] 2019-07-24 13:44
@bbarthec any updates on this? Any way we can help further?

**Comment by andresmtz98** [comment] 2019-07-24 21:51
AVFoundation is the f***ing problem xdd

**Comment by bbarthec** [comment] 2019-07-25 08:44
Right now I'm busy with SDK34 release process, but I will take care of it once the new SDK is out 🙂

**Comment by gabzim** [comment] 2019-09-19 19:12
Hi @bbarthec any updates on this?

**Comment by anwarsalman** [comment] 2019-09-25 23:25
@bbarthec Has the  SDK34 release been completed? We are running into the same issue? I was wondering if you have an updated estimate on when you can fix this issue - it is clear that others users are running into the same issue as we are, any help is greatly appreciated.

**Comment by bbarthec** [comment] 2019-10-10 08:44
Hey @gabzim, @anwarsalman! My apologies for being inactive in this issue for so long! 🙇 I'm on this issue right now and I'm going to add [MLKit from Firebase](https://firebase.google.com/docs/ml-kit/read-barcodes) for additional barcode scanning as it supports PDF417 format 😊 ([similar Firebase module](https://firebase.google.com/docs/ml-kit/detect-faces) is added in our `FaceDetector` module for detecting faces).

**Comment by gabzim** [comment] 2019-10-10 20:09
Excellent @bbarthec do you think there's a chance this will make it to SDK 36? If yes, do we have a rough release date for that SDK?

**Comment by bbarthec** [comment] 2019-10-11 07:56
@gabzim, landing fix for this issue in SDK36 is my goal now 😉 Rough estimation for next release date is in the first half/beginning of the next month.

**Comment by xiCO2k** [comment] 2019-10-23 15:00
Hey @bbarthec also detected that code39 is not working well for example with car VIN codes like this:

![image](https://user-images.githubusercontent.com/823088/67406661-427b4400-f5ae-11e9-9690-bb9461f4e608.png)

Do you think the ZXing library can also help with that?

Thanks

**Closed** 2019-11-12 14:57 UTC
Labels: BarCodeScanner, bug, project: ios-runtime, status: in review
