### ISSUE TITLE
__dirname is always static in generateStaticParams()

### ISSUE THREAD

**Issue by yurii-chikhrai-wk** [expo/expo#29688] opened 2024-06-12 12:28 UTC
### Minimal reproducible example

https://github.com/yurii-chikhrai-wk/expo-generateStaticParams-error

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

No (web-only issue)

### Summary

`__dirname` identifier inside `generateStaticParams` not dynamic and always linked to `/node_modules/expo-router/node`

### Environment

```
 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.2/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.13 => 51.0.13 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by marklawlor** [comment] 2024-06-25 08:08
Unfortunately I'm going to close this as won't fix, but I will document this better in the docs. Expo Router "copies" your files into a new directory and compiles there there, so the `__dirname` is not guaranteed to match.

The issue is also present in Next.js (which Expo Router used for inspiration for this featured). The Next.js documentation is here [here](https://nextjs.org/docs/pages/api-reference/functions/get-static-props#reading-files-use-processcwd). Additional Next.js discussion, with some work arounds, on the issue [here](https://github.com/vercel/next.js/discussions/32236)

**Closed by marklawlor** 2024-06-25 08:08 UTC
Labels: needs review, Router
