### ISSUE TITLE
Can't load specific png in testflight. (failed md5 integrity check)

### ISSUE THREAD

**Issue by yavorsky** [expo/expo#3283] opened 2019-01-22 12:39 UTC
### Environment
 Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.1 
      react: 16.4.0 => 16.4.0 
      react-native: ^0.57.8 => 0.57.608 
      react-navigation: 1.0.0-beta.29 => 1.0.0-beta.29 
    npmGlobalPackages:
      expo-cli: 2.6.14

### Steps to Reproduce

1. Create some png under `assets/image.png`.
2. Run `expo build:ios`
3. Upate `assets/image.png` (via photoshop, etc).
3. Run `expo build:ios` again.
4. Download ios app binary
5. Open Application Loader and upload binary.
6. Via Testflight download the app.
7. In the app `Asset.loadAsync([require('../assets/image.png')]).catch(e => alert(e))`. 

### Expected Behavior

It shoul just work.

### Actual Behavior
For `Asset.loadAsync([require('../assets/image.png')]).catch(e => alert(e))`. 
You'll see something like:
<img width="254" alt="screen shot 2019-01-22 at 2 00 23 pm" src="https://user-images.githubusercontent.com/1521229/51536104-20079f00-1e53-11e9-9d14-b544793292a5.png">

**Comment by ide** [comment] 2019-01-22 19:19
This might be due to one of the bugs in the React Native packager -- try expo start -c to clear your cache?

**Comment by janakg** [comment] 2019-01-24 12:52
@yavorsky  suggested solution solved your problem?   @ide I am noting a similar issue in the universal expo-font module as well.                     Downloaded file for asset 'SiviShapeIcons.ttf' Located at https://d1wp6m56sqw74a.cloudfront.net/~assets/d3d4914018bf684363912f5dd4c4666e failed MD5 integrity check

**Comment by janakg** [comment] 2019-01-26 04:06
@AdamJNavarro  This repo with universal modules has the exact same issue, I believe the logic is shared. See it is of any use.

https://github.com/janakg/my-app-with-universal-modules

**Comment by sjchmiela** [comment] 2019-02-04 15:17
Hey, @janakg! I looked at your repository and the problem that the application surfaces is that `expo-asset` isn't very well supported in vanilla React Native apps as it expects all assets to be located on CloudFront. However, it would be possible to fix your problem with that font, you'd only need to pass a custom `Asset` instance (i.e. created by hand and then with edited `localUri`) to `Font.loadAsync` instead of a `require`-d module.

At the moment I wasn't able to reproduce the issue you've described with the repo you've provided, do you have some pointers on what should I do to trigger the error?

**Comment by sjchmiela** [comment] 2019-02-06 13:30
@adamtsai1, something like:
```
const asset = Asset.fromModule(require(…));
asset.localUri = "<URI where the font file will be put>";
asset.downloaded = true;
```

BTW this shouldn't happen in Expo, if this issue happens you eg. have an upstream version of React Native, please confirm that `react-native` comes from `github.com/expo/react-native…`. 🙂

**Comment by janakg** [comment] 2019-02-07 14:20
> Hey, @janakg! I looked at your repository and the problem that the application surfaces is that `expo-asset` isn't very well supported in vanilla React Native apps as it expects all assets to be located on CloudFront. However, it would be possible to fix your problem with that font, you'd only need to pass a custom `Asset` instance (i.e. created by hand and then with edited `localUri`) to `Font.loadAsync` instead of a `require`-d module.
> 
> At the moment I wasn't able to reproduce the issue you've described with the repo you've provided, do you have some pointers on what should I do to trigger the error?

@sjchmiela As you mentioned it is something to do with FS APIs. Can you point to exact versions in my package json and try?

**Comment by tanx** [comment] 2019-06-14 20:57
> @yavorsky suggested solution solved your problem? @ide I am noticing a similar issue in the universal expo-font module as well.

I'm getting this same error for `.ttf` files on Android after upgrading to expo 33.0.5. Did a fresh eject to Expokit.

**Comment by tanx** [comment] 2019-06-14 21:10
Possibly the same issue as this one. Linked example here: https://github.com/expo/expo/issues/4217#issuecomment-502263947

**Comment by tsapeta** [comment] 2020-07-18 14:46
Let me close this issue as there haven't been any activity recently, but feel free to comment here if you're still encountering this in the most recent SDK version 🙂

**Closed by tsapeta** 2020-07-18 14:46 UTC
