### ISSUE TITLE
[image-picker][ios] Black/Dark bar at the bottom when the photo is taken in landscape orientation.

### ISSUE THREAD

**Issue by foolem** [expo/expo#19464] opened 2022-10-07 21:17 UTC
### Summary

I think we might have an issue with the [fixOrientation.swift file](https://github.com/expo/expo/blob/552c204b5e642ee6946745e38b2a4e38d965a6ea/packages/expo-image-picker/ios/UIImage%2BfixOrientation.swift).

This issue started happening when we upgraded our Expo SDK to 45. Version 44 worked well.

Now we use SDK 46 and the issue persists.

When the photo is taken in landscape orientation and the phone keeps it in that orientation until the image finishes processing. The image result is an image with a black bar at the bottom.

![black bar](https://user-images.githubusercontent.com/29935579/194653479-5977a6e1-adc4-44ff-a23a-d008a3620d81.jpeg)

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
      Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/filipefenrich/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.9 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.8 
    Expo Workflow: bare

### Minimal reproducible example

```
import * as ImagePicker from 'expo-image-picker';

// Turn the iPhone to any landscape orientation.
// Keep the iPhone in landscape orientation until the photo is saved.

const result = await ImagePicker.launchCameraAsync({
  mediaTypes: ImagePicker.MediaTypeOptions.Images,
  quality: 0.7,
  allowsEditing: false,
  aspect: [4, 3],
  exif: true,
});

// After the image is returned, you'll see the image has this black bar on the bottom.

```

**Comment by foolem** [comment] 2022-10-07 22:24
When [I added this patch here](https://github.com/expo/expo/issues/17875#issuecomment-1221547735). It started working, no more black bars.

**Comment by Simek** [comment] 2022-10-10 09:52
Hello @foolem, this fix has been merged already and will be a part of next package release:
* https://github.com/expo/expo/pull/19185

Closing as a duplicate of #17875.

**Closed by Simek** 2022-10-10 09:52 UTC
Labels: needs review
