### ISSUE TITLE
Problem with Samsung devices

### ISSUE THREAD

**Issue by claudiofus** [expo/expo#18291] opened 2022-07-19 08:14 UTC
### Summary

This problem occurred with SDK 45 and EAS build only in Android devices, especially Samsung Galaxy A51, Samsung Galaxy A52s 5G, Samsung Galaxy Z Flip3 5G, Samsung Galaxy S21+ 5G

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.soulfully.quizmedicina2020 <<<

backtrace:
  #00  pc 00000000006703bc  /data/app/~~d6CdOraDz3qhB5b2AcguQQ==/com.soulfully.quizmedicina2020-UgMhkIm1ImLylQW2AeHyYA==/split_config.arm64_v8a.apk!libjsc.so
  #00  pc 000000000000063c  [vdso] (__kernel_rt_sigreturn)
  #00  pc 00000000000d82d4  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+4)
  #00  pc 000000000001663c  /system/lib64/libutils.so (android::Looper::pollInner(int)+180)
  #00  pc 0000000000016520  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112)
  #00  pc 0000000000152458  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  #00  pc 000000000028444c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (art_jni_trampoline+108)
  #00  pc 00000000007e9008  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.os.MessageQueue.next+232)
  #00  pc 00000000007e61f4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.os.Looper.loopOnce+100)
  #00  pc 00000000007e60f4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.os.Looper.loop+516)
  #00  pc 00000000005632f0  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (android.app.ActivityThread.main+800)
  #00  pc 00000000002ca9e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568)
  #00  pc 000000000035b5d0  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+608)
  #00  pc 000000000035b348  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52)
  #00  pc 00000000000b2f74  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+132)
  #00  pc 0000000000b394cc  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+140)
  #00  pc 0000000000b42968  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2376)
  #00  pc 00000000002ca9e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568)
  #00  pc 000000000044ca04  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+464)
  #00  pc 000000000062cf30  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+268)
  #00  pc 00000000000b2ac4  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+120)
  #00  pc 00000000000beb68  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+848)
  #00  pc 00000000000025c8  /system/bin/app_process64 (main+1396)
  #00  pc 0000000000082004  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+96)
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45.0.0

### Environment

```
 expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      npm: 8.12.1 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.18 => 0.3.18 
      babel-preset-expo: ^9.1.0 => 9.1.0 
      expo: ^45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 5.5.1
    Expo Workflow: managed
```

### Reproducible demo

I don't know when it occurs

**Comment by fobos531** [comment] 2022-07-19 08:45
duplicate of #18083

**Closed** 2022-07-19 09:42 UTC
Labels: needs review
