### ISSUE TITLE
[expo-camera] Have to set `type` twice in order for it to take effect when using useCamera2Api

### ISSUE THREAD

**Issue by harterc1** [expo/expo#8339] opened 2020-05-18 02:15 UTC
### Environment

Testing on Android Device (Pixel 1)

```
Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.16.1/bin/npm
    IDEs:
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.7 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.20.9
```

### Steps to Reproduce

1. Add a `Camera` from `expo-camera` in your app and set the prop `type="front"`.

2. Additionally, set prop `useCamera2Api={true}`

3. Add a button that simply toggles the `type` value back and forth between `"front"` and `"back"`. 

### Expected Behavior

The `Camera` should accurately reflect the current value of it's `type` prop value.

### Actual Behavior

After the camera's initial mount, you'll have to press your button twice in order for it to start reacting to the change in `type` value.  (Which means it'll show the "front" camera when the value is `"back"` and vice versa.)

**Comment by IjzerenHein** [comment] 2020-05-18 15:17
I've not been able to find an issue in the `expo-camera` package that would explain this. In the past there have been problems with the camera 2 APIs which may be the reason it was disabled by default.

*from notes in https://docs.expo.io/versions/latest/sdk/camera/*

> Android devices can use one of two available Camera apis underneath. This was previously chosen automatically, based on the device's Android system version and camera hardware capabilities. As we experienced some issues with Android's Camera2 API, we decided to choose the older API as a default. However, using the newer one is still possible through setting useCamera2Api prop to true. The change we made should be barely visible - the only thing that is not supported using the old Android's API is setting focus depth.

@bbarthec @lukmccall @sjchmiela Do you know whether this could this have anything to do with the Camera2 API issues? Also do you know if there is a way to view the commit history of this package before it was moved to the `packages` folder ?

**Comment by sjchmiela** [comment] 2020-05-18 16:27
> Also do you know if there is a way to view the commit history of this package before it was moved to the packages folder?

I usually go to the commit introducing the new file (first commit in <kbd>History</kbd>), then hit <kbd>parent</kbd> (as in commit) in GitHub view, then <kbd>Browse files</kbd>, <kbd>Find file</kbd>, I look for the same one and there I have it.

Regarding the issue my initial hunch is that we are not synchronizing reacting to prop changes (`didSetProps:`-like), but I may be wrong on that.

**Comment by IjzerenHein** [comment] 2020-05-19 07:27
This appears to be an issue in the Camera2 implementation which is no longer supported by Google. We do not control that code, but technically we could copy the code from https://github.com/react-native-community/react-native-camera/tree/master/android/src/main/java/com/google/android/cameraview
I however do not think that's a very future proof solution. At some point the `expo-camera` package should be updated to use the newer androidx.camera.view component.

**Comment by IjzerenHein** [comment] 2020-05-19 07:27
Closing as this appears to be a duplicate of #4192

**Closed by IjzerenHein** 2020-05-19 07:27 UTC
Labels: Camera, project: android-runtime

**Comment by sjchmiela** [comment] 2020-05-19 07:29
Good thing we already have that code copied at https://github.com/expo/expo/tree/master/android/cameraview/cameraview. 😅 (As far as I can remember correctly, the `cameraview` package we bundle with `expokit` NPM package is the one built from this by us.)

**Comment by IjzerenHein** [comment] 2020-05-19 07:55
Ah thanks for letting me know, I did not know this :+1: 🙏
