### ISSUE TITLE
Webview HTML renders as string on Android in dev environment

### ISSUE THREAD

**Issue by beningreenjam** [expo/expo#4566] opened 2019-06-12 12:38 UTC
### Development Environment

```bash
Expo CLI 2.19.5 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.5 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.0.9 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.19.5
```

Targets:
Android 4.1+
iOS 9.0+

Upgraded from Expo 32 to 33

Was working prior to upgrade with the code below. No documentation on webview for Expo 33.

### Expected Behavior

Renders as HTML as HTML on all devices in both production and dev

### Actual Behavior

Renders HTML document as string on Android in dev environment. As expected on other devices.

### Reproducible Demo

Create file called `test.html` with any dummy test HTML content inside.

```bash
import React, {Component} from "react";
import {WebView} from "react-native";
import {Asset} from "expo-asset";

export default class Graph extends Component {
    getSource = () => {
        const source = {uri: Asset.fromModule(require('./test.html')).uri};

        if (!__DEV__) {
            return source;
        }

        source.headers = {'Accept': 'text/html', 'Content-Type': 'text/html'};
        return source;
    };

    render = () => (
        <WebView
            style={{width: 300, height: 300, backgroundColor: '#00000000'}}
            source={this.getSource()}
            bounces={false}
            useWebKit={true}
            scrollEnabled={false}
        />
    );
}
```

**Comment by cruzach** [comment] 2019-06-12 15:12
Hey @beningreenjam, 

You can read this in our docs, but:

>Required Android and iOS versions: The minimum Android version Expo supports is Android 5 and the minimum iOS version is iOS 10.0.

If you can repro this behavior on the later versions, I'll be happy to re-open the issue 👍

**Comment by beningreenjam** [comment] 2019-06-12 16:23
@cruzach I've been testing on iOS 12.3.1 and Android 8.0.0

**Comment by bulby97** [comment] 2019-06-27 11:55
@cruzach Latest android and having the same issues.

**Comment by bulby97** [comment] 2019-06-27 12:03
@beningreenjam did you find a solution ?

**Comment by cruzach** [comment] 2019-06-27 14:44
[Here](https://docs.expo.io/versions/latest/react-native/webview/#__next) is the documentation for `Webview`. Are you sure this is a problem with Expo? `Webview` is imported from `react-native`. Can you confirm this doesn't happen on a plain react-native project?

**Comment by andreiortiz** [comment] 2019-07-03 08:27
> [Here](https://docs.expo.io/versions/latest/react-native/webview/#__next) is the documentation for `Webview`. Are you sure this is a problem with Expo? `Webview` is imported from `react-native`. Can you confirm this doesn't happen on a plain react-native project?

hi, im encountering the same issue, just upgraded to expo sdk 33.

also, the link attached for the documentation for sdk 33 for webview in expo is not working.
https://docs.expo.io/versions/v33.0.0/react-native/webview/
also, cant find the WebView in the latest expo sdk documentation.


Thank you.

**Comment by paldepind** [comment] 2019-07-10 12:11
As far as I can tell, since WebView has been removed from react-native `import {WebView} from "react-native"` is no longer the way to go. One should instead import `webview` from react-native-webview.

That doesn't solve the issue though. I think the issue is the related to this react-native-webview issue: https://github.com/react-native-community/react-native-webview/issues/428.

**Comment by cruzach** [comment] 2019-07-15 14:22
Sorry about that docs link- we incorporated `react-native-webview` into the Expo SDK in SDK33, and needed to move the API from the "React Native" section of our docs to the "SDK" section. Done now! -> https://docs.expo.io/versions/v33.0.0/sdk/webview/

Anyways, thanks @paldepind for linking that issue. Since this looks like it's an upstream issue with `react-native-webview`, I'm going to close this. If someone is able to get the right behavior on a plain RN project, please share it and I'll re-open this!

**Closed by cruzach** 2019-07-15 14:22 UTC
Labels: bug

**Comment by GiFree** [comment] 2019-07-22 00:57
@cruzach Hello, im having same issue, problem is not in WebView, propably with expo or some bundler inside it which provides static html file inside `pre` tag. 
[situation photo](https://i.gyazo.com/536fc43a1b1f72a7d6942eb9d27421f6.png)

**Comment by cruzach** [comment] 2019-07-22 15:25
@GiFree could you open a new issue and follow the issue template? Make sure to provide a reproducible example please!

**Comment by zhouping3** [comment] 2019-08-01 03:37
hi, im encountering the same issue,  expo sdk 33.

**Comment by bulby97** [comment] 2019-08-01 03:44
I fixed the issue ! Thanks to [this link](https://medium.com/@filipedegrazia/embedding-a-local-website-on-your-expo-react-native-project-eea322738872)

```
componentDidMount() {
    this.HTMLFile = Asset.fromModule(require('./index.html'))

    if (!this.HTMLFile.localUri) {
      Asset.loadAsync(require('./bibleWebView/dist/index.html')).then(() => {
        this.HTMLFile = Asset.fromModule(require('./bibleWebView/dist/index.html'))
        this.setState({ isHTMLFileLoaded: true })
      })
    } else {
      this.setState({ isHTMLFileLoaded: true })
    }
}
```


in the render:

  render () {
    if (!this.state.isHTMLFileLoaded) {
      return null
    }

    const { localUri } = this.HTMLFile

    return (
      <WebView
        source={
          Platform.OS === 'android'
            ? {
              uri: localUri.includes('ExponentAsset')
                ? localUri
                : 'file:///android_asset/' + localUri.substr(9)
            }
            : require('./index.html')}
        ....
      />
    )
```

**Comment by zhouping3** [comment] 2019-08-02 11:28
@bulby97 what's your Development Environment? i aslo saw that link,but not solve this problem

**Comment by edouard-claude** [comment] 2019-09-26 12:01
> I fixed the issue ! Thanks to [this link](https://medium.com/@filipedegrazia/embedding-a-local-website-on-your-expo-react-native-project-eea322738872)
> 
> ```
> componentDidMount() {
>     this.HTMLFile = Asset.fromModule(require('./index.html'))
> 
>     if (!this.HTMLFile.localUri) {
>       Asset.loadAsync(require('./index.html')).then(() => {
>         this.HTMLFile = Asset.fromModule(require('./index.html'))
>         this.setState({ isHTMLFileLoaded: true })
>       })
>     } else {
>       this.setState({ isHTMLFileLoaded: true })
>     }
> }
> ```
> 
> in the render:
> 
> ```
>   render () {
>     if (!this.state.isHTMLFileLoaded) {
>       return null
>     }
> 
>     const { localUri } = this.HTMLFile
> 
>     return (
>       <WebView
>         source={
>           Platform.OS === 'android'
>             ? {
>               uri: localUri.includes('ExponentAsset')
>                 ? localUri
>                 : 'file:///android_asset/' + localUri.substr(9)
>             }
>             : require('./index.html')}
>         ....
>       />
>     )
> ```

Hi, 

Thank you for your post, however, I have this error message:

```
Encountered an error loading page Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_ACCESS_DENIED",
  "loading": false,
  "target": 793,
  "title": "",
  "url": "file:///data/user/0/host.exp.exponent/cache/ExperienceData/[...]/ExponentAsset-f7999351c571a968d5a9028cf5d49f39.html",
}
```

**Comment by chachaxw** [comment] 2019-11-03 09:07
> I fixed the issue ! Thanks to [this link](https://medium.com/@filipedegrazia/embedding-a-local-website-on-your-expo-react-native-project-eea322738872)
> 
> ```
> componentDidMount() {
>     this.HTMLFile = Asset.fromModule(require('./index.html'))
> 
>     if (!this.HTMLFile.localUri) {
>       Asset.loadAsync(require('./index.html')).then(() => {
>         this.HTMLFile = Asset.fromModule(require('./index.html'))
>         this.setState({ isHTMLFileLoaded: true })
>       })
>     } else {
>       this.setState({ isHTMLFileLoaded: true })
>     }
> }
> ```
> 
> in the render:
> 
> ```
>   render () {
>     if (!this.state.isHTMLFileLoaded) {
>       return null
>     }
> 
>     const { localUri } = this.HTMLFile
> 
>     return (
>       <WebView
>         source={
>           Platform.OS === 'android'
>             ? {
>               uri: localUri.includes('ExponentAsset')
>                 ? localUri
>                 : 'file:///android_asset/' + localUri.substr(9)
>             }
>             : require('./index.html')}
>         ....
>       />
>     )
> ```

It works for me, but some files are still unable to view. Did you meet this issu?

**Comment by Le4Q** [comment] 2020-01-15 16:03
> > I fixed the issue ! Thanks to [this link](https://medium.com/@filipedegrazia/embedding-a-local-website-on-your-expo-react-native-project-eea322738872)
> > ```
> > componentDidMount() {
> >     this.HTMLFile = Asset.fromModule(require('./index.html'))
> > 
> >     if (!this.HTMLFile.localUri) {
> >       Asset.loadAsync(require('./index.html')).then(() => {
> >         this.HTMLFile = Asset.fromModule(require('./index.html'))
> >         this.setState({ isHTMLFileLoaded: true })
> >       })
> >     } else {
> >       this.setState({ isHTMLFileLoaded: true })
> >     }
> > }
> > ```
> > 
> > 
> > in the render:
> > ```
> >   render () {
> >     if (!this.state.isHTMLFileLoaded) {
> >       return null
> >     }
> > 
> >     const { localUri } = this.HTMLFile
> > 
> >     return (
> >       <WebView
> >         source={
> >           Platform.OS === 'android'
> >             ? {
> >               uri: localUri.includes('ExponentAsset')
> >                 ? localUri
> >                 : 'file:///android_asset/' + localUri.substr(9)
> >             }
> >             : require('./index.html')}
> >         ....
> >       />
> >     )
> > ```
> 
> Hi,
> 
> Thank you for your post, however, I have this error message:
> 
> ```
> Encountered an error loading page Object {
>   "canGoBack": false,
>   "canGoForward": false,
>   "code": -1,
>   "description": "net::ERR_ACCESS_DENIED",
>   "loading": false,
>   "target": 793,
>   "title": "",
>   "url": "file:///data/user/0/host.exp.exponent/cache/ExperienceData/[...]/ExponentAsset-f7999351c571a968d5a9028cf5d49f39.html",
> }
> ```

Have you tried adding WebView's allowFileAccess prop?

**Comment by hrtest-dev** [comment] 2020-09-25 15:37
same issue here net::ERR_ACCESS_DENIED, do this work for any of you?
