### ISSUE TITLE
"Cycle in dependencies between targets 'EXApplication' and 'ExpoModulesCore'" error when "expo run:ios" after running "expo export"

### ISSUE THREAD

**Issue by raphaelmsr** [expo/expo#15079] opened 2021-11-07 09:42 UTC
### Summary

Hi,

I am developing an app under the managed worfklow, but since I needed a RN module I had to manage both expo and native modules (my customer is checking the app development with Expo Go, it is so easy to deploy that I dont want to switch 100% to Custom dev client for now)

After having deployed for the first time to my private server with `expo export `, I went back to `expo run:ios`
and found myself with this error 

`Cycle in dependencies between targets 'EXApplication' and 'ExpoModulesCore'; building could produce unreliable results. `

and couldn't build at all.

Fixed it by deleting the `ios` folder in the project; although it shouldn't be an error I guess

PS : I'm so fond of the way I can't develop thanks to Expo Go for quick adhoc distribution and custom dev client for the realworld behaviour of an app, magical!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

 Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.20.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.1 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Run expo export on a project, and then expo run:ios 
It should crash saying there's a conflict in the cycle in dependencies between targets 'EXApplication' and 'ExpoModulesCore'
Deleting the ios folder resulting from expo export and then running expo run should fix the problem

**Comment by brentvatne** [comment] 2021-11-12 05:26
this may be caused by having multiple versions of expo-modules-core in your project. try running `yarn why expo-modules-core` to see which versions you are using. upgrade them all to the same version -- you can do this by clearing your lockfile, for example

**Comment by just-a-normal-human** [comment] 2021-11-29 16:08
I have exact same error but without doing `expo export`. Doing `yarn why expo-modules-core` gives `=> Found "expo-modules-core@0.4.8"` but no other versions. Switching Xcode to legacy build works, but is not permanent fix since legacy build will soon be deprecated.

**Comment by drewgom** [comment] 2021-11-30 03:22
Hi, I'm running in to this same issue, and not having any success with the Legacy Build Settings. When I try to use that, I get `module map file '/Users/****/Library/Developer/Xcode/DerivedData/myproject-duscfxyethnygeanyyyiohrescjn/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.modulemap' not found`

**Comment by drewgom** [comment] 2021-11-30 03:44
@raphaelmsr @just-a-normal-human not sure if this helps for your guys use case, but for my scenario where I was getting `Cycle in dependencies between targets 'EXApplication' and 'ExpoModulesCore'` I got it to work by moving the `Compile Sources` phase of compilation to be before the `Headers` phase.

I did this by:
1. Opening `Pods/Pods.xcodeproj` in Xcode
2. Opening the Issue Navigator
3. Selecting the `ExpoModulesCore` target
4. Selecting Build Phases
5. Moving `Compile Sources` to be above `Headers`

I posted a screenshot of how I have `ExpoModulesCore` configured. Previously, `Headers` was above `Compile Sources`

<img width="2032" alt="Screen Shot 2021-11-29 at 7 41 29 PM" src="https://user-images.githubusercontent.com/44813535/143981882-6bd348a1-01e5-4591-9845-55cda816fdfb.png">

**Comment by foolem** [comment] 2021-12-08 13:17
> @raphaelmsr @just-a-normal-human not sure if this helps for your guys use case, but for my scenario where I was getting `Cycle in dependencies between targets 'EXApplication' and 'ExpoModulesCore'` I got it to work by moving the `Compile Sources` phase of compilation to be before the `Headers` phase.
> 
> I did this by:
> 
> 1. Opening `Pods/Pods.xcodeproj` in Xcode
> 2. Opening the Issue Navigator
> 3. Selecting the `ExpoModulesCore` target
> 4. Selecting Build Phases
> 5. Moving `Compile Sources` to be above `Headers`
> 
> I posted a screenshot of how I have `ExpoModulesCore` configured. Previously, `Headers` was above `Compile Sources`
> 
> <img alt="Screen Shot 2021-11-29 at 7 41 29 PM" width="2000" src="https://user-images.githubusercontent.com/44813535/143981882-6bd348a1-01e5-4591-9845-55cda816fdfb.png">

Great solution, but it will work on you machine only, when you need to to a `pod install` again, this config will vanish...

I hope there is a more solid solution for this.

**Comment by foolem** [comment] 2021-12-08 13:26
I found this, you can change the build phase order inside Podfile... [](https://github.com/tuist/tuist/discussions/2817)

**Comment by foolem** [comment] 2021-12-08 14:06
Add this to your Podfile:

`  post_integrate do |installer|
    update_pod_build_phase_order("./Pods/Pods.xcodeproj", "ExpoModulesCore")
  end

  def update_pod_build_phase_order(xcodeproj_path, target_name)
    puts "Updating build phase order of 'Headers' in #{xcodeproj_path}, #{target_name} \n"
    project = Xcodeproj::Project.open(xcodeproj_path)
    target = project.targets.select { |t| t.name == target_name }.first
    puts "Found target: #{target.name}\n"
    cocoapods_index = target.build_phases.index do |b|
      puts "#{b} , #{b == "HeadersBuildPhase"}"
      b.to_s == "HeadersBuildPhase"
    end
    if cocoapods_index.nil? == false
        puts "#{target_name}: 'HeadersBuildPhase' index was: #{cocoapods_index}, moving to index 1.\n"
        target.build_phases.move_from(cocoapods_index, 1)
    end
    project.save
  end`

**Comment by mrados7** [comment] 2021-12-21 15:13
I'm having same issue and none of the above solutions work for me. XCode 13.1.
```
error: Cycle in dependencies between targets 'EXApplication' and 'ExpoModulesCore'; building could produce unreliable results.
Cycle path: EXApplication → ExpoModulesCore → EXApplication
```
`yarn why expo-modules-core` returns only one version:
```
=> Found "expo-modules-core@0.4.7"
```

**Comment by BlackRockSoul** [comment] 2021-12-21 23:57
> I'm having same issue and none of the above solutions worked for me. XCode 13.1.

`cd ios && rm -rf Pods && pod install && cd ..` helped for me for some reason. Maybe someone will find it useful

**Comment by a-eid** [comment] 2022-01-23 09:05
to solve the issue you have to remove the `Pods` directory.

`rm -fr ios/Pods && yarn ios`

**Comment by swizes** [comment] 2022-05-04 06:25
This has to be fixed. Why am I forced to do `rm -fr ios/Pods && yarn ios` (yet it fails) everytime

**Comment by mcrstudio** [comment] 2022-06-10 09:48
Why on earth are people celebrating these comments. Deleting and reinstalling Pods is *not* the correct solution. If you're going to make me use the entire bulls*** ecosystem of Expo tools just to use your Secure Storage plugin - the least you can do it ensure it doesn't build like dirt.

**Comment by swizes** [comment] 2022-06-10 09:53
> Why on earth are people celebrating these comments. Deleting and reinstalling Pods is _not_ the correct solution. If you're going to make me use the entire bulls*** ecosystem of Expo tools just to use your Secure Storage plugin - the least you can do it ensure it doesn't build like dirt.

I was facing with this issue in several projects.

Only "solution" that has worked for me was

Create new react-native project
Install expo 45
Do every native module setup step for each library
Copy src folder to the new project
Test each module, if they are working

Now I have saved tons of hours by not having to do "remove pods, reinstall again, fail, remove pods, reinstall again, hope to not fail, fail"
I love my life.

**Comment by brentvatne** [comment] 2022-06-10 09:53
@mcrstudio - nobody is forcing you to use anything. feel free to use another library to accomplish the same thing: https://reactnative.directory

**Comment by brentvatne** [comment] 2022-06-10 09:54
if someone can provide a repository that we can clone and reproduce this easily we can investigate it further!

**Comment by swizes** [comment] 2022-06-10 09:55
> osted a screenshot of how I have `Exp`

Unfortunately, I don't have anymore a repo to serve as an example. But I can confirm that it happened on expo 44, rn 0.66-0.67 versions, hope that helps

**Comment by mcrstudio** [comment] 2022-06-10 09:59
> @mcrstudio - nobody is forcing you to use anything. feel free to use another library to accomplish the same thing: https://reactnative.directory

No, it's just that Expo's Secure Storage is one of the most battle tested and proven solutions. My complaint is that if I want to use the well-tested library, I *am* being forced to use excess bloat when it's evidently not necessary.

I don't want to use Expo. I want to access one or two of the community-favourite modules without having to use and setup the entire Expo ecosystem in the application. It's arguably irrelevant to this specific ticket but this is an issue I'm facing, that's nothing to do with the SecureStorage module and has wasted my time trying to try the several fixes above and find the "not quite the worst" solution.

**Comment by brentvatne** [comment] 2022-06-10 10:21
the expo package installs the module system that this is built on and a few common dependencies that you can opt out of if you like. it doesn’t install the whole ecosystem. we build and maintain many modules and so there are a variety of reasons why we choose to do this on top of our own module system.

if you would like to help with this issue please share a minimal reproducible example.

**Comment by mcrstudio** [comment] 2022-06-10 10:23
@brentvatne Yeah, I get that. I let my frustration take over my logical thinking. I've revoked the previous comments, apologies for the abrupt approach.

**Comment by brentvatne** [comment] 2022-06-10 10:27
it happens. i hope we can get to the bottom of this so others don’t have to experience the same!

**Comment by WNemencha** [comment] 2022-06-30 07:26
Got that (almost) same issue today; here's the full report from XCode in case it may help troubleshoot this

<details>
  <summary>Click to enlarge the stacktrace:</summary>
  <pre>

Showing Recent Messages
Cycle in dependencies between targets 'Expo' and 'ExpoModulesCore'; building could produce unreliable results. This usually can be resolved by moving the target's Headers build phase before Compile Sources.
Cycle path: Expo → ExpoModulesCore → Expo
Cycle details:
→ Target 'Expo': Libtool /Users/wnemencha/Library/Developer/Xcode/DerivedData/MyApp-xxxx/Build/Products/Debug-iphoneos/Expo/libExpo.a normal
○ Target 'Expo' has target dependency on Target 'ExpoModulesCore'
○ That command depends on command in Target 'ExpoModulesCore': script phase “Copy generated compatibility header”
→ Target 'ExpoModulesCore' has compile command with input '/Users/wnemencha/Dev/MyApp/node_modules/expo-modules-core/ios/EXAppDefines.m'


Raw dependency cycle trace:

target:  ->

node: <all> ->

command: <all> ->

node: /Users/wnemencha/Library/Developer/Xcode/DerivedData/MyApp-xxxx/Build/Products/Debug-iphoneos/Expo/libExpo.a ->

command: target-Expo-8699adb1dd336b26511df848a716bd42a25b62413967ce2e85dd322deda890fa-:Debug:Libtool /Users/wnemencha/Library/Developer/Xcode/DerivedData/MyApp-xxxx/Build/Products/Debug-iphoneos/Expo/libExpo.a normal ->

node: /Users/wnemencha/Library/Developer/Xcode/DerivedData/MyApp-xxxx/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Expo.build/Objects-normal/arm64/EXAppDefinesLoader.o ->

command: target-Expo-8699adb1dd336b26511df848a716bd42a25b62413967ce2e85dd322deda890fa-:Debug:CompileC /Users/wnemencha/Library/Developer/Xcode/DerivedData/MyApp-xxxx/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Expo.build/Objects-normal/arm64/EXAppDefinesLoader.o /Users/wnemencha/Dev/MyApp/node_modules/expo/ios/EXAppDefinesLoader.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler ->

node: <target-Expo-8699adb1dd336b26511df848a716bd42a25b62413967ce2e85dd322deda890fa--begin-compiling> ->

command: Gate target-Expo-8699adb1dd336b26511df848a716bd42a25b62413967ce2e85dd322deda890fa--begin-compiling ->

node: <target-ExpoModulesCore-8699adb1dd336b26511df848a716bd424adf7a56d3940c17ada4a48d64c7dc78--modules-ready> ->

command: Gate target-ExpoModulesCore-8699adb1dd336b26511df848a716bd424adf7a56d3940c17ada4a48d64c7dc78--modules-ready ->

CYCLE POINT ->

node: /Users/wnemencha/Library/Developer/Xcode/DerivedData/MyApp-xxxx/Build/Products/Debug-iphoneos/ExpoModulesCore/ExpoModulesCore.modulemap ->

command: target-ExpoModulesCore-8699adb1dd336b26511df848a716bd424adf7a56d3940c17ada4a48d64c7dc78-:Debug:PhaseScriptExecution Copy generated compatibility header /Users/wnemencha/Library/Developer/Xcode/DerivedData/MyApp-xxxx/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ExpoModulesCore.build/Script-33455739B9B865188D939E1A4514CBD3.sh ->

node: /Users/wnemencha/Library/Developer/Xcode/DerivedData/MyApp-xxxx/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ExpoModulesCore.build/Script-33455739B9B865188D939E1A4514CBD3.sh ->

command: target-ExpoModulesCore-8699adb1dd336b26511df848a716bd424adf7a56d3940c17ada4a48d64c7dc78-:Debug:WriteAuxiliaryFile /Users/wnemencha/Library/Developer/Xcode/DerivedData/MyApp-xxxx/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ExpoModulesCore.build/Script-33455739B9B865188D939E1A4514CBD3.sh ->

node: <target-ExpoModulesCore-8699adb1dd336b26511df848a716bd424adf7a56d3940c17ada4a48d64c7dc78--phase1-compile-sources> ->

command: Gate target-ExpoModulesCore-8699adb1dd336b26511df848a716bd424adf7a56d3940c17ada4a48d64c7dc78--phase1-compile-sources ->

node: /Users/wnemencha/Library/Developer/Xcode/DerivedData/MyApp-xxxx/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ExpoModulesCore.build/Objects-normal/arm64/EXAppDefines.o ->

command: target-ExpoModulesCore-8699adb1dd336b26511df848a716bd424adf7a56d3940c17ada4a48d64c7dc78-:Debug:CompileC /Users/wnemencha/Library/Developer/Xcode/DerivedData/MyApp-xxxx/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ExpoModulesCore.build/Objects-normal/arm64/EXAppDefines.o /Users/wnemencha/Dev/MyApp/node_modules/expo-modules-core/ios/EXAppDefines.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler ->

node: /Users/wnemencha/Library/Developer/Xcode/DerivedData/MyApp-xxxx/Build/Products/Debug-iphoneos/ExpoModulesCore/ExpoModulesCore.modulemap
  </pre>
</details>

**Comment by Tonytodo24** [comment] 2022-07-21 05:40
> 

I've Nothing Else To Say But Thank You. I can't figure out on what else to say. But I want to thank you for everything. Since i've suffered from this error all morning.
Yes the problem is Pods file.

**Comment by Tonytodo24** [comment] 2022-07-21 05:41
> > I'm having same issue and none of the above solutions worked for me. XCode 13.1.
> 
> `cd ios && rm -rf Pods && pod install && cd ..` helped for me for some reason. Maybe someone will find it useful

I've Nothing Else To Say But Thank You. I can't figure out on what else to say. But I want to thank you for everything. Since i've suffered from this error all morning.
Yes the problem is Pods file.

**Comment by challme28** [comment] 2022-08-31 20:53
- `npx react-native-clean-project`
- `(cd ios && pod deintegrate && pod install)`
You may use any of those commands once you've installed the library. They some times fix the issue, they some times not.
At the end of the day, resetting all changes worked.
It had not work previously but it did just now. Imo, this is what we get when a framework is still in beta for so many years.

**Comment by brentvatne** [comment] 2022-11-26 02:33
to summarize - if you encounter this error, you may need to clear and reinstall pods.

**Closed by brentvatne** 2022-11-26 02:33 UTC
Labels: needs review
