### ISSUE TITLE
[Expo-In-App-Purchase] Android Multiple calls of setPurchaseListener's callback for Subscriptions

### ISSUE THREAD

**Issue by dorapax-lab** [expo/expo#14389] opened 2021-09-12 13:08 UTC
### Summary

Any async method inside `setPurchaseListener` is calling more than one time (multiple times) after a test subscription.

When I do a test subscription first time `testAsyncMethod()` only calls once (correct behaviour). But after 5 minutes (since it is a test subscription) subscription got cancelled and again try to do the subscription `testAsyncMethod()` calls twice and so on, (next time it is thrice and so on).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.5 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.17.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: bare

**"expo-in-app-purchases": "^11.0.1",**

### Reproducible demo or steps to reproduce from a blank project

```
InAppPurchases.setPurchaseListener(
      ({ responseCode, results, errorCode }) => {
        // Purchase was successful
        if (responseCode === InAppPurchases.IAPResponseCode.OK) {
          results.forEach(async (purchase) => {
            if (!purchase.acknowledged) {
              await testAsyncMethod()

              // finish the transaction on platform's end
              InAppPurchases.finishTransactionAsync(purchase, true)
            }
          })

          // handle particular error codes
        } else if (
          responseCode === InAppPurchases.IAPResponseCode.USER_CANCELED
        ) {
          console.log('User canceled the transaction')
        } else if (responseCode === InAppPurchases.IAPResponseCode.DEFERRED) {
          console.log(
            'User does not have permissions to buy but requested parental approval (iOS only)'
          )
        } else {
          console.warn(
            `Something went wrong with the purchase. Received errorCode ${errorCode}`
          )
        }
      }
    )


const testAsyncMethod = async() => {
     console.log('to test the number of calling times')
}
```

**Comment by cruzach** [comment] 2021-09-13 13:52
duplicate of https://github.com/expo/expo/issues/11432

**Closed by cruzach** 2021-09-13 13:52 UTC
Labels: needs review
