### ISSUE TITLE
Expokit : Empty ios/user/Supporting/shell-app-manifest.json file generates error while archiving

### ISSUE THREAD

**Issue by wpconsulate** [expo/expo#1993] opened 2018-07-15 17:07 UTC
I have an CRNA project which is detached and being developed with expokit. the iOS project files are generated by expo.  App runs fine on My Phone when I connect my Phone and runs fine on emulator as well. No Build Error is there. I'm trying to export .ipa file in XCode, for that when i archiving the project I'm getting the following error:

> ~/Desktop/Projects/iosproject ~/Desktop/Projects/iosproject/ios
> [22:22:40] Error reading the manifest file. Make sure the path '/Users/apple/Desktop/Projects/iosproject/ios/iosproject/Supporting/shell-app-manifest.json' is correct.
> 
> Error: Unexpected end of JSON input
> [22:22:40] Set EXPO_DEBUG=true in your env to view the stack trace.
> Command /bin/sh failed with exit code 1

When I checked the file (ios/user/Supporting/shell-app-manifest.json)  contents it's an empty file.

  
### Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.1.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/iterationgroup-b787bafe-7514-43d5-a18e-93a1e9030be3.tar.gz

### Steps to Reproduce
create a CRNA project detach it from expo "exp detact" and try archiving the project.

### Expected Behavior
it should work fine and build the project archive.

**Comment by epologee** [comment] 2018-07-16 13:53
Same here. We seem to get past this by putting empty JSON braces `{}` in the file. But I have no idea what the file is actually for... 😬

**Comment by blackberry4311** [comment] 2018-07-18 08:58
@lilosir u save my day man

**Comment by esamelson** [comment] 2018-07-18 23:57
@lilosir is right -- you need to run `exp publish` at least once before archiving your project.

I'm going to close this as I believe the issue is resolved.

**Closed by esamelson** 2018-07-18 23:57 UTC
Labels: project: turtle

**Comment by Dsantacruz** [comment] 2019-04-22 08:30
I could not export an apk, because first I must run : expo publish
