### ISSUE TITLE
Expo: App entry not found, after update sdk 52

### ISSUE THREAD

**Issue by MYT-2024** [expo/expo#32861] opened 2024-11-13 12:28 UTC
### Minimal reproducible example

k

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

Since adding expo go sdk 52, when I run my project in expo go, expo shows me this error message: 
App entry not found
The app entry point named "main" was not registered. This may be due to an uncaught error thrown from a module's top-level code. Refer to the CLI logs and the native device logs for more details.

![IMG_0445](https://github.com/user-attachments/assets/024aa21e-a119-4fa0-80d3-148dc7a95b32)

in my package.json file here is the app entry:  "main": "expo/AppEntry.js",
which worked until the update

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 13.6.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.11.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 10.9.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /Users/chriscal/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.4 => 52.0.4 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 12.6.2
      expo-cli: 6.3.12
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
• Field: ios - should NOT have additional property 'useDeviceToken'.

Expected package @expo/config-plugins@~9.0.0
Found invalid:
  @expo/config-plugins@4.1.5
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions.

The following issues were found when validating your dependencies against React Native Directory:
Unsupported on New Architecture: @react-native-community/checkbox, react-native-image-crop-picker
Untested on New Architecture: react-native-phone-input
Unmaintained: react-native-deck-swiper, react-native-modal, react-native-phone-input
No metadata available: @expo/config-plugins, @expo/metro-runtime, axios, expo-checkbox, expo-google-app-auth, socket.io-client, typescript
Advice: 
- Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
- Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
```

**Comment by Blasci** [comment] 2024-11-13 14:09
Same issue here...

**Comment by usmansbk** [comment] 2024-11-13 15:07
Try add an `index.ts` file to your root folder with the following code:
```js
import { registerRootComponent } from "expo";

import App from "./App";

// registerRootComponent calls AppRegistry.registerComponent('main', () => App);
// It also ensures that whether you load the app in Expo Go or in a native build,
// the environment is set up appropriately
registerRootComponent(App);
```

then update your package.json:

```json
  "main": "index.ts",
```

**Comment by zsomborgellerfi** [comment] 2024-11-13 15:29
Same issue

**Comment by JustJoostNL** [comment] 2024-11-13 15:31
Could be related to #32587?

**Comment by MYT-2024** [comment] 2024-11-13 15:40
> Try add an `index.ts` file to your root folder with the following code:
> 
> ```js
> import { registerRootComponent } from "expo";
> 
> import App from "./App";
> 
> // registerRootComponent calls AppRegistry.registerComponent('main', () => App);
> // It also ensures that whether you load the app in Expo Go or in a native build,
> // the environment is set up appropriately
> registerRootComponent(App);
> ```
> 
> then update your package.json:
> 
> ```json
>   "main": "index.ts",
> ```

I tried it, it didn't change anything

**Comment by usmansbk** [comment] 2024-11-13 15:49
Then one of your packages is blocking it. For me it was react-native-mmkv

**Comment by zsomborgellerfi** [comment] 2024-11-13 15:51
I got this resolved by updating our sentry configs based on this:
https://docs.sentry.io/platforms/react-native/tracing/instrumentation/react-navigation/

**Comment by schriker** [comment] 2024-11-13 20:27
I'm also having this issue. I'm also using sentry. Also check eas build and it is failing at uploading source maps to sentry.

**Comment by bitmaxsuporte** [comment] 2024-11-13 21:20
Same issue

**Comment by floresvfer** [comment] 2024-11-13 21:39
Same issue

**Comment by floresvfer** [comment] 2024-11-13 22:20
After updating to the new Expo SDK, I encountered this issue due to a library that is no longer supported with the new architecture. In my expo.json configuration file, I explicitly set it to not use the new architecture:
```json
{
  "experiments": {
    "newArchitecture": false
  }
}
```
However, the app kept crashing. After reviewing all deprecated libraries, I found that the issue was caused by `expo-barcode-scanner`, which Expo no longer supports in SDK52.

What really helped me identify the problem was running the app on Android, where the error messages were much clearer and more explicit. On the other hand, in iOS, I only got a generic message:

`App entry not found`

I hope this information helps others facing a similar issue when updating their Expo projects.

> Same issue

**Comment by brentvatne** [comment] 2024-11-13 22:47
hey folks, it looks like what is happening here is there is an error in your app but it's not being surfaced due to a regression in error reporting in react-native 0.76: https://github.com/facebook/react-native/pull/47287 - this will be fixed in 0.76.2.

**Comment by disolaterX** [comment] 2024-11-14 06:17
this is also coming up, any idea I am one new latest "expo": "~52.0.6", "expo-router": "~4.0.5"

ERROR  node_modules/expo-router/_ctx.ios.js: node_modules/expo-router/_ctx.ios.js:Invalid call at line 2: process.env.EXPO_ROUTER_APP_ROOT
First argument of `require.context` should be a string denoting the directory to require

**Comment by AndrianarivoAlpha** [comment] 2024-11-14 08:16
Same issue

**Comment by jophuijbers-wf** [comment] 2024-11-14 12:31
In my case it was the package [react-native-smartlook-analytics](https://www.npmjs.com/package/react-native-smartlook-analytics)

**Comment by Hiba-Bazerbashi** [comment] 2024-11-14 17:23
the same , is there any temporary fix to work this out

**Comment by Hiba-Bazerbashi** [comment] 2024-11-14 17:38
> In my case it was the package [react-native-smartlook-analytics](https://www.npmjs.com/package/react-native-smartlook-analytics)

how did you catch the error???

**Comment by Roshan0511** [comment] 2024-11-15 05:19
Did anyone resolved this error?

**Comment by Roshan0511** [comment] 2024-11-15 11:51
Hey folks, I found the solution of this error, hope this will help you out too.

- Run this command in terminal to fix all the dependencies for Expo 52. 
`` npx expo install expo@^52.0.0 --fix ``
- Then use this command for check, if there any issue still present in the project or not
`` npx expo-doctor@latest ``

These two commands will help you out to identify the issues.

Thanks.

**Comment by Hiba-Bazerbashi** [comment] 2024-11-15 18:16
> Hey folks, I found the solution of this error, hope this will help you out too.
> 
> * Run this command in terminal to fix all the dependencies for Expo 52.
>   `npx expo install expo@^52.0.0 --fix`
> * Then use this command for check, if there any issue still present in the project or not
>   `npx expo-doctor@latest`
> 
> These two commands will help you out to identify the issues.
> 
> Thanks.

hey @Roshan0511 have you already solved the issue with this commands??

**Comment by brentvatne** [comment] 2024-11-15 21:09
hello! please ensure you are updated to the latest version of the expo package and react-native. errors were being swallowed by react-native in 0.76.0 and 0.76.1 but were fixed in 0.76.2. see: https://github.com/facebook/react-native/pull/47287

**Comment by brentvatne** [comment] 2024-11-15 21:10
if your issue persists with react-native 0.76.2, please create a new issue and share a minimal repro. thanks!

**Closed by brentvatne** 2024-11-15 21:09 UTC
Labels: needs review

**Comment by Roshan0511** [comment] 2024-11-16 10:51
> > Hey folks, I found the solution of this error, hope this will help you out too.
> > 
> > * Run this command in terminal to fix all the dependencies for Expo 52.
> >   `npx expo install expo@^52.0.0 --fix`
> > * Then use this command for check, if there any issue still present in the project or not
> >   `npx expo-doctor@latest`
> > 
> > These two commands will help you out to identify the issues.
> > Thanks.
> 
> hey @Roshan0511 have you already solved the issue with this commands?? it didn't work for me and same error in expo doctor

Yes, this worked for me.
May I know what error are showing when you run `npx expo-doctor@latest` command?

**Comment by Hiba-Bazerbashi** [comment] 2024-11-16 13:10
@Roshan0511 
> Yes, this worked for me. May I know what error are showing when you run `npx expo-doctor@latest` command?

`
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
Unmaintained: redux-persist
No metadata available: @babel/plugin-proposal-export-namespace-from, @expo/config-plugins, @expo/metro-runtime, @expo/ngrok, @hookform/error-message, @hookform/resolvers, @reduxjs/toolkit, cross-fetch, fast-text-encoding, firebase, jest-fetch-mock, mime, moment, react-native-elements, react-redux, react-test-renderer, yup, yup-password, yup-phone-lite
Advice: 
- Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
- Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
`
and when run my app on android device ,i get this vague error :
` ERROR  TypeError: Cannot read property 'EventEmitter' of undefined, js engine: hermes ` .

I already have 0.76.2 @brentvatne

**Comment by brentvatne** [comment] 2024-11-16 18:24
@Hiba-Bazerbashi - the error you are seeing is not what this issue is about. you should use your typical approach to debugging to determine what the cause is. if you're stuck, try https://expo.fyi/manual-debugging
