### ISSUE TITLE
[ios14][home] Stop polling Clipboard, replace with intentional UI

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#9087] opened 2020-07-03 19:35 UTC
Currently we poll for clipboard changes every 2000ms when the projects screen is active, in order to display a button to press to open a URL from clipboard: https://github.com/expo/expo/blob/3bfa490507a04055183e36b99820d099c8f97f96/home/components/ProjectTools.js

We should re-design this feature so the user explicitly opts-in to having their clipboard read from. Exactly how this looks is up to the implementor.

**Comment by tsapeta** [comment] 2020-07-03 20:13
Duplicate of #9028 😛 I already created a bunch of iOS 14 related stuff

**Closed** 2020-07-03 20:35 UTC
Labels: home
