### ISSUE TITLE
Can't create a working ios release build for ejected app.

### ISSUE THREAD

**Issue by edwardchen** [expo/expo#7798] opened 2020-04-10 17:44 UTC
## 🐛 Bug Report
I've already run expo publish. I think my manifest file may be invalid. How can I debug this and figure out what's causing the issue? It works just fine in "debug" configuration.

### Environment

  Expo CLI 3.17.21 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.11.0 - ~/.nvm/versions/node/v13.11.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.7 - ~/.nvm/versions/node/v13.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.3
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      react-navigation: ^2.18.2 => 2.18.3
    npmGlobalPackages:
      expo-cli: 3.17.21

### Steps to Reproduce

Creating release build in xcode.

### Expected Behavior

App doesn't crash on startup.

### Actual Behavior

App crashes on startup with this error in xcode.

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The embedded manifest is invalid. If you are making a release build for the first time, make sure you have run `expo publish` at least once.'

**Comment by cruzach** [comment] 2020-04-10 19:40
After publishing, did you add the generated files to  our Xcode project (`ios/<your-project-name>/Supporting/app.manifest` and `ios/<your-project-name>/Supporting/app.bundle` [as it says in the docs](https://github.com/expo/expo/tree/master/packages/expo-updates#embed-an-initial-update)?

**Comment by edwardchen** [comment] 2020-04-10 19:59
Hmm, yeah they're there under Supporting in xcode.

Looking at the code, wouldn't it show this message if the manifest doesn't exist?
> The embedded manifest is invalid or could not be read. Make sure you have created app.manifest and app.bundle files and added them to your Xcode project. If you are using Expo CLI, make sure you have run `expo publish` or `expo export` at least once. More information at https://expo.fyi/embedded-assets

**Comment by brentvatne** [comment] 2020-04-10 20:17
@edwardchen - can you share your app.json?

**Comment by edwardchen** [comment] 2020-04-10 20:20
Here it is:

{
  "expo": {
    "name": "eaterpad",
    "description": "Nutrition Tracking Application",
    "slug": "eaterpad",
    "privacy": "public",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.1.7",
    "orientation": "portrait",
    "icon": "./assets/ios-logo.png",
    "scheme": "eaterpad",
    "splash": {
      "image": "./assets/ios-splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0,
      "enabled": false
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.eaterpad.eaterpad",
      "publishBundlePath": "ios/eaterpad/Supporting/shell-app.bundle",
      "publishManifestPath": "ios/eaterpad/Supporting/shell-app-manifest.json",
      "appStoreUrl": "https://apps.apple.com/us/app/eaterpad/id1435737620?ls=1",
      "infoPlist": {
        "UIUserInterfaceStyle": "Light"
      }
    },
    "android": {
      "package": "com.eaterpad.eaterpad",
      "versionCode": 31,
      "permissions": [
        "com.android.vending.BILLING",
        "CAMERA",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE"
      ],
      "playStoreUrl": "https://play.google.com/store/apps/details?id=com.eaterpad.eaterpad",
      "publishBundlePath": "android/app/src/main/assets/shell-app.bundle",
      "publishManifestPath": "android/app/src/main/assets/shell-app-manifest.json"
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "eaterpad",
            "project": "eaterpad",
            "authToken": "5cb91f052b6c4de18667f1e33980a3cab2887c13010f4d7dad44ed154ff0903e"
          }
        }
      ]
    },
    "entryPoint": "node_modules/expo/AppEntry.js"
  },
  "displayName": "eaterpad",
  "name": "eaterpad"
}

**Comment by esamelson** [comment] 2020-04-10 20:29
hey @edwardchen -- looks like you're migrating to the bare workflow from ExpoKit, is that correct? could you try removing the `publishBundlePath` and `publishManifestPath` keys from your app.json and re-publishing?

**Comment by edwardchen** [comment] 2020-04-10 20:40
yup migrating to bare from expokit.

seems like removing publishBundlePath and publishManifestPath doesn't fix the issue.

**Comment by esamelson** [comment] 2020-04-10 20:57
hmm ok, after removing those keys and rerunning `expo publish`, what are the contents of your app.manifest file?

**Comment by edwardchen** [comment] 2020-04-10 21:03
app.manifest is just this:

{}

**Comment by edwardchen** [comment] 2020-04-10 21:13
My shell-app-manifest.json and shell-app.bundle have contents though. Is that supposed to be in app.manifest and app.bundle instead?

If I copy that over into app.manifest and app.bundle, I get the error that superbright reported here:
https://forums.expo.io/t/it-is-necessary-to-run-expo-publish-in-order-to-generate-a-production-build/35360/5?u=edwardchen

2020-04-10 18:05:17.460983+0300 collect[8448:2356523] *** Terminating app due to uncaught exception ‘NSInvalidArgumentException’, reason: '* -[NSFileManager copyItemAtPath:toPath:options:error:]: source path is nil’**

not sure how any of this is supposed to work but trying to figure it out.

**Comment by esamelson** [comment] 2020-04-10 22:37
@edwardchen - hmm, the fact that app.manifest is empty, even after removing those keys from app.json and running `expo publish`, suggests that you aren't running the most up-to-date expo-cli. Could you make sure that you are running the latest expo-cli (3.17.21 at the time of writing this)?

After running `expo publish`, app.manifest should be a non-empty JSON object with a bunch of metadata about your app -- including a list of assets that should be bundled with the app. The "Bundle Expo Assets" build step should insert those assets into the binary at build-time, and that's the assertion that seems to be failing. Updating to the latest expo-cli should do the trick -- I'm trying to repro this right now, as well, though!

**Comment by edwardchen** [comment] 2020-04-10 22:42
Yeah it's weird that it's empty. running expo publish doesn't appear to create anything. Maybe there's a silent error or something?

I believe I'm running expo-cli 3.17.21. It says so in the "environment section" of my initial post. (output of expo diagnostics). I'm trying to figure out what's going happening.

**Comment by esamelson** [comment] 2020-04-10 23:02
ahh -- do you have the `expokit` package still listed in your package.json, by chance? If so, try removing that and then running `expo publish`.

**Comment by edwardchen** [comment] 2020-04-10 23:13
yep that was it. thanks for the help!

**Comment by Andruschenko** [comment] 2020-04-13 22:21
I ejected from the **managed workflow** to the **bare workflow** and I get the exact same error when trying a release build on **iOS**. 
My release builds on **Android** also crash immediately. There I can observe the error `E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2` in Android Logcat after running `react native --variant=release`.

My `ios/<your-project-name>/Supporting/app.manifest` as well as my `ios/<your-project-name>/Supporting/app.bundle` are just `{}` - two empty objects.

I read through all of the discussion here - I don't have any `publishBundlePath` nor `publishManifestPath` in my `app.json` and of course no `expokit` package in my `package.json`.

Perhaps my problem is worth a separate issue?!

**Comment by adamsolomon1986** [comment] 2020-04-14 19:52
expo is killing me after ejecting. It's like a crazy ex that doesn't want to leave you alone.

**Comment by brentvatne** [comment] 2020-04-14 20:12
@adamsolomon1986 - what do you mean? if you don't want to use expo-updates then follow the instructions on https://github.com/expo/expo/blob/master/packages/expo-updates/README.md in reverse to remove it from your app. then all you have left is a vanilla react-native app

**Comment by brentvatne** [comment] 2020-04-14 20:26
@Andruschenko - sorry for the confusion! we just released expo-updates a couple of weeks ago and in some cases the workflow isn't as ergonomic or clear as it could be.

## what currently happens

if you have not published yet, you will see this in your logs when you run a release build on ios:

```
2020-04-14 13:16:20.854086-0700 app[12622:156506] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The embedded manifest is invalid. If you are making a release build for the first time, make sure you have run `expo publish` at least once.'
```

if you have not published yet, you will see this in your logs when you run a release build on android:

*no useful error is shown*

## what we are working on

we are investigating changing expo-updates such that a bundle is created at the time when a build is performed, rather than requiring you to publish beforehand. @esamelson is working on this now.

## how we will improve the clarity around the current process of creating release builds

- we have added a warning if users have `expokit` and `expo-updates` in the same project, because they are incompatible (https://github.com/expo/expo-cli/commit/2c0176b297ea1d66c976a98bdd3ebb420927709d) - this is the problem that led to this particular issue being created.
- we will add some information on eject about publishing before release builds.

<hr />

to address your questions specifically:

1. yes
2. we recently decided that they should indeed be left out of the gitignore (https://github.com/expo/expo/commit/6c58775625b3b86764c54a6c70601c8c9ea0c68c) and templates were updated accordingly. so, feel free to remove those lines in your project

**Comment by Andruschenko** [comment] 2020-04-14 20:50
@brentvatne Thanks for your elaborate reply and @esamelson and your efforts to make the transition to the bare workfllow smoother.

The reason I spent 2 days on this is because I was first only attempting a release build on Android. 
Since I got very irritating errors I first suspected the issue to be unrelated to Expo and spent a lot of time of trying different fixes. When I finally attempted a release build on iOS, I quickly got to this issue here which helped me to finally resolve it - that being said, thanks for adding some information on eject about publishing before release builds.

I really enjoyed the managed workflow experience of Expo and am looking forward to using the bare workflow after this first hick-up. Keep up the great work!

**Comment by brentvatne** [comment] 2020-04-14 20:55
@Andruschenko - my bad, we actually do show a relevant error on android -- i can see why you would have missed it though because i did too. android logs scroll by so fast 😅

**Comment by nmelentjevs** [comment] 2020-04-17 10:19
I am experiencing the same issues and have been unable to fix that by updating expo-cli. I don't have expokit in my package.json either.

Env:
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 2.99 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: ~0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1

Still getting 

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The embedded manifest is invalid.` Error

**Comment by bfarrgaynor** [comment] 2020-04-30 21:14
I'm experiencing a similar issue. Empty manifest file. No expokit in package.json and expo-cli@3.20.1

**Comment by brentvatne** [comment] 2020-04-30 21:15
did you run `expo publish`?

if so, look for `app.manifest` in your ios directory and see where it ended up. it's possible that you renamed your project or somehow ended up in a state where the ios project files are not where expo-cli expects them to be

**Comment by bfarrgaynor** [comment] 2020-04-30 21:16
Yes I did. I have an empty manifest file {}

**Comment by bfarrgaynor** [comment] 2020-04-30 21:30
Wait I think you are right about the app renaming thing.

**Comment by brentvatne** [comment] 2020-04-30 23:51
what did you find?

**Comment by bfarrgaynor** [comment] 2020-04-30 23:55
My project name was changed in my app.json which meant that expo publish was creating a folder with that name and putting the manifest in there instead of the original package name of my XCode project. Changing the app.json name back to the old one did the trick and I was able to simply change my project name in XCode.

**Comment by bfarrgaynor** [comment] 2020-04-30 23:58
PS I wanted to thank you for your active support on this and your follow up. I don't know if you guys are on payroll or not but we really appreciate this project/package. Please keep up the great work.

**Comment by brentvatne** [comment] 2020-05-01 00:08
thank you for following up! we're working on some changes that will get rid of the need to create app.bundle and app.manifest and publish priority to doing a build, so that should eliminate this problem entirely for people i hope!

i'll close the issue as we've documented that it's necessary to run `expo publish` before doing a build currently, provided warnings around that, and folks can read this thread if they end up in a similar situation as yours with a renamed project @bfarrgaynor :)

**Closed by brentvatne** 2020-05-01 00:08 UTC
Labels: Bare Workflow, Updates, status: needs more info

**Comment by nmelentjevs** [comment] 2020-05-02 10:19
I've tried everything mentioned and still get:
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The embedded manifest is invalid. If you are making a release build for the first time, make sure you have run `expo publish` at least once.'

I have updated to the latest expo-cli version and ran expo publish again, however, still works in debug build and not the release.

**Comment by bfarrgaynor** [comment] 2020-05-02 12:07
Have a look in your iOS folder to see if it made a new folder with your projects name, that's what mine did, it put the manifest file in there. If you've renamed your project at some point it will do that. The fix is to rename your project back to its old name in app.json and run expo publish again. Then try to build.

Sent from mobile. Please excuse brevity.

________________________________

**Comment by nmelentjevs** [comment] 2020-05-03 13:52
I did indeed change to a new name and now changed it back, ran expo publish again, yet the error persists. I have also tried creating a brand new expo init project and ejecting then publishing and the same error occurs.

**Comment by bfarrgaynor** [comment] 2020-05-03 13:58
Close your xcode and reopen it, run a build clean

Sent from mobile. Please excuse brevity.

________________________________

**Comment by nmelentjevs** [comment] 2020-05-03 14:20
Reopened, cleaned build, still the same error. I have no idea where I may be doing something wrong

**Comment by nmelentjevs** [comment] 2020-05-03 14:28
The Xcode traces this error to expo updates embedded manifest error

**Comment by bfarrgaynor** [comment] 2020-05-03 17:56
Is your manifest file empty?

Sent from mobile. Please excuse brevity.

________________________________

**Comment by nmelentjevs** [comment] 2020-05-03 18:02
My shell-app-manifest.json and shell-app.bundle are successfully generated, however app.bundle and app.manifest are empty

**Comment by bfarrgaynor** [comment] 2020-05-03 18:09
Do you see any folders in your iOS folder with a manifest and bundle in them? Like check the sub folders, expand them all.

Sent from mobile. Please excuse brevity.

________________________________

**Comment by nmelentjevs** [comment] 2020-05-03 18:31
The only folder with manifest and bundle is iOS/<projectname>/Supporting with shell-app-manifest.json, shell-app.bundle, empty app.bundle and {} in app.manifest. I don't see any bundle or manifest files elsewhere.

**Comment by bfarrgaynor** [comment] 2020-05-03 20:53
Check through finder or terminal and not xcode

Sent from mobile. Please excuse brevity.

________________________________

**Comment by KangKY** [comment] 2020-05-06 09:15
I had the same problem. ( app.manifest invalid. just {} )

In my case, I solved by checking manifest URL.
After "expo push" command, you will see the phrase below.
"The manifest URL is: https://exp.host/@[YOUR-ID]/[YOUR-APP-SLUG] (​https://exp.host/@[YOUR-ID]/[YOUR-APP-SLUG]/index.exp?sdkVersion=37.0.0​). Learn more. (​https://expo.fyi/manifest-url​)"

Enter the url in the browser and check if the json content exists.
(If it is not shown unfortunately, please check the URL again.)
Copy json string and paste to "app.manifest" file.

Finally, enter the "gradlew assembleRelease" and BUILD SUCESS.

**Comment by nmelentjevs** [comment] 2020-05-06 09:17
I have fixed my issue by removing app bundle and manifest paths from app.json. Now it works as intended after expo publish

**Comment by thedarkcder** [comment] 2020-05-08 01:22
The url produced for the app manifest is wrong - its missing the ":' - its produces "http//"

**Comment by bureyburey** [comment] 2020-05-09 10:01
i had a somewhat similar/related issue:
each time i tried make an android build **without using expo publish** the generated apk was outdated (it generated the version that was last created by running **expo publish**)

a workaround i did in order to avoid running **expo publish** before each build was this:

1) generate the index.android file by running:
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

2) remove app.bundle (which is generated by **expo publish** in the folder /
android/app/src/main/assets

3) make a copy of **index.android.bundle** (in the same folder) and rename it to **app.bundle**

4) run **./gradlew assembleRelease** from /android folder

at the moment i am doing this manually, but the process can easily be automated.

hopefully this helps anyone who encountered something similar.
