### ISSUE TITLE
Is it working for RN 0.61

### ISSUE THREAD

**Issue by lucasriondel** [expo/expo#5859] opened 2019-10-03 16:07 UTC
I have updated my bare app from 0.59 to 0.61 and my expo features are not working anymore. I am using expo-barcode-scanner and expo-image picker 7.0 but they doesn't seem to do anything.

The barcode scanner freezes the app when launched, and the image picker's `launchCameraAsync` is not launching either but doesn't freeze the app at least (and permissions are asked) on android.

Is Expo compatible with 0.61 ? When using expo-cli and creating a new project, it installs the 0.59.10 version of RN.

**Comment by cruzach** [comment] 2019-10-03 17:11
duplicate of #5858

**Closed by cruzach** 2019-10-03 17:11 UTC
