### ISSUE TITLE
[expo-image] Android: image not loaded after app launched from recents 

### ISSUE THREAD

**Issue by Artem-Kalugin** [expo/expo#22100] opened 2023-04-12 15:04 UTC
### Minimal reproducible example

https://github.com/Artem-Kalugin/expo-image-android-not-loaded-minimal-example

### Summary
- The problem reproducible at least on XIaomi Redmi 9/Redmi 7 note with Android 10, both development and release builds.
- The problem **isn't** reproducible on  emulated Galaxy Fold with android 13.
- Reproducible for both local and remote images.

After fresh install of expo+expo-image into bare react native project bug with unloaded image occurs.

How to reproduce: 
1. Place image somewhere in the app, make it visible
2. Press hardware back button/do exit app gesture
3. Reopen app again (make sure that it wasn't unloaded and resumes from previous point)

https://user-images.githubusercontent.com/40625262/231502228-c5baa9c0-8422-4f9e-857e-59439e8a64e7.mp4

### Environment

```
 System:
      OS: macOS 13.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.5.0 - /opt/homebrew/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 9.3.1 - /opt/homebrew/bin/npm
      Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /Users/artemkalugin/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    Expo Workflow: bare
```

**Comment by RRaideRR** [comment] 2023-04-13 07:17
Also experienced that issue in the past! Glad you were able to reproduce

**Comment by lukmccall** [comment] 2023-04-17 10:36
Hi @Artem-Kalugin, thanks for your report. However, I'm not able to reproduce this issue. I don't have access to XIaomi Redmi 9 or Redmi 7. Could you provide a native log from your device? Also, can you try to reproduce this behavior with the newest version of the expo-image (1.1.0)?

**Comment by RRaideRR** [comment] 2023-04-17 11:00
@lukmccall it could be related to [my comment over here](https://github.com/expo/expo/issues/21921#issuecomment-1494767390).

As you can see in the video, first-time render works fine but further re-renders tend to often show only the placeholder.

**Comment by Artem-Kalugin** [comment] 2023-04-17 11:10
Hi @lukmccall

**Comment by Artem-Kalugin** [comment] 2023-04-17 11:13
Hi @lukmccall, logs in attach
Upgrading to 1.1.0 did not help
I also noticed that problem is also reproducible on emulated pixel 4 with android 10 
[logs.txt](https://github.com/expo/expo/files/11249449/logs.txt)

**Comment by lukmccall** [comment] 2023-04-17 13:38
> @lukmccall it could be related to [my comment over here](https://github.com/expo/expo/issues/21921#issuecomment-1494767390).
> 
> As you can see in the video, first-time render works fine but further re-renders tend to often show only the placeholder. I can reproduce this with all my different Android phones.

There are two separate issues, both of them should be fixed in the next version which should be released later that week. 

> Upgrading to 1.1.0 did not help
> I also noticed that problem is also reproducible on emulated pixel 4 with android 10

Thanks for attaching the logs. I think I was able to track down the root cause.

**Closed** 2023-04-17 13:52 UTC
Labels: Image, Issue accepted

**Comment by huytdps13400** [comment] 2023-04-30 18:49
Help me

**Comment by codexoft-ke** [comment] 2025-01-07 14:27
Me too have same error on development build the images work perfect but on realise the images are not showing

**Comment by innergap** [comment] 2025-01-13 14:49
Same here "expo-image": "~2.0.3"

**Comment by codexoft-ke** [comment] 2025-01-16 11:58
I resolved the issue by deleting the existing android/ios dir and prebuild project again all expo modules are working as usual

**Comment by mirik999** [comment] 2025-02-27 11:54
The same problem.
"expo-image": "~2.0.6"

**Comment by codexoft-ke** [comment] 2025-03-03 13:41
> The same problem. "expo-image": "~2.0.6"

Try by deleting android and ios folder the prebuild the project again

**Comment by aalapd** [comment] 2025-04-01 19:34
Can confirm it's happening on expo go and only affecting Android. iOS and web show images just fine.
