### ISSUE TITLE
Push notifications not delivered when Android device is back online

### ISSUE THREAD

**Issue by vandrieu** [expo/expo#4067] opened 2019-04-25 00:28 UTC
### Environment

Android Expo app receiving push notifications, either from backend or even from expo web push notifications tool (https://expo.io/dashboard/notifications).

### Steps to Reproduce

1. Create a dummy app and follow documentation to setup push notifications (https://docs.expo.io/versions/latest/guides/push-notifications/ + https://docs.expo.io/versions/latest/guides/using-fcm/).
1. Run your app on both an android device (not simulator) and an iOS device (not simulator)
1. Make sure both devices are online
1. Using expo push notifications tool (https://expo.io/dashboard/notifications), send a notification to both devices
1. Make sure both devices have received a notification
1. Put both devices offline 
1. Send a notification to both devices again
1. Stay offline for a few seconds (like 10 seconds)
1. Put both devices back online

### Expected Behavior

Going back online, both devices receive the notification.

### Actual Behavior

✅Going back online, iOS device receives the notification.
❌**Going back online, Android device does not receive the notification**.

Trying to isolate the problem, we have many layers here:
1. Backend sending the notification: I used expo notification tool, any issue here?
1. Expo <-> FCM communication: issue might be here
1. My Firebase/FCM setup: seems good because if I deliberately push a wrong key ("expo push:android:upload --api-key DUMMY") then the expo web push notifications tool says "InvalidCredentials: Failed to authenticate with the FCM server. Ensure the FCM server key you uploaded is correct." and if I put the right key from firebase, it does not say that, it show the green success tick.
1. FCM messaging engine: FCM docs say if the device is offline, they keep the message, waiting for device to go back online (max. wait time is 4 weeks). I think it works, as all apps I have on my android device do deliver my notifications each morning when I turn my smartphone on.
1. Expo SDK displaying the notification: I think that works, I think it just never receives it, but that's just a guess
1. My app / my code: not relevant, the app is doing nothing ("expo init" boilerplate)

Issue on layer 2?

**Comment by davidmargolin** [comment] 2019-04-26 18:43
Same issue here

**Comment by noxonsu** [comment] 2019-05-01 04:25
look same  https://stackoverflow.com/questions/43747169/android-firebase-push-notifications-are-not-delivered-after-coming-to-online-fro

**Comment by vandrieu** [comment] 2019-05-01 07:25
Hello Evan. This morning (just a few minutes ago for me, here in Europe), I switched airplane mode OFF when I woke up, my devices went online, and for the first time ever, I received on my Android device some notifications that have been emitted a few minutes/hours in the past (while I was offline) from my expo standalone app. Cool! Does it mean you finalized the fix?

**Comment by esamelson** [comment] 2019-10-15 19:30
Hi all -- I think this issue has the same root cause as this one https://github.com/expo/expo/issues/2194 and the fix was pushed to production on Apr 29, which lines up with the timing here. More details about the issue and the fix are in the linked issue if you're curious. It sounds like this is resolved so I'm going to go ahead and close this.

**Closed by esamelson** 2019-10-15 19:30 UTC
Labels: Notifications, project: android-runtime
