### ISSUE TITLE
ask permission window suddendly disappears iOS

### ISSUE THREAD

**Issue by MassimilianoCuccia** [expo/expo#2694] opened 2018-11-12 14:11 UTC
On Android it works, while I'm having some problems on **iOS**.

**The window asking user for permission is shown, but suddendly disappears.
The application is stuck and doesn't accept any input (even shake)** 
I have to kill the Expo Client task and start again.

This happens executing this line of code:
Permissions.askAsync(Permissions.CAMERA)
or even this
Permissions.askAsync(Permissions.NOTIFICATIONS);

"expo": "^29.0.0",
"react": "^16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz",

tested running package manager with
react-native-scripts start
and even with
exp start

testing on iPAD, expo client 2.9.0.103161

already seen issue #2130

Thanks for helping

**Comment by sjchmiela** [comment] 2018-11-21 10:44
Actually, we had a similar issue in our test app in Expo — Native Component List. We've managed to fix it by moving `Permissions.askAsync` from `componentDidMount()` method to a method called by `onFocus` navigation event (see https://github.com/expo/expo/commit/cdac009ed272b2c50b70f25c25c61f3de217a1d9). It seems this behavior was caused by a bug in `react-native-screens` fixed recently by https://github.com/kmagiera/react-native-screens/commit/f57223659cf5d296f865c327fbae3a4ddf40af71. Unfortunately, this commit isn't included in neither Expo Client nor standalone app templates, so we have to work around the bug. 🙂 

Are you asking for permission in `componentDidMount()`? If so, could you, please, move call it instead when the screen focuses and let me know if it helped?

**Comment by bbarthec** [comment] 2018-12-11 19:39
I've checked it out just now and it seems that it's already fixed.
Therefore I'm closing this issue tentatively as the problem seems to be resolved with upcoming sdk release.

**Closed by bbarthec** 2018-12-11 19:39 UTC
