### ISSUE TITLE
Expo Imagepicker crashing on Android but works on IOS

### ISSUE THREAD

**Issue by mohs1n** [expo/expo#3470] opened 2019-02-09 11:03 UTC
Hello!
I'm trying to use Expo Imagepicker along with AWS to store the images. Now the imagepicker works ok on IOS but on Android when I choose the image from the gallery it crashes the app and the app restarts. I'm attaching the code as well as versions below.
Versions:
Expo "sdkVersion": "29.0.0",
React native : "react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz",
Snack : https://snack.expo.io/@mohs1n/imagepickerissue
Android log :

> 2019-02-09 14:52:28.832 1838-1854/? I/ActivityManager: Start proc 27944:android.process.acore/u0a17 for content provider com.android.providers.contacts/.ContactsProvider2
> 2019-02-09 14:52:28.868 27944-27944/? E/d.process.acor: Not starting debugger since process cannot load the jdwp agent.
> 2019-02-09 14:52:35.547 1838-1851/? E/memtrack: Couldn't load memtrack module
> 2019-02-09 14:52:36.423 27723-27973/? E/ReactNativeJS: React Native version mismatch.

```
JavaScript version: 0.55.4
Native version: 0.57.1

Make sure that you have rebuilt the native code. If the problem persists try clearing the Watchman and packager caches with `watchman watch-del-all && react-native start --reset-cache`.
```
2019-02-09 14:52:40.537 27723-27993/? D/b: Got cached OkHttp response for https://exp.host/@exponent/home/bundle?versionName=2.10.4
2019-02-09 14:52:40.537 27723-27993/? D/b: Have cached source file for https://exp.host/@exponent/home/bundle?versionName=2.10.4
2019-02-09 14:52:41.384 1838-1854/? I/ActivityManager: Start proc 28012:com.android.chrome:webview_service/u0a81 for service com.android.chrome/org.chromium.android_webview.services.VariationsSeedServer
2019-02-09 14:52:41.467 28012-28012/? E/webview_servic: Not starting debugger since process cannot load the jdwp agent.
2019-02-09 14:52:41.518 1838-1851/? E/memtrack: Couldn't load memtrack module
2019-02-09 14:52:49.585 1838-1851/? E/memtrack: Couldn't load memtrack module
2019-02-09 14:52:54.070 1715-1773/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
2019-02-09 14:53:04.903 1838-1851/? E/memtrack: Couldn't load memtrack module
2019-02-09 14:53:11.758 1838-1851/? E/memtrack: Couldn't load memtrack module
2019-02-09 14:53:26.817 1838-2499/? I/ActivityManager: START u0 {act=android.intent.action.GET_CONTENT typ=image/* cmp=com.android.documentsui/.picker.PickActivity} from uid 10085
2019-02-09 14:53:27.123 1838-1851/? E/memtrack: Couldn't load memtrack module
2019-02-09 14:53:27.184 1838-1851/? E/memtrack: Couldn't load memtrack module
2019-02-09 14:53:27.195 27723-27848/? E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at [https://developers.facebook.com/docs/graph-api}](https://developers.facebook.com/docs/graph-api%7D)
2019-02-09 14:53:31.452 27723-27848/? E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at [https://developers.facebook.com/docs/graph-api}](https://developers.facebook.com/docs/graph-api%7D)
2019-02-09 14:53:34.248 27723-27848/? E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at [https://developers.facebook.com/docs/graph-api}](https://developers.facebook.com/docs/graph-api%7D)
2019-02-09 14:53:34.263 27723-27973/? I/ReactNativeJS: { type: 'image',
cancelled: false,
height: 1900,
width: 1900,
uri: 'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540kenectedtech%252Fkennectedapp/ImagePicker/b9d5afec-17dc-4e32-bc39-fcda14175a9c.png' }
2019-02-09 14:53:34.316 27723-27973/? I/ReactNativeJS: file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540kenectedtech%252Fkennectedapp/ImagePicker/b9d5afec-17dc-4e32-bc39-fcda14175a9c.png
2019-02-09 14:53:34.836 27723-27848/? E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at [https://developers.facebook.com/docs/graph-api}](https://developers.facebook.com/docs/graph-api%7D)
2019-02-09 14:53:35.076 27723-27723/? E/d: java.lang.RuntimeException:

Really need to fix this issue.

**Comment by AdamJNavarro** [comment] 2019-02-09 21:42
Hey @mohs1n,

The Snack you provided does not have any relevant code in it demonstrating the ImagePicker crash. It just has your dependencies added in the package.json. Can you update the snack or provide a new snack link that repros the crash?

Cheers,
Adam

**Comment by mohs1n** [comment] 2019-02-10 06:16
> Hey @mohs1n,
> 
> The Snack you provided does not have any relevant code in it demonstrating the ImagePicker crash. It just has your dependencies added in the package.json. Can you update the snack or provide a new snack link that repros the crash?
> 
> Cheers,
> Adam

I've uploaded the code to App.js. Can you re-check? https://snack.expo.io/@mohs1n/imagepickerissue

**Comment by AdamJNavarro** [comment] 2019-02-14 19:58
Hey @mohs1n,

There's unfortunately way too much going on in this snack. Can you follow this guide: https://stackoverflow.com/help/mcve and create a new Snack with just the relevant, necessary code.

**Comment by namnguyentat** [comment] 2019-03-18 10:23
I have the same problem

**Comment by brentvatne** [comment] 2019-03-28 16:18
going to close this because nobody has provided a minimal reproducible example (info in https://stackoverflow.com/help/mcve). please create a new issue with one if you are encountering this problem, thanks!

**Closed by brentvatne** 2019-03-28 16:18 UTC
Labels: ImagePicker
