### ISSUE TITLE
Expo Go Android app loads stale build while developing in production mode

### ISSUE THREAD

**Issue by ShaneMcNamara** [expo/expo#11844] opened 2021-02-04 19:58 UTC
**Summary**

When developing with Expo CLI in production mode (`expo start -c --no-dev`) my Android project is not updated, even after killing the app and restarted Expo CLI. Only after clearing the Expo Go app data from the device can it receive the new updated files.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

39.0.5

**Environment**

 Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.3 - /Users/ShaneMcNamara/.rvm/gems/ruby-2.2.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6821437
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.0 => 4.4.3 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

Repro steps:
1. `expo init android-test`. Choose blank project.
2. `cd android-test`
3. `expo start -c --no-dev`. 
4. Scan QR with Expo Go Android app. You should see the boilerplate text on a white background.
5. Change App.js to have `backgroundColor: 'red'`
6. Stop Expo CLI, kill Expo Go  and 'android-test' Android apps.
7. Repeat steps 3 and 4. Background color should be red, but is still white.
8. Again kill Expo Go and 'android-test' Android apps. Go into Android Settings -> Apps -> Expo Go -> Storage. Click "Clear data".
9. Open Expo Go and scan the QR code from Expo-CLI. You should see the boilerplate text on a red background.

**Comment by outaTiME** [comment] 2021-02-06 21:49
hi @ShaneMcNamara, 
yup, same here for a long time ago, in local environment (if i go with android), i need to run in dev mode so expo client takes the application updates

**Comment by esamelson** [comment] 2021-02-17 03:38
Thanks for the report, all -- I've reproduced this issue and can confirm. We have a fix planned, don't yet have a time frame for it but will update this issue with more information when we can.

**Comment by ShaneMcNamara** [comment] 2021-03-11 20:37
@esamelson,  I see that you've made some progress on this issue. Do you have an ETA on a release?/

Thanks.

**Comment by esamelson** [comment] 2021-03-11 21:49
Hi @ShaneMcNamara - yes, this fix will go out with the SDK 41 version of Expo Go (though the fix will work for all supported SDK versions). We're just starting the QA/release process, so the new version will probably be out to the App/Play stores in a few weeks.

**Comment by ide** [comment] 2021-10-01 16:49
Closing since https://github.com/expo/expo/pull/12111 was merged several months ago.

**Closed by ide** 2021-10-01 16:49 UTC
Labels: needs review
