### ISSUE TITLE
Application crashes when opening the app after closing it while the location background service was running

### ISSUE THREAD

**Issue by abdullah-abunada** [expo/expo#10139] opened 2020-09-10 12:39 UTC
### Summary of Issue 
The application crashes when opening it after closing it while the location background service was running
other notes: 
1) this issue occurs when GPS Sensor is enabled in both the expo client and the android device.
2) if I disabled the GPS location sensor then opening the app its opened normally.

### Debugging

1- TaskManager
```
 java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke interface method 'void l.d.a.c.a(android.content.Context, l.d.a.c$b, java.lang.Runnable, l.d.b.l.e)' on a null object reference
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7403)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void l.d.a.c.a(android.content.Context, l.d.a.c$b, java.lang.Runnable, l.d.b.l.e)' on a null object reference
        at expo.modules.taskManager.TaskService.executeTask(TaskService.java:17)
        at expo.modules.taskManager.Task.execute(Task.java:2)
        at expo.modules.location.taskConsumers.LocationTaskConsumer.executeTaskWithLocationBundles(LocationTaskConsumer.java:4)
        at expo.modules.location.taskConsumers.LocationTaskConsumer.didExecuteJob(LocationTaskConsumer.java:10)
        at expo.modules.taskManager.TaskService.handleJob(TaskService.java:7)
        at expo.modules.taskManager.TaskJobService.onStartJob(TaskJobService.java:3)
        at android.app.job.JobService$1.onStartJob(JobService.java:62)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7403) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
```
2- Location

```
Process: com.spoongate.rider, PID: 14793
    java.lang.RuntimeException: Unable to start service expo.modules.location.services.LocationTaskService@8c17018 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4106)
        at android.app.ActivityThread.access$1800(ActivityThread.java:220)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1892)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7403)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
        at expo.modules.location.services.LocationTaskService.onStartCommand(LocationTaskService.java:1)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4088)
        at android.app.ActivityThread.access$1800(ActivityThread.java:220) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1892) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7403) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
2020-09-13 21:09:37.703 14793-14833/? E/Perf: Fail to get file list com.spoongate.rider
2020-09-13 21:09:43.273 1604-7094/? E/InputDispatcher: Window handle Window{db861e4 u0 Application Error: com.spoongate.rider} has no registered input channel
2020-09-13 21:09:45.984 14850-14850/? E/spoongate.ride: Not starting debugger since process cannot load the jdwp agent.
2020-09-13 21:09:46.188 14850-14890/? E/Perf: Fail to get file list com.spoongate.rider
2020-09-13 21:09:46.489 834-834/? E/Layer: [Surface(name=AppWindowToken{55aae0f token=Token{1dd176e ActivityRecord{fb1dee9 u0 com.spoongate.rider/host.exp.exponent.MainActivity t1652}}})/@0xd4938ff - animation-leash#0] No local sync point found
2020-09-13 21:09:54.589 1604-9228/? E/InputDispatcher: Window handle Window{ef9e8f4 u0 com.spoongate.rider/host.exp.exponent.MainActivity} has no registered input channel
```

https://snack.expo.io/@a.abunada/e3f4ff

### Steps to Reproduce
1- run the example code in expo client or android device
2- enable device location (Location sensor)
3- enable the background task
4- close application
5- reopen it
6- crash will happen

### Expected Behavior vs Actual Behavior
Expected Behavior: after closing the application when the location service is running, it should be closed with the app, and then when I open the application it should work normally without crashing.
Actual Behavior: the application crashed, and if need to run it again you should clear the app storage.

**Comment by abdullah-abunada** [comment] 2020-09-12 07:30
another note: this issue occurs when GPS Sensor is enabled in both the expo client and the android device.

**Comment by abdullah-abunada** [comment] 2020-09-13 18:16
@Tomasz Sapeta any updates?

**Comment by Zanchee** [comment] 2020-09-14 22:56
Seems like a duplicate of #9288

**Comment by byCedric** [comment] 2020-09-28 12:33
@Zanchee it's not a duplicate of #9288, that issue is about tasks unable to unregister from the task manager and causing a lot of tasks being left running. 

This issue contains 2 separate issues:
1. How we start the task manager in managed projects ([fixed by PR #10409](https://github.com/expo/expo/pull/10409))
2. How we resolve the channel id when the location service is getting restarted ([fixed by PR #10410](https://github.com/expo/expo/pull/10410))

Both of these fixes are included in the next SDK 39 patch, we hope to push it out soon (probably somewhere this week or early next week).

Thanks for the issue report @abdullah-abunada, and sorry for the inconvenience!

**Closed by byCedric** 2020-09-28 12:33 UTC
Labels: Location, TaskManager, bug

**Comment by Zanchee** [comment] 2020-09-28 13:17
@byCedric thanks for the insight! Greatly appreciate the work you've done on these issues! If I could give you a GitHub medal, I would!

**Comment by byCedric** [comment] 2020-09-28 13:54
Haha I appreciate it! Again, I'm really sorry this happened and we'll push out a fix asap!

**Comment by superyarik** [comment] 2020-10-02 07:27
@byCedric btw, how we can see then this fix will be pushed? after we need update minor version of expo (39.0.#) ?
