### ISSUE TITLE
Expo router entry point not finding root _layout 

### ISSUE THREAD

**Issue by Ben-Stacey** [expo/expo#30121] opened 2024-07-02 08:15 UTC
### Minimal reproducible example

https://github.com/Ben-Stacey/test

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

On loading of the expo app I expect to be taken to the index screen. When I load the app Expo router is not finding the entry point into the repo. This is giving my the "Welcome to expo, start by creating a file in the app directory". Affecting IOS but also the only device I have tested on. 

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.14 => 51.0.17 
      expo-router: ^3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by marklawlor** [comment] 2024-07-04 08:20
Duplicate of https://github.com/expo/expo/issues/28933

Please avoid using `react-native-dotenv` and use Expo's inbuilt `.env` file support.

**Closed by marklawlor** 2024-07-04 08:20 UTC
Labels: outdated, needs review, Router

**Comment by Ben-Stacey** [comment] 2024-07-04 19:20
@marklawlor I changed to use expo in built `.env` support and the issue persists

**Comment by endvidous** [comment] 2025-02-02 21:20
@Ben-Stacey  Did you figure out how to make it work? Could you please let me know as I am also facing the same issue

**Comment by Pmmoks** [comment] 2025-02-04 23:59
Did anyone find a solution? I'm facing the same issue. None of the above suggestions is working for me.
