### ISSUE TITLE
Notification deep linking on standalone app often fails when app is closed

### ISSUE THREAD

**Issue by Dygerati** [expo/expo#785] opened 2017-10-15 17:59 UTC
I'm using push notifications on my app, and handling selected notifications by navigating to a certain screen. This works great in the non-standalone version of my app, but I've encountered some potentially significant issues on the standalone version. 

The issues only seem to occur when the app is entirely closed (not backgrounded, but closed), and the notification is received. On the iOS version this just results in the deep linking failing, basically with `props.exp.notification` being null or undefined, so that the app doesn't handle the notification. 

On android it's a little more ominous--the entire screen goes black and the app is unresponsive. The issue is sticky, in that it will likely continue to happen when I try to open the app again afterward; even if I've forced quit the app. 

That said, this doesn't happen all the time. At times it works as expected as well.

I have an e-mail chain going regarding the Android issue with @quinlanj, but I'm just now starting to suspect that these issues are related and I wanted to document it in in an issue.

**Comment by aniltirola** [comment] 2017-10-22 12:42
I am experiencing also problems, when testing my ios app in testflight;

- closing the app with homebutton double-tap
- swipe up to close
- now the app is 'closed'
- send push message
- tap on the push message
- app opens
- in the root-component there I try to get this.props.exp.notification
- sometimes there is no 'notification' in this.props.exp

I tried this really many, many times. Sometimes I try it about 10 or 20 times successively; sometimes there is the object 'notification' available and sometimes not; currently I only recognized this in ios-builds testing on real device with testflight;

**Comment by aniltirola** [comment] 2017-10-25 14:44
here is the gist from my app; I put everything in one file for easier debugging;
https://gist.github.com/aniltirola/df68c33f12f4028fe162fca658c3c5c8

**Comment by trungtrungkang** [comment] 2017-11-06 12:23
I am experiencing same problems. If the app was in background mode, when tap on the notification:
- ios: The app doesn't receive notification event quite frequently.
- android: The app stuck in the splash screen.

Hope that this issue will be resolved soon!

**Comment by ide** [comment] 2017-11-06 20:20
Just want to acknowledge that we are aware of this issue but don't have any updates.

**Comment by terribleben** [comment] 2017-11-07 00:39
Tentatively fixed here: https://github.com/expo/expo/commit/9f3eefca1506ccbced610a001cbe9cc4526c9b4b

Will ship with SDK 23.

**Comment by Dygerati** [comment] 2017-11-07 01:18
Thanks much @terribleben. Is this thought to address the issue with android black-screen or similar as well? I was never certain if it was the same issue, or if it was related to the notification handling. 

Also is it possible to just include a forked version of expo v22  in my project implementing this commit as well? Or another way to work around this issue before v23?

**Comment by terribleben** [comment] 2017-11-07 01:21
Ah sorry for being unclear - my fix only addresses the iOS side. The Android issue is actually a different issue with similar symptoms.

There's no straightforward way for you to use this fix before we release SDK 23, because the native code for standalone apps is built on Expo's servers, and we won't deploy the latest code until SDK 23 comes out. We're hoping to ship SDK 23 soon.

**Comment by jesseruder** [comment] 2017-11-09 19:50
Fixed the android side of this in SDK 23!

**Closed** 2017-11-17 02:44 UTC
Labels: project: client-android, project: client-ios

**Comment by aniltirola** [comment] 2017-11-21 21:40
Hello friends,

I just wanted to confirm that now everything works with sdk-23.0.0 It seems, that `this.props.exp.notification` was removed. But this is ok according to the explanation from @brentvatne here: https://github.com/expo/expo/issues/832

so now I removed my code depending on `this.props.exp.notification`  - now I only work with

```
_handleNotification = ({ origin, data }) => {
    // do something here
};
```

it works every time on ios - production build; built with `exp:build:ios`, tested on real device with testflight;

thanks for your hard work;

**Comment by Dygerati** [comment] 2017-11-28 13:17
I actually tried removing my reference to `his.props.exp.notification`, and my Android app stopped working for push notifications received while the app was closed. So I've put it back in. ¯\_(ツ)_/¯

This is on v23.

**Comment by julezKiano** [comment] 2017-12-05 12:27
For me this isn't firing on android when the app is completely closed 
`_handleNotification = ({ origin, data }) => {
    // do something here
};`
iOS works as expected.

**Comment by Dygerati** [comment] 2017-12-05 13:35
@julezKiano As mentioned above, I'm having the same issue with Android. I have to use the `props.exp.notification` property to force it to work on Android. Not intended, I'm sure, but it's a workaround.

**Comment by julezKiano** [comment] 2017-12-05 13:51
@Dygerati I tried that as well, I think they no longer pass in the notification object. [Refer](https://github.com/expo/expo/issues/843)

**Comment by Dygerati** [comment] 2017-12-05 19:08
@julezKiano It's strange, and I saw that as well, but does it apply to v23? Because my app is running v23 and I just confirmed that it's definitely using `props.exp.notification` when I receive a notification on Android (when the app is closed). 

I simply have this code in App.js
```
if (props.exp && props.exp.notification) {
     logger('Grabbed notification from "props.exp.notification"');
     notificationHandler(props.exp.notification);
 }
```

And the logging is being called.

**Comment by julezKiano** [comment] 2017-12-06 14:29
@Dygerati yes, very strange. I'm on v23 as well, testing on both Android an iOS. Hopefully this will be resolved in the next release. It seems a bit redundant for the listener in iOS to catch tapped on notifications and at the same time still pass in `props.exp.notification`

**Comment by nthgol** [comment] 2018-03-30 17:51
@brentvatne on iOS, the Notifications.addListener picks up all three allowable cases in the table below:
![image](https://user-images.githubusercontent.com/26420958/38147671-473d5e42-3421-11e8-800e-f0216476e278.png)

Can you update the table to make it clear that reaching into props.exp.notification in App.js (root component) is not necessary? (Maybe someone can confirm this on android.)

**Comment by nitish-deckspire** [comment] 2018-04-23 16:54
@nthgol hey what do you mean by "Notifications.addListener picks up all three allowable cases"? As in it picks up all situations and props.exp.notification is obsolete ongoing? Can you confirm what SDK onward this is the case?

**Comment by nthgol** [comment] 2018-04-23 17:32
@nitish-deckspire yes I found props.exp.notification did not add any cases not already picked up by the listener, implying it is obsolete. Keeping it around would be a matter of preference if you don't need the listener. 

I found it to be true for 25+

**Comment by nitish-deckspire** [comment] 2018-04-24 01:01
@terribleben Hey I'm having the same issue as @aniltirola on SDK v26 on iOS, notifications work generally, but not when the app is closed -- neither exp.props.notification nor Notification.addListener is working. I've tried v23, v24, and v26 with no luck -- any advice?

**Comment by nthgol** [comment] 2018-04-24 02:02
@nitish-deckspire  are you sure you aren't talking about when the app is backgrounded/closed? neither of the two methods you listed will pick anything up unless the user explicitly opens a notification they received on iOS

**Comment by nitish-deckspire** [comment] 2018-04-24 04:15
@nthgol no this is when the app is closed and the user swipes the notification to open -- I even tried a basic push notification example app (https://docs.expo.io/versions/latest/guides/push-notifications) and the issue is that props.exp.notification does not get set

**Comment by feliperaul** [comment] 2018-04-25 03:54
I'm on SDK version 25 and in iOS 11.3 my handleNotification callback is never called if the app is closed.

By closed I mean force closing the app or after an iPhone reboot. 

If the app is simply in background (for example, opening app and then switching to Safari or springboard) it works.

Here's the code:

static handleNotification(notification, navigation) {
    if (notification.origin === 'selected') {
      navigation.navigate(notification.data.screen);
    }
  }

If the app is in background, as soon as I click on the notification the app opens and navigates to the screen name passed on `data.screen`. But if I force close the app and send the exact same notification, when I click on the notification the app will simply open but no navigation will happen.

**Comment by terribleben** [comment] 2018-04-25 16:52
Hey all, it sounds like we had a regression here. This thread is pretty old, and it's probably a different bug with the same symptoms, so I've opened a [new thread](https://github.com/expo/expo/issues/1691) because it makes it easier for us to track. Feel free to discuss there, and sorry for not noticing this sooner!
