### ISSUE TITLE
Expo SDK 46.0.7 Error: Fetching the token failed: Please set your Project ID.

### ISSUE THREAD

**Issue by code4muktesh** [expo/expo#18642] opened 2022-08-15 05:04 UTC
### Summary

Getting error as

Error: Fetching the token failed: Please set your Project ID. A valid Firebase Project ID is required to communicate with Firebase server APIs: It identifies your application with Firebase.Please refer to https://firebase.google.com/support/privacy/init-options.

Note: When run on production then app is getting crashed.

Woking fine with SDK 45

### What platform(s) does this occur on?

Android, iOS

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ^46.0.7 => 46.0.7
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.4 => 0.69.4
      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: bare

### Minimal reproducible example

Integrate with FCM notification and expo start -c

**Comment by NicholasLoh** [comment] 2022-08-15 07:19
duplicate of #18570

**Comment by code4muktesh** [comment] 2022-08-15 07:25
> duplicate of #18570

I think this is not duplicate because facing with SDK 46 not 45 and also app is getting crashed in Prod mode on real android device not on expo go

**Comment by NicholasLoh** [comment] 2022-08-16 03:30
I downgraded to SDK 45 and the issue does not show up in prod. It seems like SDK 46 have some issue reading the `google-service.json` from  `app.json` because my MapView is also blank which is because it can't get the api key for google maps

**Comment by brentvatne** [comment] 2022-08-16 20:19
Expo Go 2.25.2 is live on the Play Store and installable via CLI and includes the fix for this (our Google credentials for usage in Expo Go were not being used correctly).

If this is happening for you in production (after building with EAS Build) it is likely a misconfiguration on your end, we are unable to reproduce any such issues in production.

**Closed by brentvatne** 2022-08-16 20:19 UTC
Labels: needs review

**Comment by humblesami** [comment] 2023-01-06 10:56
Its a duplicate of [issues#18570](https://github.com/expo/expo/issues/18570)
And the problem is with expo go version=>2.25
And the solution is
1. Probably short and recommended by other (not tested by me) => Downgrade to Expo 2.24.6 if you can
2. If you have usb cable and you can attach device to dev computer then get rid of expo at all
2.1 use command "expo eject" => Go to react-native project
2.2 build again with command "npx react-native run-android"
2.3 Run "npx react-native start"
