### ISSUE TITLE
[expo-splash-screen] No native splash screen registered for given view controller.Call 'SplashScreen.show' for given view controller first

### ISSUE THREAD

**Issue by changLiuUNSW** [expo/expo#7689] opened 2020-04-06 13:18 UTC
I am keep getting below errors when use ```expo-splash-screen```
```
No native splash screen registered for given view controller.
Call 'SplashScreen.show' for given view controller first
```
I am using bare workflow in my app and follow  [expo-splash-screen README](https://github.com/expo/expo/tree/94cbc77e990f54bf92219750616209c085714ff5/packages/expo-splash-screen) to setup splash screen.

It works fine in Android but not iOS. Is there any step missing in the readme file ?

**Comment by changLiuUNSW** [comment] 2020-04-06 14:29
Maybe it is caused by below code, but I am not familiar with native code
```
  self.moduleRegistryAdapter = [[UMModuleRegistryAdapter alloc] initWithModuleRegistryProvider:[[UMModuleRegistryProvider alloc] init]];
  self.launchOptions = launchOptions;

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
#ifdef DEBUG
  [self initializeReactNativeApp];
#else
  EXUpdatesAppController *controller = [EXUpdatesAppController sharedInstance];
  controller.delegate = self;
  [controller startAndShowLaunchScreen:self.window];
#endif
```

**Comment by cruzach** [comment] 2020-04-06 21:18
Please provide a reproducible demo, along with the rest of the information we ask for in the bug report template

**Comment by changLiuUNSW** [comment] 2020-04-07 14:02
@cruzach  I just confirmed this issue only happen for release build not debug build. I will provide a repo by the end of this weekend

**Comment by alorr10** [comment] 2020-04-15 03:27
I'm seeing the same issue!

**Comment by 0duaht** [comment] 2020-04-20 20:01
Also experiencing this. Happens with Bare workflow projects using expo-updates. The flicker happens when an update is published.

**Comment by pearup** [comment] 2020-04-21 05:11
Also experienced the same problem, it seems somehow in release build, all the JS function calls don't actually get to the native side.
If it helps, I'm temporarily using this:
https://github.com/crazycodeboy/react-native-splash-screen
It works very well for me.

**Comment by SamyOptimize** [comment] 2020-04-21 20:02
Can confirm this is also happening on my project. The splash screen shows up then an empty screen then the app opens. tried `preventAutoHideAsync` in `componentDidMount` and in the global scope's `constructor` but nothing worked. Kept getting that error on release builds

**Comment by brentvatne** [comment] 2020-04-21 20:25
please share a reproducible example @0duaht @changLiuUNSW!

@SamyOptimize - i replied to you on the other issue with respect to the example that you provided and how you to update your code to work: https://github.com/expo/expo/issues/7821#issuecomment-617389797 - perhaps this is related in your case

**Comment by 0duaht** [comment] 2020-04-21 20:49
@brentvatne here's a reproducible example - https://github.com/expo/expo/issues/7689#issuecomment-613794665

**Comment by alorr10** [comment] 2020-04-22 17:47
Was just able to reproduce again following these steps:

1. `expo init SplashScreenTest`
2. `expo install expo-splash-screen`
3. `cd ios && pod install && cd ..`
4. `yarn expo-splash-screen -p "ios" -r "cover" "#0a0234" ~/Desktop/icons/Splash.png`
5. Build in dev mode - works fine. `SplashScreen.preventAutoHideAsync()` keeps the splash screen showing and `SplashScreen.hideAsync()` removes it.
6. expo publish
7.  Build in release mode: `SplashScreen.preventAutoHideAsync()` and `SplashScreen.hideAsync()` have no effect. OTA updates are working fine but the app opens immediately after the native splash screen is shown, and there is the famous white flicker. 

Here is my App.js - it should show the splash screen for 2 seconds before hiding it. This works as expected in dev but is ignored in release.

```
import React, { useEffect } from 'react';
import { StyleSheet, View } from 'react-native';
import * as SplashScreen from 'expo-splash-screen';

SplashScreen.preventAutoHideAsync();

export default function App() {
  useEffect(() => {
    setTimeout(() => SplashScreen.hideAsync(), 2000);
  }, []);
  return (
    <View style={styles.container}/>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
  },
});
```

**Comment by SamyOptimize** [comment] 2020-04-22 18:04
Can confirm that that's what I also did as @alorr10 did and the problem still persists

**Comment by brentvatne** [comment] 2020-04-22 18:16
@bbarthec - that should be a reproducible example for you to work off of :)

**Comment by esamelson** [comment] 2020-04-23 02:06
hey all -- looks like this is indeed caused by a bad interaction between expo-updates and expo-splash-screen. thanks for the report and the clear repro case. we're looking into it and hope to have a fix soon!

**Comment by esamelson** [comment] 2020-04-23 23:54
hey everyone -- we are working on figuring out the correct solution for this and will release new compatible versions of these libraries as soon as we can. but in the meantime you can fix this yourself in AppDelegate by applying the following diff:

```diff
+#import <EXSplashScreen/EXSplashScreenService.h>
+#import <UMCore/UMModuleRegistryProvider.h>

 - (RCTBridge *)initializeReactNativeApp
 {
  ...
   [self.window makeKeyAndVisible];

+  EXSplashScreenService *splashScreenService = (EXSplashScreenService *)[UMModuleRegistryProvider getSingletonModuleForClass:[EXSplashScreenService class]];
+  [splashScreenService showSplashScreenFor:rootViewController];

   return bridge;
 }

**Comment by zchwyng** [comment] 2020-04-29 21:59
I'm still experiencing the white flash in release builds running on iPhone 8 – works fine on iPhone X though. Am I doing something wrong? This is what my AppDelegate.m looks like: https://pastebin.com/uTid5yqk

Really grateful for any pointers!

**Comment by 0duaht** [comment] 2020-04-29 22:12
@zchwyng do you have a lot of bundled assets?

**Comment by zchwyng** [comment] 2020-04-29 23:25
> @zchwyng do you have a lot of bundled assets?

I have 5 bundled images (total ~450 kb)

**Comment by 0duaht** [comment] 2020-04-30 01:38
Not sure if it's related to the bundle size, will try reproducing, but in our case the release-build white flash comes up on the very first install, possibly while downloading and syncing assets. Tried to reproduce with a bare project without bundled assets, no white flash.

Solution we ended up with was keeping the splash screen on until any of Update events fire, or after say 3 seconds (whichever happens first).
https://github.com/expo/expo/tree/master/packages/expo-updates#updatesaddlistenereventlistener

**Comment by zchwyng** [comment] 2020-04-30 18:33
> Not sure if it's related to the bundle size, will try reproducing, but in our case the release-build white flash comes up on the very first install, possibly while downloading and syncing assets. Tried to reproduce with a bare project without bundled assets, no white flash.
> 
> Solution we ended up with was keeping the splash screen on until any of Update events fire, or after say 3 seconds (whichever happens first).
> https://github.com/expo/expo/tree/master/packages/expo-updates#updatesaddlistenereventlistener

I tried setting assetBundlePatterns in app.json to an empty folder and also added a timeout of 2 seconds before running SplashScreen.hide(), but it didn't help unfortunately. I also tried setting updates.enabled to false in app.json but I'm still seeing a small glitch.

**Comment by Mickael-FAVRE-FELIX** [comment] 2020-06-01 16:50
I have the same message error, and I have to call : SplashScreen.hideAsync() in App.js (without any call to  SplashScreen.preventAutoHide()), to hide the splash screen (otherwise the splash screen doesn't hide)

I tried esamelson modifications but it doesn't work.

Any solution ?

**Comment by martinezguillaume** [comment] 2020-06-17 07:48
@esamelson solution work for me. But I still have white blank flicker in the middle of my splash screen.

In Release, it's like:
- My app starts
- Splashscreen appears
- Splashscreen disappear -> white screen
- @esamelson [code](https://github.com/expo/expo/issues/7689#issuecomment-618728916) will make the splashscreen reappears
(`preventAutoHideAsync` & `hide` are working as expected)

Now in Debug, I have the following warning: `'SplashScreen.show' has already been called for given view controller.`
It seems that in Debug everything is working great, but in Release we have to manually called `showSplashScreenFor` don't know why.

**Comment by OscarYuen** [comment] 2020-06-25 13:36
> @esamelson solution works for me. But I still have white flicker in the middle of my splash screen.
> 
> In Release, it's like:
> 
> * My app starts
> * Splashscreen appears
> * Splashscreen disappear -> white screen
> * @esamelson [code](https://github.com/expo/expo/issues/7689#issuecomment-618728916) will make the splashscreen reappears (calling `showSplashScreenFor`)
>   (`preventAutoHideAsync` & `hide` are working as expected)
> 
> Now in Debug, I have the following warning: `'SplashScreen.show' has already been called for given view controller.`
> It seems that in Debug everything is working great, but in Release we have to manually called `showSplashScreenFor` don't know why, making a double called to this function in Debug
> 
> For now, I'll leave it like that and wait for update !

I don't have expo-updates installed in my bare workflow but meet the same issues as yours (white flickering)

**Comment by OscarYuen** [comment] 2020-06-27 17:40
> > @esamelson solution works for me. But I still have white flicker in the middle of my splash screen.
> > In Release, it's like:
> > 
> > * My app starts
> > * Splashscreen appears
> > * Splashscreen disappear -> white screen
> > * @esamelson [code](https://github.com/expo/expo/issues/7689#issuecomment-618728916) will make the splashscreen reappears (calling `showSplashScreenFor`)
> >   (`preventAutoHideAsync` & `hide` are working as expected)
> > 
> > Now in Debug, I have the following warning: `'SplashScreen.show' has already been called for given view controller.`
> > It seems that in Debug everything is working great, but in Release we have to manually called `showSplashScreenFor` don't know why, making a double called to this function in Debug
> > For now, I'll leave it like that and wait for update !
> 
> I don't have expo-updates installed in my bare workflow but meet the same issues as yours (white flickering)

Confirmed white flickering issue still exists in SDK 38 bareworkflow.

**Comment by OscarYuen** [comment] 2020-06-29 16:49
**Remark: I am using bare workflow without expo-updates** 
In case you don't want any flickering from your app and you are not using Splash screen API in your js code.
You can simply comment out 
`[super application:application didFinishLaunchingWithOptions:launchOptions];`
and change the rootView.backgroundColor to your splash background color to try to make it look natural

Example:
```
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"main" initialProperties:nil];
  rootView.backgroundColor = **[[UIColor alloc] initWithRed:0.96f green:0.65f blue:0.14f alpha:1]**; //Change to orange background color

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
//  [super application:application didFinishLaunchingWithOptions:launchOptions];
```

**Comment by RupamShaw** [comment] 2020-07-20 02:36
still getting white flickering screen expo-38.0.1

**Comment by OscarYuen** [comment] 2020-07-20 11:38
> still getting white flickering screen expo-38.0.1

You can install the latest expo-splash-sceen v0.4.0 directly. It would fix the flickering issue.
For android build, you need to change the 3rd argument of SplashScreen.show to `false` in MainActivity.java onCreate function

**Comment by andrekovac** [comment] 2020-07-20 21:55
@OscarYuen thanks! However, also with other resize modes (e.g. COVER) one needs to change the third argument of `SplashScreen.show` to be of type boolean. [See here](https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-splashscreenshowactivity-activity-splashscreenimageresizemode-mode-boolean-statusbartranslucent).

**Comment by OscarYuen** [comment] 2020-07-21 06:37
> @OscarYuen thanks! However, also with other resize modes (e.g. COVER) one needs to change the third argument of `SplashScreen.show` to be of type boolean. [See here](https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-splashscreenshowactivity-activity-splashscreenimageresizemode-mode-boolean-statusbartranslucent).

Yes, you are right.
The choice of using true or false as 3rd argument depends on whether the status bar is translucent.
In my case, I used false.

**Comment by grimunit** [comment] 2020-07-30 16:17
For me I'm still getting the white screen on Android but not on iOS, I updated to 0.4.0 of expo-splash-screen. I'm on expo-38.0.1 I also made sure my `MainActivity.java` had the following:

```java
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // SplashScreen.show(...) has to be called after super.onCreate(...)
    // Below line is handled by '@expo/configure-splash-screen' command and it's discouraged to modify it manually
    SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, true);
}
```

It shows this screen after first correctly showing my splash image. Then shows the white screen with a stock icon, then shows my splash screen again and then hides to show my app.

<img width="372" alt="Screen Shot 2020-07-30 at 10 16 38 AM" src="https://user-images.githubusercontent.com/1504994/88947477-d1a83d00-d24d-11ea-9cf7-0f803e6322e8.png">

**Comment by sbrighiu** [comment] 2020-08-03 11:19
@grimunit you should check if 
      SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class);
helps you. In some version the API changed and it is not properly updated on Android generated MainActivity.java

**Comment by grimunit** [comment] 2020-08-03 14:26
@sbrighiu Thanks for the suggestion, ya I actually already had that initially and I was getting the same thing. I think I tried 10 different things haha. Ultimately I had to switch to react-native-splash-screen and everything is working now :/

**Comment by yzalvov** [comment] 2020-09-01 12:23
Hi all. 
Well, after having enough with `expo-splash-screen` for my ejected (bare workflow) project, I've decided to give `react-native-splash-screen` a try. 

@grimunit Please advise, is it enough to just `yarn remove expo-splash-screen` and install and setup `react-native-splash-screen` according to its github page? Or should I consider any additional steps to clean `expo-splash-screen` magic from native iOS/Android files? 
Many thanks for considering my request.

**Comment by grimunit** [comment] 2020-09-01 14:25
@yzalvov unfortunately my experience will not guarantee the same for you, especially since I didn't eject but started out with the bare workflow and it looks like others have been having different issues removing expo-splash-screen after they ejected as seen in [this issue](https://github.com/expo/expo/issues/9604). So just start removing it and googling around to help with any issues you encounter, kinda been the norm for working in react native as everyone has a different starting point.

**Comment by yzalvov** [comment] 2020-09-01 15:43
Thank you @grimunit ! Especially for the issue link. I may give the `react-native-splash-screen` another try (first one didn't go well..). 
Does the `SplashScreen.preventAutoHideAsync()` really work for anyone? It may be my "ejected situation", but for me on iOS it doesn't work. I can log a result of that call as `true` and even if I don't use the `SplashScreen.hideAsync()` later, my splash screen hides automatically.

**Comment by RealDyllon** [comment] 2020-09-03 00:59
Rolling back to "expo-splash-screen" v0.3.1 with the bare workflow fixed it for me, solution here: https://github.com/expo/expo/issues/9432#issuecomment-684089679
Copied here:

>> Is there any way to use old version 0.3.1? Expo has it own bundled version 0.5 and running pod-install installs the higher version. Splash screen methods like preventAutoHideAsync and hideAsync only work in 0.3.1.

>I was able to solve it via the following steps:

>Install "expo-splash-screen" at 0.3.1 in package.json
>Update Podfile as per unimodules instructions to exclude the included version of 'expo-splash-screen' by updating the line `use_unimodules!` to `use_unimodules!(exclude: ['expo-splash-screen'])`
>Manually install the expo-splash-screen pods from Podfile with the line:
>`pod 'EXSplashScreen', :path => '../node_modules/expo-splash-screen/ios'`
>Keep the AppDelegate.m file as before
>After doing this and running a fresh pod install I was able to use the SplashScreen.preventAutoHideAsync and SplashScreen.hideAsync methods with their desired functionality.

Having installed v0.3.1, I then had to reconfigure the splash-screen for ios and android using the CLI tool (`yarn run configure-splash-screen`)

**Comment by JasonGreenAmerica** [comment] 2020-09-14 22:39
> Rolling back to "expo-splash-screen" v0.3.1 with the bare workflow fixed it for me, solution here: [#9432 (comment)](https://github.com/expo/expo/issues/9432#issuecomment-684089679)
> Copied here:
> 
> > > Is there any way to use old version 0.3.1? Expo has it own bundled version 0.5 and running pod-install installs the higher version. Splash screen methods like preventAutoHideAsync and hideAsync only work in 0.3.1.
> 
> > I was able to solve it via the following steps:
> 
> > Install "expo-splash-screen" at 0.3.1 in package.json
> > Update Podfile as per unimodules instructions to exclude the included version of 'expo-splash-screen' by updating the line `use_unimodules!` to `use_unimodules!(exclude: ['expo-splash-screen'])`
> > Manually install the expo-splash-screen pods from Podfile with the line:
> > `pod 'EXSplashScreen', :path => '../node_modules/expo-splash-screen/ios'`
> > Keep the AppDelegate.m file as before
> > After doing this and running a fresh pod install I was able to use the SplashScreen.preventAutoHideAsync and SplashScreen.hideAsync methods with their desired functionality.
> 
> Having installed v0.3.1, I then had to reconfigure the splash-screen for ios and android using the CLI tool (`yarn run configure-splash-screen`)
@RealDyllon I got.

$.../node_modules/.bin/configure-splash-screen
error: missing required argument 'backgroundColor'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by RealDyllon** [comment] 2020-09-14 23:15
@JasonGreenAmerica 
You need to pass params to the configure command, as described here:

https://github.com/expo/expo-cli/tree/master/packages/configure-splash-screen#-usage

**Comment by bbarthec** [comment] 2020-10-07 15:00
As this issue has grown quite big & touches variety of different aspect of `expo-splash-screen` module I'm closing it and kindly ask anyone suffering from the misbehaviour of this module to open a separate issue following the template (paying extra attention to the `Reproducible Demo` section).

**Closed by bbarthec** 2020-10-07 15:00 UTC
Labels: Bare Workflow, SplashScreen

**Comment by MatheusPires99** [comment] 2020-10-17 02:45
I am having this exactly same problem: 
`No native splash screen registered for given view controller.Call 'SplashScreen.show' for given view controller first`

But I am not using expo-slash-screen library, I have a bare workflow project with expo unimodules using react-native-splash-screen, so why I am having this warning?

<img width="682" alt="Captura de Tela 2020-10-16 às 23 44 47" src="https://user-images.githubusercontent.com/49207932/96326739-abeb3280-1009-11eb-93a8-7e24580d228c.png">
<img width="398" alt="Captura de Tela 2020-10-16 às 23 45 03" src="https://user-images.githubusercontent.com/49207932/96326741-ad1c5f80-1009-11eb-9574-24f76c09d8b5.png">

**Comment by calluna18** [comment] 2020-10-27 16:09
I had the same problem as @MatheusPires99 and noticed that  the `expo-splash-screen` unimodule was installed by default just by installing expo and assumed this caused some conflict with `react-native-spash-screen`. Solved it by explicitly excluding `expo-splash-screen` in `ios/Podfile` with `use_unimodules!(exclude: ['expo-splash-screen'])` which seem to have solved the problem for me. Don't forget to run `pod install` after the change. 

Hope it could help someone else! 🙂 

Have not tried it out for Android but I assume you could just do the same there (see docs):
https://docs.expo.io/bare/installing-unimodules/

**Comment by MatheusPires99** [comment] 2020-10-31 13:30
@calluna18 I added `use_unimodules!(exclude: ['expo-splash-screen'])` on ios/Podfile and now I am getting another warning:

![Captura de Tela 2020-10-31 às 10 28 58](https://user-images.githubusercontent.com/49207932/97780527-ff11c900-1b63-11eb-9cc3-11e0c2d0313a.png)

**Comment by yagudaev** [comment] 2021-04-28 22:38
In my case, I saw this warning in an Expo Managed Workflow. We had a splash screen defined in `app.json`, however we were missing the following:

```javascript
// App.js

import 'expo-splash-screen'
...
```

Importing the splash screen like so made the warning go away :).

**Comment by vsurge** [comment] 2021-05-07 00:00
This works for me:

```
import {LogBox} from 'react-native';

LogBox.ignoreLogs([
  "No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.",
])
```

**Comment by Pat-Gekoski** [comment] 2021-06-01 01:44
I started getting the warning on my managed expo project today......I placed the hideAsyc() function in a setTimeout call like others have. That seems to cause the problem. I was trying to prevent the flicker from switching my authentication navigation to my main navigation when the auth was verified by delaying the hiding of the SplashScreen. Seems to be a common problem.

**Comment by nandorojo** [comment] 2021-06-13 22:31
This happens to me in the simulator the first time I run my app in with expo-dev-client. If I refresh, it works fine.

**Comment by marcusmc** [comment] 2021-08-15 13:20
Ran into this problem, and although it's likely an edge case, thought it would be worth writing down.  I had an RN Alert that was being rendered outside of the application's standard flow (largely as a debug tool).  Once I removed this alert, the error went away.  I imagine that inadvertently attempting to render anything before the splash screen is hidden could cause this issue as well.

**Comment by haibert** [comment] 2021-10-14 16:38
Is there a solution for this ? Mine started when I updated to expo sdk 43, managed work flow.
