### ISSUE TITLE
Detached app launch very slowly for release app in China, especially android and abnormally spend halve an minute entering app.

### ISSUE THREAD

**Issue by OPChips** [expo/expo#1924] opened 2018-06-27 12:43 UTC
For a Chinese react native develeper, I encountered something abnormal to develop app using expo. For my detached, released and published app, most of users complain that the app spend too long time to enter home page, especially android users. So I doubt that, when starting up expo app,    whether app access to expo server and how can I disable this behavior? Is there something wrong about expo ? And I discover that when I close all network, app launch very faster than before.
  This issue is very very important for me and some Chinese developer, please tell me how to solve it, or how to sharply improve starting speed for release app.

  develop environment:
  npm: 5.6.0
  node: 8.11.1
  react: 16.3.1
  react-native: 0.52+ (expo fork 27.0.0)
  expo: 27.0.0
  operation system: OS X 10.13.4
  test mobile phone system: iOS 10.2、android 6.0.1+

**Comment by anp** [comment] 2018-06-28 07:30
@OPChips hi! I think if you set `fallbackToCacheTimeout` to a number lower than the default you should be able to continue loading the offline version of the app while updates are requested in the background. Does the [`updates` key in app.json](https://docs.expo.io/versions/unversioned/workflow/configuration#updates) cover what you'd need here?

**Comment by icodytan** [comment] 2018-06-30 01:49
@OPChips I'm sorry, I understand the problem wrong. Looking at your`updates`, you are opening the expo's OTA, causing the user to request the expo's network each time the app is opened, but accessing the expo's OTA in China is too slow. Try to close it?
```
"updates": {
    "enabled": false
}
```

**Comment by OPChips** [comment] 2018-06-30 06:38
@icodytan thank you very much, I recently have changed this value, than case improved a bit.

**Comment by aatreya** [comment] 2018-06-30 15:30
We've noticed the same issue, even though fallbackToCacheTimeout is also 0 for us. Putting the device in airplane mode makes it launch much faster. Is there any way to prevent the app from blocking on a network request when the timeout is 0 and updates are still enabled?

If the timeout is 0, isn't Expo supposed to launch the app immediately and download updates asynchronously in the background?

**Comment by esamelson** [comment] 2018-07-03 17:12
Hi all - thanks for the reports. We'll try and look into this as soon as we can. In the meantime, it would be super helpful if someone experiencing this issue could take a look at all of the network requests your app is making on launch (maybe with something like [Charles Proxy](https://www.charlesproxy.com/)) and let us know if you see anything out of the ordinary or can identify which request(s) is causing the app to hang.

**Comment by aatreya** [comment] 2018-08-02 00:09
We just updated to SDK 29 and the issue is still occurring. It happens only on android, and still doesn't happen when the device is in airplane mode (in which case it will load the cached bundle). The app loading time seems inversely correlated with network speed, even though the APK has a cached JS bundle and the fallback timeout is 0. I'll try to see if I can get any additional details via proxy, but my best hunch right now is that the app load is still blocking on downloading the manifest (or the whole bundle?) even when it shouldn't.

**Comment by esamelson** [comment] 2018-08-14 22:13
Hi @aatreya - thanks, this is very helpful. Unfortunately I'm still unable to reproduce this using macos' network link conditioner. Could you let us know:

- if your app is detached or not
- `updates` settings in app.json
- if this happens EVERY time the app is launched with poor network speed, or
- if you launch the app with good network speed and it launches properly, does it continue to happen on the same installation if you move back to poor network speed?

Thanks very much, and really sorry for the trouble 😞

**Comment by aatreya** [comment] 2018-08-14 22:37
Answers below:
- App is detached
- "updates": {
      "fallbackToCacheTimeout": 0
    },
- The behavior does seem to happen every time. Will poke at this more and try to verify though.
- Yes - the slow loads continue to happen even after a cached bundle has been downloaded successfully.

**Comment by esamelson** [comment] 2018-08-28 18:26
@aatreya are you by any chance using the `AppLoading` or `SplashScreen` APIs from expo sdk?

**Comment by zhaozhiming** [comment] 2018-10-09 09:04
@esamelson When I detach the app, the `app.json` configuration will still work for my app? Thanks.

**Comment by dajohnny** [comment] 2019-02-27 15:38
@OPChips  Can I know your question had fixed?  I meeting the same question.

**Comment by esamelson** [comment] 2019-10-09 19:30
Hi, we're closing inactive issues that apply to SDK versions we no longer support. It sounds like the issue was resolved. If not, please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.

**Closed by esamelson** 2019-10-09 19:30 UTC
Labels: project: expokit
