### ISSUE TITLE
[expo-splash-screen] - missing support for `react-native` new architecture

### ISSUE THREAD

**Issue by coolersham** [expo/expo#21662] opened 2023-03-10 13:58 UTC
### Minimal reproducible example

https://github.com/expo/expo/tree/main/templates/expo-template-bare-minimum

### General overview
Since upgrading to the new architecture of `react-native` with the new `Fabric` renderer it is noticeable that the `SplashScreen` behaviour is not the same as before.
Using that line `SplashScreen.preventAutoHideAsync()` in `App.js` without ever calling `SplashScreen.hideAsync()` previously led to the fact that the defined `SplashScreen` does not hide.

### Expected behaviour
Calling`SplashScreen.preventAutoHideAsync()` should not hide the `SplashScreen` before calling `SplashScreen.hideAsync()`.

#### Actual behaviour
`SplashScreen` is hidden immediately and does ignore prevention execution.

### Steps to reproduce (from iOS perspective)
1. Use the example project `expo-template-bare-minimum` and install all dependencies via your favourite package manager (you can even bump all packages included in `package.json` to their latest versions; should not make a difference).
1. Navigate into the `ios` folder and execute `pod install`.
1. Add the following line `SplashScreen.preventAutoHideAsync()` outside of the `App` component located in the `App.js` file.
1. Open the Xcode workspace, configure the signing config and build the app to a real or simulator device.
1. Notice how the `SplashScreen` just works fine and as expected.
1. Now change the configuration in the `Podfile` so that the project uses the new architecture of `react-native`. Following configuration should do the trick:
```
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = '1'

platform :ios, podfile_properties['ios.deploymentTarget'] || '13.0'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...), which will be excluded. To fix this,
# you can also exclude `react-native-flipper` in `react-native.config.js`
#
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
#   }
# }
# ```
flipper_config = FlipperConfiguration.disabled
if ENV['NO_FLIPPER'] == '1' then
  # Explicitly disabled through environment variables
  flipper_config = FlipperConfiguration.disabled
elsif podfile_properties.key?('ios.flipper') then
  # Configure Flipper in Podfile.properties.json
  if podfile_properties['ios.flipper'] == 'true' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"])
  elsif podfile_properties['ios.flipper'] != 'false' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"], { 'Flipper' => podfile_properties['ios.flipper'] })
  end
end

target 'HelloWorld' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']
  
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Note that if you have use_frameworks! enabled, Flipper will not work if enabled
    :flipper_configuration => flipper_config
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end

```
1. Again execute `pod install` in the `ios` folder and notice the different output on the console.
1. Reload the Xcode workspace and rebuild the app to a real or simulator device.
1. Notice how the `SplashScreen` is broken and does not work as expected anymore.

### Conclusion
If I am the one missing something or there are required changes in another file, which I have to apply, please let me know. Thanks for looking into this issue and I am looking forward to a reply :)

### Environment

```    
System:
   OS: macOS 13.2.1
   Shell: 5.8.1 - /bin/zsh
Binaries:
   Node: 16.19.1 - /usr/local/bin/node
   Yarn: 1.22.19 - /opt/homebrew/bin/yarn
   npm: 8.19.3 - /opt/homebrew/opt/node@16/bin/npm
Managers:
   CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
SDKs:
   iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
IDEs:
   Android Studio: 2022.1 AI-221.6008.13.2211.9514443
   Xcode: 14.2/14C18 - /usr/bin/xcodebuild
```

**Comment by claudiofus** [comment] 2023-03-14 14:18
I'm facing the same error

**Comment by o-alexandrov** [comment] 2023-05-28 09:24
Just to document, afaik, this is a related PR https://github.com/expo/expo/pull/22588
Thank you very much `@Kudo` (formatting to avoid a ping)

**Comment by o-alexandrov** [comment] 2023-07-05 11:17
Thank you @Kudo, the issue seems to be resolved when using `expo@49.0.0-beta.5`, `expo-splash-screen@0.20.3`.

**Comment by Kudo** [comment] 2023-07-07 05:40
thanks! good to know the version resolving the issue. i'm closing this issue. if it still happening, please let me know. thanks!

**Closed by Kudo** 2023-07-07 05:40 UTC
Labels: SplashScreen, Issue accepted

**Comment by mirocosic** [comment] 2023-11-21 19:26
> thanks! good to know the version resolving the issue. i'm closing this issue. if it still happening, please let me know. thanks!

hey @Kudo !
I'm seeing this issue again in `expo@49.0.20` and `expo-splash-screen@0.20.5`
It was working somewhere until `expo@49.0.7` 

here is the reproduction repo
https://github.com/mirocosic/expo-splash-screen-repro

Can you take a look please? 👀
