### ISSUE TITLE
ExpoPermissions.askAsyncwith arguments( location ): -[NSTaggedPointerString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0xad4bd1eb5a978bf1

### ISSUE THREAD

**Issue by Rutvik17** [expo/expo#7480] opened 2020-03-26 02:42 UTC
## 🐛 Bug Report
I started getting this error when calling to get Location Permissions.

## Error
`An exception was thrown while calling `ExpoPermissions.askAsync` with arguments `(
    location
)`: -[NSTaggedPointerString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0xad4bd1eb5a978bf1`

## Environment
```
    "expo-location": "~7.0.0",
    "expo-constants": "latest",
    "expo-permissions": "~7.0.0",
    "@expo/vector-icons": "latest",
    "expo": "^35.0.0",
    "expo-linear-gradient": "~7.0.0",
    "firebase": "^7.2.2",
    "native-base": "^2.13.8",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
```
    

## My Code
The only place where i am asking for permissions is here 

```

> `try {
>                 let { status } = await Permissions.askAsync(Permissions.LOCATION);
>                 this.setState({
>                     locationPermission: status
>                 });
>                 if (this.state.locationPermission === 'granted') {
>                     this._getLocationAsync();
>                 }
>             } catch (e) {
>                 console.log(e);
>                 this.setState({
>                     errorMessage: 'Something went wrong, please try again!',
>                 });
>             }`

```

**Comment by IjzerenHein** [comment] 2020-03-27 13:57
Hi! There seems to be mismatch between your SDK 35 and `expo-permissions` dependencies.

I was able to reproduce the problem only when I used `expo-permissions~8.0.0` in combination with SDK 35. However when using SDK 35 you need to use `expo-permissions~7.0.0`.

Please make sure you have `expo-permissions~7.0.0` installed (preferably by using `expo install expo-permissions`) and also that your `app.json` contains `"sdkVersion": "35.0.0"`.

Compatibility overview:

| Expo SDK   | expo-permissions   |
|---|---|
| 35  | `~7.0.0`  |
| 36  | `~8.0.0`  |

**Comment by Rutvik17** [comment] 2020-03-28 02:07
sdk version in my app.json is `35.0.0`
` "sdkVersion": "35.0.0",`
 my `package.json`
```
    "expo": "^35.0.0",
    "expo-location": "~7.0.0",
    "expo-constants": "latest",
    "expo-permissions": "~7.0.0",
```

I am still getting the same error. That does not solve the issue. You should `reopen` this issue.

**Comment by IjzerenHein** [comment] 2020-03-28 06:12
Could you run `expo-doctor` and see whether that solves anything?

Also please run `expo-diagnostics` and log the results here.

**Comment by Rutvik17** [comment] 2020-03-28 06:30
Results from `expo diagnostics`
```
Expo CLI 3.15.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.15.5
```

**Comment by IjzerenHein** [comment] 2020-03-28 06:40
Okay, well that looks good so far.

Could you check which version of `expo-permissions` is installed in `node_modules` ?

Also please run the `npm ls expo-permissions` command log the results here?

**Comment by Rutvik17** [comment] 2020-03-28 06:41
yes `expo-permissions` is installed in `node_modules`

results from `npm ls expo-permissions`
```

├─┬ expo@35.0.1
│ └── expo-permissions@7.0.0  deduped
└── expo-permissions@7.0.0 

```

**Comment by IjzerenHein** [comment] 2020-03-28 06:42
> yes expo-permissions is installed in node_modules

Which version?

**Comment by Rutvik17** [comment] 2020-03-28 06:44
`7.0.0`

**Comment by Rutvik17** [comment] 2020-03-28 06:45
```
{
  "_args": [
    [
      "expo-permissions@7.0.0",
      "/Users/shreejikrupa/Desktop/React-Native/Day"
    ]
  ],
  "_from": "expo-permissions@7.0.0",
  "_id": "expo-permissions@7.0.0",
  "_inBundle": false,
  "_integrity": "sha512-C+qyVz+pdZO4YpVR2HSC3gsBZg0Qb8brCFgzmDmWcAtgrOiHClaLPdhI2XtQuGh8ubXcKPUGZp++UCEGiG0Jxg==",
  "_location": "/expo-permissions",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "expo-permissions@7.0.0",
    "name": "expo-permissions",
    "escapedName": "expo-permissions",
    "rawSpec": "7.0.0",
    "saveSpec": null,
    "fetchSpec": "7.0.0"
  },
  "_requiredBy": [
    "/",
    "/expo"
  ],
  "_resolved": "https://registry.npmjs.org/expo-permissions/-/expo-permissions-7.0.0.tgz",
  "_spec": "7.0.0",
  "_where": "/Users/shreejikrupa/Desktop/React-Native/Day",
  "author": {
    "name": "650 Industries, Inc."
  },
  "bugs": {
    "url": "https://github.com/expo/expo/issues"
  },
  "description": "Allows you prompt for various permissions to access device sensors, personal data, etc.",
  "devDependencies": {
    "expo-module-scripts": "~1.1.1"
  },
  "gitHead": "4e13b3cb88d9205f14bee7764038ab2dd9ef1fbd",
  "homepage": "https://docs.expo.io/versions/latest/sdk/permissions/",
  "jest": {
    "preset": "expo-module-scripts"
  },
  "keywords": [
    "react-native",
    "expo",
    "permissions"
  ],
  "license": "MIT",
  "main": "build/Permissions.js",
  "name": "expo-permissions",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/expo/expo.git",
    "directory": "packages/expo-permissions"
  },
  "scripts": {
    "build": "expo-module build",
    "clean": "expo-module clean",
    "expo-module": "expo-module",
    "lint": "expo-module lint",
    "prepare": "expo-module prepare",
    "prepublishOnly": "expo-module prepublishOnly",
    "test": "expo-module test"
  },
  "sideEffects": false,
  "types": "build/Permissions.d.ts",
  "unimodulePeerDependencies": {
    "@unimodules/core": "*",
    "unimodules-permissions-interface": "*"
  },
  "version": "7.0.0"
}

```

**Comment by IjzerenHein** [comment] 2020-03-28 06:57
Okay, well it definitely seems the correct version of `expo-permissions` is installed.

If you go to the home screen and `Project` tab in the Expo client, which version does it show?

*Example*
![image](https://user-images.githubusercontent.com/6184593/77817241-bd023f80-70c9-11ea-89d4-9fb3257a73cc.png)

**Comment by Rutvik17** [comment] 2020-03-28 07:04
It does say Sdk 35 is supported

**Comment by Rutvik17** [comment] 2020-03-29 08:12
I upgraded my sdk to version 36.0.0 and the problem got resolved. 
And using expo-permissions: 8.0.0

**Comment by IjzerenHein** [comment] 2020-03-29 08:34
Well, glad to hear it's fixed for you now.

It's strange to what exactly was wrong here. The problem occurs when there is a mismatch between the SDK and the `expo-permissions` JS code.

Closing this for now, will re-open when other people also experience this problem.

**Closed by IjzerenHein** 2020-03-29 08:34 UTC
Labels: Permissions
