### ISSUE TITLE
Orientation not locked on iPad

### ISSUE THREAD

**Issue by NickErrant** [expo/expo#68] opened 2017-02-28 22:38 UTC
Setting orientation in exp.json behaves as expected on iPhone, but does not lock orientation on iPads. I believe this was done to accommodate multitasking. Since multitasking doesn't make much sense for my application, I would appreciate a way to disable it and keep the orientation as set in the config json.

**Comment by terribleben** [comment] 2017-03-03 18:31
Hi - we chatted briefly in Slack but just responding here to make sure this is tracked. We don't do anything special on iPads right now for orientation, but maybe we should be.

**Comment by chownation** [comment] 2017-03-11 00:40
I would expect that the orientation would be locked as well on an iPad? I'm experiencing a similar issue where I have `"orientation": "landscape",` locked in the exp.json - however, the Dimensions.get('window') seems to be pulling a Portrait mode dimension pre-landscape load. And then turning the device also resizes the items from Landscape to Portrait.

**Comment by stephenhandley** [comment] 2017-04-08 23:08
This isn't working for me on iPhone either. I'm using `create-react-native-app` and my config looks like
```
{
  "expo": {
    "sdkVersion": "15.0.0",
    "orientation": "portrait"
  }
}
```
but rotating the device sideways results in landscape mode.

Sounds like this isn't being handled properly on iOS on either iPhone or iPad.

**Comment by terribleben** [comment] 2017-04-12 19:29
Hi, @NickErrant was correct that multitasking was the culprit. This was inadvertent, not deliberate. For now I'm going to opt out of multitasking on all projects (to get the correct orientation locking behavior), and we can add in proper multitasking support later. This change will ship with SDK 16 and apply to all older projects as well.

@chownation you may continue to see the behavior where the initial dimensions show portrait and a few frames later get updated to reflect landscape, this is just a side effect of the way we enforce the orientation. I recommend subscribing to updates:

```
const RCTDeviceEventEmitter = require('RCTDeviceEventEmitter');

class App extends React.Component {
  state = {
    screenWidth: 0,
    screenHeight: 0,
  };

  componentDidMount() {
    RCTDeviceEventEmitter.addListener('didUpdateDimensions', this._didUpdateDimensions);
    this._didUpdateDimensions();
  }

  _didUpdateDimensions = () => {
    let { width: screenWidth, height: screenHeight } = Dimensions.get('window');
    this.setState({ screenWidth, screenHeight });
  }

...```

@stephenhandley I'm unable to reproduce that behavior, orientation lock works for me on an iPhone. Can you share a minimal repro if possible?

**Comment by terribleben** [comment] 2017-04-20 02:09
The fix for this went out today with SDK 16. Please reopen if you're still seeing issues specific to iPad orientation after you update.

**Closed by terribleben** 2017-04-20 02:09 UTC
