### ISSUE TITLE
Double mount of components when using usePathname in parent folder _layout.js

### ISSUE THREAD

**Issue by pang0018** [expo/expo#25120] opened 2023-10-30 19:02 UTC
### Minimal reproducible example

https://github.com/pang0018/expo-router-double-mount-issue

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Steps to reproduce:
- Start the web app
- Click "Private" link
- Click "Private Stuff" link

Expected Results
We should see one message in the developer console that says "Stuff Page Mounted"

Observed
We see two messages in the developer console that says "Stuff Page Mounted" indicating that the component mounted and rendered twice.

The double mounting appears to only start to happen once we call usePathname in the parent _layout.js

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.4 - /usr/local/bin/npm
      Watchman: 2023.06.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    Expo Workflow: managed

Using expo-router 2.0.10

**Comment by marklawlor** [comment] 2023-11-01 00:43
@pang0018 Just confirming, are you seeing this in production? In development `useEffect` will fire twice https://react.dev/reference/react/useEffect#my-effect-runs-twice-when-the-component-mounts

**Comment by oliviercperrier** [comment] 2023-11-01 01:21
> @pang0018 Just confirming, are you seeing this in production? In development `useEffect` will fire twice https://react.dev/reference/react/useEffect#my-effect-runs-twice-when-the-component-mounts

I can confirm that im having this issue on a production build.

**Comment by pang0018** [comment] 2023-11-01 15:40
> Screen mouting twice when using usePathname, useSegment, etc in a _layout #25133

@marklawlor  Good question. I exported the above example for web and tested it with Serve CLI. The console message appeared twice indicating to me that the component mounted twice.

**Comment by pang0018** [comment] 2023-11-08 14:43
@marklawlor any update on reviewing this issue?

**Comment by EvanBacon** [comment] 2023-11-13 22:23
@pang0018 we're currently struggling to consistently reproduce the issue.

**Comment by pang0018** [comment] 2023-11-14 00:13
Interesting @EvanBacon. Is not happening for your team with my Minimal reproducible example?

**Comment by pang0018** [comment] 2024-02-13 18:44
I still believe this is an issue. Will test with v3 this week

**Comment by marklawlor** [comment] 2024-02-23 02:03
I'm going to close this issue as I believe it is solved in v3. Please reply if you can reproduce the issue.

Here are the steps I've taken to test

### Updating to SDK 50

- Clone repo
- Remove package-lock.json
- change Expo version in `package.json` `expo: "^50.0.7"`
- Run `npm install`
- Run `npx expo install --fix`
- Remove `'expo-router/babel'` from `babel.config.js`

### Changes made

- added `console.log(<component_name>, usePathname())` to all `_layout.tsx` files.

### Test

I used on both development&production for web&native and was unable to reproduce the issue. 

The logs I saw were consistent across platforms

```
// initial render
RootLayout /

// Naviate to /private
PrivateLayout /private
RootLayout /private

// Naviate to /private/stuff
StuffLayout /private/stuff
Stuff Page Mounted
RootLayout /private/stuff
```

The last additional log `RootLayout` is to be expected due to the root NavigationController  being updated.

**Closed by marklawlor** 2024-02-23 02:03 UTC
Labels: needs review, Router
