### ISSUE TITLE
Warning: 'react-native' dependency is not installed

### ISSUE THREAD

**Issue by JuanCAlpizar** [expo/expo#876] opened 2017-10-28 14:45 UTC
I've been seeing this issue in both `exp` cli and the AppImage file distribuited for Linux, I'm running both in their latest stable version at the moment of writing this.

Whenever I create a project with either I see a this text : 

    Warning: 'react-native' dependency is not installed.
    If there is an issue running your project, please run `npm install` in [project_folder] and restart.

where `[project_folder]` it's the current project path.

Fun fact is `react-native` npm package is installed globally, so if I type `react-native --version` I get an output from the current installed version

    [jc@jc-pc test_project]$ react-native --version
    react-native-cli: 2.0.1
    react-native: https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz

The problem itself is not major because it solves itself once you run `npm install` inside of the folder, but beats one of the purposes of this tool, which should be a simple, one step setup of the project.

Am I missing something for both the AppImage and the `exp` command to recognize the `react-native` dependency? 

Thanks

**Comment by btk** [comment] 2017-10-28 15:28
Did you reverse to an older commit with git?

Did you try removing your `node_modules` folder and installing your npm packages again with `npm install` or yarn? Also you should share your package.json file

**Comment by JuanCAlpizar** [comment] 2017-10-28 16:33
Sorry, I'm fairly new with nodejs and npm stuff, can you tell me how to revert to an older commit? I see many attributes in the package.json related to the current version, but I don't see a specific commit attribute, and yes I actually removed all of my global packages and started again from scratch using `npm install`. My only global packages right now are related to expo:

    [jc@jc-pc test_project]$ npm -g ls --depth 0
    /home/jc/.nvm/versions/node/v8.3.0/lib
    ├── exp@45.1.0
    ├── npm@5.5.1
    ├── react@16.0.0
    └── react-native-cli@2.0.1

    npm ERR! peer dep missing: eslint-plugin-babel@^4.0.0, required by eslint-config-expo@5.1.3

I currently use `nvm`, does that could be affecting the way expo detects the `react-native` package? When you ask the `package.json` I assume you're referring to the one of exp, in my case located under `/home/jc/.nvm/versions/node/v8.3.0/lib/node_modules/exp/package.json` which has the following content:

    {
      "_from": "exp",
      "_id": "exp@45.1.0",
      "_inBundle": false,
      "_integrity": "sha512-d/aRxe6eCT0W6hv/djQsOafSpvGK6feMbUSgAmYWVr5s124aZqGCfQlBgacgCLk08lxeHHCsvrhBqU5JloylHg==",
      "_location": "/exp",
      "_phantomChildren": {},
      "_requested": {
        "type": "tag",
        "registry": true,
        "raw": "exp",
        "name": "exp",
        "escapedName": "exp",
        "rawSpec": "",
        "saveSpec": null,
        "fetchSpec": "latest"
      },
      "_requiredBy": [
        "#USER"
      ],
      "_resolved": "https://registry.npmjs.org/exp/-/exp-45.1.0.tgz",
      "_shasum": "87ad82e058921128226f9a21aa4173c683ce36f2",
      "_spec": "exp",
      "_where": "/home/jc",
      "author": {
        "name": "support@expo.io"
      },
      "bin": {
        "exp": "./bin/exp.js"
      },
      "bugs": {
        "url": "https://github.com/expo/exp/issues"
      },
      "bundleDependencies": false,
      "dependencies": {
        "@expo/bunyan": "^1.8.10",
        "@expo/json-file": "^5.2.0",
        "@expo/ngrok": "2.2.9",
        "@expo/simple-spinner": "^1.0.2",
        "babel-runtime": "^6.9.2",
        "chalk": "^2.0.1",
        "commander": "^2.9.0",
        "delay-async": "^1.0.0",
        "es6-error": "^3.0.0",
        "glob": "^7.0.3",
        "indent-string": "^3.1.0",
        "inquirer": "^2.0.0",
        "lodash": "^4.17.4",
        "mz": "^2.6.0",
        "progress": "^2.0.0",
        "qrcode-terminal": "^0.11.0",
        "semver": "^5.0.1",
        "source-map-support": "^0.4.1",
        "untildify": "^3.0.2",
        "xdl": "46.1.0"
      },
      "deprecated": false,
      "description": "The command-line tool for creating and publishing Expo apps",
      "devDependencies": {
        "babel-eslint": "^7.1.0",
        "babel-plugin-add-module-exports": "^0.2.1",
        "babel-plugin-transform-flow-strip-types": "^6.8.0",
        "babel-plugin-transform-inline-imports-commonjs": "^1.2.0",
        "babel-plugin-transform-runtime": "^6.9.0",
        "babel-preset-es2015": "^6.9.0",
        "babel-preset-stage-1": "^6.5.0",
        "eslint": "^3.9.1",
        "eslint-config-expo": "^5.0.1",
        "eslint-plugin-babel": "^3.3.0",
        "eslint-plugin-flowtype": "^2.25.0",
        "eslint-plugin-import": "^2.2.0",
        "eslint-plugin-react": "^6.6.0",
        "gulp": "github:gulpjs/gulp#4.0",
        "gulp-babel": "^6.1.2",
        "gulp-changed": "^1.3.0",
        "gulp-plumber": "^1.1.0",
        "gulp-sourcemaps": "^1.6.0",
        "pkg": "^4.2.1",
        "rimraf": "^2.5.2"
      },
      "engines": {
        "node": ">=6.9.1"
      },
      "files": [
        "build",
        "bin"
      ],
      "homepage": "https://github.com/expo/exp#readme",
      "keywords": [
        "expo",
        "react-native"
      ],
      "license": "MIT",
      "main": "build/exp.js",
      "name": "exp",
      "pkg": {
        "scripts": "build/**/*.js"
      },
      "powertools": {
        "group": [
          "dev-tools",
          "exp"
        ]
      },
      "preferGlobal": true,
      "repository": {
        "type": "git",
        "url": "git+https://github.com/expo/exp.git"
      },
      "scripts": {
        "build": "gulp clean && gulp babel",
        "pkg": "pkg .",
        "prepare": "yarn build",
        "start": "yarn run build && yarn run watch",
        "watch": "gulp watch"
      },
      "version": "45.1.0"
    }

**Comment by btk** [comment] 2017-10-28 17:49
I was referring to the package.json in your `project_folder`.

Follow this steps;
- Go to your project folder
- Remove your node_modules/ directory.
- Open your project folder on a terminal and type the command `npm install`

**Comment by JuanCAlpizar** [comment] 2017-10-29 03:22
Ah, I get it but what's the point on that again? Maybe I'm new to the tool and I don't completely understand its capabilities, but I thought both the XDE and exp should be able to setup everything without additional commands. I was looking to use the XDE, but having to open a terminal to run the `npm install` on every project is counter productive.

If I stop the packager or open a new terminal and run the `npm install` command inside the folder the issue gets fixed once I restart the project, but the point was either exp or XDE are not detecting `react-native` dependency which is installed globally

**Comment by btk** [comment] 2017-10-29 03:39
@JuanCAlpizar It might be just a bug or your operating system.  You normally don't have to do that in the normal sequences.

Also dont forget to close this issue or if you feel like there is something wrong, gather enough information and report that bug. I suspect the linux.

**Comment by JuanCAlpizar** [comment] 2017-10-29 09:05
@btk  yeah it can be countless things so far. I just remembered I read somewhere react native and expo had issues with npm 5 (I'm running npm 5.5) so I proceed as follows

- Logged as root
- Uninstalled any global node package using `nvm`
- Removed `nvm`
- Reboot
- Logged as root
- Uninstalled any global node package related to react, react-native and exp using `npm`
- Reboot
- Logged as root
- Installed Yarn
- Execute `yarn global add react react-native-cli exp`
- Reboot
- Logged as root

Now I have the following output from `yarn global list`

    [root@jc-pc jc]# yarn global list
    yarn global v1.2.1
    info "exp@45.1.0" has binaries:
       - exp
    info "react-native-cli@2.0.1" has binaries:
       - react-native
    Done in 2.06s.

and both the `react-native` and `exp` command work from terminal, `exp init` works without errors but after running `exp start` inside the project folder I have the same output

    [jc@jc-pc test-project]$ exp start
    [exp] Using project at /home/jc/test-project
    [exp] Warning: 'react-native' dependency is not installed.
    [exp] 
    [exp] If there is an issue running your project, please run `npm install` in /home/jc/test-project and restart.
    [exp] Starting React Native packager...
    [exp] Scanning folders for symlinks in /home/jc/test-project/node_modules (4ms)
    [exp] Loading dependency graph.
    [exp] Running packager on port 19001.
    [exp] Expo is ready.
    [exp] You can scan this QR code:

    [some huge QR code image]
   
    [exp] Your URL is: exp://192.168.96.34:19000
    [exp] Switched to a LAN URL because the tunnel appears to be down. Only devices in the same network can access the app. Restart with `exp start` to try reconnecting.
    [exp] Logs for your project will appear below. Press Ctrl+C to exit.
    [exp] Dependency graph loaded.

All of the dependencies are installed and loaded so I don't really know what additional information I could give you to investigate any further, if you have an idea please let me know else I'm closing the issue and I'll just halt using the XDE tool for creating a project and do the process directly with the `exp` command from the terminal using `yarn install` between the `exp init` and the `exp start`, maybe this will get fixed by its own in a future update anyway as long as it's not affecting anything else I'm not aware of.

**Closed** 2017-10-30 17:20 UTC

**Comment by sodbileg** [comment] 2017-11-01 03:47
Exactly same issue here. There wasn't any issue 10 days ago.

**Comment by sodbileg** [comment] 2017-11-02 04:59
Seems like the issue is gone now.

**Comment by rafWork** [comment] 2017-12-28 19:32
this problem is bothering me too. "Create new project" on Expo XDE does not install react and react native.

**Comment by FrancisRenaud** [comment] 2018-01-02 00:30
Hi I'm having pretty much the same issue.
On fresh install, the starter app seems fine.

However, as soon as I add an import statement such as `import { TabNavigator } from 'react-navigation'` XDE resuses to run my app and complains that `react-native` is not installed.

Should I downgrade npm to a 4.x version?

Or has anyone identified the source of the problem?

Thanks!

**Comment by jacquelynwax** [comment] 2018-02-06 21:48
@FrancisRenaud were you able to get this issue fixed? I'm having the exact same problem right now with importing and having my app and complains that react-native is not installed.

Any help is much appreciated!
Thank you!

**Comment by EvanBacon** [comment] 2018-02-06 22:03
@jacquelynwax I don't have the same problem. I am using `node v8.5.0`, `npm v5.6.0`, and `exp@49.2.2` I suspect the issue is related to versioning

**Comment by FrancisRenaud** [comment] 2018-02-07 00:10
@jacquelynwax I downgraded to npm 4.x and the problem disappeared. If you can afford to do this it might help.

**Comment by Donskelle** [comment] 2018-03-13 20:35
Same happend to me `node v9.8.0` and `npm v5.6.0`
I just removed node_modules and reinstalled
```
rm -rf node_modules
npm install
```

**Comment by chasen-bettinger** [comment] 2018-03-16 17:17
This is an issue for me with yarn. I tried @Donskelle 's solution, but it did not work for me (maybe because I am not using npm). Looking for a solution with yarn!

**Comment by lasuax** [comment] 2018-05-04 09:00
Maybe not a solution but "npm i react --save-dev" may be considered as a workaround.

**Comment by isamuhiro** [comment] 2018-05-11 14:55
Removing `package-lock.json`, `yarn.lock`and `node_modules` and then running `yarn` should do the trick.

**Comment by steelx** [comment] 2018-05-17 05:05
deleting `package-lock.json` and `node_modules` folder and then `npm install` STILL facing issue.

**Comment by Rutulpatel7077** [comment] 2018-07-05 15:44
Yarn Solved my problem!

**Comment by llanginger** [comment] 2018-07-10 17:31
@Rutulpatel7077 Please post how Yarn solved it!

**Comment by Rutulpatel7077** [comment] 2018-07-10 18:06
@llanginger please do this...

1. Remove node_modules folder 
 `rm -rf node_modules`.
2. Delete package-lock.json file.
3. start expo.
4. And after do `yarn install`.
5. close and restart expo again....

**Comment by AlberErre** [comment] 2018-07-31 15:10
Just faced the same issue over here, solved following @Donskelle trick. 

`rm -rf node_modules`
`npm install` 

Currently using node `10.7.0` and npm `6.2.0`

**Comment by samber91** [comment] 2018-08-21 00:55
Hi. I have the same problem here. i've tried all these solutions, still same issue. I'm really new to this, so i would humbly ask somebody to help me via remote control please. let me know if you need my account details. thk u

**Comment by danikane** [comment] 2018-09-05 08:44
So for some people it's working with NPM, not Yarn.
And for some it's vice versa. :)
I'm using Yarn and removing node_modules and the lock file doesn't help.

This has been nagging me for a while, but I don't pay much attention to it. It doesn't affect anything.

**Comment by daVincere** [comment] 2018-12-07 11:11
Was facing such an issue. Nothing mentioned here worked.

It seems that the real issue is in the compilation of the `package.json` file

For me, it was the issue with value of the `name` object in `package.json` file.
`{
  "name": "Company Name",
......`

Changing this to 
`{
"name": "company-name",
.....`
sorted the issue. 

If you're facing the similar issue of packages (`react-native`) not being installed, try:
a. Installing those packages manually i.e. `npm install react-native` or,  
b. Checking all your configuration files for errors such as mine.

Hope this helps the few of you.
