### ISSUE TITLE
Standalone apk crashing because of reanimated2.0.0-alpha.

### ISSUE THREAD

**Issue by PhoenixCreation** [expo/expo#11266] opened 2020-12-08 08:04 UTC
### Summary of Issue 
Standalone apk crashing because of reanimated2.0.0-alpha. Works fine in development and with expo-cli but crashes as a standalone app.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
expo diagnostics output:
![Expo-issue](https://user-images.githubusercontent.com/63447220/101455260-4c017000-3958-11eb-9fc7-f312f2d31974.png)

Tested on:
Device: Samsung galaxy J7 Neo.
Android version: 9.0

### Reproducible Demo

I am sorry but as this involves not core supported library(react-native-reanimated@2.0.0-alpha.6.1) I can't create snack.
So I have created a GitHub repo [here.](https://github.com/PhoenixCreation/expo-reanimated-crash)

An android apk can be find here for next 30 days(till 11 JAN 2021). [Link to apk.](https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40phoenixcreation/testOfstandalone-fd92f45f1d1c418399947570ad118b86-signed.apk)

 
### Steps to Reproduce

I haven't done  so much. just imported Animated from "react-native-reanimated".
And just created <Animated.Text />

Total changes is blank(JavaScript) template from expo init are equal to this [commit changes.](https://github.com/PhoenixCreation/expo-reanimated-crash/commit/390a010624cbc531f1648c89e2c0cd5dc02d28c1)

### Expected Behavior vs Actual Behavior
Expected Behavior:
Opens standalone app and just display text.

Actual Behavior:
Crashes upon launching the standalone app.

## Description
I was working on animations(actually I am still new to animations) and created some animations and wanted to share to my friend. So I created standalone apk with `expo build:android` and installed on my physical device and It won't open. I figured out that the issue is with reanimated@2.0.0 with expo. This projects repo can be found [here.](https://github.com/PhoenixCreation/react-native-animations) It might help for more in depth info but shall not be considered as a main issue - repo for this issue.

So I created new project for testing with `expo init` (with blank template) and just did all changes required for reanimated-2 as mentioned in docs of expo SDK 39. Installed the reanimated-2 and created text element with it and run with expo-cli.
It ran perfect with development. Then I created standalone apk and It crashed same as the my previous one.

I don't know should I use reanimated-2 for standalone build or not. I couldn't found it and expo doc shows it so I think it should be usable in standalone too.

**Comment by brentvatne** [comment] 2020-12-09 23:32
hi there! ymmv with this on the alpha release. i'd recommend giving sdk 40 with the new react-native-reanimated@2.0.0-rc.0 a try to see if that resolves your issue

**Comment by PhoenixCreation** [comment] 2020-12-10 04:17
Thanks @brentvatne. I'll check it out. will let you know the results.

**Comment by PhoenixCreation** [comment] 2020-12-10 07:03
@brentvatne Nope. The same issue. You can recheck the github repo [here again.](https://github.com/PhoenixCreation/expo-reanimated-crash). I have upgrded to sdk 40 and reanimated rc.0. But still the standalone build is crashing upon start.
The new link to sdk40.0.0 apk is [here.](https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40phoenixcreation/testOfstandalone-c5be15322bb341b4a889124a87da9953-signed.apk)
Can you please check that what actual problem is? I still think it is reanimated.

**Comment by PhoenixCreation** [comment] 2020-12-11 12:22
> Can you please check that what actual problem is? I still think it is reanimated.

Well quick update. It is caused by reanimated 2. I have ran some test cases with and without reanimated 2 and found that reanimated 2 is the problem.
Animated API from 'react-native' work fine.

**Comment by PhoenixCreation** [comment] 2020-12-13 06:46
@brentvatne  @byCedric  Any info? Any update?

**Comment by outaTiME** [comment] 2020-12-23 00:03
@PhoenixCreation In some android devices I am apparently experiencing a similar problem, even sometimes I have sporadic crashes in ios.

the experimental `turbomodules` and the reanimated `rc0` do not seem to be quite stable even to put them productively

some time ago I created an issue in the reanimated repository:

https://github.com/software-mansion/react-native-reanimated/issues/1454

**Comment by brentvatne** [comment] 2020-12-23 00:17
@PhoenixCreation - react-native-reanimated is maintained by a separate team outside of expo, and we include it as a dependency. the library has still not reached a stable state (as indicated by the rc tag, which means release candidate) and so you may encounter issues when using it.

@outaTiME - you don't need to use the experimental turbomodules flag with sdk 40, i'd suggest removing it. also worth updating your issue on react-native-reanimated to use the latest version supported in sdk 40 and trying to share a reproducible example

**Comment by brentvatne** [comment] 2020-12-23 02:15
> @brentvatne Nope. The same issue. You can recheck the github repo [here again.](https://github.com/PhoenixCreation/expo-reanimated-crash). I have upgrded to sdk 40 and reanimated rc.0. But still the standalone build is crashing upon start.
> The new link to sdk40.0.0 apk is [here.](https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40phoenixcreation/testOfstandalone-c5be15322bb341b4a889124a87da9953-signed.apk)
> Can you please check that what actual problem is? I still think it is reanimated.

your app doesn't appear to be using reanimated at all, aside from the dependency. react-native-animatable is unrelated to react-native-reanimated.

here is an example of using react-native-reanimated v2 in a standalone app: https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40brents/testing-3c7d4e1a0e164a17a08adec6353ec48d-signed.apk

it's just this app: https://github.com/expo/examples/tree/master/with-reanimated2

you can create it on your machine with `npx create-react-native-app my-app -t with-reanimated2`

**Comment by outaTiME** [comment] 2020-12-23 02:39
> @PhoenixCreation - react-native-reanimated is maintained by a separate team outside of expo, and we include it as a dependency. the library has still not reached a stable state (as indicated by the rc tag, which means release candidate) and so you may encounter issues when using it.
> 
> @outaTiME - you don't need to use the experimental turbomodules flag with sdk 40, i'd suggest removing it. also worth updating your issue on react-native-reanimated to use the latest version supported in sdk 40 and trying to share a reproducible example

Thanks @brentvatne, I'm going to try to remove the experimental turbomodules flag from the app.json and test a new standalone build on both platforms, then I'll see to update the issue in the reanimated repository 💪

**Comment by PhoenixCreation** [comment] 2020-12-23 03:03
> your app doesn't appear to be using reanimated at all, aside from the dependency. react-native-animatable is unrelated to react-native-reanimated.

I am sorry but as mentioned earlier in this message. I have ran some test cases to find out does it works or not and forgot to put last version on github with reanimated as dependency. 

> Well quick update. It is caused by reanimated 2. I have ran some test cases with and without reanimated 2 and found that reanimated 2 is the problem.
> Animated API from 'react-native' work fine.

And I know that reanimated v2 is not stable yet but it has so much good things in it and also I had to create something quickly for my project. That's why I was so curious about progress. Sorry for that.

>https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40brents/testing-3c7d4e1a0e164a17a08adec6353ec48d-signed.apk

I'll check this out and tell you results.

**Comment by brentvatne** [comment] 2020-12-23 03:04
ah i see, i didn't realize that you had committed the tests you ran to the reproducible example repository. anyhow, if you run into problems with the above, let me know

**Comment by PhoenixCreation** [comment] 2020-12-23 03:31
>https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40brents/testing-3c7d4e1a0e164a17a08adec6353ec48d-signed.apk

This works completely fine. No issues with this build. So this raises one question...
In sdk40 if we have turbo modules enabled then can it cause crash? Because I might have enabled it all the time.

 Well I guess I will just wait for stable release of reanimated v2. Thank you for your responses @brentvatne.

I might not be able to check more things as I crashed my laptop and it is in repairing😂. But consider this issue closed from my side. You can wait for @outaTiME 's response and then close this issue.

**Comment by outaTiME** [comment] 2020-12-23 14:39
At the moment I see everything quite stable (on both platforms) removing the experimental `turbomodules` flag from the `app.json`, and as PhoenixCreation says, could it be that the experimental flag has been generating these crashes in SDK40?

**Comment by brentvatne** [comment] 2020-12-23 18:32
that seems possible. it enables turbomodule, and we don't run any tests against this environment. there is no need to enable it for reanimated 2 anymore and we don't recommend it in the docs, so the solution to this issue seems to be to remove the turbomodules flag that used to be necessary for reanimated 2 in sdk 39.

**Closed by brentvatne** 2020-12-23 18:32 UTC
Labels: Android, Reanimated, Turtle, needs more info, project: upstream
