### ISSUE TITLE
Notifications in standalone version

### ISSUE THREAD

**Issue by vasujogani** [expo/expo#9146] opened 2020-07-09 06:17 UTC
I have implemented a notification handler by doing `Notifications.addListener((notification) => { alert('hi'); })`. This works when I test the app on Expo on both Android and IOS. However, after doing `expo publish`, this doesn't work on the standalone app for IOS. The Notifications are received by iOS when the app is closed. Notifications are _not_ seen when app is in the foreground/open, but I'm assuming they are received and automatically deleted since the app is already open. However, regardless, notification `handler` is not fired as I never see that `alert`. Why is that? How can I fix it?

On Android, it's not storing the token. I'm using `Notifications.getExpoPushTokenAsync();` and it only works for iOS. So, at the moment, Android phones are not even receiving notifications (in the standalone version).

Thank you

**Comment by JamieS1211** [comment] 2020-07-09 09:45
I have also had significant problems here. In expo SDK 37 I found that the `Notifications.getExpoPushTokenAsync()` function would hang and never resolve, and as of SDK 38 the replacement function how throws an error #9061

**Comment by RodolfoGS** [comment] 2020-07-09 12:16
Maybe the problem is related with the `useNextNotificationsApi` flag. Read this and test add that flag to `app.json`: https://docs.expo.io/versions/latest/sdk/notifications/#android

Also test `addNotificationReceivedListener` and `addNotificationResponseReceivedListener` methods.

---
To show the notification when the app is in foreground: https://docs.expo.io/versions/latest/sdk/notifications/#handling-incoming-notifications-when-the-app-is
```
import * as Notifications from 'expo-notifications';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});
```

**Comment by lukmccall** [comment] 2020-07-09 12:20
`useNextNotificationsApi` flag only affects android. On iOS, you don't have to have this flag set to true.

**Comment by RodolfoGS** [comment] 2020-07-09 12:24
Oh, It's true, the flag is only for Android, my fail 🤦‍♂️

**Comment by cruzach** [comment] 2020-07-09 14:15
@vasujogani we provide an issue template so that you can provide all the information we need to help you. Unfortunately, without that information, it's hard for us to move forward. 

On Android, you will need to follow [this FCM setup guide](https://docs.expo.io/push-notifications/using-fcm/) and then rebuild your app (not just run `expo publish).  Also, `Notifications.addListener` is for the legacy notifications API, you should know that we created a brand new module in SDK 38, [`expo-notifications`](https://docs.expo.io/versions/latest/sdk/notifications/).

On iOS, if you are seeing the notifications come in when the app is backgrounded, then they are likely working correctly and maybe your listener isn't being created correctly? Without a reproducible demo, we can't know. While the iOS app is foregrounded, and using the legacy notifications API on SDK 37 or below, you'll need to pass `_iosDisplayInForeground: true` to have the system show the notification - https://docs.expo.io/versions/latest/sdk/legacy-notifications/#localnotification

I'm going to close this issue for now since, like I said, we need the information in the bug report template to move forward. If you can provide that, I can definitely re-open the issue

**Closed by cruzach** 2020-07-09 14:15 UTC
