### ISSUE TITLE
undefined is not an object (evaluating 'ExponentKeepAwake.activate')

### ISSUE THREAD

**Issue by minh-tien** [expo/expo#1552] opened 2018-03-20 15:00 UTC
## Issue:
Hello!  
I have issue to run application on Expo. I created a completely new project in Expo XDE, and without making any changes. Expo XDE returns red screen when I try to load it in the device with the following log:  
`undefined is not an object (evaluating 'ExponentKeepAwake.activate')`   
This issue only occurs when using real device connected via Wifi, while emulator (Bluestack) works as expected.
![a](https://user-images.githubusercontent.com/36288304/37662520-d1805d7e-2c89-11e8-8b6c-0ee0d39d7f84.png)
## Environment:
* **Device:** Android 6.0 and Expo 2.3.2
* **OS:** Windows 10 (version 1709)
* **Network:** No proxy or firewall

**Comment by schazers** [comment] 2018-03-21 18:23
Hi, sorry you're having this issue! Someone asked recently about this issue, but it was happening on an emulator, not the device. See this thread: https://forums.expo.io/t/exponentkeepawake-activate/6895/8

Could you double-check anything with network settings that could be related to what boomza suggests?

**Comment by esamelson** [comment] 2018-03-22 19:56
Hi there @minh-tien - thanks for the report. I'm unable to reproduce it unfortunately :( could you provide a bit more information? I'd be interested in knowing

1) version of XDE you're running
2) are you using tunnel, LAN, or localhost to serve your project? (e.g. does your project url look something like exp://v6-4dp.esamelson.my-new-project.exp.direct:80, exp://192.168.0.1:19000, or exp://localhost:19000)
3) could you post your app.json?

Thanks very much!

**Comment by minh-tien** [comment] 2018-03-23 06:40
Hi @schazers, I think it's probably because the wifi connection has a problem (but I'm not sure, because I can use wifi to access google, github, ... normally). Also, I also tried using another computer and restarted the wifi modem but the problem still is not resolved

Hi @esamelson, I am using Expo XDE version 2.22.1
### The default app.json when creating new projects, I do not change anything
```json
{
  "expo": {
    "name": "issues",
    "description": "This project is really great.",
    "slug": "issues",
    "privacy": "public",
    "sdkVersion": "25.0.0",
    "platforms": ["ios", "android"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "ios": {
      "supportsTablet": true
    }
  }
}
```
### I've tried many different cases:
* **Tunnel and wifi connection:** Not working
* **Tunnel and 3G connection:** Works well
* **LAN and wifi connection:** Not working
### And now I can temporarily solve the issue in the following steps:
1. Clear the Expo Client application data
2. Enable 3G on device and use Tunnel
3. Turn off 3G, turn on wifi and switch to using LAN
4. Everything works as expected, including the "Live Reload" feature (I think it was probably because the Expo client cached the project when it first used 3G connectivity)

**Comment by jseverinson** [comment] 2018-04-02 08:28
I've had this same problem occur while upgrading to SDK 26, on real device. I restarted the XDE, and as I opened this app I noticed this error was thrown but the packager was still building the JS bundle in the XDE in the background. I waited for a while for it to finish building (took 80 secs), then force quit the app on the device and then restarted which got me past the red screen error.

**Comment by minh-tien** [comment] 2018-04-05 14:24
Hi @jseverinson, I have encountered this problem in both SDK 25 and 26. I tried your way but the problem has not been resolved :(

**Comment by alfizo** [comment] 2018-06-07 20:42
I have the exact same problem i dont know how to fix it...

**Comment by anp** [comment] 2018-06-07 20:47
If you're still having this issue, could you try to open the URL from XDE in your phone's browser?

**Comment by Beissner** [comment] 2018-07-16 10:05
I'm having the same issue on the emulator. Has anyone found a fix?

**Comment by alfizo** [comment] 2018-07-16 10:43
@Beissner try switching from android emulator to genymotion it helped me!

**Comment by Beissner** [comment] 2018-07-16 12:18
Thank you! That seems to fix it. Does anyone know why it doesn't work with Android Studio's emulator?

**Comment by JoeRoddy** [comment] 2018-07-16 16:06
Uninstalling Expo from the emulator -> stop and restart the emulator ->  restart my app fixed it for me. YMMV.

**Comment by camilaazuma** [comment] 2018-10-24 22:05
Has anyone found a solution for this? 🤔

**Comment by dccmmtop** [comment] 2018-10-25 05:07
I solved this problem.

1. restart your react-native project on computer
2. restart your expo  on  android
3. log in to your Expo account on the compute and android
4. scan QR code

![image](https://user-images.githubusercontent.com/17303988/47477251-d826ab00-d856-11e8-84c6-03b088515f00.png)

**Comment by sjchmiela** [comment] 2018-11-06 11:13
I believe this issue should be fixed now, thanks for submitting the solution, @dccmmtop!

**Closed by sjchmiela** 2018-11-06 11:13 UTC
Labels: project: android-runtime

**Comment by andyklimczak** [comment] 2019-01-27 04:43
Running into this again trying to upgrade from expo sdk 31 -> 32
