### ISSUE TITLE
can't get Location.getHeadingAsync() in Android Tablet

### ISSUE THREAD

**Issue by lgngnr** [expo/expo#4081] opened 2019-04-26 10:24 UTC
## 🐛 Bug Report
I have the same problem with all Android tablet emulators. Location.getHeadingAsync() does not return the value when manual setting the magnetic-field but only when gps position change, like geo fix. Sometime even changing gps position with geo fix Location.getHeadingAsync() does not return the value. Attaching a then callback this does not being executed.
 
### Environment
  Expo CLI 2.15.4 environment info:
    System:
      OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 10.15.2 - /usr/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 5.8.0 - /usr/bin/npm
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.6.1 => 3.8.1 
    npmGlobalPackages:
      expo-cli: 2.15.4

The problem is common in all android tablet emulator, but works good in all android phone emulators. Right now i can't test it on ios. Expo kit project.

### Steps to Reproduce
Attach a then callback to Location.getHeadingAsync() or just get the value with await/async and set manually magnetic field in virtual sensors of android emulator. Can't get the heading value in tablet emulator but works well in phone emulators. Start working when change the gps position with geofix but sometime does not work neither.

For example
``` javascript
Location.getHeadingAsync().then(headObj => {
            head = (headObj.trueHeading != -1) ? headObj.trueHeading : headObj.magHeading;
            console.log('heading value', head);
});
```
1. if i change the magnetic-field sensors value in android emulator the head value does not being logged in console in case of android tablet emulator but works well in phone emulators;
2. if i change the gps position with geo fix i can see the heading value logged in console but sometime does not work neither;

Again i can get the heading logged properly in all android phone emulator but not in tablets.

### Expected Behavior
Return the heading value in case of android tablet like in android phone emulators

### Actual Behavior
Heading value does not returned in android tablet changing magnetic-field sensor values

**Comment by lukmccall** [comment] 2019-07-16 07:09
Could you check if this bug will occurred when you change `getHeadingAsync` to `watchHeadingAsync`?

**Comment by lukmccall** [comment] 2019-10-01 08:46
I'm closing this issue because I couldn't reproduce this bug and you didn't provide me with more information.
Feel free to reopen this issue if this bug still exists.

**Closed by lukmccall** 2019-10-01 08:46 UTC
Labels: Location, status: needs more info
