### ISSUE TITLE
[Android] [Producción] Expo-notificaciones addNotificationResponseReceivedListener

### ISSUE THREAD

**Issue by webuijorgeGL** [expo/expo#11698] opened 2021-01-20 17:43 UTC
## 🐛 Bug Report

SDK EXPO 40
Expo-notifications V 0.8.2
method: addNotificationResponseReceivedListener
Enviroment: Production
Android

### Summary of Issue

I using Expo-notification with FCM (Firebase cloud Message ). Everything works in dev mode using the expo push notification tool and local notification. But when I create the APK to test the push notification on Android I detected the method addNotificationResponseReceivedListener is no reached. I get a notification the I tapped it but nothing happens.

### Environment

Just in production APK android

### Reproducible Demo

https://snack.expo.io/@jorgsuau/expo-notification-failed-on-android-when-i-tried-use-addnotificationresponsereceivedlistener

**Comment by cruzach** [comment] 2021-01-20 21:31
Tested this on a standalone android APK built with `expo build:android -t apk` using the code from [this snack](https://snack.expo.io/@charliecruzan/push-notifications), and I received the alert after tapping the notification as expected. 

This probably has to do with how you're setting your notification response listener, so I suggest taking a look at that. In my example, I set in the global scope. If you'd rather not do that, and since you're using a functional component, you may want to switch over to using the [useLastNotificationResponse hook](https://docs.expo.io/versions/latest/sdk/notifications/#uselastnotificationresponse-undefined--notificationresponse--null) instead of `addNotificationResponseReceivedListener` (I'm actually going to update the docs to use that hook instead 😄 ).

Closing this issue for now because it is likely an implementation issue and not a bug with the Expo SDK, but will reopen if that turns out not to be the case

**Closed by cruzach** 2021-01-20 21:31 UTC
Labels: needs review

**Comment by xdajay** [comment] 2021-01-30 15:53
@cruzach  addNotificationResponseReceivedListener works for component-based implementation? on latest Expo SDK 40.
If not, how does the hook based implementation works for react-navigation 4x Thank you!
